GRANT SELECT ON DARHDOC_DBT TO IvanovConvert;
GRANT SELECT ON DARHDOC$_DBT TO IvanovConvert;
GRANT SELECT ON DACCOUNT_DBT TO IvanovConvert;
GRANT SELECT ON DACCOUNT$_DBT TO IvanovConvert;
GRANT SELECT ON DMCACCDOC_DBT TO IvanovConvert;
