CREATE TABLE DSCTRACC_TMP
(
  T_CHAPTER  NUMBER(5),    -- 1 (А), 3 (В)   Номер главы
  T_CURRENCY NUMBER(10),   -- Идентификатор валюты
  T_DTACC    VARCHAR2(25), -- Номер л/с по Дт - по главе А - по б/с 47422 - по главе В - по б/с 99998
  T_KTACC    VARCHAR2(25)  -- Номер л/с по Кт - по главе А - по б/с 47423 - по главе В - по б/с 99999
);

CREATE UNIQUE INDEX DSCTRACC_TMP_IDX0 ON DSCTRACC_TMP ( T_CHAPTER, T_CURRENCY );

CREATE TABLE DSCACCMAP1_TMP
(
  T_OLDACC  VARCHAR2(25),
  T_NEWACC  VARCHAR2(25),
  T_ISEXEC  CHAR(1) DEFAULT CHR(88)
);

CREATE UNIQUE INDEX DSCACCMAP1_TMP_IDX0 ON DSCACCMAP1_TMP ( T_OLDACC );
CREATE UNIQUE INDEX DSCACCMAP1_TMP_IDX1 ON DSCACCMAP1_TMP ( T_NEWACC );
CREATE INDEX DSCACCMAP1_TMP_IDX2 ON DSCACCMAP1_TMP ( T_ISEXEC );

CREATE TABLE DSCACCMAP2_TMP
(
  T_OLDACC  VARCHAR2(25),
  T_NEWACC  VARCHAR2(25)
);

CREATE UNIQUE INDEX DSCACCMAP2_TMP_IDX0 ON DSCACCMAP2_TMP ( T_OLDACC );
CREATE UNIQUE INDEX DSCACCMAP2_TMP_IDX1 ON DSCACCMAP2_TMP ( T_NEWACC );

GRANT EXECUTE ON SCIDMAP TO Ivanov2028_86;
GRANT SELECT ON DSCTRACC_TMP TO Ivanov2028_86;

