DROP TABLE D_MFB13_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE D_MFB13_TMP
(
  T_ID_SPB_MFB13      NUMBER(10),
  T_ID_MB_REQUISITES  NUMBER(10),
  T_REPORTDATE        DATE,
  T_CLRACCCODE        VARCHAR2(16),
  T_CURRENCYID        VARCHAR2(12),
  T_NETTOSUM          NUMBER(32,12),
  T_OBJECTCODE        VARCHAR2(36),
  T_OBJECTID          NUMBER(10)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

CREATE UNIQUE INDEX D_MFB13_TMP_IDX0 ON D_MFB13_TMP
(T_ID_SPB_MFB13)
/