DROP TABLE D_SPB03_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE D_SPB03_TMP
(
  T_ID_SPB_SPB03      NUMBER(10),
  T_ID_MB_REQUISITES  NUMBER(10),
  T_DOC_NO            VARCHAR2(32),
  T_CLRACCCODE        VARCHAR2(16),
  T_RECNO             NUMBER(10),
  T_CURRENCYID        VARCHAR2(12),
  T_SETTLEDATE        DATE,
  T_SECURITYID        VARCHAR2(32),
  T_ISIN              VARCHAR2(32),
  T_FACEVALUE         NUMBER(32,12),
  T_PRICETYPE         VARCHAR2(4),
  T_CLIENTCODE        VARCHAR2(12),
  T_REPOPART          NUMBER(5),
  T_BUYSELL           VARCHAR2(1),
  T_SETTLECODE        VARCHAR2(16),
  T_TRADENO           VARCHAR2(20),
  T_TRADEDATE         DATE,
  T_TRADETIME         DATE,
  T_TRADETYPE         VARCHAR2(1),
  T_TRADEPERIOD       VARCHAR2(8),
  T_SPECIALPERIOD     VARCHAR2(32),
  T_PRIMARYORDERID    VARCHAR2(20),
  T_ORDERID           VARCHAR2(20),
  T_DECIMALS          NUMBER(5),
  T_PRICE             NUMBER(32,12),
  T_QUANTITY          NUMBER(32,12),
  T_VALUE             NUMBER(32,12),
  T_AMOUNT            NUMBER(32,12),
  T_EXCHCOMM          NUMBER(32,12),
  T_CLRCOMM           NUMBER(32,12),
  T_CCPCODE           VARCHAR2(16),
  T_CPFIRMID          VARCHAR2(12),
  T_REPORATE          NUMBER(32,12),
  T_ACCINT            NUMBER(32,12),
  T_PRICE2            NUMBER(32,12),
  T_BOARDID           VARCHAR2(16),
  T_BOARDNAME         VARCHAR2(128),
  T_SECURITYTYPE      VARCHAR2(4),
  T_SECCURRENCYID     VARCHAR2(12),
  T_PARTYID           NUMBER(10),
  T_SFCONTRID         NUMBER(10),
  T_ISNOTFIND         NUMBER(5),
  T_ISERROR           NUMBER(5),
  T_CPFIRMPARTYID     NUMBER(10),
  T_CURID             NUMBER(10),
  T_CALENDID          NUMBER(5),
  T_MARKETSCHEMEID    NUMBER(10),
  T_NDAY1             NUMBER(5),
  T_PAYMDATE1         DATE,
  T_PAYMDATE2         DATE,
  T_CALCITOGDATE      DATE,
  T_FIID              NUMBER(10),
  T_WORKSETTLEDATE    DATE,
  T_OBJECTID          NUMBER(10),
  T_PORTFOLIO         NUMBER(5),
  T_CALENDID_TRD      NUMBER(5),
  T_ISREPO            NUMBER(5),
  T_ACCINT2           NUMBER(32,12),
  T_SETTLEDATE2       DATE,
  T_AMOUNT2           NUMBER(32,12),
  T_VALUE2            NUMBER(32,12),
  T_PRICE2_2          NUMBER(32,12),
  T_CLRACCCODETYPE    NUMBER(5),
  T_COMMENTAR         VARCHAR2(64),
  T_MARKETREPORTID    NUMBER(10)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

CREATE UNIQUE INDEX D_SPB03_TMP_IDX0 ON D_SPB03_TMP
(T_ID_SPB_SPB03)
/

CREATE INDEX D_SPB03_TMP_IDX1 ON D_SPB03_TMP
(T_TRADENO, T_BUYSELL, T_CLIENTCODE)
/

CREATE INDEX D_SPB03_TMP_IDX2 ON D_SPB03_TMP
(T_CLIENTCODE)
/

CREATE INDEX D_SPB03_TMP_IDX3 ON D_SPB03_TMP
(T_SECURITYID)
/