DROP TABLE D_MFB06C_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE D_MFB06C_TMP
(
  T_ID_SPB_MFB06C     NUMBER(10),
  T_ID_MB_REQUISITES  NUMBER(10),
  T_DOC_NO            VARCHAR2(32),
  T_RECNO             NUMBER(10),
  T_CLIENTCODE        VARCHAR2(12),
  T_CURRENCYID        VARCHAR2(12),
  T_INFTYPE           NUMBER(5),
  T_CLEARINGTIME      DATE,
  T_SETTLEDATE        DATE,
  T_SECURITYID        VARCHAR2(32),
  T_ISIN              VARCHAR2(32),
  T_PRICETYPE         VARCHAR2(4),
  T_REPOPART          NUMBER(5),
  T_BUYSELL           VARCHAR2(1),
  T_SETTLECODE        VARCHAR2(16),
  T_CLRACCCODE        VARCHAR2(16),
  T_TRADEDATE         DATE,
  T_TRADENO           VARCHAR2(20),
  T_DECIMALS          NUMBER(5),
  T_PRICE             NUMBER(32,12),
  T_QUANTITY          NUMBER(32,12),
  T_VALUE             NUMBER(32,12),
  T_AMOUNT            NUMBER(32,12),
  T_EXCHCOMM          NUMBER(32,12),
  T_ACCINT            NUMBER(32,12),
  T_CPFIRMID          VARCHAR2(12),
  T_REPOPERIOD        NUMBER(5),
  T_REPORTTIME        DATE,
  T_CLRCOMM           NUMBER(32,12),
  T_TRADEMODEID       NUMBER(5),
  T_TRADEPERIOD       NUMBER(5),
  T_ISREPO            NUMBER(5),
  T_PARTYID           NUMBER(10),
  T_SFCONTRID         NUMBER(10),
  T_ISNOTFIND         NUMBER(5),
  T_ISERROR           NUMBER(5),
  T_CPFIRMPARTYID     NUMBER(10),
  T_CURID             NUMBER(10),
  T_CALENDID          NUMBER(5),
  T_MARKETSCHEMEID    NUMBER(10),
  T_NDAY1             NUMBER(5),
  T_NDAY2             NUMBER(5),
  T_PAYMDATE1         DATE,
  T_PAYMDATE2         DATE,
  T_CALCITOGDATE      DATE,
  T_WORKSETTLEDATE    DATE,
  T_OBJECTID          NUMBER(10),
  T_PORTFOLIO         NUMBER(5),
  T_FIID              NUMBER(10),
  T_CALENDID_TRD      NUMBER(5),
  T_ISOUTEXCREPO      NUMBER(5),
  T_MARKETREPORTID    NUMBER(10)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

CREATE UNIQUE INDEX D_MFB06C_TMP_IDX0 ON D_MFB06C_TMP
(T_ID_SPB_MFB06C)
/

CREATE INDEX D_MFB06C_TMP_IDX1 ON D_MFB06C_TMP
(T_TRADENO, T_BUYSELL, T_CLIENTCODE)
/

CREATE INDEX D_MFB06C_TMP_IDX2 ON D_MFB06C_TMP
(T_CLIENTCODE)
/

CREATE INDEX D_MFB06C_TMP_IDX3 ON D_MFB06C_TMP
(T_CURRENCYID)
/

CREATE INDEX D_MFB06C_TMP_IDX4 ON D_MFB06C_TMP
(T_CLIENTCODE, T_REPOPART)
/

CREATE INDEX D_MFB06C_TMP_IDX5 ON D_MFB06C_TMP
(T_CLIENTCODE, T_REPOPART, T_BUYSELL, T_TRADENO)
/