DROP TABLE D_MFB99_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE D_MFB99_TMP
(
  T_ID_SPB_MFB99      NUMBER(10),
  T_ID_MB_REQUISITES  NUMBER(10),
  T_ENTRYNUMBER       VARCHAR2(215),
  T_CLRACCCODE        VARCHAR2(16),
  T_BANKACCCODE       VARCHAR2(64),
  T_DEBIT             NUMBER(32,12),
  T_CREDIT            NUMBER(32,12),
  T_REPORTDATE        DATE,
  T_CURRENCYID        VARCHAR2(12),
  T_CODETYPE          NUMBER(10),
  T_OTHERCLIRACC      VARCHAR2(32),
  T_OBJECTID          NUMBER(10)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

CREATE UNIQUE INDEX D_MFB99_TMP_IDX0 ON D_MFB99_TMP
(T_ID_SPB_MFB99)
/