CREATE OR REPLACE TRIGGER USER_NOMINAL_ENDMONTH_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_RECID ON USER_NOMINAL_ENDMONTH_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_RECID = 0 OR :NEW.T_RECID IS NULL) THEN
    SELECT USER_NOMINAL_ENDMONTH_DBT_SEQ.NEXTVAL INTO :NEW.T_RECID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('USER_NOMINAL_ENDMONTH_DBT_SEQ');
    IF :NEW.T_RECID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/