-- Таблица "DNPTXOBJ_TMP"
DROP TABLE DNPTXOBJ_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE DNPTXOBJ_TMP (
    T_ID NUMBER(10)
  , T_FUNCTIONKIND NUMBER(5)
  , T_DATE DATE
  , T_CLIENT NUMBER(10)
  , T_DIRECTION NUMBER(5)
  , T_LEVEL NUMBER(5)
  , T_USER CHAR(1)
  , T_KIND NUMBER(5)
  , T_SUM NUMBER(32,12)
  , T_CUR NUMBER(10)
  , T_ANALITICKIND1 NUMBER(5)
  , T_ANALITIC1 NUMBER(10)
  , T_ANALITICKIND2 NUMBER(5)
  , T_ANALITIC2 NUMBER(10)
  , T_ANALITICKIND3 NUMBER(5)
  , T_ANALITIC3 NUMBER(10)
  , T_ANALITICKIND4 NUMBER(5)
  , T_ANALITIC4 NUMBER(10)
  , T_ANALITICKIND5 NUMBER(5)
  , T_ANALITIC5 NUMBER(10)
  , T_ANALITICKIND6 NUMBER(5)
  , T_ANALITIC6 NUMBER(10)
  , T_COMMENT VARCHAR2(256)
  , T_DOCID NUMBER(10)
  , T_STEP NUMBER(5)
  , T_REESTRSUM NUMBER(32,12)
  , T_FROMOUTSYST CHAR(1)
  , T_OUTSYSTCODE VARCHAR2(35)
  , T_OUTOBJID VARCHAR2(30)
  , T_SOURCEOBJID NUMBER(10)
  , T_TECHNICAL CHAR(1)
  , T_ACTION NUMBER(5)
  , T_REALOBJID NUMBER(10)
  , T_CONVDATE DATE
  , T_TAXPERIOD NUMBER(5)
  , T_TRANSFDATE DATE
  , T_TRANSFKIND NUMBER(5)
  , T_HOLDING_PERIOD NUMBER(5)
) ON COMMIT PRESERVE ROWS
/
COMMENT ON TABLE DNPTXOBJ_TMP IS 'временное хранение объектов НДФЛ'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ID IS 'T_ID'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_FUNCTIONKIND IS 'T_FUNCTIONKIND'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_DATE IS 'T_DATE'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_CLIENT IS 'T_CLIENT'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_DIRECTION IS 'T_DIRECTION'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_LEVEL IS 'T_LEVEL'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_USER IS 'T_USER'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_KIND IS 'T_KIND'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_SUM IS 'T_SUM'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_CUR IS 'T_CUR'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITICKIND1 IS 'T_ANALITICKIND1'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITIC1 IS 'T_ANALITIC1'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITICKIND2 IS 'T_ANALITICKIND2'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITIC2 IS 'T_ANALITIC2'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITICKIND3 IS 'T_ANALITICKIND3'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITIC3 IS 'T_ANALITIC3'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITICKIND4 IS 'T_ANALITICKIND4'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITIC4 IS 'T_ANALITIC4'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITICKIND5 IS 'T_ANALITICKIND5'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITIC5 IS 'T_ANALITIC5'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITICKIND6 IS 'T_ANALITICKIND6'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ANALITIC6 IS 'T_ANALITIC6'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_COMMENT IS 'T_COMMENT'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_DOCID IS 'T_DOCID'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_STEP IS 'T_STEP'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_REESTRSUM IS 'T_REESTRSUM'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_FROMOUTSYST IS 'Признак "Получено из внешней системы"'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_OUTSYSTCODE IS 'Код внешней системы'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_OUTOBJID IS 'ID во внешней системе'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_SOURCEOBJID IS 'Идентификатор объекта-источника'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_TECHNICAL IS 'Технический расчет'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_ACTION IS 'Действие'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_REALOBJID IS 'ID существующего НДР'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_CONVDATE IS 'Дата конвертации t_Sum в рубли'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_TAXPERIOD IS 'Налоговый период'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_TRANSFDATE IS 'Дата трансформации ИИС в ИИС-3'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_TRANSFKIND IS 'Период расчета'
/
COMMENT ON COLUMN DNPTXOBJ_TMP.T_HOLDING_PERIOD IS 'Целое количество лет нахождения ц/б в собственности налогоплательщика'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXOBJ_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXOBJ_TMP_IDX0 ON DNPTXOBJ_TMP (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXOBJ_TMP_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXOBJ_TMP_IDX1 ON DNPTXOBJ_TMP (
   T_KIND ASC
  ,T_ANALITICKIND2 ASC
  ,T_ANALITIC2 ASC
  ,T_DATE ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DNPTXOBJ_TMP_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE DNPTXOBJ_TMP_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXOBJ_TMP_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXOBJ_TMP FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXOBJ_TMP_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXOBJ_TMP_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
