DROP TABLE D_SPB21_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE D_SPB21_TMP
(
  T_ID_SPB_SPB21      NUMBER(10),
  T_ID_MB_REQUISITES  NUMBER(10),
  T_TRADEDATE         DATE,
  T_BOARDID           VARCHAR2(16),
  T_SECURITYID        VARCHAR2(32),
  T_FACEVALUE         NUMBER(32,12),
  T_SECCURRENCYID     VARCHAR2(12),
  T_SECURITYTYPE      VARCHAR2(128),
  T_DECIMALS          NUMBER(5),
  T_CURRENCYID        VARCHAR2(12),
  T_ACCRUEDINTEREST   NUMBER(32,12),
  T_TOTALAMOUNT       NUMBER(32,12),
  T_MAXDEALPRICE      NUMBER(32,12),
  T_MINDEALPRICE      NUMBER(32,12),
  T_WAPRICE           NUMBER(32,12),
  T_MARKETPRICE3      NUMBER(32,12)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

CREATE UNIQUE INDEX D_SPB21_TMP_IDX0 ON D_SPB21_TMP
(T_ID_SPB_SPB21)
/