--Изменение urefill_step_dbt
CREATE OR REPLACE TRIGGER "UREFILL_STEP_DBT_T0_AINC"
  BEFORE INSERT OR UPDATE OF T_STEPID ON UREFILL_STEP_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:new.T_STEPID = 0 OR :new.T_STEPID IS NULL) THEN
    SELECT UREFILL_MANUAL_STEP_SEQ.nextval INTO :new.T_STEPID FROM dual;
  ELSE
    SELECT last_number INTO v_id FROM user_sequences WHERE sequence_name = UPPER('UREFILL_MANUAL_STEP_SEQ');
    IF :new.T_STEPID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/