CREATE GLOBAL TEMPORARY TABLE DDL_WRTOFFDEBTSUMVAL_TMP (
    T_SORT NUMBER(10)
  , T_DEBTDATE DATE
  , T_DEBTTYPE NUMBER(5)
  , T_DEBTID NUMBER(10)
  , T_DEBTSUM NUMBER(32,12)
  , T_DEBTCUR NUMBER(10)
  , T_DEBTSFCONTR NUMBER(10)
  , T_CLIENTID NUMBER(10)
  , T_DLCONTRID NUMBER(10)
)  ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DDL_WRTOFFDEBTSUMVAL_TMP IS 'Временная таблица расшифровок сумм задолженности к списанию'
/
COMMENT ON COLUMN DDL_WRTOFFDEBTSUMVAL_TMP.T_SORT IS 'Порядковый номер задолженности'
/
COMMENT ON COLUMN DDL_WRTOFFDEBTSUMVAL_TMP.T_DEBTDATE IS 'Дата возникновения задолженности'
/
COMMENT ON COLUMN DDL_WRTOFFDEBTSUMVAL_TMP.T_DEBTTYPE IS 'Тип задолженности'
/
COMMENT ON COLUMN DDL_WRTOFFDEBTSUMVAL_TMP.T_DEBTID IS 'Идентификатор задолженности'
/
COMMENT ON COLUMN DDL_WRTOFFDEBTSUMVAL_TMP.T_DEBTSUM IS 'Сумма соответствующей задолженности'
/
COMMENT ON COLUMN DDL_WRTOFFDEBTSUMVAL_TMP.T_DEBTCUR IS 'Валюта задолженности'
/
COMMENT ON COLUMN DDL_WRTOFFDEBTSUMVAL_TMP.T_DEBTSFCONTR IS 'Идентификатор субдоговора'
/
COMMENT ON COLUMN DDL_WRTOFFDEBTSUMVAL_TMP.T_CLIENTID IS 'Идентификатор клиента'
/
COMMENT ON COLUMN DDL_WRTOFFDEBTSUMVAL_TMP.T_DLCONTRID IS 'Идентификатор ДБО'
/

CREATE INDEX DDL_WRTOFFDEBTSUMVAL_TMP_IDX1 ON DDL_WRTOFFDEBTSUMVAL_TMP
(T_CLIENTID, T_DLCONTRID, T_DEBTCUR)
/
