CREATE GLOBAL TEMPORARY TABLE DDL_DEBTSUMLOG_TMP (
    T_TYPE NUMBER(5)
  , T_DLCONTRID NUMBER(10)
  , T_TEXT VARCHAR2(500)
) ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DDL_DEBTSUMLOG_TMP IS 'Временная таблица сообщений при автоматическом списании/выносе на просрочку задолженности'
/
COMMENT ON COLUMN DDL_DEBTSUMLOG_TMP.T_TYPE IS 'Тип сообщения'
/
COMMENT ON COLUMN DDL_DEBTSUMLOG_TMP.T_DLCONTRID IS 'Идентификатор ДБО'
/
COMMENT ON COLUMN DDL_DEBTSUMLOG_TMP.T_TEXT IS 'Текст сообщения'
/