/*
$Name:          f652ControlProtocolView.mac
$Module:        Регламентируемая отчетность
$Description:   Форма 652. Протокол контроля расчитанных данных
*/

/**
 * Форма 652. Протокол контроля расчитанных данных.
 *
 * @since   04.07.2013
 * @author  Kirin Pavel
 * @version 6.00.020.31
 */

class (RcbDataProtocolView) F652ControlProtocolView()
    initRcbDataProtocolView("control", false);

    private macro initialize()
        m_table.addColumn("Код валюты", 4, AL_CENTER);
        m_table.addColumn("Сумма в строке 4", 16, AL_RIGHT);
        m_table.addColumn("Контрольная сумма", 16, AL_RIGHT);
        m_table.addColumn("Результат сравнения", 16, AL_RIGHT);
    end;

    macro printHead()
        m_table.printHead();
    end;

    macro printString(dataSet)
        m_table.printStringTransferByWord(dataSet.fiid,
                                          round(dataSet.sum, 0),
                                          round(dataSet.checksum, 0),
                                          round(dataSet.comparison, 0));
    end;

    macro printNoErr()
        println("Контроль произведен успешно, ошибок в отчете не обнаружено");
    end;

    macro printBottom()
        m_table.printBottom();
    end;
end;

class (RcbCalculateProtocolView) F652CalculateControlProtocolView(protocolName : String)
    initRcbCalculateProtocolView("Форма 652. Оперативный отчет о движении средств в иностранной валюте на транзитных валютных счетах резидентов", protocolName);

    macro printHead()
        println(m_reportName);
        println(m_description);
        println();
        println("Период отчета за " + RcbApplication().currentReport.context.period.beginDate);
        println("Исполнитель " + {oper} + " " + исполнитель);
        println("Дата и время выпуска отчета " + date() + " " + time());
        println();
    end;

    private macro initialize()
        m_dataProtocolViewPull.push_back(F652ControlProtocolView());
    end;
end;