--Установка кода участника торгов
DECLARE
BEGIN
  UPDATE DDL_LIMITPRM_DBT
     SET T_FIRMCODE = 'MC0134700000'
   WHERE T_MARKETKIND = 1 
     AND T_MARKETID = 2
     AND T_IMPLKIND = 2;

EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DDL_LIMITPRM_DBT
     SET T_FIRMCODE = 'RSXMB'
   WHERE T_MARKETKIND = 1 
     AND T_MARKETID = 151337
     AND T_IMPLKIND = 2;

EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/