--Добавление поля
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDL_LIMITPRM_DBT ADD T_IMPLKIND NUMBER(10) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_LIMITPRM_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DDL_LIMITPRM_DBT_IDX1 ON DDL_LIMITPRM_DBT (
   T_MARKETKIND ASC
  ,T_MARKETID ASC
  ,T_IMPLKIND ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

COMMIT
/




