--Добавление поля
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDL_CLIENTINFO_DBT ADD T_IMPLKIND NUMBER(10) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDL_CLIENTINFO_DBT ADD T_FIRM_ID VARCHAR2(12) DEFAULT CHR(1)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/



COMMIT
/




