--5047
BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5047,180,'Moody''s 180','Moody''s Agency',210,'ИД рейт. Moody''s эмит-в КО в рудате в ин валюте','3');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '4'
   WHERE T_LIST = 5047
     AND T_ELEMENT = 2;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5047,173,'Moody''s 173','Moody''s Agency',210,'ИД рейт. Moody''s эмит-в КО в рудате в ин валюте','5');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '6'
   WHERE T_LIST = 5047
     AND T_ELEMENT = 257;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5047,178,'Moody''s 178','Moody''s Agency',210,'ИД рейт. Moody''s эмит-в КО в рудате в ин валюте','7');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '8'
   WHERE T_LIST = 5047
     AND T_ELEMENT = 154;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5047,209,'Moody''s 209','Moody''s Agency',210,'ИД рейт. Moody''s эмит-в КО в рудате в ин валюте','9');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '10'
   WHERE T_LIST = 5047
     AND T_ELEMENT = 176;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '11'
   WHERE T_LIST = 5047
     AND T_ELEMENT = 156;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '12'
   WHERE T_LIST = 5047
     AND T_ELEMENT = 174;
END;
/


--5051
BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5051,180,'Moody''s 180','Moody''s Agency',483,'ИД рейт. Moody''s эмит-в КО в рудате в ин валюте 3453У','3');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '4'
   WHERE T_LIST = 5051
     AND T_ELEMENT = 2;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5051,173,'Moody''s 173','Moody''s Agency',483,'ИД рейт. Moody''s эмит-в КО в рудате в ин валюте 3453У','5');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '6'
   WHERE T_LIST = 5051
     AND T_ELEMENT = 257;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5051,178,'Moody''s 178','Moody''s Agency',483,'ИД рейт. Moody''s эмит-в КО в рудате в ин валюте 3453У','7');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '8'
   WHERE T_LIST = 5051
     AND T_ELEMENT = 154;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5051,209,'Moody''s 209','Moody''s Agency',483,'ИД рейт. Moody''s эмит-в КО в рудате в ин валюте 3453У','9');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '10'
   WHERE T_LIST = 5051
     AND T_ELEMENT = 176;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '11'
   WHERE T_LIST = 5051
     AND T_ELEMENT = 156;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '12'
   WHERE T_LIST = 5051
     AND T_ELEMENT = 174;
END;
/



--5048
BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5048,173,'Moody''s 173','Moody''s Agency',210,'ИД рейт. Moody''s эмит-в не КО в рудате в ин валюте','1');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5048,209,'Moody''s 209','Moody''s Agency',210,'ИД рейт. Moody''s эмит-в не КО в рудате в ин валюте','1');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5048,171,'Moody''s 171','Moody''s Agency',210,'ИД рейт. Moody''s эмит-в не КО в рудате в ин валюте','1');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5048,178,'Moody''s 178','Moody''s Agency',210,'ИД рейт. Moody''s эмит-в не КО в рудате в ин валюте','3');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '4'
   WHERE T_LIST = 5048
     AND T_ELEMENT = 176;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '5'
   WHERE T_LIST = 5048
     AND T_ELEMENT = 156;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '6'
   WHERE T_LIST = 5048
     AND T_ELEMENT = 174;
END;
/


--5052
BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5052,173,'Moody''s 173','Moody''s Agency',483,'ИД рейт. Moody''s эмит-в не КО в рудате в ин валюте 3453У','1');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5052,209,'Moody''s 209','Moody''s Agency',483,'ИД рейт. Moody''s эмит-в не КО в рудате в ин валюте 3453У','1');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5052,171,'Moody''s 171','Moody''s Agency',483,'ИД рейт. Moody''s эмит-в не КО в рудате в ин валюте 3453У','1');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
   VALUES(5052,178,'Moody''s 178','Moody''s Agency',483,'ИД рейт. Moody''s эмит-в не КО в рудате в ин валюте 3453У','3');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '4'
   WHERE T_LIST = 5052
     AND T_ELEMENT = 176;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '5'
   WHERE T_LIST = 5052
     AND T_ELEMENT = 156;
END;
/

DECLARE
BEGIN
  UPDATE DLLVALUES_DBT
     SET T_RESERVE = '6'
   WHERE T_LIST = 5052
     AND T_ELEMENT = 174;
END;
/



BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/