--Добавление блоков пересчета СНОБ
/*Status*/

DECLARE
BEGIN
  INSERT INTO DOPRSTKND_DBT(T_STATUSKINDID,T_CODE,T_NAME,T_DOCKIND,T_SORT,T_ELIMINATED)
  VALUES(1105,'ПРСЧ','Пересчет СНОБ',110,0,CHR(0));


  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(1105,1,'Выполнить',CHR(0));

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(1105,2,'Завершить',CHR(0));


EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

/*Blocks*/
/*14904*/

DECLARE
BEGIN
  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(1490405,'Пересчет СНОБ',110,0,CHR(0),CHR(1),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

/*14918*/

DECLARE
BEGIN
  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(1491805,'Пересчет СНОБ',110,0,CHR(0),CHR(1),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

/*14933*/

DECLARE
BEGIN
  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(1493304,'Пересчет СНОБ',110,0,CHR(0),CHR(1),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

/*Steps*/
/*14904*/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(1490405,301,1,0,0,CHR(0),0,CHR(0),0,0,'vsr0301rp.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Пересчет СНОБ',11000000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


/*14918*/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(1491805,201,1,0,0,CHR(0),0,CHR(0),0,0,'vsv0201rp.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Пересчет СНОБ',0,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


/*14933*/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(1493304,301,1,0,0,CHR(0),0,CHR(0),0,0,'vsf0301.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Пересчет СНОБ',11000000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


/*status on block*/
/*14904*/
DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(1490405,1102,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(41490405,1105,2,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(20000072,1105,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

/*14918*/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(1491805,1102,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(1491805,1105,2,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(20000904,1105,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

/*14933*/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(1493304,1102,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(1493304,1105,2,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(40000118,1105,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

/*blocks in operation*/
/*14904*/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 14904
       AND T_BLOCKID = 1490405;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN

    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,14904,1490405,6,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),'R') RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,1105,1,0);

  END IF;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

/*14918*/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 14918
       AND T_BLOCKID = 1491805;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN

    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,14918,1491805,6,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),'R') RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,1105,1,0);

  END IF;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


/*14933*/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 14933
       AND T_BLOCKID = 1493304;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN

    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,14933,1493304,5,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),'R') RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,1102,1,0);

  END IF;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/