/* DEF-43066 
Удаление текущей привязки счетов к КУ "+Форвард, РПИ1" и "-Форвард, РПИ1".
Действия по добавлению к КУ нового параметра шаблона номера счета 1824 "ВидБА"
Изменении существующих и добавление новых шаблонов к КУ. */
DECLARE
    v_num   NUMBER := 0;
BEGIN
    UPDATE DMCCATEG_DBT
       SET T_PARAM4 = 3559, T_CLASS4 = 1824
     WHERE T_NUMBER IN (5135, 5136) AND T_PARAM4 = 0 AND T_CLASS4 = 0;

    UPDATE DMCTEMPL_DBT
       SET T_MASK = '9000013', T_VALUE4 = 1
     WHERE t_number IN (1, 2) AND T_CATID IN (876, 877) AND T_VALUE4 = -1;

    BEGIN
        SELECT 1
          INTO v_num
          FROM DMCTEMPL_DBT
         WHERE T_CATID IN (876, 877) AND t_number > 4 and rownum = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            v_num := 0;
    END;

    IF (v_num = 0)
    THEN
        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (876,
                     5,
                     100,
                     1,
                     -1,
                     2,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47408',
                     '9040013',
                     'А',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (876,
                     6,
                     100,
                     1,
                     -1,
                     3,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47408',
                     '9020013',
                     'А',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (876,
                     7,
                     100,
                     1,
                     -1,
                     4,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47408',
                     '9010013',
                     'А',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (876,
                     8,
                     100,
                     1,
                     -1,
                     5,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47408',
                     '9030013',
                     'А',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (876,
                     9,
                     101,
                     1,
                     -1,
                     2,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47408',
                     '9040013',
                     'А',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (876,
                     10,
                     101,
                     1,
                     -1,
                     4,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47408',
                     '9010013',
                     'А',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (876,
                     11,
                     101,
                     1,
                     -1,
                     3,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47408',
                     '9020013',
                     'А',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (876,
                     12,
                     101,
                     1,
                     -1,
                     5,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47408',
                     '9030013',
                     'А',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (877,
                     5,
                     100,
                     1,
                     -1,
                     4,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47407',
                     '9010013',
                     'П',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (877,
                     6,
                     101,
                     1,
                     -1,
                     4,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47407',
                     '9010013',
                     'П',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (877,
                     7,
                     100,
                     1,
                     -1,
                     3,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47407',
                     '9020013',
                     'П',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (877,
                     8,
                     101,
                     1,
                     -1,
                     3,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47407',
                     '9020013',
                     'П',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (877,
                     9,
                     100,
                     1,
                     -1,
                     5,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47407',
                     '9030013',
                     'П',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (877,
                     10,
                     101,
                     1,
                     -1,
                     5,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47407',
                     '9030013',
                     'П',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (877,
                     11,
                     100,
                     1,
                     -1,
                     2,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47407',
                     '9040013',
                     'П',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));

        INSERT INTO DMCTEMPL_DBT (T_CATID,
                                  T_NUMBER,
                                  T_VALUE1,
                                  T_VALUE2,
                                  T_VALUE3,
                                  T_VALUE4,
                                  T_VALUE5,
                                  T_VALUE6,
                                  T_VALUE7,
                                  T_VALUE8,
                                  T_CHAPTER,
                                  T_BALANCE,
                                  T_MASK,
                                  T_KIND_ACCOUNT,
                                  T_GROUPNUM,
                                  T_HASPERIOD,
                                  T_NOTAUTO,
                                  T_ISCLOSE,
                                  T_ACCOUNTCLIENT,
                                  T_TYPEACCOUNT,
                                  T_RESERVE)
             VALUES (877,
                     12,
                     101,
                     1,
                     -1,
                     2,
                     -1,
                     -1,
                     -1,
                     -1,
                     1,
                     '47407',
                     '9040013',
                     'П',
                     0,
                     CHR (0),
                     CHR (0),
                     CHR (0),
                     0,
                     CHR (1),
                     CHR (1));
    END IF;

    DELETE dmcaccdoc_dbt
     WHERE T_CATID IN (876, 877) AND T_ISCOMMON = CHR (88);
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/