--Обновление информации по блокам и шагам операции
DECLARE
BEGIN
  UPDATE DOPRBLOCK_DBT
     SET T_NAME = 'Корректировка. Отправка записей в Хранилище СНОБ'
   WHERE T_BLOCKID = 204405;

EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DOPROBLCK_DBT
     SET T_NOTINUSE = 'X',
         T_SYMBOL = CHR(0)
   WHERE T_KIND_OPERATION = 2044
     AND T_BLOCKID = 204403;

EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DOPROBLCK_DBT
     SET T_SYMBOLSFORINSERTION = '#',
         T_SYMBOL = 'С'
   WHERE T_KIND_OPERATION = 2044
     AND T_BLOCKID = 204404;

EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DOPROSTEP_DBT
     SET T_NOTINUSE = 'X'
   WHERE T_BLOCKID = 204403
     AND T_NUMBER_STEP = 20;

EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE DOPROSTEP_DBT
     SET T_NAME = 'Корректировка. Отправка записей в Хранилище СНОБ'
   WHERE T_BLOCKID = 204405
     AND T_NUMBER_STEP = 28;

EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/