DECLARE
  v_ID NUMBER := 0;
BEGIN
  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('êÖÜ_íéêÉéÇ_êÖèé_ë_ñä');

  IF(v_ID <> 0) THEN 
    UPDATE DREGVAL_DBT
       SET T_FMTBLOBDATA_XXXX = ''
     WHERE T_KEYID = v_ID; 
  END IF;

EXCEPTION 
  WHEN OTHERS THEN NULL;
END;
/

COMMIT
/