-- Шаг финреза для валютно-процентных СВОПов

DECLARE 
BEGIN
   EXECUTE IMMEDIATE ' Insert into DOPROSTEP_DBT
   (T_BLOCKID, T_NUMBER_STEP, T_KIND_ACTION, T_DAYOFFSET, T_SCALE, 
    T_DAYFLAG, T_CALENDARID, T_SYMBOL, T_PREVIOUS_STEP, T_MODIFICATION, 
    T_CARRY_MACRO, T_PRINT_MACRO, T_POST_MACRO, T_NOTINUSE, T_FIRSTSTEP, 
    T_NAME, T_DATEKINDID, T_REV, T_AUTOEXECUTESTEP, T_ONLYHANDCARRY, 
    T_ISALLOWFOROPER, T_OPERORGROUP, T_RESTRICTEARLYEXECUTION, T_USERTYPES, T_INITDATEKINDID, 
    T_ASKFORDATE, T_BACKOUT, T_ISBACKOUTGROUP, T_MASSEXECUTEMODE, T_ISCASE, 
    T_ISDISTAFFEXECUTE, T_SKIPINITAFTERPLANDATE, T_MASSPACKSIZE)
 Values
   (20000665, 136, 1, 0, 0, 
    CHR(0), 0, ''!'', 36, 0, 
    ''dvnop136.mac'', CHR(1), CHR(1), CHR(0), CHR(0), 
    ''Отражение финансового результат'', 19900012, CHR(0), CHR(0), CHR(0), 
    0, CHR(0), CHR(88), CHR(1), 0, 
    CHR(0), 0, CHR(0), 0, CHR(0), 
    CHR(0), CHR(88), 0) ';
EXCEPTION
   WHEN OTHERS THEN 
     NULL;
END;
/

