--Добавление поля
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DLIMIT_MONEY_REVISE_DBT ADD T_SOFR_REPO_DIF NUMBER (32,12)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DLIMIT_SECUR_REVISE_DBT ADD T_SOFR_REPO_DIF NUMBER (32,12)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DLIMIT_SECUR_REVISE_DBT ADD T_MARKET NUMBER (10)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DLIMIT_SECUR_REVISE_DBT ADD T_MARKET_KIND VARCHAR2(10)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/