DECLARE
BEGIN
  INSERT INTO DOPRKOPER_DBT(T_KIND_OPERATION,T_DOCKIND,T_NOTINUSE,T_INITMACRO,T_SYSTYPES,T_NAME,T_SHORTNAME,T_UPGRADE,T_ISMAINTANANCE,T_PARENT,T_VERSION,T_MASSOPRSTART)
  VALUES(32011,127,CHR(0),'sp_doc.mac','ZT','Зачисление ценных бумаг (НДФЛ)','ЗАЧИСЛЕНИЕ_НДФЛ',CHR(0),CHR(0),0,CHR(1),CHR(88));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                            T_SYMBOLSFORINSERTION,T_SYMBOL)
  VALUES(0,32011,201100,1,CHR(0),CHR(0),CHR(0),CHR(88),CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

  INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
  VALUES(v_OperBlockID,1271,1,0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRINIST_DBT(T_KIND_OPERATION,T_STATUSKINDID,T_NUMVALUE)
  VALUES(32011,1271,1);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSYSTP_DBT(T_DOCKIND,T_TYPE,T_NAME_TYPE,T_CONTENS,T_RESERVED)
  VALUES(127,'T','Зач_НДФЛ','Зачисление ценных бумаг (НДФЛ)',CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/