-- Таблица "DDL_REPORT_PRCSWAP_TMP"

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DDL_REPORT_PRCSWAP_TMP (
    T_DEALID NUMBER(10)
  , T_DOCKIND NUMBER(5)
  , T_DEALCODE VARCHAR2(30)
  , T_DEALDATE DATE
  , T_SWAPTYPE NUMBER(5)
  , T_CONTRACTORNAME VARCHAR2(60)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON TABLE DDL_REPORT_PRCSWAP_TMP IS ''Контроль платежей по проц.свопу''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_PRCSWAP_TMP.T_DEALID IS ''идентификатор сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_PRCSWAP_TMP.T_DOCKIND IS ''вид документа''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_PRCSWAP_TMP.T_DEALCODE IS ''код сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_PRCSWAP_TMP.T_DEALDATE IS ''дата сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_PRCSWAP_TMP.T_SWAPTYPE IS ''вид свопа''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_PRCSWAP_TMP.T_CONTRACTORNAME IS ''наименование контрагента''';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
