/* обновление справочников */
BEGIN
   INSERT INTO DBANK_MSG (T_NUMBER, T_PAGE, T_CONTENTS )
   VALUES (26048,0,'Отчетный год не может быть меньше, чем 2023 г.');
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DOBJECTS_DBT (T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE)
   VALUES(193,'Процедура запроса к источнику данных',CHR(1),0,0,CHR(1),CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7545,13,'13',5,3,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7545,15,'15',5,3,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7545,30,'30',5,3,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7546,201,'КБК 0201',10,3,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7546,207,'КБК 0207',10,3,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7546,208,'КБК 0208',10,3,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7547,1,'Резидент',15,2,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7547,2,'Нерезидент',15,2,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DSEQUENT_DBT(T_SEQID,T_DESCRIPTION,T_RESETTYPE,T_RESETDATE,T_RESETTIME,T_RESETMONTHS,T_IDENTPROGRAM,T_PASSEND,T_SYSDATECHECK,
                           T_SYSRESETTIME,T_CHECKHISTORY,T_SEQSTATUS,T_STARTVALUE,T_ENDVALUE,T_BRANCH,T_ISLOCAL,T_LEVEL,T_NOUPGRADE,
                           T_USEMETERINHIST,T_RESETCALCTYPE,T_RESERVE)
  VALUES(364,'Формирование номера процедуры запроса к источнику данных',0,TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),0,0,'Г',CHR(1),CHR(0),TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),CHR(0),0,0,0,1,CHR(0),1,CHR(0),CHR(0),0,CHR(1));
  

  INSERT INTO DREFER_DBT(T_REFID,T_SEQID,T_DESCRIPTION,T_CALCTYPE,T_TEMPLATE,T_MAXLEN,T_MACROFILE,T_MACROPROC,T_STATE,T_BANKDATE,T_SYSDATE,
                         T_SYSTIME,T_USERID,T_IDENTPROGRAM,T_CHECKMISSED,T_CHECKRANGENUMLIMIT,T_CHECKHISTORY,T_CURREFID,T_BRANCH,T_ISLOCAL,
                         T_NOUPGRADE,T_RESERVE)
  VALUES(368,364,'Номер процедуры запроса к источнику данных',1,'\n',10,CHR(1),CHR(1),0,TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),0,'Г',CHR(0),CHR(0),CHR(0),0,1,CHR(0),CHR(0),CHR(1));
  

  INSERT INTO DREFOBJ_DBT(T_OBJECTTYPE,T_REFTYPE,T_REFID,T_IDENTPROGRAM,T_NAME,T_STATE,T_BANKDATE,T_SYSDATE,T_SYSTIME,T_USERID,T_SYSTEM,T_RESERVE)
  VALUES(193,1,368,'S','Формирование номера процедуры запроса к источнику данных',0,TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),0,'X',CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
