-- Таблица "DDL_REPORT_TRNA_G_TMP"

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DDL_REPORT_TRNA_G_TMP (
    T_IDENTPROG CHAR(1)
  , T_DEALID NUMBER(10)
  , T_DOCKIND NUMBER(5)
  , T_DEALCODE VARCHAR2(30)
  , T_NAME VARCHAR2(79)
  , T_DEALDATE DATE
  , T_EXECDATE DATE
  , T_NOTE VARCHAR2(49)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON TABLE DDL_REPORT_TRNA_G_TMP IS ''Отчет-сверка проводок глав А и Г''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRNA_G_TMP.T_IDENTPROG IS ''вид подсистемы''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRNA_G_TMP.T_DEALID IS ''идентификатор сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRNA_G_TMP.T_DOCKIND IS ''вид документа''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRNA_G_TMP.T_DEALCODE IS ''код сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRNA_G_TMP.T_NAME IS ''вид операции''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRNA_G_TMP.T_DEALDATE IS ''дата начала сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRNA_G_TMP.T_EXECDATE IS ''дата исполнении сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRNA_G_TMP.T_NOTE IS ''примечание''';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
