-- Таблица "DNPTXTBEXT_DBT"

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DNPTXTBEXT_DBT (
    T_ID NUMBER(10)
  , T_CLIENTID NUMBER(10)
  , T_TAXPERIOD NUMBER(5)
  , T_INCDATE DATE
  , T_INCTIME DATE
  , T_KBKCALC VARCHAR2(20)
  , T_KBKKEEP VARCHAR2(20)
  , T_TAXBASEKIND NUMBER(5)
  , T_NOBAMOUNT NUMBER(32,12)
  , T_NDFLCALCAMOUNT NUMBER(32,12)
  , T_NDFLCALCRATE NUMBER(5)
  , T_NDFLKEEPAMOUNT NUMBER(32,12)
  , T_NDFLKEEPRATE NUMBER(5)
  , T_TAXPAYERSTATUS NUMBER(5)
  , T_SYSTEMCODE VARCHAR2(100)
  , T_DOCKIND NUMBER(5)
  , T_DOCID NUMBER(10)
  , T_ISCHANGED CHAR(1)
  , T_LOADDATE DATE
  , T_LOADTIME DATE
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DNPTXTBEXT_DBT IS 'Внешние события СНОБ'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_ID IS 'Идентификатор записи'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_CLIENTID IS 'Идентификатор клиента'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_TAXPERIOD IS 'Налоговый период'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_INCDATE IS 'Дата получения дохода'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_INCTIME IS 'Время получения дохода'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_KBKCALC IS 'КБК исчисленного налога'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_KBKKEEP IS 'КБК удержанного налога'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_TAXBASEKIND IS 'Вид налоговой базы'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_NOBAMOUNT IS 'НОБ'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_NDFLCALCAMOUNT IS 'Исчисленный налог'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_NDFLCALCRATE IS 'Ставка рассчитанного НДФЛ'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_NDFLKEEPAMOUNT IS 'Удержанный налог'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_NDFLKEEPRATE IS 'Ставка удержанного налога'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_TAXPAYERSTATUS IS 'Статус налогоплательщика'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_SYSTEMCODE IS 'СИ'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_DOCKIND IS 'Вид операции, изменившей запись'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_DOCID IS 'Идентификатор операции, изменившей запись'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_ISCHANGED IS 'Признак изменения записи'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_LOADDATE IS 'Дата загрузки'/
COMMENT ON COLUMN DNPTXTBEXT_DBT.T_LOADTIME IS 'Время загрузки'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXTBEXT_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXTBEXT_DBT_IDX0 ON DNPTXTBEXT_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXTBEXT_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXTBEXT_DBT_IDX1 ON DNPTXTBEXT_DBT (
   T_CLIENTID ASC
  ,T_TAXPERIOD ASC
  ,T_INCDATE ASC
  ,T_INCTIME ASC
  ,T_NDFLKEEPRATE ASC
  ,T_TAXBASEKIND ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXTBEXT_DBT_IDX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXTBEXT_DBT_IDX2 ON DNPTXTBEXT_DBT (
   T_CLIENTID ASC
  ,T_TAXPERIOD ASC
  ,T_KBKKEEP ASC
)
/

DECLARE
   e_exist_seq EXCEPTION;
   PRAGMA EXCEPTION_INIT(  e_exist_seq,    -955 );
BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE DNPTXTBEXT_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
   WHEN e_exist_seq THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER DNPTXTBEXT_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXTBEXT_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXTBEXT_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXTBEXT_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
