-- Таблица "DDLSELECTPT_TMP"

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DDLSELECTPT_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DDLSELECTPT_TMP (
    T_CLIENTID NUMBER(10)
  , T_CLIENTCODE VARCHAR2(35)
  , T_CLIENTNAME VARCHAR2(320)
  , T_SELECTFLAG CHAR(1)
  , T_MESSAGE VARCHAR2(500) DEFAULT CHR(1)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DDLSELECTPT_TMP IS 'Врем. таблица для множ. выбора клиентов'/
COMMENT ON COLUMN DDLSELECTPT_TMP.T_CLIENTID IS 'Идентификатор клиента'/
COMMENT ON COLUMN DDLSELECTPT_TMP.T_CLIENTCODE IS 'Код клиента'/
COMMENT ON COLUMN DDLSELECTPT_TMP.T_CLIENTNAME IS 'Наименование клиента'/
COMMENT ON COLUMN DDLSELECTPT_TMP.T_SELECTFLAG IS 'Признак выбора'/
COMMENT ON COLUMN DDLSELECTPT_TMP.T_MESSAGE IS 'Сообщение'/
