DECLARE
   e_exist_field EXCEPTION;
   PRAGMA EXCEPTION_INIT(e_exist_field, -1430);
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDVNDEAL_DBT ADD (T_METHODAPPLIC NUMBER(5) DEFAULT 0)';
EXCEPTION 
   WHEN e_exist_field THEN NULL;
END;
/
