-- Таблица "DNPTXTBEXT_TMP"

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DNPTXTBEXT_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DNPTXTBEXT_TMP (
    T_CLIENTID NUMBER(10)
  , T_TAXPERIOD NUMBER(5)
  , T_INCDATE DATE
  , T_INCTIME DATE
  , T_KBKCALC VARCHAR2(20)
  , T_KBKKEEP VARCHAR2(20)
  , T_TAXBASEKIND NUMBER(5)
  , T_NOBAMOUNT NUMBER(32,12)
  , T_NDFLCALCAMOUNT NUMBER(32,12)
  , T_NDFLCALCRATE NUMBER(5)
  , T_NDFLKEEPAMOUNT NUMBER(32,12)
  , T_NDFLKEEPRATE NUMBER(5)
  , T_TAXPAYERSTATUS NUMBER(5)
  , T_SYSTEMCODE VARCHAR2(100)
  , T_LOADDATE DATE
  , T_LOADTIME DATE
  , T_RECORDID VARCHAR2(50)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/


COMMENT ON TABLE DNPTXTBEXT_TMP IS 'Внешние события СНОБ (врем.)'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_CLIENTID IS 'Идентификатор клиента'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_TAXPERIOD IS 'Налоговый период'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_INCDATE IS 'Дата получения дохода'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_INCTIME IS 'Время получения дохода'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_KBKCALC IS 'КБК исчисленного налога'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_KBKKEEP IS 'КБК удержанного налога'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_TAXBASEKIND IS 'Вид налоговой базы'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_NOBAMOUNT IS 'НОБ'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_NDFLCALCAMOUNT IS 'Исчисленный налог'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_NDFLCALCRATE IS 'Ставка рассчитанного НДФЛ'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_NDFLKEEPAMOUNT IS 'Удержанный налог'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_NDFLKEEPRATE IS 'Ставка удержанного налога'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_TAXPAYERSTATUS IS 'Статус налогоплательщика'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_SYSTEMCODE IS 'СИ'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_LOADDATE IS 'Дата загрузки'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_LOADTIME IS 'Время загрузки'/
COMMENT ON COLUMN DNPTXTBEXT_TMP.T_RECORDID IS 'ID записи в Хранилище'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXTBEXT_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXTBEXT_TMP_IDX0 ON DNPTXTBEXT_TMP (
   T_RECORDID ASC
)
/
