-- Таблица "DDL_REPORT_CONTR"

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DDL_REPORT_CONTR (
    T_ID NUMBER(10)
  , T_KIND NUMBER(5)
  , T_PERIOD VARCHAR2(100)
  , T_SYSDATE DATE
  , T_OPERDATE DATE
  , T_SYSTIME DATE
  , T_OPER NUMBER(5)
  , T_ERR NUMBER(5)
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON TABLE DDL_REPORT_CONTR IS ''Информ. о проверочных отчетах''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CONTR.T_ID IS ''идентификатор отчета''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CONTR.T_KIND IS ''вид отчета''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CONTR.T_PERIOD IS ''отчетный период/дата''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CONTR.T_SYSDATE IS ''системная дата запуска отчета ''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CONTR.T_OPERDATE IS ''дата запуска отчета ''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CONTR.T_SYSTIME IS ''системное время запуска отчета ''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CONTR.T_OPER IS ''номер операциониста, выпустившего отчет ''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CONTR.T_ERR IS ''признак наличия ошибок/расхождений''';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_REPORT_CONTR_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DDL_REPORT_CONTR_IDX0 ON DDL_REPORT_CONTR (T_ID ASC)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DDL_REPORT_CONTR_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
   e_exist_seq EXCEPTION;
   PRAGMA EXCEPTION_INIT(  e_exist_seq,    -955 );
BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE DDL_REPORT_CONTR_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
   WHEN e_exist_seq THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER DDL_REPORT_CONTR_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDL_REPORT_CONTR FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDL_REPORT_CONTR_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDL_REPORT_CONTR_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

