-- Таблица "DDL_REPORT_OVER4742_TMP"

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DDL_REPORT_OVER4742_TMP (
    T_DEALID NUMBER(10)
  , T_DOCKIND NUMBER(5)
  , T_DEALCODE VARCHAR2(30)
  , T_REST_CALC NUMBER(32,12)
  , T_REST_WRITTEN NUMBER(32,12)
  , T_DIVERG NUMBER(32,12)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON TABLE DDL_REPORT_OVER4742_TMP IS ''Отчет проверка переоценки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_OVER4742_TMP.T_DEALID IS ''идентификатор сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_OVER4742_TMP.T_DOCKIND IS ''вид документа''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_OVER4742_TMP.T_DEALCODE IS ''код сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_OVER4742_TMP.T_REST_CALC IS ''накопленная переоценка''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_OVER4742_TMP.T_REST_WRITTEN IS ''списанная переоценка''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_OVER4742_TMP.T_DIVERG IS ''расхождения''';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
