DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXTBEXT_DBT ADD T_RECORDID VARCHAR2(50) DEFAULT CHR(1)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXTBEXT_DBT.T_RECORDID IS ''Идентификатор записи в Хранилище''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXTBEXT_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX DNPTXTBEXT_DBT_IDX1 ON DNPTXTBEXT_DBT (
   T_CLIENTID ASC
  ,T_TAXPERIOD ASC
  ,T_TAXBASEKIND ASC
)
/


BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXTBEXT_DBT_IDX3';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXTBEXT_DBT_IDX3 ON DNPTXTBEXT_DBT (
   T_RECORDID ASC
)
/