-- Таблица "DDL_REPORT_CLOSEDACC_TMP"

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DDL_REPORT_CLOSEDACC_TMP (
    T_IDENTPROG CHAR(1)
  , T_DEALID NUMBER(10)
  , T_DOCKIND NUMBER(5)
  , T_DEALCODE VARCHAR2(29)
  , T_NAME VARCHAR2(78)
  , T_DEALDATE DATE
  , T_CLOSEDDATE DATE
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON TABLE DDL_REPORT_CLOSEDACC_TMP IS ''Отчет8582. Закртые счета''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CLOSEDACC_TMP.T_IDENTPROG IS ''идентификатор подсистемы''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CLOSEDACC_TMP.T_DEALID IS ''идентификатор сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CLOSEDACC_TMP.T_DOCKIND IS ''Вид документа''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CLOSEDACC_TMP.T_DEALCODE IS ''код сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CLOSEDACC_TMP.T_NAME IS ''название операции''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CLOSEDACC_TMP.T_DEALDATE IS ''дата сделки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_CLOSEDACC_TMP.T_CLOSEDDATE IS ''дата закрытия''';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/