--Наполнение таблиц при реализации операции зачета удержанного НДФЛ
DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 2046
       AND T_BLOCKID = 204602;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN

    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,2046,204602,2,CHR(0),CHR(0),CHR(0),CHR(0),CHR(0),CHR(1),'З') RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,46491,4,0);

  END IF;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 2046
       AND T_BLOCKID = 204603;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN

    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,2046,204603,3,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,46491,5,0);

  END IF;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/