-- Таблица "DBRK_REPTMP_DBT"

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRK_REPTMP_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DBRK_REPTMP_DBT (
    T_DATE         DATE        DEFAULT TRUNC (SYSDATE)
  , T_SESSIONID    NUMBER(10)
  , T_DLCONTRID    NUMBER(10)
  , T_GROUPNUMBER  NUMBER(10)
  , T_ROWNUM       NUMBER(10)
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/