dROP TABLE DPORTFOLIO_TMP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE DPORTFOLIO_TMP
(
  T_PORTFID       NUMBER(5),
  T_ISQUOTED      NUMBER(5),
  T_DEALID        NUMBER(10),
  T_SUMID        number(10),
  T_FIID          NUMBER(10),
  T_PARTYID     number(10),
  T_AVKINDSHNAME  VARCHAR2(15 BYTE),
  T_ACCOUNT       VARCHAR2(25 BYTE),
  T_BALANCE       number(10),
  T_DOCKIND       NUMBER(5),
  T_DOCID         NUMBER(10),
  T_PARTNUM       NUMBER(5),
  T_DEPARTMENT    NUMBER(5),
  AMOUNT                        NUMBER(24,2),
  UNKD_WITH_COUPON              NUMBER(24,2),
  COUPON_AMOUNT                 NUMBER(24,2),
  DISCOUNT_AMOUNT               NUMBER(24,2),
  PREMIUM_AMOUNT                NUMBER(24,2),
  BALANCE_PRICE                 NUMBER(24,2),
  OVERVALUE                     NUMBER(24,2),
  RESERVE_AMOUNT                NUMBER(24,2)   
)
ON COMMIT PRESERVE ROWS
NOCACHE;


CREATE INDEX DPORTFOLIO_TMP_IDX0 ON DPORTFOLIO_TMP
(T_PORTFID, T_ISQUOTED, T_PARTYID, T_AVKINDSHNAME, T_FIID, 
T_ACCOUNT);



