--Скрипты для индексов

DECLARE
  E_INDEX_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX dptbicdir_dbt_idxg';
EXCEPTION WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_IND_ALREDY_EXIST EXCEPTION;
  PRAGMA EXCEPTION_INIT (E_IND_ALREDY_EXIST, -955);
BEGIN
  --created by cre_ptbicdir_index.sql
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX dptbicdir_dbt_idxg ON dptbicdir_dbt (DECODE(t_BDPRecordKey, CHR(1), NULL, t_BDPRecordKey))';
EXCEPTION WHEN E_IND_ALREDY_EXIST THEN NULL;
END;
/

DECLARE
  E_INDEX_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX dbnkdirpls_tmp_idxg';
EXCEPTION WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_IND_ALREDY_EXIST EXCEPTION;
  PRAGMA EXCEPTION_INIT (E_IND_ALREDY_EXIST, -955);
BEGIN
  --created by cre_ptbicdir_index.sql
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX dbnkdirpls_tmp_idxg ON dbnkdirpls_tmp (DECODE(t_PartyID, 0, NULL, t_PartyID))';
EXCEPTION WHEN E_IND_ALREDY_EXIST THEN NULL;
END;
/

DECLARE
  E_INDEX_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX dptbicdir_dbt_idxh';
EXCEPTION WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_IND_ALREDY_EXIST EXCEPTION;
  PRAGMA EXCEPTION_INIT (E_IND_ALREDY_EXIST, -955);
BEGIN
  --created by cre_ptbicdir_index.sql
  EXECUTE IMMEDIATE 'CREATE INDEX dptbicdir_dbt_idxh ON dptbicdir_dbt (REPLACE(REPLACE(REPLACE(UPPER(TRIM(t_InstitutionName)),'' '', '' ''||CHR(2)), CHR(2)||'' ''), CHR(2)))';
EXCEPTION WHEN E_IND_ALREDY_EXIST THEN NULL;
END;
/

