--------------------------------------------------------------------
-- Скрипты для triggers before insert: clob to xml   

CREATE OR REPLACE TRIGGER DXML2_DFISCLOG_DBT_CLOB2XML
BEFORE INSERT
   ON DXML2_DFISCLOG_DBT    FOR EACH ROW
BEGIN
  IF :new.T_TMPCLOB IS NOT NULL THEN
    :new.T_FMTBLOBDATA_XXXX := XmlType(:new.T_TMPCLOB);
    :new.T_TMPCLOB := NULL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER DXML2_DFISCLOG_TMP_CLOB2XML
BEFORE INSERT
   ON DXML2_DFISCLOG_TMP    FOR EACH ROW
BEGIN
  IF :new.T_TMPCLOB IS NOT NULL THEN
    :new.T_FMTBLOBDATA_XXXX := XmlType(:new.T_TMPCLOB);
    :new.T_TMPCLOB := NULL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER DXML2_DOPERLOG_DBT_CLOB2XML
BEFORE INSERT
   ON DXML2_DOPERLOG_DBT    FOR EACH ROW
BEGIN
  IF :new.T_TMPCLOB IS NOT NULL THEN
    :new.T_FMTBLOBDATA_XXXX := XmlType(:new.T_TMPCLOB);
    :new.T_TMPCLOB := NULL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER DXML2_DOPERLOG_TMP_CLOB2XML
BEFORE INSERT
   ON DXML2_DOPERLOG_TMP    FOR EACH ROW
BEGIN
  IF :new.T_TMPCLOB IS NOT NULL THEN
    :new.T_FMTBLOBDATA_XXXX := XmlType(:new.T_TMPCLOB);
    :new.T_TMPCLOB := NULL;
  END IF;
END;
/
