--Скрипт триггера

CREATE OR REPLACE TRIGGER DACCTRN_BATCH_TMP_SUMNATCUR
   BEFORE UPDATE ON DACCTRN_BATCH_TMP
   FOR EACH ROW
DECLARE
BEGIN

   IF (:NEW.T_SUM_PAYER_NATCUR IS NULL) THEN
     :NEW.T_SUM_PAYER_NATCUR := 0;
   END IF;

  IF (:NEW.T_SUM_RECEIVER_NATCUR IS NULL) THEN
     :NEW.T_SUM_RECEIVER_NATCUR := 0;
   END IF;

END;
/
