-- История лота Вид, в котором отображается история изменения реквизитов лота, включая архивные и текущие данные. 
CREATE OR REPLACE VIEW V_SCWRTHIST
AS 
(
  (SELECT T_BCID            ,
          T_SUMID           ,
          T_ID_OPERATION    ,
          T_ID_STEP         ,
          T_ACTION          ,
          T_INSTANCE        ,
          T_CHANGEDATE      ,
          T_FIID            ,
          T_PORTFOLIO       ,
          T_GROUPID         ,
          T_DATE            ,
          T_TIME            ,
          T_AMOUNT          ,
          T_AMOUNTBD        ,
          T_SUM             ,
          T_CURRENCY        ,
          T_COST            ,
          T_BALANCECOST     ,
          T_BALANCECOSTBD   ,
          T_NKDAMOUNT       ,
          T_INTERESTINCOME  ,
          T_NOTCARRYINTEREST,
          T_INTERESTDATE    ,
          T_BEGDISCOUNT     ,
          T_DISCOUNTINCOME  ,
          T_NOTCARRYDISCOUNT,
          T_DISCOUNTDATE    ,
          T_OUTLAY          ,
          T_RESERVAMOUNT    ,
          T_RESERVDATE      ,
          T_OVERAMOUNT      ,
          T_OVERAMOUNTBD    ,
          T_OVERDATE        ,
          T_STATE           ,
          T_STATEDATE       ,
          T_LNKREF          ,
          T_BONUS           ,
          T_OLDBEGDATE      ,
          T_OLDBEGDISCOUNT  ,
          T_BEGDATE         ,
          T_BEGBONUSDATE    ,
          T_BEGBONUS        ,
          T_BONUSDATE       ,
          T_INCOMERESERV    ,
          T_BEGINTERESTDATE ,
          T_BEGDISCOUNTDATE ,
          T_DISCOUNTCORR   ,
          T_OLDBEGBONUS,   
          T_RECALCDATE,    
          T_ISEDIT,
          T_COSTPFI,
          T_WRTVATOUTLAY,
          T_WRTOUTLAY,
          T_ACCOUNTEDDEFDIFF,
          T_CORRESTRESERVE,
          T_ESTRESERVE,
          T_AMORTCOST   
     FROM DPMWRTBC_DBT)
  UNION ALL
  (SELECT 0,                         
          t_SumID,                   
          t_ID_Operation,            
          t_ID_Step,                 
          t_Action,                  
          t_Instance,                
          t_ChangeDate,              
          t_FIID,                    
          T_PORTFOLIO,               
          t_GroupID,                 
          t_Date,                    
          t_Time,                    
          t_Amount,                  
          T_AMOUNTBD,                
          t_Sum,                     
          t_Currency,                
          t_Cost,                    
          t_BalanceCost,             
          T_BALANCECOSTBD,           
          t_NKDAmount,               
          t_InterestIncome,          
          t_NotCarryInterest,        
          t_InterestDate,            
          t_BegDiscount,             
          t_DiscountIncome,          
          t_NotCarryDiscount,        
          t_DiscountDate,            
          t_Outlay,                  
          t_ReservAmount,            
          t_ReservDate,              
          t_OverAmount,              
          T_OVERAMOUNTBD,            
          t_OverDate,                
          t_State,                   
          t_StateDate,               
          0,                          
          t_Bonus,               
          T_OLDBEGDATE,
          T_OLDBEGDISCOUNT,
          T_BEGDATE         ,
          T_BEGBONUSDATE    ,
          T_BEGBONUS        ,
          T_BONUSDATE       ,
          T_INCOMERESERV    ,
          T_BEGINTERESTDATE ,
          T_BEGDISCOUNTDATE ,
          T_DISCOUNTCORR   ,
          T_OLDBEGBONUS,   
          T_RECALCDATE,    
          T_ISEDIT,
          T_COSTPFI,
          T_WRTVATOUTLAY,
          T_WRTOUTLAY,
          T_ACCOUNTEDDEFDIFF,
          T_CORRESTRESERVE,
          T_ESTRESERVE,
          T_AMORTCOST        
     FROM DPMWRTSUM_DBT)
)
/

-- Расширенные архивные данные лота 
-- Вид, в котором отображаются архивные данные лота + постоянные реквизиты лота
CREATE OR REPLACE VIEW V_SCWRTBCEX
AS 
(
  SELECT BC.T_BCID            ,
         BC.T_SUMID           ,
         BC.T_ID_OPERATION    ,
         BC.T_ID_STEP         ,
         BC.T_ACTION          ,
         BC.T_INSTANCE        ,
         BC.T_CHANGEDATE      ,
         BC.T_FIID            ,
         BC.T_PORTFOLIO       ,
         BC.T_GROUPID         ,
         BC.T_DATE            ,
         BC.T_TIME            ,
         BC.T_AMOUNT          ,
         BC.T_AMOUNTBD        ,
         BC.T_SUM             ,
         BC.T_CURRENCY        ,
         BC.T_COST            ,
         BC.T_BALANCECOST     ,
         BC.T_BALANCECOSTBD   ,
         BC.T_NKDAMOUNT       ,
         BC.T_INTERESTINCOME  ,
         BC.T_NOTCARRYINTEREST,
         BC.T_INTERESTDATE    ,
         BC.T_BEGDISCOUNT     ,
         BC.T_DISCOUNTINCOME  ,
         BC.T_NOTCARRYDISCOUNT,
         BC.T_DISCOUNTDATE    ,
         BC.T_OUTLAY          ,
         BC.T_RESERVAMOUNT    ,
         BC.T_RESERVDATE      ,
         BC.T_OVERAMOUNT      ,
         BC.T_OVERAMOUNTBD    ,
         BC.T_OVERDATE        ,
         BC.T_STATE           ,
         BC.T_STATEDATE       ,
         BC.T_LNKREF          ,
         BC.T_BONUS           ,
         BC.T_BEGBONUS        ,
         BC.T_BONUSDATE       ,
         BC.T_OLDBEGDATE      ,
         BC.T_OLDBEGDISCOUNT  , 
         (case WHEN (Lot.T_BUY_SALE = 0) /*покупка\зачисление*/ AND           
                    (BC.T_STATE     = 1) /*Поставлен*/ AND                    
                    (BC.T_AMOUNT    > 0)                                      
               THEN 'X'                                                       
          ELSE chr(0)                                                         
          END                                                                 
         ) AS t_IsFree ,                                                      
         Lot.T_DOCKIND,
         Lot.T_DOCID  ,               
         Lot.T_PARTNUM,               
         Lot.T_PARTY  ,               
         Lot.T_CONTRACT,              
         Lot.T_BUY_SALE,              
         Lot.T_KIND    ,              
         Lot.T_COUPON      ,          
         Lot.T_PARTLY      ,    
         Lot.T_DEPARTMENT  ,    
         Lot.T_DEALID      ,    
         Lot.T_DEALDATE    ,    
         Lot.T_DEALCODE    ,    
         Lot.T_ENTERDATE   ,    
         Lot.T_TRUST       ,    
         Lot.T_PARENT      ,    
         Lot.T_SOURCE,
         BC.t_BegInterestDate,
         BC.t_BegDiscountDate,
         BC.t_DiscountCorr   ,
         BC.t_OldBegBonus    ,
         BC.t_RecalcDate     ,
         BC.t_IsEdit,
         BC.T_BEGBONUSDATE,
         BC.T_BEGDATE,
         BC.T_INCOMERESERV,
         BC.T_OLDBONUS,
         BC.T_NOTWRTBONUS,
         BC.T_COSTPFI,
         BC.T_WRTOUTLAY,
         BC.T_WRTOUTLAYDATE,
         BC.T_WRTVATOUTLAY,
         BC.T_FAIRVALUE,
         BC.T_CORRVALUE,
         BC.T_ACCOUNTEDDEFDIFF,
         BC.T_CORRINTTOEIR,
         BC.T_CORRESTRESERVE,
         BC.T_ESTRESERVE,
         BC.T_AMORTCOST,
         Lot.T_SORTCODE,
         BC.T_BEGDEFDIFF,
         BC.T_DEFDIFFDATE,
         BC.T_EFFECTINTERESTRATE,
         Lot.T_AMORTCOSTDATE,
         BC.T_CORRDATE,
         BC.T_AMORTCALCKIND,
         BC.T_ESTRESERVEDATE,
         BC.T_CORRINTTOEIRDATE,
         BC.T_CORRESTRESERVEDATE,
         BC.T_HEDGCORR,
         BC.T_HEDGCORRDATE,
         BC.T_AMORTHEDGCORR,
         BC.T_AMORTHEDGCORRDATE
    FROM DPMWRTSUM_DBT Lot, DPMWRTBC_DBT BC                                   
   WHERE BC.t_SumID   = Lot.t_SumID                                           
)                                                                            
/

-- Расширенная история лота. Вид, в котором  отображается история всех реквизитов лота. Строится по архивным и текущим данным
CREATE OR REPLACE VIEW V_SCWRTHISTEX
AS 
(
  (SELECT *
     FROM V_SCWRTBCEX vbcex
  ) UNION ALL
  (SELECT 0,                         
          T_SUMID           ,
          T_ID_OPERATION    ,
          T_ID_STEP         ,
          T_ACTION          ,
          T_INSTANCE        ,
          T_CHANGEDATE      ,
          T_FIID            ,
          T_PORTFOLIO       ,
          T_GROUPID         ,
          T_DATE            ,
          T_TIME            ,
          T_AMOUNT          ,
          T_AMOUNTBD        ,
          T_SUM             ,
          T_CURRENCY        ,
          T_COST            ,
          T_BALANCECOST     ,
          T_BALANCECOSTBD   ,
          T_NKDAMOUNT       ,
          T_INTERESTINCOME  ,
          T_NOTCARRYINTEREST,
          T_INTERESTDATE    ,
          T_BEGDISCOUNT     ,
          T_DISCOUNTINCOME  ,
          T_NOTCARRYDISCOUNT,
          T_DISCOUNTDATE    ,
          T_OUTLAY          ,
          T_RESERVAMOUNT    ,
          T_RESERVDATE      ,
          T_OVERAMOUNT      ,
          T_OVERAMOUNTBD    ,
          T_OVERDATE        ,
          T_STATE           ,
          T_STATEDATE       ,
          0, -- T_LNKREF
          T_BONUS           ,
          T_BEGBONUS        ,
          T_BONUSDATE       ,
          T_OLDBEGDATE      ,
          T_OLDBEGDISCOUNT  , 
          t_IsFree ,       
          T_DOCKIND,        
          T_DOCID  ,        
          T_PARTNUM,        
          T_PARTY  ,        
          T_CONTRACT,       
          T_BUY_SALE,       
          T_KIND    ,       
          T_COUPON      ,   
          T_PARTLY      ,   
          T_DEPARTMENT  ,   
          T_DEALID      ,   
          T_DEALDATE    ,   
          T_DEALCODE    ,   
          T_ENTERDATE   ,   
          T_TRUST       ,   
          T_PARENT      ,   
          T_SOURCE,
          t_BegInterestDate,
          t_BegDiscountDate,
          t_DiscountCorr   ,
          t_OldBegBonus    ,
          t_RecalcDate     ,
          t_IsEdit,
          T_BEGBONUSDATE,
          T_BEGDATE,
          T_INCOMERESERV,
          T_OLDBONUS,
          T_NOTWRTBONUS,
          T_COSTPFI,
          T_WRTOUTLAY,
          T_WRTOUTLAYDATE,
          T_WRTVATOUTLAY,
          T_FAIRVALUE,
          T_CORRVALUE,
          T_ACCOUNTEDDEFDIFF,
          T_CORRINTTOEIR,
          T_CORRESTRESERVE,
          T_ESTRESERVE,
          T_AMORTCOST,
          T_SORTCODE,
          T_BEGDEFDIFF,
          T_DEFDIFFDATE,
          T_EFFECTINTERESTRATE,
          T_AMORTCOSTDATE,
          T_CORRDATE,
          T_AMORTCALCKIND,
          T_ESTRESERVEDATE,
          T_CORRINTTOEIRDATE,
          T_CORRESTRESERVEDATE,
          T_HEDGCORR,
          T_HEDGCORRDATE,
          T_AMORTHEDGCORR,
          T_AMORTHEDGCORRDATE
     FROM DPMWRTSUM_DBT lot)
)
/

-- Для просмотра из скроллинга
CREATE OR REPLACE VIEW DV_SCWRTHISTEX
AS 
(
  (SELECT *
     FROM V_SCWRTHISTEX
  )
)
/

-- Текущее состояние портфеля. Вид, в котором отражается текущее состояние портфеля.
CREATE OR REPLACE VIEW V_SCWRTPORT
AS 
(
  SELECT T_DEPARTMENT             T_DEPARTMENT,       
         T_PARTY                  T_PARTY,            
         T_CONTRACT               T_CONTRACT,         
         T_FIID                   T_FIID,             
         T_PORTFOLIO              T_PORTFOLIO,          
         SUM(T_AMOUNT)            T_AMOUNT,           
         SUM(T_COST)              T_COST,             
         SUM(T_BALANCECOST)       T_BALANCECOST,      
         SUM(T_NKDAMOUNT)         T_NKDAMOUNT,        
         SUM(T_INTERESTINCOME)    T_INTERESTINCOME,   
         SUM(T_NOTCARRYINTEREST)  T_NOTCARRYINTEREST, 
         SUM(T_DISCOUNTINCOME)    T_DISCOUNTINCOME,   
         SUM(T_NOTCARRYDISCOUNT)  T_NOTCARRYDISCOUNT, 
         SUM(T_NOTCARRYDISCOUNT)  T_OUTLAY,           
         SUM(T_RESERVAMOUNT)      T_RESERVAMOUNT,     
         SUM(T_OVERAMOUNT)        T_OVERAMOUNT,
         SUM(T_BONUS)             T_BONUS,
         SUM(t_NotWrtBonus)       t_NotWrtBonus,
         SUM(T_COSTPFI)           T_COSTPFI
    FROM DPMWRTSUM_DBT
   WHERE T_ISFREE = chr(88)
  GROUP BY T_DEPARTMENT, T_PARTY, T_CONTRACT, T_PORTFOLIO, T_FIID
)
/