-- ’ ¡«¨æ  "DNPTXCHECK_NDR_SKR_TMP"

CREATE GLOBAL TEMPORARY TABLE DNPTXCHECK_NDR_SKR_TMP (
    T_ID NUMBER(10)
  , T_CLIENTID NUMBER(10)
  , T_OPERATION_ID NUMBER(10)
  , T_INCOME NUMBER(32,12)
  , T_EXPENSE NUMBER(32,12)
  , T_NOB_NDR NUMBER(32,12)
  , T_NOB_SKR NUMBER(32,12)
  , T_NOB13 NUMBER(32,12)
  , T_NOB30 NUMBER(32,12)
  , T_NOB15 NUMBER(32,12)
  , T_NOB18 NUMBER(32,12)
  , T_NOB20 NUMBER(32,12)
  , T_NOB22 NUMBER(32,12)
  , T_CHECK_NOB NUMBER(32,12)
  , T_NDFL_NDR NUMBER(32,12)
  , T_NDFL_SKR NUMBER(32,12)
  , T_NDFL_13 NUMBER(32,12)
  , T_NDFL_30 NUMBER(32,12)
  , T_NDFL_15 NUMBER(32,12)
  , T_NDFL_18 NUMBER(32,12)
  , T_NDFL_20 NUMBER(32,12)
  , T_NDFL_22 NUMBER(32,12)
  , T_CHECK_NDFL NUMBER(32,12)
  , T_CHECK_STG VARCHAR2(50)
) ON COMMIT PRESERVE ROWS
/
COMMENT ON TABLE DNPTXCHECK_NDR_SKR_TMP IS '‘¢¥àª  ‘Ž/„”‹'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_ID IS 'ˆ¤¥­â¨ä¨ª â®à § ¯¨á¨'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_CLIENTID IS 'ˆ¤¥­â¨ä¨ª â®à ª«¨¥­â '
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_OPERATION_ID IS 'ˆ¤¥­â¨ä¨ª â®à § ¯¨á¨ ¨§ â ¡«¨æë DNPTXSNOBVER_DBT'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_INCOME IS '„®å®¤ë'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_EXPENSE IS '‚ëç¥âë'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NOB_NDR IS 'Ž „'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NOB_SKR IS 'Ž áªà®««¨­£'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NOB13 IS 'Ž 13%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NOB30 IS 'Ž 30%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NOB15 IS 'Ž 15%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NOB18 IS 'Ž 18%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NOB20 IS 'Ž 20%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NOB22 IS 'Ž 22%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_CHECK_NOB IS 'à®¢¥àª  Ž'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NDFL_NDR IS '„”‹ ã¤. „'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NDFL_SKR IS '„”‹ ã¤. ‘ªà®««¨­£'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NDFL_13 IS '„”‹ 13%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NDFL_30 IS '„”‹ 30%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NDFL_15 IS '„”‹ 15%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NDFL_18 IS '„”‹ 18%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NDFL_20 IS '„”‹ 20%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_NDFL_22 IS '„”‹ 22%'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_CHECK_NDFL IS 'à®¢¥àª  „”‹'
/
COMMENT ON COLUMN DNPTXCHECK_NDR_SKR_TMP.T_CHECK_STG IS '’¥å á¢¥àª '
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXCHECK_NDR_SKR_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXCHECK_NDR_SKR_TMP_IDX0 ON DNPTXCHECK_NDR_SKR_TMP (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXCHECK_NDR_SKR_TMP_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXCHECK_NDR_SKR_TMP_IDX1 ON DNPTXCHECK_NDR_SKR_TMP (
   T_OPERATION_ID ASC
  ,T_CLIENTID ASC
)
/

CREATE SEQUENCE DNPTXCHECK_NDR_SKR_TMP_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXCHECK_NDR_SKR_TMP_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXCHECK_NDR_SKR_TMP FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXCHECK_NDR_SKR_TMP_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXCHECK_NDR_SKR_TMP_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
