--Добавление новых полей в таблицу сверки СНОБ
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVER_DBT ADD T_CHECKTYPE NUMBER(5) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_CHECKTYPE IS ''Тип сверки''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVER_DBT ADD T_UNLOADNOB CHAR(1) DEFAULT CHR(0)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_UNLOADNOB IS ''Выгрузка НОБ''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVER_DBT ADD T_UNLOADNDFL CHAR(1) DEFAULT CHR(0)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_UNLOADNDFL IS ''Выгрузка НДФЛ''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVER_DBT ADD T_UNLOADONLYERROR CHAR(1) DEFAULT CHR(0)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_UNLOADONLYERROR IS ''Выгрузка только ошибок''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVER_DBT ADD T_BYCLIENTSLIST CHAR(1) DEFAULT CHR(0)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_BYCLIENTSLIST IS ''По списку клиентов''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVER_DBT ADD T_BYCLIENT CHAR(1) DEFAULT CHR(0)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_BYCLIENT IS ''По клиенту''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVER_DBT ADD T_CLIENTID NUMBER(10) DEFAULT -1';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_CLIENTID IS ''Идентификатор клиента''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

