--Добавить новый справочник
BEGIN
  INSERT INTO DOBJECTS_DBT (T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE)
     VALUES(4162,'Типы сверки СНОБ','ТипСвСНОБ',0,0,CHR(1),CHR(0));

  INSERT INTO DLLVALUES_DBT (T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
     VALUES(4162,1,'1','Техническая',1,'Техническая',CHR(1));
    
  INSERT INTO DLLVALUES_DBT (T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
     VALUES(4162,2,'2','Сверка НОБ/НДФЛ',2,'Сверка НОБ/НДФЛ',CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
     
END;
/



