-- Таблица "DNPTXSHORT_TOTALCALC_DBT"

CREATE TABLE DNPTXSHORT_TOTALCALC_DBT (
    T_GUID VARCHAR2(40)
  , T_FIELDNAME VARCHAR2(50)
  , T_FIELDTYPE NUMBER(5)
  , T_FIELDVALUE VARCHAR2(200)
)
/
COMMENT ON TABLE DNPTXSHORT_TOTALCALC_DBT IS 'Данные основного листа краткой справки'
/
COMMENT ON COLUMN DNPTXSHORT_TOTALCALC_DBT.T_GUID IS 'Идентификатор запуска'
/
COMMENT ON COLUMN DNPTXSHORT_TOTALCALC_DBT.T_FIELDNAME IS 'Наименование поля на листе'
/
COMMENT ON COLUMN DNPTXSHORT_TOTALCALC_DBT.T_FIELDTYPE IS 'Тип поля RSL'
/
COMMENT ON COLUMN DNPTXSHORT_TOTALCALC_DBT.T_FIELDVALUE IS 'Значение поля'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXSHORT_TOTALCALC_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXSHORT_TOTALCALC_DBT_IDX0 ON DNPTXSHORT_TOTALCALC_DBT (
   T_GUID ASC
  ,T_FIELDNAME ASC
)
/
