-- Таблица "DNPTXSHORT_BILL_DBT"

CREATE TABLE DNPTXSHORT_BILL_DBT (
      T_GUID       VARCHAR2(40)
    , T_ITOG       CHAR(1)
    , T_SORT       NUMBER(10)
    , T_DOCNUMBER  VARCHAR2(100)  DEFAULT CHR(1)  
    , T_DOPER      VARCHAR2(40)   DEFAULT CHR(1)  
    , T_NBILL      VARCHAR2(45)   DEFAULT CHR(1)  
    , T_COST       VARCHAR2(45)   DEFAULT CHR(1)  
    , T_REPAYMENT  VARCHAR2(45)   DEFAULT CHR(1)  
    , T_INTEREST   VARCHAR2(45)   DEFAULT CHR(1)  
    , T_DISCOUNT   VARCHAR2(45)   DEFAULT CHR(1)  
    , T_SUMNOB     VARCHAR2(45)   DEFAULT CHR(1)  
)
/

COMMENT ON TABLE DNPTXSHORT_BILL_DBT IS 'Данные листа РЕПО краткой справки'
/
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_GUID       IS 'Идентификатор запуска'
/
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_ITOG       IS 'Итоговая строка'
/
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_SORT       IS 'Сортировка'
/
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_DOCNUMBER  IS 'Номер документа'
/                      
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_DOPER      IS 'Дата операции'
/                        
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_NBILL      IS '№ векселя'
/                            
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_COST       IS 'Затраты на приобретение векселя, руб.'
/
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_REPAYMENT  IS 'Сумма погашения / выкупа, руб.'
/       
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_INTEREST   IS 'Проценты, руб.'
/                       
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_DISCOUNT   IS 'Дисконт, руб.'
/                        
COMMENT ON COLUMN DNPTXSHORT_BILL_DBT.T_SUMNOB     IS 'Сумма НОБ, руб.'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXSHORT_BILL_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX DNPTXSHORT_BILL_DBT_IDX0 ON DNPTXSHORT_BILL_DBT (
   T_GUID ASC, T_ITOG ASC, T_SORT ASC
)
/

