--Наполнение системных аблиц для операции сверки НОБ/НДФЛ
DECLARE
BEGIN
  INSERT INTO DOPRKDOC_DBT(T_DOCKIND,T_PRIMARY,T_MODE,T_NAME,T_DBFILE,T_MACRONAME,T_CLASSMACRONAME,T_CLASSNAME,T_PARENTDOCKIND,T_MAXPHASE,T_PROGRAM,T_ORIGIN)
  VALUES(4653,'X',0,'Сверка НОБ/НДФЛ','nptxsnobver.dbt',CHR(1),CHR(1),CHR(1),0,0,CHR(0),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRKDATE_DBT(T_DATEKINDID , T_DOCKIND , T_NUMBERDATE , T_NAMEDATE , T_ELIMINATED)
  VALUES(465300000,4653,0,'Дата операции',CHR(0));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRKDATE_DBT(T_DATEKINDID , T_DOCKIND , T_NUMBERDATE , T_NAMEDATE , T_ELIMINATED)
  VALUES(465399999,4653,-1,'Дата цепочки',CHR(0));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSTKND_DBT(T_STATUSKINDID,T_CODE,T_NAME,T_DOCKIND,T_SORT,T_ELIMINATED)
  VALUES(46531,'ДО','Документооборот',4653,0,CHR(0));


  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(46531,1,'Открыт',CHR(0));

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(46531,2,'Закрыт',CHR(0));

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(46531,3,'Отвергнут',CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(204901,'Выполнение сверки',4653,0,CHR(0),CHR(1),1);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(204901,46531,2,'X');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRKSTEP_DBT(T_DOCKIND,T_KIND_ACTION,T_NAME,T_ISALLOWFOROPER,T_OPERORGROUP,T_RESERVE)
  VALUES(4653,1,'Пользовательский шаг',0,CHR(0),CHR(1));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(204901,10,1,0,0,CHR(0),0,CHR(0),0,0,'nptxchecknobndfl010.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Инициализация',465300000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(204901,20,1,0,0,CHR(0),0,CHR(0),10,0,'nptxchecknobndfl020.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Сверка',465300000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(204901,30,1,0,0,CHR(0),0,CHR(0),20,0,'nptxchecknobndfl030.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Формирование и отправка сообщения',465300000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRKOPER_DBT(T_KIND_OPERATION,T_DOCKIND,T_NOTINUSE,T_INITMACRO,T_SYSTYPES,T_NAME,T_SHORTNAME,T_UPGRADE,T_ISMAINTANANCE,T_PARENT,T_VERSION,T_MASSOPRSTART)
  VALUES(2049,4653,CHR(0),CHR(1),CHR(1),'Сверка НОБ/НДФЛ','СВЕР_НОБ_НДФЛ',CHR(0),CHR(0),0,CHR(1),CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRINIST_DBT(T_KIND_OPERATION,T_STATUSKINDID,T_NUMVALUE)
  VALUES(2049,46531,1);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
  v_OperBlockID NUMBER;
BEGIN

  INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                            T_SYMBOLSFORINSERTION,T_SYMBOL)
  VALUES(0,2049,204901,1,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

  INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
  VALUES(v_OperBlockID,46531,1,0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/