CREATE GLOBAL TEMPORARY TABLE DDL_DEBTREESTREXCEL_TMP
(
  T_ROWNUM         NUMBER(5),	
  T_DBONUM         VARCHAR2(64),	
  T_DEBTACCOUNT    VARCHAR2(25),	
  T_DEBTACCOUNTVAL VARCHAR2(7),	
  T_DEBTDATE       DATE,	
  T_DEBTSUM        NUMBER(32,12)	
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DDL_DEBTREESTREXCEL_TMP IS 'Данные Excel для реестра задолженности'
/
COMMENT ON COLUMN DDL_DEBTREESTREXCEL_TMP.T_ROWNUM IS 'Номер строки файла'
/
COMMENT ON COLUMN DDL_DEBTREESTREXCEL_TMP.T_DBONUM IS 'Номер ДБО'
/
COMMENT ON COLUMN DDL_DEBTREESTREXCEL_TMP.T_DEBTACCOUNT IS 'Номер брокерского счета, по которому возникла задолженность'
/
COMMENT ON COLUMN DDL_DEBTREESTREXCEL_TMP.T_DEBTACCOUNTVAL IS 'Валюта брокерского счета, по которому возникла задолженность'
/
COMMENT ON COLUMN DDL_DEBTREESTREXCEL_TMP.T_DEBTDATE IS 'Дата возникновения задолженности'
/
COMMENT ON COLUMN DDL_DEBTREESTREXCEL_TMP.T_DEBTSUM IS 'Сумма задолженности'
/