-- Таблица "DNPTXSHORT_REPPARM_DBT"

CREATE TABLE DNPTXSHORT_REPPARM_DBT (
      T_GUID VARCHAR2(40)
    , T_REQGUID VARCHAR2(40) DEFAULT CHR(1)
    , T_STATUS  NUMBER(5) DEFAULT 0
    , T_ENDDATE DATE DEFAULT TO_DATE('01.01.0001','DD.MM.YYYY')          
    , T_REPTYPE NUMBER(5) DEFAULT 0          
    , T_BYDEPO  CHAR(1) DEFAULT CHR(0)         
    , T_AVRKIND NUMBER(5) DEFAULT 0          
    , T_AVRFIID NUMBER(10) DEFAULT -1          
    , T_NEEDREALIZLIST CHAR(1) DEFAULT CHR(0)   
    , T_NEEDSHORTPOSLIST CHAR(1) DEFAULT CHR(0) 
    , T_NEEDREPOLIST CHAR(1) DEFAULT CHR(0)     
    , T_NEEDLUCRELIST CHAR(1) DEFAULT CHR(0)    
    , T_NEEDPFILIST CHAR(1) DEFAULT CHR(0)      
    , T_NEEDBILLLIST CHAR(1) DEFAULT CHR(0)     
    , T_NEEDPROTOCOLLIST CHAR(1) DEFAULT CHR(0) 
    , T_INCLUDE_TECH CHAR(1) DEFAULT CHR(0)     
    , T_BYIIS CHAR(1) DEFAULT CHR(0)            
    , T_CLIENTID NUMBER(10) DEFAULT -1         
    , T_DLCONTRID NUMBER(10) DEFAULT 0         
)
/
COMMENT ON TABLE DNPTXSHORT_REPPARM_DBT IS 'Параметры для подготовки данных краткой справки'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_GUID IS 'Идентификатор запуска'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_REQGUID IS 'Идентификатор внешнего запроса'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_ENDDATE          IS 'Отчетная дата'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_REPTYPE          IS 'Тип отчета'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_BYDEPO           IS 'Использовать данные Депозитария'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_AVRKIND          IS 'Вид ц/б'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_AVRFIID          IS 'Идентификатор ц/б'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_NEEDREALIZLIST   IS 'Реализация'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_NEEDSHORTPOSLIST IS 'Короткие позиции'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_NEEDREPOLIST     IS 'РЕПО'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_NEEDLUCRELIST    IS 'Материальная выгода'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_NEEDPFILIST      IS 'ПФИ'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_NEEDBILLLIST     IS 'Вексельные операции'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_NEEDPROTOCOLLIST IS 'Протокол'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_INCLUDE_TECH     IS 'С учетом технических НДР'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_BYIIS            IS 'По ИИС'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_CLIENTID         IS 'Идентификатор клиента'
/
COMMENT ON COLUMN DNPTXSHORT_REPPARM_DBT.T_DLCONTRID        IS 'Идентификатор договора ИИС'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXSHORT_REPPARM_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXSHORT_REPPARM_DBT_IDX0 ON DNPTXSHORT_REPPARM_DBT (
   T_GUID ASC
)
/
