-- Таблица "DNPTXSHORT_PROTOCOL_DBT"

CREATE TABLE DNPTXSHORT_PROTOCOL_DBT (
      T_GUID        VARCHAR2(40)
    , T_ITOG        CHAR(1)
    , T_SORT        NUMBER(10)
    , T_INCOMENDR   VARCHAR2(50)   DEFAULT CHR(1)  
    , T_INCOMECODE  VARCHAR2(10)   DEFAULT CHR(1)  
    , T_INCOMENAME  VARCHAR2(100)  DEFAULT CHR(1)  
    , T_INCOMESUM   VARCHAR2(45)   DEFAULT CHR(1)  
    , T_EXPENSENDR  VARCHAR2(50)   DEFAULT CHR(1)  
    , T_EXPENSECODE VARCHAR2(10)   DEFAULT CHR(1)  
    , T_EXPENSENAME VARCHAR2(100)  DEFAULT CHR(1)  
    , T_EXPENSESUM  VARCHAR2(45)   DEFAULT CHR(1)  
)
/

COMMENT ON TABLE DNPTXSHORT_PROTOCOL_DBT IS 'Данные листа РЕПО краткой справки'
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_GUID         IS 'Идентификатор запуска'
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_ITOG         IS 'Итоговая строка'
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_SORT         IS 'Сортировка'
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_INCOMENDR    IS 'НДР(доход)'
/         
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_INCOMECODE   IS 'Код дохода'         
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_INCOMENAME   IS 'Наименование дохода'
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_INCOMESUM    IS 'Сумма дохода'       
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_EXPENSENDR   IS 'НДР(расход)'        
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_EXPENSECODE  IS 'Код вычета'         
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_EXPENSENAME  IS 'Наименование вычета'
/
COMMENT ON COLUMN DNPTXSHORT_PROTOCOL_DBT.T_EXPENSESUM   IS 'Сумма вычета' 
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXSHORT_PROTOCOL_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX DNPTXSHORT_PROTOCOL_DBT_IDX0 ON DNPTXSHORT_PROTOCOL_DBT (
   T_GUID ASC, T_ITOG ASC, T_SORT ASC
)
/

