apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  namespace: location
  name: sofr-qmngr-mq-adapter
spec:
  type: url
  targets:
    - https://gitlab.rshbdev.ru/rshbintech/it-invest/ckips/ips/integrations/sofr-qmngr-mq-adapter/-/blob/master/catalog-component-info.yaml