CREATE TABLE DDL_PROF_DBT
(
  T_UNIQ_NAME     VARCHAR2(300),
  T_OBJKIND       NUMBER(10),
  T_OBJID         VARCHAR2(300),
  T_RECCOMMENT    VARCHAR2(500),
  T_SID           NUMBER(10),
  T_FIRSTBEGTIME  TIMESTAMP(6),
  T_FIRSTENDTIME  TIMESTAMP(6),
  T_LASTENDTIME   TIMESTAMP(6),
  T_COUNT         NUMBER(10),
  T_TIMETOTAL     NUMBER(20),
  T_TIMEMIN       NUMBER(20),
  T_TIMEMAX       NUMBER(20),
  T_TIMEAVG       NUMBER(32,12),
  T_TIMEMEDIAN    NUMBER(32,12)
)
/

CREATE INDEX DDL_PROF_DBT_IDX0 ON DDL_PROF_DBT
(T_UNIQ_NAME, T_OBJKIND, T_OBJID, T_SID)
/

CREATE INDEX DDL_PROF_DBT_IDX1 ON DDL_PROF_DBT
(T_FIRSTENDTIME)
/

CREATE INDEX DDL_PROF_DBT_IDX2 ON DDL_PROF_DBT
(T_LASTENDTIME)
/

CREATE INDEX DDL_PROF_DBT_IDX3 ON DDL_PROF_DBT
(T_SID)
/

CREATE INDEX DDL_PROF_DBT_IDX4 ON DDL_PROF_DBT
(T_FIRSTBEGTIME)
/