BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE DTRN_PROHIBITED_DBT ADD T_ISEXCLUDED CHAR(1) DEFAULT CHR(0)';
END;
/

BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE DTRN_PROHIBITED_DBT ADD T_EXCLUDEDATE DATE DEFAULT to_date(''01/01/0001'', ''dd/mm/yyyy'')';
END;
/

BEGIN
EXECUTE IMMEDIATE 'CREATE INDEX DTRN_PROHIBITED_DBT_IDX2 ON DTRN_PROHIBITED_DBT (T_ISEXCLUDED ASC)';
END;
/