-- Таблица

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DNPTXSHSUM_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DNPTXSHSUM_TMP
(
  T_DOCID         NUMBER(10),
  T_PARENT_DOCID  NUMBER(10),
  T_CODE          VARCHAR2(15),
  T_AMOUNT        NUMBER(32,12),
  T_SUM           NUMBER(32,12)
)ON COMMIT PRESERVE ROWS
/
