--Добавление полей
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDVDEAL_DBT ADD T_PRICE_RUR NUMBER(32,12) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDVDEAL_DBT.T_PRICE_RUR IS ''Цена в рублях''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDVDEAL_DBT ADD T_POSITIONCOST_RUR NUMBER(32,12) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDVDEAL_DBT.T_POSITIONCOST_RUR IS ''Стоимость сделки в рублях''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDVDEAL_DBT ADD T_BASEFUT_AMOUNT NUMBER(32,12) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDVDEAL_DBT.T_BASEFUT_AMOUNT IS ''Количество базового актива''';
   EXCEPTION WHEN e_exist_field THEN NULL;                                                          
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDVDEAL_DBT ADD T_RECORD_ID NUMBER(10) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDVDEAL_DBT.T_RECORD_ID IS ''ID записи репликации, по которой была создана сделка''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/