-- Таблица "DOWNBONDSREGISTERHST_DBT"

CREATE TABLE DOWNBONDSREGISTERHST_DBT (
    T_DEALID NUMBER(10)
  , T_FIID NUMBER(10)
  , T_CHANGEDATE DATE
  , T_AMOUNT NUMBER(32,12)
  , T_ISBUY CHAR(1)
  , T_RESELL CHAR(1)
  , T_PRICE NUMBER(32,12)
)/

COMMENT ON TABLE DOWNBONDSREGISTERHST_DBT IS 'Исправленная история по размещениям'/
COMMENT ON COLUMN DOWNBONDSREGISTERHST_DBT.T_DEALID IS 'ID сделки размещения'/
COMMENT ON COLUMN DOWNBONDSREGISTERHST_DBT.T_FIID IS 'ID финансового инструмента'/
COMMENT ON COLUMN DOWNBONDSREGISTERHST_DBT.T_CHANGEDATE IS 'Дата изменения остатка'/
COMMENT ON COLUMN DOWNBONDSREGISTERHST_DBT.T_AMOUNT IS 'Количество бумаг'/
COMMENT ON COLUMN DOWNBONDSREGISTERHST_DBT.T_ISBUY IS 'Выкуп'/
COMMENT ON COLUMN DOWNBONDSREGISTERHST_DBT.T_RESELL IS 'Размещение выкупленного'/
COMMENT ON COLUMN DOWNBONDSREGISTERHST_DBT.T_PRICE IS 'Цена для вторичного размещения'/

