-- Таблица
DROP TABLE DNPTXOP1OPLNK_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE DNPTXOP1OPLNK_TMP
(
  T_DOCID         NUMBER(10),
  T_PARENT_DOCID  NUMBER(10),
  T_AMOUNT        NUMBER(32,12),
  T_AMOUNT1       NUMBER(32,12),
  T_AMOUNT2       NUMBER(32,12),
  T_SUM1          NUMBER(32,12),
  T_FLAGSUM1      CHAR(1),
  T_SUM2          NUMBER(32,12),
  T_FLAGSUM2      CHAR(1),
  T_SUM3          NUMBER(32,12),
  T_FLAGSUM3      CHAR(1)
) ON COMMIT PRESERVE ROWS
/
