BEGIN

EXECUTE IMMEDIATE 'alter table DNUNPREP_TMP add T_NKDREPRUB3 NUMBER(32,12)';

EXECUTE IMMEDIATE 'alter table DNUNPREP_TMP add T_NKDREPVN NUMBER(32,12)';
 
EXECUTE IMMEDIATE 'alter table DNUNPREP_TMP add T_NKDREPCHGNUMRUB NUMBER(32,12)';

EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/