/*ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  RS-Bank V6                                                                        R-Style Softlab
  ” ©« ¯®¤á¨áâ¥¬ë "¥£« ¬¥­â¨àã¥¬ ï ®âç¥â­®áâì"

  Š« áá ¯ à ¬¥âà®¢ ®âç¥â  ”

  ‘®§¤ ­: 20.04.2007 - Ser.
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ*/
class TParameters()
    local class TReservation()
        private var m_naturalPersonRouble;
        private var m_notresidentLendingAgencyRouble;
        private var m_othersRouble;
        private var m_notresidentLendingAgencyCurrency;
        private var m_othersCurrency;        

        getRegistryValue( "REPTREG/REP_GROUPS/”/Œ€’ˆ‚› 255-/…‡…‚ˆ‚€ˆ…/”ˆ‡‹ˆ–€_‚_“‹Ÿ•",  V_DOUBLE, m_naturalPersonRouble, NULL);
        getRegistryValue( "REPTREG/REP_GROUPS/”/Œ€’ˆ‚› 255-/…‡…‚ˆ‚€ˆ…/Š_……‡_‚_“‹Ÿ•", V_DOUBLE, m_notresidentLendingAgencyRouble, NULL );
        getRegistryValue( "REPTREG/REP_GROUPS/”/Œ€’ˆ‚› 255-/…‡…‚ˆ‚€ˆ…/ˆ›…_‚_“‹Ÿ•",     V_DOUBLE, m_othersRouble, NULL );
        getRegistryValue( "REPTREG/REP_GROUPS/”/Œ€’ˆ‚› 255-/…‡…‚ˆ‚€ˆ…/Š_……‡_‚_‚€‹’…", V_DOUBLE, m_notresidentLendingAgencyCurrency, NULL );
        getRegistryValue( "REPTREG/REP_GROUPS/”/Œ€’ˆ‚› 255-/…‡…‚ˆ‚€ˆ…/ˆ›…_‚_‚€‹’…",     V_DOUBLE, m_othersCurrency, NULL );

        private macro checkReservation()
            if ((m_naturalPersonRouble == NULL) or
                (m_notresidentLendingAgencyRouble == NULL) or
                (m_othersRouble == NULL) or
                (m_notresidentLendingAgencyCurrency == NULL) or
                (m_othersCurrency == NULL))
                runError("¥ § ¤ ­ë ­ áâà®©ª¨: REPTCB/REP_GROUPS/”/Œ€’ˆ‚› 255-/…‡…‚ˆ‚€ˆ…/");
            end;
        end;

        macro getNaturalPersonRouble()
            return m_naturalPersonRouble/100;
        end;

        macro getNotresidentLendingAgencyRouble()
            return m_notresidentLendingAgencyRouble/100;
        end;

        macro getOthersRouble()
            return m_othersRouble/100;
        end;

        macro getNotresidentLendingAgencyCurrency()
            return m_notresidentLendingAgencyCurrency/100;
        end;

        macro getOthersCurrency()
            return m_othersCurrency/100;
        end;
        checkReservation();
    end;

    private var m_period                 = rcbApplication().currentReport.context.period;
    private var m_departmentCode         = rcbApplication().currentReport.context.departmentCode;
    private var m_planNumber             = ‹®£¨ç¥áª¨©« ­‘ç¥â®¢;
    private var m_isDataBalance          = false;
    private var m_isConversionOfCurrency = false;
    private var m_topSelfId              = {OurBank};
    private var m_reservation            = TReservation();
    private var m_averagingOutValue      = 0;
    private var m_isAveragingOut         = false;
    private var m_printZero              = 0;
    private var m_printApplicationZero   = false;
    private var m_reportLength;
    private var m_isPaidCancellation     = false;
    private var m_isCalendarWeekends     = true;

    macro isPaidCancellation()
        return m_isPaidCancellation;
    end;

    macro getPrintZero()
        return m_printZero;
    end;

    macro getPeriod()
        return m_period;
    end;

    macro getBeginDate()
        return m_period.beginDate;
    end;

    macro getEndDate()
        return m_period.endDate;
    end;

    macro getDepartmentCode()
        return m_departmentCode;
    end;

    macro getPlanNumber()
        return m_planNumber;
    end;

    macro isDataBalance()
        return m_isDataBalance;
    end;

    macro isConversionOfCurrency()
        return m_isConversionOfCurrency;
    end;

    macro getTopSelfId()
        return m_topSelfId;
    end;

    macro getReservation()
        return m_reservation;
    end;

    macro isAveragingOut()
        return m_isAveragingOut;
    end;

    macro getAveragingOutValue()
        return m_averagingOutValue;
    end;

    macro isPrintApplicationZero()
        return m_printApplicationZero;
    end;

    macro getReportLength()
        return m_reportLength;
    end;

    macro isOneFilial() : Bool
        //§ £«ãèª 
        return false;
    end;

    macro isHeadDepartment() : Bool
        //§ £«ãèª 
        return true;
    end;

    macro isCalendarWeekends() : Bool
        return m_isCalendarWeekends;
    end;

    local macro initializeTopSelfId()
        var dataSet = TRsbDataSet("SELECT rsb_rep_pt.get_top_superior_id(" + {OurBank} + ") t_topSelfId FROM DUAL");

        if (dataSet.next())
            m_topSelfId = dataSet.topSelfId;
        end;
    end;

    getRegistryValue("REPTREG/REP_GROUPS/”/…—€’œ_“‹…‰",                    V_INTEGER, m_printZero,              NULL);
    getRegistryValue("REPTREG/REP_GROUPS/”/„€›… €‹€‘€",                  V_BOOL,    m_isDataBalance,          NULL);
    getRegistryValue("REPTREG/REP_GROUPS/”/‚€‹’€__Š“‘“",                 V_BOOL,    m_isConversionOfCurrency, NULL);
    getRegistryValue("REPTREG/REP_GROUPS/”/“‘…„…ˆ…",                      V_BOOL,    m_isAveragingOut,         NULL);
    getRegistryValue("REPTREG/REP_GROUPS/”/Œ€’ˆ‚› 255-/“‘…„…ˆ…",      V_DOUBLE,  m_averagingOutValue,      NULL);
    getRegistryValue("REPTREG/REP_GROUPS/”/…—€’œ “‹…‚›• ˆ‹†…ˆ‰",       V_BOOL,    m_printApplicationZero,   NULL);
    getRegistryValue("REPTREG/REP_GROUPS/COMMON/˜ˆˆ€_’—…’€",                V_INTEGER, m_reportLength,           NULL);
    getRegistryValue("REPTREG/REP_GROUPS/”/€‘’ƒ. ˆ ‹€—. ‘“Š…„ˆ’",     V_BOOL,    m_isPaidCancellation,   NULL);
    getRegistryValue("REPTREG/REP_GROUPS/”/‚›•„. ˆ €. „ˆ  Š€‹…„€", V_BOOL,    m_isCalendarWeekends,   NULL);

    initializeTopSelfId();
end;
