/*
$Name:         vaw100.mac
$Module:       Учтенные векселя
$Description:  Мена векселей СВ<->УВ. S.актуализация балансовых счетов

            va-вексель
             w-операция мены векселей СВ<->УВ
           100-номер (соответствующий шагу)
*/

IMPORT vacateg, va4each, vaacc, vsbnrfd, vatickfd, vawdates, vamisc, vslib, vaxutils;

PRIVATE VAR
    StepDate = {curdate};           /* Дата выполнения шага */

PRIVATE MACRO АктСчетПередаваемогоВекселя(bnr, leg, tick, numOrd, lnk)
var Счет, fd, stat = 0;

    fd = VSBannerFD(bnr, leg, tick.BofficeKind, tick);

    if((stat == 0) and not VA_GetAccount("Наш вексель", fd, Счет, MC_OPENACC_CREATE, fd.ОпределитьВалютуУчета(), null, null, StepDate))
        stat = 1;
    end;

    if((stat == 0) and not VA_GetAccount("СВексель к исполнению", fd, Счет, MC_OPENACC_CREATE, fd.ОпределитьВалютуУчета(), null, null, StepDate))
        stat = 1;
    end;

    if((stat == 0) and not VA_GetAccount("Разн.ценности и документы", fd, Счет, MC_OPENACC_CREATE, NATCUR, null, null, StepDate))
        stat = 1;
    end;

    if(stat == 0)
        if(ВексельПроцентный(leg))
            if(not VA_GetAccount("БВыплДиск,Сц/б", fd, Счет, MC_OPENACC_CREATE, fd.ОпределитьВалютуУчета(), FIROLE_PERCENT, null, StepDate))
                stat = 1;
            end;

            if((stat == 0) and not VA_GetAccount("-Эмиссия, СВ", fd, Счет, MC_OPENACC_CREATE, NATCUR, FIROLE_PERCENT, null, StepDate))
                stat = 1;
            end;

            if((stat == 0) and not VA_GetAccount("Обяз%,СВексель", fd, Счет, MC_OPENACC_CREATE, fd.ОпределитьВалютуУчета(), null, null, StepDate))
                stat = 1;
            end;
        end;
    end;

    if(stat == 0)
        if(ВексельДисконтный(leg, bnr))
            if(not VA_GetAccount("БВыплДиск,Сц/б", fd, Счет, MC_OPENACC_CREATE, fd.ОпределитьВалютуУчета(), FIROLE_DISCOUNT, null, StepDate))
                stat = 1;
            end;

            if((stat == 0) and not VA_GetAccount("-Эмиссия, СВ", fd, Счет, MC_OPENACC_CREATE, NATCUR, FIROLE_DISCOUNT, null, StepDate))
                stat = 1;
            end;
        end;
    end;

    return stat;
END;

/* Актуализирует счета векселей
*/
PRIVATE MACRO СчетаВекселей(tick)
var stat = 0;

    stat = VA_ForEachBanner(tick, @АктСчетПередаваемогоВекселя, VSORDLNK_K_SALE);

    return (stat == 0);
END;

/* Запуск шага
   Алгоритм:
     Актуализировать и открыть счета категорий (см. УАМ)
*/
MACRO ExecuteStep(Buffer, dl_tick)
var stat = 0;
    record tick(dl_tick);

    SetBuff(tick, dl_tick);

    GetOprDate(DATE_XW_REG, @StepDate);

    if(StepDate > {curdate})
        stat = VA_Err("Преждевременное выполнение шага запрещено.");
    end;

    if(stat == 0)
        stat = VA_ProcessDiffPaym(tick);
    end;

    if((stat == 0) and not СчетаВекселей(tick))
        stat = 1;
    end;

    return stat;
END;

/* Макрос постобработки
*/
MACRO PostStep(
                CommitOrRollback, /*1-выполнение шага,2 -откат шага*/
                errTrn,        /* Статус выполнения шага-!0-произошла ошибка */
                FirstDoc,      /* Указатель на первичный документ */
                ID_Operation,  /* Номер экземпляра операции */
                Num_Step,      /* Номер шага операции(из настроек) */
                Kind_Operation,/* Вид операции */
                KindDoc,       /* Вид первичного документа */
                KindStep,      /* Вид шага операции */
                ID_Step)       /* Номер шага операции */

    if(errTrn or (CommitOrRollback == 2))
        /* Произошла ошибка или происходит откат */
        return;
    end;

    return 1;
END;

/* Макрос печати
*/
MACRO PrintStepDocs(
                ID_Operation,  /* Номер экземпляра операции */
                ID_Step,       /* Номер шага операции */
                Kind_Operation,/* Вид операции */
                KindStep)      /* Вид шага операции */

    exit(1);
END;
