/*********************************************************************
*  ---------------------                                             *
*  R-Style Software Lab.                                             *
*  ---------------------                                             *
*  RS-Retail                                                         *
*                                                                    *
*  Пластиковые карточки                                              *
*                                                                    *
*  Действия при удалении Карточки Платежной системы STB-Card         *
*                                                                    *
*  Лебедев С.В.                                                      *
*  17.12.99                                                          *
*********************************************************************/

import "sc_error.mac","stb_com.mac";

record SC_CARD (scCard, "spcard.def");       /* Карточка - Глобальная строка */

file LinkProp  (scLGrPr,"spcard.def") write; /* Связь объектов со свойствами */
file Prop      (scProp, "spcard.def") write; /* Свойства объектов            */


/*********************************************************************
             Поиск индивидуальных лимитов в файле свойств
*********************************************************************/
macro FindProperty

  var stat = FALSE;

  KeyNum(LinkProp,2);
  LinkProp.FNCash       = SC_CARD.FNCash;
  LinkProp.recRef       = SC_CARD.cardRef;
  LinkProp.recRef2      = "";
  LinkProp.CodeProperty = LogSC_Card;
  LinkProp.TypeProperty = TypeLIMIT;
  if (GetEQ(LinkProp))
    if (LinkProp.PropertyOrGroup == OnProperty)
      KeyNum(Prop,0);
      Prop.FNCash      = LinkProp.FNCash;
      Prop.PropertyRef = LinkProp.GrPrRef;
      stat = GetEQ(Prop);
    end;
  end;

  return stat;

end;


/*********************************************************************
		 Действия при удалении карточки
*********************************************************************/
macro DeleteCardFromProperty

  if (FindProperty())
    if (NOT Delete(LinkProp))
      AbortTrn();
    end;
    if (NOT Delete(Prop))
      AbortTrn();
    end;
  end;

end;


/*********************************************************************
       	          Г Л А В Н А Я   П Р О Г Р А М М А
*********************************************************************/

  ALG_STAT = НЕТ_ОШИБКИ;

  if (ALG_WHATDO == SCPSMAC_DELETE)
    if (NOT ProcessTrn(NULL,"DeleteCardFromProperty",Prop,LinkProp));
      ALG_STAT = ЕСТЬ_ОШИБКА;
    end;
  end;

end;
