--Временная таблица

CREATE GLOBAL TEMPORARY TABLE DNPTX6CALCKBK_TMP
(
  T_CLIENTID          NUMBER(10),
  T_RATE              FLOAT(53),
  T_KBK               VARCHAR2(20),
  T_TOTALPLUS         NUMBER(32,12),
  T_TOTALMINUS        NUMBER(32,12),
  T_TAXCALCULATED     NUMBER(32,12),
  T_TAXCALCULATEDDIV  NUMBER(32,12),
  T_TAXPAID           NUMBER(32,12),
  T_TAXDUE            NUMBER(32,12),
  T_TAXOVER           NUMBER(32,12),
  T_TAXTORETURNDUE    NUMBER(32,12),
  T_ZNP               NUMBER(32,12),
  T_ISHIGHRATE        CHAR(1)
)
ON COMMIT PRESERVE ROWS
/
