DECLARE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDLCONTRSERV_DBT ADD T_NUMBER VARCHAR2(20) DEFAULT CHR(1)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDLCONTRSERV_DBT.T_NUMBER IS ''Номер договора''';
END;
/

DECLARE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDLCONTRSERV_DBT ADD T_CONCDATE DATE DEFAULT TO_DATE(''01.01.0001'', ''MM.DD.YYYY'')';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDLCONTRSERV_DBT.T_CONCDATE IS ''Дата заключения договора''';
END;
/
