/*
$Name: dpglrep.mac
$Module: „¥¯®§¨â à¨©
$Description: Žâç¥â ®¡ ¨á¯®«­¥­¨¨ £«®¡ «ì­®© ®¯¥à æ¨¨
*/
import RsbDataSet;
import cb_sql;
import FIInter, DPInter, secinter, dpstdrep;

private var HeaderStr = " Ž ’ — … ’   Ž    ˆ ‘  Ž ‹  …  ˆ ˆ   ƒ ‹ Ž  € ‹ œ  Ž ‰   Ž  …  € – ˆ ˆ";
private var HeadreStrReject = "“ ‚ … „ Ž Œ ‹ …  ˆ …   Ž    Ž ’ Š € ‡ …   ‚   ˆ ‘  Ž ‹  …  ˆ ˆ    Ž  “ — …  ˆ Ÿ";

private const OBJTYPE_TRANSACTION_CONTENT = 1200; /* ‘®¤¥à¦ ­¨¥ âà ­§ ªæ¨¨ */

//¢¨¤ë £«®¡ «ì­ëå ®¯¥à æ¨©
const DP_GLOBOPOPERATION_CONVERT  = 4741; //ª®­¢¥àâ æ¨ï
const DP_GLOBOPOPERATION_REPAY    = 4742; //¯®£ è¥­¨¥
const DP_GLOBOPOPERATION_BONEMISS = 4743; //¡®­ãá­ ï í¬¨áá¨ï

//ä®à¬ë ª®­¢¥àâ æ¨¨
const CONVFORM_CONVERT = 1;  //ª®­¢¥àâ æ¨ï
const CONVFORM_CUTTING = 2;  //¤à®¡«¥­¨¥
const CONVFORM_CONSOL  = 3;  //ª®­á®«¨¤ æ¨ï
const CONVFORM_ANUL    = 4;  // ­ã«¨à®¢ ­¨¥ ª®¤  ¤®¯®«­¨â¥«ì­®£® ¢ë¯ãáª 
const CONVFORM_SUMM    = 5;  //®¡ê¥¤¨­¥­¨¥ ¢ë¯ãáª®¢


private const ALG_FORMCONVERT = 3233;
private const ALG_DEPO_OPERSTATEPAST = 3216; // ‚ à¨ ­âë ®¡à ¡®â®ª ¯®àãç¥­¨© ¤¥¯® ¢ ¯à®è«®¬

private const DP_NOTEKIND_REJECT = 2; /* ¯à¨¬¥ç ­¨¥ "¯à¨ç¨­  ®âª § " */
const DP_NOTEKIND_REJECT_REGLIN = 1; /* ¯à¨¬¥ç ­¨¥ "¯à¨ç¨­  ®âª § " ¤«ï áâà®ª¨ à¥¥áâà */
const OBJTYPE_REGLIN = 121;

var SpLogopr    = TBFile("splogopr");
var GroundAdd = TBFile("spground", "R", 6);
var SpgrData, SpgrCmd;

var   _NumDprt         :integer,   _GrDoc           :integer,
      _BeginDate       :date,      _EndDate         :date,   
      _XldBegin        :string,    _XldEnd          :string, 
      _OpKind          :integer,   _iGlOpForm       :integer,
      _OpStatus        :integer,   _OpStatusBegin   :date,   
      _OpStatusEnd     :date,      _OjdNumBegin     :string, 
      _OjdNumEnd       :string,    _iStoragePlace   :integer,
      _iStorAcc        :integer,   _iIssuer         :integer,
      _iFI             :integer,   _iIssuerTo       :integer,
      _iFIIDto         :integer,   _iParty          :integer,
      _iDepoAcc        :integer,   _LOAuotoKey      :integer,
      _ToExcel         :bool,      _is_ap           :bool;    

var _DocumentID = 0, _GlRepRecipientID = -1, _RepNum, _RepDate;

var GlRepDataSet = "";



private var HeadTable = "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿\n"+
                        "³          Ž¯¨á ­¨¥ ¢ë¯ãáª            ³   Š®«¨ç¥áâ¢® æ/¡   ³\n"+
                        "ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´";


private var HeadTableRejAccConv = "ÚÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿\n"+
                                  "³  ü ¯/¯  ³     ‘ç¥â ¤¥¯®      ³     ‚« ¤¥«¥æ áç¥â  ¤¥¯®    ³ Š®«¨ç¥áâ¢® ª®­¢¥àâ¨àã¥¬ëå æ/¡ ³      à¨ç¨­  ®âª §       ³\n"+
                                  "ÃÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´";


private var HeadTableRejAccRepay = "ÚÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿\n"+
                                   "³  ü ¯/¯  ³     ‘ç¥â ¤¥¯®      ³     ‚« ¤¥«¥æ áç¥â  ¤¥¯®    ³   Š®«¨ç¥áâ¢® ¯®£ è ¥¬ëå æ/¡   ³      à¨ç¨­  ®âª §       ³\n"+
                                   "ÃÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´";


private var HeadTableRejAccBon   = "ÚÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿\n"+
                                   "³  ü ¯/¯  ³     ‘ç¥â ¤¥¯®      ³     ‚« ¤¥«¥æ áç¥â  ¤¥¯®    ³ Š®«¨ç¥áâ¢® æ/¡ ¤«ï à áç¥â  ¡®­ãá  ³      à¨ç¨­  ®âª §       ³\n"+
                                   "ÃÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´";

private var tablewidth = Index(HeadTableRejAccBon, "\n");
var GlRep = null;//= CMakeReport(HeadTable);
const FontStyleTitel =  "ex_FS(b)";

macro AddStr()
   GlRep.AddStr();
end;

macro AddEmptyStr();
   GlRep.AddEmptyStr();
end;

macro PrintCell( Str, width )
   DP_AddPrintCell( GlRep,  Str, strlen(Str)+2, 0, "l:" + FontStyleTitel, _is_ap, REP_ELEM_STR );
end;

macro PrintCellTable( Str )
   DP_AddPrintCell( GlRep,  Str, 0, 0, "l:w:" + FontStyleTitel );
end;

macro PrintCellSize( Str, S_Size )
   DP_AddPrintCell( GlRep,  Str, S_Size, 0, "l:w:" + FontStyleTitel, _is_ap, REP_ELEM_STR );
end;

macro PrintCellTableSizeCenter( Str, S_Size, Format )
   if(ValType(Format) == V_UNDEF )
       Format ="";
   end;
   DP_AddPrintCell( GlRep,   Str, S_Size, 0, "c:w:" + Format + FontStyleTitel );
end;

macro PrintCellTableSizeRight( Str, S_Size, Format )
   if(ValType(Format) == V_UNDEF )
       Format ="";
   end;
   DP_AddPrintCell( GlRep,   Str, S_Size, 0, "r:w:" + Format + FontStyleTitel );
end;

macro PrintCellTableSize( Str, S_Size, Format )
   if(ValType(Format) == V_UNDEF )
       Format ="";
   end;
   DP_AddPrintCell( GlRep,  Str, S_Size, 0, "l:w:" + Format + FontStyleTitel );
end;

macro GetStateReglinAcc(RegisterID, DepoRoot)
  var query, Data;
  var state = DPREGLINSTATE_CLOSE;

  query =   " select t_State from ddpreglin_dbt "
          + "  where t_RegisterID = " + RegisterID
          + "    and t_HolderAccID in ( select t_AutoKey from ddepoacnt_dbt where t_Root = "+DepoRoot+" )"; 

  Data = TRsbDataSet(query);
  if( Data.moveNext() )
    state = Data.State;
  end;   

  return state;
end;

private macro GetLLVALUES( List, Elem )
  file llvalues("llvalues");

  ClearRecord(llvalues);
  llvalues.List    = List;
  llvalues.Element = Elem;
  if( GetEQ(llvalues) )
    return llvalues.Name;
  end;

  return "";
end; 

macro GetPartyFullName( PartyID, RepDate )
  var cParty = CDPParty(PartyID, RepDate);

  return cParty.Name();
end;

macro GetRecipientName()
  var RecipientName = "-";
  
  if(_GlRepRecipientID > 0)
    RecipientName = GetPartyName( _GlRepRecipientID, true );
  elif( _LOAuotoKey )
    SpLogopr.rec.AutoKey = _LOAuotoKey;
    if( SpLogopr.GetEQ() )
      GroundAdd.rec.SourceDocKind = 830;
      GroundAdd.rec.SourceDocID = _LOAuotoKey;
      GroundAdd.rec.Direction   = EXITING;
      GroundAdd.rec.Department  = {OperDprt};
      GroundAdd.rec.Division = SelfDivision;
      if(GroundAdd.GetEQ())
        if(GroundAdd.rec.PartyName == "")
          RecipientName = GetPartyName( GroundAdd.rec.Party, true );
        else
          RecipientName = GroundAdd.rec.PartyName;
        end;
      end;
    end;
  end;
  return RecipientName;
end;


macro GetOperationName(Kind_Operation)
  file opr("oprkoper");
  var stat = 0;

  opr.Kind_Operation = Kind_Operation;
  stat = GetEQ(opr);
  return IIF( stat, opr.Name, "" );

end;

macro GetRejectNote( DocID )

  return readNoteForObject( OBJTYPE_REESTRLIST,
                            string(DocID),
                            DP_NOTEKIND_REJECT);

end;

macro GetRejectNoteReglin( DocID )

  var DocumentID:integer = DocID;

  return readNoteForObject( OBJTYPE_REGLIN,
                            L_Z(0, 10-strlen(string(DocumentID)))+string(DocumentID),
                            DP_NOTEKIND_REJECT_REGLIN );

end;

macro GetFaceValueFiStr( FaceValueFI )
  file fin("fininstr");
  var stat = 0;

  fin.FIID = FaceValueFI;
  stat = GetEQ(fin);

  return IIF( stat, string( fin.FI_Code + " (" + fin.Name + ") "), "-");
end;

macro GetFirstSpgrData()
  var query;
  var stat = 0;

  query =   " select spgr.t_AltXld, spgr.t_SignedDate, llv.t_Name "
          + " from dspground_dbt spgr, dspgrdoc_dbt spgrdoc, dllvalues_dbt llv "
          + " where spgr.t_SPgroundID = spgrdoc.t_SPgroundID "
          + "   and spgr.t_Direction != " + EXITING
          + "   and spgrdoc.t_SourceDocKind = ? " 
          + "   and spgrdoc.t_SourceDocID   = ? " 
          + "   and llv.t_List = " + OBJTYPE_KINDDOC
          + "   and llv.t_Element = spgr.t_Kind ";

  SpgrCmd = DL_RSDCommand(query);
  SpgrCmd.AddParam(GlRepDataSet.DocKind);
  SpgrCmd.AddParam(GlRepDataSet.DocumentID);

  SpgrData = SpgrCmd.Execute();
  stat = SpgrData.moveNext();

  return IIF(stat, SpgrData.Name + " ü" + SpgrData.AltXld + " ®â " + string(date(SpgrData.SignedDate:f)), "-");

end;

macro GetNextSpgrData()
  var stat = 0;
  stat = SpgrData.moveNext();
  return IIF(stat, SpgrData.Name + " ü" + SpgrData.AltXld + " ®â " + string(date(SpgrData.SignedDate:f)), "");
end;

macro GetSumREGLINrest(RegisterID, FIIDfrom, FIIDto, DepoRoot )

  var Reglin, query, cmd, rest = 0;

  cmd = DL_RSDCommand();

  if( FIIDfrom != -1 )
    query =   " select sum(rl.t_Hrest) as cnt from ddpreglin_dbt rl, daccount_dbt acc "
            + " where rl.t_RegisterID = ? " 
            + " and rl.t_FIIDfrom = ? ";

    cmd.AddParam(RegisterID);
    cmd.AddParam(FIIDfrom);
  
  elif( FIIDto != -1 )
    query =   " select sum(rl.t_BruttoAmount) as cnt from ddpreglin_dbt rl, daccount_dbt acc "
            + " where rl.t_RegisterID = ? " 
            + " and rl.t_FIIDto = ? ";

    cmd.AddParam(RegisterID);
    cmd.AddParam(FIIDto);
  end;

  /*¢ë¡¥à¥¬ ¢á¥ áç¥â  â¥à¬¨­ «ì­ëå à §¤¥«®¢ ãª § ­­®£® áç¥â /à §¤¥«  */
  query = query + " and rl.t_Type = " + DP_REGLINETYPE_LACCOUNT
                + " and acc.t_Account = rl.t_LAccount "
                + " and acc.t_Chapter = " + 5 // CHAPT5
                + " and acc.t_Code_Currency = rl.t_FIIDfrom "
                + "    AND acc.t_DepoAcc IN   "
                + "   (    SELECT da.t_AutoKey   "
                + "         FROM ddepoacnt_dbt da   "
                + "           WHERE da.t_AutoKey NOT IN   "
                + "             (SELECT t_superior   "
                + "                  FROM ddepoacnt_dbt   "
                + "                  WHERE t_Superior != 0 AND t_Root = da.t_Root)   "
                + "             START WITH da.t_AutoKey = ? "  
                + "             CONNECT BY PRIOR da.t_Autokey = da.t_Superior) ";  

  cmd.AddParam(GlRepDataSet.LAccID);

  if( ((FIIDfrom != -1) or (FIIDto != -1)) and (DepoRoot > 0) )
    query = query + " and rl.t_HolderAccID in ( select ac.t_AutoKey from ddepoacnt_dbt ac where ac.t_Root = ?) ";
    cmd.AddParam(DepoRoot);
  end;

  Reglin = cmd.Execute(query);

  Reglin.moveNext();
  if( ValType(Reglin.cnt) != V_UNDEF )
    rest = Reglin.cnt;
  end;

  return rest;

end;

macro CreateRepSQLQuery(UseMortgagee:bool)

  var query = "";

  query =   " select crp.t_DocumentID, crp.t_Date, crp.t_Kind_Operation, crp.t_ConvForm, crp.t_ConvNumerator, crp.t_ConvDenominator, "
          + " crp.t_OperState, crp.t_OprXid, crp.t_OprDate, crp.t_OprTime, "
          + " crp.t_Currency, crp.t_DocKind, crp.t_Product, crp.t_InitiatorName, "
          + " spgr.t_Xld, spgr.t_AltXld, spgr.t_SignedDate, spgr.t_RegistrDate, "
          + " reg.t_Date as DateRst, reg.t_StoragePlace, reg.t_RegisterID, reg.t_Issuer, "
          + " accc.t_DepoAccID, "
          + " baseavoiriss.t_ISIN, baseavoiriss.t_LSIN, baseavoiriss.t_Issue, baseavoiriss.t_Tranche, "
          + " basefin.t_FI_Code, basefin.t_Name as FIName, avrk.t_Name as AvrName, "
          + " rsi_rsb_fiinstr.FI_GetNominalOnDate(basefin.t_FIID, reg.t_Date, 1) as FaceValue, basefin.t_FaceValueFI, basefin.t_Issued,"
          + " acnt.t_BriefCode, acnt.t_AutoKey LAccID, "
          + " pmfi.t_FIID, "
          + " rsb_fiinstr.FI_IsQualified(basefin.t_FIID, reg.t_Date) as isQualifiedBaseFI "

          + " from ddpcorpop_dbt crp, ddpregstr_dbt reg, dspground_dbt spgr, "
          + "      ddpacccrp_dbt accc, ddppmfi_dbt pmfi, " 
          + "      dfininstr_dbt basefin, davoiriss_dbt baseavoiriss, davrkinds_dbt avrk, "
          + "      ddepoacnt_dbt acnt "

          + " where reg.t_DocumentID = crp.t_DocumentID "
          + "   and spgr.t_SPgroundID = crp.t_SPgroundID "
          + "   and crp.t_DocKind IN ("+DP_DEPOPER_CONVERT+","+DP_DEPOPER_REPAY+","+DP_DEPOPER_BONEMISS+" )"
          + "   and accc.t_RegisterID = reg.t_RegisterID "
          + "   and pmfi.t_RegisterID = reg.t_RegisterID "
          + "   and basefin.t_FIID = pmfi.t_FIID "
          + "   and baseavoiriss.t_FIID = pmfi.t_FIID "
          + "   and avrk.t_FI_Kind = basefin.t_FI_Kind "
          + "   and avrk.t_AvoirKind = basefin.t_AvoirKind "
          + "   and acnt.t_AutoKey = accc.t_DepoAccID ";

  if( _DocumentID > 0)
    query = query + " and crp.t_DocumentID = " + _DocumentID;
  end;

  if( _NumDprt )
    query = query + " and crp.t_Department  = " + _NumDprt
                  + " and reg.t_Department  = " + _NumDprt
                  + " and spgr.t_Department = " + _NumDprt;
  end;  

  if( _GrDoc > 0 )
    query = query + " and spgr.t_Kind = " + _GrDoc;
  end;

  if( _BeginDate != date(0,0,0) )
    query = query + " and spgr.t_RegistrDate >= " + GetSQLDate(_BeginDate);
  end;
  if( _EndDate != date(0,0,0) )
    query = query + " and spgr.t_RegistrDate <= " + GetSQLDate(_EndDate);
  end;

  if( _XldBegin != "" )
    query = query + " and spgr.t_Xld >= '" + _XldBegin + "' ";
  end;
  if( _XldEnd != "" )
    query = query + " and spgr.t_Xld <= '" + _XldEnd + "' ";
  end;

  if( _OpKind )
    query = query + " and crp.t_Kind_Operation = " + _OpKind;
  end;

  if( _iGlOpForm ) 
    query = query + " and crp.t_ConvForm = " + _iGlOpForm;
  end;

  if( (_OpStatus > 0) and ( _OpStatus != 2) )
    query = query + " and crp.t_OperState = " + _OpStatus;
  end;

  if( _OpStatusBegin != date(0,0,0) )
    query = query + " and crp.t_OprDate >= " + GetSQLDate(_OpStatusBegin);
  end;
  if( _OpStatusEnd != date(0,0,0) )
    query = query + " and crp.t_OprDate <= " + GetSQLDate(_OpStatusEnd);
  end;

  if( _OjdNumBegin != "" )
    query = query + " and crp.t_OprXid >= '" + _OjdNumBegin + "' ";
  end;
  if( _OjdNumEnd != "" )
    query = query + " and crp.t_OprXid <= '" + _OjdNumEnd + "' ";
  end;

  if( _iStoragePlace != -1 )
    query = query + " and reg.t_StoragePlace = " + _iStoragePlace;
  end;

  if( _iStorAcc )
    //¥á«¨ § ¤ ­ áç¥â, â® ¨é¥¬ ¯® ¢á¥¬ ¯®¤à §¤¥« ¬, à á¯®«®¦¥­­ë¬ ­¨¦¥ 
    query = query + " and EXISTS( select acrp.t_DepoAccId from ddpacccrp_dbt acrp where acrp.t_DepoAccID in ( select acnt0.t_AutoKey from ddepoacnt_dbt acnt0 where acnt0.t_Root = "+_iStorAcc+" or acnt0.t_AutoKey = "+_iStorAcc+") and acrp.t_RegisterID = reg.t_RegisterID )";
  end;

  if( _iIssuer != -1 )
    query = query + " and EXISTS( select mfi.t_FIID from ddppmfi_dbt mfi where mfi.t_FIID in ( select fin.t_FIID from dfininstr_dbt fin where RSI_RSB_FIInstr.FI_GetIssuerOnDate( fin.t_FIID, reg.t_Date ) =  "+_iIssuer+") and mfi.t_RegisterID = reg.t_RegisterID )";
  end;
  if( _iFI > 0 )
    query = query + " and EXISTS( select mfi.t_FIID from ddppmfi_dbt mfi where mfi.t_FIID = "+_iFI+" and mfi.t_RegisterID = reg.t_RegisterID ) ";
  end;

  if( _iIssuerTo != -1 )
    query = query + " and EXISTS( select f.t_FIID from dfininstr_dbt f where f.t_FIID = crp.t_Currency and RSI_RSB_FIInstr.FI_GetIssuerOnDate( f.t_FIID, reg.t_Date ) =  "+_iIssuerTo+" ) ";
  end;

  if( _iFIIDto > 0 )
    query = query + " and crp.t_Currency = " + _iFIIDto;
  end;

  if( _iParty != -1 )
    query = query + " and (EXISTS( select 1 from ddpreglin_dbt lin1 where lin1.t_RegisterID = reg.t_registerID and lin1.t_HolderID = "+_iParty+") ";
    if(UseMortgagee == true)
      query = query + " OR EXISTS( select 1 "
                    + "              from ddpreglin_dbt lin1, ddpacap_dbt acap, ddpacapau_dbt acapau "
                    + "             where lin1.t_RegisterID = reg.t_registerID "
                    + "               and acap.t_ApNodeID = lin1.t_HolderAccID "
                    + "               and acap.t_APartyID = " + _iParty
                    + "               and acap.t_Role = " + DEPOACAPROLE_MORTGAGEE
                    + "               and acapau.t_APID = acap.t_APID "
                    + "               and acapau.t_AuNodeID = lin1.t_HolderPartID "
                    + "               and acapau.t_AuthKind = " + OBJTYPE_DEPOAUTHORITY_GETINFO
                    + "          ) ";
    end;

    query = query + " )"
  end;

  if( _iDepoAcc > 0 )
    query = query + " and EXISTS( select 1 from ddpreglin_dbt lin2 where lin2.t_RegisterID = reg.t_registerID and lin2.t_HolderAccID = "+_iDepoAcc+") ";
  end;

  return query;

end;

macro PrintSeparateLine(_tablewidth)
  AddStr();
  PrintCellSize("-----------------------------------------------------------------------------", _tablewidth);
end;

macro PrintRepHeader(_tablewidth)
  var width = 25;
  var SpgrStr = "", SpgrStrNext = "";

  AddStr();
  AddEmptyStr();
  AddEmptyStr();
  PrintCellSize("Žâ¯à ¢¨â¥«ì ®âç¥â ", width);
  PrintCellSize(GetPartyFullName({OurBank}, date(GlRepDataSet.OprDate)), _tablewidth-width);

  AddStr();
  PrintCellSize("®«ãç â¥«ì ®âç¥â ", width);
  PrintCellSize(GetRecipientName(), _tablewidth-width); 

  AddStr();
  PrintCellSize("®àãç¥­¨¥", width);
  PrintCellSize("ü " + IIF( GlRepDataSet.AltXld, GlRepDataSet.AltXld, "-") + " ®â " + string(date(GlRepDataSet.SignedDate)) + ", ‚å.ü " + GlRepDataSet.Xld + ", ¤ â  ¯à¨¥¬  " + string(date(GlRepDataSet.RegistrDate)), _tablewidth-width);

  AddStr();
  PrintCellSize("ˆ­¨æ¨ â®à", width);
  PrintCellSize(string(GlRepDataSet.InitiatorName), _tablewidth-width);

  AddStr();
  PrintCellSize("„¥¯®§¨â à­ ï ®¯¥à æ¨ï", width);
  PrintCellSize("ŠŽ-" + GlRepDataSet.Kind_Operation + ", " + GetOperationName(GlRepDataSet.Kind_Operation) + IIF( (GlRepDataSet.Kind_Operation == DP_GLOBOPOPERATION_CONVERT), " ( ä®à¬  - "+string(DL_GetNameAlg( ALG_FORMCONVERT, GlRepDataSet.ConvForm ))+ ", ª®íää¨æ¨¥­â - " + string(GlRepDataSet.ConvNumerator)+"/"+string(GlRepDataSet.ConvDenominator) + " )", "") , _tablewidth-width);

  AddStr();
  PrintCellSize( "   ®á­®¢ ­¨¥", width);

  SpgrStr     = GetFirstSpgrData();
  SpgrStrNext = GetNextSpgrData();
  PrintCell( IIF(SpgrStrNext, SpgrStr+",", SpgrStr) );
  while( (SpgrStrNext != "" ))
    SpgrStr = SpgrStrNext;
    SpgrStrNext=GetNextSpgrData();
    AddStr();
    PrintCellSize( " ", width);
    PrintCellSize(IIF(SpgrStrNext, SpgrStr+",", SpgrStr), _tablewidth-width);
  end;

  AddStr();
  PrintCellSize( " ", width);
  PrintCellSize(GetLLVALUES(OBJTYPE_TRANSACTION_CONTENT,GlRepDataSet.Product), _tablewidth-width);
end;

macro PrintRepFooter(DepoAcc, _tablewidth)
  var width = 35;
  var RejNote = "";
  var Data, query, cmd; 
  var IsRej = false;

  IsRej = ((GlRepDataSet.OperState) or (GetStateReglinAcc(GlRepDataSet.RegisterID, DepoAcc) == DPREGLINSTATE_REJECT) );
  
  AddStr();
  AddEmptyStr();
  PrintCellSize("Ž¡à ¡®âª  ¯®àãç¥­¨ï", width);
  PrintCellSize(string(DL_GetNameAlg(ALG_DEPO_OPERSTATEPAST, IIF( IsRej, DP_INVSTATUSORDER_REJECT, GlRepDataSet.OperState) )), _tablewidth-width);
  
  AddStr();
  PrintCellSize(IIF(IsRej, "    ¯à¨ç¨­  ®âª § ", "    § ¯¨áì ¢ ¦ãà­ «¥ ®¯¥à æ¨©"), width);
  if( IsRej )
    RejNote = GetRejectNote(GlRepDataSet.DocumentID);
    if( RejNote == "" )
      //­ ©â¨ ¬ ªá¨¬ «ì­ë© ReglineID ¤«ï ¤ ­­®£® áç¥â 
      query =   " select max(lin.t_ReglineID) as MaxReglin from ddpreglin_dbt lin, ddepoacnt_dbt acnt " 
              + "  where lin.t_RegisterID = ? "
              + "    and lin.t_State = " + DPREGLINSTATE_REJECT
              + "    and acnt.t_AutoKey = lin.t_HolderAccID "
              + "    and acnt.t_Root    = ? ";

      cmd = DL_RSDCommand(query);
      cmd.AddParam(GlRepDataSet.RegisterID);
      cmd.AddParam(DepoAcc);
      
      Data = cmd.Execute();         
      if( Data.moveNext() )
        RejNote = GetRejectNoteReglin(Data.MaxReglin);
      end;
    end;
  end;
  PrintCellSize(IIF(IsRej, RejNote, string(GlRepDataSet.OprXid) ) , _tablewidth-width);

  AddStr();
  PrintCellSize("    ¤ â , ¢à¥¬ï", width);
  PrintCellSize(string(date(GlRepDataSet.OprDate)) + ", "+ string(time(GlRepDataSet.OprTime)), _tablewidth-width);

  AddStr();
  PrintCellSize("    ¨á¯®«­¨â¥«ì", width);
  PrintCellSize(DP_FooterExecuterSign({oper}), _tablewidth-width);

end;

macro PrintRstDate(_tablewidth)
  var width = 35;

  AddStr();
  AddEmptyStr();
  PrintCellSize("„ â  á¡®à  à¥¥áâà ", width);
  PrintCellSize(string(date(GlRepDataSet.DateRst)), _tablewidth-width);

end;

macro PrintStoragePlace(_tablewidth)
  var width = 35;
  AddStr();
  AddEmptyStr();
  PrintCellSize("Œ¥áâ® åà ­¥­¨ï ¨/¨«¨ ãç¥â  æ¥­­ëå ¡ã¬ £", _tablewidth-width);

  AddStr();
  PrintCellSize( "    „¥¯®§¨â à¨©", width);
  PrintCellSize( GetPartyFullName(GlRepDataSet.StoragePlace, date(GlRepDataSet.OprDate)) , _tablewidth-width);

  AddStr();
  PrintCellSize( "    áç¥â ¤¥¯®", width);
  PrintCellSize( GlRepDataSet.BriefCode , _tablewidth-width);

end;

macro PrintBaseAvoir(DepoRoot, _tablewidth)
  var fin = TBFile("fininstr");
  var width = 35;
  var cntFIID = 0;
  
  fin.rec.FIID = GlRepDataSet.FIID;
  if( not GetEQ(fin) )
    AddStr();
    PrintCellSize( "¥ ­ ©¤¥­  æ/¡ á ¨¤¥­â¨ä¨ª â®à®¬ = " + GlRepDataSet.FIID, _tablewidth);
    return;
  end;
  
  AddStr();
  PrintCellSize( "    í¬¨â¥­â", width);
  PrintCellSize( GetPartyFullName(GlRepDataSet.Issuer, date(GlRepDataSet.OprDate)) , _tablewidth-width);

  AddStr();
  PrintCellSize( "    ª®¤ ¨ ­ ¨¬¥­®¢ ­¨¥", width);
  PrintCellSize( string(GlRepDataSet.FI_Code + " (" + GlRepDataSet.FIName + ")" + IIF(GlRepDataSet.isQualifiedBaseFI, "", " (Š–)"))   , _tablewidth-width);

  AddStr();
  PrintCellSize("    ü £®á.à¥£¨áâà æ¨¨", width);
  PrintCellSize( GlRepDataSet.LSIN + IIF( GlRepDataSet.ISIN != "", " ("+GlRepDataSet.ISIN+") ", "") , _tablewidth-width);

  AddStr();
  PrintCellSize("    ¢¨¤", width);
  PrintCellSize( GlRepDataSet.AvrName , _tablewidth-width);

  AddStr();
  PrintCellSize("    ü ¢ë¯ãáª /âà ­è ", width);
  PrintCellSize( string(GlRepDataSet.Issue+"/"+IIF(GlRepDataSet.Tranche != "", GlRepDataSet.Tranche, "-") ) , _tablewidth-width);

  AddStr();
  PrintCellSize("    ­®¬¨­ «", width);
  PrintCellSize( string(IIF( _is_ap, string(GlRepDataSet.FaceValue:a), GlRepDataSet.FaceValue)+ " (" +NumToStr(GlRepDataSet.FaceValue) + ") ") , _tablewidth-width);

  AddStr();
  PrintCellSize("    ¢ «îâ ", width);
  PrintCellSize( GetFaceValueFiStr(GlRepDataSet.FaceValueFI) ,_tablewidth-width);

  AddStr();
  PrintCellSize("    ¤ â  ¢ë¯ãáª ", width);
  PrintCellSize( string(date(GlRepDataSet.Issued)), _tablewidth-width);

  cntFIID = GetSumREGLINrest(GlRepDataSet.RegisterID, GlRepDataSet.FIID, -1, DepoRoot);
  AddStr();
  PrintCellSize("    ª®«¨ç¥áâ¢®", width);
  PrintCellSize( string(—¨á«®C‡ ¤ ­­®©’®ç­®áâìî(cntFIID, DP_GetPrecision(cntFIID, fin.rec.SumPrecision), IIF(_is_ap, "a", ""))
    + " (" +NumToStr(cntFIID, null, null, null, null, DP_GetPrecision(cntFIID, fin.rec.SumPrecision)) + ") èâ."), _tablewidth-width);

end;

macro PrintCalcAvoir(DepoRoot, _tablewidth)
  var width = 35;
  var fin = TBFile("fininstr");
  var avriss = TBFile("avoiriss");
  file avrk("avrkinds");
  var cntFIID = 0;
  var FaceValue = $0;

  if( GlRepDataSet.Currency == -1 ) return end;

  fin.rec.FIID = GlRepDataSet.Currency;
  avriss.rec.FIID = GlRepDataSet.Currency;
  if( (not GetEQ(fin)) or (not GetEQ(avriss)) )
    AddStr();
    PrintCellSize( "¥ ­ ©¤¥­  æ/¡ á ¨¤¥­â¨ä¨ª â®à®¬ = "+GlRepDataSet.Currency , _tablewidth);
    return;
  end;

  avrk.FI_Kind = fin.rec.FI_Kind;
  avrk.AvoirKind = fin.rec.AvoirKind;
  if( not GetEQ(avrk) )
    AddStr();
    PrintCellSize( "¥¨§¢¥áâ­ë© ¢¨¤ æ/¡ á ¨¤¥­â¨ä¨ª â®à®¬ = "+GlRepDataSet.Currency , _tablewidth);
    return;
  end;

  FaceValue = GetFaceValue(fin.rec.FIID, date(GlRepDataSet.DateRst));

  AddStr();
  PrintCellSize( "    í¬¨â¥­â", width);
  PrintCellSize( GetPartyFullName( FI_GetIssuerOnDate(fin, date(GlRepDataSet.DateRst) ), date(GlRepDataSet.OprDate)) , _tablewidth-width);

  AddStr();
  PrintCellSize( "    ª®¤ ¨ ­ ¨¬¥­®¢ ­¨¥", width);
  PrintCellSize( string(fin.rec.FI_Code + " (" + fin.rec.Name + ")" + IIF(QualifiedSecur(avriss, fin, date(GlRepDataSet.Date)), "", " (Š–)")) , _tablewidth-width);

  AddStr();
  PrintCellSize("    ü £®á.à¥£¨áâà æ¨¨", width);
  PrintCellSize( avriss.rec.LSIN + IIF( avriss.rec.ISIN != "", " ("+avriss.rec.ISIN+") ", "") , _tablewidth-width);

  AddStr();
  PrintCellSize("    ¢¨¤", width);
  PrintCellSize( avrk.Name, _tablewidth-width );

  AddStr();
  PrintCellSize("    ü ¢ë¯ãáª /âà ­è ", width);
  PrintCellSize( string(avriss.rec.Issue+"/"+IIF(avriss.rec.Tranche != "", avriss.rec.Tranche, "-") ) , _tablewidth-width);

  AddStr();
  PrintCellSize("    ­®¬¨­ «", width);
  PrintCellSize( string(IIF( _is_ap, string(FaceValue:a), FaceValue )+ " (" +NumToStr(FaceValue) + ") ") , _tablewidth-width);

  AddStr();
  PrintCellSize("    ¢ «îâ ", width);
  PrintCellSize( GetFaceValueFiStr(fin.rec.FaceValueFI) , _tablewidth-width);

  AddStr();
  PrintCellSize("    ¤ â  ¢ë¯ãáª ", width);
  PrintCellSize( string(date(fin.rec.Issued)), _tablewidth-width);

  cntFIID = GetSumREGLINrest(GlRepDataSet.RegisterID, -1, GlRepDataSet.Currency, DepoRoot);
  AddStr();
  PrintCellSize("    ª®«¨ç¥áâ¢®", width);
  PrintCellSize( string(—¨á«®C‡ ¤ ­­®©’®ç­®áâìî(cntFIID, DP_GetPrecision(cntFIID, fin.rec.SumPrecision), IIF(_is_ap, "a", ""))
    + " (" +NumToStr(cntFIID, null, null, null, null, DP_GetPrecision(cntFIID, fin.rec.SumPrecision)) + ") èâ."), _tablewidth-width);

end;

macro PrintBaseAvoirTable()
  file fin("fininstr");
  var SumPrecision = 0;
  var cntFIID = 0;

  fin.FIID = GlRepDataSet.FIID;
  if( GetEQ(fin) )
    SumPrecision = fin.SumPrecision;
  end;

  cntFIID = GetSumREGLINrest(GlRepDataSet.RegisterID, GlRepDataSet.FIID, -1, 0);
  AddStr();
  PrintCellTable(string(  GlRepDataSet.FI_Code + " (" + GlRepDataSet.FIName + "), "
                        + GlRepDataSet.LSIN + IIF( GlRepDataSet.ISIN != "", " ("+GlRepDataSet.ISIN+"), ", "")
                        + GlRepDataSet.AvrName + ", " + GlRepDataSet.Issue ) );
  DP_AddPrintCell( GlRep, cntFIID, 0, DP_GetPrecision(cntFIID, SumPrecision), "r:" + FontStyleTitel, _is_ap );

  AddStr();
  PrintCellTable("ˆ’ŽƒŽ");
  DP_AddPrintCell( GlRep, cntFIID, 0, DP_GetPrecision(cntFIID, SumPrecision), "r:" + FontStyleTitel, _is_ap );

end;

private macro PrintReport()

  PrintSeparateLine(tablewidth);
  PrintRstDate(tablewidth);
  PrintStoragePlace(tablewidth);

  AddStr();
  AddEmptyStr();

  if( GlRepDataSet.Kind_Operation == DP_GLOBOPOPERATION_CONVERT )   //ª®­¢¥àâ æ¨ï

    if( (GlRepDataSet.ConvForm == CONVFORM_CONVERT) or 
        (GlRepDataSet.ConvForm == CONVFORM_CUTTING) or
        (GlRepDataSet.ConvForm == CONVFORM_CONSOL) )
      PrintCellSize("–¥­­ë¥ ¡ã¬ £¨, ª®­¢¥àâ¨àã¥¬®£® ¢ë¯ãáª ", tablewidth);
      PrintBaseAvoir(0, tablewidth);
      AddStr();
      AddEmptyStr();
      PrintCellSize("‚ë¯ãáª, ¢ ª®â®àë© ª®­¢¥àâ¨àãîâáï æ¥­­ë¥ ¡ã¬ £¨", tablewidth);
      PrintCalcAvoir(0, tablewidth);
    elif( GlRepDataSet.ConvForm == CONVFORM_ANUL )
      PrintCellSize("–¥­­ë¥ ¡ã¬ £¨, à §¬¥é ¥¬®£® ¢ë¯ãáª  ", tablewidth);
      PrintBaseAvoir(0, tablewidth);
      AddStr();
      AddEmptyStr();
      PrintCellSize("–¥­­ë¥ ¡ã¬ £¨ ¢ë¯ãáª , ¯® ®â­®è¥­¨î ª ª®â®à®¬ã à §¬¥é ¥¬ë© ï¢«ï¥âáï ¤®¯®«­¨â¥«ì­ë¬", tablewidth);
      PrintCalcAvoir(0, tablewidth);
    elif( GlRepDataSet.ConvForm == CONVFORM_SUMM )
      PrintCellSize("–¥­­ë¥ ¡ã¬ £¨, ®á­®¢­®£® ¢ë¯ãáª ", tablewidth);
      PrintCalcAvoir(0, tablewidth);
      AddStr();
      AddEmptyStr();
      PrintCellSize("–¥­­ë¥ ¡ã¬ £¨, à ­¥¥ à §¬¥é¥­­ëå ¢ë¯ãáª®¢", tablewidth);
      PrintBaseAvoirTable();
    end;

  elif( GlRepDataSet.Kind_Operation == DP_GLOBOPOPERATION_REPAY )     //¯®£ è¥­¨¥
    PrintCellSize("®£ è ¥¬ë¥ æ¥­­ë¥ ¡ã¬ £¨", tablewidth);
    PrintBaseAvoir(0, tablewidth);
  elif( GlRepDataSet.Kind_Operation == DP_GLOBOPOPERATION_BONEMISS )  //¡®­ãá­ ï í¬¨áá¨ï
    PrintCellSize("–¥­­ë¥ ¡ã¬ £¨, ¯® ª®â®àë¬ ­ ç¨á«ïîâáï ¤®å®¤ë", tablewidth);
    PrintBaseAvoir(0, tablewidth);
    AddStr();
    AddEmptyStr();
    PrintCellSize("–¥­­ë¥ ¡ã¬ £¨ ¢ë¯ãáª , ­ ç¨á«¥­­ë¥ ¢ ª ç¥áâ¢¥ ¤®å®¤ ", tablewidth);
    PrintCalcAvoir(0, tablewidth);
  end;


  PrintSeparateLine(tablewidth);

end;

//¯à®â®ª®« ®âª § ­­ëå áç¥â®¢
private macro PrintRejectedAcc()

  var TableHeader = "";
  var query, DataRej;
  var Data;
  var CountRej = 1;
  var Col1 = 0, Col2 = 0, Col3 = 0, Col4 = 0, Col5 = 0;
  var SummRest = 0;
  var Format;
  var MaxSumPrecision = 0;

  if( GlRepDataSet.Kind_Operation == DP_GLOBOPOPERATION_CONVERT )
    TableHeader = HeadTableRejAccConv;
  elif( GlRepDataSet.Kind_Operation == DP_GLOBOPOPERATION_REPAY )
    TableHeader = HeadTableRejAccRepay;
  elif( GlRepDataSet.Kind_Operation == DP_GLOBOPOPERATION_BONEMISS )
    TableHeader = HeadTableRejAccBon;
  end;


  //à §¬¥àë ª®«®­®ª
  if( TableHeader == HeadTableRejAccConv )
    Col1 = 9;
    Col2 = 20;
    Col3 = 28;
    Col4 = 31;
    Col5 = 26;
  elif( TableHeader == HeadTableRejAccRepay )
    Col1 = 9;
    Col2 = 20;
    Col3 = 28;
    Col4 = 31;
    Col5 = 26; 
  elif( TableHeader == HeadTableRejAccBon )
    Col1 = 9;
    Col2 = 20;
    Col3 = 28;
    Col4 = 35;
    Col5 = 26;
  end;


  query =   " select distinct acnt.t_Root, acnt.t_BriefCode, acnt.t_Owner from ddepoacnt_dbt acnt, ddpreglin_dbt lin"
          + " where acnt.t_AutoKey = lin.t_HolderAccID "
          + "   and lin.t_RegisterID = " + GlRepDataSet.RegisterID
          + "   and lin.t_State = " + DPREGLINSTATE_REJECT;

  DataRej = TRsbDataSet(query);
  while( DataRej.moveNext() )
    if( CountRej == 1 )

      AddStr();
      AddEmptyStr();
      PrintCellSize("à®â®ª®« § à¥£¨áâà¨à®¢ ­­ëå ®âª §®¢ ¯® áç¥â ¬ ¤¥¯® ¢ á¯¨áª¥-à¥¥áâà¥", tablewidth);
      AddStr();
      GlRep.AutoScan("[\n"+TableHeader+"]" );
      Format = "ex_B(rlb)";
    end;

    
    PrintCellTableSizeCenter(string(CountRej), Col1, Format );
    PrintCellTableSize(string(DataRej.BriefCode), Col2, Format );
    PrintCellTableSize(string(GetPartyFullName(DataRej.Owner, date(GlRepDataSet.OprDate))), Col3, Format );

    //¯®áç¨â âì ª®«-¢® æ/¡                        
    query =   " select sum(lin.t_HRest) as Rest, max(nvl(fiin.t_SumPrecision," + AVOIRISS_SUM_PRECISION + ")) as SumPrecision "
            + "   from ddpreglin_dbt lin, ddepoacnt_dbt acnt, dfininstr_dbt fiin " 
            + "  where lin.t_RegisterID = " + GlRepDataSet.RegisterID
            + "    and lin.t_State = " + DPREGLINSTATE_REJECT
            + "    and acnt.t_AutoKey = lin.t_HolderAccID "
            + "    and acnt.t_Root    = " + DataRej.Root
            + "    and lin.t_FIIDfrom = fiin.t_FIID(+) ";

    Data = TRsbDataSet(query);         
    if( Data.moveNext() )
      PrintCellTableSizeRight(string(—¨á«®C‡ ¤ ­­®©’®ç­®áâìî(double(Data.Rest), DP_GetPrecision(Data.Rest, Data.SumPrecision), IIF(_is_ap, "a", ""))), Col4, Format );
      SummRest = SummRest + Data.Rest;
      if( Data.SumPrecision > MaxSumPrecision )
        MaxSumPrecision = Data.SumPrecision;
      end;
    else
      PrintCellTableSizeRight(string(0), Col4, Format );
    end;

    //­ ©â¨ ¬ ªá¨¬ «ì­ë© ReglineID ¤«ï ¤ ­­®£® áç¥â 
    query =   " select max(lin.t_ReglineID) as MaxReglin from ddpreglin_dbt lin, ddepoacnt_dbt acnt " 
            + "  where lin.t_RegisterID = " + GlRepDataSet.RegisterID
            + "    and lin.t_State = " + DPREGLINSTATE_REJECT
            + "    and acnt.t_AutoKey = lin.t_HolderAccID "
            + "    and acnt.t_Root    = " + DataRej.Root;

    Data = TRsbDataSet(query);         
    if( Data.moveNext() )
      PrintCellTableSize(string(GetRejectNoteReglin( Data.MaxReglin )), Col5, Format );
    else
      PrintCellTableSize(string("-"), Col5, Format );
    end;

    AddStr();
    Format = "";
    CountRej = CountRej + 1;
  end;

  //ˆ’ŽƒŽ
  if( CountRej > 1 )
    PrintCellTableSize(string(""), Col1 );
    PrintCellTableSize(string(""), Col2 );
    PrintCellTableSize(string("ˆ’ŽƒŽ"), Col3 );
    PrintCellTableSizeRight(string(—¨á«®C‡ ¤ ­­®©’®ç­®áâìî(double(SummRest), DP_GetPrecision(SummRest, MaxSumPrecision), IIF(_is_ap, "a", ""))), Col4 );
    PrintCellTableSize(string(""), Col5 );
    AddStr();
  end;

  AddEmptyStr();
end;

private macro CreateEmptyRep()
          
  DP_StdHeaderLO_Ex( GlRep, FontStyleTitel, HeaderStr, _LOAuotoKey, 0, false, null, null, tablewidth, _RepNum, _RepDate );
  AddEmptyStr();
  PrintCellSize( "¥â ¤ ­­ëå, ã¤®¢«¥â¢®àïîé¨å ¯ à ¬¥âà ¬ ®âç¥â .", tablewidth);
  AddEmptyStr();
  DP_StdFooter_Ex(GlRep, FontStyleTitel, NULL, NULL, tablewidth);
  return 1;
end;

private macro CreateRepExt(LOAuotoKey)
  var sQuery = "";
  var count = 0;
  var stat = 0;
  var i = 0;
  var CountRep = 0;
  var PrintSubNum = false;
  var Progress = CProgressBar;

  DP_BeginProtocol();  //­ ç âì ¯à®â®ª®«¨à®¢ ­¨¥ - ¯®¤¬¥­  MsgBox

  if( (_XldBegin != _XldEnd) or (_XldBegin == "") or (_XldEnd == "") )
    PrintSubNum = true;
  end;

  sQuery = CreateRepSQLQuery(false);
  GlRepDataSet = TRsbDataSet( sQuery, RSDVAL_CLIENT, RSDVAL_STATIC);
  GlRepDataSet.MoveLast();  //­ã¦­®, çâ®¡ë ®¯à¥¤¥«¨âì à §¬¥à ª¥è 
  count = GlRepDataSet.GetRecCount();//à ¡®â ¥â â®«ìª® á RSDVAL_STATIC!!!
  stat = GlRepDataSet.MoveFirst();
  if( (count > 0) and (stat) )
    Progress.Init( count, "ˆ¤ñâ ä®à¬¨à®¢ ­¨¥ ®âçñâ ...", "Žâç¥â ®¡ ¨á¯®«­¥­¨¨ £«®¡ «ì­®© ®¯¥à æ¨¨" );
               
    while( stat )
      i = Progress.Use();

      if( stat )
        AddEmptyStr();
        DP_StdHeaderLO_Ex( GlRep, FontStyleTitel, IIF( GlRepDataSet.OperState, HeadreStrReject, HeaderStr), LOAuotoKey, CountRep = CountRep + 1, PrintSubNum, null, null, tablewidth, _RepNum, _RepDate );

        PrintRepHeader(tablewidth);
        PrintReport();
        PrintRepFooter(0, tablewidth);
        //¯à®â®ª®« ®âª § ­­ëå áç¥â®¢
        PrintRejectedAcc();

        DP_StdFooter_Ex(GlRep, FontStyleTitel, NULL, NULL, tablewidth);
        AddEmptyStr();

        stat = GlRepDataSet.moveNext();
      end;
    end;                           
  
    Progress.Remove();
  end;

  if( (count==0) or ( CountRep == 0) )
    count = 0;
  end;

  DP_AddProtocol(GlRep, "protocol");  //¤®¡ ¢¨¬ ¯à®â®ª®« ª ã¦¥ áä®à¬¨à®¢ ­­®¬ã ®âç¥âã
  DP_EndProtocol();                 //§ ª®­ç¨âì ¯à®â®ª®«¨à®¢ ­¨¥

  return count;
end;

private macro CreateReport(  NumDprt         :integer,  GrDoc           :integer,
                     BeginDate       :date,     EndDate         :date,
                     XldBegin        :string,   XldEnd          :string,
                     OpKind          :integer,  iGlOpForm       :integer,
                     OpStatus        :integer,  OpStatusBegin   :date,
                     OpStatusEnd     :date,     OjdNumBegin     :string,
                     OjdNumEnd       :string,   iStoragePlace   :integer,
                     iStorAcc        :integer,  iIssuer         :integer,
                     iFI             :integer,  iIssuerTo       :integer,
                     iFIIDto         :integer,  LOAuotoKey      :integer,
                     ToExcel         :bool,     is_ap           :bool
)
  var count = 0;

  _iParty  = -1; 
  _iDepoAcc = 0;

  _NumDprt        =   NumDprt;     _GrDoc          =   GrDoc;        
  _BeginDate      =   BeginDate;   _EndDate        =   EndDate;      
  _XldBegin       =   XldBegin;    _XldEnd         =   XldEnd;       
  _OpKind         =   OpKind;      _iGlOpForm      =   iGlOpForm;    
  _OpStatus       =   OpStatus;    _OpStatusBegin  =   OpStatusBegin;
  _OpStatusEnd    =   OpStatusEnd; _OjdNumBegin    =   OjdNumBegin;  
  _OjdNumEnd      =   OjdNumEnd;   _iStoragePlace  =   iStoragePlace;
  _iStorAcc       =   iStorAcc;    _iIssuer        =   iIssuer;      
  _iFI            =   iFI;         _iIssuerTo      =   iIssuerTo;    
  _iFIIDto        =   iFIIDto;     _LOAuotoKey     =   LOAuotoKey;   
  _ToExcel        =   ToExcel;      _is_ap         =   is_ap;        
  
  _DocumentID = 0;
  _GlRepRecipientID = -1;
  Dl_CallInsertStat( IIF( ToExcel, DL_OUTREPORT_EXCEL, DL_OUTREPORT_STD ) );
  GlRep = CMakeReport();

  count = CreateRepExt(LOAuotoKey);

  return DP_StdReportControl( _LOAuotoKey, count, @CreateEmptyRep, 0, ToExcel, GlRep );
  
end;
macro DP_GlobRepByDoc(DocumentID, Recipient, RepNum, RepDate, _Rep:@variant)
  
  if((ValType(_Rep) != V_UNDEF) and (_Rep != null))
     GlRep = _Rep;
  else
     GlRep = CMakeReport();
  end;

  _iParty  = -1; 
  _iDepoAcc = 0;

  _NumDprt        =   {operdprt};  _GrDoc          =   0;        
  _BeginDate      =   date(0,0,0); _EndDate        =   date(0,0,0);      
  _XldBegin       =   "";          _XldEnd         =   "";       
  _OpKind         =   0;           _iGlOpForm      =   0;    
  _OpStatus       =   -1;          _OpStatusBegin  =   date(0,0,0);
  _OpStatusEnd    =   date(0,0,0); _OjdNumBegin    =   "";  
  _OjdNumEnd      =   "";          _iStoragePlace  =   -1;
  _iStorAcc       =   0;           _iIssuer        =   -1;      
  _iFI            =   -1;          _iIssuerTo      =   -1;    
  _iFIIDto        =   -1;          _LOAuotoKey     =   0;   
  _ToExcel        =   false;       _is_ap          =   true;        

  _DocumentID = DocumentID;
  _GlRepRecipientID = Recipient;
  _RepNum     = RepNum;
  _RepDate    = RepDate;
   
  CreateRepExt();

  _Rep = GlRep;
end;
