/*
$Name: dpptyarh.mac
$Module: Депозитарий
$Description: Архивные сведения о субъекте
*/

import FIInter, CurrInter, CTInter, dprepsec, DPInter, "adress.mac", cb_sql;

const физическое_лицо = 2;
const юридическое_лицо= 1;

const MAXINT = 2147483647;

/* Административные операции.*/ 
/* Алгоритмы с названиями полей анкет. */
CONST  ALG_DEPO_DACNT      = 3220; /* счет депо */
CONST  ALG_DEPO_DPART      = 3221; /* раздел    */
CONST  ALG_DEPO_ACC        = 3222; /* лицевой   */
CONST  ALG_DEPO_CLNT       = 3223; /* депонент  */
CONST  ALG_DEPO_AVOIR      = 3224; /* ц\б       */

private var cParty = NULL;

file NameAlg("namealg");

var HeadTable = "┌─────────────────────┬──────────┬─────────────┬────────────────────────────────────────────┬──────────┐\n"+
                "│Тип                  │Серия     │Номер        │Выдан                                       │Дата      │\n"+
                "├─────────────────────┼──────────┼─────────────┼────────────────────────────────────────────┼──────────┤";
                
var tablewidth = Index(HeadTable, "\n");
var Rep = CMakeReport(HeadTable);
const RepFontStyleTitel =  "ex_FS(b)";

/*Внутренний интерфейс в Namealg.dbt*/
macro __NameAlg(Type, Number)
  NameAlg.iTypeAlg = Type;
  NameAlg.iNumberAlg = Number;
  if( GetEQ(NameAlg) )
    return NameAlg.szNameAlg;
  end;
  return " Не определен ";
end;

/*Дата последнего изменения статуса*/
macro LastStChangDate(depoadmo)
   
  var admo = TBFile("depoadmo");
  var query =    "  t_AdmoprID in  "
                 "     ( select MAX(t_AdmoprID) from ddepoadmo_dbt where "
                 "     t_Item      =  " + depoadmo.rec.Item
               + " and t_partyID   =  " + depoadmo.rec.PartyID
               + " and t_DepoAcc   =  " + depoadmo.rec.DepoAcc
               + " and t_DepoPart  =  " + depoadmo.rec.DepoPart
               + " and t_FIID      =  " + depoadmo.rec.FIID;

  if(depoadmo.rec.Account != "")
    query = query + " and t_Account = '" + depoadmo.rec.Account + "'";
  else
    query = query + " and t_Account = CHR(0)";
      end;

    query = query + " and t_OperDate  <  " + GetSQLDate(depoadmo.rec.OperDate)
                  + " and t_OperKind !=  " + SPAO_CON_MODIFYING    
                  + "     ) ";
   
   admo.AddFilter(query); 
   admo.next();

   if( nrecords(admo) <= 0 )
     return depoadmo.rec.OperDate; /* Что-то не сработало */
   else
     return admo.rec.OperDate;
   end;
  
   return depoadmo.rec.OperDate; /* Что-то не сработало */
end;

/*Архивная анкета*/
macro PrintForm(depoadmo, RepDate, AdmopCarryDate, FisLitso)
   file Ground(spground);
   Ground.SPgroundID = depoadmo.rec.Ground;
   if(not GetEQ(Ground))
      clearrecord(Ground);
   end;

   DP_AddPrintCell( Rep,  "                зарегистрирована в депозитарии ", 47, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR );
   DP_AddPrintCell( Rep,  RepDate, 10, 0, "l:f:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   Rep.AddEmptyStr();
   DP_AddPrintCell( Rep,  "                    по состоянию на закрытие ", 46, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR );
   DP_AddPrintCell( Rep,  AdmopCarryDate, 10, 0, "l:f:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   DP_AddPrintCell( Rep,  "(по факту исполнения поручения на адм. операцию вх.№ ", 53, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR );
   DP_AddPrintCell( Rep,  Ground.Xld+" от "+DateToStr(Ground.RegistrDate, true)+" исх.№ "+Ground.AltXld+" от "+DateToStr(Ground.SignedDate, true)+")", tablewidth-53, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   Rep.AddEmptyStr();
   DP_AddPrintCell( Rep,  " Текущий статус ", 17, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR );
   DP_AddPrintCell( Rep,  cParty.Status()+" установлен "+DateToStr(LastStChangDate(depoadmo), true), tablewidth-17, 0, "l:w:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
/*По содержимому*/
   Rep.AddEmptyStr();
   Rep.AddEmptyStr();
   DP_AddPrintCell( Rep,  "                      Наименование: ", 37, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR );
   DP_AddPrintCell( Rep,  cParty.Name(), tablewidth-37, 0, "l:w:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
if(FisLitso)
   DP_AddPrintCell( Rep,  "пол: " + cParty.IsMale(), 50, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   DP_AddPrintCell( Rep,  "дата и место рождения: ", 23, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR );
   DP_AddPrintCell( Rep,  cParty.Born(), 10, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR );
   DP_AddPrintCell( Rep,  "  " + cParty.BirsPlase(), tablewidth-33, 0, "l:w:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
end;
   DP_AddPrintCell( Rep,  "Юрисдикция: " + cParty.NRCountry(), tablewidth, 0, "l:w:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   DP_AddPrintCell( Rep,  "ИНН" + cParty.CodeINN(), tablewidth, 0, "l:w:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   Rep.AddEmptyStr();
   DP_AddPrintCell( Rep,  " Адрес регистрации: " + cParty.Region() + " " + cParty.Place()+" "+   
                     cParty.Street()+" "+  cParty.House()+" "+
                     cParty.NumCorps()+" "+cParty.Flat(),
                    tablewidth, 0, "l:w:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   DP_AddPrintCell( Rep,  "Почтовый адрес: " + cParty.PostIndex() +" "+ cParty.Adress(), tablewidth, 0, "l:w:" + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
if(FisLitso)
   Rep.AddEmptyStr();
   DP_AddPrintCell( Rep,  " Сведения о документе:",  tablewidth, 0, "l:w:"  + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   DP_AddPrintCell( Rep,  cParty.PaperKindName(), 0, 0, "l:w:" + RepFontStyleTitel);
   DP_AddPrintCell( Rep,  cParty.PaperSeries(), 0, 0, "l:w:" + RepFontStyleTitel);
   DP_AddPrintCell( Rep,  cParty.PaperNumber(), 0, 0, "l:w:" + RepFontStyleTitel);
   DP_AddPrintCell( Rep,  cParty.PaperIssuerName(), 0, 0, "l:w:" + RepFontStyleTitel);
   DP_AddPrintCell( Rep,  date(cParty.PaperIssuedDate()), 0, 0, "l:f:" + RepFontStyleTitel);
   Rep.AddStr();
end;
   Rep.AddEmptyStr();
   DP_AddPrintCell( Rep,  " Способы связи:",  tablewidth, 0, "l:w:"  + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   DP_AddPrintCell( Rep,  "тел.: " + cParty.PhoneNumber()+" "+cParty.PhoneNumber2(), tablewidth, 0, "l:w:"  + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   DP_AddPrintCell( Rep,  "факс: " + cParty.Fax(),  tablewidth, 0, "l:w:"  + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   DP_AddPrintCell( Rep,  "email:" + cParty.E_Mail(),  tablewidth, 0, "l:w:"  + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   Rep.AddEmptyStr();
   DP_AddPrintCell( Rep,  " Ответственные лица:",  tablewidth, 0, "l:w:"  + RepFontStyleTitel, false, REP_ELEM_STR );
   Rep.AddStr();
   var i = 1;
   while(cParty.GetNextPerson())
     DP_AddPrintCell( Rep,  cParty.PersonName(),  tablewidth, 0, "l:w:"  + RepFontStyleTitel, false, REP_ELEM_STR );
     Rep.AddStr();
     i = i + 1;
   end;
   Rep.AddEmptyStr();
   Rep.AddEmptyStr();
end;

macro Arch_party_form( iDepart:integer,
                       Deponent:integer,
                       DepoAcc:integer,
                       AdmopCarryDate:date,  /* Дата администр. операции */
                       AdmID:integer, /*DEPOADMO.AdmoprID - Номер адм. операции*/
                       RepDate:date,
                       ReportNum:string,
                       ToExcel:bool)

    file party("party");
    var SqlQuery, client;
    var depoadmo = TBFile("depoadmo");
    var AdmOprID = 0;
    var stat:integer = 0, i;  
    var Item;

    if(Deponent == -1)
      MsgBox("   Необходимо указать депонента.");
      return 1;
    end;
    Dl_CallInsertStat( IIF( ToExcel, DL_OUTREPORT_EXCEL, DL_OUTREPORT_STD ) );

    DP_BeginProtocol();  //начать протоколирование - подмена MsgBox

    party.PartyID = Deponent;
    if(not GetEQ(party))
       MsgBox("Депонент не найден.");
    end;

    SqlQuery = RSDCommand("select * " +                                             
                          "  from dclient_dbt " +                             
                          " where t_ServiceKind = " + string(PTSK_DEPOS) + 
                          "   and t_PartyID = ? " +
                          "   and t_Department = ? " +      
                          "   and t_Branch = 0");                               

    SqlQuery.addParam("", RSDBP_IN, Deponent);
    SqlQuery.addParam("", RSDBP_IN, iDepart);
    SqlQuery.execute();                                                       
    client = TRsbDataSet(SqlQuery);                                        
                                                                            
    if( not client.MoveNext() )
      MsgBox("Депонент не находится на обслуживании в указанном филиале");
    end;
      
    var iDpnt = Deponent;
    
    cParty = CDPParty(iDpnt, AdmopCarryDate, true);

    AdmOprID = cParty.GetAdmOprID();
    if(AdmOprID <= 0)

      if(not DP_ProtocolIsEmpty())
        DP_AddPrintCell(Rep, "Не найдена административная операция c депонентом до указанной даты.", 70, 0, "l:" + RepFontStyleTitel, false, REP_ELEM_STR);
        Rep.AddStr();

        DP_AddProtocol(Rep, "protocol");  //добавим протокол к уже сформированному отчету
        DP_EndProtocol();                 //закончить протоколирование

        if( ToExcel )
         Rep.PrintWinRep();
         Rep.ShowWinRep();
        else
         Rep.PrintRep();
        end;
      else
        DP_EndProtocol();                 //закончить протоколирование
      end;

       MsgBox(" Не найдена административная операция c депонентом до указанной даты.");
       return 1;
    else
      depoadmo.rec.AdmOprID = AdmOprID;
      if(not depoadmo.GetEQ())
        MsgBox(" Не найдена административная операция c ID = " + AdmOprID);
        return 1;
      end;
    end;

    DP_StdHeaderLO_Ex( Rep, RepFontStyleTitel, "Анкета депонента", 0, 0, false, RepDate, RepDate, tablewidth );
    /*Собственно отчет*/
    PrintForm(depoadmo, date(client.startdate), AdmopCarryDate, party.LegalForm==физическое_лицо);

    if(not stat)
       DP_StdFooter_Ex(Rep, RepFontStyleTitel, NULL, NULL, tablewidth);

       DP_AddProtocol(Rep, "protocol");  //добавим протокол к уже сформированному отчету
       DP_EndProtocol();                 //закончить протоколирование

       if( ToExcel )
         Rep.PrintWinRep();
         Rep.ShowWinRep();
       else
         Rep.PrintRep();
       end;
    else
      DP_EndProtocol();                 //закончить протоколирование
    end;

    return stat;
end;
