/*
$Name: order_inv.mac
$Module: Депозитарий
$Description: Отчет об исполнении поручения
*/

import deposerv, CurrInter, dpzakrhr, cb_sql, opr_depo;
import RsbDataSet;

/* виды значений объекта - Сторона баланса (1000) */
private const SIDEBALANCE_UNDEFINE = 0;  /* не установлен */
private const SIDEBALANCE_ACTIVE   = 1;  /* активный      */
private const SIDEBALANCE_PASSIVE  = 2;  /* пассивный     */

const OBJTYPE_TRANSACTION_CONTENT = 1200; /* Содержание транзакции */
const SP_DEPOPER_INFOPER = 830; /* Информационная операция */
const OBJTYPE_DEPODRAFT = 104; /* Поручение на перевод ц/б */
const DP_NOTEKIND_REJECT = 3; /* примечание "причина отказа" */

var EmptyTable = "┌────────────────────────────────────────────────────────────────────────────────────────┐\n"+
                 "│                                                                                        │\n"+
                 "├────────────────────────────────────────────────────────────────────────────────────────┤";

const tablewidth = Index(EmptyTable, "\n");
var RepInv = CMakeReport(EmptyTable);
const RepFontStyleInv =  "ex_FS(b)";

var CountReport = 0;
private var Department;
/*документы Депозитария */
var DeposDocKind = TArray();
/*Названия документов Депозитария*/
var DeposDocName = TArray();

 DeposDocKind[0] = SP_DEPOPER_BOOKORDER;
 DeposDocName[0] = "Внутридепозитарный перевод безналичных ценных бумаг";
 DeposDocKind[1] = SP_DEPOPER_TRANSFERORDER;
 DeposDocName[1] = "Междепозитарный перевод безналичных ценных бумаг";
 DeposDocKind[2] = SP_DEPOPER_ENROLMENT;
 DeposDocName[2] = "Зачисление безналичных ценных бумаг ";
 DeposDocKind[3] = SP_DEPOPER_RECORDER;
 DeposDocName[3] = "Прием на хранение документарных ц/б";
 DeposDocKind[4] = SP_DEPOPER_WITHDRORDER;
 DeposDocName[4] = "Снятие с хранения документарных ц/б";

/*закрытое -- статус поручения депо*/
private const SC_SPDRAFT_STATUS_CLOSE = 3;
/* Номер объекта - блокировка ЦБ */
private const KIND_BLOCK_CB = 1202;
/*вид этого отчета*/
const spdbuhopReportType = 28;

var __reportXld, __rep_date, __OurName, __LogOprID, __is_app;

private var orderXld:string,
    orderXld_end:string,
    order_date_from:date,
    order_date_to:date,
    execut_date_from:date,
    execut_date_to:date,
    ojdnum_begin:string,
    ojdnum_end:string,
    iParty:integer,
    iPartyAC:integer,
    iPartyACPart:integer,
    iDAccount:string,
    iOperation_kind:integer,
    iOrerationStatus:integer,
    FIID:integer,
    InvCardID:integer,
    no_doub:bool,
    ToExcel:bool,
    GrDoc:integer,
    DraftID:integer,
    RepRecipientID:integer,
    RepNum,
    RepDate;

var InitString   = TArray();

private var llval = TBFile("llvalues");
/*var RecipientName = TBFile("party");*/
var iReport = 0;

var DataPrinted = false;

private var Progress = CProgressBar;

private file  depoacnt("depoacnt");

private macro OurName()       /*Our Name*/
  file party (party);
  party.PartyID = {OurBank};
  if(not GetEQ(party))
    MsgBox("Не найден наш банк");
    return "";
  end;
  return party.Name;
end;

private macro CheckDepoRoot(depoacntAK, Root)
   if ( ( Root == -1 ) or ( Root == 0 ) )
     return true;
   end;

   depoacnt.AutoKey = depoacntAK;
   if(GetEQ(depoacnt) and (depoacnt.Root == Root))
      return true;
   end;
   return false;
end;

macro TestDepoAcc( PartyID, iDepoAcc, iDepoPart, iDaccount, Node, isPayer, PaymID )
  var dpacnt = TBFile("depoacnt", "R", 0);
  var pmdocs = TBFILE("pmdocs", "R", 2);
  var doc = TBFILE ("acctrn", "R");

  /* если задан л/с */
  if ( iDaccount != "")
    pmdocs.rec.PaymentID = PaymID;
    if ( pmdocs.GetEQ() )
      doc.rec.AccTrnID = pmdocs.rec.AccTrnID;
      /*поиск в докуметах */
      if ( doc.GetEQ() )
        if (isPayer)
          if ( iDaccount != doc.rec.Account_Payer)
            return false;
          end;
        else
          if ( iDaccount != doc.rec.Account_Receiver)
            return false;
          end;
        end;
      else
        /*println("Не найден документ проводки");    */
        return false;
      end;

    else
      /*println("Не найдена привязка платежа к проводке");*/
      return false;
    end;

  /* если задан раздел */
  elif (iDepoPart > 0)
    if ( Node != iDepoPart )
      return false;
    end;

  else /* если задан только счет */
    if ( dpacnt.GetEQ(Node) )
      if ( (dpacnt.rec.root != dpacnt.rec.AutoKey) AND dpacnt.GetEQ(dpacnt.rec.Root) )
        if ( ((dpacnt.rec.AutoKey != iDepoAcc) AND ( iDepoAcc > 0))  OR (dpacnt.rec.Owner != PartyID) )
          return false;
        end;
      end;
    end;
  end;

  return true;
end;

macro TestParty( kind, dacc, iParty, iDepoAcc, iDepoPart, paym_file )

   if ( kind == SP_DEPOPER_BOOKORDER )
     depoacnt.AutoKey = dacc;
     if( GetEQ(depoacnt) and ( depoacnt.Kind == SIDEBALANCE_ACTIVE ) )
        return true;
     end;
   end;

   return false;
end;

private macro GetHeadAccForAcc(Node)
  var dpacnt = TBfile("depoacnt");

  dpacnt.Clear();
  dpacnt.rec.AutoKey = Node;
  if(dpacnt.GetEQ())
    if(dpacnt.rec.AutoKey != dpacnt.rec.Root) /*Если он сам не является головой*/
       dpacnt.rec.AutoKey = dpacnt.rec.Root;
       dpacnt.GetEQ();
       return dpacnt.rec.Code;
    end;
  end;
  return "";
end;

macro GetLLVALUES( List, Elem )
  file llvalues("llvalues");

  ClearRecord(llvalues);
  llvalues.List    = List;
  llvalues.Element = Elem;
  if( GetEQ(llvalues) )
    return llvalues.Name;
  end;

  return "";
end;

private class OneCert
   var IssuerID;
   var Nominal;
   var NominalStr;
   var IssuedDate;
   var Series;
   var NumberFirst;
   var NumberLast;
   var Amount;
end;

private class DepoOrderFilter(_kind,
                      _Opstatus,
                      _iDepoacnt,
                      _iPartyACPart,
                      _iDAccount,
                      _iParty,
                      _orderXld,
                      _orderXld_end,
                      _order_date_from,
                      _order_date_to,
                      _execut_date_from,
                      _execut_date_to,

                      _iOperation_kind,
                      _FIID,
                      _InvCardID,
                      _no_doub)

   var kind              = _kind,
       iPartyAC          = _iDepoacnt,
       iPartyACPart      = _iPartyACPart,
       iDaccount         = _iDAccount,
       iParty            = _iParty,
       orderXld          = _orderXld,
       orderXld_end      = _orderXld_end,
       order_date_from   = _order_date_from,
       order_date_to     = _order_date_to,
       execut_date_from  = _execut_date_from,
       execut_date_to    = _execut_date_to,
       opstatus          = _Opstatus,
       iOperation_kind   = _iOperation_kind,
       FIID              = _FIID,
       InvCardID         = _InvCardID,
       no_doub           = _no_doub;

   var Xld = __reportXld;

   var Name,
       FIName,
       FICode,
       Nominal,
       NominalFiCode,
       NominalFiName,
       IssuedDate;

   var BnDepositary    = "",
       BnCustAgentName = "",
       iIssuer         = -1,
       OpKind          = -1;

   var nrec = 0; //кол-во выбранных записей

 //  var Order   =TBFile("spdraft", "R", 1);
   var Order, query, cmd;
   var spground=TBFile("spground");
   var spdrmove=TBFile("spdrmove");
   var pmpaym  =TBFile("pmpaym");
   var pmrmprop=TBFile("pmrmprop");
   var pmprop_kred =TRecHandler("pmprop");
   var fininstr=TBFile("fininstr");
   var FaceFIID=TBFile("fininstr");
   var avoiriss=TBFile("avoiriss");
   var avrkinds=TBFile("avrkinds");
   var issuer  =TBFile("party");
   var Oper    =TBFile("person");
   var invlist1 = TBFile("invlist");
   var splogoprReport=TBFile("splogopr");
   var spgroundReport=TBFile("spground", "R", 6);
   var spgroundAdd;
   var oprkoper=TBFile("oprkoper");
   var notetext=TBfile("notetext");
   var carry =TRecHandler("acctrn");
   var dpacntPayer = TRecHandler("depoacnt");
   var dpacntReceiver = TRecHandler("depoacnt");

   macro NRecords()
     return Order.NRecords;
   end;

   macro recSpdraft ()
     return Order.rec;
   end;

   macro recSpground()
     return spground.rec;
   end;

   macro recPmpaym()
     return pmpaym.rec;
   end;

   macro recPmrmprop()
     return pmrmprop.rec;
   end;

   macro recPmpropKred()
     return pmprop_kred.rec;
   end;

   macro recFininstr()
     return fininstr.rec;
   end;

   macro recFaceFIID()
     return FaceFIID.rec;
   end;

   macro recAvoiriss()
     return avoiriss.rec;
   end;

   macro recAvrkinds()
     return avrkinds.rec;
   end;

   macro recIssuer()
     return issuer.rec;
   end;

   macro recOper()
     return Oper.rec;
   end;

   macro recInvList()
     return invlist1.rec;
   end;

   macro recSpgroundReport()
     return spgroundReport.rec;
   end;

   macro recSpgroundAdd()
     return spgroundAdd;
   end;

   macro recNoteText()
     return notetext.rec;
   end;

   macro setNominal(Amount, FIID)
      FaceFIID.rec.FIID = FIID;
      if( FIID != -1 )
         if ( not FaceFIID.GetEQ )
            println("Не найдена валюта номинала");
         else
            NominalFiName = FaceFIID.rec.Name;
            if( FaceFIID.rec.Ccy != "" )
              NominalFiCode = FaceFIID.rec.Ccy;
            else
              NominalFiCode = "-";
            end;

            if(__is_app)
              Nominal = ЧислоCЗаданнойТочностью(Amount, fininstr.rec.Point+2, "a");
            else
              Nominal = ЧислоCЗаданнойТочностью(Amount, fininstr.rec.Point+2);
            end;

            Nominal = Nominal + " (" + CurToStrAlt(ЧислоCЗаданнойТочностью(Amount, fininstr.rec.Point+2), NULL, NULL, int(FaceFIID.rec.ISO_Number), fininstr.rec.Point+2) + ")";
         end;
      else
         NominalFiCode = "-";
         NominalFiName = "-";
         Nominal = "-";
      end;
   end;

   macro setIssuedDate(FIID)
      file fin("fininstr");
      fin.FIID = FIID;
      if( FIID != -1 )
         if ( not GetEQ(fin) )
            println("Не найдена ценная бумага");
         else
            if( fin.Issued != date(0,0,0) )
              IssuedDate = fin.Issued;
            else
              IssuedDate = "-";
            end;
         end;
      else
         IssuedDate    = "-";
      end;
   end;

   macro CheckInvCardID(PaymID, InvCardID)
      var stat;
      invlist1.DropFilter();
      invlist1.AddFilter("t_PaymentID = " + PaymID
                          + " and t_InvCardID = "+InvCardID );
      if(invlist1.next() )
            return true;
         end;
      return false;
   end;

   macro GetFirstSpgrdoc()
     var stat = false;
     spgroundAdd = TRsbDataSet( " select spgr.* from dspgrdoc_dbt gr, dspground_dbt spgr "
                              + "  where gr.t_SourceDocKind = " + Order.rec.Kind
                              + "    and gr.t_SourceDocID =" + Order.rec.AutoKey
                              + "    and spgr.t_SPgroundID = gr.t_SPgroundID "
                              + "    and spgr.t_Direction <> " + EXITING);
     stat = spgroundAdd.moveNext();
     return stat;
   end;

   macro GetNextSpgrdoc()
     var stat;

     stat = spgroundAdd.moveNext();
     return stat;
   end;

   macro GetRecipientID()
    return RepRecipientID;
   end;

   macro GetRecipientName()
     var RecipientName = "";

     if(RepRecipientID > 0)
       RecipientName = GetPartyName( RepRecipientID, true );
     elif( __LogOprID != 0 )
       splogoprReport.rec.AutoKey = __LogOprID;
       if( splogoprReport.GetEQ() )
         spgroundReport.rec.SourceDocKind = SP_DEPOPER_INFOPER;
         spgroundReport.rec.SourceDocID   = splogoprReport.rec.AutoKey;
         spgroundReport.rec.Direction     = EXITING;
         spgroundReport.rec.Department    = Department;
         spgroundReport.rec.Division      = SelfDivision;
         if(spgroundReport.GetEQ())
           if(spgroundReport.rec.PartyName == "")
             RecipientName = GetPartyName( spgroundReport.rec.Party, true );
           else
             RecipientName = spgroundReport.rec.PartyName;
           end;
         end;
       end;
     else
       RecipientName = "-"
     end;

     return RecipientName;
   end;

   macro GetCarry()
     var pmdocs, cmd;
     var doc = TBFile("acctrn", "R", 0);
     var pmdocs_rec =TRecHandler("pmdocs");

     cmd = DL_RSDCommand("select * from dpmdocs_dbt where t_PaymentID = ?");
     cmd.AddParam(recPmpaym().PaymentID);

     pmdocs = cmd.Execute();
     if( pmdocs.moveNext() )
       pmdocs.GetRecord().CopyTo( pmdocs_rec.rec );

       /* Если проводок больше одной - л/с не выводим, т.к. не известно какую проводку брать */
       if(pmdocs.moveNext())
         carry.Clear();
       else
         doc.rec.AccTrnID = pmdocs_rec.rec.AccTrnID;
         /*поиск в документах */
         if( doc.GetEQ() )
           Copy(carry, doc);
         else
           carry.Clear();
           /* Не найден документ проводки */
           return false;
         end;
       end;
     else
       /* Не найдена привязка платежа к проводке */
       return false;
     end;

     return true;
   end;

   macro recDocument()
     return carry.rec;
   end;

   macro SetDpAcnt(DepoID, rDpAcnt)
     var dpacnt = TBfile("depoacnt");
     var stat;

     dpacnt.Clear();
     dpacnt.rec.AutoKey = DepoID;
     stat = dpacnt.GetEQ();

     if( stat )
        Copy(rDpAcnt, dpacnt);
     else
        rDpAcnt.Clear();
     end;

     return stat;
   end;

   macro recDpAcntPayer()
     return dpacntPayer.rec;
   end;

   macro recDpAcntReceiver()
     return dpacntReceiver.rec;
   end;

   macro FindOPRKOPER()
     oprkoper.rec.Kind_Operation = Order.rec.Kind_Operation;
     return oprkoper.getEQ();
   end;

   macro GetNoteText()
     notetext.Clear();
     notetext.AddFilter( " t_ObjectType = " + OBJTYPE_DEPODRAFT
                         + " and t_NoteKind   = " + DP_NOTEKIND_REJECT
                         + " and t_DocumentID = " + string(Order.rec.AutoKey) );
     return notetext.next();
   end;

   macro GetRejectNote()

     return readNoteForObject( OBJTYPE_DEPODRAFT,
                               string(Order.rec.AutoKey),
                               DP_NOTEKIND_REJECT);

   end;

   macro conformed ()
      var stat, ReportWasAlreadyCreate = false, Payer, Receiver, DwNode, BnNode;
      var isActiveBookorder;

      if((Order.rec.Kind_Operation != iOperation_kind)
          and (iOperation_kind > 0))
        return false;
      end;

      spground.rec.SPgroundID = Order.rec.SPgroundID;
      if(not spground.GetEQ())
         /*println("Не найден документ -- основание бухгалтерской операции");*/
         return false;
      end;

      if( (GrDoc > 0) AND (spground.rec.Kind != GrDoc) )
         return false;
      end;

      if( ((order_date_from > date(0,0,0)) and (order_date_to > date(0,0,0))) and ((spground.rec.RegistrDate < order_date_from)
         or (spground.rec.RegistrDate > order_date_to)) )
         return false;
      end;

      /* проверка вхождения в диапазон */
      if ( (orderXld_end != "") AND (orderXld != ""))
        if ( (spground.rec.Xld < orderXld) OR (orderXld_end < spground.rec.Xld) )
          return false;
        end;
      end;

      spdrmove.rec.DraftID = Order.rec.AutoKey;
      if(not spdrmove.GetEQ)
         println("Не найден платеж");
         return false;
      end;

      pmpaym.rec.PaymentID = spdrmove.rec.PaymentID;
      if(not pmpaym.GetEQ)
         /*println("Не найден платеж");*/
         return false;
      end;

      pmrmprop.rec.PaymentID = pmpaym.rec.PaymentID;
      if(not pmrmprop.GetEQ)
         /*println("Не найдены реквизиты платежа по депозитарным операциям");*/
      end;

      /* проверка по статусу */
      if ( (Order.rec.OperState != opstatus) AND ((opstatus != 2) AND (opstatus != -1)) )
        return false;
      end;

      /* проверка по разделу и счету */
      if ( (iPartyACPart > 0 ) OR (iPartyAC > 0) OR (iDaccount != "") OR (iParty > 0))
        /* если внутридепозитарный */
        if (Order.rec.Kind == SP_DEPOPER_BOOKORDER)
          if (isActiveBookorder == true)
            if ( (TestDepoAcc( iParty, iPartyAC, iPartyACPart, iDAccount, pmpaym.rec.ReceiverDpNode,
                  0, pmpaym.rec.PaymentID) == false) and
                 (TestDepoAcc( iParty, iPartyAC, iPartyACPart, iDaccount, pmpaym.rec.PayerDpNode,
                  0, pmpaym.rec.PaymentID) == false)
               )
              return false;
            end;
          else
            if ( (TestDepoAcc( iParty, iPartyAC, iPartyACPart, iDaccount, pmpaym.rec.PayerDpNode,
                  1, pmpaym.rec.PaymentID ) == false) AND
                 (TestDepoAcc( iParty, iPartyAC, iPartyACPart, iDaccount, pmpaym.rec.ReceiverDpNode,
                  0, pmpaym.rec.PaymentID ) == false)
               )
              return false;
            end;
          end;
        /* если списание*/
        elif ((Order.rec.Kind == SP_DEPOPER_TRANSFERORDER) OR
              (Order.rec.Kind == SP_DEPOPER_WITHDRORDER) )

          if ( (TestDepoAcc( iParty, iPartyAC, iPartyACPart, iDaccount, pmpaym.rec.PayerDpNode,
                1, pmpaym.rec.PaymentID ) == false) AND
                (TestDepoAcc( iParty, iPartyAC, iPartyACPart, iDaccount, pmpaym.rec.ReceiverDpNode,
                0, pmpaym.rec.PaymentID ) == false)
             )
              return false;
          end;

        /* если зачисление */
        elif ((Order.rec.Kind == SP_DEPOPER_ENROLMENT) OR
              (Order.rec.Kind == SP_DEPOPER_RECORDER) )

          if ( (TestDepoAcc( iParty, iPartyAC, iPartyACPart, iDaccount, pmpaym.rec.ReceiverDpNode,
               0, pmpaym.rec.PaymentID ) == false) AND
               (TestDepoAcc( iParty, iPartyAC, iPartyACPart, iDaccount, pmpaym.rec.PayerDpNode,
               1, pmpaym.rec.PaymentID ) == false)
              )
              return false;
          end;

        end;
      end;

      if( (DraftID == 0) AND ((execut_date_from > date(0,0,0)) and (execut_date_to > date(0,0,0)))and ((pmpaym.rec.ValueDate < execut_date_from)
         or (pmpaym.rec.ValueDate > execut_date_to)) )
         return false;
      end;

      if( (DraftID == 0) AND ( ojdnum_begin != "" ) AND (ojdnum_end != "")
          AND ( (Order.rec.OprXid < ojdnum_begin) OR (Order.rec.OprXid > ojdnum_end) ) )
         return false;
      end;

      if((pmpaym.rec.FIID != FIID)
         and (FIID != -1))
         return false;
      end;

      fininstr.rec.FIID = pmpaym.rec.FIID;
      if(not fininstr.GetEQ)
         /*println("Не найден фин. инструмент платежа");*/
         return false;
      else
        iIssuer = FI_GetIssuerOnDate( fininstr, execut_date_to );
      end;

      if( (InvCardID) and
          (not CheckInvCardID(pmpaym.rec.PaymentID, InvCardID)) )
         return false;
      end;

      return true;
   end;

   macro __PrepBase()
      var FaceValueMoney = 0.0;
      var cFin;
      cFin = CDPFinInstr(pmpaym.rec.FIID, pmpaym.rec.ValueDate);

      if( FindOPRKOPER() )
        Name = "КОП-" + oprkoper.rec.Kind_Operation + ", " + oprkoper.rec.Name;
      else
        Name = DeposDocName[find_index(DeposDocKind, kind)];
      end;

      avoiriss.rec.FIID = pmpaym.rec.FIID;
      if(not avoiriss.GetEQ)
         /*println("Не найдена ценная бумага");*/
         return false;
      end;
      avrkinds.rec.FI_Kind = fininstr.rec.FI_Kind;
      avrkinds.rec.AvoirKind = fininstr.rec.AvoirKind;
      if(not avrkinds.GetEQ)
         /*println("Не найден вид ценной бумаги");
         return false;  */
      end;

      if( fininstr.rec.issuer != -1 )
        issuer.rec.PartyID = FI_GetIssuerOnDate( fininstr, execut_date_to );
        if( not issuer.GetEQ )
         /*println("Не найден эмитент ценной бумаги");*/
          return false;
        end;
      end;
      Oper.rec.Oper = Order.rec.Oper;
      if(not Oper.GetEQ)
         /*println("Не найден операционист");
         return false;*/
      end;
      /*тут можно развести данные для разных операций*/
      if(kind == SP_DEPOPER_BOOKORDER)
         BnDepositary = __OurName;
      elif(kind == SP_DEPOPER_TRANSFERORDER)
         BnDepositary = pmrmprop.rec.ReceiverBankName;
      end;

      if(GetPaymentInfo( null, null, pmprop_kred.rec, pmpaym.rec.PaymentID, PMS_CREDIT )== false)
        /*println("Не найдены свойства платежа по кредиту ID = " + string(pmpaym.PaymentID) );
        return false;*/
      end;

      if(pmprop_kred.rec.CorrID != {OurBank})  /*Корреспондент депозитария получателя*/
         BnCustAgentName = pmrmprop.rec.ReceiverCorrBankName;
      else
         BnCustAgentName = __OurName;
      end;

      FIName = cfin.Name();

      FICode = cfin.LSIN();
      if(FICode == "")
        FICode = cfin.ISIN();
        if(FICode == "")
          FICode = cfin.getFins().FI_Code;
        end;
      end;

      if( pmpaym.rec.ValueDate == {curdate} )
        FaceValueMoney = GetFaceValue(Avoiriss.rec.FIID, pmpaym.rec.ValueDate);
      else
        FaceValueMoney = cfin.FaceValue();
      end;
      setNominal( FaceValueMoney, cfin.FaceValueFI());
      setIssuedDate(cfin.FIID());

      OpKind = DefineKindOperation( pmpaym.rec.PayerDpNode, pmpaym.rec.ReceiverDpNode );
      SetDpAcnt( recPmpaym.PayerDpNode, dpacntPayer );
      SetDpAcnt( recPmpaym.ReceiverDpNode, dpacntReceiver );
   end;

   macro First()
      var stat;

      cmd = DL_RSDCommand();

      query =   " select distinct dr.t_Kind, dr.t_Kind_Operation, dr.t_AutoKey, dr.t_OperState, "
              + " dr.t_Initiator, dr.t_Product, dr.t_OprXid, dr.t_OprXid2, dr.t_SPgroundID, dr.t_Oper "
              + " from dspdraft_dbt dr, dspground_dbt spgr, dspdrmove_dbt spm, dpmpaym_dbt pm"
              + " where dr.t_Kind   = ? "
              + " and   dr.t_Status = " + SC_SPDRAFT_STATUS_CLOSE
              + " and   dr.t_Department = ? "
              + " and   spgr.t_SPgroundID = dr.t_SPGroundID "
              + " and   spm.t_DraftID = dr.t_AutoKey "
              + " and   pm.t_PaymentID = spm.t_PaymentID";

      cmd.AddParam(kind);
      cmd.AddParam(Department);

      if(DraftID > 0)
        query = query + " and   dr.t_AutoKey = ? ";
        cmd.AddParam(DraftID);
      end;

      if((order_date_from > date(0,0,0)) and (order_date_to > date(0,0,0)))
        query = query + " and   spgr.t_RegistrDate >= ? "
                      + " and   spgr.t_RegistrDate <= ? ";

        cmd.AddParam(order_date_from);
        cmd.AddParam(order_date_to);
      end;

      if( iOperation_kind > 0 )
        query = query + " and   dr.t_kind_Operation = ? ";
        cmd.AddParam(iOperation_kind);
      end;

      if ( (orderXld_end != "") AND (orderXld != ""))
        query = query + " and spgr.t_Xld >= ? "
                      + " and spgr.t_Xld <= ? ";

        cmd.AddParam(orderXld);
        cmd.AddParam(orderXld_end);
      end;

      if( InvCardID )
        query = query + " and pm.t_PaymentID in ( select il.t_PaymentID from dinvlist_dbt il where il.t_InvCardID = ? )";

        cmd.AddParam(InvCardID);
      end;

      if ( (opstatus != 2) AND (opstatus != -1) )
        query = query + " and dr.t_OperState = ? ";

        cmd.AddParam(opstatus);
      end;

      if( FIID != -1 )
         query = query + " and pm.t_FIID = ? ";

         cmd.AddParam(FIID);
      end;

      nrec = cmd.GetCount(query);
      Order = cmd.Execute(query);
      while (Order.MoveNext() )
         if(conformed ())
            __PrepBase();
            return true;
         end;
      end;
      return false;
   end;

   macro Next()
      var stat;
      while ( Order.MoveNext()  )
         if(conformed ())
            __PrepBase();
            return true;
         end;
      end;
      return false;
   end;

end;

/* Печать ценных бумаг и описи сертификатов с сортировкой по эмитенту, серии и номерам */
macro PrintSecurities(Order)
  var cIssuer;
  var IK = IK_class(Order.recPmpaym);
  var IK_List = TArray;
  var cert;
  var cert_old;
  var stat;
  var IKCount = 0;
  var IKNum = 0;
  var IssuerIKCount = 0;
  var IssuerIKNum = 0;

  IK_List.Size = 0;
  stat = IK.First_IK();

  // если есть сертификаты
  if( stat )
    while( stat )
      cert = OneCert;

      cert.IssuerID     = IK.Issuer;
      cert.Nominal      = IK.Nominal.Nominal;
      cert.NominalStr   = IK.FaceValueFiCcy();
      cert.IssuedDate   = IK.IssueDate;
      cert.Series       = IK.Series;
      cert.NumberFirst  = trim(IK.Number);
      cert.NumberLast   = trim(IK.Number);
      cert.Amount       = IK.IK_Amount();

      IK_List[IK_List.Size] = cert;

      stat = IK.Next_IK();
    end;

    TArray_QSort(IK_List, "IssuerID", 1, "Series", 1, "NumberFirst", 1, "NumberLast", 1 );

    cert_old = OneCert;
    IKCount = 0;
    IKNum = IK_List.Size;
    IssuerIKCount = 0;
    IssuerIKNum = 0;
    while(( IKCount < IKNum ) and ( cert_old.IssuerID != IK_List[IKCount].IssuerID ))
      cert_old.IssuerID = IK_List[IKCount].IssuerID;
      cert_old.NominalStr = IK_List[IKCount].NominalStr;
      cert_old.IssuedDate = IK_List[IKCount].IssuedDate;

      IssuerIKCount = IKCount;
      IssuerIKNum = 0;

      while( ( IssuerIKCount < IKNum ) and ( cert_old.IssuerID == IK_List[IssuerIKCount].IssuerID ) )
        IssuerIKNum = IssuerIKNum + IK_List[IssuerIKCount].Amount;
        IssuerIKCount = IssuerIKCount + 1;
      end;

      DP_AddPrintCell( RepInv, "Ценные бумаги", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();

      if( Order.recIssuer.PartyID > 0 )
        cIssuer = CDPParty( Order.recIssuer.PartyID, Order.recSpground.RegistrDate );
      else
        cIssuer = CDPParty( IK_List[IKCount].IssuerID, Order.recSpground.RegistrDate );
      end;
      DP_AddPrintCell( RepInv, "    эмитент             ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, cIssuer.Name(), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();
      DP_AddPrintCell( RepInv, "    наименование        ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, Order.FIName + IIF(QualifiedSecur(Order.avoiriss, Order.fininstr, Order.execut_date_to), "", " (НКЦБ)"), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();
      DP_AddPrintCell( RepInv, "    № гос.регистрации   ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, Order.FICode, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();
      DP_AddPrintCell( RepInv, "    вид                 ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, Order.recAvrkinds.Name, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();
      DP_AddPrintCell( RepInv, "    № выпуска/транша    ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, Order.recAvoiriss.Issue, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();

      if(not DP_CheckAvoirKind(Order.RecFininstr.AvoirKind, AVOIRISSKIND_INVESTMENT_SHARE)) // пай
         DP_AddPrintCell( RepInv, "    номинал             ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
         DP_AddPrintCell( RepInv, Order.Nominal, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
         RepInv.AddStr();
         DP_AddPrintCell( RepInv, "    валюта              ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
         DP_AddPrintCell( RepInv, Order.NominalFiCode + " (" + Order.NominalFiName + ")", tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
         RepInv.AddStr();
         DP_AddPrintCell( RepInv, "    дата выпуска        ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
         DP_AddPrintCell( RepInv, DateToStr(Order.IssuedDate, true), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
         RepInv.AddStr();
      end;

      DP_AddPrintCell( RepInv, "    количество          ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, ЧислоCЗаданнойТочностью(IssuerIKNum, DP_GetPrecision(IssuerIKNum, Order.RecFinInstr.SumPrecision), IIF( __is_app, "a", "" ) ) +
                       " (" + NumToStr(IssuerIKNum, null, null, null, null, DP_GetPrecision(Order.recPmpaym.Amount, Order.RecFinInstr.SumPrecision)) + ") шт.", tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();

      DP_AddPrintCell( RepInv, "    опись сертификатов", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();

      IssuerIKCount = IKCount;
      while( ( IssuerIKCount < IKNum ) and ( cert_old.IssuerID == IK_List[IssuerIKCount].IssuerID ) )
        DP_AddPrintCell( RepInv, "           " + IK_List[IssuerIKCount].Series, 19, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
        DP_AddPrintCell( RepInv, IK_List[IssuerIKCount].NumberFirst + "-" + IK_List[IssuerIKCount].NumberLast, 20, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
        if( ( Order.Nominal == "-" ) or ( Order.NominalFiCode == "-" ) )
          DP_AddPrintCell( RepInv, "номинал: " + setApp(IK_List[IssuerIKCount].Nominal, __is_app) + " " + IK_List[IssuerIKCount].NominalStr, 25, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
        end;
        if( Order.IssuedDate == "-" )
          DP_AddPrintCell( RepInv, "дата выпуска: " + DateToStr(IK_List[IssuerIKCount].IssuedDate, true), 27, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
        end;
        RepInv.AddStr();

        IssuerIKCount = IssuerIKCount + 1;
      end;

      RepInv.AddEmptyStr();
      RepInv.AddStr();

      IKCount = IKCount + IssuerIKCount;
    end; // while(( IKCount < IKNum ) and ( cert_old.IssuerID != IK_List[IKCount].IssuerID ))
  else // if( stat ) если сертификатов нет
    cIssuer = CDPParty( Order.recIssuer.PartyID, Order.recSpground.RegistrDate );

    DP_AddPrintCell( RepInv, "Ценные бумаги", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    RepInv.AddStr();

    DP_AddPrintCell( RepInv, "    эмитент             ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    DP_AddPrintCell( RepInv, cIssuer.Name(), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    RepInv.AddStr();
    DP_AddPrintCell( RepInv, "    наименование        ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    DP_AddPrintCell( RepInv, Order.FIName + IIF(QualifiedSecur(Order.avoiriss, Order.fininstr, Order.execut_date_to), "", " (НКЦБ)"), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    RepInv.AddStr();
    DP_AddPrintCell( RepInv, "    № гос.регистрации   ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    DP_AddPrintCell( RepInv, Order.FICode, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    RepInv.AddStr();
    DP_AddPrintCell( RepInv, "    вид                 ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    DP_AddPrintCell( RepInv, Order.recAvrkinds.Name, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    RepInv.AddStr();
    DP_AddPrintCell( RepInv, "    № выпуска/транша    ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    DP_AddPrintCell( RepInv, Order.recAvoiriss.Issue, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    RepInv.AddStr();

    if(not DP_CheckAvoirKind(Order.RecFininstr.AvoirKind, AVOIRISSKIND_INVESTMENT_SHARE)) // пай
      DP_AddPrintCell( RepInv, "    номинал             ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, Order.Nominal, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();
      DP_AddPrintCell( RepInv, "    валюта              ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, Order.NominalFiCode + " (" + Order.NominalFiName + ")", tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();
      DP_AddPrintCell( RepInv, "    дата выпуска        ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, DateToStr(Order.IssuedDate, true), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      RepInv.AddStr();
    end;

    DP_AddPrintCell( RepInv, "    количество          ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    DP_AddPrintCell( RepInv, ЧислоCЗаданнойТочностью((Order.recPmpaym.Amount), DP_GetPrecision(Order.recPmpaym.Amount, Order.RecFinInstr.SumPrecision), IIF( __is_app, "a", "" ) ) +
                     " (" + NumToStr(Order.recPmpaym.Amount, null, null, null, null, DP_GetPrecision(Order.recPmpaym.Amount, Order.RecFinInstr.SumPrecision))+ ") шт.", tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    RepInv.AddStr();

    DP_AddPrintCell( RepInv, "    опись сертификатов", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    RepInv.AddStr();
  end; // if( stat )
end;

private macro PrintDepoAcntRest(Order, AcntAutoKey, AcntCode)
  var query, cmd, DataSet;
  var strapp = "";

  if(__is_app)
    strapp = "a";
  end;

  query =   " with q as (select *"
          + "              from daccount_dbt acc "
          + "             where acc.t_DepoRoot = ? AND acc.t_Code_Currency = ?"
          + "           ) "
          + " select NVL((select MAX(fin.t_SumPrecision) from dfininstr_dbt fin, q where fin.t_FIID = q.t_Code_Currency), 0) as SumPrecision, "
          + "        cast((select SUM(rsb_account.restac( q.t_Account, q.t_Code_Currency, ? , q.t_Chapter, null )) from q) as number(32,12) ) as Rest"
          + "   from dual ";

  cmd = DL_RSDCommand(query);
  cmd.AddParam(AcntAutoKey);
  cmd.AddParam(Order.recPmpaym.fiid);
  cmd.AddParam(date(Order.recPmpaym.ValueDate));

  DataSet = cmd.Execute();
  if(DataSet.moveNext())

    DP_AddPrintCell( RepInv, "Остаток по счету "+AcntCode+" на конец операционного дня "+string(Order.recPmpaym.ValueDate:f)+" "+ЧислоCЗаданнойТочностью(DataSet.Rest, DataSet.SumPrecision, strapp)+" шт.", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
    RepInv.AddStr();
  end;
end;

/* 800 "Поручение на книжный перевод эмиссионных ценных бумаг"*/
/* 805 "Поручение на междепозитарный перевод эмиссионных ценных бумаг"*/
/* и прочее*/
macro PrintOrderForm(Order, Reject, iCount, PrintSubNum)
   var BlockCode, BlockName, GroundAdd = "", stat, Reciever = "-", dubl = "";
   var acnt = TBFile("depoacnt", "R", 0);
   var acntD = TRecHandler("depoacnt.dbt");
   var acntC = TRecHandler("depoacnt.dbt");
   var Code,BriefCode;
   var PartCode;
   var PartBriefCode;
   var cInitiator, cPayer, cReceiver, cIssuer;
   var NeedPrintDebetRest = false, NeedPrintCreditRest = false;
   var DepoAcTypeForRest = "";
   var RecieverID;

   acntD.Clear();
   acntC.Clear();

   //инициатор поручения
   if(not Order.no_doub)
     dubl = " (дубликат) ";
   end;

   if( iCount > 0 )
     DP_AddPrintCell( RepInv, "-------------------------------------------------------------------------------", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
   end;

   if( Reject == false  )
     DP_StdHeaderLO_Ex( RepInv, RepFontStyleInv, "Отчет об исполнении инвентарной операции" + dubl, __LogOprID, iCount+1, PrintSubNum, Order.execut_date_from, Order.execut_date_to, tablewidth, RepNum, RepDate );
   else
     DP_StdHeaderLO_Ex( RepInv, RepFontStyleInv, "Уведомление об отказе в исполнении поручения" + dubl, __LogOprID, iCount+1, PrintSubNum, Order.execut_date_from, Order.execut_date_to, tablewidth, RepNum, RepDate );
   end;

   Reciever = Order.GetRecipientName();
   RecieverID = Order.GetRecipientID();

   stat = Order.GetFirstSpgrdoc();
   while( stat )
     GroundAdd = GroundAdd + GetLLVALUES(OBJTYPE_KINDDOC,Order.recSpgroundAdd.Kind) + " №" +
                 Order.recSpgroundAdd.AltXld + " от " + string(Order.recSpground.SignedDate:f);
     stat = Order.GetNextSpgrdoc();
     if( stat )
       GroundAdd = GroundAdd + ", \n";
     end;
   end;
   if(GroundAdd == "")
     GroundAdd = "-";
   end;

   cInitiator = CDPParty( Order.recSpdraft.Initiator, Order.recSpground.RegistrDate );

   DP_AddPrintCell( RepInv, "Отправитель отчета      ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   DP_AddPrintCell( RepInv, GetPartyName( {OurBank}, true ), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   DP_AddPrintCell( RepInv, "Получатель отчета       ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   DP_AddPrintCell( RepInv, Reciever, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   DP_AddPrintCell( RepInv, "Поручение               ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   DP_AddPrintCell( RepInv, "№" + Order.recSpground.AltXld + " от " + string(Order.recSpground.SignedDate:f) +
                      ", Вх.№" + Order.recSpground.Xld + ", дата приема " + string(Order.recSpground.RegistrDate:f),
                      tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   DP_AddPrintCell( RepInv, "Инициатор               ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   DP_AddPrintCell( RepInv, cInitiator.Name(), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   DP_AddPrintCell( RepInv, "Депозитарная операция   ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   DP_AddPrintCell( RepInv, Order.Name, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   DP_AddPrintCell( RepInv, "    основание           ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   DP_AddPrintCell( RepInv, GroundAdd, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   DP_AddPrintCell( RepInv, "                        ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   DP_AddPrintCell( RepInv, GetLLVALUES(OBJTYPE_TRANSACTION_CONTENT,Order.recSpdraft.Product), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   DP_AddPrintCell( RepInv, "-------------------------------------------------------------------------------", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();

   DataPrinted = true;
   Order.GetCarry();

   if( Order.recDpAcntPayer().AutoKey > 0 )

     acnt.Clear();
     acnt.rec.AutoKey = Order.recDpacntPayer().Root;
     stat = acnt.GetEQ();
     if(NOT stat)
       Code = "";
       BriefCode = "";
     else
       Code = acnt.rec.Code;
       BriefCode = acnt.rec.BriefCode;
       copy(acntD, acnt);
     end;

     if(Order.recDpacntPayer().AutoKey != Order.recDpacntPayer().Root)
       PartCode = Order.recDpacntPayer().Code;
       PartBriefCode = Order.recDpacntPayer().BriefCode;
     end;

     cPayer = CDPParty( Order.recDpacntPayer().Owner, Order.recSpground.RegistrDate );

     DP_AddPrintCell( RepInv, "Д Е Б Е Т", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "Счет депо               ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, Code + " (короткий " + BriefCode + ")", tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "    владелец            ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, cPayer.Name(), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "        ИНН             ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, cPayer.CodeINN(), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "        код анкеты      ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, ПолучитьКодСубъекта(Order.recDpacntPayer().Owner, PTCK_CONTR), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "    раздел              ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, Order.recDpacntPayer().Code + " (короткий " + Order.recDpacntPayer().BriefCode + ")", tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "    лицевой счет        ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, Order.recDocument.Account_Payer, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     RepInv.AddEmptyStr();
   end;

   if( Order.recDpAcntReceiver().AutoKey > 0 )

     acnt.Clear();
     acnt.rec.AutoKey = Order.recDpacntReceiver().Root;
     stat = acnt.GetEQ();
     if(NOT stat)
       Code = "";
       BriefCode = "";
     else
       Code = acnt.rec.Code;
       BriefCode = acnt.rec.BriefCode;
       copy(acntC, acnt);
     end;

     if(Order.recDpacntReceiver().AutoKey != Order.recDpacntReceiver().Root)
       PartCode = Order.recDpacntReceiver().Code;
       PartBriefCode = Order.recDpacntReceiver().BriefCode;
     end;

     cReceiver = CDPParty( Order.recDpacntReceiver().Owner, Order.recSpground.RegistrDate );

     DP_AddPrintCell( RepInv, "К Р Е Д И Т", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "Счет депо               ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, Code + " (короткий " + BriefCode + ")", tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "    владелец            ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, cReceiver.Name(), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "        ИНН             ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, cReceiver.CodeINN(), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "        код анкеты      ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, ПолучитьКодСубъекта(Order.recDpacntReceiver().Owner, PTCK_CONTR), tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "    раздел              ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, Order.recDpacntReceiver().Code + " (короткий " + Order.recDpacntReceiver().BriefCode + ")", tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     DP_AddPrintCell( RepInv, "    лицевой счет        ", 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     DP_AddPrintCell( RepInv, Order.recDocument.Account_Receiver, tablewidth - 24, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     RepInv.AddEmptyStr();
     RepInv.AddEmptyStr();
   end;

   PrintSecurities( Order );

   private macro IsOwnerMoveAvr(paymentID, recipientID)
      var query, DataSet, isOwner = false;
      var Select;

      query =  " select 1 "
             + "   from daccsubdc_dbt accs, daccvanl_dbt accv, daccount_dbt acc "
             + "  where accs.t_PaymentID = ? "
             + "    and accv.t_AccAnaliticsID = accs.t_AccAnaliticsID "
             + "    and acc.t_Chapter = accv.t_chapter "
             + "    and acc.t_Account = accv.t_Account "
             + "    and acc.t_Code_Currency = accv.t_Fiid "
             + "    and acc.t_Client = ? ";

      Select = RSDCommand( query );
      Select.AddParam("", RSDBP_IN, paymentID );
      Select.AddParam("", RSDBP_IN, recipientID );
      Select.Execute();

      DataSet = TRSBDataSet(Select);
      if( DataSet.MoveNext() )
         isOwner = true;
      end;

      return isOwner;
   end;

   private macro AddCells_Xid(xid)
      DP_AddPrintCell( RepInv, "    запись в журнале операций        ", 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
      DP_AddPrintCell( RepInv, xid, tablewidth - 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   end;

   ////////////////////////////////////////////
   //напечатать остатки по счетам на конец дня.
   macro CheckDepoAcType(AcntType)
     var query, cmd, DataSet;

     query =   " select 1 "
             + "   from ddepoac_dbt ac, dllvalues_dbt lv "
             + "  where ac.t_ID = ? "
             + "    and lv.t_List = " + OBJTYPE_DEPOKINDTYPE
             + "    and lv.t_element = ac.t_Type "
             + "    and lv.t_Code IN ('"+StrSubst ( DepoAcTypeForRest, ",", "','" )+"')";

     cmd = DL_RSDCommand(query);
     cmd.AddParam(AcntType);

     DataSet = cmd.Execute();
     if(DataSet.moveNext())
       return true;
     end;

     return false;
   end;

   if((acntD.rec.AutoKey > 0) OR (acntC.rec.AutoKey > 0))
     GetRegistryValue("DEPO\\DEPOACTYPEFORREST", V_STRING, DepoAcTypeForRest, stat);
     if( stat != 0 )
       msgbox("Ошибка поиска значения настройки \"Вывод остатков в отчёте об исполнении для типов счетов\"");
     else
       DepoAcTypeForRest = StrSubst ( DepoAcTypeForRest, " ", "" );
       if(DepoAcTypeForRest != "")
         if((acntD.rec.Kind != SIDEBALANCE_PASSIVE) and (acntC.rec.Kind == SIDEBALANCE_PASSIVE)) //зачисление
           NeedPrintCreditRest = true;
         elif((acntD.rec.Kind == SIDEBALANCE_PASSIVE) and (acntC.rec.Kind != SIDEBALANCE_PASSIVE)) //списание
           NeedPrintDebetRest = true;
         elif((acntD.rec.Kind == SIDEBALANCE_PASSIVE) and (acntC.rec.Kind == SIDEBALANCE_PASSIVE)) //перевод
           if((acntD.rec.AutoKey != acntC.rec.AutoKey) and (acntD.rec.Owner == acntC.rec.Owner)) //в поручении разные счета одного владельца
             NeedPrintCreditRest = true;
             NeedPrintDebetRest = true;
           elif(acntD.rec.AutoKey == acntC.rec.AutoKey) //в поручении разные разделы одного счета депо
             NeedPrintDebetRest = true;
           elif((acntD.rec.AutoKey != acntC.rec.AutoKey) and (acntD.rec.Owner != acntC.rec.Owner)) //в поручении счета разных владельцев
             if(RecieverID == acntD.rec.Owner)
               NeedPrintDebetRest = true;
             elif(RecieverID == acntC.rec.Owner)
               NeedPrintCreditRest = true;
             end;
           end;
         end;

         if(NeedPrintDebetRest == true)
           NeedPrintDebetRest = CheckDepoAcType(acntD.rec.Type);
         end;

         if(NeedPrintCreditRest == true)
           NeedPrintCreditRest = CheckDepoAcType(acntC.rec.Type);
         end;

         if((NeedPrintDebetRest == true) OR (NeedPrintCreditRest == true))
           RepInv.AddEmptyStr();
         end;

         if( ( Reject == false ) AND ( NeedPrintDebetRest == true )  )
           PrintDepoAcntRest(Order, acntD.rec.AutoKey, acntD.rec.Code);
         end;

         if( ( Reject == false ) AND ( NeedPrintCreditRest == true ) )
           PrintDepoAcntRest(Order, acntC.rec.AutoKey, acntC.rec.Code);
         end;

         if(  ( Reject == false ) AND ( (NeedPrintDebetRest == true) OR (NeedPrintCreditRest == true) )  )
           RepInv.AddEmptyStr();
         end;
       end;
     end;
   end;
   ////////////////////////////////////////////

   DP_AddPrintCell( RepInv, "-------------------------------------------------------------------------------", tablewidth, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   RepInv.AddEmptyStr();

   DP_AddPrintCell( RepInv, "Обработка поручения        ", 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   if (Reject == false)
     DP_AddPrintCell( RepInv, "\"ИСПОЛНЕНО\"", tablewidth - 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();

     if( (Order.OpKind != KINDOPER_TRANSFER) and (Order.OpKind != KINDOPER_MOVEMENT) )
        AddCells_Xid( Order.recSpdraft.OprXid );
     else
        if( Order.OpKind == KINDOPER_TRANSFER )
           if( order.GetRecipientID() == Order.recDpAcntPayer().Owner )
              AddCells_Xid( Order.recSpdraft.OprXid );
           elif( order.GetRecipientID() == Order.recDpAcntReceiver().Owner )
              AddCells_Xid( Order.recSpdraft.OprXid2 );
           elif( (Order.recDpAcntPayer().Owner == Order.recDpAcntReceiver().Owner)
              or ((order.GetRecipientID() != Order.recDpAcntPayer().Owner) and (order.GetRecipientID() != Order.recDpAcntReceiver().Owner)) )
              AddCells_Xid( Order.recSpdraft.OprXid );
              RepInv.AddStr();
              AddCells_Xid( Order.recSpdraft.OprXid2 );
           end;
        elif( Order.OpKind == KINDOPER_MOVEMENT )
           AddCells_Xid( Order.recSpdraft.OprXid );
           if( (order.GetRecipientID() == {OurBank}) or IsOwnerMoveAvr(order.recPmpaym.PaymentID, order.GetRecipientID()) )
              RepInv.AddStr();
              AddCells_Xid( Order.recSpdraft.OprXid2 );
           end;
        end;
     end;
     RepInv.AddStr();
   else
     DP_AddPrintCell( RepInv, "\"ОТКАЗАНО В ИСПОЛНЕНИИ\"", tablewidth - 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
     RepInv.AddStr();
     if( Order.GetNoteText() )
        DP_AddPrintCell( RepInv, "    причина отказа         ", 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
        DP_AddPrintCell( RepInv, Order.GetRejectNote(), tablewidth - 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
        RepInv.AddStr();
     end;
   end;

   DP_AddPrintCell( RepInv, "    дата                             ", 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   DP_AddPrintCell( RepInv, string(Order.recPmpaym.ValueDate:f), tablewidth - 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   DP_AddPrintCell( RepInv, "    исполнитель                      ", 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   DP_AddPrintCell( RepInv, Order.recOper.Name, tablewidth - 37, 0, "l:w:" + RepFontStyleInv, __is_app, REP_ELEM_STR );
   RepInv.AddStr();
   RepInv.AddEmptyStr();
   RepInv.AddEmptyStr();
   RepInv.AddEmptyStr();
end;

macro FindDepoOrders(kind,
                     Opstatus,
                     iPartyAC,
                     iPartyACPart,
                     iDAccount,
                     iParty,
                     orderXld,
                     orderXld_end,
                     order_date_from,
                     order_date_to,
                     execut_date_from,
                     execut_date_to,

                     iOperation_kind,
                     FIID,
                     InvCardID,
                     no_doub,
                     PrintSubNum)

    var Order, stat, i = 0;

    Order = DepoOrderFilter(kind,
                      Opstatus,
                      iPartyAC,
                      iPartyACPart,
                      iDAccount,
                      iParty,
                      orderXld,
                      orderXld_end,
                      order_date_from,
                      order_date_to,
                      execut_date_from,
                      execut_date_to,

                      iOperation_kind,
                      FIID,
                      InvCardID,
                      no_doub);

    stat = Order.First();

    while(stat)
          if( order.Order.rec.OperState != DP_INVSTATUSORDER_REJECT )
            PrintOrderForm(Order, false, iReport, PrintSubNum);
          else
            PrintOrderForm(Order, true, iReport, PrintSubNum);
          end;
          iReport = Progress.Use();
          i = i + 1;
       stat = Order.Next();
    end;
    return i;
end;

private macro CreateRep()

   var isPrint = 0, i = 0, PrintSubNum = false;
   var j = 0;
   var Order;
   var ValRec = TARRAY;
   InitString[0] = "депонента";
   InitString[1] = "оператора";
   InitString[2] = "распорядителя";

   DP_BeginProtocol();  //начать протоколирование - подмена MsgBox

   while(i < DeposDocKind.Size)
      Order = DepoOrderFilter(DeposDocKind[i],
                        iOrerationStatus,
                        iPartyAC,
                        iPartyACPart,
                        iDAccount,
                        iParty,
                        orderXld,
                        orderXld_end,
                        order_date_from,
                        order_date_to,
                        execut_date_from,
                        execut_date_to,

                        iOperation_kind,
                        FIID,
                        InvCardID,
                              no_doub);
      Order.First();
      CountReport = CountReport + Order.nrec;
      ValRec[ValRec.size] = Order.nrec;
      i = i + 1;
   end;

   i = 0;
   Progress.Init(CountReport, "Формирование отчета", "Отчет об исполнении поручения");

   while((i < DeposDocKind.Size) and (CountReport > 0) )
      if( CountReport > 1 )
        PrintSubNum = true;
      end;
      if( ValRec[i] > 0 )
      isPrint = isPrint +
         FindDepoOrders(DeposDocKind[i],
                        iOrerationStatus,
                        iPartyAC,
                        iPartyACPart,
                        iDAccount,
                        iParty,
                        orderXld,
                        orderXld_end,
                        order_date_from,
                        order_date_to,
                        execut_date_from,
                        execut_date_to,

                        iOperation_kind,
                        FIID,
                        InvCardID,
                        no_doub,
                        PrintSubNum );
      end;

      i = i + 1;
   end;

   Progress.Remove();

   if(isPrint != 0)
      RepInv.AddEmptyStr();
      RepInv.AddEmptyStr();
      DP_StdAuthPerson_Ex(RepInv, RepFontStyleInv);
      DP_StdDeposInfo_Ex(RepInv, RepFontStyleInv, tablewidth);
      DP_StdExecReport_Ex(RepInv, RepFontStyleInv, NULL, NULL, tablewidth);
   else
      CountReport = 0;
   end;

   DP_AddProtocol(RepInv, "protocol");  //добавим протокол к уже сформированному отчету
   DP_EndProtocol();                    //закончить протоколирование

   return isPrint;
end;

macro Order_INV( _GrDoc:integer,          /*Вид первичного документа */
                 _order_date_from:date,   /*Диапазон дат регистрации поручений*/
                 _order_date_to:date,     /*Диапазон дат регистрации поручений*/
                 _orderXld:string,        /*№ поручения депо по журналу входящих документов депозитария Используется как фильтр по поручениям */
                 _orderXld_end:string,    /* если диапазон номеров */
                 _iOperation_kind:integer, /* класс операции (зацисление, списание и т.д.)   */
                 _iOrerationStatus:integer, /* исполнено/отказано/не задано*/
                 _execut_date_from:date,  /*Диапазон дат исполнений (проводок) поручений*/
                 _execut_date_to:date,    /*Диапазон дат исполнений (проводок) поручений*/
                 _ojdnum_begin:string,
                 _ojdnum_end:string,
                 _Department:integer,
                 _iParty:integer,          /*субьект, исп. при фильтрации*/
                 _iPartyAC:integer,        /*счет депо  */
                 _iPartyACPart:integer,    /* раздел счета депо */
                 _iDAccount:string,        /* л/с */
                 _FIID:integer,
                 _InvCardID:integer,
                 LogOprID:integer,
                 _ToExcel:bool,
                 is_app:bool,
                 _no_doub:bool,
                 _Rep:@variant,
                 _DraftID:integer
                 )
   var count;

   if((ValType(_Rep) != V_UNDEF) and (_Rep != null))
     RepInv = _Rep;
   end;

   __OurName  = OurName();
   __LogOprID = LogOprID;
   __is_app   = is_app;
   Department = _Department;
   orderXld         =  _orderXld;
   orderXld_end     =  _orderXld_end;
   order_date_from  =  _order_date_from;
   order_date_to    =  _order_date_to;
   execut_date_from =  _execut_date_from;
   execut_date_to   =  _execut_date_to;
   iParty           =  _iParty;
   iPartyAC         =  _iPartyAC;
   iPartyACPart     =  _iPartyACPart;
   iDAccount        =  _iDAccount;
   iOperation_kind  =  _iOperation_kind;
   iOrerationStatus =  _iOrerationStatus;
   FIID             =  _FIID;
   InvCardID        =  _InvCardID;
   no_doub          =  _no_doub;
   ToExcel          =  _ToExcel;
   ojdnum_begin     =  _ojdnum_begin;
   ojdnum_end       =  _ojdnum_end;
   GrDoc            =  _GrDoc;

   DraftID = _DraftID;
   RepRecipientID = -1;
   RepNum = false;

   count = CreateRep();

   _Rep = RepInv;

   return count;
end;

macro Order_INVbyDraft(_DraftID, _Recipient, _RepNum, _RepDate, _Rep:@variant)

   if((ValType(_Rep) != V_UNDEF) and (_Rep != null))
     RepInv = _Rep;
   end;

   __OurName  = OurName();
   __LogOprID = 0;
   __is_app   = true;
   Department = {OperDprt};
   orderXld         =  "";
   orderXld_end     =  "";
   order_date_from  =  date(0,0,0);
   order_date_to    =  date(0,0,0);
   execut_date_from =  _RepDate;
   execut_date_to   =  _RepDate;
   iParty           =  -1;
   iPartyAC         =  0;
   iPartyACPart     =  0;
   iDAccount        =  "";
   iOperation_kind  =  0;
   iOrerationStatus =  -1;
   FIID             =  -1;
   InvCardID        =  0;
   no_doub          =  true;
   ojdnum_begin     =  "";
   ojdnum_end       =  "";
   GrDoc            =  0;

   DraftID = _DraftID;
   RepRecipientID = _Recipient;
   RepNum = _RepNum;
   RepDate = _RepDate;

   CreateRep();

   _Rep = RepInv;

end;

