/*
$Name:        dvfx080.mac
$Module:      Производные инструменты
$Description: Конверсионная операция. Шаг "Закрытие"
*/
import InsCarryDoc, "dv_categ.mac", "dv_car.mac";

macro ExecuteStep( doc, FDoc, DocKind, ID_Operation, ID_Step )

  record deal(dvndeal);
  var FD;
  var ДатаИсполненияШага:date;
  var DataSet;
  var isLastDate = false;

  SetBuff(deal, FDoc);
  FD = DVFirstDocFXDeal(DL_DVFXDEAL, deal);

  GetOprDate(DV_FXDEAL_OPRDATE_CLOSE, ДатаИсполненияШага);

  isLastDate = not DL_IsDayDyn(ДатаИсполненияШага, makeArray(DL_KeyPair("ObjectType",FD.ПолучитьКалендТип())), true);

  var sql = RSDCommand( " select t_purpose " +
                        "   from dpmpaym_dbt " +
                        "  where t_dockind     = ? " +
                        "    and t_documentid  = ? " +
                        "    and t_paymstatus  < ? " +
                        "    and t_paymstatus != ? " );
  sql.addParam("", RSDBP_IN, FD.Kind);
  sql.addParam("", RSDBP_IN, FD.ID);
  sql.addParam("", RSDBP_IN, PM_READY_TO_SEND);
  sql.addParam("", RSDBP_IN, PM_CLOSED_W_M_MOVEMENT);
  sql.execute();
  DataSet = TRsbDataSet(sql);

  /*PNV 493273****/  
  /*if( DataSet.MoveNext() )
     MsgBox("Не все платежи по операции закрыты");
     return 1;
  else*/
     if( ПИ_ЗакрыватьСчетаПоСделке() )
        sql = RSDCommand( " select categ.t_code, accdoc.t_account, accdoc.t_currency, accdoc.t_chapter, accdoc.t_firole,  " +
                          " (select max (t_restdate)  " +
                          " from drestdate_dbt rdt " +
                          " where rdt.t_accountid = " +
                          "          (select acc.t_accountid " +
                          "             from daccount_dbt acc " +
                          "             where     acc.t_chapter = accdoc.t_chapter " +
                          "                   and acc.t_account = accdoc.t_account " +
                          "                   and acc.t_code_currency = accdoc.t_currency)) as t_maxdate " +
                          " from dmcaccdoc_dbt accdoc, dmccateg_dbt categ,  dmctempl_dbt Templ " +
                          " where accdoc.t_dockind = ? " +
                          "   and accdoc.t_docid = ? " +
                          "   and accdoc.t_catid = categ.t_id " +
                          "   and categ.t_updatemode = 0 " +
                          "   and  templ.T_CATID = categ.T_ID " +
                          "   and accdoc.t_TemplNum = templ.t_Number "+
                          "   and categ.t_code not in ('+Форвард, прочие0', '-Форвард, прочие0') " +
                          "   and (/*exists( select * " +
                          "                  from daccount_dbt acc " +
                          "                 where acc.t_chapter = accdoc.t_chapter " +
                          "                   and acc.t_account = accdoc.t_account " +
                          "                   and acc.t_code_currency = accdoc.t_currency " +
                          "                   and acc.t_close_date = '01.01.0001' )" 
                          "                   and( ( (Categ.t_Param1 = " + string( OBJTYPE_DV_KIND_ACCOUNTING) + " ) and (Categ.t_Class1 = " + string( LLCLASS_DV_KIND_ACCOUNTING) + " ) and (Templ.t_Value1 <> 2) ) OR " +
                          "                        ( (Categ.t_Param2 = " + string( OBJTYPE_DV_KIND_ACCOUNTING) + " ) and (Categ.t_Class2 = " + string( LLCLASS_DV_KIND_ACCOUNTING) + " ) and (Templ.t_Value2 <> 2) ) OR " +
                          "                        ( (Categ.t_Param3 = " + string( OBJTYPE_DV_KIND_ACCOUNTING) + " ) and (Categ.t_Class3 = " + string( LLCLASS_DV_KIND_ACCOUNTING) + " ) and (Templ.t_Value3 <> 2) ) OR " +
                          "                        ( (Categ.t_Param4 = " + string( OBJTYPE_DV_KIND_ACCOUNTING) + " ) and (Categ.t_Class4 = " + string( LLCLASS_DV_KIND_ACCOUNTING) + " ) and (Templ.t_Value4 <> 2) ) OR " +
                          "                        ( (Categ.t_Param5 = " + string( OBJTYPE_DV_KIND_ACCOUNTING) + " ) and (Categ.t_Class5 = " + string( LLCLASS_DV_KIND_ACCOUNTING) + " ) and (Templ.t_Value5 <> 2) ) OR " +
                          "                        ( (Categ.t_Param6 = " + string( OBJTYPE_DV_KIND_ACCOUNTING) + " ) and (Categ.t_Class6 = " + string( LLCLASS_DV_KIND_ACCOUNTING) + " ) and (Templ.t_Value6 <> 2) ) OR " +
                          "                        ( (Categ.t_Param7 = " + string( OBJTYPE_DV_KIND_ACCOUNTING) + " ) and (Categ.t_Class7 = " + string( LLCLASS_DV_KIND_ACCOUNTING) + " ) and (Templ.t_Value7 <> 2) ) OR " +
                          "                        ( (Categ.t_Param8 = " + string( OBJTYPE_DV_KIND_ACCOUNTING) + " ) and (Categ.t_Class8 = " + string( LLCLASS_DV_KIND_ACCOUNTING) + " ) and (Templ.t_Value8 <> 2) ) ) " +
                          "        or */ ( (DBMS_LOB.SUBSTR(accdoc.t_account, 5, 1) in('61601','52601','52602'))" +  /*PNV*/
                          "        or (DBMS_LOB.SUBSTR(accdoc.t_account, 3, 1) in('933','934','939','940','963','964','969','970')) )" + /*PNV*/
                          "       )"
                        );
        sql.addParam("", RSDBP_IN, FD.Kind);
        sql.addParam("", RSDBP_IN, FD.ID);
        DataSet = TRsbDataSet(sql);
        while( DataSet.MoveNext() )

           var closeDate = ДатаИсполненияШага;
           var maxDate = SQL_ConvTypeDate(DataSet.maxdate);
           if (isLastDate and (ValType(maxDate) == V_DATE) and (maxDate > date(0,0,0)))
              closeDate = maxDate;
           end;

           var rest = abs(RestA(DataSet.account, closeDate, NULL, DataSet.chapter, DataSet.currency)) +
                      abs(RestA(DataSet.account, date(31,12,9999), NULL, DataSet.chapter, DataSet.currency));

           if( rest > 0 )
              MsgBox("Не нулевой остаток на счете " + DataSet.account);
              return 1;
           elif( MC_FindAndCloseAccount(DataSet.code, fd, closeDate, DataSet.firole, DataSet.currency, MC_ACC_CLOSE_INDIVIDUAL_INDATE) )
              MsgBox("Невозможно закрыть счет " + DataSet.account);
              return 1;
           end;
        end;
     end;
  //end;
  /*PNV 493273****/  

  if( not InsertOprStatus(DV_FX_OPERSTATUS_KIND_DOC, DV_FX_OPERSTATUS_DOC_CLOSE) )
     MsgBox("Ошибка при установке статуса <Документооборот> по операции.");
     return 1;
  end;

  return 0;
end;
