/*
$Name:        dvfx030.mac
$Module:      Производные инструменты
$Description: Конверсионная операция. Шаг "Постановка на внебаланс"
*/
import InsCarryDoc, "dv_categ.mac", "dv_car.mac", "dv_period.mac";

private macro НужноСтавитьНаБаланс(FD):bool
  if ( (FD.СрокСделки() != DV_PERIODCLS_T0) and  
        ( (not FD.IsClient()) OR
          (FD.IsBNote() and (FD.ВалютаБазовогоАктива()!=FD.ВалютаКонтрАктива()) and RegVal_УчетРазноВалютныхБанкнотныхСделок() )
        )     
     )
     return true;
  end;
  return false;  
end;

private macro ПоставитьЧастьСделкиНаВнебаланс( FD, doc, ДатаИсполненияШага ):integer

  var corr = TRecHandler("account.dbt");
  var outBalReq = TRecHandler("account.dbt"), 
      outBalCom = TRecHandler("account.dbt");

  if ( not НужноСтавитьНаБаланс(FD) )
    return 0; 
  end;

  var датаОткрСчетов = DL_GetBalanceDateAfterWorkDayByCalendar(FD.ДатаСделки(),0,FD.ПолучитьКалендСвязанный());

  if( FD.ДатаИсполнения() != FD.ДатаСделки() )
     if( not DV_ОбновитьСтатусЧастиСделки(FD.nFI, DL_LEG_OUTBAL) )
        MsgBox("Ошибка при изменении статуса сделки");
        return 1;
     end;

     if ((FD.deal.rec.kind == 12730) or (FD.deal.rec.kind == 12735) or (FD.deal.rec.kind == 22730))
	 
        if( not FD.OpenAccount("-Форвард, прочие", null, false, FIROLE_FICOM, outBalCom, FD.SetAccOpenDate(датаОткрСчетов)) )
           return 1;
        end;
     
        if( not FD.OpenAccount("+Форвард, прочие", null, false, FIROLE_FIREQ, outBalReq, FD.SetAccOpenDate(датаОткрСчетов)) )
           return 1;
        end;
     
	 else
     if( not FD.IsExistAccount("-Форвард, прочие", null, true, FIROLE_FICOM, outBalCom, null, датаОткрСчетов) )
        if( not FD.OpenAccount("-Форвард, прочие", null, false, FIROLE_FICOM, outBalCom, FD.SetAccOpenDate(датаОткрСчетов)) )
           return 1;
        end;
     end;

     if( not FD.IsExistAccount("+Форвард, прочие", null, true, FIROLE_FIREQ, outBalReq, null, датаОткрСчетов) )
        if( not FD.OpenAccount("+Форвард, прочие", null, false, FIROLE_FIREQ, outBalReq, FD.SetAccOpenDate(датаОткрСчетов)) )
           return 1;
        end;
     end;
	 end;

     FD.SetFIIDForCorAccNum(FD.ВалютаТребования());
     if( not FD.IsExistAccount("СчКорреспГлаваГ", null, false, FD.РольСчКорреспГлаваГВнб(FIROLE_CORACC_ACTIVE), corr, null, датаОткрСчетов) )
        if( not FD.OpenAccount("СчКорреспГлаваГ", null, false, FD.РольСчКорреспГлаваГВнб(FIROLE_CORACC_ACTIVE), corr, FD.SetAccOpenDate(датаОткрСчетов)) )
           return 1;
        end;
     end;
     if( not ПроводкаПоКатегориямУчета( FD,
                                        outBalReq, corr,
                                        ДатаИсполненияШага,
                                        4,
                                        FD.ВалютаТребования(),
                                        FD.СуммаТребования(),
                                        doc,
                                        INPCARRY, "", "",
                                        "Постановка требований на внебалансовый учет по" + IIF(FD.DealPart == 1," сделке "," второй части сделки ") + FD.DealCode()+" от "+FD.Deal.rec.date + ". Контрагент: "+ DV_GetPartyName (FD.Deal.rec.contractor),/*CHVA  511666*/
                                        null,
                                        FIROLE_FIREQ, null
                                      )
       )
        return 1;
     end;

     FD.SetFIIDForCorAccNum(FD.ВалютаОбязательства());
     if( not FD.IsExistAccount("СчКорреспГлаваГ", null, false, FD.РольСчКорреспГлаваГВнб(FIROLE_CORACC_PASSIVE), corr, null, датаОткрСчетов) )
        if( not FD.OpenAccount("СчКорреспГлаваГ", null, false, FD.РольСчКорреспГлаваГВнб(FIROLE_CORACC_PASSIVE), corr, FD.SetAccOpenDate(датаОткрСчетов)) )
           return 1;
        end;
     end;
     if( not ПроводкаПоКатегориямУчета( FD,
                                        corr, outBalCom,
                                        ДатаИсполненияШага,
                                        4,
                                        FD.ВалютаОбязательства(),
                                        FD.СуммаОбязательства(),
                                        doc,
                                        INPCARRY, "", "",
                                        "Постановка обязательств на внебалансовый учет по" + IIF(FD.DealPart == 1," сделке "," второй части сделки ") + FD.DealCode()+" от "+FD.Deal.rec.date + ". Контрагент: "+ DV_GetPartyName (FD.Deal.rec.contractor),/*CHVA  511666*/
                                        null,
                                        null, FIROLE_FICOM
                                      )
       )
        return 1;
     end;
  end;

  return 0;
end;

private macro СВОП_ПоставитьЧастьСделкиНаВнебаланс( FD, doc, ДатаИсполненияШага ):integer

  record accdoc_plus(mcaccdoc);
  record accdoc_minus(mcaccdoc);
  var DebAccBuf  = TRecHandler("account");
  var CredAccBuf = TRecHandler("account");
  var corr = TRecHandler("account.dbt");
  var NeedTransfer:bool = false;
  var DebAcc:string  = ""; var DebFIID:integer  = ALLFININSTR;  var DebFiRole  = FIROLE_UNDEF;
  var CredAcc:string = ""; var CredFIID:integer = ALLFININSTR;  var CredFiRole = FIROLE_UNDEF;

  if( FD.ДатаИсполнения() != FD.ДатаСделки() )
     if( not DV_ОбновитьСтатусЧастиСделки(FD.nFI, DL_LEG_OUTBAL) )
        MsgBox("Ошибка при изменении статуса сделки");
        return 1;
     end;

     DebFIID = FD.ВалютаТребования();
     CredFIID = FD.ВалютаОбязательства();
     
     DebAcc = "+Форвард, дрейф внебирж";
     CredAcc = "-Форвард, дрейф внебирж";
     
     DebFiRole  = FIROLE_FIREQ;
     CredFiRole  = FIROLE_FICOM;
    
     if( (not FD.OpenAccount( DebAcc,  null, null, DebFiRole,  DebAccBuf,  ДатаИсполненияШага, DebFIID,  null, accdoc_plus ) ) OR
         (not FD.OpenAccount( CredAcc, null, null, CredFiRole, CredAccBuf, ДатаИсполненияШага, CredFIID, null, accdoc_minus ) ) )
        return 1;
     end;
    
     /*проверяем, существует ли счет для того, чтобы не лезла ошибка, что такой счет уже существует #210153*/
     FD.SetFIIDForCorAccNum(DebFIID);
     if( not FD.IsExistAccount( "СчКорреспГлаваГ", null, false, FD.РольСчКорреспГлаваГВнб(FIROLE_CORACC_ACTIVE), corr, null, ДатаИсполненияШага ) )
        if( (not FD.OpenAccount( "СчКорреспГлаваГ", null, false, FD.РольСчКорреспГлаваГВнб(FIROLE_CORACC_ACTIVE), corr, ДатаИсполненияШага ) ) )
           return 1;
        end;
     end;
     if( not ПроводкаПоКатегориямУчета( FD,
                                        DebAccBuf, corr,
                                        ДатаИсполненияШага,
                                        4,
                                        FD.ВалютаТребования(),
                                        FD.СуммаТребования(),
                                        doc,
                                        INPCARRY, "", "",
                                        "Постановка требований на внебалансовый учет по" + IIF(FD.DealPart == 1," сделке "," второй части сделки ") + FD.DealCode() +" от "+FD.Deal.rec.date + ". Контрагент: "+ DV_GetPartyName (FD.Deal.rec.contractor)
                                      )
       )
        return 1;
     end;
    
     FD.SetFIIDForCorAccNum(CredFIID);
     if( not FD.IsExistAccount( "СчКорреспГлаваГ", null, false, FD.РольСчКорреспГлаваГВнб(FIROLE_CORACC_PASSIVE), corr, null, ДатаИсполненияШага ) )
        if( (not FD.OpenAccount( "СчКорреспГлаваГ", null, false, FD.РольСчКорреспГлаваГВнб(FIROLE_CORACC_PASSIVE), corr, ДатаИсполненияШага ) ) )
           return 1;
        end;
     end;
     if( not ПроводкаПоКатегориямУчета( FD,
                                        corr, CredAccBuf,
                                        ДатаИсполненияШага,
                                        4,
                                        FD.ВалютаОбязательства(),
                                        FD.СуммаОбязательства(),
                                        doc,
                                        INPCARRY, "", "",
                                        "Постановка обязательств на внебалансовый учет по" + IIF(FD.DealPart == 1," сделке "," второй части сделки ") + FD.DealCode() +" от "+FD.Deal.rec.date + ". Контрагент: "+ DV_GetPartyName (FD.Deal.rec.contractor)
                                      )
       )
        return 1;
     end;

     var TransfDate:date = date(0,0,0);
     if( ПереноситьПоСрокам(FD, ДатаИсполненияШага, @TransfDate, true, accdoc_plus.PeriodID, accdoc_minus.PeriodID, DebAcc, CredAcc, DebFIID, CredFIID, DebFiRole, CredFiRole, FD.ДатаИсполнения()) )
        NeedTransfer = true;
        DL_CalendDefineOprDate(FD, IIF( FD.DealPart == 1, DV_FXDEAL_OPRDATE_COTERMS, DV_FXDEAL_OPRDATE_COTERMS_2), TransfDate );
     end;
    
     if( not InsertOprStatus( IIF(FD.DealPart == 1, DV_FX_OPERSTATUS_KIND_COTERMS, DV_FX_OPERSTATUS_KIND_COTERMS_2), IIF(NeedTransfer, DV_OPERSTATUS_COTERMS_TRANSFER, DV_OPERSTATUS_COTERMS_NOTRANSFER) ) )
        MsgBox("Ошибка при установке статуса <Перенос по срокам> для операции.");
        return 1;
     end;

     if( not NeedTransfer )
        if( not InsertOprStatus(DV_FX_OPERSTATUS_KIND_BALANCE, DV_FX_OPERSTATUS_DL_RUN) )
           MsgBox("Ошибка при установке статуса <Баланс> по операции.");
           return 1;
        end;
     end;
  else
     if( not InsertOprStatus(DV_FX_OPERSTATUS_KIND_BALANCE, DV_FX_OPERSTATUS_DL_RUN) )
        MsgBox("Ошибка при установке статуса <Баланс> по операции.");
        return 1;
     end;
  end;

  return 0;
end;

macro ExecuteStep( doc, FDoc, DocKind, ID_Operation, ID_Step )

  record deal(dvndeal);
  var FrVal = TRecHandler("dvnfrval");
  var FD, FD2;
  var ДатаИсполненияШага:date;

  SetBuff(deal, FDoc);
  FD = DVFirstDocFXDeal(DL_DVFXDEAL, deal);

  GetOprDate(DV_FXDEAL_OPRDATE_BEGIN_OP, ДатаИсполненияШага);

  if( FD.IsSWAP() )/*ветка для учета и закрытия старых сделок закрытой операции 2740*/
/*
     if( (not FD.IsClient()) and (not FD.ВалютныйРынок()) )
        /* Если в таблице DDVNFRVAL_DBT нет записи по сделке за дату заключения  */
        if( not FD.ВыполненаПереоценкаСС( ДатаИсполненияШага, FrVal ) )
           FrVal.rec.DealID       = FD.Deal.rec.Id;
           FrVal.rec.DocKind      = FD.Deal.rec.DocKind;
           FrVal.rec.Date         = ДатаИсполненияШага;
           FrVal.rec.FairValueAlg = FD.nFI.rec.FairValueAlg;
           if( DV_InsFrValPanel(FrVal) == 0 )
              if( DV_InsertFrVal(FrVal) != 0 )
                 MsgBox("Ошибка при вставке записи оценки справедливой стоимости.");
                 return 1;
              end;
           else
              return 1;
           end;
        end;
        /* Выполнить проводки по учету СС и премии*/
        if( FrVal.rec.FairValue != 0 )
           var DebAcc:string  = "", CredAcc:string = "";
           var ИспользоватьВыбытие:bool = false;
        
           if( (FrVal.rec.InterimPayDate != SET_CHAR) or
               ((FrVal.rec.InterimPayDate == SET_CHAR) and ПИ_НеИсп61601ПостСВОП() and (FD.ДатаИсполнения() <= GetDateAfterWorkDays(FD.Deal.rec.Date, 2)) )
             )
              ИспользоватьВыбытие = false;
           else
              ИспользоватьВыбытие = true;
           end;
        
           if( FrVal.rec.FairValue > 0 )
              DebAcc  = "+ПФИ";
              CredAcc = IIF(ИспользоватьВыбытие, "Выбытие ПФИ", "Доходы ПФИ");
           elif( FrVal.rec.FairValue < 0 )
              DebAcc  = IIF(ИспользоватьВыбытие, "Выбытие ПФИ", "Расходы ПФИ");
              CredAcc = "-ПФИ";
           end;
        
           if( not ПроводкаПоКатегориямУчета( FD,
                                              DebAcc, CredAcc,
                                              ДатаИсполненияШага, 1,
                                              NATCUR, abs(FrVal.rec.FairValue),
                                              doc,
                                              INPCARRY, "", "",
                                              "Учет справедливой стоимости при первоначальном признании"
                                            )
             )
              return 1;
           end;
        end;
     end;

*/
     if( СВОП_ПоставитьЧастьСделкиНаВнебаланс(FD, doc, ДатаИсполненияШага) != 0 )
        return 1;
     end;
     FD2 = DVFirstDocFXDeal(DL_DVFXDEAL, deal, 2);
     if( СВОП_ПоставитьЧастьСделкиНаВнебаланс(FD2, doc, ДатаИсполненияШага) != 0 )
        return 1;
     end;
  else
     if( ПоставитьЧастьСделкиНаВнебаланс(FD, doc, ДатаИсполненияШага) != 0 )
        return 1;
     end;
  end;

  if( FD.IsBNote() and (GetOprStatus(DV_FX_OPERSTATUS_KIND_OFFBAL_CHDEAL) == DV_FX_OPERSTATUS_DL_RUN) and (GetOprStatus(DV_FX_OPERSTATUS_KIND_OFFBALANCE) == DV_FX_OPERSTATUS_DL_COMPLETE))
      if( not InsertOprStatus(DV_FX_OPERSTATUS_KIND_OFFBAL_CHDEAL, DV_FX_OPERSTATUS_DL_COMPLETE) )
        MsgBox("Ошибка при установке статуса <Внебаланс> по операции.");
        return 1;
      end;
  else
  if( not InsertOprStatus(DV_FX_OPERSTATUS_KIND_OFFBALANCE, DV_FX_OPERSTATUS_DL_COMPLETE) )
     MsgBox("Ошибка при установке статуса <Внебаланс> по операции.");
     return 1;
  end;

  if( not FD.IsSWAP() )
     if( not InsertOprStatus(DV_FX_OPERSTATUS_KIND_BALANCE, DV_FX_OPERSTATUS_DL_RUN) )
        MsgBox("Ошибка при установке статуса <Баланс> по операции.");
        return 1;
     end;
  end;
  end;
 

  return 0;
end;
