/*
$Name:        dvfx040.mac
$Module:      Производные инструменты
$Description: Конверсионная операция. Шаг "Переоценка т/о по поставке"
*/
import InsCarryDoc, "dv_categ.mac", "dv_car.mac";

macro ExecuteStep( doc, FDoc, DocKind, ID_Operation, ID_Step )
       
  record tick(dvndeal);
  var FD, FD2;
  var ДатаИсполненияШага:date;
  var isBloomDeal = 0; /*PNV*/

  SetBuff(tick, FDoc);
  FD = DVFirstDocFXDeal(DL_DVFXDEAL, tick);
  GetOprDate(DV_FXDEAL_OPRDATE_BEGIN_OP, ДатаИсполненияШага);

  /*PNV*/
  if (not GetMainObjAttr( null, OBJTYPE_FXOPER_DV, strLpad(string(FD.deal.rec.id), 34, "0"), 5, isBloomDeal))
    isBloomDeal = 0;
  end;

  if (isBloomDeal != 3)/*PNV не через bloomberg*/
      if ( ПИКО_ПровестиПереоценкуЧастиСделки(FD, doc, ДатаИсполненияШага) != 0 )
           return 1;
      end;  
  end;
  /*PNV*/

  if( FD.IsSWAP() )
    FD2 = DVFirstDocFXDeal(DL_DVFXDEAL, tick, 2);
    if ( ПИКО_ПровестиПереоценкуЧастиСделки(FD2, doc, ДатаИсполненияШага) != 0 )
       return 1;
    end;
  end;

  if( not (FD.IsBNote() and (GetOprStatus(DV_FX_OPERSTATUS_KIND_OFFBAL_CHDEAL) == DV_FX_OPERSTATUS_DL_COMPLETE)))
  if( not InsertOprStatus(DV_FX_OPERSTATUS_KIND_BALANCE, DV_FX_OPERSTATUS_DL_RUN) )
    MsgBox("Ошибка при установке статуса <Баланс> по операции.");
    return 1;
  end;
  end;

return 0; 
End;
