/*
$Name:        dvndeal_modify.mac
$Module:      Производные инструменты
$Description: Функции для запуска изменения условий сделок.
*/

import DVInter;

// запуск операции изменения условий для форварда и покупки/продажи Т+3
// возвращает 0 в случае успеха
// id          dnvdeal.id
// Time1       время сделки
// Amount      количество БА 
// Cost        стоимость БА
// OpenDate    признак открытой даты 
// Price       Цена единицы БА
// Point       точность цены
// PriceFIID   валюта цены
// ExecDate    Дата исполнения
// PayDate     дата оплаты
// SuplDate    дата поставки
// MsgError    выводить (TRUE) запросы на экран
macro dv_modify_forward(id, Time1, Amount, Cost, OpenDate, Price, Point, PriceFIID, ExecDate, PayDate, SuplDate, MsgError):integer
   var d2 = TRecHandler("dvndeal.dbt");
   var f2 = TRecHandler("dvnfi.dbt");
   var d1 = TBFile("dvndeal.dbt");
   var stat:integer;

   d1.rec.ID = Id;
   if(not d1.GetEQ())
      return 1;
   end;
   Copy(d2, d1);
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv, f2);
   if( stat != 0) return stat; end;

   if(Time1 != NULL) d2.rec.Time = Time1; end;
   if(Amount != NULL) f2.rec.Amount = Amount; end; 
   if(Cost != NULL) f2.rec.Cost = Cost; end;  
   if(OpenDate != NULL) f2.rec.OpenDate = OpenDate; end; 
   if(Price != NULL) f2.rec.Price = Price; end;      
   if(Point != NULL )f2.rec.Point = Point; end;       
   if(PriceFIID != NULL) f2.rec.PriceFIID = PriceFIID; end;
   if(ExecDate != NULL) f2.rec.ExecDate = ExecDate; end; 
   if(PayDate != NULL) f2.rec.PayDate = PayDate; end;   
   if(SuplDate != NULL) f2.rec.SuplDate = SuplDate; end; 


   stat = DV_RunChangingConditions(d2, f2, NULL, MsgError);
   return stat;
end;

// запуск операции изменения условий для опциона
// возвращает 0 в случае успеха
// id          dnvdeal.id
// Time1       время сделки
// Cost        стоимость БА
// OpenDate    признак открытой даты 
// OptionStyle стиль опциона 
// Bonus       сумма премии
// BonusDate   дата оплаты премии
// BonusPrice  Премия за единицу БА
// Amount      количество БА 
// Price       Цена единицы БА
// Point       точность цены
// PriceFIID   валюта цены
// ExecDate    Дата исполнения
// ExecTime    время исполнения
// PayDate     дата оплаты
// SuplDate    дата поставки
// ExpiryDate  Дата истечения срока действия
// AccFIID     ID валюты расчетов
// MsgError    выводить (TRUE) запросы на экран
macro dv_modify_option(id, Time1, OptionStyle, Bonus, BonusDate, BonusPrice, Amount, Price, Point, PriceFIID, ExecDate, ExecTime, PayDate, SuplDate, ExpiryDate, AccFIID, MsgError):integer
   var d2 = TRecHandler("dvndeal.dbt");
   var f2 = TRecHandler("dvnfi.dbt");
   var d1 = TBFile("dvndeal.dbt");
   var stat:integer;

   d1.rec.ID = Id;
   if(not d1.GetEQ())
      return 1;
   end;
   Copy(d2, d1);
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv, f2);
   if( stat != 0) return stat; end;

   if(Time1 != NULL) d2.rec.Time = Time1; end;  
   if(OptionStyle != NULL) d2.rec.OptionStyle = OptionStyle; end;
   if(Bonus != NULL) d2.rec.Bonus = Bonus; end;
   if(BonusDate != NULL) d2.rec.BonusDate = BonusDate; end;
   if(BonusPrice != NULL) d2.rec.BonusPrice = BonusPrice; end;

   if(ExecDate != NULL) f2.rec.ExecDate = ExecDate; end; 
   if(ExecTime != NULL) f2.rec.ExecTime = ExecTime; end;
   if(Amount != NULL) f2.rec.Amount = Amount; end;      
   if(Price != NULL) f2.rec.Price = Price; end;       
   if(PriceFIID != NULL) f2.rec.PriceFIID = PriceFIID; end;
   if(Point != NULL )f2.rec.Point = Point; end;       
   if(PayDate != NULL) f2.rec.PayDate = PayDate; end; 
   if(SuplDate != NULL) f2.rec.SuplDate = SuplDate; end; 
   if(AccFIID != NULL) f2.rec.AccFIID = AccFIID; end;    
   if(ExpiryDate != NULL) f2.rec.ExpiryDate = ExpiryDate; end; 

   stat = DV_RunChangingConditions(d2, f2, NULL, MsgError);
   return stat;
end;

// запуск операции изменения условий для валютного свопа
// возвращает 0 в случае успеха
// id          dnvdeal.id
// Time1       время сделки
// Amount      Сумма БА
// Cost        Сумма КА части 1
// Cost2       Сумма КА части 2
// PriceFIID   валюта КА
// PayDate     Дата поставки КА части 1
// SuplDate    Дата поставки БА части 1
// PayDate2    Дата поставки КА части 2
// SuplDate2   Дата поставки БА части 2
// MsgError    выводить (TRUE) запросы на экран
macro dv_modify_curswap(id, Time1, Amount, Cost, Cost2, PriceFIID, PayDate, SuplDate, PayDate2, SuplDate2, MsgError ):integer
   var d2 = TRecHandler("dvndeal.dbt");
   var f2 = TRecHandler("dvnfi.dbt");
   var f22 = TRecHandler("dvnfi.dbt");
   var d1 = TBFile("dvndeal.dbt");
   var stat:integer;

   d1.rec.ID = Id;
   if(not d1.GetEQ())
      return 1;
   end;
   Copy(d2, d1);
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv, f2);
   if( stat != 0) return stat; end;
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv2, f22);
   if( stat != 0) return stat; end;

   if(Time1 != NULL) d2.rec.Time = Time1; end;
   if(Amount != NULL) 
      f2.rec.Amount = Amount;
      f22.rec.Amount = Amount;  
   end;      
   if(PriceFIID != NULL) 
      f2.rec.PriceFIID = PriceFIID;
      f22.rec.PriceFIID = PriceFIID; 
   end;
   if(PayDate != NULL) f2.rec.PayDate = PayDate; end; 
   if(SuplDate != NULL) f2.rec.SuplDate = SuplDate; end; 
   if(PayDate2 != NULL) f22.rec.PayDate = PayDate2; end; 
   if(SuplDate2 != NULL) f22.rec.SuplDate = SuplDate2; end; 
   if(Cost != NULL) f2.rec.Cost = Cost; end;
   if(Cost2 != NULL) f22.rec.Cost = Cost2; end;          

   stat = DV_RunChangingConditions(d2, f2, f22, MsgError);
   return stat;
end;

// запуск операции изменения условий для процентного свопа
// возвращает 0 в случае успеха
// id          dnvdeal.id
// Time1       время сделки
// Amount      Сумма БА требования
// Amount2     Сумма БА обязательства
// MsgError    выводить (TRUE) запросы на экран
macro dv_modify_prcswap(id, Time1, Amount, Amount2, MsgError ):integer
   var d2 = TRecHandler("dvndeal.dbt");
   var f2 = TRecHandler("dvnfi.dbt");
   var f22 = TRecHandler("dvnfi.dbt");
   var d1 = TBFile("dvndeal.dbt");
   var stat:integer;

   d1.rec.ID = Id;
   if(not d1.GetEQ())
      return 1;
   end;
   Copy(d2, d1);
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv, f2);
   if( stat != 0) return stat; end;
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv2, f22);
   if( stat != 0) return stat; end;

   if(Time1 != NULL) d2.rec.Time = Time1; end;  
   if(Amount != NULL) f2.rec.Amount = Amount; end;      
   if(Amount2 != NULL) f22.rec.Amount = Amount2; end;      
   if(f22.rec.IsInverse)
      if(f2.rec.Amount > 0 )
         f22.rec.Course = f22.rec.Amount/f2.rec.Amount;
      end;
   else
      if(f22.rec.Amount > 0 )
         f22.rec.Course = f2.rec.Amount/f22.rec.Amount;
      end;
   end;
   stat = DV_RunChangingConditions(d2, f2, f22, MsgError);
   return stat;
end;


// запуск операции изменения условий для свопа
// возвращает 0 в случае успеха
// id          dnvdeal.id
// Time1       время сделки
// Amount      Сумма БА
// Cost        Сумма КА части 1
// Cost2       Сумма КА части 2
// PriceFIID   валюта КА
// PayDate     Дата поставки КА части 1
// SuplDate    Дата поставки БА части 1
// PayDate2    Дата поставки КА части 2
// SuplDate2   Дата поставки БА части 2
// MsgError    выводить (TRUE) запросы на экран
macro dv_modify_fxswap(id, Time1, Amount, Cost, Cost2, PriceFIID, PayDate, SuplDate, PayDate2, SuplDate2, MsgError ):integer
   var d2 = TRecHandler("dvndeal.dbt");
   var f2 = TRecHandler("dvnfi.dbt");
   var f22 = TRecHandler("dvnfi.dbt");
   var d1 = TBFile("dvndeal.dbt");
   var stat:integer;

   d1.rec.ID = Id;
   if(not d1.GetEQ())
      return 1;
   end;
   Copy(d2, d1);
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv, f2);
   if( stat != 0) return stat; end;
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv2, f22);
   if( stat != 0) return stat; end;

   if(Time1 != NULL) d2.rec.Time = Time1; end; 
   if(Amount != NULL) 
      f2.rec.Amount = Amount;
      f22.rec.Amount = Amount; 
   end;      
   if(PriceFIID != NULL) 
      f2.rec.PriceFIID = PriceFIID;
      f22.rec.PriceFIID = PriceFIID; 
   end;
   if(PayDate != NULL) f2.rec.PayDate = PayDate; end; 
   if(SuplDate != NULL) f2.rec.SuplDate = SuplDate; end; 
   if(PayDate2 != NULL) f22.rec.PayDate = PayDate2; end; 
   if(SuplDate2 != NULL) f22.rec.SuplDate = SuplDate2; end; 
   if(Cost != NULL) f2.rec.Cost = Cost; end;
   if(Cost2 != NULL) f22.rec.Cost = Cost2; end;          

   stat = DV_RunChangingConditions(d2, f2, f22, MsgError);
   return stat;
end;

// запуск операции изменения условий для банкнотной сделки
// возвращает 0 в случае успеха
// id          dnvdeal.id
// Amount      Сумма БА
// Cost        Сумма КА
// PriceFIID   валюта КА
// PayDate     Дата валютирования КА
// SuplDate    Дата валютирования БА
// MsgError    выводить (TRUE) запросы на экран
macro dv_modify_fxbnote(id, Amount, Cost, PriceFIID, PayDate, SuplDate, MsgError ):integer
   var d2 = TRecHandler("dvndeal.dbt");
   var f2 = TRecHandler("dvnfi.dbt");
   var d1 = TBFile("dvndeal.dbt");
   var stat:integer;

   d1.rec.ID = Id;
   if(not d1.GetEQ())
      return 1;
   end;
   Copy(d2, d1);
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv, f2);
   if( stat != 0) return stat; end;

   if(Amount != NULL) f2.rec.Amount = Amount; end;      
   if(PriceFIID != NULL) f2.rec.PriceFIID = PriceFIID; end;
   if(PayDate != NULL) f2.rec.PayDate = PayDate; end; 
   if(SuplDate != NULL) f2.rec.SuplDate = SuplDate; end; 
   if(Cost != NULL) f2.rec.Cost = Cost; end;

   stat = DV_RunChangingConditions(d2, f2, NULL, MsgError);
   return stat;
end;

// запуск операции изменения условий для конверсионной операции Покупка/Продажа
// возвращает 0 в случае успеха
// id          dnvdeal.id
// Amount      Сумма БА
// Cost        Сумма КА
// PriceFIID   валюта КА
// PayDate     Дата валютирования КА
// SuplDate    Дата валютирования БА
// MsgError    выводить (TRUE) запросы на экран
macro dv_modify_fxdeal(id, Amount, Cost, PriceFIID, PayDate, SuplDate, MsgError ):integer
   var d2 = TRecHandler("dvndeal.dbt");
   var f2 = TRecHandler("dvnfi.dbt");
   var d1 = TBFile("dvndeal.dbt");
   var stat:integer;

   d1.rec.ID = Id;
   if(not d1.GetEQ())
      return 1;
   end;
   Copy(d2, d1);
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv, f2);
   if( stat != 0) return stat; end;

   if(Amount != NULL) f2.rec.Amount = Amount; end;      
   if(PriceFIID != NULL) f2.rec.PriceFIID = PriceFIID; end;
   if(PayDate != NULL) f2.rec.PayDate = PayDate; end; 
   if(SuplDate != NULL) f2.rec.SuplDate = SuplDate; end; 
   if(Cost != NULL) f2.rec.Cost = Cost; end;

   stat = DV_RunChangingConditions(d2, f2, NULL, MsgError);
   return stat;
end;

// запуск операции изменения условий для свопа
// возвращает 0 в случае успеха
// id          dnvdeal.id
// PayDate     Плановая дата оплаты 
// SuplDate    Плановая дата поставки
// SuplTime    Плановая время поставки
// MsgError    выводить (TRUE) запросы на экран
macro dv_modify_fxmet(id, PayDate, SuplDate, SuplTime, MsgError ):integer
   var d2 = TRecHandler("dvndeal.dbt");
   var f2 = TRecHandler("dvnfi.dbt");
   var d1 = TBFile("dvndeal.dbt");
   var stat:integer;

   d1.rec.ID = Id;
   if(not d1.GetEQ())
      return 1;
   end;
   Copy(d2, d1);
   stat = FindDVNFI(Id, DV_NFIType_BaseActiv, f2);
   if( stat != 0) return stat; end;

   if(PayDate != NULL) f2.rec.PayDate = PayDate; end; 
   if(SuplDate != NULL) f2.rec.SuplDate = SuplDate; end; 
   if(SuplTime != NULL) f2.rec.SuplTime = SuplTime; end;

   stat = DV_RunChangingConditions(d2, f2, NULL, MsgError);
   return stat;
end;




