/*
$Name:        dvopcur100.mac
$Module:      ФИССИКО
$Description: Операция "Расчеты на рынке СПФИ", Шаг Закрытие дня
*/
import InsCarryDoc, "dv_categ.mac";

MACRO ExecuteStep( Doc, FirstDoc, DocKind, ID_Operation, ID_Step )
  record oper(dvoper);

  SetBuff(oper, FirstDoc);
  var FD_Oper = DVFirstDocOper(DL_DVOPER, oper);

  var sql = DL_RSDCommand( " SELECT * " +
                           "   FROM ddvndeal_dbt deals, dpmpaym_dbt paym" +
                           "  WHERE     deals.t_MarketKind = " + DV_MARKETKIND_SPFIMARKET +
                           "        AND deals.t_State <> 0 " +
                           "        AND deals.t_Client = -1 " +
                           "        AND paym.t_DocumentID = DEALS.T_ID" +
                           "        AND DEALS.T_DOCKIND = PAYM.T_DOCKIND " +
                           "        AND paym.t_ValueDate = ? " +
                           "        AND PAYM.T_PAYMSTATUS NOT IN (32000, 150, 3000)" +/*PNV добавлен статус "на отправке"*/
                           "        AND (SELECT COUNT (1) NRec" +
                           "               FROM doprstep_dbt step, doproper_dbt oper" +
                           "              WHERE     oper.t_DocKind = DEALS.T_DOCKINd" +
                           "                    AND LTRIM (oper.t_DocumentID) = DEALS.T_ID" +
                           "                    AND step.t_ID_Operation = oper.t_ID_Operation" +
                           "                    AND step.t_IsExecute != 'X'" +
                           "                    AND step.t_Symbol != 'З') != 0"
                         ); 

  sql.addParam( FD_Oper.DVOper.rec.Date );
  var Data = sql.execute();

  if( Data.MoveNext() )
     MsgBox("Есть неисполненные ТО");
     return 1;
  end;
  sql = DL_RSDCommand( " SELECT count(1) NRec " +
                       "   FROM doprstep_dbt step, doproper_dbt oper " +
                       "  WHERE oper.t_DocKind             = ? " +
                       "    AND ltrim(oper.t_DocumentID)   = ?  " +
                       "    AND step.t_ID_Operation        = oper.t_ID_Operation " +
                       "    AND step.t_IsExecute           != 'X' "+ 
                       "    AND step.t_Symbol              != 'З' " +
                       "    AND step.t_Number_Step         <> 100 " // не равен текущему(100) шагу
                     ); 

  sql.addParam( FD_Oper.Kind );
  sql.addParam( FD_Oper.ID );
  Data = sql.execute();

  if( Data.MoveNext() and (SQL_ConvTypeInteger(Data.NRec) > 0) )
     MsgBox("В операции есть неисполненные шаги");
     return 1;
  end;

  sql = DL_RSDCommand( " SELECT LISTAGG(t_Code, ', ') WITHIN GROUP (ORDER BY t_Code) codeFI " +
                       "   FROM (SELECT comis.t_Code " +
                       "           FROM ddlcomis_dbt dlcomis, dsfcomiss_dbt comis " +
                       "          WHERE dlcomis.t_DocKind     = ? " +
                       "            AND dlcomis.t_DocID       = ? " +
                       "            AND dlcomis.t_FactPayDate = TO_DATE('01.01.0001', 'dd.mm.yyyy') " +
                       "            AND comis.t_FeeType       = dlcomis.t_FeeType   " +
                       "            AND comis.t_Number        = dlcomis.t_ComNumber " +
                       "          group by comis.t_Code " +
                       "        )"
                     );

  sql.addParam( FD_Oper.Kind );
  sql.addParam( FD_Oper.ID );

  Data = sql.execute();
  if( Data.MoveNext() and (SQL_ConvTypeStr(Data.codeFI) != "") )
     MsgBox("В операции есть неоплаченные комиссии: "+SQL_ConvTypeStr(Data.codeFI));
     return 1;
  end;

  if( not InsertOprStatus(DV_OPCUR_OPERSTATUS_KIND_DOC, DV_OPCUR_OPERSTATUS_COMPLETE) )
     MsgBox("Ошибка при установке статуса <Статус операции> по операции.");
     return 1;
  end;
 
  return 0;
end;


