import deprintr, BankInter, Printer;

const LPT1 = 0;

var
  DisableExitMacro = false, 
  OutputPrinted, 
  MacroOutput;

macro CheckPrinter( RegPath, ToScreen, PortName );

  var
   Port = LPT1,
   Type = V_STRING,
   Value,
   ErrCode,
   RepeatCheckPrint = TRUE;


  Message("Проверка готовности принтера...");
  if(GetRegistryValue(RegPath, Type, Value, ErrCode) == V_STRING)
    if(Value == "NUL")
      /*Не печатаем договор*/
      Message;
      Exit( 1 );
    elif(Value == "PRN")
      if(ToScreen == "\x00")
        if((ValType(PortName) == V_UNDEF) or (PortName == ""))
          PortName = "ШИРОКИЙ";
        end;
        Port = GetPrintPort( PortName );
        RepeatCheckPrint = TRUE;
        while (RepeatCheckPrint)
          if (CheckLocalPrinter(Port) == 0)
            if ( not IsOutputAccumulated )
              if ( not GetTrue( true, "Начать печать?" ) )
                Message;
                Exit( 1 );
              end;
            end;
            /*назначаем вывод на принтер*/
            RepeatCheckPrint = FALSE;
          else
            if (GetTrue(FALSE,"Принтер не готов! Переназначить вывод на экран?"))
              RepeatCheckPrint = FALSE;
            end;
          end;
        end;
      end;
    end;
    MacroOutput = Value;
  end;
  OutputPrinted = false;
  Message;
end;

macro PrintOutput

  var
    outFile;

  if ( MacroOutput != "PRN" )
    return;
  end;

  outFile = SetOutput( "nul" );
  PrintFile( outFile );
  if ( IsOutputAccumulated )
    DelFile( outFile );
  end;
end;

macro ExitMacro( noOutput )

  if ( DisableExitMacro )
    return;
  end;

  if ( noOutput != null )
    if ( noOutput )
      Exit( 1 );
    end;
  end;

  if ( ( MacroOutput == "PRN" ) )
    if ( not OutputPrinted )
      if ( IsOutputAccumulated )
        PrintOutput;
      else
        Exit( 2 );
      end;
    else
      Exit( 1 );
    end;
  else
    Exit( 0 );
  end;
end;

