
/* Компенсации за день */

file Compens("compens.dbt") key 1;

macro LastNameWithInitials;

  return Compens.LastName+" "+SubStr(Compens.FirstName,1,1)+"."+
    SubStr(Compens.PatrName,1,1)+".";
end;

macro OutHeader;

  println("                                                 Компенсации за "+
    String(Compens.Date));
  println;
  [┌─────────────────────────┬────────────────────────┬──────────┬──────────┬───────────────────┬─────────────┬───────────────────┬─────────────────────────┐];
  [│                         │                        │   Дата   │   Дата   │   Сумма вклада,   │ Коэффициент │       Сумма       │ Номер счета, на который │];
  [│  Н о м е р   с ч е т а  │ Фамилия И.О. вкладчика │ рождения │ закрытия │    подлежащая     │ компенсации │    компенсации    │ зачисляется компенсация │];
  [│                         │                        │ вкладчика│  счета   │    компенсации    │             │                   │                         │];
  [├─────────────────────────┼────────────────────────┼──────────┼──────────┼───────────────────┼─────────────┼───────────────────┼─────────────────────────┤];
end;

macro OutLine;

  [│#########################│########################│##########│##########│###################│#############│###################│#########################│]
  (
    Compens.Account,
    LastNameWithInitials,
    Compens.BirthDate,
    Compens.AccClsDate,
    Compens.CompensedSum,
    Compens.Rate,
    Compens.Sum,
    Compens.DestAccount
  );
end;

macro OutBottom;

  [└─────────────────────────┴────────────────────────┴──────────┴──────────┴───────────────────┴─────────────┴───────────────────┴─────────────────────────┘];
end;

  var
    RecFound,TheDate,{curdate};

  TheDate={curdate};
  GetDate(TheDate,"Введите дату");
  Compens.Date=TheDate;

  OutHeader;
  RecFound=GetEQ(Compens);
  while(RecFound and (Compens.Date==TheDate))
    OutLine;
    RecFound=Next(Compens);
  end;
  OutBottom;
end;




