/***************************************************************************\
| Ib_opinform.mac Система:RS-Retail Автор: Войновский М.                    |
| Информирование внешней системы об операции                                |
| Для шага "После завершения операции" операции                             |
\***************************************************************************/
 import deprintr, alg_vars, rsd, ic_aux;
/*---------- Инициализируемые структуры ---------------------------------*/
private var {curdate};

var needSendAccInf = rsdcommand(" SELECT opob.* FROM dsb_casln_dbt cl1, dsb_casln_dbt cl2, dopobject_dbt opob "
                                " WHERE CL2.T_APPLICATIONKIND2 = ? AND CL2.T_APPLICATIONKEY2 = ? AND CL2.T_REFVALUE2 = 0 "
                                " AND CL1.T_APPLICATIONKIND1 = CL2.T_APPLICATIONKIND1 AND CL1.T_APPLICATIONKEY1 = CL2.T_APPLICATIONKEY1 "
                                " AND OPOB.T_OPAPPKIND = CL1.T_APPLICATIONKIND2 AND OPOB.T_OPAPPKEY = CL1.T_APPLICATIONKEY2 AND OPOB.T_OBJECTTYPE = 11002 "
                                " AND OPOB.T_OBJECTREF = CHR (0) ");
needSendAccInf.AddParam("OPAPPKIND",RSDBP_IN,ALG_SBDEPDOC.IAPPLICATIONKIND);
needSendAccInf.AddParam("OPAPPKEY",RSDBP_IN,ALG_SBDEPDOC.APPLICATIONKEY);
needSendAccInf.execute();
var rs_needSendAccInf = RsdRecordset(needSendAccInf);
var count = 0;
while ( rs_needSendAccInf.moveNext() )
  count = count + 1;
  var res = Сообщить_о_движении_по_счету(convertNullInt(rs_needSendAccInf.value("T_OPAPPKIND")), convertNullStr(rs_needSendAccInf.value("T_OPAPPKEY")));
  if ((res.ReqID != "") and (res.Result == 0))
    var insertOPObj = rsdcommand("UPDATE dopobject_dbt SET T_OBJECTREF = ? WHERE T_OBJECTTYPE = 11002 AND T_OBJECTREF = CHR(0) AND T_OPAPPKIND = ? AND T_OPAPPKEY = ?");
    insertOPObj.AddParam("OBJECTREF",RSDBP_IN, res.ReqID);
    insertOPObj.AddParam("OPAPPKIND",RSDBP_IN,convertNullInt(rs_needSendAccInf.value("T_OPAPPKIND")));
    insertOPObj.AddParam("OPAPPKEY",RSDBP_IN,convertNullStr(rs_needSendAccInf.value("T_OPAPPKEY")));
    insertOPObj.execute();
    ALG_RESULT=OK_RES;
  end;
end;
if ( count == 0 )
  ALG_RESULT=SKIP_RES;
end;
OnError
ALG_RESULT=ERR_RES;

return;
