import BrParm, Acc_Form;

file OGSZIssue1("ogsz_iss") key 1;

record OGSZDocInfo("ci_doc.1");
record OGSZRecInfo("ci_rec.1");

var
  CopyCode,
  RetiredSum,
  WarrTotSum,
  TotNumItems,
  TotWarrYieldSum,
  TotBoughtWarrYieldSum,
  TotSoldItems,
  TotBoughtItems,
  TotCommissionSum,
  TotSum,
  TotTaxSum,
  TotRetiredSum,
  TotSoldSum,
  TotBoughtSum,
  TotWarrTotSum;

array
  WYSumArr,
  TotWYSumArr;

const
  CI_OGSZ=1;

const
  O_OGSZ_SELL=1,
  O_OGSZ_BUY=2,
  O_OGSZ_PAYWARR=3,
  O_OGSZ_KEEP=4;


macro OutOperHead;

  [
                                                                               Филиал №
                                                                               отделения
                                                                               Сбербанка РФ


                                    Отчет по операциям по ОГСЗ за ##########

  ]
  (
    {curdate}
  );
end;

macro OutSellHead;

  [ ];
  [Продажа облигаций];
  [ ];
  [+------+------------------+------+------------------+------------------+------------------+------------------+];
  [|Серия |     Номинал      | Кол. |      Н К Д       |Курсовая надбавка |     Получено     |   В т.ч. налог   |];
  [+------+------------------+------+------------------+------------------+------------------+------------------+];
end;

macro GetNumItems

  var
    RecFound,
    NumItems=0;

  CapIssueDoc.RecApplicKind=CapIssueRec.ApplicationKind;
  CapIssueDoc.RecApplicKey=CapIssueRec.ApplicationKey;

  RecFound=GetEQ(CapIssueDoc);
  while(RecFound
    and (CapIssueDoc.RecApplicKind==CapIssueRec.ApplicationKind)
    and (CapIssueDoc.RecApplicKey==CapIssueRec.ApplicationKey))
    if ( CheckCIDoc )
      SetRecordAddr(OGSZDocInfo,CapIssueDoc,0,
        FldOffset(CapIssueDoc,"Info"),true);
      NumItems=NumItems+OGSZDocInfo.NumItems;
    end;
    RecFound=Next(CapIssueDoc);
  end;
  return NumItems;
end;

macro OutSellLine;

  SetRecordAddr(OGSZRecInfo,CapIssueRec,0,FldOffset(CapIssueRec,"Info"),true);
  [| #### | ################ | #### | ################ | ################ | ################ | ################ |]
  (
    OGSZRecInfo.Series,
    OGSZRecInfo.Par,
    GetNumItems,
    OGSZRecInfo.WarrYieldSum,
    OGSZRecInfo.CommissionSum,
    CapIssueRec.Sum,
    OGSZRecInfo.TaxSum
  );
end;

macro OutBuyHead;

  [ ];
  [Покупка облигаций];
  [ ];
  [+------+------------------+------+------------------+------------------+------------------+];
  [|Серия |     Номинал      | Кол. |      Н К Д       |Курсовая надбавка |     Получено     |];
  [+------+------------------+------+------------------+------------------+------------------+];
end;

macro OutBuyLine;

  SetRecordAddr(OGSZRecInfo,CapIssueRec,0,FldOffset(CapIssueRec,"Info"),true);
  [| #### | ################ | #### | ################ | ################ | ################ |]
  (
    OGSZRecInfo.Series,
    OGSZRecInfo.Par,
    GetNumItems,
    OGSZRecInfo.WarrYieldSum,
    OGSZRecInfo.CommissionSum,
    CapIssueRec.Sum
  );
end;

macro OutSellTotals;

  [+-------------------------+------+------------------+------------------+------------------+------------------+];
  SetRecordAddr(OGSZRecInfo,CapIssueRec,0,FldOffset(CapIssueRec,"Info"),true);
  [| И т о г о :             | #### | ################ | ################ | ################ | ################ |]
  (
    TotNumItems,
    TotWarrYieldSum,
    TotCommissionSum,
    TotSum,
    TotTaxSum
  );
end;

macro OutBuyTotals;

  SetRecordAddr(OGSZRecInfo,CapIssueRec,0,FldOffset(CapIssueRec,"Info"),true);
  [+-------------------------+------+------------------+------------------+------------------+];
  [| И т о г о :             | #### | ################ | ################ | ################ |]
  (
    TotNumItems,
    TotWarrYieldSum,
    TotCommissionSum,
    TotSum
  );
end;

macro OutPayWarrHead;

  [ ];
  [Оплата купонов и погашение облигаций];
  [ ];
  [+------+------------------+----------------------------------------------------------------------------------------------+------------------+------------------+];
  [|      |                  |                   С у м м а ,  в ы п л а ч е н н а я   п о   к у п о н а м                   | Выплачено по     |                  |];
  [|Серия |     Номинал      |------------------+------------------+------------------+------------------+------------------| погашенным       | Итого выплачено  |];
  [|      |                  |      1 - м у     |      2 - м у     |      3 - м у     |      4 - м у     |    В с е г о     | облигациям       |                  |];
  [+------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+];
end;

macro GetOGSZIssue;

  OGSZIssue.Type=CI_OGSZ;
  OGSZIssue.IssueID=CapIssueRec.Issue;
  if(not GetEQ(OGSZIssue))
    MsgBox("Выпуск ОГСЗ не найден: #"+String(CapIssueRec.Issue));
  end;
end;

macro GetWarrantYieldSums;

  var
    RecFound,
    i=1;

  while(i<=4)
    WYSumArr(i)=$0;
    i=i+1;
  end;
  RetiredSum=$0;
  WarrTotSum=$0;

  GetOGSZIssue;
  CapIssueDoc.RecApplicKind=CapIssueRec.ApplicationKind;
  CapIssueDoc.RecApplicKey=CapIssueRec.ApplicationKey;

  RecFound=GetEQ(CapIssueDoc);
  while(RecFound
    and (CapIssueDoc.RecApplicKind==CapIssueRec.ApplicationKind)
    and (CapIssueDoc.RecApplicKey==CapIssueRec.ApplicationKey))
    if ( CheckCIDoc )
      SetRecordAddr(OGSZDocInfo,CapIssueDoc,0,FldOffset(CapIssueDoc,"Info"),true);
      if(OGSZDocInfo.WarrantNumber!=OGSZIssue.NumWarrants)
         WYSumArr(OGSZDocInfo.WarrantNumber)=
           WYSumArr(OGSZDocInfo.WarrantNumber)+CapIssueDoc.Sum;
      else
         WYSumArr(OGSZDocInfo.WarrantNumber)=
           WYSumArr(OGSZDocInfo.WarrantNumber)+CapIssueDoc.Sum-
           OGSZIssue.Par*OGSZDocInfo.NumItems;
         RetiredSum=RetiredSum+OGSZIssue.Par*OGSZDocInfo.NumItems;
      end;
    end;
    RecFound=Next(CapIssueDoc);
  end;

  i=1;
  while(i<=4)
    WarrTotSum=WarrTotSum+WYSumArr(i);
    i=i+1;
  end;
end;

macro OutPayWarrLine

  SetRecordAddr(OGSZRecInfo,CapIssueRec,0,FldOffset(CapIssueRec,"Info"),true);
  [| #### | ################ | ################ | ################ | ################ | ################ | ################ | ################ | ################ |]
  (
    OGSZRecInfo.Series,
    OGSZRecInfo.Par,
    WYSumArr(1),
    WYSumArr(2),
    WYSumArr(3),
    WYSumArr(4),
    WarrTotSum,
    RetiredSum,
    CapIssueRec.Sum
  );
end;

macro OutPayWarrTotals

  SetRecordAddr(OGSZRecInfo,CapIssueRec,0,FldOffset(CapIssueRec,"Info"),true);
  [+------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+];
  [| И т о г о :             | ################ | ################ | ################ | ################ | ################ | ################ | ################ |]
  (
    TotWYSumArr(1),
    TotWYSumArr(2),
    TotWYSumArr(3),
    TotWYSumArr(4),
    TotWarrTotSum,
    TotRetiredSum,
    TotSum
  );
end;

macro SellReport

  var
    RecFound;

  TotNumItems=0;
  TotWarrYieldSum=$0;
  TotCommissionSum=$0;
  TotSum=$0;
  TotTaxSum=$0;

  ClearRecord(CapIssueRec);
  CapIssueRec.Branch=Branch;
  CapIssueRec.IsCur=0;
  CapIssueRec.Type=CI_OGSZ;

  OutSellHead;
  RecFound=GetGE(CapIssueRec);
  while(RecFound
    and (CapIssueRec.Branch==Branch)
    and (CapIssueRec.IsCur==0)
    and (CapIssueRec.Type==CI_OGSZ))
    if((CapIssueRec.Date=={curdate})
      and (CapIssueRec.Brigade==OperBrigade)
      and (CapIssueRec.Operation==O_OGSZ_SELL))
      OutSellLine;
      SetRecordAddr(OGSZRecInfo,CapIssueRec,0,
        FldOffset(CapIssueRec,"Info"),true);
      TotNumItems=TotNumItems+GetNumItems;
      TotWarrYieldSum=TotWarrYieldSum+OGSZRecInfo.WarrYieldSum;
      TotCommissionSum=TotCommissionSum+OGSZRecInfo.CommissionSum;
      TotSum=TotSum+CapIssueRec.Sum;
      TotTaxSum=TotTaxSum+OGSZRecInfo.TaxSum;
    end;
    RecFound=Next(CapIssueRec);
  end;
  OutSellTotals;
end;

macro BuyReport

  var
    RecFound;

  TotNumItems=0;
  TotWarrYieldSum=0;
  TotCommissionSum=0;
  TotSum=0;
  TotTaxSum=0;

  ClearRecord(CapIssueRec);
  CapIssueRec.Branch=Branch;
  CapIssueRec.IsCur=0;
  CapIssueRec.Type=CI_OGSZ;

  OutBuyHead;
  RecFound=GetGE(CapIssueRec);
  while(RecFound
    and (CapIssueRec.Branch==Branch)
    and (CapIssueRec.IsCur==0)
    and (CapIssueRec.Type==CI_OGSZ))
    if((CapIssueRec.Date=={curdate})
      and (CapIssueRec.Brigade==OperBrigade)
      and (CapIssueRec.Operation==O_OGSZ_BUY))
      OutBuyLine;
      SetRecordAddr(OGSZRecInfo,CapIssueRec,0,
        FldOffset(CapIssueRec,"Info"),true);
      TotNumItems=TotNumItems+GetNumItems;
      TotWarrYieldSum=TotWarrYieldSum+OGSZRecInfo.WarrYieldSum;
      TotCommissionSum=TotCommissionSum+OGSZRecInfo.CommissionSum;
      TotSum=TotSum+CapIssueRec.Sum;
      TotTaxSum=TotTaxSum+OGSZRecInfo.TaxSum;
    end;
    RecFound=Next(CapIssueRec);
  end;
  OutBuyTotals;
end;

macro PayWarrReport

  var
    RecFound,
    i=1;

  while(i<=4)
    TotWYSumArr(i)=$0;
    i=i+1;
  end;
  TotRetiredSum=$0;
  TotWarrTotSum=$0;
  TotSum=$0;

  ClearRecord(CapIssueRec);
  CapIssueRec.Branch=Branch;
  CapIssueRec.IsCur=0;
  CapIssueRec.Type=CI_OGSZ;

  OutPayWarrHead;
  RecFound=GetGE(CapIssueRec);
  while(RecFound
    and (CapIssueRec.Branch==Branch)
    and (CapIssueRec.IsCur==0)
    and (CapIssueRec.Type==CI_OGSZ))
    if((CapIssueRec.Date=={curdate})
      and (CapIssueRec.Brigade==OperBrigade)
      and (CapIssueRec.Operation==O_OGSZ_PAYWARR))
      GetWarrantYieldSums;
      OutPayWarrLine;
      SetRecordAddr(OGSZRecInfo,CapIssueRec,0,
        FldOffset(CapIssueRec,"Info"),true);
      i=1;
      while(i<=4)
        TotWYSumArr(i)=TotWYSumArr(i)+WYSumArr(i);
        i=i+1;
      end;
      TotRetiredSum=TotRetiredSum+RetiredSum;
      TotWarrTotSum=TotWarrTotSum+WarrTotSum;
      TotSum=TotSum+CapIssueRec.Sum;
    end;
    RecFound=Next(CapIssueRec);
  end;
  OutPayWarrTotals;
end;

macro OGSZOperReport;

  OutOperHead;
  SellReport;
  BuyReport;
  PayWarrReport;
end;

macro OutSellBuyRecHead;

  var
    BranchStrNum = "",
    DepartNum = "",
    DepartName = "";

  GetBranchParams( Branch, BranchStrNum, DepartNum, DepartName );
  SetRecordAddr(OGSZRecInfo,CapIssueRec,0,FldOffset(CapIssueRec,"Info"),true);
  [                                                                                                                                   Ф. №201
     ##################################
                                                                                                                               Филиал №  #########
     Сберегательного банка № ##########

     
     
                                                               В Е Д О М О С Т Ь
     
                                                на покупку и продажу облигаций государственного
                                             сберегательного займа Российской Федерации #### серии
                                                                за ##########
     

     Смена № #####

  ]
  (
    DepartName,
    BranchStrNum,
    DepartNum,
    OGSZRecInfo.Series,
    {curdate},
    OperBrigade
  );
  [+--------+--------------------------------------------------------+-------------------------------------------------------+-------------------+];
  [|Номерной|                    П р о д а н о                       |                     К у п л е н о                     |   П о д п и с и   |];
  [| талон, |-----------+--------------+-----------------------------|-----------+--------------+----------------------------|---------+---------|];
  [|выданный|Количество |Ном. стоимость| Получ. за продан. облигации |Количество |Ном. стоимость| Выплач. за купл. облигации |         |         |];
  [|клиенту |-----+-----|  проданных   |---------------+-------------|-----+-----|  купленных   |--------------+-------------|контролер| кассир  |];
  [|        | шт  |д/шт |  облигаций   |      Всего    | В т.ч. НКД  | шт  |д/шт |  облигаций   |     Всего    | В т.ч  НКД  |         |         |];
  [+--------+-----+-----+--------------+---------------+-------------+-----+-----+--------------+--------------+-------------+---------+---------+];
end;                                                                                                                                              
                                                                                                                                                  
macro OutSellBuyRecLine;                                                                                                                          
                                                                                                                                                  
  var                                                                                                                                             
    SoldSum=$0,                                                                                                                                   
    BoughtSum=$0,                                                                                                             
    SoldParSum=$0,
    BoughtParSum=$0,
    SoldWarrYield=$0,
    BoughtWarrYield=$0,
    SoldItems=0,
    BoughtItems=0;

  SetRecordAddr(OGSZDocInfo,CapIssueDoc,0,
    FldOffset(CapIssueDoc,"Info"),true);
  if(CapIssueRec.Operation==O_OGSZ_SELL)
    SoldSum=CapIssueDoc.Sum;
    SoldParSum=OGSZDocInfo.Par*OGSZDocInfo.NumItems;
    SoldWarrYield=OGSZDocInfo.WarrantYield;
    SoldItems = OGSZDocInfo.NumItems;
  elif(CapIssueRec.Operation==O_OGSZ_BUY)
    BoughtSum=CapIssueDoc.Sum;
    BoughtParSum=OGSZDocInfo.Par*OGSZDocInfo.NumItems;
    BoughtWarrYield=OGSZDocInfo.WarrantYield;
    BoughtItems = OGSZDocInfo.NumItems;
  end;

  [|########|#####|#####|##############|###############|#############|#####|#####|##############|##############|#############|         |         |]
  (
    CapIssueDoc.DocNumber,
    SoldItems:z,
    SoldItems:z,
    SoldParSum:z,
    SoldSum:z,
    SoldWarrYield:z,
    BoughtItems:z,
    BoughtItems:z,
    BoughtParSum:z,
    BoughtSum:z,
    BoughtWarrYield:z
  );
  TotSoldItems = TotSoldItems + SoldItems;
  TotSoldSum=TotSoldSum+SoldSum;
  TotWarrYieldSum=TotWarrYieldSum+SoldWarrYield;
  TotBoughtItems = TotBoughtItems + BoughtItems;
  TotBoughtWarrYieldSum=TotBoughtWarrYieldSum+BoughtWarrYield;
  TotBoughtSum=TotBoughtSum+BoughtSum;
end;

macro OutSellBuyRecTotals

  var
    SellCredAcc,
    SellDebAcc,
    BuyCredAcc,
    BuyDebAcc;

  GetBookAcc(O_OGSZ_SELL, SellDebAcc, SellCredAcc);
  GetBookAcc(O_OGSZ_BUY, BuyDebAcc, BuyCredAcc);
  [+--------+-----+-----+--------------+---------------+-------------+-----+-----+--------------+--------------+-------------+---------+---------+];
  [| Итого: |#####|#####|              |###############|#############|#####|#####|              |##############|#############|         |         |]
  (
    TotSoldItems,
    TotSoldItems,
    TotSoldSum,
    TotWarrYieldSum,
    TotBoughtItems,
    TotBoughtItems,
    TotBoughtSum,
    TotBoughtWarrYieldSum
  );
  [ ];
  [                                                    Д-т сч. ];
  [                                                    ########################## ]
  (Acc_Form(BuyDebAcc));
  [ ];
  [                                 Д-т сч. ];
  [                                 ########################## ]
  (Acc_Form(SellDebAcc));
  [ ];
  [             Расход по сч.                          К-т сч. ];
  [             ___________________                    ########################## ]
  (Acc_Form(BuyCredAcc));
  [ ];
  [                                 К-т сч. ];
  [                                 ########################## ]
  (Acc_Form(SellCredAcc));
  [ ];
  [                                                    Приход по сч.];
  [                                                    _________________ ];
end;

macro OutPayWarrRecHead;

  var
    BranchStrNum = "",
    DepartNum = "",
    DepartName = "",
    DebAcc,
    CredAcc;

  GetBranchParams( Branch, BranchStrNum, DepartNum, DepartName );
  GetBookAcc(CapIssueRec.Operation, DebAcc, CredAcc);
  SetRecordAddr(OGSZRecInfo,CapIssueRec,0,FldOffset(CapIssueRec,"Info"),true);
  [  Сбербанк России                                                                                                                                    Ф. № 202
     ##################################
     Сберегательного банка № ##########
     Филиал № ##########


                                                 КОНТРОЛЬНАЯ  ВЕДОМОСТЬ                                                           Отметки бухгалтерии

                                    на оплату купонов и погашение облигаций государственного                                      Дебет  сч. ######################
                                      сберегательного займа Российской Федерации #### серии                                       Кредит сч. ######################
                                                     за ##########                                                                Дебет  сч. ______________________
                                                                                                                                  Кредит сч. ______________________


    Смена № #####

  ]
  (
    DepartName,
    DepartNum,
    BranchStrNum,
    Acc_Form(DebAcc),
    OGSZRecInfo.Series,
    Acc_Form(CredAcc),
    {curdate},
    OperBrigade
  );
  [+-----------+------------------+--------------------------------------------------------------------------------------------+------------------+-----------------+];
  [| Номерной  |                  |                  С у м м а ,  в ы п л а ч е н н а я   п о   к у п о н а м                  |      Сумма,      |                 |];
  [|  талон,   |   Номинальная    |                                                                                            |    выплаченная   |      Итого      |];
  [| выданный  |                  |------------------+-----------------+------------------+-----------------+------------------|   по погашенным  |                 |];
  [| клиенту   |    стоимость     |     1 - м у      |     2 - м у     |     3 - м у      |    4 - м у      |    В с е г о     |    облигациям    |    выплачено    |];
  [|           |                  |                  |                 |                  |                 |                  |                  |                 |];
  [+-----------+------------------+------------------+-----------------+------------------+-----------------+------------------+------------------+-----------------+];
end;

macro OutPayWarrRecLine;

  var
    i=1;

  while(i<=4)
    WYSumArr(i)=$0;
    i=i+1;
  end;
  RetiredSum=$0;

  GetOGSZIssue;
  SetRecordAddr(OGSZDocInfo,CapIssueDoc,0,FldOffset(CapIssueDoc,"Info"),true);
  if(OGSZDocInfo.WarrantNumber!=OGSZIssue.NumWarrants)
    WYSumArr(OGSZDocInfo.WarrantNumber)=CapIssueDoc.Sum;
  else
    WYSumArr(OGSZDocInfo.WarrantNumber)=CapIssueDoc.Sum-
      OGSZIssue.Par*OGSZDocInfo.NumItems;
    RetiredSum=OGSZIssue.Par*OGSZDocInfo.NumItems;
  end;
  WarrTotSum=WYSumArr(OGSZDocInfo.WarrantNumber);

  [|   ####    | ################ | ################ | ############### | ################ | ############### | ################ | ################ | ############### |]
  (
    CapIssueDoc.DocNumber,
    OGSZDocInfo.Par*OGSZDocInfo.NumItems,
    WYSumArr(1),
    WYSumArr(2),
    WYSumArr(3),
    WYSumArr(4),
    WarrTotSum,
    RetiredSum,
    CapIssueDoc.Sum
  );
  TotWYSumArr(1)=TotWYSumArr(1)+WYSumArr(1);
  TotWYSumArr(2)=TotWYSumArr(2)+WYSumArr(2);
  TotWYSumArr(3)=TotWYSumArr(3)+WYSumArr(3);
  TotWYSumArr(4)=TotWYSumArr(4)+WYSumArr(4);
  TotNumItems = TotNumItems + OGSZDocInfo.NumItems;
  TotWarrTotSum=TotWarrTotSum+WarrTotSum;
  TotRetiredSum=TotRetiredSum+RetiredSum;
  TotSum=TotSum+CapIssueDoc.Sum;
end;

macro OutPayWarrRecTotals

  [+-----------+------------------+------------------+-----------------+------------------+-----------------+------------------+------------------+-----------------+];
  [| Итого:    |                  | ################ | ############### | ################ | ############### | ################ | ################ | ############### |]
  (
    TotWYSumArr(1),
    TotWYSumArr(2),
    TotWYSumArr(3),
    TotWYSumArr(4),
    TotWarrTotSum,
    TotRetiredSum,
    TotSum
  );
  [

  Сумма прописью: #
  ] ( RubToStr( TotSum ) );
end;

macro OutSellBuyRecTail;

  [



                                                                               Контролер _____________        Кассир____________

                                                                                                       Ст. бухгалтер ___________

                                                                                               Работник депозитария ____________
  ];
end;

macro OutPayWarrRecTail

  [ ];
  [ ];
  [Контролер (оператор) ________________________________     Кассир ______________________________ ];
  [ ];
  [                     Отметки бухгалтерии ];
  [                     Дебет счета ____________________     Кредит счета ____________________ ];                     
  [                     Дебет счета ____________________     Кредит счета ____________________ ];                     
  [ ];
  [                     Гл. (ст.) бухгалтер _______________________ ];
  [ ];
  [ ];
end;

macro OGSZSellBuyRecBody;

  var
    RecFound;

  CapIssueDoc.RecApplicKind=CapIssueRec.ApplicationKind;
  CapIssueDoc.RecApplicKey=CapIssueRec.ApplicationKey;

  RecFound=GetEQ(CapIssueDoc);
  while(RecFound
    and (CapIssueDoc.RecApplicKind==CapIssueRec.ApplicationKind)
    and (CapIssueDoc.RecApplicKey==CapIssueRec.ApplicationKey))
    if ( CheckCIDoc ) 
      OutSellBuyRecLine;
    end;
    RecFound=Next(CapIssueDoc);
  end;
end;

macro OGSZSellBuyRecCopy

  TotSoldSum=$0;
  TotBoughtSum=$0;
  TotWarrYieldSum=$0;
  TotBoughtWarrYieldSum=$0;
  TotSoldItems = 0;
  TotBoughtItems = 0;
  OutSellBuyRecHead;
  OGSZSellBuyRecBody;
  OutSellBuyRecTotals;
  OutSellBuyRecTail;
  PrintLn( StrFor( 12 ) );
end;

macro OGSZSellBuyRec;

  CopyCode = "А";
  OGSZSellBuyRecCopy;
/*
  CopyCode = "Б";
  OGSZSellBuyRecCopy;
*/
end;

macro OGSZPayWarrRecBody;

  var
    RecFound;

  CapIssueDoc.RecApplicKind=CapIssueRec.ApplicationKind;
  CapIssueDoc.RecApplicKey=CapIssueRec.ApplicationKey;

  RecFound=GetEQ(CapIssueDoc);
  while(RecFound
    and (CapIssueDoc.RecApplicKind==CapIssueRec.ApplicationKind)
    and (CapIssueDoc.RecApplicKey==CapIssueRec.ApplicationKey))
    if ( CheckCIDoc )
      OutPayWarrRecLine;
    end;
    RecFound=Next(CapIssueDoc);
  end;
end;

macro OGSZPayWarrRecCopy;

  TotNumItems=0;
  TotWYSumArr(1)=$0;
  TotWYSumArr(2)=$0;
  TotWYSumArr(3)=$0;
  TotWYSumArr(4)=$0;
  TotWarrTotSum=$0;
  TotRetiredSum=$0;
  TotSum=$0;
  OutPayWarrRecHead;
  OGSZPayWarrRecBody;
  OutPayWarrRecTotals;
  OutPayWarrRecTail;
  PrintLn( StrFor( 12 ) );
end;

macro OGSZPayWarrRec;

  CopyCode = "А";
  OGSZPayWarrRecCopy;
/*
  CopyCode = "Б";
  OGSZPayWarrRecCopy;
*/
end;

macro OGSZRec(ApplicationKind,ApplicationKey);

  KeyNum(CapIssueRec,2);
  CapIssueRec.ApplicationKind=ApplicationKind;
  CapIssueRec.ApplicationKey=ApplicationKey;
  if(not GetEQ(CapIssueRec))
    MsgBox("Ошибка при печати ведомости");
    return;
  end;
  if((CapIssueRec.Operation==O_OGSZ_SELL)
    or (CapIssueRec.Operation==O_OGSZ_BUY))
    OGSZSellBuyRec;
  elif(CapIssueRec.Operation==O_OGSZ_PAYWARR)
    OGSZPayWarrRec;
  end;
end;

macro OGSZReportPayWarr;

  var
    NotEmpty = false,
    PrevIssue = 0,
    OGSZFound,
    RecFound;

  TotWYSumArr(1)=$0;
  TotWYSumArr(2)=$0;
  TotWYSumArr(3)=$0;
  TotWYSumArr(4)=$0;
  TotNumItems = 0;
  TotWarrTotSum=$0;
  TotRetiredSum=$0;
  TotSum=$0;

  ClearRecord(OGSZIssue1);
  OGSZIssue1.Type=CI_OGSZ;

  OGSZFound=GetGE(OGSZIssue1);
  while(OGSZFound
    and (OGSZIssue1.Type=CI_OGSZ))

    ClearRecord(CapIssueRec);
    CapIssueRec.Branch=Branch;
    CapIssueRec.IsCur=0;
    CapIssueRec.Type=CI_OGSZ;
    CapIssueRec.Issue=OGSZIssue1.IssueID;

    RecFound=GetGE(CapIssueRec);
    while(RecFound
      and (CapIssueRec.Branch==Branch)
      and (CapIssueRec.IsCur==0)
      and (CapIssueRec.Type==CI_OGSZ)
      and (CapIssueRec.Issue==OGSZIssue1.IssueID))
      if((CapIssueRec.Date=={curdate})
        and (CapIssueRec.Brigade==OperBrigade))
        if(CapIssueRec.Operation==O_OGSZ_PAYWARR)
          if(CapIssueRec.Issue!=PrevIssue)
            if(PrevIssue)
              OutPayWarrRecTotals;
              OutPayWarrRecTail;
              PrintLn( StrFor( 12 ) );
            end;
            PrevIssue=CapIssueRec.Issue;
            TotWYSumArr(1)=$0;
            TotWYSumArr(2)=$0;
            TotWYSumArr(3)=$0;
            TotWYSumArr(4)=$0;
            TotNumItems = 0;
            TotWarrTotSum=$0;
            TotRetiredSum=$0;
            TotSum=$0;
            OutPayWarrRecHead;
            NotEmpty=true;
          end;
          OGSZPayWarrRecBody;
        end;
      end;
      RecFound=Next(CapIssueRec);
    end;
    OGSZFound=Next(OGSZIssue1);
  end;
  if(NotEmpty)
    OutPayWarrRecTotals;
    OutPayWarrRecTail;
  end;
end;

macro OGSZReportSellBuy

  var
    NotEmpty = false,
    PrevIssue = 0,
    RecFound;

  TotSoldSum=$0;
  TotBoughtSum=$0;
  TotWarrYieldSum=$0;
  TotBoughtWarrYieldSum=$0;
  TotSoldItems = 0;
  TotBoughtItems = 0;
  ClearRecord(CapIssueRec);
  CapIssueRec.Branch=Branch;
  CapIssueRec.IsCur=0;
  CapIssueRec.Type=CI_OGSZ;

  RecFound=GetGE(CapIssueRec);
  while(RecFound
    and (CapIssueRec.Branch==Branch)
    and (CapIssueRec.IsCur==0)
    and (CapIssueRec.Type==CI_OGSZ))
    if((CapIssueRec.Date=={curdate})
      and (CapIssueRec.Brigade==OperBrigade))
      if((CapIssueRec.Operation==O_OGSZ_SELL)
        or (CapIssueRec.Operation==O_OGSZ_BUY))
        if(CapIssueRec.Issue!=PrevIssue)
          if(PrevIssue)
            OutSellBuyRecTotals;
            OutSellBuyRecTail;
            PrintLn( StrFor( 12 ) );
          end;
          PrevIssue=CapIssueRec.Issue;
          TotSoldSum=$0;
          TotBoughtSum=$0;
          TotWarrYieldSum=$0;
          TotBoughtWarrYieldSum=$0;
          TotSoldItems = 0;
          TotBoughtItems = 0;
          OutSellBuyRecHead;
          NotEmpty=true;
        end;
        OGSZSellBuyRecBody;
      end;
    end;
    RecFound=Next(CapIssueRec);
  end;
  if(NotEmpty)
    OutSellBuyRecTotals;
    OutSellBuyRecTail;
  end;
end;

macro OGSZReport

  CopyCode = "А";
  OGSZReportSellBuy;
/*
  CopyCode = "Б";
  OGSZReportSellBuy;
*/
  CopyCode = "А";
  OGSZReportPayWarr;
/*
  CopyCode = "Б";
  OGSZReportPayWarr;
*/
end;