/*
  Эмитент. Печать договора.
  Голова макроса - запускается из операций 301-303

  Последнее обновление: 16 марта 2007

  Стольников Сергей
*/

import BankInter, Alg_Vars, pr___dda, ChkPrn, QueryRes;

var
    RegPath = "RS-RETAIL\\ПЕЧАТИ\\ВКЛАДЫ\\ДОГОВОРА";

if ( StrFor( GetProgramID() ) == "П" )
  Exit(1);  /* В Последконтроле договор не выпускается */
end;

ALG_RESULT = ERR_RES;/*заранее инициализируем код возврата*/
CheckPrinter( RegPath, StrFor( 0 ) );
ALG_RESULT = OK_RES;/*заранее инициализируем код возврата*/

sc___dda(); /*вызов основного макроса*/

QueryResult( "Договор был напечатан?" );
if ( MacroOutput == "PRN" )
  Exit( 1 );
end;
