/*
$Name:               PRNDOGS.MAC
$Module:             DEPOSITR
$Description:        Печать договора
*/
/*
  RS-Bank
  Частные вклады для Сбербанка

  Вызов макpо печати договоpа для шагов алгоpитма

  07.02.97 | Зубов В.Ю. | Создан
*/

import toolprndogs, QueryRes;

  var
    RegPath = "RS-RETAIL\\ПЕЧАТИ\\ВКЛАДЫ\\ДОГОВОРА";

if ( StrFor( GetProgramID() ) == "П" )
  Exit(1);  /* В Последконтроле договор не выпускается */
end;

ALG_RESULT = ERR_RES;/*заранее инициализируем код возврата*/
CheckPrinter( RegPath, StrFor( 0 ) );
ALG_RESULT = OK_RES;/*заранее инициализируем код возврата*/

Main_MAC(ALG_DEPOSITOR,ALG_SBDEPDOC,ALG_COMDEPCLNT,ALG_COMPAYER, false);/*вызов основного макроса*/

QueryResult( "Договор был напечатан?" );
if ( MacroOutput == "PRN" )
  Exit( 1 );
end;

