-- Таблица "DNPTXSNOBREP_TMP"

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DNPTXSNOBREP_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DNPTXSNOBREP_TMP (
    T_INCOMEREGIONDATE DATE
  , T_INCOMEREGIONTIME DATE
  , T_INCOMEDATE DATE
  , T_INCOMETIME DATE
  , T_NOBAMOUNT NUMBER(32,12)
  , T_NDFLCALCULATEAMOUNT NUMBER(32,12)
  , T_NDFLTAXRATE NUMBER(5)
  , T_NDFLKEEPAMOUNT NUMBER(32,12)
  , T_NDFLKEEPRATE NUMBER(5)
  , T_KBKCALCULATE VARCHAR2(20)
  , T_KBKKEEP VARCHAR2(20)
  , T_TAXBASETYPE NUMBER(5)
  , T_TAXPAYERSTATUS NUMBER(5)
  , T_SYSTEMCODE VARCHAR2(100)
  , T_CLIENTID NUMBER(10)
  , T_RECORDID VARCHAR2(50)
  , T_OPERATIONID VARCHAR2(50)
  , T_EVENTID VARCHAR2(50)
  , T_EVENTTYPE NUMBER(5)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DNPTXSNOBREP_TMP IS 'Временная таблица отчета по СНОБ'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXSNOBREP_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXSNOBREP_TMP_IDX0 ON DNPTXSNOBREP_TMP (
   T_CLIENTID ASC
  ,T_INCOMEDATE ASC
  ,T_INCOMETIME ASC
)
/
