DECLARE
	e_col_exist EXCEPTION;
	PRAGMA EXCEPTION_INIT (e_col_exist, -01430);
BEGIN
	EXECUTE IMMEDIATE 'ALTER TABLE DDL_REGISTERIA_TMP ADD ( ' || 
			'T_OPTIONTERMS VARCHAR2(100),' ||
			'T_FUTURESAMOUNT NUMBER(32,12),' ||
			'T_QUOTECUR VARCHAR2(3),' ||
			'T_OPTIONDEALBONUS NUMBER(32,12),' ||
			'T_BAKINDNAME VARCHAR2(30)' ||
		')';

	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGISTERIA_TMP.T_OPTIONTERMS IS ''Условия по опциону''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGISTERIA_TMP.T_FUTURESAMOUNT IS ''Количество фьючерских контрактор''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGISTERIA_TMP.T_QUOTECUR IS ''Валюта котировки, премии по опциону''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGISTERIA_TMP.T_OPTIONDEALBONUS IS ''Премия по опциону''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGISTERIA_TMP.T_BAKINDNAME IS ''Базисный актив ПФИ''';

EXCEPTION WHEN e_col_exist THEN NULL;
END;
/
