BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_REGISTERIA_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DDL_REGISTERIA_TMP_IDX0 ON DDL_REGISTERIA_TMP (
   T_AUTOINC ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_REGISTERIA_TMP_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX DDL_REGISTERIA_TMP_IDX1 ON DDL_REGISTERIA_TMP (
   T_PART ASC
  ,T_DEALID ASC
  ,T_DEALSUBKIND ASC
  ,T_DEALPART ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_REGISTERIA_TMP_IDX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DDL_REGISTERIA_TMP_IDX2 ON DDL_REGISTERIA_TMP (
   T_PART ASC
  ,T_ACCTYPE ASC
  ,T_ACCOUNT ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_REGISTERIA_TMP_IDX3';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DDL_REGISTERIA_TMP_IDX3 ON DDL_REGISTERIA_TMP (
   T_PART ASC
  ,T_CLIENTCONTRID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DDL_REGISTERIA_TMP_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE DDL_REGISTERIA_TMP_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER DDL_REGISTERIA_TMP_T0_AINC
  BEFORE INSERT OR UPDATE OF T_AUTOINC ON DDL_REGISTERIA_TMP FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_AUTOINC = 0 OR :NEW.T_AUTOINC IS NULL) THEN
    SELECT DDL_REGISTERIA_TMP_SEQ.NEXTVAL INTO :NEW.T_AUTOINC FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDL_REGISTERIA_TMP_SEQ');
    IF :NEW.T_AUTOINC >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END
/