CREATE OR REPLACE TRIGGER DDL_REGISTERIA_TMP_T0_AINC
  BEFORE INSERT OR UPDATE OF T_AUTOINC ON DDL_REGISTERIA_TMP FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_AUTOINC = 0 OR :NEW.T_AUTOINC IS NULL) THEN
    SELECT DDL_REGISTERIA_TMP_SEQ.NEXTVAL INTO :NEW.T_AUTOINC FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDL_REGISTERIA_TMP_SEQ');
    IF :NEW.T_AUTOINC >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/