DECLARE
  v_ID NUMBER := 0;
BEGIN
  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('…‚Ž… ‘ŽŽ™. Š‹ˆ…’“ ˆˆ‘');

  IF(v_ID <> 0) THEN 
    UPDATE DREGVAL_DBT
       SET T_LINTVALUE = 10, T_LDOUBLEVALUE = 0
     WHERE T_KEYID = v_ID; 
  END IF;

  v_ID := 0;
  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('Ž‚’ŽŽ… ‘ŽŽ™. Š‹ˆ…’“ ˆˆ‘');

  IF(v_ID <> 0) THEN 
    UPDATE DREGVAL_DBT
       SET T_LINTVALUE = 7, T_LDOUBLEVALUE = 0
     WHERE T_KEYID = v_ID; 
  END IF;

  v_ID := 0;
  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('…‚›‰ Ž’—…’ Ž„ ˆ „Š');

  IF(v_ID <> 0) THEN 
    UPDATE DREGVAL_DBT
       SET T_LINTVALUE = 5, T_LDOUBLEVALUE = 0
     WHERE T_KEYID = v_ID; 
  END IF;

  v_ID := 0;
  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('Ž‚’Ž›‰ Ž’—…’ Ž„ ˆ „Š');

  IF(v_ID <> 0) THEN 
    UPDATE DREGVAL_DBT
       SET T_LINTVALUE = 1, T_LDOUBLEVALUE = 0
     WHERE T_KEYID = v_ID; 
  END IF;

EXCEPTION 
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/