BEGIN
  UPDATE DITEMUSER_DBT
     SET T_ICASEITEM = 930
   WHERE T_CIDENTPROGRAM = CHR(83) 
     AND T_ICASEITEM = 20209;

  UPDATE DMENUITEM_DBT
     SET T_ICASEITEM = 930
   WHERE T_ISTEMPLATE = CHR(0)
     AND T_IIDENTPROGRAM = 83
     AND T_ICASEITEM = 20209;

EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/