DECLARE
	e_col_exist EXCEPTION;
	PRAGMA EXCEPTION_INIT (e_col_exist, -01430);
BEGIN
	EXECUTE IMMEDIATE 'ALTER TABLE DDL_REGISTERIA_TMP MODIFY ( ' || 
			'T_CLIENTAGR VARCHAR2(100)' ||
		')';

	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGISTERIA_TMP.T_CLIENTAGR IS ''Договор с клиентом''';

EXCEPTION WHEN e_col_exist THEN NULL;
END;
/
