-- Таблица "DDEF48287_SFSSI_DBT"

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DDEF48287_SFSSI_DBT (
      T_ACTIONDATE        DATE   
    , T_ACTIONTIME        DATE   
    , T_PARTYID           NUMBER(10)
    , T_SFCONTRID         NUMBER(10)   
    , T_MCACCDOCID        NUMBER(10)   
    , T_FIID              NUMBER(10)   
    , T_CHAPTER           NUMBER(5)    
    , T_ACCOUNT           VARCHAR2(35) 
    , T_CLIENTNAME        VARCHAR2(60)
    , T_SFCONTRNUMBER     VARCHAR2(20)    
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DDEF48287_SFSSI_DBT IS 'Архив создания СПИ в рамках def-48287'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_ACTIONDATE       IS 'Дата операции'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_ACTIONTIME       IS 'Время операции'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_PARTYID          IS 'Идентификатор клиента'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_SFCONTRID        IS 'Идентификатор договора обслуживания'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_MCACCDOCID       IS 'Идентификатор документа счёта'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_FIID             IS 'Идентификатор валюты'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_CHAPTER          IS 'Номер главы'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_ACCOUNT          IS 'Счет клиента'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_CLIENTNAME       IS 'Имя клиента'/
COMMENT ON COLUMN DDEF48287_SFSSI_DBT.T_SFCONTRNUMBER    IS 'Номер договора'/