DECLARE
 V_OBJECTTYPE NUMBER (10);
BEGIN
  SELECT MAX(T_OBJECTTYPE)+1 INTO V_OBJECTTYPE FROM dobjects_dbt;
  INSERT INTO dobjects_dbt (T_OBJECTTYPE,T_NAME,T_CODE,T_USERNUMBER,T_PARENTOBJECTTYPE,T_SERVICEMACRO,T_MODULE) VALUES (V_OBJECTTYPE,'Технические пользователи СОФР','Teh_Oper',0,0,null,0);                         
  INSERT INTO dllvalues_dbt (T_LIST,T_ELEMENT,T_CODE,T_NAME,T_FLAG,T_NOTE,T_RESERVE) VALUES (V_OBJECTTYPE,1,001,'',1,'',null);         
  INSERT INTO dllvalues_dbt (T_LIST,T_ELEMENT,T_CODE,T_NAME,T_FLAG,T_NOTE,T_RESERVE) VALUES (V_OBJECTTYPE,2,002,'',2,'',null);            
  INSERT INTO dllvalues_dbt (T_LIST,T_ELEMENT,T_CODE,T_NAME,T_FLAG,T_NOTE,T_RESERVE) VALUES (V_OBJECTTYPE,9997,9997,'',9997,'',null) ;            
  COMMIT;
END;/     