DECLARE
    e_col_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT (e_col_exist, -01430);
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DDL_REGISTERIA_TMP ADD ( ' || 
            'T_DOCKIND NUMBER(10)'  ||
        ')';

    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGISTERIA_TMP.T_DOCKIND IS ''Вид документа''';

EXCEPTION WHEN e_col_exist THEN NULL;
END;
/
