-- Таблица "DDL_REGIABUF_DBT"

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DDL_REGIABUF_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    e_object_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_object_exists, -955); 
BEGIN
    EXECUTE IMMEDIATE 
        'CREATE TABLE DDL_REGIABUF_DBT ' || 
        '(' || 
        'T_SESSIONID NUMBER(20),' ||
        'T_CALCID NUMBER (20),' ||
        'T_FUTURESPRICE NUMBER(32,12),' || 
        'T_OUTSTANDCLAIMS NUMBER(32,12),' || 
        'T_OUTSTANDOBL NUMBER(32,12),' || 
        'T_ISBUY NUMBER(5),' || 
        'T_ACCREST NUMBER(32,12),' || 
        'T_ACCCUR VARCHAR2(3),' || 
        'T_OPTIONPREMIUM NUMBER(32,12),' || 
        'T_KINDPFI VARCHAR2(60),' || 
        'T_OPTIONTYPE VARCHAR2(4),' || 
        'T_AUTOINC NUMBER(10),' || 
        'T_DEALPART NUMBER(5),' || 
        'T_CLIENTID NUMBER(10),' || 
        'T_PFI NUMBER(10),' || 
        'T_CLIENTCONTRID NUMBER(10),' || 
        'T_PART NUMBER(5),' || 
        'T_DEALID NUMBER(10),' || 
        'T_CURRCLAIMOBL VARCHAR2(3),' || 
        'T_DEALCODE VARCHAR2(30),' || 
        'T_ACCOUNTNAME VARCHAR2(1000),' || 
        'T_ACCOUNT VARCHAR2(25),' || 
        'T_CASHRIGHT VARCHAR2(23),' || 
        'T_RISKLEVEL VARCHAR2(12),' || 
        'T_CLIENTCVALINV VARCHAR2(16),' || 
        'T_CLIENTRESIDENT VARCHAR2(11),' || 
        'T_CLIENTCOUNTRY VARCHAR2(30),' || 
        'T_CLIENTFORM VARCHAR2(2),' || 
        'T_PROXYNUM VARCHAR2(50),' || 
        'T_PROXYNAME VARCHAR2(320),' || 
        'T_EXCHANGECODE VARCHAR2(36),' || 
        'T_CLIENTAGREND DATE,' || 
        'T_CLIENTAGRDATE DATE,' || 
        'T_CLIENTAGR VARCHAR2(100),' || 
        'T_CLIENTNAME VARCHAR2(320),' || 
        'T_FACTDATEM DATE,' || 
        'T_PLANDATEM DATE,' || 
        'T_FACTDATESP DATE,' || 
        'T_PLANDATESP DATE,' || 
        'T_BROKERCOMISS NUMBER(32,12),' || 
        'T_INTERESTAMOUNT NUMBER(32,12),' || 
        'T_INTERESTRATE FLOAT(53),' || 
        'T_SETCURRENCY VARCHAR2(3),' || 
        'T_NOMINALCURRENCY VARCHAR2(3),' || 
        'T_PRICECURRENCY VARCHAR2(3),' || 
        'T_DEALVALUERUR NUMBER(32,12),' || 
        'T_DEALVALUE NUMBER(32,12),' || 
        'T_TOTALCOSTRUR NUMBER(32,12),' || 
        'T_TOTALCOST NUMBER(32,12),' || 
        'T_COSTNATCUR NUMBER(32,12),' || 
        'T_COST NUMBER(32,12),' || 
        'T_PRINCIPAL NUMBER(32,12),' || 
        'T_ISSUERNAME VARCHAR2(320),' || 
        'T_SECSERIES VARCHAR2(40),' || 
        'T_ISIN VARCHAR2(70),' || 
        'T_SECCODE VARCHAR2(70),' || 
        'T_SECSUBKIND VARCHAR2(36),' || 
        'T_SECKIND VARCHAR2(30),' || 
        'T_DEALKIND VARCHAR2(85),' || 
        'T_DEALDIRECTION VARCHAR2(320),' || 
        'T_DEALTYPEADR VARCHAR2(11),' || 
        'T_UNQUALIFIEDSEC VARCHAR2(2),' || 
        'T_GENAGR VARCHAR2(100),' || 
        'T_DEALCODETS VARCHAR2(30),' || 
        'T_DEALDATE DATE,' || 
        'T_DEALTIME DATE,' || 
        'T_MARKETNAME VARCHAR2(60),' || 
        'T_MARKETTYPE VARCHAR2(60),' || 
        'T_EXTBROKER VARCHAR2(320),' || 
        'T_EXTBROKERDOC VARCHAR2(20),' || 
        'T_DEALTYPE VARCHAR2(12),' || 
        'T_STATUS_PURCB VARCHAR2(26),' || 
        'T_SIDE1 VARCHAR2(320),' || 
        'T_SIDE2 VARCHAR2(320),' || 
        'T_CLIENT_ASSIGN VARCHAR2(50),' || 
        'T_CONFIRMDOC VARCHAR2(20),' || 
        'T_DUEPROCESS VARCHAR2(23),' || 
        'T_EXECMETHOD VARCHAR2(9),' || 
        'T_FORMPAYMENT VARCHAR2(35),' || 
        'T_ISBASKET NUMBER(5),' || 
        'T_DEALSUBKIND NUMBER(5),' || 
        'T_DEBET NUMBER(32,12),' || 
        'T_CREDIT NUMBER(32,12),' || 
        'T_ACCTYPE NUMBER(5),' || 
        'T_OPTIONTERMS VARCHAR2(100),' ||
        'T_FUTURESAMOUNT NUMBER(32,12),' ||
        'T_QUOTECUR VARCHAR2(3),' ||
        'T_OPTIONDEALBONUS NUMBER(32,12),' ||
        'T_BAKINDNAME VARCHAR2(30),' ||
        'T_DOCKIND NUMBER(10)' ||
        ')';

  EXECUTE IMMEDIATE 'COMMENT ON TABLE DDL_REGIABUF_DBT IS ''Отчет Реестр ВУ''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_FUTURESPRICE IS ''Цена фьючерского контракта''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_OUTSTANDCLAIMS IS ''Неисполненные требования''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_OUTSTANDOBL IS ''Неисполненные обязательства''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_ISBUY IS ''Покупка''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_ACCREST IS ''Остаток на счете''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_OPTIONPREMIUM IS ''Премия по опциону''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_KINDPFI IS ''Тип ПФИ''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_OPTIONTYPE IS ''Тип опциона''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_PART IS ''Раздел отчета''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALID IS ''Идентификатор сделки''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CURRCLAIMOBL IS ''Валюта требования/ обязательства''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALCODE IS ''Номер сделки''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_ACCOUNTNAME IS ''Наименование счета ВУ''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_ACCOUNT IS ''Номер счета ВУ''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CASHRIGHT IS ''Право на использование денежных средств клиента банком''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_RISKLEVEL IS ''Категория клиента''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CLIENTCVALINV IS ''Клиент является/не является квалифицированным инвестором''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CLIENTRESIDENT IS ''Клиент является/не является налоговым резидентом''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CLIENTCOUNTRY IS ''Гражданство Клиента''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CLIENTFORM IS ''Клиент является ФЛ/ЮЛ/ИП''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_PROXYNUM IS ''Доверенность клиента''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_PROXYNAME IS ''Представитель клиента''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_EXCHANGECODE IS ''Код на бирже''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CLIENTAGREND IS ''Дата расторжения''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CLIENTAGRDATE IS ''Дата заключения''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CLIENTAGR IS ''Договор с клиентом''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CLIENTNAME IS ''Наименование / код клиента''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_FACTDATEM IS ''Дата оплаты ценных бумаг Факт''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_PLANDATEM IS ''Дата оплаты ценных бумаг План''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_FACTDATESP IS ''Дата перерегистрации (поставки) ценных бумаг Факт''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_PLANDATESP IS ''Дата перерегистрации  (поставки) ценных бумаг План''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_BROKERCOMISS IS ''Комиссия брокера''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_INTERESTAMOUNT IS ''Сумма процентов''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_INTERESTRATE IS ''Cтавка % (РЕПО, займ)''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_SETCURRENCY IS ''Валюта расчетов''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_NOMINALCURRENCY IS ''Валюта номинала''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_PRICECURRENCY IS ''Валюта цены''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALVALUERUR IS ''Стоимость сделки в рублевом эквиваленте''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALVALUE IS ''Стоимость сделки''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_TOTALCOSTRUR IS ''Сумма сделки в рублевом эквиваленте''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_TOTALCOST IS ''Сумма сделки в валюте''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_COSTNATCUR IS ''Цена одной ценной бумаги в рублевом эквиваленте''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_COST IS ''Цена одной ценной бумаги в валюте''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_PRINCIPAL IS ''Количество ценных бумаг''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_ISSUERNAME IS ''Эмитент ценной бумаги''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_SECSERIES IS ''Выпуск / транш /  серия ценной бумаги''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_ISIN IS ''№гос.регистрации/ ISIN''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_SECCODE IS ''Наименование/ код ценной бумаги''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_SECSUBKIND IS ''Подвид ценной бумаги''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_SECKIND IS ''Вид ценной бумаги''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALKIND IS ''Вид сделки (покупка, продажа, займ, РЕПО и пр.)''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALDIRECTION IS ''Направление сделки''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALTYPEADR IS ''Вид заявки (адресная/ безадресная)''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_UNQUALIFIEDSEC IS ''Сделка с неквалифицированными ЦБ''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_GENAGR IS ''Генеральное соглашение''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALCODETS IS ''Внешний номер сделки''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALDATE IS ''Дата заключения сделки''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALTIME IS ''Время заключения сделки''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_MARKETNAME IS ''Место совершения сделки''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_MARKETTYPE IS ''Сектор биржи/режим торгов''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_EXTBROKER IS ''Внешний брокер''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_EXTBROKERDOC IS ''Номер договора с внешним брокером''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEALTYPE IS ''Тип сделки''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_STATUS_PURCB IS ''Сатус ПУРЦБ''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_SIDE1 IS ''Сторона 1''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_SIDE2 IS ''Сторона 2''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CLIENT_ASSIGN IS ''Поручение клиента на операцию''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CONFIRMDOC IS ''Подтверждающий документ''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DUEPROCESS IS ''Порядок исполнения обязательств''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_EXECMETHOD IS ''Способ исполнения обязательств''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_FORMPAYMENT IS ''Форма расчетов''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DEBET IS ''Списано по сделке''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_CREDIT IS ''Зачслено по сделке''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_ACCTYPE IS ''Тип счета ВУ (ЦБ, ДС, ФО)''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_OPTIONTERMS IS ''Условия по опциону''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_FUTURESAMOUNT IS ''Количество фьючерских контрактор''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_QUOTECUR IS ''Валюта котировки, премии по опциону''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_OPTIONDEALBONUS IS ''Премия по опциону''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_BAKINDNAME IS ''Базисный актив ПФИ''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REGIABUF_DBT.T_DOCKIND IS ''Вид документа''';
EXCEPTION 
    WHEN e_object_exists THEN NULL; 
END;
/

declare
 cnt number;
begin
  select count(*) into cnt from user_indexes i where i.TABLE_NAME='DDL_REGIABUF_DBT' and i.INDEX_NAME='DDL_REGIABUF_DBT_IDX0' ;
  if cnt =1 then
    execute immediate 'drop index DDL_REGIABUF_DBT_IDX0';
  end if;
  execute immediate 'CREATE UNIQUE INDEX DDL_REGIABUF_DBT_IDX0 ON DDL_REGIABUF_DBT (T_AUTOINC ASC)';
end;
/


declare
 cnt number;
begin
  select count(*) into cnt from user_indexes i where i.TABLE_NAME='DDL_REGIABUF_DBT' and i.INDEX_NAME='DDL_REGIABUF_DBT_IDX1' ;
  if cnt =1 then
    execute immediate 'drop index DDL_REGIABUF_DBT_IDX1';
  end if;
  execute immediate 'CREATE INDEX DDL_REGIABUF_DBT_IDX1 ON DDL_REGIABUF_DBT (T_PART ASC, T_DEALID ASC, T_DEALSUBKIND ASC, T_DEALPART ASC)';
end;
/

declare
 cnt number;
begin
  select count(*) into cnt from user_indexes i where i.TABLE_NAME='DDL_REGIABUF_DBT' and i.INDEX_NAME='DDL_REGIABUF_DBT_IDX2' ;
  if cnt =1 then
    execute immediate 'drop index DDL_REGIABUF_DBT_IDX2';
  end if;
  execute immediate 'CREATE INDEX DDL_REGIABUF_DBT_IDX2 ON DDL_REGIABUF_DBT (T_PART ASC,T_ACCTYPE ASC,T_ACCOUNT ASC)';
end;
/

declare
 cnt number;
begin
  select count(*) into cnt from user_indexes i where i.TABLE_NAME='DDL_REGIABUF_DBT' and i.INDEX_NAME='DDL_REGIABUF_DBT_IDX3' ;
  if cnt =1 then
    execute immediate 'drop index DDL_REGIABUF_DBT_IDX3';
  end if;
  execute immediate 'CREATE INDEX DDL_REGIABUF_DBT_IDX3 ON DDL_REGIABUF_DBT (T_PART ASC,T_CLIENTCONTRID ASC)';
end;
/

DECLARE
   vcnt   NUMBER;
BEGIN
   SELECT COUNT (*)
     INTO vcnt
     FROM user_sequences
    WHERE UPPER (sequence_name) = 'DDL_REGIABUF_DBT_SEQ';

   IF vcnt = 0
   THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE DDL_REGIABUF_DBT_SEQ
                                START WITH 1
                                MAXVALUE 9999999999999999999999999999
                                MINVALUE 1
                                NOCYCLE
                                NOCACHE
                                NOORDER';
   END IF;
END;
/

CREATE OR REPLACE TRIGGER DDL_REGIABUF_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_AUTOINC ON DDL_REGIABUF_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_AUTOINC = 0 OR :NEW.T_AUTOINC IS NULL) THEN
    SELECT DDL_REGIABUF_DBT_SEQ.NEXTVAL INTO :NEW.T_AUTOINC FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDL_REGIABUF_DBT_SEQ');
    IF :NEW.T_AUTOINC >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

declare
 cnt number;
begin
  select count(*) into cnt from user_indexes i where i.TABLE_NAME='DDL_REGIABUF_DBT' and i.INDEX_NAME='DDL_REGIABUF_DBT_IDX4' ;
  if cnt =1 then
    execute immediate 'drop index DDL_REGIABUF_DBT_IDX4';
  end if;
  execute immediate 'CREATE INDEX DDL_REGIABUF_DBT_IDX4 ON DDL_REGIABUF_DBT (T_SESSIONID)';
end;
/

declare
 cnt number;
begin
  select count(*) into cnt from user_indexes i where i.TABLE_NAME='DDL_REGIABUF_DBT' and i.INDEX_NAME='DDL_REGIABUF_DBT_IDX5' ;
  if cnt =1 then
    execute immediate 'drop index DDL_REGIABUF_DBT_IDX5';
  end if;
  execute immediate 'CREATE INDEX DDL_REGIABUF_DBT_IDX5 ON DDL_REGIABUF_DBT (T_CALCID)';
end;
/