
CREATE TABLE USR_CLEAR_LOG_PARAMS
(
   t_id              NUMBER,
   t_table_name      VARCHAR2 (4000),
   t_query           CLOB,
   t_last_clearing   DATE
);

CREATE SEQUENCE USR_CLEAR_LOG_PARAMS_ID_SEQ
   START WITH 1
   MAXVALUE 999999999999999999999999999
   MINVALUE 1
   NOCYCLE
   CACHE 50
   NOORDER;

CREATE OR REPLACE TRIGGER USR_CLEAR_LOG_PARAMS_AINC
   BEFORE INSERT OR UPDATE OF T_ID
   ON USR_CLEAR_LOG_PARAMS
   FOR EACH ROW
DECLARE
   v_id   INTEGER;
BEGIN
   IF (:NEW.t_id = 0 OR :NEW.t_id IS NULL)
   THEN
      SELECT   USR_CLEAR_LOG_PARAMS_ID_SEQ.NEXTVAL INTO :NEW.t_id FROM DUAL;
   ELSE
      SELECT   LAST_NUMBER
        INTO   v_id
        FROM   USER_SEQUENCES
       WHERE   SEQUENCE_NAME = UPPER ('USR_CLEAR_LOG_PARAMS_ID_SEQ');

      IF :NEW.t_id >= v_id
      THEN
         RAISE DUP_VAL_ON_INDEX;
      END IF;
   END IF;
END;
/