BEGIN
   INSERT INTO USR_CLEAR_LOG_PARAMS
	 VALUES   (
				  0,
				  'DXR_LOG_DBT',
				  'DECLARE
  max_id INTEGER := 0;
  min_id INTEGER := 0;
BEGIN
  SELECT max(t_id), min(t_id) INTO max_id, min_id FROM DXR_LOG_DBT WHERE t_sysdate < (sysdate - NUMTODSINTERVAL(7, ''DAY''));

  WHILE max_id >= min_id
  LOOP
    DELETE FROM DXR_LOG_DBT DX WHERE DX.T_ID BETWEEN (max_id - 10000) AND max_id;
    COMMIT;

    EXECUTE IMMEDIATE ''ALTER SESSION SET DDL_LOCK_TIMEOUT = 60'';
    EXECUTE IMMEDIATE ''ALTER TABLE DXR_LOG_DBT ENABLE ROW MOVEMENT'';
    EXECUTE IMMEDIATE ''ALTER TABLE DXR_LOG_DBT SHRINK SPACE COMPACT'';
    EXECUTE IMMEDIATE ''ALTER TABLE DXR_LOG_DBT SHRINK SPACE CASCADE'';
    EXECUTE IMMEDIATE ''ALTER TABLE DXR_LOG_DBT DISABLE ROW MOVEMENT'';
    EXECUTE IMMEDIATE ''ALTER SESSION SET DDL_LOCK_TIMEOUT = 0'';

    max_id := max_id - 10000;
  END LOOP;
END;
',  NULL);

                                   
INSERT INTO USR_CLEAR_LOG_PARAMS
	 VALUES   (
				  0,
				  'DQUEUE_LOG_DBT',
				  'DECLARE
  max_id INTEGER := 0;
  min_id INTEGER := 0;
BEGIN
  SELECT max(t_id), min(t_id) INTO max_id, min_id FROM DQUEUE_LOG_DBT WHERE t_sysdate < (sysdate - NUMTODSINTERVAL(7, ''DAY''));

  WHILE max_id >= min_id
  LOOP
    DELETE FROM DQUEUE_LOG_DBT DQ WHERE DQ.T_ID BETWEEN (max_id - 10000) AND max_id;
    COMMIT;

    EXECUTE IMMEDIATE ''ALTER SESSION SET DDL_LOCK_TIMEOUT = 60'';
    EXECUTE IMMEDIATE ''ALTER TABLE DXR_LOG_DBT ENABLE ROW MOVEMENT'';
    EXECUTE IMMEDIATE ''ALTER TABLE DXR_LOG_DBT SHRINK SPACE COMPACT'';
    EXECUTE IMMEDIATE ''ALTER TABLE DXR_LOG_DBT SHRINK SPACE CASCADE'';
    EXECUTE IMMEDIATE ''ALTER TABLE DXR_LOG_DBT DISABLE ROW MOVEMENT'';
    EXECUTE IMMEDIATE ''ALTER SESSION SET DDL_LOCK_TIMEOUT = 0'';

    max_id := max_id - 10000;
  END LOOP;
END;
',  NULL);

END;
/