preprod:
  hosts:
    tst-sofr-ap02:
      ansible_host: 10.21.20.41
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_scheme: https
      ansible_winrm_transport: certificate
      ansible_winrm_cert_pem: .cicd/client-cert.pem
      ansible_winrm_cert_key_pem: .cicd/client-cert.pem
    # tst-sofr-ap05: # is ansible controller (master node) now
    #   ansible_host: 10.21.20.43
    #   ansible_connection: winrm
    #   ansible_port: 5986
    #   ansible_winrm_scheme: https
    #   ansible_winrm_transport: certificate
    #   ansible_winrm_cert_pem: .cicd/client-cert.pem
    #   ansible_winrm_cert_key_pem: .cicd/client-cert.pem
    # tst-sofr-ap06: # is empty
    #   ansible_host: 10.21.20.45
    #   ansible_connection: winrm
    #   ansible_port: 5986
    #   ansible_winrm_scheme: https
    #   ansible_winrm_transport: certificate
    #   ansible_winrm_cert_pem: .cicd/client-cert.pem
    #   ansible_winrm_cert_key_pem: .cicd/client-cert.pem