DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE DWREPOREP_TMP';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DWREPOREP_TMP (
    T_PARTYNAME VARCHAR2(320)
  , T_ENDDEALSUMRUR NUMBER(32,12)
  , T_ENDDEALSUM NUMBER(32,12)
  , T_BEGDEALSUMRUR NUMBER(32,12)
  , T_BEGDEALSUM NUMBER(32,12)
  , T_DEALCODE VARCHAR2(30)
  , T_ISSUERNAME VARCHAR2(320)
  , T_DEALCUR VARCHAR2(3)
  , T_DEALTYPE VARCHAR2(20)
) ON COMMIT PRESERVE ROWS
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE DDL_REPORT_REPO_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/

CREATE TABLE DDL_REPORT_REPO_DBT (
    T_PERIOD VARCHAR2(29)
  , T_OPER NUMBER(10)
  , T_OPERDATE DATE
  , T_SYSDATE DATE
  , T_ID NUMBER(10)
  , T_SYSTIME DATE
  , T_ERR NUMBER(5)
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_REPORT_REPO_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DDL_REPORT_REPO_DBT_IDX0 ON DDL_REPORT_REPO_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DDL_REPORT_REPO_DBT_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE DDL_REPORT_REPO_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DDL_REPORT_REPO_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDL_REPORT_REPO_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDL_REPORT_REPO_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDL_REPORT_REPO_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END
/