BEGIN
  EXECUTE IMMEDIATE 'alter table DDL_REPORT_OVER4742_TMP add T_NUMACC VARCHAR2(25)';
  EXECUTE IMMEDIATE 'alter table DDL_REPORT_OVER4742_TMP add T_EXIST_ACC NUMBER(32,12)';
EXCEPTION 
 WHEN OTHERS THEN NULL;
END;
/
