-- Таблица "DASTS_CURRLOTSIZE_DBT"

CREATE TABLE DASTS_CURRLOTSIZE_DBT (
    T_ID NUMBER(10)
  , T_MAIN_BOARD VARCHAR2(4)
  , T_SECCODE VARCHAR2(12)
  , T_LOTAMOUNT NUMBER(32,12)
)
/

COMMENT ON TABLE DASTS_CURRLOTSIZE_DBT IS 'Таблица размеров лотов ВР'/
COMMENT ON COLUMN DASTS_CURRLOTSIZE_DBT.T_ID IS 'ID записи'/
COMMENT ON COLUMN DASTS_CURRLOTSIZE_DBT.T_MAIN_BOARD IS 'Режим торгов'/
COMMENT ON COLUMN DASTS_CURRLOTSIZE_DBT.T_SECCODE IS 'Код инструмента'/
COMMENT ON COLUMN DASTS_CURRLOTSIZE_DBT.T_LOTAMOUNT IS 'Размер лота'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DASTS_CURRLOTSIZE_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DASTS_CURRLOTSIZE_DBT_IDX0 ON DASTS_CURRLOTSIZE_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DASTS_CURRLOTSIZE_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DASTS_CURRLOTSIZE_DBT_IDX1 ON DASTS_CURRLOTSIZE_DBT (
   T_MAIN_BOARD ASC
  ,T_SECCODE ASC
)/

CREATE SEQUENCE DASTS_CURRLOTSIZE_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DASTS_CURRLOTSIZE_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DASTS_CURRLOTSIZE_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DASTS_CURRLOTSIZE_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DASTS_CURRLOTSIZE_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

