DECLARE
    cnt       NUMBER;
BEGIN
    SELECT COUNT (1)
      INTO cnt
      FROM DOBJATCOR_DBT 
     WHERE T_OBJECTTYPE = RSB_SECUR.OBJTYPE_SECDEAL AND T_GROUPID = 118;

    IF CNT > 0
    THEN
      DELETE FROM DOBJATCOR_DBT WHERE T_OBJECTTYPE = RSB_SECUR.OBJTYPE_SECDEAL AND T_GROUPID = 118;
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
END;
/