-- Таблица "DOWNBONDSREGISTER_TMP"

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE DOWNBONDSREGISTER_TMP';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DOWNBONDSREGISTER_TMP (
    T_DRAWINGDATE DATE
  , T_DRAWPERIOD NUMBER(5)
  , T_INCOMERATE NUMBER(32,12)
  , T_CALCNKD NUMBER(32,12)
  , T_FIXDATE DATE
  , T_ISBUY CHAR(1)
) ON COMMIT PRESERVE ROWS
/

COMMENT ON TABLE DOWNBONDSREGISTER_TMP IS 'downbondsregister_tmp'/
COMMENT ON COLUMN DOWNBONDSREGISTER_TMP.T_DRAWINGDATE IS 'Дата выплаты купона'/
COMMENT ON COLUMN DOWNBONDSREGISTER_TMP.T_DRAWPERIOD IS 'Период расчёта купона'/
COMMENT ON COLUMN DOWNBONDSREGISTER_TMP.T_INCOMERATE IS 'Размер купона в %'/
COMMENT ON COLUMN DOWNBONDSREGISTER_TMP.T_CALCNKD IS 'НКД на 1шт. на дату выплаты'/
COMMENT ON COLUMN DOWNBONDSREGISTER_TMP.T_FIXDATE IS 'Дата фиксации обязательств'/
COMMENT ON COLUMN DOWNBONDSREGISTER_TMP.T_ISBUY IS 'Погашение купона при выкупе'/