BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DVALINTMARKETRATE_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX DVALINTMARKETRATE_DBT_IDX1 ON DVALINTMARKETRATE_DBT (T_MARKETRATEID ASC, T_BEGINDATE ASC)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/