DECLARE
  v_ID       NUMBER := 0;
  v_ParentID NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = 0 AND LOWER(T_NAME) = LOWER('РСХБ');
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('6-НДФЛ 2023');

  INSERT INTO DREGPARM_DBT(T_KEYID,T_PARENTID,T_NAME,T_TYPE,T_GLOBAL,T_DESCRIPTION,T_SECURITY,T_ISBRANCH,T_TEMPLATE )
  VALUES(0,v_ParentID,'2024 ДАТА ОТСЧЕТА РАЗДЕЛА 1',2,'X','Дата отсчета для Раздела 1. Налоговый период 2024',CHR(0),CHR(0),CHR(1)) returning T_KEYID INTO v_ID;

  INSERT INTO DREGVAL_DBT(T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX )
  VALUES(v_ID,0,0,CHR(0),0,0,0,'31352E30322E3230323500');

  INSERT INTO DREGPARM_DBT(T_KEYID,T_PARENTID,T_NAME,T_TYPE,T_GLOBAL,T_DESCRIPTION,T_SECURITY,T_ISBRANCH,T_TEMPLATE )
  VALUES(0,v_ParentID,'2024 ДАТА ОТСЧЕТА РАЗДЕЛА 2',2,'X','Дата отсчета для Раздела 2. Налоговый период 2024',CHR(0),CHR(0),CHR(1)) returning T_KEYID INTO v_ID;

  INSERT INTO DREGVAL_DBT(T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX )
  VALUES(v_ID,0,0,CHR(0),0,0,0,'31352E30322E3230323500');


EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/
