
DECLARE 
 v_Exist NUMBER := 0;
BEGIN
  SELECT count(1) INTO v_Exist FROM DOBJECTS_DBT WHERE T_OBJECTTYPE = 5065;
  if v_Exist = 0 THEN
   INSERT INTO DOBJECTS_DBT (T_OBJECTTYPE,
                             T_NAME,
                             T_CODE,
                             T_USERNUMBER,
                             T_PARENTOBJECTTYPE,
                             T_SERVICEMACRO,
                             T_MODULE)
        VALUES (5065,
                'Класс переоцениваемых счетов',
                'КлПереоц',
                0,
                0,
                CHR (1),
                CHR (0));

   INSERT INTO DLLCLASS_DBT (T_CLASSIFICATOR,
                             T_LIST,
                             T_SHORTNAME,
                             T_NAME,
                             T_RESERVED)
        VALUES (5065,
                5065,
                'КлассПереоценки',
                'Класс переоцениваемых счетов',
                CHR (1));

   INSERT INTO DLLCLSVAL_DBT (T_CLASSIFICATOR,
                              T_ELEMENT,
                              T_LIST,
                              T_ISSYS,
                              T_SORT)
        VALUES (5065,
                1,
                5065,
                CHR (0),
                0);

   INSERT INTO DLLCLSVAL_DBT (T_CLASSIFICATOR,
                              T_ELEMENT,
                              T_LIST,
                              T_ISSYS,
                              T_SORT)
        VALUES (5065,
                2,
                5065,
                CHR (0),
                0);

   INSERT INTO DLLVALUES_DBT (T_LIST,
                              T_ELEMENT,
                              T_CODE,
                              T_NAME,
                              T_FLAG,
                              T_NOTE,
                              T_RESERVE)
        VALUES (5065,
                1,
                '1',
                'Счета 5-го класса',
                1,
                CHR (1),
                CHR (1));

   INSERT INTO DLLVALUES_DBT (T_LIST,
                              T_ELEMENT,
                              T_CODE,
                              T_NAME,
                              T_FLAG,
                              T_NOTE,
                              T_RESERVE)
        VALUES (5065,
                2,
                '2',
                'Прочие счета',
                2,
                CHR (1),
                CHR (1));
  END IF;
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

BEGIN
   UPDATE DMCCATEG_DBT
      SET T_PARAM4 = 5065, T_CLASS4 = 5065
    WHERE T_CODE IN ('+ПереоценкаА', '-ПереоценкаА');
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

DECLARE
   v_CatID       NUMBER := 0;
   v_CatNumber   NUMBER := 0;
   v_Number      NUMBER := 0;
   v_Exist       NUMBER := 0;
BEGIN
   SELECT T_ID, T_NUMBER
     INTO v_CatID, v_CatNumber
     FROM dmccateg_dbt
    WHERE T_CODE = '+ПереоценкаА';



   IF v_CatID > 0
   THEN
      SELECT count(1) INTO v_Exist FROM DMCTEMPL_DBT WHERE T_CATID = v_CatID AND T_BALANCE = '70603' AND T_MASK = '26301ZZ' AND T_VALUE1 = 1 AND T_VALUE2 = 0 AND T_VALUE3 = 0 AND T_VALUE4 = 1;
      if v_Exist = 0 THEN
      SELECT MAX (T_NUMBER)
        INTO v_Number
        FROM DMCTEMPL_DBT
       WHERE T_CATID = v_CatID;

      v_Number := v_Number + 1;

      INSERT INTO DMCTEMPL_DBT (T_CATID,
                                T_NUMBER,
                                T_VALUE1,
                                T_VALUE2,
                                T_VALUE3,
                                T_VALUE4,
                                T_VALUE5,
                                T_VALUE6,
                                T_VALUE7,
                                T_VALUE8,
                                T_CHAPTER,
                                T_BALANCE,
                                T_MASK,
                                T_KIND_ACCOUNT,
                                T_GROUPNUM,
                                T_HASPERIOD,
                                T_NOTAUTO,
                                T_ISCLOSE,
                                T_ACCOUNTCLIENT,
                                T_TYPEACCOUNT,
                                T_RESERVE)
           VALUES (v_CatID,
                   v_Number,
                   1,
                   0,
                   0,
                   1,
                   -1,
                   -1,
                   -1,
                   -1,
                   1,
                   '70603',
                   '26301ZZ',
                   'П',
                   0,
                   CHR (0),
                   CHR (88),
                   CHR (0),
                   0,
                   'Ц',
                   CHR (1));

      INSERT INTO DMCACCDOC_DBT (T_ID,
                                 T_ISCOMMON,
                                 T_DOCKIND,
                                 T_DOCID,
                                 T_CATID,
                                 T_CATNUM,
                                 T_CHAPTER,
                                 T_ACCOUNT,
                                 T_CURRENCY,
                                 T_TEMPLNUM,
                                 T_GROUPNUM,
                                 T_PERIODID,
                                 T_ACTIVATEDATE,
                                 T_DISABLINGDATE,
                                 T_ISUSABLE,
                                 T_FIID,
                                 T_OWNER,
                                 T_PLACE,
                                 T_ISSUER,
                                 T_KIND_ACCOUNT,
                                 T_CENTR,
                                 T_CENTROFFICE,
                                 T_ACTIONDATE,
                                 T_FIID2,
                                 T_CLIENTCONTRID,
                                 T_BANKCONTRID,
                                 T_MARKETPLACEID,
                                 T_MARKETPLACEOFFICEID,
                                 T_FIROLE,
                                 T_INDEXDATE,
                                 T_DEPARTMENTID,
                                 T_CONTRACTOR,
                                 T_BRANCH,
                                 T_CORRDEPARTMENTID,
                                 T_CURRENCYEQ,
                                 T_CURRENCYEQ_RATETYPE,
                                 T_CURRENCYEQ_RATEDATE,
                                 T_CURRENCYEQ_RATEEXTRA,
                                 T_MCBRANCH)
           VALUES (0,
                   CHR (88),
                   0,
                   0,
                   v_CatID,
                   v_CatNumber,
                   1,
                   '70603810400002630102',
                   (SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '810'),
                   v_Number,
                   0,
                   0,
                   TRUNC (SYSDATE),
                   TO_DATE ('01.01.0001', 'dd.mm.yyyy'),
                   CHR (88),
                   NVL((SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '840'),0),
                   -1,
                   -1,
                   -1,
                   'П',
                   -1,
                   -1,
                   TRUNC (SYSDATE),
                   -1,
                   -1,
                   -1,
                   -1,
                   -1,
                   0,
                   -1,
                   1,
                   -1,
                   1,
                   0,
                   -1,
                   0,
                   0,
                   0,
                   1);

      INSERT INTO DMCACCDOC_DBT (T_ID,
                                 T_ISCOMMON,
                                 T_DOCKIND,
                                 T_DOCID,
                                 T_CATID,
                                 T_CATNUM,
                                 T_CHAPTER,
                                 T_ACCOUNT,
                                 T_CURRENCY,
                                 T_TEMPLNUM,
                                 T_GROUPNUM,
                                 T_PERIODID,
                                 T_ACTIVATEDATE,
                                 T_DISABLINGDATE,
                                 T_ISUSABLE,
                                 T_FIID,
                                 T_OWNER,
                                 T_PLACE,
                                 T_ISSUER,
                                 T_KIND_ACCOUNT,
                                 T_CENTR,
                                 T_CENTROFFICE,
                                 T_ACTIONDATE,
                                 T_FIID2,
                                 T_CLIENTCONTRID,
                                 T_BANKCONTRID,
                                 T_MARKETPLACEID,
                                 T_MARKETPLACEOFFICEID,
                                 T_FIROLE,
                                 T_INDEXDATE,
                                 T_DEPARTMENTID,
                                 T_CONTRACTOR,
                                 T_BRANCH,
                                 T_CORRDEPARTMENTID,
                                 T_CURRENCYEQ,
                                 T_CURRENCYEQ_RATETYPE,
                                 T_CURRENCYEQ_RATEDATE,
                                 T_CURRENCYEQ_RATEEXTRA,
                                 T_MCBRANCH)
           VALUES (0,
                   CHR (88),
                   0,
                   0,
                   v_CatID,
                   v_CatNumber,
                   1,
                   '70603810000002630104',
                   (SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '810'),
                   v_Number,
                   0,
                   0,
                   TRUNC (SYSDATE),
                   TO_DATE ('01.01.0001', 'dd.mm.yyyy'),
                   CHR (88),
                   NVL((SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '978'),0),
                   -1,
                   -1,
                   -1,
                   'П',
                   -1,
                   -1,
                   TRUNC (SYSDATE),
                   -1,
                   -1,
                   -1,
                   -1,
                   -1,
                   0,
                   -1,
                   1,
                   -1,
                   1,
                   0,
                   -1,
                   0,
                   0,
                   0,
                   1);

      INSERT INTO DMCACCDOC_DBT (T_ID,
                                 T_ISCOMMON,
                                 T_DOCKIND,
                                 T_DOCID,
                                 T_CATID,
                                 T_CATNUM,
                                 T_CHAPTER,
                                 T_ACCOUNT,
                                 T_CURRENCY,
                                 T_TEMPLNUM,
                                 T_GROUPNUM,
                                 T_PERIODID,
                                 T_ACTIVATEDATE,
                                 T_DISABLINGDATE,
                                 T_ISUSABLE,
                                 T_FIID,
                                 T_OWNER,
                                 T_PLACE,
                                 T_ISSUER,
                                 T_KIND_ACCOUNT,
                                 T_CENTR,
                                 T_CENTROFFICE,
                                 T_ACTIONDATE,
                                 T_FIID2,
                                 T_CLIENTCONTRID,
                                 T_BANKCONTRID,
                                 T_MARKETPLACEID,
                                 T_MARKETPLACEOFFICEID,
                                 T_FIROLE,
                                 T_INDEXDATE,
                                 T_DEPARTMENTID,
                                 T_CONTRACTOR,
                                 T_BRANCH,
                                 T_CORRDEPARTMENTID,
                                 T_CURRENCYEQ,
                                 T_CURRENCYEQ_RATETYPE,
                                 T_CURRENCYEQ_RATEDATE,
                                 T_CURRENCYEQ_RATEEXTRA,
                                 T_MCBRANCH)
           VALUES (0,
                   CHR (88),
                   0,
                   0,
                   v_CatID,
                   v_CatNumber,
                   1,
                   '70603810000002630129',
                   (SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '810'),
                   v_Number,
                   0,
                   0,
                   TRUNC (SYSDATE),
                   TO_DATE ('01.01.0001', 'dd.mm.yyyy'),
                   CHR (88),
                   NVL((SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '156'),0),
                   -1,
                   -1,
                   -1,
                   'П',
                   -1,
                   -1,
                   TRUNC (SYSDATE),
                   -1,
                   -1,
                   -1,
                   -1,
                   -1,
                   0,
                   -1,
                   1,
                   -1,
                   1,
                   0,
                   -1,
                   0,
                   0,
                   0,
                   1);

      INSERT INTO DMCACCDOC_DBT (T_ID,
                                 T_ISCOMMON,
                                 T_DOCKIND,
                                 T_DOCID,
                                 T_CATID,
                                 T_CATNUM,
                                 T_CHAPTER,
                                 T_ACCOUNT,
                                 T_CURRENCY,
                                 T_TEMPLNUM,
                                 T_GROUPNUM,
                                 T_PERIODID,
                                 T_ACTIVATEDATE,
                                 T_DISABLINGDATE,
                                 T_ISUSABLE,
                                 T_FIID,
                                 T_OWNER,
                                 T_PLACE,
                                 T_ISSUER,
                                 T_KIND_ACCOUNT,
                                 T_CENTR,
                                 T_CENTROFFICE,
                                 T_ACTIONDATE,
                                 T_FIID2,
                                 T_CLIENTCONTRID,
                                 T_BANKCONTRID,
                                 T_MARKETPLACEID,
                                 T_MARKETPLACEOFFICEID,
                                 T_FIROLE,
                                 T_INDEXDATE,
                                 T_DEPARTMENTID,
                                 T_CONTRACTOR,
                                 T_BRANCH,
                                 T_CORRDEPARTMENTID,
                                 T_CURRENCYEQ,
                                 T_CURRENCYEQ_RATETYPE,
                                 T_CURRENCYEQ_RATEDATE,
                                 T_CURRENCYEQ_RATEEXTRA,
                                 T_MCBRANCH)
           VALUES (0,
                   CHR (88),
                   0,
                   0,
                   v_CatID,
                   v_CatNumber,
                   1,
                   '70603810900002630107',
                   (SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '810'),
                   v_Number,
                   0,
                   0,
                   TRUNC (SYSDATE),
                   TO_DATE ('01.01.0001', 'dd.mm.yyyy'),
                   CHR (88),
                   NVL((SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '756'),0),
                   -1,
                   -1,
                   -1,
                   'П',
                   -1,
                   -1,
                   TRUNC (SYSDATE),
                   -1,
                   -1,
                   -1,
                   -1,
                   -1,
                   0,
                   -1,
                   1,
                   -1,
                   1,
                   0,
                   -1,
                   0,
                   0,
                   0,
                   1);
      END IF;
   END IF;

   v_CatID := 0;
   v_CatNumber := 0;
   v_Number := 0;

   SELECT T_ID, T_NUMBER
     INTO v_CatID, v_CatNumber
     FROM dmccateg_dbt
    WHERE T_CODE = '-ПереоценкаА';



   IF v_CatID > 0
   THEN
      SELECT count(1) INTO v_Exist FROM DMCTEMPL_DBT WHERE T_CATID = v_CatID AND T_BALANCE = '70608' AND T_MASK = '46301ZZ' AND T_VALUE1 = 1 AND T_VALUE2 = 0 AND T_VALUE3 = 0 AND T_VALUE4 = 1;
      if v_Exist = 0 THEN
      SELECT MAX (T_NUMBER)
        INTO v_Number
        FROM DMCTEMPL_DBT
       WHERE T_CATID = v_CatID;

      v_Number := v_Number + 1;

      INSERT INTO DMCTEMPL_DBT (T_CATID,
                                T_NUMBER,
                                T_VALUE1,
                                T_VALUE2,
                                T_VALUE3,
                                T_VALUE4,
                                T_VALUE5,
                                T_VALUE6,
                                T_VALUE7,
                                T_VALUE8,
                                T_CHAPTER,
                                T_BALANCE,
                                T_MASK,
                                T_KIND_ACCOUNT,
                                T_GROUPNUM,
                                T_HASPERIOD,
                                T_NOTAUTO,
                                T_ISCLOSE,
                                T_ACCOUNTCLIENT,
                                T_TYPEACCOUNT,
                                T_RESERVE)
           VALUES (v_CatID,
                   v_Number,
                   1,
                   0,
                   0,
                   1,
                   -1,
                   -1,
                   -1,
                   -1,
                   1,
                   '70608',
                   '46301ZZ',
                   'А',
                   0,
                   CHR (0),
                   CHR (88),
                   CHR (0),
                   0,
                   'Ц',
                   CHR (1));

      INSERT INTO DMCACCDOC_DBT (T_ID,
                                 T_ISCOMMON,
                                 T_DOCKIND,
                                 T_DOCID,
                                 T_CATID,
                                 T_CATNUM,
                                 T_CHAPTER,
                                 T_ACCOUNT,
                                 T_CURRENCY,
                                 T_TEMPLNUM,
                                 T_GROUPNUM,
                                 T_PERIODID,
                                 T_ACTIVATEDATE,
                                 T_DISABLINGDATE,
                                 T_ISUSABLE,
                                 T_FIID,
                                 T_OWNER,
                                 T_PLACE,
                                 T_ISSUER,
                                 T_KIND_ACCOUNT,
                                 T_CENTR,
                                 T_CENTROFFICE,
                                 T_ACTIONDATE,
                                 T_FIID2,
                                 T_CLIENTCONTRID,
                                 T_BANKCONTRID,
                                 T_MARKETPLACEID,
                                 T_MARKETPLACEOFFICEID,
                                 T_FIROLE,
                                 T_INDEXDATE,
                                 T_DEPARTMENTID,
                                 T_CONTRACTOR,
                                 T_BRANCH,
                                 T_CORRDEPARTMENTID,
                                 T_CURRENCYEQ,
                                 T_CURRENCYEQ_RATETYPE,
                                 T_CURRENCYEQ_RATEDATE,
                                 T_CURRENCYEQ_RATEEXTRA,
                                 T_MCBRANCH)
           VALUES (0,
                   CHR (88),
                   0,
                   0,
                   v_CatID,
                   v_CatNumber,
                   1,
                   '70608810500004630102',
                   (SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '810'),
                   v_Number,
                   0,
                   0,
                   TRUNC (SYSDATE),
                   TO_DATE ('01.01.0001', 'dd.mm.yyyy'),
                   CHR (88),
                   NVL((SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '840'),0),
                   -1,
                   -1,
                   -1,
                   'А',
                   -1,
                   -1,
                   TRUNC (SYSDATE),
                   -1,
                   -1,
                   -1,
                   -1,
                   -1,
                   0,
                   -1,
                   1,
                   -1,
                   1,
                   0,
                   -1,
                   0,
                   0,
                   0,
                   1);

      INSERT INTO DMCACCDOC_DBT (T_ID,
                                 T_ISCOMMON,
                                 T_DOCKIND,
                                 T_DOCID,
                                 T_CATID,
                                 T_CATNUM,
                                 T_CHAPTER,
                                 T_ACCOUNT,
                                 T_CURRENCY,
                                 T_TEMPLNUM,
                                 T_GROUPNUM,
                                 T_PERIODID,
                                 T_ACTIVATEDATE,
                                 T_DISABLINGDATE,
                                 T_ISUSABLE,
                                 T_FIID,
                                 T_OWNER,
                                 T_PLACE,
                                 T_ISSUER,
                                 T_KIND_ACCOUNT,
                                 T_CENTR,
                                 T_CENTROFFICE,
                                 T_ACTIONDATE,
                                 T_FIID2,
                                 T_CLIENTCONTRID,
                                 T_BANKCONTRID,
                                 T_MARKETPLACEID,
                                 T_MARKETPLACEOFFICEID,
                                 T_FIROLE,
                                 T_INDEXDATE,
                                 T_DEPARTMENTID,
                                 T_CONTRACTOR,
                                 T_BRANCH,
                                 T_CORRDEPARTMENTID,
                                 T_CURRENCYEQ,
                                 T_CURRENCYEQ_RATETYPE,
                                 T_CURRENCYEQ_RATEDATE,
                                 T_CURRENCYEQ_RATEEXTRA,
                                 T_MCBRANCH)
           VALUES (0,
                   CHR (88),
                   0,
                   0,
                   v_CatID,
                   v_CatNumber,
                   1,
                   '70608810100004630104',
                   (SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '810'),
                   v_Number,
                   0,
                   0,
                   TRUNC (SYSDATE),
                   TO_DATE ('01.01.0001', 'dd.mm.yyyy'),
                   CHR (88),
                   NVL((SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '978'),0),
                   -1,
                   -1,
                   -1,
                   'А',
                   -1,
                   -1,
                   TRUNC (SYSDATE),
                   -1,
                   -1,
                   -1,
                   -1,
                   -1,
                   0,
                   -1,
                   1,
                   -1,
                   1,
                   0,
                   -1,
                   0,
                   0,
                   0,
                   1);

      INSERT INTO DMCACCDOC_DBT (T_ID,
                                 T_ISCOMMON,
                                 T_DOCKIND,
                                 T_DOCID,
                                 T_CATID,
                                 T_CATNUM,
                                 T_CHAPTER,
                                 T_ACCOUNT,
                                 T_CURRENCY,
                                 T_TEMPLNUM,
                                 T_GROUPNUM,
                                 T_PERIODID,
                                 T_ACTIVATEDATE,
                                 T_DISABLINGDATE,
                                 T_ISUSABLE,
                                 T_FIID,
                                 T_OWNER,
                                 T_PLACE,
                                 T_ISSUER,
                                 T_KIND_ACCOUNT,
                                 T_CENTR,
                                 T_CENTROFFICE,
                                 T_ACTIONDATE,
                                 T_FIID2,
                                 T_CLIENTCONTRID,
                                 T_BANKCONTRID,
                                 T_MARKETPLACEID,
                                 T_MARKETPLACEOFFICEID,
                                 T_FIROLE,
                                 T_INDEXDATE,
                                 T_DEPARTMENTID,
                                 T_CONTRACTOR,
                                 T_BRANCH,
                                 T_CORRDEPARTMENTID,
                                 T_CURRENCYEQ,
                                 T_CURRENCYEQ_RATETYPE,
                                 T_CURRENCYEQ_RATEDATE,
                                 T_CURRENCYEQ_RATEEXTRA,
                                 T_MCBRANCH)
           VALUES (0,
                   CHR (88),
                   0,
                   0,
                   v_CatID,
                   v_CatNumber,
                   1,
                   '70608810800004630129',
                   (SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '810'),
                   v_Number,
                   0,
                   0,
                   TRUNC (SYSDATE),
                   TO_DATE ('01.01.0001', 'dd.mm.yyyy'),
                   CHR (88),
                   NVL((SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '156'),0),
                   -1,
                   -1,
                   -1,
                   'А',
                   -1,
                   -1,
                   TRUNC (SYSDATE),
                   -1,
                   -1,
                   -1,
                   -1,
                   -1,
                   0,
                   -1,
                   1,
                   -1,
                   1,
                   0,
                   -1,
                   0,
                   0,
                   0,
                   1);

      INSERT INTO DMCACCDOC_DBT (T_ID,
                                 T_ISCOMMON,
                                 T_DOCKIND,
                                 T_DOCID,
                                 T_CATID,
                                 T_CATNUM,
                                 T_CHAPTER,
                                 T_ACCOUNT,
                                 T_CURRENCY,
                                 T_TEMPLNUM,
                                 T_GROUPNUM,
                                 T_PERIODID,
                                 T_ACTIVATEDATE,
                                 T_DISABLINGDATE,
                                 T_ISUSABLE,
                                 T_FIID,
                                 T_OWNER,
                                 T_PLACE,
                                 T_ISSUER,
                                 T_KIND_ACCOUNT,
                                 T_CENTR,
                                 T_CENTROFFICE,
                                 T_ACTIONDATE,
                                 T_FIID2,
                                 T_CLIENTCONTRID,
                                 T_BANKCONTRID,
                                 T_MARKETPLACEID,
                                 T_MARKETPLACEOFFICEID,
                                 T_FIROLE,
                                 T_INDEXDATE,
                                 T_DEPARTMENTID,
                                 T_CONTRACTOR,
                                 T_BRANCH,
                                 T_CORRDEPARTMENTID,
                                 T_CURRENCYEQ,
                                 T_CURRENCYEQ_RATETYPE,
                                 T_CURRENCYEQ_RATEDATE,
                                 T_CURRENCYEQ_RATEEXTRA,
                                 T_MCBRANCH)
           VALUES (0,
                   CHR (88),
                   0,
                   0,
                   v_CatID,
                   v_CatNumber,
                   1,
                   '70608810000004630107',
                   (SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '810'),
                   v_Number,
                   0,
                   0,
                   TRUNC (SYSDATE),
                   TO_DATE ('01.01.0001', 'dd.mm.yyyy'),
                   CHR (88),
                   NVL((SELECT T_FIID
                      FROM DFININSTR_DBT
                     WHERE T_CODEINACCOUNT = '756'),0),
                   -1,
                   -1,
                   -1,
                   'А',
                   -1,
                   -1,
                   TRUNC (SYSDATE),
                   -1,
                   -1,
                   -1,
                   -1,
                   -1,
                   0,
                   -1,
                   1,
                   -1,
                   1,
                   0,
                   -1,
                   0,
                   0,
                   0,
                   1);
      END IF;
   END IF;
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/