BEGIN
   EXECUTE IMMEDIATE 'alter table DIMPOPRDU_TMP ADD T_ImportID varchar2(10)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DIMPOPRDU_TMP.T_ImportID IS ''ID Операции выгрузки''';
END;
/

BEGIN
  INSERT INTO DNOTEKIND_DBT(T_OBJECTTYPE, T_NOTEKIND, T_NOTETYPE, T_NAME, T_KEEPOLDVALUES, T_NOTINUSE, T_ISPROTECTED,
                            T_MAXLEN, T_NOTUSEFIELDUSE, T_MACRONAME, T_DECPL, T_ISPROGONLY)
              VALUES(101,39,7,'ID строки файла ц/б, выведенных из ДУ',CHR(0),CHR(0),CHR(0),0,CHR(0),CHR(1),0,CHR(0));
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/