DECLARE
BEGIN
  INSERT INTO DOPRSYSTP_DBT(T_DOCKIND,T_TYPE,T_NAME_TYPE,T_CONTENS,T_RESERVED)
  VALUES(199,'K','Клиентская','Клиентская',CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSYSTP_DBT(T_DOCKIND,T_TYPE,T_NAME_TYPE,T_CONTENS,T_RESERVED)
  VALUES(4813,'K','Клиентская','Клиентская',CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  UPDATE DOPRKOPER_DBT
     SET T_SYSTYPES = T_SYSTYPES || 'K'
   WHERE T_KIND_OPERATION = 32715 AND INSTR (T_SYSTYPES, 'K') = 0;
END;
/


DECLARE
BEGIN
  UPDATE DOPRKOPER_DBT
     SET T_SYSTYPES = T_SYSTYPES || 'K'
   WHERE T_KIND_OPERATION = 32730 AND INSTR (T_SYSTYPES, 'K') = 0;
END;
/

