--Добавление поля
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DASTSCURR_TRADES_DBT ADD T_SECBOARD VARCHAR2(4) DEFAULT CHR(0)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DASTSCURR_TRADES_DEL_DBT ADD T_SECBOARD VARCHAR2(4) DEFAULT CHR(0)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER DASTSCURR_TRADES_DBT_HIST
  BEFORE DELETE ON DASTSCURR_TRADES_DBT
  FOR EACH ROW
DECLARE
  HISTID INTEGER;
BEGIN
INSERT INTO DASTSCURR_TRADES_DEL_DBT (
T_ID,
T_IS_SNAPSHOT,
T_TRADENO ,
T_ORDERNO,
T_TRADETIME ,
T_TRADEDATE,
T_PARENTTRADENO,
T_BUYSELL,
T_BROKERREF,
T_CPFIRMID,
T_SECCODE,
T_PRICE,
T_QUANTITY,
T_VALUE,
T_SETTLEDATE,
T_SETTLECODE, -- NEW
T_TRADETYPE,-- NEW
T_CLEARINGCENTERCOMM,-- NEW
T_EXCHANGECOMM,-- NEW
T_TRADINGSYSTEMCOMM,-- NEW
T_CLIENTCODE,
T_STATUS,
T_CURRENCYID,
T_SECBOARD
) 
VALUES (
:old.T_ID,
:old.T_IS_SNAPSHOT,
:old.T_TRADENO ,
:old.T_ORDERNO,
:old.T_TRADETIME ,
:old.T_TRADEDATE,
:old.T_PARENTTRADENO,
:old.T_BUYSELL,
:old.T_BROKERREF,
:old.T_CPFIRMID,
:old.T_SECCODE,
:old.T_PRICE,
:old.T_QUANTITY,
:old.T_VALUE,
:old.T_SETTLEDATE,
:old.T_SETTLECODE, -- NEW
:old.T_TRADETYPE,-- NEW
:old.T_CLEARINGCENTERCOMM,-- NEW
:old.T_EXCHANGECOMM,-- NEW
:old.T_TRADINGSYSTEMCOMM,-- NEW
:old.T_CLIENTCODE,
:old.T_STATUS,
:old.T_CURRENCYID,
:old.T_SECBOARD
);
END DASTSCURR_TRADES_DBT_HIST;
/