
BEGIN
  EXECUTE IMMEDIATE 'drop table DET_SECURITY_KIND';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table DET_SECURITY_KIND_ASS_KIND';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table DET_SECURITY';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table ASS_SECURITY_KIND';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DET_SECURITY_KIND 
   (  CODE VARCHAR2(100), 
  NAME VARCHAR2(250), 
  NAME_S VARCHAR2(250), 
  IS_EMISSIVE VARCHAR2(2), 
  IS_INDIVIDUAL VARCHAR2(2), 
  SECURITY_KIND_NUM VARCHAR2(16),  
  GENNEFIMODE VARCHAR2(16), 
  DT VARCHAR2(10), 
  REC_STATUS VARCHAR2(2), 
  SYSMOMENT VARCHAR2(20), 
  EXT_FILE VARCHAR2(300)
   )/
   COMMENT ON COLUMN DET_SECURITY_KIND.CODE IS 'Код вида ценной бумаги'/
   COMMENT ON COLUMN DET_SECURITY_KIND.NAME IS 'Название вида ценной бумаги'/
   COMMENT ON COLUMN DET_SECURITY_KIND.NAME_S IS 'Название вида ценной бумаги - краткое'/
   COMMENT ON COLUMN DET_SECURITY_KIND.IS_EMISSIVE IS 'Признак эмиссионности ценной бумаги'/
   COMMENT ON COLUMN DET_SECURITY_KIND.IS_INDIVIDUAL IS 'Признак индивидуальной ценной бумаги'/
   COMMENT ON COLUMN DET_SECURITY_KIND.SECURITY_KIND_NUM IS 'Порядковый номер вида ценной бумаги'/
   COMMENT ON COLUMN DET_SECURITY_KIND.GENNEFIMODE IS 'Режим генерации ФИ для НЭЦБ'/
   COMMENT ON COLUMN DET_SECURITY_KIND.DT IS 'Дата открытия записи'/
   COMMENT ON COLUMN DET_SECURITY_KIND.REC_STATUS IS 'Статус записи'/
   COMMENT ON COLUMN DET_SECURITY_KIND.SYSMOMENT IS 'Момент выгрузки'/
   COMMENT ON COLUMN DET_SECURITY_KIND.EXT_FILE IS 'Идентификатор порции данных'/
   COMMENT ON TABLE DET_SECURITY_KIND  IS 'Справочник видов ценных бумаг'/
  GRANT DELETE ON DET_SECURITY_KIND TO PUBLIC/
  GRANT INSERT ON DET_SECURITY_KIND TO PUBLIC/
  GRANT SELECT ON DET_SECURITY_KIND TO PUBLIC/
  GRANT UPDATE ON DET_SECURITY_KIND TO PUBLIC/
  
CREATE TABLE DET_SECURITY_KIND_ASS_KIND 
   (
   SECURITY_KIND_ASS_KIND_CODE VARCHAR2(100), 
   SECURITY_KIND_ASS_KIND_NAME VARCHAR2(250), 
   DT VARCHAR2(10), 
   REC_STATUS VARCHAR2(2), 
   SYSMOMENT VARCHAR2(20), 
   EXT_FILE VARCHAR2(300)
   ) /
   COMMENT ON COLUMN DET_SECURITY_KIND_ASS_KIND.SECURITY_KIND_ASS_KIND_CODE IS 'Код отношения между видами ценных бумаг'/
   COMMENT ON COLUMN DET_SECURITY_KIND_ASS_KIND.SECURITY_KIND_ASS_KIND_NAME IS 'Название отношения между видами ценных бумаг'/
   COMMENT ON COLUMN DET_SECURITY_KIND_ASS_KIND.DT IS 'Дата открытия записи'/
   COMMENT ON COLUMN DET_SECURITY_KIND_ASS_KIND.REC_STATUS IS 'Статус записи'/
   COMMENT ON COLUMN DET_SECURITY_KIND_ASS_KIND.SYSMOMENT IS 'Момент выгрузки'/
   COMMENT ON COLUMN DET_SECURITY_KIND_ASS_KIND.EXT_FILE IS 'Идентификатор порции данных'/
   COMMENT ON TABLE DET_SECURITY_KIND_ASS_KIND  IS 'Справочник видов отношения между видами ценных бумаг'/
  GRANT DELETE ON DET_SECURITY_KIND_ASS_KIND TO PUBLIC/
  GRANT INSERT ON DET_SECURITY_KIND_ASS_KIND TO PUBLIC/
  GRANT SELECT ON DET_SECURITY_KIND_ASS_KIND TO PUBLIC/
  GRANT UPDATE ON DET_SECURITY_KIND_ASS_KIND TO PUBLIC/
  

CREATE TABLE DET_SECURITY 
   (  TYPESECURITY VARCHAR2(1), 
  CODE VARCHAR2(100), 
  DATE_ISSUE VARCHAR2(10), 
  NOMINAL VARCHAR2(40), 
  REGNUM VARCHAR2(50), 
  FINSTRSECURITY_FINSTR_CODE VARCHAR2(30), 
  SECURITY_TYPE_711_CODE_TYPE VARCHAR2(10) DEFAULT '-1', 
  ISSUER_CODE VARCHAR2(250), 
  UNDERWRITER_CODE VARCHAR2(250), 
  FINSTRCURNOM_FINSTR_CODE VARCHAR2(30), 
  PROCBASE VARCHAR2(100), 
  DT VARCHAR2(10), 
    SECURITY_KIND_CODE VARCHAR2(100), 
  REC_STATUS VARCHAR2(2), 
  SYSMOMENT VARCHAR2(20), 
  EXT_FILE VARCHAR2(300)
   ) /
   COMMENT ON COLUMN DET_SECURITY.TYPESECURITY IS 'Тип ценной бумаги'/
   COMMENT ON COLUMN DET_SECURITY.CODE IS 'Код ценной бумаги в учетной системе'/
   COMMENT ON COLUMN DET_SECURITY.DATE_ISSUE IS 'Дата эмиссии'/
   COMMENT ON COLUMN DET_SECURITY.NOMINAL IS 'Номинал (для облигаций - минимальный номинал)'/
   COMMENT ON COLUMN DET_SECURITY.REGNUM IS 'Регистрационный номер'/
   COMMENT ON COLUMN DET_SECURITY.FINSTRSECURITY_FINSTR_CODE IS 'Код фин. инструмента ценной бумаги'/
   COMMENT ON COLUMN DET_SECURITY.SECURITY_TYPE_711_CODE_TYPE IS 'Код типа ЦБ для ф711'/
   COMMENT ON COLUMN DET_SECURITY.ISSUER_CODE IS 'Уникальный код эмитента (управляющей компании для ПИФов)'/
   COMMENT ON COLUMN DET_SECURITY.UNDERWRITER_CODE IS 'Уникальный код андеррайтера'/
   COMMENT ON COLUMN DET_SECURITY.FINSTRCURNOM_FINSTR_CODE IS 'Код фин. инструмента валюты номинала'/
   COMMENT ON COLUMN DET_SECURITY.PROCBASE IS 'Код базы расчета процентов'/
   COMMENT ON COLUMN DET_SECURITY.DT IS 'Дата операции в учетной системе'/
   COMMENT ON COLUMN DET_SECURITY.SECURITY_KIND_CODE IS 'Код вида ЦБ'/
   COMMENT ON COLUMN DET_SECURITY.REC_STATUS IS 'Статус записи'/
   COMMENT ON COLUMN DET_SECURITY.SYSMOMENT IS 'Момент выгрузки'/
   COMMENT ON COLUMN DET_SECURITY.EXT_FILE IS 'Идентификатор порции данных'/
   COMMENT ON TABLE DET_SECURITY  IS 'Справочник ценных бумаг'/
  GRANT DELETE ON DET_SECURITY TO PUBLIC/
  GRANT INSERT ON DET_SECURITY TO PUBLIC/
  GRANT SELECT ON DET_SECURITY TO PUBLIC/
  GRANT UPDATE ON DET_SECURITY TO PUBLIC/
  

CREATE TABLE ASS_SECURITY_KIND 
   (
	SECURITY_KIND_ASS_KIND_CODE VARCHAR2(100), 
	SECURITY_KIND_PAR_CODE VARCHAR2(100), 
	SECURITY_KIND_CHILD_CODE VARCHAR2(100), 
	DT VARCHAR2(10), 
	REC_STATUS VARCHAR2(2), 
	SYSMOMENT VARCHAR2(20), 
	EXT_FILE VARCHAR2(300)
   ) /
   COMMENT ON COLUMN ASS_SECURITY_KIND.SECURITY_KIND_ASS_KIND_CODE IS 'Код отношения между видами ценных бумаг'/
   COMMENT ON COLUMN ASS_SECURITY_KIND.SECURITY_KIND_PAR_CODE IS 'Код вида ценной бумаги - родителя'/
   COMMENT ON COLUMN ASS_SECURITY_KIND.SECURITY_KIND_CHILD_CODE IS 'Код вида ценной бумаги - потомка'/
   COMMENT ON COLUMN ASS_SECURITY_KIND.DT IS 'Дата открытия записи'/
   COMMENT ON COLUMN ASS_SECURITY_KIND.REC_STATUS IS 'Статус записи'/
   COMMENT ON COLUMN ASS_SECURITY_KIND.SYSMOMENT IS 'Момент выгрузки'/
   COMMENT ON COLUMN ASS_SECURITY_KIND.EXT_FILE IS 'Идентификатор порции данных'/
   COMMENT ON TABLE ASS_SECURITY_KIND  IS 'Справочник cвязtq между видами ценных бумаг'/
  GRANT DELETE ON ASS_SECURITY_KIND TO PUBLIC/
  GRANT INSERT ON ASS_SECURITY_KIND TO PUBLIC/
  GRANT SELECT ON ASS_SECURITY_KIND TO PUBLIC/
  GRANT UPDATE ON ASS_SECURITY_KIND TO PUBLIC/
  

