UPDATE  NFIELD SET ISGRID = 1 WHERE NAME = 'T_NEXTSTAMP' AND ID_NTABLE = (SELECT ID_NTABLE FROM NTABLE WHERE NAME  = 'DSSH_ACTION_DBT')
/

DELETE FROM NFIELD WHERE NAME = 'T_NEXTSTAMP' AND ID_NTABLE = (SELECT ID_NTABLE FROM NTABLE WHERE NAME  = 'DSS_SHEDULER_DBT')
/
