UPDATE  NFIELD SET ISGRID = 0 WHERE NAME = 'T_NEXTSTAMP' AND ID_NTABLE = (SELECT ID_NTABLE FROM NTABLE WHERE NAME  = 'DSSH_ACTION_DBT')
/

INSERT INTO NFIELD
   ( ID_NFORM, ID_NTABLE, ID_STYPEFIELD, LEN, NAME, REDEFINITION, ISSEND, ISSIGN, ISGRID, ISVISIBLE, TEXT, ISTEXTUP, ORDERFIELD, ISUPPER, ISEDIT, ISLKP, ISLKPONLY, ISCALC, ALIASFIELD, ISREQ, VERSIONREC)
 VALUES
   ( (SELECT ID_NFORM FROM NFORM WHERE TEXT = 'Активность плановой процедуры'), 
   (SELECT ID_NTABLE FROM NTABLE WHERE NAME  = 'DSS_SHEDULER_DBT'), 
   9, 0, 
    'T_NEXTSTAMP', 0, 0, 0, 
    1, 0, 'Время следующего запуска процедуры', 0, 12051, 
    0, 
    0, 0, 0, 1, 'T_NEXTSTAMP', 0, 0)
/