CREATE GLOBAL TEMPORARY TABLE DNPTXCTRLEXCEL_TMP
(
  T_CLIENTNAME    VARCHAR2(320),	
  T_CLIENTIDSOFR  VARCHAR2(35),	
  T_CLIENTIDCFT   VARCHAR2(35),	
  T_IIS           VARCHAR2(64),	
  T_DUETOTAL      NUMBER(32,12),	
  T_ISFORMED      CHAR(1),	
  T_ERROR         VARCHAR2(100),	
  T_CSVSTR        VARCHAR2(1000)	
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DNPTXCTRLEXCEL_TMP IS 'Загруж. данные EXCEL для справок НДФЛ'
/
COMMENT ON COLUMN DNPTXCTRLEXCEL_TMP.T_CLIENTNAME IS 'ФИО'
/
COMMENT ON COLUMN DNPTXCTRLEXCEL_TMP.T_CLIENTIDSOFR IS 'ID CОФР'
/
COMMENT ON COLUMN DNPTXCTRLEXCEL_TMP.T_CLIENTIDCFT IS 'ID ЦФТ'
/
COMMENT ON COLUMN DNPTXCTRLEXCEL_TMP.T_IIS IS 'Номер договора ИИС'
/
COMMENT ON COLUMN DNPTXCTRLEXCEL_TMP.T_DUETOTAL IS 'Сумма задолженности(+)/переплаты(-) по НДФЛ'
/
COMMENT ON COLUMN DNPTXCTRLEXCEL_TMP.T_ISFORMED IS 'Признак формирования Справки по НДФЛ'
/
COMMENT ON COLUMN DNPTXCTRLEXCEL_TMP.T_ERROR IS 'Возможные ошибки'
/
COMMENT ON COLUMN DNPTXCTRLEXCEL_TMP.T_CSVSTR IS 'Вся строка по клиенту из Отчета'
/