--Временная таблица
CREATE GLOBAL TEMPORARY TABLE DNPTXCTRLCLNT_TMP
(
  T_CLIENTID          NUMBER(10),
  T_CLIENTCODE        VARCHAR2(200),
  T_CLIENTNAME        VARCHAR2(400),
  T_DATAEXISTS        CHAR
)
ON COMMIT PRESERVE ROWS
/
