DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXLNK_DBT ADD T_BENEFITID NUMBER(10) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXLNK_DBT.T_BENEFITID IS ''‚¨¤ «μ£®βλ''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXLNK_DBT_IDX9';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXLNK_DBT_IDX9 ON DNPTXLNK_DBT (
   T_BENEFITID ASC
)
/
