CREATE GLOBAL TEMPORARY TABLE DNPTXBENEFITSCONDITIONS_TMP (
    T_ID NUMBER(10)
  , T_CONDID NUMBER(10)
  , T_BENEFITID NUMBER(10)
  , T_KINDDEALTYPE NUMBER(5)
  , T_DEALTYPE NUMBER(5)
  , T_DEALOBJECT NUMBER(5)
  , T_RESIDENTSTATUS NUMBER(5)
  , T_OWNERPERIODSIGN VARCHAR2(5)
  , T_OWNERPERIOD NUMBER(10)
  , T_ISEXCEPT CHAR(1)
  , T_ISSUERCOUNTRY VARCHAR2(3)
  , T_BENEFITSIGNONFI NUMBER(10)
  , T_CIRCULATE NUMBER(10)
  , T_BENEFITSIGNONISSUER NUMBER(10)
  , T_BENEFITSIGNONCLIENT NUMBER(10)
  , T_DEALDATESIGN VARCHAR2(5)
  , T_DEALDATE DATE
  , T_SPECIALCONDITION NUMBER(10)
  , T_VERSION NUMBER(5)
  , T_OPER NUMBER(5)
  , T_CHANGEDATE DATE
  , T_CHANGETIME DATE
  , T_ACTION NUMBER(5)
) ON COMMIT PRESERVE ROWS
/
COMMENT ON TABLE DNPTXBENEFITSCONDITIONS_TMP IS 'Условия для льгот (врем.)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_ID IS 'Уникальный идентификатор записи'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_CONDID IS 'Идентификатор условия в БД'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_BENEFITID IS 'Идентификатор вида льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_KINDDEALTYPE IS 'Вид типа сделки (по виду связи НУ, по виду сделок)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_DEALTYPE IS 'Тип сделки'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_DEALOBJECT IS 'Объект сделки (Идентификатор финансового инструмента)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_RESIDENTSTATUS IS 'Налоговый статус ФЛ'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_OWNERPERIODSIGN IS 'Знак для срока владения (>, >= и тд)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_OWNERPERIOD IS 'Срок владения'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_ISEXCEPT IS 'Доп. условие для выбора страны'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_ISSUERCOUNTRY IS 'Страна эмитента'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_BENEFITSIGNONFI IS 'Признак льготы на активе'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_CIRCULATE IS 'Обращаемость ФИ'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_BENEFITSIGNONISSUER IS 'Признак экономически значимой организации на эмитенте'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_BENEFITSIGNONCLIENT IS 'Признак льготы на клиенте'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_DEALDATESIGN IS 'Знак для даты заключения сделки (>, >= и тд)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_DEALDATE IS 'Дата приобретения актива'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_SPECIALCONDITION IS 'Специальное условие'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_VERSION IS 'Номер изменения записи'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_OPER IS 'Операционист, изменивший запись'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_CHANGEDATE IS 'Дата изменения'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_CHANGETIME IS 'Время изменения записи'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONS_TMP.T_ACTION IS 'Действие'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXBENEFITSCOND_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXBENEFITSCOND_TMP_IDX0 ON DNPTXBENEFITSCONDITIONS_TMP (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXBENEFITSCOND_TMP_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXBENEFITSCOND_TMP_IDX1 ON DNPTXBENEFITSCONDITIONS_TMP (
   T_BENEFITID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXBENEFITSCONDI_TMP_IDX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXBENEFITSCOND_TMP_IDX2 ON DNPTXBENEFITSCONDITIONS_TMP (
   T_CONDID ASC
)
/

CREATE SEQUENCE DNPTXBENEFITSCONDITIONS_TMP_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXBENEFITSCOND_TMP_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXBENEFITSCONDITIONS_TMP FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXBENEFITSCONDITIONS_TMP_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXBENEFITSCONDITIONS_TMP_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER DNPTXBENEFITSCOND_TMP_TBIU
  BEFORE INSERT OR UPDATE 
  ON DNPTXBENEFITSCONDITIONS_TMP
  FOR EACH ROW
DECLARE
BEGIN

  IF (INSERTING AND :NEW.T_CHANGEDATE = TO_DATE('01.01.0001','DD.MM.YYYY')) OR UPDATING THEN
    :NEW.T_CHANGEDATE := TRUNC(SYSDATE);
    :NEW.T_CHANGETIME := TO_DATE('01-01-0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD-MM-YYYY:HH24:MI:SS'); 
  END IF;

END;
/