-- Таблица "DNPTXBENEFITSCONDITIONSCH_DBT"

CREATE TABLE DNPTXBENEFITSCONDITIONSCH_DBT (
    T_ID NUMBER(10)
  , T_BENEFITID NUMBER(10)
  , T_CONDID NUMBER(10)
  , T_ACTION NUMBER(5)
  , T_KINDDEALTYPE_OLD NUMBER(5)
  , T_KINDDEALTYPE_NEW NUMBER(5)
  , T_DEALTYPE_OLD NUMBER(5)
  , T_DEALTYPE_NEW NUMBER(5)
  , T_DEALOBJECT_OLD NUMBER(5)
  , T_DEALOBJECT_NEW NUMBER(5)
  , T_RESIDENTSTATUS_OLD NUMBER(5)
  , T_RESIDENTSTATUS_NEW NUMBER(5)
  , T_OWNERPERIODSIGN_OLD VARCHAR2(5)
  , T_OWNERPERIODSIGN_NEW VARCHAR2(5)
  , T_OWNERPERIOD_OLD NUMBER(10)
  , T_OWNERPERIOD_NEW NUMBER(10)
  , T_ISEXCEPT_OLD CHAR(1)
  , T_ISEXCEPT_NEW CHAR(1)
  , T_ISSUERCOUNTRY_OLD VARCHAR2(3)
  , T_ISSUERCOUNTRY_NEW VARCHAR2(3)
  , T_BENEFITSIGNONFI_OLD NUMBER(10)
  , T_BENEFITSIGNONFI_NEW NUMBER(10)
  , T_CIRCULATE_OLD NUMBER(10)
  , T_CIRCULATE_NEW NUMBER(10)
  , T_BENEFITSIGNONISSUER_OLD NUMBER(10)
  , T_BENEFITSIGNONISSUER_NEW NUMBER(10)
  , T_BENEFITSIGNONCLIENT_OLD NUMBER(10)
  , T_BENEFITSIGNONCLIENT_NEW NUMBER(10)
  , T_DEALDATESIGN_OLD VARCHAR2(5)
  , T_DEALDATESIGN_NEW VARCHAR2(5)
  , T_DEALDATE_OLD DATE
  , T_DEALDATE_NEW DATE
  , T_SPECIALCONDITION_OLD NUMBER(10)
  , T_SPECIALCONDITION_NEW NUMBER(10)
  , T_OPER NUMBER(5)
  , T_CHANGEDATE DATE
  , T_CHANGETIME DATE
)
/
COMMENT ON TABLE DNPTXBENEFITSCONDITIONSCH_DBT IS 'История условий для льгот'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_ID IS 'Уникальный идентификатор записи'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_BENEFITID IS 'Идентификатор льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_CONDID IS 'Идентификатор условия льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_ACTION IS 'Действие'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_KINDDEALTYPE_OLD IS 'Прежний вид типа сделки (по виду связи НУ, по виду сделок)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_KINDDEALTYPE_NEW IS 'Новый вид типа сделки (по виду связи НУ, по виду сделок)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_DEALTYPE_OLD IS 'Прежний тип сделки'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_DEALTYPE_NEW IS 'Новый тип сделки'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_DEALOBJECT_OLD IS 'Прежний объект сделки (Идентификатор финансового инструмента)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_DEALOBJECT_NEW IS 'Новый объект сделки (Идентификатор финансового инструмента)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_RESIDENTSTATUS_OLD IS 'Прежний налоговый статус ФЛ'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_RESIDENTSTATUS_NEW IS 'Новый налоговый статус ФЛ'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_OWNERPERIODSIGN_OLD IS 'Прежний знак для срока владения (>, >= и тд)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_OWNERPERIODSIGN_NEW IS 'Новый знак для срока владения (>, >= и тд)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_OWNERPERIOD_OLD IS 'Прежний срок владения'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_OWNERPERIOD_NEW IS 'Новый срок владения'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_ISEXCEPT_OLD IS 'Прежнее доп. условие для выбора страны'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_ISEXCEPT_NEW IS 'Новое доп. условие для выбора страны'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_ISSUERCOUNTRY_OLD IS 'Прежняя страна эмитента'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_ISSUERCOUNTRY_NEW IS 'Новая страна эмитента'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_BENEFITSIGNONFI_OLD IS 'Прежний признак льготы на активе'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_BENEFITSIGNONFI_NEW IS 'Новый признак льготы на активе'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_CIRCULATE_OLD IS 'Прежняя обращаемость ФИ'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_CIRCULATE_NEW IS 'Новая обращаемость ФИ'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_BENEFITSIGNONISSUER_OLD IS 'Прежний признак экономически значимой организации на эмитенте'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_BENEFITSIGNONISSUER_NEW IS 'Новый признак экономически значимой организации на эмитенте'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_BENEFITSIGNONCLIENT_OLD IS 'Прежний признак льготы на клиенте'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_BENEFITSIGNONCLIENT_NEW IS 'Новый признак льготы на клиенте'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_DEALDATESIGN_OLD IS 'Прежний знак для даты заключения сделки (>, >= и тд)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_DEALDATESIGN_NEW IS 'Новый знак для даты заключения сделки (>, >= и тд)'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_DEALDATE_OLD IS 'Прежняя дата приобретения актива'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_DEALDATE_NEW IS 'Новая дата приобретения актива'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_SPECIALCONDITION_OLD IS 'Прежнее специальное условие'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_SPECIALCONDITION_NEW IS 'Новое специальное условие'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_OPER IS 'Операционист, изменивший запись'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_CHANGEDATE IS 'Дата изменения записи'
/
COMMENT ON COLUMN DNPTXBENEFITSCONDITIONSCH_DBT.T_CHANGETIME IS 'Время изменения записи'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXBENEFITSCONDCH_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXBENEFITSCONDCH_DBT_IDX0 ON DNPTXBENEFITSCONDITIONSCH_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXBENEFITSCONDCH_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXBENEFITSCONDSCH_DBT_IDX1 ON DNPTXBENEFITSCONDITIONSCH_DBT (
   T_CONDID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXBENEFITSCONDSCH_DBT_IDX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXBENEFITSCONDCH_DBT_IDX2 ON DNPTXBENEFITSCONDITIONSCH_DBT (
   T_BENEFITID ASC
)
/

CREATE SEQUENCE DNPTXBENEFITSCONDITIONSCH_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXBENEFITSCONDCH_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXBENEFITSCONDITIONSCH_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXBENEFITSCONDITIONSCH_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXBENEFITSCONDITIONSCH_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
