-- Таблица "DNPTXBENEFITSCH_DBT"

CREATE TABLE DNPTXBENEFITSCH_DBT (
    T_ID NUMBER(10)
  , T_BENEFITID NUMBER(10)
  , T_BENEFITTYPE_OLD VARCHAR2(20)
  , T_BENEFITTYPE_NEW VARCHAR2(20)
  , T_BEGDATEBENEFIT_OLD DATE
  , T_BEGDATEBENEFIT_NEW DATE
  , T_ENDDATEBENEFIT_OLD DATE
  , T_ENDDATEBENEFIT_NEW DATE
  , T_BENEFITPRIORITY_OLD NUMBER(10)
  , T_BENEFITPRIORITY_NEW NUMBER(10)
  , T_BENEFITGROUP_OLD NUMBER(10)
  , T_BENEFITGROUP_NEW NUMBER(10)
  , T_LAW_OLD VARCHAR2(2000)
  , T_LAW_NEW VARCHAR2(2000)
  , T_STATUS_OLD NUMBER(5)
  , T_STATUS_NEW NUMBER(5)
  , T_OPER NUMBER(5)
  , T_CHANGEDATE DATE
  , T_CHANGETIME DATE
)
/
COMMENT ON TABLE DNPTXBENEFITSCH_DBT IS 'История настроечн. таблицы налог. льгот'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_ID IS 'Идентификатор вида льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_BENEFITID IS 'Идентификатор записи о льготе'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_BENEFITTYPE_OLD IS 'Прежний вид льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_BENEFITTYPE_NEW IS 'Новый вид льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_BEGDATEBENEFIT_OLD IS 'Прежняя дата начала применения льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_BEGDATEBENEFIT_NEW IS 'Новая дата начала применения льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_ENDDATEBENEFIT_OLD IS 'Прежняя дата окончания применения льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_ENDDATEBENEFIT_NEW IS 'Новая дата окончания применения льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_BENEFITPRIORITY_OLD IS 'Прежний приоритет применения льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_BENEFITPRIORITY_NEW IS 'Новый приоритет применения льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_BENEFITGROUP_OLD IS 'Прежний идентификатор группы льготируемых доходов, к которой относится вид льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_BENEFITGROUP_NEW IS 'Новый идентификатор группы льготируемых доходов, к которой относится вид льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_LAW_OLD IS 'Прежние законы, регулирующие предоставление льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_LAW_NEW IS 'Новые законы, регулирующие предоставление льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_STATUS_OLD IS 'Прежний статус льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_STATUS_NEW IS 'Новый статус льготы'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_OPER IS 'Операционист, изменивший запись'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_CHANGEDATE IS 'Дата изменения'
/
COMMENT ON COLUMN DNPTXBENEFITSCH_DBT.T_CHANGETIME IS 'Время изменения'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXBENEFITSCH_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXBENEFITSCH_DBT_IDX0 ON DNPTXBENEFITSCH_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXBENEFITSCH_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXBENEFITSCH_DBT_IDX1 ON DNPTXBENEFITSCH_DBT (
   T_BENEFITID ASC
)
/

CREATE SEQUENCE DNPTXBENEFITSCH_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXBENEFITSCH_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXBENEFITSCH_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXBENEFITSCH_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXBENEFITSCH_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
