CREATE GLOBAL TEMPORARY TABLE DPROTOCOLVALIDATECFT_TMP (
  t_id       NUMBER GENERATED ALWAYS AS IDENTITY,
  t_message  VARCHAR2(4000),
  t_created  DATE DEFAULT SYSDATE,
  t_error_code NUMBER DEFAULT 0
)
ON COMMIT PRESERVE ROWS
NOCACHE
/