DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXLNKBC_DBT ADD T_BENEFITID NUMBER(10) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXLNKBC_DBT.T_BENEFITID IS ''‚¨¤ «μ£®βλ''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/
