/*‡ ¯®«­¥­¨¥ ­ áâà®¥ç­®© â ¡«¨æë*/
DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITS_DBT(T_BENEFITID,T_BENEFITTYPE,T_BEGDATEBENEFIT,T_ENDDATEBENEFIT,T_BENEFITPRIORITY,T_BENEFITGROUP,T_LAW,T_STATUS,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,'‹_1',TO_DATE('01.01.2025', 'DD.MM.YYYY'),TO_DATE('31.12.2027', 'DD.MM.YYYY'),1,2793,'¯.17.2-1. áâ. 217 Š ”',1,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'))
RETURNING T_BENEFITID INTO v_BenefitID;

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,1,'>',1,CHR(0),CHR(1),3,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,17,1,'>',1,CHR(0),'RUS',3,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,16,1,'>',1,CHR(0),CHR(1),3,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

END;
/

DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITS_DBT(T_BENEFITID,T_BENEFITTYPE,T_BEGDATEBENEFIT,T_ENDDATEBENEFIT,T_BENEFITPRIORITY,T_BENEFITGROUP,T_LAW,T_STATUS,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,'‹_11',TO_DATE('01.01.2023','DD.MM.YYYY'),TO_DATE('31.12.2024','DD.MM.YYYY'),2,2793,'¯.17.2-1. áâ. 217 Š ”',1,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'))
RETURNING T_BENEFITID INTO v_BenefitID;

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,0,'>',1,CHR(0),CHR(1),3,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,16,0,'>',1,CHR(0),CHR(1),3,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,17,0,'>',1,CHR(0),'RUS',3,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

END;
/

DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITS_DBT(T_BENEFITID,T_BENEFITTYPE,T_BEGDATEBENEFIT,T_ENDDATEBENEFIT,T_BENEFITPRIORITY,T_BENEFITGROUP,T_LAW,T_STATUS,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,'‹_2',TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),3,2792,'€¡§ æ 1, ¯.17.2. áâ. 217 Š ”'||CHR(10)||'€¡§ æ 1, ¯.2, áâ. 284.2 Š ”',1,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'))
RETURNING T_BENEFITID INTO v_BenefitID;

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,1,'>',5,CHR(0),CHR(1),2,0,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

END;
/

DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITS_DBT(T_BENEFITID,T_BENEFITTYPE,T_BEGDATEBENEFIT,T_ENDDATEBENEFIT,T_BENEFITPRIORITY,T_BENEFITGROUP,T_LAW,T_STATUS,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,'‹_7',TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),4,2792,'€¡§ æ 6, ¯.17.2. áâ. 217 Š ”',1,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'))
RETURNING T_BENEFITID INTO v_BenefitID;

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,0,'>',5,CHR(0),'RUS',0,0,1,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

END;
/

DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITS_DBT(T_BENEFITID,T_BENEFITTYPE,T_BEGDATEBENEFIT,T_ENDDATEBENEFIT,T_BENEFITPRIORITY,T_BENEFITGROUP,T_LAW,T_STATUS,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,'‹_5',TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),5,2792,'€¡§ æ 1, ¯.17.2. áâ. 217 Š ”'||CHR(10)||'€¡§ æ 3, ¯.2, áâ. 284.2 Š ”',1,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'))
RETURNING T_BENEFITID INTO v_BenefitID;

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,1,'>',5,CHR(0),CHR(1),0,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),1,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

END;
/

DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,1,'>',5,CHR(0),CHR(1),0,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),1,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,17,0,'>',1,CHR(0),'RUS',3,1,0,0,'>=',TO_DATE('01.01.2012','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,16,0,'>',1,CHR(0),CHR(1),3,1,0,0,'>=',TO_DATE('01.01.2013','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,0,'>',1,CHR(0),CHR(1),3,1,0,0,'>=',TO_DATE('01.01.2011','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));


END;
/

DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITS_DBT(T_BENEFITID,T_BENEFITTYPE,T_BEGDATEBENEFIT,T_ENDDATEBENEFIT,T_BENEFITPRIORITY,T_BENEFITGROUP,T_LAW,T_STATUS,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,'‹_9',TO_DATE('01.01.2016','DD.MM.YYYY'),TO_DATE('31.12.2024','DD.MM.YYYY'),7,2792,'€¡§ æ 1, ¯.17.2. áâ. 217 Š ”'||CHR(10)||'€¡§ æ 1, ¯.2, áâ. 284.2 Š ”',1,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'))
RETURNING T_BENEFITID INTO v_BenefitID;

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,0,'>',5,CHR(0),CHR(1),2,0,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

END;
/

DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITS_DBT(T_BENEFITID,T_BENEFITTYPE,T_BEGDATEBENEFIT,T_ENDDATEBENEFIT,T_BENEFITPRIORITY,T_BENEFITGROUP,T_LAW,T_STATUS,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,'‹_10',TO_DATE('04.09.2023','DD.MM.YYYY'),TO_DATE('31.12.2024','DD.MM.YYYY'),8,2792,'€¡§ æ 6, ¯.17.2. áâ. 217 Š ”',1,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'))
RETURNING T_BENEFITID INTO v_BenefitID;

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,0,'>',5,CHR(0),'RUS',0,0,1,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

END;
/

DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITS_DBT(T_BENEFITID,T_BENEFITTYPE,T_BEGDATEBENEFIT,T_ENDDATEBENEFIT,T_BENEFITPRIORITY,T_BENEFITGROUP,T_LAW,T_STATUS,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,'‹_12',TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),9,2792,'€¡§ æ 1, ¯.17.2. áâ. 217 Š ”'||CHR(10)||'€¡§ æ 3, ¯.2, áâ. 284.2 Š ”',1,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'))
RETURNING T_BENEFITID INTO v_BenefitID;

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,0,'>',5,CHR(0),CHR(1),0,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),1,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

END;
/

DECLARE
  v_BenefitID NUMBER := 0;
BEGIN

INSERT INTO DNPTXBENEFITS_DBT(T_BENEFITID,T_BENEFITTYPE,T_BEGDATEBENEFIT,T_ENDDATEBENEFIT,T_BENEFITPRIORITY,T_BENEFITGROUP,T_LAW,T_STATUS,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,'‹_8',TO_DATE('01.01.2028','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),10,2792,'€¡§ æ 1, ¯.17.2. áâ. 217 Š ”'||CHR(10)||'€¡§ æ 2, ¯.2, áâ. 284.2 Š ”',1,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'))
RETURNING T_BENEFITID INTO v_BenefitID;

INSERT INTO DNPTXBENEFITSCONDITIONS_DBT
(T_ID,T_BENEFITID,T_KINDDEALTYPE,T_DEALTYPE,T_DEALOBJECT,T_RESIDENTSTATUS,T_OWNERPERIODSIGN,T_OWNERPERIOD,T_ISEXCEPT,T_ISSUERCOUNTRY,T_BENEFITSIGNONFI,T_CIRCULATE,T_BENEFITSIGNONISSUER,T_BENEFITSIGNONCLIENT,
 T_DEALDATESIGN,T_DEALDATE,T_SPECIALCONDITION,T_VERSION,T_OPER,T_CHANGEDATE,T_CHANGETIME)
VALUES(0,v_BenefitID,1,1,20,1,'>',5,CHR(0),'RUS',3,1,0,0,CHR(1),TO_DATE('01.01.0001','DD.MM.YYYY'),0,0,1,TRUNC(SYSDATE),TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'));

END;
/
