/*
$Name:             mtcng_service.mac
$Module:           RS-Retail
$Description:      Сервисные функции для взаимодействия с ContactNG
*/

import RsbFormsInter, mtcntng_webserv;

var idSelectPayment = 0;

record inputNumPay ( "MTINCOME", "rtusrmac" ) dialog;
record inputOutgoing ( "MTOUTGON", "rtusrmac" ) dialog;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class ( XmlRSLStruct ) TCNGTransfer

  var trnDate = date( 0, 0, 0 );        // Дата перевода
  var trnReference : string;            // Номер перевода
  var trnCurrency : string;             // Валюта
  var trnAmount : money;                // Сумма
  var trnFeesClient : money;            // Комиссия
  var trnFeesClientCurr : string;       // Валюта комиссии
  var trnFeesClientLocal : money;       // Комиссия в национальной валюте
  var trnFeesPart : money;              // Часть комиссии участника системы, взятая с клиента отправителя
  var trnSendPoint : string;            // Филиал отправителя
  var trnPickupPoint : string;          // Филиал получателя
  var trnService : integer;             // Код услуги
  var trnTerminalNumber : string;       // Номер терминала
  var trnRate : double;                 // Курс валюты
  var tAccountNumber : string;          // Номер счета услуги
  var tDogNumber;                       // Номер договора на услугу
  var tOrderNumber;                     // Номер заказа
  var tOrderDate = date( 0, 0, 0 );     // Дата заказа
  var tLogin : string;                  // Логин пользователя услуги
  var tFIOUser : string;                // ФИО пользователя услуги
  var trnPassword : string;             // Пароль
  var trnAdditionalInfo : string;       // Дополнительная информация
  var tUsageExpiried = date( 0, 0, 0 ); // Дата окончания услуги
  var tCurrencyCource : double;         // Курс валюты
  var tCardNumber : string;             // Номер карты
  var tBIC : string;                    // БИК банка
  var tAttr1 : string;                  // Атрибут 1
  var tAttr2 : string;                  // Атрибут 2
  var tAttr3 : string;                  // Атрибут 3
  var tAttr4 : string;                  // Атрибут 4
  var tAttr5 : string;                  // Атрибут 5
  var tAttr6 : string;                  // Атрибут 6
  var tAttr7 : string;                  // Атрибут 7
  var tAttr8 : string;                  // Атрибут 8
  var tAttr9 : string;                  // Атрибут 9
  var tAttr10 : string;                 // Атрибут 10
  var sName : string;                   // Фамилия отправителя
  var sLastName : string;               // Имя отправителя
  var sSurName : string;                // Отчество отправителя
  var sBirthday = date( 0, 0, 0 );      // Дата рождения отправителя
  var sBirthPlace : string;             // Место рождения отправителя
  var sCountryC : string;               // Гражданство отправителя
  var sCountry : string;                // Страна отправителя
  var sZipCode : string;                // Почтовый индекс отправителя
  var sRegion : string;                 // Регион (штат) отправителя
  var sCity : string;                   // Город отправителя
  var sAddress : string;                // Адрес отправителя (улица, дом, квартира)
  var sPhone : string;                  // Телефон отправителя
  var sIDTypeCode : integer;            // Код типа документа отправителя
  var sIDtype : string;                 // Тип документа отправителя
  var sIDnumber : string;               // Серия и номер документа отправителя
  var sIDdate = date( 0, 0, 0 );        // Дата выдачи документа отправителя
  var sIDwhom : string;                 // Кем выдан документ отправителя
  var sIDwhomCode : string;             // Код подразделения, которым выдан документ отправителя
  var sIDexpireDate = date( 0, 0, 0 );  // Дата истечения срока действия документа отправителя
  var sResident : integer;              // Резидент
  var sResidentC : string;              // Страна резидентности
  var sCountryStay : string;            // Страна проживания отправителя
  var sCountryOfBirth : string;         // Страна места рождения отправителя
  var sCityOfBirth : string;            // Город места рождения отправителя
  var sCardNumber : string;             // Номер карты отправителя
  var sAuthorizationCode : string;      // Код авторизации отправителя
  var bName : string;                   // Фамилия получателя
  var bLastName : string;               // Имя получателя
  var bSurName : string;                // Отчество получателя
  var bBirthday = date( 0, 0, 0 );      // Дата рождения получателя
  var bBirthPlace : string;             // Место рождения получателя
  var bCountryC : string;               // Гражданство получателя
  var bCountry : string;                // Страна получателя
  var bZipCode : string;                // Почтовый индекс получателя
  var bRegion : string;                 // Регион (штат) получателя
  var bCity : string;                   // Город получателя
  var bAddress : string;                // Адрес получателя (улица, дом, квартира)
  var bPhone : string;                  // Телефон получателя
  var bIDTypeCode : integer;            // Код типа документа получателя
  var bIDtype : string;                 // Тип документа получателя
  var bIDnumber : string;               // Серия и номер документа получателя
  var bIDdate = date( 0, 0, 0 );        // Дата выдачи документа получателя
  var bIDwhom : string;                 // Кем выдан документ получателя
  var bIDwhomCode : string;             // Код подразделения, которым выдан документ получателя
  var bIDexpireDate = date( 0, 0, 0 );  // Дата истечения срока действия документа получателя
  var bResident : integer;              // Резидент
  var bResidentC : string;              // Страна резидентности
  var bShowedIDtype : string;           // Тип предъявленного документа получателя
  var bShowedIDnumber : string;         // Серия и номер предъявленного документа получателя
  var bAccount : string;                // Счет получателя
  var bAccountType : string;            // Тип счета получателя
  var bBank : string;                   // Банк для зачисления на счет
  var bBranch : string;                 // Филиал банка для зачисления на счет
  var bBankAddress : string;            // Адрес банка для зачисления на счет
  var bEMAIL : string;                  // EMail получателя
  var trnReturnFees : integer;          // Признак возврата комиссии в случае аннулировании перевода
  var trnReturnFeesClient : money;      // Сумма комиссии в валюте перевода к возврату клиенту-отправителю
  var trnReturnFeesClientLocal : money; // Сумма комиссии в валюте внесения (локальной валюте) к возврату клиенту-отправителю
  var trnReturnRsbFees : money;         // Сумма комиссии в валюте перевода к возврату из ОЦ
  var trnRecipientAmount : money;       // Сумма в валюте перевода/платежа получателя
  var trnRecipientCurrency : string;    // Валюта перевода/платежа получателя
  var trnRecipientRate : double;        // Курс конверсии валюты перевода в валюту перевода получателя

  InitXmlRSLStruct;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TReqReadyToPaySub

  class A
    var trnReference : string;
  end;

  var attr = A;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TReqReadyToPay

  class ( TRequestAttributesBase ) A
    var USER_ID : integer;
    var LANG : string = "RU";

    InitTRequestAttributesBase( "TMoneyOrderObject", "IncomingReadyToPay" ); 
  end;

  var attr = A;
  var PARAMS = TReqReadyToPaySub;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TRespReadyToPayFields

  class A
    var ID : integer;
    var TRN : string;
    var CODE : string;
    var AMOUNT : money;
    var SENDER_NAME : string;
    var REC_NAME : string;
    var PP_CODE : string;
    var BANK_NAME : string;
    var CITY : string;
    var COUNTRY : string;
    var ADDITIONALINFO : string;
    var DT_FILE_STR = date;
    var STATE : integer;
    var STATE_STR : string;
  end;

  var attr = A;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TRespReadyToPay

  class ( TResponseAttributesBase ) A
    ;
  end;

  class TRowData
    var ROWDATA = TArray; 
  end;

  var attr = A;
  var DATA : string;

  // =====================================================================
  macro GetDataPacket ( rows )

    var packet = TRowData;
    var err;

    packet.ROWDATA[0] = TRespReadyToPayFields;
                  
    err = RtXml2Rsl( DATA, packet );
    rows = packet.ROWDATA;

    SetParm( 1, rows );

    return err;
  end;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TReqGet

  class ( TRequestAttributesBase ) A
    var DOC_ID : integer;
    var USER_ID : integer;
    var INOUT : string = "I";
    var LANG : string = "RU";

    InitTRequestAttributesBase( "TMoneyOrderObject", "Get" ); 
  end;

  var attr = A;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class ( TCNGTransfer ) TRespGet

  class ( TResponseAttributesBase ) A
    var STATE : integer;
  end;

  InitTCNGTransfer;

  var attr = A;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TReqGetState

  class ( TRequestAttributesBase ) A
    var DOC_ID : integer;
    var USER_ID : integer;
    var LANG : string = "RU";

    InitTRequestAttributesBase( "TMoneyOrderObject", "GetState" ); 
  end;

  var attr = A;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TRespGetState

  class ( TResponseAttributesBase ) A
    var STATE : integer;
  end;

  var attr = A;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class ( TCNGTransfer ) TReqNewOutgoing

  class ( TRequestAttributesBase ) A
    var USER_ID : integer;

    //InitTRequestAttributesBase( "TMoneyOrderObject", "NewOutgoing" );
    InitTRequestAttributesBase( "TMoneyOrderObject", "NewAndSendOutgoing" );
  end;

  InitTCNGTransfer;

  var attr = A;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TRespNewOutgoing

  class ( TResponseAttributesBase ) A

    var ID : integer;    
  end;

  var attr = A;
  var FieldsToPrint = TArray;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TReqPing

  class ( TRequestAttributesBase ) A
    var USER_ID : integer = 1;

    InitTRequestAttributesBase( "TAbonentObject", "Ping" ); 
  end;

  var attr = A;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
class TRespPing

  class ( TResponseAttributesBase ) A
    var SCHEME : string = "";
  end;

  var attr = A;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro checkPing ( silence )

  var req = TReqPing;
  var resp = TRespPing;
  var retCode = 0;
  var counter = 0;

  if ( ValType( silence ) == V_UNDEF )
    silence = false;
  end;

  while ( true )

    counter = counter + 1;

    retCode = CNG_Request( req, resp, true );

    if ( retCode != 0 )
      if ( counter >= 3 )
        break;
      end;
    else
      break;
    end;
  end;

  if ( ( retCode == 100 ) or ( retCode == 105 ) )
    if ( silence )
      PushErrorMessage( "Не удалось получить информацию из КЦ при запросе о наличии связи" );
    else
      MsgBox( "Не удалось получить информацию из КЦ при запросе о наличии связи" );
    end;
  elif ( retCode != 0 )
    if ( ( ValType( resp.attr.ERR_TEXT ) == V_STRING ) and ( resp.attr.ERR_TEXT != "" ) )
      if ( silence )
        PushErrorMessage( "Ошибка " + retCode + " при запросе в КЦ о наличии связи|" + resp.attr.ERR_TEXT );
      else
        MsgBox( "Ошибка " + retCode + " при запросе в КЦ о наличии связи|" + resp.attr.ERR_TEXT );
      end;
    else
      if ( silence )
        PushErrorMessage( "Ошибка " + retCode + " при запросе в КЦ о наличии связи" );
      else
        MsgBox( "Ошибка " + retCode + " при запросе в КЦ о наличии связи" );
      end;
    end;
  end;

  return retCode;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro defNamesStateMonTransFromPC( numState )

  var nameState = "";

  if ( ValType( numState ) != V_INTEGER )
    return nameState;
  end;

  if ( numState == -1 )
    nameState = "Удален";
  elif ( numState == 0 )
    nameState = "Оплачен";
  elif ( numState == 1 )
    nameState = "В обработке";
  elif ( numState == 2 )
    nameState = "Приостановлен";
  elif ( numState == 3 )
    nameState = "Отправлен в банк получателя";
  elif ( numState == 4 )
    nameState = "Готов к выплате";
  elif ( numState == 5 )
    nameState = "Ожидает выплаты";
  elif ( numState == 6 )
    nameState = "Выплачен получателю";
  elif ( numState == 7 )
    nameState = "Запрошен на возврат";
  elif ( numState == 8 )
    nameState = "Готов к возврату";
  elif ( numState == 9 )
    nameState = "К возврату, ожидает выплаты";
  elif ( numState == 10 )
    nameState = "Возвращен";
  elif ( numState == 100 )
    nameState = "Новый перевод";
  elif ( numState == 101 )
    nameState = "Ожидает оплаты";
  end;

  return nameState;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
private macro convertCurrFromCNGString( c : string ) : integer

  if ( ( StrUpr( c ) == "RUR" ) or ( StrUpr( c ) == "RUB" ) )
    return 0;
  elif ( StrUpr( c ) == "USD" )
    return 1;
  elif ( StrUpr( c ) == "EUR")
    return 5;
  else
    return -1;
  end;     
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro ParseFIOFromCNGString( fio, name1, name2, name3 )

  var i;
  var s = Trim( fio );
  var n = 0;

  name1 = name2 = name3 = "";

  n = Index( s, " " );

  if ( n > 0 )
    name1 = Trim( SubStr( s, 1, n ) );
    s = Trim( SubStr( s, n ) );
  else
    name1 = s;
  end;

  n = Index( s, " " );

  if ( n > 0 )
    name2 = Trim( SubStr( s, 1, n ) );
    name3 = Trim( SubStr( s, n ) );
  else
    name2 = s;
  end;
  
  SetParm( 1, name1 );
  SetParm( 2, name2 );
  SetParm( 3, name3 );
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro getPaperKindFromCNGTypeCode( paperKind2, pointCode )

  var id = -1;
  var cmd;
  var rs;

  if ( paperKind2 >= 0 )
    cmd = RsdCommand( "select t_type_bnk as typeBnk "
                      "from dtypedul_cng_bnk_dbt "
                      "where t_type_cng = :typeCng" );

    cmd.addParam( "typeCng", RSDBP_IN, paperKind2 );

    rs = RsdRecordSet( cmd );

    cmd.execute( );
  
    if ( rs.moveNext( ) )
      id = rs.value( "typeBnk" );
    end;
  end;

  return id;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro getPaperIdFromCNGString( name : string )

  var id = -1;

  if ( name == "" )
    return id;
  end;

  if ( ( Index( StrLwr( name ), "офицер" ) ) and ( Index( StrLwr( name ), "удостоверение" ) ) )
    id = 1;
  elif ( ( Index( StrLwr( name ), "военный" ) ) and ( Index( StrLwr( name ), "солдат" ) ) )
    id = 2;
  elif ( ( Index( StrLwr( name ), "минморфлот" ) ) )
    id = 3;
  elif ( ( Index( StrLwr( name ), "свидетельство" ) ) and ( Index( StrLwr( name ), "рожден" ) and ( Index( StrLwr( name ), "иностран" ) ) ) )
    id = 17;
  elif ( ( Index( StrLwr( name ), "жительство" ) ) )
    id = 5;
  elif ( ( Index( StrLwr( name ), "паспорт" ) ) and ( Index( StrLwr( name ), "загран" ) ) )
    id = 6;
  elif ( ( Index( StrLwr( name ), "освобожден" ) ) )
    id = 9;
  elif ( ( Index( StrLwr( name ), "паспорт" ) ) and ( Index( StrLwr( name ), "дипломат" ) ) )
    id = 10;
  elif ( ( Index( StrLwr( name ), "паспорт" ) ) and ( Index( StrLwr( name ), "иностранный" ) ) )
    id = 11;
  elif ( ( Index( StrLwr( name ), "удостоверение" ) ) and ( Index( StrLwr( name ), "бежен" ) ) )
    id = 13;
  elif ( ( Index( StrLwr( name ), "удостоверение" ) ) )
    id = 14;
  elif ( ( Index( StrLwr( name ), "паспорт" ) ) and ( Index( StrLwr( name ), "моряк" ) ) )
    id = 15;
  elif ( ( Index( StrLwr( name ), "офицер" ) ) and ( Index( StrLwr( name ), "запас" ) ) )
    id = 16;
  elif ( ( Index( StrLwr( name ), "рожден" ) ) )
    id = 4;
  elif ( Index( StrLwr( name ), "свидетельство" ) )
    if ( ( Index( StrLwr( name ), "иммигрант" ) ) or ( Index( StrLwr( name ), "бежен" ) ) )
      id = 12;
    end;
  elif ( ( Index( StrLwr( name ), "иные" ) ) )
    id = 18;
  elif ( ( Index( StrLwr( name ), "иностранн" ) ) and ( Index( StrLwr( name ), "государство" ) ) )
    id = 101;
  elif ( ( Index( StrLwr( name ), "разрешение" ) ) and ( Index( StrLwr( name ), "проживание" ) ) )
    id = 102;
  elif ( Index( StrLwr( name ), "паспорт" ) )
    if ( ( Index( name, "РФ" ) ) or ( Index( StrLwr( name ), "росси" ) ) )
      id = 0;
    end;
  end;

  return id;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro ParsePaperFromCNGString( inputStr, sr, num )

  var blancPos = 0;
  var lastBlancPos = 0;
  var tmpStr = Trim( inputStr );

  sr = "";
  num = "";

  while ( true )
    blancPos = Index( tmpStr, " ", lastBlancPos + 1 );

    if ( blancPos > 0 )
      lastBlancPos = blancPos;
    else
      break;
    end;
  end;

  if ( lastBlancPos != 0 )
    sr = Trim( SubStr( inputStr, 1, lastBlancPos ) );
    num = Trim( SubStr( inputStr, lastBlancPos + 1 ) );
  else
    sr = "";
    num = Trim( inputStr );
  end;

  SetParm( 1, sr );
  SetParm( 2, num );
end;


// =====================================================================
private macro getCodeLat3( inCode )

  var cmd;
  var rs;
  var outCode = inCode;

  if ( StrLen( inCode ) == 2 )
    cmd = RsdCommand( "select t_codelat3 as codeLat3 "
                      "from dcountry_dbt "
                      "where t_codelat2 = :codeLat2" );

    cmd.addParam( "codeLat2", RSDBP_IN, inCode );

    rs = RsdRecordSet( cmd );

    cmd.execute( );
  
    if ( rs.moveNext( ) )
      outCode = rs.value( "codeLat3" );
    end;
  end;

  return outCode;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro GetTemplates( client_ID, serv_ID, persistClient )

  var rmto_trans_tmp = TBFile( "rmto_trans.tmp", "W" );
  var clientList = TClientList;
  var cmd;
  var rs;
  var cycle = true;
  var i = 0;
  var dataPacket;
  var retCode;
  var codeKind = 50;
  var codeClientCNT = 0;
  var addMsg;
  var branch = NumFNCash( );
  var psId = 3;
  var servId = String( serv_ID );
  var cmdString = "";
  var stat = true;

  cmd = RsdCommand( "truncate table drmto_trans_tmp" );
  cmd.execute( );

  cmd = RsdCommand( "truncate table drmto_aux_attr_tmp" );
  cmd.execute( );

  if ( client_ID > 0 )
    if ( clientList.GetRecord( client_ID ) )
      ;
    else
      MsgBox( "Не найден клиент с кодом " + String( client_ID ) );
      stat = false;
    end;
  end;

  if ( stat )
    cmdString = "select rmto_trans.* from drmto_trans_dbt rmto_trans " + 
                "where rmto_trans.t_ourFlag != 0 and " +
                      "rmto_trans.t_psId = :psId and " +
                      "rmto_trans.t_psTransID != 0 and " +
                      "rmto_trans.t_action != 2";

    if ( client_ID > 0 )
      cmdString = cmdString + " and rmto_trans.t_senderPartyID = :senderPartyID";
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.Name1 != "" ) )
      cmdString = cmdString + " and Upper( rmto_trans.t_senderName1 ) = Upper( :name1 )";
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.Name2 != "" ) )
      cmdString = cmdString + " and Upper( rmto_trans.t_senderName2 ) = Upper( :name2 )";
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.Name3 != "" ) )
      cmdString = cmdString + " and Upper( rmto_trans.t_senderName3 ) = Upper( :name3 )";
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.Born != Date( 0, 0, 0 ) ) )
      cmdString = cmdString + " and rmto_trans.t_senderBorn = :born";
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.PaperKind >= 0 ) )
      cmdString = cmdString + " and rmto_trans.t_senderPaperKind = :paperKind";
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.PaperSeries != "" ) )
      cmdString = cmdString + " and rmto_trans.t_senderPaperSeries = :paperSeries";
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.PaperNumber != "" ) )
      cmdString = cmdString + " and rmto_trans.t_senderPaperNumber = :paperNumber";
    end;

    if ( serv_ID > 0 )
      cmdString = cmdString + " and exists ( select 1 " +
                                            "from drmto_aux_attr_dbt rmto_aux_attr " +
                                            "where rmto_aux_attr.t_branch = rmto_trans.t_branch and " +
                                                  "rmto_aux_attr.t_mto_id = rmto_trans.t_transid and " +
                                                  "rmto_aux_attr.t_typeinfo = 0 and " +
                                                  "Upper( rmto_aux_attr.t_field_ps ) = 'TRNSERVICE' and " +
                                                  "rmto_aux_attr.t_val_string = :servId )";
    end;

    cmdString = cmdString + " order by t_ourFlag, t_senderName1, t_senderName2, t_senderName3, t_transCode desc";

    cmd = RsdCommand( cmdString );

    cmd.addParam( "psId", RSDBP_IN, psId );

    if ( client_ID > 0 )
      cmd.addParam( "senderPartyID", RSDBP_IN, client_ID );
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.Name1 != "" ) )
      cmd.addParam( "name1", RSDBP_IN, persistClient.rec.Name1 );
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.Name2 != "" ) )
      cmd.addParam( "name2", RSDBP_IN, persistClient.rec.Name2 );
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.Name3 != "" ) )
      cmd.addParam( "name3", RSDBP_IN, persistClient.rec.Name3 );
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.Born != Date( 0, 0, 0 ) ) )
      cmd.addParam( "born", RSDBP_IN, persistClient.rec.Born );
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.PaperKind >= 0 ) )
      cmd.addParam( "paperKind", RSDBP_IN, persistClient.rec.PaperKind );
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.PaperSeries != "" ) )
      cmd.addParam( "paperSeries", RSDBP_IN, persistClient.rec.PaperSeries );
    end;

    if ( ( client_ID == 0 ) and ( persistClient.rec.PaperNumber != "" ) )
      cmd.addParam( "paperNumber", RSDBP_IN, persistClient.rec.PaperNumber );
    end;

    if ( serv_ID > 0 )
      cmd.addParam( "servId", RSDBP_IN, String( servId ) );
    end;

    rs = RsdRecordSet( cmd );

    cmd.execute( );

    while ( rs.moveNext( ) )

      i = i + 1;

      rmto_trans_tmp.Clear( );
      rmto_trans_tmp.rec.branch = NumFNCash( );
      rmto_trans_tmp.rec.transId = i;
      rmto_trans_tmp.rec.psId = rs.value( "t_psId" );
      rmto_trans_tmp.rec.transCode = rs.value( "t_transCode" );
      rmto_trans_tmp.rec.ourFlag = 1;
      rmto_trans_tmp.rec.sendDate = rs.value( "t_sendDate" );
      rmto_trans_tmp.rec.receivePointCode = rs.value( "t_receivePointCode" );
      rmto_trans_tmp.rec.recBankName = rs.value( "t_recBankName" );
      rmto_trans_tmp.rec.recAddInfo = rs.value( "t_recAddInfo" );
      rmto_trans_tmp.rec.curCode = rs.value( "t_curCode" );

      if ( rs.value( "t_senderPartyID" ) > 0 )
        if ( clientList.GetRecord( rs.value( "t_senderPartyID" ) ) )
          if ( ( rs.value( "t_senderName1" ) == clientList.CurRec.Rec.Name1 ) and
               ( rs.value( "t_senderName2" ) == clientList.CurRec.Rec.Name2 ) and
               ( rs.value( "t_senderName3" ) == clientList.CurRec.Rec.Name3 )    )
            rmto_trans_tmp.rec.senderPartyID = rs.value( "t_senderPartyID" );
          end;
        end;
      end;

      rmto_trans_tmp.rec.senderName1 = rs.value( "t_senderName1" );
      rmto_trans_tmp.rec.senderName2 = rs.value( "t_senderName2" );
      rmto_trans_tmp.rec.senderName3 = rs.value( "t_senderName3" );
      rmto_trans_tmp.rec.senderBorn = rs.value( "t_senderBorn" );
      rmto_trans_tmp.rec.senderBornPlace = rs.value( "t_senderBornPlace" );
      rmto_trans_tmp.rec.senderCitizenship = rs.value( "t_senderCitizenship" );
      rmto_trans_tmp.rec.senderNotResident = rs.value( "t_senderNotResident" );
      rmto_trans_tmp.rec.senderResidentship = rs.value( "t_senderResidentship" );
      rmto_trans_tmp.rec.senderPaperKind = rs.value( "t_senderPaperKind" );
      rmto_trans_tmp.rec.senderPaperSeries = rs.value( "t_senderPaperSeries" );
      rmto_trans_tmp.rec.senderPaperNumber = rs.value( "t_senderPaperNumber" );
      rmto_trans_tmp.rec.senderPaperIssuedDate = rs.value( "t_senderPaperIssuedDate" );
      rmto_trans_tmp.rec.senderPaperIssuer = rs.value( "t_senderPaperIssuer" );
      rmto_trans_tmp.rec.senderPaperIssuerCode = rs.value( "t_senderPaperIssuerCode" );
      rmto_trans_tmp.rec.senderCountry = rs.value( "t_senderCountry" );
      rmto_trans_tmp.rec.senderPostIndex = rs.value( "t_senderPostIndex" );
      rmto_trans_tmp.rec.senderRegion = rs.value( "t_senderRegion" );
      rmto_trans_tmp.rec.senderPlace = rs.value( "t_senderPlace" );
      rmto_trans_tmp.rec.senderAdress = rs.value( "t_senderAdress" );
      rmto_trans_tmp.rec.senderPhoneNumber = rs.value( "t_senderPhoneNumber" );
      rmto_trans_tmp.rec.senderEMail = rs.value( "t_senderEMail" ); 
      
      rmto_trans_tmp.rec.recName1 = rs.value( "t_recName1" );
      rmto_trans_tmp.rec.recName2 = rs.value( "t_recName2" );
      rmto_trans_tmp.rec.recName3 = rs.value( "t_recName3" );
      rmto_trans_tmp.rec.recBorn = rs.value( "t_recBorn" );
      rmto_trans_tmp.rec.recBornPlace = rs.value( "t_recBornPlace" );
      rmto_trans_tmp.rec.recCitizenship = rs.value( "t_recCitizenship" );
      rmto_trans_tmp.rec.recNotResident = rs.value( "t_recNotResident" );
      rmto_trans_tmp.rec.recResidentship = rs.value( "t_recResidentship" );
      rmto_trans_tmp.rec.recPaperKind = rs.value( "t_recPaperKind" );
      rmto_trans_tmp.rec.recPaperSeries = rs.value( "t_recPaperSeries" );
      rmto_trans_tmp.rec.recPaperNumber = rs.value( "t_recPaperNumber" );
      rmto_trans_tmp.rec.recPaperIssuedDate = rs.value( "t_recPaperIssuedDate" );
      rmto_trans_tmp.rec.recPaperIssuer = rs.value( "t_recPaperIssuer" );
      rmto_trans_tmp.rec.recPaperIssuerCode = rs.value( "t_recPaperIssuerCode" );
      rmto_trans_tmp.rec.recPaperExpiratDate = rs.value( "t_recPaperExpiratDate" );
      rmto_trans_tmp.rec.recCountry = rs.value( "t_recCountry" );
      rmto_trans_tmp.rec.recPostIndex = rs.value( "t_recPostIndex" );
      rmto_trans_tmp.rec.recRegion = rs.value( "t_recRegion" );
      rmto_trans_tmp.rec.recPlace = rs.value( "t_recPlace" );
      rmto_trans_tmp.rec.recAdress = rs.value( "t_recAdress" );
      rmto_trans_tmp.rec.recPhoneNumber = rs.value( "t_recPhoneNumber" );
      rmto_trans_tmp.rec.recCountryCode = rs.value( "t_recCountryCode" );
      rmto_trans_tmp.rec.recPlaceName = rs.value( "t_recPlaceName" );

      rmto_trans_tmp.rec.psTransID = rs.value( "t_psTransID" );

      stat = rmto_trans_tmp.Insert( );
      if ( not stat )
        MsgBox( "Ошибка при формировании временных таблиц" );
        break;
      end;
    end;
  end;

  return stat;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro GetPaymentData( trn_id : integer, trans, inOrOut, silence, state, forReturn )

  var req = TReqGet;
  var resp = TRespGet;
  var retCode;
  var i = 0;
  var cycle = true;
  var stat = true;

  req.attr.USER_ID = 0;
  req.attr.DOC_ID = trn_id;

  if ( ValType( inOrOut ) == V_STRING )
    if ( ( inOrOut == "O" ) or ( inOrOut == "I" ) )
      req.attr.INOUT = inOrOut;
    end;
  end;

  if ( ValType( silence ) != V_BOOL )
    silence = false;
  end;

  while ( cycle )
    cycle = false;

    retCode = CNG_Request( req, resp );

    if ( retCode == 0 )
      retCode = resp.attr.RE;
    end;

    if ( ( retCode == 100 ) or ( retCode == 105 ) )
      if ( silence )
        stat = false;
      else
        if ( GetTrue( true, "Не удалось получить информацию из КЦ. Повторить попытку ?" ) )
          cycle = true;
        else
          stat = false;
        end;
      end;
    elif ( retCode != 0 )
      if ( not silence )
        if ( ( ValType( resp.attr.ERR_TEXT ) == V_STRING ) and ( resp.attr.ERR_TEXT != "" ) )
          MsgBox( MT_PS_MESSAGE_PREFIX + resp.attr.ERR_TEXT );
        else
          MsgBox( "Ошибка при запросе в КЦ о получении данных по платежу" );
        end;
      end;
      stat = false;
    end;
  end;

  if ( stat )
    if ( ValType( resp.trnReference ) != V_UNDEF )
      trans.rec.transCode = resp.trnReference;
    end;
    if ( ( ValType( resp.trnDate ) == V_DATE ) and ( resp.trnDate != date( 0, 0, 0 ) ) )
      trans.rec.sendDate = resp.trnDate;
    end;
    if ( ValType( resp.trnSendPoint ) != V_UNDEF )
      trans.rec.sendPointCode = resp.trnSendPoint;
    end;
    if ( ValType( resp.trnPickupPoint ) != V_UNDEF )
      trans.rec.receivePointCode = resp.trnPickupPoint;
    end;
    if ( ValType( resp.trnAmount ) != V_UNDEF )
      trans.rec.sum = resp.trnAmount;
    end;
    if ( ValType( resp.trnCurrency ) != V_UNDEF )
      trans.rec.curCode = convertCurrFromCNGString( resp.trnCurrency );
    else
      trans.rec.curCode = -1;
    end;
    if ( ValType( resp.sName ) != V_UNDEF )
      trans.rec.senderName1 = resp.sName;
    end;
    if ( ValType( resp.sLastName ) != V_UNDEF )
      trans.rec.senderName2 = resp.sLastName;
    end;
    if ( ValType( resp.sSurName ) != V_UNDEF )
      trans.rec.senderName3 = resp.sSurName;
    end;
    if ( ValType( resp.sBirthday ) != V_UNDEF )
      trans.rec.senderBorn = resp.sBirthday;
    end;
    if ( ValType( resp.sBirthPlace ) != V_UNDEF )
      trans.rec.senderBornPlace = resp.sBirthPlace;
    end;
    if ( ValType( resp.sCountryOfBirth ) != V_UNDEF )
      ;
    end;
    if ( ValType( resp.sResident ) != V_UNDEF )
      if ( resp.sResident == 0 )
        trans.rec.senderNotResident = 1;
      else
        trans.rec.senderNotResident = 0;
      end;
    end;
    if ( ValType( resp.sResidentC ) != V_UNDEF )
      trans.rec.senderResidentship = resp.sResidentC;
    end;
    trans.rec.senderPaperKind = -1;
    trans.rec.senderPaperKind2 = -1;
    if ( ValType( resp.sIDTypeCode ) == V_INTEGER )
      trans.rec.senderPaperKind2 = resp.sIDTypeCode;
      trans.rec.senderPaperKind = getPaperKindFromCNGTypeCode( trans.rec.senderPaperKind2, trans.rec.sendPointCode );
    else
      trans.rec.senderPaperKind = -1;
      trans.rec.senderPaperKind2 = -1;
    end;
    if ( ( trans.rec.senderPaperKind == -1 ) and ( ValType( resp.sIDtype ) != V_UNDEF ) )
      trans.rec.senderPaperKind = getPaperIdFromCNGString( resp.sIDtype );
    end;
    if ( ValType( resp.sIDnumber ) != V_UNDEF )
      ParsePaperFromCNGString( resp.sIDnumber, trans.rec.senderPaperSeries, trans.rec.senderPaperNumber );
    end;
    if ( ( ValType( resp.sIDdate ) == V_DATE ) and ( resp.sIDdate != date( 0, 0, 0 ) ) )
      trans.rec.senderPaperIssuedDate = resp.sIDdate;
    end;
    if ( ValType( resp.sIDwhom ) != V_UNDEF )
      trans.rec.senderPaperIssuer = resp.sIDwhom;
    end;
    if ( ValType( resp.sIDwhomCode ) != V_UNDEF )
      trans.rec.senderPaperIssuerCode = resp.sIDwhomCode;
    end;
    if ( ( ValType( resp.sIDexpireDate ) == V_DATE ) and ( resp.sIDexpireDate != date( 0, 0, 0 ) ) )
      trans.rec.senderPaperExpiratDate = resp.sIDexpireDate;
    end;
    if ( ValType( resp.sCountryC ) != V_UNDEF )
      trans.rec.senderCitizenship = getCodeLat3( resp.sCountryC );
    end;
    if ( ValType( resp.sCountry ) != V_UNDEF )
      trans.rec.senderCountry = getCodeLat3( resp.sCountry );
    end;
    if ( ValType( resp.sZipCode ) != V_UNDEF )
      trans.rec.senderPostIndex = resp.sZipCode;
    end;
    if ( ValType( resp.sRegion ) != V_UNDEF )
      trans.rec.senderRegion = resp.sRegion;
    end;
    if ( ValType( resp.sCity ) != V_UNDEF )
      trans.rec.senderPlace = resp.sCity;
    end;
    if ( ValType( resp.sAddress ) != V_UNDEF )
      trans.rec.senderAdress = resp.sAddress;
    end;
    if ( ValType( resp.sPhone ) != V_UNDEF )
      trans.rec.senderPhoneNumber = resp.sPhone;
    end;
    if ( ValType( resp.bName ) != V_UNDEF )
      trans.rec.recName1 = resp.bName;
    end;
    if ( ValType( resp.bLastName ) != V_UNDEF )
      trans.rec.recName2 = resp.bLastName;
    end;
    if ( ValType( resp.bSurName ) != V_UNDEF )
      trans.rec.recName3 = resp.bSurName;
    end;
    if ( ValType( resp.bBirthday ) != V_UNDEF )
      trans.rec.recBorn = resp.bBirthday;
    end;
    if ( ValType( resp.bBirthPlace ) != V_UNDEF )
      trans.rec.recBornPlace = resp.bBirthPlace;
    end;
    if ( ValType( resp.bResident ) != V_UNDEF )
      if ( resp.bResident == 0 )
        trans.rec.recNotResident = 1;
      else
        trans.rec.recNotResident = 0;
      end;
    end;
    if ( ValType( resp.bResidentC ) != V_UNDEF )
      trans.rec.recResidentship = resp.bResidentC;
    end;
    if ( ValType( resp.bIDTypeCode ) == V_INTEGER )
      trans.rec.recPaperKind2 = resp.bIDTypeCode;
      trans.rec.recPaperKind = getPaperKindFromCNGTypeCode( trans.rec.recPaperKind2, trans.rec.receivePointCode );
    else
      trans.rec.recPaperKind = -1;
      trans.rec.recPaperKind2 = -1;
    end;
    if ( ( trans.rec.recPaperKind == -1 ) and ( ValType( resp.bIDtype ) != V_UNDEF ) )
      trans.rec.recPaperKind = getPaperIdFromCNGString( resp.bIDtype );
    end;
    if ( ValType( resp.bIDnumber ) != V_UNDEF )
      ParsePaperFromCNGString( resp.bIDnumber, trans.rec.recPaperSeries, trans.rec.recPaperNumber );
    end;
    if ( ( ValType( resp.bIDdate ) == V_DATE ) and ( resp.bIDdate != date( 0, 0, 0 ) ) )
      trans.rec.recPaperIssuedDate = resp.bIDdate;
    end;
    if ( ValType( resp.bIDwhom ) != V_UNDEF )
      trans.rec.recPaperIssuer = resp.bIDwhom;
    end;
    if ( ValType( resp.bIDwhomCode ) != V_UNDEF )
      trans.rec.recPaperIssuerCode = resp.bIDwhomCode;
    end;
    if ( ( ValType( resp.bIDexpireDate ) == V_DATE ) and ( resp.bIDexpireDate != date( 0, 0, 0 ) ) )
      trans.rec.recPaperExpiratDate = resp.bIDexpireDate;
    end;
    if ( ValType( resp.bCountryC ) != V_UNDEF )
      trans.rec.recCitizenship = getCodeLat3( resp.bCountryC );
    end;
    if ( ValType( resp.bCountry ) != V_UNDEF )
      trans.rec.recCountry = getCodeLat3( resp.bCountry );
    end;
    if ( ValType( resp.bZipCode ) != V_UNDEF )
      trans.rec.recPostIndex = resp.bZipCode;
    end;
    if ( ValType( resp.bRegion ) != V_UNDEF )
      trans.rec.recRegion = resp.bRegion;
    end;
    if ( ValType( resp.bCity ) != V_UNDEF )
      trans.rec.recPlace = resp.bCity;
    end;
    if ( ValType( resp.bAddress ) != V_UNDEF )
      trans.rec.recAdress = resp.bAddress;
    end;
    if ( ValType( resp.bPhone ) != V_UNDEF )
      trans.rec.recPhoneNumber = resp.bPhone;
    end;
    if ( ValType( resp.bAccountType ) != V_UNDEF )
      trans.rec.recTypeAccount = resp.bAccountType;
    end;
    if ( ValType( resp.tAccountNumber ) != V_UNDEF )
      trans.rec.recAccount = resp.tAccountNumber;
    end;
    if ( ValType( resp.trnAdditionalInfo ) != V_UNDEF )
      trans.rec.recAddInfo = resp.trnAdditionalInfo;
    end;
    if ( ValType( resp.bBank ) != V_UNDEF )
      trans.rec.recBankName = resp.bBank;
    end;
    if ( ValType( resp.bAccount ) != V_UNDEF )
      trans.rec.recBankAccount = resp.bAccount;
    end;
    if ( ValType( resp.trnPassword ) != V_UNDEF )
      trans.rec.password = resp.trnPassword;
    end;
    if ( ValType( resp.bEMAIL ) != V_UNDEF )
      trans.rec.recEMail = resp.bEMAIL;
    end;
    if ( ValType( resp.trnFeesClientCurr ) != V_UNDEF )
      trans.rec.curCodeCommis = convertCurrFromCNGString( resp.trnFeesClientCurr );
    end;
    if ( ValType( resp.trnFeesPart ) != V_UNDEF )
      trans.rec.sumCommisOur = resp.trnFeesPart;
    end;

    if ( ValType( forReturn ) == V_BOOL )
      if ( forReturn and ( ValType( resp.trnReturnFees ) == V_INTEGER ) )
        if ( resp.trnReturnFees > 0 )
          trans.rec.isReturnComiss = "X";
          trans.rec.returnCS_CurCode = trans.rec.curCode;
          if ( ( ValType( resp.trnReturnFeesClient ) != V_UNDEF ) and ( ValType( resp.trnReturnRsbFees ) != V_UNDEF ) )
            trans.rec.returnCS_Client = resp.trnReturnFeesClient;
            trans.rec.returnCS_CC = resp.trnReturnRsbFees;
          end;
        end;
      end;
    end;

    if ( IsEqClass( "XmlRSLStruct", resp ) )
      var auxAttr = trans.auxAttr;
      var auxBranch = trans.rec.Branch;
      var addValues = resp.GetValues( );

      if ( auxBranch == 0 )
        auxBranch = NumFNcash( );
      end;

      if ( addValues != null )
        i = 0;
        while ( i < addValues.Size )

          auxAttr.Rewind;
          auxAttr.Clear;
          auxAttr.KeyNum = 1;
          auxAttr.rec.Branch = auxBranch;
          auxAttr.rec.MTO_Id = trans.rec.transId;
          auxAttr.rec.TypeInfo = 0;
          auxAttr.rec.Field_PS = addValues[i].name;

          if ( auxAttr.GetEQ )
            if ( auxAttr.rec.Type == 7 )
              auxAttr.rec.Val_String = addValues[i].value;

              auxAttr.Update;
            end;
          else
            auxAttr.Clear;
            auxAttr.rec.Branch = auxBranch;
            auxAttr.rec.MTO_Id = trans.rec.transId;
            auxAttr.rec.TypeInfo = 0;
            auxAttr.rec.Field_PS = addValues[i].name;
            auxAttr.rec.Type = 7;
            auxAttr.rec.Val_String = addValues[i].value;

            auxAttr.Insert;
          end;

          i = i + 1;
        end;
      end;	
    end;

    trans.rec.psTransID = trn_id;

    /*
    if ( ( trans.rec.sendPointCode == trans.rec.receivePointCode ) and ( trans.rec.sendPointCode != "" ) )
      trans.rec.ourFlag = 1;
    end;
    */

    if ( trans.rec.curCode < 0 )
      if ( not silence )
        MsgBox( "Не хватает данных по платежу при запросе в КЦ" );
      end;
      stat = false;
    end;       
  end;

  if ( stat )
    SetParm( 4, resp.attr.STATE );
  end;

  return stat;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro GetIncomingPayments

  var req = TReqReadyToPay;
  var resp = TRespReadyToPay;
  var dataPacket;
  var retCode;
  var cmd;
  var rmto_trans_tmp = TBFile( "rmto_trans.tmp", "W" );
  var cycle = true;
  var i = 0;
  var stat = true;

  cmd = RsdCommand( "truncate table drmto_trans_tmp" );
  cmd.execute( );

  cmd = RsdCommand( "truncate table drmto_aux_attr_tmp" );
  cmd.execute( );

  if ( stat )
    req.attr.USER_ID = 0;

    while ( cycle )
      cycle = false;

      retCode = CNG_Request( req, resp );

      if ( retCode == 0 )
        retCode = resp.attr.RE;
      end;

      if ( ( retCode == 100 ) or ( retCode == 105 ) )
        if ( GetTrue( true, "Не удалось получить информацию из КЦ. Повторить попытку ?" ) )
          cycle = true;
        else
          stat = false;
        end;
      elif ( retCode != 0 )
        if ( ( ValType( resp.attr.ERR_TEXT ) == V_STRING ) and ( resp.attr.ERR_TEXT != "" ) )
          MsgBox( MT_PS_MESSAGE_PREFIX + resp.attr.ERR_TEXT );
        else
          MsgBox( "Ошибка при запросе в КЦ о получении данных по платежам" );
        end;
        stat = false;
      end;
    end;
  end;

  if ( stat )
    if ( resp.GetDataPacket( dataPacket ) != 0 )
      MsgBox( "Ошибка при загрузке шаблонов" );
      stat = false;
    end;
  end;

  if ( stat )
    i = 0;

    while ( i < dataPacket.Size )
      if ( dataPacket[i].attr.STATE == 4 )
        rmto_trans_tmp.Clear( );
        rmto_trans_tmp.rec.branch = NumFNCash( );
        rmto_trans_tmp.rec.transId = i + 1;
        rmto_trans_tmp.rec.psId = 3; // !!!!! Возможно надо будет добавить передачу
        rmto_trans_tmp.rec.transCode = dataPacket[i].attr.TRN;
        rmto_trans_tmp.rec.ourFlag = 0;
        rmto_trans_tmp.rec.sendDate = dataPacket[i].attr.DT_FILE_STR;
        if ( dataPacket[i].attr.STATE == 4 )
          rmto_trans_tmp.rec.state = "ONSET_____";
        end;
        rmto_trans_tmp.rec.sendPointCode = dataPacket[i].attr.PP_CODE;
        rmto_trans_tmp.rec.receivePointCode = "";
        rmto_trans_tmp.rec.sum = dataPacket[i].attr.AMOUNT;
        rmto_trans_tmp.rec.curCode = convertCurrFromCNGString( dataPacket[i].attr.CODE );
        ParseFIOFromCNGString( dataPacket[i].attr.SENDER_NAME, rmto_trans_tmp.rec.senderName1,
                                                               rmto_trans_tmp.rec.senderName2,
                                                               rmto_trans_tmp.rec.senderName3 );
        rmto_trans_tmp.rec.senderPlace = dataPacket[i].attr.CITY;
        rmto_trans_tmp.rec.senderCountry = dataPacket[i].attr.COUNTRY;
        ParseFIOFromCNGString( dataPacket[i].attr.REC_NAME, rmto_trans_tmp.rec.recName1,
                                                            rmto_trans_tmp.rec.recName2,
                                                            rmto_trans_tmp.rec.recName3 );
        rmto_trans_tmp.rec.recAddInfo = dataPacket[i].attr.ADDITIONALINFO;
        rmto_trans_tmp.rec.psTransID = dataPacket[i].attr.ID;

        if ( rmto_trans_tmp.rec.curCode < 0 )
          stat = false;
          MsgBox( "Ошибка определения кода валюты при формировании временных таблиц" );
          break;
        end;

        stat = rmto_trans_tmp.Insert( );
        if ( not stat )
          MsgBox( "Ошибка при формировании временных таблиц" );
          break;
        end;
      end;

      i = i + 1;
    end;
  end;

  return stat;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro GetOutgoingPayments

  var req = TReqGetState;
  var resp = TRespGetState;
  var retCode;
  var statusCode = 0;
  var cmd;
  var rs;
  var rmto_trans_tmp = TBFile( "rmto_trans.tmp", "W" );
  var branch = NumFNCash( );
  var psId = 3;
  var cycle = true;
  var i = 0;
  var stat = true;
          
  if ( inputOutgoing.datePay == Date( 0, 0, 0 ) )
    MsgBox( "Для получения списка платежей узла необходимо указать дату" );
    stat = false;
  end;

  if ( stat )
    cmd = RsdCommand( "truncate table drmto_trans_tmp" );
    cmd.execute( );

    cmd = RsdCommand( "truncate table drmto_aux_attr_tmp" );
    cmd.execute( );
  end;

  if ( stat )
    cmd = RsdCommand( "select * "
                      "from drmto_trans_dbt "
                      "where t_branch = :branch and "
                            "t_ourFlag = 1 and "
                            "t_sendDate = :sendDate and "
                            "t_psId = :psId and "
                            "t_psTransID != 0 and "
                            "t_action != 2 " 
                            "order by t_branch, t_ourFlag, t_sendDate, t_transCode desc" );
        
    cmd.addParam( "branch", RSDBP_IN, branch );
    cmd.addParam( "sendDate", RSDBP_IN, inputOutgoing.datePay );
    cmd.addParam( "psId", RSDBP_IN, psId );

    rs = RsdRecordSet( cmd );

    cmd.execute( );
  
    while ( rs.moveNext( ) )

      statusCode = 0;

      req.attr.USER_ID = rs.value( "t_recPartyID" );
      req.attr.DOC_ID = rs.value( "t_psTransID" );

      retCode = CNG_Request( req, resp );

      if ( retCode == 0 )
        retCode = resp.attr.RE;
      end;

      if ( retCode == 0 )
        statusCode = resp.attr.STATE;
      end;

      if ( statusCode == 4 )

        i = i + 1;

        rmto_trans_tmp.Clear( );
        rmto_trans_tmp.rec.branch = NumFNCash( );
        rmto_trans_tmp.rec.transId = i;
        rmto_trans_tmp.rec.psId = rs.value( "t_psId" );
        rmto_trans_tmp.rec.transCode = rs.value( "t_transCode" );
        rmto_trans_tmp.rec.ourFlag = 1;
        rmto_trans_tmp.rec.state = rs.value( "t_state" );
        rmto_trans_tmp.rec.sendDate = rs.value( "t_sendDate" );
        rmto_trans_tmp.rec.sendPointCode = rs.value( "t_sendPointCode" );
        rmto_trans_tmp.rec.receivePointCode = rs.value( "t_receivePointCode" );
        rmto_trans_tmp.rec.sum = rs.value( "t_sum" );
        rmto_trans_tmp.rec.curCode = rs.value( "t_curCode" );
        rmto_trans_tmp.rec.recBankName = rs.value( "t_recBankName" );
        rmto_trans_tmp.rec.recAddInfo = rs.value( "t_recAddInfo" );
        rmto_trans_tmp.rec.senderName1 = rs.value( "t_senderName1" );
        rmto_trans_tmp.rec.senderName2 = rs.value( "t_senderName2" );
        rmto_trans_tmp.rec.senderName3 = rs.value( "t_senderName3" );
        rmto_trans_tmp.rec.recName1 = rs.value( "t_recName1" );
        rmto_trans_tmp.rec.recName2 = rs.value( "t_recName2" );
        rmto_trans_tmp.rec.recName3 = rs.value( "t_recName3" );
        rmto_trans_tmp.rec.recBorn = rs.value( "t_recBorn" );
        rmto_trans_tmp.rec.recBornPlace = rs.value( "t_recBornPlace" );
        rmto_trans_tmp.rec.recCitizenship = rs.value( "t_recCitizenship" );
        rmto_trans_tmp.rec.recNotResident = rs.value( "t_recNotResident" );
        rmto_trans_tmp.rec.recResidentship = rs.value( "t_recResidentship" );
        rmto_trans_tmp.rec.recPaperKind = rs.value( "t_recPaperKind" );
        rmto_trans_tmp.rec.recPaperSeries = rs.value( "t_recPaperSeries" );
        rmto_trans_tmp.rec.recPaperNumber = rs.value( "t_recPaperNumber" );
        rmto_trans_tmp.rec.recPaperIssuedDate = rs.value( "t_recPaperIssuedDate" );
        rmto_trans_tmp.rec.recPaperIssuer = rs.value( "t_recPaperIssuer" );
        rmto_trans_tmp.rec.recPaperIssuerCode = rs.value( "t_recPaperIssuerCode" );
        rmto_trans_tmp.rec.recPaperExpiratDate = rs.value( "t_recPaperExpiratDate" );
        rmto_trans_tmp.rec.recCountry = rs.value( "t_recCountry" );
        rmto_trans_tmp.rec.recPostIndex = rs.value( "t_recPostIndex" );
        rmto_trans_tmp.rec.recRegion = rs.value( "t_recRegion" );
        rmto_trans_tmp.rec.recPlace = rs.value( "t_recPlace" );
        rmto_trans_tmp.rec.recAdress = rs.value( "t_recAdress" );
        rmto_trans_tmp.rec.recPhoneNumber = rs.value( "t_recPhoneNumber" );
        rmto_trans_tmp.rec.recCountryCode = rs.value( "t_recCountryCode" );
        rmto_trans_tmp.rec.recPlaceName = rs.value( "t_recPlaceName" );
        rmto_trans_tmp.rec.psTransID = rs.value( "t_psTransID" );

        stat = rmto_trans_tmp.Insert( );
        if ( not stat )
          MsgBox( "Ошибка при формировании временных таблиц" );
          break;
        end;
      end;
    end;
  end;

  return stat;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
private macro onF2( )

  var req = TReqReadyToPay;
  var resp = TRespReadyToPay;
  var dataPacket;
  var retCode;
  var cycle = true;
  var stat = true;

  if ( stat )
    if ( StrLen( inputNumPay.numPay ) == 0 )
      MsgBox( "Задайте номер платежа" );
      stat = false;
    end;
  end;

  if ( stat )
    if ( StrLen( inputNumPay.numPay ) > 16 )
      MsgBox( "Не верно задан номер платежа" );
      stat = false;
    end;
  end;

  if ( stat )
    req.attr.USER_ID = 0;
    req.PARAMS.attr.trnReference = inputNumPay.numPay;

    while ( cycle )
      cycle = false;

      retCode = CNG_Request( req, resp );

      if ( retCode == 0 )
        retCode = resp.attr.RE;
      end;

      if ( ( retCode == 100 ) or ( retCode == 105 ) )
        if ( GetTrue( true, "Не удалось получить информацию из КЦ. Повторить попытку ?" ) )
          cycle = true;
        else
          stat = false;
        end;
      elif ( retCode != 0 )
        if ( ( ValType( resp.attr.ERR_TEXT ) == V_STRING ) and ( resp.attr.ERR_TEXT != "" ) )
          MsgBox( MT_PS_MESSAGE_PREFIX + resp.attr.ERR_TEXT );
        else
          MsgBox( "Ошибка при запросе в КЦ о получении данных по платежу" );
        end;
        stat = false;
      end;
    end;
  end;

  if ( stat )
    if ( resp.GetDataPacket( dataPacket ) != 0 )
      MsgBox( "Ошибка при загрузке шаблонов" );
      stat = false;
    end;
  end;

  if ( stat )
   if ( dataPacket.Size > 0 )
      idSelectPayment = dataPacket[0].attr.ID;
    else
      MsgBox( "Не найден платеж с кодом " + inputNumPay.numPay );
      stat = false;
    end;
  end;

  return stat;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
private macro onF3

  var templateID = 0;
  var cmd;
  var rs;

  if ( GetIncomingPayments( ) )
    if ( CNG_SelectTemplate( 0, templateID ) )

      cmd = RsdCommand( "select rmto_trans.t_transCode as transCode " 
                        "from drmto_trans_tmp rmto_trans " +
                        "where rmto_trans.t_Branch = :branch " +
                          "and rmto_trans.t_transId = :transId" );

      rs = RsdRecordset( cmd );

      cmd.addParam( "branch", RSDBP_IN, NumFNCash( ) );
      cmd.addParam( "transId", RSDBP_IN, templateID );

      cmd.execute( );

      if ( rs.moveNext() )
        inputNumPay.numPay = rs.value( "transCode" );
      end;
    end;
  end;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro keyHandler( IP, cmd, id, key )

  var stat = CM_DEFAULT;

  if ( cmd == DLG_KEY )
    if ( key == 27 )
      stat = CM_CANCEL;
    elif  ( key == 316 )
      if ( onF2( inputNumPay.numPay ) )
        stat = CM_SAVE;
      end;
    elif  ( key == 317 )
      onF3( );
    elif  ( key == 323 )
      stat = CM_IGNORE;
    end;
  end;

  return stat;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro SelectIncomingPayment( )

  var stat = true;

  idSelectPayment = 0;

  ClearRecord( inputNumPay );

  stat = RunDialog( inputNumPay, "keyHandler" );

  if ( stat )
    ;
  else
    idSelectPayment = 0;
  end;

  return idSelectPayment;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
private macro onF2Outgoing( )

  var req = TReqGetState;
  var resp = TRespGetState;
  var dataPacket;
  var retCode;
  var cycle = true;
  var stat = true;
  var psCodeCNT = 3;
  var psTransId = 0;
  var nameState = "";
  var cmd;
  var rs;

  if ( stat )
    if ( StrLen( inputOutgoing.numPay ) == 0 )
      MsgBox( "Задайте номер платежа" );
      stat = false;
    end;
  end;

  if ( stat )
    if ( StrLen( inputOutgoing.numPay ) > 16 )
      MsgBox( "Не верно задан номер платежа" );
      stat = false;
    end;
  end;

  if ( stat )
    cmd = RsdCommand( "select rmto_trans.t_psTransId as psTransId " +
                      "from drmto_trans_dbt rmto_trans " +
                      "where rmto_trans.t_branch = :branch and " +
                            "rmto_trans.t_psId = :psId and " +
                            "rmto_trans.t_transCode = :transCode " +
                            "order by rmto_trans.t_sendDate desc" );

    rs = RsdRecordset( cmd );
    cmd.addParam( "branch", RSDBP_IN, NumFNcash( ) );
    cmd.addParam( "psId", RSDBP_IN, psCodeCNT );
    cmd.addParam( "transCode", RSDBP_IN, inputOutgoing.numPay );

    cmd.execute( );

    if ( rs.moveNext( ) )
      psTransId = rs.value( "psTransId" );
    else
      MsgBox( "Не найден перевод c идентификатором \"" + inputOutgoing.numPay + "\"" );
      stat = false;
    end;
  end;

  if ( stat )
    req.attr.USER_ID = 0;
    req.attr.DOC_ID = psTransId;

    while ( cycle )
      cycle = false;

      retCode = CNG_Request( req, resp );

      if ( retCode == 0 )
        retCode = resp.attr.RE;
      end;
                  
      if ( ( retCode == 100 ) or ( retCode == 105 ) )
        if ( GetTrue( true, "Не удалось получить информацию из КЦ. Повторить попытку ?" ) )
          cycle = true;
        else
          stat = false;
        end;
      elif ( retCode != 0 )
        if ( ( ValType( resp.attr.ERR_TEXT ) == V_STRING ) and ( resp.attr.ERR_TEXT != "" ) )
          MsgBox( MT_PS_MESSAGE_PREFIX + resp.attr.ERR_TEXT );
        else
          MsgBox( "Ошибка при запросе в КЦ о получении данных по платежу" );
        end;
        stat = false;
      end;
    end;
  end;

  if ( stat )
    if ( ( resp.attr.STATE == 3 ) or ( resp.attr.STATE == 4 ) )
      idSelectPayment = psTransId;
    else
      nameState = defNamesStateMonTransFromPC( resp.attr.STATE );

      if ( nameState != "" )
        MsgBox( "Платеж находится в состоянии \"" + nameState + "\"|Выполнение операции запрещено" );
      else
        MsgBox( "Платеж находится в состоянии \"" + resp.attr.STATE + "\"|Выполнение операции запрещено" );
      end;

      stat = false;
    end;
  end;

  return stat;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
private macro onAltF3Outgoing( id )

  var codeSelect;
  var codeClient = 0;
  var templateID = 0;
  var cmd;
  var rs;

  if ( id == 5 )
    codeSelect = SelectUniqClient( codeClient, inputOutgoing.name1, inputOutgoing.name2, inputOutgoing.name3, inputOutgoing.born );

    if ( codeSelect == 0 )

      if ( GetTemplates( codeClient, 0 ) )
        if ( CNG_SelectTemplate( 0, templateID ) )

          cmd = RsdCommand( "select rmto_trans.t_transCode as transCode " 
                            "from drmto_trans_tmp rmto_trans " +
                            "where rmto_trans.t_branch = :branch " +
                              "and rmto_trans.t_transId = :transId" );

          rs = RsdRecordset( cmd );

          cmd.addParam( "branch", RSDBP_IN, NumFNCash( ) );
          cmd.addParam( "transId", RSDBP_IN, templateID );

          cmd.execute( );

          if ( rs.moveNext() )
            if ( ( rs.value( "transCode" ) == "" ) or ( rs.value( "transCode" ) == StrFor( 1 ) ) )
              ;
            else
              inputOutgoing.numPay = rs.value( "transCode" );
            end;
          end;
        end;
      end;
    elif ( codeSelect > 0 )
      ;
    else
      MsgBox( "Отправитель не является клиентом нашего банка" );
    end;
  end;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
private macro onF3Outgoing( id )

  var clientList = TClientList;
  var templateID = 0;
  var cmd;
  var rs;

  if ( ( id == 1 ) or ( id == 2 ) or ( id == 3 ) or ( id == 4 ) )
    if ( clientList.SelectByFIO( ) )
      inputOutgoing.name1 = clientList.CurRec.Rec.Name1;
      inputOutgoing.name2 = clientList.CurRec.Rec.Name2;
      inputOutgoing.name3 = clientList.CurRec.Rec.Name3;
      inputOutgoing.born = clientList.CurRec.Rec.Born;
    end;
  elif ( id == 5 )
    if ( GetOutgoingPayments( ) )
      if ( CNG_SelectTemplate( 0, templateID ) )

        cmd = RsdCommand( "select rmto_trans.t_transCode as transCode " 
                          "from drmto_trans_tmp rmto_trans " +
                          "where rmto_trans.t_Branch = :branch " +
                            "and rmto_trans.t_transId = :transId" );

        rs = RsdRecordset( cmd );

        cmd.addParam( "branch", RSDBP_IN, NumFNCash( ) );
        cmd.addParam( "transId", RSDBP_IN, templateID );

        cmd.execute( );

        if ( rs.moveNext() )
          inputOutgoing.numPay = rs.value( "transCode" );
        end;
      end;
    end;
  end;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro keyHandlerOutgoing( IP, cmd, id, key )

  var stat = CM_DEFAULT;

  if ( cmd == DLG_INIT )
    SetFocus( IP, 5 );
    stat = CM_IGNORE;
  elif ( cmd == DLG_KEY )
    if ( key == 27 )
      stat = CM_CANCEL;
    elif  ( key == 316 )
      if ( onF2Outgoing( ) )
        stat = CM_SAVE;
      end;
    elif  ( key == 317 )
      onF3Outgoing( id );
      UpdateFields( IP );
    elif  ( key == 362 )
      onAltF3Outgoing( id );
    elif  ( key == 323 )
      stat = CM_IGNORE;
    end;
  end;

  return stat;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro SelectOutgoingPayment( numPay )

  var stat = true;

  idSelectPayment = 0;
  numPay = "";

  ClearRecord( inputOutgoing );

  inputOutgoing.datePay = date( );//{curdate};

  stat = RunDialog( inputOutgoing, "keyHandlerOutgoing" );

  if ( stat )
    numPay = inputOutgoing.numPay;
  else
    idSelectPayment = 0;
  end;

  SetParm( 0, numPay );

  return idSelectPayment;
end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
private var pointCodeForRef = "";

macro GetRefDataTrnProc

  var cmd;
  var rs;
  var id = 0;
  var parent_id = 0;
  var scen_id = 0;
  var city_id = 0;
  var i;
  var isGroup;
  var groupNum;
  array aGroupNum;
      
  // Захват в эксклюзивное пользование справочника банков ----------------
  cmd = RsdCommand( "select cng_banks.t_id as id, cng_banks.t_parent_id as parent_id, " + 
                           "cng_banks.t_scen_id as scen_id, cng_banks.t_city_id as city_id " + 
                    "from dcng_banks_dbt cng_banks " + 
                    "where cng_banks.t_pp_code = :pp_code " + 
                    "for update" );

  cmd.addParam( "pp_code", RSDBP_IN, pointCodeForRef );

  rs = RsdRecordSet( cmd );

  cmd.execute( );

  if ( rs.moveNext( ) )
    id = rs.value( "id" );
    parent_id = rs.value( "parent_id" );
    scen_id = rs.value( "scen_id" );
    city_id = rs.value( "city_id" );
  end;

  // Захват в эксклюзивное пользование справочника группы полей, заполняемых на шаге
  if ( scen_id > 0 )
    cmd = RsdCommand( "select 1 " +
                      "from dcng_scitem_grp_dbt cng_scitem_grp " +
                      "where cng_scitem_grp.t_scen_id = :scen_id " +
                      "for update" );

    cmd.addParam( "scen_id", RSDBP_IN, scen_id );

    cmd.execute( );
  end;

  // Захват в эксклюзивное пользование справочника группы полей, заполняемых для участника
  if ( id > 0 )
    cmd = RsdCommand( "select cng_attr_grps.t_groupnum as groupnum " +
                      "from dcng_attr_grps_dbt cng_attr_grps " +
                      "where ( cng_attr_grps.t_subj_code = :id and cng_attr_grps.t_subj_type = 3 ) " +
                      "for update" );

    cmd.addParam( "id", RSDBP_IN, id );

    rs = RsdRecordSet( cmd );

    cmd.execute( );

    while ( rs.moveNext( ) )
      groupNum = rs.value( "groupnum" );
      i = 0;
      isGroup = false;
      while ( i < ASize( aGroupNum ) )
        if ( aGroupNum( i ) == groupNum )
          isGroup = true;
          break;
        end;
        i = i + 1;
      end;

      if ( not isGroup )
        aGroupNum( ASize( aGroupNum ) ) = groupNum;
      end;
    end;
  end;

  if ( parent_id > 0 )
    cmd = RsdCommand( "select cng_attr_grps.t_groupnum as groupnum " +
                      "from dcng_attr_grps_dbt cng_attr_grps " +
                      "where ( cng_attr_grps.t_subj_code = :parent_id and cng_attr_grps.t_subj_type = 2 )" +
                      "for update" );

    cmd.addParam( "parent_id", RSDBP_IN, parent_id );

    rs = RsdRecordSet( cmd );

    cmd.execute( );

    while ( rs.moveNext( ) )
      groupNum = rs.value( "groupnum" );
      i = 0;
      isGroup = false;
      while ( i < ASize( aGroupNum ) )
        if ( aGroupNum( i ) == groupNum )
          isGroup = true;
          break;
        end;
        i = i + 1;
      end;

      if ( not isGroup )
        aGroupNum( ASize( aGroupNum ) ) = groupNum;
      end;
    end;
  end;

  if ( scen_id > 0 )
    cmd = RsdCommand( "select cng_attr_grps.t_groupnum as groupnum " +
                      "from dcng_attr_grps_dbt cng_attr_grps " +
                      "left join dcng_scitem_grp_dbt cng_scitem_grp on ( cng_scitem_grp.t_scen_id = :scen_id ) " +
                      "where ( cng_attr_grps.t_subj_code = cng_scitem_grp.t_id and cng_attr_grps.t_subj_type = 5 )" +
                      "for update" );

    cmd.addParam( "scen_id", RSDBP_IN, scen_id );

    rs = RsdRecordSet( cmd );

    cmd.execute( );

    while ( rs.moveNext( ) )
      groupNum = rs.value( "groupnum" );
      i = 0;
      isGroup = false;
      while ( i < ASize( aGroupNum ) )
        if ( aGroupNum( i ) == groupNum )
          isGroup = true;
          break;
        end;
        i = i + 1;
      end;

      if ( not isGroup )
        aGroupNum( ASize( aGroupNum ) ) = groupNum;
      end;
    end;
  end;

  // Захват в эксклюзивное пользование справочника списка полей документа к заполнению
  i = 0;
  while ( i < ASize( aGroupNum ) )
    cmd = RsdCommand( "select 1 " +
                      "from dcng_attrlist_dbt cng_attrlist " +
                      "where cng_attrlist.t_erased = 0 and " +
                            "cng_attrlist.t_grp_num = :grp_num " +
                      "for update" );

    cmd.addParam( "grp_num", RSDBP_IN, aGroupNum( i ) );

    cmd.execute( );

    i = i + 1;
  end;

  // Захват в эксклюзивное пользование справочника статусов документа в котором возможно изменение аттрибута
  i = 0;
  while ( i < ASize( aGroupNum ) )
    cmd = RsdCommand( "select 1 " +
                      "from dcng_attr_chng_dbt cng_attr_chng " +
                      "left join dcng_attrlist_dbt cng_attrlist on ( cng_attrlist.t_erased = 0 and cng_attrlist.t_grp_num = :grp_num ) " +
                      "where cng_attr_chng.t_attr_id = cng_attrlist.t_id " +
                      "for update" );

    cmd.addParam( "grp_num", RSDBP_IN, aGroupNum( i ) );

    cmd.execute( );

    i = i + 1;
  end;

  // Захват в эксклюзивное пользование справочника ограничения на суммы отправляемых переводов
  if ( id > 0 )
    cmd = RsdCommand( "select 1 " +
                      "from dcng_min_max_dbt cng_min_max " +
                      "where cng_min_max.t_bank_id = :id " +
                      "for update" );

    cmd.addParam( "id", RSDBP_IN, id );

    cmd.execute( );
  end;

  if ( ( parent_id > 0 ) and ( parent_id != id ) )
    cmd = RsdCommand( "select 1 " +
                      "from dcng_min_max_dbt cng_min_max " +
                      "where cng_min_max.t_bank_id = :parent_id " +
                      "for update" );

    cmd.addParam( "parent_id", RSDBP_IN, parent_id );

    cmd.execute( );
  end;

  cmd = RsdCommand( "select 1 " +
                    "from dcng_min_max_dbt cng_min_max " +
                    "where cng_min_max.t_bank_id = 0 " +
                    "for update" );

  cmd.execute( );

  // Захват в эксклюзивное пользование справочника городов ---------------
  if ( city_id > 0 )
    cmd = RsdCommand( "select 1 " +
                      "from dcng_city_dbt cng_city " +
                      "where cng_city.t_id = :city_id " +
                      "for update" );

    cmd.addParam( "city_id", RSDBP_IN, city_id );

    cmd.execute( );
  end;

  // Захват в эксклюзивное пользование справочника валют -----------------
  if ( id > 0 )
    cmd = RsdCommand( "select 1 " +
                      "from dcng_currency_dbt cng_currency " +
                      "where ( cng_currency.t_subj_code = :id and cng_currency.t_subj_type = 3 ) " +
                      "for update" );

    cmd.addParam( "id", RSDBP_IN, id );

    cmd.execute( );
  end;

  if ( parent_id > 0 )
    cmd = RsdCommand( "select 1 " +
                      "from dcng_currency_dbt cng_currency " +
                      "where ( cng_currency.t_subj_code = :parent_id and cng_currency.t_subj_type = 2 ) " +
                      "for update" );

    cmd.addParam( "parent_id", RSDBP_IN, parent_id );

    cmd.execute( );
  end;

  if ( city_id > 0 )
    cmd = RsdCommand( "select 1 " +
                      "from dcng_currency_dbt cng_currency " +
                      "where ( cng_currency.t_subj_code = :city_id and cng_currency.t_subj_type = 4 ) " +
                      "for update" );

    cmd.addParam( "city_id", RSDBP_IN, city_id );

    cmd.execute( );

    cmd = RsdCommand( "select 1 " +
                      "from dcng_currency_dbt cng_currency " +
                      "left join dcng_city_dbt cng_city on ( cng_city.t_id = :city_id ) " +
                      "where ( cng_currency.t_subj_code = cng_city.t_country and cng_currency.t_subj_type = 1 ) " +
                      "for update" );

    cmd.addParam( "city_id", RSDBP_IN, city_id );

    cmd.execute( );
  end;

  // =====================================================================

  // Копирование справочника банков --------------------------------------
  cmd = RsdCommand( "insert into dcng_banks_tmp tmp ( tmp.T_ID, tmp.T_ERASED, tmp.T_PARENT_ID, tmp.T_PP_CODE, tmp.T_BIC, tmp.T_NAME, tmp.T_ADDRESS, tmp.T_PHONE, tmp.T_WT_WEEK, tmp.T_WT_HOLIDAY, tmp.T_IS_BLOCKED, tmp.T_NAME_LAT, tmp.T_ADDRESS_LAT, tmp.T_CONTACT, tmp.T_IS_KFM, tmp.T_IS_ONLINE, tmp.T_CAN_REVOKE, tmp.T_CAN_CHANGE, tmp.T_GET_MONEY, tmp.T_CITY_ID, tmp.T_LOGO_ID, tmp.T_SCEN_ID, tmp.T_UNIQUE_TRN ) " +
                    "select cng_banks.T_ID, cng_banks.T_ERASED, cng_banks.T_PARENT_ID, cng_banks.T_PP_CODE, cng_banks.T_BIC, cng_banks.T_NAME, cng_banks.T_ADDRESS, cng_banks.T_PHONE, cng_banks.T_WT_WEEK, cng_banks.T_WT_HOLIDAY, cng_banks.T_IS_BLOCKED, cng_banks.T_NAME_LAT, cng_banks.T_ADDRESS_LAT, cng_banks.T_CONTACT, cng_banks.T_IS_KFM, cng_banks.T_IS_ONLINE, cng_banks.T_CAN_REVOKE, cng_banks.T_CAN_CHANGE, cng_banks.T_GET_MONEY, cng_banks.T_CITY_ID, cng_banks.T_LOGO_ID, cng_banks.T_SCEN_ID, cng_banks.T_UNIQUE_TRN " +
                    "from dcng_banks_dbt cng_banks " +
                    "where cng_banks.t_pp_code = :pp_code" );

  cmd.addParam( "pp_code", RSDBP_IN, pointCodeForRef );

  cmd.execute( );

  // Копирование справочника группы полей, заполняемых на шаге -----------
  if ( scen_id > 0 )
    cmd = RsdCommand( "insert into dcng_scitem_grp_tmp tmp ( tmp.T_ID, tmp.T_ERASED, tmp.T_SCEN_ID, tmp.T_STEP, tmp.T_OBJECT_CLASS, tmp.T_OBJECT_ACTION, tmp.T_LIST_SRC ) " +
                      "select cng_scitem_grp.T_ID, cng_scitem_grp.T_ERASED, cng_scitem_grp.T_SCEN_ID, cng_scitem_grp.T_STEP, cng_scitem_grp.T_OBJECT_CLASS, cng_scitem_grp.T_OBJECT_ACTION, cng_scitem_grp.T_LIST_SRC " +
                      "from dcng_scitem_grp_dbt cng_scitem_grp " +
                      "where cng_scitem_grp.t_scen_id = :scen_id" );

    cmd.addParam( "scen_id", RSDBP_IN, scen_id );

    cmd.execute( );
  end;

  // Копирование справочника группы полей, заполняемых для участника -----
  if ( id > 0 )
    cmd = RsdCommand( "insert into dcng_attr_grps_tmp tmp ( tmp.T_SUBJ_TYPE, tmp.T_SUBJ_CODE, tmp.T_GROUPNUM, tmp.T_SEQNUMBER ) " +
                      "select cng_attr_grps.T_SUBJ_TYPE, cng_attr_grps.T_SUBJ_CODE, cng_attr_grps.T_GROUPNUM, cng_attr_grps.T_SEQNUMBER " +
                      "from dcng_attr_grps_dbt cng_attr_grps " +
                      "where ( cng_attr_grps.t_subj_code = :id and cng_attr_grps.t_subj_type = 3 )" );

    cmd.addParam( "id", RSDBP_IN, id );

    cmd.execute( );
  end;

  if ( parent_id > 0 )
    cmd = RsdCommand( "insert into dcng_attr_grps_tmp tmp ( tmp.T_SUBJ_TYPE, tmp.T_SUBJ_CODE, tmp.T_GROUPNUM, tmp.T_SEQNUMBER ) " +
                      "select cng_attr_grps.T_SUBJ_TYPE, cng_attr_grps.T_SUBJ_CODE, cng_attr_grps.T_GROUPNUM, cng_attr_grps.T_SEQNUMBER " +
                      "from dcng_attr_grps_dbt cng_attr_grps " +
                      "where ( cng_attr_grps.t_subj_code = :parent_id and cng_attr_grps.t_subj_type = 2 )" );

    cmd.addParam( "parent_id", RSDBP_IN, parent_id );

    cmd.execute( );
  end;

  if ( scen_id > 0 )
    cmd = RsdCommand( "insert into dcng_attr_grps_tmp tmp ( tmp.T_SUBJ_TYPE, tmp.T_SUBJ_CODE, tmp.T_GROUPNUM, tmp.T_SEQNUMBER ) " +
                      "select cng_attr_grps.T_SUBJ_TYPE, cng_attr_grps.T_SUBJ_CODE, cng_attr_grps.T_GROUPNUM, cng_attr_grps.T_SEQNUMBER " +
                      "from dcng_attr_grps_dbt cng_attr_grps " +
                      "left join dcng_scitem_grp_dbt cng_scitem_grp on ( cng_scitem_grp.t_scen_id = :scen_id ) " +
                      "where ( cng_attr_grps.t_subj_code = cng_scitem_grp.t_id and cng_attr_grps.t_subj_type = 5 )" );

    cmd.addParam( "scen_id", RSDBP_IN, scen_id );

    cmd.execute( );
  end;

  // Копирование справочника списка полей документа к заполнению ---------
  i = 0;
  while ( i < ASize( aGroupNum ) )

    cmd = RsdCommand( "insert into dcng_attrlist_tmp tmp ( tmp.T_ID, tmp.T_ERASED, tmp.T_GRP_NUM, tmp.T_FIELD_GRP, tmp.T_SORTORDER, tmp.T_IS_COND, tmp.T_MIN_VALUE, tmp.T_MAX_VALUE, " +
                                                          "tmp.T_CURR_CODE, tmp.T_CURR_USE_EQ, tmp.T_S_RESIDENT, tmp.T_FIELD_NAME, tmp.T_FIELD_CAPTION, tmp.T_FIELD_CAPTION_LAT, " +
                                                          "tmp.T_REG_MASK, tmp.T_BIC, tmp.T_IS_REQUIRED, tmp.T_EXAMPLE, tmp.T_COMMENT, tmp.T_COMMENT_LAT, tmp.T_MAX_LEN, " +
                                                          "tmp.T_SHORT_CAPTION, tmp.T_SHORT_CAPTION_LAT, tmp.T_INOUTEDIT, tmp.T_DATA_TYPE, tmp.T_VISIBLE, tmp.T_LANG ) " +
                      "select cng_attrlist.T_ID, cng_attrlist.T_ERASED, cng_attrlist.T_GRP_NUM, cng_attrlist.T_FIELD_GRP, cng_attrlist.T_SORTORDER, " +
                             "cng_attrlist.T_IS_COND, cng_attrlist.T_MIN_VALUE, cng_attrlist.T_MAX_VALUE, cng_attrlist.T_CURR_CODE, " +
                             "cng_attrlist.T_CURR_USE_EQ, cng_attrlist.T_S_RESIDENT, cng_attrlist.T_FIELD_NAME, cng_attrlist.T_FIELD_CAPTION, " +
                             "cng_attrlist.T_FIELD_CAPTION_LAT, cng_attrlist.T_REG_MASK, cng_attrlist.T_BIC, cng_attrlist.T_IS_REQUIRED, " +
                             "cng_attrlist.T_EXAMPLE, cng_attrlist.T_COMMENT, cng_attrlist.T_COMMENT_LAT, cng_attrlist.T_MAX_LEN, " +
                             "cng_attrlist.T_SHORT_CAPTION, cng_attrlist.T_SHORT_CAPTION_LAT, cng_attrlist.T_INOUTEDIT, cng_attrlist.T_DATA_TYPE, " +
                             "cng_attrlist.T_VISIBLE, cng_attrlist.T_LANG " +
                      "from dcng_attrlist_dbt cng_attrlist " +
                      "where cng_attrlist.t_erased = 0 and " +
                            "cng_attrlist.t_grp_num = :grp_num" );

    cmd.addParam( "grp_num", RSDBP_IN, aGroupNum( i ) );

    cmd.execute( );

    i = i + 1;
  end;

  // Копирование справочника статусов документа в котором возможно изменение аттрибута
  i = 0;
  while ( i < ASize( aGroupNum ) )
    cmd = RsdCommand( "insert into dcng_attr_chng_tmp tmp ( tmp.T_ATTR_ID, tmp.T_STATUS ) " +
                      "select cng_attr_chng.T_ATTR_ID, cng_attr_chng.T_STATUS " +
                      "from dcng_attr_chng_dbt cng_attr_chng " +
                      "left join dcng_attrlist_dbt cng_attrlist on ( cng_attrlist.t_erased = 0 and cng_attrlist.t_grp_num = :grp_num ) " +
                      "where cng_attr_chng.t_attr_id = cng_attrlist.t_id" );

    cmd.addParam( "grp_num", RSDBP_IN, aGroupNum( i ) );

    cmd.execute( );

    i = i + 1;
  end;

  // Копирование справочника ограничения на суммы отправляемых переводов -
  if ( id > 0 )
    cmd = RsdCommand( "insert into dcng_min_max_tmp tmp ( tmp.T_ID, tmp.T_ERASED, tmp.T_BANK_ID, tmp.T_CURR_CODE, tmp.T_MIN_SUM, tmp.T_MAX_SUM ) " +
                      "select cng_min_max.T_ID, cng_min_max.T_ERASED, cng_min_max.T_BANK_ID, cng_min_max.T_CURR_CODE, cng_min_max.T_MIN_SUM, cng_min_max.T_MAX_SUM " +
                      "from dcng_min_max_dbt cng_min_max " +
                      "where cng_min_max.t_bank_id = :id" );

    cmd.addParam( "id", RSDBP_IN, id );

    cmd.execute( );
  end;

  if ( ( parent_id > 0 ) and ( parent_id != id ) )
    cmd = RsdCommand( "insert into dcng_min_max_tmp tmp ( tmp.T_ID, tmp.T_ERASED, tmp.T_BANK_ID, tmp.T_CURR_CODE, tmp.T_MIN_SUM, tmp.T_MAX_SUM ) " +
                      "select cng_min_max.T_ID, cng_min_max.T_ERASED, cng_min_max.T_BANK_ID, cng_min_max.T_CURR_CODE, cng_min_max.T_MIN_SUM, cng_min_max.T_MAX_SUM " +
                      "from dcng_min_max_dbt cng_min_max " +
                      "where cng_min_max.t_bank_id = :parent_id" );

    cmd.addParam( "parent_id", RSDBP_IN, parent_id );

    cmd.execute( );
  end;

  cmd = RsdCommand( "insert into dcng_min_max_tmp tmp ( tmp.T_ID, tmp.T_ERASED, tmp.T_BANK_ID, tmp.T_CURR_CODE, tmp.T_MIN_SUM, tmp.T_MAX_SUM ) " +
                    "select cng_min_max.T_ID, cng_min_max.T_ERASED, cng_min_max.T_BANK_ID, cng_min_max.T_CURR_CODE, cng_min_max.T_MIN_SUM, cng_min_max.T_MAX_SUM " +
                    "from dcng_min_max_dbt cng_min_max " +
                    "where cng_min_max.t_bank_id = 0" );

  cmd.execute( );

  // Копирование справочника городов -------------------------------------
  if ( city_id > 0 )
    cmd = RsdCommand( "insert into dcng_city_tmp tmp ( tmp.T_ID, tmp.T_ERASED, tmp.T_CITY, tmp.T_CITY_LAT, tmp.T_COUNTRY, tmp.T_REGION, tmp.T_PP_CODE ) " +
                      "select cng_city.T_ID, cng_city.T_ERASED, cng_city.T_CITY, cng_city.T_CITY_LAT, cng_city.T_COUNTRY, cng_city.T_REGION, cng_city.T_PP_CODE " +
                      "from dcng_city_dbt cng_city " +
                      "where cng_city.t_id = :city_id" );

    cmd.addParam( "city_id", RSDBP_IN, city_id );

    cmd.execute( );
  end;

  // Копирование справочника валют ---------------------------------------
  if ( id > 0 )
    cmd = RsdCommand( "insert into dcng_currency_tmp tmp ( tmp.T_SUBJ_TYPE, tmp.T_SUBJ_CODE, tmp.T_IS_PAYMENT, tmp.T_CODE_CURRENCY ) " +
                      "select cng_currency.T_SUBJ_TYPE, cng_currency.T_SUBJ_CODE, cng_currency.T_IS_PAYMENT, cng_currency.T_CODE_CURRENCY " +
                      "from dcng_currency_dbt cng_currency " +
                      "where ( cng_currency.t_subj_code = :id and cng_currency.t_subj_type = 3 )" );

    cmd.addParam( "id", RSDBP_IN, id );

    cmd.execute( );
  end;

  if ( parent_id > 0 )
    cmd = RsdCommand( "insert into dcng_currency_tmp tmp ( tmp.T_SUBJ_TYPE, tmp.T_SUBJ_CODE, tmp.T_IS_PAYMENT, tmp.T_CODE_CURRENCY ) " +
                      "select cng_currency.T_SUBJ_TYPE, cng_currency.T_SUBJ_CODE, cng_currency.T_IS_PAYMENT, cng_currency.T_CODE_CURRENCY " +
                      "from dcng_currency_dbt cng_currency " +
                      "where ( cng_currency.t_subj_code = :parent_id and cng_currency.t_subj_type = 2 )" );

    cmd.addParam( "parent_id", RSDBP_IN, parent_id );

    cmd.execute( );
  end;

  if ( city_id > 0 )
    cmd = RsdCommand( "insert into dcng_currency_tmp tmp ( tmp.T_SUBJ_TYPE, tmp.T_SUBJ_CODE, tmp.T_IS_PAYMENT, tmp.T_CODE_CURRENCY ) " +
                      "select cng_currency.T_SUBJ_TYPE, cng_currency.T_SUBJ_CODE, cng_currency.T_IS_PAYMENT, cng_currency.T_CODE_CURRENCY " +
                      "from dcng_currency_dbt cng_currency " +
                      "where ( cng_currency.t_subj_code = :city_id and cng_currency.t_subj_type = 4 )" );

    cmd.addParam( "city_id", RSDBP_IN, city_id );

    cmd.execute( );

    cmd = RsdCommand( "insert into dcng_currency_tmp tmp ( tmp.T_SUBJ_TYPE, tmp.T_SUBJ_CODE, tmp.T_IS_PAYMENT, tmp.T_CODE_CURRENCY ) " +
                      "select cng_currency.T_SUBJ_TYPE, cng_currency.T_SUBJ_CODE, cng_currency.T_IS_PAYMENT, cng_currency.T_CODE_CURRENCY " +
                      "from dcng_currency_dbt cng_currency " +
                      "left join dcng_city_dbt cng_city on ( cng_city.t_id = :city_id ) " +
                      "where ( cng_currency.t_subj_code = cng_city.t_country and cng_currency.t_subj_type = 1 )" );

    cmd.addParam( "city_id", RSDBP_IN, city_id );

    cmd.execute( );
  end;

end;


/**************************************************************************\
|                                                                          |
\**************************************************************************/
macro GetRefData( pointCode )

  var cmd;
  var saveStatLine;
  var stat = true;

  pointCodeForRef = pointCode;

  saveStatLine = Message( " Копирование справочников во временные таблицы ..." );

  cmd = RsdCommand( "truncate table dcng_banks_tmp" );
  cmd.execute( );

  cmd = RsdCommand( "truncate table dcng_scitem_grp_tmp" );
  cmd.execute( );

  cmd = RsdCommand( "truncate table dcng_attr_grps_tmp" );
  cmd.execute( );

  cmd = RsdCommand( "truncate table dcng_attrlist_tmp" );
  cmd.execute( );

  cmd = RsdCommand( "truncate table dcng_attr_chng_tmp" );
  cmd.execute( );

  cmd = RsdCommand( "truncate table dcng_min_max_tmp" );
  cmd.execute( );

  cmd = RsdCommand( "truncate table dcng_city_tmp" );
  cmd.execute( );

  cmd = RsdCommand( "truncate table dcng_currency_tmp" );
  cmd.execute( );

  if ( stat )
    stat = ProcessTrn( 0, "GetRefDataTrnProc" );
  end;

  Message( saveStatLine );

  return stat;
end;
