/*
$Name:        rep_for_reconsilation_panel.mac
$Module:      
$Description: Отчет по сделкам с ЦБ в СОФР для целей реконсиляции. Панель
$Programmer:  Котов C.
*/
import "DlRepForm_h.mac", "globals.mac";

CONST PNFLD_COMTRAVR_CLIENT_CODE              = 0,       /* Клиент               */
      PNFLD_COMTRAVR_CLIENT_NAME              = 1,
      PNFLD_COMTRAVR_BEGINDATE                = 2,       /* Дата начала          */
      PNFLD_COMTRAVR_ENDDATE                  = 3;       /* Дата завершения      */

CLASS Dl_ComTrAvr_Form_Data()
  VAR 
  ClientCode,
  ClientName,
  BegDate,
  EndDate;

  ClientCode = -1;
  ClientName = -1;
  BegDate = {curdate};
  EndDate = {curdate};

END;

VAR DlComTrAvrRepFormData = Dl_ComTrAvr_Form_Data();

PRIVATE CONST
  H_CLIENT_CODE     = 101,
  H_PNFLD_OPERNUM   = 102;

PRIVATE MACRO DLUSR_FldProc_ClientContr( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT ):INTEGER
  var ClientID =  -1;
  var ServKind = TArray();

  ClientID = pThis.GetFieldValue( PNFLD_COMTRAVR_CLIENT_CODE );
  
  if( Cmd == DLG_INIT )
     if( FldRealValue == null )
        FldRealValue = -1;
     end;
     if( FldRealValue <= 0 )                           
        FldShowValue = STR_ALLVALUE;
     end;
  elif( (Cmd == DLG_KEY) AND (Key == KEY_SPACE) )
     FldRealValue = -1;
     FldShowValue = STR_ALLVALUE;
  elif( (Cmd == DLG_KEY) AND (Key == KEY_F3) AND
        (ClientID > 0) )
//     ServKind[ServKind.Size] = 1;
//     DL_ListSfContrByServKind( @FldShowValue, @FldRealValue, pThis.CurrentFldX(), pThis.CurrentFldY(), ClientID, ServKind ); 
  end;
  return CM_DEFAULT;
END;

PRIVATE MACRO Default( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT ):INTEGER
  if( Cmd == DLG_INIT )
    FldShowValue = FldRealValue;
  elif( Cmd == DLG_CHANGEVALUE ) /*значение поля было изменено*/
    FldRealValue = FldRealValue;
  end;
  return CM_DEFAULT;
END;
                    
CLASS (DL_CPanel) rep_for_reconsilation_Panel()

  PRIVATE MACRO Init()

     AddFieldProc( 0, PNFLD_COMTRAVR_CLIENT_CODE,              H_CLIENT_CODE,             @DL_FldProc_SecClient,      DlComTrAvrRepFormData.ClientCode);
     AddFieldProc( 0, PNFLD_COMTRAVR_CLIENT_NAME,              DL_PNFLD_CLIENT_NAME_OFBU, @Default,                   DlComTrAvrRepFormData.ClientName);
                                                                                         
     AddFieldProc( 0, PNFLD_COMTRAVR_BEGINDATE,                DL_PNFLD_BEGINDATE,        @DL_FldProc_BeginDate,      {curdate});
     AddFieldProc( 0, PNFLD_COMTRAVR_ENDDATE,                  DL_PNFLD_ENDDATE,          @DL_FldProc_EndDate,        {curdate});                 


  END;

  PRIVATE MACRO Check():BOOL
     return true;
  END;
  
  initDL_CPanel( "sp_rep.lbr", "CONS" );
 
END;

