-- Удаление невалидных объектов
BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE SHCHERBININSV.RSHB_RSI_SCLIMIT';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ошибка: '||SQLCODE||' - '||SQLERRM);
END;
/