/*********************************************************************
*  --------------------                                              *
*  R-Style Software Lab                                              *
*  --------------------                                              *
*  RS-Retail                                                         *
*  Эмитент                                                           *
*                                                                    *
*  Система автоматического обмена информацией между Эмитентом и      *
*  Процессинговым центром СберБанка в формате UniCard                *
*                                                                    *
*  Обработка входящего файла по транзакциям                          *
*                                                                    *
*  Лебедев С.В.                                                      *
*  19.02.99                                                          *
*********************************************************************/

import sb_c_trn;


/*********************************************************************
            Проверка имени выбранного файла для обработки
*********************************************************************/
macro CheckFileName

  var stat      = TRUE;
  var ErrorCode = NOERROR;
  var NumInYear;
  var NumFileForDay;
  var Year;
  var Str;
  var REC_NO;
  var BANK;
  var AGNCY;

  Message(" Проверка файла ...");
  /* Длина имени файла должна быть 12 */
  if (ErrorCode == NOERROR)
    if (StrLen(ShortNameTranFile < 12))
      ErrorCode = "10"; /* Ошибка в формате названия входного файла */
    end;
  end;
  /* Первые символы имени файла - идентификатор банка */
  if (ErrorCode == NOERROR)
    if (SubStr(ShortNameTranFile,1,StrLen(PosCode)) != PosCode)
      ErrorCode = "100"; /* Код идентификации банка в названии входного файла не верен */
    end;
  end;
  /* Расширение файла - число */
  if (ErrorCode == NOERROR)
    Str = SubStr(ShortNameTranFile,Index(ShortNameTranFile,".") + 1);
    if (NOT IsStringDigit(Str))
      ErrorCode = "10"; /* Ошибка в формате названия входного файла */
    else
      NumFileForDay = Int(Trim(str));
    end;
  end;
  /* Проверим соответствие первой строки и названия файла */
  if (ErrorCode == NOERROR)
    ReWind(TranFile);
    stat = Next(TranFile);
    if (NOT stat)
      ErrorCode = "13"; /* Ошибка при чтении записи входного файла */
    end;
    if (ErrorCode == NOERROR)
      REC_NO = Int(Trim(SubStr(TranFile.str,3,6)));
      if ((REC_NO != 1) OR (SubStr(TranFile.str,1,2) != TypeTitle))
        ErrorCode = "14"; /* Первая строка файла - не заголовок */
      end;
      if (ErrorCode == NOERROR)
        BANK = Int(Trim(SubStr(TranFile.str,9,2)));
        if (BANK != Int(CodeTB))
          ErrorCode = "15"; /* Код тербанка в записи не верен */
        end;
      end;
      if (ErrorCode == NOERROR)
        AGNCY = Int(Trim(SubStr(TranFile.str,15,4)));
        if (AGNCY != NumFileForDay)
          ErrorCode = "16"; /* Номер файла за день не соответствует в имени файла и заголовочной строке */
        end;
      end;
      if (ErrorCode == NOERROR)
        Year = Int(SubStr(TranFile.str,166,4));
        DateFile = Date(Int(SubStr(TranFile.str,162,2)),
                        Int(SubStr(TranFile.str,164,2)),
                        Year                       );
        if (DateFile - Date(1,1,Year) + 1 != NumInYear)
          ErrorCode = "17"; /* Дата создания файла в заголовочной части не соответствует имени файла */
        end;
      end;
    end;
  end;

  /* Есть ошибка - прекратить выполнение программы */
  if (ErrorCode == NOERROR)
    stat = TRUE;
  else
    stat = FALSE;
    [ #](NameError(ErrorCode,""));
  end;

  return stat;

end;

/*********************************************************************
                      Выбор файла для обработки
*********************************************************************/
macro ChooseAndOpenFile

  var PathName;
  var str;
  var stat;
  var Flag = TRUE;

  stat = FindPos();
  if (NOT stat)
    [ ];
    str = "Процессинговый центр с кодом " + PosCode + " не найден";
    [ #](str);
  else
    PathName = InputPath + ShortNameTranFile;
    stat = SelectFile(NameTranFile,PathName,"Выберите файл для обработки");
    if (NOT stat)
      [ ];
      [ Отказались от обработки файла транзакций];
    else
      NameTranFile = Trim(NameTranFile);
      ShortNameTranFile = NameTranFile;
      while (Flag)
        if (Index(ShortNameTranFile,"\\"))
          Flag = TRUE;
        else
          Flag = FALSE;
        end;
        if (Flag)
          ShortNameTranFile = SubStr(ShortNameTranFile,Index(ShortNameTranFile,"\\") + 1);
        end;
      end;
    end;
  end;

  if (stat)
    stat = Open(TranFile,NameTranFile);
    if (NOT stat)
      [ #](NameError("12",""));
    end;
  end;

  return stat;

end;


/*********************************************************************
**********************************************************************
                  Г Л А В Н А Я    П Р О Г Р А М М А
**********************************************************************
*********************************************************************/

  var stat, errmes="";

  /* Выбор входного файла */
  stat = ChooseAndOpenFile();
  /* Проверка ЭЦП */
  if ( CheckESignFile( NameTranFile, errmes, true ) )
    ;
  else
    stat = false;
  end;
  /* Проверка имени входного файла */
  if (stat)
/*    stat = CheckFileName();*/
  end;
  /* Проверяем правильность заполнения головника и хвостовика */
  if (stat)
    stat = CheckHeaderAndTailer();
  end;
  /* Проверим, обрабатывался ли выбранный файл ранее */
/*  if (stat)
    TestPrevWorkOperFile();
  end;*/
  /* Обработка файла транзакций */
  if (stat)
/*    stat = Write_To_Mail();
    if (stat)*/
      WorkWithTranFile();
/*      Write_X_To_Mail();
    end;*/
  end;

end;
