/******************************************************************************
  Проверка перед выполнением выдачи карты
******************************************************************************/
import RSD, sb_comm, alg_vars;

  file scCodif("sccodif") key 1;
  var cmd, rs;

  ALG_RESULT = ERR_RES;

  cmd = RsdCommand("select t_CardStateCode" 
                   " from dScCard_dbt where" 
                   " t_FNcash = ? and t_ContractID = ? and t_CurrentCntrCard = 'X'");

  cmd.addParam("t_FNcash", RsdBp_in);
  cmd.value("t_FNcash") = ALG_CARDCONTRACT.Branch;
  cmd.addParam("t_ContractID", RsdBp_in);
  cmd.value("t_ContractID") = ALG_CARDCONTRACT.ID;

  cmd.execute;
  rs = RsdRecordset(cmd); 
  if( rs.moveNext() )

    scCodif.codType = LogSC_CardS;
    scCodif.codCode = VCardState_OK;
    scCodif.psRef   = 0;
    if (GetEQ(scCodif))
      if ((rs.value(0) == scCodif.CodCode       ) OR
          (rs.value(0) == scCodif.SimilarCodCode) )
        ALG_RESULT = END_RES;
      else
        ALG_RESULT = OK_RES;
      end;
    end;

  end;

end;
