import RSD;

const K_ENTER   = 13;
const K_ESC     = 27;
const K_F5      = 319;

PRIVATE MACRO AddCol (ar,ind, fld, head, width, rdonly,  dp)
   ar.value (ind * 6)     = fld;
   ar.value (ind * 6 + 1) = head;
   ar.value (ind * 6 + 2) = width;
   ar.value (ind * 6 + 3 ) = rdonly;   // fldType
   ar.value (ind * 6 + 4 ) = dp;//   decPoint
   ar.value (ind * 6 + 5 ) = 0;   // reserv
END;

var shift = 0, kind = 0, {curdate}, cdate = {curdate}; /* ,cdate = date(9,1,2019); */

macro Scroll
   var sql, cmd, rs, col1, need = true,Column = TArray(),i, ColumnValue, ColumnName, NumColumns = 0;

   macro EvProc(rs, cmd, id, key)
     var  CM_DEFAULT = null;
    
     if (cmd == DLG_INIT)
       EndAction;
     elif (cmd == DLG_KEY)
        if (key == K_F5)
          if (getDate(cdate, "Укажите дату:"))
             need = true;
             return CM_SELECT;
          end;
        elif (key == K_ESC)
          return 2;
        end;
     end;
     return CM_DEFAULT;
  end;

   col1 = TArray;   

   AddCol (col1, 0, "bracc",    "Счет",    20,  true);
   AddCol (col1, 1, "sinrest",  "Исходящий остаток в СОФР", 20, true, 2);
   AddCol (col1, 2, "cinrest",  "Исходящий остаток в Диасофт", 20, true, 2);
   AddCol (col1, 3, "dev",      "Расхождение",       20, true, 2);

   while (need)
      need = false;
      BegAction(0, "Ждите, формируется список ...", false);
      sql =

"select s.bracc\n" +
"      , nvl(s.inrest, 0) sinrest\n" + 
"      , nvl(c.inrest, 0) cinrest\n" + 
"      , nvl(s.inrest, 0) - nvl(c.inrest, 0) dev\n" + 
"  from (\n" + 
"select stbl.*\n" + 
"  from (select ra.t_account bracc, NVL(rc.t_rest, 0) inrest, fi.t_ccy cur\n" + 
"  from daccount_dbt ra\n" + 
"  inner join dfininstr_dbt fi\n" + 
"     on (fi.t_fiid = ra.t_code_currency)\n" + 
"  left join drestdate_dbt rc\n" + 
"    on (rc.t_accountid = ra.t_accountid  and rc.t_restcurrency =  ra.t_code_currency and rc.t_restdate = (select max(t_restdate) from drestdate_dbt where t_accountid = ra.t_accountid and t_restcurrency = ra.t_code_currency and t_restdate <= to_date(:cdate, 'dd.mm.yyyy')))\n" + 
"where ra.t_account like '306%'\n" + 
"   and (ra.t_nameaccount <> chr(1)) and (ra.t_open_close = chr(0) or  (ra.t_close_date >= to_date(:cdate, 'dd.mm.yyyy')))\n" + 
") stbl) s\n" + 
"  full join\n" + 
" (select ctbl.*\n" + 
" from (select bracc, to_number(replace(inrest, ',', '.'), '999999999999999999999999.999999999999999') inrest, cur\n" + 
" from dias_bracc da\n" + 
" where rdate = to_date(:cdate,'dd.mm.yyyy')\n" + 
") ctbl ) c\n" + 
"  on (s.bracc = c.bracc)\n" + 
// "where (s.bracc is not null and c.bracc is not null)\n" + 
// "where (s.bracc is not null)\n" + 
// "  and (nvl(s.inrest, 0) <> nvl(c.inrest, 0))\n" + 
"  where (nvl(s.inrest, 0) <> nvl(c.inrest, 0))\n" + 
"  order by s.bracc";

      cmd = RSDCommand(sql);
      cmd.AddParam("cdate1", RSDBP_IN, strsubst(string(cdate), " ", "0"));
      cmd.AddParam("cdate2", RSDBP_IN, strsubst(string(cdate), " ", "0"));
      cmd.AddParam("cdate3", RSDBP_IN, strsubst(string(cdate), " ", "0"));
      rs = RSDRecordset(cmd , null, RSDVAL_STATIC );


      if (RunScroll (rs,4, col1, "test" ,"EvProc","Сверка остатков по брокерских счетам за " + strsubst(string(cdate), " ", "0"), "F5 - Изменить дату  ESC - Выход", true, 1, 1))
       //   return rs1;
      end;
   end;

return null;

end;
if (getDate(cdate, "Укажите дату:"))
  Scroll;
end;
exit(1);