/*
$Name:        load_Sub_Categ.mac
$Module:      Ценные бумаги
$Description: Загрузка значений категории "Сегмент корпоративного бизнеса"
*/

import activex, or_rep_h, globals, func_lib;

   var InputDir, FullNameFile, ExtName, DirName, errmsg, err = 0, suc = 0, count = 0, stat = 0;
   var Sheet, fcol = 1, frow = 1, row;
   //DEF-28868, пересечение категорий с категориями тестов НКИ
   const CATEG_PARTY_SEGM = 115; // DEF-28868, пересечение категорий с категориями тестов НКИ

   var datafilemask;
   var List;
   var CurFileName = "", v_state = true, inn, categ, partyid;
   var TermPath = GetCurDir(true) + "\\TxtFile";
  /*Выбираем файл для обработки*/
  if(not SelectFile(FullNameFile, "*.xls*", "Выберите файл для загрузки", 0, true))
    errmsg = "Отказ от загрузки";
    return false;
  end;
  splitfile(FullNameFile, CurFileName, ExtName);
  CurFileName = CurFileName + ExtName;
  DirName = substr(FullNameFile, 1, index(FullNameFile, CurFileName) - 1);

   if (not copyfile("$" + DirName + CurFileName, "$" + TermPath + "\\" + CurFileName) )
      MsgBox("Ошибка при передаче файла на терминал");
   end;

   /*Открываем файл*/
   BegAction(1, "Обработка файла \"" + TermPath + "\\" + FileName + "\". Ждите...");

   if(not OpenExcelFile(CurFileName, false, true, TermPath))
      MsgBox("Ошибка открытия файла \"" + TermPath + "\\" + FileName + "\"");
      EndAction(1);
      return 0;
   end;
   sheet = ExcelApplication.Sheets(1);

   /*Ищем первую строку*/
      if(valtype(sheet.cells(frow, 1).value) == V_UNDEF)
         MsgBox("В файле с данными первая ячейка пуста, загрузка прерывается");
         exit(1);
      end;
   row = frow;
   //Бежим по файлу
   InitProgress(-1);
   while (v_state) 
      if (valtype(sheet.cells(row, 1).value) == V_UNDEF)
         v_state = false;
         continue;
      else
         Inn = string(sheet.cells(row, 1).value:0:0);
         categ = int(sheet.cells(row, 2).value);
      end;
      Partyid = GetPartyID_byPartyCode(16, Inn);
      If( (categ <1) OR (categ >3))
         Println("Ошибка. Не верное значение категории. По коду ИНН = " + Inn + " указано значение  = " + categ + ". Значение же должно быть в диапазоне от 1 до 3 " );
         err = err +1;
         row = row + 1;
         continue;
      end;
      If(Partyid>0)
         if( ( not DisconnectObjAttr(OBJTYPE_PARTY,  string(Partyid:o:10), CATEG_PARTY_SEGM) ) OR
            ( not ConnectObjAttr(stat, OBJTYPE_PARTY, string(Partyid:o:10), CATEG_PARTY_SEGM, categ, null, null, {curdate}) ))
             println( "Ошибка при установке Категории для субъекта с ИНН = " + inn );
         else
            suc = suc + 1;
         end;
      else
         Println("Ошибка определения субъекта по коду ИНН = " + Inn);
         err = err +1;
      end;


      row = row + 1;
  end;
  RemProgress();
  row = row-1;
  Println("Всего обработано строк = " + row);
  Println("Успешно = " + suc);
  Println("С ошибками = " + err);

  ExcelApplication.ActiveWorkbook.Close;

