DECLARE
BEGIN
  INSERT INTO DOPRKDOC_DBT(T_DOCKIND,T_PRIMARY,T_MODE,T_NAME,T_DBFILE,T_MACRONAME,T_CLASSMACRONAME,T_CLASSNAME,T_PARENTDOCKIND,T_MAXPHASE,T_PROGRAM,T_ORIGIN)
  VALUES(4652,'X',0,'Операция замены кодов доходов','nptxop.dbt',CHR(1),CHR(1),CHR(1),0,0,CHR(0),0);

  INSERT INTO DOPRKDATE_DBT(T_DATEKINDID , T_DOCKIND , T_NUMBERDATE , T_NAMEDATE , T_ELIMINATED)
  VALUES(465200000,4652,0,'Дата операции',CHR(0));
  
  INSERT INTO DOPRKDATE_DBT(T_DATEKINDID , T_DOCKIND , T_NUMBERDATE , T_NAMEDATE , T_ELIMINATED)
  VALUES(465299999,4652,-1,'Дата цепочки',CHR(0));

  INSERT INTO DOPRSTKND_DBT(T_STATUSKINDID,T_CODE,T_NAME,T_DOCKIND,T_SORT,T_ELIMINATED)
  VALUES(46521,'ДО','Документооборот',4652,0,CHR(0));

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(46521,1,'Открыт',CHR(0));

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(46521,2,'Закрыт',CHR(0));

  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(204801,'Замена кодов',4652,0,CHR(0),CHR(1),3);

  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(204801,46521,1,CHR(0));

  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(204801,46521,2,CHR(0));

  INSERT INTO DOPRKSTEP_DBT(T_DOCKIND,T_KIND_ACTION,T_NAME,T_ISALLOWFOROPER,T_OPERORGROUP,T_RESERVE)
  VALUES(4652,1,'Пользовательский шаг',0,CHR(0),CHR(1));
  
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(204801,5,1,0,0,CHR(0),0,CHR(0),0,0,'nptxchangecode005.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Инициализация',465200000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(204801,10,1,0,0,CHR(0),0,'З',0,0,'nptxchangecode010.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Откат прежних расчетов',465200000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(204801,15,1,0,0,CHR(0),0,'О',0,0,'nptxchangecode015.mac',CHR(1),'nptxchangecode015.mac',CHR(0),CHR(0),'Подготовка данных по выплатам купона',465200000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(204801,20,1,0,0,CHR(0),0,'О',0,0,'nptxchangecode020.mac',CHR(1),'nptxchangecode020.mac',CHR(0),CHR(0),'Формирование ндр',465200000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);
  
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(204801,50,1,0,0,CHR(0),0,'О',0,0,'nptxchangecode050.mac',CHR(1),'nptxchangecode050.mac',CHR(0),CHR(0),'Завершение операции',465200000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);
  
  INSERT INTO DOPRKOPER_DBT(T_KIND_OPERATION,T_DOCKIND,T_NOTINUSE,T_INITMACRO,T_SYSTYPES,T_NAME,T_SHORTNAME,T_UPGRADE,T_ISMAINTANANCE,T_PARENT,T_VERSION,T_MASSOPRSTART)
  VALUES(2048,4652,CHR(0),CHR(1),CHR(1),'Операция замены кодов доходов','ОПЗМКОД',CHR(0),CHR(0),0,CHR(1),CHR(0));

  INSERT INTO DOPRINIST_DBT(T_KIND_OPERATION,T_STATUSKINDID,T_NUMVALUE)
  VALUES(2048,46521,1);

END;
/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN

    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,2048,204801,1,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,46521,1,0);
END;
/
