--Обнвление полей с NULL
DECLARE
BEGIN
  UPDATE DNPTXOP_DBT
     SET T_PAYMEDICAL = CHR(0)
   WHERE T_PAYMEDICAL IS NULL;

  UPDATE DNPTXOP_DBT
     SET T_RECEIVER = -1
   WHERE T_RECEIVER IS NULL;
END;
/