CREATE TABLE DNPTXCODECHANGE_DBT 
(
  T_ID              NUMBER(10),
  T_OPERATIONID     NUMBER(10),
  T_OPERDATE        DATE,
  T_SALE            CHAR(1),
  T_CHANGECODE      CHAR(1),
  T_CLIENTID        NUMBER(10),
  T_CONTRACTID      NUMBER(10),
  T_TAXPERIOD       NUMBER(5),
  T_BEGINDATE       DATE,
  T_ENDDATE         DATE,
  T_RECORDPAYMENTID VARCHAR2(20),
  T_PAYMENTDATE     DATE,
  T_PAYRECEIVEDDATE DATE,
  T_FIID            NUMBER(10),
  T_ISIN            VARCHAR2(40),
  T_ACCOUNTNUMBER   VARCHAR2(25),
  T_ISCIRC          NUMBER(5),
  T_ISSUEDDATE      DATE,
  T_GROUP           NUMBER(10),
  T_CODE_BEFOR      NUMBER(10),
  T_CODE_AFTER      NUMBER(10),
  T_ISCHANGEFLAG    CHAR(1),
  T_TAXBASE         NUMBER(32,12),
  T_UNKD            NUMBER(32,12),
  T_SUM_FOR_CHANGE  NUMBER(32,12),
  T_PAYMENTRECORDSNOBID VARCHAR2(50),
  T_RECORDSNOBID    VARCHAR2(50),
  T_INCDATE         DATE,
  T_INCTIME         DATE,
  T_NOBAMOUNT       NUMBER(32,12),
  T_TAXRATE         NUMBER(10,0),
  T_KBK_BEFOR       VARCHAR2(30),
  T_KBK_AFTER       VARCHAR2(30),
  T_ERRORTEXT       VARCHAR2(250),
  T_IDDCDRECORDS    VARCHAR2(20)
)
/


CREATE UNIQUE INDEX DNPTXCODECHANGE_DBT_IDX0 ON DNPTXCODECHANGE_DBT
(T_ID)
/


CREATE SEQUENCE DNPTXCODECHANGE_DBT_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/


CREATE OR REPLACE TRIGGER DNPTXCODECHANGE_DBT_T0_AINC 
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXCODECHANGE_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXCODECHANGE_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXCODECHANGE_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
