
CREATE TABLE DNPTXGENREPLACEOP_DBT
(
    T_ID            NUMBER (10),
    T_PARTYID       NUMBER (10),
    T_SESSIONID     VARCHAR2 (200),
    T_STATE         NUMBER (5),
    T_CFTID         VARCHAR2 (20),
    T_PACKNUM       NUMBER (10),
    T_CONTRID       NUMBER (10),
    T_IISCONTRID    NUMBER (10),
    T_OPRDATE       DATE,
    T_ERROR         VARCHAR2 (200),
    T_GENOPRCODE    VARCHAR2 (25)
)
/

CREATE UNIQUE INDEX DNPTXGENREPLACEOP_DBT_IDX0
    ON DNPTXGENREPLACEOP_DBT (T_ID)
 /

CREATE INDEX DNPTXGENREPLACEOP_DBT_IDX1
    ON DNPTXGENREPLACEOP_DBT (T_SESSIONID, T_PACKNUM, T_STATE)
 /

CREATE SEQUENCE DNPTXGENREPLACEOP_DBT_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXGENREPLACEOP_DBT_T1_AINC
    BEFORE INSERT OR UPDATE OF T_ID
    ON DNPTXGENREPLACEOP_DBT
    FOR EACH ROW
DECLARE
    V_ID   INTEGER;
BEGIN
    IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL)
    THEN
        SELECT DNPTXGENREPLACEOP_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
    ELSE
        SELECT LAST_NUMBER
          INTO V_ID
          FROM USER_SEQUENCES
         WHERE UPPER (SEQUENCE_NAME) = UPPER ('DNPTXGENREPLACEOP_DBT');

        IF :NEW.T_ID >= V_ID
        THEN
            RAISE DUP_VAL_ON_INDEX;
        END IF;
    END IF;
END;
/