CREATE OR REPLACE TRIGGER DEMAIL_NOTIFY_DBT_ADDHIST_USR
  AFTER UPDATE ON DEMAIL_NOTIFY_DBT FOR EACH ROW
DECLARE
  v_id number(5);
BEGIN
 INSERT INTO DEMAIL_NOTIFY_HIST_DBT 
 (
  T_ID,
  T_SID,
  T_OSUSER,
  T_ENID,
  T_HEAD,
  T_DATEADD,
  T_DATESEND,
  T_ISSEND,
  T_ERROR,
  T_EMAIL,
  T_VERSION,
  T_TEXT,
  T_EMAIL_CC,
  T_EMAIL_BCC,
  T_ISHTML
 )
VALUES ( /* T_ID */0,
 SYS_CONTEXT ('USERENV', 'SID'),
 SYS_CONTEXT ('USERENV', 'OS_USER'),
 :old.T_ID,
 :old.T_HEAD ,
 :old.T_DATEADD ,
 :old.T_DATESEND ,
 :old.T_ISSEND ,
 :old.T_ERROR ,
 :old.T_EMAIL ,
 :old.T_VERSION ,
 :old.t_text ,
 :old.T_EMAIL_CC ,
 :old.T_EMAIL_BCC ,
 :old.T_ISHTML
);
END;
/