DROP TABLE ASS_ACCOUNTDEAL CASCADE CONSTRAINTS;

CREATE TABLE ASS_ACCOUNTDEAL
(
  DT                     VARCHAR2(10 BYTE),
  SYSMOMENT              VARCHAR2(20 BYTE),
  ACCOUNT_CODE           VARCHAR2(250 BYTE),
  ROLEACCOUNT_DEAL_CODE  VARCHAR2(100 BYTE),
  DEAL_CODE              VARCHAR2(100 BYTE),
  REC_STATUS             VARCHAR2(2 BYTE),
  STG_FCODE              VARCHAR2(4 BYTE),
  STG_PACK_ID            DATE,
  EXT_FILE               VARCHAR2(300 BYTE)     DEFAULT 'AAD_BISQUIT#-1#B0',
  STG_PK_HASH            VARCHAR2(32 BYTE),
  STG_ROW_HASH           VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE ASS_CARRYDEAL CASCADE CONSTRAINTS;

CREATE TABLE ASS_CARRYDEAL
(
  DT            VARCHAR2(10 BYTE),
  SYSMOMENT     VARCHAR2(20 BYTE),
  CARRY_CODE    VARCHAR2(250 BYTE),
  DEAL_CODE     VARCHAR2(100 BYTE),
  REC_STATUS    VARCHAR2(2 BYTE),
  STG_FCODE     VARCHAR2(4 BYTE),
  STG_PACK_ID   DATE,
  EXT_FILE      VARCHAR2(300 BYTE)              DEFAULT 'ACD_BISQUIT#-1#B0',
  STG_PK_HASH   VARCHAR2(32 BYTE),
  STG_ROW_HASH  VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE ASS_DEAL_CAT_VAL CASCADE CONSTRAINTS;

CREATE TABLE ASS_DEAL_CAT_VAL
(
  DT                          VARCHAR2(10 BYTE) NOT NULL,
  SYSMOMENT                   VARCHAR2(20 BYTE) NOT NULL,
  DEAL_CODE                   VARCHAR2(100 BYTE) NOT NULL,
  DEAL_CAT_VAL_CODE           VARCHAR2(100 BYTE) NOT NULL,
  DEAL_CAT_VAL_CODE_DEAL_CAT  VARCHAR2(100 BYTE) NOT NULL,
  REC_STATUS                  VARCHAR2(2 BYTE)  NOT NULL,
  STG_FCODE                   VARCHAR2(4 BYTE),
  STG_PACK_ID                 DATE,
  EXT_FILE                    VARCHAR2(300 BYTE) DEFAULT 'ADCV_BISQUIT#-1#B0',
  STG_PK_HASH                 VARCHAR2(32 BYTE),
  STG_ROW_HASH                VARCHAR2(32 BYTE),
  STG_ISTEMP                  NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE ASS_DEAL_MIGRATION CASCADE CONSTRAINTS;

CREATE TABLE ASS_DEAL_MIGRATION
(
  DT                              VARCHAR2(10 BYTE),
  SYSMOMENT                       VARCHAR2(20 BYTE),
  DEAL_CUR_CODE                   VARCHAR2(100 BYTE),
  DEAL_PREV_CODE                  VARCHAR2(100 BYTE),
  DEPARTMENT_CUR_CODE_DEPARTMENT  VARCHAR2(30 BYTE),
  DEPARTMENT_PREV_CODE_DEPARTMEN  VARCHAR2(30 BYTE),
  REC_STATUS                      VARCHAR2(2 BYTE),
  EXT_FILE                        VARCHAR2(300 BYTE),
  MIGRATION_TYPE                  VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE ASS_FCT_DEAL CASCADE CONSTRAINTS;

CREATE TABLE ASS_FCT_DEAL
(
  DT                  VARCHAR2(10 BYTE),
  SYSMOMENT           VARCHAR2(20 BYTE),
  PARENT_CODE         VARCHAR2(100 BYTE),
  CHILD_CODE          VARCHAR2(100 BYTE),
  TYPE_DEAL_REL_CODE  VARCHAR2(100 BYTE),
  REC_STATUS          VARCHAR2(2 BYTE),
  STG_FCODE           VARCHAR2(4 BYTE),
  STG_PACK_ID         DATE,
  EXT_FILE            VARCHAR2(300 BYTE)        DEFAULT 'AFD_BISQUIT#-1#B0',
  STG_PK_HASH         VARCHAR2(32 BYTE),
  STG_ROW_HASH        VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE ASS_HALFCARRYDEAL CASCADE CONSTRAINTS;

CREATE TABLE ASS_HALFCARRYDEAL
(
  DT              VARCHAR2(10 BYTE)             NOT NULL,
  SYSMOMENT       VARCHAR2(20 BYTE)             NOT NULL,
  DEAL_CODE       VARCHAR2(100 BYTE)            NOT NULL,
  HALFCARRY_CODE  VARCHAR2(250 BYTE)            NOT NULL,
  REC_STATUS      VARCHAR2(2 BYTE)              NOT NULL,
  STG_FCODE       VARCHAR2(4 BYTE),
  STG_PACK_ID     DATE,
  EXT_FILE        VARCHAR2(300 BYTE)            DEFAULT 'AHD_BISQUIT#-1#B0',
  STG_PK_HASH     VARCHAR2(32 BYTE),
  STG_ROW_HASH    VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE DET_SUBJECT_ROLEDEAL CASCADE CONSTRAINTS;

CREATE TABLE DET_SUBJECT_ROLEDEAL
(
  CODE            VARCHAR2(100 BYTE),
  NAME            VARCHAR2(250 BYTE),
  RSDH_ROLE_CODE  VARCHAR2(100 BYTE),
  DT              VARCHAR2(10 BYTE),
  SYSMOMENT       VARCHAR2(20 BYTE),
  REC_STATUS      VARCHAR2(2 BYTE),
  EXT_FILE        VARCHAR2(300 BYTE),
  STG_FCODE       VARCHAR2(4 BYTE),
  STG_PACK_ID     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE DET_SYSTEM CASCADE CONSTRAINTS;

CREATE TABLE DET_SYSTEM
(
  SYSTEM_CODE  VARCHAR2(250 BYTE),
  SYSTEM_NAME  VARCHAR2(250 BYTE),
  RANK         VARCHAR2(4 BYTE),
  DT           VARCHAR2(10 BYTE),
  SYSMOMENT    VARCHAR2(20 BYTE),
  REC_STATUS   VARCHAR2(2 BYTE),
  EXT_FILE     VARCHAR2(300 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_ATTR_SCHEDULE CASCADE CONSTRAINTS;

CREATE TABLE FCT_ATTR_SCHEDULE
(
  TYPESCH                  VARCHAR2(3 BYTE),
  PERIODICITY              VARCHAR2(30 BYTE),
  COUNT_PERIOD             VARCHAR2(5 BYTE),
  DAY_PAY                  VARCHAR2(3 BYTE),
  GRACE_PERIODICITY        VARCHAR2(3 BYTE),
  GRACE_COUNT_PERIOD       VARCHAR2(5 BYTE),
  SUM_REPAY                VARCHAR2(26 BYTE),
  DT_OPEN_PER              VARCHAR2(10 BYTE),
  DT_CLOSE_PER             VARCHAR2(10 BYTE),
  DT                       VARCHAR2(10 BYTE),
  SYSMOMENT                VARCHAR2(20 BYTE),
  IS_WORKDAY               VARCHAR2(2 BYTE),
  DEAL_CODE                VARCHAR2(100 BYTE),
  TYPEREPAY_CODE           VARCHAR2(250 BYTE),
  EXTERNAL_TYPEREPAY_CODE  VARCHAR2(250 BYTE),
  REC_STATUS               VARCHAR2(2 BYTE),
  EXT_FILE                 VARCHAR2(300 BYTE),
  MONTH_PAY                VARCHAR2(2 BYTE),
  STG_FCODE                VARCHAR2(4 BYTE),
  STG_PACK_ID              DATE,
  STG_PK_HASH              VARCHAR2(32 BYTE),
  STG_ROW_HASH             VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_DEAL CASCADE CONSTRAINTS;

CREATE TABLE FCT_DEAL
(
  BEGINDATE        VARCHAR2(10 BYTE),
  CODE             VARCHAR2(100 BYTE),
  DEALTYPE         VARCHAR2(3 BYTE),
  DOCNUM           VARCHAR2(100 BYTE),
  DT               VARCHAR2(10 BYTE),
  ENDDATE          VARCHAR2(10 BYTE),
  IS_INTERIOR      VARCHAR2(2 BYTE),
  NOTE             VARCHAR2(4000 BYTE),
  SYSMOMENT        VARCHAR2(20 BYTE),
  SUBJECT_CODE     VARCHAR2(250 BYTE),
  DEPARTMENT_CODE  VARCHAR2(30 BYTE),
  REC_STATUS       VARCHAR2(2 BYTE),
  EXT_FILE         VARCHAR2(300 BYTE),
  STG_FCODE        VARCHAR2(4 BYTE),
  STG_PACK_ID      DATE,
  STG_PK_HASH      VARCHAR2(32 BYTE),
  STG_ROW_HASH     VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_DEAL_CARRY CASCADE CONSTRAINTS;

CREATE TABLE FCT_DEAL_CARRY
(
  CODE              VARCHAR2(100 BYTE)          NOT NULL,
  DOCNUM            VARCHAR2(50 BYTE),
  GROUND            VARCHAR2(256 BYTE),
  VALUE             VARCHAR2(26 BYTE)           NOT NULL,
  VALUE_NAT         VARCHAR2(50 BYTE)           NOT NULL,
  DT                VARCHAR2(10 BYTE)           NOT NULL,
  SYSMOMENT         VARCHAR2(20 BYTE)           NOT NULL,
  ACCOUNT_DBT_CODE  VARCHAR2(250 BYTE)          NOT NULL,
  ACCOUNT_CRD_CODE  VARCHAR2(250 BYTE)          NOT NULL,
  REC_STATUS        VARCHAR2(2 BYTE)            NOT NULL,
  EXT_FILE          VARCHAR2(300 BYTE)          NOT NULL,
  STG_FCODE         VARCHAR2(4 BYTE),
  STG_PACK_ID       DATE,
  INFO              VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_DEAL_DMP CASCADE CONSTRAINTS;

CREATE TABLE FCT_DEAL_DMP
(
  BEGINDATE        VARCHAR2(10 BYTE),
  CODE             VARCHAR2(100 BYTE),
  DEALTYPE         VARCHAR2(3 BYTE),
  DOCNUM           VARCHAR2(100 BYTE),
  DT               VARCHAR2(10 BYTE),
  ENDDATE          VARCHAR2(10 BYTE),
  IS_INTERIOR      VARCHAR2(2 BYTE),
  NOTE             VARCHAR2(4000 BYTE),
  SYSMOMENT        VARCHAR2(20 BYTE),
  SUBJECT_CODE     VARCHAR2(250 BYTE),
  DEPARTMENT_CODE  VARCHAR2(30 BYTE),
  REC_STATUS       VARCHAR2(2 BYTE),
  EXT_FILE         VARCHAR2(300 BYTE),
  STG_FCODE        VARCHAR2(4 BYTE),
  STG_PACK_ID      DATE,
  STG_PK_HASH      VARCHAR2(32 BYTE),
  STG_ROW_HASH     VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_DEAL_INDICATOR CASCADE CONSTRAINTS;

CREATE TABLE FCT_DEAL_INDICATOR
(
  NUMBER_VALUE            VARCHAR2(31 BYTE),
  DATE_VALUE              VARCHAR2(10 BYTE),
  STRING_VALUE            VARCHAR2(256 BYTE),
  DT                      VARCHAR2(10 BYTE),
  SYSMOMENT               VARCHAR2(20 BYTE),
  DEAL_CODE               VARCHAR2(100 BYTE),
  DEAL_ATTR_CODE          VARCHAR2(100 BYTE),
  CURRENCY_CURR_CODE_TXT  VARCHAR2(3 BYTE),
  MEASUREMENT_UNIT_CODE   VARCHAR2(100 BYTE),
  REC_STATUS              VARCHAR2(2 BYTE),
  EXT_FILE                VARCHAR2(300 BYTE),
  STG_FCODE               VARCHAR2(4 BYTE),
  STG_PACK_ID             DATE,
  STG_PK_HASH             VARCHAR2(32 BYTE),
  STG_ROW_HASH            VARCHAR2(32 BYTE),
  STG_ISTEMP              NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_DEALRISK CASCADE CONSTRAINTS;

CREATE TABLE FCT_DEALRISK
(
  DT                     VARCHAR2(10 BYTE),
  GROUND                 VARCHAR2(250 BYTE),
  RESERVE_RATE           VARCHAR2(18 BYTE),
  SYSMOMENT              VARCHAR2(20 BYTE),
  DEAL_CODE              VARCHAR2(100 BYTE),
  RISKCAT_CODE           VARCHAR2(250 BYTE),
  RISKCAT_CODE_TYPERISK  VARCHAR2(250 BYTE),
  REC_STATUS             VARCHAR2(2 BYTE),
  EXT_FILE               VARCHAR2(300 BYTE),
  STG_FCODE              VARCHAR2(4 BYTE),
  STG_PACK_ID            DATE,
  STG_PK_HASH            VARCHAR2(32 BYTE),
  STG_ROW_HASH           VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_DEAL_RST CASCADE CONSTRAINTS;

CREATE TABLE FCT_DEAL_RST
(
  DT               VARCHAR2(10 BYTE),
  SYSMOMENT        VARCHAR2(20 BYTE),
  VAL_CRD_ACC      VARCHAR2(26 BYTE),
  VAL_CRD_AMT      VARCHAR2(26 BYTE),
  VAL_CRD_CUR      VARCHAR2(26 BYTE),
  VAL_CRD_NAT      VARCHAR2(50 BYTE),
  VAL_CRD_RUR      VARCHAR2(26 BYTE),
  VAL_DBT_ACC      VARCHAR2(26 BYTE),
  VAL_DBT_AMT      VARCHAR2(26 BYTE),
  VAL_DBT_CUR      VARCHAR2(26 BYTE),
  VAL_DBT_NAT      VARCHAR2(50 BYTE),
  VAL_DBT_RUR      VARCHAR2(26 BYTE),
  VAL_RST_ACC_IN   VARCHAR2(26 BYTE),
  VAL_RST_ACC_OUT  VARCHAR2(26 BYTE),
  VAL_RST_AMT_IN   VARCHAR2(26 BYTE),
  VAL_RST_AMT_OUT  VARCHAR2(26 BYTE),
  VAL_RST_CUR_IN   VARCHAR2(26 BYTE),
  VAL_RST_CUR_OUT  VARCHAR2(26 BYTE),
  VAL_RST_NAT_IN   VARCHAR2(50 BYTE),
  VAL_RST_NAT_OUT  VARCHAR2(50 BYTE),
  VAL_RST_RUR_IN   VARCHAR2(26 BYTE),
  VAL_RST_RUR_OUT  VARCHAR2(26 BYTE),
  DEAL_CODE        VARCHAR2(100 BYTE),
  ACCOUNT_CODE     VARCHAR2(250 BYTE),
  REC_STATUS       VARCHAR2(2 BYTE),
  EXT_FILE         VARCHAR2(300 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_DM_CARRY_ASS CASCADE CONSTRAINTS;

CREATE TABLE FCT_DM_CARRY_ASS
(
  CODE             VARCHAR2(100 BYTE)           NOT NULL,
  DT               VARCHAR2(10 BYTE)            NOT NULL,
  SYSMOMENT        VARCHAR2(20 BYTE)            NOT NULL,
  DEAL_CARRY_CODE  VARCHAR2(100 BYTE)           NOT NULL,
  DEAL_CODE        VARCHAR2(100 BYTE)           NOT NULL,
  REC_STATUS       VARCHAR2(2 BYTE)             NOT NULL,
  EXT_FILE         VARCHAR2(300 BYTE)           NOT NULL,
  STG_FCODE        VARCHAR2(4 BYTE),
  STG_PACK_ID      DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_MBKCREDEAL CASCADE CONSTRAINTS;

CREATE TABLE FCT_MBKCREDEAL
(
  DEAL_CODE     VARCHAR2(100 BYTE),
  FINSTR_CODE   VARCHAR2(30 BYTE),
  DEALTYPEMBK   VARCHAR2(1 BYTE),
  DEALSUM       VARCHAR2(25 BYTE),
  TYPESYND      VARCHAR2(1 BYTE),
  SYSMOMENT     VARCHAR2(20 BYTE),
  REC_STATUS    VARCHAR2(2 BYTE),
  EXT_FILE      VARCHAR2(300 BYTE),
  STG_FCODE     VARCHAR2(4 BYTE),
  STG_PACK_ID   DATE,
  STG_PK_HASH   VARCHAR2(32 BYTE),
  STG_ROW_HASH  VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_MBKDEPDEAL CASCADE CONSTRAINTS;

CREATE TABLE FCT_MBKDEPDEAL
(
  DEALSUM       VARCHAR2(25 BYTE),
  SYSMOMENT     VARCHAR2(20 BYTE),
  DEALTYPEMBK   VARCHAR2(1 BYTE),
  DEAL_CODE     VARCHAR2(100 BYTE),
  FINSTR_CODE   VARCHAR2(30 BYTE),
  REC_STATUS    VARCHAR2(2 BYTE),
  EXT_FILE      VARCHAR2(300 BYTE),
  STG_FCODE     VARCHAR2(4 BYTE),
  STG_PACK_ID   DATE,
  STG_PK_HASH   VARCHAR2(32 BYTE),
  STG_ROW_HASH  VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_PROCRATE_DEAL CASCADE CONSTRAINTS;

CREATE TABLE FCT_PROCRATE_DEAL
(
  PROCSUM               VARCHAR2(28 BYTE),
  PROCRATE              VARCHAR2(18 BYTE),
  DT_NEXT_OVERVALUE     VARCHAR2(10 BYTE),
  DT_CONTRACT           VARCHAR2(10 BYTE),
  DT                    VARCHAR2(10 BYTE),
  SYSMOMENT             VARCHAR2(20 BYTE),
  DEAL_CODE             VARCHAR2(100 BYTE),
  KINDPROCRATE_CODE     VARCHAR2(100 BYTE),
  PROCBASE_CODE         VARCHAR2(100 BYTE),
  REC_STATUS            VARCHAR2(2 BYTE),
  EXT_FILE              VARCHAR2(300 BYTE),
  SUBKINDPROCRATE_CODE  VARCHAR2(100 BYTE),
  STG_FCODE             VARCHAR2(4 BYTE),
  STG_PACK_ID           DATE,
  STG_PK_HASH           VARCHAR2(32 BYTE),
  STG_ROW_HASH          VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_PROLONGATION CASCADE CONSTRAINTS;

CREATE TABLE FCT_PROLONGATION
(
  PARENT_CODE       VARCHAR2(100 BYTE),
  CHILD_CODE        VARCHAR2(100 BYTE),
  LONGSUM_NAT       VARCHAR2(26 BYTE),
  LONGSUM           VARCHAR2(26 BYTE),
  DT                VARCHAR2(10 BYTE),
  SYSMOMENT         VARCHAR2(20 BYTE),
  REC_STATUS        VARCHAR2(2 BYTE),
  EXT_FILE          VARCHAR2(300 BYTE),
  STG_FCODE         VARCHAR2(4 BYTE),
  STG_PACK_ID       DATE,
  STG_PK_HASH       VARCHAR2(32 BYTE),
  STG_ROW_HASH      VARCHAR2(32 BYTE),
  CODE_PARENT_ORIG  VARCHAR2(100 BYTE),
  CODE_CHILD_ORIG   VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_PROVISIONDEAL CASCADE CONSTRAINTS;

CREATE TABLE FCT_PROVISIONDEAL
(
  SUMMA                    VARCHAR2(26 BYTE),
  SYSMOMENT                VARCHAR2(20 BYTE),
  PROVISIONDEAL_TYPE_CODE  VARCHAR2(250 BYTE),
  DEAL_CODE                VARCHAR2(100 BYTE),
  FINSTR_CODE              VARCHAR2(30 BYTE),
  REC_STATUS               VARCHAR2(2 BYTE),
  EXT_FILE                 VARCHAR2(300 BYTE),
  QUALITY                  VARCHAR2(2 BYTE),
  STG_FCODE                VARCHAR2(4 BYTE),
  STG_PACK_ID              DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE FCT_PROVISIONDEAL IS '??? ??????? ???????????';

COMMENT ON COLUMN FCT_PROVISIONDEAL.SUMMA IS '????? ??????????? ?? ????????';

COMMENT ON COLUMN FCT_PROVISIONDEAL.SYSMOMENT IS '?????? ????????';

COMMENT ON COLUMN FCT_PROVISIONDEAL.PROVISIONDEAL_TYPE_CODE IS '??? ??????????? 1-??????????????, 2-?????, 3-??????? 4-????????';

COMMENT ON COLUMN FCT_PROVISIONDEAL.DEAL_CODE IS '"DEAL_CODE" ?????? ????????? ???????? ???? "CODE" ?????? ?? ??????? FCT_DEAL';

COMMENT ON COLUMN FCT_PROVISIONDEAL.FINSTR_CODE IS '"FINSTR_CODE" ?????? ????????? ???????? ???? "FINSTR_CODE" ?????? ?? ??????? DET_FINSTR';

COMMENT ON COLUMN FCT_PROVISIONDEAL.REC_STATUS IS '????????????? DML-????????. 0-??????? ??? ?????????, 1-????????';


DROP TABLE FCT_PROVISIONDEAL_CRED_OBJ CASCADE CONSTRAINTS;

CREATE TABLE FCT_PROVISIONDEAL_CRED_OBJ
(
  PROVISION_SUM       VARCHAR2(26 BYTE),
  AMOUNT              VARCHAR2(9 BYTE),
  DT                  VARCHAR2(10 BYTE),
  SYSMOMENT           VARCHAR2(20 BYTE),
  CREDITDEAL_CODE     VARCHAR2(100 BYTE),
  PROVISIONDEAL_CODE  VARCHAR2(100 BYTE),
  REC_STATUS          VARCHAR2(2 BYTE),
  EXT_FILE            VARCHAR2(300 BYTE),
  STG_FCODE           VARCHAR2(4 BYTE),
  STG_PACK_ID         DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE FCT_PROVISIONDEAL_CRED_OBJ IS 'История участия договора обеспечения в минимизации резерва по сделке';

COMMENT ON COLUMN FCT_PROVISIONDEAL_CRED_OBJ.PROVISION_SUM IS 'Сумма объекта обеспечения в рамках сделки обеспечения по кредитной сделке';

COMMENT ON COLUMN FCT_PROVISIONDEAL_CRED_OBJ.AMOUNT IS 'Количество';

COMMENT ON COLUMN FCT_PROVISIONDEAL_CRED_OBJ.DT IS 'Дата открытия';

COMMENT ON COLUMN FCT_PROVISIONDEAL_CRED_OBJ.SYSMOMENT IS 'Момент выгрузки';

COMMENT ON COLUMN FCT_PROVISIONDEAL_CRED_OBJ.CREDITDEAL_CODE IS '"CREDITDEAL_CODE" должно содержать значение поля "CODE" записи из таблицы FCT_DEAL';

COMMENT ON COLUMN FCT_PROVISIONDEAL_CRED_OBJ.PROVISIONDEAL_CODE IS '"PROVISIONDEAL_CODE" должно содержать значение поля "DEAL_CODE" записи из таблицы FCT_PROVISIONDEAL';

COMMENT ON COLUMN FCT_PROVISIONDEAL_CRED_OBJ.REC_STATUS IS 'Идентификатор DML-операции. 0-вставка или изменение, 1-удаление';


DROP TABLE FCT_PROVISION_OBJ_ATTR CASCADE CONSTRAINTS;

CREATE TABLE FCT_PROVISION_OBJ_ATTR
(
  VALUE                 VARCHAR2(256 BYTE),
  DT                    VARCHAR2(10 BYTE),
  SYSMOMENT             VARCHAR2(20 BYTE),
  OBJECT_CODE           VARCHAR2(100 BYTE),
  OBJECT_TYPEATTR_CODE  VARCHAR2(100 BYTE),
  FINSTR_CODE           VARCHAR2(30 BYTE),
  REC_STATUS            VARCHAR2(2 BYTE),
  EXT_FILE              VARCHAR2(300 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE FCT_PROVISION_OBJ_ATTR IS 'Значение атрибута по объекту обеспечения';

COMMENT ON COLUMN FCT_PROVISION_OBJ_ATTR.VALUE IS 'ЗНАЧЕНИЕ АТРИБУТА';

COMMENT ON COLUMN FCT_PROVISION_OBJ_ATTR.DT IS 'ДАТА ОТКРЫТИЯ';

COMMENT ON COLUMN FCT_PROVISION_OBJ_ATTR.SYSMOMENT IS 'МОМЕНТ ВЫГРУЗКИ';

COMMENT ON COLUMN FCT_PROVISION_OBJ_ATTR.OBJECT_CODE IS '"OBJECT_CODE" ДОЛЖНО СОДЕРЖАТЬ ЗНАЧЕНИЕ ПОЛЯ "CODE" ЗАПИСИ ИЗ ТАБЛИЦЫ FCT_PROVISION_OBJECT';

COMMENT ON COLUMN FCT_PROVISION_OBJ_ATTR.OBJECT_TYPEATTR_CODE IS '"OBJECT_TYPEATTR_CODE" ДОЛЖНО СОДЕРЖАТЬ ЗНАЧЕНИЕ ПОЛЯ "CODE" ЗАПИСИ ИЗ ТАБЛИЦЫ DET_PROVISION_OBJECT_TYPEATTR';

COMMENT ON COLUMN FCT_PROVISION_OBJ_ATTR.FINSTR_CODE IS '"FINSTR_CODE" ДОЛЖНО СОДЕРЖАТЬ ЗНАЧЕНИЕ ПОЛЯ "FINSTR_CODE" ЗАПИСИ ИЗ ТАБЛИЦЫ DET_FINSTR';

COMMENT ON COLUMN FCT_PROVISION_OBJ_ATTR.REC_STATUS IS 'ИДЕНТИФИКАТОР DML-ОПЕРАЦИИ. 0-ВСТАВКА ИЛИ ИЗМЕНЕНИЕ, 1-УДАЛЕНИЕ';


DROP TABLE FCT_PROVISION_OBJECT CASCADE CONSTRAINTS;

CREATE TABLE FCT_PROVISION_OBJECT
(
  CODE                       VARCHAR2(100 BYTE),
  TYPEPROVISION_OBJECT_CODE  VARCHAR2(100 BYTE),
  FINSTR_CODE                VARCHAR2(30 BYTE),
  AMOUNT                     VARCHAR2(8 BYTE),
  BALANCE_VALUE              VARCHAR2(26 BYTE),
  MARKET_VALUE               VARCHAR2(26 BYTE),
  NOTE                       VARCHAR2(4000 BYTE),
  DT                         VARCHAR2(10 BYTE),
  SYSMOMENT                  VARCHAR2(20 BYTE),
  REC_STATUS                 VARCHAR2(2 BYTE),
  EXT_FILE                   VARCHAR2(300 BYTE),
  STG_FCODE                  VARCHAR2(4 BYTE),
  STG_PACK_ID                DATE,
  STG_PK_HASH                VARCHAR2(32 BYTE),
  STG_ROW_HASH               VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_REPAYSCHEDULE_DM CASCADE CONSTRAINTS;

CREATE TABLE FCT_REPAYSCHEDULE_DM
(
  TYPESCHEDULE     VARCHAR2(2 BYTE),
  EVENTSUM         VARCHAR2(26 BYTE),
  DEALSUM          VARCHAR2(26 BYTE),
  CODE             VARCHAR2(100 BYTE),
  SYSMOMENT        VARCHAR2(20 BYTE),
  FINSTRAMOUNT     VARCHAR2(26 BYTE),
  DT               VARCHAR2(10 BYTE),
  MOVINGDIRECTION  VARCHAR2(250 BYTE),
  FINSTR_CODE      VARCHAR2(30 BYTE),
  DEAL_CODE        VARCHAR2(250 BYTE),
  TYPEREPAY_CODE   VARCHAR2(250 BYTE),
  REC_STATUS       VARCHAR2(2 BYTE),
  EXT_FILE         VARCHAR2(300 BYTE),
  STG_FCODE        VARCHAR2(4 BYTE),
  STG_PACK_ID      DATE,
  STG_PK_HASH      VARCHAR2(32 BYTE),
  STG_ROW_HASH     VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_REPAYSCHEDULE_H CASCADE CONSTRAINTS;

CREATE TABLE FCT_REPAYSCHEDULE_H
(
  PAY_DATE         VARCHAR2(10 BYTE),
  DT               VARCHAR2(10 BYTE),
  TYPESCHEDULE     VARCHAR2(2 BYTE),
  MOVINGDIRECTION  VARCHAR2(2 BYTE),
  EVENTSUM         VARCHAR2(26 BYTE),
  FINSTRAMOUNT     VARCHAR2(26 BYTE),
  DEALSUM          VARCHAR2(26 BYTE),
  SYSMOMENT        VARCHAR2(20 BYTE),
  DEAL_CODE        VARCHAR2(100 BYTE),
  TYPEREPAY_CODE   VARCHAR2(250 BYTE),
  FINSTR_CODE      VARCHAR2(30 BYTE),
  REC_STATUS       VARCHAR2(2 BYTE),
  EXT_FILE         VARCHAR2(300 BYTE),
  CODE             VARCHAR2(100 BYTE),
  PREV_DT_OPEN     VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FCT_SUBJECT_ROLEDEAL CASCADE CONSTRAINTS;

CREATE TABLE FCT_SUBJECT_ROLEDEAL
(
  DEAL_CODE     VARCHAR2(100 BYTE),
  SUBJECT_CODE  VARCHAR2(250 BYTE),
  ROLE_CODE     VARCHAR2(100 BYTE),
  IS_AGREEMENT  VARCHAR2(1 BYTE),
  DT_AGREEMENT  VARCHAR2(10 BYTE),
  DT            VARCHAR2(10 BYTE),
  SYSMOMENT     VARCHAR2(20 BYTE),
  REC_STATUS    VARCHAR2(2 BYTE),
  EXT_FILE      VARCHAR2(300 BYTE),
  STG_FCODE     VARCHAR2(4 BYTE),
  STG_PACK_ID   DATE,
  BEGINDATE     VARCHAR2(10 BYTE),
  ENDDATE       VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ASS_ACCOUNTDEAL_IDX_EF ON ASS_ACCOUNTDEAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ASS_CARRYDEAL_IDX_EF ON ASS_CARRYDEAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ASS_DEAL_CAT_VAL_IDX_EF ON ASS_DEAL_CAT_VAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ASS_FCT_DEAL_IDX_EF ON ASS_FCT_DEAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ASS_HALFCARRYDEAL_IDX_EF ON ASS_HALFCARRYDEAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_DEAL_IDX_EF ON FCT_DEAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_DEAL_INDICATOR_IDX_EF ON FCT_DEAL_INDICATOR
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_DEALRISK_IDX_EF ON FCT_DEALRISK
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_MBKCREDEAL_IDX_EF ON FCT_MBKCREDEAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_MBKDEPDEAL_IDX_EF ON FCT_MBKDEPDEAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_PROCRATE_DEAL_IDX_EF ON FCT_PROCRATE_DEAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_PROVISIONDEAL_IDX_EF ON FCT_PROVISIONDEAL
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_PROVISION_OBJECT_IDX ON FCT_PROVISION_OBJECT
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_REPAYSCHEDULE_H_IND ON FCT_REPAYSCHEDULE_H
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FCT_REPAYSCHEDULE_IDX_EF_DM ON FCT_REPAYSCHEDULE_DM
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FFCT_ATTR_SCHEDULE_IDX_EF ON FCT_ATTR_SCHEDULE
(TRIM("EXT_FILE"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT DELETE, SELECT, INSERT, UPDATE ON ASS_ACCOUNTDEAL TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON ASS_CARRYDEAL TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON ASS_DEAL_CAT_VAL TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON ASS_FCT_DEAL TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON ASS_HALFCARRYDEAL TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON FCT_ATTR_SCHEDULE TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON FCT_DEAL TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON FCT_DEAL_INDICATOR TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON FCT_DEALRISK TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON FCT_MBKCREDEAL TO PUBLIC;

GRANT DELETE, SELECT, INSERT, UPDATE ON FCT_PROCRATE_DEAL TO PUBLIC;
