--объекты очереди
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5003, 'Данные из Ru-Data', '1', 5003, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5002, 'Начальные лимиты QUIK', '2', 5002, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5004, 'Корректировка лимитов QUIK', '3', 5004, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5005, 'Лимиты из QUIK для сверки', '4', 5005, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5006, 'Сведения по счетам для ДБО', '5', 5006, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5007, 'Остатки по счетам ДЕПО для сверки', '6', 5007, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5008, 'Данные по Счетам БУ для сверки', '7', 5008, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5009, 'Данные по Проводкам для сверки', '8', 5009, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5010, 'Данные по Договору брокерского обслуживания', '9', 5010, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5011, 'Данные по Договору ДЕПО', '10', 5011, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5012, 'Запрос данных по счетам ДЕПО для сверки', '11', 5012, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5013, 'Рассчитанные резервы', '12', 5013, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5014, 'Запрос обновления данных из Ru-Data', '13', 5014, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5015, 'Сделочная модель по ЦБ, ПФИ', '14', 5015, 0, CHR(1), CHR(0));
INSERT INTO dobjects_dbt( T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE )
VALUES( 5016, 'Сделочная модель по МБК, ВО', '15', 5016, 0, CHR(1), CHR(0));

UPDATE dobjects_dbt --связка дистрибутивного объекта Счет с FUNCID dfunc_dbt
SET T_USERNUMBER = 5005
WHERE T_OBJECTTYPE = 4;

UPDATE dobjects_dbt --связка дистрибутивного объекта Проволка с FUNCID dfunc_dbt
SET T_USERNUMBER = 5006
WHERE T_OBJECTTYPE = 1;

--объекты очереди
