/*Добавление поля в таблицу DNPTXHOLDGEN_DBT*/
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXHOLDGEN_DBT ADD T_BYCLIENTLIST CHAR(1) DEFAULT CHR(0)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXHOLDGEN_DBT.T_BYCLIENTLIST IS ''Операция сгенерирована по списку клиентов''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

