BEGIN
  DELETE FROM DPROCESS_U_DBT d
   WHERE T_SUBTYPE = 719 AND T_TYPE = 1;       
          
  UPDATE DPROCESS_U_DBT
     SET T_NUM = T_NUM - 1
   WHERE T_NUM > 15 AND T_SUBTYPE != 719 AND T_TYPE = 1;

END;
/