/*
$Name:          cipher_widget.mac
$Module:        WEB-Главная книга
$Description:   Макрос виджета выбора шифра
*/
Import RSD;
class TWebCipher
  var Shifr_Oper;
  var Comment;
end;

class TWebCipherListerItem
  var Shifr_Oper;
  var Comment;
end;

macro WebCore_GetCipherListerItemList(NotUsed, sub, listLen)
  
  var cmd,rs;

  var Arr = TArray;

  var query = "SELECT c.* "
              "FROM DCIPHER_DBT c "
              "WHERE 1=1 ";        
  
  if (NotUsed!=null)

    var addthis = "";

    if (NotUsed == true) addthis = "AND c.t_notused = 'X' ";
        else addthis = "AND c.t_notused <> 'X' ";
    end;

    if (addthis!="") 
        query = query + addthis;
    end;

  end;

  if (sub != "")
    query = query + " AND LOWER(T_SHIFR_OPER) LIKE LOWER ('%' || ? || '%') " ;
  end;

  if (listLen != 0)
    query = query + " AND ROWNUM < " + string(listLen);
  end;

  query = query + " ORDER BY T_SHIFR_OPER";

  cmd = RsdCommand(query);

  if (sub != "")
     cmd.addParam( "", RSDBP_IN, sub );
  end;

  rs = RsdRecordset(cmd);

  while (rs.movenext)
      
      var obj = TWebCipherListerItem;
      
      obj.Shifr_Oper = rs.value("t_shifr_oper");
      obj.Comment = rs.value("t_comment");

      Arr[Arr.size] = obj;

  end;

  return Arr;

end;

macro WebCore_GetCipherItemByShifr(Shifr_oper)

  var obj;

  var cmd, rs;

  var query = " SELECT c.* FROM DCIPHER_DBT c WHERE T_SHIFR_OPER =  " + Shifr_oper ;

  cmd = RsdCommand(query);

  rs = RsdRecordset(cmd);

  if (rs.movenext)

     obj =  TWebCipher;

     obj.Shifr_oper = rs.value("t_shifr_oper");
     obj.Comment = rs.value("t_comment");
     //obj.NotUsed = rs.value("t_notused");

  end;

  return obj;

end;               

macro WebCore_CreateTWebCipher(Shifr_oper, Comment, NotUsed)

  var obj = TWebCipher;

  obj.Shifr_oper = Shifr_oper;
  obj.Comment    = Comment;
  
  return obj;

end;