/*
$Name:          f501ArReportCalculateController.mac
$Module:        Отчеты ЦБ
$Description:   Форма 501Ar. Класс контроллера расчета отчета.
*/

class (RcbReportCalculateController) TF501ArReportCalculateController()
    private macro clearValues()
        getReport().getPart(TF501ArGlobal().getPart1Id()).getPartCompositeValue().removeAllValues();
        getReport().getPart(TF501ArGlobal().getPart2Id()).getPartCompositeValue().removeAllValues();
        RcbApplication().transactionManager.commit();
        getReport().getPart(TF501ArGlobal().getPart1Id()).clear();
        getReport().getPart(TF501ArGlobal().getPart2Id()).clear();
    end;

    private macro pushControllers()
        m_partCalculateControllers.push_back(objectFactoryInstance.createPartCalculateController(getReport().getPart(TF501ArGlobal().getPart1Id()), this));
        m_partCalculateControllers.push_back(objectFactoryInstance.createPartCalculateController(getReport().getPart(TF501ArGlobal().getPart2Id()), this));
    end;

    private macro printAdditionalProtocolData()
//        TF501ArSettings().printCalculationReport(getProtocolView());
    end;

    macro initialize() : Bool
        clearValues();
        pushControllers();

        getDatasources().getDatasource("501ArData").cacheData();

        return m_partCalculateControllers.size > 0;
    end;

    private macro postprocess()
    end;

    macro calculate()
        var result = calculate();
        for (var i, m_partCalculateControllers)
           i.getDataProtocolView().save();
        end;
        return result;
    end;

    private macro constructorTF501ArReportCalculateController()
        initRcbReportCalculateController();
    end;

    constructorTF501ArReportCalculateController();
end;
