/*
$Name:         dl711Part4.mac
$Module:       Депозитарий
$Description:  Выборка данных для Ф711 Ч4 
*/
import "dl711avoir.mac";

private const LLCLASS_KIND_BLOCK_CB_ENCUMBER711 = 1842; //Обременённые для формы 711
       
const PART_4_1   = 0; // Данные о цифровых свидетельствах, выданных депозитарием
const PART_4_2   = 1; // Данные об УЦП, ЦФА и иных цифровых правах, учитываемые на счетах депо и иных счетах клиентов депозитария
const PART_4_2_1 = 2; // Данные об объеме проведенных депозитарных операций с учитываемыми УЦП, ЦФА и иными цифровыми правами
const PART_4_3   = 3; // Данные об УЦП, ЦФА и иных цифровых правах, принадлежащих кредитной организации
const PART_4_4   = 4; // Сведения об операциях с УЦП, ЦФА и иными цифровыми правами, переданными и принятыми кредитной организацией на возвратной основе

/*Фильтр для отбора*/
private class Filter
  var Departments:string = string({OperDprt}),
      BegDate:date       = {curdate},
      RepDate:date       = {curdate},
      RepPart:integer    = 0;
end;

private macro GetQueryForSub(OnDate:date, RepDateSQL:string, BlockClass:integer)

  var query = " SUM(0) ";
  
  query = "                 SUM(CASE WHEN ";

  if(BlockClass == LLCLASS_KIND_BLOCK_CB_ENCUMBER711)
    query = query + " ( dpac.t_IsTrade = 'X' OR ";
  end;

  query = query + "                                EXISTS(SELECT 1 "
                + "                                            FROM ddepoatvl_dbt atvl "
                + "                                           WHERE atvl.t_IsType = CHR(0) "
                + "                                             AND atvl.t_ID = dacntPart.t_AutoKey "
                + "                                             AND atvl.t_AttrNum = 6 " //DEPOATTR_ATTNUM_BLOCK
                + "                                             AND atvl.t_Value IN (SELECT TO_CHAR(clsv.t_Element) "
                + "                                                                    FROM dllclsval_dbt clsv "
                + "                                                                   WHERE clsv.t_Classificator = "+BlockClass+")"
                + "                                         ) ";

  if(BlockClass == LLCLASS_KIND_BLOCK_CB_ENCUMBER711)
    query = query + " )";
  end;

  query = query + "                               THEN rsi_rsb_account.restsa( accsub.t_AccAnaliticsID, accsub.t_SubAccountID, "+RepDateSQL+", 1 ) "
                + "                          ELSE 0 END "
                + "                    ) " ;
  return query;
end;

private macro GetCountryCode(pt:TRecHandler):string
  const UNKNOWN_CODE       = "999",
        INTERNATIONAL_COUNTRY_CODE = "998",
        INTERNATIONAL_CODE = "996";
  var tools = C_711Tools();
  var CountryCode = "";
  if((pt.rec.LegalForm != PTLEGF_PERSN) and tools.CheckPartyIsSubjType(pt.rec.PartyID, 14 /*Международная компания по 290-ФЗ*/ ))
    CountryCode = INTERNATIONAL_CODE;
  elif ((pt.rec.LegalForm != PTLEGF_PERSN) and tools.CheckPartyType(pt.rec.PartyID, 34 /*Международная организация*/ ))
    CountryCode = INTERNATIONAL_COUNTRY_CODE;
  else 
    if (pt.rec.NotResident == "X")
      CountryCode = DP_GetCountryByCodeLat3(pt.rec.NRCountry).CodeNum3;
      if(CountryCode == "")
        CountryCode = UNKNOWN_CODE;
      end;
    else
      CountryCode = {ResidentCountryCodeNum};
    end;
  end;
  return CountryCode;
end;

private macro GetLSIN(fiid:integer)
  var cmd, dataSet;
  var LSIN = "";
  
  cmd = DL_RSDCommand("SELECT t_LSIN FROM davoiriss_dbt WHERE t_Fiid = ?");
  cmd.addParam(fiid);
  
  dataSet = cmd.Execute();
  if(dataSet.moveNext())
    LSIN = dataSet.LSIN;
  end;
  return LSIN;
end;

private macro GetStoragePlaceMark(pt:TRecHandler, fiid:integer, operid:integer):string
  var mark = "";
  var cmd, dataSet;
  
  cmd = DL_RSDCommand("SELECT t_isRegistrar, t_isIssuer, t_isDepositary, t_isBank FROM drepparty_vw WHERE t_ID = ?");
  cmd.addParam(pt.rec.PartyID);
  
  dataSet = cmd.Execute();
  
  if(dataSet.moveNext())
    if(pt.rec.PartyID == operid)
      mark = "О";
    end;
    if((dataSet.IsRegistrar == 1) and (dataSet.IsIssuer == 0))
      mark = "Р";
    end;
    if((dataSet.IsDepositary == 1) and (dataSet.IsBank == 1))
      mark = "К";
    end;
    if((dataSet.IsDepositary == 1) and (dataSet.IsBank == 0))
      mark = "Н";
    end;
  end;
  return mark;
end;

private macro SetType(_fiid:integer, _code711:string):string
  var type = "";
  var fiid = _fiid;
  var code711 = _code711;
  var cmd, dataSet;
  
  cmd = DL_RSDCommand("SELECT avr.t_ShortName FROM davrkinds_dbt avr, dfininstr_dbt fin where avr.t_fi_kind = fin.t_fi_kind AND avr.t_avoirkind = fin.t_avoirkind AND fin.t_fiid = ?");
  cmd.addParam(fiid);
  
  dataSet = cmd.Execute();
  if(dataSet.moveNext())
    if(code711 != "")
      type = code711+"("+dataSet.ShortName+")";
    else return dataSet.ShortName;
    end;
  end;
  
  return type;
end;

private macro IsEmissive(fiid:integer):bool
  var cmd, dataSet;
  
  cmd = DL_RSDCommand("SELECT ak.t_IsEmissive FROM davrkinds_dbt ak, dfininstr_dbt fin where ak.t_FI_Kind = fin.t_FI_Kind and ak.t_AvoirKind = fin.t_AvoirKind and fin.t_fiid = ? ");
  cmd.addParam(fiid);
  dataSet = cmd.Execute();
  if(dataSet.moveNext())
    return (dataSet.IsEmissive == "X");
  end;
  return false;
end;

/*Раздел 4.1*/
private class C_711PART4_1(flt_)
  private var flt = flt_;
  private var tools = C_711Tools();
  
  private macro PostProcess()
    var cmd, dataSet, queryUpd = "";
    var pt:TRecHandler;
    var count = 0;
    var IssuerName = "", IssuerINN = "", IssuerOGRN = "", IssuerCountryCode = "", OperName = "", OperINN = "", Type = "", Code711 = "";
    var IssuerINN_MARK = "", IssuerINN_TIN = "", IssuerNotResCode = "", OperINN_MARK = "", OperINN_TIN = "", OperNotResCode = ""; 
    
    cmd = DL_RSDCommand( "SELECT t_AutoKey, t_fiid, t_issuer, t_issuerinn, t_issuerogrn, t_parentfi, t_operid, t_operinn, t_code711, t_facevaluecode FROM d711part4_tmp");
    dataSet = cmd.Execute();
    while (dataSet.moveNext())
      IssuerName = "";
      IssuerINN = dataSet.issuerinn;
      IssuerOGRN = dataSet.issuerogrn;
      IssuerCountryCode = "";
      OperName = "";
      OperINN = dataSet.operinn;
      Type = "";
      Code711 = dataSet.code711;
      IssuerINN_MARK = "";
      IssuerINN_TIN = "";
      IssuerNotResCode = "";
      OperINN_MARK = "";
      OperINN_TIN = "";
      OperNotResCode = "";
      
      count = count + 1;
      
      pt = TRecHandler("party.dbt");
      //Эмитент
      if(ПолучитьСубъекта(dataSet.issuer, pt) == 0)
        IssuerName = tools.GetPartyName(pt);
        //SplitFullINN(IssuerINN, IssuerINN);
        tools.SplitINN_KPP(pt, IssuerINN, @IssuerINN, NULL, @IssuerINN_TIN, @IssuerNotResCode);
        IssuerINN_MARK = tools.GetIssuerINN_Mark(pt);
        if(IssuerOGRN == "")
          IssuerOGRN = "NN";
        end;
        IssuerCountryCode = GetCountryCode(pt);
      end;
      //Оператор ИС
      if(ПолучитьСубъекта(dataSet.operid, pt) == 0)
        OperName = tools.GetPartyName(pt);
        //SplitFullINN(OperINN, OperINN);
        tools.SplitINN_KPP(pt, OperINN, @OperINN, NULL, @OperINN_TIN, @OperNotResCode);
        OperINN_MARK = tools.GetIssuerINN_Mark(pt);
      end;
      
      Type = Code711;
      
      queryUpd = "UPDATE d711part4_tmp SET"
                 +" t_issuername  = " +tools.GetSQLStr(IssuerName) + ", "
                 +" t_issuerinn  = " +tools.GetSQLStr(IssuerINN) + ", "
                 +" t_issuercountrycode  = " + tools.GetSQLStr(IssuerCountryCode) + ", "
                 +" t_opername  = " + tools.GetSQLStr(OperName) + ", "
                 +" t_operinn  = " +tools.GetSQLStr(OperINN) + ", "
                 +" t_issuerogrn = "+tools.GetSQLStr(IssuerOGRN)+", "
                 +" t_type  = " + tools.GetSQLStr(Type)+", "
                 +" t_IssuerINN_Mark = "+tools.GetSQLStr(IssuerINN_Mark)+", "
                 +" t_IssuerINN_Tin = "+tools.GetSQLStr(IssuerINN_TIN)+", "
                 +" t_IssuerNotResCode = "+tools.GetSQLStr(IssuerNotResCode)+", "
                 +" t_OperINN_Mark = "+tools.GetSQLStr(OperINN_Mark)+", "
                 +" t_OperINN_Tin = "+tools.GetSQLStr(OperINN_TIN)+", "
                 +" t_OperNotResCode = "+tools.GetSQLStr(OperNotResCode)
                 +" WHERE t_AutoKey = " +dataSet.AutoKey;
                 
      SQL_Execute(queryUpd, "Обновление информации о данных по цс, выданных депозитарием, " + String(count), false);
    end;
  end;
  
  macro PrepareData()
    var query, cmd;
    var RepDateSQL = GetSQLDate(flt.RepDate);
    
    query = "INSERT INTO d711part4_tmp ("
                                       +" t_fiid,"
                                       +" t_issuer,"
                                       +" t_issuername,"
                                       +" t_issuerinn,"
                                       +" t_issuerogrn,"
                                       +" t_issuercountrycode,"
                                       +" t_parentfi,"
                                       +" t_opername,"
                                       +" t_operid, "
                                       +" t_operinn,"
                                       +" t_insysname,"
                                       +" t_type,"
                                       +" t_code711,"
                                       +" t_kind,"
                                       +" t_udrident,"
                                       +" t_ident,"
                                       +" t_facevalue,"
                                       +" t_facevaluecode,"
                                       +" t_numbasefi,"
                                       +" t_count"
                                       +")"
                   +" (SELECT fin.t_fiid, "                                                                                                // t_fiid
                   +"         fin.t_issuer, "                                                                                              // t_issuer
                   +"         CHR(1), "                                                                                                    // t_issuername
                   +"         rsi_rsbparty.GetPartyCode(fin.t_issuer, 16), "                                                               // t_issuerinn
                   +"         rsi_rsbparty.GetPartyCode(fin.t_issuer, 27), "                                                               // t_issuerogrn
                   +"         CHR(1), "                                                                                                    // t_issuercountrycode
                   +"         fin.t_parentfi, "                                                                                            // t_parentfi
                   +"         CHR(1), "                                                                                                    // t_opername
                   +"         digital.t_operinfosysid, "                                                                                   // t_operid
                   +"         rsi_rsbparty.GetPartyCode(digital.t_operinfosysid, 16) as t_operinn, "                                       // t_operinn
                   +"         digital.t_InfoSys, "                                                                                         // t_insysname
                   +"         CHR(1), "                                                                                                    // t_type
                   +"         rsb_secur.GetObjAttrName(12, 1,"
                   +"                                  rsb_secur.GetMainObjAttr(12,"
                   +"                                                           LPAD(avr.t_FIID, 10, '0'),"
                   +"                                                           1, "+RepDateSQL+")),"                                      // t_code711
                   +"         CHR(1), "                                                                                                    // t_kind
                   +"         digital.t_ident, "                                                                                           // t_udrident        
                   +"         fin.t_CodeInAccount, "                                                                                       // t_ident
                   +"         fin.t_facevaluefi, "                                                                                         // t_facevalue
                   +"         finVal.t_Ccy, "                                                                                              // t_facevaluecode
                   +"         avr.t_NumBaseFi, "                                                                                           // t_numbasefi      
                   +"         stor.t_count "                                                                                                 // t_count
                   +"  FROM davoiriss_dbt avr, dfininstr_dbt fin, ddigitala_dbt digital, dfininstr_dbt finVal,"
                   +"     (SELECT "+ GetQueryForSub(flt.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_ENCUMBER711)+" as t_count, "
                   +"        acc.t_Code_Currency as T_FIID "
                   +"      FROM ddepoacnt_dbt dacnt, ddepoacnt_dbt dacntPart, ddepoac_dbt dpac, daccount_dbt acc, daccvanl_dbt accvanl, daccsub_dbt accsub, daccount_dbt accAct, ddepoacnt_dbt dacntAct  "
                   +"      WHERE dacnt.T_AUTOKEY = dacnt.t_Root "
                   +"        AND dacnt.t_department IN (1) "
                   +"        AND dacnt.T_KIND = 2 "
                   +"        AND dpac.t_ID = dacnt.t_Type "
                   +"        AND acc.t_deporoot = dacnt.T_AUTOKEY "
                   +"        AND dpac.t_ID = dacnt.t_Type "
                   +"        AND acc.t_deporoot = dacnt.T_AUTOKEY "
                   +"        AND acc.t_chapter = 5 "
                   +"        AND dacntPart.t_AutoKey = acc.t_DepoAcc "
                   +"        AND accvanl.t_Account = acc.t_Account "
                   +"        AND accvanl.t_AnaliticsID = 2 "
                   +"        AND accvanl.t_FIID = acc.t_Code_Currency "
                   +"        AND accvanl.t_Chapter = acc.t_Chapter  "
                   +"        AND accsub.t_AccAnaliticsID = accvanl.t_AccAnaliticsID  "
                   +"        AND accsub.t_SpecialType = 0 "
                   +"        AND accAct.t_Chapter = acc.t_Chapter "
                   +"        AND accAct.t_Code_Currency = acc.t_Code_Currency "
                   +"        AND accAct.t_Account = accsub.t_SubAccountCode "
                   +"        AND dacntAct.t_autokey = accAct.t_deporoot "
                   +"        GROUP BY dacnt.T_OWNER, dacnt.t_Department, acc.t_Code_Currency) stor "
      +" WHERE rsi_rsb_fiinstr.fi_avrkindsgetroot(2, fin.t_avoirkind) = 62 "
      +"  AND avr.t_fiid = stor.t_fiid "
      +"  AND digital.t_fiid = fin.t_parentfi "
      +"  AND avr.t_fiid = fin.t_fiid "
      +"  AND finVal.t_fiid = fin.t_facevaluefi)";
      
    SQL_EXECUTE(query, "Сбор данных о цс, выданных депозитарием", true);
    
    SQL_Execute("DELETE FROM d711part4_tmp WHERE t_Count = 0", "Удаление информации о лишних записях", false);
    
    PostProcess();
  end;
  
  macro GetQuerySelect()
    var query = "SELECT * "
                +" FROM d711part4_tmp"
                + " ORDER BY t_AutoKey";
     
    return query; 
  end;
end;

/*Раздел 4.2*/
private class C_711PART4_2(flt_)
  private var flt = flt_;
  private var tools = C_711Tools();
  
  private macro InsertNote(autoKeyPart4, flag)
    var query = "INSERT INTO d711part4_prot_tmp (t_autokeypart4, t_flag) VALUES("
                +String(autoKeyPart4)+",'"+flag+"')";
    
    SQL_Execute(query, "Протокол");
  end;
  
  private macro PostProcess()
    var cmd, dataSet, queryUpd = "";
    var pt:TRecHandler;
    var count = 0;
    var IssuerName = "", IssuerINN = "", IssuerOGRN = "", IssuerCountryCode = "", Type = "", ParentFiType = "", ParentIssuerName = "", ParentIssuerINN = "", ParentIssuerOGRN = "", ParentIssuerCountryCode = "",
    ParentRegNum = "", StoragePlaceName = "", StoragePlaceINN = "", OperName = "", OperINN = "", OwnerCountryCode = "", Code711 = "", DepoKind = "", FaceValue = $0.0, ValueCode = "", ISIN = "", LSIN = "", Sector = "";
    var Er = "";
    var IssuerINN_MARK = "", IssuerINN_TIN = "", IssuerNotResCode = "", OperINN_MARK = "", OperINN_TIN = "", OperNotResCode = "", ParentIssuerINN_MARK = "", ParentIssuerINN_TIN = "", ParentIssuerNotResCode = "", StoragePlaceINN_MARK = "", StoragePlaceINN_TIN = "", StoragePlaceNotResCode = "";
    
    cmd = DL_RSDCommand("SELECT t_AutoKey, t_fiid, t_issuer, t_issuerinn, t_issuerogrn, t_parentfi, t_parentissuer, t_parentissuerinn, t_parentissuerogrn, t_operid, t_operinn, t_owner, t_parentfitype, t_ISIN, t_facevaluecode, t_parentvalue, t_depokind, t_storageplace, t_storageplaceinn FROM d711part4_tmp");
    
    dataSet = cmd.Execute();

    while (dataSet.moveNext())
      IssuerName = "";
      IssuerINN = dataSet.IssuerINN;
      IssuerOGRN = dataSet.IssuerOGRN;
      IssuerCountryCode = "";
      ParentIssuerName = "";
      ParentIssuerINN = dataSet.ParentIssuerINN;
      ParentIssuerOGRN = dataSet.ParentIssuerOGRN;
      ParentIssuerCountryCode = "";
      OperName = "";
      OperINN = dataSet.OperINN;
      OwnerCountryCode = ""; 
      Type = "";
      ParentRegNum = "";
      StoragePlaceName = "";
      StoragePlaceINN = dataSet.StoragePlaceINN;
      Code711 = dataSet.ParentFiType;      
      DepoKind = dataSet.DepoKind;
      ISIN = dataSet.ISIN;
      FaceValue = dataSet.ParentValue;
      IssuerINN_MARK = "";
      IssuerINN_TIN = "";
      IssuerNotResCode = "";
      OperINN_MARK = "";
      OperINN_TIN = "";
      OperNotResCode = "";
      ParentIssuerINN_MARK = "";
      ParentIssuerINN_TIN = "";
      ParentIssuerNotResCode = "";
      StoragePlaceINN_MARK = "";
      StoragePlaceINN_TIN = "";
      StoragePlaceNotResCode = "";
      
      count = count + 1;
      
      pt = TRecHandler("party.dbt");
      // Эмитент
      if(ПолучитьСубъекта(dataSet.Issuer, pt) == 0)
        IssuerName = tools.GetPartyName(pt);
        //SplitFullINN(IssuerINN, IssuerINN);
        tools.SplitINN_KPP(pt, IssuerINN, @IssuerINN, NULL, @IssuerINN_TIN, @IssuerNotResCode);
        IssuerINN_MARK = tools.GetIssuerINN_Mark(pt);
        if(IssuerOGRN == "")
          IssuerOGRN = "NN";
        end;
        IssuerCountryCode = GetCountryCode(pt);
      end;
      
      //Владелец ц/б
      if(ПолучитьСубъекта(dataSet.ParentIssuer, pt) == 0)
        ParentIssuerName = tools.GetIssuerName(pt, dataSet.ParentFi);
        tools.SplitINN_KPP(pt, ParentIssuerINN, @ParentIssuerINN, NULL, @ParentIssuerINN_TIN, @ParentIssuerNotResCode);
        ParentIssuerINN_MARK = tools.GetIssuerINN_Mark(pt);
        if(ParentIssuerOGRN == "")
          ParentIssuerOGRN = "NN";
        end;
        ParentIssuerCountryCode = GetCountryCode(pt);
      end;
      
      //Оператор ИС
      if(ПолучитьСубъекта(dataSet.operid, pt) == 0)
        OperName = tools.GetPartyName(pt);
        //(OperINN, OperINN);
        tools.SplitINN_KPP(pt, OperINN, @OperINN, NULL, @OperINN_TIN, @OperNotResCode);
        OperINN_MARK = tools.GetIssuerINN_Mark(pt);
      end;
      
      //Владелец счета
      if(ПолучитьСубъекта(dataSet.Owner, pt) == 0)
        OwnerCountryCode = GetCountryCode(pt);
      end;
      
      Type = SetType(dataSet.Fiid, "");
      
      var fn = TRecHandler("fininstr.dbt");
      if((ПолучитьФинИн(dataSet.ParentFi, fn) == 0))
        LSIN = GetLSIN(dataSet.ParentFi);
        if(IsEmissive(dataSet.ParentFi))
          if((Code711 != "SHS7") AND (Code711 != "SHS71") AND (Code711 != "SHS8"))
            ParentRegNum = LSIN;
          else ParentRegNum = tools.CorrectLSINInvst(dataSet.ParentFi, LSIN);
          end;
        else
          ParentRegNum = "";
          if((Code711 == "ENC") or (Code711 == "ENC1") or (Code711 == "ENC2") or (Code711 == "ENC3"))
            ISIN = "";
            ParentRegNum = "";
          end;
        end;
      end;
      
      if(ParentIssuerCountryCode != "643")
        ParentRegNum = "";
      end;
      
      if((Code711 == "DR") OR (Code711 == "DR1") OR (Code711 == "DR2"))
        ParentRegNum = tools.GetLSINDEPO(dataSet.ParentFi);
      end;
      
      if(FI_IsISU(fn))
        tools.GetRULESREGXID(dataSet.ParentFi);
      end;
      
      tools.CorrectFaceValue(Code711, @FaceValue, @ValueCode, 2);
      
      
      if((dataSet.Fiid != -1) and (ПолучитьФинИн(dataSet.Fiid, fn) == 0) )
        if(((dataSet.FIID == -1) or (fn.rec.Settlement_Code == 1)) and (tools.IsOurBank(dataSet.StoragePlace)))
        else 
          if(ПолучитьСубъекта(dataSet.StoragePlace, pt) == 0)
            StoragePlaceName = tools.GetPartyName(pt); 
            //SplitFullINN(StoragePlaceINN, StoragePlaceINN);
            tools.SplitINN_KPP(pt, StoragePlaceINN, @StoragePlaceINN, NULL, @StoragePlaceINN_TIN, @StoragePlaceNotResCode);
            StoragePlaceINN_MARK = tools.GetStoragePlaceINN_Mark(pt);
          end;            
        end;
      end;
      
      DepoKind = tools.GetDepoAccKind(DepoKind);
      if((DepoKind != "OWNER")
       and (DepoKind != "DEPOPROG")
       and (DepoKind != "TRUSTEE")
       and (DepoKind != "HOLDER")
       and (DepoKind != "FAUTHOLDER")
       and (DepoKind != "SUBOWNER")
       and (DepoKind != "SUBTRUSTEE"))
         Sector = "000";
      end;   
      
      if(DepoKind == "")
        Er = "!";
      end;
      
      InsertNote(dataSet.AutoKey, Er);
      
      queryUpd = "UPDATE d711part4_tmp SET"
                  +" t_IssuerName = "+tools.GetSQLStr(IssuerName)+", "
                  +" t_IssuerINN = "+tools.GetSQLStr(IssuerINN)+", "
                  +" t_IssuerOGRN = "+tools.GetSQLStr(IssuerOGRN)+ ", "
                  +" t_IssuerCountryCode = "+tools.GetSQLStr(IssuerCountryCode)+", "
                  +" t_ParentIssuerName = "+tools.GetSQLStr(ParentIssuerName)+", "
                  +" t_ParentIssuerINN = "+tools.GetSQLStr(ParentIssuerINN)+", "
                  +" t_ParentIssuerOGRN = "+tools.GetSQLStr(ParentIssuerOGRN)+ ", "
                  +" t_ParentIssuerCountryCode = "+tools.GetSQLStr(ParentIssuerCountryCode)+", "
                  +" t_OperName = "+tools.GetSQLStr(OperName)+", "
                  +" t_OperINN = "+tools.GetSQLStr(OperINN)+", "
                  +" t_OwnerCountryCode = "+tools.GetSQLStr(OwnerCountryCode)+", "                  
                  +" t_Type = "+tools.GetSQLStr(Type)+", "
                  +" t_ParentReg = "+tools.GetSQLStr(ParentRegNum)+","
                  +" t_StoragePlaceName = "+tools.GetSQLStr(StoragePlaceName)+", "
                  +" t_StoragePlaceINN = "+tools.GetSQLStr(StoragePlaceINN)+", "
                  +" t_DepoKind = "+tools.GetSQLStr(DepoKind)+", "
                  +" t_IssuerINN_Mark = "+tools.GetSQLStr(IssuerINN_Mark)+", "
                  +" t_IssuerINN_Tin = "+tools.GetSQLStr(IssuerINN_TIN)+", "
                  +" t_IssuerNotResCode = "+tools.GetSQLStr(IssuerNotResCode)+", "
                  +" t_OperINN_Mark = "+tools.GetSQLStr(OperINN_Mark)+", "
                  +" t_OperINN_Tin = "+tools.GetSQLStr(OperINN_TIN)+", "
                  +" t_OperNotResCode = "+tools.GetSQLStr(OperNotResCode)+", "
                  +" t_ParentIssuerINN_Mark = "+tools.GetSQLStr(ParentIssuerINN_Mark)+", "
                  +" t_ParentIssuerINN_Tin = "+tools.GetSQLStr(ParentIssuerINN_TIN)+", "
                  +" t_ParentIssuerNotResCode = "+tools.GetSQLStr(ParentIssuerNotResCode)+", "
                  +" t_StoragePlaceINN_Mark = "+tools.GetSQLStr(StoragePlaceINN_Mark)+", "
                  +" t_StoragePlaceINN_Tin = "+tools.GetSQLStr(StoragePlaceINN_TIN)+", "
                  +" t_StoragePlaceNotResCode = "+tools.GetSQLStr(StoragePlaceNotResCode)
                  +IIF(FaceValue == $0.0, ", t_parentvalue ="+FaceValue+", t_facevaluecode ="+tools.GetSQLStr(ValueCode), "") //Если изменился номинал, обновляем поля таблицы
                  +IIF(ISIN=="", ", t_ISIN ="+tools.GetSQLStr(ISIN), "" )
                  +IIF(Sector=="000", ", t_sector ="+tools.GetSQLStr(Sector), "" )
               +" WHERE t_AutoKey ="+dataSet.t_AutoKey;
        
      SQL_Execute(queryUpd, "Обновление информации о данных цп, цфа и иных цп, учитываемых на счетах депо и иных счетах клиентов депозитария "+String(count), false)     
    end;  
  end;
  
  macro PrepareData()
    var query, cmd;
    var RepDateSQL = GetSQLDate(flt.RepDate);
    
    query = "INSERT INTO d711part4_tmp ( t_fiid, "
                                      +" t_issuer, "
                                      +" t_issuername, "
                                      +" t_issuerinn, "
                                      +" t_issuerogrn, "
                                      +" t_issuercountrycode, "
                                      +" t_type, "
                                      +" t_name, "
                                      +" t_ident, "
                                      +" t_other, "
                                      +" t_kind, "
                                      +" t_parentfi, "
                                      +" t_parentfitype, "
                                      +" t_parentissuer, "
                                      +" t_parentissuername, "
                                      +" t_parentissuerinn, "
                                      +" t_parentissuerogrn, "
                                      +" t_parentissuercountrycode, "
                                      +" t_parentreg, "
                                      +" t_isin, "
                                      +" t_facevalue, "
                                      +" t_facevaluecode, "
                                      +" t_parentvalue, "
                                      +" t_storageplace, "
                                      +" t_storageplacename, "
                                      +" t_storageplaceinn, "
                                      +" t_operid, "
                                      +" t_operinn, "
                                      +" t_insysname, "
                                      +" t_amount, "
                                      +" t_count, "
                                      +" t_restpawn, "
                                      +" t_restcor, "
                                      +" t_restoperban, "
                                      +" t_arrest, "
                                      +" t_owner, "
                                      +" t_depokind, "
                                      +" t_sector, "
                                      +" t_ownercountrycode "
                                      +")"
                     +" (SELECT fin.t_fiid, " 
                             +" fin.t_issuer, "
                             +" chr(1), "
                             +" rsi_rsbparty.GetPartyCode(fin.t_issuer, 16), "
                             +" rsi_rsbparty.GetPartyCode(fin.t_issuer, 27), "
                             +" chr(1), "
                             +" chr(1), "
                             +" fin.t_name, "
                             +" digital.t_ident, "
                             +" digital.t_other, "
                             +" chr(1), "
                             +" fin.t_parentfi, "
                             +" rsb_secur.GetObjAttrName(12, 1,"
                             +"                          rsb_secur.GetMainObjAttr(12,"
                             +"                                                   LPAD(avr.t_FIID, 10, '0'),"
                             +"                                                   1, "+RepDateSQL+")), "
                             +" finPar.t_issuer, "
                             +" chr(1), "
                             +" rsi_rsbparty.GetPartyCode(finPar.t_issuer, 16), "
                             +" rsi_rsbparty.GetPartyCode(finPar.t_issuer, 27), "
                             +" chr(1), "
                             +" chr(1), "
                             +" avr.t_isin, "
                             +" finPar.t_facevaluefi, "
                             +" finVal.t_Iso_Number, "
                             +" NVL(rsb_fiinstr.FI_GetNominalOnDate(avr.t_FIID, "+RepDateSQL+" ), 0.0), "
                             +" stor.t_storageplace, "
                             +" chr(1), "
                             +" rsi_rsbparty.GetPartyCode(stor.t_storageplace, 16), "
                             +" digital.t_operinfosysid, "
                             +" rsi_rsbparty.GetPartyCode(digital.t_operinfosysid, 16), "
                             +" digital.t_infosys, "
                             +" stor.t_amount, "
                             +" stor.t_restlim, "
                             +" stor.t_restpawn, "
                             +" stor.t_restcor, "
                             +" stor.t_restoperban, "
                             +" stor.t_arrest, "
                             +" stor.t_owner, "
                             +" (case when stor.t_IsTrade = 'X' then 'X'||TO_CHAR(stor.T_DepoAccKind) else TO_CHAR(stor.T_DepoAccKind) end) as t_depokind, "
                             +" NVL(rcb_objattr.getObjAttr(3, 61, rcb_objattr.makePartyId(stor.t_Owner), "+RepDateSQL+"), CHR(1)) as t_sector, "
                             +" chr(1) "
         +" FROM dfininstr_dbt fin, ddigitala_dbt digital, dfininstr_dbt finPar, davoiriss_dbt avr, dfininstr_dbt finVal, "
              +" (SELECT SUM(rsi_rsb_account.restsa( accsub.t_AccAnaliticsID, accsub.t_SubAccountID, "+RepDateSQL+", 1 )) as t_amount, "
                      + GetQueryForSub(flt.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_ENCUMBER711, false) + " as t_restlim, "
                      + GetQueryForSub(flt.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_PAWN, false) + " as t_restpawn, "
                      + GetQueryForSub(flt.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_CORPRESTRICT, true) + " as t_restcor, "
                      + GetQueryForSub(flt.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_OPERBAN, false) + " as t_restoperban, "
                      + GetQueryForSub(flt.RepDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_ARREST, false) + " as t_arrest, "
                     +" acc.t_Code_Currency as t_fiid, "
                     +" rsb_depo.depokindtype(dacnt.T_AUTOKEY) as T_DepoAccKind, "
                     +" dacntAct.t_Owner as t_storageplace, "
                     +" dacnt.t_Owner as t_owner, "
                     +" dpac.t_IsTrade as t_IsTrade "
               +" FROM ddepoacnt_dbt dacnt, ddepoacnt_dbt dacntPart, ddepoac_dbt dpac, daccount_dbt acc, daccvanl_dbt accvanl, daccsub_dbt accsub, daccount_dbt accAct, ddepoacnt_dbt dacntAct "
               +" WHERE dacnt.T_AUTOKEY = dacnt.t_Root "
                 +" AND dacnt.t_opendate <= "+RepDateSQL
                 +" AND dacnt.t_department IN ("+flt.Departments+")"
                 +" AND rsb_depo.depostatus( dacnt.T_AUTOKEY, "+RepDateSQL+") != 1 "
                 +" AND rsi_rsb_account.restac( acc.t_Account, acc.T_CODE_CURRENCY, "+RepDateSQL+", acc.t_Chapter, null ) != 0 "
                 +" AND DECODE(dacnt.t_owner, 0, "+String({OurBank})+", dacnt.t_owner) NOT IN (SELECT dp.t_PartyID from ddp_dep_dbt dp) "
                 +" AND rsb_depo.depokindtype(dacnt.T_AUTOKEY) NOT IN ("+String(OBJTYPE_DEPOKINDTYPE_NOMINALKEEPER)+", "+String(OBJTYPE_DEPOKINDTYPE_FOREIGNNOMKEEPER)+")"
                 +" AND dacnt.T_KIND = 2 "
                 +" AND dpac.t_ID = dacnt.t_Type "
                 +" AND acc.t_deporoot = dacnt.T_AUTOKEY "
                 +" AND acc.t_chapter = 5 "
                 +" AND dacntPart.t_AutoKey = acc.t_DepoAcc "
                 +" AND accvanl.t_Account = acc.t_Account "
                 +" AND accvanl.t_AnaliticsID = 2 " 
                 +" AND accvanl.t_FIID = acc.t_Code_Currency "
                 +" AND accvanl.t_Chapter = acc.t_Chapter "
                 +" AND accsub.t_AccAnaliticsID = accvanl.t_AccAnaliticsID "
                 +" AND accsub.t_SpecialType = 0 "
                 +" AND accAct.t_Chapter = acc.t_Chapter "
                 +" AND accAct.t_Code_Currency = acc.t_Code_Currency "
                 +" AND accAct.t_Account = accsub.t_SubAccountCode "
                 +" AND accAct.t_Open_Date <= "+RepDateSQL
                 +" AND dacntAct.t_autokey = accAct.t_deporoot "
                 +" AND rsi_rsb_account.restsa( accsub.t_AccAnaliticsID, accsub.t_SubAccountID, "+RepDateSQL+", 1 ) > 0 "
               +" GROUP BY acc.t_Code_Currency, dacntAct.t_Owner, rsb_depo.depokindtype(dacnt.T_AUTOKEY), dacnt.t_Owner, dpac.t_IsTrade) stor "
         +" WHERE digital.t_fiid = stor.t_fiid "
           +" AND fin.t_fiid = digital.t_fiid "
           +" AND avr.t_fiid = fin.t_parentfi "
           +" AND finPar.t_fiid = fin.t_parentfi " 
           +" AND finVal.t_fiid = finPar.t_facevaluefi)";

  SQL_Execute(query, "Сбор данных о цп, цфа и иных цп, учитываемых на счетах депо и иных счетах клиентов депозитария", true);
  SQL_Execute("DELETE FROM d711part4_tmp WHERE t_amount = 0", "Удаление информации о лишних записях", false);
  
  PostProcess();  
 end;
  
  macro GetQuerySelect()
   var query = "SELECT t.* "
              + "  FROM  d711part4_tmp t"
              + " ORDER BY t.t_IssuerName, t.t_FaceValueCode";
   return query;
  end;
end;

/*Раздел 4.2.1*/
private class C_711PART4_2_1(flt_)
  private var flt = flt_;
  private var tools = C_711Tools();
  
  private macro PostProcess()
    var cmd, dataSet, queryUpd = "";
    var pt:TRecHandler;
    var count = 0;
    var IssuerName = "", IssuerINN = "", IssuerOGRN = "", IssuerCountryCode = "", Type = "", ParentIssuerName = "", ParentIssuerINN = "", ParentIssuerOGRN = "", ParentIssuerCountryCode = "",
    ParentRegNum = "", Code711 = "", FaceValue = $0.0, ValueCode = "", ISIN = "", LSIN = "";
    var IssuerINN_MARK = "", IssuerINN_TIN = "", IssuerNotResCode = "", ParentIssuerINN_MARK = "", ParentIssuerINN_TIN = "", ParentIssuerNotResCode = "";
    
    cmd = DL_RSDCommand("SELECT t_AutoKey, t_Fiid, t_Issuer, t_IssuerINN, t_IssuerOGRN, t_parentfi, t_parentissuer, t_ParentIssuerINN, t_ParentIssuerOGRN, t_parentfitype, t_ISIN, t_parentvalue FROM d711part4_tmp");
    
    dataSet = cmd.Execute();
    while(dataSet.moveNext())
      IssuerName = "";
      IssuerINN = dataSet.IssuerINN;
      IssuerOGRN = dataSet.IssuerOGRN;
      IssuerCountryCode = "";
      Type = "";
      ParentIssuerName = "";
      ParentIssuerINN = dataSet.ParentIssuerINN;
      ParentIssuerOGRN = dataSet.ParentIssuerOGRN;
      ParentIssuerCountryCode = "";
      ParentRegNum = "";
      Code711 = dataSet.ParentFiType;
      ISIN = dataSet.t_ISIN;
      FaceValue = dataSet.ParentValue;
      IssuerINN_MARK = "";
      IssuerINN_TIN = "";
      IssuerNotResCode = "";
      ParentIssuerINN_MARK = "";
      ParentIssuerINN_TIN = "";
      ParentIssuerNotResCode = "";
      
      count = count + 1;
      
      pt = TRecHandler("party.dbt");
      // Эмитент
      if(ПолучитьСубъекта(dataSet.Issuer, pt) == 0)
        IssuerName = tools.GetPartyName(pt);
        //SplitFullINN(IssuerINN, IssuerINN);
        tools.SplitINN_KPP(pt, IssuerINN, @IssuerINN, NULL, @IssuerINN_TIN, @IssuerNotResCode);
        IssuerINN_MARK = tools.GetIssuerINN_Mark(pt);
        if(IssuerOGRN == "")
          IssuerOGRN = "NN";
        end;
        IssuerCountryCode = GetCountryCode(pt);
      end;
      
      //Владелец ц/б
      if(ПолучитьСубъекта(dataSet.ParentIssuer, pt) == 0)
        ParentIssuerName = tools.GetIssuerName(pt, dataSet.ParentFi);
        tools.SplitINN_KPP(pt, ParentIssuerINN, @ParentIssuerINN, NULL, @ParentIssuerINN_TIN, @ParentIssuerNotResCode);
        ParentIssuerINN_MARK = tools.GetIssuerINN_Mark(pt);
        if(ParentIssuerOGRN == "")
          ParentIssuerOGRN = "NN";
        end;
        ParentIssuerCountryCode = GetCountryCode(pt);
      end;
      
      Type = SetType(dataSet.Fiid, "");
      
      var fn = TRecHandler("fininstr.dbt");
      if((ПолучитьФинИн(dataSet.ParentFi, fn) == 0))
        LSIN = GetLSIN(dataSet.ParentFi);
        if(IsEmissive(dataSet.ParentFi))
          if((Code711 != "SHS7") AND (Code711 != "SHS71") AND (Code711 != "SHS8"))
            ParentRegNum = LSIN;
          else ParentRegNum = tools.CorrectLSINInvst(dataSet.ParentFi, LSIN);
          end;
        else
          ParentRegNum = "";
          if((Code711 == "ENC") or (Code711 == "ENC1") or (Code711 == "ENC2") or (Code711 == "ENC3"))
            ISIN = "";
            ParentRegNum = "";
          end;
        end;
      end;
      
      if(ParentIssuerCountryCode != "643")
        ParentRegNum = "";
      end;
      
      if((Code711 == "DR") OR (Code711 == "DR1") OR (Code711 == "DR2"))
        ParentRegNum = tools.GetLSINDEPO(dataSet.ParentFi);
      end;
      
      if(FI_IsISU(fn))
        tools.GetRULESREGXID(dataSet.ParentFi);
      end;
      
      tools.CorrectFaceValue(Code711, @FaceValue, @ValueCode, 2);
      
      queryUpd = "UPDATE d711part4_tmp SET "
                  +" t_IssuerName = "+tools.GetSQLStr(IssuerName)+","
                  +" t_IssuerINN = "+tools.GetSQLStr(IssuerINN)+","
                  +" t_IssuerOGRN = "+tools.GetSQLStr(IssuerOGRN)+", "
                  +" t_IssuerCountryCode = "+tools.GetSQLStr(IssuerCountryCode)+","
                  +" t_ParentIssuerName = "+tools.GetSQLStr(ParentIssuerName)+","
                  +" t_ParentIssuerINN = "+tools.GetSQLStr(ParentIssuerINN)+","
                  +" t_parentissuerogrn = "+tools.GetSQLStr(ParentIssuerOGRN)+", "
                  +" t_ParentIssuerCountryCode = "+tools.GetSQLStr(ParentIssuerCountryCode)+","
                  +" t_Type = "+tools.GetSQLStr(Type)+","
                  +" t_ParentReg = "+tools.GetSQLStr(ParentRegNum)+", "
                  +" t_IssuerINN_Mark = "+tools.GetSQLStr(IssuerINN_Mark)+", "
                  +" t_IssuerINN_Tin = "+tools.GetSQLStr(IssuerINN_TIN)+", "
                  +" t_IssuerNotResCode = "+tools.GetSQLStr(IssuerNotResCode)+", "
                  +" t_ParentIssuerINN_Mark = "+tools.GetSQLStr(ParentIssuerINN_Mark)+", "
                  +" t_ParentIssuerINN_Tin = "+tools.GetSQLStr(ParentIssuerINN_TIN)+", "
                  +" t_ParentIssuerNotResCode = "+tools.GetSQLStr(ParentIssuerNotResCode)
                  +IIF(FaceValue == $0.0, ", t_parentvalue ="+FaceValue+", t_facevaluecode ="+tools.GetSQLStr(ValueCode), "") //Если изменился номинал, обновляем поля таблицы
                  +IIF(ISIN=="", ", t_ISIN ="+tools.GetSQLStr(ISIN), "" )
               +" WHERE t_AutoKey = " + dataSet.AutoKey;
      
      SQL_Execute(queryUpd, "Обновление информации об объеме проведенных депозитарных операций с учитываемыми утилитарными цифровыми правами, цифровыми финансовыми активами и иными цифровыми правами" + String(count), false);
    end;
  end;
  
   macro PrepareData()
    var query, cmd;
    var RepDateSQL = GetSQLDate(flt.RepDate);
    
        query = "INSERT INTO d711part4_tmp ( t_fiid, "
                                      +" t_issuer, "
                                      +" t_issuername, "
                                      +" t_issuerinn, "
                                      +" t_issuerogrn, "
                                      +" t_issuercountrycode, "
                                      +" t_type, "
                                      +" t_name, "
                                      +" t_ident, "
                                      +" t_other, "
                                      +" t_kind, "
                                      +" t_parentfi, "
                                      +" t_parentfitype, "
                                      +" t_parentissuer, "
                                      +" t_parentissuername, "
                                      +" t_parentissuerinn, "
                                      +" t_parentissuerogrn, "
                                      +" t_parentissuercountrycode, "
                                      +" t_parentreg, "
                                      +" t_isin, "
                                      +" t_facevalue, "
                                      +" t_facevaluecode, "
                                      +" t_parentvalue, "
                                      +" t_receivquant, "
                                      +" t_receivamount, "
                                      +" t_withdrawquant, "
                                      +" t_withdrawamount "
                                      +")"
                       +"(SELECT fin.t_fiid, "
                              +" fin.t_issuer, "
                              +" chr(1), "
                              +" rsi_rsbparty.GetPartyCode(fin.t_issuer, 16) as t_issuerinn, "
                              +" rsi_rsbparty.GetPartyCode(fin.t_issuer, 27) as t_issuerogrn, "
                              +" chr(1), "
                              +" chr(1), "
                              +" fin.t_name, "
                              +" digital.t_ident, "
                              +" digital.t_other, "
                              +" chr(1), "
                              +" fin.t_parentfi, "
                              +" rsb_secur.GetObjAttrName(12, 1,"
                              +"                         rsb_secur.GetMainObjAttr(12,"
                              +"                                                  LPAD(avr.t_FIID, 10, '0'),"
                              +"                                                  1, "+RepDateSQL+")), "
                              +" finPar.t_issuer, "
                              +" chr(1), "
                              +" rsi_rsbparty.GetPartyCode(finPar.t_issuer, 16), "
                              +" rsi_rsbparty.GetPartyCode(finPar.t_issuer, 27), "
                              +" chr(1), "
                              +" chr(1), "
                              +" avr.t_isin, "
                              +" finPar.t_facevaluefi, "
                              +" finVal.t_Iso_Number, "
                              +" NVL(rsb_fiinstr.FI_GetNominalOnDate(avr.t_FIID, "+RepDateSQL+" ), 0.0), "
                              +" stor.t_receivquant, "
                              +" stor.t_receivamount, "
                              +" stor.t_withdrawquant, "
                              +" stor.t_withdrawamount "
                      +" FROM dfininstr_dbt fin, dfininstr_dbt finPar, ddigitala_dbt digital, davoiriss_dbt avr, dfininstr_dbt finVal, "
                        +"(SELECT SUM (CASE "
                                    +" WHEN (((accD.t_Kind_Account = 'А') "
                                    +" OR (accD.t_Kind_Account = 'П' AND rsb_depo.depokindtype (accD.t_deporoot) = " + OBJTYPE_DEPOKINDTYPE_TRANSIT  + "))"
                                    +" AND accC.t_Kind_Account = 'П') "
                                    +" THEN trn.t_SUM_PAYER ELSE 0 END) as t_receivamount, "
                               +" SUM (CASE "
                                    +" WHEN (((accD.t_Kind_Account = 'А') "
                                    +" OR (accD.t_Kind_Account = 'П' AND rsb_depo.depokindtype (accD.t_deporoot) = " + OBJTYPE_DEPOKINDTYPE_TRANSIT  + "))"
                                    +" AND accC.t_Kind_Account = 'П') "
                                    +" THEN 1 ELSE 0 END) as t_receivquant, " 
                               +" SUM (CASE "
                                    +" WHEN (((accC.t_Kind_Account = 'А') "
                                    +" OR (accC.t_Kind_Account = 'П' AND rsb_depo.depokindtype (accC.t_deporoot) = " + OBJTYPE_DEPOKINDTYPE_TRANSIT +" )) "
                                    +" AND accD.t_Kind_Account = 'П') "
                                    +" THEN trn.t_SUM_PAYER ELSE 0 END) as t_withdrawamount, " 
                               +" SUM (CASE "
                                    +" WHEN (((accC.t_Kind_Account = 'А') "
                                    +" OR (accC.t_Kind_Account = 'П' AND rsb_depo.depokindtype (accC.t_deporoot) = " + OBJTYPE_DEPOKINDTYPE_TRANSIT +" )) "
                                    +" AND accD.t_Kind_Account = 'П') "
                                    +" THEN 1 ELSE 0 END) as t_withdrawquant, "
                               +" trn.t_FIID_PAYER t_FIID "
                        +" FROM dacctrn_dbt trn, daccount_dbt accD, daccount_dbt accC "
                        +" WHERE trn.t_STATE = 1 "
                        +"   AND trn.t_DATE_CARRY BETWEEN "  + GetSQLDate(flt.BegDate) + " AND " + RepDateSQL
                        +"   AND trn.t_account_Payer = accD.t_account "
                        +"   AND trn.t_account_Receiver = accC.t_account "
                        +"   AND accC.t_chapter = 5 "
                        +"   AND accD.t_chapter = 5 "
                        +"   AND EXISTS (SELECT 1"
                                      +" FROM ddepoacnt_dbt dacnt "
                                      +" WHERE dacnt.T_AUTOKEY = dacnt.t_Root "
                                      +"   AND dacnt.t_opendate <= "+ RepDateSQL
                                      +"   AND dacnt.t_department IN ("+flt.Departments+")"
                                      +"   AND dacnt.T_KIND = 2 "
                                      +"   AND DECODE(dacnt.t_owner, 0, "+String({OurBank})+", dacnt.t_owner) NOT IN (SELECT dp.t_PartyID from ddp_dep_dbt dp) "
                                      +"   AND ((accC.t_deporoot = dacnt.T_AUTOKEY AND accC.t_chapter = 5) "
                                      +"     OR (accD.t_deporoot = dacnt.T_AUTOKEY AND accD.t_chapter = 5))) "
                                      +" GROUP BY trn.t_FIID_PAYER ) stor "
                     +" WHERE digital.t_fiid = stor.t_fiid "
                     +"   AND fin.t_fiid = digital.t_fiid "
                     +"   AND avr.t_fiid = fin.t_parentfi "
                     +"   AND (stor.t_receivamount > 0 OR stor.t_withdrawamount > 0) "
                     +"   AND finVal.t_fiid = fin.t_facevaluefi "
                     +"   AND finPar.t_fiid = fin.t_parentfi) ";
                     
    SQL_Execute(query, "Сюор данных об объеме проведенных депозитарных операций с учитываемыми утилитарными цифровыми правами, цифровыми финансовыми активами и иными цифровыми правами", true);

    PostProcess();    
  end;
  
  macro GetQuerySelect()
    var query = "SELECT t.* "
              + "  FROM  d711part4_tmp t"
              + " ORDER BY t.t_IssuerName, t.t_FaceValueCode";
              
    return query;
  end;
end;

/*Раздел 4.3*/
private class C_711PART4_3(flt_)
  private var fltr = flt_;
  private var tools = C_711Tools();
  
  private macro InsertNote(autoKeyPart4, flag)
    var query = "INSERT INTO d711part4_prot_tmp (t_autokeypart4, t_flag) VALUES("
                +String(autoKeyPart4)+",'"+flag+"')";
    
    SQL_Execute(query, "Протокол");
  end;
  
  private macro PostProcess()
    var cmd, dataSet, queryUpd = "";
    var pt:TRecHandler;
    var count = 0;
    var IssuerName = "", IssuerINN = "", IssuerOGRN = "", IssuerCountryCode = "", Type = "", ParentIssuerName = "", ParentIssuerINN = "", ParentIssuerOGRN = "", ParentIssuerCountryCode = "",
    ParentRegNum = "", Code711 = "", FaceValue = $0.0, ValueCode = "", ISIN = "", StoragePlaceName = "", StoragePlaceINN = "", OperName = "", OperINN = "", AccPlaceName = "", AccPlaceINN = "", AccPlaceOGRN = "", AccPlaceLicense = "", AccPlaceMark = "", AccPlaceCountryCode = "", LSIN = "";
    var Er = "";
    var IssuerINN_MARK = "", IssuerINN_TIN = "", IssuerNotResCode = "", OperINN_MARK = "", OperINN_TIN = "", OperNotResCode = "", ParentIssuerINN_MARK = "", ParentIssuerINN_TIN = "", ParentIssuerNotResCode = "", StoragePlaceINN_MARK = "", StoragePlaceINN_TIN = "", StoragePlaceNotResCode = "",
        AccPlaceINN_MARK = "", AccPlaceINN_TIN = "", AccPlaceNotResCode = "";
    
    cmd = DL_RSDCommand("SELECT t_AutoKey, t_Fiid, t_Issuer, t_IssuerINN, t_IssuerOGRN, t_parentfi, t_parentfitype, t_parentissuer, t_ParentIssuerINN, t_ParentIssuerOGRN, t_ISIN, t_parentvalue, t_storageplace, t_storageplaceinn, t_operid, t_operinn, t_accplace, t_accplaceinn, t_accplaceogrn  FROM d711part4_tmp");
    
    dataSet = cmd.Execute();
    while(dataSet.moveNext())
      IssuerName = "";
      IssuerINN = dataSet.IssuerINN;
      IssuerOGRN = dataSet.IssuerOGRN;
      IssuerCountryCode = "";
      ParentIssuerName = "";
      ParentIssuerINN = dataSet.ParentIssuerINN;
      ParentIssuerOGRN = dataSet.ParentIssuerOGRN;
      ParentIssuerCountryCode = "";
      Code711 = dataSet.ParentFiType;
      ISIN = dataSet.ISIN;
      FaceValue = dataSet.ParentValue;
      StoragePlaceName = "";
      StoragePlaceINN = dataSet.StoragePlaceINN;
      OperINN = dataSet.OperINN;
      AccPlaceName = "";
      AccPlaceINN = dataSet.AccPlaceINN;
      AccPlaceOGRN = dataSet.AccPlaceOGRN;
      IssuerINN_MARK = "";
      IssuerINN_TIN = "";
      IssuerNotResCode = "";
      OperINN_MARK = "";
      OperINN_TIN = "";
      OperNotResCode = "";
      ParentIssuerINN_MARK = "";
      ParentIssuerINN_TIN = "";
      ParentIssuerNotResCode = "";
      StoragePlaceINN_MARK = "";
      StoragePlaceINN_TIN = "";
      StoragePlaceNotResCode = "";
      AccPlaceINN_MARK = "";
      AccPlaceINN_TIN = "";
      AccPlaceNotResCode = "";


    
    count = count + 1;
      
      pt = TRecHandler("party.dbt");
      // Эмитент
      if(ПолучитьСубъекта(dataSet.Issuer, pt) == 0)
        IssuerName = tools.GetPartyName(pt);
        //SplitFullINN(IssuerINN, IssuerINN);
        tools.SplitINN_KPP(pt, IssuerINN, @IssuerINN, NULL, @IssuerINN_TIN, @IssuerNotResCode);
        IssuerINN_MARK = tools.GetIssuerINN_Mark(pt);
        if(IssuerOGRN == "")
          IssuerOGRN = "NN";
        end;
        IssuerCountryCode = GetCountryCode(pt);
      end;
    
      //Владелец ц/б
      if(ПолучитьСубъекта(dataSet.ParentIssuer, pt) == 0)
        ParentIssuerName = tools.GetIssuerName(pt, dataSet.ParentFi);
        tools.SplitINN_KPP(pt, ParentIssuerINN, @ParentIssuerINN, NULL, @ParentIssuerINN_TIN, @ParentIssuerNotResCode);
        ParentIssuerINN_MARK = tools.GetIssuerINN_Mark(pt);
        if(ParentIssuerOGRN == "")
          ParentIssuerOGRN = "NN";
        end;
        ParentIssuerCountryCode = GetCountryCode(pt);
      end;
      
      //Оператор ИС
      if(ПолучитьСубъекта(dataSet.OperId, pt) == 0)
        OperName = tools.GetPartyName(pt);
        //SplitFullINN(OperINN, OperINN);
        tools.SplitINN_KPP(pt, OperINN, @OperINN, NULL, @OperINN_TIN, @OperNotResCode);
        OperINN_MARK = tools.GetIssuerINN_Mark(pt);
      end;
      
      Type = SetType(dataSet.Fiid, "");
    
      var fn = TRecHandler("fininstr.dbt");
      if((ПолучитьФинИн(dataSet.ParentFi, fn) == 0))
        LSIN = GetLSIN(dataSet.ParentFi);
        if(IsEmissive(dataSet.ParentFi))
          if((Code711 != "SHS7") AND (Code711 != "SHS71") AND (Code711 != "SHS8"))
            ParentRegNum = LSIN;
          else ParentRegNum = tools.CorrectLSINInvst(dataSet.ParentFi, LSIN);
          end;
        else
          ParentRegNum = "";
          if((Code711 == "ENC") or (Code711 == "ENC1") or (Code711 == "ENC2") or (Code711 == "ENC3"))
            ISIN = "";
            ParentRegNum = "";
          end;
        end;
      end;
      
      if(ParentIssuerCountryCode != "643")
        ParentRegNum = "";
      end;
      
      if((Code711 == "DR") OR (Code711 == "DR1") OR (Code711 == "DR2"))
        ParentRegNum = tools.GetLSINDEPO(dataSet.ParentFi);
      end;
      
      if(FI_IsISU(fn))
        tools.GetRULESREGXID(dataSet.ParentFi);
      end;
      
      tools.CorrectFaceValue(Code711, @FaceValue, @ValueCode, 2);
      
      if((ПолучитьФинИн(dataSet.Fiid, fn) == 0))
        if((dataSet.Fiid != -1))
          if(((dataSet.FIID == -1) or (fn.rec.Settlement_Code == 1)) and (tools.IsOurBank(dataSet.StoragePlace)))
          else 
            if(ПолучитьСубъекта(dataSet.StoragePlace, pt) == 0)
              StoragePlaceName = tools.GetPartyName(pt); 
              //SplitFullINN(StoragePlaceINN, StoragePlaceINN);
              tools.SplitINN_KPP(pt, StoragePlaceINN, @StoragePlaceINN, NULL, @StoragePlaceINN_TIN, @StoragePlaceNotResCode);
              StoragePlaceINN_MARK = tools.GetStoragePlaceINN_Mark(pt);
            end;            
          end;
        end;
      end;
    
       if((dataSet.Fiid != -1) and (ПолучитьФинИн(dataSet.Fiid, fn) == 0))
        if(((dataSet.FIID == -1) or (fn.rec.Settlement_Code == 1)) and (tools.IsOurBank(dataSet.AccPlace)))
        else 
          if(ПолучитьСубъекта(dataSet.AccPlace, pt) == 0)
            AccPlaceName = tools.GetPartyName(pt); 
            SplitFullINN(AccPlaceINN, AccPlaceINN);
            tools.SplitINN_KPP(pt, AccPlaceINN, @AccPlaceINN, NULL, @AccPlaceINN_TIN, @AccPlaceNotResCode);
            AccPlaceINN_MARK = tools.GetStoragePlaceINN_Mark(pt);
            if(AccPlaceOGRN == "")
              AccPlaceOGRN = "NN";
            end;
            AccPlaceCountryCode = GetCountryCode(pt);

            if((dataSet.AccPlace == dataSet.OperId))
              AccPlaceLicense = "";
            else 
              AccPlaceLicense = GetCodeParty(pt.rec.PartyID, 17);  
            end;
            
            AccPlaceMark = GetStoragePlaceMark(pt, dataSet.Fiid, dataSet.OperId);  
          end;          
        end;
      end;
      
      InsertNote(dataSet.AutoKey, "");
      
      queryUpd = "UPDATE d711part4_tmp SET "
                     +" t_IssuerName = " +tools.GetSQLStr(IssuerName) +","
                     +" t_IssuerINN = " +tools.GetSQLStr(IssuerINN) +","
                     +" t_issuerogrn = "+tools.GetSQLStr(IssuerOGRN)+", "
                     +" t_IssuerCountryCode = "+tools.GetSQLStr(IssuerCountryCode) +","
                     +" t_ParentIssuerName = " +tools.GetSQLStr(ParentIssuerName) +","
                     +" t_ParentIssuerINN = " +tools.GetSQLStr(ParentIssuerINN) +","
                     +" t_parentissuerogrn = "+tools.GetSQLStr(ParentIssuerOGRN) +", "
                     +" t_ParentIssuerCountryCode = "+tools.GetSQLStr(ParentIssuerCountryCode) +","
                     +" t_Type = " +tools.GetSQLStr(Type) +","
                     +" t_ParentReg = "+tools.GetSQLStr(ParentRegNum) +","
                     +" t_OperName = " +tools.GetSQLStr(OperName) +","
                     +" t_OperINN = " +tools.GetSQLStr(OperINN) +","
                     +" t_StoragePlaceName = " +tools.GetSQLStr(StoragePlaceName) +","
                     +" t_StoragePlaceINN = " +tools.GetSQLStr(StoragePlaceINN) +","
                     +" t_AccPlaceName = " +tools.GetSQLStr(AccPlaceName) +","
                     +" t_AccPlaceINN = " +tools.GetSQLStr(AccPlaceINN) +","
                     +" t_accplaceogrn = " +tools.GetSQLStr(AccPlaceOGRN) +", "
                     +" t_AccPlaceCountryCode = " +tools.GetSQLStr(AccPlaceCountryCode) +","
                     +" t_AccPlaceLicense = " +tools.GetSQLStr(AccPlaceLicense) +","
                     +" t_AccPlaceMark = " +tools.GetSQLStr(AccPlaceMark)+", "
                     +" t_IssuerINN_Mark = "+tools.GetSQLStr(IssuerINN_Mark)+", "
                     +" t_IssuerINN_Tin = "+tools.GetSQLStr(IssuerINN_TIN)+", "
                     +" t_IssuerNotResCode = "+tools.GetSQLStr(IssuerNotResCode)+", "
                     +" t_OperINN_Mark = "+tools.GetSQLStr(OperINN_Mark)+", "
                     +" t_OperINN_Tin = "+tools.GetSQLStr(OperINN_TIN)+", "
                     +" t_OperNotResCode = "+tools.GetSQLStr(OperNotResCode)+", "
                     +" t_ParentIssuerINN_Mark = "+tools.GetSQLStr(ParentIssuerINN_Mark)+", "
                     +" t_ParentIssuerINN_Tin = "+tools.GetSQLStr(ParentIssuerINN_TIN)+", "
                     +" t_ParentIssuerNotResCode = "+tools.GetSQLStr(ParentIssuerNotResCode)+", "
                     +" t_StoragePlaceINN_Mark = "+tools.GetSQLStr(StoragePlaceINN_Mark)+", "
                     +" t_StoragePlaceINN_Tin = "+tools.GetSQLStr(StoragePlaceINN_TIN)+", "
                     +" t_StoragePlaceNotResCode = "+tools.GetSQLStr(StoragePlaceNotResCode)+", "
                     +" t_AccPlaceINN_Mark = "+tools.GetSQLStr(StoragePlaceINN_Mark)+", "
                     +" t_AccPlaceINN_Tin = "+tools.GetSQLStr(AccPlaceINN_TIN)+", "
                     +" t_AccPlaceNotResCode = "+tools.GetSQLStr(AccPlaceNotResCode)
                     +IIF(FaceValue == $0.0, ", t_parentvalue ="+FaceValue+", t_facevaluecode ="+tools.GetSQLStr(ValueCode), "") //Если изменился номинал, обновляем поля таблицы
                     +IIF(ISIN=="", ", t_ISIN ="+tools.GetSQLStr(ISIN), "" )
               +" WHERE t_AutoKey = " + dataSet.AutoKey;

      SQL_Execute(queryUpd, "Обновление информации об уцп, цфа и иных цифровых правах, принадлежащих кредитной организации" + String(count), false);
    
    end;
  end;

  
  macro PrepareData()
    var query, cmd;
    var RepDateSQL = GetSQLDate(fltr.RepDate);
    
    query = "INSERT INTO d711part4_tmp ( t_fiid, "
                                      +" t_issuer, "
                                      +" t_issuername, "
                                      +" t_issuerinn, "
                                      +" t_issuerogrn, "
                                      +" t_issuercountrycode, "
                                      +" t_type, "
                                      +" t_name, "
                                      +" t_ident, "
                                      +" t_other, "
                                      +" t_kind, "
                                      +" t_parentfi, "
                                      +" t_parentfitype, "
                                      +" t_parentissuer, "
                                      +" t_parentissuername, "
                                      +" t_parentissuerinn, "
                                      +" t_parentissuerogrn, "
                                      +" t_parentissuercountrycode, "
                                      +" t_parentreg, "
                                      +" t_isin, "
                                      +" t_facevalue, "
                                      +" t_facevaluecode, "
                                      +" t_parentvalue, "
                                      +" t_storageplace, "
                                      +" t_storageplacename, "
                                      +" t_storageplaceinn, "
                                      +" t_operid, "
                                      +" t_opername, "
                                      +" t_operinn, "
                                      +" t_insysname, "
                                      +" t_balance, "
                                      +" t_ouramount, "
                                      +" t_repoamount, "
                                      +" t_repopawn, "
                                      +" t_repopledge, "
                                      +" t_repodebt, "
                                      +" t_repowrong, "
                                      +" t_repoother, "
                                      +" t_amount, "
                                      +" t_count, "
                                      +" t_restpawn, "
                                      +" t_restcor, "
                                      +" t_restoperban, "
                                      +" t_arrest, "
                                      +" t_accplace, "
                                      +" t_accplacename, "
                                      +" t_accplacemark, "
                                      +" t_accplaceINN, "
                                      +" t_accplaceOGRN, "
                                      +" t_accplacecountrycode, "
                                      +" t_accplacelicense"
                                      +")"
           +"WITH ourOwner AS (SELECT count(1) as t_IsOur, t_PartyID FROM ddp_dep_dbt GROUP BY t_PartyID) "
           +"(SELECT fin.t_fiid, "
                              +" fin.t_issuer, "
                              +" chr(1), "
                              +" rsi_rsbparty.GetPartyCode(fin.t_issuer, 16) as t_issuerinn, "
                              +" rsi_rsbparty.GetPartyCode(fin.t_issuer, 27) as t_issuerogrn, "
                              +" chr(1), "
                              +" chr(1), "
                              +" fin.t_name, "
                              +" digital.t_ident, "
                              +" digital.t_other, "
                              +" chr(1), "
                              +" fin.t_parentfi, "
                              +" rsb_secur.GetObjAttrName(12, 1,"
                              +"                         rsb_secur.GetMainObjAttr(12,"
                              +"                                                  LPAD(avr.t_FIID, 10, '0'),"
                              +"                                                  1, "+RepDateSQL+")), "
                              +" finPar.t_issuer, "
                              +" chr(1), "
                              +" rsi_rsbparty.GetPartyCode(finPar.t_issuer, 16), "
                              +" rsi_rsbparty.GetPartyCode(finPar.t_issuer, 27), "
                              +" chr(1), "
                              +" chr(1), "
                              +" avr.t_isin, "
                              +" finPar.t_facevaluefi, "
                              +" finVal.t_Iso_Number, "
                              +" NVL(rsb_fiinstr.FI_GetNominalOnDate(avr.t_FIID, "+RepDateSQL+" ), 0.0), "
                              +" stor.t_storageplace, "
                              +" chr(1), "
                              +" rsi_rsbparty.GetPartyCode(stor.t_storageplace, 16), "
                              +" digital.t_operinfosysid, "
                              +" chr(1), "
                              +" rsi_rsbparty.GetPartyCode(digital.t_operinfosysid, 16), "
                              +" digital.t_infosys, "
                              +" 0, "
                              +" stor.t_Rest01, "
                              +" 0, "
                              +" 0, "
                              +" 0, "
                              +" 0, " 
                              +" stor.t_Rest07, "
                              +" 0, "
                              +" stor.t_amount, "
                              +" stor.t_restlim, "
                              +" stor.t_restpawn, "
                              +" stor.t_restcor, "
                              +" stor.t_restoperban, "
                              +" stor.t_arrest, "
                              +" stor.t_accplace, "
                              +" chr(1), "
                              +" chr(0), "
                              +" rsi_rsbparty.GetPartyCode(stor.t_accplace, 16), "
                              +" rsi_rsbparty.GetPartyCode(stor.t_accplace, 27), "
                              +" chr(1), "
                              +" chr(1) "
            +"FROM dfininstr_dbt fin, ddigitala_dbt digital, dfininstr_dbt finPar, davoiriss_dbt avr, dfininstr_dbt finVal, "
            +"(SELECT SUM(case WHEN rsb_depo.depokindtype(dacnt.T_AUTOKEY) = 1 THEN (rsi_rsb_account.restsa( accsub.t_AccAnaliticsID, accsub.t_SubAccountID, "+RepDateSQL+", 1 )) ELSE 0 END) as T_Rest01, "
                   +" SUM(case WHEN rsb_depo.depokindtype(dacnt.T_AUTOKEY) = 7 THEN (rsi_rsb_account.restsa( accsub.t_AccAnaliticsID, accsub.t_SubAccountID, "+RepDateSQL+", 1 )) ELSE 0 END) as T_Rest07, "
                   +"  SUM(rsi_rsb_account.restsa( accsub.t_AccAnaliticsID, accsub.t_SubAccountID, "+RepDateSQL+", 1 )) as t_amount, "
                   + GetQueryForSub(fltr.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_ENCUMBER711, false) + " as t_restlim, "
                   + GetQueryForSub(fltr.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_PAWN, false) + " as t_restpawn, "
                   + GetQueryForSub(fltr.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_CORPRESTRICT, true) + " as t_restcor, "
                   + GetQueryForSub(fltr.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_OPERBAN, false) + " as t_restoperban, "
                   + GetQueryForSub(fltr.RepDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_ARREST, false) + " as t_arrest, "    
                  +"  acc.t_Code_Currency as T_FIID, "
                  +"  dacntAct.t_Owner as t_StoragePlace, "  
                  +"  DECODE(NVL(ourOwner.t_IsOur, 0), 0, dacntAct.t_Owner, "+String({OurBank})+") AS t_AccPlace "  
            +" FROM ourOwner, ddepoacnt_dbt dacnt, ddepoacnt_dbt dacntPart, ddepoac_dbt dpac, daccount_dbt acc, daccvanl_dbt accvanl, daccsub_dbt accsub, daccount_dbt accAct, ddepoacnt_dbt dacntAct " 
            +" WHERE dacnt.T_AUTOKEY = dacnt.t_Root "
            +" AND dacnt.t_opendate <= "+RepDateSQL
            +" AND dacnt.t_department IN ("+fltr.Departments+")"
            +" AND rsb_depo.depostatus( dacnt.T_AUTOKEY, "+RepDateSQL+") != 1 "
            +" AND rsi_rsb_account.restac( acc.t_Account, acc.T_CODE_CURRENCY, "+RepDateSQL+", acc.t_Chapter, null ) != 0 "
            +" AND DECODE(dacnt.t_owner, 0, "+String({OurBank})+", dacnt.t_owner) NOT IN (SELECT dp.t_PartyID from ddp_dep_dbt dp) "
            +" AND rsb_depo.depokindtype(dacnt.T_AUTOKEY) NOT IN ("+String(OBJTYPE_DEPOKINDTYPE_NOMINALKEEPER)+", "+String(OBJTYPE_DEPOKINDTYPE_FOREIGNNOMKEEPER)+")"
            +" AND dacnt.T_KIND = 2 "
            +" AND dpac.t_ID = dacnt.t_Type "
            +" AND acc.t_deporoot = dacnt.T_AUTOKEY "
            +" AND acc.t_chapter = 5 "
            +" AND dacntPart.t_AutoKey = acc.t_DepoAcc "
            +" AND accvanl.t_Account = acc.t_Account "
            +" AND accvanl.t_AnaliticsID = 2 " 
            +" AND accvanl.t_FIID = acc.t_Code_Currency "
            +" AND accvanl.t_Chapter = acc.t_Chapter "
            +" AND accsub.t_AccAnaliticsID = accvanl.t_AccAnaliticsID "
            +" AND accsub.t_SpecialType = 0 "
            +" AND accAct.t_Chapter = acc.t_Chapter "
            +" AND accAct.t_Code_Currency = acc.t_Code_Currency "
            +" AND accAct.t_Account = accsub.t_SubAccountCode "
            +" AND accAct.t_Open_Date <= "+RepDateSQL
            +" AND dacntAct.t_autokey = accAct.t_deporoot "
            +" AND ourOwner.t_PartyID (+)= dacntAct.t_Owner "
            +" AND rsi_rsb_account.restsa( accsub.t_AccAnaliticsID, accsub.t_SubAccountID, "+RepDateSQL+", 1 ) > 0 "
            +" GROUP BY acc.t_Code_Currency, dacntAct.t_Owner, DECODE(NVL(ourOwner.t_IsOur, 0), 0, dacntAct.t_Owner, "+String({OurBank})+"), rsb_depo.depokindtype(dacnt.T_AUTOKEY), dacnt.t_Owner, dpac.t_IsTrade) stor "
         +" WHERE digital.t_fiid = stor.t_fiid "
           +" AND fin.t_fiid = digital.t_fiid "
           +" AND avr.t_fiid = fin.t_parentfi "
           +" AND finPar.t_fiid = fin.t_parentfi " 
           +" AND finVal.t_fiid = finPar.t_facevaluefi)";
   
    SQL_Execute(query, "Сведения об уцп, цфа и иных цифровых правах, принадлежащих кредитной организации", true); 
    
    PostProcess();   
  end;
  
  macro GetQuerySelect()
    return "SELECT * FROM d711part4_tmp ORDER BY t_IssuerName, t_ParentReg, t_FaceValueCode, t_StoragePlaceName";
  end;
end;

/*Раздел 4.4*/
private class C_711PART4_4(flt_)
  private var fltr = flt_;
  private var tools = C_711Tools();
  
  private macro InsertNote(autoKeyPart4, flag)
    var query = "INSERT INTO d711part4_prot_tmp (t_autokeypart4, t_flag) VALUES("
                +String(autoKeyPart4)+",'"+flag+"')";
    
    SQL_Execute(query, "Протокол");
  end;

  private macro PostProcess()
    var cmd, dataSet, queryUpd = "";
    var pt:TRecHandler;
    var count = 0;
    var IssuerName = "", IssuerINN = "", IssuerOGRN = "", IssuerCountryCode = "", ParentIssuerName = "", ParentIssuerINN = "", ParentIssuerOGRN = "", ParentIssuerCountryCode = "", Type = "",ISIN = "", LSIN = "", Code711 = "", ParentRegNum = "",
    FaceValue = $0.0, ValueCode = "", OperINN = "";
    var IssuerINN_MARK = "", IssuerINN_TIN = "", IssuerNotResCode = "", OperINN_MARK = "", OperINN_TIN = "", OperNotResCode = "", ParentIssuerINN_MARK = "", ParentIssuerINN_TIN = "", ParentIssuerNotResCode = "";
    
    cmd = DL_RSDCommand("SELECT t_AutoKey, t_fiid, t_issuer, t_issuername, t_issuerinn, t_issuerogrn, t_issuercountrycode, t_parentfi, t_parentissuer, t_parentissuername, t_parentissuerinn, t_parentissuerogrn, t_parentissuercountrycode, t_parentfitype, t_ISIN, t_parentvalue, t_facevaluecode, t_operId, t_operinn FROM d711part4_tmp");
    
    dataSet = cmd.Execute();
    while(dataSet.moveNext())
      IssuerName = "";
      IssuerINN = dataSet.IssuerINN;
      IssuerOGRN = dataSet.IssuerOGRN;
      IssuerCountryCode = "";
      ParentIssuerName = "";
      ParentIssuerINN = dataSet.ParentIssuerINN;
      ParentIssuerOGRN = dataSet.ParentIssuerOGRN;
      ParentIssuerCountryCode = "";
      Type = "";
      Code711 = dataSet.ParentFiType;
      ParentRegNum = "";
      FaceValue = dataSet.ParentValue;
      ValueCode = dataSet.FaceValueCode;
      OperINN = dataSet.operINN;
      ISIN = dataSet.ISIN;
      IssuerINN_MARK = "";
      IssuerINN_TIN = "";
      IssuerNotResCode = "";
      OperINN_MARK = "";
      OperINN_TIN = "";
      OperNotResCode = "";
      ParentIssuerINN_MARK = "";
      ParentIssuerINN_TIN = "";
      ParentIssuerNotResCode = "";
      
      count = count + 1;
      
      pt = TRecHandler("party.dbt");
      // Эмитент
      if(ПолучитьСубъекта(dataSet.Issuer, pt) == 0)
        IssuerName = tools.GetPartyName(pt);
        //IssuerINN =; 
        tools.SplitINN_KPP(pt, IssuerINN, @IssuerINN, NULL, @IssuerINN_TIN, @IssuerNotResCode);
        IssuerINN_MARK = tools.GetIssuerINN_Mark(pt);
        if(IssuerOGRN == "")
          IssuerOGRN = "NN";
        end;
        IssuerCountryCode = GetCountryCode(pt);
      end;
      
      //Владелец ц/б
      if(ПолучитьСубъекта(dataSet.ParentIssuer, pt) == 0)
        ParentIssuerName = tools.GetIssuerName(pt, dataSet.ParentFi);
        tools.SplitINN_KPP(pt, ParentIssuerINN, @ParentIssuerINN, NULL, @ParentIssuerINN_TIN, @ParentIssuerNotResCode);
        ParentIssuerINN_MARK = tools.GetIssuerINN_Mark(pt);
        if(ParentIssuerOGRN == "")
          ParentIssuerOGRN = "NN";
        end;
        ParentIssuerCountryCode = GetCountryCode(pt);
      end;
      
      //Оператор ИС
      if(ПолучитьСубъекта(dataSet.operid, pt) == 0)
        tools.SplitINN_KPP(pt, OperINN, @OperINN, NULL, @OperINN_TIN, @OperNotResCode);
        OperINN_MARK = tools.GetIssuerINN_Mark(pt);
      end;
      
      Type = SetType(dataSet.Fiid, "");
      
      var fn = TRecHandler("fininstr.dbt");
      if((ПолучитьФинИн(dataSet.ParentFi, fn) == 0))
        LSIN = GetLSIN(dataSet.ParentFi);
        if(IsEmissive(dataSet.ParentFi))
          if((Code711 != "SHS7") AND (Code711 != "SHS71") AND (Code711 != "SHS8"))
            ParentRegNum = LSIN;
          else ParentRegNum = tools.CorrectLSINInvst(dataSet.ParentFi, LSIN);
          end;
        else
          ParentRegNum = "";
          if((Code711 == "ENC") or (Code711 == "ENC1") or (Code711 == "ENC2") or (Code711 == "ENC3"))
            ISIN = "";
            ParentRegNum = "";
          end;
        end;
      end;
      
      if(ParentIssuerCountryCode != "643")
        ParentRegNum = "";
      end;
      
      if((Code711 == "DR") OR (Code711 == "DR1") OR (Code711 == "DR2"))
        ParentRegNum = tools.GetLSINDEPO(dataSet.ParentFi);
      end;
      
      if(FI_IsISU(fn))
        tools.GetRULESREGXID(dataSet.ParentFi);
      end;
      
      tools.CorrectFaceValue(Code711, @FaceValue, @ValueCode, 2);
      
      InsertNote(dataSet.AutoKey, "");
      
      queryUpd = "UPDATE d711part4_tmp SET "
                  +" t_IssuerName = "+tools.GetSQLStr(IssuerName)+","
                  +" t_IssuerINN = "+tools.GetSQLStr(IssuerINN)+","
                  +" t_issuerogrn = "+tools.GetSQLStr(IssuerOGRN)+", "
                  +" t_IssuerCountryCode = "+tools.GetSQLStr(IssuerCountryCode)+","
                  +" t_ParentIssuerName = "+tools.GetSQLStr(ParentIssuerName)+","
                  +" t_ParentIssuerINN = "+tools.GetSQLStr(ParentIssuerINN)+","
                  +" t_parentissuerogrn = "+tools.GetSQLStr(ParentIssuerOGRN)+", "
                  +" t_ParentIssuerCountryCode = "+tools.GetSQLStr(ParentIssuerCountryCode)+","
                  +" t_OperINN = "+tools.GetSQLStr(OperINN)+","
                  +" t_Type = "+tools.GetSQLStr(Type)+","
                  +" t_ParentReg = "+tools.GetSQLStr(ParentRegNum)+", "
                  +" t_IssuerINN_Mark = "+tools.GetSQLStr(IssuerINN_Mark)+", "
                  +" t_IssuerINN_Tin = "+tools.GetSQLStr(IssuerINN_TIN)+", "
                  +" t_IssuerNotResCode = "+tools.GetSQLStr(IssuerNotResCode)+", "
                  +" t_OperINN_Mark = "+tools.GetSQLStr(OperINN_Mark)+", "
                  +" t_OperINN_Tin = "+tools.GetSQLStr(OperINN_TIN)+", "
                  +" t_OperNotResCode = "+tools.GetSQLStr(OperNotResCode)+", "
                  +" t_ParentIssuerINN_Mark = "+tools.GetSQLStr(ParentIssuerINN_Mark)+", "
                  +" t_ParentIssuerINN_Tin = "+tools.GetSQLStr(ParentIssuerINN_TIN)+", "
                  +" t_ParentIssuerNotResCode = "+tools.GetSQLStr(ParentIssuerNotResCode)
                  +IIF(FaceValue == $0.0, ", t_parentvalue ="+FaceValue+", t_facevaluecode ="+tools.GetSQLStr(ValueCode), "") //Если изменился номинал, обновляем поля таблицы
                  +IIF(ISIN=="", ", t_ISIN ="+tools.GetSQLStr(ISIN), "" )
               +" WHERE t_AutoKey = " + dataSet.AutoKey;
      
      SQL_Execute(queryUpd, "Обновление информации об об операциях с уцп, цфа и иными цифровыми правами, переданными кредитной организацией контрагентам на возвратной основе, принятыми кредитной организацией на возвратной основе" + String(count), false);
      
    end;
  end;
  
  macro PrepareData()
    var query, cmd;
    var RepDateSQL = GetSQLDate(fltr.RepDate);
    
    query = "INSERT INTO d711part4_tmp ( t_fiid, "
                                      +" t_issuer, "
                                      +" t_issuername, "
                                      +" t_issuerinn, "
                                      +" t_issuerogrn, "
                                      +" t_issuercountrycode, "
                                      +" t_type, "
                                      +" t_name, "
                                      +" t_ident, "
                                      +" t_other, "
                                      +" t_kind, "
                                      +" t_parentfi, "
                                      +" t_parentfitype, "
                                      +" t_parentissuer, "
                                      +" t_parentissuername, "
                                      +" t_parentissuerinn, "
                                      +" t_parentissuerogrn, "
                                      +" t_parentissuercountrycode, "
                                      +" t_parentreg, "
                                      +" t_isin, "
                                      +" t_facevalue, "
                                      +" t_facevaluecode, "
                                      +" t_parentvalue, "
                                      +" t_operid, "
                                      +" t_opername, "
                                      +" t_operinn, "
                                      +" t_insysname, "
                                      +" t_salerepo, "
                                      +" t_transloan, "
                                      +" t_buyrepo, "
                                      +" t_acceptloan, "
                                      +" t_transpledgebo, "
                                      +" t_transpledge, "
                                      +" t_acceptpledge, "
                                      +" t_restcor, "
                                      +" t_restoperban, "
                                      +" t_arrest, "
                                      +" t_prim) "
                         +"(SELECT fin.t_fiid, "
                              +" fin.t_issuer, "
                              +" chr(1), "
                              +" rsi_rsbparty.GetPartyCode(fin.t_issuer, 16), "
                              +" rsi_rsbparty.GetPartyCode(fin.t_issuer, 27), "
                              +" chr(1), "
                              +" chr(1), "
                              +" fin.t_name, "
                              +" digital.t_ident, "
                              +" digital.t_other, "
                              +" chr(1), "
                              +" fin.t_parentfi, "
                              +" rsb_secur.GetObjAttrName(12, 1,"
                              +"                         rsb_secur.GetMainObjAttr(12,"
                              +"                                                  LPAD(avr.t_FIID, 10, '0'),"
                              +"                                                  1, "+RepDateSQL+")), "
                              +" finPar.t_issuer, "
                              +" chr(1), "
                              +" rsi_rsbparty.GetPartyCode(finPar.t_issuer, 16), "
                              +" rsi_rsbparty.GetPartyCode(finPar.t_issuer, 27), "
                              +" chr(1), "
                              +" chr(1), "
                              +" avr.t_isin, "
                              +" finPar.t_facevaluefi, "
                              +" finVal.t_Iso_Number, "
                              +" NVL(rsb_fiinstr.FI_GetNominalOnDate(avr.t_FIID, "+RepDateSQL+" ), 0.0), "
                              +" digital.t_operinfosysid, "
                              +" chr(1), "
                              +" rsi_rsbparty.GetPartyCode(digital.t_operinfosysid, 16), "
                              +" digital.t_infosys, "
                              +" 0, "
                              +" 0, "
                              +" 0, "
                              +" 0, "
                              +" 0, "
                              +" 0, "
                              +" 0, "
                              +" stor.t_restcor, "
                              +" stor.t_restoperban, "
                              +" stor.t_arrest, "
                              +" chr(1) "
                         +" FROM dfininstr_dbt fin, ddigitala_dbt digital, dfininstr_dbt finPar, davoiriss_dbt avr, dfininstr_dbt finVal, "      
                             +" (SELECT "+ GetQueryForSub(fltr.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_CORPRESTRICT, true) + " as t_restcor, "
                                      + GetQueryForSub(fltr.BegDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_OPERBAN, false) + " as t_restoperban, "
                                      + GetQueryForSub(fltr.RepDate, RepDateSQL, LLCLASS_KIND_BLOCK_CB_ARREST, false) + " as t_arrest, "
                                      +" acc.t_Code_Currency as t_fiid"
                              +" FROM ddepoacnt_dbt dacnt, ddepoacnt_dbt dacntPart, ddepoac_dbt dpac, daccount_dbt acc, daccvanl_dbt accvanl, daccsub_dbt accsub, daccount_dbt accAct, ddepoacnt_dbt dacntAct "
                              +" WHERE dacnt.T_AUTOKEY = dacnt.t_Root "
                                +" AND dacnt.t_opendate <= "+RepDateSQL
                                +" AND dacnt.t_department IN ("+fltr.Departments+")"
                                +" AND rsb_depo.depostatus( dacnt.T_AUTOKEY, "+RepDateSQL+") != 1 "
                                +" AND rsi_rsb_account.restac( acc.t_Account, acc.T_CODE_CURRENCY, "+RepDateSQL+", acc.t_Chapter, null ) != 0 "
                                +" AND DECODE(dacnt.t_owner, 0, "+String({OurBank})+", dacnt.t_owner) NOT IN (SELECT dp.t_PartyID from ddp_dep_dbt dp) "
                                +" AND rsb_depo.depokindtype(dacnt.T_AUTOKEY) NOT IN ("+String(OBJTYPE_DEPOKINDTYPE_NOMINALKEEPER)+", "+String(OBJTYPE_DEPOKINDTYPE_FOREIGNNOMKEEPER)+")"
                                +" AND dacnt.T_KIND = 2 "
                                +" AND dpac.t_ID = dacnt.t_Type "
                                +" AND acc.t_deporoot = dacnt.T_AUTOKEY "
                                +" AND acc.t_chapter = 5 "
                                +" AND dacntPart.t_AutoKey = acc.t_DepoAcc "
                                +" AND accvanl.t_Account = acc.t_Account "
                                +" AND accvanl.t_AnaliticsID = 2 " 
                                +" AND accvanl.t_FIID = acc.t_Code_Currency "
                                +" AND accvanl.t_Chapter = acc.t_Chapter "
                                +" AND accsub.t_AccAnaliticsID = accvanl.t_AccAnaliticsID "
                                +" AND accsub.t_SpecialType = 0 "
                                +" AND accAct.t_Chapter = acc.t_Chapter "
                                +" AND accAct.t_Code_Currency = acc.t_Code_Currency "
                                +" AND accAct.t_Account = accsub.t_SubAccountCode "
                                +" AND accAct.t_Open_Date <= "+RepDateSQL
                                +" AND dacntAct.t_autokey = accAct.t_deporoot "
                                +" AND rsi_rsb_account.restsa( accsub.t_AccAnaliticsID, accsub.t_SubAccountID, "+RepDateSQL+", 1 ) > 0 "
                              +" GROUP BY acc.t_Code_Currency, dacntAct.t_Owner, rsb_depo.depokindtype(dacnt.T_AUTOKEY), dacnt.t_Owner, dpac.t_IsTrade) stor"
                         +" WHERE digital.t_fiid = stor.t_fiid "  
                           +" AND fin.t_fiid = digital.t_fiid "
                           +" AND avr.t_fiid = fin.t_parentfi "
                           +" AND finPar.t_fiid = fin.t_parentfi "
                           +" AND finVal.t_fiid = finPar.t_facevaluefi) ";
                           
    SQL_Execute(query, "Сведения об операциях с уцп, цфа и иными цифровыми правами, переданными кредитной организацией контрагентам на возвратной основе, принятыми кредитной организацией на возвратной основе", true); 
    
    PostProcess();
  end;
  
  macro GetQuerySelect()
    return "SELECT * FROM d711part4_tmp ORDER BY t_IssuerName, t_ParentReg, t_FaceValueCode";
  end;
end;

class C_711PART4()
  var Эмитент_ЦА:string                                                           = "",
      ИНН_Эмитента_ЦА:string                                                      = "",
      ОГРН_Эмитента_ЦА:string                                                     = "",
      КодСтраны_Эмитента_ЦА:string                                                = "",
      Наименование_Оператора:string                                               = "",
      ИНН_Оператора:string                                                        = "",
      Наименование_платформы:string                                               = "",
      Тип_ЦБ:string                                                               = "",
      Вид_требования:string                                                       = "",
      Идентификационный_номер_ЦА:string                                           = "",
      Обозначение_ЦС:string                                                       = "",
      КодВалюты_ЦС:string                                                         = "",
      Количество_УЦП_в_ЦС:numeric                                                 = $0.0,
      Количетсво_ЦС_Выпущенных_депозитарием:numeric                               = $0.0,
      Наименование_ЦА:string                                                      = "",
      Вид_ИныхЦФА:string                                                          = "",
      Вид_ФИ:string                                                               = "",
      Эмитент:string                                                              = "",
      ЭмитентИНН:string                                                           = "",      
      ЭмитентОГРН:string                                                          = "",
      ЭмитентОКСМ:string                                                          = "",
      ЦБНомерГосРег:string                                                        = "",
      ЦБISIN:string                                                               = "",
      ЦБВалюта:string                                                             = "",
      ЦБНоминал:numeric                                                           = $0.0,
      Наименование_Регистратора:string                                            = "",
      ИНН_Регистратора:string                                                     = "",
      КолвоЦА_на_счетеДепо:numeric                                                = $0.0,
      КолвоЦА_Всего_с_ограничениями:numeric                                       = $0.0,
      КолвоЦА_Взалоге:numeric                                                     = $0.0,
      КолвоЦА_ограничение_эмитентом:numeric                                       = $0.0,
      КолвоЦА_запрет_операций:numeric                                             = $0.0,
      КолвоЦА_под_арестом:numeric                                                 = $0.0,
      Вид_счетаДепо:string                                                        = "",
      Информация_оВладельце_счетаДепо:string                                      = "",
      КодСтраны_Владельца_счетаДепо:string                                        = "",
      Колво_операций_сЦА_зачисление:numeric                                       = $0.0,
      Объем_операций_сЦА_зачисление:numeric                                       = $0.0,
      Колво_операций_сЦА_списание:numeric                                         = $0.0,
      Объем_операций_сЦА_списание:numeric                                         = $0.0,
      Балансовая_стоимость_ЦФА:numeric                                            = $0.0,
      Колво_ЦФА_Всего_у_КО_на_балансе:numeric                                     = $0.0,
      Колво_ЦФА_Всего_у_КО_вне_баланса_по_РЕПО:numeric                            = $0.0,
      Колво_ЦФА_Всего_у_КО_вне_баланса_по_сделкам_займа:numeric                   = $0.0,
      Колво_ЦФА_Всего_у_КО_вне_баланса_с_погашенными_обязательствами:numeric      = $0.0,
      Колво_ЦФА_Всего_у_КО_вне_баланса_безнадежные_долги:numeric                  = $0.0,
      Колво_ЦФА_Всего_у_КО_вне_баланса_ошибочно_зачисленные:numeric               = $0.0,
      Колво_ЦФА_Всего_у_КО_вне_баланса_иное:numeric                               = $0.0,
      Наименование_организации_ведущей_учет:string                                = "",
      признак_организации_ведущей_учет:string                                     = "",
      ИНН_организации_ведущей_учет:string                                         = "",
      ОРГН_организации_ведущей_учет:string                                        = "",
      Код_страны_организации_ведущей_учет:string                                  = "",
      Номер_лицензии_организации_ведущей_учет:string                              = "",
      Колво_ЦФА_Всего_у_КО_переданных_по_пРЕПО:numeric                            = $0.0,
      Колво_ЦФА_Всего_у_КО_переданных_по_сделкам_займа:numeric                    = $0.0,
      Колво_ЦФА_Всего_у_КО_полученных_по_оРЕПО:numeric                            = $0.0,
      Колво_ЦФА_Всего_у_КО_полученных_по_сделкам_займа:numeric                    = $0.0,
      Колво_ЦФА_Всего_у_КО_переданных_взалог_пообязательстам_КО:numeric           = $0.0,
      Колво_ЦФА_Всего_у_КО_переданных_взалог_пообязательстам_Ктретьихлиц:numeric  = $0.0,
      Колво_ЦФА_Всего_у_КО_принятых_взалог:numeric                                = $0.0,
      Примечание_при_отсутств_информации:string                                   = "",
      ЭмитентаЦА_TIN:string                                                       = "",
      ЭмитентаЦА_ПризнакЭмитента:string                                           = "",
      ЭмитентаЦА_ПризнакКодаЭмНерез:string                                        = "",
      Оператор_TIN:string                                                         = "",
      Оператор_Признак:string                                                     = "",
      Оператор_ПризнакКодаНерез:string                                            = "",
      Эмитента_TIN:string                                                         = "",
      Эмитента_ПризнакЭмитента:string                                             = "",
      Эмитента_ПризнакКодаЭмНерез:string                                          = "",
      Регистратор_TIN:string                                                      = "",
      Регистратор_Признак:string                                                  = "",
      Регистратор_ПризнакКодаНерез:string                                         = "",
      ОргВедУчет_TIN:string                                                       = "",
      ОргВедУчет_Признак:string                                                   = "",
      ОргВедУчет_ПризнакКодаНерез:string                                          = "",
      
      Протокол:TArray                                                             = TArray();
      
  class TProtocol(Ошибка, ВидСчета, Владелец, КодЦА, КолЦА, Строка, Орг, БалС, ПРЕПО, ПерЗайм, ОРЕПО, ПолЗайм, ЗалогКО, ЗалогТЛ, Залог, Ограничено, Запрет, Арест)
   var Протокол_ошибка:string                                    = Ошибка,
       Протокол_видлицевогосчета:string                          = ВидСчета,
       Протокол_владелец:string                                  = Владелец,
       Протокол_КодЦА:string                                     = КодЦА,
       Протокол_КоличествоЦА:string                              = КолЦА,
       Протокол_строка:string                                    = Строка,
       Протокол_наименованиеОрганизации:string                   = Орг,
       Протокол_БалансоваяСтоимостьЦА:string                     = БалС,
       Протокол_ПРЕПО:string                                     = ПРЕПО,
       Протокол_переданныхЗайм:string                            = ПерЗайм,
       Протокол_ОРЕПО:string                                     = ОРЕПО,
       Протокол_полученныхЗайм:string                            = ПолЗайм,
       Протокол_переданнныхЗалогОбязательстваКО:string           = ЗалогКО,
       Протокол_переданнныхЗалогОбязательстваТретьихЛиц:string   = ЗалогТЛ,
       Протокол_принятыхЗалог:string                             = Залог,
       Протокол_распоряжениеОграничено:string                    = Ограничено,
       Протокол_запретОпераций:string                            = Запрет,
       Протокол_арест:string                                     = Арест;
  end;

  private var flt = Filter;
  private var objData = null;
  private var DataRec = null;

  private macro GetProtocol(autoKey):TArray
    var prot = TArray();
    var cmd, dataSet;
    
    cmd = DL_RSDCommand("SELECT * FROM d711part4_prot_tmp WHERE t_autokeypart4 = ?");
    cmd.addParam(autoKey);
    
    dataSet = cmd.Execute();
    while(dataSet.moveNext())
      prot[prot.size] = TProtocol(dataSet.Flag, "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "");
    end;
    
    return prot;
  end;

  private macro getDepoAccountKind(value)
    if (value == "OWNER")
          return "01";
      elif (value == "DEPOPROG")
          return "02";
      elif (value == "TRUSTEE")
          return "03";
      elif (value == "ISSUER")
          return "04";
      elif (value == "EMISSION")
          return "05";
      elif (value == "DEPOSIT")
          return "06";
      elif (value == "TRANSIT")
          return "07";
      elif (value == "NOMINEE")
          return "08";
      elif (value == "FNOMINEE")
          return "09";
      elif (value == "FAUTHOLDER")
          return "10";
      elif (value == "NONE")
          return "11";
      elif (value == "OTHER")
          return "12";
      elif (value == "HOLDER")
          return "13";
      elif (value == "SUBOWNER")
          return "14";
      elif (value == "SUBTRUSTEE")
          return "15";
    end;

    return "";
  end;
  
  private macro SetValues()
    Эмитент_ЦА                                                           = DataRec.IssuerName;
    ИНН_Эмитента_ЦА                                                      = DataRec.IssuerINN;
    ОГРН_Эмитента_ЦА                                                     = DataRec.IssuerOGRN;
    КодСтраны_Эмитента_ЦА                                                = DataRec.IssuerCountryCode;
    Наименование_Оператора                                               = DataRec.OperName;
    ИНН_Оператора                                                        = DataRec.OperINN;
    Наименование_платформы                                               = DataRec.InSysName;
    Тип_ЦБ                                                               = DataRec.Type;
    Вид_требования                                                       = DataRec.Kind;
    Идентификационный_номер_ЦА                                           = DataRec.UdrIdent;
    Обозначение_ЦС                                                       = DataRec.Ident;
    КодВалюты_ЦС                                                         = DataRec.FaceValueCode;
    Количество_УЦП_в_ЦС                                                  = DataRec.NumBaseFi;
    Количетсво_ЦС_Выпущенных_депозитарием                                = DataRec.Count;
    Наименование_ЦА                                                      = DataRec.Name;
    Вид_ИныхЦФА                                                          = DataRec.Other;
    Вид_ФИ                                                               = DataRec.ParentFiType;
    Эмитент                                                              = DataRec.ParentIssuerName;
    ЭмитентИНН                                                           = DataRec.ParentIssuerINN;      
    ЭмитентОГРН                                                          = DataRec.ParentIssuerOGRN;
    ЭмитентОКСМ                                                          = DataRec.ParentIssuerCountryCode;
    ЦБНомерГосРег                                                        = DataRec.ParentReg;
    ЦБISIN                                                               = DataRec.ISIN;
    ЦБВалюта                                                             = DataRec.FaceValueCode;
    ЦБНоминал                                                            = DataRec.ParentValue;
    Наименование_Регистратора                                            = DataRec.StoragePlaceName;
    ИНН_Регистратора                                                     = DataRec.StoragePlaceINN;
    КолвоЦА_на_счетеДепо                                                 = DataRec.Amount;
    КолвоЦА_Всего_с_ограничениями                                        = DataRec.Count;
    КолвоЦА_Взалоге                                                      = DataRec.RestPawn;
    КолвоЦА_ограничение_эмитентом                                        = DataRec.RestCor;
    КолвоЦА_запрет_операций                                              = DataRec.RestOperBan;
    КолвоЦА_под_арестом                                                  = DataRec.Arrest;
    Вид_счетаДепо                                                        = DataRec.DepoKind;
    Информация_оВладельце_счетаДепо                                      = DataRec.Sector;
    КодСтраны_Владельца_счетаДепо                                        = DataRec.OwnerCountryCode;
    Колво_операций_сЦА_зачисление                                        = DataRec.Receivquant;
    Объем_операций_сЦА_зачисление                                        = DataRec.Receivamount;
    Колво_операций_сЦА_списание                                          = DataRec.Withdrawquant;
    Объем_операций_сЦА_списание                                          = DataRec.Withdrawamount;
    Балансовая_стоимость_ЦФА                                             = DataRec.Balance;
    Колво_ЦФА_Всего_у_КО_на_балансе                                      = DataRec.Ouramount;
    Колво_ЦФА_Всего_у_КО_вне_баланса_по_РЕПО                             = DataRec.Repoamount;
    Колво_ЦФА_Всего_у_КО_вне_баланса_по_сделкам_займа                    = DataRec.Repopawn;
    Колво_ЦФА_Всего_у_КО_вне_баланса_с_погашенными_обязательствами       = DataRec.Repopledge;
    Колво_ЦФА_Всего_у_КО_вне_баланса_безнадежные_долги                   = DataRec.Repodebt;
    Колво_ЦФА_Всего_у_КО_вне_баланса_ошибочно_зачисленные                = DataRec.Repowrong;
    Колво_ЦФА_Всего_у_КО_вне_баланса_иное                                = DataRec.Repoother;
    Наименование_организации_ведущей_учет                                = DataRec.AccPlaceName;
    Признак_организации_ведущей_учет                                     = DataRec.AccPlaceMark;
    ИНН_организации_ведущей_учет                                         = DataRec.AccPlaceINN;
    ОРГН_организации_ведущей_учет                                        = DataRec.AccPlaceOGRN;
    Код_страны_организации_ведущей_учет                                  = DataRec.AccPlaceCountryCode;
    Номер_лицензии_организации_ведущей_учет                              = DataRec.AccPlaceLicense;
    Колво_ЦФА_Всего_у_КО_переданных_по_пРЕПО                             = DataRec.Salerepo;
    Колво_ЦФА_Всего_у_КО_переданных_по_сделкам_займа                     = DataRec.Transloan;
    Колво_ЦФА_Всего_у_КО_полученных_по_оРЕПО                             = DataRec.Buyrepo;
    Колво_ЦФА_Всего_у_КО_полученных_по_сделкам_займа                     = DataRec.Acceptloan;
    Колво_ЦФА_Всего_у_КО_переданных_взалог_пообязательстам_КО            = DataRec.Transpledgebo;
    Колво_ЦФА_Всего_у_КО_переданных_взалог_пообязательстам_Ктретьихлиц   = DataRec.Transpledge;
    Колво_ЦФА_Всего_у_КО_принятых_взалог                                 = DataRec.Acceptpledge;
    Примечание_при_отсутств_информации                                   = DataRec.Prim;
    ЭмитентаЦА_TIN                                                       = DataRec.IssuerINN_TIN;
    ЭмитентаЦА_ПризнакЭмитента                                           = DataRec.IssuerINN_MARK;
    ЭмитентаЦА_ПризнакКодаЭмНерез                                        = DataRec.IssuerNotResCode;
    Оператор_TIN                                                         = DataRec.OperINN_TIN;
    Оператор_Признак                                                     = DataRec.OperINN_MARK;
    Оператор_ПризнакКодаНерез                                            = DataRec.OperNotResCode;
    Эмитента_TIN                                                         = DataRec.ParentIssuerINN_TIN;
    Эмитента_ПризнакЭмитента                                             = DataRec.ParentIssuerINN_MARK;
    Эмитента_ПризнакКодаЭмНерез                                          = DataRec.ParentIssuerNotResCode;
    Регистратор_TIN                                                      = DataRec.StoragePlaceINN_TIN;
    Регистратор_Признак                                                  = DataRec.StoragePlaceINN_MARK;
    Регистратор_ПризнакКодаНерез                                         = DataRec.StoragePlaceNotResCode;
    ОргВедУчет_TIN                                                       = DataRec.AccPlaceINN_TIN;
    ОргВедУчет_Признак                                                   = DataRec.AccPlaceINN_MARK;
    ОргВедУчет_ПризнакКодаНерез                                          = DataRec.AccPlaceNotResCode;

    Протокол                                                             = GetProtocol(DataRec.AutoKey);
  end;
  
  private macro PrepareData()
    SQL_Truncate("d711part4_tmp");
    SQL_Truncate("d711part4_prot_tmp");
    
    if(PART_4_1 == flt.RepPart)
      objData = C_711PART4_1(flt);
    elif(PART_4_2 == flt.RepPart)
      objData = C_711PART4_2(flt);
    elif(PART_4_2_1 == flt.RepPart)
     objData = C_711PART4_2_1(flt);
    elif(PART_4_3 == flt.RepPart)
     objData = C_711PART4_3(flt);
    elif(PART_4_4 == flt.RepPart)
     objData = C_711PART4_4(flt);
    end;
    
    if(null != objData)
      objData.PrepareData();
    end;
  end;
  
  macro SetFilter(_Departments:TArray, _BegDate:date, _RepDate:date, _RepPart:integer)
    if (ValType(_Departments) != V_UNDEF)
      flt.Departments = "";
      for(var dep, _Departments)
        if (flt.Departments != "")
          flt.Departments = flt.Departments + ",";
        end;
        flt.Departments = string(flt.Departments) + string(dep);
      end;
    end;
    if (ValType(_BegDate) != V_UNDEF)
      flt.BegDate = _BegDate;
    end;
    if (ValType(_RepDate) != V_UNDEF)
      flt.RepDate = _RepDate;
    end;
    if (ValType(_RepPart) != V_UNDEF)
      flt.RepPart = _RepPart;
    end;
  end;

  macro GetFirst():bool
    var stat = 0;
    PrepareData();

    DataRec = TRsbDataSet(objData.GetQuerySelect());

    stat = DataRec.moveNext();
    if(stat)
      SetValues();
    end;

    return stat;
  end;

  macro GetNext():bool
    var stat = 0;
    stat = DataRec.moveNext();
    if(stat)
      SetValues();
    end;

    return stat;
  end;
end;

/*var deps = TArray();
var obj = null;
var stat = false;
deps[deps.size] = {OperDprt};
obj = C_711PART4();
obj.SetFilter(deps, date(01,01,2023), date(20,02,2023), 3);
stat = obj.GetFirst();
end;
*/