/*
$Name:         dl_report_TrnA_G.mac
$Module:       БО ЦБ/ФИССиКО/УВ
$Description:  Отчет "Отчет-сверка проводок глав А и Г"
*/

IMPORT "DLReport_h.mac", "dl_Report_TrnA_G_Form.mac", "dl_report_log.mac", oralib, "dv_categ.mac", "vatickfd.mac", "scsrvrepfun.mac";

PRIVATE VAR ReportHeader = 
" ########################################################                                                              \n" + 
"                                                                                                                       \n" +
"                                    ################################################################################## \n";

PRIVATE VAR TableHeader = 
"┌────────────────────────────────┬───────────────────────────────────────────┬──────────────────────────────┬───────────────────────────────┬──────────────────────────────────────┐\n"+
"│          Номер сделки          │                Вид операции               │    Дата заключения сделки    │    Дата исполнения сделки     │              Примечание              │\n"+
"│                                │                                           │                              │                               │                                      │\n"+
"├────────────────────────────────┼───────────────────────────────────────────┼──────────────────────────────┼───────────────────────────────┼──────────────────────────────────────┤";

PRIVATE VAR ReportExecutor = 
" ##################################################################################\n";

PRIVATE CONST Id_Sec = "S", Id_DV = "Ю", Id_VA = "N";

PRIVATE VAR
  m_Date:DATE,
  m_DepartmentID:INTEGER,
  IsSec:STRING,
  IsDV:STRING,
  IsVA:STRING,
  IsApostr:STRING,
  IsExcel:STRING;

PRIVATE VAR Report_TrnA_G_Form;

PRIVATE MACRO Операционист()
  var RS = TRsbDataSet("SELECT person.t_Name " +
                       "  FROM dperson_dbt person " +
                       " WHERE person.t_Oper = " + string({oper})
                       );

  if( RS.MoveNext() )
    return RS.Name;
  end;
  return "";
END;

PRIVATE MACRO ПолучитьНазваниеПодсист(IdentProg)
  if((IdentProg == Id_Sec))
    return "\"Бэк-офис ценных бумаг\"";
  elif((IdentProg == Id_DV))
    return "\"ФИССиКО\"";
  elif((IdentProg == Id_VA))
    return "\"Учтенные векселя\"";
  end;
  return "";
END;


PRIVATE MACRO ПолучитьКУ(Kind, cmd:DL_RSDCommand)
  if(Kind == 0)
  return  "SELECT CAT.T_ID T_CATID " +
          "  FROM DMCCATEG_DBT CAT " +
          " WHERE CAT.T_CODE IN (" + cmd.AddParam("+Форвард, дрейф Проц.СВОП") + "," + cmd.AddParam("-Форвард, дрейф Проц.СВОП") + ", " +
                                     cmd.AddParam("+Форвард, дрейф") + "," +           cmd.AddParam("-Форвард, дрейф") + ", " +
                                     cmd.AddParam("+Форвард, дрейф внебирж") + "," +   cmd.AddParam("-Форвард, дрейф внебирж") + ", " +
                                     cmd.AddParam("+Форвард, дрейф внебирж0") + "," +  cmd.AddParam("-Форвард, дрейф внебирж0") + ", " +
                                     cmd.AddParam("+Форвард, дрейф0") + ", " +
                                     cmd.AddParam("+Форвард, дрейф внебирж1") + "," +  cmd.AddParam("-Форвард, дрейф внебирж1") + ", " +
                                     cmd.AddParam("+Форвард, дрейф1") + "," +          cmd.AddParam("-Форвард, дрейф1") + ", " +
                                     cmd.AddParam("+Форвард, ПФИ внебирж") + "," +     cmd.AddParam("-Форвард, ПФИ внебирж") + ", " +
                                     cmd.AddParam("+Форвард, ОИ") + "," +              cmd.AddParam("-Форвард, ОИ") + ", " +
                                     cmd.AddParam("+Форвард, прочие") + "," +          cmd.AddParam("-Форвард, прочие") + ", " +
                                     cmd.AddParam("+Форвард, ПФИ") + "," +             cmd.AddParam("-Форвард, ПФИ") + ", " +
                                     cmd.AddParam("+Форвард, ФО") + "," +              cmd.AddParam("-Форвард, ФО") + ", " +
                                     cmd.AddParam("+Форвард, ПФИ0") + ", " +
                                     cmd.AddParam("+Форвард, прочие0") + "," +         cmd.AddParam("-Форвард, прочие0") + ", " +
                                     cmd.AddParam("+Форвард, ПФИ1") + "," +            cmd.AddParam("-Форвард, ПФИ1") + ", " +
                                     cmd.AddParam("+Форвард, прочие1") + "," +         cmd.AddParam("-Форвард, прочие1") + ", " +
                                     cmd.AddParam("+Форвард,дрейф внебирж ПП") + "," + cmd.AddParam("-Форвард,дрейф внебирж ПП") + ")";
  elif(Kind == 1)
  return  "SELECT CAT.T_ID T_CATID " +
          "          FROM DMCCATEG_DBT CAT " +
          "         WHERE CAT.T_CODE IN (" + cmd.AddParam("+Форвард, расчеты") + "," +   cmd.AddParam("-Форвард, расчеты") + ", " +
                                             cmd.AddParam("+Форвард, расчеты0") + "," +  cmd.AddParam("-Форвард, расчеты0") + ", " +
                                             cmd.AddParam("+Форвард, расчеты1") + "," +  cmd.AddParam("-Форвард, расчеты1") + ", " +
                                             cmd.AddParam("+Форвард, расчеты0Б") + "," + cmd.AddParam("-Форвард, расчеты0Б") + ", " +
                                             cmd.AddParam("+Форвард, расчетыДМ") + "," + cmd.AddParam("-Форвард, расчетыДМ") + ") ";
  elif(Kind == 2)
  return  "SELECT CAT.T_ID T_CATID " +
          "          FROM DMCCATEG_DBT CAT " +
          "         WHERE CAT.T_CODE IN (" + cmd.AddParam("+Форвард, РПИ") + ", " +    cmd.AddParam("-Форвард, РПИ") + ", " +
                                             cmd.AddParam("+Форвард, РПИ ФО") + ", " + cmd.AddParam("-Форвард, РПИ ФО") + ", " +
                                             cmd.AddParam("+Форвард, РПИ1") + "," +    cmd.AddParam("-Форвард, РПИ1") + ") ";
  elif(Kind == 3)
  return  "SELECT CAT.T_ID T_CATID " +
          "          FROM DMCCATEG_DBT CAT " +
          "         WHERE CAT.T_CODE IN (" + cmd.AddParam("+Форвард, РПИ") + "," +      cmd.AddParam("-Форвард, РПИ") + ", " +
                                             cmd.AddParam("+Форвард, РПИ1") + "," +     cmd.AddParam("-Форвард, РПИ1") + ", " +
                                             cmd.AddParam("+Форвард, расчеты") + "," +  cmd.AddParam("-Форвард, расчеты") + ", " +
                                             cmd.AddParam("+Форвард, расчеты0") + "," + cmd.AddParam("-Форвард, расчеты0") + ", " +
                                             cmd.AddParam("+Форвард, расчеты1") + "," + cmd.AddParam("-Форвард, расчеты1") + ") ";
  elif(Kind == 4)
  return  "SELECT CAT.T_ID T_CATID " +
          "          FROM DMCCATEG_DBT CAT " +
          "         WHERE CAT.T_CODE IN (" + cmd.AddParam("Выбытие ПФИ") + "," + cmd.AddParam("Выбытие ПФИ1") + "," + cmd.AddParam("Выбытие ПФИ ОЭБ") + ") ";
  elif(Kind == 5)
  return  "SELECT CAT.T_ID T_CATID " +
          "          FROM DMCCATEG_DBT CAT " +
          "         WHERE CAT.T_CODE IN (" + cmd.AddParam("+ПФИ ФО") + ", " + cmd.AddParam("-ПФИ ФО") + ") ";
  elif(Kind == 6)
  return  "SELECT CAT.T_ID T_CATID " +
          "          FROM DMCCATEG_DBT CAT " +
          "         WHERE CAT.T_CODE IN (" + cmd.AddParam("+Форвард, РПИ ФО") + "," + cmd.AddParam("-Форвард, РПИ ФО") + ", " +
                                             cmd.AddParam("Реализация, ц/б") + "," +  cmd.AddParam("Выбытие ПФИ") + "," + cmd.AddParam("Выбытие ДМ") + ") ";
  elif(Kind == 7)
  return  "SELECT CAT.T_ID T_CATID " +
          "          FROM DMCCATEG_DBT CAT " +
          "         WHERE CAT.T_CODE IN (" + cmd.AddParam("+ПФИ") + "," +     cmd.AddParam("-ПФИ") + ", " +
                                             cmd.AddParam("+ПФИ1") + "," +    cmd.AddParam("-ПФИ1") + ", " +
                                             cmd.AddParam("+ПФИ0") + "," +    cmd.AddParam("-ПФИ0") + ", " +
                                             cmd.AddParam("+ПФИ ОЭБ") + "," + cmd.AddParam("-ПФИ ОЭБ") + ") ";
  elif(Kind == 8)
  return  "SELECT CAT.T_ID T_CATID " +
          "          FROM DMCCATEG_DBT CAT " +
          "         WHERE CAT.T_CODE IN (" + cmd.AddParam("Выбытие ПФИ") + "," + cmd.AddParam("Выбытие ПФИ1") + "," + cmd.AddParam("Выбытие ПФИ ОЭБ") + ") ";
  end;
  return "";
END;

PRIVATE MACRO РАЗНОВАЛЮТ()
    const RegPath = "ПРОИЗВОДНЫЕ ИНСТРУМЕНТЫ\\УЧЕТ_РАЗНОВАЛЮТ_БАНКНОТ_СДЕЛОК";
    var DiffCur = "", err;
    GetRegistryValue( RegPath, V_BOOL, DiffCur, err );
    
    if ( err != 0 )
        MsgBox( "Ошибка при получении значения настройки \"" + RegPath + "\"" );
    else
        if ( DiffCur == "X" )
            return 1;
        else
            return 0;
        end;
    end;
end;

PRIVATE CLASS ( DL_CReportTemplate ) DL_Report_TrnA_G( Form:DL_CPanel, TemplateName:STRING, UseCSV:BOOL, IsWebService:BOOL, ReportHashCode:INTEGER, UsePOI:BOOL )
    var ErrorCount;
    Var CurDate = date(), CurTime = time(),
    m_CurrSheetName = "";
    var CurLog = DL_ReportLog(ReportBIQ8582_TrnA_G, CurDate, CurTime, m_Date);
    

    PRIVATE MACRO PrintMode():INTEGER
        if (IsExcel == SET_CHAR)
          return DL_OUTREPORT_EXCEL;
        end;
        return DL_OUTREPORT_STD;
    END;

    PRIVATE MACRO PrintLine(A1, A2, A3, A4, A5)
      ErrorCount = ErrorCount + 1;
      PrintTableLine( "N1_A1",  A1, null,
                      "N1_A2",  A2, null,
                      "N1_A3",  A3, null,
                      "N1_A4",  A4, null,
                      "N1_A5",  A5, null);
    END;

    PRIVATE MACRO UpdateOrInsert(CurRec, Note, IsUpdate)
      var Query = "", cmd;
      if(IsUpdate)
        Query = "UPDATE DDL_REPORT_TRNA_G_TMP SET T_NOTE = ? WHERE T_DEALID = ? AND T_DOCKIND = ?";
        cmd = RSDCommand(Query);
        cmd.AddParam("", RSDBP_IN, Note);
        cmd.AddParam("", RSDBP_IN, CurRec.DealID);
        cmd.AddParam("", RSDBP_IN, CurRec.DocKind);
        cmd.execute();
      else
        Query = "INSERT INTO DDL_REPORT_TRNA_G_TMP (T_IDENTPROG, " +
                            "           T_DEALID, " +
                            "           T_DOCKIND, " +
                            "           T_DEALCODE, " +
                            "           T_NAME, " +
                            "           T_DEALDATE, " +
                            "           T_EXECDATE, " +
                            "           T_NOTE) " +
                "VALUES (?,?,?,?,?,?,?,?)";
        cmd = RSDCommand(Query);  
        cmd.AddParam("", RSDBP_IN, CurRec.IdentProg);
        cmd.AddParam("", RSDBP_IN, CurRec.DealID);
        cmd.AddParam("", RSDBP_IN, CurRec.DocKind);
        cmd.AddParam("", RSDBP_IN, CurRec.DealCode);
        cmd.AddParam("", RSDBP_IN, CurRec.Name);
        cmd.AddParam("", RSDBP_IN, CurRec.DealDate);
        cmd.AddParam("", RSDBP_IN, CurRec.ExecDate);
        cmd.AddParam("", RSDBP_IN, Note);
        cmd.execute();
      end;
    END;

    PRIVATE MACRO ПостановкаГ(CurRec, IsUpdate:@bool)
      var TrnQuery = "";
      var Trn_cmd = DL_RSDCommand();

      var FD;
      var Trn_count = 0;
      var Q1ч_СВОП = 0, QПП_СВОП_зач_Г = 0, Qзач_Г = 0;
      if (CurRec.DealDate == m_Date)
        TrnQuery = TrnQuery +
            "SELECT /*+ leading(categ,accdoc,acc,TRN) index(accdoc DMCACCDOC_DBT_IDX4)*/ TRN.* " + 
            "  FROM ( " + ПолучитьКУ(0, Trn_cmd) + " ) " + 
            "       categ, " + 
            "       dmcaccdoc_dbt accdoc, " + 
            "       dacctrn_dbt trn, " + 
            "       daccount_dbt ac " + 
            " WHERE TRN.T_ACCTRNID IN ( " + 
            "                  SELECT NVL(DOC.T_ACCTRNID, -1) " + 
            "                    FROM DOPROPER_DBT oper, doprdocs_dbt doc " + 
            "                   WHERE OPER.T_DOCKIND = " + Trn_cmd.AddParam(CurRec.DocKind) + " AND OPER.T_DOCUMENTID = LPAD(TO_CHAR(" + Trn_cmd.AddParam(CurRec.DealID) + "), 34, '0') AND DOC.T_ID_OPERATION = OPER.T_ID_OPERATION AND DOC.T_DOCKIND = " + DLDOC_CARRY + 
            "                   UNION " + 
            "                  SELECT NVL(grdoc.T_DOCID, -1) " + 
            "                    FROM DDLGRDOC_DBT grdoc, DDLGRDEAL_DBT grdeal " + 
            "                   WHERE grdeal.T_DOCKIND = " + Trn_cmd.AddParam(CurRec.DocKind) + " AND grdeal.T_DOCID = " + Trn_cmd.AddParam(CurRec.DealID) + " AND grdoc.T_GRDEALID = grdeal.T_ID AND grdoc.T_DOCKIND = " + DLDOC_CARRY + 
            "                         ) " +
            "       AND TRN.T_DATE_CARRY = " + Trn_cmd.AddParam(m_Date) +
            "       AND (   AC.T_ACCOUNTID = TRN.T_ACCOUNTID_PAYER " + 
            "            OR AC.T_ACCOUNTID = TRN.T_ACCOUNTID_RECEIVER) " + 
            "       AND ACCDOC.T_DOCID = " + Trn_cmd.AddParam(CurRec.DealID) +
            "       AND ACCDOC.T_DOCKIND = " + Trn_cmd.AddParam(CurRec.DocKind) +
            "       AND ACCDOC.T_CATID = categ.T_CATID " + 
            "       AND ACCDOC.T_ACCOUNT = AC.T_ACCOUNT " + 
            "       AND ACCDOC.T_CHAPTER = AC.T_CHAPTER ";
        if (CurRec.DocKind == 199)
          FD = DVFirstDocNDeal(CurRec.DocKind, CurRec.DealID);
          if (FD.IsPctSWAP())
            TrnQuery = TrnQuery +
                "UNION ALL  " + 
                "SELECT  TRN.* " + 
                "  FROM ( " + ПолучитьКУ(0, Trn_cmd) + " ) " + 
                "       categ, " + 
                "       dmcaccdoc_dbt accdoc, " + 
                "       dacctrn_dbt trn, " + 
                "       daccount_dbt ac, " + 
                "       doprdocs_dbt doc, " + 
                "       DOPROPER_DBT oper, " + 
                "       DDVNPMGR_DBT pmgr " + 
                " WHERE     OPER.T_DOCKIND = " + Trn_cmd.AddParam(CurRec.DocKind) +
                "       AND OPER.T_DOCUMENTID = LPAD(TO_CHAR(" + Trn_cmd.AddParam(CurRec.DealID) + "), 34, '0') " +
                "       AND DOC.T_ID_OPERATION = OPER.T_ID_OPERATION " + 
                "       AND TRN.T_ACCTRNID = DOC.T_ACCTRNID " + 
                "       AND TRN.T_DATE_CARRY = " + Trn_cmd.AddParam(m_Date) +
                "       AND (   AC.T_ACCOUNTID = TRN.T_ACCOUNTID_PAYER " + 
                "            OR AC.T_ACCOUNTID = TRN.T_ACCOUNTID_RECEIVER) " + 
                "       AND PMGR.T_DEALID = " + Trn_cmd.AddParam(CurRec.DealID) +
                "       AND ACCDOC.T_DOCID = PMGR.T_ID " + 
                "       AND ACCDOC.T_DOCKIND = 4811 " + 
                "       AND ACCDOC.T_CATID = categ.T_CATID " + 
                "       AND ACCDOC.T_ACCOUNT = AC.T_ACCOUNT " + 
                "       AND ACCDOC.T_CHAPTER = AC.T_CHAPTER  ";
          end;
        end;
        
/*        Trn_cmd = DL_RSDCommand(TrnQuery);  
        Trn_cmd.AddParam(CurRec.DocKind);
        Trn_cmd.AddParam(CurRec.DealID);
        Trn_cmd.AddParam(CurRec.DocKind);
        Trn_cmd.AddParam(CurRec.DealID);
        Trn_cmd.AddParam(m_Date);
        Trn_cmd.AddParam(CurRec.DealID);
        Trn_cmd.AddParam(CurRec.DocKind);

        if (CurRec.DocKind == 199)
          if (FD.IsPctSWAP())
            Trn_cmd.AddParam(CurRec.DocKind);
            Trn_cmd.AddParam(CurRec.DealID);
            Trn_cmd.AddParam(m_Date);
            Trn_cmd.AddParam(CurRec.DealID);
          end;
        end;
*/
        Trn_count = Trn_cmd.GetCount(TrnQuery);
        CurLog.AddLogRow("Поиск проводок постановки Т/О по сделке " + CurRec.DealCode + " модуля " + ПолучитьНазваниеПодсист(CurRec.IdentProg) + " на внебаланс", IIF(Trn_count > 0,"найдены","не найдено"));
        if (CurRec.DocKind == 199)
          if(FD.IsSWAP() AND (FD.deal.rec.Date != FD.deal.rec.BeginDate))
            Q1ч_СВОП = 2;
          end;
          if(FD.IsPctSWAP())
            QПП_СВОП_зач_Г = FD.GetPaymentsCount();
          end;
        end;
        Qзач_Г = 2 + Q1ч_СВОП + QПП_СВОП_зач_Г;
        CurLog.AddLogRow("Определение параметра Qзач_Г по сделке " + CurRec.DealCode + " модуля " + ПолучитьНазваниеПодсист(CurRec.IdentProg), IIF(Qзач_Г > 0,"выполнено","не выполнено"));
        if ((Trn_count < Qзач_Г) OR (Trn_count <= 0))
          UpdateOrInsert(CurRec, "Ошибка проводок постановки на главу Г", IsUpdate);
          IsUpdate = false;
        end;
      end;
    END;

    PRIVATE MACRO GetPaymentsInDate(DealID)
      var RetVal = date(0,0,0);
      var Query, Data;
      Query = RSDCommand( "SELECT t_paydate FROM ddvnpmgr_dbt WHERE t_DealID = ? AND t_paydate = ?" );
      Query.NullConversion = true;
      Query.addParam("", RSDBP_IN, DealID);
      Query.addParam("", RSDBP_IN, m_Date);
      Query.execute();
    
      Data = TRsbDataSet(Query);
      if( Data.MoveNext() )
          RetVal = SQL_ConvTypeDate(Data.PayDate);
      end;

      return RetVal;
    END;

    PRIVATE MACRO ДатаВалютирования(CurRec, DealPart)
      var FD, FD2;
      if(CurRec.IdentProg == Id_DV)
        if (CurRec.DocKind == 199)
          FD = DVFirstDocNDeal(CurRec.DocKind, CurRec.DealID, 1);
          if(FD.IsSwap() OR FD.IsPctSWAP())
            FD2 = DVFirstDocNDeal(CurRec.DocKind, CurRec.DealID, 2);
            if (FD.IsSwap() AND (DealPart == 1) AND (FD.deal.rec.Date != FD.deal.rec.BeginDate))
              return FD.deal.rec.BeginDate;
            elif(FD.IsSwap())
              if (DealPart == 1)
                return min(FD.ДатаТребования(), FD.ДатаОбязательства());
              else
                return min(FD2.ДатаТребования(), FD2.ДатаОбязательства());
              end;
            elif(FD.IsPctSWAP())
              if( GetPaymentsInDate(CurRec.DealID) == date(0,0,0))
		 if (DealPart == 1)
                return min(FD.ДатаТребования(), FD.ДатаОбязательства());
               else
                return min(FD2.ДатаТребования(), FD2.ДатаОбязательства());
              end; 
              else
                 return GetPaymentsInDate(CurRec.DealID)
           end;
            end;
          else
            return min(FD.ДатаТребования(), FD.ДатаОбязательства());
          end;
        elif((CurRec.DocKind == 4813) OR (CurRec.DocKind == 4815))
          FD = DVFirstDocFXDeal(CurRec.DocKind, CurRec.DealID, 1);
          if (FD.IsSWAP())
            FD = DVFirstDocFXDeal(CurRec.DocKind, CurRec.DealID, DealPart);
          end;
          return min(FD.ДатаТребования(), FD.ДатаОбязательства());
        elif(CurRec.DocKind == 192)
          return CurRec.ExecDate;
        end;
      elif(CurRec.IdentProg == Id_VA)
         FD = VATickFD(CurRec.DocKind, CurRec.DealID);
         return min(FD.GetPlanSupplyDate(), FD.GetPlanPayDate());
      elif(CurRec.IdentProg == Id_Sec)
        FD = SPFirstDoc( LEG_KIND_DL_TICK, CurRec.DealID);
        if(DealPart == 1)
          return min(FD.dl_leg.rec.Maturity, FD.dl_leg.rec.Expiry);
        elif(FD.ExistBack() AND (DealPart == 2))
          FD2 = SPFirstDoc( LEG_KIND_DL_TICK_BACK, CurRec.DealID );
          return min(FD2.dl_leg.rec.Maturity, FD2.dl_leg.rec.Expiry);
        else
          return min(FD.dl_leg.rec.Maturity, FD.dl_leg.rec.Expiry);
        end;
      end;
      return date(0,0,0);
    END;

    PRIVATE MACRO СписаниеГ(CurRec, IsUpdate:@bool)
      var TrnQuery = "", TrnQuery_ПП = "";
      var Trn_cmd = DL_RSDCommand(), Trn_cmd_ПП = DL_RSDCommand();
      var FD;
      var Trn_count = 0, Trn_count_ПП = 0;
      var QТО_спис_Г = 0, QПП_СВОП_спис_Г = 0, Qспис_Г = 0;
      
      TrnQuery = TrnQuery +
            "SELECT /*+ leading(categ,accdoc,acc,TRN) index(accdoc DMCACCDOC_DBT_IDX4)*/ TRN.* " + 
            "  FROM ( " + ПолучитьКУ(0, Trn_cmd) + " ) " + 
            "       categ, " + 
            "       dmcaccdoc_dbt accdoc, " + 
            "       dacctrn_dbt trn, " + 
            "       daccount_dbt ac " + 
            " WHERE TRN.T_ACCTRNID IN ( " + 
            "                  SELECT NVL(DOC.T_ACCTRNID, -1) " + 
            "                    FROM DOPROPER_DBT oper, doprdocs_dbt doc " + 
            "                   WHERE OPER.T_DOCKIND = " + Trn_cmd.AddParam(CurRec.DocKind) + " AND OPER.T_DOCUMENTID = LPAD(TO_CHAR(" + Trn_cmd.AddParam(CurRec.DealID) + "), 34, '0') AND DOC.T_ID_OPERATION = OPER.T_ID_OPERATION AND DOC.T_DOCKIND = " + DLDOC_CARRY + 
            "                   UNION " + 
            "                  SELECT NVL(grdoc.T_DOCID, -1) " + 
            "                    FROM DDLGRDOC_DBT grdoc, DDLGRDEAL_DBT grdeal " + 
            "                   WHERE grdeal.T_DOCKIND = " + Trn_cmd.AddParam(CurRec.DocKind) + " AND grdeal.T_DOCID = " + Trn_cmd.AddParam(CurRec.DealID) + " AND grdoc.T_GRDEALID = grdeal.T_ID AND grdoc.T_DOCKIND = " + DLDOC_CARRY + 
            "                         ) " +
            "       AND TRN.T_DATE_CARRY = " + Trn_cmd.AddParam(m_Date) +
            "       AND (   AC.T_ACCOUNTID = TRN.T_ACCOUNTID_PAYER " + 
            "            OR AC.T_ACCOUNTID = TRN.T_ACCOUNTID_RECEIVER) " + 
            "       AND ACCDOC.T_DOCID = " + Trn_cmd.AddParam(CurRec.DealID) +
            "       AND ACCDOC.T_DOCKIND = " + Trn_cmd.AddParam(CurRec.DocKind) +
            "       AND ACCDOC.T_CATID = categ.T_CATID " + 
            "       AND ACCDOC.T_ACCOUNT = AC.T_ACCOUNT " + 
            "       AND ACCDOC.T_CHAPTER = AC.T_CHAPTER ";
      if (CurRec.DocKind == 199)
        FD = DVFirstDocNDeal(CurRec.DocKind, CurRec.DealID);
        if (FD.IsPctSWAP())
          TrnQuery_ПП = TrnQuery_ПП +
                "SELECT TRN.* " + 
                "  FROM ( " + ПолучитьКУ(0, Trn_cmd_ПП) + " ) " + 
                "       categ, " + 
                "       dmcaccdoc_dbt accdoc, " + 
                "       dacctrn_dbt trn, " + 
                "       daccount_dbt ac, " + 
                "       doprdocs_dbt doc, " + 
                "       DOPROPER_DBT oper, " + 
                "       DDVNPMGR_DBT pmgr " + 
                " WHERE     OPER.T_DOCKIND = " + Trn_cmd_ПП.AddParam(CurRec.DocKind) +
                "       AND OPER.T_DOCUMENTID = LPAD(TO_CHAR(" + Trn_cmd_ПП.AddParam(CurRec.DealID) + "), 34, '0') " +
                "       AND DOC.T_ID_OPERATION = OPER.T_ID_OPERATION " + 
                "       AND TRN.T_ACCTRNID = DOC.T_ACCTRNID " + 
                "       AND TRN.T_DATE_CARRY = " + Trn_cmd_ПП.AddParam(m_Date) +
                "       AND (   AC.T_ACCOUNTID = TRN.T_ACCOUNTID_PAYER " + 
                "            OR AC.T_ACCOUNTID = TRN.T_ACCOUNTID_RECEIVER) " + 
                "       AND PMGR.T_DEALID = " + Trn_cmd_ПП.AddParam(CurRec.DealID) +
                "       AND ACCDOC.T_DOCID = PMGR.T_ID " + 
                "       AND ACCDOC.T_DOCKIND = 4811 " + 
                "       AND ACCDOC.T_CATID = categ.T_CATID " + 
                "       AND ACCDOC.T_ACCOUNT = AC.T_ACCOUNT " + 
                "       AND ACCDOC.T_CHAPTER = AC.T_CHAPTER  ";
        end;
     end;

/*      Trn_cmd = DL_RSDCommand(TrnQuery);  
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(m_Date);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(CurRec.DocKind);
*/

      if (CurRec.DocKind == 199)
        if (FD.IsPctSWAP())
/*          Trn_cmd_ПП = DL_RSDCommand(TrnQuery_ПП); 
          Trn_cmd_ПП.AddParam(CurRec.DocKind);
          Trn_cmd_ПП.AddParam(CurRec.DealID);
          Trn_cmd_ПП.AddParam(m_Date);
          Trn_cmd_ПП.AddParam(CurRec.DealID);
*/
          Trn_count_ПП = Trn_cmd_ПП.GetCount(TrnQuery_ПП);
        end;
      end;
      Trn_count = Trn_cmd.GetCount(TrnQuery);
      CurLog.AddLogRow("Поиск проводок списания Т/О с внебаланса по сделке " + CurRec.DealCode + " модуля " + ПолучитьНазваниеПодсист(CurRec.IdentProg) + " на внебаланс", IIF((Trn_count + Trn_count_ПП) > 0,"найдены","не найдено"));
        
      if (Trn_count > 0)
        QТО_спис_Г = 2;
      else
        QТО_спис_Г = 0;
      end;
        
      if (CurRec.DocKind == 199)
        if(FD.IsPctSWAP())
          QПП_СВОП_спис_Г = FD.GetPaymentsCount();
        end;
      end;
      Qспис_Г = QТО_спис_Г + QПП_СВОП_спис_Г;
      CurLog.AddLogRow("Определение параметра Qспис_Г по сделке " + CurRec.DealCode + " модуля " + ПолучитьНазваниеПодсист(CurRec.IdentProg), IIF(Qспис_Г > 0,"выполнено","не выполнено"));
      if(((Trn_count + Trn_count_ПП) < Qспис_Г) OR ((Trn_count + Trn_count_ПП) <= 0))
        UpdateOrInsert(CurRec, "Ошибка проводок списания с главы Г", IsUpdate);
        IsUpdate = false;
      end;
    END;

    PRIVATE MACRO ПостановкаА(CurRec, IsUpdate:@bool)
      var Trn_cmd = DL_RSDCommand();

      MACRO ReturnSelect(Query, Kind_Cr, Kind_Deb, IsFirstSelect)
        if (not IsFirstSelect)
          Query = Query + " UNION ALL ";
        end;
        Query = Query + 
          "SELECT CASE " +
          "          WHEN EXISTS " +
          "                  (SELECT step.* " +
          "                     FROM doprstep_dbt step, doprdocs_dbt DOC " +
          "                    WHERE     DOC.T_ACCTRNID = TRN.T_ACCTRNID " +
          "                          AND step.T_ID_OPERATION = DOC.T_ID_OPERATION " +
          "                          AND step.t_id_step = DOC.T_ID_STEP " +
          "                          AND step.t_kind_action = " + 155 /*DV_KINDACTION_IP*/  +
          "                                                      ) " +
          "          THEN 1 ELSE 0 END IS_PP, " +
          "       TRN.* " +
          "  FROM spTRN trn " +
      /*  "  FROM dacctrn_dbt trn " +
          " WHERE TRN.T_ACCTRNID IN ( " + 
          "                  SELECT NVL(DOC.T_ACCTRNID, -1) " + 
          "                    FROM DOPROPER_DBT oper, doprdocs_dbt doc " + 
          "                   WHERE OPER.T_DOCKIND = ? AND OPER.T_DOCUMENTID = ? AND DOC.T_ID_OPERATION = OPER.T_ID_OPERATION AND DOC.T_DOCKIND = " + DLDOC_CARRY + 
          "                   UNION " + 
          "                  SELECT NVL(grdoc.T_DOCID, -1) " + 
          "                    FROM DDLGRDOC_DBT grdoc, DDLGRDEAL_DBT grdeal " + 
          "                   WHERE grdeal.T_DOCKIND = ? AND grdeal.T_DOCID = ? AND grdoc.T_GRDEALID = grdeal.T_ID AND grdoc.T_DOCKIND = " + DLDOC_CARRY + 
          "                         ) " +
          " AND TRN.T_DATE_CARRY = ? " +
        */    

          "    WHERE EXISTS " +
          "              (SELECT /*+ leading(ac_cr,categ_cr,accdoc_cr) index(accdoc_cr DMCACCDOC_DBT_IDX1)*/ * " +
          "                 FROM (" + ПолучитьКУ(Kind_Cr, Trn_cmd) + ") categ_cr, " +
          "                      dmcaccdoc_dbt accdoc_cr, " +
          "                      daccount_dbt ac_cr " +
          "                WHERE     ac_cr.T_ACCOUNTID = TRN.T_ACCOUNTID_PAYER " +
          "                      AND accdoc_cr.T_ACCOUNT = ac_cr.T_ACCOUNT " +
          "                      AND accdoc_cr.T_CATID = categ_cr.T_CATID " +
          "                      AND accdoc_cr.T_CHAPTER = ac_cr.T_CHAPTER) " +
          "       AND EXISTS " +
          "              (SELECT /*+ leading(ac_deb,categ_deb,accdoc_deb) index(accdoc_deb DMCACCDOC_DBT_IDX1) */ * " +
          "                 FROM (" + ПолучитьКУ(Kind_Deb, Trn_cmd) + ") categ_deb, " +
          "                      dmcaccdoc_dbt accdoc_deb, " +
          "                      daccount_dbt ac_deb " +
          "                WHERE     ac_deb.T_ACCOUNTID = TRN.T_ACCOUNTID_RECEIVER " +
          "                      AND accdoc_deb.T_ACCOUNT = ac_deb.T_ACCOUNT " +
          "                      AND accdoc_deb.T_CATID = categ_deb.T_CATID " +
          "                      AND accdoc_deb.T_CHAPTER = ac_deb.T_CHAPTER) ";
        return Query;
      END;

      var TrnQuery = " with spTRN as ("+
          " select /*+ materialize */ * FROM dacctrn_dbt trn " +
          " WHERE TRN.T_ACCTRNID IN ( " + 
          "                  SELECT NVL(DOC.T_ACCTRNID, -1) " + 
          "                    FROM DOPROPER_DBT oper, doprdocs_dbt doc " + 
          "                   WHERE OPER.T_DOCKIND = " + Trn_cmd.AddParam(CurRec.DocKind) + " AND OPER.T_DOCUMENTID = LPAD(TO_CHAR(" + Trn_cmd.AddParam(CurRec.DealID) + "), 34, '0') AND DOC.T_ID_OPERATION = OPER.T_ID_OPERATION AND DOC.T_DOCKIND = " + DLDOC_CARRY + 
          "                   UNION " + 
          "                  SELECT NVL(grdoc.T_DOCID, -1) " + 
          "                    FROM DDLGRDOC_DBT grdoc, DDLGRDEAL_DBT grdeal " + 
          "                   WHERE grdeal.T_DOCKIND = " + Trn_cmd.AddParam(CurRec.DocKind) + " AND grdeal.T_DOCID = " + Trn_cmd.AddParam(CurRec.DealID) + " AND grdoc.T_GRDEALID = grdeal.T_ID AND grdoc.T_DOCKIND = " + DLDOC_CARRY + 
          "                         ) " +
          " AND TRN.T_DATE_CARRY = " + Trn_cmd.AddParam(m_Date) +
          "                           )";
      var SearchNotPP;
      var FD;
      var Trn_count = 0;
      var QСд_А = 0, QПП_СВОП_А = 0, Qитого_А = 0;
      TrnQuery = ReturnSelect(TrnQuery, 1,1,true);
      TrnQuery = ReturnSelect(TrnQuery, 2,2,false);
      TrnQuery = ReturnSelect(TrnQuery, 3,4,false);
      TrnQuery = ReturnSelect(TrnQuery, 4,3,false);
      TrnQuery = ReturnSelect(TrnQuery, 5,6,false);
      TrnQuery = ReturnSelect(TrnQuery, 7,8,false);
      
      TrnQuery = " select count(*) over () as Trn_count , trn.* from (" +TrnQuery+") trn ";

/*      Trn_cmd = DL_RSDCommand(TrnQuery);  

      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
     
     Trn_cmd.AddParam(m_Date);
*/
    /* Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(m_Date);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);   
      Trn_cmd.AddParam(m_Date);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);      
      Trn_cmd.AddParam(m_Date);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(m_Date);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(CurRec.DocKind);
      Trn_cmd.AddParam(CurRec.DealID);
      Trn_cmd.AddParam(m_Date);
    */      
    //  Trn_count = Trn_cmd.GetCount();

      SearchNotPP = Trn_cmd.Execute(TrnQuery);
      while(SearchNotPP.MoveNext())
        if (Trn_count == 0)
          Trn_count = int(SearchNotPP.Trn_count);
        end;
        if (SearchNotPP.IS_PP == 0)
          QСд_А = 1;
          break;
        end;
      end;
 
     CurLog.AddLogRow("Поиск проводок постановки Т/О по сделке " + CurRec.DealCode + " модуля " + ПолучитьНазваниеПодсист(CurRec.IdentProg) + " на баланс", IIF(Trn_count > 0,"найдены","не найдено"));

        
      if (CurRec.DocKind == 199)
        FD = DVFirstDocNDeal(CurRec.DocKind, CurRec.DealID);
        if(FD.IsPctSWAP())
          QПП_СВОП_А = FD.GetPaymentsCount();
        end;
      end;
      Qитого_А = QСд_А + QПП_СВОП_А;
      CurLog.AddLogRow("Определение параметра Qитого_А по сделке " + CurRec.DealCode + " модуля " + ПолучитьНазваниеПодсист(CurRec.IdentProg), IIF(Qитого_А > 0,"выполнено","не выполнено"));
      if ((Trn_count < Qитого_А) OR (Trn_count <= 0))
        UpdateOrInsert(CurRec, "Ошибка проводок постановки на баланс", IsUpdate);
        IsUpdate = false;
      end;
    END;

    PRIVATE MACRO GetDateAndPrint(progress:integer)
      var m_DataQuery_sel = "";
      var m_DataQuery_ins = "";
      var m_DataQuery_exec;
      var m_RS, m_DataQuery, Query;
      var m_NRecsQuery;
      var m_RecsOnDate = 0;
      var result = "";
      var IsUpdate = true;

      execSQL("truncate table DDL_REPORT_TRNA_G_TMP");

      m_DataQuery_ins =     "INSERT INTO DDL_REPORT_TRNA_G_TMP (T_IDENTPROG, " +
                            "           T_DEALID, " +
                            "           T_DOCKIND, " +
                            "           T_DEALCODE, " +
                            "           T_NAME, " +
                            "           T_DEALDATE, " +
                            "           T_EXECDATE, " +
                            "           T_NOTE)";

      if(IsSec == SET_CHAR)
        m_DataQuery_sel = m_DataQuery_sel +
                            "   SELECT ?, " + //Id_Sec
                            "          TICK.T_DEALID, " +
                            "          TICK.T_BOFFICEKIND, " +
                            "          tick.t_dealcode, " +
                            "          oper.t_name, " +
                            "          TICK.T_DEALDATE, " +
                            "          (SELECT MAX(rq.t_plandate) FROM DDLRQ_DBT rq WHERE RQ.T_DOCID = tick.t_dealid and rq.t_dockind = TICK.T_BOFFICEKIND), " +
                            "          CHR(1) " +
                            "     FROM ddl_tick_dbt tick, DOPRKOPER_DBT oper " +
                            "    WHERE     TICK.T_BOFFICEKIND IN ( " + DL_SECURITYDOC + ", " +
                            "                                      " + DL_SECUROWN + " ) " +
                            "          AND TICK.T_DEALDATE <= ? " +
                            "          AND TICK.T_DEALSTATUS != 0 " +
                            "          AND (TICK.T_CLOSEDATE >= ? OR TICK.T_CLOSEDATE = TO_DATE ('01/01/0001', 'dd/mm/yyyy') AND TICK.T_DEALSTATUS != 20)" +
                            "          AND ( ? > 0 AND TICK.T_DEPARTMENT = ? OR ? < 0 )" +
                            "          AND OPER.T_KIND_OPERATION = TICK.T_DEALTYPE " +
                            "          AND TICK.T_CLIENTID <= 0 " + 
                            "          AND (TICK.T_MARKETID > 0 AND NVL((SELECT MIN (rq.t_plandate) " +
                            "              FROM DDLRQ_DBT rq  " +
                            "             WHERE     RQ.T_DOCID = TICK.t_dealid " +
                            "                   AND rq.t_dockind = TICK.T_BOFFICEKIND), TICK.T_DEALDATE) >= (TICK.T_DEALDATE + 2) OR TICK.T_MARKETID <= 0 AND NVL((SELECT MIN (rq.t_plandate) " +
                            "              FROM DDLRQ_DBT rq  " +
                            "             WHERE     RQ.T_DOCID = TICK.t_dealid " +
                            "                   AND rq.t_dockind = TICK.T_BOFFICEKIND), TICK.T_DEALDATE) > TICK.T_DEALDATE) ";
      end;

      if(IsDV == SET_CHAR)
        m_DataQuery_sel = m_DataQuery_sel + IIF (m_DataQuery_sel != "", "   UNION ", "");
        m_DataQuery_sel = m_DataQuery_sel +
                            "   SELECT ?, " + //Id_DV
                            "          DVN.T_ID, " +
                            "          DVN.T_DOCKIND,"  +
                            "          CASE WHEN DVN.T_EXTCODE != '' THEN DVN.T_EXTCODE ELSE DVN.T_CODE END, " +
                            "          oper.t_name, " +
                            "          DVN.T_DATE, " +
                            "          CASE " +
                            "             WHEN     DVNFI.T_SUPLDATE = TO_DATE ('01/01/0001', 'dd/mm/yyyy') " +
                            "                  AND DVNFI.T_PAYDATE = TO_DATE ('01/01/0001', 'dd/mm/yyyy') " +
                            "             THEN " +
                            "                DVNFI.T_EXECDATE " +
                            "             WHEN     DVNFI.T_EXECDATE >= DVNFI.T_SUPLDATE " +
                            "                  AND DVNFI.T_EXECDATE >= DVNFI.T_PAYDATE " +
                            "             THEN " +
                            "                DVNFI.T_EXECDATE " +
                            "             WHEN DVNFI.T_SUPLDATE >= DVNFI.T_PAYDATE " +
                            "             THEN " +
                            "                DVNFI.T_SUPLDATE " +
                            "             ELSE " +
                            "                DVNFI.T_PAYDATE " +
                            "          END, " +
                            "          CHR(1)" +
                            "     FROM ddvndeal_dbt dvn, ddvnfi_dbt dvnfi, DOPRKOPER_DBT oper " +
                            "    WHERE     DVN.T_DOCKIND IN (" + DL_DVNDEAL + ", " + DL_DVFXDEAL + ", " + DL_DVDEALT3 + ") " +
                            "          AND DVN.T_DATE <= ? " +
                            "          AND DVN.T_STATE != 0 " +
                            "          AND (CASE " +
                            "                  WHEN     DVNFI.T_SUPLDATE = " +
                            "                              TO_DATE ('01/01/0001', 'dd/mm/yyyy') " +
                            "                       AND DVNFI.T_PAYDATE = " +
                            "                              TO_DATE ('01/01/0001', 'dd/mm/yyyy') " +
                            "                  THEN " +
                            "                     DVNFI.T_EXECDATE " +
                            "                  WHEN     DVNFI.T_EXECDATE >= DVNFI.T_SUPLDATE " +
                            "                       AND DVNFI.T_EXECDATE >= DVNFI.T_PAYDATE " +
                            "                  THEN " +
                            "                     DVNFI.T_EXECDATE " +
                            "                  WHEN DVNFI.T_SUPLDATE >= DVNFI.T_PAYDATE " +
                            "                  THEN " +
                            "                     DVNFI.T_SUPLDATE " +
                            "                  ELSE " +
                            "                     DVNFI.T_PAYDATE " +
                            "               END) >= ? " +
                            "          AND ( ? > 0 AND DVN.T_DEPARTMENT = ? OR ? < 0 )" +
                            "          AND OPER.T_KIND_OPERATION = DVN.T_KIND " +
                            "          AND DVNFI.T_DEALID = DVN.T_ID " +
                            "          AND (DVN.T_DVKIND = 6 AND DVN.T_BEGINDATE <> DVN.T_DATE AND DVNFI.T_TYPE != 2 OR DVN.T_DVKIND IN (3,4,6) AND DVNFI.T_TYPE = 2 OR DVNFI.T_TYPE >= 0 AND DVN.T_DVKIND NOT IN (3,4,6) ) "
                            "          AND DVN.T_PERIODCLS > 0 " +
                            "          AND dvn.T_CLIENT <= 0 " +
                            "          AND (       dvn.t_dvkind = " + DV_BANKNOTE_FX  +
                            "                  AND EXISTS " +
                            "                         (SELECT * " +
                            "                            FROM ddvnfi_dbt dvnfi_1 " +
                            "                           WHERE     dvnfi_1.T_DEALID = DVN.T_ID " +
                            "                                 AND dvnfi_1.t_fiid != dvnfi_1.T_PRICEFIID) " +
                            "                  AND 1 = ? " +
                            "               OR dvn.t_dvkind != " + DV_BANKNOTE_FX + ") " +
                            "   UNION " +
                            "   SELECT ?, " + //Id_DV
                            "          DV.T_ID, " +
                            "           " + DL_DVDEAL + ", " +
                            "          DV.T_EXTCODE, " +
                            "          oper.t_name, " +
                            "          DV.T_DATE, " +
                            "          CASE WHEN OPER.T_SYSTYPES = 'EU' OR OPER.T_SYSTYPES = 'EO' THEN DV.T_DATE_CLR ELSE TURN.T_DATE END, " +
                            "          CHR(1) " +
                            "     FROM ddvdeal_dbt dv, DDVDLTURN_DBT turn, DOPRKOPER_DBT oper " +
                            "    WHERE  ( ? > 0 AND DV.T_DEPARTMENT = ? OR ? < 0 )" +
                            "          AND TURN.T_DEALID = DV.T_ID " +
                            "          AND DV.T_DATE <= ? " +
                            "          AND DV.T_STATE != 0 " +
                            "          AND (CASE WHEN OPER.T_SYSTYPES = 'EU' OR OPER.T_SYSTYPES = 'EO' THEN DV.T_DATE_CLR ELSE TURN.T_DATE END > ?" +
                            "          OR CASE WHEN OPER.T_SYSTYPES = 'EU' OR OPER.T_SYSTYPES = 'EO' THEN DV.T_DATE_CLR ELSE TURN.T_DATE END = TO_DATE ('01/01/0001', 'dd/mm/yyyy'))" +
                            "          AND DV.T_DATE < TURN.T_DATE " +
                            "          AND dv.T_CLIENT <= 0 " +
                            "          AND OPER.T_KIND_OPERATION = DV.T_KIND ";
        
      end;

      if(IsVA == SET_CHAR)
        m_DataQuery_sel = m_DataQuery_sel + IIF (m_DataQuery_sel != "", "   UNION ", "");
        m_DataQuery_sel = m_DataQuery_sel +
                            "   SELECT ?, " + //Id_VA
                            "          TICK.T_DEALID, " +
                            "          TICK.T_BOFFICEKIND, " +
                            "          tick.t_dealcode, " +
                            "          oper.t_name, " +
                            "          TICK.T_DEALDATE, " +
                            "          CASE WHEN LEG.T_MATURITY >= LEG.T_EXPIRY THEN LEG.T_MATURITY ELSE LEG.T_EXPIRY END, " +
                            "          CHR(1) " +
                            "     FROM ddl_tick_dbt tick, DOPRKOPER_DBT oper, ddl_leg_dbt leg " +
                            "    WHERE     TICK.T_BOFFICEKIND IN ( " + DL_VEKSELACCOUNTED + ", " +
                            "                                      " + DL_VAREPAY + ", " +
                            "                                      " + DL_VAPAWN + ", " +
                            "                                      " + DL_VAENWR + ") " +
                            "          AND TICK.T_DEALDATE <= ? " +
                            "          AND TICK.T_DEALSTATUS != 0 " +
                            "          AND (TICK.T_CLOSEDATE > ? OR TICK.T_CLOSEDATE = TO_DATE ('01/01/0001', 'dd/mm/yyyy'))" +
                            "          AND TICK.T_DEALDATE < CASE WHEN LEG.T_MATURITY >= LEG.T_EXPIRY THEN LEG.T_MATURITY ELSE LEG.T_EXPIRY END " +
                            "          AND ( ? > 0 AND TICK.T_DEPARTMENT = ? OR ? < 0 )" +
                            "          AND LEG.T_DEALID = TICK.T_DEALID " +
                            "          AND LEG.T_LEGKIND = 0 " +
                            "          AND tick.T_CLIENTID <= 0 " +
                            "          AND OPER.T_KIND_OPERATION = TICK.T_DEALTYPE ";
      end;
      m_DataQuery_ins = m_DataQuery_ins + m_DataQuery_sel;

      m_DataQuery_exec = RSDCommand(m_DataQuery_ins);
      if (IsSec == SET_CHAR )
        m_DataQuery_exec.AddParam( "", RSDBP_IN, Id_Sec);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_Date);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_Date);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
      end;

      if (IsDV == SET_CHAR )
      /*dvndeal*/
        m_DataQuery_exec.AddParam( "", RSDBP_IN, Id_DV);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_Date);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_Date);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, РАЗНОВАЛЮТ());
      /*dvdeal*/
        m_DataQuery_exec.AddParam( "", RSDBP_IN, Id_DV);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_Date);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_Date);
      end;

      if (IsVA == SET_CHAR )
        m_DataQuery_exec.AddParam( "", RSDBP_IN, Id_VA);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_Date);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_Date);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
        m_DataQuery_exec.AddParam( "", RSDBP_IN, m_DepartmentID);
      end;

      m_DataQuery_exec.execute();

      if (IsSec == SET_CHAR )
        m_NRecsQuery = DL_RSDCommand();
        /*m_DataQuery = "SELECT * FROM DDL_REPORT_TRNA_G_TMP WHERE T_IDENTPROG = \'" + Id_Sec + "\'";
        m_RecsOnDate = SQL_GetNRecs( m_DataQuery );*/
        m_RecsOnDate = m_NRecsQuery.GetCount( "SELECT * FROM DDL_REPORT_TRNA_G_TMP WHERE T_IDENTPROG = " + m_NRecsQuery.AddParam( Id_Sec ) );
        CurLog.AddLogRow("Поиск сделок за " + ZeroInFirst(m_Date, true) + " в модуле \"Бэк-офис ценных бумаг\"", IIF(m_RecsOnDate > 0, "найдены", "не найдено"));
      end;

      if (IsDV == SET_CHAR )
        m_NRecsQuery = DL_RSDCommand();
        /*m_DataQuery = "SELECT * FROM DDL_REPORT_TRNA_G_TMP WHERE T_IDENTPROG = \'" + Id_DV + "\'";
        m_RecsOnDate = SQL_GetNRecs( m_DataQuery );*/
        m_RecsOnDate = m_NRecsQuery.GetCount( "SELECT * FROM DDL_REPORT_TRNA_G_TMP WHERE T_IDENTPROG = " + m_NRecsQuery.AddParam( Id_DV ) );
        CurLog.AddLogRow("Поиск сделок за " + ZeroInFirst(m_Date, true) + " в модуле \"ФИССиКО\"", IIF(m_RecsOnDate > 0, "найдены", "не найдено"));
      end;

      if (IsVA == SET_CHAR )
        m_NRecsQuery = DL_RSDCommand();
        /*m_DataQuery = "SELECT * FROM DDL_REPORT_TRNA_G_TMP WHERE T_IDENTPROG = \'" + Id_VA + "\'";
        m_RecsOnDate = SQL_GetNRecs( m_DataQuery );*/
        m_RecsOnDate = m_NRecsQuery.GetCount( "SELECT * FROM DDL_REPORT_TRNA_G_TMP WHERE T_IDENTPROG = " + m_NRecsQuery.AddParam( Id_VA ) );
        CurLog.AddLogRow("Поиск сделок за " + ZeroInFirst(m_Date, true) + " в модуле \"Учтенные векселя\"", IIF(m_RecsOnDate > 0, "найдены", "не найдено"));
      end;

      m_DataQuery = "SELECT * FROM DDL_REPORT_TRNA_G_TMP";

      m_RS = TRsbDataSet( m_DataQuery );

      while(m_RS.MoveNext())
        IsUpdate = true;
        ПостановкаГ(m_Rs, @IsUpdate);
        if ((m_RS.DealDate < m_Date) AND ((m_Date == ДатаВалютирования(m_RS, 1)) OR (m_Date == ДатаВалютирования(m_RS, 2))))
          СписаниеГ(m_Rs, @IsUpdate);
          ПостановкаА(m_Rs, @IsUpdate);
        end;
        UseProgress(progress = progress + 1);
      end;

      m_DataQuery = "SELECT * FROM DDL_REPORT_TRNA_G_TMP WHERE T_NOTE <> CHR(1) ORDER BY T_NOTE, T_DEALCODE, T_NAME, T_DEALDATE";
      m_RS = TRsbDataSet( m_DataQuery );
      while(m_RS.MoveNext())
        PrintLine(m_RS.DealCode, m_RS.Name, SQL_ConvTypeDate(m_RS.DealDate), SQL_ConvTypeDate(m_RS.ExecDate),m_RS.Note);
      end;
    END;

    PRIVATE MACRO BeginReport( NumCopy:INTEGER )
      m_CurrSheetName = "Отчет";

      Dl_CallInsertStat( PrintMode() );

      SetActiveSheet (m_CurrSheetName);
      CreateTotalBook();

    END;

    PRIVATE MACRO Create( NumCopy:INTEGER )
        var progress = 0;
        ErrorCount = 0;

        CurLog.BeginLogging();

        PrintFormatString(ReportHeader,
                     "N1_DateTime", " Отчет-сверка проводок глав  А и  Г _ " + ZeroInFirst(CurDate, true) + " " + ZeroInFirst(CurTime, false),
                     "N1_HeaderTitle",   "Отчет-сверка проводок главы А и главы Г (для всех модулей СОФР) за дату " + ZeroInFirst(m_Date, true));
        CopyAllSheetInTotalBook(m_CurrSheetName, false, "N1_Header", 0, m_CurrSheetName);
        InitProgress( -1, "Идет формирование отчета", "Формирование отчета Сверка проводок глав А и Г за " + ZeroInFirst(m_Date, true));
        CopyAllSheetInTotalBook( m_CurrSheetName, false, "N1_TableHeader", 0, m_CurrSheetName, true );
        RegisterTable(  "N1_TableData", TableHeader,
                        "N1_A1", "N1_A2", "N1_A3", "N1_A4", "N1_A5");
        GetDateAndPrint(progress);

        CurLog.EndLoggingTable();
        CurLog.EndLogging();
        if ( ErrorCount > 0)
          EndTable();
          CopyAllSheetInTotalBook( m_CurrSheetName, false, GetTableRange(), 0, m_CurrSheetName, true );
          CurLog.ErrorHistoryRec();
        end;
        RemProgress();
        PrintFormatString(ReportExecutor,
                     "N1_Executor", "Исполнитель " + Операционист());
        CopyAllSheetInTotalBook( m_CurrSheetName, false, "N1_Executor", 0, m_CurrSheetName, true );
    END;

    PRIVATE MACRO CReport_Show( NumCopy:INTEGER )
      SetLastTotalBookName("Report_TrnA_G_" + 
                    ПолучитьДатуВСтроке(m_Date) + "_" + StrSubst(StrSubst(string(date()),".",""), " ", "") + StrSubst(string(time()),":",""));
      CReport_Show(NumCopy);
    end;

    PRIVATE MACRO EndReport( NumCopy:INTEGER )
      SaveTotalBook();
    END;

    initDL_CReportTemplate( Form, TemplateName, UseCSV, IsWebService, ReportHashCode, UsePOI );
END;

MACRO RunReport()

  var stat = true;

  Report_TrnA_G_Form = DL_Report_TrnA_G_Form();
   
  while(stat)
    stat = Report_TrnA_G_Form.Run();
   
     // Проверяем можем ли мы делать отчет по предоставленным данным
    if (not stat)
      break;
    else
      m_DepartmentID  = Report_TrnA_G_Form.GetFieldValue( PNFLD_TRNA_G_DEPARTCODE );
      m_Date          = Report_TrnA_G_Form.GetFieldValue( PNFLD_TRNA_G_DATE );
      IsSec           = Report_TrnA_G_Form.GetFieldValue( PNFLD_TRNA_G_SEC );
      IsDV            = Report_TrnA_G_Form.GetFieldValue( PNFLD_TRNA_G_DV );
      IsVA            = Report_TrnA_G_Form.GetFieldValue( PNFLD_TRNA_G_VA );
      IsApostr        = Report_TrnA_G_Form.GetFieldValue( PNFLD_TRNA_G_ISAPOSTR );
      IsExcel         = Report_TrnA_G_Form.GetFieldValue( PNFLD_TRNA_G_EXCEL );
    end;
   
    if( stat )
      var namefiles;
      var i = 0;  
      var Report_TrnA_G = DL_Report_TrnA_G( null, "Report_TrnA_G.xlsx", null, null, null, true );     
      Report_TrnA_G.setisshowAppl(false);
      Report_TrnA_G.Run();
      namefiles = Report_TrnA_G.GetFullReportFileNames();
      Report_TrnA_G = NULL;
      for(i, namefiles)       
        СохранениеКонтрольныхОтчетов(i, ПолучитьДатуВСтроке(m_Date));
        ВыгрузкаКонтрольныхОтчетов(i);
        if(IsExcel == SET_CHAR)
          //CDAOMSExcel(i,true).Show();
          var fileName, fileExt;
          var filePath = SplitFile(i, fileName, fileExt);

          if( not isStandAlone() )
            filePath = "$" + filePath;
          end;

          SC_ShowFile(filePath, fileName+fileExt, true);
        end;
      end;
    end;
  end;

END;

RunReport();
exit(1); 