/*
$Name:        dlinaccia.mac
$Module:      Ядро Securities
$Description: Отчет "Индивидуальный счет ВУ"
*/
IMPORT "DLReport_h.mac", "dlmisc.mac", "dldlngfun.mac", "sc_inacc.mac", "vainner.mac", "dv_car.mac", "dlnteffpm.mac";

PRIVATE CONST POI_MODE = TRUE; // DEF-57070, одновременно преобразовал шаблон

PRIVATE CONST REPDATAPART_EMISSIVE    = 1; //Часть отчета - Эмиссионные ц/б
PRIVATE CONST REPDATAPART_NOTEMISSIVE = 2; //Часть отчета - Неэмиссионные ц/б
PRIVATE CONST REPDATAPART_CURRENCY    = 3; //Часть отчета - Денежные средства
PRIVATE CONST REPDATAPART_METAL       = 4; //Часть отчета - Драгоценные металлы

//Статусы исполнения плановых обязательств
PRIVATE CONST DEALCOMM_STATE_NO      = 0; //без статуса
PRIVATE CONST DEALCOMM_STATE_EXEC    = 1; //исполнено
PRIVATE CONST DEALCOMM_STATE_REJECT  = 2; //отказ от исполнения
PRIVATE CONST DEALCOMM_STATE_OVERDUE = 3;

//Расшифровки статусов
PRIVATE VAR DealCommStateArr = TArray();
DealCommStateArr[DEALCOMM_STATE_NO]      = "";
DealCommStateArr[DEALCOMM_STATE_EXEC]    = "исполнено";
DealCommStateArr[DEALCOMM_STATE_REJECT]  = "отказ от исполнения";
DealCommStateArr[DEALCOMM_STATE_OVERDUE] = "не исполнено в срок";

CLASS DLInAccIAFormData()
  var GUID,
      DepartmentID,
      BeginDate,
      EndDate,
      DivideByDates,
      IsUseBO,
      IsUseVA,
      IsUseDV,
      IsUseDV_Cur,
      ClientID,
      IsForm,
      FormSub,
      IsVid,
      VidSub,
      Noresident,
      ContractID,
      IsUseApp,
      IsExportToExel,
      CCA_NatCUR;
    
  // Значение по умолчанию
  GUID           = "";
  DepartmentID   = -1;
  BeginDate      = {curdate};
  EndDate        = {curdate};
  DivideByDates  = "";
  ClientID       =  -1;
  IsForm         =  0;
  FormSub        =  0;
  IsVid          =  0;
  VidSub         =  0;
  Noresident     =  "";
  ContractID     =  -1;
  IsUseApp       = "X";
  IsExportToExel = "X";
  IsUseBO = "X";
  IsUseVA = "X";
  IsUseDV = "X";
  IsUseDV_Cur = "X";
  if( VA_NeedInnerAcc() == false )
     IsUseVA = "";
  end;

  CCA_NatCUR = DL_GetISOCurr(643);
END;

////////////////////////////////////////////////////////////////////////////////////////////
//Подготовка данных
////////////////////////////////////////////////////////////////////////////////////////////
PRIVATE CLASS DL_InAccIA_CreateData(Params)
  PRIVATE VAR m_Params = Params;
  PRIVATE VAR m_CheckCatArr = TArray();

  m_CheckCatArr[m_CheckCatArr.size] = "ДС Клиента, ВУ"; 
  m_CheckCatArr[m_CheckCatArr.size] = "ЦБ Клиента, ВУ";
  m_CheckCatArr[m_CheckCatArr.size] = "НЦБ Клиента, ВУ";
  m_CheckCatArr[m_CheckCatArr.size] = "ДМ клиента, ВУ";

  //Подготовить фактические данные
  PRIVATE MACRO CreateFactData()
    var repdataCache = RsbSQLInsert("dliarepdata.dbt");
    var repdataArr = TArray();
    var PrevAccount = "", PrevOutRest = $0, PrevDate = date(0,0,0);

    var cmd = DL_RSDCommand();

    var sqlQuery = " SELECT acc.t_Account, acc.t_Currency, acc.t_Place, inacc.t_DebAcc DebAcc, acc.t_Owner Client, " +
                   "        inacc.t_FIID, acc.t_Clientcontrid ClientContrID, "+
                   "        (case when inacc.t_DocumentKind = 159 then 0 else inacc.t_OperType end) OperType, " +
                   "        inacc.t_DealKind DealKind, inacc.t_Date, inacc.t_GroundNum, inacc.t_Department, " +
                   "        inacc.t_DocumentKind DocKind, inacc.t_DocumentID DocID, inacc.t_Sum Sum, inacc.t_Chapter, " +
                   "        inacc.t_GroundKind, "
                   "        fin.t_FI_Code, fin.t_Name AvrName, fin.t_FI_Kind, " +
                   "        NVL(avrkind.t_IsEmissive, chr(0)) IsEmiss, " +
                   "        case when fin.T_FIID = "+NATCUR+" then '"+string(m_Params.CCA_NatCUR)+"' else fin.T_CCY end t_CCY, "
                   "        (CASE WHEN inacc.t_Boffice = " + OBJTYPE_BACKOFFICE_SP + " THEN rsb_secur.RSI_GetDealCodeEx(inacc.t_DocumentKind, inacc.t_DocumentID) ELSE CHR(1) END) as SecDealNumber, "+
                   "        NVL(utl_raw.cast_to_varchar2(dbms_lob.substr(inacc.t_FmtBlobData_XXXX,2000)), CHR(1)) DealNumber, " +
                   "        NVL(case when inacc.t_DocumentKind in (101,154,176) " +
                   "                 then (rsb_secur.RSI_GetDealKindName(inacc.t_DocumentKind, inacc.t_DocumentID)) " +
                   "                 when inacc.t_DocumentKind in (159) then (select llv_o.t_Name from dllvalues_dbt llv_o where llv_o.t_List = " + OBJTYPE_CALCOPKIND + " and llv_o.t_Element = inacc.t_Opertype)"  +
                   "                 when inacc.t_DocumentKind in (199, 4813) then case when  (select t_type  from ddvndeal_dbt where t_id = inacc.t_documentid) in (1,5) then 'Покупка' else 'Продажа' end "
                   "                 else (select t_name from doprkdoc_dbt where t_dockind = inacc.t_DealKind) " +
                   "            end,  CHR(1)) as DealKindName, " +
                   "        NVL(bnr.t_Issuer, RSI_RSB_FIInstr.FI_GetIssuerOnDate(fin.t_FIID, ? /*0*/)) as IssuerID, " +
                   "        trim(NVL(bnr.t_BCNumber, NVL(avr.t_ISIN, NVL(avr.t_LSIN, CHR(1))))) as FI_Number, " +
                   "        NVL(avr.t_Issue, CHR(1)) as Issue, " +
                   "        NVL(avr.t_Tranche, CHR(1)) as Tranche, " +
                   "        NVL(bnr.t_BCSeries, NVL(avr.t_Series, CHR(1))) as FI_Series, " +
                   "        rsb_secur.GetMainObjAttr(659, LPAD(sf.t_ID, 10, '0'), 1, ? /*1*/) as ContrCat " +
                   " FROM ddlinacc_dbt inacc left join dvsordlnk_dbt lnk ON lnk.t_ContractID = inacc.t_DocumentID and lnk.t_DocKind = inacc.t_DocumentKind " +
                   "                         left join dvsbanner_dbt bnr ON bnr.t_BCID = lnk.t_BCID "
                   "                         left join ddvndeal_dbt dvndeal ON dvndeal.t_id = inacc.t_DocumentID and dvndeal.t_dockind = inacc.t_DocumentKind, "
                   "      dfininstr_dbt fin left join davrkinds_dbt avrkind ON avrkind.t_FI_Kind = fin.t_FI_Kind AND avrkind.t_AvoirKind = fin.t_AvoirKind " +
                   "                        left join davoiriss_dbt avr ON avr.t_FIID = fin.t_FIID, "
                   "      dsfcontr_dbt sf, dacctrn_dbt acctrn, " +
                   "      (SELECT acc.t_Account, acc.t_Place, acc.t_Owner, acc.t_Clientcontrid, acc.t_Currency " +
                   "         FROM dmccateg_dbt cat, dmcaccdoc_dbt acc " +
                   "        WHERE cat.t_LevelType = 1 " +
                   "          AND cat.t_Code in ('ДС Клиента, ВУ', 'ЦБ Клиента, ВУ', 'НЦБ Клиента, ВУ', 'ДМ клиента, ВУ')"
                   "          AND acc.t_CatNum = cat.t_Number " +
                   "          AND acc.t_Chapter in(21, 22) " +
                   "      GROUP BY acc.t_Account, acc.t_Place, acc.t_Owner, acc.t_Clientcontrid, acc.t_Currency) acc " +
                   " WHERE ((inacc.t_DebAcc = acc.t_Account) or (inacc.t_KredAcc = acc.t_Account)) " +
// KS 19.03.2020 Для выборки и планируемых
// ToDo - доработать выбору, чтобы не попадало лишнее. Рынок, договор
//                   "   AND inacc.t_Date <= ? /*2*/ " +
//                   "   AND inacc.t_Date >= ? /*3*/ " +
                   "    AND ((inacc.t_Date <= ? /*2*/     AND inacc.t_Date >= ? /*3*/) or  " +
                   "         (dvndeal.t_date <= ? /*2.1*/ AND dvndeal.t_date >= ? /*3.1*/)) " + // KS 19.03.2020 плюс планируемыe (хотя тут все)
                   "   AND inacc.t_FIID = acc.t_Currency " +
                   "   AND acctrn.t_AccTrnID = inacc.t_AccTrnID " +
                   "   AND acctrn.t_State = 1 " +
                   "   AND fin.t_FIID = inacc.t_FIID " +
                   "   AND fin.t_FI_KIND in( " + string(FIKIND_CURRENCY) + "," + string(FIKIND_AVOIRISS) + IIF( (m_Params.IsUseDV_Cur == SET_CHAR), ("," + string(FIKIND_METAL)), " ") +") " +
                   "   AND sf.t_ID = acc.t_ClientContrID " +
                   "   AND (     (    fin.t_FI_KIND = " + string(FIKIND_METAL) + 
                   "              AND inacc.t_DocumentKind in(" + DL_DVNDEAL + "," + DL_DVDEALT3 + "," + DL_DVFXDEAL + ")" + 
                   "              AND exists( select nd.t_ID " +
                   "                            from ddvndeal_dbt nd " +
                   "                           where nd.t_ID = inacc.t_DocumentID " +
                   "                             and nd.t_State > " + DVDEAL_PREP +
                   "                        )" + 
                   "             ) " +
                   "          OR ((inacc.t_DocumentKind not in(" + DL_DVDEALT3 + "," + DL_DVFXDEAL + ")) or " +
                   "        ((inacc.t_DocumentKind = " + DL_DVDEALT3 + ") and exists( select nd.t_ID " +
                   "                                                                    from ddvndeal_dbt nd " +
                   "                                                                   where nd.t_ID = inacc.t_DocumentID " +
                   "                                                                     and nd.t_IsPFI = 'X' " +
                   "                                                                         ) " +
                   "         ) or " +
                   "        ((inacc.t_DocumentKind = " + DL_DVFXDEAL + ") and exists( select tk.t_ID " +
                   "                                                                    from ddvndeal_dbt tk " +
                   "                                                                   where tk.t_ID = inacc.t_DocumentID " +
                   "                                                                     and Rsb_Secur.IsDVFXDEAL(Rsb_Secur.get_OperationGroupDocKind(Rsb_Secur.get_OperSysTypes(tk.t_Kind, tk.t_DocKind), tk.t_DocKind)) = 1 "
                   "                                                                     and ( /*EXISTS (select 1 from dpartyown_dbt Pto where Pto.T_PARTYKIND = " + String (PTK_MARKETPLASE) +
                   "                                                                             and Pto.T_PARTYID = tk.T_CONTRACTOR) and*/ tk.t_Sector = chr(88) " +
                   "                                                                         ) " +
                   "                                                                 ) " +
                   "        ) " +
                   "       ) " +
                   "      ) " +
                   "   AND inacc.t_Boffice in( ";
           
    cmd.AddParam(m_Params.EndDate);   /*0*/
    cmd.AddParam(m_Params.EndDate);   /*1*/
    cmd.AddParam(m_Params.EndDate);   /*2*/
    cmd.AddParam(m_Params.BeginDate); /*3*/
    cmd.AddParam(m_Params.EndDate);   /*2.1*/
    cmd.AddParam(m_Params.BeginDate); /*3.2*/

    var Delim = false;
    if( m_Params.IsUseBO == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(OBJTYPE_BACKOFFICE_SP); 
       Delim = true;
    end;

    if( (m_Params.IsUseDV == SET_CHAR) OR (m_Params.IsUseDV_Cur == SET_CHAR) )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(OBJTYPE_BACKOFFICE_DV);
       Delim = true;
    end;

    if( m_Params.IsUseVA == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(OBJTYPE_BACKOFFICE_VA);
       Delim = true;
    end;

    sqlQuery = sqlQuery + " ) ";

    sqlQuery = sqlQuery + "   AND sf.t_ServKind in( ";
    Delim = false;
    if( m_Params.IsUseBO == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(PTSK_STOCKDL);
       Delim = true;
    end;

    if( m_Params.IsUseDV == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(PTSK_DV);
       Delim = true;
    end;

    if( m_Params.IsUseDV_Cur == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(PTSK_CM);
       Delim = true;
    end;

    if( m_Params.IsUseVA == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(PTSK_VEKSACC);
       Delim = true;
    end;
    sqlQuery = sqlQuery + " ) ";


    if( m_Params.DepartmentID > 0)
      sqlQuery = sqlQuery + " AND inacc.t_Department = ? ";
      cmd.AddParam(m_Params.DepartmentID);
    end;

    if( m_Params.ClientID > 0 )
       sqlQuery = sqlQuery + " AND acc.t_Owner = ? ";
       cmd.AddParam(m_Params.ClientID);
    end;
   
    if( m_Params.ContractID > 0 )
       sqlQuery = sqlQuery + " AND sf.t_ID = ? ";
       cmd.AddParam(m_Params.ContractID);
    end;

    if (m_Params.DivideByDates) sqlQuery = sqlQuery + " ORDER BY acc.t_Owner, inacc.t_Date, sf.t_ID, acc.t_Place, acc.t_Account, fin.t_FIID, acctrn.t_AccTrnID";
    else sqlQuery = sqlQuery + " ORDER BY acc.t_Owner, sf.t_ID, acc.t_Place, acc.t_Account, fin.t_FIID, inacc.t_Date, acctrn.t_AccTrnID";
    end;
    
    var RepData = cmd.Execute(sqlQuery);
    
    var _Sort = 0;
    while( RepData.MoveNext() )

      var RepDataI = TRecHandler("dliarepdata.dbt");

      RepDataI.Clear();

      RepDataI.rec.GUID           = m_Params.GUID;
      RepDataI.rec.Department     = RepData.Department;
      RepDataI.rec.ClientID       = RepData.Client;
      RepDataI.rec.ContrID        = RepData.ClientContrID;
      if(RepData.FI_Kind == FIKIND_AVOIRISS)
        RepDataI.rec.Part = IIF(RepData.IsEmiss == SET_CHAR, REPDATAPART_EMISSIVE, REPDATAPART_NOTEMISSIVE);
      elif(RepData.FI_Kind == FIKIND_CURRENCY) 
        RepDataI.rec.Part = REPDATAPART_CURRENCY;
      elif(RepData.FI_Kind == FIKIND_METAL)
        RepDataI.rec.Part = REPDATAPART_METAL;
      end;

      RepDataI.rec.IsFact         = SET_CHAR;
      RepDataI.rec.PlaceID        = RepData.Place;
      RepDataI.rec.Account        = RepData.Account;
      RepDataI.rec.Chapter        = RepData.Chapter;
      RepDataI.rec.FIID           = RepData.Currency;
      RepDataI.rec.IssuerID       = RepData.IssuerID;

      RepDataI.rec.FI_Number      = RepData.FI_Number;
      RepDataI.rec.FI_Series      = RepData.FI_Series;
      RepDataI.rec.Issue          = RepData.Issue;
      RepDataI.rec.Tranche        = RepData.Tranche;

      RepDataI.rec.Date           = date(RepData.Date);

      if((PrevAccount != RepData.Account) OR (PrevDate != date(RepData.Date)))
        _Sort = 0;
      else
        _Sort = _Sort + 1;
      end;

      RepDataI.rec.Sort           = _Sort;
      RepDataI.rec.OperType       = RepData.OperType;
      RepDataI.rec.DealKindName   = RepData.DealKindName;
      RepDataI.rec.DealCode       = IIF(RepData.SecDealNumber != "", RepData.SecDealNumber, RepData.DealNumber);
      RepDataI.rec.GroundKind     = RepData.GroundKind;
      RepDataI.rec.GroundXld      = RepData.GroundNum;

      if( PrevAccount != RepData.Account )
         RepDataI.rec.InRest = DL_GetRestAccountParam(RepData.Chapter, RepData.Currency, RepData.Account, date(RepData.Date)-1);
      else
         RepDataI.rec.InRest = PrevOutRest;
      end;

      if( RepData.Account == RepData.DebAcc )
         RepDataI.rec.InSum  = RepData.Sum; /*зачисление*/
      else
         RepDataI.rec.OutSum = RepData.Sum; /*списание*/
      end;

      //т.к. счета активные, то остаток на них со знаком "минус", поэтому сумму зачисления вычитаем, а сумму списания прибавляем.
      RepDataI.rec.OutRest = RepDataI.rec.InRest - RepDataI.rec.InSum + RepDataI.rec.OutSum;

      PrevDate    = date(RepData.Date);
      PrevAccount = RepData.Account;
      PrevOutRest = RepDataI.rec.OutRest;

      // запись для блока движений по счету
      if( RepData.ContrCat != 2 ) /*не поверенный*/
         repdataArr[repdataArr.size] = TRecHandler("dliarepdata.dbt");
         copy(repdataArr[repdataArr.size-1], RepDataI);
      end;
      // запись для блока обязательств
      repdataArr[repdataArr.size] = TRecHandler("dliarepdata.dbt");
      if(date(RepData.Date) > m_Params.EndDate) // KS 19.03.2019 Планируемыми считаем только те, у которых дата не попадает в период отчета
        RepDataI.rec.IsFact    = UNSET_CHAR;
      else
        RepDataI.rec.IsFact    = SET_CHAR;
      end;
      RepDataI.rec.Sort      = 0;
      RepDataI.rec.State     = DEALCOMM_STATE_EXEC;
      RepDataI.rec.StateDate = RepDataI.rec.Date;
      copy(repdataArr[repdataArr.size-1], RepDataI);
    end;

    repdataCache.AddRecordArray(repdataArr);

    repdataCache.Insert();

  END;

  //Подготовить плановые данные БОЦБ
  PRIVATE MACRO CreatePlanDataBO()
    var inaccdata = NULL;
    var repdataCache = RsbSQLInsert("dliarepdata.dbt");
    var repdataArr = TArray();
    var inacc = NULL;

    SC_GetPlanInAcc(@inaccdata, m_Params.DepartmentID, m_Params.ClientID, m_Params.ContractID, m_Params.BeginDate, m_Params.EndDate, m_CheckCatArr);

    if((ValType(inaccdata) != V_UNDEF) and (inaccdata.m_InAccArr.size > 0))

      var sz = 0;
      var i = 0;
      while(i < inaccdata.m_InAccArr.size)

        sz = repdataArr.size;

        inacc = inaccdata.m_InAccArr[i];

        repdataArr[sz] = TRecHandler("dliarepdata.dbt");

        repdataArr[sz].Clear();

        repdataArr[sz].rec.GUID           = m_Params.GUID;
        repdataArr[sz].rec.Department     = inacc.rec.Department;

        if(inacc.rec.FIKind == FIKIND_AVOIRISS)
          repdataArr[sz].rec.Part = REPDATAPART_EMISSIVE;
        else
          repdataArr[sz].rec.Part = REPDATAPART_CURRENCY;
        end;

        repdataArr[sz].rec.IsFact    = UNSET_CHAR;
        repdataArr[sz].rec.Account   = IIF(inacc.rec.DebAcc != "", inacc.rec.DebAcc, inacc.rec.KredAcc);
        repdataArr[sz].rec.Chapter   = inacc.rec.Chapter;
        repdataArr[sz].rec.FIID      = inacc.rec.FIID;

        repdataArr[sz].rec.Date      = date(inacc.rec.Date);

        repdataArr[sz].rec.GroundXld = inacc.rec.GroundNum;

        if(repdataArr[sz].rec.Account == inacc.rec.DebAcc)
           repdataArr[sz].rec.InSum  = inacc.rec.Sum; /*зачисление*/
        else
           repdataArr[sz].rec.OutSum = inacc.rec.Sum; /*списание*/
        end;

        if( inaccdata.m_GroundArr[sz].State == DLRQ_STATE_EXEC )
           repdataArr[sz].rec.State = DEALCOMM_STATE_EXEC;
        elif( inaccdata.m_GroundArr[sz].State == DLRQ_STATE_REJECT )
           repdataArr[sz].rec.State = DEALCOMM_STATE_REJECT;
        elif( inaccdata.m_GroundArr[sz].State == DLRQ_STATE_OVERDUE )
           repdataArr[sz].rec.State = DEALCOMM_STATE_OVERDUE;
        end;

        repdataArr[sz].rec.StateDate = inaccdata.m_GroundArr[sz].StateDate;

        repdataArr[sz].rec.OperType   = inacc.rec.OperType;
        repdataArr[sz].rec.GroundKind = inacc.rec.GroundKind;

        var query =   "with acc as (select acc.t_Account, acc.t_Place, acc.t_Owner, acc.t_Clientcontrid, acc.t_Currency "
                    + "               from dmccateg_dbt cat, dmcaccdoc_dbt acc "
                    + "              where cat.t_LevelType = 1 "
                    + "                and cat.t_Code in ('ДС Клиента, ВУ', 'ЦБ Клиента, ВУ', 'НЦБ Клиента, ВУ', 'ДМ клиента, ВУ')"
                    + "                and acc.t_Account = ? /*0*/ "
                    + "                and acc.t_CatNum = cat.t_Number "
                    + "                and acc.t_Chapter in(21, 22) "
                    + "                and acc.t_Currency  = ? /*1*/ "
                    + "                and ROWNUM = 1 )"
                    + " select acc.t_Owner Client, "
                    + "        acc.t_ClientContrID ClientContrID, "
                    + "        acc.t_Place, "
                    + "        RSI_RSB_FIInstr.FI_GetIssuerOnDate(fin.t_FIID, ? /*2*/) as IssuerID, "
                    + "        NVL(avr.t_ISIN, NVL(avr.t_LSIN, CHR(1))) as FI_Number, " 
                    + "        NVL(avr.t_Issue, CHR(1)) as Issue, " 
                    + "        NVL(avr.t_Tranche, CHR(1)) as Tranche, " 
                    + "        NVL(avr.t_Series, CHR(1)) as FI_Series, " 
                    + "        NVL(case when ? in (101,154,176) " 
                    + "                then (rsb_secur.RSI_GetDealKindName(?, ?)) " 
                    + "              else (select t_name from doprkdoc_dbt where t_dockind = ?) " 
                    + "         end,  CHR(1)) as DealKindName, " 
                    + "        rsb_secur.RSI_GetDealCodeEx(? /*4*/, ? /*5*/) as SecDealNumber "
                    + "   from acc, "
                    + "        dfininstr_dbt fin left join davrkinds_dbt avrkind ON avrkind.t_FI_Kind = fin.t_FI_Kind AND avrkind.t_AvoirKind = fin.t_AvoirKind " 
                    + "                          left join davoiriss_dbt avr ON avr.t_FIID = fin.t_FIID "
                    + "  where fin.t_FIID = acc.t_Currency "; 

        var cmd = DL_RSDCommand(query);
        cmd.AddParam(IIF(inacc.rec.DebAcc != "", inacc.rec.DebAcc, inacc.rec.KredAcc));
        cmd.AddParam(repdataArr[sz].rec.FIID);
        cmd.AddParam(m_Params.EndDate);
        cmd.AddParam(inacc.rec.DocumentKind);
        cmd.AddParam(inacc.rec.DocumentKind);
        cmd.AddParam(inacc.rec.DocumentID);
        cmd.AddParam(inacc.rec.DealKind);
        cmd.AddParam(inacc.rec.DocumentKind); 
        cmd.AddParam(inacc.rec.DocumentID);

        var DataSet = cmd.Execute();

        if(DataSet.moveNext())
          
          repdataArr[sz].rec.ClientID       = DataSet.Client;
          repdataArr[sz].rec.ContrID        = DataSet.ClientContrID;
          
          repdataArr[sz].rec.PlaceID        = DataSet.Place;
          repdataArr[sz].rec.IssuerID       = DataSet.IssuerID;

          repdataArr[sz].rec.FI_Number      = DataSet.FI_Number;
          repdataArr[sz].rec.FI_Series      = DataSet.FI_Series;
          repdataArr[sz].rec.Issue          = DataSet.Issue;
          repdataArr[sz].rec.Tranche        = DataSet.Tranche;

          repdataArr[sz].rec.DealKindName   = DataSet.DealKindName;
          repdataArr[sz].rec.DealCode       = DataSet.SecDealNumber;
          

        else //В случае если реально счета ещё нет

          repdataArr[sz].rec.ClientID       = inacc.rec.PartyID;
          repdataArr[sz].rec.ContrID        = inacc.rec.PartyContrID;

          repdataArr[sz].rec.PlaceID        = inacc.rec.PlaceID;

          query = " select RSI_RSB_FIInstr.FI_GetIssuerOnDate(fin.t_FIID, ? /*1*/) as IssuerID, "
                + "        NVL(avr.t_ISIN, NVL(avr.t_LSIN, CHR(1))) as FI_Number, " 
                + "        NVL(avr.t_Issue, CHR(1)) as Issue, " 
                + "        NVL(avr.t_Tranche, CHR(1)) as Tranche, " 
                + "        NVL(avr.t_Series, CHR(1)) as FI_Series, " 
                + "        NVL(case when ? in (101,154,176,159) " 
                + "                then (rsb_secur.RSI_GetDealKindName(?, ?)) " 
                + "              else (select t_name from doprkdoc_dbt where t_dockind = ?) " 
                + "         end,  CHR(1)) as DealKindName, " 
                + "        rsb_secur.RSI_GetDealCodeEx(? /*3*/, ? /*4*/) as SecDealNumber "
                + "   from dfininstr_dbt fin left join davrkinds_dbt avrkind ON avrkind.t_FI_Kind = fin.t_FI_Kind AND avrkind.t_AvoirKind = fin.t_AvoirKind " 
                + "                          left join davoiriss_dbt avr ON avr.t_FIID = fin.t_FIID "
                + "  where fin.t_FIID = ? /*5*/ "; 

          cmd = DL_RSDCommand(query);
          cmd.AddParam(m_Params.EndDate);
          cmd.AddParam(inacc.rec.DocumentKind);
          cmd.AddParam(inacc.rec.DocumentKind);
          cmd.AddParam(inacc.rec.DocumentID);
          cmd.AddParam(inacc.rec.DealKind);
          cmd.AddParam(inacc.rec.DocumentKind); 
          cmd.AddParam(inacc.rec.DocumentID);
          cmd.AddParam(repdataArr[sz].rec.FIID);

          DataSet = cmd.Execute();
          if(DataSet.moveNext())
            repdataArr[sz].rec.IssuerID       = DataSet.IssuerID;

            repdataArr[sz].rec.FI_Number      = DataSet.FI_Number;
            repdataArr[sz].rec.FI_Series      = DataSet.FI_Series;
            repdataArr[sz].rec.Issue          = DataSet.Issue;
            repdataArr[sz].rec.Tranche        = DataSet.Tranche;

            repdataArr[sz].rec.DealKindName   = DataSet.DealKindName;
            repdataArr[sz].rec.DealCode       = DataSet.SecDealNumber;
          end;
        end;

        i = i + 1;
      end;

      repdataCache.AddRecordArray(repdataArr);

      repdataCache.Insert();
    end;

  END;

  MACRO CreatePlanDataVA()
    var cmd, query, DataSet;
    var inaccDataArr = TArray();
    var repdataCache = RsbSQLInsert("dliarepdata.dbt");
    var repdataArr = TArray();
    var inacc = TRecHandler("dlinacc.dbt");
    var sz = 0;

    cmd = DL_RSDCommand();

    query =   " select pm.t_DocKind, pm.t_DocumentID, pm.t_PaymentID, pm.t_ValueDate, pm.t_PaymStatus, "
            + "        tk.t_ClientID, tk.t_ClientContrID, tk.t_Department, tk.t_DealCode, "
            + "        NVL((select t_name from doprkdoc_dbt where t_dockind = rsb_secur.RSI_GetDealKindName(tk.t_BOfficeKind, tk.t_DealID)), CHR(1)) as DealKindName "
            + "   from dpmpaym_dbt pm, ddl_tick_dbt tk "
            + "  where pm.t_DocKind IN ("+DL_VEKSELACCOUNTED+", "+DL_VAREPAY+", "+DL_VAENWR+") "
            + "    and pm.t_ValueDate >= ? "
            + "    and pm.t_ValueDate <= ? "
            + "    and pm.t_PaymStatus != " + PM_FINISHED
            + "    and Not Exists (select 1 from dpmlink_dbt lnk where lnk.t_LinkKind = "+PMLINK_KIND_NETTING+" and lnk.t_InitialPayment = pm.t_PaymentID)"
            + "    and tk.t_DealID = pm.t_DocumentID "
            + "    and tk.t_ClientID > 0 "
            + "    and tk.t_DealStatus > " + DL_PREPARING;

    cmd.AddParam(m_Params.BeginDate);
    cmd.AddParam(m_Params.EndDate);  

    if( m_Params.DepartmentID > 0 )
      query = query + " AND tk.t_Department = ? ";
      cmd.AddParam(m_Params.DepartmentID);
    end;

    if( m_Params.ClientID > 0 )
       query = query + " AND tk.t_ClientID = ? ";
       cmd.AddParam(m_Params.ClientID);
    end;
   
    if( m_Params.ContractID > 0 )
       query = query + " AND tk.t_ClientContrID = ? ";
       cmd.AddParam(m_Params.ContractID);
    end;

    DataSet = cmd.Execute(query);
    while(DataSet.moveNext())
      inaccDataArr.size = 0;
      
      if((VA_InnerPlan(DataSet.DocKInd, DataSet.DocumentID, DataSet.PaymentID, date(DataSet.ValueDate), m_CheckCatArr, @inaccDataArr) == true) and 
         (inaccDataArr.size > 0)
        )
        var i = 0;
        
        while(i < inaccDataArr.size)
          sz = repdataArr.size;

          copy(inacc, inaccDataArr[i].inacc);

          repdataArr[sz] = TRecHandler("dliarepdata.dbt");

          repdataArr[sz].Clear();

          repdataArr[sz].rec.GUID       = m_Params.GUID;
          repdataArr[sz].rec.Department = DataSet.Department;

          if(inacc.rec.FIKind == FIKIND_AVOIRISS)
            repdataArr[sz].rec.Part = REPDATAPART_NOTEMISSIVE;
          else
            repdataArr[sz].rec.Part = REPDATAPART_CURRENCY;
          end;

          repdataArr[sz].rec.IsFact  = UNSET_CHAR;
          repdataArr[sz].rec.Account = IIF(inacc.rec.DebAcc != "", inacc.rec.DebAcc, inacc.rec.KredAcc);
          repdataArr[sz].rec.Chapter = inacc.rec.Chapter;
          repdataArr[sz].rec.FIID    = inacc.rec.FIID;
          repdataArr[sz].rec.Date    = date(inacc.rec.Date);

          if(repdataArr[sz].rec.Account == inacc.rec.DebAcc)
             repdataArr[sz].rec.InSum  = inacc.rec.Sum; /*зачисление*/
          else
             repdataArr[sz].rec.OutSum = inacc.rec.Sum; /*списание*/
          end;

          if( DataSet.PaymStatus == PM_REJECTED )
             repdataArr[sz].rec.State     = DEALCOMM_STATE_REJECT;
             repdataArr[sz].rec.StateDate = date(DataSet.ValueDate);
          elif( DataSet.PaymStatus == PM_OVERDUE )
             repdataArr[sz].rec.State     = DEALCOMM_STATE_OVERDUE;
             repdataArr[sz].rec.StateDate = date(DataSet.ValueDate);
          end;

          repdataArr[sz].rec.ClientID  = DataSet.ClientID;
          repdataArr[sz].rec.ContrID   = DataSet.ClientContrID;
          repdataArr[sz].rec.PlaceID   = inacc.rec.PlaceID;

          repdataArr[sz].rec.IssuerID = -1;
          if(inaccDataArr[i].bnr.rec.BCID > 0)
            repdataArr[sz].rec.IssuerID   = inaccDataArr[i].bnr.rec.Issuer;
            repdataArr[sz].rec.FI_Number  = trim(inaccDataArr[i].bnr.rec.BCNumber);
            repdataArr[sz].rec.FI_Series  = inaccDataArr[i].bnr.rec.BCSeries;
          end;

          repdataArr[sz].rec.OperType     = inacc.rec.OperType;
          repdataArr[sz].rec.DealKindName = DataSet.DealKindName;
          repdataArr[sz].rec.DealCode     = DataSet.DealCode;
          repdataArr[sz].rec.GroundKind   = inacc.rec.GroundKind;

          i = i + 1;
        end;
      end;
      
    end;

    repdataCache.AddRecordArray(repdataArr);

    repdataCache.Insert();

  END;

  MACRO ПроверитьСчетНаВалОбсл( Account);
    var cmdSF, querySF, DataSetSF;
    var isCur = 0;
    cmdSF = DL_RSDCommand();
       querySF =  "SELECT 1 "
        + "  FROM dmccateg_dbt cat, dmcaccdoc_dbt doc, dsfcontr_dbt sf "
        + " WHERE     cat.t_LevelType = 1 "
        + "       AND cat.t_Code IN ('ДС Клиента, ВУ', "
        + "                          'ЦБ Клиента, ВУ', "
        + "                          'НЦБ Клиента, ВУ'," 
        + "                          'ДМ клиента, ВУ') "
        + "       AND doc.t_CatNum = cat.t_Number "
        + "       AND doc.t_Chapter IN (21, 22) "
        + "       AND doc.T_ACCOUNT = ? "
        + "       AND sf.t_ID = doc.t_ClientContrID "
        + "       AND sf.t_servKind = 21 "
        + "       AND ROWNUM = 1 "
        ;
    cmdSF.AddParam(Account);

    DataSetSF = cmdSF.Execute(querySF);
    if(DataSetSF.moveNext())
      isCur = 1;
    end;

    Return isCur;
  END;

 
  MACRO CreatePlanDataDV()
    var cmd, query, DataSet;
    var inaccDataArr = TArray();
    var repdataCache = RsbSQLInsert("dliarepdata.dbt");
    var repdataArr = TArray();
    var inacc = TRecHandler("dlinacc.dbt");
    var sz = 0;
    var IsCur = 0;

    cmd = DL_RSDCommand();

    query =   " select q.*, "
            + "        NVL((select t_name from doprkdoc_dbt where t_dockind = q.DocKind), CHR(1)) as DealKindName "
            + "   from (select pm.t_DocKind as DocKind, "
            + "                pm.t_DocumentID as DocID, "
            + "                pm.t_PaymentID as PaymentID, "
            + "                0 as DlComID, "
            + "                pm.t_ValueDate as ValueDate, "
            + "                pm.t_PaymStatus as PaymStatus, "
            + "                nd.t_Client as ClientID, "
            + "                nd.t_ClientContr as ClientContrID, "
            + "                nd.t_Department as Department, "
            + "                nd.t_Code as DealCode "
            + "           from dpmpaym_dbt pm, ddvndeal_dbt nd, ddvnfi_dbt nfi1, dfininstr_dbt fin "
            + "          where pm.t_DocKind IN ("+DL_DVDEALT3+") "
            + "            and nd.t_IsPFI = 'X' "
            + "            and pm.t_ValueDate >= ? "
            + "            and pm.t_ValueDate <= ? "
            + "            and pm.t_PaymStatus != " + PM_FINISHED
            + "            and Not Exists (select 1 from dpmlink_dbt lnk where lnk.t_LinkKind = "+PMLINK_KIND_NETTING+" and lnk.t_InitialPayment = pm.t_PaymentID)"
            + "            and nd.t_ID = pm.t_DocumentID "
            + "            and nd.t_Client > 0 "
            + "            and nd.t_State > " + DVDEAL_PREP
            + "            and nfi1.t_DealID = nd.t_ID "
            + "            and nfi1.t_Type = " +DVSETTLEMET_STATE
            + "            and fin.t_FIID = nfi1.t_FIID "
            + "         UNION ALL "
            + "         select dlcomis.t_DocKind as DocKind, "
            + "                dlcomis.t_DocID as DocID, "
            + "                0 as PaymentID, "
            + "                dlcomis.t_ID as DlComID, "
            + "                dlcomis.t_PlanPayDate as ValueDate, "
            + "                0 as PaymStatus, "
            + "                nd.t_Client as ClientID, "
            + "                nd.t_ClientContr as ClientContrID, "
            + "                nd.t_Department as Department, "
            + "                nd.t_Code as DealCode "
            + "           from ddlcomis_dbt dlcomis, ddvndeal_dbt nd, ddvnfi_dbt nfi1, dfininstr_dbt fin "
            + "          where dlcomis.t_DocKind IN (" + DL_DVDEALT3 + "," + DL_DVNDEAL + ") "
            + "            and nd.t_IsPFI = 'X' "
            + "            and dlcomis.t_FactPayDate = " + GetSQLDate(date(0,0,0))
            + "            and dlcomis.t_PlanPayDate >= ? "
            + "            and dlcomis.t_PlanPayDate <= ? "
            + "            and nd.t_ID = dlcomis.t_DocID "
            + "            and nd.t_Client > 0 "
            + "            and nd.t_State > " + DVDEAL_PREP
            + "            and nfi1.t_DealID = nd.t_ID "
            + "            and fin.t_FIID = nfi1.t_FIID "
            + "            and fin.t_FI_KIND not in ( " + FIKIND_METAL + " ) "
            + "         UNION ALL "
            + "         select pm.t_DocKind as DocKind, "
            + "                pm.t_DocumentID as DocID, "
            + "                pm.t_PaymentID as PaymentID, "
            + "                0 as DlComID, "
            + "                pm.t_ValueDate as ValueDate, "
            + "                pm.t_PaymStatus as PaymStatus, "
            + "                tk.t_Client as ClientID, "
            + "                tk.t_ClientContr as ClientContrID, "
            + "                tk.t_Department as Department, "
            + "                tk.t_Code as DealCode "
            + "           from dpmpaym_dbt pm, ddvndeal_dbt tk, dfininstr_dbt fin "
            + "          where pm.t_DocKind IN ("+DL_DVFXDEAL+") "
            + "            and pm.t_ValueDate >= ? "
            + "            and pm.t_ValueDate <= ? "
            + "            and pm.t_PaymStatus != " + PM_FINISHED
            + "            and fin.t_FIID = pm.t_FIID "
            + "            and fin.t_FI_KIND not in ( " + FIKIND_METAL + " ) "
            + "            and Not Exists (select 1 from dpmlink_dbt lnk where lnk.t_LinkKind = "+PMLINK_KIND_NETTING+" and lnk.t_InitialPayment = pm.t_PaymentID)"
            + "            and tk.t_ID = pm.t_DocumentID "
            + "            and tk.t_Client > 0 "
            + "            and tk.t_State > " + DVDEAL_PREP
            + "            and Rsb_Secur.IsDVFXDEAL(Rsb_Secur.get_OperationGroupDocKind(Rsb_Secur.get_OperSysTypes(tk.t_Kind, tk.t_DocKind), tk.t_DocKind)) = 1 "
            + "            and ( EXISTS (select 1 from dpartyown_dbt Pto where Pto.T_PARTYKIND = " + String (PTK_MARKETPLASE)
            + "                    and Pto.T_PARTYID = tk.T_CONTRACTOR ) and tk.t_Sector = chr(88) "
            + "                ) "
            + "         UNION ALL "
            + "         select dlcomis.t_DocKind as DocKind, "
            + "                dlcomis.t_DocID as DocID, "
            + "                0 as PaymentID, "
            + "                dlcomis.t_ID as DlComID, "
            + "                dlcomis.t_PlanPayDate as ValueDate, "
            + "                0 as PaymStatus, "
            + "                tk.t_Client as ClientID, "
            + "                tk.t_ClientContr as ClientContrID, "
            + "                tk.t_Department as Department, "
            + "                tk.t_Code as DealCode "
            + "           from ddlcomis_dbt dlcomis, ddvndeal_dbt tk, ddvnfi_dbt nfi1, dfininstr_dbt fin "
            + "          where dlcomis.t_DocKind IN ("+DL_DVFXDEAL+") "
            + "            and dlcomis.t_FactPayDate = " + GetSQLDate(date(0,0,0))
            + "            and dlcomis.t_PlanPayDate >= ? "
            + "            and dlcomis.t_PlanPayDate <= ? "
            + "            and tk.t_ID = dlcomis.t_DocID "
            + "            and tk.t_Client > 0 "
            + "            and tk.t_State > " + DVDEAL_PREP
            + "            and nfi1.t_DealID = tk.t_ID "
            + "            and fin.t_FIID = nfi1.t_FIID "
            + "            and fin.t_FI_KIND not in ( " + FIKIND_METAL + " ) "
            + "            and Rsb_Secur.IsDVFXDEAL(Rsb_Secur.get_OperationGroupDocKind(Rsb_Secur.get_OperSysTypes(tk.t_Kind, tk.t_DocKind), tk.t_DocKind)) = 1 "
            + "            and ( EXISTS (select 1 from dpartyown_dbt Pto where Pto.T_PARTYKIND = " + String (PTK_MARKETPLASE)
            + "                    and Pto.T_PARTYID = tk.T_CONTRACTOR ) and tk.t_Sector = chr(88) "
            + "                ) ";
   if (m_Params.IsUseDV_Cur == SET_CHAR)
      query  = query        
            + "         UNION ALL "
            + "         select pm.t_DocKind as DocKind, "
            + "                pm.t_DocumentID as DocID, "
            + "                pm.t_PaymentID as PaymentID, "
            + "                0 as DlComID, "
            + "                pm.t_ValueDate as ValueDate, "
            + "                pm.t_PaymStatus as PaymStatus, "
            + "                tk.t_Client as ClientID, "
            + "                tk.t_ClientContr as ClientContrID, "
            + "                tk.t_Department as Department, "
            + "                tk.t_Code as DealCode "
            + "           from dpmpaym_dbt pm, ddvndeal_dbt tk, dfininstr_dbt fin  "
            + "          where pm.t_DocKind IN (" + DL_DVFXDEAL + "," + DL_DVNDEAL+") "
            + "            and pm.t_ValueDate >= ? "
            + "            and pm.t_ValueDate <= ? "
            + "            and pm.t_PaymStatus != " + PM_FINISHED
            + "            and tk.t_ID = pm.t_DocumentID "
            + "            and tk.t_Client > 0 "
            + "            and tk.t_State > " + DVDEAL_PREP
            + "            and fin.t_FIID = pm.t_FIID "
            + "            and fin.t_FI_KIND in ( " + FIKIND_METAL + " ) "
            + "         UNION ALL "
            + "         select dlcomis.t_DocKind as DocKind, "
            + "                dlcomis.t_DocID as DocID, "
            + "                0 as PaymentID, "
            + "                dlcomis.t_ID as DlComID, "
            + "                dlcomis.t_PlanPayDate as ValueDate, "
            + "                0 as PaymStatus, "
            + "                nd.t_Client as ClientID, "
            + "                nd.t_ClientContr as ClientContrID, "
            + "                nd.t_Department as Department, "
            + "                nd.t_Code as DealCode "
            + "           from ddlcomis_dbt dlcomis, ddvndeal_dbt nd, ddvnfi_dbt nfi1, dfininstr_dbt fin "
            + "          where dlcomis.t_DocKind IN (" + DL_DVFXDEAL + "," + DL_DVNDEAL + ") "
            + "            and dlcomis.t_FactPayDate = " + GetSQLDate(date(0,0,0))
            + "            and dlcomis.t_PlanPayDate >= ? "
            + "            and dlcomis.t_PlanPayDate <= ? "
            + "            and nd.t_ID = dlcomis.t_DocID "
            + "            and nd.t_Client > 0 "
            + "            and nd.t_State > " + DVDEAL_PREP
            + "            and nfi1.t_DealID = nd.t_ID "
            + "            and fin.t_FIID = nfi1.t_FIID "
            + "            and fin.t_FI_KIND in ( " + FIKIND_METAL + " ) ";
   end;
   query  = query   
            + "        ) q "
            + " where q.ClientID > 0 ";

    cmd.AddParam(m_Params.BeginDate);
    cmd.AddParam(m_Params.EndDate);

    cmd.AddParam(m_Params.BeginDate);
    cmd.AddParam(m_Params.EndDate);

    cmd.AddParam(m_Params.BeginDate);
    cmd.AddParam(m_Params.EndDate);

    cmd.AddParam(m_Params.BeginDate);
    cmd.AddParam(m_Params.EndDate);

    if (m_Params.IsUseDV_Cur == SET_CHAR)
      cmd.AddParam(m_Params.BeginDate);
      cmd.AddParam(m_Params.EndDate);

      cmd.AddParam(m_Params.BeginDate);
      cmd.AddParam(m_Params.EndDate);
    end;

    if( m_Params.DepartmentID > 0)
      query = query + " AND q.Department = ? ";
      cmd.AddParam(m_Params.DepartmentID);
    end;

    if( m_Params.ClientID > 0 )
       query = query + " AND q.ClientID = ? ";
       cmd.AddParam(m_Params.ClientID);
    end;
   
    if( m_Params.ContractID > 0 )
       query = query + " AND q.ClientContrID = ? ";
       cmd.AddParam(m_Params.ContractID);
    end;

    DataSet = cmd.Execute(query);
    while(DataSet.moveNext())

      if((DV_GetPlanInAcc(DataSet.DocKInd, DataSet.DocID, DataSet.PaymentID, DataSet.DlComID, date(DataSet.ValueDate), m_CheckCatArr, @inaccDataArr) == true) and 
         (inaccDataArr.size > 0)
        )

        var i = 0;
        while(i < inaccDataArr.size)
          sz = repdataArr.size;

          copy(inacc, inaccDataArr[i].inacc);

          IsCur = 0;
          if ( (m_Params.IsUseDV == UNSET_CHAR) OR (m_Params.IsUseDV_Cur == UNSET_CHAR) )   
          IsCur = ПроверитьСчетНаВалОбсл(IIF(inacc.rec.DebAcc != "", inacc.rec.DebAcc, inacc.rec.KredAcc) ) ;
            if (  ((m_Params.IsUseDV_Cur == SET_CHAR) AND IsCur == 0 ) OR ((m_Params.IsUseDV == SET_CHAR) AND IsCur == 1 ))
              i = i + 1;
              continue;
            end;
          end;

          repdataArr[sz] = TRecHandler("dliarepdata.dbt");

          repdataArr[sz].Clear();

          repdataArr[sz].rec.GUID       = m_Params.GUID;
          repdataArr[sz].rec.Department = DataSet.Department;

          if(inacc.rec.FIKind == FIKIND_AVOIRISS)
            repdataArr[sz].rec.Part = REPDATAPART_EMISSIVE;
          elif(inacc.rec.FIKind == FIKIND_CURRENCY)
            repdataArr[sz].rec.Part = REPDATAPART_CURRENCY;
          else //if(inacc.rec.FIKind == FIKIND_METAL)
            repdataArr[sz].rec.Part = REPDATAPART_METAL;
          end;

          repdataArr[sz].rec.IsFact  = UNSET_CHAR;
          repdataArr[sz].rec.Account = IIF(inacc.rec.DebAcc != "", inacc.rec.DebAcc, inacc.rec.KredAcc);
          repdataArr[sz].rec.Chapter = inacc.rec.Chapter;
          repdataArr[sz].rec.FIID    = inacc.rec.FIID;
          repdataArr[sz].rec.Date    = date(inacc.rec.Date);

          if(repdataArr[sz].rec.Account == inacc.rec.DebAcc)
             repdataArr[sz].rec.InSum  = inacc.rec.Sum; /*зачисление*/
          else
             repdataArr[sz].rec.OutSum = inacc.rec.Sum; /*списание*/
          end;

          if( DataSet.PaymStatus == PM_REJECTED )
             repdataArr[sz].rec.State     = DEALCOMM_STATE_REJECT;
             repdataArr[sz].rec.StateDate = date(DataSet.ValueDate);
          elif( DataSet.PaymStatus == PM_OVERDUE )
             repdataArr[sz].rec.State     = DEALCOMM_STATE_OVERDUE;
             repdataArr[sz].rec.StateDate = date(DataSet.ValueDate);
          end;

          repdataArr[sz].rec.ClientID  = DataSet.ClientID;
          repdataArr[sz].rec.ContrID   = DataSet.ClientContrID;
          repdataArr[sz].rec.PlaceID   = inacc.rec.PlaceID;

          repdataArr[sz].rec.IssuerID = -1;

          repdataArr[sz].rec.OperType     = inacc.rec.OperType;
          repdataArr[sz].rec.DealKindName = DataSet.DealKindName;
          repdataArr[sz].rec.DealCode     = DataSet.DealCode;
          repdataArr[sz].rec.GroundKind   = inacc.rec.GroundKind;

          i = i + 1;
        end;

      end;
    end;

    repdataCache.AddRecordArray(repdataArr);

    repdataCache.Insert();

  END;

  MACRO CreatePlanDataNTG()
    var cmd, query, DataSet;
    var inaccDataArr = TArray();
    var repdataCache = RsbSQLInsert("dliarepdata.dbt");
    var repdataArr = TArray();
    var inacc = TRecHandler("dlinacc.dbt");
    var sz = 0;
    var IsCur = 0;

    cmd = DL_RSDCommand();

    query =   " select pm.t_DocKind, pm.t_DocumentID, pm.t_PaymentID, pm.t_ValueDate, pm.t_PaymStatus, "
            + "        nt.t_ClientID, nt.t_ClientContrID, nt.t_Department, nt.t_DealNumber, "
            + "        NVL((select t_name from doprkdoc_dbt where t_dockind = pm.t_DocKind), CHR(1)) as DealKindName "
            + "   from ddl_nett_dbt nt, dpmpaym_dbt pm "
            + "  where pm.t_DocKind = nt.t_DocKind "
            + "    and pm.t_DocumentID = nt.t_NettingID "
            + "    and pm.t_ValueDate >= ? "
            + "    and pm.t_ValueDate <= ? "
            + "    and pm.t_PaymStatus != " + PM_FINISHED
            + "    and nt.t_ClientID > 0 "
            + "    and nt.t_Status > " + DL_PREPARING;

    cmd.AddParam(m_Params.BeginDate);
    cmd.AddParam(m_Params.EndDate);
    
    if( (m_Params.IsUseVA == SET_CHAR) AND ((m_Params.IsUseDV == SET_CHAR) OR (m_Params.IsUseDV_Cur == SET_CHAR)))
      query = query + " and nt.t_IdentProgram IN (41, 42) ";
    elif(m_Params.IsUseVA == SET_CHAR)
      query = query + " and nt.t_IdentProgram = 41 ";
    elif((m_Params.IsUseDV == SET_CHAR) OR (m_Params.IsUseDV_Cur == SET_CHAR))
      query = query + " and nt.t_IdentProgram = 42 ";
    end;

    if( m_Params.DepartmentID > 0)
      query = query + " AND nt.t_Department = ? ";
      cmd.AddParam(m_Params.DepartmentID);
    end;

    if( m_Params.ClientID > 0 )
       query = query + " AND nt.t_ClientID = ? ";
       cmd.AddParam(m_Params.ClientID);
    end;
   
    if( m_Params.ContractID > 0 )
       query = query + " AND nt.t_ClientContrID = ? ";
       cmd.AddParam(m_Params.ContractID);
    end;
    
    DataSet = cmd.Execute(query);
    while(DataSet.moveNext())

      if((NTG_GetPlanInAcc(DataSet.DocKInd, DataSet.DocumentID, DataSet.PaymentID, date(DataSet.ValueDate), m_CheckCatArr, @inaccDataArr) == true) and 
         (inaccDataArr.size > 0)
        )

        var i = 0;
        while(i < inaccDataArr.size)
          sz = repdataArr.size;

          copy(inacc, inaccDataArr[i].inacc);
          IsCur = 0;
          if ( (m_Params.IsUseDV == UNSET_CHAR) OR (m_Params.IsUseDV_Cur == UNSET_CHAR) )   
            IsCur = ПроверитьСчетНаВалОбсл(IIF(inacc.rec.DebAcc != "", inacc.rec.DebAcc, inacc.rec.KredAcc) ) ;
            if (  ((m_Params.IsUseDV_Cur == SET_CHAR) AND IsCur == 0 ) OR ((m_Params.IsUseDV == SET_CHAR) AND IsCur == 1 ))
              i = i + 1;
              continue;
            end;
          end;

          repdataArr[sz] = TRecHandler("dliarepdata.dbt");

          repdataArr[sz].Clear();

          repdataArr[sz].rec.GUID       = m_Params.GUID;
          repdataArr[sz].rec.Department = DataSet.Department;

          if(inacc.rec.FIKind == FIKIND_AVOIRISS)
            repdataArr[sz].rec.Part = IIF(DataSet.IdentProgram == 41, REPDATAPART_NOTEMISSIVE, REPDATAPART_EMISSIVE);
          else
            repdataArr[sz].rec.Part = REPDATAPART_CURRENCY;
          end;

          repdataArr[sz].rec.IsFact  = UNSET_CHAR;
          repdataArr[sz].rec.Account = IIF(inacc.rec.DebAcc != "", inacc.rec.DebAcc, inacc.rec.KredAcc);
          repdataArr[sz].rec.Chapter = inacc.rec.Chapter;
          repdataArr[sz].rec.FIID    = inacc.rec.FIID;
          repdataArr[sz].rec.Date    = date(inacc.rec.Date);

          if(repdataArr[sz].rec.Account == inacc.rec.DebAcc)
             repdataArr[sz].rec.InSum  = inacc.rec.Sum; /*зачисление*/
          else
             repdataArr[sz].rec.OutSum = inacc.rec.Sum; /*списание*/
          end;

          if( DataSet.PaymStatus == PM_REJECTED )
             repdataArr[sz].rec.State     = DEALCOMM_STATE_REJECT;
             repdataArr[sz].rec.StateDate = date(DataSet.ValueDate);
          elif( DataSet.PaymStatus == PM_OVERDUE )
             repdataArr[sz].rec.State     = DEALCOMM_STATE_OVERDUE;
             repdataArr[sz].rec.StateDate = date(DataSet.ValueDate);
          end;

          repdataArr[sz].rec.ClientID  = DataSet.ClientID;
          repdataArr[sz].rec.ContrID   = DataSet.ClientContrID;
          repdataArr[sz].rec.PlaceID   = inacc.rec.PlaceID;

          repdataArr[sz].rec.IssuerID = -1;

          repdataArr[sz].rec.OperType     = inacc.rec.OperType;
          repdataArr[sz].rec.DealKindName = DataSet.DealKindName;
          repdataArr[sz].rec.DealCode     = DataSet.DealNumber;
          repdataArr[sz].rec.GroundKind   = inacc.rec.GroundKind;

          i = i + 1;
        end;
      end;
    end;

    repdataCache.AddRecordArray(repdataArr);

    repdataCache.Insert();
  END;

  //Отобрать данные по счетам, где были остатки на дату начала отчёта, но не было и не будет проводок за отчётный период
  PRIVATE MACRO CreateDataWithoutMove()
    var repdataCache = RsbSQLInsert("dliarepdata.dbt");
    var repdataArr = TArray();

    var cmd = DL_RSDCommand();

    var sqlQuery = " SELECT mc.t_DepartmentID Department, mc.t_Owner Client, mc.t_ClientContrID, mc.t_Place, mc.t_Account, mc.t_Currency, mc.t_Chapter, " +
                   "        fin.t_FI_Code, fin.t_Name AvrName, fin.t_FI_Kind, case when fin.T_FIID = "+NATCUR+" then '"+string(m_Params.CCA_NatCUR)+"' else fin.T_CCY end t_CCY, " +
                   "        NVL(avrkind.t_IsEmissive, chr(0)) IsEmiss, " +
                   "        RSI_RSB_FIInstr.FI_GetIssuerOnDate(fin.t_FIID, ?) as IssuerID, " +
                   "        NVL(avr.t_ISIN, NVL(avr.t_LSIN, CHR(1))) as FI_Number, " +
                   "        NVL(avr.t_Issue, CHR(1)) as Issue, " +
                   "        NVL(avr.t_Tranche, CHR(1)) as Tranche, " +
                   "        NVL(avr.t_Series, CHR(1)) as FI_Series " +
                   "   FROM dfininstr_dbt fin left join davrkinds_dbt avrkind ON avrkind.t_FI_Kind = fin.t_FI_Kind AND avrkind.t_AvoirKind = fin.t_AvoirKind " +
                   "                          left join davoiriss_dbt avr ON avr.t_FIID = fin.t_FIID, "
                   "        dsfcontr_dbt sf, " +
                   "        (SELECT DISTINCT mc.t_DepartmentID, mc.t_Owner, mc.t_ClientContrID, mc.t_Place, mc.t_Account, mc.t_Currency, mc.t_Chapter " +
                   "           FROM dmccateg_dbt cat, dmcaccdoc_dbt mc " +
                   "          WHERE cat.t_LevelType = 1 " +
                   "            AND cat.t_Code in ('ДС Клиента, ВУ', 'ЦБ Клиента, ВУ', 'НЦБ Клиента, ВУ', 'ДМ клиента, ВУ')"
                   "            AND mc.t_CatNum = cat.t_Number " +
                   "            AND mc.t_Chapter in(21, 22) ) mc " +
                   " WHERE exists(select acc.* " +
                   "                from daccount_dbt acc " +
                   "               where acc.t_Chapter       = mc.t_Chapter " +
                   "                 and acc.t_Account       = mc.t_Account " +
                   "                 and acc.t_Code_Currency = mc.t_Currency " +
                   "                 and (acc.t_Close_Date = TO_DATE('01.01.0001','DD.MM.YYYY') or acc.t_Close_Date >= ?) " +
                   "                 and acc.t_Open_Date    <= ? " +
                   "             ) " +
                   "   AND not exists(select rd.* " +
                   "                    from ddliarepdata_dbt rd " +
                   "                   where rd.t_Chapter    = mc.t_Chapter " +
                   "                     and rd.t_Account    = mc.t_Account " +
                   "                     and rd.t_FIID       = mc.t_Currency " +
                   "                     and rd.t_Department = mc.t_DepartmentID " +
                   "                     and rd.t_PlaceID    = mc.t_Place " +
                   "                     and rd.t_ClientID   = mc.t_Owner " +
                   "                     and rd.t_ContrID    = mc.t_ClientContrID " +
                   "                     and rd.t_GUID       = ? " +
                   "                 ) " +    
                   "   AND fin.t_FIID = mc.t_Currency " +
                   "   AND fin.t_FI_KIND in( " + string(FIKIND_CURRENCY) + "," + string(FIKIND_AVOIRISS) + ") " +
                   "   AND sf.t_ID = mc.t_ClientContrID " +
                   "   AND sf.t_DateBegin <= ? " +
                   "   AND (sf.t_DateClose >= ? OR sf.t_DateClose = TO_DATE('01.01.0001', 'DD.MM.YYYY')) " +
                   "   AND sf.t_ServKind in( ";
    
    cmd.AddParam(m_Params.EndDate);
    cmd.AddParam(m_Params.BeginDate);
    cmd.AddParam(m_Params.EndDate);
    cmd.AddParam(m_Params.GUID);
    cmd.AddParam(m_Params.EndDate);
    cmd.AddParam(m_Params.BeginDate);

    var Delim = false;
    if( m_Params.IsUseBO == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(PTSK_STOCKDL);
       Delim = true;
    end;

    if( m_Params.IsUseDV == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(PTSK_DV);
       Delim = true;
    end;

    if( m_Params.IsUseDV_Cur == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(PTSK_CM);
       Delim = true;
    end;

    if( m_Params.IsUseVA == SET_CHAR )
       sqlQuery = sqlQuery + IIF(Delim, ",", "") + string(PTSK_VEKSACC);
       Delim = true;
    end;

    sqlQuery = sqlQuery + " ) ";

    if( m_Params.DepartmentID > 0)
      sqlQuery = sqlQuery + " AND mc.t_DepartmentID = ? ";
      cmd.AddParam(m_Params.DepartmentID);
    end;

    if( m_Params.ClientID > 0 )
       sqlQuery = sqlQuery + " AND mc.t_Owner = ? ";
       cmd.AddParam(m_Params.ClientID);
    end;
   
    if( m_Params.ContractID > 0 )
       sqlQuery = sqlQuery + " AND mc.t_ClientContrID = ? ";
       cmd.AddParam(m_Params.ContractID);
    end;

    sqlQuery = sqlQuery + " ORDER BY mc.t_DepartmentID, mc.t_Owner, mc.t_ClientContrID, mc.t_Place, mc.t_Account, mc.t_Currency, mc.t_Chapter ";
    
    var RepData = cmd.Execute(sqlQuery);
    
    while( RepData.MoveNext() )

      var RepDataI = TRecHandler("dliarepdata.dbt");

      RepDataI.Clear();

      RepDataI.rec.InRest = DL_GetRestAccountParam(RepData.Chapter, RepData.Currency, RepData.Account, m_Params.BeginDate-1);

      if( RepDataI.rec.InRest != 0.0 )

         RepDataI.rec.GUID           = m_Params.GUID;
         RepDataI.rec.Department     = RepData.Department;
         RepDataI.rec.ClientID       = RepData.Client;
         RepDataI.rec.ContrID        = RepData.ClientContrID;
         if( RepData.FI_Kind == FIKIND_AVOIRISS )
            RepDataI.rec.Part = IIF(RepData.IsEmiss == SET_CHAR, REPDATAPART_EMISSIVE, REPDATAPART_NOTEMISSIVE);
         else
            RepDataI.rec.Part = REPDATAPART_CURRENCY;
         end;
         RepDataI.rec.IsFact         = "_";
         RepDataI.rec.PlaceID        = RepData.Place;
         RepDataI.rec.Account        = RepData.Account;
         RepDataI.rec.Chapter        = RepData.Chapter;
         RepDataI.rec.FIID           = RepData.Currency;
         RepDataI.rec.IssuerID       = RepData.IssuerID;
         RepDataI.rec.FI_Number      = RepData.FI_Number;
         RepDataI.rec.FI_Series      = RepData.FI_Series;
         RepDataI.rec.Issue          = RepData.Issue;
         RepDataI.rec.Tranche        = RepData.Tranche;
         RepDataI.rec.Date           = m_Params.BeginDate;

         repdataArr[repdataArr.size] = TRecHandler("dliarepdata.dbt");
         copy(repdataArr[repdataArr.size-1], RepDataI);
      end;
    end;

    repdataCache.AddRecordArray(repdataArr);

    repdataCache.Insert();

  END;

  MACRO Create()
    //Фактические данные

    CreateFactData();

    //Планируемые данные
    if(m_Params.IsUseBO == SET_CHAR)
      CreatePlanDataBO();
    end;

    if( m_Params.IsUseVA == SET_CHAR )
      CreatePlanDataVA();
    end;

    if( (m_Params.IsUseDV == SET_CHAR) OR (m_Params.IsUseDV_Cur == SET_CHAR) )
      CreatePlanDataDV();
    end; 

    if( (m_Params.IsUseVA == SET_CHAR) OR (m_Params.IsUseDV == SET_CHAR) OR (m_Params.IsUseDV_Cur == SET_CHAR)) //неттинг БОЦБ обрабатывается сразу в CreatePlanDataBO
      CreatePlanDataNTG();
    end;

    // Данные по счетам без движения
    CreateDataWithoutMove();
  END;

END;


////////////////////////////////////////////////////////////////////////////////////////////
//Печать отчета
////////////////////////////////////////////////////////////////////////////////////////////

PRIVATE VAR TableHeader1 =
"-----------------T-------------------------T-----------------T-----------------T-----------------T-----------------T------------------T------------------T------------------T-------------------┐\n"+
"│ Дата расчетной │  Наименование расчетной │      Вид        │        №        │      Вид        │       №         │ Входящий остаток │ Зачисление (шт.) │  Списание (шт.)  │ Исходящий остаток │\n"+
"│    операции    │       операции          │ сделки/операции │ сделки/операции │ подтверждающего │ подтверждающего │       (шт.)      │                  │                  │       (шт.)       │\n"+
"│                │                         │     с ц/б       │     с ц/б       │    документа    │    документа    │                  │                  │                  │                   │\n"+
"│                │                         │                 │                 │                 │                 │                  │                  │                  │                   │\n"+
"+----------------+-------------------------+-----------------+-----------------+-----------------+-----------------+------------------+------------------+------------------+-------------------+";

PRIVATE VAR DealCommTableHeader1 =
"Обязательства по сделке\n"+
"-----------------T-------------------------T-----------------T-----------------T-----------------T-----------------T------------------T------------------T--------------------┐\n"+
"│   Планируемая  │    Вид обязательства    │      Вид        │        №        │    Изменение    │ Дата изменения  │   Планируемое    │   Планируемое    │ Плановый исходящий │\n"+
"│ дата исполнения│                         │ сделки/операции │ сделки/операции │  обязательства  │                 │ зачисление (шт.) │  списание (шт.)  │    остаток (шт.)   │\n"+
"│                │                         │     с ц/б       │     с ц/б       │                 │                 │                  │                  │                    │\n"+
"│                │                         │                 │                 │                 │                 │                  │                  │                    │\n"+
"+----------------+-------------------------+-----------------+-----------------+-----------------+-----------------+------------------+------------------+--------------------+";


PRIVATE VAR TableHeader2 =
"-----------------T-------------------------T-----------------T-----------------T-----------------T-----------------T------------------T------------------T------------------T-------------------┐\n"+
"│ Дата расчетной │  Наименование расчетной │      Вид        │        №        │      Вид        │       №         │ Входящий остаток │ Зачисление (шт.) │  Списание (шт.)  │ Исходящий остаток │\n"+
"│    операции    │       операции          │ сделки/операции │ сделки/операции │ подтверждающего │ подтверждающего │       (шт.)      │                  │                  │       (шт.)       │\n"+
"│                │                         │     с ц/б       │     с ц/б       │    документа    │    документа    │                  │                  │                  │                   │\n"+
"│                │                         │                 │                 │                 │                 │                  │                  │                  │                   │\n"+
"+----------------+-------------------------+-----------------+-----------------+-----------------+-----------------+------------------+------------------+------------------+-------------------+";

PRIVATE VAR DealCommTableHeader2 =
"Обязательства по сделке\n"+
"-----------------T-------------------------T-----------------T-----------------T-----------------T-----------------T------------------T------------------T--------------------┐\n"+
"│   Планируемая  │    Вид обязательства    │      Вид        │        №        │    Изменение    │ Дата изменения  │   Планируемое    │   Планируемое    │ Плановый исходящий │\n"+
"│ дата исполнения│                         │ сделки/операции │ сделки/операции │  обязательства  │                 │ зачисление (шт.) │  списание (шт.)  │    остаток (шт.)   │\n"+
"│                │                         │     с ц/б       │     с ц/б       │                 │                 │                  │                  │                    │\n"+
"│                │                         │                 │                 │                 │                 │                  │                  │                    │\n"+
"+----------------+-------------------------+-----------------+-----------------+-----------------+-----------------+------------------+------------------+--------------------+";


PRIVATE VAR TableHeader3 =
"-----------------T-------------------------T-----------------T-----------------T-----------------T-----------------T------------------T------------------T------------------T-------------------┐\n"+
"│ Дата расчетной │  Наименование расчетной │      Вид        │        №        │      Вид        │       №         │ Входящий остаток │    Зачисление    │     Списание     │ Исходящий остаток │\n"+
"│    операции    │       операции          │ сделки/операции │ сделки/операции │ подтверждающего │ подтверждающего │                  │                  │                  │                   │\n"+
"│                │                         │     с ц/б       │     с ц/б       │    документа    │    документа    │                  │                  │                  │                   │\n"+
"│                │                         │                 │                 │                 │                 │                  │                  │                  │                   │\n"+
"+----------------+-------------------------+-----------------+-----------------+-----------------+-----------------+------------------+------------------+------------------+-------------------+";

PRIVATE VAR DealCommTableHeader3 =
"Обязательства по сделке\n"+
"-----------------T-------------------------T-----------------T-----------------T-----------------T-----------------T------------------T------------------T--------------------┐\n"+
"│   Планируемая  │    Вид обязательства    │      Вид        │        №        │    Изменение    │ Дата изменения  │                  │                  │      Исходящий     │\n"+
"│ дата исполнения│                         │ сделки/операции │ сделки/операции │  обязательства  │                 │    Зачислено     │     Списано      │       остаток      │\n"+
"│                │                         │                 │                 │                 │                 │                  │                  │                    │\n"+
"│                │                         │                 │                 │                 │                 │                  │                  │                    │\n"+
"+----------------+-------------------------+-----------------+-----------------+-----------------+-----------------+------------------+------------------+--------------------+";


PRIVATE CLASS (DL_CReportTemplate) DL_InAccIA_Report(params)
  var m_DepID, m_DepCode, m_ContrNumber:string = "";
  var m_CurrSheetName = "", m_NoData = true, m_PrintDep = false, m_PrintDate = false, m_RegisterTable = false, m_PrintAccount = false;
  var m_PrevOutRest:double = 0.0, m_PrevInRest :double =0.0, m_ItogIn:money = $0.0, m_ItogOut:money = $0.0, m_PlanItogIn:double =0.0, m_PlanItogOut:double =0.0;
  var m_prevCCY = "", m_PrevContrCat:integer = -1;
  var m_PartyShNamesArr = TArray();
  var m_RepData;
  private const TEMPLATE_SHEET_NAME = "Индивидуальный счет ВУ";
  PRIVATE VAR m_Params = Params;
  
  var PrevClient = -1, PrevContr = -1, PrevPart = 0, PrevFIID = -1, PrevAccount = "", PrevIsFact = "U";

  PRIVATE MACRO ПолучитьКороткоеИмяСубъекта( PartyID )

    var party_name:string = "";

    if( PartyID >= 0 )
       if(ValType(m_PartyShNamesArr[PartyID]) != V_UNDEF)
          party_name = m_PartyShNamesArr[PartyID];
       else
          var rParty = TRecHandler("party.dbt");
          if( not ПолучитьСубъекта(PartyID, rParty) )
             party_name = rParty.rec.ShortName;
             m_PartyShNamesArr[PartyID] = party_name;
          end;
       end;
    end;

    return party_name;
  END;

  PRIVATE MACRO PrintMode():INTEGER
    if( (m_Params.IsExportToExel == SET_CHAR) and (m_Params.IsUseApp == "X") )
       return DL_OUTREPORT_EXCEL;
    elif( (m_Params.IsExportToExel == SET_CHAR) and (m_Params.IsUseApp != "X") )
       return DL_OUTREPORT_EXCEL_NO_FORMAT;
    else
       return DL_OUTREPORT_STD;
    end;
  END;

  PRIVATE MACRO BeginReport()
    Dl_CallInsertStat(PrintMode());
    CreateTotalBook();
    SetActiveSheet("Индивидуальный счет ВУ");
    SetUseApp(m_Params.IsUseApp == "X");
  END;

  PRIVATE MACRO EndReport()
    SaveTotalBook();
  END;

  PRIVATE MACRO ЯвляетсяИнвПаем( FIID:integer ):bool
    
    var cmd = DL_RSDCommand();
    var query =   "select t_FI_Kind FIKind, t_AvoirKind AvoirKind from dfininstr_dbt where t_FIID = ?";
    cmd.AddParam(FIID);
    var result = cmd.Execute(query);
    
    if(result.moveNext())
      if((result.FIKind == 2) and (result.AvoirKind == 16)) return true;
      else return false;
      end;
    else return false;
    end;
    
  END;
  
  PRIVATE MACRO ПолучитьТочностьКоличестваПая( FIID:integer ):integer
  
    var cmd = DL_RSDCommand();
    var query =   "select t_SumPrecision SumPrec from dfininstr_dbt where t_FIID = ?";
    cmd.AddParam(FIID);
    var result = cmd.Execute(query);
    
    if(result.moveNext())
      return result.SumPrec;
    else return null;
    end;
  
  END;
  
  PRIVATE MACRO PrintLine( Part:integer, A0, A1, A2, A3, A4, A5, A6, A7, A8, A9 )

    if( Part == REPDATAPART_EMISSIVE )
       var precision:integer = null;
       if ( ЯвляетсяИнвПаем(m_RepData.FIID) )
         precision = ПолучитьТочностьКоличестваПая(m_RepData.FIID);
       end;
       
       PrintTableLine( "N1_A0", A0, null,
                       "N1_A1", A1, null,
                       "N1_A2", A2, null,
                       "N1_A3", A3, null,
                       "N1_A4", A4, null,
                       "N1_A5", A5, null,
                       "N1_A6", A6, precision,
                       "N1_A7", A7, precision,
                       "N1_A8", A8, precision,
                       "N1_A9", A9, precision
                     );
    elif( Part == REPDATAPART_NOTEMISSIVE)
       PrintTableLine( "N2_A0", A0, null,
                       "N2_A1", A1, null,
                       "N2_A2", A2, null,
                       "N2_A3", A3, null,
                       "N2_A4", A4, null,
                       "N2_A5", A5, null,
                       "N2_A6", A6, null,
                       "N2_A7", A7, null,
                       "N2_A8", A8, null,
                       "N2_A9", A9, null
                     );
    elif( Part == REPDATAPART_CURRENCY )
       PrintTableLine( "N3_A0", A0, null,
                       "N3_A1", A1, null,
                       "N3_A2", A2, null,
                       "N3_A3", A3, null,
                       //"N3_A4", A4, null, // KS 24.03.2020
                       //"N3_A5", A5, null, // KS 24.03.2020
                       "N3_A6", A6, 2,
                       "N3_A7", A7, 2,
                       "N3_A8", A8, 2,
                       "N3_A9", A9, 2
                     );
    elif( Part == REPDATAPART_METAL )
       PrintTableLine( "N4_A0", A0, null,
                       "N4_A1", A1, null,
                       "N4_A2", A2, null,
                       "N4_A3", A3, null,
                       "N4_A4", A4, null,
                       "N4_A5", A5, null,
                       "N4_A6", A6, 2,
                       "N4_A7", A7, 2,
                       "N4_A8", A8, 2,
                       "N4_A9", A9, 2
                     );
    end;

  END;

  PRIVATE MACRO PrintLineItog( Part:integer, A0, A7, A8 )

    if( Part == REPDATAPART_EMISSIVE )
       var precision:integer = null;
       if ( ЯвляетсяИнвПаем(m_RepData.FIID) )
         precision = ПолучитьТочностьКоличестваПая(m_RepData.FIID);
       end;
       
       PrintTableLine( "N1_A0", A0, null,
                       "N1_A7", A7, precision,
                       "N1_A8", A8, precision
                     );
    elif( Part == REPDATAPART_NOTEMISSIVE)
       PrintTableLine( "N2_A0", A0, null,
                       "N2_A7", A7, null,
                       "N2_A8", A8, null
                     );
    elif( Part == REPDATAPART_CURRENCY )
       PrintTableLine( "N3_A0", A0, null,
                       "N3_A7", A7, 2,
                       "N3_A8", A8, 2
                     );
    elif( Part == REPDATAPART_METAL )
       PrintTableLine( "N4_A0", A0, null,
                       "N4_A7", A7, 2,
                       "N4_A8", A8, 2
                     );
    end;
  END;

  PRIVATE MACRO PrintLinePlan( Part:integer, A0, A1, A2, A3, C1, C2, A5, A6, A7 ) 
    if( Part == REPDATAPART_EMISSIVE )
       var precision:integer = null;
       if ( ЯвляетсяИнвПаем(prevFIID) )
         precision = ПолучитьТочностьКоличестваПая(prevFIID);
       end;

       PrintTableLine( "N1_A0_1",   A0, null,
                       "N1_A1_1",   A1, null,
                       "N1_A2_1",   A2, null,
                       "N1_A3_1",   A3, null,
                       "N1_C1",     C1, null,
                       "N1_C2",     C2, null,
                       "N1_A5_5",   A5, precision,
                       "N1_A6_6",   A6, precision,
                       "Plan_Emis", A7, precision
                     );
    elif( Part == REPDATAPART_NOTEMISSIVE)
       PrintTableLine( "N2_A0_1",    A0, null,
                       "N2_A1_1",    A1, null,
                       "N2_A2_1",    A2, null,
                       "N2_A3_1",    A3, null,
                       "N2_C1",      C1, null,
                       "N2_C2",      C2, null,
                       "N2_A5_5",    A5, null,
                       "N2_A6_6",    A6, null,
                       "Plan_NEmis", A7, null
                     );
    elif( Part == REPDATAPART_CURRENCY )
       PrintTableLine( "N3_A0_1", A0, null,
                       "N3_A1_1", A1, null,
                       "N3_A2_1", A2, null,
                       "N3_A3_1", A3, null,
                       "N3_C2",   C2, null,
                       "N3_A5_5", A5, 2,
                       "N3_A6_6", A6, 2,
                       "Plan_DS", A7, 2
                     );
    elif( Part == REPDATAPART_METAL )
       PrintTableLine( "N4_A0_1", A0, null,
                       "N4_A1_1", A1, null,
                       "N4_A2_1", A2, null,
                       "N4_A3_1", A3, null,
                       "N4_C1",   C1, null,
                       "N4_C2",   C2, null,
                       "N4_A5_5", A5, 2,
                       "N4_A6_6", A6, 2,
                       "Plan_DM", A7, 2
                     );
    end;

  END;

  PRIVATE MACRO PrintLinePlanItog( Part:integer, A0, A5, A6 ) 
    if( Part == REPDATAPART_EMISSIVE )
       var precision:integer = null;
       if ( ЯвляетсяИнвПаем(prevFIID) )
         precision = ПолучитьТочностьКоличестваПая(prevFIID);
       end;

       PrintTableLine( "N1_A0_1",   A0, null,
                       "N1_A5_5",   A5, precision,
                       "N1_A6_6",   A6, precision
                     );
    elif( Part == REPDATAPART_NOTEMISSIVE)
       PrintTableLine( "N2_A0_1",    A0, null,
                       "N2_A5_5",    A5, null,
                       "N2_A6_6",    A6, null
                     );
    elif( Part == REPDATAPART_CURRENCY )
       PrintTableLine( "N3_A0_1", A0, null,
                       "N3_A5_5", A5, 2,
                       "N3_A6_6", A6, 2
                     );
    elif( Part == REPDATAPART_METAL )
       PrintTableLine( "N4_A0_1", A0, null,
                       "N4_A5_5", A5, 2,
                       "N4_A6_6", A6, 2
                     );
    end;
  END;

  PRIVATE MACRO EndCopyTable( Part:integer, IsFact:string, NotPrintRest:bool )

     var PrintRest = false;

     if( m_RegisterTable == true)
      
        if( IsFact == SET_CHAR )
          if( Part == REPDATAPART_EMISSIVE )
             Merge("N1_A0", "N1_A5", null);
          elif( Part == REPDATAPART_NOTEMISSIVE )
             Merge("N2_A0", "N2_A5", null);
          elif( Part == REPDATAPART_CURRENCY )
             Merge("N3_A0", "N3_A3", null);
          elif( Part == REPDATAPART_METAL )
             Merge("N4_A0", "N4_A5", null);
          end;

          PrintLineItog(Part, "ИТОГО:", m_ItogIn, m_ItogOut);
        else
          if( Part == REPDATAPART_EMISSIVE )
             Merge("N1_A0_1", "N1_C2", null);
          elif( Part == REPDATAPART_NOTEMISSIVE )
             Merge("N2_A0_1", "N2_C2", null);
          elif( Part == REPDATAPART_CURRENCY )
             Merge("N3_A0_1", "N3_C2", null);
          elif( Part == REPDATAPART_METAL )
             Merge("N4_A0_1", "N4_C2", null);
          end;

          PrintLinePlanItog(Part, "ИТОГО по неисполненным обязательствам:", m_PlanItogIn, m_PlanItogOut);
        end;

        EndTable();
        CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, GetTableRange(), 0, m_CurrSheetName, true);

        m_RegisterTable = false;
        PrintRest = true;
     end;

     if( (PrintRest and ((NotPrintRest == NULL) or (NotPrintRest == false))) or
         (m_PrintAccount and (IsFact == "_"))
       )
       //т.к. счета активные, то остаток на них со знаком "минус", поэтому сумму зачисления вычитаем, а сумму списания прибавляем.

       if( Part == REPDATAPART_EMISSIVE )
          var precision:integer = null;
          if ( ЯвляетсяИнвПаем(prevFIID) )
             precision = ПолучитьТочностьКоличестваПая(prevFIID);
          end;
          
          PrintFormatString("Исходящий остаток #", "N1_F7_1", -(m_PrevOutRest));
          ExternalSetCellPoint("N1_F7_1", precision);
          CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_EndAccount", 0, m_CurrSheetName, true);

          if( m_PrevContrCat != 2 )
             PrintFormatString("Плановый исходящий остаток #", "N1_F7_2", -(m_PrevInRest - m_PlanItogIn + m_PlanItogOut));
             ExternalSetCellPoint("N1_F7_2", precision);
             CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_EndPlanAccount", 0, m_CurrSheetName, true);
          end;

       elif( Part == REPDATAPART_NOTEMISSIVE)
          PrintFormatString("Исходящий остаток #", "N2_F7_1", -(m_PrevOutRest));
          CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N2_EndAccount", 0, m_CurrSheetName, true);

          if( m_PrevContrCat != 2 )
             PrintFormatString("Плановый исходящий остаток #", "N2_F7_2", -(m_PrevInRest - m_PlanItogIn + m_PlanItogOut));
             CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N2_EndPlanAccount", 0, m_CurrSheetName, true);
          end;
       elif( Part == REPDATAPART_CURRENCY )
          PrintFormatString("Исходящий остаток # #", "N3_F7_1", -(m_PrevOutRest),
                                                     "N3_F7_3", m_prevCCY
                           );
          CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N3_EndAccount", 0, m_CurrSheetName, true);

          if( m_PrevContrCat != 2 )
             PrintFormatString("Плановый исходящий остаток # #", "N3_F7_2", -(m_PrevInRest - m_PlanItogIn + m_PlanItogOut),
                                                                 "N3_F7_4", m_prevCCY
                              );
             CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N3_EndPlanAccount", 0, m_CurrSheetName, true);
          end;
       elif( Part == REPDATAPART_METAL )
          PrintFormatString("Исходящий остаток # #", "N4_F7_1", -(m_PrevOutRest),
                                                     "N4_F7_3", m_prevCCY
                           );
          CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N4_EndAccount", 0, m_CurrSheetName, true);

          if( m_PrevContrCat != 2 )
             PrintFormatString("Плановый исходящий остаток # #", "N4_F7_2", -(m_PrevInRest - m_PlanItogIn + m_PlanItogOut),
                                                                 "N4_F7_4", m_prevCCY
                              );
             CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N4_EndPlanAccount", 0, m_CurrSheetName, true);
          end;
       end;

       m_PrevOutRest = $0.0;
       m_PrevInRest  = $0.0;
       m_PlanItogIn  = $0.0;
       m_PlanItogOut = $0.0;
       m_prevCCy     = "";
       m_PrintAccount = false;
     end;
  END;

  PRIVATE MACRO PrintHeader()
  
    var cmd = DL_RSDCommand();

    var sqlQuery = "select dParty_dbt.t_Name Name from dParty_dbt, ddp_Dep_dbt "
                 + "where dParty_dbt.t_PartyID = ddp_Dep_dbt.t_PartyID and "
                 + "ddp_Dep_dbt.t_Code = ?";

    cmd.AddParam(m_DepCode);
   var nameQuery = cmd.Execute(sqlQuery);
   nameQuery.MoveNext();

    var Header = "Филиал: #\n"+
                 "                    ИНДИВИДУАЛЬНЫЙ СЧЕТ ВНУТРЕННЕГО УЧЕТА ПО ДОГОВОРУ БРОКЕРСКОГО ОБСЛУЖИВАНИЯ\n";
    PrintFormatString(Header, "N1_H1_0", nameQuery.Name);
    CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_RepHeader", 0, m_CurrSheetName, true);
  END;

  PRIVATE MACRO PrintRepDate( onDate )
    var str:string = "";

    if( ValType(onDate) == V_UNDEF )
       if( m_Params.BeginDate == m_Params.EndDate )
         str = string(m_Params.BeginDate:f);
       else
         str = " с " + string(m_Params.BeginDate:f) + " по " + string(m_Params.EndDate:f);
       end;
    else
       str = string(onDate);
    end;

    PrintFormatString("             Отчетный период #", "N1_H1_1", str);
    CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_RepDate", 1, m_CurrSheetName, true);
  END;

  PRIVATE MACRO PrintClient() 
    PrintFormatString("Клиент: #", "N1_H1_2", m_RepData.ClientShortName);
    CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Client", 1, m_CurrSheetName, true);
  END;

  PRIVATE MACRO PrintContr( NumConc:string, DateConc:date )
    PrintFormatString("Договор № # от #", "N1_H2_1", IIF(NumConc == NULL, "", NumConc),
                                          "N1_H2_2", IIF(DateConc == NULL, "", DateConc)
                     );
    CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Contr", 1, m_CurrSheetName, true);
  END;

 /* PRIVATE MACRO PrintPart( Part:integer )
    if( Part == REPDATAPART_EMISSIVE )
       PrintFormatString("#", "N1_Emiss", "Эмиссионные ценные бумаги, инвестиционные паи и депозитарные расписки");
       PrintFormatString("Номер счета: #","" "N1_EMISS_CONTRACT", "ЦБ-3_"+m_RepData.SfNumber);
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Emiss_2", 1, m_CurrSheetName, true);
       
       //CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_EMISS_CONTRACT", 1, m_CurrSheetName, true);

    elif( Part == REPDATAPART_NOTEMISSIVE )
       PrintFormatString("#", "N1_NotEmiss", "Неэмиссионные ценные бумаги");
       PrintFormatString("Номер счета: #", "N1_NOTEMISS_CONTRACT", "ЦБ-3_"+m_RepData.SfNumber);
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_NotEmiss_2", 1, m_CurrSheetName, true);
       
    else//if( Part == REPDATAPART_CURRENCY )
       PrintFormatString("#", "N1_Curr", "Денежные средства");
       PrintFormatString("Номер счета: #", "N1_CURR_CONTRACT", "ДС-3_"+m_RepData.SfNumber);
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Curr_2", 1, m_CurrSheetName, true);
       
    end;
  END; *//*KEA 522539*/

PRIVATE MACRO PrintPart( Part:integer )
    if( Part == REPDATAPART_EMISSIVE )
       PrintFormatString("#", "N1_Emiss", "Эмиссионные ценные бумаги, инвестиционные паи и депозитарные расписки");
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Emiss", 1, m_CurrSheetName, true);
    elif( Part == REPDATAPART_NOTEMISSIVE )
       PrintFormatString("#", "N1_NotEmiss", "Неэмиссионные ценные бумаги");
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_NotEmiss", 1, m_CurrSheetName, true);
    elif( Part == REPDATAPART_CURRENCY )
       PrintFormatString("#", "N1_Curr", "Денежные средства");
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Curr", 1, m_CurrSheetName, true);
    elif( Part == REPDATAPART_METAL )
       PrintFormatString("#", "N1_DM", "Драгоценные металлы");
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_DM", 1, m_CurrSheetName, true);
    end;
  END;

  PRIVATE MACRO PrintFIID()

    if( m_RepData.Part == REPDATAPART_EMISSIVE )
       var ISIN_LSIN:string = "", Series:string = "", Issue:string = "", Tranche:string = "";
       ISIN_LSIN = m_RepData.FI_Number;
  
       if( m_RepData.FI_Series != "" )
          Series = "с. " + m_RepData.FI_Series;
       end;
  
       if( m_RepData.Issue != "" )
          Issue = "в. " + m_RepData.Issue;
       end;
  
       if( m_RepData.Tranche != "" )
          Tranche = "т. " + m_RepData.Tranche;
       end;

       PrintFormatString("Ценная бумага: #, вид #, эмитент #\n" + 
                         " ISIN/№ гос.регистрации #, # #, #", "N1_H3_0", m_RepData.FI_Name,
                                                              "N1_H3_1", m_RepData.AvrKindName,
                                                              "N1_H3_2", m_RepData.IssuerShortName,
                                                              "N1_H3_3", ISIN_LSIN,
                                                              "N1_H3_4", Issue,
                                                              "N1_H3_5", Series,
                                                              "N1_H3_6", Tranche
                        );
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_FIID", 1, m_CurrSheetName, true);
    else //if( Part == REPDATAPART_NOTEMISSIVE )

       PrintFormatString("Ценная бумага: # Код ц/б: #\n" + 
                         " Эмитент: # Вид: # Серия: # Номер: #", "N2_H3_0", m_RepData.FI_Name,
                                                                 "N2_H3_1", m_RepData.FI_Code,
                                                                 "N2_H3_2", m_RepData.IssuerShortName,
                                                                 "N2_H3_3", m_RepData.AvrKindName,
                                                                 "N2_H3_4", m_RepData.FI_Series,
                                                                 "N2_H3_5", m_RepData.FI_Number
                        );
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N2_FIID", 1, m_CurrSheetName, true);
    end;
  END;

  PRIVATE MACRO PrintAccount()

    var NeedTable:bool = IIF(m_RepData.IsFact == SET_CHAR, true, false);
    m_ItogIn = $0.0; m_ItogOut= $0.0;

    // если не было фактических проводок и сразу начинаем печатать плановые
    //if( m_RepData.IsFact == UNSET_CHAR ) // KS 19.03.2020 В любом случае в шапке посчитаю остаток заранее, из-за сортировки InRest подхватывается не тот
       m_RepData.InRest = DL_GetRestAccountParam(m_RepData.Chapter, m_RepData.FIID, m_RepData.Account, m_Params.BeginDate-1);
    //end;

    if( m_RepData.Part == REPDATAPART_EMISSIVE )
       var precision:integer = null;
       if ( ЯвляетсяИнвПаем(m_RepData.FIID) )
          precision = ПолучитьТочностьКоличестваПая(m_RepData.FIID);
       end;
       if(m_RepData.NameAccount == "")
         m_RepData.NameAccount = m_RepData.ClientShortName + " (ЦБ Клиента, ВУ)";
       end;  
       PrintFormatString("Место учета #\nЛицевой счет # #\n" +
                         " Входящий остаток #", "N1_H4_1", m_RepData.PlaceShortName,
                                                "N1_H4_2", m_RepData.Account,
                                                "N1_H4_3", m_RepData.NameAccount,
                                                "N1_H4_4", -(m_RepData.InRest)
                        );
       ExternalSetCellPoint("N1_H4_4", precision);
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Account", 1, m_CurrSheetName, true);

       if( NeedTable )
         CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_TableHeader", 0, m_CurrSheetName, true);

         RegisterTable( "N1_TableLine", TableHeader1,
                        "N1_A0", "N1_A1", "N1_A2", "N1_A3", "N1_A4", "N1_A5", "N1_A6", "N1_A7", "N1_A8", "N1_A9"
                      );
         m_RegisterTable = true;
       end;
    elif( m_RepData.Part == REPDATAPART_NOTEMISSIVE )
       if(m_RepData.NameAccount == "")
         m_RepData.NameAccount = m_RepData.ClientShortName + " (НЦБ Клиента, ВУ)";
       end;
       PrintFormatString("Лицевой счет: # #\n" +
                         " Входящий остаток #", "N2_H3_6", m_RepData.Account,
                                                "N2_H3_7", m_RepData.NameAccount,
                                                "N2_H4_3", -(m_RepData.InRest)
                        );
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N2_Account", 1, m_CurrSheetName, true);

       if( NeedTable )
         CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N2_TableHeader", 0, m_CurrSheetName, true);

         RegisterTable( "N2_TableLine", TableHeader2,
                        "N2_A0", "N2_A1", "N2_A2", "N2_A3", "N2_A4", "N2_A5", "N2_A6", "N2_A7", "N2_A9"
                      );
         m_RegisterTable = true;
       end;
    elif( m_RepData.Part == REPDATAPART_CURRENCY )
       if(m_RepData.NameAccount == "")
         m_RepData.NameAccount = m_RepData.ClientShortName + " (ДС Клиента, ВУ)";
       end;
       PrintFormatString("Лицевой счет # #\n" +
                         " Входящий остаток # #", "N3_H3_1",   m_RepData.Account,
                                                  "N3_H3_1_1", m_RepData.NameAccount,
                                                  "N3_H3_2",  -(m_RepData.InRest),
                                                  "N3_H3_3",   m_RepData.CCY
                        );
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N3_Account", 1, m_CurrSheetName, true);

       if( NeedTable )
         CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N3_TableHeader", 0, m_CurrSheetName, true);

         RegisterTable( "N3_TableLine", TableHeader3,
                        "N3_A0", "N3_A1", "N3_A2", "N3_A3", /*"N3_A4", "N3_A5",*/ "N3_A6", "N3_A7", "N3_A8", "N3_A9" // KS 24.03.2020
                      );

         m_RegisterTable = true;
       end;
    elif( m_RepData.Part == REPDATAPART_METAL )
       if(m_RepData.NameAccount == "")
         m_RepData.NameAccount = m_RepData.ClientShortName + " (ДМ клиента, ВУ)";
       end;
       PrintFormatString("Лицевой счет # #\n" +
                         " Входящий остаток # #", "N4_H3_1",   m_RepData.Account,
                                                  "N4_H3_1_1", m_RepData.NameAccount,
                                                  "N4_H3_2",  -(m_RepData.InRest),
                                                  "N4_H3_3",   m_RepData.CCY
                        );
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N4_Account", 1, m_CurrSheetName, true);

       if( NeedTable )
         CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N4_TableHeader", 0, m_CurrSheetName, true);

         RegisterTable( "N4_TableLine", TableHeader3,
                        "N4_A0", "N4_A1", "N4_A2", "N4_A3", "N4_A4", "N4_A5", "N4_A6", "N4_A7", "N4_A8", "N4_A9"
                      );

         m_RegisterTable = true;
       end;
    end;

    m_PrevInRest = m_PrevOutRest = m_RepData.InRest;
    m_PrintAccount = true;
  END;

  PRIVATE MACRO PrintDealComm()

    m_PlanItogIn = $0.0; m_PlanItogOut= $0.0;

    if( m_RepData.Part == REPDATAPART_EMISSIVE )
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_DealCommHead", 0, m_CurrSheetName, true);

       RegisterTable( "N1_DealCommTableLine", DealCommTableHeader1,
                      "N1_A0_1", "N1_A1_1", "N1_A2_1", "N1_A3_1", "N1_C1", "N1_C2", "N1_A5_5", "N1_A6_6", "Plan_Emis"
                    );
    elif( m_RepData.Part == REPDATAPART_NOTEMISSIVE)
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N2_DealCommHead", 0, m_CurrSheetName, true);

       RegisterTable( "N2_DealCommTableLine", DealCommTableHeader2,
                      "N2_A0_1", "N2_A1_1", "N2_A2_1", "N2_A3_1", "N2_C1", "N2_C2", "N2_A5_5", "N2_A6_6", "Plan_NEmis"
                    );
    elif( m_RepData.Part == REPDATAPART_CURRENCY )
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N3_DealCommHead", 0, m_CurrSheetName, true);

       RegisterTable( "N3_DealCommTableLine", DealCommTableHeader3,
                      "N3_A0_1", "N3_A1_1", "N3_A2_1", "N3_A3_1", /*"N3_C1",*/ "N3_C2", "N3_A5_5", "N3_A6_6", "Plan_DS" // KS 24.03.2020
                    );
    elif( m_RepData.Part == REPDATAPART_METAL )
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N4_DealCommHead", 0, m_CurrSheetName, true);

       RegisterTable( "N4_DealCommTableLine", DealCommTableHeader3,
                      "N4_A0_1", "N4_A1_1", "N4_A2_1", "N4_A3_1", "N4_C1", "N4_C2", "N4_A5_5", "N4_A6_6"
                    );
    end;

    m_RegisterTable = true;
  END;
  
  PRIVATE MACRO PrintHeaderWhenDateSeparately( onDate, NumConc, DateConc, SkipName )
    if ( (ValType(skipName) == V_UNDEF) or (SkipName == false) )
      var Header = "                    ИНДИВИДУАЛЬНЫЙ СЧЕТ ВНУТРЕННЕГО УЧЕТА ПО ДОГОВОРУ БРОКЕРСКОГО ОБСЛУЖИВАНИЯ\n";
      CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_RepHeaderName", 3, m_CurrSheetName, true);
    end;
    
    PrintFormatString("             Отчетный период #", "N1_H1_1", string( onDate ));
    CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_RepDate", 1, m_CurrSheetName, true);
    
    PrintFormatString("Клиент: #", "N1_H1_2", m_RepData.ClientShortName);
    CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Client", 1, m_CurrSheetName, true);
    
    PrintFormatString("Договор № # от #", "N1_H2_1", IIF(NumConc == NULL, "", NumConc),
                                          "N1_H2_2", IIF(DateConc == NULL, "", DateConc));
    CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Contr", 1, m_CurrSheetName, true);
  END;

  PRIVATE MACRO ПечататьДанные( onDate )

    var prevDate:date;
    m_PrintDate = false;
    var printSepareteDatesHeader = false;

    var cmd = DL_RSDCommand();
    var GroundKindNumber; //BIQ-5485 
    var sqlQuery =   " select rd.*, fin.t_FI_Code, fin.t_Name as FI_Name, NVL(avrk.t_Name, CHR(1)) as AvrKindName, "
                   + "        case when fin.T_FIID = "+NATCUR+" then '"+string(m_Params.CCA_NatCUR)+"' else fin.T_CCY end t_CCY, "
                   + "        NVL((select acc.t_NameAccount from daccount_dbt acc where acc.t_Chapter = rd.t_Chapter and acc.t_Account = rd.t_Account and acc.t_Code_Currency = rd.t_FIID), CHR(1)) as NameAccount, "
                   + "        NVL(client.t_ShortName, CHR(1)) as ClientShortName, "
                   + "        NVL(issuer.t_ShortName, CHR(1)) as IssuerShortName, "
                   + "        NVL(place.t_ShortName, CHR(1)) as PlaceShortName, "
                   + "        NVL(contr.t_Number, CHR(1)) as SfNumber, "
                   + "        NVL(dsf.t_Number, CHR(1)) as NumConc, "
                   + "        NVL(dsf.t_DateConc, "+GetSQLDate(date(0,0,0))+") as DateConc, "
                   + "         (case when rd.t_OperType=0 then 'Расчетная операция' else  NVL(llv_o.t_Name, CHR(1)) end) as OperTypeName, "
                   + "        NVL(llv_g.t_Name, CHR(1)) as GroundKindName, "
                   + "        rsb_secur.GetMainObjAttr(659, LPAD(rd.t_ContrID, 10, '0'), 1, ?) as ContrCat "
                   //+ "        , nvl(tick.t_dealcodets, rd.t_dealcode) t_dealcodets "//28.01.2020 RAS:494669
                   + "        , nvl (decode (length(trim(tick.t_dealcodets)), 1,  rd.t_dealcode, tick.t_dealcodets), rd.t_dealcode ) t_dealcodets "//BIQ-5485, пустой номер - не всегда НУЛЛ 
                   + "        , tick.t_dealdate dealdate "//MAA:509183 28.04.2020 
                   + "   from ddliarepdata_dbt rd "
                   + "        left join ddl_tick_dbt tick ON tick.t_dealcode = rd.t_DealCode "//28.01.2020 RAS:494669
                   + "        left join dparty_dbt client ON client.t_PartyID = rd.t_ClientID "
                   + "        left join dparty_dbt issuer ON issuer.t_PartyID = rd.t_IssuerID "
                   + "        left join dparty_dbt place ON place.t_PartyID = rd.t_PlaceID "
                   + "        left join dsfcontr_dbt contr ON contr.t_ID = rd.t_ContrID "
                   + "        left join ddlcontrmp_dbt mp ON mp.t_SfContrID = contr.t_ID "
                   + "        left join ddlcontr_dbt dl ON dl.t_DlcontrID = mp.t_DlContrID "
                   + "        left join dsfcontr_dbt dsf ON dsf.t_ID = dl.t_sfcontrID "
                   + "        left join dllvalues_dbt llv_g ON llv_g.t_List = " + string(OBJTYPE_KINDDOC) + " and llv_g.t_Element = rd.t_GroundKind "
                   + "        left join dllvalues_dbt llv_o ON llv_o.t_List = " + OBJTYPE_CALCOPKIND + " and llv_o.t_Element = rd.t_OperType, "
                   + "        dfininstr_dbt fin left outer join davrkinds_dbt avrk ON avrk.t_FI_Kind = fin.t_FI_Kind and avrk.t_AvoirKind = fin.t_AvoirKind "
                   + "  where rd.t_GUID = ? "
                   + "    and rd.t_Department = ? "
                   + "    and fin.t_FIID = rd.t_FIID ";

    cmd.AddParam(m_Params.EndDate);
    cmd.AddParam(m_Params.GUID);
    cmd.AddParam(m_DepCode);

    if( ValType(onDate) != V_UNDEF )
      sqlQuery = sqlQuery + " AND rd.t_Date = ? ";
      cmd.AddParam(onDate);
    end;
    
    var NRecs = cmd.GetCount(sqlQuery);

    if( NRecs > 0 )
       if ( m_Params.DivideByDates )
          sqlQuery = sqlQuery + " order by rd.t_ClientID, rd.t_Date, rd.t_ContrID, rd.t_Part, rd.t_Account, rd.t_FIID, rd.t_IsFact DESC, rd.t_Sort, rd.t_DealCode ";
       else
       sqlQuery = sqlQuery + " order by rd.t_ClientID, rd.t_ContrID, rd.t_Part, rd.t_Account, rd.t_FIID, rd.t_IsFact DESC, rd.t_Date, rd.t_Sort, rd.t_DealCode ";
       end;
       
       m_RepData = cmd.Execute(sqlQuery);

       InitProgress(NRecs, "Отчет: Индивидуальный счет ВУ", "Печать данных");

       var i = 0;
       while( m_RepData.MoveNext() )

      /*    if ( (date(m_RepData.Date) < m_Params.BeginDate) or (date(m_RepData.Date) > m_Params.EndDate) )
             continue;
          end;     *//*GAA: 505590, подробности ниже*/
          
          printSepareteDatesHeader = false;
          
          if( (not m_PrintDep) )
             EndCopyTable(PrevPart, PrevIsFact);
             m_CurrSheetName = string(m_DepCode);
             UseNewSheetInTotalBook();
             PrintHeader();
             m_PrintDep = true;
             m_PrintDate = false;
          end;

          if( not m_PrintDate )
             if ( not m_Params.DivideByDates )
             EndCopyTable(PrevPart, PrevIsFact);
                PrintRepDate();
             end;
             m_PrintDate = true;
             PrevClient = -1;
          end;

          if( PrevClient != m_RepData.ClientID ) 
             EndCopyTable(PrevPart, PrevIsFact);
             if ( m_Params.DivideByDates )
                if ( not printSepareteDatesHeader )
                   if ( i != 0 )
                      PrintHeaderWhenDateSeparately( date(m_RepData.Date), m_RepData.NumConc, m_RepData.DateConc );
                   else
                      PrintHeaderWhenDateSeparately( date(m_RepData.Date), m_RepData.NumConc, m_RepData.DateConc, true );
                   end;
                   printSepareteDatesHeader = true;
                end;
             else
             PrintClient(m_RepData.ClientShortName);
             end;
             PrevContr = -1;
             m_PrevContrCat = -1;
          end;

          if( PrevContr != m_RepData.ContrID )
             EndCopyTable(PrevPart, PrevIsFact);
             if ( m_Params.DivideByDates )
                if ( not printSepareteDatesHeader )
                   if ( i != 0 )
                      PrintHeaderWhenDateSeparately( date(m_RepData.Date), m_RepData.NumConc, m_RepData.DateConc );
                   else
                      PrintHeaderWhenDateSeparately( date(m_RepData.Date), m_RepData.NumConc, m_RepData.DateConc, true );
                   end;
                   printSepareteDatesHeader = true;
                end;
             else
             PrintContr(m_RepData.NumConc, m_RepData.DateConc);
             end;
             PrevPart = 0;
          end;
          
          if ( (ValType(PrevDate) != V_UNDEF) and (PrevDate != date(m_RepData.Date)) and (m_Params.DivideByDates) and (i != 0) and (not printSepareteDatesHeader) )
             EndCopyTable(PrevPart, PrevIsFact);
             PrintHeaderWhenDateSeparately( date(m_RepData.Date), m_RepData.NumConc, m_RepData.DateConc );
             printSepareteDatesHeader = true;
          end;

          if( (PrevPart != m_RepData.Part) or (printSepareteDatesHeader) )
             EndCopyTable(PrevPart, PrevIsFact);
             PrintPart(m_RepData.Part);
             PrevFIID = -1;
          end;

          if( (PrevFIID != m_RepData.FIID) and (m_RepData.Part != REPDATAPART_CURRENCY) and (m_RepData.Part != REPDATAPART_METAL))
             EndCopyTable(PrevPart, PrevIsFact);
             PrintFIID();
             PrevAccount = "";
          end;

          if( PrevAccount != m_RepData.Account )
             EndCopyTable(PrevPart, PrevIsFact);
             PrintAccount();
             PrevIsFact = "U";
          end;

          /*GAA: 505590 перенес в данное место, т.к. в некоторых случаях данное условие приводит к потере информации о ц/б.
           Нпрм.: если имеются сделки Т+ и отчет формируется за дату заключения сделки и по ц/б из сделки имелся остаток на счете ВУ, то в отчете сформированном за дату заключение сделки
                  не отразится информация об остатке по данной ц/б */
          // KS 19.03.2020 Простите, коллеги, но мне надо как-то выводить планируемые списания/зачисления
          /*
          if ( (date(m_RepData.Date) < m_Params.BeginDate) or (date(m_RepData.Date) > m_Params.EndDate) )
             continue;
          end;  
          */
          if (date(m_RepData.Date) < m_Params.BeginDate)
             continue;
          end;  

          if( ((PrevIsFact != m_RepData.IsFact) and (m_RepData.IsFact == UNSET_CHAR)) )
             if ( (PrevIsFact == SET_CHAR) )
               EndCopyTable( PrevPart, PrevIsFact, true);
             end;
             PrintDealComm();
          end;

         
          if( m_RepData.IsFact != "_" )
             if( m_RepData.IsFact == SET_CHAR ) 
//              if ( m_RepData.StateDate == date(0,0,0) )/*CHVA*/
              if ( m_RepData.State == 1 ) /* MAA: 509611 07.05.2020 */
               m_ItogIn  = m_ItogIn  + m_RepData.InSum;
               m_ItogOut = m_ItogOut + m_RepData.OutSum;
               if( PrevAccount != m_RepData.Account )// KS 19.03.2020 Из-за сортировки остатки подхватываются не те. Здесь вычислю входящий остаток:
                 m_PrevOutRest = DL_GetRestAccountParam(m_RepData.Chapter, m_RepData.FIID, m_RepData.Account, date(m_RepData.Date)-1);
               end;

               GroundKindNumber = m_RepData.GroundKindName;
               If (strlen(m_RepData.GroundKindName) == 0) //BIQ-5485 проверим поручение (GRD.T_KIND = 251 ) для операции зачисления (t.t_sourcedockind = 127 )
                  var cmdgrd = DL_RSDCommand();
                  var sqlQr =   " SELECT grd.t_xld, decode (grd.t_kind, 251, 'Поручение клиента на операцию', CHR(1)) Grnd FROM dspgrdoc_dbt t "
                   +"             inner join ddl_tick_dbt tick on tick.t_dealcode = ? and t.t_sourcedocid = tick.t_dealid and t.t_sourcedockind = 127 "
                   +"             inner join  dspground_dbt grd on GRD.T_SPGROUNDID = T.T_SPGROUNDID and GRD.T_KIND = 251 " ;
                  
                   cmdgrd.AddParam(m_RepData.dealcode);
                                           
                    var  m_RepDt = cmdgrd.Execute(sqlQr);
                  
                      while( m_RepDt.MoveNext() )
                          m_RepData.GroundKindName = m_RepDt.Grnd;
                          GroundKindNumber = m_RepDt.t_xld;
                      end;
               end;

               PrintLine(m_RepData.Part,
                         date(m_RepData.Date), m_RepData.OperTypeName, m_RepData.DealKindName, /*28.01.2020 RAS:494669 m_RepData.DealCode*/
                        // m_RepData.dealcodets, m_RepData.GroundKindName, m_RepData.GroundKindName + " от " + date(m_RepData.dealdate), //MAA:509183 28.04.2020 
                         m_RepData.dealcodets, m_RepData.GroundKindName, GroundKindNumber + " от " + date(m_RepData.dealdate), //BIQ-5485 
                         // KS 19.03.2020
                         // -(m_RepData.InRest), m_RepData.InSum, m_RepData.OutSum, -(m_RepData.OutRest));
                         -(m_PrevOutRest), m_RepData.InSum, m_RepData.OutSum, -(m_PrevOutRest - m_RepData.InSum + m_RepData.OutSum));
           
               //m_PrevOutRest = m_RepData.OutRest;
               m_PrevOutRest = m_PrevOutRest - m_RepData.InSum + m_RepData.OutSum;
               m_PrevInRest = m_PrevOutRest;
              end;
             else
               if( m_RepData.State != DEALCOMM_STATE_REJECT )
                 m_PlanItogIn  = m_PlanItogIn  + m_RepData.InSum;
                 m_PlanItogOut = m_PlanItogOut + m_RepData.OutSum;
               end;

               if( PrevAccount != m_RepData.Account ) // KS 19.03.2020 Из-за сортировки остатки подхватываются не те. Здесь вычислю входящий остаток:
                 m_PrevInRest = DL_GetRestAccountParam(m_RepData.Chapter, m_RepData.FIID, m_RepData.Account, date(m_RepData.Date)-1);
               end;
           
               PrintLinePlan(m_RepData.Part,
                             date(m_RepData.Date), m_RepData.OperTypeName + /*28.01.2020 RAS:494669*/ " по сделке: " + m_RepData.DealKindName, m_RepData.DealKindName, /*28.01.2020 RAS:494669 m_RepData.DealCode*/m_RepData.dealcodets,
                             DealCommStateArr[m_RepData.State], date(m_RepData.StateDate), 
                             m_RepData.InSum, m_RepData.OutSum, -(m_PrevInRest - m_RepData.InSum + m_RepData.OutSum));
               var precision:integer = null;
               if ( ЯвляетсяИнвПаем(m_RepData.FIID) )
                  precision = ПолучитьТочностьКоличестваПая(m_RepData.FIID);
               end;
               ExternalSetCellPoint("Plan_Emis", precision);
               m_PrevInRest = m_PrevInRest - m_RepData.InSum + m_RepData.OutSum; // KS 19.03.2020 Пересчитываем остатки
             end;
          end;

          PrevClient  = m_RepData.ClientID;
          PrevContr   = m_RepData.ContrID;
          PrevDate    = date(m_RepData.Date);
          PrevPart    = m_RepData.Part;
          PrevFIID    = m_RepData.FIID;
          PrevAccount = m_RepData.Account;
          PrevIsFact  = m_RepData.IsFact;
          m_PrevCCY   = m_RepData.CCY;
          m_PrevContrCat = m_RepData.ContrCat;

          UseProgress(i = i + 1);
       end;

       RemProgress();

       EndCopyTable(PrevPart, PrevIsFact);

       m_NoData = false;
    end;
  END;

  PRIVATE MACRO ПоФилиалу()
    m_PrintDep = false;
    ПечататьДанные();

    if( m_PrintDep )
       AddStandardFooter("N1_");
       CopyAllSheetInTotalBook(TEMPLATE_SHEET_NAME, false, "N1_Footer", 1, m_CurrSheetName, true);
    end;
  END;

  MACRO Create()

    var query, cmd, cmdData, NRec = 0, Num = 0;

    m_NoData = true;

    cmd = DL_RSDCommand();

    query =   " select distinct dp.t_Code, dp.t_PartyID "
            + "   from ddliarepdata_dbt ia, ddp_dep_dbt dp "
            + "  where ia.t_GUID = ? "
            + "    and dp.t_Code = ia.t_Department ";

    cmd.AddParam(m_Params.GUID);

    if(m_Params.DepartmentID > 0)
      query = query + " and dp.t_Code = ? ";
      cmd.AddParam(m_Params.DepartmentID);
    end;
     
    NRec = cmd.GetCount(query);
    if( NRec > 0 )
       query = query + " order by dp.t_Code ";

       cmdData = cmd.Execute(query);

       InitProgress(NRec, "Печать данных по филиалам", "Печать данных по филиалам");
       while( cmdData.Movenext() )
          m_DepID   = cmdData.PartyID;
          m_DepCode = cmdData.Code;
          ПоФилиалу();
          UseProgress(Num = Num + 1);
       end;
       RemProgress();
    end;

    if( m_NoData == true )
       PrintFormatString("#", "N1_ReportRunFalse", "Нет данных для формирования отчета.");
       CopyAllSheetInTotalBook(null, false, "N1_ReportRunFalse", 0, null, true);
    end;

  END;

  initDL_CReportTemplate(NULL, "Report_InAccIA.xlsx", true, null, null, POI_MODE, true);
END;

////////////////////////////////////////////////////////////////////////////////////////////
//Запуск отчета
////////////////////////////////////////////////////////////////////////////////////////////

PRIVATE MACRO GetIARepObjectQuery(Params)
  var query = "";

  query =   " select DISTINCT cl.t_PartyID "
          + "   from dclient_dbt cl, dparty_dbt pt" 
          + "  where cl.t_PartyID <> " + {OurBank}
          + "    and pt.t_PartyID = cl.t_PartyID "
          + "    and cl.t_StartDate <= " + GetSQLDate(Params.EndDate)
          + "    and (cl.t_FinishDate = " + GetSQLDate(date(0,0,0)) + " or cl.t_FinishDate < " + GetSQLDate(Params.BeginDate) + ") "
          + "    and cl.t_ServiceKind IN (";

  var Delim = false;
  if( Params.IsUseBO == SET_CHAR )
     query = query + IIF(Delim, ",", "") + string(PTSK_STOCKDL); 
     Delim = true;
  end;

  if( Params.IsUseDV == SET_CHAR )
     query = query + IIF(Delim, ",", "") + string(PTSK_DV);
     Delim = true;
  end;

  if( Params.IsUseDV_Cur == SET_CHAR )
     query = query + IIF(Delim, ",", "") + string(PTSK_CM);
     Delim = true;
  end;

  if( Params.IsUseVA == SET_CHAR )
     query = query + IIF(Delim, ",", "") + string(PTSK_VEKSACC);
     Delim = true;
  end;

  query = query + " ) ";

  if( Params.DepartmentID > 0)
    query = query + " AND cl.t_Department = " + Params.DepartmentID;
  end;

  if( Params.ClientID > 0 )
     query = query + " AND cl.t_PartyID = " + Params.ClientID;
  end;
 
  if( (Params.IsForm > 0) and (Params.FormSub != 0) )
     if( Params.IsForm == 1 )
        query = query + " and pt.t_LegalForm = " + Params.FormSub;
     end;
     if( Params.IsForm == 2 )
        query = query + " and pt.t_LegalForm != " + Params.FormSub;
     end;
  end;

  if( (Params.IsVid > 0) and (Params.VidSub != 0) )
     if( Params.IsVid == 1 )
        query = query + " and EXISTS (select 1 from dpartyown_dbt Pto where Pto.t_PartyID = cl.t_PartyID and Pto.T_PARTYKIND = "+Params.VidSub+") ";
     end;
     if( Params.IsVid == 2 )
        query = query + " and NOT EXISTS (select 1 from dpartyown_dbt Pto where Pto.t_PartyID = cl.t_PartyID and Pto.T_PARTYKIND = "+Params.VidSub+") ";
     end;
  end;

  if( Params.NoResident )
     query = query + " and pt.t_NotResident = 'X' ";
  end;

  query =   " select 0 as t_ObjectType, q.t_PartyID as t_ObjectID, ROWNUM as t_GroupNumber, q.t_PartyID as t_ClientID "
          + "   from ("+query+") q ";

  return query;
END;

MACRO ОтобратьОбъектыДляИндСчетВУ(_taskID, _execID, _conveyerID, _packetSize, _Params)
  var cnt = 0;
  var query, DataSet;

  query = " INSERT INTO DCNVDOC_DBT(T_TASKID,T_EXECID,T_CONVTYPEID,T_PACKID,T_OBJECTTYPE,T_OBJECTID) "
        + " SELECT "+_taskID+","+_execID+","+_conveyerID+",q.t_GroupNumber, q.t_ObjectType, q.t_ObjectID "
        + "   FROM (" + GetIARepObjectQuery(_Params) + ") q ";
  query = query + " ORDER BY q.t_ObjectID ";

  SQL_Execute(query, "Отбор объектов", false );
  
  if(_packetSize == 0)
    cnt = 1;
  else
    query =   " select NVL(max(t_PackID), 0) as cnt "
            + "   from dcnvdoc_dbt "
            + "  where t_ExecID = " + _execID;
    
    DataSet = TRsbDataSet(query);
    if(DataSet.moveNext())
      if(DataSet.cnt < _packetSize)
        cnt = 1;
      else
        cnt = int(round(int(DataSet.cnt)/_packetSize, 0));
      end;
    end;
  end;

  return cnt;
END;

MACRO ExecuteCreateDataIA(_taskID, _execID, _conveyerID, _operationID, _packetID, _Params)
  var query, cmd, DataSet;
  var cnt = 0;
  var err = 0;

  if((_conveyerID) and (_packetID))
    
    query =  "select t_ObjectID as t_ClientID from dcnvdoc_dbt where t_ExecID = ? and t_ConvTypeID = ? and t_PackID = ?";
    
    cmd = DL_RSDCommand(query);
    
    cmd.AddParam(_execID);
    cmd.AddParam(_conveyerID);
    cmd.AddParam(_packetID);
    
    DataSet = cmd.Execute();
    if(DataSet.moveNext())

      _Params.ClientID = DataSet.ClientID;

      DL_InAccIA_CreateData(_Params).Create();
    end;

  else
    query = "select q.t_ClientID from ("+GetIARepObjectQuery(_Params)+") q ";
    cmd = DL_RSDCommand(query);
    cnt = cmd.GetCount();

    if(cnt > 0)
      InitProgress( cnt, "Идет подготовка данных...", "Подготовка данных для отчета" );

      DataSet = cmd.Execute();
      var i = 0;
      while(DataSet.moveNext())

        _Params.ClientID = DataSet.ClientID;

        DL_InAccIA_CreateData(_Params).Create();

        UseProgress(i = i + 1);
      end;

      RemProgress();
    end;
  end; 
  
  if((_conveyerID) and (_packetID))
    /*не зависимо от того, делали что-то или нет - ставим исходящий статус обрабатываемой пачке*/
    var exec = RSDCommand(  " UPDATE dcnvpack_dbt "
                          + " SET t_State = t_State + 1 "
                          + " WHERE t_ExecID = ? "
                          + "   AND t_ConvTypeID = ? "
                          + "   AND t_PackID = ? ");

    exec.addParam( "", RSDBP_IN, _execID );
    exec.addParam( "", RSDBP_IN, _conveyerID );
    exec.addParam( "", RSDBP_IN, _packetID );
    exec.execute();
  end; 

  return err;
END;

PRIVATE MACRO CreateData(params)
  var OperID = 16; //Операция для конвейера - Пакетная подготовка данных для отчета "Индивидуальный счет ВУ"
  var ConvID = 20; //Вид конвейера Данные для отчета "Индивидуальный счет ВУ"
  var UseConveyer = SecurUseConveyer(ConvID, OperID);
  var err = 0;

  if(UseConveyer)
    var cnv = RsbConveyerExec(ConvID);

    cnv.AddParamsForConveyer(ConvID, params, 0);
    cnv.AddParamsForOperation(ConvID, OperID, params, "", 0);
    cnv.showPanelMonitoring(1);
    cnv.Run();
  else
    err = ExecuteCreateDataIA(0, 0, 0, 0, 0, params);
  end;

  return err;
END;

MACRO DL_CreateRepIA( params )

  params.GUID = DL_GetGUID();

  CreateData(params);

  var report = DL_InAccIA_Report(params);
  report.Run();

  SQL_Execute("DELETE FROM DDLIAREPDATA_DBT WHERE T_GUID = '"+params.GUID+"'", "", false );
END;
