/*
$Name:             dlregoper.mac
$Module:           Ценные бумаги
$Description:      Отчет "Субрегистр иных операций"
*/

/*******************************************************************************
 DESCRIPTION  :   Отчет " Субрегистр иных операций"
 PROGRAMMED BY:   Свириденка A.И.
 CREATION DATE:   17.04.07
*******************************************************************************/

IMPORT FIInter,"DLReport_h.mac", "dlmisc.mac";
IMPORT "dlregoper_form.mac";


PRIVATE VAR  m_Form = DL_AccountsReg_Panel();

private const DEALSTATUS_ALL    = -1, /* Все сделки */
              DEALSTATUS_CLOSED = 20,  /* Закрытые */
              DEALSTATUS_OPENED = 10;  /* Открытые */

  PRIVATE MACRO UpdateFormFields():INTEGER
    DlRegOperData.IsUseBO             = m_Form.GetFieldValue( PNFLD_REGOPER_MODULE_BO );
    DlRegOperData.IsUseVA             = m_Form.GetFieldValue( PNFLD_REGOPER_MODULE_VA );
    DlRegOperData.BeginDate           = m_Form.GetFieldValue( PNFLD_REGOPER_BEGINDATE );
    DlRegOperData.EndDate             = m_Form.GetFieldValue( PNFLD_REGOPER_FINISHDATE );
    
    DlRegOperData.SplitByDates        = m_Form.GetFieldValue( PNFLD_REGOPER_SPLIT_BY_DATES );
    
    DlRegOperData.SecurKind           = m_Form.GetFieldValue( PNFLD_REGOPER_SECUR_KIND );
    DlRegOperData.Issuer              = m_Form.GetFieldValue( PNFLD_REGOPER_ISSUER );
    DlRegOperData.SecurCode           = m_Form.GetFieldValue( PNFLD_REGOPER_SECUR_CODE );
    DlRegOperData.OperType            = m_Form.GetFieldValue( PNFLD_REGOPER_OPER_TYPE );
    DlRegOperData.ClientID            = m_Form.GetFieldValue( PNFLD_REGOPER_CLIENT );

    DlRegOperData.IsForm              = m_Form.GetFieldValue( PNFLD_REGOPER_ISFORM );
    DlRegOperData.FormSub             = m_Form.GetFieldValue( PNFLD_REGOPER_FORMSUB );
    DlRegOperData.IsVid               = m_Form.GetFieldValue( PNFLD_REGOPER_ISVID );
    DlRegOperData.VidSub              = m_Form.GetFieldValue( PNFLD_REGOPER_VIDSUB );
    DlRegOperData.Noresident          = m_Form.GetFieldValue( PNFLD_REGOPER_NORESIDENT );

    DlRegOperData.isOperClosed        = m_Form.GetFieldValue( PNFLD_REGOPER_DEALTYPE_CLOSED );
    DlRegOperData.isOperOpened        = m_Form.GetFieldValue( PNFLD_REGOPER_DEALTYPE_OPENED );
    DlRegOperData.isOperAll           = m_Form.GetFieldValue( PNFLD_REGOPER_DEALTYPE_ALL );
    DlRegOperData.OperKind            = m_Form.GetFieldValue( PNFLD_REGOPER_OPER_KIND );
    DlRegOperData.DepoID              = m_Form.GetFieldValue( PNFLD_REGOPER_DEPO );
    DlRegOperData.isOnORBC            = m_Form.GetFieldValue( PNFLD_REGOPER_ON_ORCB );
    DlRegOperData.Exchange            = m_Form.GetFieldValue( PNFLD_REGOPER_EXCGANGE );
    DlRegOperData.isNotOnORBC         = m_Form.GetFieldValue( PNFLD_REGOPER_NOT_ON_ORCB );
    DlRegOperData.isThroughBroker     = m_Form.GetFieldValue( PNFLD_REGOPER_THROUGH_BROKER );
    DlRegOperData.BrokerID            = m_Form.GetFieldValue( PNFLD_REGOPER_BROKER );
    
    DlRegOperData.IsUseOpostrofs      = m_Form.GetFieldValue( PNFLD_REGOPER_WITH_APOSTROFS );
    DlRegOperData.IsExportToExel      = m_Form.GetFieldValue( PNFLD_REGOPER_TO_EXEL );
    DlRegOperData.DepartmentID        = m_Form.GetFieldValue( PNFLD_REGOPER_DEPARTMENT );
    
    if (DlRegOperData.isOperClosed == "X")
      DlRegOperData.OperStatus = DEALSTATUS_CLOSED;
    elif(DlRegOperData.isOperOpened == "X")
      DlRegOperData.OperStatus = DEALSTATUS_OPENED;
    else
      DlRegOperData.OperStatus = DEALSTATUS_ALL;
    end;
    
  END;


macro MakeReports()

  var stat = 0;
  
  stat = m_Form.Run();
  
  // Проверяем можем ли мы делать отчет по предоставленным данным
  if (not stat)
    Exit(1);
  end;
       
  UpdateFormFields();

  Dl_CallInsertStat( IIF( DlRegOperData.IsExportToExel, DL_OUTREPORT_EXCEL, DL_OUTREPORT_STD ) );
  if (DlRegOperData.IsUseVA == "X" )
    ExecMacroFile("varegoper.mac", "MakeReport", DlRegOperData );  
  end;  

  if (DlRegOperData.IsUseBO == "X" )
    ExecMacroFile("scsregop.mac", "SubRegistrReport", 
      DlRegOperData.DepartmentID,
      DlRegOperData.SecurKind,
      DlRegOperData.Issuer,
      DlRegOperData.SecurCode,
      DlRegOperData.OperType,
      DlRegOperData.ClientID,

      DlRegOperData.IsForm,     
      DlRegOperData.FormSub,    
      DlRegOperData.IsVid,      
      DlRegOperData.VidSub,     
      DlRegOperData.Noresident, 

      DlRegOperData.DepoID,
      DlRegOperData.OperKind,
      DlRegOperData.isOnORBC,
      DlRegOperData.Exchange,
      DlRegOperData.isNotOnORBC,
      DlRegOperData.isThroughBroker,
      DlRegOperData.BrokerID,
      DlRegOperData.BeginDate,
      DlRegOperData.EndDate,
      DlRegOperData.SplitByDates,
      DlRegOperData.OperStatus,
      DlRegOperData.IsUseOpostrofs,
      DlRegOperData.IsExportToExel
      );  
  end;  

  MakeReports();

end;

MakeReports();
exit(1);
