/*
$Name:             IISContrMonitor_Reports.mac
$Module:           Ценные бумаги
$Description:      Отчеты по договорам ИИС для обеспечения мониторинга своевременного предоставления клиентами документов о расторжении договора ИИС, открытого у другого ПУ.
                   Формирование отчетов
*/

import "IISContrMonitor_Form.mac", "dlquery.mac", "dldlngfun.mac";

private const CATEGORY_PRESENCE_OF_IIS = 121,        //Категория "Сведения о наличии или отсутствии ИИС у другого ПУ"
              CATEGORY_DOCUMENTS_PROVIDED_IIS = 122; //Категория "Предоставлены подтвержд. документы о расторжении ИИС у другого ПУ"

private const NOTEKIND_IIS_CLOSING_DATE = 175; //Примечание "Дата расторжения договора ИИС в случ. непредоставл. докум."

private const DLCONTRMSG_KIND_NEED_PROVIDE_IIS = 507; //Вид сообщения "Уведомление клиенту о необходимости предоставления документов по ИИС"

PRIVATE CLASS (DL_CReportTemplate) SP_IISContrMonitor_Required_Report(Parm:DL_CPanel)
  private var m_Parm = Parm;
  private var m_IsDataExist = false;

  private macro PrintMode():integer
    return DL_OUTREPORT_EXCEL;
  end;

  private macro PrintReportHead(ReportDate:date)
    PrintFormatString("", "N1_D1", "на дату " + DateToStr(ReportDate));

    RegisterTable( "N1_MainTable", "", 
                   "N1_A1", 
                   "N1_A2", 
                   "N1_A3", 
                   "N1_A4", 
                   "N1_A5", 
                   "N1_A6", 
                   "N1_A7", 
                   "N1_A8", 
                   "N1_A9", 
                   "N1_A10"
                 );
  end;

  private macro PrintLine(dataSet) 
    PrintTableLine( "N1_A1",  dataSet.CntrNumber,     null,
                    "N1_A2",  date(dataSet.CntrDate), null,
                    "N1_A3",  dataSet.ClientName,     null,
                    "N1_A4",  IIF(valtype(dataSet.LoadDate) != V_UNDEF, date(dataSet.LoadDate), ""), null, 
                    "N1_A5",  dataSet.CntrEmail,      null,
                    "N1_A6",  dataSet.MsgCount,       null, 
                    "N1_A7",  IIF(valtype(dataSet.LastMsgDate) != V_UNDEF, date(dataSet.LastMsgDate), ""), null, 
                    "N1_A8",  IIF(valtype(dataSet.LastMsgTime) != V_UNDEF, time(dataSet.LastMsgTime), ""), null, 
                    "N1_A9",  dataSet.DaysPassed,     null,
                    "N1_A10", IIF(valtype(dataSet.DaysLeft) != V_UNDEF, dataSet.DaysLeft, ""), null 
                  );
  end;      

  private macro ExecuteReport()
    var query, cmd, dataSet;
    var cnt = 0, i = 0;

    query = "SELECT sfcontr.t_Number as t_CntrNumber, sfcontr.t_DateBegin as t_CntrDate, partyClnt.t_Name as t_ClientName, "
          + "       dlcontr.t_Email as t_CntrEmail, TO_NUMBER(? - sfcontr.t_DateBegin) as t_DaysPassed, "
          + "       (SELECT MIN(note.t_Date) "
          + "          FROM dnotetext_dbt note "
          + "         WHERE note.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "           AND note.t_DocumentID = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "           AND note.t_Date <> " + GetSQLDate(date(0,0,0))
          + "           AND note.t_Oper = 9997 " 
          + "       ) as t_LoadDate, " //Минимальная дата примечаний от опера 9997
          + "       (SELECT COUNT(1) " 
          + "          FROM ddlcontrmsg_dbt msg "
          + "         WHERE msg.t_DlContrID = dlcontr.t_DlContrID "
          + "           AND msg.t_Kind = " + string(DLCONTRMSG_KIND_NEED_PROVIDE_IIS)
          + "       ) as t_MsgCount, " //Пока считаем все сообщения: и успешно отправленные, и зависшие в процессе
          + "       (SELECT MAX(msg.t_SendDate) "
          + "          FROM ddlcontrmsg_dbt msg "
          + "         WHERE msg.t_DlContrID = dlcontr.t_DlContrID "
          + "           AND msg.t_Kind = " + string(DLCONTRMSG_KIND_NEED_PROVIDE_IIS)
          + "           AND msg.t_SendDate <= ? "
          + "       ) as t_LastMsgDate, "
          + "       (SELECT MAX(msg.t_SendTime) " //В теории за день должно быть только одно сообщение, но мало ли 
          + "          FROM ddlcontrmsg_dbt msg "                                                                  
          + "         WHERE msg.t_DlContrID = dlcontr.t_DlContrID "                                                
          + "           AND msg.t_Kind = " + string(DLCONTRMSG_KIND_NEED_PROVIDE_IIS)                              
          + "           AND msg.t_SendDate = (SELECT MAX(msg1.t_SendDate) "                                        
          + "                                   FROM ddlcontrmsg_dbt msg1 "                                        
          + "                                  WHERE msg1.t_DlContrID = dlcontr.t_DlContrID "                      
          + "                                    AND msg1.t_Kind = " + string(DLCONTRMSG_KIND_NEED_PROVIDE_IIS)    
          + "                                    AND msg1.t_SendDate <= ?) "                                       
          + "       ) as t_LastMsgTime, "                                                                                            
          + "       TO_NUMBER((SELECT RSB_Struct.GetDate(note.t_Text) "
          + "                    FROM dnotetext_dbt note "
          + "                   WHERE note.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                     AND note.t_NoteKind = " + string(NOTEKIND_IIS_CLOSING_DATE)
          + "                     AND note.t_DocumentID = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                 ) - ?) as t_DaysLeft "
          + "  FROM ddlcontr_dbt dlcontr, dsfcontr_dbt sfcontr, dparty_dbt partyClnt "
          + " WHERE dlcontr.t_IIS = 'X' "
          + "   AND EXISTS (SELECT 1 "
          + "                 FROM dobjatcor_dbt atc "
          + "                WHERE atc.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                  AND atc.t_GroupID = " + string(CATEGORY_PRESENCE_OF_IIS)
          + "                  AND atc.t_AttrID = 1 " //Да 
          + "                  AND atc.t_Object = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                  AND ? BETWEEN atc.t_ValidFromDate AND atc.t_ValidToDate) "
          + "   AND NOT EXISTS (SELECT 1 "
          + "                     FROM dobjatcor_dbt atc "
          + "                    WHERE atc.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                      AND atc.t_GroupID = " + string(CATEGORY_DOCUMENTS_PROVIDED_IIS)
          + "                      AND atc.t_AttrID = 1 " //Да 
          + "                      AND atc.t_Object = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                      AND ? BETWEEN atc.t_ValidFromDate AND atc.t_ValidToDate) "
          + "   AND sfcontr.t_ID = dlcontr.t_SfContrID "
          + "   AND sfcontr.t_DateBegin <= ? "
          + "   AND (sfcontr.t_DateClose = " + GetSQLDate(date(0,0,0)) + " OR sfcontr.t_DateClose > ?) "
          + "   AND partyClnt.t_PartyID = sfcontr.t_PartyID "
          + " ORDER BY sfcontr.t_DateBegin, sfcontr.t_Number ";

    cmd = DL_RSDCommand(query);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    
    cnt = cmd.GetCount();

    if(cnt > 0)
      InitProgress(cnt, "Отчет \"Договоры ИИС, по которым требуется предоставление подтверждающих документов о расторжении договора ИИС, заключенного с другим ПУ\"", "Формирование отчета" );
      
      dataSet = cmd.Execute();
      PrintReportHead(m_Parm.ReportDate);
      m_IsDataExist = true;

      while(dataSet.MoveNext())
        PrintLine(dataSet);
        i = i + 1;
        UseProgress(i);
      end;

      EndTable();
      RemProgress;
    else
      msgbox("Нет данных для выпуска отчета");
      m_IsDataExist = false;
    end;
    
    OnError(e)
      msgbox(cmd.GetErrorString(e));
  end;

  private macro Create()
    ExecuteReport();
  end;

  initDL_CReportTemplate(null, "Report_IISContrMonitor_Required.xlsx");  
END;

PRIVATE CLASS (DL_CReportTemplate) SP_IISContrMonitor_NotProvided_Report(Parm:DL_CPanel, IsIntegration:bool)
  private var m_Parm = Parm, m_IsIntegration = IsIntegration;
  private var m_IsDataExist = false;

  private macro PrintMode():integer
    return DL_OUTREPORT_EXCEL;
  end;

  private macro BeginReport()
    SetIsShowAppl(not m_IsIntegration);
  end;

  private macro PrintReportHead(ReportDate:date)
    PrintFormatString("", "N1_D2", "на дату " + DateToStr(ReportDate));

    RegisterTable( "N1_MainTable", "", 
                   "N1_B1", 
                   "N1_B2", 
                   "N1_B3", 
                   "N1_B4", 
                   "N1_B5", 
                   "N1_B6", 
                   "N1_B7", 
                   "N1_B8", 
                   "N1_B9", 
                   "N1_B10"
                 );
  end;

  private macro PrintLine(dataSet) 
    PrintTableLine( "N1_B1",  dataSet.CntrNumber,     null,
                    "N1_B2",  date(dataSet.CntrDate), null,
                    "N1_B3",  dataSet.ClientName,     null,
                    "N1_B4",  IIF(valtype(dataSet.LoadDate) != V_UNDEF, date(dataSet.LoadDate), ""), null, 
                    "N1_B5",  dataSet.CntrEmail,      null,
                    "N1_B6",  dataSet.MsgCount,       null, 
                    "N1_B7",  IIF(valtype(dataSet.LastMsgDate) != V_UNDEF, date(dataSet.LastMsgDate), ""), null, 
                    "N1_B8",  IIF(valtype(dataSet.LastMsgTime) != V_UNDEF, time(dataSet.LastMsgTime), ""), null, 
                    "N1_B9",  dataSet.DaysPassed,     null,
                    "N1_B10", IIF(valtype(dataSet.DaysLeft) != V_UNDEF, dataSet.DaysLeft, ""), null 
                  );
  end;      

  private macro ExecuteReport()
    var query, cmd, dataSet;
    var cnt = 0, i = 0;

    query = "SELECT sfcontr.t_Number as t_CntrNumber, sfcontr.t_DateBegin as t_CntrDate, partyClnt.t_Name as t_ClientName, "
          + "       dlcontr.t_Email as t_CntrEmail, TO_NUMBER(? - sfcontr.t_DateBegin) as t_DaysPassed, "
          + "       (SELECT MIN(note.t_Date) "
          + "          FROM dnotetext_dbt note "
          + "         WHERE note.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "           AND note.t_DocumentID = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "           AND note.t_Date <> " + GetSQLDate(date(0,0,0))
          + "           AND note.t_Oper = 9997 " 
          + "       ) as t_LoadDate, " //Минимальная дата примечаний от опера 9997
          + "       (SELECT COUNT(1) " 
          + "          FROM ddlcontrmsg_dbt msg "
          + "         WHERE msg.t_DlcontrID = dlcontr.t_DlContrID "
          + "           AND msg.t_Kind = " + string(DLCONTRMSG_KIND_NEED_PROVIDE_IIS)
          + "       ) as t_MsgCount, " //Пока считаем все сообщения: и успешно отправленные, и зависшие в процессе
          + "       (SELECT MAX(msg.t_SendDate) "
          + "          FROM ddlcontrmsg_dbt msg "
          + "         WHERE msg.t_DlContrID = dlcontr.t_DlContrID "
          + "           AND msg.t_Kind = " + string(DLCONTRMSG_KIND_NEED_PROVIDE_IIS)
          + "           AND msg.t_SendDate <= ? "
          + "       ) as t_LastMsgDate, "
          + "       (SELECT MAX(msg.t_SendTime) " //В теории за день должно быть только одно сообщение, но мало ли 
          + "          FROM ddlcontrmsg_dbt msg "                                                                  
          + "         WHERE msg.t_DlContrID = dlcontr.t_DlContrID "                                                
          + "           AND msg.t_Kind = " + string(DLCONTRMSG_KIND_NEED_PROVIDE_IIS)                              
          + "           AND msg.t_SendDate = (SELECT MAX(msg1.t_SendDate) "                                        
          + "                                   FROM ddlcontrmsg_dbt msg1 "                                        
          + "                                  WHERE msg1.t_DlContrID = dlcontr.t_DlContrID "                      
          + "                                    AND msg1.t_Kind = " + string(DLCONTRMSG_KIND_NEED_PROVIDE_IIS)    
          + "                                    AND msg1.t_SendDate <= ?) "                                       
          + "       ) as t_LastMsgTime, "                                                                                            
          + "       TO_NUMBER((SELECT RSB_Struct.GetDate(note.t_Text) "
          + "                    FROM dnotetext_dbt note "
          + "                   WHERE note.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                     AND note.t_NoteKind = " + string(NOTEKIND_IIS_CLOSING_DATE)
          + "                     AND note.t_DocumentID = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                 ) - ?) as t_DaysLeft "
          + "  FROM ddlcontr_dbt dlcontr, dsfcontr_dbt sfcontr, dparty_dbt partyClnt "
          + " WHERE dlcontr.t_IIS = 'X' "
          + "   AND EXISTS (SELECT 1 "
          + "                 FROM dobjatcor_dbt atc "
          + "                WHERE atc.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                  AND atc.t_GroupID = " + string(CATEGORY_PRESENCE_OF_IIS)
          + "                  AND atc.t_AttrID = 1 " //Да 
          + "                  AND atc.t_Object = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                  AND ? BETWEEN atc.t_ValidFromDate AND atc.t_ValidToDate) "
          + "   AND NOT EXISTS (SELECT 1 "
          + "                     FROM dobjatcor_dbt atc "
          + "                    WHERE atc.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                      AND atc.t_GroupID = " + string(CATEGORY_DOCUMENTS_PROVIDED_IIS)
          + "                      AND atc.t_AttrID = 1 " //Да 
          + "                      AND atc.t_Object = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                      AND ? BETWEEN atc.t_ValidFromDate AND atc.t_ValidToDate) "
          + "   AND NVL((SELECT RSB_Struct.GetDate(note.t_Text) "
          + "             FROM dnotetext_dbt note "
          + "            WHERE note.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "              AND note.t_NoteKind = " + string(NOTEKIND_IIS_CLOSING_DATE)
          + "              AND note.t_DocumentID = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "          ), TO_DATE('31.12.9999','DD.MM.YYYY')) <= ? "
          + "   AND sfcontr.t_ID = dlcontr.t_SfContrID "
          + "   AND sfcontr.t_DateBegin <= ? "
          + "   AND (sfcontr.t_DateClose = " + GetSQLDate(date(0,0,0)) + " OR sfcontr.t_DateClose > ?) "
          + "   AND partyClnt.t_PartyID = sfcontr.t_PartyID "
          + " ORDER BY sfcontr.t_DateBegin, sfcontr.t_Number ";

    cmd = DL_RSDCommand(query);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(date(m_Parm.ReportDate + m_Parm.DaysToClose));
    cmd.AddParam(m_Parm.ReportDate);
    cmd.AddParam(m_Parm.ReportDate);
    
    cnt = cmd.GetCount();

    if(cnt > 0)
      InitProgress(cnt, "Отчет \"Договоры ИИС, по которым не предоставлены подтверждающие документы о расторжении договора ИИС, заключенного с другим ПУ\"", "Формирование отчета" );
      
      dataSet = cmd.Execute();
      PrintReportHead(m_Parm.ReportDate);
      m_IsDataExist = true;

      while(dataSet.MoveNext())
        PrintLine(dataSet);
        i = i + 1;
        UseProgress(i);
      end;

      EndTable();
      RemProgress;
    else
      msgbox("Нет данных для выпуска отчета");
      m_IsDataExist = false;
    end;
    
    OnError(e)
      msgbox(cmd.GetErrorString(e));
  end;

  private macro Create()
    ExecuteReport();
  end;

  macro CReport_DataExist()
    if(m_IsIntegration == true)
      return m_IsDataExist;
    end;
    return true; 
  end;

  initDL_CReportTemplate(null, "Report_IISContrMonitor_NotProvided.xlsx");  
END;

PRIVATE CLASS (DL_CReportTemplate) SP_IISContrMonitor_Provided_Report(Parm:DL_CPanel)
  private var m_Parm = Parm;
  private var m_IsDataExist = false;

  private macro PrintMode():integer
    return DL_OUTREPORT_EXCEL;
  end;

  private macro PrintReportHead(BeginDate:date, EndDate:date)
    PrintFormatString("", "N1_T2_T3", "за период с " + DateToStr(BeginDate) + " по " + DateToStr(EndDate));

    RegisterTable( "N1_MainTable", "", 
                   "N1_C1", 
                   "N1_C2", 
                   "N1_C3", 
                   "N1_C4", 
                   "N1_C5"
                 );
  end;

  private macro PrintLine(dataSet) 
    PrintTableLine( "N1_C1", dataSet.CntrNumber,         null,
                    "N1_C2", date(dataSet.CntrDate),     null,
                    "N1_C3", dataSet.ClientName,         null,
                    "N1_C4", date(dataSet.ProvidedDate), null, 
                    "N1_C5", IIF(valtype(dataSet.DaysLeft) != V_UNDEF, dataSet.DaysLeft, ""), null
                  );
  end;      

  private macro ExecuteReport()
    var query, cmd, dataSet;
    var cnt = 0, i = 0;

    query = "SELECT sfcontr.t_Number as t_CntrNumber, sfcontr.t_DateBegin as t_CntrDate, partyClnt.t_Name as t_ClientName, atcProvided.t_ValidFromDate as t_ProvidedDate, "
          + "       TO_NUMBER((SELECT RSB_Struct.GetDate(note.t_Text) "
          + "                    FROM dnotetext_dbt note "
          + "                   WHERE note.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                     AND note.t_NoteKind = " + string(NOTEKIND_IIS_CLOSING_DATE)
          + "                     AND note.t_DocumentID = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                 ) - atcProvided.t_ValidFromDate) as t_DaysLeft "
          + "  FROM ddlcontr_dbt dlcontr, dsfcontr_dbt sfcontr, dparty_dbt partyClnt, dobjatcor_dbt atcProvided "
          + " WHERE dlcontr.t_IIS = 'X' "
          + "   AND EXISTS (SELECT 1 "
          + "                 FROM dobjatcor_dbt atc "
          + "                WHERE atc.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                  AND atc.t_GroupID = " + string(CATEGORY_PRESENCE_OF_IIS)
          + "                  AND atc.t_AttrID = 1 " //Да 
          + "                  AND atc.t_Object = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                  AND ? BETWEEN atc.t_ValidFromDate AND atc.t_ValidToDate) "
          + "   AND atcProvided.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "   AND atcProvided.t_GroupID = " + string(CATEGORY_DOCUMENTS_PROVIDED_IIS)
          + "   AND atcProvided.t_AttrID = 1 " //Да 
          + "   AND atcProvided.t_Object = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "   AND atcProvided.t_ValidFromDate BETWEEN ? AND ? "
          + "   AND atcProvided.t_ValidToDate >= ? "
          + "   AND sfcontr.t_ID = dlcontr.t_SfContrID "
          + "   AND sfcontr.t_DateBegin <= ? "
          + "   AND (sfcontr.t_DateClose = " + GetSQLDate(date(0,0,0)) + " OR sfcontr.t_DateClose > ?) "
          + "   AND partyClnt.t_PartyID = sfcontr.t_PartyID "
          + " ORDER BY sfcontr.t_DateBegin, sfcontr.t_Number ";

    cmd = DL_RSDCommand(query);
    cmd.AddParam(m_Parm.ProvidedEndDate);
    cmd.AddParam(m_Parm.ProvidedBeginDate);
    cmd.AddParam(m_Parm.ProvidedEndDate);
    cmd.AddParam(m_Parm.ProvidedEndDate);
    cmd.AddParam(m_Parm.ProvidedEndDate);
    cmd.AddParam(m_Parm.ProvidedEndDate);
    
    cnt = cmd.GetCount();

    if(cnt > 0)
      InitProgress(cnt, "Отчет \"Договоры ИИС, по которым предоставлены подтверждающие документы о расторжении договора ИИС, заключенного с другим ПУ\"", "Формирование отчета" );
      
      dataSet = cmd.Execute();
      PrintReportHead(m_Parm.ProvidedBeginDate, m_Parm.ProvidedEndDate);
      m_IsDataExist = true;

      while(dataSet.MoveNext())
        PrintLine(dataSet);
        i = i + 1;
        UseProgress(i);
      end;

      EndTable();
      RemProgress;
    else
      msgbox("Нет данных для выпуска отчета");
      m_IsDataExist = false;
    end;
    
    OnError(e)
      msgbox(cmd.GetErrorString(e));
  end;

  private macro Create()
    ExecuteReport();
  end;

  initDL_CReportTemplate(null, "Report_IISContrMonitor_Provided.xlsx");  
END;

PRIVATE CLASS (DL_CReportTemplate) SP_IISContrMonitor_Close_Report(Parm:DL_CPanel)
  private var m_Parm = Parm;
  private var m_IsDataExist = false;

  private macro PrintMode():integer
    return DL_OUTREPORT_EXCEL;
  end;

  private macro PrintReportHead(BeginDate:date, EndDate:date)
    PrintFormatString("", "N1_T4_T5", "за период с " + DateToStr(BeginDate) + " по " + DateToStr(EndDate));

    RegisterTable( "N1_MainTable", "", 
                   "N1_E1", 
                   "N1_E2", 
                   "N1_E3", 
                   "N1_E4", 
                   "N1_E5"
                 );
  end;

  private macro PrintLine(dataSet) 
    PrintTableLine( "N1_E1", dataSet.CntrNumber,      null,
                    "N1_E2", date(dataSet.CntrDate),  null,
                    "N1_E3", date(dataSet.CloseDate), null, 
                    "N1_E4", dataSet.ClientName,      null,
                    "N1_E5", dataSet.t_CntrEmail,     null 
                  );
  end;      

  private macro ExecuteReport()
    var query, cmd, dataSet;
    var cnt = 0, i = 0;

    query = "SELECT sfcontr.t_Number as t_CntrNumber, sfcontr.t_DateBegin as t_CntrDate, partyClnt.t_Name as t_ClientName, "
          + "       sfcontr.t_DateClose as t_CloseDate, dlcontr.t_Email as t_CntrEmail "
          + "  FROM ddlcontr_dbt dlcontr, dsfcontr_dbt sfcontr, dparty_dbt partyClnt "
          + " WHERE dlcontr.t_IIS = 'X' "
          + "   AND EXISTS (SELECT 1 "
          + "                 FROM dobjatcor_dbt atc "
          + "                WHERE atc.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                  AND atc.t_GroupID = " + string(CATEGORY_PRESENCE_OF_IIS)
          + "                  AND atc.t_AttrID = 1 " //Да 
          + "                  AND atc.t_Object = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                  AND ? BETWEEN atc.t_ValidFromDate AND atc.t_ValidToDate) "
          + "   AND NOT EXISTS (SELECT 1 "
          + "                     FROM dobjatcor_dbt atc "
          + "                    WHERE atc.t_ObjectType = " + string(OBJTYPE_BROKERCONTR_DL)
          + "                      AND atc.t_GroupID = " + string(CATEGORY_DOCUMENTS_PROVIDED_IIS)
          + "                      AND atc.t_AttrID = 1 " //Да 
          + "                      AND atc.t_Object = LPAD(dlcontr.t_DlContrID, 34, '0') "
          + "                      AND ? BETWEEN atc.t_ValidFromDate AND atc.t_ValidToDate) "
          + "   AND sfcontr.t_DateClose BETWEEN ? AND ? "
          + "   AND sfcontr.t_ID = dlcontr.t_SfContrID "
          + "   AND partyClnt.t_PartyID = sfcontr.t_PartyID "
          + " ORDER BY sfcontr.t_DateBegin, sfcontr.t_Number ";

    cmd = DL_RSDCommand(query);
    cmd.AddParam(m_Parm.CloseEndDate);
    cmd.AddParam(m_Parm.CloseEndDate);
    cmd.AddParam(m_Parm.CloseBeginDate);
    cmd.AddParam(m_Parm.CloseEndDate);
    
    cnt = cmd.GetCount();

    if(cnt > 0)
      InitProgress(cnt, "Отчет \"Закрытые договоры ИИС, по которым не предоставлены подтверждающие документы о расторжении договора ИИС, заключенного с другим ПУ\"", "Формирование отчета" );
      
      dataSet = cmd.Execute();
      PrintReportHead(m_Parm.CloseBeginDate, m_Parm.CloseEndDate);
      m_IsDataExist = true;

      while(dataSet.MoveNext())
        PrintLine(dataSet);
        i = i + 1;
        UseProgress(i);
      end;

      EndTable();
      RemProgress;
    else
      msgbox("Нет данных для выпуска отчета");
      m_IsDataExist = false;
    end;
    
    OnError(e)
      msgbox(cmd.GetErrorString(e));
  end;

  private macro Create()
    ExecuteReport();
  end;

  initDL_CReportTemplate(null, "Report_IISContrMonitor_Close.xlsx");  
END;

MACRO ReportRunEx(IsIntegration:bool,daystoclose):TArray
  var stat = true;
  var report = null; 
 
  var param = IISContrMonitor_Panel();

  var FullReportFileNames = TArray();

  while(stat)
    if(not IsIntegration)
      stat = param.Run();
    else
      param.IsNotProvidedRep = SET_CHAR; 
    end;

    if(stat)
      if(param.IsRequiredRep == SET_CHAR)
        report = SP_IISContrMonitor_Required_Report(param);      
        report.Run();
      end;

      if(param.IsNotProvidedRep == SET_CHAR)
//shev возможно надо переделать, но для интеграции пока сделаю так, чтобы получать значение настроек для первого и второго отчета
        if(valtype(daystoclose) != 0)
           param.daystoclose = daystoclose;
        end;
        report = SP_IISContrMonitor_NotProvided_Report(param, IsIntegration);      
        report.Run();
        if(IsIntegration)
          FullReportFileNames = report.GetFullReportFileNames();
          stat = false; 
        end;       
      end;

      if(param.IsProvidedRep == SET_CHAR)
        report = SP_IISContrMonitor_Provided_Report(param);      
        report.Run();
      end;

      if(param.IsCloseRep == SET_CHAR)
        report = SP_IISContrMonitor_Close_Report(param);      
        report.Run();
      end;
    end;
  end;

  return FullReportFileNames;
END;