/* Триггер на t_state */
CREATE OR REPLACE TRIGGER USR_REQ677_DBT_T3_STATE
  BEFORE INSERT OR UPDATE OF T_STATE ON USR_REQ677_DBT FOR EACH ROW
DECLARE
  x_State CHAR(1) := NVL(:NEW.T_STATE,chr(32));
BEGIN
  IF (x_State = chr(133)) THEN 
    SELECT chr(69) INTO :NEW.T_STATE FROM DUAL;
  ELSIF (x_State NOT IN ('X', 'E', 'F', 'I')) THEN
    SELECT CHR(32) INTO :NEW.T_STATE FROM DUAL;
  END IF;
END;
/
