/* Триггер на авто-инкремент */
CREATE OR REPLACE TRIGGER USR_REQ677_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON USR_REQ677_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT USR_REQ677_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('USR_REQ677_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

/* Триггер на дату/время создания */
CREATE OR REPLACE TRIGGER USR_REQ677_DBT_T1_INS
  BEFORE INSERT ON USR_REQ677_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  :NEW.T_CREATESYSDATE := SYSDATE;
END;
/

/* Триггер на дату/время обновления */
CREATE OR REPLACE TRIGGER USR_REQ677_DBT_T2_UPD
  BEFORE INSERT OR UPDATE ON USR_REQ677_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  :NEW.T_UPDATESYSDATE := SYSDATE;
END;
/