create table Show_max_seq 
    (seq_id integer generated by default as identity,
     sequence_Name varchar2(100), 
     Max_Value integer, 
     Min_Value integer, 
     Last_Number integer,
     Trigger_name varchar2(100),
     Trigger_body LONG,
     Owner varchar2(100),
     Table_name varchar2(100),
     Status varchar2(20));

comment on table  Show_max_seq is  'Список последовательностей, по которым их текущее значение приблизилось к максимальному (>95%)';
comment on column Show_max_seq.sequence_Name is 'название последовательности';
comment on column Show_max_seq.Max_Value is 'максимальное значение';
comment on column Show_max_seq.Min_Value is 'минимальное значение';
comment on column Show_max_seq.Last_Number is 'текущее значение'; 
comment on column Show_max_seq.Trigger_name is 'название триггера, в котором используется последовательность';
comment on column Show_max_seq.Trigger_body is 'тело триггера';
comment on column Show_max_seq.Owner is 'владелец триггера';
comment on column Show_max_seq.Table_name is 'имя таблицы на триггер';
comment on column Show_max_seq.Status is 'статус триггера';
