CREATE GLOBAL TEMPORARY TABLE D_RIA_PANELCONTRS_TMP
(
  T_SETFLAG      CHAR(1),
  T_CLIENTID     NUMBER(10),
  T_DLCONTRID    NUMBER(10),
  T_CONTRNUMBER  VARCHAR2(20),
  T_CONTRNAME    VARCHAR2(200)
)
ON COMMIT PRESERVE ROWS
/

CREATE GLOBAL TEMPORARY TABLE D_RIA_PANELCLIENTS_TMP
(
  T_SETFLAG     CHAR(1),
  T_CLIENTID    NUMBER(10),
  T_CLIENTCODE  VARCHAR2(30),
  T_CLIENTNAME  VARCHAR2(320)
)
ON COMMIT PRESERVE ROWS
/
