-- Добавить поле в таблицу "DNPTXLNKDIASPAY_DBT"
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXLNKDIASPAY_DBT ADD T_RECEIVEDCOUPONAMOUNT NUMBER(32,12) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_RECEIVEDCOUPONAMOUNT IS ''Сумма полученного НКД из Диасофта (ПНКД)''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

