/*Обновление объектов НДР*/
DECLARE
BEGIN

  UPDATE DNPTXOBJ_DBT OBJ
     SET OBJ.T_ANALITICKIND6 = 0,
         OBJ.T_ANALITIC6 = -1
   WHERE OBJ.T_LEVEL IN (3,4,5,6,7)
     AND OBJ.T_ANALITICKIND6 = 6020
     AND OBJ.T_ANALITIC6 > 0
     AND RSI_NPTO.CheckContrIIS(OBJ.T_ANALITIC6) = 0;

END;
/

DECLARE
BEGIN

  UPDATE DNPTXOBJBC_DBT OBJ
     SET OBJ.T_ANALITICKIND6 = 0,
         OBJ.T_ANALITIC6 = -1
   WHERE OBJ.T_LEVEL IN (3,4,5,6,7)
     AND OBJ.T_ANALITICKIND6 = 6020
     AND OBJ.T_ANALITIC6 > 0
     AND RSI_NPTO.CheckContrIIS(OBJ.T_ANALITIC6) = 0;

END;
/