CREATE GLOBAL TEMPORARY TABLE DBRKREPCOURSES_TMP
(
  T_CURRENCY     NUMBER(10),
  T_CCY          VARCHAR2(3),
  T_SERVKIND     NUMBER(5),
  T_SERVKINDSUB  NUMBER(10),
  T_INRATE       NUMBER(32,12),
  T_INPOINT      NUMBER(5),
  T_OUTRATE      NUMBER(32,12),
  T_OUTPOINT     NUMBER(5)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPCOURSES_TMP IS 'Данные для ОБ. Курсы валют'
/
COMMENT ON COLUMN DBRKREPCOURSES_TMP.T_CURRENCY IS 'Идентификатор валюты'
/
COMMENT ON COLUMN DBRKREPCOURSES_TMP.T_CCY IS 'Буквенный код валюты по ISO'
/
COMMENT ON COLUMN DBRKREPCOURSES_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPCOURSES_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/
COMMENT ON COLUMN DBRKREPCOURSES_TMP.T_INRATE IS 'Курс на начало периода'
/
COMMENT ON COLUMN DBRKREPCOURSES_TMP.T_INPOINT IS 'Кол-во отображаемых знаков после запятой на начало периода'
/
COMMENT ON COLUMN DBRKREPCOURSES_TMP.T_OUTRATE IS 'Курс на конец периода'
/
COMMENT ON COLUMN DBRKREPCOURSES_TMP.T_OUTPOINT IS 'Кол-во отображаемых знаков после запятой на конец периода'
/