CREATE GLOBAL TEMPORARY TABLE DDACCOUNTCORRECTION_TMP (
 T_ACCOUNT            VARCHAR2(25) ,
 T_RIGHTCLIENTNAME    VARCHAR2(60)  ,
 T_CURRENCYACC        NUMBER(10),
 T_CCYACC             VARCHAR2(3) ,
 T_REST               NUMBER,
 T_TURNOVER           CHAR(1),
 T_RIGHTROOTDATEBEGIN DATE,
 T_RIGHTROOTNUMBER    VARCHAR2(64) ,
 T_BEFORENAMEACCOUNT  VARCHAR2(1000) ,
 T_AFTERNAMEACCOUNT   VARCHAR2(1000), 
 T_WRONGSUBNUMBER     VARCHAR2(64),
 T_NEWACCOUNT         VARCHAR2(25) ,
 T_USERTYPEACCOUNT    VARCHAR2(16) ,
 T_RIGHTCLIENTID      NUMBER(10), 
 T_RIGHTSERVKINDSUB   NUMBER(5) ,
 T_RIGHTSERVKIND      NUMBER(5), 
 T_RIGHTSFID          NUMBER(10), 
 T_RIGHTMARKETID      NUMBER(10),
 T_RIGHTDLCONTRID     NUMBER(10) ,
 T_WRONGROOTNUMBER    VARCHAR2(64), 
 T_WRONGTSFROOTID     NUMBER(10), 
 T_WRONGROOTDATEBEGIN DATE,
 T_WRONGCLIENTID      NUMBER(10) ,
 T_WRONGCLIENTNAME    VARCHAR2(60),
 T_WRONGDLCONTRID     NUMBER(10),
 T_WRONGSFID          NUMBER(10)
 ) 
ON COMMIT PRESERVE ROWS
NOCACHE
/