DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724CONTR_DBT ADD T_PARENT_SF_ID NUMBER(10) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;
   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724FIREST_DBT ADD T_PRICE   NUMBER(32,12) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;
   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724FIREST_DBT ADD T_PRICERUB   NUMBER(32,12) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;
   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724FIREST_DBT ADD T_PRICEFI NUMBER(10) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;
   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724FIREST_DBT ADD T_NKD  NUMBER(32,12) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;
   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724FIREST_DBT ADD T_ACCOUNT VARCHAR2(25)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724WRTAVR_DBT ADD T_CODE     VARCHAR2(30) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724WRTMONEY_DBT ADD T_CODE     VARCHAR2(25) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724WRTMONEY_DBT ADD T_CODE     VARCHAR2(25) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724WRTAVR_DBT ADD T_NKDNRUR     NUMBER(32,12) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724WRTAVR_DBT ADD T_NKD     NUMBER(32,12) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724WRTAVR_DBT ADD T_COSTNRUR     NUMBER(32,12) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/


DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724WRTAVR_DBT ADD T_PRICEFIID     NUMBER(10) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724WRTAVR_DBT ADD T_RATE     NUMBER(32, 12) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724ARREAR_DBT ADD T_DEALCODE     VARCHAR2(30) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724ARREAR_DBT ADD T_DEALCODETS     VARCHAR2(30) DEFAULT 0';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/