DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724ARREAR_DBT ADD T_VALUENRUR NUMBER(32,12)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/
