/*
$Name:          f119PartCalculateController.mac
$Module:        Отчеты ЦБ
$Description:   Форма 119. Классы контроллеров расчета разделов.
*/

private class (RcbPartCalculateController) TF119PartCalculateController(reportCalculateController : Object, partId : String)
    private var m_protocolView;
    private var m_dataProtocolView;
    private var m_datasource : Object;

    private macro getCalculateAttributeData(attributeId : String, functionName : String, dependencesAttributeIdPool : RcbArray)
        if (dependencesAttributeIdPool == null)
            dependencesAttributeIdPool = RcbArray();
        end;

        var dependencesAttributePool = RcbArray();

        dependencesAttributeIdPool.moveFirst();
        while (dependencesAttributeIdPool.moveNext())
            dependencesAttributePool.push_back(m_part.getAttribute(dependencesAttributeIdPool.getCurrentItem()));
        end;

        return RcbCalculationAttributeData(m_part.getAttribute(attributeId),
                                           RcbArray().initialize(RcbCalculationData(r2m(this, functionName),
                                                                                    RcbArray().initialize(attributeId)
                                                                                   )
                                                                ),
                                           RcbDependencesData(dependencesAttributePool)
                                          );
    end;

    macro calculateAttribute(attributeId)
//        m_dataProtocolView.printSymbolBeginProcess(attributeId);

        var attribute = m_part.getAttribute(attributeId);
        attribute.getValue().setMaxInterestRate(m_datasource.getData(null, attribute, "").getMaxInterestRate().exact);

//        m_dataProtocolView.printSymbolEndProcess();
    end;

    macro execute()
//        m_protocolView.printLine("");

//        m_dataProtocolView.printSymbolBeginProcess(null, "init special symbols");
        for (var i, m_datasources.getDatasource("lines").getData())
            var line = i[0];

            message("Инициализация строки " + line);

            var storage = m_part.getPartCompositeValue().addValue();
            var attributeValue = objectFactoryInstance.createAttributeValue(m_part, storage).setLine(line);
            var attributeProperties = objectFactoryInstance.createAttributeProperties(m_part, storage).setPartId(getPartId()).setAccountMask(BOCB, i[1]).setAccountMask(BORetail, i[2]).setAccountMask(BODeposits, i[3]);

            m_part.addAttribute(line, attributeValue, attributeProperties);

            m_reportCalculateController.addCalculationAttributeData(getCalculateAttributeData(line, "calculateAttribute"));
        end;

//        m_dataProtocolView.printSymbolEndProcess();
    end;

    macro getDataProtocolView()
        return m_dataProtocolView;
    end;

    private macro constructorTF119PartCalculateController(reportCalculateController : Object, partId : String)
        initRcbPartCalculateController(reportCalculateController, partId);
        m_protocolView = m_dataSources.getProtocolView();
//        m_dataProtocolView = m_protocolView.getDataProtocolView("lines");
    end;

    constructorTF119PartCalculateController(reportCalculateController, partId);
end;

class (TF119PartCalculateController) TF119Part1CalculateController(reportCalculateController : Object)
    macro execute()
        execute();
        m_dataProtocolView = m_protocolView.getDataProtocolView("part1");
        m_protocolView.printLine("Для раздела 1 сформирован csv-файл с данными: " + getDataProtocolView().getFileName());
    end;

    private macro constructorTF119Part1CalculateController(reportCalculateController : Object)
        initTF119PartCalculateController(reportCalculateController, TF119Global().getPart1Id());
        m_datasource = m_datasources.getDatasource("part1");
    end;

    constructorTF119Part1CalculateController(reportCalculateController);
end;

class (TF119PartCalculateController) TF119Part2CalculateController(reportCalculateController : Object)
    macro execute()
        execute();
        m_dataProtocolView = m_protocolView.getDataProtocolView("part2");
        m_protocolView.printLine("Для раздела 2 сформирован csv-файл с данными: " + getDataProtocolView().getFileName());
    end;

    private macro constructorTF119Part2CalculateController(reportCalculateController : Object)
        initTF119PartCalculateController(reportCalculateController, TF119Global().getPart2Id());
        m_datasource = m_datasources.getDatasource("part2");
    end;

    constructorTF119Part2CalculateController(reportCalculateController);
end;

class (TF119PartCalculateController) TF119Part3CalculateController(reportCalculateController : Object)
    macro execute()
        execute();
        m_dataProtocolView = m_protocolView.getDataProtocolView("part3");
        m_protocolView.printLine("Для раздела 3 сформирован csv-файл с данными: " + getDataProtocolView().getFileName());
        m_protocolView.printСsvInExcelInstructions("Бэкофис","Номер договора/счета");
    end;

    private macro constructorTF119Part3CalculateController(reportCalculateController : Object)
        initTF119PartCalculateController(reportCalculateController, TF119Global().getPart3Id());
        m_datasource = m_datasources.getDatasource("part3");
    end;

    constructorTF119Part3CalculateController(reportCalculateController);
end;
