BEGIN
  INSERT INTO DSEQUENT_DBT (T_SEQID,T_DESCRIPTION,T_RESETTYPE,T_RESETDATE,T_RESETTIME,T_RESETMONTHS,T_IDENTPROGRAM,T_PASSEND,T_SYSDATECHECK,T_SYSRESETTIME,
                            T_CHECKHISTORY,T_SEQSTATUS,T_STARTVALUE,T_ENDVALUE,T_BRANCH,T_ISLOCAL,T_LEVEL,T_NOUPGRADE,T_USEMETERINHIST,T_RESETCALCTYPE,T_RESERVE)
       VALUES (363,'Код в номере счета Ценной бумаги',0,TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),0,0,'Г',CHR(1),CHR(0),TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),
               CHR(0),0,1,99999,1,CHR(0),1,CHR(0),CHR(0),0,CHR(1));

EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  UPDATE DREFER_DBT 
     SET T_SEQID = 363,
         T_CALCTYPE = 2,
         T_MACROFILE = 'rshb_fi_codeinacc.mac',
         T_MACROPROC = 'GetCodeInAcc'
   WHERE T_REFID = 47;
                      
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
