import DVInter,dv_lib,fx_globals;

              
   private var que,rs9,ii,{curdate},da,dealid,rs5,zz;
   da=DV_SDAT({curdate});
   que="select t_id from ddvndeal_dbt a  where a.t_contractor="+_NKC+"  and ( a.t_kind=22730 or a.t_kind=2730 or a.t_kind=2740)  and to_char(t_date,'dd.mm.yyyy') = '"+da+"'";
   rs9 = LnGetRecordSet(que);
   if(rs9 != null)
     while(rs9.moveNext())
       dealid=int(rs9.value(0));
       zz=DV_ExecDeal(dealid,false);
     end;
   end;
END;