/*
 $Description: функция для автообработки операций расчетов по срочной бирже
 */

import RSD, FIInter, DealsInter, SPInter, DVInter, "rgtgtrec.mac", "gtdlfun.mac", "Календарь", "spserv.mac";

//macro DV_AutoJobMArketOper
 VAR dvoper = TRecHandler("dvoper");
 var IsExistsDVData=false;
 var stat,res;
             var QueryDV = "SELECT dvoper.* "                                     + 
                          "  FROM ddvoper_dbt dvoper  "                           +
                          " WHERE DVOPER.T_DOCKIND = 194 "                        +
                          "       AND DVOPER.T_OPERKIND = 12600 "                 +
                          "       AND DVOPER.T_DATE = " + GetSQLDate({curdate})   +
                          "       AND DVOPER.T_STATE = 0";

            var cmdDV = RSDCommand( QueryDV );
           cmdDV.NullConversion = true;
           cmdDV.Execute();
           var DV = TRsbDataSet(cmdDV);
           while(DV.MoveNext())
               IsExistsDVData = true;
               DV.GetRecord().CopyTo(dvoper.rec);
               stat = DV_InsertMoveStepInDVOperFromGate(dvoper, 1 /*KindActionDV*/); //1  в данном случае основная цепочка
               if(stat == 0)
                    msgbox("Выполнена обработка операции \"" + dvoper.rec.Code + "\"");
               end;
          end;

         if(not IsExistsDVData)
               msgbox("В модуле \"ФИСС и КО\" не найдена открытая операция расчетов на бирже со схемой расчетов, на дату " + string(Date));
         end;
       
end;