import InsCarryDoc, "dv_categ.mac", "dv_car.mac";

private macro ПоставитьНаПросрочку( FD, doc, ДатаИсполненияШага ):integer


     if( not ПроводкаПоКатегориямУчета( FD,  
                                        "-Форвард, РПИ", "Обяз. с н.с.",
                                        ДатаИсполненияШага,
                                        1,
                                        FD.ВалютаОбязательства(),
                                        FD.СуммаОбязательства(),
                                        doc,
                                        INPCARRY, FD.kind, "",
                                        "Просроченные обязательства по сделке " + FD.DealCode(),
                                        null, null,
                                        FD.ВалютаОбязательства(), FD.ВалютаОбязательства(),
                                        FD.ВалютаОбязательства(), FD.СуммаОбязательства()
                                       )
       )
        return 1;
     end;

    return 0;

end;

macro ExecuteStep( doc, FDoc, DocKind, ID_Operation, ID_Step )

  record ndeal(dvndeal);
  SetBuff( ndeal, FDoc );
  var FD = DVFirstDocNDeal(DocKind, ndeal);
  var ДатаИсполненияШага:date;
  var ПлатежОб = RsbPayment( FD.ПлатежОб.rec.PaymentID );

  ДатаИсполненияШага = FD.ДатаИсполнения();

  if( ПоставитьНаПросрочку(FD, doc, ДатаИсполненияШага) != 0 )
     return 1;
  end;
  if( FD.ПлатежОб.rec.PaymentID > 0 )

     if( ПИ_УстановитьСтатусПлатежа(ПлатежОб, PM_OVERDUE) )
        MsgBox( "Ошибка при утановке платежу статуса \"Просрочен\"" );
        return 1;
     end;
  end;

  return 0;

end;

