DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE D724R3CLIENT_GROUP ADD T_ACCKINDIIS NUMBER(5)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/