DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXOP_DBT ADD T_TECHNICAL CHAR(1) DEFAULT CHR(0)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXOP_DBT.T_TECHNICAL IS ''Технический расчет''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/