/*Пересоздание индекса*/
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXCALC_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXCALC_DBT_IDX0 ON DNPTXCALC_DBT
(T_KIND, T_CLIENT, T_CONTRACT, T_ENDDATE, T_IIS, T_SUBKIND)
/