DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXMASSPROT_DBT ADD T_CONTRNUM VARCHAR2(64) DEFAULT CHR(1)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXMASSPROT_DBT.T_CONTRNUM IS ''Номер договора ДБО''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/