-- Таблица "DREGPARMTAG_DBT"

CREATE TABLE DREGPARMTAG_DBT (
    T_ID NUMBER(10)
  , T_KEYID NUMBER(10)
  , T_TAG1 VARCHAR2(25)
  , T_TAG2 VARCHAR2(25)
  , T_TAG3 VARCHAR2(25)
  , T_TAG4 VARCHAR2(25)
  , T_TAG5 VARCHAR2(25)
  , T_TAG6 VARCHAR2(25)
  , T_TAG7 VARCHAR2(25)
  , T_TAG8 VARCHAR2(25)
  , T_TAG9 VARCHAR2(25)
  , T_TAG10 VARCHAR2(25)
)
/
COMMENT ON TABLE DREGPARMTAG_DBT IS 'Теги системных настроек'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_ID IS 'Уникальный Id записи в таблице'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_KEYID IS 'Идентификатор ключа настройки  = T_KEYID таблицы DREGPARM_DBT'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG1 IS 'Значение тега 1'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG2 IS 'Значение тега 2'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG3 IS 'Значение тега 3'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG4 IS 'Значение тега 4'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG5 IS 'Значение тега 5'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG6 IS 'Значение тега 6'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG7 IS 'Значение тега 7'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG8 IS 'Значение тега 8'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG9 IS 'Значение тега 9'
/
COMMENT ON COLUMN DREGPARMTAG_DBT.T_TAG10 IS 'Значение тега 10'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DREGPARMTAG_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DREGPARMTAG_DBT_IDX0 ON DREGPARMTAG_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DREGPARMTAG_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DREGPARMTAG_DBT_IDX1 ON DREGPARMTAG_DBT (
   T_KEYID ASC
)
/

CREATE SEQUENCE DREGPARMTAG_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DREGPARMTAG_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DREGPARMTAG_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DREGPARMTAG_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DREGPARMTAG_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

ALTER TABLE DREGPARM_DBT ADD (
  CONSTRAINT PK_REGPARM_KEYID
  PRIMARY KEY
  (T_KEYID)
  USING INDEX DREGPARM_DBT_IDX0)
/

ALTER TABLE DREGPARMTAG_DBT ADD CONSTRAINT FK_REGPARMTAG_KEYID FOREIGN KEY (T_KEYID) REFERENCES DREGPARM_DBT(T_KEYID)
/