/*Создание таблицы*/
CREATE TABLE DNPTXOPMASS_DBT
(
  T_GUID      VARCHAR2(32)  NOT NULL,
  T_PACKNUM   NUMBER(10)    NOT NULL,
  T_CLIENTID  NUMBER(10)    NOT NULL,
  T_DLCONTRID NUMBER(10)    NOT NULL
)
/

COMMENT ON TABLE DNPTXOPMASS_DBT IS 'Для разб. данных на пачки для парал. генерации операций расчета НОБ'
/

COMMENT ON COLUMN DNPTXOPMASS_DBT.T_GUID IS 'Уникальный идентификатор'
/

COMMENT ON COLUMN DNPTXOPMASS_DBT.T_PACKNUM IS 'Номер пачки данных'
/

COMMENT ON COLUMN DNPTXOPMASS_DBT.T_CLIENTID IS 'Идентификатор клиента'
/

COMMENT ON COLUMN DNPTXOPMASS_DBT.T_DLCONTRID IS 'Идентификатор ДБО'
/

CREATE INDEX DNPTXOPMASS_DBT_IDX0 ON DNPTXOPMASS_DBT
(T_GUID, T_PACKNUM)
/
