DROP TABLE DNPTXOPMASSLIST_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE DNPTXOPMASSLIST_TMP
(
  T_IN_CLIENTID  VARCHAR2(35),
  T_CLIENTID     NUMBER(10),
  T_CONTRNUM     VARCHAR2(64),
  T_DLCONTRID    NUMBER(10)
)
ON COMMIT PRESERVE ROWS
/


CREATE INDEX DNPTXOPMASSLIST_IDX1 ON DNPTXOPMASSLIST_TMP
(T_CLIENTID)
/