/*„®¡ ¢¨âì § ¯¨áì*/
DECLARE
  v_ID       NUMBER := 0;
  v_ParentID NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = 0 AND LOWER(T_NAME) = LOWER('‘•');
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('„ˆ…Š’Žˆˆ');
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('OUT');
  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('6-„”‹');

  IF v_ID > 0 THEN
    UPDATE DREGVAL_DBT 
       SET T_FMTBLOBDATA_XXXX = '54787446696C6500'
     WHERE T_KEYID = v_ID;
  END IF;

END;
/

