-- Таблица "DREGPARMSTORY_DBT"

CREATE TABLE DREGPARMSTORY_DBT (
    T_ID NUMBER(10)
  , T_KEYID NUMBER(10)
  , T_DATEBEGIN DATE
  , T_DATEEND DATE
  , T_INTVALUE NUMBER(10)
  , T_DOUBLEVALUE FLOAT(24)
  , T_BOOLVALUE CHAR(1)
  , T_STRINGVALUE VARCHAR2(50)
)
/
COMMENT ON TABLE DREGPARMSTORY_DBT IS 'Исторические данные по настройкам'
/
COMMENT ON COLUMN DREGPARMSTORY_DBT.T_ID IS 'Уникальный Id записи в таблице'
/
COMMENT ON COLUMN DREGPARMSTORY_DBT.T_KEYID IS 'Идентификатор ключа настройки = T_KEYID таблицы DREGPARM_DBT'
/
COMMENT ON COLUMN DREGPARMSTORY_DBT.T_DATEBEGIN IS 'Дата начала периода действия значения настройки'
/
COMMENT ON COLUMN DREGPARMSTORY_DBT.T_DATEEND IS 'Дата окончания периода действия значения настройки'
/
COMMENT ON COLUMN DREGPARMSTORY_DBT.T_INTVALUE IS 'Целочисленное значение'
/
COMMENT ON COLUMN DREGPARMSTORY_DBT.T_DOUBLEVALUE IS 'Значение числа с плавающей точкой'
/
COMMENT ON COLUMN DREGPARMSTORY_DBT.T_BOOLVALUE IS 'Значение признака YES/NO'
/
COMMENT ON COLUMN DREGPARMSTORY_DBT.T_STRINGVALUE IS 'Строковое значение'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DREGPARMSTORY_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DREGPARMSTORY_DBT_IDX0 ON DREGPARMSTORY_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DREGPARMSTORY_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DREGPARMSTORY_DBT_IDX1 ON DREGPARMSTORY_DBT (
   T_KEYID ASC
)
/

CREATE SEQUENCE DREGPARMSTORY_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DREGPARMSTORY_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DREGPARMSTORY_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DREGPARMSTORY_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DREGPARMSTORY_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
