DECLARE
 cntdel INTEGER := 0;
BEGIN
	FOR all_file IN (SELECT * FROM DXR_LOG_DBT WHERE t_sysdate < (sysdate - NUMTODSINTERVAL(7, 'DAY'))) LOOP
   		BEGIN
 			cntdel := cntdel + 1;
 			DELETE FROM DXR_LOG_DBT dl WHERE dl.t_id = all_file.t_id;
 			IF cntdel >= 10000 THEN
  				BEGIN
   					cntdel := 0;
   					COMMIT;
  				END;
 			END IF;
   		END;
  	END LOOP;
	COMMIT;
	EXECUTE IMMEDIATE 'ALTER SESSION SET DDL_LOCK_TIMEOUT = 60';
	EXECUTE IMMEDIATE 'ALTER TABLE DXR_LOG_DBT ENABLE ROW MOVEMENT';
	EXECUTE IMMEDIATE 'ALTER TABLE DXR_LOG_DBT SHRINK SPACE CASCADE';
	EXECUTE IMMEDIATE 'ALTER TABLE DXR_LOG_DBT DISABLE ROW MOVEMENT';
	EXECUTE IMMEDIATE 'ALTER SESSION SET DDL_LOCK_TIMEOUT = 0';
END;
/
