/*
$Name:          F603ReportCalculateController.mac
$Module:        ¥£« ¬¥­â¨àã¥¬ ï ®âç¥â­®áâì
$Description:   ”®à¬  603. Š®­âà®««¥à à áç¥â  ®âç¥â 
*/

class (RcbReportCalculateController) F603ReportCalculateController()
    initRcbReportCalculateController();

    private macro clearValues()
        global.getRcbReport().attributeValue("„ ­­ë¥âç¥â ").removeAllValues();
        RcbApplication().TransactionManager().commit();
        getDataSources().clear();
    end;

    macro initialize() : Bool
        clearValues();

        m_partCalculateControllers.push_back(F603PartCalculateController(this),"1");
        return m_partCalculateControllers.size > 0;

    end;
end;

class (F603ReportCalculateController) F603ReportCalculateController_2539()
    initF603ReportCalculateController();

    macro initialize() : Bool
        clearValues();

        m_partCalculateControllers.push_back(F603PartCalculateController_2539(this),"1");
        return m_partCalculateControllers.size > 0;

    end;
end;

class (F603ReportCalculateController) F603ReportCalculateController_3129()
    initF603ReportCalculateController();

    macro initialize() : Bool
        clearValues();

        m_partCalculateControllers.push_back(F603PartCalculateController_3129(this),"1");
        return m_partCalculateControllers.size > 0;
    end;
end;

class (F603ReportCalculateController) F603ReportCalculateController_4212()
    initF603ReportCalculateController();

    macro initialize() : Bool
        clearValues();

        m_partCalculateControllers.push_back(F603PartCalculateController_4212(this),"1");
        return m_partCalculateControllers.size > 0;
    end;
end;
