/***********************************************************************
*  Модуль           : Шлюз                                     
*  Имя файла        : gtmktrep.mac
*  Описание         : Добавление объекта "отчет биржи/брокера" в шлюз
*  Программист      : IL 30.09.05
************************************************************************/
IMPORT "gtconst.inc", "rgtgtrec.mac", "gtdlfun.mac";

/*Добавить отчет биржи/брокера 
  App             [In]  - приложение репликации
  PackIns         [In]  - true - режим пакетной вставки
  MarketReportID  [Out] - ID созданного в шлюзе объекта
  ErrMes          [Out] - сообщение об ошибке
  Stat            [Out] - код ошибки
  ReportNumber    [In]  - Номер отчета
  ImpDate         [In]  - Дата отчета
  RgPartyObject   [In]  - ID субъекта в шлюзе (не реальный ID в базе !)
*/
VAR RGMkRep;
MACRO WriteMarketReport( SeanceID:integer, iSeanceLog:GTDL_Log, SourceCode:STRING, OutMarketReportID:@INTEGER, OutErrMes:@STRING, OutStat:@INTEGER, ReportNumber:STRING, ImpDate:DATE, RgPartyObject:STRING )
  VAR stat = 0;

  RGMkRep = TGTRecord(НепосредственнаяВставка, 
                 SeanceID, 
                 iSeanceLog,
                 RG_MARKETREPORT, 
                 String("Отчет биржи/брокера №" + ReportNumber),
                 Создать );

  if(NOT RGMkRep.InitByCode(RG_MARKETREPORT, ReportNumber, SourceCode) )
     stat = 1;
  end;

  if(not stat)
     RGMkRep.SetParmByName("RGMKRP_NUMBER", ReportNumber);
     RGMkRep.SetParmByName("RGMKRP_DATE",   ImpDate);
     RGMkRep.SetParmByName("RGMKRP_AUTHOR", RgPartyObject);
  end;

  OutMarketReportID = RGMkRep.GetObjectID();
  if(RGMkRep.GetLastError())
     OutErrMes = RGMkRep.GetLastError();
  else
     OutErrMes = "";
  end;
  OutStat           = stat;

  return (stat == 0);
END;
