/*
$Name:        DBO_XML.mac
$Module:      Интеграция с внешними системами
$Description: Информация по всем договорам и счетам,включая остатки брокерских счетов и ценных бумаг
*/
import oralib, likepy, globals;

const REG_EXPORT_PATH = "РСХБ\\ИНТЕГРАЦИЯ\\ДИРЕКТОРИИ\\EXPORT\\ДБО"; //путь для выгрузки файла
// Создаёт дочерний элемент вида:  <ElementName>ElementValue</ElementName> 
macro MakeOneElement (ParentElement, ElementName, ElementValue, xml)
   var Element;
   Element = xml.createElement(ElementName);
   Element.Text = ElementValue;
   ParentElement.appendChild(Element);
End;

macro MakeDateStrDBO (_dt:Date)
   var dt = String(_dt);
   dt = StrSubst(dt, " ", "0");
   dt = StrSubst(dt, ".", "");
      dt = substr(dt,5) + substr(dt,3,2)+ substr(dt,1,2);
   return dt;
End;

//Создать xml
macro MakeXml (ClientId, OperKind)
   var ContrData, AccData,DepoData, sql, xml, tempXML;
   var BrokerService,RepDate, ClientData,Contracts,Contract,Account, BrokerAccounts,ClientDataD,ContractsD, ContractD, DepoAccounts, AccountD, Security;
   var created, StrPath, ErrCode, sqlEx, sqltr, sqlfi, sqlcurse;
   var finum;
   var SecuritiesCost = 0;
   var SecuritiesCurrencyCode = "";   
   var cur_elem = null;

   GetRegistryValue(REG_EXPORT_PATH, V_STRING, StrPath, ErrCode);
//   if( ErrCode > 0 )
      StrPath = "d:\\rshb_sofr\\export\\DBO";
//   end;
   sql = ExecSqlSelect("select trunc(sysdate) from dual");
   sql.movenext();

   TempXML = StrPath + "\\Diasoft2DBO_"+MakeDateStrDBO(sql.value(0))+".xml";

   xml = ActiveX("Microsoft.XMLDOM");
   xml.appendChild( xml.createProcessingInstruction("xml"," version='1.0' encoding='UTF-8'") );
   BrokerService  = xml.createElement("BrokerService");

   sqltr = "truncate table DdepoAccRest_dbt";
   sqltr = RSDCommand(sqltr);
   sqltr.execute();
   
   sqltr = "truncate table Ddepofiidcost_dbt";
   sqltr = RSDCommand(sqltr);
   sqltr.execute();

   sqlex = String(
"declare \n",
"   vnotekind number; \n",
"   vtext varchar2(1500 byte); \n",
"   vfi number; \n",
"   vcost number; \n",
"   v_MMVB_Code VARCHAR2(35); \n",
"   v_SPB_Code  VARCHAR2(35); \n",
"   v_mp_mmvb number; \n",
"   v_mp_spb number; \n",
"begin \n",
"   INSERT INTO DdepoAccRest_dbt (T_CONTRID,T_SUBKIND,T_REST,T_ISIN,T_SECNAME,T_FIID) \n",
"   WITH dbo AS ( \n",
"      SELECT mp_sf.t_servkind, \n",
"             mp_sf.t_servkindsub, \n",
"             mp_sf.t_number, \n",
"             mp_sf.t_id sfcontrid, \n",
"             mp_sf.t_partyid, \n",
"             dl.t_dlcontrid \n",
"       FROM \n",
"            ddlcontr_dbt    dl, \n",
"            ddlcontrmp_dbt  mp, \n",
"            dsfcontr_dbt    mp_sf \n",
"      WHERE mp.t_dlcontrid = dl.t_dlcontrid \n",
"            AND mp.t_mpclosedate =  TO_DATE ('01010001', 'ddmmyyyy') \n",
"            AND mp.t_sfcontrid = mp_sf.t_id \n",
"            AND mp_sf.t_servkind = 1 \n",
//"and dl.t_dlcontrid in (13727,13728, 10425) \n",
"        ) \n",
"   SELECT dbo.t_dlcontrid, \n",
"          dbo.t_servkindsub, \n",
"          -1 * rsb_account.restac (accd.t_Account, \n",
"                                   accd.t_Currency, \n",
"                                   SYSDATE, \n",
"                                   accd.t_Chapter, \n",
"                                   NULL) AS restcb, \n",
"          a.t_isin AS isin, \n",
"          f.t_name AS secname, \n",
"          f.t_fiid \n",
"     FROM dbo, \n",
"          dmcaccdoc_dbt  accd, \n",
"          dmccateg_dbt   cat, \n",
"          davoiriss_dbt  a, \n",
"          dfininstr_dbt  f \n",
"    WHERE accd.t_Chapter = 22 \n",
"      AND accd.t_ClientContrID = dbo.sfcontrid \n",
"      AND accd.t_iscommon = CHR (88) \n",
"      AND accd.t_owner = dbo.t_partyid \n",
"      AND cat.t_Id = accd.t_CatID \n",
"      AND cat.t_LevelType = 1 \n",
"      AND cat.t_Code = 'ЦБ Клиента, ВУ' \n",
"      AND a.T_FIID = accd.T_CURRENCY \n",
"      AND f.t_fi_kind = 2 \n",
"      AND a.t_fiid = f.t_fiid; \n",
"   commit; \n",
"   UPDATE DdepoAccRest_dbt d \n",
"      SET d.t_depoacc = (select rsb_struct.getString(t_text) \n",
"                           from dnotetext_dbt \n",
"                          where t_documentid = LPAD(d.t_contrid, 34, 0) \n",
"                            and t_objecttype = 207 \n",
"                            and t_notekind = decode(d.T_SUBKIND,8,104,101)); \n",
"   commit; \n",
"   insert into Ddepofiidcost_dbt (t_fiid) \n",
"     select distinct t_fiid from DdepoAccRest_dbt; \n",
"   update Ddepofiidcost_dbt d set t_facevalue = (select t_facevaluefi from dfininstr_dbt f where f.t_fiid = d.t_fiid); \n",
"   update Ddepofiidcost_dbt d set t_ccy = (select t_ccy from dfininstr_dbt f where f.t_fiid = d.t_facevalue); \n",
"   commit; \n",
"   v_MMVB_Code := trim(rsb_common.GetRegStrValue('SECUR\\MICEX_CODE', 0)); \n",
"   v_SPB_Code  := trim(rsb_common.GetRegStrValue('SECUR\\SPBEX_CODE', 0)); \n",
"   select t_objectid into v_mp_mmvb \n",
"     from dobjcode_dbt where t_objecttype = 3 and t_codekind = 1 and t_code = v_MMVB_Code and t_state =0; \n",
"   select t_objectid into v_mp_spb \n",
"     from dobjcode_dbt where t_objecttype = 3 and t_codekind = 1 and t_code = v_SPB_Code and t_state =0; \n",
"   for datax in (select t_fiid, rowid from Ddepofiidcost_dbt) loop \n",
"      vcost := GetRateFin(datax.t_fiid, sysdate, v_mp_mmvb, v_mp_spb, vfi); \n",
"      update Ddepofiidcost_dbt set t_ficost = vfi, t_cost = vcost \n",
"       where rowid = datax.rowid; \n",
"   end loop; \n",
"   update Ddepofiidcost_dbt d set t_ficostccy = (select t_ccy from dfininstr_dbt f where f.t_fiid = d.t_ficost); \n",
"   commit; \n",
"end;" );
   sqlex = RSDCommand(sqlex);
   sqlex.execute();
   
   ContrData = ExecSqlSelect(
   "SELECT dep.t_name as Branchid,                                                                             "+
   "       cod.t_code as ClientID,                                                                             "+
   "       sfcontr.t_number,                                                                                   "+
   "       t_datebegin as Contractdate,                                                                        "+
   "       decode (dlcontr.t_iis, 'X', 1, 0) as IsIIs,                                                         "+
   "       dlcontr.t_dlcontrid                                                                                 "+
   "  FROM ddlcontr_dbt dlcontr,                                                                               "+
   "       dsfcontr_dbt sfcontr,                                                                               "+
   "       dparty_dbt p,                                                                                       "+
   "       ddp_dep_dbt dep,                                                                                    "+
   "       dobjcode_dbt cod                                                                                    "+
   " WHERE dlcontr.t_sfcontrid = sfcontr.t_id                                                                  "+
   "   AND sfcontr.t_dateclose = TO_DATE('01.01.0001', 'dd.mm.yyyy')                                           "+
   "   AND sfcontr.t_datebegin <= sysdate                                                                      "+
   "   AND sfcontr.t_department = dep.T_code                                                                   "+
   "   AND p.t_partyid = sfcontr.t_partyid                                                                     "+
   "   AND cod.t_objecttype = 3 AND cod.t_objectid = p.t_partyid AND cod.t_codekind = 101 AND cod.t_state = 0  "+
//"and dlcontr.t_dlcontrid in (13727,13728, 10425) "+
   "   AND EXISTS (select 1 from ddlcontrmp_dbt mp, dsfcontr_dbt sub                                           "+
   "                where mp.t_sfcontrid = sub.t_id                                                            "+
   "                  and sub.t_servkind = 1                                                                   "+
   "                  and sub.t_servkindsub in (8, 9)                                                          "+
   "                  and mp.t_dlcontrid = dlcontr.t_dlcontrid)                                                ");
   Repdate = xml.createElement("RepDate");
   RepDate.Text = date(sql.value(0));
   BrokerService.appendchild(RepDate);
   cur_elem = 0;
   while (ContrData.moveNext())
      ClientData = xml.createElement("ClientData");
      MakeOneElement (ClientData, "Branch", string(ContrData.value("Branchid")), xml);
      MakeOneElement (ClientData, "BisId",  string(ContrData.value("ClientID")), xml);
      
      Contracts = xml.createElement("Contracts");
      AccData = ExecSqlSelect("select  settacc.t_account,                                                                     "+
                              "        (select t_ccy from dfininstr_dbt fi where FI.T_FIID = settacc.t_fiid) as AccCurCode,   "+
                              "        RSI_RSB_ACCOUNT.restall( settacc.t_account, 1, settacc.t_fiid, trunc(sysdate)) as rest,"+
                              "        decode(sfcontr.t_servkindsub, 8, 'ММВБ', 9, 'Внебиржа') as TPCode,                     "+
                              "        sfcontr.t_servkindsub                                                                  "+
                              "  from ddlcontrmp_dbt dlcontrmp, dsfcontr_dbt sfcontr, dsfssi_dbt sfssi, dsettacc_dbt settacc  "+
                              " where dlcontrmp.t_dlcontrid = :ContrID                                                        "+
                              "   and dlcontrmp.t_sfcontrid = sfcontr.t_id                                                    "+
                              "   and sfssi.t_objecttype = 659 and sfssi.t_objectid = lpad(sfcontr.t_id, 10, '0')             "+
                              "   and sfssi.t_setaccid = settacc.t_settaccid                                                  "+
                              "   and sfcontr.t_servkind = 1                                                                  "+
                              "   and sfcontr.t_servkindsub in (8, 9)                                                         "+
                              " order by t_servkindsub                                                                        ",
                              makeArray(SqlParam("ContrID", ContrData.value("t_dlcontrid"))));
      cur_elem = 0;
      while(AccData.MoveNext())
         if (cur_elem != AccData.value("t_servkindsub"))
            if (cur_elem != 0)
               Contract.appendchild(BrokerAccounts);
               Contracts.appendchild(Contract);
            end;
            Contract = xml.createElement("Contract");
            MakeOneElement (Contract, "DogBrok", string(ContrData.value("t_number")), xml);
            MakeOneElement (Contract, "DateBrok", date(ContrData.value("Contractdate")), xml);
            MakeOneElement (Contract, "NameTP", string(AccData.value("TPCode")), xml);
            MakeOneElement (Contract, "IIS", ContrData.value("IsIIs"), xml);
            BrokerAccounts = xml.createElement("BrokerAccounts");

            cur_elem = AccData.value("t_servkindsub");
         end;
         Account = xml.createElement("Account");
         MakeOneElement (Account, "Number",  string(AccData.value("t_account")), xml);
         MakeOneElement (Account, "Rest",  string(AccData.value("rest")), xml);
         BrokerAccounts.appendchild(Account);
      end;
      if (cur_elem != 0)
         Contract.appendchild(BrokerAccounts);
         Contracts.appendchild(Contract);
      end;
         
      ClientData.appendchild(Contracts);
      BrokerService.appendchild(ClientData);
   
      Depodata = ExecSqlSelect(" select acc.t_depoacc, acc.t_rest, acc.t_isin, acc.t_secname, acc.t_fiid,   "+
                               "        ficost.t_ficostccy, ficost.t_ccy, ficost.t_cost*acc.t_rest as cost, "+
                               "        acc.t_subkind,                                                      "+
                               "        decode(acc.t_subkind, 8, 'ММВБ', 9, 'Внебиржа') as TPCode           "+
                               "   from DdepoAccRest_dbt acc ,                                              "+
                               "        Ddepofiidcost_dbt ficost                                            "+
                               "   where acc.t_contrid = :Contrid and acc.t_subkind in (8,9)                "+
                               "     and acc.t_depoacc is not null                                          "+
                               "     and acc.t_fiid = ficost.t_fiid                                         "+
                               " order by t_subkind;                                                        ",
                               makeArray(SqlParam("ContrID", ContrData.value("t_dlcontrid"))));
      cur_elem = 0;
      while (DepoData.movenext())
         if (cur_elem != Depodata.value("t_subkind"))
            if (cur_elem == 0)
               ClientDataD = xml.createElement("ClientDataD");
               MakeOneElement (ClientDataD, "Branch", string(ContrData.value("Branchid")), xml);
               MakeOneElement (ClientDataD, "BisId",  ContrData.value("ClientID"), xml);
               if (Depodata.value("t_subkind") == 9)
                  MakeOneElement (ClientDataD, "NameTP", "Внебиржа", xml);
               end;
            else 
               DepoAccounts.appendchild(AccountD);
               ContractD.appendchild(DepoAccounts);
               ContractsD.appendchild(ContractD);
            end;
            
            ContractsD = xml.createElement("Contracts");
            ContractD = xml.createElement("Contract");
            MakeOneElement (ContractD, "DogBrok", string(ContrData.value("t_number")), xml);
            MakeOneElement (ContractD, "DateBrok", date(ContrData.value("Contractdate")), xml);
            MakeOneElement (ContractD, "NameTP", DepoData.value("TPCode"), xml);
            MakeOneElement (ContractD, "IIS", ContrData.value("IsIIs"), xml);
            DepoAccounts = xml.createElement("DepoAccounts");
            AccountD = xml.createElement("AccountD");
            MakeOneElement (AccountD, "NumberD",  string(DepoData.value("t_depoacc")), xml);
            
            cur_elem = Depodata.value("t_subkind")
         end;
         
         Security = xml.createElement("Security");
         MakeOneElement (Security, "SecName",  string(DepoData.value("t_secname")), xml);
         MakeOneElement (Security, "ISIN",  string(DepoData.value("t_isin")), xml);
         MakeOneElement (Security, "RestCB",  string(DepoData.value("t_rest")), xml);

         SecuritiesCost = String(DepoData.value("cost"));
         SecuritiesCurrencyCode = DepoData.value("t_ficostccy");
         if (DepoData.value("cost") == 0)
            SecuritiesCurrencyCode = DepoData.value("t_ccy");
         end; 
         MakeOneElement (Security, "Cost",  SecuritiesCost, xml);
         MakeOneElement (Security, "FundBrief", SecuritiesCurrencyCode, xml);
         AccountD.appendchild(Security);
      end;

      if (cur_elem != 0)
         DepoAccounts.appendchild(AccountD);
         ContractD.appendchild(DepoAccounts);
         ContractsD.appendchild(ContractD);
         
         ClientDataD.appendchild(ContractsD); 
         BrokerService.appendchild(ClientDataD);
      end;
      created = 0;
   end;
   xml.appendchild(BrokerService);

//   println(string(xml.xml));
   xml.Save(TempXML);
   return 0;
onError(err)
   return 1;
End;

//MakeXml;
