private class CErrorFilterData(pErrorCode: Integer, pErrorMessagePart: String)
  var errorCode = pErrorCode;
  var errorMessagePart = pErrorMessagePart;
end;

macro GetErrorFilterRecs(): TArray
  var result = TArray();
  
  result(result.size) = CErrorFilterData(1, "Сделка загружена ранее!");
  result(result.size) = CErrorFilterData(1, "начата операция! Обновление не возможно");
  result(result.size) = CErrorFilterData(-1000, "Сделки Repo не обрабатываются");
  
  return result;
end;