//А.Киселев 08.01.2011 интерфейсная загрузка RUData Общая информация по ценным бумагам, купоны и частичные погашения облигаций
import "loadRUData.mac";


var StrLSIN_ISIN = "",
    Mode = -1,
    err  = "";


private macro iif(c,a,b)
   if (c) return a; else return b; end;
end;

if( ( GetString( StrLSIN_ISIN, "Укажите LSIN или ISIN ценной бумаги.", 35 ) ) and ( StrLSIN_ISIN != "" ) )
    var Dt = TRsbDataSet(" select a.t_isin, a.t_lsin, f.t_name, (select t_shortname from dparty_dbt where t_partyid = f.t_issuer) issuername " +
                         " from davoiriss_dbt a, dfininstr_dbt f where a.t_fiid = f.t_fiid " + 
                         " and ( (a.t_isin = '" +trim(StrLSIN_ISIN)+"') or (a.t_lsin ='" +trim(StrLSIN_ISIN)+"'))");
   if (Dt.movenext())
      if (MsgBoxEx( "Бумага уже есть в справочнике. | "  
                    + " ISIN: " + dt.isin +" № гос.рег: " + dt.lsin + "| " 
                    + Dt.name + "|"
                    + "Эмитент: " + Dt.issuername + "|" 
                    + " Обновить выпуск по данным RU DATA? ", MB_YES+MB_NO, IND_YES, "Предупреждение", "") == IND_YES)
         Mode = 0;
      end;
   else
      if (MsgBoxEx( "Бумаги нет в справочнике. | "  
                  + " Загрузить новый выпуск из RU DATA ? ", MB_YES+MB_NO, IND_YES, "Предупреждение", "") == IND_YES)
         Mode = 1;
      end;
   end;

   if (Mode != -1)
      if( SOFR_LoadRuDataByID( StrUpr( StrLSIN_ISIN ), Mode, @err, null, true ) )
         MsgBox("Ценная бумага с кодом " + StrLSIN_ISIN + iif(Mode," загружена."," обновлена."));
      else
         MsgBox("Ценная бумага с кодом " + StrLSIN_ISIN + iif(Mode," не загружена."," не обновлена.")+"|" + err);
      end;
   else
      MsgBox("Обработка отменена.");
   end;
elif( ( {Oper} == 1 ) and (MsgBoxEx( "Загружаем данные по всем бумагам справочника СОФР?", MB_YES+MB_NO, IND_YES, "Предупреждение", "") == IND_YES) )
   if( SOFR_LoadBondAndSec( @err ) )
      MsgBox("Ценные бумаги загружены.");
   else
      MsgBox("Ошибки при загрузке ценных бумаг. |"+err);
   end;
end;

Exit(1);
