import RSD,bankinter, CTInter;
import "Func_lib.mac";

/* Загрузка сведений из Диасофт по договорам и счетам ДЕПО */
macro m_dias_depo_data_load()
   var v_is_clean_in_advance = false; /* 20190107 - kva: добавил признак предварительной очистки sofr_contaccdeporesult */
   var v_sql_cl, v_cmd_cl;
   var cmd1, rs1, cmdrez, rsrez;
   var cmd = "select RECID, CONTRACTNUMBER, CONTRACTDATE, DEPONUMBER, to_char(DEPODATE, 'dd.mm.yyyy'), DEPOID,ACCDEPONUMBER, SECTIONCODE,to_char(DEPOCLOSEDATA, 'dd.mm.yyyy')  from SOFR_CONTACCDEPOIN";
   cmd = RSDCommand(cmd);
   var rs = RsdRecordset(cmd);
   var Error = 0;
   var errortext = "";

   while(rs.movenext)
      cmd1 = "select ddlcontr.t_dlcontrid from "+
             " ddlcontr_dbt ddlcontr "+
             " left join dsfcontr_dbt sfcontr on sfcontr.t_id = ddlcontr.T_SFCONTRID "+
             " where sfcontr.t_number = :inparam ";
      cmd1 = rsdcommand(cmd1);
      cmd1.AddParam("inparam", RSDBP_IN, rs.value(1));
      rs1 = RsdRecordset(cmd1);
      rs1.movenext;
      if (valtype(rs1.value(0))== 26)
         error = 1;
         errortext = "Не найден Договор БО"
      else
         if ((substr(rs.value(6), 1, 1) == "К") or ((substr(rs.value(6), 1, 1) == "K"))) //не знаю, кириллица или латиница, поэтому на всякий случай
            if (addnoteforobject(207,string(rs1.value(0):34:o),101,rs.value(6)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
            if (addnoteforobject(207,string(rs1.value(0):34:o),105,rs.value(7)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
         elif ((substr(rs.value(6), 1, 1) == "Т") or ((substr(rs.value(6), 1, 1) == "T"))) //не знаю, кириллица или латиница, поэтому на всякий случай
            if (addnoteforobject(207,string(rs1.value(0):34:o),104,rs.value(6)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
            if (addnoteforobject(207,string(rs1.value(0):34:o),106,rs.value(7)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
         elif ((substr(rs.value(6), 1, 1) == "M") or ((substr(rs.value(6), 1, 1) == "М"))) //не знаю, кириллица или латиница, поэтому на всякий случай
            if (addnoteforobject(207,string(rs1.value(0):34:o),107,rs.value(6)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
            if (addnoteforobject(207,string(rs1.value(0):34:o),108,rs.value(7)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
         elif ((substr(rs.value(6), 1, 3) == "D-0") or ((substr(rs.value(6), 1, 3) == "Д-0"))) //не знаю, кириллица или латиница, поэтому на всякий случай
            if (addnoteforobject(207,string(rs1.value(0):34:o),101,rs.value(6)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
            if (addnoteforobject(207,string(rs1.value(0):34:o),105,rs.value(7)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
         elif ((substr(rs.value(6), 1, 3) == "D-T") or ((substr(rs.value(6), 1, 3) == "Д-Т"))) //не знаю, кириллица или латиница, поэтому на всякий случай
            if (addnoteforobject(207,string(rs1.value(0):34:o),104,rs.value(6)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
            if (addnoteforobject(207,string(rs1.value(0):34:o),106,rs.value(7)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;

         elif ((substr(rs.value(6), 1, 1) == "D") or ((substr(rs.value(6), 1, 1) == "Д")) and (substr(rs.value(6), 3, 1) != "Д")) //не знаю, кириллица или латиница, поэтому на всякий случай
            if (addnoteforobject(207,string(rs1.value(0):34:o),101,rs.value(6)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
            if (addnoteforobject(207,string(rs1.value(0):34:o),105,rs.value(7)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
         end;

         if (valtype(rs.value(3))!= 26)
            if (addnoteforobject(207,string(rs1.value(0):34:o),102,rs.value(3)) == 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
         end;
         if (valtype(rs.value(4))!= 26)
            if (addnoteforobject(207,string(rs1.value(0):34:o),103,date(rs.value(4)))== 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
         end;
         if (valtype(rs.value(8))!= 26)
            if (addnoteforobject(207,string(rs1.value(0):34:o),110,date(rs.value(8)))== 1)
               error = 2;
               errortext = "Невозможно вставить примечание";
            end;
         end;

         // BIQ-7089 Гераськина Т.В.
         UpdateStatusContractFromDepo(rs1.value(0));
      end;

      /* 20190107 - kva: добавил предварительную очистку таблицы */
      if(not v_is_clean_in_advance)
         v_sql_cl = "TRUNCATE TABLE sofr_contaccdeporesult";
         v_cmd_cl = RSDCommand(v_sql_cl);
         v_cmd_cl.execute();

         v_cmd_cl.close(); v_cmd_cl = NULL; v_sql_cl = NULL;

         v_is_clean_in_advance = true;
      end;

      cmdrez = "insert into SOFR_CONTACCDEPORESULT(recid, contractnumber, CONTRACTDATE , DEPONUMBER , DEPODATE , DEPOID , ACCDEPONUMBER , SECTIONCODE ,DEPOCLOSEDATA, RESULTCODE , RESULTTEXT, t_timestamp ) values "+
               "(:inparam0, :inparam1, :inparam2, :inparam3, :inparam4,:inparam5, :inparam6, :inparam7,:inparam8,:inparam9,:inparam10, systimestamp )";
      cmdrez = rsdcommand(cmdrez);
      cmdrez.AddParam("inparam0", RSDBP_IN, rs.value(0));
      cmdrez.AddParam("inparam1", RSDBP_IN, rs.value(1));
      cmdrez.AddParam("inparam2", RSDBP_IN, rs.value(2));
      cmdrez.AddParam("inparam3", RSDBP_IN, rs.value(3));
      cmdrez.AddParam("inparam4", RSDBP_IN, rs.value(4));
      cmdrez.AddParam("inparam5", RSDBP_IN, rs.value(5));
      cmdrez.AddParam("inparam6", RSDBP_IN, rs.value(6));
      cmdrez.AddParam("inparam7", RSDBP_IN, rs.value(7));
      cmdrez.AddParam("inparam8", RSDBP_IN, rs.value(8));
      cmdrez.AddParam("inparam9", RSDBP_IN, error);
      cmdrez.AddParam("inparam10", RSDBP_IN, errortext);
      cmdrez.execute;
      error = 0;
      errortext = "";
   end;
/* 20190107 - kva: по ФТ очистку этой таблицы выполняет Внешняя система *//*
   var cmddel = "truncate table SOFR_CONTACCDEPOIN";
   cmddel = RSDCommand(cmddel);
   cmddel.execute;
*/
end;
//m_dias_depo_data_load();