import "u_common_email_utils.mac";

if (not gettrue(false,"Начать выгрузку в ЦХД сделок по ПФИ?"))
  msgbox ("Был отказ от выгрузки");  
  exit(1);       
end;


 var  cmd =ExecSqlSelect( "select * from uTableProcessEvent_dbt where T_OBJECTTYPE = 28 and t_status = 4 and trunc(t_timestamp)= trunc(sysdate) ");

 if (cmd.movenext())
   if (not gettrue(false,"Выгрузка в ЦХД сделок по ПФИ сегодня уже производилась. Вы хотите провести выгрузку за сегодня повторно?"))
      msgbox ("Был отказ от выгрузки");  
      exit(1);       
   end;
 end;

begaction (20, "Выгрузка данных");
  ExecMacroFile("ws_synch_SOFR.mac", "ws_Event_CHD_PFI");
endaction;
msgbox ("Выгрузка окончена");
exit(1);     

