--Обновление пользовательских шагов операции 12715
BEGIN
    UPDATE DOPROSTEP_DBT SET T_SYMBOL = 'И' WHERE T_BLOCKID = 40000022 AND T_NUMBER_STEP = 10;
    UPDATE DOPROSTEP_DBT SET T_SYMBOL = '#' WHERE T_BLOCKID = 40000022 AND T_NUMBER_STEP = 11;
    UPDATE DOPROSTEP_DBT SET T_PREVIOUS_STEP = 110 WHERE T_BLOCKID = 40000030 AND T_NUMBER_STEP = 115;                 
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/