-- Таблица "DTRN_PROHIBITED_DBT"

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DTRN_PROHIBITED_DBT (
    T_ID NUMBER(10)
  , T_ACCTRNID NUMBER(10)
  , T_DATE_CARRY DATE
  , T_FIID_PAYER NUMBER(10)
  , T_FIID_RECEIVER NUMBER(10)
  , T_ACCOUNTID_PAYER NUMBER(10)
  , T_ACCOUNTID_RECEIVER NUMBER(10)
  , T_ACCOUNT_PAYER VARCHAR2(25)
  , T_ACCOUNT_RECEIVER VARCHAR2(25)
  , T_SUM_NATCUR NUMBER(32,12)
  , T_SUM_PAYER NUMBER(32,12)
  , T_SUM_RECEIVER NUMBER(32,12)
  , T_OPER NUMBER(10)
  , T_GROUND VARCHAR2(600)
  , T_DOCID NUMBER(10)
  , T_DOCKIND NUMBER(5)
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON TABLE DTRN_PROHIBITED_DBT IS ''Запрещенные проводки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_ID IS ''Идентификатор записи''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_ACCTRNID IS ''Идентификатор проводки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_DATE_CARRY IS ''Дата проводки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_FIID_PAYER IS ''Валюта плательщика''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_FIID_RECEIVER IS ''Валюта получателя''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_ACCOUNTID_PAYER IS ''Идентификатор счета плательщика''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_ACCOUNTID_RECEIVER IS ''Идентификатор счета получателя''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_ACCOUNT_PAYER IS ''Счет плательщика''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_ACCOUNT_RECEIVER IS ''Счет получателя''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_SUM_NATCUR IS ''Сумма в нац.валюте''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_SUM_PAYER IS ''Сумма плательщика''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_SUM_RECEIVER IS ''Сумма получателя''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_OPER IS ''Операционист''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_GROUND IS ''Основание проводки''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_DOCID IS ''Идентификатор операции''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRN_PROHIBITED_DBT.T_DOCKIND IS ''Вид документа''';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DTRN_PROHIBITED_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DTRN_PROHIBITED_DBT_IDX0 ON DTRN_PROHIBITED_DBT (
   T_ID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DTRN_PROHIBITED_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DTRN_PROHIBITED_DBT_IDX1 ON DTRN_PROHIBITED_DBT (
   T_DATE_CARRY DESC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DTRN_PROHIBITED_DBT_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
   e_exist_seq EXCEPTION;
   PRAGMA EXCEPTION_INIT(  e_exist_seq,    -955 );
BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE DTRN_PROHIBITED_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
   WHEN e_exist_seq THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER DTRN_PROHIBITED_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DTRN_PROHIBITED_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DTRN_PROHIBITED_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DTRN_PROHIBITED_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/