-- Таблица "DNPTXACCTRNDATA_TMP"

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DNPTXACCTRNDATA_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DNPTXACCTRNDATA_TMP (
    T_NPTXOPID NUMBER(10)
  , T_ACCTRNID NUMBER(10)
  , T_OBJID    NUMBER(10)
  , T_ISPRINTED CHAR(1)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/


COMMENT ON TABLE DNPTXACCTRNDATA_TMP IS 'Проводки для отчета по удержанноу НДФЛ'/
COMMENT ON COLUMN DNPTXACCTRNDATA_TMP.T_NPTXOPID  IS 'Идентификатор операции удержания'/
COMMENT ON COLUMN DNPTXACCTRNDATA_TMP.T_ACCTRNID  IS 'Идентификатор проводки'/
COMMENT ON COLUMN DNPTXACCTRNDATA_TMP.T_OBJID     IS 'Идентификатор объекта НДР'/
COMMENT ON COLUMN DNPTXACCTRNDATA_TMP.T_ISPRINTED IS 'Призна напечатанной проводки'/
