DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXOBJ_TMP ADD T_CONVDATE DATE DEFAULT TO_DATE(''01.01.0001'',''DD.MM.YYYY'')';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXOBJ_TMP.T_CONVDATE IS ''Дата конвертации t_Sum в рубли''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

