-- Таблица "DTRNRULES_DBT"

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DTRNRULES_DBT (
    T_ID NUMBER(10)
  , T_ACC_MASK VARCHAR2(25)
  , T_SIDE NUMBER(5)
  , T_ATTR_KIND NUMBER(5)
  , T_OPER NUMBER(5)
  , T_ATTR_VALUE VARCHAR2(32)
  , T_ISACTIVE CHAR(1)
  , T_STARTDATE DATE
  , T_ENDDATE DATE
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON TABLE DTRNRULES_DBT IS ''Правила блокировки проводок''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULES_DBT.T_ID IS ''Идентификатор правила''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULES_DBT.T_ACC_MASK IS ''Маска счета ''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULES_DBT.T_SIDE IS ''Дебет или кредит''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULES_DBT.T_ATTR_KIND IS ''Вид атрибута''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULES_DBT.T_OPER IS ''Вид операции''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULES_DBT.T_ATTR_VALUE IS ''Значение аттрибута''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULES_DBT.T_ISACTIVE IS ''Статус правила, активное ли''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULES_DBT.T_STARTDATE IS ''Дата начала''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULES_DBT.T_ENDDATE IS ''Дата окончания''';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DTRNRULES_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DTRNRULES_DBT_IDX0 ON DTRNRULES_DBT (
   T_ID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DTRNRULES_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DTRNRULES_DBT_IDX1 ON DTRNRULES_DBT (
   T_ISACTIVE ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DTRNRULES_DBT_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
   e_exist_seq EXCEPTION;
   PRAGMA EXCEPTION_INIT(  e_exist_seq,    -955 );
BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE DTRNRULES_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
   WHEN e_exist_seq THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER DTRNRULES_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DTRNRULES_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DTRNRULES_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DTRNRULES_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/