DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXOBJ_TMP ADD T_ACTION NUMBER(5) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXOBJ_TMP.T_ACTION IS ''Действие''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXOBJ_TMP ADD T_REALOBJID NUMBER(10) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXOBJ_TMP.T_REALOBJID IS ''ID существующего НДР''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/
