-- Таблица "DDIFNDRTMP_DBT"

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DDIFNDRTMP_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DDIFNDRTMP_DBT (
    T_DATE         DATE        DEFAULT TRUNC (SYSDATE)
  , T_SESSIONID    NUMBER(10)
  , T_DOCID        NUMBER(10)
  , T_OPERDATE     DATE
  , T_PERSONID     NUMBER(10)
  , T_CLIENT       VARCHAR2(500)
  , T_CONTRACT     VARCHAR2(500)
  , T_ACCDEB       VARCHAR2(50)
  , T_ACCCRED      VARCHAR2(50)
  , T_BALSUMRUB    NUMBER(32,12)
  , T_OBJECTTYPE   VARCHAR2(50)
  , T_TAXPAID      NUMBER(32,12)
  , T_ACCTRNID     NUMBER(10)
  , T_OBJID        NUMBER(10)
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/