/*Добавить статус на блок операции*/
DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203500,46052,3,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/