--Добавление новых полей в таблицу значений по операция НДФЛ
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXVAL_DBT ADD T_RATE NUMBER(5) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXVAL_DBT.T_RATE IS ''Ставка, к которой относится значение''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXVAL_DBT ADD T_KBK VARCHAR2(20) DEFAULT CHR(1)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXVAL_DBT.T_KBK IS ''КБК, к которому относится значение''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXVAL_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX DNPTXVAL_DBT_IDX1 ON DNPTXVAL_DBT
(T_DOCKIND, T_DOCID, T_KIND, T_RATE, T_KBK, T_DATE)
/

