/*Добавление настройки*/
DECLARE
  v_ID       NUMBER := 0;
  v_ParentID NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = 0 AND LOWER(T_NAME) = LOWER('COMMON');
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('НДФЛ');

  INSERT INTO DREGPARM_DBT(T_KEYID,T_PARENTID,T_NAME,T_TYPE,T_GLOBAL,T_DESCRIPTION,T_SECURITY,T_ISBRANCH,T_TEMPLATE)
  VALUES(0,v_ParentID,'НП_ВВОДА_ДОРАБОТОК_МАТ.ВЫГОДА',0,'X','Определяет налоговый период, начиная с которого вводится в действие новый алгоритм расчета НОБ по мат. выгоде',CHR(0),CHR(0),CHR(1)) returning T_KEYID INTO v_ID;

  INSERT INTO DREGPARMTAG_DBT(T_ID, T_KEYID, T_TAG1, T_TAG2, T_TAG3, T_TAG4, T_TAG5, T_TAG6, T_TAG7, T_TAG8, T_TAG9, T_TAG10)
              VALUES(0, v_ID, 'TAX', CHR(1), CHR(1), CHR(1), CHR(1), CHR(1), CHR(1), CHR(1), CHR(1), CHR(1));

  INSERT INTO DREGVAL_DBT(T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX )
  VALUES(v_ID,0,0,CHR(0),0,2025,0,'');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/
