declare
n integer;
begin
  select count(*) into n from user_tables t where t.TABLE_NAME = 'U_DEPOACC_TRADEPLACE' ;
  if n > 0 then
    execute immediate 'drop table U_DEPOACC_TRADEPLACE';
  end if;
  execute immediate 'create table U_DEPOACC_TRADEPLACE
  (
    t_depoacc_firstletter  VARCHAR2(5) not null,
    t_depoacc_middlenumber VARCHAR2(10) not null,
    t_market               VARCHAR2(124) not null,
    t_agreement_suffix     CHAR(2)
  )';
  execute immediate 'comment on table U_DEPOACC_TRADEPLACE is ''BIQ-13034 ­ αβΰ®¥η­®© β ΅«¨ζ  ¤«ο δγ­ªζ¨¨ GetSubAgreementByDepoAccount''';
  execute immediate 'comment on column U_DEPOACC_TRADEPLACE.t_depoacc_firstletter is ''ΰ¥δ¨ªα αη¥β  „¥―®''';
  execute immediate 'comment on column U_DEPOACC_TRADEPLACE.t_depoacc_middlenumber is ''¥αβ® εΰ ­¥­¨ο ΰ §¤¥«  αη¥β  „…''';
  execute immediate 'comment on column U_DEPOACC_TRADEPLACE.t_market is ''«®ι ¤   εΰ ­¥­¨ο ζ/΅ Ά ‘” ¨§ 2 ( € „, € ‘―΅  ­ª)''';
  execute immediate 'comment on column U_DEPOACC_TRADEPLACE.t_agreement_suffix is ''‘γδδ¨ªα αγ΅¤®£®Ά®ΰ  Ά ‘”. €Άβ®¬ β¨η¥αª¨ § ―®«­ο¥βαο Ά § Ά¨α¨¬®αβ¨ ®β §­ η¥­¨ο ―®«ο "«®ι ¤ª "''';
  execute immediate 'create unique index U_DEPOACC_TRADEPLACE_IDX1 on U_DEPOACC_TRADEPLACE (T_DEPOACC_FIRSTLETTER, T_DEPOACC_MIDDLENUMBER)';

  insert into U_DEPOACC_TRADEPLACE values ('K-','0404','αª«ξη¥­¨¥','');
  insert into U_DEPOACC_TRADEPLACE values ('T-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','3036',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','3336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI1-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI2-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI3-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI4-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI5-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI6-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI7-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI8-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('TI9-','3636',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','3637',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','3650',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','3677',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','3939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','3950','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('K-','4040','αª«ξη¥­¨¥','');
  insert into U_DEPOACC_TRADEPLACE values ('T-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','6239','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','6336',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','6350',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','6377',' € „','_δ');
  insert into U_DEPOACC_TRADEPLACE values ('T-','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('D-T','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T1-','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T2-','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T3-','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T4-','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T5-','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T6-','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T7-','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T8-','6939','€ ‘  ­ª','_s');
  insert into U_DEPOACC_TRADEPLACE values ('T9-','6939','€ ‘  ­ª','_s');
end;
