/*Добавление настройки*/
DECLARE

BEGIN

  UPDATE DNPTXTOTALBASEBC_DBT SET T_DLCONTRID = 0 WHERE T_DLCONTRID IS NULL;

  UPDATE DNPTXTOTALBASEBC_DBT SET T_SPECIALTAG = CHR(0) WHERE T_SPECIALTAG IS NULL;

  UPDATE DNPTXTOTALBASEBC_DBT SET T_SYSCOME = 1 WHERE T_SYSCOME IS NULL;

END;
/
