-- Таблица "DNPTXTAXBASERANGES_TMP"
DECLARE
   e_noexist_table EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_noexist_table, -942);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DNPTXTAXBASERANGES_TMP CASCADE CONSTRAINTS';
   EXCEPTION WHEN e_noexist_table THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DNPTXTAXBASERANGES_TMP (
    T_TAXBASETYPE NUMBER(10)
  , T_TAXPERIOD NUMBER(5)
  , T_RANGE NUMBER(5)
  , T_BASESUM NUMBER(32,12)
  , T_TAXRATE NUMBER(5)
  , T_KBK VARCHAR2(20)
  , T_TAXCALC NUMBER(32,12)
  , T_TAXHOLD NUMBER(32,12)
  , T_SPECIALTAG VARCHAR2(16)
) ON COMMIT PRESERVE ROWS
/

COMMENT ON TABLE DNPTXTAXBASERANGES_TMP IS 'Врем. табл. нал. диапазонов НОБ'
/

COMMENT ON COLUMN DNPTXTAXBASERANGES_TMP.T_TAXBASETYPE IS 'Вид НОБ'
/

COMMENT ON COLUMN DNPTXTAXBASERANGES_TMP.T_TAXPERIOD IS 'Налоговый период'
/

COMMENT ON COLUMN DNPTXTAXBASERANGES_TMP.T_RANGE IS 'Номер диапазона'
/

COMMENT ON COLUMN DNPTXTAXBASERANGES_TMP.T_BASESUM IS 'Сумма НОБ'
/

COMMENT ON COLUMN DNPTXTAXBASERANGES_TMP.T_TAXRATE IS 'Налоговая ставка'
/

COMMENT ON COLUMN DNPTXTAXBASERANGES_TMP.T_KBK IS 'КБК'
/

COMMENT ON COLUMN DNPTXTAXBASERANGES_TMP.T_TAXCALC IS 'Налог исчисленный'
/

COMMENT ON COLUMN DNPTXTAXBASERANGES_TMP.T_TAXHOLD IS 'Налог исчисленный к удержанию'
/

COMMENT ON COLUMN DNPTXTAXBASERANGES_TMP.T_SPECIALTAG IS 'Спец. признак'
/

