/*
Добавление нового статуса Подкрепление ИРК 
*/
DECLARE

t_count integer;

BEGIN
  INSERT INTO DOPRSTKND_DBT(T_STATUSKINDID,T_CODE,T_NAME,T_DOCKIND,T_SORT,T_ELIMINATED)
  SELECT 484131,'ИРК','Подкрепление ИРК',4607,0,CHR(0)
  FROM dual
  WHERE NOT EXISTS ( SELECT 1 FROM DOPRSTKND_DBT WHERE T_STATUSKINDID = 484131); 

SELECT count(*) INTO t_count from DOPRSTVAL_DBT where T_STATUSKINDID = 484131;
if t_count = 0 then

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(484131,1,'Готов к исполнению',CHR(0));

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(484131,2,'Завершено',CHR(0));

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(484131,3,'Отказано',CHR(0));

end if;
END;
/