/*Добавить блок*/
DECLARE
BEGIN
  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(203517,'Расчет НДР457',4605,0,CHR(0),CHR(1),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/
