/*──────────────────────────────────────────────────────────────────────────┐
  RS-Bank 6.0                                          R-Style Software Lab

  File Name   : BankBills.mac
  Programmer  : Кастелин А.Н.
  Comment     : контрольные примеры для RsVox объекта RvsBankBill
└───────────────────────────────────────────────────────────────────────────*/

IMPORT RsbObjFactory, dlmisc, HTMLRep, bills;

PRIVATE MACRO HTMLDecodeFormula(f)
    if   (f == -1)
        return "unknown (-1)";
    elif (f == 0)
        return "дисконт (0)";
    elif (f == 1)
        return "простые %% (1)";
    elif (f == 2)
        return "сложные %% (2)";
    elif (f == 3)
        return "дисконтно-процентный (3)";
    end;

    return "n/a";
END;
//=========================================================

PRIVATE MACRO PrintHolders(hld)
var stat = hld.Next(),
    data = false;

    if (stat)
        rep_tbl_regroup();
        rep_tbl_start();

        rep_hdr("BCID");
        rep_hdr("Дата приобретения векселя");
        rep_hdr("Держатель векселя");

        rep_tbl_hdrend();

        data = true;
    end;

    while (stat)
        rep_tbl_group(hld.BCID);
        rep_tbl_row_start();

        rep_cell(hld.BCID);             // BCID
        rep_cell(hld.HandingDate);      // Дата приобретения векселя
        rep_cell(hld.Party.FullName);   // Держатель векселя

        rep_tbl_row_end();

        stat = hld.Next();
    end;

    if (data)
        rep_tbl_end();
    end;

    return data;
END;
//=========================================================

PRIVATE MACRO PrintExpenses(exp)
var stat = exp.Next(),
    data = false;

    if (stat)
        rep_tbl_regroup();
        rep_tbl_start();

        rep_hdr("BCID");
        rep_hdr("Дата значения остатка");
        rep_hdr("Сумма");
        rep_hdr("Валюта");
        rep_hdr("Дебет");
        rep_hdr("Кредит");
        rep_hdr("Филиал");

        rep_tbl_hdrend();
    
        data = true;
    end;

    while (stat)

        rep_tbl_group(exp.BCID);
        rep_tbl_row_start();

        rep_cell(exp.BCID);                                     // BCID
        rep_cell(exp.Valuedate);                                // Дата значения остатка
        rep_cell(exp.Amount);                                   // Сумма
        rep_cell(exp.Currency);                                 // Валюта
        rep_cell(exp.DebitAccount);                             // Дебит
        rep_cell(exp.CreditAccount);                            // Кредит
        rep_cell(exp.DL_DepartmentName(exp.DepartmentID));      // Филиал

        rep_tbl_row_end();

        stat = exp.Next();
    end;

    if (data)
        rep_tbl_end();
    end;

    return data;
END;
//=========================================================

const obj_name = "RvsBankBill";

var factory = RsbObjectFactory();
if (factory == NULL)
    msgbox("can't create RsbObjFactory");
    return;
end;

var bnr = factory.GetObject(obj_name);
if (bnr == NULL)
    msgbox("can't create " + obj_name);
    return;
end;

var rep_date = date(01, 01, 9999);

GetDate(rep_date, "Введите отчётную дату:");

bnr.SetParmValue("EndDate", rep_date);

bnr.AddSortFld("Formula");
bnr.AddSortFld("Series");
bnr.AddSortFld("Number");

rep_start("..\\txtfile\\" + obj_name + "_rep.html", obj_name + " " + string(rep_date));

rep_br("контрольные примеры для RsVox объекта " + obj_name);
rep_br("");

rep_br("выборка на дату " + string(rep_date));
rep_br("");

rep_tbl_start();

rep_hdr("BCID");
rep("<th colspan=2>""Серия/ номер векселя""</th>");
rep_hdr("Сведения о держателе ценной бумаги");
rep_hdr("Дата размещения ценной бумаги");
rep_hdr("Срок погашения");
rep_hdr("Фактическая дата погашения ценной бумаги");
rep_hdr("Плановая дата погашения ценной бумаги");
rep_hdr("Вид дохода");
rep_hdr("Дата истечения срока векселя");
rep_hdr("Код формулировки срока");
rep_hdr("Дата 'не ранее'");
rep_hdr("Дата 'не позднее'");
rep_hdr("Процентная ставка");
rep_hdr("Ставка дисконта");
rep_hdr("Балансовая стоимость ценной бумаги");
rep_hdr("Валюта ЦБ");
rep_hdr("Номер ЛС векселя");
rep_hdr("Дата выдачи");
rep_hdr("Вид договора, по которому выдан вексель");
rep_hdr("Стоимость продажи ценной бумаги");
rep_hdr("Валюта продажи ЦБ");
rep_hdr("Дата выкупа");
rep_hdr("Вид операции, по которой выкуплен вексель");
rep_hdr("Стоимость выкупа");
rep_hdr("Валюта выкупа");
rep_hdr("Контрагент по договору выкупа");
rep_hdr("Сумма процентных выплат с момента размещения до погашения");
rep_hdr("Сумма дисконтных выплат");
rep_hdr("Валюта выплат");
rep_hdr("Сумма процентных выплат с момента размещения до отчётной даты");
rep_hdr("Валюта начисленных %%");
rep_hdr("Номер ЛС начисленных %%");
rep_hdr("BCStatus");
rep_hdr("Филиал");

rep_tbl_hdrend();

var stat = bnr.Next();
var party_name = "-", repay_party_name = "-";
while (stat)

    if (bnr.GiveParty)
        party_name = bnr.GiveParty.FullName;
    else
        party_name = "-";
    end;

    if (bnr.RepayParty)
        repay_party_name = bnr.RepayParty.FullName;
    else
        repay_party_name = "-";
    end;

    rep_tbl_group(bnr.BCID);
    rep_tbl_row_start();

    rep_cell(bnr.BCID);                                 // BCID
    rep_cell(bnr.Series);                               // Серия/ номер векселя
    rep_cell(bnr.Number);
    rep_cell(party_name);                               // Сведения о держателе ценной бумаги
    rep_cell(bnr.Start);                                // Дата размещения ценной бумаги
    rep_cell(bnr.AbsoluteTerm);                         // Срок погашения
    rep_cell(bnr.Closed);                               // Фактическая дата погашения ценной бумаги
    rep_cell(bnr.Maturity);                             // Плановая дата погашения ценной бумаги
    rep_cell(HTMLDecodeFormula(bnr.Formula));           // Вид дохода
    rep_cell(bnr.Expiry);                               // Дата истечения срока векселя
    rep_cell(DecodeValidity(bnr.Validity));             // Код формулировки срока
    rep_cell(bnr.NotEarlier);                           // Дата 'не ранее'
    rep_cell(bnr.NotLater);                             // Дата 'не позднее'
    rep_cell(bnr.Rate);                                 // Процентная ставка
    rep_cell(bnr.DiscountRate);                         // Ставка дисконта
    rep_cell(bnr.Principal);                            // Балансовая стоимость ценной бумаги
    rep_cell(bnr.PrincipalCur);                         // Валюта ЦБ
    rep_cell(bnr.BillAccount);                          // Номер ЛС векселя
    rep_cell(bnr.GiveDate);                             // Дата выдачи
    rep_cell(bnr.GiveOperType);                         // Вид договора, по которому выдан вексель
    rep_cell(bnr.GiveBCCost);                           // Стоимость продажи ценной бумаги
    rep_cell(bnr.GiveCurrency);                         // Валюта продажи ЦБ
    rep_cell(bnr.RepayDate);                            // Дата выкупа
    rep_cell(bnr.RepayOperType);                        // Вид операции, по которой выкуплен вексель
    rep_cell(bnr.RepayBCCost);                          // Стоимость выкупа
    rep_cell(bnr.RepayCurrency);                        // Валюта выкупа
    rep_cell(repay_party_name);                         // Контрагент по договору выкупа
    rep_cell(bnr.Cost);                                 // Сумма процентных выплат с момента размещения до погашения
    rep_cell(bnr.Discount);                             // Сумма дисконтных выплат
    rep_cell(bnr.PrincipalCur);                         // Валюта выплат
    rep_cell(bnr.PCRest);                               // Сумма процентных выплат с момента размещения до отчётной даты
    rep_cell(bnr.PrincipalCur);                         // Валюта начисленных %%
    rep_cell(bnr.PCAccount);                            // Номер ЛС начисленных %%
    rep_cell(bnr.BCStatus);                             // BCStatus
    rep_cell(DL_DepartmentName(bnr.DepartmentID));      // Филиал

    rep_tbl_row_end();

    stat = bnr.Next();
end;

rep_tbl_end();

    stat = bnr.Next();
var op;
while (stat)

    rep_br("держатели векселя " + bnr.Series + " " + bnr.Number + ":");
    PrintHolders(bnr.Holders);
    rep_br("");


    rep_br("уплаченные расходы по векселю " + bnr.Series + " " + bnr.Number + ":");
    PrintExpenses(bnr.Carries);
    rep_br("");

    stat = bnr.Next();
end;

rep_end();
        
