/*ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  RS-Bank 6.0                                          R-Style Software Lab

  File Name   : HTMLRep.mac
  Programmer  : Š áâ¥«¨­ €..
  Comment     : ¢ë¢®¤ ®âçñâ®¢ ¢ HTML
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ*/

IMPORT BankInter;

private file f_rep() txt write;

private var f_name;

PRIVATE CONST
    rep_row_color_1 = "#EDFFFF",
    rep_row_color_2 = "#FFF7F7";

PRIVATE VAR
    group_val   = TArray,
    group_color = rep_row_color_1,
    t_start;

MACRO ToHTMLString(str)
    if (str == NULL)
        return "<font size=-1 color=#888888>Undefined</font>";
    else
        return strsubst(string(str), " ", "&nbsp");
    end;
END;

MACRO rep(str)
    if (valtype(str) == V_UNDEF)
        str = "";
    end;
    insert(f_rep, str);
END;

MACRO rep_br(str)
    rep(string(str) + "<br>");
END;

MACRO rep_hdr(str)
    rep("<th>" + string(str) + "</th>");
END;

MACRO rep_cell(str)
    rep("<td>" + ToHTMLString(str) + "</td>");
END;

MACRO rep_start(file_name, title)
    f_name = file_name;
    open(f_rep, f_name);
    rep("<html><title>" + string(title) + "</title><body bgcolor=#FFFFFF>");

    t_start = time();
END;

MACRO rep_end()
    rep_br("");
    rep_br("<small><i>¢à¥¬ï £¥­¥à æ¨¨ ®âçñâ  " + string(time() - t_start:m)) + "</i></small>";

    rep("</body></html>");
    close(f_rep);
    println("âçñâ ¢ë¢¥¤¥­ ¢ ä ©« " + f_name);
END;

MACRO rep_tbl_start()
    rep("<table border = 0 bgcolor=#777777 cellspacing=1 cellpadding=2><tr bgcolor=#E8E8F8>");
END;

MACRO rep_tbl_hdrend()
    rep("</tr>");
END;

MACRO rep_tbl_group()
var a_gr = TArray,
    v_gr, i = 0, s = 0, eq = false;

    // read params
    while(GetParm(i, v_gr))
        a_gr.size = a_gr.size + 1;
        a_gr[a_gr.size - 1] = v_gr;
        i = i + 1;
    end;

    // compare params
    if (a_gr.size != group_val.size)
        eq = false;
    else
        i = 0;
        s = max(a_gr.size, group_val.size);
        eq = true;

        while ((i < s) and (eq))
            if (a_gr[i] != group_val[i])
                eq = false;
            end;

            i = i + 1;
        end;
    end;

    if (group_val.size == 0)
        group_color = rep_row_color_1;

        group_val = a_gr;
    elif (not eq)
        if (group_color == rep_row_color_1)
            group_color = rep_row_color_2;
        else
            group_color = rep_row_color_1;
        end;

        group_val = a_gr;
    end;

END;

MACRO rep_tbl_regroup()
    group_val.size = 0;
    group_color = rep_row_color_1;
END;

MACRO rep_tbl_row_start()
    rep("<tr bgcolor=" + group_color + ">");
END;

MACRO rep_tbl_row_end()
    rep("</tr>");
END;

MACRO rep_tbl_end()
    rep("</table>");
END;
