/*
$Name:        Broker_fix_alg.mac
$Module:      ПЗО
$Description: Макрос алгоритма фиксированной комиссии
*/
import fiinter, "spserv.mac";
macro GetServicePayValue ( sfcalcalddr, datebegin, dateend, basetype, baseSum, sfcontraddr )
var summa = $250,MINIMUM = $3000, stavka1 = 0.15/*Chesnokov D.S. 512567*/, stavka2 = 0.2, stavka = $0, CurBaseSum = $0;
var Comcode = "", ComVal = 0;


Private Macro GetMaxMaxSum(sfcontr, Begdate, Enddate)

var sql, cmd, rs, MaxSumm = 0, CurMaxSum = 0, sql659, cmd659, rs659, sql57, cmd57, rs57, sqlcom, cmdcom, rscom, month, year;

  DateSplit(EndDate, null, month, year);
  BegDate = Date(1,month,year);
  EndDate = Date(GetDaysInMonth(EndDate),month,year);
   sql  = String( "select distinct con.* from dsfcontrplan_dbt sfplan, dsfconcom_dbt con, dsfcomiss_dbt comiss  where sfplan.t_sfcontrid = ? and sfplan.t_begin <= ?\n" 
                    ,"  and ((sfplan.t_end >= ?) OR ( sfplan.t_end = to_date('01.01.0001','dd.mm.yyyy')) )\n"  
                    ," and con.t_objecttype = 659 and con.t_objectid = sfplan.t_sfcontrid and con.t_commnumber = comiss.t_number\n"  
                    ,"   and comiss.t_feetype = 1 and UPPER(comiss.t_code) = 'БРОКЕРФИКС'\n");
   cmd = Dl_RsdCommand(sql);
   cmd.AddParam(sfcontr.id);
   cmd.AddParam(Enddate);
   cmd.AddParam(Begdate);
   rs = cmd.execute;
   While(rs.movenext)
      CurMaxSum = 0;
      sql659  = String( " select NVL(max(sfcal.t_summax), 0) as summax659 from dsfconcom_dbt con, dsfcalcal_dbt sfcal where con.t_id = ? and sfcal.t_concomid = con.t_id\n");
      cmd659 = Dl_RsdCommand(sql659);
      cmd659.AddParam(rs.t_id);
      rs659 = cmd659.execute;
      While(rs659.movenext)
          If(rs659.summax659 > CurMaxSum)
             CurMaxSum = rs659.summax659;
          end;
      end;// eow2

      If(CurMaxSum  == 0)

         sql57  = String( " select NVL(max(cl.t_summax), 0) summax57 from  dsfconcom_dbt con , dsfcalcal_dbt cl  where  con.t_commnumber = ? and con.t_objecttype = 57 and con.t_objectid = ? and cl.t_concomid = con.t_id and con.t_feetype = 1\n");
         cmd57 = Dl_RsdCommand(sql57);
         cmd57.AddParam(rs.t_commnumber);
         cmd57.AddParam(rs.t_sfplanid);
         rs57 = cmd57.execute;
         While(rs57.movenext)
            If(rs57.summax57 > CurMaxSum)
               CurMaxSum = rs57.summax57;
            end;
         end;//eow3
         If(CurMaxSum  == 0)
            sqlcom  = String( " select t_summax as summaxcom from dsfcalcal_dbt where t_commnumber = ? and t_feetype = 1 and t_concomid = 0\n");
            cmdcom = Dl_RsdCommand(sqlcom);
            cmdcom.AddParam(rs.t_commnumber);
            rscom = cmdcom.execute;
            If(rscom.movenext)
               If(rscom.summaxcom > CurMaxSum)
                  CurMaxSum = rscom.summaxcom;
               end;
            end;

         end;
      end;
      If(CurMaxSum> MaxSumm)
         MaxSumm =  CurMaxSum;
      end;
   end; // eow1
   return MaxSumm;

End;

record sfcontr ("sfcontr.dbt");
record sfcal ("sfcalcal.dbt");
 var sel, rs, cmd;
 var TempComSumVal = $0, TempComSumRur = $0, OneCente = $0;
 var Summ = $0, MaxComSum = $0;
 setbuff(sfcontr, sfcontraddr);
 setbuff(sfcal, sfcalcalddr);
 CurBaseSum = baseSum;
 
 MaxComSum = GetMaxMaxSum(sfcontr, datebegin, dateend);
 If(MaxComSum == 0)
    MaxComSum = sfcal.SumMax;
 end;

 if(MaxComSum < CurBaseSum/*baseSum*/)
   summa = $0;
 else
   Summa = MaxComSum - CurBaseSum/*baseSum*/;
 end; 
 if(sfcal.commnumber != 0)
 return money( summa );
 end;
END;
