/* Макрос с объявленными переменными
   для исключения проблем с переопределением */

IMPORT deprintr;
import lgs;

var {cNum};


macro _GetIniString(ИмяПараметра, ДобавитьРазделитель)
   file ff (".\\sbbank.ini") txt;
   var ТекСтр, ТекПарам, ПозРазделителя, Результат;

   if (ДобавитьРазделитель == Null)  	ДобавитьРазделитель = True; 	end;

   while (next(ff))
      ТекСтр = ff.str;
      ПозРазделителя = index(ТекСтр, "=");
      if (ПозРазделителя > 0)
         ТекПарам = Trim( SubStr(ТекСтр, 1, ПозРазделителя - 1) );
         if (ТекПарам == ИмяПараметра)
            Результат = trim( SubStr(ТекСтр, ПозРазделителя + 1) );
            if ((ДобавитьРазделитель) and 
                (index(Результат, "\\") != 0) and 
                (index(Результат, "*") == 0)
               )
               Результат = Результат + "\\";
            end;
            Return(Результат)
         end;
      end;
   end;
   Return "";
end; 


macro _AddIniString(ИмяПараметра, ЗначениеПараметра)
   file ff (".\\sbbank.ini") txt write;
   SetDelim("="); /*Разделитель полей*/

   while (next(ff))
      if (trim(ff(0)) == ИмяПараметра)
         /*MsgBox("Параметр " + ИмяПараметра + " уже существует: " + trim(ff(1)));*/
         Return False;
      end;
   end;

   SetDelim("");
   insert(ff, " ");
   insert(ff, " " + ИмяПараметра + " = " + ЗначениеПараметра + ";");
   Close(ff);

   Return True;
end;

