import          InsCarryDoc, payinter;

record          BasePmPaym(  pmpaym );
record          ContrPmPaym( pmpaym );

/*------------------------------------------------------------------------------------\
|               Списание валюты для обратной продажи                                  |
|                                                                                     |
\------------------------------------------------------------------------------------*/


macro   ExecuteStep( doc, order )
/*
        record          bo(ps_bcord);
        record          d (arhdoc);

        Var             Account_Cur;

        SetBuff( bo, order );
        SetBuff( d, doc );


        /*      Проверить лицевой счет, на который будет зачисляться валюта  */
        if ( CheckAccount( 
                        214,                    /* Тип счета */
                        Account_Cur,            /* В случае успеха, сюда вернется номер счета*/
                        BasePmPaym.FIID,        /* Код валюты */
                        1                       /* Глава */
                        )  !=  0 )
                return  1;
        end;


        /*
                Обратное списание валютных средств клиента
        */
        ClearRecord(d);
        
        d.Chapter = 1;
        d.Code_Currency = BasePmPaym.FIID;
        d.Account_Payer = BasePmPaym.PayerAccount;
        d.Account_Receiver = Account_Cur;
        d.Result_Carry = 1;

        d.Kind_Oper = " 1";
        d.Shifr_Oper = "09";

        d.Sum = BasePmPaym.Amount;

        d.Date_Carry       = {curdate};

        d.Ground = "Заявка на конвертацию валюты № " + String( bo.Number ) + ". Обратное списание валюты.";


        if ( d.Code_Currency == 0 )
                if( not InsertRubDocument())
                   msgbox("Ошибка при вставке рублевого документа");
                   return 1;
                end;
        else
                if( not InsertCurDocument())
                   msgbox("Ошибка при вставке валютного документа");
                   return 1;
                end;
                   
        end;

    */
        return 0;

end;