/************************************************************************/
/*         Автоматизированная банковская система RS-Bank v5.1           */
/*                 Copyright (c) R-Style Software Lab 1998              */
/*  Имя файла        : pssfcary.mac                                     */
/*  Описание         : Проводка рублевого платежа-оплаты ПЗО            */
/*  Программист      : Алешин А.В.                                      */
/*  Создан           : 14.11.02                                         */
/************************************************************************/

import InsCarryDoc,  PaymInter, "sfinsdoc.mac";
import paym_rec; /* Pm_paym, Pm_rmprop, Pm_debet, Pm_credit */

RECORD  Ps_payord( pspayord );
RECORD  Ps_paydem( pspaydem ); /* параметры требования */

RECORD  d(arhdoc);

/* Выполнение шага */
macro ExecuteStep( doc, payorder, DocKind )

  setbuff( Ps_payord, payorder );
  setbuff( d, doc );

  if(ВставитьПлатуЗаОбслуживание(Pm_paym, doc, Pm_rmprop.Number, Pm_paym.ValueDate, Pm_paym.Department, Pm_paym.NumberPack) ) 
    return 1; 
  end;

  /* Изменяем статус платежа на Закрыт */
  if( not InsertPaymentStat( Pm_Paym.PaymentID, PM_FINISHED ) )
    msgbox( "Ошибка при обновлении статуса платежа" );
    return 1;
  end;

  return 0;
end;
