/* -------------------------------------------------------------------- */
/*         Автоматизированная банковская система RS-Bank v6.0           */
/*                 Copyright (c) R-Style Software Lab                   */
/*                                                                      */
/*  Имя файла  : rqchcs.mac                                             */
/*                                                                      */
/*  Описание   : Операция - 3035 - "Закрытие лицевого счета"            */
/*               Шаг      - 20   - "Закрывать дополнительные счета?"    */
/*                                                                      */
/*  Программист: Андреева Е.П.                                          */
/*                                                                      */
/*  Создан     : 11.11.2004                                             */
/*                                                                      */
/* -------------------------------------------------------------------- */
import reqinter, PSInter, BankInter;

var ReqCloseAccObj:RsbReqCloseAcc;

/* Выполнение шага */
MACRO ExecuteCaseStep( Kind_Operation, Number_Step )

  var NumStep:integer = 0;
  array Text;
  array Buttons;
  if ( ReqCloseAccObj.AccCloseDate > {curdate} )
    Text(0) = string("Дата закрытия счета ", ReqCloseAccObj.AccCloseDate, " еще не наступила. Закрыть счет текущим операционным днем?");
    Buttons(0) = "Текущим опер. днем";
    Buttons(1) = "Прервать";
    var stat = ConfWin(Text, Buttons, 1);
    if (stat == 1)
      return 1;
    end;
    ReqCloseAccObj.AccCloseDate = {curdate};
    var sc = TBFile("sfcontr", "W", 1);
    sc.Clear();
    sc.rec.ObjectType = SF_ACCOUNT;
    sc.rec.FIID = ReqCloseAccObj.Code_Currency;
    sc.rec.Object = ReqCloseAccObj.Account;
    sc.rec.ServKind = PTSK_PAY;
    if (sc.GetEQ())
      sc.rec.DateClose = {curdate};
      sc.Update();
    end;
  end;

  var accbuf = GetAccount( 1, ReqCloseAccObj.Account, ReqCloseAccObj.Code_Currency );

  if( 
      ( ReqCloseAccObj.Code_Currency == NATCUR ) or 
      ( Req_IsCliringFIID( ReqCloseAccObj.Code_Currency ) ) or 
      ( not ( Index( accbuf.rec.Type_Account, "X" ) ) ) 
    )
    NumStep = 50;
  else
    NumStep = 30;
  end;

  return string( NumStep );

END;
