/************************************************************************/
/*         Автоматизированная банковская система RS-Bank                */
/*                 Copyright (c) R-Style Software Lab 2002              */
/*                                                                      */
/*  Имя файла      : rqchngfss.mac                                      */
/*                                                                      */
/*  Описание       : Печать сообщений об изменении номера счета в ФСС   */
/*                                                                      */
/*  Программист    : Popova O.                                          */
/*                                                                      */
/*  Создан         : 11.03.10                                           */
/*                                                                      */
/************************************************************************/

IMPORT "BnkTemplReport.mac";
import rqmeslib;

MACRO ЗаполнитьДанныеСообщенияОбИзмененииФСС( chnga, wlmes )

  var stat:integer = ЗаполнитьДанныеРегистрацииБанкаФСС();
  //if( stat == 0 )
    stat = ЗаполнитьДанныеСообщенияОбИзменении( chnga, wlmes );
  //end;
  ЗаполнитьКодНалоговогоОргана();

  return stat;

END;

class (BnkTemplReport)ReqChangeFSSReport(p_chnga, p_wlmes)
  var chnga = p_chnga, wlmes = p_wlmes;

  MACRO Create()
    
     ОчиститьФормуСообщения();
     ЗаполнитьДанныеСообщенияОбИзмененииФСС( chnga, wlmes );

     SetValuesMultiCell( "SeriesAndNum_1" , SeriesAndNum       ,3 , 20 ,
                         "NOCode_1"       , CodeGNI            ,3 ,  4 ,
                         "IndexFSS_1"     , IndexFSS           ,3 ,  6 ,
                         "BankIndex_1"    , BankIndex          ,3 ,  6 ,    
                         "BankRegNom_1"   , BankRegNom         ,3 ,  4 ,  
                         "BankNumber_1"   , BankNumber         ,3 ,  4 ,  
                         "BankBIC_1"      , BankBIC            ,3 ,  9 ,
                         "BankINN_1"      , BankINN            ,3 , 12 ,   
                         "BankKPP_1"      , BankKPP            ,3 ,  9 ,    
                         "BankOGRN_1"     , BankOGRN           ,3 , 13 ,    
                         "ReqAccountOld_1", ReqAccountOld      ,3 , 20 ,
                         "DogAccNumber_1" , DogAccNumber       ,3 , 20 ,  
                         "ClientINN_1"    , ClientINN          ,3 , 12 ,
                         "ClientKPP_1"    , ClientKPP          ,3 ,  9 ,
                         "ClientOGRN_1"   , ClientOGRN         ,3 , 15 ,
                         "NatCurAcc_1"    , NatCurAcc          ,3 ,  1 ,           
                         "ValCurAcc_1"    , ValCurAcc          ,3 ,  1 ,            
                         "ReqAccount_1"   , ReqAccount         ,3 , 20 ,
                         "ChngAccDateD_1" , ChngAccDateD       ,3 ,  2 , 
                         "ChngAccDateM_1" , ChngAccDateM       ,3 ,  2 ,             
                         "ChngAccDateY_1" , ChngAccDateY       ,3 ,  4 , 
                         "BankIndex_2"    , ""                 ,3 ,  6 ,    
                         "BankRegNom_2"   , ""                 ,3 ,  4 ,  
                         "BankNumber_2"   , ""                 ,3 ,  4 ,  
                         "BankBIC_2"      , ""                 ,3 ,  9 ,
                         "BankINN_2"      , ""                 ,3 , 12 ,   
                         "BankKPP_2"      , ""                 ,3 ,  9 ,    
                         "BankOGRN_2"     , ""                 ,3 , 13 ,    
                         "DBank_1"        , ""                 ,3 ,  2 ,
                         "MBank_1"        , ""                 ,3 ,  2 ,
                         "YBank_1"        , ""                 ,3 ,  4 ,
                         "OpClAccDateD_1" , ChngAccDateD       ,3 ,  2 ,
                         "OpClAccDateM_1" , ChngAccDateM       ,3 ,  2 ,
                         "OpClAccDateY_1" , ChngAccDateY       ,3 ,  4 ,
                         "Phone_1"        , Phone              ,3 , 20 ,      
                         "SeriesAndNum_2" , SeriesAndNum       ,3 , 20 ,        
                         "NOCode_2"       , CodeGNI            ,3 ,  4 ,
                         "OutSideDateD_1" , OutSideDateD       ,3 ,  2 ,       
                         "OutSideDateM_1" , OutSideDateM       ,3 ,  2 ,       
                         "OutSideDateY_1" , OutSideDateY       ,3 ,  4 ,       
                         "ReqAccountOld_2", ReqAccountOld      ,3 , 20 ,
                         "DogAccNumber_2" , DogAccNumber       ,3 , 20 ,
                         "ClientINN_2"    , ClientINN          ,3 , 12 ,
                         "ClientKPP_2"    , ClientKPP          ,3 ,  9 ,
                         "ClientOGRN_2"   , ClientOGRN         ,3 , 15 ,
                         "NatCurAcc_2"    , NatCurAcc          ,3 ,  1 ,
                         "ValCurAcc_2"    , ValCurAcc          ,3 ,  1 ,
                         "OpClAccDateD_2" , ChngAccDateD       ,3 ,  2 ,           
                         "OpClAccDateM_2" , ChngAccDateM       ,3 ,  2 ,        
                         "OpClAccDateY_2" , ChngAccDateY       ,3 ,  4 ,        
                         "Phone_2"        , Phone              ,3 , 20 
                       );             

    
    SetValues( "NameFSS"     , NameFSS    ,
               "AdressFSS"   , AdressFSS  ,
               "BankName_1"  , BankName   ,       
               "BankAdress_1", BankAdress ,
               "ClientName_1", ClientName ,
               "KindAcc_1"   , KindAcc    ,                     
               "BankName_2"  , ""         ,                         
               "BankAdress_2", ""         ,
               "PostBank_1"  , PostBank   ,
               "FIOBank_1"   , FIOBank    ,
               "NameFSS_2"   , NameFSS    , 
               "ClientName_2", ClientName ,
               "KindAcc_2"   , KindAcc    ,                 
               "PostBank_2"  , PostBank   ,             
               "FIOBank_2"   , FIOBank
             );
  end;
  
  initBnkTemplReport("ReqChangeFSS.xls");
end;


MACRO PrintChangeAccFSS( chnga, wlmes )
  return ReqChangeFSSReport(chnga, wlmes).Print();
END;
