/* ╔══════════════════════════════════════════════════════════════════╗ */
/*         Автоматизированная банковская система RS-Bank v5.0           */
/*                 Copyright (c) R-Style Software Lab 1998              */
/*                                                                      */
/*  Имя файла        : sfinsdoc.mac                                     */
/*                                                                      */
/*  Описание         : Выполнение шага по                               */
/*                     оплате картотеки №2, если документ является      */
/*                     платой за обслуживание                           */
/*                     Макрос является следствием SCR 47205             */
/*                     Эта решение - временное, до той поры, пока       */
/*                     RSPAYMENT не научится работать с еще             */
/*                     невставленными платежами                         */
/*                                                                      */
/*  Программист      : Дудин В.А.                                       */
/*                                                                      */
/*  Создан           : 30.04.2004                                       */
/*                                                                      */
/* ╚══════════════════════════════════════════════════════════════════╝ */
import BankInter, sfinsdoc, "paym_rec.mac";

RECORD  PartPmpaym(   pmpaym );     /* ─┐                                                               */
RECORD  PartDebet (   pmprop );     /*  ├─ параметры платежного документа частичной оплаты картотеки №2 */
RECORD  PartCredit(   pmprop );     /*  │                                                               */
RECORD  PartPmrmprop( pmrmprop );   /* ─┘                                                               */

MACRO ExecuteStep( doc, payorder )

private RECORD pspayord( pspayord );
setbuff(pspayord,payorder);

  if(pspayord.Origin == PSPO_OR_SF)
     if(ВставитьПлатуЗаОбслуживание(PartPmpaym, doc, PartPmrmprop.Number,
                                    PartPmpaym.ValueDate, PartPmpaym.Department, PartPmpaym.NumberPack))
        return 1;
     end;
  end;
  return 0;
END;