/*
 $Name:        F345KlikoExportController.mac
 $Module:      Регламентируемая отчетность
 $Description: Форма 345. Контроллер экспорта в kliko.exe
*/

/* ──────────────────────────────────────────────────────────────────────────┐
   RS-Bank V6                                                 R-Style Softlab
   Файл подсистемы "Регламентированная отчетность"

   Форма 345. Контроллер экспорта в kliko.exe.

   CREATED : 20.11.12 Gor.
└────────────────────────────────────────────────────────────────────────── */

class (TRcbKlikoView) F345KlikoView(fileExtension : String, reportDate : Date)

    private macro constructorT345PartKlikoView(fileExtension, reportDate)

        initTRcbKlikoView(fileExtension, reportDate);

        var day;
        var month;
        var year;

        dateSplit(m_reportDate + 1, day, month, year);

        m_name = получитьКаталогЭкспорта() + "\\" + strLpad(String(day),   2, "0")
                                                  + strLpad(String(month), 2, "0")
                                                  + String(year)
                                                  + "Kliko"
                                                  + "." + m_fileExtension;
    end;

    constructorT345PartKlikoView(fileExtension, reportDate);
end;

class (RcbKlikoExportController) F345KlikoExportController()
    initRcbKlikoExportController("345", objectFactoryInstance.createReport(RcbApplication.currentReport));

    private macro getDescriptorInfo()
        return "";
    end;

    private macro dateDecor(_date : Date) : String
        var dd, mm, yy;
        var dateDecor : String = "";

        DateSplit(_date, dd, mm, yy);

        if (dd < 10)
           dateDecor = "0" + String(dd);
        else
           dateDecor = String(dd);
        end;
        if (mm < 10)
           dateDecor = dateDecor + "." + "0" + String(mm);
        else
           dateDecor = dateDecor + "." + String(mm);
        end;

        dateDecor = dateDecor + "." + String(yy);

        return dateDecor;
    end;

    private macro printPart(partCode : String)
        var part, value, i, tableVal;
        var currentDay : Date = global.getRcbPeriod().beginDate;
        var dataPool = TArray();

        m_view.printHead(partCode);

        if (partCode == "F345")
            part = m_report.getPart("ОсновнойРаздел");

            while (currentDay <= global.getRcbPeriod().endDate + 1)
                dataPool = TArray();
                dataPool[dataPool.size] = dateDecor(currentDay);

                //собираем строку из граф за дату currentDay
                for (i, i=2, i=global.getPart1TotalsColumnNumber(), 1)
                    value = nvl(part.getAttribute(string(i)).getScaledValue(Date(currentDay)), 0);
                    dataPool[dataPool.size] = String(Int(value));
                end;

                m_view.printRow(dataPool);
                currentDay = currentDay + 1;
            end;
        elif(partCode == "F345_SPRAV")
            part = m_report.getPart("Справочно");

            for (i, i=1, i=global.getSpravPartLineCount(), 1)
                dataPool = TArray();
                tableVal = part.getAttribute("Sprav").getScaledValue(string(i));

                m_view.printRow(String(nvl(tableVal.cnt_account, 0)), String(Int(nvl(tableVal.value, 0))));
            end;
        end;
    end;

    macro createView()
         return F345KlikoView(m_fileExtension, m_report.getPeriod().endDate);
    end;

    private macro printDataZone()
        m_view.setOutputFile();

        printPart("F345");
        printPart("F345_SPRAV");

        m_view.resetOutputFile();
    end;
end;

class (F345KlikoExportController) F345KlikoExportController_3468()
    initF345KlikoExportController();

    private macro getDescriptorInfo()
        return "";
    end;

    private macro printPart(partCode : String)
        var part, value, i, tableVal;
        var currentDay : Date = global.getRcbPeriod().beginDate;
        var dataPool = TArray();

        m_view.printHead(partCode);

        if (partCode == "F345")
            part = m_report.getPart("ОсновнойРаздел");

            while (currentDay <= global.getRcbPeriod().endDate + 1)
                dataPool = TArray();
                dataPool[dataPool.size] = dateDecor(currentDay);

                //собираем строку из граф за дату currentDay
                for (i, i=2, i=global.getPart1TotalsColumnNumber(), 1)
                    value = nvl(part.getAttribute(string(i)).getScaledValue(Date(currentDay)), 0);
                    dataPool[dataPool.size] = String(Int(value));
                end;

                m_view.printRow(dataPool);
                currentDay = currentDay + 1;
            end;
        elif(partCode == "F345_SPRAV")
            part = m_report.getPart("Справочно");

            for (i, i=1, i=10, 1)
                dataPool = TArray();
                tableVal = part.getAttribute("Sprav").getScaledValue(string(i));

                m_view.printRow(String(nvl(tableVal.cnt_account, 0)), String(Int(nvl(tableVal.value, 0))));
            end;
        end;
    end;
end;

class (F345KlikoExportController) F345KlikoExportController_3564()
    initF345KlikoExportController();

    private macro getDescriptorInfo()
        return "F345_15.PAK от 25.03.2015";
    end;

    private macro printPart(partCode : String)
        var part, value, i, tableVal, tableValGk;
        var currentDay : Date = global.getRcbPeriod().beginDate;
        var dataPool = TArray();

        m_view.printHead(partCode);

        if (partCode == "F345")
            part = m_report.getPart("ОсновнойРаздел");

            while (currentDay <= global.getRcbPeriod().endDate + 1)
                dataPool = TArray();
                dataPool[dataPool.size] = dateDecor(currentDay);

                //собираем строку из граф за дату currentDay
                for (i, i=2, i=global.getPart1TotalsColumnNumber(), 1)
                    value = nvl(part.getAttribute(string(i)).getScaledValue(Date(currentDay)), 0);
                    dataPool[dataPool.size] = String(Int(value));
                end;

                m_view.printRow(dataPool);
                currentDay = currentDay + 1;
            end;
        elif(partCode == "F345_SPRAV")
            part = m_report.getPart("Справочно");

            for (i, i = 1, i = 9, 1)
                dataPool = TArray();
                tableVal = part.getAttribute("Sprav").getScaledValue(string(i));
                tableValGk = part.getAttribute("Sprav").getScaledValue(string(i) + "_ГК");

                m_view.printRow(String(int(nvl(tableVal.cnt_account, 0))), String(int(nvl(tableValGk.cnt_account, 0))), String(Int(nvl(tableVal.value, 0))), String(Int(nvl(tableValGk.value, 0))));
            end;
        end;
    end;
end;

class (F345KlikoExportController) F345KlikoExportController_Т1_30_1_01_3573()
    initF345KlikoExportController();

    private macro getDescriptorInfo()
        return "F345_17.PAK от 14.01.2016";
    end;

    private macro printPart(partCode : String)
        var part, value, i, tableVal, tableValGk;
        var currentDay : Date = global.getRcbPeriod().beginDate;
        var dataPool = TArray();

        m_view.printHead(partCode);

        if (partCode == "F345")
            part = m_report.getPart("ОсновнойРаздел");

            while (currentDay <= global.getRcbPeriod().endDate + 1)
                dataPool = TArray();
                dataPool[dataPool.size] = dateDecor(currentDay);

                //собираем строку из граф за дату currentDay
                for (i, i = 2, i = global.getPart1TotalsColumnNumber(), 1)
                    value = nvl(part.getAttribute(string(i)).getScaledValue(Date(currentDay)), 0);
                    dataPool[dataPool.size] = String(Int(value));
                end;

                m_view.printRow(dataPool);
                currentDay = currentDay + 1;
            end;
        elif(partCode == "F345_SPRAV")
            part = m_report.getPart("Справочно");

            for (i, i = 1, i = 9, 1)
                dataPool = TArray();
                tableVal = part.getAttribute("Sprav").getScaledValue(string(i));
                tableValGk = part.getAttribute("Sprav").getScaledValue(string(i) + "_ГК");

                m_view.printRow(i, String(int(nvl(tableVal.cnt_account, 0))), String(int(nvl(tableValGk.cnt_account, 0))), String(Int(nvl(tableVal.value, 0))), String(Int(nvl(tableValGk.value, 0))));
            end;
        end;
    end;
end;

class (F345KlikoExportController_Т1_30_1_01_3573) F345KlikoExportController_364FZ()
    initF345KlikoExportController_Т1_30_1_01_3573();

    private macro getDescriptorInfo()
        return "f345_18.pak от 26.07.2016";
    end;
end;

class (F345KlikoExportController_364FZ) F345KlikoExportController_4212()
    initF345KlikoExportController_364FZ();

    private macro printPart(partCode : String)
        var part, value, i, tableVal, tableValGk;
        var currentDay : Date = global.getRcbPeriod().beginDate;
        var dataPool = TArray();

        m_view.printHead(partCode);

        if (partCode == "F345")
            part = m_report.getPart("ОсновнойРаздел");

            while (currentDay <= global.getRcbPeriod().endDate)
                dataPool = TArray();
                dataPool[dataPool.size] = dateDecor(currentDay);

                //собираем строку из граф за дату currentDay
                for (i, i = 2, i = global.getPart1TotalsColumnNumber(), 1)
                    value = nvl(part.getAttribute(string(i)).getScaledValue(Date(currentDay)), 0);
                    dataPool[dataPool.size] = String(Int(value));
                end;

                m_view.printRow(dataPool);
                currentDay = currentDay + 1;
            end;
        elif(partCode == "F345_SPRAV")
            part = m_report.getPart("Справочно");

            for (i, i = 1, i = 9, 1)
                dataPool = TArray();
                tableVal = part.getAttribute("Sprav").getScaledValue(string(i));
                tableValGk = part.getAttribute("Sprav").getScaledValue(string(i) + "_ГК");

                m_view.printRow(i, String(int(nvl(tableVal.cnt_account, 0))), String(int(nvl(tableValGk.cnt_account, 0))), String(Int(nvl(tableVal.value, 0))), String(Int(nvl(tableValGk.value, 0))));
            end;
        end;
    end;
end;