--Добавление настройки с классами для Квика
DECLARE
  v_ID       NUMBER := 0;
  v_ParentID NUMBER := 0;
BEGIN
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = (SELECT T_KEYID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('БРОКЕРСКОЕ ОБСЛУЖИВАНИЕ'))  AND LOWER(T_NAME) = LOWER('QUIK');

  IF(v_ParentId <> 0) THEN 
    INSERT INTO DREGPARM_DBT (T_KEYID,T_PARENTID,T_NAME,T_TYPE,T_GLOBAL,T_DESCRIPTION,T_SECURITY,T_ISBRANCH,T_TEMPLATE)
                      VALUES (0,v_ParentID,'CLASSES',2,'X','Классы с правами пользователей терминала',CHR(0),CHR(0),CHR(1)) returning T_KEYID INTO v_ID;

    INSERT INTO DREGVAL_DBT (T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX)
                     VALUES (v_ID,0,0,CHR(0),0,0,0,to_blob(utl_raw.cast_to_raw(
                     'EQDB, EQEO, EQEU, EQGO, EQOB, EQTD, EQTU, EQYO, TQBD, TQBE, TQBR, TQCB, TQDD, TQDE, TQIF, TQOB, TQOD, TQTD, TQTE, TQTF, TQIR, TQOE, TQPI, TQOY, TQIY, CETS_SU')));
  END IF;

EXCEPTION 
  WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/