DECLARE
  V_NEW_FIID NUMBER(10) := 0;
  V_CNT NUMBER(5) := 0;
BEGIN
  SELECT MAX(T_FIID) INTO V_NEW_FIID FROM DFININSTR_DBT;

  SELECT COUNT(1) INTO V_CNT FROM DFININSTR_DBT WHERE T_FI_CODE = '032';
  IF V_CNT = 0 THEN
    V_NEW_FIID := V_NEW_FIID + 1;
    INSERT INTO DFININSTR_DBT 
      (T_FIID, T_FI_CODE, T_FI_KIND, T_AVOIRKIND, T_NAME, T_DEFINITION, 
       T_CODEINACCOUNT, T_ISO_NUMBER, T_CCY, T_ISSUER, T_ISSUED, T_SETTLEMENT_CODE, 
       T_FACEVALUEFI, T_FACEVALUE, T_PARENTFI, T_DRAWINGDATE, T_EXPIRYDATE, T_ISCLOSED, 
       T_USERFIELD1, T_USERFIELD2, T_USERFIELD3, T_USERFIELD4, T_ISINVERSE, T_SCALE, 
       T_POINT, T_ISSYS, T_ISADDITIONAL, T_MAINFIID, T_SUMPRECISION, T_ISGENERALIZED, 
       T_GENERALIZEDFIID, T_RESERVE, T_DURATION, T_TYPEDURATION, T_VERSION, T_DATESETTLEMENT, T_EARLYSETTLEMENT
      )
    VALUES 
      (V_NEW_FIID, '032', 1, 0, 'Аргентинское песо', CHR(1), 
       '032', '032', 'ARS', -1, TO_DATE('01.01.0001','DD.MM.YYYY'), 0, 
       0, 0, 0, TO_DATE('01.01.0001','DD.MM.YYYY'), TO_DATE('01.01.0001','DD.MM.YYYY'), CHR(0),
       CHR(1), CHR(1), CHR(1), CHR(1), CHR(0), 0,
       0, CHR(0), CHR(0), -1, 2, CHR(0),
       -1, CHR(1), 0, 0, 0, 0, CHR(0)
      );
  END IF;

  SELECT COUNT(1) INTO V_CNT FROM DFININSTR_DBT WHERE T_FI_CODE = '901';
  IF V_CNT = 0 THEN  
    V_NEW_FIID := V_NEW_FIID + 1; 
    INSERT INTO DFININSTR_DBT 
      (T_FIID, T_FI_CODE, T_FI_KIND, T_AVOIRKIND, T_NAME, T_DEFINITION, 
       T_CODEINACCOUNT, T_ISO_NUMBER, T_CCY, T_ISSUER, T_ISSUED, T_SETTLEMENT_CODE, 
       T_FACEVALUEFI, T_FACEVALUE, T_PARENTFI, T_DRAWINGDATE, T_EXPIRYDATE, T_ISCLOSED, 
       T_USERFIELD1, T_USERFIELD2, T_USERFIELD3, T_USERFIELD4, T_ISINVERSE, T_SCALE, 
       T_POINT, T_ISSYS, T_ISADDITIONAL, T_MAINFIID, T_SUMPRECISION, T_ISGENERALIZED, 
       T_GENERALIZEDFIID, T_RESERVE, T_DURATION, T_TYPEDURATION, T_VERSION, T_DATESETTLEMENT, T_EARLYSETTLEMENT
      )
    VALUES 
      (V_NEW_FIID, '901', 1, 0, 'Новый тайваньский доллар', CHR(1), 
       '901', '901', 'TWD', -1, TO_DATE('01.01.0001','DD.MM.YYYY'), 0, 
       0, 0, 0, TO_DATE('01.01.0001','DD.MM.YYYY'), TO_DATE('01.01.0001','DD.MM.YYYY'), CHR(0),
       CHR(1), CHR(1), CHR(1), CHR(1), CHR(0), 0,
       0, CHR(0), CHR(0), -1, 2, CHR(0),
       -1, CHR(1), 0, 0, 0, 0, CHR(0)
      ); 
  END IF; 

  SELECT COUNT(1) INTO V_CNT FROM DFININSTR_DBT WHERE T_FI_CODE = '410';
  IF V_CNT = 0 THEN      
    V_NEW_FIID := V_NEW_FIID + 1; 
    INSERT INTO DFININSTR_DBT 
      (T_FIID, T_FI_CODE, T_FI_KIND, T_AVOIRKIND, T_NAME, T_DEFINITION, 
       T_CODEINACCOUNT, T_ISO_NUMBER, T_CCY, T_ISSUER, T_ISSUED, T_SETTLEMENT_CODE, 
       T_FACEVALUEFI, T_FACEVALUE, T_PARENTFI, T_DRAWINGDATE, T_EXPIRYDATE, T_ISCLOSED, 
       T_USERFIELD1, T_USERFIELD2, T_USERFIELD3, T_USERFIELD4, T_ISINVERSE, T_SCALE, 
       T_POINT, T_ISSYS, T_ISADDITIONAL, T_MAINFIID, T_SUMPRECISION, T_ISGENERALIZED, 
       T_GENERALIZEDFIID, T_RESERVE, T_DURATION, T_TYPEDURATION, T_VERSION, T_DATESETTLEMENT, T_EARLYSETTLEMENT
      )
    VALUES 
      (V_NEW_FIID, '410', 1, 0, 'Вона', CHR(1), 
       '410', '410', 'KRW', -1, TO_DATE('01.01.0001','DD.MM.YYYY'), 0, 
       0, 0, 0, TO_DATE('01.01.0001','DD.MM.YYYY'), TO_DATE('01.01.0001','DD.MM.YYYY'), CHR(0),
       CHR(1), CHR(1), CHR(1), CHR(1), CHR(0), 0,
       0, CHR(0), CHR(0), -1, 2, CHR(0),
       -1, CHR(1), 0, 0, 0, 0, CHR(0)
      );
  END IF;

  SELECT COUNT(1) INTO V_CNT FROM DFININSTR_DBT WHERE T_FI_CODE = '152';
  IF V_CNT = 0 THEN    
    V_NEW_FIID := V_NEW_FIID + 1; 
    INSERT INTO DFININSTR_DBT 
      (T_FIID, T_FI_CODE, T_FI_KIND, T_AVOIRKIND, T_NAME, T_DEFINITION, 
       T_CODEINACCOUNT, T_ISO_NUMBER, T_CCY, T_ISSUER, T_ISSUED, T_SETTLEMENT_CODE, 
       T_FACEVALUEFI, T_FACEVALUE, T_PARENTFI, T_DRAWINGDATE, T_EXPIRYDATE, T_ISCLOSED, 
       T_USERFIELD1, T_USERFIELD2, T_USERFIELD3, T_USERFIELD4, T_ISINVERSE, T_SCALE, 
       T_POINT, T_ISSYS, T_ISADDITIONAL, T_MAINFIID, T_SUMPRECISION, T_ISGENERALIZED, 
       T_GENERALIZEDFIID, T_RESERVE, T_DURATION, T_TYPEDURATION, T_VERSION, T_DATESETTLEMENT, T_EARLYSETTLEMENT
      )
    VALUES 
      (V_NEW_FIID, '152', 1, 0, 'Чилийское песо', CHR(1), 
       '152', '152', 'CLP', -1, TO_DATE('01.01.0001','DD.MM.YYYY'), 0, 
       0, 0, 0, TO_DATE('01.01.0001','DD.MM.YYYY'), TO_DATE('01.01.0001','DD.MM.YYYY'), CHR(0),
       CHR(1), CHR(1), CHR(1), CHR(1), CHR(0), 0,
       0, CHR(0), CHR(0), -1, 2, CHR(0),
       -1, CHR(1), 0, 0, 0, 0, CHR(0)
      );
  END IF;
EXCEPTION
  WHEN OTHERS THEN it_log.log('Ошибка создания финансового инструмента');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/