-- Таблица "DDLCONTRSERV_DBT"
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DDLCONTRSERV_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DDLCONTRSERV_DBT (
    T_ID NUMBER(10) DEFAULT 0
  , T_DLCONTRID NUMBER(10) DEFAULT 0
  , T_SERVKIND NUMBER(5) DEFAULT 0
  , T_BEGINDATE DATE DEFAULT TO_DATE(''01.01.0001'', ''MM.DD.YYYY'')                
  , T_BEGINMEMO VARCHAR2(50) DEFAULT CHR(1)
  , T_ENDDATE DATE DEFAULT TO_DATE(''01.01.0001'', ''MM.DD.YYYY'')
  , T_ENDMEMO VARCHAR2(50) DEFAULT CHR(1)
  , T_UPDATEDATE DATE DEFAULT TO_DATE(''01.01.0001'', ''MM.DD.YYYY'')
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DDLCONTRSERV_DBT IS 'Подключенные услуги ДБО'/
COMMENT ON COLUMN DDLCONTRSERV_DBT.T_ID IS 'Идентификатор записи'/
COMMENT ON COLUMN DDLCONTRSERV_DBT.T_DLCONTRID IS 'Идентификатор ДБО'/
COMMENT ON COLUMN DDLCONTRSERV_DBT.T_SERVKIND IS 'Вид услуги из справочника "Виды услуг ДБО"'/
COMMENT ON COLUMN DDLCONTRSERV_DBT.T_BEGINDATE IS 'Дата подключения услуги'/
COMMENT ON COLUMN DDLCONTRSERV_DBT.T_BEGINMEMO IS 'Номер служебной записки на подключение услуги'/
COMMENT ON COLUMN DDLCONTRSERV_DBT.T_ENDDATE IS 'Дата отключения услуги'/
COMMENT ON COLUMN DDLCONTRSERV_DBT.T_ENDMEMO IS 'Номер служебной записки на отключение услуги'/
COMMENT ON COLUMN DDLCONTRSERV_DBT.T_UPDATEDATE IS 'Дата последнего обновления записи'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDLCONTRSERV_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DDLCONTRSERV_DBT_IDX0 ON DDLCONTRSERV_DBT (
   T_ID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDLCONTRSERV_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DDLCONTRSERV_DBT_IDX1 ON DDLCONTRSERV_DBT (
   T_DLCONTRID ASC
  ,T_SERVKIND ASC
  ,T_BEGINDATE ASC
  ,T_ENDDATE ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDLCONTRSERV_DBT_IDX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DDLCONTRSERV_DBT_IDX2 ON DDLCONTRSERV_DBT (
   T_DLCONTRID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE DDLCONTRSERV_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER DDLCONTRSERV_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDLCONTRSERV_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDLCONTRSERV_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER(''DDLCONTRSERV_DBT_SEQ'');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER DDLCONTRSERV_DBT_UPDATEDATE
  BEFORE INSERT OR UPDATE ON DDLCONTRSERV_DBT FOR EACH ROW
DECLARE
BEGIN
  :NEW.T_UPDATEDATE := SYSDATE;
END;';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
