--Обновление событий СНОБ
DECLARE
BEGIN
  UPDATE DNPTXTOTALBASE_DBT
     SET T_INITIAL_DOCKIND = T_DOCKIND,
         T_INITIAL_DOCID   = T_DOCID
   WHERE T_INITIAL_DOCKIND = 0
     AND T_INITIAL_DOCID   = 0;
END;
/

DECLARE
BEGIN
  UPDATE DNPTXTOTALBASEBC_DBT
     SET T_INITIAL_DOCKIND = T_DOCKIND,
         T_INITIAL_DOCID   = T_DOCID
   WHERE T_INITIAL_DOCKIND = 0
     AND T_INITIAL_DOCID   = 0;
END;
/ 

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

