-- Представление 
CREATE OR REPLACE VIEW DV_SCQINVHIST AS
  SELECT SCQINVH.T_PARTYID,
          SCQINVH.T_STATE,
          SCQINVH.T_BEGDATE,
          SCQINVH.T_ENDDATE,
          SCQINVH.T_OPER,
          SCQINVH.T_SYSDATE,
          SCQINVH.T_SYSTIME,
          SCQINVH.T_CAUSE,
          SCQINVH.T_CODE,
          SCQINVH.T_KIND
     FROM DSCQINVH_DBT SCQINVH
  UNION ALL
  SELECT SCQINV.T_PARTYID,
          SCQINV.T_STATE,
          GREATEST(SCQINV.T_REGDATE, SCQINV.T_CHANGEDATE) AS T_BEGDATE,
          TO_DATE( '01.01.0001', 'dd.mm.yyyy' ) as T_ENDDATE,
          SCQINV.T_OPER,
          SCQINV.T_SYSDATE,
          SCQINV.T_SYSTIME,
          SCQINV.T_CAUSE,
          SCQINV.T_CODE,
          SCQINV.T_KIND
     FROM DSCQINV_DBT SCQINV
/