-- Таблица "DDL_BASESUM_DBT"
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DDL_BASESUM_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DDL_BASESUM_DBT (
    T_ID NUMBER(10)
  , T_OPID NUMBER(10) 
  , T_DATE DATE 
  , T_COMNUMBER NUMBER(5)
  , T_FEETYPE NUMBER(5)
  , T_CLIENTID NUMBER(10)
  , T_DLCONTRID NUMBER(10)
  , T_SUM NUMBER(32,12)
  , T_CURRENCY NUMBER(10)
  , T_LNKOPID NUMBER(10)
  , T_STATE CHAR(1)
  , T_COMRATE NUMBER(32,12)
  , T_COMSUM NUMBER(32,12)
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DDL_BASESUM_DBT IS 'Таблица базовых сумм'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_ID IS 'Идентификатор базовой суммы'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_OPID IS 'Идентификатор запуска'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_DATE IS 'Дата базовой суммы'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_COMNUMBER IS 'Номер комиссии'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_FEETYPE IS 'Тип взимания'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_CLIENTID IS 'Идентификатор клиента'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_DLCONTRID IS 'Идентификатор ДБО'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_SUM IS 'Базовая сумма'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_CURRENCY IS 'Валюта базовой суммы'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_LNKOPID IS 'Идентификатор связанной записи'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_STATE IS 'Статус записи'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_COMRATE IS 'Ставка комиссии'/
COMMENT ON COLUMN DDL_BASESUM_DBT.T_COMSUM IS 'Сумма комиссии'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_BASESUM_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DDL_BASESUM_DBT_IDX0 ON DDL_BASESUM_DBT (
   T_ID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_BASESUM_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DDL_BASESUM_DBT_IDX1 ON DDL_BASESUM_DBT (
   T_DATE ASC
  ,T_DLCONTRID ASC
  ,T_COMNUMBER ASC
  ,T_FEETYPE ASC
  ,T_STATE ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_BASESUM_DBT_IDX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DDL_BASESUM_DBT_IDX2 ON DDL_BASESUM_DBT (
   T_OPID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_BASESUM_DBT_IDX3';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DDL_BASESUM_DBT_IDX3 ON DDL_BASESUM_DBT (
   T_LNKOPID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DDL_BASESUM_DBT_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE DDL_BASESUM_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER DDL_BASESUM_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDL_BASESUM_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDL_BASESUM_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER(''DDL_BASESUM_DBT_SEQ'');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/