-- Таблица "DDL_BASESUMLOG_TMP"
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DDL_BASESUMLOG_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DDL_BASESUMLOG_TMP (
    T_TYPE NUMBER(5)
  , T_DLCONTRID NUMBER(10)
  , T_DATE DATE
  , T_TEXT VARCHAR2(500)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DDL_BASESUMLOG_TMP IS 'Временная таблица сообщений при расчете базовых сумм'/
COMMENT ON COLUMN DDL_BASESUMLOG_TMP.T_TYPE IS 'Тип сообщения'/
COMMENT ON COLUMN DDL_BASESUMLOG_TMP.T_DLCONTRID IS 'Идентификатор ДБО'/
COMMENT ON COLUMN DDL_BASESUMLOG_TMP.T_DATE IS 'Дата расчета'/
COMMENT ON COLUMN DDL_BASESUMLOG_TMP.T_TEXT IS 'Текст сообщения'/