DECLARE
   ex_table_exists EXCEPTION;
   PRAGMA EXCEPTION_INIT(ex_table_exists, -955);
BEGIN
   execute immediate 'CREATE TABLE DNPTXSNOBVER_DBT ( ' ||
                        ' T_ID              NUMBER(10,0) ' ||
                        ',T_DOCKIND         NUMBER(5,0) ' ||
                        ',T_KIND_OPERATION  NUMBER(5,0) ' ||
                        ',T_CODE            VARCHAR2(25) ' ||
                        ',T_OPERDATE        DATE ' ||
                        ',T_BEGINDATE       DATE ' ||
                        ',T_ENDDATE         DATE ' ||
                        ',T_INCLUDECANCELED CHAR(1) ' ||
                        ',T_PREVDATE        DATE ' ||
                        ',T_STATUS          NUMBER(5,0) ' ||
                     ')';
                        
EXCEPTION
   WHEN ex_table_exists
   THEN it_log.log('CCBO-1489. Таблица DNPTXSNOBVER_DBT уже существует');
END;
/

COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_ID IS 'ID клиента'/
COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_DOCKIND IS 'Вид первичного документа'/
COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_KIND_OPERATION IS 'Вид операции'/
COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_CODE IS 'Код операции'/
COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_OPERDATE IS 'Дата операции'/
COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_BEGINDATE IS 'За период от...'/
COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_ENDDATE IS 'За период до...'/
COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_INCLUDECANCELED IS 'В том числе отмененные'/
COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_PREVDATE IS 'Дата предыдущей операции'/
COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_STATUS IS 'Статус операции'/
COMMENT ON TABLE DNPTXSNOBVER_DBT IS 'Операции технической сверки СНОБ'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXSNOBVER_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXSNOBVER_DBT_IDX0 ON DNPTXSNOBVER_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXSNOBVER_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXSNOBVER_DBT_IDX1 ON DNPTXSNOBVER_DBT (
   T_DOCKIND ASC,
   T_CODE ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXSNOBVER_DBT_IDX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX DNPTXSNOBVER_DBT_IDX2 ON DNPTXSNOBVER_DBT (
   T_OPERDATE ASC,
   T_INCLUDECANCELED ASC
)
/

DECLARE
   e_exist_seq EXCEPTION;
   PRAGMA EXCEPTION_INIT(  e_exist_seq,    -955 );
BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE DNPTXSNOBVER_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
   WHEN e_exist_seq THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER DNPTXSNOBVER_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXSNOBVER_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXSNOBVER_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXSNOBVER_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
