-- Таблица "DDL_BASESUMOP_DBT"
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DDL_BASESUMOP_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DDL_BASESUMOP_DBT (
    T_ID NUMBER(10)
  , T_BEGDATE DATE
  , T_ENDDATE DATE
  , T_COMNUMBER NUMBER(5)
  , T_FEETYPE NUMBER(5)
  , T_CLIENTID NUMBER(10)
  , T_DLCONTRID NUMBER(10)
  , T_ACTION NUMBER(5)
  , T_PRINTLOG CHAR(1)
  , T_LOG CLOB
  , T_OPER NUMBER(5)
  , T_SYSDATE DATE DEFAULT SYSDATE
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DDL_BASESUMOP_DBT IS 'Экземпляры запуска опер.расчета баз.сумм'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_ID IS 'Идентификатор'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_BEGDATE IS 'Дата начала периода'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_ENDDATE IS 'Дата окончания периода'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_COMNUMBER IS 'Номер комиссии'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_FEETYPE IS 'Тип взимания'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_CLIENTID IS 'Идентификатор клиента'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_DLCONTRID IS 'Идентификатор ДБО'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_ACTION IS 'Вид действия'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_PRINTLOG IS 'Флаг расширенного протокола'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_LOG IS 'Протокол'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_OPER IS 'Операционист'/
COMMENT ON COLUMN DDL_BASESUMOP_DBT.T_SYSDATE IS 'Системная дата'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_BASESUMOP_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DDL_BASESUMOP_DBT_IDX0 ON DDL_BASESUMOP_DBT (
   T_ID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DDL_BASESUMOP_DBT_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE DDL_BASESUMOP_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER DDL_BASESUMOP_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDL_BASESUMOP_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDL_BASESUMOP_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER(''DDL_BASESUMOP_DBT_SEQ'');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/