-- Таблица "DDL_BASESUMVAL_DBT"
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DDL_BASESUMVAL_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DDL_BASESUMVAL_DBT (
    T_BASESUMID NUMBER(10)
  , T_OBJKIND NUMBER(5)
  , T_OBJECTID NUMBER(10)
  , T_KIND NUMBER(5)
  , T_AMOUNT NUMBER(32,12)
  , T_RATEID NUMBER(10)
  , T_RATEDATE DATE
  , T_RATE NUMBER(32,12)
  , T_NKD NUMBER(32,12)
  , T_COST NUMBER(32,12)
  , T_COSTCUR NUMBER(10)
  , T_CBRATE NUMBER(32,12)
  , T_COSTRUB NUMBER(32,12)
  , T_SFCONTRID NUMBER(10)
  , T_MARKETID NUMBER(10)
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DDL_BASESUMVAL_DBT IS 'Таблица расшифровок базовых сумм'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_BASESUMID IS 'Идентификатор базовой суммы'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_OBJKIND IS 'Вид объекта'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_OBJECTID IS 'Идентификатор объекта'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_KIND IS 'Вид актива'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_AMOUNT IS 'Количество актива'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_RATEID IS 'Идентификатор котировки'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_RATEDATE IS 'Дата котировки'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_RATE IS 'Котировка'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_NKD IS 'НКД за дату расчета'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_COST IS 'Стоимость'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_COSTCUR IS 'Валюта стоимости'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_CBRATE IS 'Курс ЦБ РФ валюты стоимости к рублю'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_COSTRUB IS 'Стоимость в рублях'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_SFCONTRID IS 'Идентификатор субдоговора'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_MARKETID IS 'Идентификатор биржи'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDL_BASESUMVAL_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DDL_BASESUMVAL_DBT_IDX0 ON DDL_BASESUMVAL_DBT (
   T_BASESUMID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Таблица "DDL_BASESUMVAL_TMP"
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DDL_BASESUMVAL_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DDL_BASESUMVAL_TMP (
    T_OBJKIND NUMBER(5)
  , T_OBJECTID NUMBER(10)
  , T_KIND NUMBER(5)
  , T_AMOUNT NUMBER(32,12)
  , T_RATEID NUMBER(10)
  , T_RATEDATE DATE
  , T_RATE NUMBER(32,12)
  , T_NKD NUMBER(32,12)
  , T_COST NUMBER(32,12)
  , T_COSTCUR NUMBER(10)
  , T_CBRATE NUMBER(32,12)
  , T_COSTRUB NUMBER(32,12)
  , T_SFCONTRID NUMBER(10)
  , T_MARKETID NUMBER(10)
) ON COMMIT DELETE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DDL_BASESUMVAL_DBT IS 'Временная таблица расшифровок базовых сумм'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_OBJKIND IS 'Вид объекта'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_OBJECTID IS 'Идентификатор объекта'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_KIND IS 'Вид актива'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_AMOUNT IS 'Количество актива'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_RATEID IS 'Идентификатор котировки'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_RATEDATE IS 'Дата котировки'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_RATE IS 'Котировка'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_NKD IS 'НКД за дату расчета'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_COST IS 'Стоимость'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_COSTCUR IS 'Валюта стоимости'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_CBRATE IS 'Курс ЦБ РФ валюты стоимости к рублю'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_COSTRUB IS 'Стоимость в рублях'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_SFCONTRID IS 'Идентификатор субдоговора'/
COMMENT ON COLUMN DDL_BASESUMVAL_DBT.T_MARKETID IS 'Идентификатор биржи'/