DECLARE
   v_CatID NUMBER := 0;
BEGIN

   BEGIN
	SELECT T_ID INTO v_CatID FROM DMCCATEG_DBT WHERE T_CODE = '+Œ à¦ , „Œ';
	EXCEPTION
	WHEN NO_DATA_FOUND THEN v_CatID := 0;
   END;
	
   IF v_CatID <= 0 THEN	
	   INSERT INTO DMCCATEG_DBT
				   (T_ID,T_NUMBER,T_CODE,T_NAME,T_GROUPID,T_LEVELTYPE,T_UPDATEMODE,T_PERIODKIND,T_PERIODGROUPNUM,T_PARAM1,T_CLASS1,T_PARAM2,T_CLASS2,T_PARAM3,T_CLASS3,
					T_PARAM4,T_CLASS4,T_PARAM5,T_CLASS5,T_PARAM6,T_CLASS6,T_PARAM7,T_CLASS7,T_PARAM8,T_CLASS8,T_MASK,T_ATTRMASK,T_CURTYPE,T_OPTIONAL,T_NOTINUSE,
					T_UPGRADE,T_DONTUPDATE,T_PAIRCATID,T_INDEXDATEUNIT,T_RESERVE)
	   VALUES(0,5188,'+Œ à¦ , „Œ','+Œ à¦ , „Œ',109,1,3,0,0,1122,701,3550,1819,0,0,0,0,0,0,0,0,0,0,0,0,'‚‚‚Š0000',0,0,CHR(0),CHR(0),CHR(0),CHR(0),0,0,CHR(1))
	   RETURNING T_ID INTO v_CatID;

	   INSERT INTO DMCTEMPL_DBT
				   (T_CATID,T_NUMBER,T_VALUE1,T_VALUE2,T_VALUE3,T_VALUE4,T_VALUE5,T_VALUE6,T_VALUE7,T_VALUE8,T_CHAPTER,T_BALANCE,T_MASK,
					T_KIND_ACCOUNT,T_GROUPNUM,T_HASPERIOD,T_NOTAUTO,T_ISCLOSE,T_ACCOUNTCLIENT,T_TYPEACCOUNT,T_RESERVE)
	   VALUES(v_CatID,1,2,6,-1,-1,-1,-1,-1,-1,1,'70604','2560101','',0,CHR(0),CHR(0),CHR(0),0,CHR(1),CHR(1));
	   
	   INSERT INTO DMCTEMPL_DBT
				   (T_CATID,T_NUMBER,T_VALUE1,T_VALUE2,T_VALUE3,T_VALUE4,T_VALUE5,T_VALUE6,T_VALUE7,T_VALUE8,T_CHAPTER,T_BALANCE,T_MASK,
					T_KIND_ACCOUNT,T_GROUPNUM,T_HASPERIOD,T_NOTAUTO,T_ISCLOSE,T_ACCOUNTCLIENT,T_TYPEACCOUNT,T_RESERVE)
	   VALUES(v_CatID,2,2,7,-1,-1,-1,-1,-1,-1,1,'70604','2560102','',0,CHR(0),CHR(0),CHR(0),0,CHR(1),CHR(1));
	   
	   INSERT INTO DMCTEMPL_DBT
				   (T_CATID,T_NUMBER,T_VALUE1,T_VALUE2,T_VALUE3,T_VALUE4,T_VALUE5,T_VALUE6,T_VALUE7,T_VALUE8,T_CHAPTER,T_BALANCE,T_MASK,
					T_KIND_ACCOUNT,T_GROUPNUM,T_HASPERIOD,T_NOTAUTO,T_ISCLOSE,T_ACCOUNTCLIENT,T_TYPEACCOUNT,T_RESERVE)
	   VALUES(v_CatID,3,2,8,-1,-1,-1,-1,-1,-1,1,'70604','2560103','',0,CHR(0),CHR(0),CHR(0),0,CHR(1),CHR(1));
	   
	   INSERT INTO DMCTEMPL_DBT
				   (T_CATID,T_NUMBER,T_VALUE1,T_VALUE2,T_VALUE3,T_VALUE4,T_VALUE5,T_VALUE6,T_VALUE7,T_VALUE8,T_CHAPTER,T_BALANCE,T_MASK,
					T_KIND_ACCOUNT,T_GROUPNUM,T_HASPERIOD,T_NOTAUTO,T_ISCLOSE,T_ACCOUNTCLIENT,T_TYPEACCOUNT,T_RESERVE)
	   VALUES(v_CatID,4,2,9,-1,-1,-1,-1,-1,-1,1,'70604','2560104','',0,CHR(0),CHR(0),CHR(0),0,CHR(1),CHR(1));

	   
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,31,'#');
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,3,'' );
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,1,'‚' );
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,9,'Š' );
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,14,'');

	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5188,192,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5188,193,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5188,194,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5188,199,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5188,4812,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5188,4813,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5188,4814,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5188,4815,CHR(0),CHR(1));
	END IF;
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
   v_CatID NUMBER := 0;
BEGIN

   BEGIN
	SELECT T_ID INTO v_CatID FROM DMCCATEG_DBT WHERE T_CODE = '-Œ à¦ , „Œ';
	EXCEPTION
	WHEN NO_DATA_FOUND THEN v_CatID := 0;
   END;
	
   IF v_CatID <= 0 THEN	
	   INSERT INTO DMCCATEG_DBT
				   (T_ID,T_NUMBER,T_CODE,T_NAME,T_GROUPID,T_LEVELTYPE,T_UPDATEMODE,T_PERIODKIND,T_PERIODGROUPNUM,T_PARAM1,T_CLASS1,T_PARAM2,T_CLASS2,T_PARAM3,T_CLASS3,
					T_PARAM4,T_CLASS4,T_PARAM5,T_CLASS5,T_PARAM6,T_CLASS6,T_PARAM7,T_CLASS7,T_PARAM8,T_CLASS8,T_MASK,T_ATTRMASK,T_CURTYPE,T_OPTIONAL,T_NOTINUSE,
					T_UPGRADE,T_DONTUPDATE,T_PAIRCATID,T_INDEXDATEUNIT,T_RESERVE)
	   VALUES(0,5189,'-Œ à¦ , „Œ','-Œ à¦ , „Œ',4,1,3,0,0,1122,701,3550,1819,0,0,0,0,0,0,0,0,0,0,0,0,'‚‚‚Š0000',0,0,CHR(0),CHR(0),CHR(0),CHR(0),0,0,CHR(1))
	   RETURNING T_ID INTO v_CatID;

	   INSERT INTO DMCTEMPL_DBT
				   (T_CATID,T_NUMBER,T_VALUE1,T_VALUE2,T_VALUE3,T_VALUE4,T_VALUE5,T_VALUE6,T_VALUE7,T_VALUE8,T_CHAPTER,T_BALANCE,T_MASK,
					T_KIND_ACCOUNT,T_GROUPNUM,T_HASPERIOD,T_NOTAUTO,T_ISCLOSE,T_ACCOUNTCLIENT,T_TYPEACCOUNT,T_RESERVE)
	   VALUES(v_CatID,1,2,6,-1,-1,-1,-1,-1,-1,1,'70609','4560101','€',0,CHR(0),CHR(0),CHR(0),0,CHR(1),CHR(1));
	   
	   INSERT INTO DMCTEMPL_DBT
				   (T_CATID,T_NUMBER,T_VALUE1,T_VALUE2,T_VALUE3,T_VALUE4,T_VALUE5,T_VALUE6,T_VALUE7,T_VALUE8,T_CHAPTER,T_BALANCE,T_MASK,
					T_KIND_ACCOUNT,T_GROUPNUM,T_HASPERIOD,T_NOTAUTO,T_ISCLOSE,T_ACCOUNTCLIENT,T_TYPEACCOUNT,T_RESERVE)
	   VALUES(v_CatID,2,2,7,-1,-1,-1,-1,-1,-1,1,'70609','4560102','€',0,CHR(0),CHR(0),CHR(0),0,CHR(1),CHR(1));
	   
	   INSERT INTO DMCTEMPL_DBT
				   (T_CATID,T_NUMBER,T_VALUE1,T_VALUE2,T_VALUE3,T_VALUE4,T_VALUE5,T_VALUE6,T_VALUE7,T_VALUE8,T_CHAPTER,T_BALANCE,T_MASK,
					T_KIND_ACCOUNT,T_GROUPNUM,T_HASPERIOD,T_NOTAUTO,T_ISCLOSE,T_ACCOUNTCLIENT,T_TYPEACCOUNT,T_RESERVE)
	   VALUES(v_CatID,3,2,8,-1,-1,-1,-1,-1,-1,1,'70609','4560103','€',0,CHR(0),CHR(0),CHR(0),0,CHR(1),CHR(1));
	   
	   INSERT INTO DMCTEMPL_DBT
				   (T_CATID,T_NUMBER,T_VALUE1,T_VALUE2,T_VALUE3,T_VALUE4,T_VALUE5,T_VALUE6,T_VALUE7,T_VALUE8,T_CHAPTER,T_BALANCE,T_MASK,
					T_KIND_ACCOUNT,T_GROUPNUM,T_HASPERIOD,T_NOTAUTO,T_ISCLOSE,T_ACCOUNTCLIENT,T_TYPEACCOUNT,T_RESERVE)
	   VALUES(v_CatID,4,2,9,-1,-1,-1,-1,-1,-1,1,'70609','4560104','€',0,CHR(0),CHR(0),CHR(0),0,CHR(1),CHR(1));

	   
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,31,'#');
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,3,'' );
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,1,'‚' );
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,9,'Š' );
	   INSERT INTO DMCTPLELM_DBT(T_CATID,T_IDELEMENT,T_SYMBOL) VALUES(v_CatID,14,'');

	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5189,192,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5189,193,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5189,194,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5189,199,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5189,4812,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5189,4813,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5189,4814,CHR(0),CHR(1));
	   INSERT INTO DMCDOCCAT_DBT(T_CATID,T_CATNUM,T_DOCKIND,T_NOTINUSE,T_RESERVE) VALUES(v_CatID,5189,4815,CHR(0),CHR(1));
	END IF;
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/