BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE D_EQM3T_TMP CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE D_EQM3T_TMP (
    T_ID_MB_EQM3T NUMBER(10)
  , T_ID_MB_REQUISITES NUMBER(10)
  , T_ID_PROCESSING_LOG NUMBER(10)
  , T_CURRENCYID VARCHAR2(3)
  , T_BOARDID VARCHAR2(4)
  , T_TRADEDATE DATE
  , T_SETTLEDATE DATE
  , T_SECURITYID VARCHAR2(12)
  , T_PRICETYPE VARCHAR2(4)
  , T_TRDACCID VARCHAR2(12)
  , T_TRADENO VARCHAR2(20)
  , T_TRADETIME DATE
  , T_BUYSELL VARCHAR2(1)
  , T_SETTLECODE VARCHAR2(12)
  , T_DECIMALS NUMBER(5)
  , T_PRICE NUMBER(32,12)
  , T_QUANTITY NUMBER(10)
  , T_VALUE NUMBER(32,12)
  , T_AMOUNT NUMBER(32,12)
  , T_CLRCOMM NUMBER(32,12)
  , T_ORDERNO VARCHAR2(20)
  , T_CPFIRMID VARCHAR2(12)
  , T_ACCINT NUMBER(32,12)
  , T_SESSIONNO VARCHAR2(1)
  , T_CLIENTCODE VARCHAR2(12)
  , T_VCLIENTCODE VARCHAR2(12)
  , T_FIRMID VARCHAR2(12)
  , T_SECURITYTYPE VARCHAR2(4)
  , T_FACEVALUE NUMBER(32,12)
  , T_SECCURRENCYID VARCHAR2(3)
  , T_RECNO NUMBER(10)
  , T_SECSETID VARCHAR2(12)
  , T_FACEAMOUNT NUMBER(32,12)
  , T_ORDTYPE VARCHAR2(3)
  , T_ORDTYPECODE VARCHAR2(4)
  , T_TRADETYPE VARCHAR2(1)
  , T_BROKERREF VARCHAR2(20)
  , T_DOC_NO VARCHAR2(12)
  , T_PARTYID NUMBER(10)
  , T_SFCONTRID NUMBER(10)
  , T_ISSEB NUMBER(5)
  , T_CPFIRMPARTYID NUMBER(10)
  , T_CURID NUMBER(10)
  , T_CALENDID NUMBER(5)
  , T_MARKETSCHEMEID NUMBER(10)
  , T_NDAY1 NUMBER(5)
  , T_NDAY2 NUMBER(5)
  , T_PAYMDATE1 DATE
  , T_PAYMDATE2 DATE
  , T_CALCITOGDATE DATE
  , T_WORKSETTLEDATE DATE
  , T_OBJECTID NUMBER(10)
  , T_PORTFOLIO NUMBER(5)
  , T_FIID NUMBER(10)
  , T_UNDERWR NUMBER(5)
  , T_UNDERWR_BUY NUMBER(5)
  , T_UNDERWRDOID NUMBER(10)
  , T_ISREPO NUMBER(5)
  , T_REPOPERIOD NUMBER(5)
  , T_MATCHREF VARCHAR2(10)
  , T_ISFINDEQM06 NUMBER(5)
  , T_EXTSETTLECODE VARCHAR2(12)
  , T_MARKETREPORTID NUMBER(10)
  , T_BOARDNAME VARCHAR2(30)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE D_EQM3T_TMP IS 'Таблица для создания ЗР по EQM3T'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ID_MB_EQM3T IS 'ID_MB_EQM3T'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ID_MB_REQUISITES IS 'ID_MB_REQUISITES'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ID_PROCESSING_LOG IS 'ID_PROCESSING_LOG'/
COMMENT ON COLUMN D_EQM3T_TMP.T_CURRENCYID IS 'CURRENCYID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_BOARDID IS 'BOARDID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_TRADEDATE IS 'TRADEDATE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_SETTLEDATE IS 'SETTLEDATE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_SECURITYID IS 'SECURITYID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_PRICETYPE IS 'PRICETYPE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_TRDACCID IS 'TRDACCID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_TRADENO IS 'TRADENO'/
COMMENT ON COLUMN D_EQM3T_TMP.T_TRADETIME IS 'TRADETIME'/
COMMENT ON COLUMN D_EQM3T_TMP.T_BUYSELL IS 'BUYSELL'/
COMMENT ON COLUMN D_EQM3T_TMP.T_SETTLECODE IS 'SETTLECODE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_DECIMALS IS 'DECIMALS'/
COMMENT ON COLUMN D_EQM3T_TMP.T_PRICE IS 'PRICE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_QUANTITY IS 'QUANTITY'/
COMMENT ON COLUMN D_EQM3T_TMP.T_VALUE IS 'VALUE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_AMOUNT IS 'AMOUNT'/
COMMENT ON COLUMN D_EQM3T_TMP.T_CLRCOMM IS 'CLRCOMM'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ORDERNO IS 'ORDERNO'/
COMMENT ON COLUMN D_EQM3T_TMP.T_CPFIRMID IS 'CPFIRMID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ACCINT IS 'ACCINT'/
COMMENT ON COLUMN D_EQM3T_TMP.T_SESSIONNO IS 'SESSIONNO'/
COMMENT ON COLUMN D_EQM3T_TMP.T_CLIENTCODE IS 'CLIENTCODE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_VCLIENTCODE IS 'VCLIENTCODE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_FIRMID IS 'FIRMID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_SECURITYTYPE IS 'SECURITYTYPE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_FACEVALUE IS 'FACEVALUE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_SECCURRENCYID IS 'SECCURRENCYID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_RECNO IS 'RECNO'/
COMMENT ON COLUMN D_EQM3T_TMP.T_SECSETID IS 'SECSETID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_FACEAMOUNT IS 'FACEAMOUNT'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ORDTYPE IS 'ORDTYPE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ORDTYPECODE IS 'ORDTYPECODE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_TRADETYPE IS 'TRADETYPE'/
COMMENT ON COLUMN D_EQM3T_TMP.T_BROKERREF IS 'BROKERREF'/
COMMENT ON COLUMN D_EQM3T_TMP.T_DOC_NO IS 'DOC_NO'/
COMMENT ON COLUMN D_EQM3T_TMP.T_PARTYID IS 'PARTYID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_SFCONTRID IS 'SfContrID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ISSEB IS 'IsSEB'/
COMMENT ON COLUMN D_EQM3T_TMP.T_CPFIRMPARTYID IS 'CPFirmPartyId'/
COMMENT ON COLUMN D_EQM3T_TMP.T_CURID IS 'CURID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_CALENDID IS 'CALENDID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_MARKETSCHEMEID IS 'MarketSchemeID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_NDAY1 IS 'nday1'/
COMMENT ON COLUMN D_EQM3T_TMP.T_NDAY2 IS 'nday2'/
COMMENT ON COLUMN D_EQM3T_TMP.T_PAYMDATE1 IS 'paymdate1'/
COMMENT ON COLUMN D_EQM3T_TMP.T_PAYMDATE2 IS 'paymdate2'/
COMMENT ON COLUMN D_EQM3T_TMP.T_CALCITOGDATE IS 'calcitogdate'/
COMMENT ON COLUMN D_EQM3T_TMP.T_WORKSETTLEDATE IS 'WorkSettleDate'/
COMMENT ON COLUMN D_EQM3T_TMP.T_OBJECTID IS 'objectid'/
COMMENT ON COLUMN D_EQM3T_TMP.T_PORTFOLIO IS 'Portfolio'/
COMMENT ON COLUMN D_EQM3T_TMP.T_FIID IS 'FIID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_UNDERWR IS 'UnderWr'/
COMMENT ON COLUMN D_EQM3T_TMP.T_UNDERWR_BUY IS 'UnderWr_buy'/
COMMENT ON COLUMN D_EQM3T_TMP.T_UNDERWRDOID IS 'UnderWrDOID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ISREPO IS 'IsREPO'/
COMMENT ON COLUMN D_EQM3T_TMP.T_REPOPERIOD IS 'RepoPeriod'/
COMMENT ON COLUMN D_EQM3T_TMP.T_MATCHREF IS 't_matchref'/
COMMENT ON COLUMN D_EQM3T_TMP.T_ISFINDEQM06 IS 't_isfindeqm06'/
COMMENT ON COLUMN D_EQM3T_TMP.T_EXTSETTLECODE IS 'extsettlecode'/
COMMENT ON COLUMN D_EQM3T_TMP.T_MARKETREPORTID IS 'MarketReportID'/
COMMENT ON COLUMN D_EQM3T_TMP.T_BOARDNAME IS 'Название режима торгов'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX D_EQM3T_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX D_EQM3T_TMP_IDX0 ON D_EQM3T_TMP (
   T_ID_MB_EQM3T ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX D_EQM3T_TMP_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX D_EQM3T_TMP_IDX1 ON D_EQM3T_TMP (
   T_TRADENO ASC
  ,T_BUYSELL ASC
  ,T_VCLIENTCODE ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX D_EQM3T_TMP_IDX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX D_EQM3T_TMP_IDX2 ON D_EQM3T_TMP (
   T_VCLIENTCODE ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX D_EQM3T_TMP_IDX3';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX D_EQM3T_TMP_IDX3 ON D_EQM3T_TMP (
   T_TRDACCID ASC
  ,T_VCLIENTCODE ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX D_EQM3T_TMP_IDX4';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX D_EQM3T_TMP_IDX4 ON D_EQM3T_TMP (
   T_SECURITYID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX D_EQM3T_TMP_IDX5';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX D_EQM3T_TMP_IDX5 ON D_EQM3T_TMP (
   T_TRDACCID ASC
)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
