BEGIN
  UPDATE DOBJATTR_DBT
     SET T_FULLNAME = CASE WHEN T_NUMINLIST = 'TQRD' THEN 'T+ D bonds'
                           WHEN T_NUMINLIST = 'AUBB' THEN 'Buy-back Board'
                           WHEN T_NUMINLIST = 'EQDP' THEN 'Dark Pool'
                           WHEN T_NUMINLIST = 'EQEU' THEN 'Main market: bonds USD'
                           WHEN T_NUMINLIST = 'EQGO' THEN 'Main market: bonds GBR'
                           WHEN T_NUMINLIST = 'EQRE' THEN 'REPO with CCP 1 day EUR'
                           WHEN T_NUMINLIST = 'EQTD' THEN '’0 ETF: USD'
                           WHEN T_NUMINLIST = 'EQTU' THEN '’0 ETF: EUR'
                           WHEN T_NUMINLIST = 'EQWE' THEN 'REPO with CCP 7 days EUR'
                           WHEN T_NUMINLIST = 'EQYO' THEN 'Main market: bonds CNY'
                           WHEN T_NUMINLIST = 'FBCB' THEN 'REPO CB'
                           WHEN T_NUMINLIST = 'FBCE' THEN 'EUR REPO: with CB (auction)'
                           WHEN T_NUMINLIST = 'FBCU' THEN 'USD REPO: with CB (auction)'
                           WHEN T_NUMINLIST = 'GCOM' THEN 'REPO with CCP with GCP 1 m.'
                           WHEN T_NUMINLIST = 'GCOW' THEN 'REPO with CCP with GCP 7 days'
                           WHEN T_NUMINLIST = 'GCOY' THEN 'REPO with CCP with GCP 1 y.'
                           WHEN T_NUMINLIST = 'GCSM' THEN 'REPO with CCP with GCP 2 m.'
                           WHEN T_NUMINLIST = 'GCSW' THEN 'REPO with CCP with GCP 14 days'
                           WHEN T_NUMINLIST = 'GCTM' THEN 'REPO with CCP with GCP 3 m.'
                           WHEN T_NUMINLIST = 'GCTR' THEN 'Transfer GCP'
                           WHEN T_NUMINLIST = 'GCUM' THEN 'REPO with CCP with GCP 6 m.'
                           WHEN T_NUMINLIST = 'GEOM' THEN 'REPO with CCP with GCP 1 m. (EUR)'
                           WHEN T_NUMINLIST = 'GEOW' THEN 'REPO with CCP with GCP 7 days (EUR)'
                           WHEN T_NUMINLIST = 'GEOY' THEN 'REPO with CCP with GCP 1 y. (EUR)'
                           WHEN T_NUMINLIST = 'GERP' THEN 'REPO with CCP with GCP 1 day (EUR)'
                           WHEN T_NUMINLIST = 'GESM' THEN 'REPO with CCP with GCP 2 m. (EUR)'
                           WHEN T_NUMINLIST = 'GESW' THEN 'REPO with CCP with GCP 14 days (EUR)'
                           WHEN T_NUMINLIST = 'GETM' THEN 'REPO with CCP with GCP 3 m. (EUR)'
                           WHEN T_NUMINLIST = 'GEUM' THEN 'REPO with CCP with GCP 6 m. (EUR)'
                           WHEN T_NUMINLIST = 'GUOM' THEN 'REPO with CCP with GCP 1 m. (USD)'
                           WHEN T_NUMINLIST = 'GUOW' THEN 'REPO with CCP with GCP 7 days (USD)'
                           WHEN T_NUMINLIST = 'GUOY' THEN 'REPO with CCP with GCP 1 y. (USD)'
                           WHEN T_NUMINLIST = 'GURP' THEN 'REPO with CCP with GCP 1 day (USD)'
                           WHEN T_NUMINLIST = 'GUSM' THEN 'REPO with CCP with GCP 2 m. (USD)'
                           WHEN T_NUMINLIST = 'GUSW' THEN 'REPO with CCP with GCP 14 days (USD)'
                           WHEN T_NUMINLIST = 'GUTM' THEN 'REPO with CCP with GCP 3 m. (USD)'
                           WHEN T_NUMINLIST = 'GUUM' THEN 'REPO with CCP with GCP 6 m. (USD)'
                           WHEN T_NUMINLIST = 'LIQB' THEN 'Tech trades with CCP'
                           WHEN T_NUMINLIST = 'LIQO' THEN 'Tech trades with CCP otc'
                           WHEN T_NUMINLIST = 'LIQR' THEN 'Settl.unfulfil.oblig.CCP-REPO'
                           WHEN T_NUMINLIST = 'OCPE' THEN 'OTC deals with CCP (EUR)'
                           WHEN T_NUMINLIST = 'OCPR' THEN 'OTC deals with CCP'
                           WHEN T_NUMINLIST = 'OCPU' THEN 'OTC deals with CCP (USD)'
                           WHEN T_NUMINLIST = 'OTCB' THEN 'Anonymous NDM'
                           WHEN T_NUMINLIST = 'OTCE' THEN 'Anonymous NDM (EUR)'
                           WHEN T_NUMINLIST = 'OTCU' THEN 'Anonymous NDM (USD)'
                           WHEN T_NUMINLIST = 'PACY' THEN 'Auction:Negotiated deals CNY'
                           WHEN T_NUMINLIST = 'PAEU' THEN 'Auction:Negotiated deals EUR'
                           WHEN T_NUMINLIST = 'PAGB' THEN 'Auction:Negotiated deals GBP'
                           WHEN T_NUMINLIST = 'PAUS' THEN 'Auction:Negotiated deals USD'
                           WHEN T_NUMINLIST = 'PEGC' THEN 'REPO with CCP with GCP Negdeal (EUR)'
                           WHEN T_NUMINLIST = 'PSBE' THEN 'Buy-back:Negotiated deals EUR'
                           WHEN T_NUMINLIST = 'PSBU' THEN 'Buy-back:Negotiated deals USD'
                           WHEN T_NUMINLIST = 'PSDB' THEN 'Neg. deals: D bonds'
                           WHEN T_NUMINLIST = 'PSDE' THEN 'Neg. deals: D stocks'
                           WHEN T_NUMINLIST = 'PSEO' THEN 'Neg. deals: bonds EUR'
                           WHEN T_NUMINLIST = 'PSEQ' THEN 'Neg. deals: stocks'
                           WHEN T_NUMINLIST = 'PSEU' THEN 'Neg. deals: bonds USD'
                           WHEN T_NUMINLIST = 'PSGO' THEN 'Neg. deals: bonds GBP'
                           WHEN T_NUMINLIST = 'PSIF' THEN 'Neg. deals: investment funds'
                           WHEN T_NUMINLIST = 'PSQI' THEN 'Qualified inv. - Neg.deals'
                           WHEN T_NUMINLIST = 'PSRE' THEN 'REPO with CCP Negdeal EUR'
                           WHEN T_NUMINLIST = 'PSSD' THEN 'Neg. deals: FRGN stocks USD'
                           WHEN T_NUMINLIST = 'PSSE' THEN 'Neg. deals: Shares and DRs EUR'
                           WHEN T_NUMINLIST = 'PSTD' THEN 'Neg. deals: ETF USD'
                           WHEN T_NUMINLIST = 'PSTE' THEN 'Neg. deals: ETF EUR'
                           WHEN T_NUMINLIST = 'PSTF' THEN 'Neg. deals: ETF'
                           WHEN T_NUMINLIST = 'PSYO' THEN 'Neg. deals: bonds CNY'
                           WHEN T_NUMINLIST = 'PTDE' THEN 'NDM with CCP: D stocks'
                           WHEN T_NUMINLIST = 'PTIF' THEN 'NDM with CCP: investment funds'
                           WHEN T_NUMINLIST = 'PTOD' THEN 'Neg. deals with CCP: Bonds USD'
                           WHEN T_NUMINLIST = 'PTQI' THEN 'Qualified inv. - NDM with CCP'
                           WHEN T_NUMINLIST = 'PTSD' THEN 'NDM w/CCP: FRGNÿstck, DRs USD'
                           WHEN T_NUMINLIST = 'PTSE' THEN 'Neg.deals CCP: Shares,DRs EUR'
                           WHEN T_NUMINLIST = 'PTTD' THEN 'NDM with CCP: ETF USD'
                           WHEN T_NUMINLIST = 'PTTE' THEN 'NDM with CCP: ETF EUR'
                           WHEN T_NUMINLIST = 'PTTF' THEN 'NDM with CCP: ETF'
                           WHEN T_NUMINLIST = 'PUGC' THEN 'REPO with CCP with GCP Negdeal (USD)'
                           WHEN T_NUMINLIST = 'RFND' THEN 'Refund payments'
                           WHEN T_NUMINLIST = 'RFNE' THEN 'Refund payments (EUR)'
                           WHEN T_NUMINLIST = 'RFNU' THEN 'Refund payments (USD)'
                           WHEN T_NUMINLIST = 'RPEO' THEN 'REPO-M (EUR)'
                           WHEN T_NUMINLIST = 'RPEU' THEN 'REPO-M (USD)'
                           WHEN T_NUMINLIST = 'RPEY' THEN 'REPO-M (CNY)'
                           WHEN T_NUMINLIST = 'RPMA' THEN 'REPO with stocks, DRs'
                           WHEN T_NUMINLIST = 'RPMO' THEN 'REPO with bonds'
                           WHEN T_NUMINLIST = 'RPUA' THEN 'REPO with stocks (USD settle)'
                           WHEN T_NUMINLIST = 'RPUO' THEN 'REPO with bonds (USD settle)'
                           WHEN T_NUMINLIST = 'SADM' THEN 'TECH SWAP'
                           WHEN T_NUMINLIST = 'SPEQ' THEN 'Delivery for FC (shares)'
                           WHEN T_NUMINLIST = 'SPOB' THEN 'Delivery for FC (bonds)'
                           WHEN T_NUMINLIST = 'TQBD' THEN 'T+: FRGN stocks, DRs USD'
                           WHEN T_NUMINLIST = 'TQBE' THEN 'T+: Shares and DRs EUR'
                           WHEN T_NUMINLIST = 'TQCB' THEN 'T+ Bonds'
                           WHEN T_NUMINLIST = 'TQDB' THEN 'Dark Pool - Bonds'
                           WHEN T_NUMINLIST = 'TQDU' THEN 'Dark Pool - Bonds USD'
                           WHEN T_NUMINLIST = 'TQIF' THEN 'T+: investment funds'
                           WHEN T_NUMINLIST = 'TQQD' THEN 'Qualified inv.-T+ USD'
                           WHEN T_NUMINLIST = 'TQQI' THEN 'Qualified inv.-T+'
                           WHEN T_NUMINLIST = 'TQTE' THEN 'T+: ETF EUR'
                           WHEN T_NUMINLIST = 'TRAN' THEN 'Transfers'
                           WHEN T_NUMINLIST = 'FBFX' THEN 'REPO fix versus CB'
                           WHEN T_NUMINLIST = 'EQEO' THEN 'Main market: bonds EUR'
                           WHEN T_NUMINLIST = 'TQTD' THEN 'T+: ETF USD'
                           WHEN T_NUMINLIST = 'EQDB' THEN 'Main market: D bonds'
                           WHEN T_NUMINLIST = 'EQWD' THEN 'REPO with CCP 7 days USD'
                           WHEN T_NUMINLIST = 'TADM' THEN 'TECH REPO with CCP Negdeal'
                           WHEN T_NUMINLIST = 'NADM' THEN 'TECH trades with CCP Negdeal'
                           WHEN T_NUMINLIST = 'EQWP' THEN 'REPO with CCP 7 days'
                           WHEN T_NUMINLIST = 'TQDE' THEN 'T+: D stocks'
                           WHEN T_NUMINLIST = 'PSBB' THEN 'Buy-back:Negotiated deals'
                           WHEN T_NUMINLIST = 'SMAL' THEN 'T+: Odd lot trading'
                           ELSE T_FULLNAME
                       END
   WHERE T_OBJECTTYPE = 101
     AND T_GROUPID = 106;
                      
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/


BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/