DECLARE
    e_col_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT (e_col_exist, -01430);
BEGIN

    EXECUTE IMMEDIATE 'ALTER TABLE DLOTSREP_TMP MODIFY (T_SUMID NUMBER(10))';

EXCEPTION WHEN e_col_exist THEN NULL;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/