BEGIN
  UPDATE DMCTEMPL_DBT SET T_MASK = REPLACE(T_MASK, '56','65') WHERE T_CATID IN (SELECT CAT.T_ID FROM DMCCATEG_DBT CAT WHERE T_CODE IN ('+Маржа, ДМ', '-Маржа, ДМ'));
EXCEPTION 
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  UPDATE DMCCATEG_DBT SET T_MASK = REPLACE(T_MASK, 'ВВВ','810') WHERE T_CODE IN ('+Маржа, ДМ', '-Маржа, ДМ');
  DELETE FROM DMCTPLELM_DBT WHERE T_CATID IN (SELECT CAT.T_ID FROM DMCCATEG_DBT CAT WHERE T_CODE IN ('+Маржа, ДМ', '-Маржа, ДМ')) AND T_SYMBOL = 'В';
EXCEPTION 
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/