/* Добавление нового образца меню и роли */

BEGIN
   INSERT INTO DMENUTPL_DBT (T_MENUID, T_NAME, T_BRANCH, T_USEINCHILD, T_ISDISTRIBUTED, T_IDENTPROGRAM, T_ISOUTERSYSTEM)
               VALUES(1036, 'Ответственный сотрудник НДФЛ', 1, 'X', '', 'S', 'X');
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   INSERT INTO DACSROLETREE_DBT (T_ROLEID, T_PARENTID, T_NAME, T_COMMENT, T_MENUID, T_ISOUTERSYSTEM)
               VALUES (10036, -1, '[36] Ответственный сотрудник НДФЛ', CHR(0), 1036, 'X');
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   INSERT INTO DACSGROUP_DBT (T_GROUPID, T_NAME, T_COMMENT, T_ISNOTLOCAL, T_DEPARTMENT, T_ISOUTERSYSTEM)
               VALUES (10036, '[36] Ответственный сотрудник НДФЛ', CHR(0), 'X', 1, 'X');
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

DECLARE
   v_NumberPoint NUMBER := 0;
   v_ParentID NUMBER := 0;
BEGIN

   SELECT NVL(MAX(T_INUMBERPOINT), 0)
     INTO v_NumberPoint
     FROM DMENUITEM_DBT
    WHERE T_OBJECTID      = 1036
      AND T_ISTEMPLATE    = 'X'
      AND T_IIDENTPROGRAM = 83;

   v_NumberPoint := v_NumberPoint + 1;

   INSERT INTO DMENUITEM_DBT(T_OBJECTID,T_ISTEMPLATE,T_IIDENTPROGRAM,T_INUMBERPOINT,T_INUMBERFATHER,T_INUMBERLINE,T_ICASEITEM,T_CSYSTEMITEM,T_SZNAMEITEM,T_SZNAMEPROMPT,T_IHELP,T_IPROGITEM)
               VALUES(1036,'X',83,v_NumberPoint,0,45,0,'X',' Налоговый учет','Налоговый учет',0,83);

   v_ParentID := v_NumberPoint;


   v_NumberPoint := v_NumberPoint + 1;

   INSERT INTO DMENUITEM_DBT(T_OBJECTID,T_ISTEMPLATE,T_IIDENTPROGRAM,T_INUMBERPOINT,T_INUMBERFATHER,T_INUMBERLINE,T_ICASEITEM,T_CSYSTEMITEM,T_SZNAMEITEM,T_SZNAMEPROMPT,T_IHELP,T_IPROGITEM)
               VALUES(1036,'X',83,v_NumberPoint,v_ParentID,20,0,'X',' НДФЛ','НДФЛ',0,83);

   v_ParentID := v_NumberPoint;


   v_NumberPoint := v_NumberPoint + 1;

   INSERT INTO DMENUITEM_DBT(T_OBJECTID,T_ISTEMPLATE,T_IIDENTPROGRAM,T_INUMBERPOINT,T_INUMBERFATHER,T_INUMBERLINE,T_ICASEITEM,T_CSYSTEMITEM,T_SZNAMEITEM,T_SZNAMEPROMPT,T_IHELP,T_IPROGITEM)
               VALUES(1036,'X',83,v_NumberPoint,v_ParentID,5,0,'X',' СНОБ',CHR(1),0,83);

   v_ParentID := v_NumberPoint;


   v_NumberPoint := v_NumberPoint + 1;

   INSERT INTO DMENUITEM_DBT(T_OBJECTID,T_ISTEMPLATE,T_IIDENTPROGRAM,T_INUMBERPOINT,T_INUMBERFATHER,T_INUMBERLINE,T_ICASEITEM,T_CSYSTEMITEM,T_SZNAMEITEM,T_SZNAMEPROMPT,T_IHELP,T_IPROGITEM)
               VALUES(1036,'X',83,v_NumberPoint,v_ParentID,100,0,'X',' Отчеты',CHR(1),0,83);

   v_ParentID := v_NumberPoint;


   v_NumberPoint := v_NumberPoint + 1;

   INSERT INTO DMENUITEM_DBT(T_OBJECTID,T_ISTEMPLATE,T_IIDENTPROGRAM,T_INUMBERPOINT,T_INUMBERFATHER,T_INUMBERLINE,T_ICASEITEM,T_CSYSTEMITEM,T_SZNAMEITEM,T_SZNAMEPROMPT,T_IHELP,T_IPROGITEM)
               VALUES(1036,'X',83,v_NumberPoint,v_ParentID,10,20209,'X',' Отчет по СНОБ и удержанному НДФЛ','Отчет по СНОБ и удержанному НДФЛ',0,83);


   v_NumberPoint := v_NumberPoint + 1;

   INSERT INTO DMENUITEM_DBT(T_OBJECTID,T_ISTEMPLATE,T_IIDENTPROGRAM,T_INUMBERPOINT,T_INUMBERFATHER,T_INUMBERLINE,T_ICASEITEM,T_CSYSTEMITEM,T_SZNAMEITEM,T_SZNAMEPROMPT,T_IHELP,T_IPROGITEM)
               VALUES(1036,'X',83,v_NumberPoint,v_ParentID,20,20210,'X',' История операций по ФЛ','Отчет "История операций по ФЛ"',0,83);


   v_NumberPoint := v_NumberPoint + 1;

   INSERT INTO DMENUITEM_DBT(T_OBJECTID,T_ISTEMPLATE,T_IIDENTPROGRAM,T_INUMBERPOINT,T_INUMBERFATHER,T_INUMBERLINE,T_ICASEITEM,T_CSYSTEMITEM,T_SZNAMEITEM,T_SZNAMEPROMPT,T_IHELP,T_IPROGITEM)
               VALUES(1036,'X',83,v_NumberPoint,0,60,0,'X',' Р~а~зное','Разное',399,83);

   v_ParentID := v_NumberPoint;

   v_NumberPoint := v_NumberPoint + 1;

   INSERT INTO DMENUITEM_DBT(T_OBJECTID,T_ISTEMPLATE,T_IIDENTPROGRAM,T_INUMBERPOINT,T_INUMBERFATHER,T_INUMBERLINE,T_ICASEITEM,T_CSYSTEMITEM,T_SZNAMEITEM,T_SZNAMEPROMPT,T_IHELP,T_IPROGITEM)
               VALUES(1036,'X',83,v_NumberPoint,v_ParentID,10,9999,'X',' Вы~х~од','Выход из программы',320,83);

   v_NumberPoint := v_NumberPoint + 1;

   INSERT INTO DMENUITEM_DBT(T_OBJECTID,T_ISTEMPLATE,T_IIDENTPROGRAM,T_INUMBERPOINT,T_INUMBERFATHER,T_INUMBERLINE,T_ICASEITEM,T_CSYSTEMITEM,T_SZNAMEITEM,T_SZNAMEPROMPT,T_IHELP,T_IPROGITEM)
               VALUES(1036,'X',83,v_NumberPoint,v_ParentID,110,9993,'X',' В~ы~бор операционного дня','Выбор операционного дня',0,83);


EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
