--Обновление статуса блока операции
DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 14933
       AND T_BLOCKID = 1493304;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID <> 0 THEN
    UPDATE DOPRCBLCK_DBT
       SET T_STATUSKINDID = 1105
     WHERE T_OPERBLOCKID = v_OperBlockID;
  END IF;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/