--Установка постобработки на шаг
BEGIN
    UPDATE DOPROSTEP_DBT SET T_POST_MACRO = 'dvsw140.mac' WHERE T_BLOCKID = 20000638 AND T_NUMBER_STEP = 140;
EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
END;
/