--Добавление блока и шага для операции расчета НОБ
DECLARE
BEGIN
  INSERT INTO DOPRSTKND_DBT(T_STATUSKINDID,T_CODE,T_NAME,T_DOCKIND,T_SORT,T_ELIMINATED)
  VALUES(46058,'ОТМ','Отмена прежних событий СНОБ',4605,0,CHR(0));


  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(46058,1,'Выполнить',CHR(0));

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
  VALUES(46058,2,'Завершить',CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(203515,'Отмена прежних событий СНОБ',4605,0,CHR(0),CHR(1),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(203515,104,1,0,0,CHR(0),0,CHR(0),0,0,'nptxcalc104.mac',CHR(1),'nptxcalc104.mac',CHR(0),CHR(0),'Отмена прежних записей о событиях СНОБ',460500000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  UPDATE doprostep_dbt
      SET t_post_macro = t_carry_macro
    WHERE T_BLOCKID IN (201000, 201100) AND t_number_step in (30, 40);

EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203506,46058,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203510,46058,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203513,46058,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203514,46058,1,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203515,46056,1,'X');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203515,46058,2,'X');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 2035
       AND T_BLOCKID = 203515;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN

    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,2035,203515,16,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,46058,1,0);

  END IF;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/