DECLARE
    e_col_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT (e_col_exist, -01430);
BEGIN
    EXECUTE IMMEDIATE 'DELETE FROM DDL_REGIABUF_DBT';
    COMMIT;
    EXECUTE IMMEDIATE 'ALTER TABLE DDL_REGIABUF_DBT MODIFY ( ' || 
            't_plandatem VARCHAR2(128),'  ||
			't_factdatem VARCHAR2(128)'  ||
        ')';

EXCEPTION WHEN e_col_exist THEN NULL;
END;
/
