BEGIN
  INSERT INTO DOBJGROUP_DBT (T_OBJECTTYPE, T_GROUPID, T_TYPE, T_NAME, T_SYSTEM, T_ORDER, T_MACRONAME, T_KEEPOLDVALUES,
                             T_UPDATEFLAG, T_SUCCESSOPFLAG, T_ATTROBJECTTYPE, T_ATTRGROUPID, T_ISHIDDEN, T_FULLNAMEISBASIC,
                             T_SYSHIDDEN, T_NOTUSEFIELDUSE, T_ISMEANPARENTNODE, T_ISMANUALFIRST, T_COMMENT)
                     VALUES (12,130,'X','Вхождение иностранного выпуска в группу инструментов <российские ценные бумаги>',CHR(0),130,CHR(1),CHR(0),0,CHR(0),0,0,CHR(0),CHR(0),CHR(0),CHR(0),CHR(0),CHR(0),CHR(1));

EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  INSERT INTO DOBJATTR_DBT (T_OBJECTTYPE, T_GROUPID, T_ATTRID, T_PARENTID, T_CODELIST, T_NUMINLIST, T_NAMEOBJECT, T_CHATTR, T_LONGATTR, T_INTATTR,
                            T_NAME, T_FULLNAME, T_OPENDATE, T_CLOSEDATE, T_CLASSIFICATOR, T_CORRACTYPE, T_BALANCE, T_ISOBJECT)
                    VALUES (12,130,1,0,CHR(1),'1','1',CHR(0),0,0,'Да','Да',TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE('01-01-0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),0,CHR(1),CHR(1),CHR(0));                      
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
INSERT INTO DOBJATCOR_DBT(T_OBJECTTYPE, T_GROUPID, T_ATTRID, T_OBJECT, T_GENERAL, T_VALIDFROMDATE, T_OPER, T_VALIDTODATE, T_SYSDATE, T_SYSTIME, T_ISAUTO, T_ID)
  SELECT 12,
         130, /*Вхождение иностранного выпуска в группу инструментов <российские ценные бумаги>*/
         1, /*Да*/
         LPAD(AVOIR.T_FIID,10,'0'),
         'X',
         TRUNC(SYSDATE),
         9997,
         TO_DATE('31.12.9999','DD.MM.YYYY'),
         TRUNC(SYSDATE),
         TO_DATE('01.01.0001 ' || TO_CHAR(SYSDATE, 'HH24:MI:SS'),'DD.MM.YYYY HH24:MI:SS'),
         'X',
         0
    FROM DAVOIRISS_DBT AVOIR
   WHERE AVOIR.T_ISIN IN ('US33835G2057','US87238U2033');
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

