DECLARE
    e_col_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT (e_col_exist, -01430);
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DDL_REGIA_LOG_DBT ADD T_LINKID NUMBER(20)';

EXCEPTION WHEN e_col_exist THEN NULL;
END;
/
