drop TABLE SOFR_CONTRACTBOOUT;
CREATE TABLE SOFR_CONTRACTBOOUT 
   (	CONTRACTID VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	CONTRACTNUMBER VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	CONTRACTDATE DATE NOT NULL ENABLE,
	TYPETP NUMBER(10,0) NOT NULL ENABLE,
	FUNDS VARCHAR2(100 CHAR), 
	CLIENTTYPE NUMBER(10,0) NOT NULL ENABLE, 
	CLIENTID VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	BRANCHID VARCHAR2(4 CHAR) NOT NULL ENABLE,
	CODECLI VARCHAR2(10 CHAR),
	MGRCLI VARCHAR2(100 CHAR),
	REGPLACECLI VARCHAR2(100 CHAR),
	RESULTCODE VARCHAR2(100 CHAR),
	RESULTTEXT VARCHAR2(500 CHAR),
	t_timestamp date 
	) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;

   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.CONTRACTID IS 'ИД договора в СОФР';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.CONTRACTNUMBER IS 'Номер договора';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.CONTRACTDATE IS 'Дата открытия договора';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.TYPETP IS 'Тип торговой площадки 	1 - ММВБ, 2 - Внебиржа'; 
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.FUNDS IS 'Буквенное обозначение валют через запятую, в которых будут происходить расчеты по договорую Например: RUB, USD';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.CLIENTTYPE IS 'Тип клиента	1 - ФЛ, 2 - ЮЛ';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.CLIENTID IS 'ИД клиента ';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.BRANCHID IS '4-х значный код филиала';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.CODECLI IS 'Уникальный код клиента на Бирже';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.MGRCLI IS 'Менеджер клиента';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.REGPLACECLI IS 'Место регистрации клиента';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.RESULTCODE IS 'Код ошибки';
   COMMENT ON COLUMN SOFR_CONTRACTBOOUT.RESULTTEXT IS 'Текст ошибки';
  
  