 drop TABLE SOFR_CONTRACTBORESULT;
 CREATE TABLE SOFR_CONTRACTBORESULT 
   (	CONTRACTID VARCHAR2(100 CHAR) NOT NULL , 
	CONTRACTNUMBER VARCHAR2(100 CHAR) NOT NULL,
	CONTRACTDATE DATE NOT NULL ,
	TYPETP NUMBER(10) NOT NULL ,
	FUNDS VARCHAR2(100 CHAR), 
	CLIENTTYPE NUMBER(10) NOT NULL ,
	CLIENTID VARCHAR2(10 CHAR) NOT NULL ,
	BRANCHID VARCHAR2(4 CHAR) NOT NULL ,
	CODECLI VARCHAR2(10 CHAR), 
	MGRCLI VARCHAR2(100 CHAR), 
	REGPLACECLI VARCHAR2(100 CHAR), 
	RESULTCODE VARCHAR2(100 CHAR), 
	RESULTTEXT VARCHAR2(500 CHAR),
	t_timestamp date 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;

   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.CONTRACTNUMBER IS 'Номер договора';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.CONTRACTDATE IS 'Дата договора обслуживания';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.TYPETP IS 'Тип торговой площадки 	1 ? ММВБ, 2 ? Внебиржа';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.FUNDS IS 'Буквенное обозначение валют через запятую, в которых будут происходить расчеты по договорую Например: RUB, USD';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.CLIENTTYPE IS 'Тип клиента	1 - ФЛ, 2 - ЮЛ';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.CLIENTID IS 'ИД клиента из Бисквит';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.BRANCHID IS '4-х значный код филиала из Бисквит';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.CODECLI IS 'Уникальный код клиента на Бирже';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.MGRCLI IS 'Менеджер клиента';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.REGPLACECLI IS 'Место регистрации клиента';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.RESULTCODE IS 'Код ошибки';
   COMMENT ON COLUMN SOFR_CONTRACTBORESULT.RESULTTEXT IS 'Текст ошибки';
   COMMENT ON TABLE SOFR_CONTRACTBORESULT  IS 'Таблица обработки результатов договоров БО';
