drop TABLE SOFR_CONTACCDEPOIN;
CREATE TABLE SOFR_CONTACCDEPOIN 
   (	RECID NUMBER(*,0) NOT NULL ENABLE, 
	CONTRACTNUMBER VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	CONTRACTDATE DATE NOT NULL ENABLE, 
	DEPONUMBER VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	DEPODATE DATE NOT NULL ENABLE, 
	DEPOID VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	ACCDEPONUMBER VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	SECTIONCODE VARCHAR2(30 CHAR) NOT NULL ENABLE,
	t_timestamp date 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;

   COMMENT ON COLUMN SOFR_CONTACCDEPOIN.RECID IS 'ИД записи';
   COMMENT ON COLUMN SOFR_CONTACCDEPOIN.CONTRACTNUMBER IS 'Номер Договора брокерского обслуживания ';
   COMMENT ON COLUMN SOFR_CONTACCDEPOIN.CONTRACTDATE IS 'Дата открытия Договора брокерского обслуживания ';
   COMMENT ON COLUMN SOFR_CONTACCDEPOIN.DEPONUMBER IS 'Номер Договора ДЕПО ';
   COMMENT ON COLUMN SOFR_CONTACCDEPOIN.DEPODATE IS 'Дата Договора ДЕПО ';
   COMMENT ON COLUMN SOFR_CONTACCDEPOIN.DEPOID IS 'ИД Договора ДЕПО ';
   COMMENT ON COLUMN SOFR_CONTACCDEPOIN.ACCDEPONUMBER IS 'Номер сводного счета ';
   COMMENT ON COLUMN SOFR_CONTACCDEPOIN.SECTIONCODE IS 'Обозначение раздела ';
   COMMENT ON TABLE SOFR_CONTACCDEPOIN  IS 'Таблица договоров и счетов Депо';
