drop TABLE SOFR_CONTACCDEPORESULT; 
CREATE TABLE SOFR_CONTACCDEPORESULT 
   (	RECID NUMBER(*,0) NOT NULL ENABLE, 
	CONTRACTNUMBER VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	CONTRACTDATE DATE NOT NULL ENABLE, 
	DEPONUMBER VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	DEPODATE DATE NOT NULL ENABLE, 
	DEPOID VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	ACCDEPONUMBER VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	SECTIONCODE VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	RESULTCODE VARCHAR2(100 CHAR), 
	RESULTTEXT VARCHAR2(500 CHAR),
	t_timestamp date 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;

   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.RECID IS 'ИД записи';
   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.CONTRACTNUMBER IS 'Номер Договора брокерского обслуживания';
   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.CONTRACTDATE IS 'Дата открытия Договора брокерского обслуживания ';
   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.DEPONUMBER IS 'Номер Договора ДЕПО ';
   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.DEPODATE IS 'Дата Договора ДЕПО ';
   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.DEPOID IS 'ИД Договора ДЕПО';
   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.ACCDEPONUMBER IS 'Номер сводного счета ';
   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.SECTIONCODE IS 'Код раздела';
   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.RESULTCODE IS 'Код ошибки';
   COMMENT ON COLUMN SOFR_CONTACCDEPORESULT.RESULTTEXT IS 'Текст ошибки';
   COMMENT ON TABLE SOFR_CONTACCDEPORESULT  IS 'Таблица результатов обработки договоров и счетов Депо в СОФР';
