CREATE TABLE SOFR_SverkaContDepoIn
   (	RECID NUMBER(*,0) NOT NULL ENABLE, 
	DEPONumber  VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	AccDEPONumber  VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	SectionCode  VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	ContractNumber  VARCHAR2(100 CHAR) NOT NULL ENABLE,
	t_timestamp date 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;

   COMMENT ON COLUMN SOFR_SverkaContDepoIn.RECID IS 'ИД записи';
   COMMENT ON COLUMN SOFR_SverkaContDepoIn.DEPONumber IS 'Номер Договора ДЕПО ';
   COMMENT ON COLUMN SOFR_SverkaContDepoIn.AccDEPONumber IS 'Номер сводного счета ДЕПО ';
   COMMENT ON COLUMN SOFR_SverkaContDepoIn.SectionCode IS 'Обозначение раздела ДЕПО ';
   COMMENT ON COLUMN SOFR_SverkaContDepoIn.ContractNumber IS 'Номер Договора брокерского обслуживания ';
   COMMENT ON TABLE SOFR_SverkaContDepoIn  IS 'Таблица данных по счетам ДЕПО для сверки';

  CREATE UNIQUE INDEX SOFR_SverkaContDepoIn_IDX0 ON SOFR_SverkaContDepoIn (RECID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS;
  
  CREATE SEQUENCE SOFR_SverkaContDepoIn_SEQ_1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

  CREATE OR REPLACE TRIGGER SOFR_SverkaContDepoIn_T0_AINC 
 BEFORE INSERT OR UPDATE OF RECID ON SOFR_SVERKARESTDEPOIN FOR EACH ROW
DECLARE
    v_id INTEGER;
BEGIN
    IF (:new.RECID = 0 OR :new.RECID IS NULL)
    THEN
        SELECT SOFR_SverkaContDepoIn_SEQ_1.nextval INTO :new.RECID FROM dual;
    ELSE
        SELECT last_number INTO v_id FROM user_sequences WHERE sequence_name = UPPER ('SOFR_SverkaContDepoIn_SEQ_1');
            IF :new.RECID >= v_id
            THEN
                RAISE DUP_VAL_ON_INDEX;
            END IF;
    END IF;
END;