CREATE TABLE SOFR_SverkaAccDepoRestIn
   (	RECID NUMBER(*,0) NOT NULL ENABLE, 
	AccDepoID  NUMBER(*,0) NOT NULL ENABLE, 
	ReportDate  DATE NOT NULL ENABLE, 
	ISIN  VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	PValue  NUMBER(*,0) NOT NULL ENABLE,
	t_timestamp date 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN SOFR_SverkaAccDepoRestIn.RECID IS 'ИД записи';
   COMMENT ON COLUMN SOFR_SverkaAccDepoRestIn.AccDepoID IS 'ИД записи в таблице счетов ';
   COMMENT ON COLUMN SOFR_SverkaAccDepoRestIn.ReportDate IS 'Дата сведений ';
   COMMENT ON COLUMN SOFR_SverkaAccDepoRestIn.ISIN IS 'Код ЦБ (ISIN)';
   COMMENT ON COLUMN SOFR_SverkaAccDepoRestIn.PValue IS 'Количество ЦБ';
   COMMENT ON TABLE SOFR_SverkaAccDepoRestIn  IS 'Таблица данных по остаткам по счетам ДЕПО для сверки';

  CREATE UNIQUE INDEX SOFR_SverkaAccDepoRestIn_IDX0 ON SOFR_SverkaAccDepoRestIn (RECID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
  
  CREATE SEQUENCE SOFR_SverkaAccDepoRestIn_SEQ_1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

  CREATE OR REPLACE TRIGGER SOFR_SverkaDepoRestIn_T0_AINC 
 BEFORE INSERT OR UPDATE OF RECID ON SOFR_SverkaAccDepoRestIn FOR EACH ROW
DECLARE
    v_id INTEGER;
BEGIN
    IF (:new.RECID = 0 OR :new.RECID IS NULL)
    THEN
        SELECT SOFR_SverkaAccDepoRestIn_SEQ_1.nextval INTO :new.RECID FROM dual;
    ELSE
        SELECT last_number INTO v_id FROM user_sequences WHERE sequence_name = UPPER ('SOFR_SverkaAccDepoRestIn_SEQ_1');
            IF :new.RECID >= v_id
            THEN
                RAISE DUP_VAL_ON_INDEX;
            END IF;
    END IF;
END;