/* ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
   RS-Bank V6                                                 R-Style Softlab
   ” ©« ¯®¤á¨áâ¥¬ë "¥£« ¬¥­â¨à®¢ ­­ ï ®âç¥â­®áâì"

   ”®à¬  901. Š« áá ®âç¥â .

   CREATED : 17.08.2013 ABP.
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ */
class (RcbReportBase) TF901Report(report : RcbReport, isLazy : Bool)
    private macro initialize()
        addPart("1", getRcbReport().attributeValue("„ ­­ë¥âç¥â ")).initialize();
    end;

    macro isEmpty()
        m_parts.moveFirst();
        while (m_parts.moveNext())
            if (not m_parts.getCurrentItem().isEmpty())
                return false;
            end;
        end;

        return true;
    end;

    private macro constructorTF901Report(report : RcbReport, isLazy : Bool)
        initRcbReportBase(report, isLazy);
    end;

    constructorTF901Report(report, isLazy);
end;
