/*
$Name:          Ofr_export_ea.mac
$Module:        Регламентируемая отчетность
$Description:   Выгрузка ОФР в реестр отчетов.
*/

import OfrImport;

/**
 * Получить имя файла печатной формы 
 */

macro getPrintableReportView()
    var fileName = objectFactoryInstance.createApplicationReportView(objectFactoryInstance.createPrintProtocolView()).getFileName();
    return getTxtFileName(fileName);
end;

