-- Таблица
DROP TABLE DNPTXOP1OPLNK_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE DNPTXOP1OPLNK_TMP
(
  T_DOCID         NUMBER(10),
  T_PARENT_DOCID  NUMBER(10),
  T_AMOUNT        NUMBER(32,12)
)
/
