


BEGIN
  EXECUTE IMMEDIATE 'drop table LDR_INFA_PFI.DET_ACCOUNT_SOFR';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table LDR_INFA_PFI.DET_ACC_ASS_KIND';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table LDR_INFA_PFI.FCT_ACCOUNT_SOFR';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table LDR_INFA_PFI.TMP_ACC306';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table LDR_INFA_PFI.TMP_ACC_SUBJ_306';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table LDR_INFA_PFI.ASS_DET_ACCOUNT_SOFR';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/


CREATE TABLE "LDR_INFA_PFI"."DET_ACCOUNT_SOFR" 
   (  "CODE" VARCHAR2(100), 
  "ACCOUNT_NUMBER" VARCHAR2(30), 
  "ACCOUNT_NAME" VARCHAR2(250), 
  "IS_INCONSOLIDATE" VARCHAR2(2), 
  "DT_OPEN_ACC" VARCHAR2(10), 
  "DT_CLOSE_ACC" VARCHAR2(10), 
  "SYSTEM_CODE" VARCHAR2(100), 
  "SUBJECT_CODE" VARCHAR2(100), 
  "FINSTR_CODE" VARCHAR2(30), 
  "DEPARTMENT_CODE" VARCHAR2(30), 
  "CURRENCY_CODE_TXT" VARCHAR2(3), 
  "CHAPTER_CODE" VARCHAR2(1), 
  "DT" VARCHAR2(10), 
  "REC_STATUS" VARCHAR2(2), 
  "SYSMOMENT" VARCHAR2(20), 
  "EXT_FILE" VARCHAR2(300)
   ) /
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."CODE" IS 'Код аналитического счёта СОФР'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."ACCOUNT_NUMBER" IS 'Номер аналитического счёта СОФР'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."ACCOUNT_NAME" IS 'Наименование аналитического счёта СОФР'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."IS_INCONSOLIDATE" IS 'Значения из домена DD_BOOLEAN'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."DT_OPEN_ACC" IS 'Дата открытия счёта'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."DT_CLOSE_ACC" IS 'Дата закрытия счёта'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."SYSTEM_CODE" IS 'Код учётной системы'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."SUBJECT_CODE" IS 'Код субъекта экономической деятельности'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."FINSTR_CODE" IS 'Код фининструмента, для учёта которого открыт счёт'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."DEPARTMENT_CODE" IS 'Код подразделения'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."CURRENCY_CODE_TXT" IS 'Код валюты, в которой номинирован счёт'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."CHAPTER_CODE" IS 'Код главы'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."DT" IS 'Дата открытия записи'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."REC_STATUS" IS 'Статус записи'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."SYSMOMENT" IS 'Момент выгрузки'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"."EXT_FILE" IS 'Идентификатор порции данных'/
   COMMENT ON TABLE "LDR_INFA_PFI"."DET_ACCOUNT_SOFR"  IS 'Аналитические счета СОФР'/
  GRANT DELETE ON "LDR_INFA_PFI"."DET_ACCOUNT_SOFR" TO PUBLIC/
  GRANT INSERT ON "LDR_INFA_PFI"."DET_ACCOUNT_SOFR" TO PUBLIC/
  GRANT SELECT ON "LDR_INFA_PFI"."DET_ACCOUNT_SOFR" TO PUBLIC/
  GRANT UPDATE ON "LDR_INFA_PFI"."DET_ACCOUNT_SOFR" TO PUBLIC/




CREATE TABLE "LDR_INFA_PFI"."DET_ACC_ASS_KIND" 
   (	"ACC_ASS_KIND_CODE" VARCHAR2(100), 
	"ACC_ASS_KIND_NAME" VARCHAR2(250), 
	"DT" VARCHAR2(10), 
	"REC_STATUS" VARCHAR2(2), 
	"SYSMOMENT" VARCHAR2(20), 
	"EXT_FILE" VARCHAR2(300)
   )  /
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACC_ASS_KIND"."ACC_ASS_KIND_CODE" IS 'Код отношения между лицевыми счетами'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACC_ASS_KIND"."ACC_ASS_KIND_NAME" IS 'Наименование отношения между лицевыми счетами'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACC_ASS_KIND"."DT" IS 'Дата открытия записи'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACC_ASS_KIND"."REC_STATUS" IS 'Статус записи'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACC_ASS_KIND"."SYSMOMENT" IS 'Момент выгрузки'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."DET_ACC_ASS_KIND"."EXT_FILE" IS 'Идентификатор порции данных'/
   COMMENT ON TABLE "LDR_INFA_PFI"."DET_ACC_ASS_KIND"  IS 'Тип связи между лицевыми счетами'/

  GRANT DELETE ON "LDR_INFA_PFI"."DET_ACC_ASS_KIND" TO PUBLIC/
  GRANT INSERT ON "LDR_INFA_PFI"."DET_ACC_ASS_KIND" TO PUBLIC/
  GRANT SELECT ON "LDR_INFA_PFI"."DET_ACC_ASS_KIND" TO PUBLIC/
  GRANT UPDATE ON "LDR_INFA_PFI"."DET_ACC_ASS_KIND" TO PUBLIC/
  
  
  CREATE TABLE "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR" 
   (  "ACCOUNT_SOFR_CODE" VARCHAR2(100), 
  "REST" VARCHAR2(26), 
  "REST_NAT" VARCHAR2(26), 
  "DEBET" VARCHAR2(26), 
  "DEBET_NAT" VARCHAR2(26), 
  "CREDIT" VARCHAR2(26), 
  "CREDIT_NAT" VARCHAR2(26), 
  "DT" VARCHAR2(10), 
  "SYSMOMENT" VARCHAR2(20), 
  "REC_STATUS" VARCHAR2(2), 
  "EXT_FILE" VARCHAR2(300)
   ) /
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."ACCOUNT_SOFR_CODE" IS 'Код аналитического счёта СОФР'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."REST" IS 'Остаток в валюте счёта на конец операционного дня'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."REST_NAT" IS 'Остаток в национальной валюте на конец операционного дня'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."DEBET" IS 'Оборот по дебету в валюте счёта на конец операционного дня'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."DEBET_NAT" IS 'Оборот по дебету в национальной валюте на конец операционного дня'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."CREDIT" IS 'Оборот по кредиту в валюте счёта на конец операционного дня'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."CREDIT_NAT" IS 'Оборот по кредиту в национальной валюте на конец операционного дня'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."DT" IS 'Дата открытия записи'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."SYSMOMENT" IS 'Момент выгрузки'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."REC_STATUS" IS 'Статус записи'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"."EXT_FILE" IS 'Идентификатор порции данных'/
   COMMENT ON TABLE "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR"  IS 'Остатки и обороты по аналитическим счетам СОФР'/
  GRANT DELETE ON "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR" TO PUBLIC/
  GRANT INSERT ON "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR" TO PUBLIC/
  GRANT SELECT ON "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR" TO PUBLIC/
  GRANT UPDATE ON "LDR_INFA_PFI"."FCT_ACCOUNT_SOFR" TO PUBLIC/


CREATE TABLE "LDR_INFA_PFI"."TMP_ACC306" 
   (  "T_ACCOUNTID" NUMBER(10,0), 
  "T_ACCOUNT" VARCHAR2(25) NOT NULL ENABLE, 
  "T_NAMEACCOUNT" VARCHAR2(1000), 
  "T_LEGALFORM" NUMBER(5,0), 
  "T_OPEN_DATE" DATE, 
  "T_CLOSE_DATE" DATE, 
  "T_CLIENT" NUMBER(10,0), 
  "T_DEPARTMENT" NUMBER(5,0), 
  "T_NAME" VARCHAR2(12), 
  "T_CODE_CURRENCY" NUMBER(10,0), 
  "T_CCY" VARCHAR2(3), 
  "T_FI_CODE" VARCHAR2(15), 
  "T_NOTRESIDENT" CHAR(1), 
  "T_NRCOUNTRY" VARCHAR2(3), 
  "T_USERFIELD4" VARCHAR2(80)
   )  /

  GRANT DELETE ON "LDR_INFA_PFI"."TMP_ACC306" TO PUBLIC/
  GRANT INSERT ON "LDR_INFA_PFI"."TMP_ACC306" TO PUBLIC/
  GRANT SELECT ON "LDR_INFA_PFI"."TMP_ACC306" TO PUBLIC/
  GRANT UPDATE ON "LDR_INFA_PFI"."TMP_ACC306" TO PUBLIC/

  
  CREATE TABLE "LDR_INFA_PFI"."TMP_ACC_SUBJ_306" 
   (	"T_ACCOUNTID" NUMBER(10,0), 
	"T_ACCOUNT" VARCHAR2(25), 
	"T_PARTYID" NUMBER(10,0), 
	"SUBJECT_CODE" VARCHAR2(100)
   ) /
  GRANT DELETE ON "LDR_INFA_PFI"."TMP_ACC_SUBJ_306" TO "PUBLIC"/
  GRANT INSERT ON "LDR_INFA_PFI"."TMP_ACC_SUBJ_306" TO "PUBLIC"/
  GRANT SELECT ON "LDR_INFA_PFI"."TMP_ACC_SUBJ_306" TO "PUBLIC"/
  GRANT UPDATE ON "LDR_INFA_PFI"."TMP_ACC_SUBJ_306" TO "PUBLIC"/
  
  
  CREATE TABLE "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR" 
   (	"ACC_ASS_KIND_CODE" VARCHAR2(100), 
	"ACCOUNT_PAR_CODE" VARCHAR2(100), 
	"ACCOUNT_SOFR_CHI_CODE" VARCHAR2(100), 
	"DT" VARCHAR2(10), 
	"SYSMOMENT" VARCHAR2(20), 
	"REC_STATUS" VARCHAR2(2), 
	"EXT_FILE" VARCHAR2(300)
   )/
   COMMENT ON COLUMN "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR"."ACC_ASS_KIND_CODE" IS 'Код отношения между счетами СОФР'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR"."ACCOUNT_PAR_CODE" IS 'Код сводного счета ? родителя'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR"."ACCOUNT_SOFR_CHI_CODE" IS 'Код аналитического счета СОФР ? потомка'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR"."DT" IS 'Дата открытия записи'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR"."SYSMOMENT" IS 'Момент выгрузки'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR"."REC_STATUS" IS 'Статус записи'/
   COMMENT ON COLUMN "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR"."EXT_FILE" IS 'Идентификатор порции данных'/
   COMMENT ON TABLE "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR"  IS 'Ассоциатор связи аналитических и сводных счетов'/
  GRANT DELETE ON "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR" TO PUBLIC/
  GRANT INSERT ON "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR" TO PUBLIC/
  GRANT SELECT ON "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR" TO PUBLIC/
  GRANT UPDATE ON "LDR_INFA_PFI"."ASS_DET_ACCOUNT_SOFR" TO PUBLIC/

  
