/*Добавить записи*/
BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,1,2,TO_DATE('01.01.2023','DD.MM.YYYY'),TO_DATE('31.12.2024','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,1,3,TO_DATE('01.01.2023','DD.MM.YYYY'),TO_DATE('31.12.2024','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,1,4,TO_DATE('01.01.2023','DD.MM.YYYY'),TO_DATE('31.12.2024','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,1,5,TO_DATE('01.01.2023','DD.MM.YYYY'),TO_DATE('31.12.2024','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,1,6,TO_DATE('01.01.2023','DD.MM.YYYY'),TO_DATE('31.12.2024','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,3,2,TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,3,3,TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,3,4,TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,3,5,TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,3,7,TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNPTXLINKSKINDSNOB_DBT(T_ID, T_TYPESNOB, T_TAXBASETYPE, T_BEGDATETYPESNOB, T_ENDDATETYPESNOB, T_USER, T_DREC)
   VALUES (0,2,6,TO_DATE('01.01.2025','DD.MM.YYYY'),TO_DATE('31.12.9999','DD.MM.YYYY'),1,TO_DATE('31.10.2024','DD.MM.YYYY'));
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/
