-- Таблица "DDLCONTRFROBCH_DBT"

CREATE TABLE DDLCONTRFROBCH_DBT (
    T_ID NUMBER(10)
  , T_FROBID NUMBER(10)
  , T_TAXPERIOD_OLD NUMBER(5)
  , T_INCOMECODE_OLD NUMBER(5)
  , T_INCOMESUM_OLD NUMBER(32,12)
  , T_DEDUCTIONCODE_OLD NUMBER(5)
  , T_DEDUCTIONSUM_OLD NUMBER(32,12)
  , T_TAXPERIOD_NEW NUMBER(5)
  , T_INCOMECODE_NEW NUMBER(5)
  , T_INCOMESUM_NEW NUMBER(32,12)
  , T_DEDUCTIONCODE_NEW NUMBER(5)
  , T_DEDUCTIONSUM_NEW NUMBER(32,12)
  , T_OPER NUMBER(5)
  , T_CHANGEDATE DATE
  , T_CHANGETIME DATE
)
/

COMMENT ON TABLE DDLCONTRFROBCH_DBT IS 'Изменение записей ФР ДБО'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_ID IS 'Идентификатор записи'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_FROBID IS 'Идентификатор записи об ФР ДБО'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_TAXPERIOD_OLD IS 'Прежний налоговый период'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_INCOMECODE_OLD IS 'Прежний код дохода'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_INCOMESUM_OLD IS 'Прежняя сумма дохода'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_DEDUCTIONCODE_OLD IS 'Прежний код вычета'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_DEDUCTIONSUM_OLD IS 'Прежняя сумма вычета'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_TAXPERIOD_NEW IS 'Новый налоговый период'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_INCOMECODE_NEW IS 'Новый код дохода'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_INCOMESUM_NEW IS 'Новая сумма дохода'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_DEDUCTIONCODE_NEW IS 'Новый код вычета'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_DEDUCTIONSUM_NEW IS 'Новая сумма вычета'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_OPER IS 'Операционист, изменивший запись'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_CHANGEDATE IS 'Дата изменения'/
COMMENT ON COLUMN DDLCONTRFROBCH_DBT.T_CHANGETIME IS 'Время изменения'/

CREATE UNIQUE INDEX DDLCONTRFROBCH_DBT_IDX0 ON DDLCONTRFROBCH_DBT (
   T_ID ASC
)
/

CREATE   INDEX DDLCONTRFROBCH_DBT_IDX1 ON DDLCONTRFROBCH_DBT (
   T_FROBID ASC
)
/

CREATE SEQUENCE DDLCONTRFROBCH_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DDLCONTRFROBCH_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDLCONTRFROBCH_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDLCONTRFROBCH_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDLCONTRFROBCH_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
