-- Таблица "DNPTXLINKSKINDSNOBCH_DBT"

CREATE TABLE DNPTXLINKSKINDSNOBCH_DBT (
    T_ID NUMBER(10)
  , T_LNKID NUMBER(10)
  , T_TYPESNOB_OLD NUMBER(10)
  , T_TAXBASETYPE_OLD NUMBER(10)
  , T_BEGDATETYPESNOB_OLD DATE
  , T_ENDDATETYPESNOB_OLD DATE
  , T_TYPESNOB_NEW NUMBER(10)
  , T_TAXBASETYPE_NEW NUMBER(10)
  , T_BEGDATETYPESNOB_NEW DATE
  , T_ENDDATETYPESNOB_NEW DATE
  , T_USER NUMBER(5)
  , T_DREC DATE
)
/

COMMENT ON TABLE DNPTXLINKSKINDSNOBCH_DBT IS 'Изм. настр. табл. связи видов НОБ и СНОБ'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_ID IS 'Идентификатор записи'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_LNKID IS 'Идентификатор записи из настроечной таблицы'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_TYPESNOB_OLD IS 'Прежний вид СНОБ'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_TAXBASETYPE_OLD IS 'Прежний вид НОБ для Хранилища'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_BEGDATETYPESNOB_OLD IS 'Прежняя дата начала действия'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_ENDDATETYPESNOB_OLD IS 'Прежняя дата окончания действия'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_TYPESNOB_NEW IS 'Новый вид СНОБ'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_TAXBASETYPE_NEW IS 'Новый вид НОБ для Хранилища'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_BEGDATETYPESNOB_NEW IS 'Новая дата начала действия'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_ENDDATETYPESNOB_NEW IS 'Новая дата окончания действия'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_USER IS 'Пользователь, изменившый запись'/
COMMENT ON COLUMN DNPTXLINKSKINDSNOBCH_DBT.T_DREC IS 'Дата изменения'/

CREATE UNIQUE INDEX DNPTXLINKSKINDSNOBCH_DBT_IDX0 ON DNPTXLINKSKINDSNOBCH_DBT (
   T_ID ASC
)
/

CREATE   INDEX DNPTXLINKSKINDSNOBCH_DBT_IDX1 ON DNPTXLINKSKINDSNOBCH_DBT (
   T_LNKID ASC
)
/

CREATE SEQUENCE DNPTXLINKSKINDSNOBCH_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXLINKSKINDSNOBCH_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXLINKSKINDSNOBCH_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXLINKSKINDSNOBCH_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXLINKSKINDSNOBCH_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
