-- Таблица "DNPTXSNOBLIMITCH_DBT"

CREATE TABLE DNPTXSNOBLIMITCH_DBT (
    T_ID NUMBER(10)
  , T_LIMID NUMBER(10)
  , T_ISRESIDENT_OLD CHAR(1)
  , T_TYPESNOB_OLD NUMBER(10)
  , T_LIMITSNOB_OLD NUMBER(32,12)
  , T_TAXRATE_OLD NUMBER(5)
  , T_CODEKBK_OLD NUMBER(10)
  , T_BEGDATESCALE_OLD DATE
  , T_ENDDATESCALE_OLD DATE
  , T_ISRESIDENT_NEW CHAR(1)
  , T_TYPESNOB_NEW NUMBER(10)
  , T_LIMITSNOB_NEW NUMBER(32,12)
  , T_TAXRATE_NEW NUMBER(5)
  , T_CODEKBK_NEW NUMBER(10)
  , T_BEGDATESCALE_NEW DATE
  , T_ENDDATESCALE_NEW DATE
  , T_USER NUMBER(5)
  , T_DREC DATE
)
/

COMMENT ON TABLE DNPTXSNOBLIMITCH_DBT IS 'Изм. настр. табл. предельных знач. СНОБ'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_ID IS 'Идентификатор записи'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_LIMID IS 'Идентификатор записи о лимите'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_ISRESIDENT_OLD IS 'Прежний признак резидента'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_TYPESNOB_OLD IS 'Прежний вид СНОБ'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_LIMITSNOB_OLD IS 'Прежнее предельное значение'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_TAXRATE_OLD IS 'Прежняя ставка'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_CODEKBK_OLD IS 'Прежний код КБК'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_BEGDATESCALE_OLD IS 'Прежняя дата начала действия шкалы'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_ENDDATESCALE_OLD IS 'Прежняя дата окончания действия шкалы'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_ISRESIDENT_NEW IS 'Новый признак резидента'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_TYPESNOB_NEW IS 'Новый вид СНОБ'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_LIMITSNOB_NEW IS 'Новое предельное значение'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_TAXRATE_NEW IS 'Новая ставка'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_CODEKBK_NEW IS 'Новый код КБК'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_BEGDATESCALE_NEW IS 'Новая дата начала действия шкалы'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_ENDDATESCALE_NEW IS 'Новая дата окончания действия шкалы'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_USER IS 'Пользователь, изменивший запись'/
COMMENT ON COLUMN DNPTXSNOBLIMITCH_DBT.T_DREC IS 'Дата изменения'/

CREATE UNIQUE INDEX DNPTXSNOBLIMITCH_DBT_IDX0 ON DNPTXSNOBLIMITCH_DBT (
   T_ID ASC
)
/

CREATE   INDEX DNPTXSNOBLIMITCH_DBT_IDX1 ON DNPTXSNOBLIMITCH_DBT (
   T_LIMID ASC
)
/

CREATE SEQUENCE DNPTXSNOBLIMITCH_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXSNOBLIMITCH_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXSNOBLIMITCH_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXSNOBLIMITCH_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXSNOBLIMITCH_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
