-- Таблица "DDLCONTRFROB_TMP"

CREATE GLOBAL TEMPORARY TABLE DDLCONTRFROB_TMP (
    T_ID NUMBER(10)
  , T_FROBID NUMBER(10)
  , T_DLCONTRID NUMBER(10)
  , T_TAXPERIOD NUMBER(5)
  , T_INCOMECODE NUMBER(5)
  , T_INCOMESUM NUMBER(32,12)
  , T_DEDUCTIONCODE NUMBER(5)
  , T_DEDUCTIONSUM NUMBER(32,12)
  , T_OPER NUMBER(5)
  , T_CHANGEDATE DATE
  , T_CHANGETIME DATE
  , T_VERSION NUMBER(5)
  , T_ACTION NUMBER(5)
) ON COMMIT PRESERVE ROWS
/

COMMENT ON TABLE DDLCONTRFROB_TMP IS 'Финрез по ДБО, получ. от другого брокера'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_ID IS 'Идентификатор записи'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_FROBID IS 'Идентификатор из постонной таблицы'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_DLCONTRID IS 'Идентификатор ДБО'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_TAXPERIOD IS 'Налоговый период'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_INCOMECODE IS 'Код дохода'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_INCOMESUM IS 'Сумма дохода'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_DEDUCTIONCODE IS 'Код вычета'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_DEDUCTIONSUM IS 'Сумма вычета'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_OPER IS 'Операционист, изменивший запись'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_CHANGEDATE IS 'Дата изменения'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_CHANGETIME IS 'Время изменения'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_VERSION IS 'Номер изменения записи'/
COMMENT ON COLUMN DDLCONTRFROB_TMP.T_ACTION IS 'Действие'/


CREATE UNIQUE INDEX DDLCONTRFROB_TMP_IDX0 ON DDLCONTRFROB_TMP (
   T_ID ASC
)
/

CREATE SEQUENCE DDLCONTRFROB_TMP_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DDLCONTRFROB_TMP_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDLCONTRFROB_TMP FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDLCONTRFROB_TMP_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDLCONTRFROB_TMP_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER DLCONTRFROB_TMP_TBIU
  BEFORE INSERT OR UPDATE 
  ON DDLCONTRFROB_TMP
  FOR EACH ROW
DECLARE
BEGIN

  :NEW.T_CHANGEDATE := TRUNC(SYSDATE);
  :NEW.T_CHANGETIME := TO_DATE('01-01-0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD-MM-YYYY:HH24:MI:SS'); 

END;
/
