DROP TABLE UBALANCERSHB_DBT CASCADE CONSTRAINTS;

CREATE TABLE UBALANCERSHB_DBT
(
  T_BALANCE       VARCHAR2(25 BYTE),
  T_KIND_ACCOUNT  VARCHAR2(2 BYTE),
  T_EXTKIND       VARCHAR2(2 BYTE),
  T_SHORTNAME     VARCHAR2(25 BYTE)
)
;


CREATE INDEX RSHB_SEC_TEST2.UBALANCERSHB_DBT_IDX0 ON UBALANCERSHB_DBT
(T_BALANCE)
;
