import ws_validation;
import ws_types;
import general;


class (IWindow) PanelWindow(params)
    var MenuType: integer;

    private macro SetPropertiesAndTitle(params)
        var recordId: integer = 0;
        var recordVersion: integer = 0;
        var refRecordId: integer = 0;
        var visaId: integer = 0;
        if (params.Params)
            refRecordId = params.Params;
        end;
        var tableName: string = "";
        var PKField: string = "";
        var cmd = TRslOraQuery();
        if (params.ScrollingId == 0)
            cmd.SqlText = "begin :Table := RSP_FORM.GET_MAINTABLEFORM(:FormId, 0); :PK := RSP_FORM.GET_PK_TABLE(:Table); end;";
            cmd.DeclareAndSet("Table", tableName, "FormId", params.FormId, "PK", PKField);
        else
            cmd.SqlText = "begin RSP_FORM.GET_TABLE_PK_FORMMENU(:IDNMenu, :Table, :PK); end;";
            cmd.DeclareAndSet("IDNMenu", params.ScrollingId, "Table", tableName, "PK", PKField);
        end;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        tableName = cmd.GetVariable("Table");
        PKField = cmd.GetVariable("PK");
        cmd.Clear();
        cmd.SqlText = "select id_smenu, id_formspr, decode(id_nformdn, null, id_nform, id_nformdn) FormId from NMENU where id_nmenu = :MenuId";
        cmd.DeclareAndSet("MenuId", params.ScrollingId);
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        if (params.PropIndex("MenuType") != -1)
            MenuType = params.MenuType;
        else
            MenuType = cmd.GetByName("id_smenu").AsInteger;
        end;
        if ((MenuType == TypeMainMenuDict) or (MenuType == TypeMenuDictRef))
            Id = cmd.GetByName("id_formspr").AsInteger;
            cmd.Clear();
            cmd.SqlText = "select RSP_COMMON.GET_NAME_BY_ID('FORM', :FormSprId) FormName from DUAL";
            cmd.DeclareAndSet("FormSprId", Id);
            if (not cmd.Execute())
                RunError(ToANSI(cmd.Error));
            end;
            if (params.PropIndex("CurrentRow") != -1)
                recordId = GenGetProp(params.CurrentRow, tableName + "8" + PKField);
                recordVersion = params.CurrentRow.VersionRec;
            end;
            Title = "Панель справочника \"" + cmd.GetByName("FormName").AsString + "\"";
        elif (MenuType == TypeMainMenuMacro)
            cmd.Clear();
            cmd.SqlText = "select TEXT as FormName from NFORM where ID_NFORM = :FormId";
            cmd.DeclareAndSet("FormId", params.formId);
            if (not cmd.Execute())
                RunError(ToANSI(cmd.Error));
            end;
            Title = cmd.GetByName("FormName").AsString;
            Id = params.formId;
        else
            if (params.PropIndex("CurrentRow") != -1)
                Id = params.CurrentRow.Id_NForm;
                cmd.Clear();
                cmd.SqlText = "select RSP_COMMON.GET_NAME_BY_ID('NFORM', :FormId) FormName from DUAL";
                cmd.DeclareAndSet("FormId", Id);
                if (not cmd.Execute())
                    RunError(ToANSI(cmd.Error));
                end;
                recordId = GenGetProp(params.CurrentRow, tableName + "8" + PKField);
                recordVersion = params.CurrentRow.VersionRec;
                if (MenuType == TypeMainMenuVisa)
                    visaId = params.CurrentRow.Id_NVTyp;
                end;
                Title = cmd.GetByName("FormName").AsString;
            else
                Id = cmd.GetByName("FormId").AsInteger;
                cmd.Clear();
                cmd.SqlText = "select RSP_COMMON.GET_NAME_BY_ID('NFORM', :FormId) FormName from DUAL";
                cmd.DeclareAndSet("FormId", Id);
                if (not cmd.Execute())
                    RunError(ToANSI(cmd.Error));
                end;
                Title = cmd.GetByName("FormName").AsString;
            end;
        end;
        var wParams = WebServiceParams(
            recordId,
            recordVersion,
            IIF((MenuType == TypeMenuFormDep) or (MenuType == TypeMenuDictRef), refRecordId, 0),
            IIF((MenuType == TypeMenuFormDep) or (MenuType == TypeMenuDictRef), params.ScrollingId, 0),
            IIF(MenuType == TypeMainMenuVisa, visaId, 0)
        );
        if ((MenuType == TypeMainMenuDict) or (MenuType == TypeMenuDictRef))
            GetObjectService = WebServiceCallback("ws_panel", "GetSprPanelObject", wParams.ToStr());
        elif (MenuType == TypeMainMenuMacro)
            wParams = Xml2Rsl(params.Params);
//            wParams.Params = params.Params;
            if (params.PropIndex("Model") != -1)
                wParams.Model = params.Model;
//               if (params.Model.PropIndex("Operation") != -1)
//                  wParams.CODE = Params.Model.Operation;
//               else
//                  wParams.Model = params.Model;
//                  wParams.ID = GenGetProp(params.Model, tableName + "8" + PKField);
//                  wParams.VR = GenGetProp(params.Model, tableName + "8VERSIONREC");
//               end;
            end;
            GetObjectService = WebServiceCallback("ws_panelmacro", "GetMacPanelObject", Rsl2Xml(wParams));
        else
            GetObjectService = WebServiceCallback("ws_panel", "GetPanelObject", wParams.ToStr());
        end;
    end;

    private macro SetSysButtons()
        SysButtons = TArray();
        var sysButton = makeObj(
            "ISysButton",
            "Name", PredefinedSysButton.Save
        );
        if ((MenuType == TypeMainMenuDict) or (MenuType == TypeMenuDictRef))
            sysButton.Service = WebServiceCallback("ws_panel", "SaveSprPanelObject");
            SysButtons[SysButtons.Size] = sysButton;
            SysButtons[SysButtons.Size] = makeObj(
                "ISysButton",
                "Name", PredefinedSysButton.Apply,
                "Visible", false
            );
        elif (MenuType == TypeMenuFormDep)
            sysButton.Service = WebServiceCallback("ws_panel", "SavePanelObject");
            SysButtons[SysButtons.Size] = sysButton;
            SysButtons[SysButtons.Size] = makeObj(
                "ISysButton",
                "Name", PredefinedSysButton.Apply,
                "Service", WebServiceCallback("ws_panel", "ApplyPanelObject")
            );
        else
            sysButton.Service = WebServiceCallback("ws_panel", "SavePanelObject");
            SysButtons[SysButtons.Size] = sysButton;
            SysButtons[SysButtons.Size] = makeObj(
                "ISysButton",
                "Name", PredefinedSysButton.Apply,
                "Service", WebServiceCallback("ws_panel", "ApplyPanelObject")
            );
        end;
    end;

    private macro GetToolbarItem(menuItem: IToolbarItem, buttonText: string): IToolbarItem
        return makeObj(
            "IToolbarItem",
            "Type", ToolbarItemType.Button,
            "Text", buttonText,
            "Image", menuItem.Image,
            "HotKey", menuItem.HotKey,
            "Tooltip", menuItem.ToolTip,
            "Service", menuItem.Service,
            "ConfirmationType", menuItem.ConfirmationType,
            "NeedSelectedRows", menuItem.NeedSelectedRows
        );
    end;

    private macro SetToolBarItems(params)
        var cmd = TRslOraQuery();
        var menuId;
        if (params.PropIndex("MenuId") != -1)
            menuId = params.MenuId;
        else
            menuId = params.Params;
        end;
        var queryText: string = "";
        cmd.SqlText = "begin :QueryText := RSP_WEB.GET_QUERY_MENUFORM_BY_USER(:FormId, :ScrollingId, :DictFlag); end;";
        cmd.DeclareAndSet("QueryText", queryText, "FormId", Id, "ScrollingId", IIF(MenuType == TypeMainMenuMacro, menuId, params.ScrollingId), "DictFlag", IIF(MenuType == TypeMainMenuDict, 1, 0));
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        queryText = cmd.GetVariable("QueryText");
        cmd.Clear();
        cmd.SqlText = queryText;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        ToolbarItems = TArray();
        var groupName: string = "";
        var toolbarItem, menuItem;
        var toolbarButtons = TArray();
        var wParams;
        while (not cmd.Eof)
            if (cmd.GetByName("MainName").AsString != groupName)
                if (groupName != "")
                    ToolbarItems[ToolbarItems.Size] = toolbarItem;
                end;
                groupName = cmd.GetByName("MainName").AsString;
                toolbarItem = makeObj(
                    "IToolbarItem",
                    "Type", ToolbarItemType.MenuButton,
                    "Text", cmd.GetByName("MainName").AsString,
                    "MenuItems", TArray()
                );
            end;
            menuItem = makeObj(
                "IToolbarItem",
                "Type", ToolbarItemType.Button,
                "Text", cmd.GetByName("MenuName").AsString,
                "Image", cmd.GetByName("IconWeb").AsString,
                "HotKey", cmd.GetByName("NameKey").AsString,
                "Tooltip", cmd.GetByName("MenuName").AsString
            );
            if (cmd.Rec.NameStep == "Prev")
                if (int(cmd.Rec.Id_SMenu) == TypeMainMenuState)
                    wParams = makeObj("TDynamicBean", "ScrollingId", params.ScrollingId, "State", cmd.GetByName("StateStep").AsInteger);
                    menuItem.Service = WebServiceCallback("ws_step", "StepBackWeb", Rsl2Xml(wParams));
                elif (int(cmd.Rec.Id_SMenu) == TypeMainMenuVisa)
                    var wParamNo = WebServiceParams(cmd.GetByName("StateStep").AsInteger, params.CurrentRow.Id_NVTyp);
                    menuItem.Service = WebServiceCallback("ws_stepvisa", "VisaNO", wParamNo.ToStr());
                elif (int(cmd.Rec.Id_SMenu) == TypeMainMenuPosit)
                    wParams = makeObj("TDynamicBean", "ScrollingId", params.ScrollingId, "State", cmd.GetByName("StateStep").AsInteger);
                    menuItem.Service = WebServiceCallback("ws_step", "StepBackWeb", Rsl2Xml(wParams));
                end;
                menuItem.ConfirmationType = ServiceConfirmationType.Comment;
            elif (cmd.Rec.NameStep == "Next")
                if (int(cmd.Rec.Id_SMenu) == TypeMainMenuState)
                    wParams = makeObj("TDynamicBean", "ScrollingId", params.ScrollingId, "State", cmd.GetByName("StateStep").AsInteger);
                    menuItem.Service = WebServiceCallback("ws_step", "StepNextWeb", Rsl2Xml(wParams));
                elif (int(cmd.Rec.Id_SMenu) == TypeMainMenuVisa)
                    var wParamYes = WebServiceParams(cmd.GetByName("StateStep").AsInteger, params.CurrentRow.Id_NVTyp);
                    menuItem.Service = WebServiceCallback("ws_stepvisa", "VisaOK", wParamYes.ToStr());
                elif (int(cmd.Rec.Id_SMenu) == TypeMainMenuPosit)
                    wParams = makeObj("TDynamicBean", "ScrollingId", params.ScrollingId, "State", cmd.GetByName("StateStep").AsInteger);
                    menuItem.Service = WebServiceCallback("ws_step", "StepNextWeb", Rsl2Xml(wParams));
                end;
                menuItem.ConfirmationType = ServiceConfirmationType.YesNo;
            elif ((cmd.Rec.Id_SMenu == TypeMenuFormDep) or (cmd.Rec.Id_SMenu == TypeMenuFormRef) or (cmd.Rec.Id_SMenu == TypeMenuDictRef))
                menuItem.Service = WebServiceCallback("ws_panel", "OpenSubordinateScrolling", cmd.GetByName("Id_NMenu").AsString);
            elif (cmd.Rec.Id_SMenu == TypeMenuFormMain)
                menuItem.Service = WebServiceCallback("ws_panel", "OpenMainFormPanel", cmd.GetByName("Id_NMenu").AsString);
            elif (cmd.Rec.Id_SMenu == TypeMainMenuDict)
                menuItem.Service = WebServiceCallback("ws_scrolling", "GetScrollingDictToolbar", cmd.GetByName("ID_NMENU").AsString);
            elif (cmd.Rec.NameTabFile)
                wParams = makeObj("TDynamicBean", "TABFILE", cmd.GetByName("NameTabFile").AsString, "FORM", Id, "IDMENU", params.ScrollingId);
                menuItem.Service = WebServiceCallback("ws_scrollfiles", "OpenSubordinateScrolFiles", Rsl2Xml(wParams));
            elif (cmd.Rec.ID_NMENU == "Print")
                wParams = makeObj("TDynamicBean", "MACROFILE", cmd.GetByName("MacroFileWeb").AsString, "MACROPROC", cmd.GetByName("MacroProcWeb").AsString);
                menuItem.Service = WebServiceCallback("ws_print", "printForm", Rsl2Xml(wParams));
            else
                wParams = makeObj("TDynamicBean", "ScrollingId", params.ScrollingId, "IDNMENU", cmd.GetByName("ID_NMENU").AsString);
                menuItem.Service = WebServiceCallback(cmd.GetByName("MacroFileWeb").AsString, cmd.GetByName("MacroProcWeb").AsString, Rsl2Xml(wParams));
            end;
            if (cmd.Rec.IsToolbar)
                toolbarButtons[toolbarButtons.Size] = GetToolbarItem(menuItem, cmd.GetByName("ButtonText").AsString);
            end;
            toolbarItem.MenuItems[toolbarItem.MenuItems.Size] = menuItem;
            cmd.Next();
        end;
        if (groupName != "")
            ToolbarItems[ToolbarItems.Size] = toolbarItem;
        end;
        for (var toolbarButton, toolbarButtons)
            ToolbarItems[ToolbarItems.Size] = toolbarButton;
        end;
    end;

    private macro GetViewFields(fieldId: integer, formId: integer): TArray
        var cmd = TRslOraQuery();
        var cmdGetCursor = TRslOraQuery();
        var queryText: string = "";
        cmdGetCursor.SqlText = "begin :QueryText := RSP_WEB.GET_FIELDLKP(:IDFORM, :IDFIELD); end;";
        cmdGetCursor.DeclareAndSet( ":IDFORM", formId, ":IDFIELD", fieldId);
        cmdGetCursor.DeclareAndSetCursor("QueryText", cmd);
        if (not cmdGetCursor.Execute())
            RunError(ToANSI(cmdGetCursor.Error));
        end;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        var viewFields = TArray();
        while (not cmd.Eof)
            if (cmd.Rec.isGrid)
                viewFields[viewFields.Size] = makeObj(
                    "IListItem",
                    "ID", cmd.Rec.Id,
                    "Type", cmd.Rec.TypeField,
                    "Title", cmd.Rec.Text,
                    "Tooltip", cmd.Rec.Text,
//                    "Width", cmd.GetByName("Width").AsInteger,
                    "Source", cmd.Rec.Source
                );
            end;
            cmd.Next();
        end;
        return viewFields;
    end;

    private macro GetViewFieldsSpr(fieldId: integer): TArray
        var cmd = TRslOraQuery();
        var cmdGetCursor = TRslOraQuery();
        var queryText: string = "";
        cmdGetCursor.SqlText = "begin :QueryText := RSP_WEB.GET_FIELDLKPSPR(:IDFIELD); end;";
        cmdGetCursor.DeclareAndSet(":IDFIELD", fieldId);
        cmdGetCursor.DeclareAndSetCursor("QueryText", cmd);
        if (not cmdGetCursor.Execute())
            RunError(ToANSI(cmdGetCursor.Error));
        end;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        var viewFields = TArray();
        while (not cmd.Eof)
            if (cmd.Rec.isGrid)
                viewFields[viewFields.Size] = makeObj(
                    "IListItem",
                    "ID", cmd.Rec.Id,
                    "Type", cmd.Rec.TypeField,
                    "Title", cmd.Rec.Text,
                    "Tooltip", cmd.Rec.Text,
//                    "Width", cmd.GetByName("Width").AsInteger,
                    "Source", cmd.Rec.Source
                );
            end;
            cmd.Next();
        end;
        return viewFields;
    end;

    private macro GetMappingFields(fieldId: integer, formId: integer): TArray
        var cmd = TRslOraQuery();
        var cmdGetCursor = TRslOraQuery();
        var queryText: string = "";
        cmdGetCursor.SqlText = "begin :QueryText := RSP_WEB.GET_FIELDLKP(:IDFORM, :IDFIELD); end;";
        cmdGetCursor.DeclareAndSet(":IDFORM", formId, ":IDFIELD", fieldId);
        cmdGetCursor.DeclareAndSetCursor("QueryText", cmd);
        if (not cmdGetCursor.Execute())
            RunError(ToANSI(cmdGetCursor.Error));
        end;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        var mappingFields = TArray();
        while (not cmd.Eof)
            if ((cmd.Rec.ListSource) and (cmd.Rec.ObjSource))
                mappingFields[mappingFields.Size] = makeObj(
                    "IMappingItem",
                    "ListSource", cmd.Rec.ListSource,
                    "ObjSource", cmd.Rec.ObjSource
                );
            end;
            cmd.Next();
        end;
        return mappingFields;
    end;

    private macro GetMappingFieldsSpr(fieldId: integer): TArray
        var cmd = TRslOraQuery();
        var cmdGetCursor = TRslOraQuery();
        var queryText: string = "";
        cmdGetCursor.SqlText = "begin :QueryText := RSP_WEB.GET_FIELDLKPSPR(:IDFIELD); end;";
        cmdGetCursor.DeclareAndSet(":IDFIELD", fieldId);
        cmdGetCursor.DeclareAndSetCursor("QueryText", cmd);
        if (not cmdGetCursor.Execute())
            RunError(ToANSI(cmdGetCursor.Error));
        end;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        var mappingFields = TArray();
        while (not cmd.Eof)
            if ((cmd.Rec.ListSource) and (cmd.Rec.ObjSource))
                mappingFields[mappingFields.Size] = makeObj(
                    "IMappingItem",
                    "ListSource", cmd.Rec.ListSource,
                    "ObjSource", cmd.Rec.ObjSource
                );
            end;
            cmd.Next();
        end;
        return mappingFields;
    end;

    private macro SetSprFields()
        var cmd  = TRslOraQuery();
        var cmdGetCursor = TRslOraQuery();
        var queryText: string = "";
        cmdGetCursor.SqlText = "begin :QueryText := RSP_WEB.GET_FIELDSFORM(:IDFORM); end;";
        cmdGetCursor.DeclareAndSet(":IDFORM", Id);
        cmdGetCursor.DeclareAndSetCursor("QueryText", cmd);
        if (not cmdGetCursor.Execute())
            RunError(ToANSI(cmdGetCursor.Error));
        end;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        Fields = TArray();
        var top: integer = 0;
        var rowNum: integer = 0;
        var left: integer = 0;
        while (not cmd.Eof)
            if ((top > 0) and (cmd.Rec.Top != top))
                rowNum = rowNum + 1;
                left = 0;
            end;
            var list = null;
            if (cmd.Rec.IsLkp)
                list = makeObj(
                    "IList",
                    "ID", cmd.GetByName("Id_Field").AsInteger,
                    "MultiPage", false,
                    "MultiSelect", false,
                    "ContextChar", 2,
                    "SelectOnly", cmd.Rec.IsLkpOnly,
                    "GetRowsService", WebServiceCallback("ws_panel", "GetPanelListRowsService", cmd.GetByName("id_formlkp").AsInteger),
                    "GetRowCountService", WebServiceCallback("ws_panel", "GetPanelListRowCountService", cmd.GetByName("id_formlkp").AsInteger),
                    "ViewFields", GetViewFieldsSpr(cmd.GetByName("Id_Field").AsInteger),
                    "MappingFields", GetMappingFieldsSpr(cmd.GetByName("Id_Field").AsInteger)
                );
            end;
            Fields[Fields.Size] = makeObj(
                "IPanelItem",
                "Id", cmd.GetByName("Id_Field").AsInteger,
                "Row", rowNum,
                "Type", PanelItemType.Input,
                "Field", makeObj(
                    "IInput",
                    "Type", cmd.Rec.TypeField,
                    "Label", cmd.Rec.Text,
                    "LabelTop", false,
                    "Tips", makeObj("ITips", "Tooltip", cmd.Rec.Comments),
                    "ReadOnly", not cmd.Rec.Edit,
                    "Enabled", cmd.Rec.Read,
                    "TabStop", cmd.Rec.Edit,
                    "ClearButton", false,
                    "Required", cmd.Rec.Required,
                    "MaxLength", cmd.Rec.Size,
                    "Mask", cmd.Rec.Mask,
                    "Source", cmd.Rec.Source,
                    "List", list,
                    "Design", makeObj(
                        "IDesign",
                        "Font", makeObj(
                            "IFont",
                            "FontFamily", cmd.Rec.FFont,
                            "Bold", Index(cmd.GetByName("FStyle").AsString, "1"),
                            "Italic", Index(cmd.GetByName("FStyle").AsString, "2"),
                            "Color", cmd.GetByName("FColor").AsInteger
                        ),
                        "Background", cmd.GetByName("CColor").AsInteger
                    ),
                    "TextWrapping", true,
                    "LinesCount", cmd.Rec.Height,
                    "Location", makeObj(
                        "ILocation",
                        "MinWidth", cmd.GetByName("Width").AsInteger,
                        "Width", cmd.GetByName("Width").AsInteger,
                        "StretchHorizontal", cmd.GetByName("Width").AsInteger > HORIZONTAL_STRETCH_WIDTH,
                        "StretchVertical", false,
                        "MarginLeft", IIF(left == 0, cmd.GetByName("Left").AsInteger, cmd.GetByName("Left").AsInteger - left)
                    )
                )
            );
            top = cmd.Rec.Top;
            left = cmd.GetByName("Left").AsInteger + cmd.GetByName("Width").AsInteger;
            cmd.Next();
        end;
    end;
/*
    private macro SetFields(params)
        var cmd = TRslOraQuery();
        var queryText: string = "";
        var isedit = 0;
        var sright = 0;
        cmd.SqlText = "begin :QueryText := RSP_WEB.GET_NFIELDFORM; end;";
        cmd.DeclareAndSet("QueryText", queryText);
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        queryText = cmd.GetVariable("QueryText");
        cmd.Clear();
        cmd.SqlText = queryText;
        if (params.PropIndex("Model") != -1)
            cmd.DeclareAndSet(":IDMenu", int(params.Params), ":IDFORM", Id, ":IDFORM", Id);
        else
            cmd.DeclareAndSet(":IDMenu", int(params.ScrollingId), ":IDFORM", Id, ":IDFORM", Id);
        end;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        Fields = TArray();
        var top: integer = 0;
        var rowNum: integer = 0;
        var left: integer = 0;
        while (not cmd.Eof)
            if ((top > 0) and (cmd.Rec.Top != top))
                rowNum = rowNum + 1;
                left = 0;
            end;
            if (cmd.Rec.IsVisible)
                var list = null;
                if (cmd.Rec.IsLkp)
                    list = makeObj(
                        "IList",
                        "ID", cmd.GetByName("Id_NField").AsInteger,
                        "MultiPage", false,
                        "MultiSelect", false,
                        "ContextChar", 2,
                        "SelectOnly", cmd.Rec.IsLkpOnly,
                        "GetRowsService", WebServiceCallback("ws_panel", "GetPanelListRowsService", cmd.GetByName("Id_Form").AsInteger),
                        "GetRowCountService", WebServiceCallback("ws_panel", "GetPanelListRowCountService", cmd.GetByName("Id_Form").AsInteger),
                        "ViewFields", GetViewFields(cmd.GetByName("Id_NField").AsInteger, Id),
                        "MappingFields", GetMappingFields(cmd.GetByName("Id_NField").AsInteger, Id)
                    );
                end;
                Fields[Fields.Size] = makeObj(
                    "IPanelItem",
                    "Id", cmd.GetByName("Id_NField").AsInteger,
                    "Row", rowNum,
                    "Type", PanelItemType.Input,
                    "Field", makeObj(
                        "IInput",
                        "Type", cmd.Rec.TypeField,
                        "Label", IIF(cmd.GetByName("IsTextUp").AsInteger == 2, null, cmd.Rec.Text),
                        "LabelTop", cmd.GetByName("IsTextUp").AsInteger == 1,
                        "Tips", makeObj("ITips", "Tooltip", cmd.Rec.Text),
                        "ReadOnly", not cmd.Rec.Edit,
                        "Enabled", true,
                        "TabStop", cmd.Rec.Edit,
                        "ClearButton", false,
                        "Required", cmd.Rec.Required,
                        "MaxLength", cmd.Rec.Len,
                        "Mask", cmd.Rec.Mask,
                        "ValidateOnLostFocus", (cmd.GetByName("ChkFile").AsString != "") and (cmd.GetByName("ChkProc").AsString != ""),
                        "Source", cmd.Rec.Source,
                        "List", list,
                        "Design", makeObj(
                            "IDesign",
                            "Font", makeObj(
                                "IFont",
                                "FontFamily", cmd.Rec.FFont,
                                "Bold", Index(cmd.GetByName("FStyle").AsString, "1"),
                                "Italic", Index(cmd.GetByName("FStyle").AsString, "2"),
                                "Color", cmd.GetByName("FColor").AsInteger
                            ),
                            "Background", cmd.GetByName("CColor").AsInteger
                        ),
                        "TextWrapping", true,
                        "LinesCount", cmd.Rec.Height,
                        "Location", makeObj(
                            "ILocation",
                            "MinWidth", cmd.GetByName("Width").AsInteger,
                            "Width", cmd.GetByName("Width").AsInteger,
                            "StretchHorizontal", cmd.GetByName("Width").AsInteger > HORIZONTAL_STRETCH_WIDTH,
                            "StretchVertical", false,
                            "MarginLeft", IIF(left == 0, cmd.GetByName("Left").AsInteger, cmd.GetByName("Left").AsInteger - left)
                        )
                    )
                );
            end;
            top = cmd.Rec.Top;
            left = cmd.GetByName("Left").AsInteger + cmd.GetByName("Width").AsInteger;
            cmd.Next();
        end;
    end;
*/
    private macro MakeFields(cmd, level: integer, rowNum: @integer): TArray
        var groupItemFields = TArray();
        var top: integer = 0;
        var left: integer = 0;
        while (not cmd.Eof and (cmd.GetByName("Level").AsInteger == level) and (cmd.GetByName("TypeItem").AsString == "FieldItem"))
            if ((top > 0) and (cmd.Rec.Top != top))
                rowNum = rowNum + 1;
                left = 0;
            end;
            if (cmd.Rec.IsVisible)
                var list = null;
                if (cmd.Rec.IsLkp)
                    list = makeObj(
                        "IList",
                        "ID", cmd.GetByName("ItemId").AsInteger,
                        "MultiPage", false,
                        "MultiSelect", false,
                        "ContextChar", 2,
                        "SelectOnly", cmd.Rec.IsLkpOnly,
                        "GetRowsService", WebServiceCallback("ws_panel", "GetPanelListRowsService", cmd.GetByName("Id_Form").AsInteger),
                        "GetRowCountService", WebServiceCallback("ws_panel", "GetPanelListRowCountService", cmd.GetByName("Id_Form").AsInteger),
                        "ViewFields", GetViewFields(cmd.GetByName("ItemId").AsInteger, Id),
                        "MappingFields", GetMappingFields(cmd.GetByName("ItemId").AsInteger, Id)
                    );
                end;
                groupItemFields[groupItemFields.Size] = makeObj(
                    "IPanelItem",
                    "Id", cmd.GetByName("ItemId").AsInteger,
                    "Row", rowNum,
                    "Type", PanelItemType.Input,
                    "Field", makeObj(
                        "IInput",
                        "Type", cmd.Rec.TypeField,
                        "Label", IIF(cmd.GetByName("IsTextUp").AsInteger == 2, null, cmd.Rec.Text),
                        "LabelTop", cmd.GetByName("IsTextUp").AsInteger == 1,
                        "Tips", makeObj("ITips", "Tooltip", cmd.Rec.Text),
                        "ReadOnly", not cmd.Rec.Edit,
                        "Enabled", true,
                        "TabStop", cmd.Rec.Edit,
                        "ClearButton", false,
                        "Required", cmd.Rec.Required,
                        "MaxLength", cmd.Rec.Len,
                        "Mask", cmd.Rec.Mask,
                        "ValidateOnLostFocus", (cmd.GetByName("ChkFile").AsString != "") and (cmd.GetByName("ChkProc").AsString != ""),
                        "Source", cmd.Rec.Source,
                        "List", list,
                        "Design", makeObj(
                            "IDesign",
                            "Font", makeObj(
                                "IFont",
                                "FontFamily", cmd.Rec.FFont,
                                "Bold", Index(cmd.GetByName("FStyle").AsString, "1"),
                                "Italic", Index(cmd.GetByName("FStyle").AsString, "2"),
                                "Color", cmd.GetByName("FColor").AsInteger
                            ),
                            "Background", cmd.GetByName("CColor").AsInteger
                        ),
                        "TextWrapping", true,
                        "LinesCount", cmd.Rec.Height,
                        "Location", makeObj(
                            "ILocation",
                            "MinWidth", cmd.GetByName("Width").AsInteger,
                            "Width", cmd.GetByName("Width").AsInteger,
                            "StretchHorizontal", cmd.GetByName("Width").AsInteger > HORIZONTAL_STRETCH_WIDTH,
                            "StretchVertical", false,
                            "MarginLeft", IIF(left == 0, cmd.GetByName("Left").AsInteger, cmd.GetByName("Left").AsInteger - left)
                        )
                    )
                );
            end;
            top = cmd.Rec.Top;
            left = cmd.GetByName("Left").AsInteger + cmd.GetByName("Width").AsInteger;
            cmd.Next();
        end;
        return groupItemFields;
    end;
/*
    private macro MakeFieldsWithRadio(cmd, level: integer, rowNum: @integer): TArray
        var groupItemFields = TArray();
        var top: integer = 0;
        var left: integer = 0;
        while (not cmd.Eof and (cmd.GetByName("Level").AsInteger == level) and (cmd.GetByName("TypeItem").AsString == "FieldItem"))
            if ((top > 0) and (cmd.Rec.Top != top))
                rowNum = rowNum + 1;
                left = 0;
            end;
            if (cmd.Rec.IsVisible)
                var list = null;
                if (cmd.Rec.IsLkp)
                    list = makeObj(
                        "IList",
                        "ID", cmd.GetByName("ItemId").AsInteger,
                        "MultiPage", false,
                        "MultiSelect", false,
                        "ContextChar", 2,
                        "SelectOnly", cmd.Rec.IsLkpOnly,
                        "GetRowsService", WebServiceCallback("ws_panel", "GetPanelListRowsService", cmd.GetByName("Id_Form").AsInteger),
                        "GetRowCountService", WebServiceCallback("ws_panel", "GetPanelListRowCountService", cmd.GetByName("Id_Form").AsInteger),
                        "ViewFields", GetViewFields(cmd.GetByName("ItemId").AsInteger, Id),
                        "MappingFields", GetMappingFields(cmd.GetByName("ItemId").AsInteger, Id)
                    );
                end;
                groupItemFields[groupItemFields.Size] = makeObj(
                    "IPanelItem",
                    "Id", "Radio_" + cmd.GetByName("ItemId").AsInteger,
                    "Row", rowNum,
                    "Type", PanelItemType.Input,
                    "Field", makeObj(
                        "IInput",
                        "Type", PanelInputFieldType.Radio,
                        "Label", IIF(cmd.GetByName("IsTextUp").AsInteger == 2, null, cmd.Rec.Text),
                        "LabelTop", false,
                        "Tips", makeObj("ITips", "Tooltip", cmd.Rec.Text),
                        "ReadOnly", false,
                        "Enabled", true,
                        "TabStop", true,
                        "Required", false,
                        "DefaultValue", "VIN_ID" || "PIN",
                        "Source", "MovPropertyType",
                        "TextWrapping", false,
                        "Location", makeObj(
                            "ILocation",
                            "MinWidth", IIF(left == 0, cmd.GetByName("Left").AsInteger, cmd.GetByName("Left").AsInteger - left - 20 - 10),
                            "Width", IIF(left == 0, cmd.GetByName("Left").AsInteger, cmd.GetByName("Left").AsInteger - left - 20 - 10),
                            "StretchHorizontal", false,
                            "StretchVertical", false,
                            "MarginLeft", IIF(left == 0, 0, 20)
                        )
                    )
                );
                groupItemFields[groupItemFields.Size] = makeObj(
                    "IPanelItem",
                    "Id", cmd.GetByName("ItemId").AsInteger,
                    "Row", rowNum,
                    "Type", PanelItemType.Input,
                    "Field", makeObj(
                        "IInput",
                        "Type", cmd.Rec.TypeField,
                        "Tips", makeObj("ITips", "Tooltip", cmd.Rec.Text),
                        "ReadOnly", not cmd.Rec.Edit or (MovPropertyType != "VIN_ID" || "PIN"),
                        "Enabled", true,
                        "TabStop", cmd.Rec.Edit,
                        "ClearButton", false,
                        "Required", cmd.Rec.Required,
                        "MaxLength", cmd.Rec.Len,
                        "Mask", cmd.Rec.Mask,
                        "ValidateOnLostFocus", (cmd.GetByName("ChkFile").AsString != "") and (cmd.GetByName("ChkProc").AsString != ""),
                        "Source", cmd.Rec.Source,
                        "List", list,
                        "Design", makeObj(
                            "IDesign",
                            "Font", makeObj(
                                "IFont",
                                "FontFamily", cmd.Rec.FFont,
                                "Bold", Index(cmd.GetByName("FStyle").AsString, "1"),
                                "Italic", Index(cmd.GetByName("FStyle").AsString, "2"),
                                "Color", cmd.GetByName("FColor").AsInteger
                            ),
                            "Background", cmd.GetByName("CColor").AsInteger
                        ),
                        "TextWrapping", true,
                        "LinesCount", cmd.Rec.Height,
                        "Location", makeObj(
                            "ILocation",
                            "MinWidth", cmd.GetByName("Width").AsInteger,
                            "Width", cmd.GetByName("Width").AsInteger,
                            "StretchHorizontal", cmd.GetByName("Width").AsInteger > HORIZONTAL_STRETCH_WIDTH,
                            "StretchVertical", false,
                            "MarginLeft", 10
                        )
                    )
                );
            end;
            top = cmd.Rec.Top;
            left = cmd.GetByName("Left").AsInteger + 10 + cmd.GetByName("Width").AsInteger;
            cmd.Next();
        end;
        return groupItemFields;
    end;
*/
    private macro MakeGroupItem(cmd, level: integer, rowNum: @integer, isRadioGroup: bool)
        var groupItem = makeObj(
            "IPanelItem",
            "Id", cmd.GetByName("ItemId").AsInteger,
            "Row", rowNum,
            "Type", PanelItemType.Group,
            "Field", makeObj(
                "IGroup",
                "Type", cmd.GetByName("TypeField").AsString,
                "Label", cmd.GetByName("Source").AsString,
                "Fields", makeArray(
                    makeObj(
                        "IPanelItem",
                        "Id", "GroupPanel_" + cmd.GetByName("ItemId").AsInteger,
                        "Row", 0,
                        "Type", PanelItemType.Group,
                        "Field", makeObj(
                            "IGroup",
                            "Type", GroupItemType.Panel
                        )
                    )
                )
            )
        );
        cmd.Next();
        while (not cmd.Eof and (cmd.GetByName("Level").AsInteger == level))
            if (cmd.GetByName("TypeItem").AsString == "GroupItem")
                if (groupItem.Field.Fields[0].Field.Fields)
                    rowNum = groupItem.Field.Fields[0].Field.Fields[groupItem.Field.Fields[0].Field.Fields.Size - 1].Row + 1;
                else
                    groupItem.Field.Fields[0].Field.Fields = TArray();
                end;
                groupItem.Field.Fields[0].Field.Fields[groupItem.Field.Fields[0].Field.Fields.Size] = MakeGroupItem(cmd, level + 1, @rowNum, cmd.GetByName("TypeField").AsString == "RadioGroup");
            elif (cmd.GetByName("TypeItem").AsString == "FieldItem")
                if (groupItem.Field.Fields[0].Field.Fields)
                    rowNum = groupItem.Field.Fields[0].Field.Fields[groupItem.Field.Fields[0].Field.Fields.Size - 1].Row + 1;
                    var childFields: TArray;
/*
                    if (isRadioGroup)
                        childFields = MakeFieldsWithRadio(cmd, level, @rowNum);
                    else
*/
                        childFields = MakeFields(cmd, level, @rowNum);
//                    end;
                    for (var childField, childFields)
                        groupItem.Field.Fields[0].Field.Fields[groupItem.Field.Fields[0].Field.Fields.Size] = childField;
                    end;
                else
                    var tempRowNum: integer = 0;
/*
                    if (isRadioGroup)
                        groupItem.Field.Fields[0].Field.Fields = MakeFieldsWithRadio(cmd, level, @tempRowNum);
                    else
*/
                        groupItem.Field.Fields[0].Field.Fields = MakeFields(cmd, level, @tempRowNum);
//                    end;
                    if (rowNum == 0)
                        rowNum = tempRowNum;
                    end;
                end;
            end;
        end;
        return groupItem;
    end;

    private macro SetGroupItems(params)
        var cmd = TRslOraQuery();
        var queryText: string = "";
        cmd.SqlText = "begin :QueryText := RSP_WEB.GET_GROUPITEMFORM; end;";
        cmd.DeclareAndSetLOB("QueryText", queryText);
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        queryText = cmd.GetVariable("QueryText");
        cmd.Clear();
        cmd.SqlText = queryText;
        if (params.PropIndex("Model") != -1)
            cmd.DeclareAndSet(":IDForm", Id, ":IDMenu", int(params.Params), ":IDForm", Id, ":IDForm", Id);
        else
            cmd.DeclareAndSet(":IDForm", Id, ":IDMenu", int(params.ScrollingId), ":IDForm", Id, ":IDForm", Id);
        end;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        Fields = TArray();
        var level: integer = 1;
        var rowNum: integer = 0;
        while (not cmd.Eof)
            if (cmd.GetByName("Level").AsInteger == level)
                if (cmd.GetByName("TypeField").AsString == "TabItem")
                    rowNum = 0;
                elif (Fields.Size)
                    rowNum = Fields[Fields.Size - 1].Row + 1;
                end;
                if (cmd.GetByName("TypeItem").AsString == "GroupItem")
                    Fields[Fields.Size] = MakeGroupItem(cmd, level + 1, @rowNum, cmd.GetByName("TypeField").AsString == "RadioGroup");
                elif (cmd.GetByName("TypeItem").AsString == "FieldItem")
                    var tempRowNum: integer = 0;
                    Fields[Fields.Size] = makeObj(
                        "IPanelItem",
                        "Id", "FieldPanel_" + rowNum,
                        "Row", rowNum,
                        "Type", PanelItemType.Group,
                        "Field", makeObj(
                            "IGroup",
                            "Type", GroupItemType.Panel,
                            "Fields", MakeFields(cmd, level, @tempRowNum)
                        )
                    );
                end;
            end;
        end;
    end;

    private macro SetValidationService()
        var cmd = TRslOraQuery();
        if ((MenuType == TypeMainMenuDict) or (MenuType == TypeMenuDictRef))
            cmd.SqlText = "select mfsaveweb MacroFile, mpsaveweb MacroFunc from FORM where id_form = :FormSprId";
            cmd.DeclareAndSet("FormSprId", Id);
        else
            cmd.SqlText = "select chkfileweb MacroFile, chkprocweb MacroFunc from NFORM where id_nform = :FormId";
            cmd.DeclareAndSet("FormId", Id);
        end;
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        if ((cmd.GetByName("MacroFile").AsString != "") and (cmd.GetByName("MacroFunc").AsString != ""))
            ValidationService = WebServiceCallback(cmd.GetByName("MacroFile").AsString, cmd.GetByName("MacroFunc").AsString);
        end;
    end;

    SetPropertiesAndTitle(params);
    WindowParams = makeObj(
        "IWindowParams",
        "Width", 800,
        "Height", 600,
        "HelpPage", "",
        "IsModal", false,
        "IsResizing", true
    );
    Appearance = WindowAppearanceType.Panel;
    SetSysButtons();
    if ((MenuType == TypeMainMenuDict) or (MenuType == TypeMenuDictRef))
        SetToolBarItems(params);
        SetSprFields();
    else
        SetToolBarItems(params);
//        SetFields(params);
        SetGroupItems(params);
    end;
    SetValidationService();
end;

private macro GetListSQLText(formId, fieldId, filter: string): string
    var cmd = TRslOraQuery();
    cmd.SqlText = "select RSP_WEB.GET_ROWLKP(:FormId, :FieldId) QueryText from DUAL";
    cmd.DeclareAndSet("FormId", formId, "FieldId", fieldId);
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    return cmd.Rec.QueryText;
end;

macro GetPanelListRowsService(params)
    var wParams = WebServiceParams();
    wParams.FromStr(params.Params);
    var cmd = TRslOraQuery();
    cmd.SqlText = SQL_WrapSelect(GetListSQLText(params.Params, params.ScrollingId, GetSqlFilterCondition(params.FilterItems)), params.PageNumber, params.PageSize);
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    return cmd;
end;

macro GetPanelListRowCountService(params): integer
    var wParams = WebServiceParams();
    wParams.FromStr(params.Params);
    var cmd = TRslOraQuery();
    cmd.SqlText = "select count(*) CNT from (" + GetListSQLText(params.Params, params.ScrollingId, GetSqlFilterCondition(params.FilterItems)) + ")";
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    return cmd.GetByName("CNT").AsInteger;
end;

// Сервис скроллинга тулбара
macro OpenSubordinateScrolling(params)//, menuId, formId, panelObject)
    var tableFieldName: string = "";
    var cmd = TRslOraQuery();
    var scrollingId = params.Params;
    var panelObject = params.Model;
    var fieldName = "";
    cmd.SqlText = "select id_smenu, tbnm, clnm1dn, tbnm_dn, clnm2dn from NMENU where id_nmenu = :MenuId";
    cmd.DeclareAndSet("MenuId", scrollingId);
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    var menuType = cmd.GetByName("id_smenu").AsInteger;

    if (menuType == TypeMenuFormDep)
        tableFieldName = cmd.Rec.tbnm + "8" + cmd.Rec.clnm1dn;
    elif (menuType == TypeMenuFormRef)
       tableFieldName = cmd.Rec.tbnm;
       cmd.Clear();
       cmd.SqlText = "begin :FieldName := RSP_FORM.GET_PK_TABLE(:TableName); end;";
       cmd.DeclareAndSet("TableName", tableFieldName, "FieldName", fieldName);
       if (not cmd.Execute())
           RunError(ToANSI(cmd.Error));
       end;
       fieldName = cmd.GetVariable("FieldName");
       tableFieldName = tableFieldName + "8" + fieldName;
    else
       cmd.Clear();
       cmd.SqlText = "begin :TableFieldName := RSP_FORM.GET_FIELDREFFORM(:MenuId, 1, :DictFlag); end;";
       cmd.DeclareAndSet("TableFieldName", tableFieldName, "MenuId", scrollingId, "DictFlag", IIF(menuType == TypeMenuDictRef, 1, 0));
       if (not cmd.Execute())
           RunError(ToANSI(cmd.Error));
       end;
       tableFieldName = cmd.GetVariable("TableFieldName");
    end;

    // Получение ИД записи
    var recordId: integer = 0;
    if (panelObject != null)
        recordId = GenGetProp(panelObject, tableFieldName);
    end;
    return WebServiceResult(WebServiceResultType.Window, ScrollingWindow(scrollingId, recordId));
end;

macro GetSprPanelObject(params, formSprId)
    var wParams = WebServiceParams();
    wParams.FromStr(params);
    var cmd = TRslOraQuery();
    var queryText: string = "";
    cmd.SqlText = "begin :QueryText := RSP_WEB.GET_FIELDSFORMPANEL(:FormSprId, :Id, :Version, :RefId, :ScrollingID); end;";
    cmd.DeclareAndSet(
        "QueryText", queryText,
        "FormSprId", int(formSprId),
        "Id", IIF(int(wParams.id_record), int(wParams.id_record), 0),
        "Version", IIF(int(wParams.id_record), int(wParams.version_record), 0),
        "RefId", IIF(int(wParams.id_refrecord), int(wParams.id_refrecord), 0),
        "ScrollingID", IIF(int(wParams.id_scrolling), int(wParams.id_scrolling), 0)
    );
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    queryText = cmd.GetVariable("QueryText");
    cmd.Clear();
    cmd.SqlText = queryText;
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    var rec = cmd.Rec;
    var panelObjectPropIndex: integer = 0;
    var panelObjectPropNumber = cmd.FieldCount;
    var panelObject = TDynamicBean();
    while (panelObjectPropIndex < panelObjectPropNumber)
        GenSetProp(panelObject, cmd.GetFieldName(panelObjectPropIndex), rec[panelObjectPropIndex]);
        panelObjectPropIndex = panelObjectPropIndex + 1;
    end;
    return panelObject;
end;

class QueryBuilder(_tableName: string, _propNames: TArray, _propValues: TArray, _recordId: integer, _recordVersion: integer)
    var tableName: string = _tableName;
    var propNames: TArray = _propNames;
    var propValues: TArray = _propValues;
    var recordId: integer = _recordId;
    var recordVersion: integer = _recordVersion;

    private macro ConvertToSQL(value)
        if ((ValType(value) == V_STRING) or (ValType(value) == V_DATE))
            return "'" + value + "'";
        else
            return value;
        end;
    end;

    macro GetQueryText(): string
        var queryText: string = "";
        if (recordId == 0)
            queryText = "insert into " + tableName + " (" + join(propNames, ", ") + ") "
                        "values ('" + join(propValues, "', '") + "')";
        else
            var setValues = TArray();
            var i: integer = 0;
            while (i < propNames.Size)
                setValues[setValues.Size] = propNames[i] + " = " + ConvertToSQL(propValues[i]);
                i = i + 1;
            end;
            queryText = "update " + tableName +
                        "   set " + join(setValues, ", ") +
                        " where ID_" + tableName + " = " + recordId + " and VERSIONREC = " + recordVersion;
        end;
        return queryText;
    end;
end;

private macro OccurrenceCount(source: string, character: string): integer
    var result: integer = 0;
    var i = Index(source, character);
    while (i)
        result = result + 1;
        i = Index(source, character, i + 1);
    end;
    return result;
end;

macro CheckSpr(windowModel, source): WebServiceResponse
    var response = WebResponseBuilder();
    if (Index(windowModel.SFI8STRCODE, "Z"))
        response.AddValidationError("Код валюты не может содержать символ \"Z\"", source, 11);
    end;
    return response.Result();
end;

macro Check(windowModel, source): WebServiceResponse
    var response = WebResponseBuilder();
    if (windowModel.PAYM8AMOUNT > $10)
        response.AddValidationError("Сумма не может быть больше 10", "PAYM8AMOUNT", 1);
    end;
    if (StrLen(windowModel.RMAIN8GROUND) > 10)
        response.AddValidationError("Длина Основания не может быть больше 10 символов", "RMAIN8GROUND", 2);
    end;
    return response.Result();
end;

macro SaveSprPanelObject(params)
    var cmd = TRslOraQuery();
    var tableName: string = "";
    var fieldName: string = "";
    cmd.SqlText = "begin :TableName := RSP_FORM.GET_MAINTABLEFORM(:FormSprId, 1); :FieldName := RSP_FORM.GET_PK_TABLE(:TableName); end;";
    cmd.DeclareAndSet("TableName", tableName, "FormSprId", params.WindowId, "FieldName", fieldName);
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    tableName = cmd.GetVariable("TableName");
    fieldName = cmd.GetVariable("FieldName");
    var recordId = GenGetProp(params.Model, tableName + "8" + fieldName);
    var recordVersion = GenGetProp(params.Model, tableName + "8VersionRec");
    var panelObjectPropIndex: integer = 0;
    var panelObjectPropNumber = params.Model.PropNumber();
    var panelObjectPropNames = TArray();
    var panelObjectPropValues = TArray();
    while (panelObjectPropIndex < panelObjectPropNumber)
        var propName = params.Model.PropName(panelObjectPropIndex);
        if ((propName != tableName + "8" + fieldName) and (propName != tableName + "8VersionRec") and (OccurrenceCount(propName, "8") == 1))
          if (ValType(params.Model[panelObjectPropIndex]) != V_UNDEF)
            panelObjectPropNames[panelObjectPropNames.Size] = SubStr(propName, Index(propName, "8") + 1);
            panelObjectPropValues[panelObjectPropValues.Size] = params.Model[panelObjectPropIndex];
          end;
        end;
        panelObjectPropIndex = panelObjectPropIndex + 1;
    end;
    var qb = QueryBuilder(tableName, panelObjectPropNames, panelObjectPropValues, recordId, recordVersion);
    cmd.Clear();
    cmd.SqlText = qb.GetQueryText();
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    OraTrnCommit();
    return WebServiceResult(WebServiceResultType.Action, makeArray(IAction(WebServiceActionType.Close), IAction(WebServiceActionType.RefreshParent)));
end;

macro GetPanelObject(params, formId)
    var tableFieldName = "";
    var wParams = WebServiceParams();
    wParams.FromStr(params);
    if (int(wParams.id_refrecord) != 0)
        var scrollingId = int(wParams.id_scrolling);
        var cmd = TRslOraQuery();
        cmd.SqlText = "select id_smenu, id_formspr from NMENU where id_nmenu = :MenuId";
        cmd.DeclareAndSet("MenuId", scrollingId);
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        var menuType = cmd.GetByName("id_smenu").AsInteger;
        if (menuType == TypeMenuFormDep)
            cmd.Clear();
            cmd.SqlText = "begin :TableFieldName := RSP_FORM.GET_FIELDREFFORM(:MenuId, 0); end;";
            cmd.DeclareAndSet("TableFieldName", tableFieldName, "MenuId", scrollingId);
            if (not cmd.Execute())
              RunError(ToANSI(cmd.Error));
            end;
            tableFieldName = cmd.GetVariable("TableFieldName");
        end;
    end;
    var panelObject;
    if (int(wParams.id_record) == 0)
        panelObject = TRslPayDoc(int(formId), 0);
        if (tableFieldName)
            GenSetProp(panelObject.Rec, tableFieldName, int(wParams.id_refrecord));
            panelObject.UpdRefField();
        end;
    else
        panelObject = TRslPayDoc(int(formId), int(wParams.id_record), int(wParams.version_record));
    end;
    return panelObject;
end;

private macro PreparePanelObjectForSaving(formId, alteredPanelObject)
    var tableName: string = "";
    var fieldName: string = "";
    var cmd = TRslOraQuery();
    cmd.SqlText = "begin :TableName := RSP_FORM.GET_MAINTABLEFORM(:FormId); :FieldName := RSP_FORM.GET_PK_TABLE(:TableName); end;";
    cmd.DeclareAndSet("TableName", tableName, "FormId", formId, "FieldName", fieldName);
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    tableName = cmd.GetVariable("TableName");
    fieldName = cmd.GetVariable("FieldName");
    var recordId = GenGetProp(alteredPanelObject, tableName + "8" + fieldName);
    var recordVersion = GenGetProp(alteredPanelObject, tableName + "8" + FieldVersion);
    var panelObject;
    if ((recordId == null) or (recordId == 0))
        panelObject = TRslPayDoc(int(formId), 0);
    else
        panelObject = TRslPayDoc(int(formId), int(recordId), int(recordVersion));
        if (ValType(panelObject) != V_GENOBJ)
            RunError(ToANSI("Ошибка сохранения: документ был изменен другим пользователем."));
        end;
    end;
    var rec = panelObject.Rec;
    var panelObjectPropIndex: integer = 0;
    var panelObjectPropNumber = alteredPanelObject.PropNumber();
    while (panelObjectPropIndex < panelObjectPropNumber)
        var panelObjectPropValue = alteredPanelObject[panelObjectPropIndex];
        if (ValType(panelObjectPropValue) == V_MONEY)
            panelObjectPropValue = double(panelObjectPropValue) / 100;
        end;
        if (ValType(panelObjectPropValue) == V_BOOL)
//            panelObjectPropValue = IIF(panelObjectPropValue, "X", "");
            panelObjectPropValue = IIF(panelObjectPropValue, 1, 0);
        end;
        rec[panelObjectPropIndex] = panelObjectPropValue;
        panelObjectPropIndex = panelObjectPropIndex + 1;
    end;
    return panelObject;
end;

macro SavePanelObject(params)
    var formId = params.WindowId;
    var object = params.Model;
    var panelObject = PreparePanelObjectForSaving(formId, object);
    var result: WebServiceResult;
    var wParams, parentPanelObject;
    if (params.Params)
        wParams = Xml2Rsl(params.Params);
        if(wParams.PropIndex("param") != -1)
           panelObject.Params = Rsl2Xml(wParams.param);
        end;
        if (not panelObject.SetMacro(wParams.Mac, wParams.Proc))
            OraTrnRollBack();
            return WebServiceResult(WebServiceResultType.Message, IMessage("Ошибка!", "Ошибка при установке макрофункции для документа: " + panelObject.Error, MessageBoxType.Error));
        end;
    end;
    if (panelObject.Save())
/*
        if (params.Params)
            var wParams = Xml2Rsl(params.Params);
            ExecMacroFile(wParams.Mac, wParams.Proc, panelObject.rec, wParams.Param);
        end;
*/
        OraTrnCommit();
        var Actions = makeArray(IAction(WebServiceActionType.Close), IAction(WebServiceActionType.RefreshParent));
        if (StrLen(panelObject.Params) > 0)
            Actions[Actions.size] = Xml2Rsl(panelObject.Params);
        end;
        result = WebServiceResult(WebServiceResultType.Action, Actions);
    else
        OraTrnRollBack();
        result = WebServiceResult(WebServiceResultType.Message, IMessage("Ошибка", "Ошибка сохранения: " + panelObject.Error, MessageBoxType.Error));
    end;
    return result;
end;

macro ApplyPanelObject(params)
    var FormID = params.WindowId;
    var Object = params.Model;
    var panelObject = PreparePanelObjectForSaving(FormID, Object);
    var result: WebServiceResult;
    var wParams, parentPanelObject;
    if (params.Params)
        wParams = Xml2Rsl(params.Params);
        if (wParams.PropIndex("param") != -1)
            panelObject.Params = Rsl2Xml(wParams.param);
        end;
        if (not panelObject.SetMacro(wParams.Mac, wParams.Proc))
            OraTrnRollBack();
            return WebServiceResult(WebServiceResultType.Message, IMessage("Ошибка!", "Ошибка при установке макрофункции для документа: " + panelObject.Error, MessageBoxType.Error));
        end;
    end;
    if (panelObject.Save())
        OraTrnCommit();
        panelObject.Refresh();
        var Actions = makeArray(IAction(WebServiceActionType.UpdateModel, panelObject), IAction(WebServiceActionType.RefreshParent));
        if (StrLen(panelObject.Params) > 0)
            Actions[Actions.size] = Xml2Rsl(panelObject.Params);
        end;
        result = WebServiceResult(WebServiceResultType.Action, Actions);
    else
        OraTrnRollBack();
        return WebServiceResult(WebServiceResultType.Message, IMessage("Ошибка", "Ошибка сохранения: " + panelObject.Error, MessageBoxType.Error));
    end;
    return result;
end;

private macro OpenMainForm(menuId, formId, panelObject)
debugbreak;
    var result: WebServiceResult;
    var cmd = TRslOraQuery();
    var Table      : string = "";
    var PKField    : string = "";
    var FKField    : string = "";
    var MainTable  : string = "";
    var MainPKField: string = "";
    var FieldNForm : string = "";
    var AttrPanel = TDynamicBean();

    cmd.SqlText = "begin RSP_FORM.GET_ATTR_FOR_MAINFORM(:IDNMenu, :Table, :FK, :PK, :MainTable, :MainField, :FieldForm); end;";
    cmd.DeclareAndSet("IDNMenu", menuId, "Table", Table, "FK", FKField, "PK", PKField, "MainTable", MainTable, "MainField", MainPKField, "FieldForm", FieldNForm);
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    Table       = cmd.GetVariable("Table");
    FKField     = cmd.GetVariable("FK");
    PKField     = cmd.GetVariable("PK");
    MainTable   = cmd.GetVariable("MainTable");
    MainPKField = cmd.GetVariable("MainField");
    FieldNForm  = cmd.GetVariable("FieldForm");
    // Получение ИД текущей записи
    var recordId = GenGetProp(panelObject, Table + "8" + PKField);
    // Получение атрибутов записи главной формы
    cmd.Clear();
    cmd.SqlText = "select " + FieldNForm + " nform,"
                  "       " + MainTable + "." + MainPKField + " ID,"
                  "       " + MainTable + ".versionrec vr"
                  "  from " + MainTable + ", " + Table +
                  " where " + MainTable + "." + MainPKField + " = " + Table + "." + FKField +
                  "   and " + Table + "." + PKField + " = " + recordId;
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    if (cmd.Eof)
        return WebServiceResult(WebServiceResultType.Message, IMessage("Ошибка", "Для данного документа отсутствует главная форма"));
    end;
    var CurrentRow = TDynamicBean();
    AttrPanel.Params = null;
    AttrPanel.ScrollingId = menuId;
    CurrentRow.Id_NForm = int(cmd.Rec.nform);
    CurrentRow.VersionRec = int(cmd.Rec.vr);
    GenSetProp(CurrentRow, MainTable + "8" + MainPKField, int(cmd.Rec.ID));
    AttrPanel.CurrentRow = CurrentRow;
    cmd.Clear();
    cmd.SqlText = "select id_wpanel, panel from WPANEL where usernick = :Oper and form = :FormId and menu = :MenuId";
    cmd.DeclareAndSet("Oper", string({Oper}), "FormId", CurrentRow.Id_NForm, "MenuId", menuId);
    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;
    var panel;
    var wParams;
    if (cmd.Eof)
        panel = PanelWindow(AttrPanel);
        var panelXml = Rsl2Xml(panel);
        wParams = WebServiceParams(0, 0, 0, 0, 0);
        panel.GetObjectService.Params = wParams.ToStr();
        cmd.Clear();
        cmd.SqlText = "insert into WPANEL (USERNICK, FORM, MENU, PANEL) values (:Oper, :FormId, :MenuId, :PanelXml)";
        cmd.DeclareAndSet("Oper", string({Oper}), "FormId", CurrentRow.Id_NForm, "MenuId", menuId);
        cmd.DeclareAndSetLOB("PanelXml", Rsl2Xml(panel));
        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;
        OraTrnCommit();
        result = WebServiceResult(WebServiceResultType.Window, makeObj("TRslXmlStr", "XmlStr", panelXml));
    else
        panel = Xml2Rsl(cmd.GetByName("panel").AsString);
        var id = GenGetProp(AttrPanel.CurrentRow, MainTable + "8" + MainPKField);
        var version = AttrPanel.CurrentRow.VersionRec;
        wParams = WebServiceParams(id, version, 0, 0, 0);
        panel.GetObjectService.Params = wParams.ToStr();
        result = WebServiceResult(WebServiceResultType.Window, panel);
    end;
    return result;
end;

// Сервис открытия главной формы из панели подчиненной формы
macro OpenMainFormPanel(params)
    var menuId = params.Params;
    var FormID = params.WindowId;
    var Object = params.Model;
    return OpenMainForm(menuId, FormID, Object);
end;

// Сервис открытия главной формы из скроллинга подчиненных форм
macro OpenMainFormScrolling(params)
    var menuId = params.Params;
    var FormID = params.CurrentRow.Id_NForm;
    var Object = params.CurrentRow;
    return OpenMainForm(menuId, FormID, Object);
end;

/*-------Макрофункции получения панели из меню типа Макрос-------------*/
macro GetPanelQuery(params, formId, MacroName, ProcName)
    var wParams = Xml2Rsl(params.Params);
    var result: WebServiceResult;
    var i = 0;
    var cmd = TRslOraQuery();

    if (params.PropIndex("ScrollingId") == -1)
        cmd.SqlText = "select id_nmenuowner from nmenu where id_nmenu = :MenuId";
        cmd.DeclareAndSet("MenuId", wParams.IDNMENU);

        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;

        params.ScrollingId = cmd.GetByName("id_nmenuowner").AsInteger;
    end;

    var menuType = TypeMainMenuMacro;
    cmd.Clear();
    cmd.SqlText = "select id_wpanel, panel from WPANEL where usernick = :Oper and form = :FormId and menu = :MenuId";
    cmd.DeclareAndSet("Oper", string({Oper}), "FormId", formId, "MenuId", wParams.IDNMENU);

    if (not cmd.Execute())
        RunError(ToANSI(cmd.Error));
    end;

    if (cmd.Eof)
        params.menuType = TypeMainMenuMacro;
        params.formId   = formId;
        params.menuId   = wParams.IDNMENU;
        var panel = PanelWindow(params);

        if (wParams.PropIndex("MacroSave") != -1)
            while (i < panel.SysButtons.Size)
                if (panel.SysButtons[i].Name == "save")
                    panel.SysButtons[i].Service.Params = Rsl2Xml(wParams.MacroSave);
                end;
                if (panel.SysButtons[i].Name == "apply")
                    panel.SysButtons[i].Service.Params = Rsl2Xml(wParams.MacroSave);
                end;
                i = i + 1;
            end;
        end;

        if ((StrLen(MacroName) > 0) and (StrLen(ProcName) > 0))
            panel.GetObjectService.MacroName = MacroName;
            panel.GetObjectService.ProcName = ProcName;
        end;

        var panelXml = Rsl2Xml(panel);
        cmd.Clear();
        cmd.SqlText = "insert into WPANEL (USERNICK, FORM, MENU, PANEL) values (:Oper, :FormId, :MenuId, :PanelXml)";
        cmd.DeclareAndSet("Oper", string({Oper}), "FormId", formId, "MenuId", wParams.IDNMENU);
        cmd.DeclareAndSetLOB("PanelXml", Rsl2Xml(panel));

        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;

        OraTrnCommit();
        result = WebServiceResult(WebServiceResultType.Window, makeObj("TRslXmlStr", "XmlStr", panelXml));
    else
        panel = Xml2Rsl(cmd.GetByName("panel").AsString);

        if (wParams.PropIndex("MacroSave") != -1)
            while (i < panel.SysButtons.size)
                if (panel.SysButtons[i].Name == "save")
                    panel.SysButtons[i].Service.Params = Rsl2Xml(wParams.MacroSave);
                end;
                i = i + 1;
            end;
        end;

        var tableName: string = "";
        var PKField: string = "";
        cmd.Clear();

        if (params.ScrollingId == 0)
            cmd.SqlText = "begin :Table := RSP_FORM.GET_MAINTABLEFORM(:FormId, 0); :PK := RSP_FORM.GET_PK_TABLE(:Table); end;";
            cmd.DeclareAndSet("Table", tableName, "FormId", formId, "PK", PKField);
        else
            cmd.SqlText = "begin RSP_FORM.GET_TABLE_PK_FORMMENU(:IDNMenu, :Table, :PK); end;";
            cmd.DeclareAndSet("IDNMenu", params.ScrollingId, "Table", tableName, "PK", PKField);
        end;

        if (not cmd.Execute())
            RunError(ToANSI(cmd.Error));
        end;

        tableName = cmd.GetVariable("Table");
        PKField = cmd.GetVariable("PK");
        var id = 0;
        var version = 0;
        var visaTypeId: integer = 0;

        result = WebServiceResult(WebServiceResultType.Window, panel);
    end;

    return result;
end;
