# WARN: This playbook executing by external shell script
---
  - name: Deploy artifact
    hosts: prod
    gather_facts: false
    vars_files:
      - ~/secrets
      - globals/vars.yml
      - stands/prod/vars.yml
      - certs/prod-cert.yml

    pre_tasks:
      - name: Deploy client SSL cert
        ansible.builtin.copy:
          content: "{{ VAULT_CERT_CONTENT }}"
          dest: ./client-cert.pem
        delegate_to: localhost
        run_once: true
        no_log: true

      - name: Show artifact tag name, stand name
        ansible.builtin.debug:
          msg: 
            - "Artifact: {{ _VERSION_ }}"
            - "Stand: {{ STAND.NAME }}"

    tasks:
      - ansible.builtin.include_role:
          name: transfer
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
        vars:
          src: "{{ GLOBALS.PROD.RUNNER.ARTIFACT.DIRPATH }}/{{ GLOBALS.PROD.MAVEN.ARTIFACT_ID }}-{{ _VERSION_ }}.zip"
          dest: "{{ GLOBALS.PROD.REMOTE.WORKSPACE.DIRPATH }}"
      - ansible.builtin.include_role:
          name: disable-services
        vars:
          list: "{{ STAND.SOFR.SERVICES | difference([{'NAME': 'RsAppServ_SOFR_PLAN'}]) }}"
      - ansible.builtin.include_role:
          name: disable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
        vars:
          list: "{{ STAND.SOFR.SERVICES | difference([{'NAME': 'RsAppServ_SOFR'}]) }}"
      - ansible.builtin.include_role:
          name: disable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
        vars:
          list: "{{ STAND.TOMCAT.SERVICES | difference([{'NAME': 'Tomcat8'},{'NAME': 'Tomcat8_32'}]) }}"
      - ansible.builtin.include_role:
          name: disable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.1.NAME }}" #sgo-ap608
            run_once: yes
        vars:
          list: "{{ STAND.TOMCAT.SERVICES | difference([{'NAME': 'Tomcat8_5_RSHB_SOFR_ALLIANCE'},{'NAME': 'Tomcat8_5_RSHB_SOFR_PROD'}]) }}"
      - ansible.builtin.include_role:
          name: disable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.1.NAME }}" #sgo-ap608
            run_once: yes
        vars:
          list: "{{ STAND.RABBITMQ.SERVICES }}"
      - ansible.builtin.include_role:
          name: disable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
          list:
            - NAME: RSBankWS-Proxy
      - ansible.builtin.include_role:
          name: unpack
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
        vars:
          filepath: "{{ GLOBALS.PROD.REMOTE.WORKSPACE.DIRPATH }}\\{{ GLOBALS.PROD.MAVEN.ARTIFACT_ID }}-{{ _VERSION_ }}.zip"
          jobid: ''
      - ansible.builtin.include_role:
          name: configs
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
        vars:
          dirpathprops: "{{ GLOBALS.PROD.REMOTE.RSBANKWS_PROXY.CONFIG.DIRPATH }}"
          dirpathjswconf: "{{ GLOBALS.PROD.REMOTE.JSW.CONFIG.DIRPATH }}"
          stand: "{{ STAND.NAME }}"
          config: "{{ GLOBALS.PROD.REMOTE.RSBANKWS_PROXY.CONFIG.NAME }}"
          wconfig: "{{ GLOBALS.PROD.REMOTE.JSW.CONFIG.NAME }}"
        when: _RECONFIG_ == 'yes'
      - ansible.builtin.include_role:
          name: jar
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
        vars:
          artifact: "{{ GLOBALS.PROD.REMOTE.WORKSPACE.DIRPATH }}\\{{ GLOBALS.PROD.MAVEN.ARTIFACT_ID }}-{{ _VERSION_ }}"
          jar: "{{ GLOBALS.PROD.MAVEN.ARTIFACT_ID | regex_replace('-custom', '') }}.jar"
          proxy: "{{ GLOBALS.PROD.REMOTE.RSBANKWS_PROXY.DIRPATH }}"
      - ansible.builtin.include_role:
          name: enable-services
        vars:
          list: "{{ STAND.SOFR.SERVICES | difference([{'NAME': 'RsAppServ_SOFR_PLAN'}]) }}"
      - ansible.builtin.include_role:
          name: enable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
        vars:
          list: "{{ STAND.SOFR.SERVICES | difference([{'NAME': 'RsAppServ_SOFR'}]) }}"
      - ansible.builtin.include_role:
          name: enable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
        vars:
          list: "{{ STAND.TOMCAT.SERVICES | difference([{'NAME': 'Tomcat8'},{'NAME': 'Tomcat8_32'}]) }}"
      - ansible.builtin.include_role:
          name: enable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.1.NAME }}" #sgo-ap608
            run_once: yes
        vars:
          list: "{{ STAND.TOMCAT.SERVICES | difference([{'NAME': 'Tomcat8_5_RSHB_SOFR_ALLIANCE'},{'NAME': 'Tomcat8_5_RSHB_SOFR_PROD'}]) }}"
      - ansible.builtin.include_role:
          name: enable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.1.NAME }}" #sgo-ap608
            run_once: yes
        vars:
          list: "{{ STAND.RABBITMQ.SERVICES }}"
      - ansible.builtin.include_role:
          name: enable-services
          apply:
            delegate_to: "{{ STAND.HOSTS.0.NAME }}" #sgo-ap605
            run_once: yes
          list:
            - NAME: RSBankWS-Proxy