# WARN: This playbook executing by external shell script
---
  - name: Deploy artifact
    hosts: preprod
    gather_facts: false
    vars_files:
      - ~/secrets
      - globals/vars.yml
      - stands/preprod/vars.yml
      - certs/prod-cert.yml

    pre_tasks:
      - name: Deploy client SSL cert
        ansible.builtin.copy:
          content: "{{ VAULT_CERT_CONTENT }}"
          dest: ./client-cert.pem
        delegate_to: localhost
        run_once: true
        no_log: true

      - name: Show artifact tag name, stand name
        ansible.builtin.debug:
          msg: 
            - "Artifact: {{ _VERSION_ }}"
            - "Stand: {{ STAND.NAME }}"

    tasks:
      - ansible.builtin.include_role:
          name: transfer
        vars:
          src: "{{ GLOBALS.PREPROD.RUNNER.ARTIFACT.DIRPATH }}/{{ GLOBALS.PREPROD.MAVEN.ARTIFACT_ID }}-{{ _VERSION_ }}.zip"
          dest: "{{ GLOBALS.PREPROD.REMOTE.WORKSPACE.DIRPATH }}"
      - ansible.builtin.include_role:
          name: disable-services
        vars:
          list: "{{ STAND.SOFR.SERVICES }}"
      - ansible.builtin.include_role:
          name: disable-services
        vars:
          list: "{{ STAND.TOMCAT.SERVICES }}"
      - ansible.builtin.include_role:
          name: disable-services
        vars:
          list:
            - NAME: RSBankWS-Proxy
      - ansible.builtin.include_role:
          name: unpack
        vars:
          filepath: "{{ GLOBALS.PREPROD.REMOTE.WORKSPACE.DIRPATH }}\\{{ GLOBALS.PREPROD.MAVEN.ARTIFACT_ID }}-{{ _VERSION_ }}.zip"
          jobid: ''
      - ansible.builtin.include_role:
          name: configs
        vars:
          dirpathprops: "{{ GLOBALS.PREPROD.REMOTE.RSBANKWS_PROXY.CONFIG.DIRPATH }}"
          dirpathjswconf: "{{ GLOBALS.PREPROD.REMOTE.JSW.CONFIG.DIRPATH }}"
          stand: "{{ STAND.NAME }}"
          config: "{{ GLOBALS.PREPROD.REMOTE.RSBANKWS_PROXY.CONFIG.NAME }}"
          wconfig: "{{ GLOBALS.PREPROD.REMOTE.JSW.CONFIG.NAME }}"
        when: _RECONFIG_ == 'yes'
      - ansible.builtin.include_role:
          name: jar
        vars:
          artifact: "{{ GLOBALS.PREPROD.REMOTE.WORKSPACE.DIRPATH }}\\{{ GLOBALS.PREPROD.MAVEN.ARTIFACT_ID }}-{{ _VERSION_ }}"
          jar: "{{ GLOBALS.PREPROD.MAVEN.ARTIFACT_ID }}.jar"
          proxy: "{{ GLOBALS.PREPROD.REMOTE.RSBANKWS_PROXY.DIRPATH }}"
      - ansible.builtin.include_role:
          name: enable-services
        vars:
          list: "{{ STAND.SOFR.SERVICES }}"
      - ansible.builtin.include_role:
          name: enable-services
        vars:
          list: "{{ STAND.TOMCAT.SERVICES }}"
      - ansible.builtin.include_role:
          name: enable-services
        vars:
          list: 
            - NAME: RSBankWS-Proxy