# WARN: This playbook executing in rsbankws-proxy-cicd pipeline
---
  - name: Deploy artifact
    hosts: "{{ _HOST_ }}"
    gather_facts: false
    vars_files:
    # declared in rsbankws-proxy-cicd
      - "{{ _CI_PROJECT_DIR_ }}/globals/vault.yml"
      - "{{ _CI_PROJECT_DIR_ }}/globals/vars.yml"
      - "{{ _CI_PROJECT_DIR_ }}/certs/cert.yml"
      - "{{ _CI_PROJECT_DIR_ }}/stands/{{ _STAND_ }}/vault.yml"
      - "{{ _CI_PROJECT_DIR_ }}/stands/{{ _STAND_ }}/vars.yml"

    pre_tasks:
      - name: Deploy client SSL cert
        ansible.builtin.copy:
          content: "{{ VAULT_CERT_CONTENT }}"
          dest: "{{ _CI_PROJECT_DIR_ }}/client-cert.pem"
        delegate_to: localhost
        no_log: true

      - name: Show artifact tag name, stand name
        ansible.builtin.debug:
          msg: 
            - "Artifact: {{ _VERSION_ }}"
            - "Stand: {{ STAND.NAME }}"

    tasks:
      - ansible.builtin.include_role:
          name: transfer
        vars:
          src: "{{ GLOBALS.TEST.RUNNER.ARTIFACT.DIRPATH }}/{{ GLOBALS.TEST.MAVEN.ARTIFACT_ID }}-{{ _VERSION_ }}.zip"
          dest: "{{ GLOBALS.TEST.REMOTE.WORKSPACE.DIRPATH }}"
      - ansible.builtin.include_role:
          name: disable-services
        vars:
          list: "{{ STAND.SOFR.SERVICES }}"
      - ansible.builtin.include_role:
          name: disable-services
        vars:
          list: "{{ STAND.TOMCAT.SERVICES }}"
      - ansible.builtin.include_role:
          name: disable-services
        vars:
          list:
            - NAME: RSBankWS-Proxy
      - ansible.builtin.include_role:
          name: unload
      - ansible.builtin.include_role:
          name: unpack
        vars:
          filepath: "{{ GLOBALS.TEST.REMOTE.WORKSPACE.DIRPATH }}\\{{ GLOBALS.TEST.MAVEN.ARTIFACT_ID }}-{{ _VERSION_ }}.zip"
          jobid: "{{ GLOBALS.TEST.GITLAB.JOB_ID }}"
      - ansible.builtin.include_role:
          name: configs
        vars:
          dirpathprops: "{{ GLOBALS.TEST.REMOTE.WEBAPPS.PROPERTIES.DIRPATH }}"
          dirpathjsw: "{{ GLOBALS.TEST.REMOTE.JSW.DIRPATH }}"
          stand: "{{ STAND.NAME }}"
          config: "{{ GLOBALS.TEST.REMOTE.RSBANKWS_PROXY.CONFIG }}"
        when: _RECONFIG_ == 'yes'
      - ansible.builtin.include_role:
          name: jar
        vars:
          artifact: "{{ GLOBALS.TEST.REMOTE.WORKSPACE.DIRPATH }}\\{{ GLOBALS.TEST.MAVEN.ARTIFACT_ID }}-{{ _VERSION_ }}{{ GLOBALS.TEST.GITLAB.JOB_ID }}"
          jar: "{{ GLOBALS.TEST.MAVEN.ARTIFACT_ID }}.jar"
          proxy: "{{ GLOBALS.TEST.REMOTE.RSBANKWS_PROXY.DIRPATH }}"
      - ansible.builtin.include_role:
          name: enable-services
        vars:
          list: "{{ STAND.SOFR.SERVICES }}"
      - ansible.builtin.include_role:
          name: enable-services
        vars:
          list: "{{ STAND.TOMCAT.SERVICES }}"
      - ansible.builtin.include_role:
          name: enable-services
        vars:
          list: 
            - NAME: RSBankWS-Proxy
      - ansible.builtin.include_role:
          name: notify
        vars:
          stand: "{{ STAND.NAME }}"
          release: "{{ _VERSION_ }}"
          token: "{{ VAULT.CREDS.TELEGRAM.TOKEN }}"
          telegram_chat_id: "{{ VAULT.CREDS.TELEGRAM.CHAT_ID }}"
          joburl: "{{ GLOBALS.TEST.GITLAB.JOB_URL }}"
      - ansible.builtin.include_role:
          name: register
        vars:
          date: "{{ GLOBALS.TEST.GITLAB.JOB_STARTED_AT.split('T').0 }}" 
          time: "{{ GLOBALS.TEST.GITLAB.JOB_STARTED_AT.split('T').1 | regex_search('\\d\\d:\\d\\d') }}"
          jobnum: "{{ GLOBALS.TEST.GITLAB.JOB_ID | regex_replace('_', '') }}"
          user_tag: "{{ GLOBALS.TEST.GITLAB.USER_LOGIN }}"
          stand: "{{ STAND.NAME }}"
          release: "{{ _VERSION_ }}"
          file: pipeline.log
          stand_dir: "{{ STAND.SOFR.DIRPATH }}"