-- Таблица "DUSERREFGOSREG_DBT"

CREATE TABLE DUSERREFGOSREG_DBT (
    T_ID NUMBER(10)
  , T_REQUESTNUMBER NUMBER(10)
  , T_STARTDATE DATE
  , T_ENDDATE DATE
  , T_REQUESTREGISTRATIONDATE DATE
  , T_CLIENTID VARCHAR2(100)
  , T_SYSTEMID VARCHAR2(50)
  , T_SYSTEMNODEID VARCHAR2(50)
  , T_PARTYID NUMBER(10)
  , T_SYSDATE DATE
)
/

COMMENT ON TABLE DUSERREFGOSREG_DBT IS 'Экземпляры запроса справки госслужащего'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_ID IS 'Идентификатор'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_REQUESTNUMBER IS 'Идентификатор запроса'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_STARTDATE IS 'Дата начала периода'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_ENDDATE IS 'Дата окончания периода'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_REQUESTREGISTRATIONDATE IS 'Дата и время регистрации запроса'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_CLIENTID IS 'Код клиента'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_SYSTEMID IS 'Идентификатор системы/приложения'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_SYSTEMNODEID IS 'Идентификатор узла/экземпляра системы/приложения'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_PARTYID IS 'Идентификатор клиента в СОФР'
/
COMMENT ON COLUMN DUSERREFGOSREG_DBT.T_SYSDATE IS 'Системная дата'
/

CREATE UNIQUE INDEX DUSERREFGOSREG_DBT_IDX0 ON DUSERREFGOSREG_DBT (
   T_ID ASC
)
/

CREATE SEQUENCE DUSERREFGOSREG_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DUSERREFGOSREG_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DUSERREFGOSREG_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DUSERREFGOSREG_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DUSERREFGOSREG_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER DUSERREFGOSREG_DBT_SYSDATE
  BEFORE INSERT ON DUSERREFGOSREG_DBT FOR EACH ROW
DECLARE
BEGIN
  :NEW.T_SYSDATE := SYSDATE;
END;
/


