--Пересоздание индекса DUSERREFGOSREGAVOIR_DBT_IDX1 на неуникальный
DROP INDEX DUSERREFGOSREGAVOIR_DBT_IDX1
/

CREATE INDEX DUSERREFGOSREGAVOIR_DBT_IDX1 ON DUSERREFGOSREGAVOIR_DBT (
   T_REFID ASC
  ,T_FIID ASC
)
/

