DECLARE
    cnt     NUMBER;
BEGIN
  SELECT COUNT (1)
    INTO cnt
    FROM DOBJGROUP_DBT
   WHERE T_OBJECTTYPE = 12 AND T_GROUPID = 131;

  IF CNT > 0
  THEN
     DELETE 
        FROM DOBJATCOR_DBT
       WHERE T_OBJECTTYPE = 12 AND T_GROUPID = 131;    
     DELETE 
        FROM DOBJATTR_DBT
       WHERE T_OBJECTTYPE = 12 AND T_GROUPID = 131; 
     DELETE 
        FROM DOBJGROUP_DBT
       WHERE T_OBJECTTYPE = 12 AND T_GROUPID = 131; 
  END IF;
END;
/