-- Таблица "DTRNRULESHIST_DBT"

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE DTRNRULESHIST_DBT ( ' ||
                '    T_HISTID NUMBER(10) ' ||
                '  , T_ACTION NUMBER(5) ' ||
                '  , T_CHANGEDATEHIST DATE ' ||
                '  , T_OPERID NUMBER(10) ' ||
                '  , T_ID NUMBER(10) ' ||
                '  , T_ACC_MASK VARCHAR2(25) ' ||
                '  , T_SIDE NUMBER(5) ' ||
                '  , T_ATTR_KIND NUMBER(5) ' ||
                '  , T_OPER NUMBER(5) ' ||
                '  , T_ATTR_VALUE VARCHAR2(32) ' ||
                '  , T_ISACTIVE CHAR(1) ' ||
                '  , T_STARTDATE DATE ' ||
                '  , T_ENDDATE DATE ' ||
                '  , T_CHANGEDATE DATE )';

EXECUTE IMMEDIATE 'COMMENT ON TABLE DTRNRULESHIST_DBT IS ''История изменения правил''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULESHIST_DBT.T_HISTID IS ''идентификатор записи истории''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULESHIST_DBT.T_ACTION IS ''Вид изменения''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULESHIST_DBT.T_CHANGEDATEHIST IS ''дата изменения''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DTRNRULESHIST_DBT.T_OPERID IS ''идентификатор операциониста''';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/


BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DTRNRULESHIST_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DTRNRULESHIST_DBT_IDX0 ON DTRNRULESHIST_DBT (   T_HISTID ASC)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DTRNRULESHIST_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE   INDEX DTRNRULESHIST_DBT_IDX1 ON DTRNRULESHIST_DBT (   T_ID ASC)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DTRNRULESHIST_DBT_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE DTRNRULESHIST_DBT_SEQ ' ||
                  '  START WITH 1 ' ||
                  '  MAXVALUE 999999999999999999999999999 ' ||
                  '  MINVALUE 1 ' ||
                  '  NOCYCLE ' ||
                  '  NOCACHE ' ||
                  '  NOORDER';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER DTRNRULESHIST_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_HISTID ON DTRNRULESHIST_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_HISTID = 0 OR :NEW.T_HISTID IS NULL) THEN
    SELECT DTRNRULESHIST_DBT_SEQ.NEXTVAL INTO :NEW.T_HISTID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DTRNRULESHIST_DBT_SEQ');
    IF :NEW.T_HISTID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

