-- Таблица "DNPTXRETCONFCH_DBT"

CREATE TABLE DNPTXRETCONFCH_DBT (
    T_ID NUMBER(10)
  , T_RCID NUMBER(10)
  , T_TAXPERIOD_OLD NUMBER(5)
  , T_DATEPART1_OLD DATE
  , T_DATEPART2_OLD DATE
  , T_TAXPERIOD_NEW NUMBER(5)
  , T_DATEPART1_NEW DATE
  , T_DATEPART2_NEW DATE
  , T_OPER NUMBER(5)
  , T_RECDATE DATE
)
/
COMMENT ON TABLE DNPTXRETCONFCH_DBT IS 'Изменения настроечной таблицы'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_ID IS 'Идентификатор записи'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_RCID IS 'Идентификатор записи из настроечной таблицы'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_TAXPERIOD_OLD IS 'Прежний налоговый период'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_DATEPART1_OLD IS 'Прежняя дата отсчета для раздела 1'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_DATEPART2_OLD IS 'Прежняя дата отсчета для раздела 2'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_TAXPERIOD_NEW IS 'Новый налоговый период'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_DATEPART1_NEW IS 'Новая дата отсчета для раздела 1'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_DATEPART2_NEW IS 'Новая дата отсчета для раздела 2'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_OPER IS 'Операционист, изменивший запись'/
COMMENT ON COLUMN DNPTXRETCONFCH_DBT.T_RECDATE IS 'Дата изменения записи'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXRETCONFCH_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXRETCONFCH_DBT_IDX0 ON DNPTXRETCONFCH_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXRETCONFCH_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXRETCONFCH_DBT_IDX1 ON DNPTXRETCONFCH_DBT (
   T_RCID ASC
)
/

CREATE SEQUENCE DNPTXRETCONFCH_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXRETCONFCH_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXRETCONFCH_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXRETCONFCH_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXRETCONFCH_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
