DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXOBJ_DBT ADD T_TAXPERIOD NUMBER(5) DEFAULT 0';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXOBJ_DBT.T_TAXPERIOD IS ''Налоговый период''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/
