BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX DMARKETRATE_DBT_IDX2 ON DMARKETRATE_DBT (T_FIID ASC, T_CONTRACTDAYS  ASC)';
EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS   EXCEPTION;
    PRAGMA EXCEPTION_INIT (E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DIT_TRANSFERRATES_TMP (
   T_FIID NUMBER(10), T_RATE FLOAT (53), T_STARTDATE DATE, T_PERIOD NUMBER(10)
) ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS
    THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX DIT_TRANSFERRATES_TMP_IDX1 ON DIT_TRANSFERRATES_TMP (T_FIID ASC, T_STARTDATE  ASC, T_PERIOD ASC)';
EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX DIT_TRANSFERRATES_TMP_IDX2 ON DIT_TRANSFERRATES_TMP (T_FIID ASC, T_PERIOD ASC)';
EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
END;
/

DECLARE
 v_ParentID NUMBER(10);
 v_KeyIDTR    NUMBER(10);
 v_KeyID    NUMBER(10);
BEGIN

  SELECT t_KeyID INTO v_ParentID
  FROM dregparm_dbt 
  WHERE t_Name = '‘•' AND t_ParentID = 0;

  SELECT t_KeyID INTO v_ParentID
  FROM dregparm_dbt 
  WHERE t_Name = '…‘… ‘‹“†‚€…' AND t_ParentID = v_ParentID;

  BEGIN

    INSERT INTO dregparm_dbt(T_KEYID, T_PARENTID, T_NAME, T_TYPE, T_GLOBAL, T_DESCRIPTION, T_SECURITY, T_ISBRANCH, T_TEMPLATE)
       VALUES(0, v_ParentID, '’€‘”…›… ‘’€‚ €‘', 0, chr(0), '', chr(0), chr(0), chr(1))
     RETURNING T_KEYID INTO v_KeyIDTR;

    INSERT INTO dregval_dbt(T_KEYID, T_REGKIND, T_OBJECTID, T_BLOCKUSERVALUE, T_EXPDEP, T_LINTVALUE, T_LDOUBLEVALUE, T_FMTBLOBDATA_XXXX)
       VALUES(v_KeyIDTR, 0, 0, chr(0), 0, 0, 0, '');
       
    INSERT INTO dregparm_dbt(T_KEYID, T_PARENTID, T_NAME, T_TYPE, T_GLOBAL, T_DESCRIPTION, T_SECURITY, T_ISBRANCH, T_TEMPLATE)
       VALUES(0, v_KeyIDTR, '’ ’.‘’€‚ ‘. KAFKA', 0, chr(0), '¬―®ΰβ βΰ ­αδ¥ΰ­λε αβ Ά®ª ¨α―®«μ§γξ Kafka; 1 - ¤ , 0 - ­¥β', chr(0), chr(0), chr(1))
     RETURNING T_KEYID INTO v_KeyID;

    INSERT INTO dregval_dbt(T_KEYID, T_REGKIND, T_OBJECTID, T_BLOCKUSERVALUE, T_EXPDEP, T_LINTVALUE, T_LDOUBLEVALUE, T_FMTBLOBDATA_XXXX)
       VALUES(v_KeyID, 0, 0, chr(0), 0, 1, 0, '');
       
    UPDATE dregparm_dbt SET T_PARENTID = v_KeyIDTR WHERE T_NAME = 'EMAIL_„‹__‡€ƒ_’€‘”_‘’';

  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN NULL;
  END;

EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
END;
/

BEGIN
    INSERT INTO DBANK_MSG(T_NUMBER,T_PAGE,T_CONTENTS) VALUES (29205, 0, '¥¤ ªβ¨ΰ®Ά ­¨¥ ―ΰ®ζ¥­β­λε αβ Ά®ª § ―ΰ¥ι¥­®, ¨¬―®ΰβ  Άβ®¬ β¨η¥αª¨ ®αγι¥αβΆ«ο¥βαο ¨§ α¨αβ¥¬λ €‘');
END;
/
