-- Таблица "DUSERREFGOSREGAVOIR_DBT"

CREATE TABLE DUSERREFGOSREGAVOIR_DBT (
    T_REFID NUMBER(10)
  , T_TYPENAMENONSTOCKINFO VARCHAR2(150)
  , T_ISINLSIN VARCHAR2(35)
  , T_FIID NUMBER(10)
  , T_ISSUERNAME VARCHAR2(150)
  , T_NOMINALSUM NUMBER(32,12)
  , T_TOTALQUANTITYNONSTOCK NUMBER(32,12)
  , T_TOTALAMOUNTNONSTOCK NUMBER(32,12)
  , T_FROMSOFR CHAR(1)
  , T_ERRORNUM NUMBER(5)
  , T_ERRORTEXT VARCHAR2(300)
  , T_GUID VARCHAR2(32)
)
/

COMMENT ON TABLE DUSERREFGOSREGAVOIR_DBT IS 'Данные по ЦБ справка госслужащего'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_REFID IS 'Идентификатор экземпляра запроса'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_TYPENAMENONSTOCKINFO IS 'Вид и наименование ценной бумаги'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_ISINLSIN IS 'Идентификатор выпуска ISIN/LSIN'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_FIID IS 'Идентификатор выпуска в СОФР'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_ISSUERNAME IS 'Лицо, выдавшее (выпустившее) ценную бумагу'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_NOMINALSUM IS 'Номинальная величина обязательств (руб.)'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_TOTALQUANTITYNONSTOCK IS 'Общее количество'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_TOTALAMOUNTNONSTOCK IS 'Общая стоимость (руб.)'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_FROMSOFR IS 'Признак обновления данных из СОФР'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_ERRORNUM IS 'Код ошибки'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_ERRORTEXT IS 'Текст ошибки'
/
COMMENT ON COLUMN DUSERREFGOSREGAVOIR_DBT.T_GUID IS 'Уникальный текстовый GUID по строке'
/

CREATE INDEX DUSERREFGOSREGAVOIR_DBT_IDX0 ON DUSERREFGOSREGAVOIR_DBT (
   T_REFID ASC
)
/

CREATE UNIQUE INDEX DUSERREFGOSREGAVOIR_DBT_IDX1 ON DUSERREFGOSREGAVOIR_DBT (
   T_REFID ASC
  ,T_FIID ASC
)
/

