-- Таблица "DNPTXRETCONF_DBT"

CREATE TABLE DNPTXRETCONF_DBT (
    T_ID NUMBER(10)
  , T_TAXPERIOD NUMBER(5)
  , T_DATEPART1 DATE
  , T_DATEPART2 DATE
  , T_OPER NUMBER(5)
  , T_RECDATE DATE
)
/
COMMENT ON TABLE DNPTXRETCONF_DBT IS 'Настроечная таблица дат для отраж. возвр'/
COMMENT ON COLUMN DNPTXRETCONF_DBT.T_ID IS 'Идентификатор записи'/
COMMENT ON COLUMN DNPTXRETCONF_DBT.T_TAXPERIOD IS 'Налоговый период'/
COMMENT ON COLUMN DNPTXRETCONF_DBT.T_DATEPART1 IS 'Дата отсчета для раздела 1'/
COMMENT ON COLUMN DNPTXRETCONF_DBT.T_DATEPART2 IS 'Дата отсчета для раздела 2'/
COMMENT ON COLUMN DNPTXRETCONF_DBT.T_OPER IS 'Пользователь'/
COMMENT ON COLUMN DNPTXRETCONF_DBT.T_RECDATE IS 'Дата записи'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXRETCONF_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXRETCONF_DBT_IDX0 ON DNPTXRETCONF_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXRETCONF_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXRETCONF_DBT_IDX1 ON DNPTXRETCONF_DBT (
   T_TAXPERIOD ASC
)
/

CREATE SEQUENCE DNPTXRETCONF_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXRETCONF_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXRETCONF_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXRETCONF_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXRETCONF_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER DNPTXRETCONF_DBT_TAIU
  AFTER INSERT OR UPDATE 
  ON DNPTXRETCONF_DBT
  FOR EACH ROW
DECLARE
BEGIN

  IF UPDATING THEN
    INSERT INTO DNPTXRETCONFCH_DBT (T_ID, T_RCID, T_TAXPERIOD_OLD, T_DATEPART1_OLD, T_DATEPART2_OLD, T_TAXPERIOD_NEW, T_DATEPART1_NEW, T_DATEPART2_NEW, T_OPER, T_RECDATE)
    VALUES(0, :NEW.T_ID, :OLD.T_TAXPERIOD, :OLD.T_DATEPART1, :OLD.T_DATEPART2, :NEW.T_TAXPERIOD, :NEW.T_DATEPART1, :NEW.T_DATEPART2, :NEW.T_OPER, :NEW.T_RECDATE);
  ELSE
    INSERT INTO DNPTXRETCONFCH_DBT (T_ID, T_RCID, T_TAXPERIOD_OLD, T_DATEPART1_OLD, T_DATEPART2_OLD, T_TAXPERIOD_NEW, T_DATEPART1_NEW, T_DATEPART2_NEW, T_OPER, T_RECDATE)
    VALUES(0, :NEW.T_ID, 0, TO_DATE('01.01.0001','DD.MM.YYYY'), TO_DATE('01.01.0001','DD.MM.YYYY'), :NEW.T_TAXPERIOD, :NEW.T_DATEPART1, :NEW.T_DATEPART2, :NEW.T_OPER, :NEW.T_RECDATE);
  END IF;

END;
/
