DECLARE
    cnt     NUMBER;
    v_keyId NUMBER;
BEGIN
  SELECT COUNT (1)
    INTO cnt
    FROM DREGPARM_DBT
   WHERE T_NAME = '„€’€ €—. ‚ˆ„ˆŒŽ‘’ˆ ‡€—ˆ‘‹…ˆ‰';

  IF CNT = 0
  THEN
    SELECT T_KEYID INTO v_keyId FROM DREGPARM_DBT WHERE T_NAME = 'SECUR' AND t_parentid = 0;

    INSERT INTO DREGPARM_DBT (T_NAME, T_TYPE, T_DESCRIPTION, T_PARENTID)
      VALUES('„€’€ €—. ‚ˆ„ˆŒŽ‘’ˆ ‡€—ˆ‘‹…ˆ‰',2,'„€’€ €—. ‚ˆ„ˆŒŽ‘’ˆ ‡€—ˆ‘‹…ˆ‰',v_keyId) 
      RETURNING t_keyid INTO v_keyId;

    INSERT INTO DREGVAL_DBT (T_KEYID, T_LINTVALUE, T_EXPDEP, T_OBJECTID, T_REGKIND,T_FMTBLOBDATA_XXXX)
      VALUES(v_keyId,0,0,0,0,to_blob(utl_raw.cast_to_raw('26.10.2020')));

  COMMIT;
  END IF;
END;