-- Таблица "DUSERREFGOSREGINC_DBT"

CREATE TABLE DUSERREFGOSREGINC_DBT (
    T_REFID NUMBER(10)
  , T_INCOMETYPE VARCHAR2(100)
  , T_INCOMETYPENUM NUMBER(5)
  , T_INCOMEAMOUNT NUMBER(32,12)
  , T_FROMSOFR CHAR(1)
)
/

COMMENT ON TABLE DUSERREFGOSREGINC_DBT IS 'Данные по видам дохода справка госслужащего'
/
COMMENT ON COLUMN DUSERREFGOSREGINC_DBT.T_REFID IS 'Идентификатор экземпляра запроса'
/
COMMENT ON COLUMN DUSERREFGOSREGINC_DBT.T_INCOMETYPE IS 'Вид Дохода'
/
COMMENT ON COLUMN DUSERREFGOSREGINC_DBT.T_INCOMETYPENUM IS 'Числовой идентификатор вида дохода'
/
COMMENT ON COLUMN DUSERREFGOSREGINC_DBT.T_INCOMEAMOUNT IS 'Величина дохода (руб.)'
/
COMMENT ON COLUMN DUSERREFGOSREGINC_DBT.T_FROMSOFR IS 'Признак данных из СОФР'
/

CREATE INDEX DUSERREFGOSREGINC_DBT_IDX0 ON DUSERREFGOSREGINC_DBT (
   T_REFID ASC
)
/

CREATE INDEX DUSERREFGOSREGINC_DBT_IDX1 ON DUSERREFGOSREGINC_DBT (
   T_REFID ASC
  ,T_INCOMETYPE ASC
)
/

