DECLARE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVERTB_DBT ADD T_STORSTATE NUMBER (5)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVERTB_DBT.T_STORSTATE IS ''Статус записи в СОФР''';
END;
/