CREATE TABLE SOFR_IPS_IDLNK
(
  T_SERVICEID  NUMBER(5)                        NOT NULL,
  T_INTID      NUMBER(10)                       NOT NULL,
  T_EXTID      NUMBER(15)
)
/

COMMENT ON COLUMN SOFR_IPS_IDLNK.T_SERVICEID IS 'Идентификатор сервиса'/

COMMENT ON COLUMN SOFR_IPS_IDLNK.T_INTID IS 'ID СОФР'/

COMMENT ON COLUMN SOFR_IPS_IDLNK.T_EXTID IS 'ID IPS'/


CREATE UNIQUE INDEX SOFR_IPS_IDLNK_IDX0 ON SOFR_IPS_IDLNK
(T_SERVICEID, T_INTID)
/

CREATE UNIQUE INDEX SOFR_IPS_IDLNK_IDX1 ON SOFR_IPS_IDLNK
(T_EXTID)
/

CREATE SEQUENCE SOFR_IPS_IDLNK_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER "SOFR_IPS_IDLNK_T0_AINC"
   BEFORE INSERT OR UPDATE OF T_EXTID
   ON SOFR_IPS_IDLNK    FOR EACH ROW
DECLARE
   v_id   INTEGER;
BEGIN
   IF (:new.T_EXTID = 0 OR :new.T_EXTID IS NULL)
   THEN
      SELECT SOFR_IPS_IDLNK_SEQ.NEXTVAL INTO :new.T_EXTID FROM DUAL;
   ELSE
      SELECT last_number
        INTO v_id
        FROM user_sequences
       WHERE sequence_name = UPPER ('SOFR_IPS_IDLNK_SEQ');

      IF :new.T_EXTID >= v_id
      THEN
         RAISE DUP_VAL_ON_INDEX;
      END IF;
   END IF;
END;
/

CREATE UNIQUE INDEX SOFR_IPS_MESSAGE_IDX0 ON SOFR_IPS_MESSAGE
(T_ID)
/

CREATE INDEX SOFR_IPS_MESSAGE_IDX1 ON SOFR_IPS_MESSAGE
(T_STATUS, T_SERVICEID)
/
