DECLARE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVER_DBT ADD T_OPER NUMBER(5)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_OPER IS ''Id операциониста''';
END;
/

DECLARE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVER_DBT RENAME COLUMN T_INCLUDECANCELED TO T_RETURNCANCELED';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVER_DBT.T_RETURNCANCELED IS ''Возвращать отмененные''';
END;
/

DECLARE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVERTB_DBT ADD T_RECORD_STATUS CHAR(1)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVERTB_DBT.T_RECORD_STATUS IS ''Статус записи в хранилище СНОБ''';
END;
/

DECLARE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXSNOBVERTB_DBT ADD T_CHECKED CHAR(1)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSNOBVERTB_DBT.T_CHECKED IS ''Признак сверки записи''';
END;
/