DECLARE
BEGIN
   UPDATE DOPROSTEP_DBT
      SET T_SYMBOL = CHR (135)
    WHERE T_BLOCKID = 204703 AND T_NUMBER_STEP = 25 AND T_SYMBOL <> CHR (135);

   UPDATE DOPRSTEP_DBT
      SET T_SYMBOL = CHR (135)
    WHERE T_BLOCKID = 204703 AND T_NUMBER_STEP = 25 AND T_SYMBOL <> CHR (135);

   execute immediate 'DROP INDEX DNPTXSNOBVERTB_DBT_IDX1';

   execute immediate 'CREATE INDEX DNPTXSNOBVERTB_DBT_IDX1 ON DNPTXSNOBVERTB_DBT (T_BATCHID, T_EVENT_ID)';
END;
/