DECLARE
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DGLOBALLOCK_DBT CASCADE CONSTRAINT';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

DECLARE
BEGIN
   EXECUTE IMMEDIATE '
        CREATE TABLE DGLOBALLOCK_DBT
        (
            T_LOCKID   VARCHAR2 (100),
            CONSTRAINT DGLOBALLOCK_PK PRIMARY KEY (T_LOCKID)
        )';
END;
/