BEGIN 
  UPDATE SMB_PROCTYPE 
     SET EXCHANGENAME = 'ëèÅ'
   WHERE FILE_TYPE IN ('SPB03', 'ORDERS', 'MFB06C'); 

  UPDATE SMB_PROCTYPE 
     SET EXCHANGENAME = 'åÅ'
   WHERE FILE_TYPE IN ('SEM02', 'SEM03', 'EQM06', 'SEM25'); 
END;
/