/*
$Name:        dlnt05.mac
$Module:      Неттинг
$Description: макрос шага "Подтверждение сделки"
*/
import "ntgftagrq.mac";

PRIVATE RECORD ntg_buff ("dl_nett");
PRIVATE FILE pmlink ("pmlink") key 1;

/* печать подтверждения */
macro PrintConfirmation( NettingID, IdentProgram )
  var TempFile;

  if( IdentProgram == 14/*IP_SEC*/ ) /*операция выполняется из БОЦБ*/
    message("Идет формирование подтверждения...");

    if ( not FormTagForPrintRQ(NettingID, 0, true) )
      return 1;
    end;

    TempFile = SetOutput( CreateFileName );

    DLWREPS_PrintReportFromTagFile( TempFile );
    SetOutput(NULL, false);
  end;

  return 0;
end;

MACRO ExecuteStep(Buffer, Document)
  SetBuff( ntg_buff, Document );

  ClearRecord(pmlink);
  pmlink.DocKind    = ntg_buff.DocKind;
  pmlink.DocumentID = ntg_buff.NettingID;
  if((not GetGE(pmlink)) OR (pmlink.DocKind != ntg_buff.DocKind) OR
     (pmlink.DocumentID != ntg_buff.NettingID))
     msgbox("У сделки отсутствуют платежи.| Воспользуйтесь Ctrl-P.");
     return 1;
  end;

  return 0;
END;


/* Макрос постобработки */
MACRO PostStep (    
                CommitOrRollback, /*1-выполнение шага,2 -отакат шага*/
                errTrn,           /* Статус выполнения шага-!0-произошла ошибка */
                FDoc,             /* Указатель на первичный документ */
                ID_Operation,     /* Номер экземпляра операции */
                Num_Step,         /* Номер шага операции(из настроек) */
                Kind_Operation,   /* Вид операции */
                KindDoc,          /* Вид первичного документа */
                KindStep,         /* Вид шага операции */
                ID_Step)          /* Номер шага операции */

  record dl_nett(dl_nett);
  SetBuff(dl_nett, FDoc ); 

  if (errTrn OR (CommitOrRollback == 2)) 
      /* Произошла ошибка или происходит откат */
      return;
  end;

  PrintConfirmation( dl_nett.NettingID, dl_nett.IdentProgram );
  
  return 0;
END;


/* Макрос печати */
MACRO PrintStepDocs (
                ID_Operation,  /* Номер экземпляра операции */
                ID_Step,       /* Номер шага операции */
                Kind_Operation,/* Вид операции */
                KindStep)      /* Вид шага операции */

   file oproper("oproper") ;
   file dl_nett("dl_nett");

   oproper.ID_Operation = ID_Operation;
   if( not GetEQ(oproper) )
      MsgBox("Не найден экземпляр операции");
      return 0;
   end;

   dl_nett.NettingID = int(oproper.DocumentID);
   if( not GetEQ(dl_nett) )
      MsgBox("Не первичный документ <dl_nett.dbt>");
      return 0;
   end;

   PrintConfirmation( dl_nett.NettingID, dl_nett.IdentProgram );

   exit(1); /*Для того, чтобы не выводился пустой файл */

END;
