/*
$Name:         vsf027.mac
$Module:       Собственные векселя
$Description:  Шаг "Перенос к исполнению" операции "Погашение собственных векселей банка, выданных другим филиалом"
*/

/* Операция погашения векселя другого филиала. шаг перевод на счет к исполнению.*/
IMPORT OprInter, vsdates, vsmove, vsrep;


/* Запуск шага
*/
MACRO ExecuteStep(Buffer, dl_order, DocKind, ID_Operation, ID_Step)
var StepDate, stat = 0;

    record order( dl_order );
    SetBuff( order, dl_order );

    /*PNV 528376*/
    if(not VS_TestStepDate(DATE_BART_PAY, @StepDate, order.SignDate))
        stat = 1;
    end;
    /*PNV 528376*/

    if(not ПереводВекселейКИспол(order, StepDate))
       stat = 1;
    end;

    if ((StepDate >= GetStartSTBDate()) and (FilterMakeNDRObj(order.Contractor) == OBJ_FIZ_KND) and (IsNoNDLFOpr(order.ContractID) == false))
        if( not InsertOprStatus(VS_OPERSTATUS_VSDEALS_ENDED_SNOB, VS_OPERSTATUS_VSDEALS_ENDED_RUN)) //Запрос СНОБ = Выполнить
            msgBox( "Ошибка при установке статуса вида \"Запрос СНОБ\" операции" );
          return 1;
        end;
        /*Принудительная вставка блока по символу*/
        Opr_InsertBranch("S", OPRBR_PARALLEL, true);
    else
      if( not InsertOprStatus(VS_OPERSTATUS_VSDEALS_ENDED_SNOB, VS_OPERSTATUS_VSDEALS_ENDED_COMPLETE)) //Запрос СНОБ = Завершить
        msgBox( "Ошибка при установке статуса вида \"Запрос СНОБ\" операции" );
        return 1;
      end;
      if( not InsertOprStatus(VS_OPERSTATUS_VSDEALS_ENDED_ZPHR, VS_OPERSTATUS_VSDEALS_ENDED_COMPLETE)) //Формирование и передача записи в хран. = Завершить
        msgBox( "Ошибка при установке статуса вида \"Формирование и передача записи в хран.\" операции" );
        return 1;
      end;

      if( not InsertOprStatus(1104, 1)) //Завершение шагов операции = Завершить
        msgBox( "Ошибка при установке статуса вида \"Завершение шагов операции\" операции" );
        return 1;
      end;
      /*Принудительная вставка блока по символу*/
      Opr_InsertBranch("E", OPRBR_PARALLEL, true);
    end;

    return stat;
END;