import get;


/*
   Макрофайл описания общих переменных
*/

/* Создает экземпляр объекта, имя класса которого и список свойств задаются при помощи строковых параметров */
macro makeObj(className: string)
    const obj = GenObject(className);
    var name, val, num = 1;
    while (getParm(num, name))
        getParm(num + 1, val);
        GenSetProp(obj, name, val);
        num = num + 2;
    end;
    return obj;
end;



//ИД типов меню
const TypeMainMenuAllDoc  = GetIdByCode("SMENU", "ID_SMENU", 1); //Все документы
const TypeMainMenuState   = GetIdByCode("SMENU", "ID_SMENU", 2); //Документы в одном состоянии
const TypeMainMenuVisa    = GetIdByCode("SMENU", "ID_SMENU", 3); //Визирование
const TypeMainMenuPosit   = GetIdByCode("SMENU", "ID_SMENU", 4); //Позиционирование
const TypeMainMenuMonitor = GetIdByCode("SMENU", "ID_SMENU", 5); //Наличие документов
const TypeMainMenuOpDay   = GetIdByCode("SMENU", "ID_SMENU", 6); //Открытие дня
const TypeMainMenuClDay   = GetIdByCode("SMENU", "ID_SMENU", 7); //Зарытие дня
const TypeMainMenuCalend  = GetIdByCode("SMENU", "ID_SMENU", 8); //Календарь
const TypeMainMenuMacro   = GetIdByCode("SMENU", "ID_SMENU",10); //Макрос
const TypeMainMenuDict    = GetIdByCode("SMENU", "ID_SMENU",20); //Справочник
const TypeMenuDictRef     = GetIdByCode("SMENU", "ID_SMENU",21); //Связанный справочник
const TypeMenuFormDep     = GetIdByCode("SMENU", "ID_SMENU",22); //Подчиненные формы
const TypeMenuFormMain    = GetIdByCode("SMENU", "ID_SMENU",23); //Главная форма
const TypeMenuFormRef     = GetIdByCode("SMENU", "ID_SMENU",24); //Связанные формы

/*формы справочников*/
const Type_Spr_SFI   = GetIdByCode("form","ID_FORM",10);
const Type_Spr_NKs   = GetIdByCode("form","ID_FORM",4);


//Полномочия пользователя
const Right_DayOpen  = GetIdByCode("SRIGHT", "ID_SRIGHT", 160); //Открытие опердня
const Right_DayClose = GetIdByCode("SRIGHT", "ID_SRIGHT", 170); //Закрытие опердня



/* Наименования (Id) скроллиногов Позиционирования */
const LeftPositioningSrollingName = "LeftPositioningSrolling";
const RightPositioningSrollingName = "RightPositioningSrolling";


/* Обертка запроса для скроллинга с паджинацией */
macro SQL_WrapSelect( Query:string,    /* Строка запроса */
                      PageNum:integer, /* Номер страницы */
                      PageSize:integer /* Размер страницы */
                    ):string
  var RetVal:string = "";

  RetVal = " SELECT t.* FROM ( SELECT rownum RN, tt.* FROM ( " + Query;

  if( PageSize > 0 )
     RetVal = RetVal + " ) tt WHERE ROWNUM <= " + string(PageSize*(PageNum + 1)) + " ) t WHERE t.RN >= " + string(PageSize*(PageNum) + 1) + " ";
  else
     RetVal = RetVal + " ) tt ) t ";
  end;

  return RetVal;
end;
