import globals, get_mfo, FIInter, ReportInter, PTInter, "bbprncom.mac", "prnlib.mac", likepy;
import prpmbuff, prpmboi;


private const NATCUR            = 0;


var pr_cb_doc:TRecHandler  = TRecHandler("cb_doc.dbt", "bank.def");

MACRO printCB_DOC(cbdoc, pmpaym, rm, NumCopy)

  var Payer,
      Receiver,
      BIC_Payer       = "",
      BIC_Receiver    = "",
      CorAcc_Payer    = "",
      CorAcc_Receiver = "",
      NameDocument    = "",
      Sum,
      SumR,
      dateDoc,
      SPOD_str = IfThenElse( Index( cbdoc.TypeDocument, "‡" ), "‘„", "" );

  /* ®¤£®â®¢ª  áâà®ª ª ¯¥ç â¨ */
  ARRAY SS, SG, SBP, SBR, SP, SR, SCH;

  NameDocument = "Œ…Œˆ€‹œ›‰";
  if( IsCORRECTING( cbdoc.TypeDocument ) )
    NameDocument = "ˆ‘€‚ˆ’…‹œ›‰";
  end;

  if( pmpaym.ValueDate > Date(0, 0, 0) )
     dateDoc = pmpaym.ValueDate;
  else
     dateDoc = {curdate};
  end;

  /*  áç¥â áã¬¬ë ¢ àã¡«ïå */
  if(cbdoc.Code_Currency != NATCUR)
    ConvSum( SumR, pmpaym.Amount, dateDoc, cbdoc.Code_Currency );
  else SumR = "";
  end;
  Sum = CurToStrAlt( pmpaym.Amount, null, null, GetISOCode( cbdoc.Code_Currency ) );

  Payer    = pr_pmrmprop.rec.PayerName;
  Receiver = pr_pmrmprop.rec.ReceiverName;

  if(cbdoc.Code_Currency == NATCUR)
    BIC_Payer = {MFO_Bank};
    CorAcc_Payer = {CORAC_Bank};

    BIC_Receiver = {MFO_Bank};
    CorAcc_Receiver = {CORAC_Bank};
  end;
  strsplit( {Name_Bank},          SBP,   43,43,3 );
  strsplit( {Name_Bank},          SBR,   43,43,3 );
  strsplit( Sum,                  SS,    76,76,2 );
  strsplit( rm.Ground,            SG,    87,67,3 );
  strsplit( Payer,                SP,    43,43,4 );
  strsplit( Receiver,             SR,    43,43,4 );

  GetNameChapter(cbdoc.Chapter, SCH, 23);

  while(NumCopy != 0)

    if(cbdoc.Chapter != 1)
 [
  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³  ############## „… N  ³ ############### ³ #######################           ####     ³
  ³    ##################### ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ                    ³
  ³    #####################                            /„ â /                              ³
  ÃÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
 ](NameDocument:r, rm.Number:c, pmpaym.ValueDate:m:c:f, SPOD_str, SCH(0), SCH(1));
    else
 [
  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³  ############## „… N  ³ ############### ³ #######################           ####     ³
  ³                          ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ                    ³
  ³                                                     /„ â /                              ³
  ÃÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
 ](NameDocument:r, rm.Number:c, pmpaym.ValueDate:m:c:f, SPOD_str);
    end;

 [³ ‘ã¬¬     ³ ############################################################################ ³
  ³ ¯à®¯¨áìî ³ ############################################################################ ³
  ÃÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³ ########################################### ³  ‘ã¬¬    ³ ############################   ³
 ](SS(0), SS(1),SP(0), pmpaym.Amount:l:f);

    if(cbdoc.Code_Currency != NATCUR)
 [³ ########################################### ³          ³ ############################   ³]
  (SP(1), SumR:l:f);
    else
 [³ ########################################### ³          ³ ############################   ³]
  (SP(1), "");
    end;

 [³ ########################################### ÃÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³ « â¥«ìé¨ª ################################ ³  ‘ç.N    ³ #########################      ³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´                                ³
  ³ ########################################### ³  ˆŠ     ³ #################              ³
  ³ ########################################### ÃÄÄÄÄÄÄÄÄÄÄ´                                ³
  ³  ­ª ¯« â¥«ìé¨ª    ######################## ³  ‘ç.N    ³ #########################      ³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³ ########################################### ³  ˆŠ     ³ #################              ³
  ³ ########################################### ÃÄÄÄÄÄÄÄÄÄÄ´                                ³
  ³  ­ª ¯®«ãç â¥«ï    ######################## ³  ‘ç.N    ³ #########################      ³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´                                ³
  ³ ########################################### ³  ‘ç.N    ³ #########################      ³
  ³ ########################################### ÃÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³ ########################################### ³ ˜¨äà.¤®ª.³ ###### ³‘à®ª ¯« â.³            ³
  ³ ########################################### ÃÄÄÄÄÄÄÄÄÄÄ´        ÃÄÄÄÄÄÄÄÄÄÄ´            ³
  ³                                             ³ §­.¯« â.³        ³ç¥à.¯« â.³            ³
  ³ ®«ãç â¥«ì                                  ³   Š®¤    ³        ³¥§.¯®«¥  ³            ³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³  §­ ç¥­¨¥ ¯« â¥¦   ################################################################### ³
  ³ ####################################################################################### ³
  ³ ####################################################################################### ³
  ³                                                                                         ³
  ³                              ®¤¯¨á¨                                                    ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

]
   (SP(2),
    SP(3), pmpaym.PayerAccount,
    SBP(0), BIC_Payer,
    SBP(1), 
    SBP(2), CorAcc_Payer,
    SBR(0), BIC_Receiver,
    SBR(1), 
    SBR(2), CorAcc_Receiver,
    SR(0),  pmpaym.ReceiverAccount,
    SR(1), SR(2), rm.ShifrOper,/* cbdoc.Kind_oper,*/
    SR(3),
    SG(0), SG(1), SG(2) );

    NumCopy = NumCopy - 1;
  end;

END;


MACRO PrintDocument( ncopy:integer):bool
 var DocKind:integer = pr_pmpaym.rec.DocKind;

 if( DocKind != 70/*DLDOC_MEMORIALORDER*/ )
   MsgBox("„ ­­ë© ¢¨¤ ¤®ªã¬¥­â  ­¥ ¯®¤¤¥à¦¨¢ ¥âáï ¬ ªà®á®¬");
   return FALSE;
 end;
 
  if( pr_pmrmprop.rec.ShifrOper == "17" )
    return PrintBankOrder( ncopy );
  else
    printCB_DOC( pr_cb_doc.rec, pr_pmpaym.rec, pr_pmrmprop.rec, ncopy );
    return TRUE;
  end;

END;
