/*──────────────────────────────────────────────────────────────────────────────
Fedosyuk S.I. R-Style Software Lab. Bryansk
Create Data:  05.07.2006
File:         compoper.mac
Name:         Протокол сравнения блоков и видов операций
──────────────────────────────────────────────────────────────────────────────*/
import rsd, "globals.mac";

var countDiffers : integer;
var cmd : RsdCommand;
var cmd_ : RsdCommand;

/*начало печать отчета*/
macro PrintHeader( Type : integer, Block : integer )
  var Header : string;

  Header = "ПРОТОКОЛ СРАВНЕНИЯ ";

  if( Type == 1 )
    Header =  Header + "ВИДОВ ОПЕРАЦИЙ ";
    if( Block == 1 )
      Header = Header + "(включая сравнение блоков операции)";
    else
      Header = Header + "(исключая сравнение блоков операции)";
    end;
  else
    Header = Header + "БЛОКОВ";
  end;

[
###############################################################################
                                                   Дата отчета: ##########

]
( Header:c, date );

end;

macro PrintFooter()
  var str : string;

  if( countDiffers == 0 )
    println( "Различий нет." );
  else
    println( );
    println( "Обнаружено различий: ", countDiffers );
  end;
end;

macro PrintCompareType( Type : integer,
                        ElemID_1 : integer, ElemVer_1 : string, ElemName_1 : string, 
                        ElemID_2 : integer, ElemVer_2 : string, ElemName_2 : string  )
  var str : string;

  str = "\nСравниваются ";

  if( Type == 1 )
    str = str + "виды операций:";
  else
    str = str + "блоки:";
  end;

  println( str );

  str = ElemID_1 + " ( " + ElemVer_1 + " ) " + "\"" + ElemName_1 + "\"";
  println( str );
  str = ElemID_2 + " ( " + ElemVer_2 + " ) " + "\"" + ElemName_2 + "\"";
  println( str );
end;

macro PrintDiffers( strDiffer : string )
  var str : string;
  countDiffers = countDiffers + 1;
  str = countDiffers + ". " + strDiffer;
  println( str );
end;

/*начало печати отчета по блокам*/
/*"Различие в описании блоков <BlockID_1> и <BlockID_2> поля: <список наименований полей таблицы (по русски), в которых найдено различие через запятую> (DOPRBLOCK_DBT)"*/
macro PrintDiffersOPRBLOCK( BlockID_1 : integer, BlockID_2 : integer, FieldsList : string )
  PrintDiffers( "Различия в описании блоков " + BlockID_1 + " и " + BlockID_2 + " поля: " + FieldsList + " (DOPRBLOCK_DBT)" );
end;

/*"Статус при выходе из блока <T_CODE> <T_NAME> со значением <T_NUMVALUE> описан только для блока <T_BLOCKID> (DOPRSBLCK_DBT)"*/
macro PrintNotExistOPRSBLCK( BlockID : integer, Code : string, Name : string, NumValue : integer )
  PrintDiffers( "Статус при выходе из блока " + Code + " " + Name + " со значением " + NumValue + " описан только для блока " + BlockID + " (DOPRSBLCK_DBT)" );
end;

/*"Статус при выходе из блока <T_CODE> <T_NAME> со значением <T_NUMVALUE> задается по умолчанию при выходе из блока <T_BLOCKID> и не задается для соответствущего значения сегмента блока <OTHERBLOCK> (DOPRSBLCK_DBT)"*/
macro PrintNotExistOPRSBLCKDef( BlockID : integer, Code : string, Name : string, NumValue : integer, OtherBlock : integer )
  PrintDiffers( "Статус при выходе из блока " + Code + " " + Name + " со значением " + NumValue + " задается по умолчанию при выходе из блока " + BlockID + " и не задается для соответствущего значения сегмента блока " + OtherBlock + " (DOPRSBLCK_DBT)" );
end;

/*"Различие в описании настроек шага номер <T_NUMBER_STEP> блоков <BlockID_1> и <BlockID_2> поля: <список наименований полей таблицы (по русски), в которых найдено различие через запятую> (DOPROSTEP_DBT)"*/
macro PrintDiffersOPROSTEP( BlockID_1 : integer, BlockID_2 : integer, NumberStep : integer, FieldsList : string )
  PrintDiffers( "Различие в описании настроек шага номер " + NumberStep + " блоков " + BlockID_1 + " и " + BlockID_2 + " поля: " + FieldsList + " (DOPROSTEP_DBT)" );
end;

/*"Шаг номер <T_NUMBER_STEP> задан только для блока <T_BLOCKID> (DOPROSTEP_DBT)"*/
macro PrintNotExistOPROSTEP( BlockID : integer, NumberStep : integer )
  PrintDiffers( "Шаг номер " + NumberStep + " задан только для блока " + BlockID + " (DOPROSTEP_DBT)" );
end;

/*"Различие в описании фазы операционного дня для документа "<наименование (T_NAME) документа T_DOCKIND по таблице DOPRKDOC_DBT>" шага номер <T_NUMBER_STEP> блоков <BlockID_1> и <BlockID_2> (DOPROPHASE_DBT)"*/
macro PrintDiffersOPROPHASE( BlockID_1 : integer, BlockID_2 : integer, DocKind : integer, NumberStep : integer )
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = "SELECT t_Name FROM doprkdoc_dbt " +
              "WHERE t_dockind = " + DocKind + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  if( rs.moveNext())
    PrintDiffers( "Различие в описании фазы операционного дня для документа \"" + rs.value(0) + "\" шага номер " + NumberStep + " блоков " + BlockID_1 + " и " + BlockID_2 + " (DOPROPHASE_DBT)" );
  end;
end;

/*"Максимальная фаза опердня задана только для документа "<наименование (T_NAME) документа T_DOCKIND по таблице DOPRKDOC_DBT>" шага номер <T_NUMBER_STEP> блока <T_BLOCKID> и не задана для соответствущего шага блока <OTHERBLOCK> (DOPROPHASE_DBT)"*/
macro PrintNotExistOPROPHASE( BlockID : integer, DocKind : integer, NumberStep : integer, OtherBlock : integer )
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = "SELECT t_Name FROM doprkdoc_dbt " +
              "WHERE t_dockind = " + DocKind + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  if( rs.moveNext())
    PrintDiffers( "Максимальная фаза опердня задана только для документа \"" + rs.value(0) + "\" шага номер " + NumberStep + " блока " + BlockID + " и не задана для соответствущего шага блока " + OtherBlock + " (DOPROPHASE_DBT)" );
  end;
end;

/*"Различие в описании настройки строчек <T_CODE> для шага номер <T_NUMBER_STEP> блоков <BlockID_1> и <BlockID_2> поля: <список наименований полей таблицы (по русски), в которых найдено различие через запятую> (DOPRLINE_DBT)"*/
macro PrintDiffersOPRLINE( BlockID_1 : integer, BlockID_2 : integer, Code : string, NumberStep : integer, FieldsList : string )
  PrintDiffers( "Различие в описании настройки строчек " + Code + " для шага номер " + NumberStep + " блоков " + BlockID_1 + " и " + BlockID_2 + " поля: " + FieldsList + " (DOPRLINE_DBT)" );
end;

/*"Настройка строчек <T_CODE> задана только для шага номер <T_NUMBER_STEP> блока <T_BLOCKID> и не задана для соответствующего шага блока <OTHERBLOCK> (DOPRLINE_DBT)"*/
macro PrintNotExistOPRLINE( BlockID : integer, Code : string, NumberStep : integer, OtherBlock : integer )
  PrintDiffers( "Настройка строчек " + Code + " задана только для шага номер " + NumberStep + " блока " + BlockID + " и не задана для соответствующего шага блока " + OtherBlock + " (DOPRLINE_DBT)" );
end;

/*"Различие в выражении строчки <T_LINECODE> поля документа <T_FIELDNUMBER> для шага операции для шага номер <T_NUMBER_STEP> блоков <BlockID_1> и <BlockID_2> поля: <список наименований полей таблицы (по русски), в которых найдено различие через запятую> (DOPREXPR_DBT)"*/
macro PrintDiffersOPREXPR( BlockID_1 : integer, BlockID_2 : integer, LineCode : string, FieldNumber : integer, NumberStep : integer, FieldsList : string )
  PrintDiffers( "Различие в выражении строчки " + LineCode + " поля документа " + FieldNumber + " для шага операции для шага номер " + NumberStep + " блоков " + BlockID_1 + " и " + BlockID_2 + " поля: " + FieldsList + " (DOPREXPR_DBT)" );
end;

/*"Выражение строчки <T_LINECODE> поля документа <T_FIELDNUMBER> задано только для шага номер <T_NUMBER_STEP> блока <T_BLOCKID> и не задано для соответствующей строчки блока <OTHERBLOCK> (DOPREXPR_DBT)"*/
macro PrintNotExistOPREXPR( BlockID : integer, LineCode : string, FieldNumber : integer, NumberStep : integer, OtherBlock : integer )
  PrintDiffers( "Выражение строчки " + LineCode + " поля документа " + FieldNumber + " задано только для шага номер " + NumberStep + " блока " + BlockID + " и не задано для соответствующей строчки блока " + OtherBlock + " (DOPREXPR_DBT)" );
end;

/*"Различие в настройке <расчета (T_ACTION = OPRKSFCM_ACTION_CALC) или оплаты (T_ACTION = OPRKSFCM_ACTION_PAY)> единовременной комиссии <T_COMMNUMBER> по шага номер <T_NUMBER_STEP> блоков <BlockID_1> и <BlockID_2> поля: <список наименований полей таблицы (по русски), в которых найдено различие через запятую> (DOPRKSFCM_DBT)"*/
macro PrintDiffersOPRKSFCM( BlockID_1 : integer, BlockID_2 : integer, Action : string, CommNumber : integer, NumberStep : integer, FieldsList : string )
  PrintDiffers( "Различие в настройке " + Action + " единовременной комиссии " + CommNumber + " по шага номер " + NumberStep + " блоков " + BlockID_1 + " и " + BlockID_2 + " поля: " + FieldsList + " (DOPRKSFCM_DBT)" );
end;

/*"Настройка <расчета (T_ACTION = OPRKSFCM_ACTION_CALC) или оплаты (T_ACTION = OPRKSFCM_ACTION_PAY)> единовременной комиссии <T_COMMNUMBER> задана только для шага номер <T_NUMBER_STEP> блока <T_BLOCKID> и не задана для соответствущего шага блока <OTHERBLOCK> (DOPRKSFCM_DBT)"*/
macro PrintNotExistOPRKSFCM( BlockID : integer, Action : string, CommNumber : integer, NumberStep : integer, OtherBlock : integer )
  PrintDiffers( "Настройка " + Action + " единовременной комиссии " + CommNumber + " задана только для шага номер " + NumberStep + " блока " + BlockID + " и не задана для соответствущего шага блока " + OtherBlock + " (DOPRKSFCM_DBT)" );
end;

/*"Различие в настройке показа шагов и документов для операциониста <T_OPER> шага номер <T_NUMBER_STEP> блоков <BlockID_1> и <BlockID_2> (DOPRSHOW_DBT)"*/
macro PrintDiffersOPRSHOW( BlockID_1 : integer, BlockID_2 : integer, NumberStep : integer, Oper : integer )
  PrintDiffers( "Различие в настройке показа шагов и документов для операциониста " + Oper + " шага номер " + NumberStep + " блоков " + BlockID_1 + " и " + BlockID_2 + " (DOPRSHOW_DBT)" );
end;

/*"Настройка показа шагов и документов операцианисту <T_OPER> задана только для шага номер <T_NUMBER_STEP> блока <T_BLOCKID> и не задана для соответствующего шага блока <OTHERBLOCK> (DOPRSHOW_DBT)"*/
macro PrintNotExistOPRSHOW( BlockID : integer, NumberStep : integer, Oper : integer, OtherBlock : integer )
  PrintDiffers( "Настройка показа шагов и документов операцианисту " + Oper + " задана только для шага номер " + NumberStep + " блока " + BlockID + " и не задана для соответствующего шага блока " + OtherBlock + " (DOPRSHOW_DBT)" );
end;
/*конец печати отчета по блокам*/

/*начало печати отчета по видам операций*/
/*"Различие в описании видов операций < Operation_Kind_1> и < Operation_Kind_2> поля: <список наименований полей таблицы (по русски), в которых найдено различие через запятую> (DOPRKOPER_DBT)"*/
macro PrintDiffersOPRKOPER( KindOperation_1 : integer, KindOperation_2 : integer, FieldsList : string )
  PrintDiffers( "Различие в описании видов операций " + KindOperation_1 + " и " + KindOperation_2 + " поля: " + FieldsList + " (DOPRKOPER_DBT)" );
end;

/*"Различие в описании проверки документа в начале операции для видов операций < Operation_Kind_1> и < Operation_Kind_2> (DOPRCHDOC_DBT)"*/
macro PrintDiffersOPRCHDOC( KindOperation_1 : integer, KindOperation_2 : integer )
  PrintDiffers( "Различие в описании проверки документа в начале операции для видов операций " + KindOperation_1 + " и " + KindOperation_2 + " (DOPRCHDOC_DBT)" );
end;

/*"Проверка документа задана только для вида операции <T_KIND_OPERATION> (DOPRCHDOC_DBT)"*/
macro PrintNotExistOPRCHDOC( KindOperation_1 : integer )
  PrintDiffers( "Проверка документа задана только для вида операции " + KindOperation_1 + " (DOPRCHDOC_DBT)" );
end;

/*"Различие в описании значения сегмента статуса <T_STATUSKINDID> видов операций <Operation_Kind_1> и <Operation_Kind_2> (DOPRINIST_DBT)"*/
macro PrintDiffersOPRINIST( KindOperation_1 : integer, KindOperation_2 : integer, StatusKindID : integer )
  PrintDiffers( "Различие в описании значения сегмента статуса " + StatusKindID + " видов операций " + KindOperation_1 + " и " + KindOperation_2 + " (DOPRINIST_DBT)" );
end;

/*"Значение сегмента статуса операции задано только для вида операции <T_KIND_OPERATION> и не задано для <OTHEROPER> (DOPRINIST_DBT)"*/
macro PrintNotExistOPRINIST( KindOperation : integer, OtherOper : integer )
  PrintDiffers( "Значение сегмента статуса операции задано только для вида операции " + KindOperation + " и не задано для " + OtherOper + " (DOPRINIST_DBT)" );
end;

/*"Различие в настройке номер <T_SORT> блока <BlockID_1> вида операции < Operation_Kind_1> и блока <BlockID_2> вида операции < Operation_Kind_2> поля: <список наименований полей таблицы (по русски), в которых найдено различие через запятую> (DOPROBLCK_DBT)"*/
macro PrintDiffersOPROBLCK( KindOperation_1 : integer, KindOperation_2 : integer, BlockID_1 : integer, BlockID_2 : integer, t_Sort : integer, FieldsList : string )
  PrintDiffers( "Различие в настройке номер " + t_Sort + " блока " + BlockID_1 + " вида операции " + KindOperation_1 + " и блока " + BlockID_2 + " вида операции " + KindOperation_2 + " поля: " + FieldsList + " (DOPROBLCK_DBT)" );
end;

/*"Настройка <T_OPERBLOCKID> блока <T_BLOCKID> под номером <T_SORT> задана только для вида операции <T_KIND_OPERATION> и не задана для <OTHEROPER> (DOPROBLCK_DBT)"*/
macro PrintNotExistOPROBLCK( KindOperation : integer, t_Sort : integer, OperBlockID : integer, BlockID : integer, OtherOper : integer )
  PrintDiffers( "Настройка " + OperBlockID + " блока " + BlockID + " под номером " + t_Sort + " задана только для вида операции " + KindOperation + " и не задана для " + OtherOper + " (DOPROBLCK_DBT)" );
end;

/*"Различие в условии выполнения блоков операции <OperBlockID_1> вида операции < Operation_Kind_1> и блока <OperBlockID_2> вида операции < Operation_Kind_2> поля: <список наименований полей таблицы (по русски), в которых найдено различие через запятую> (DOPRCBLCK_DBT)"*/
macro PrintDiffersOPRCBLCK( KindOperation_1 : integer, KindOperation_2 : integer, OperBlockID_1 : integer, OperBlockID_2 : integer, FieldsList : string )
  PrintDiffers( "Различие в условии выполнения блоков операции " + OperBlockID_1 + " вида операции " + KindOperation_1 + " и блока " + OperBlockID_2 + " вида операции " + KindOperation_2 + " поля: " + FieldsList + " (DOPRCBLCK_DBT)" );
end;

/**/
macro PrintNotExistOPRCBLCK( StatusKindID : integer, OperBlockID : integer )
  PrintDiffers( "Значение сегмента статуса " + StatusKindID + " условия выполнения блока задано только для настройки блока " + OperBlockID + " (DOPRCBLCK_DBT)" );
end;
/*конец печати отчета по видам операций*/

/*конец печать отчета*/


/*начало сравнения блоков*/
macro CompareFieldsExt( rs : RsdRecordset, startField : integer, numFields : integer, compFields : integer, FieldName, strCompareResult : @string ) : bool
  var countField : integer;
  var IsDif : bool;
  
  strCompareResult = "";
  IsDif = false;
  countField = 0;
  while( countField < compFields )
    if( rs.value( startField + countField ) != rs.value( numFields + startField + countField ))
      if( strlen( strCompareResult ))
        strCompareResult = strCompareResult + ", " + FieldName( countField );
      else
        strCompareResult = FieldName( countField );
      end;
      IsDif = true;
    end;
    countField = countField + 1;
  end;

  return IsDif;
end;

macro CompareFields( rs : RsdRecordset, startField : integer, numFields : integer ) : bool
  var countField : integer;
  var IsDif : bool;
  
  IsDif = false;
  countField = 0;
  while((( startField + countField ) < numFields ) and ( IsDif == false ))
    if( rs.value( startField + countField ) != rs.value( numFields + startField + countField ))
      IsDif = true;
    end;
    countField = countField + 1;
  end;

  return IsDif;
end;

/*Сравнить данные таблицы "Статус при выходе из блока" OPRSBLCK*/
macro CompareOPRSBLCK( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  "t_blockid     " NUMBER(10,0) NOT NULL ENABLE, 
  "t_statuskindid" NUMBER(10,0) NOT NULL ENABLE, 
  "t_numvalue    " NUMBER(5,0), 
*/
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = "SELECT s.T_BLOCKID, s.T_STATUSKINDID, ss.T_CODE, ss.T_NAME, s.T_NUMVALUE " + 
              "FROM doprsblck_dbt s " + 
              "JOIN DOPRSTKND_DBT ss ON (s.T_STATUSKINDID = ss.T_STATUSKINDID) " +
              "WHERE s.T_BLOCKID = " + BlockID_1 +
              "AND (s.T_STATUSKINDID, s.T_NUMVALUE) NOT IN ( " +
              "SELECT T_STATUSKINDID, T_NUMVALUE " + 
              "FROM doprsblck_dbt " + 
              "WHERE T_BLOCKID = " + BlockID_2 +
              ") " +
              "UNION " +
              "SELECT s.T_BLOCKID, s.T_STATUSKINDID, ss.T_CODE, ss.T_NAME, s.T_NUMVALUE " + 
              "FROM doprsblck_dbt s " + 
              "JOIN DOPRSTKND_DBT ss ON (s.T_STATUSKINDID = ss.T_STATUSKINDID) " +
              "WHERE s.T_BLOCKID = " + BlockID_2 +
              "AND (s.T_STATUSKINDID, s.T_NUMVALUE) NOT IN ( " +
              "SELECT T_STATUSKINDID, T_NUMVALUE " + 
              "FROM doprsblck_dbt " + 
              "WHERE T_BLOCKID = " + BlockID_1 +
              ") "; 

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPRSBLCK( rs.value(0), rs.value(2), rs.value(3), rs.value(4));
  end;
end;

macro CompareOPRSBLCKDef( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  "t_blockid     " NUMBER(10,0) NOT NULL ENABLE, 
  "t_statuskindid" NUMBER(10,0) NOT NULL ENABLE, 
  "t_numvalue    " NUMBER(5,0), 
*/
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = "SELECT s.T_BLOCKID, s.T_STATUSKINDID, ss.T_CODE, ss.T_NAME, s.T_NUMVALUE, " + BlockID_2 + " AS OTHERBLOCK " + 
              "FROM doprsblck_dbt s " + 
              "JOIN DOPRSTKND_DBT ss ON (s.T_STATUSKINDID = ss.T_STATUSKINDID) " +
              "WHERE s.T_BLOCKID = " + BlockID_1 +
              "AND s.T_DEFAULT = 'X' " +
              "AND (s.T_STATUSKINDID, s.T_NUMVALUE) IN ( " +
              "SELECT T_STATUSKINDID, T_NUMVALUE " + 
              "FROM doprsblck_dbt " + 
              "WHERE T_BLOCKID = " + BlockID_2 +
              "AND (T_DEFAULT <> 'X' OR T_DEFAULT IS NULL) " +
              ") " +
              "UNION " +
              "SELECT s.T_BLOCKID, s.T_STATUSKINDID, ss.T_CODE, ss.T_NAME, s.T_NUMVALUE, " + BlockID_1 + " AS OTHERBLOCK " + 
              "FROM doprsblck_dbt s " + 
              "JOIN DOPRSTKND_DBT ss ON (s.T_STATUSKINDID = ss.T_STATUSKINDID) " +
              "WHERE s.T_BLOCKID = " + BlockID_2 +
              "AND s.T_DEFAULT = 'X' " +
              "AND (s.T_STATUSKINDID, s.T_NUMVALUE) IN ( " +
              "SELECT T_STATUSKINDID, T_NUMVALUE " + 
              "FROM doprsblck_dbt " + 
              "WHERE T_BLOCKID = " + BlockID_1 +
              "AND (T_DEFAULT <> 'X' OR T_DEFAULT IS NULL) " +
              ") "; 

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPRSBLCKDef( rs.value(0), rs.value(2), rs.value(3), rs.value(4), rs.value(5));
  end;
end;

/*Сравнить данные таблицы "Настройка шага" OPROSTEP*/
macro CompareOPROSTEP( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  "T_BLOCKID                " NUMBER(10,0) NOT NULL ENABLE, 
  "T_NUMBER_STEP            " NUMBER(5,0) NOT NULL ENABLE, 
  "T_KIND_ACTION            " NUMBER(5,0), 
  "T_DAYOFFSET              " NUMBER(5,0), 
  "T_SCALE                  " NUMBER(5,0), 
  "T_DAYFLAG                " CHAR(1 BYTE), 
  "T_CALENDARID             " NUMBER(5,0), 
  "T_SYMBOL                 " CHAR(1 BYTE), 
  "T_PREVIOUS_STEP          " NUMBER(5,0), 
  "T_MODIFICATION           " NUMBER(5,0), 
  "T_CARRY_MACRO            " VARCHAR2(79 BYTE), 
  "T_PRINT_MACRO            " VARCHAR2(79 BYTE), 
  "T_POST_MACRO             " VARCHAR2(79 BYTE), 
  "T_NOTINUSE               " CHAR(1 BYTE), 
  "T_FIRSTSTEP              " CHAR(1 BYTE), 
  "T_NAME                   " VARCHAR2(64 BYTE), 
  "T_DATEKINDID             " NUMBER(10,0), 
  "T_REV                    " CHAR(1 BYTE), 
  "T_AUTOEXECUTESTEP        " CHAR(1 BYTE), 
  "T_ONLYHANDCARRY          " CHAR(1 BYTE), 
  "T_ISALLOWFOROPER         " NUMBER(10,0), 
  "T_OPERORGROUP            " CHAR(1 BYTE), 
  "T_RESTRICTEARLYEXECUTION " CHAR(1 BYTE), 
  "T_USERTYPES              " VARCHAR2(16 BYTE), 
  "T_INITDATEKINDID         " NUMBER(10,0), 
  "T_ASKFORDATE             " CHAR(1 BYTE), 
  "T_BACKOUT                " NUMBER(10,0) DEFAULT 0, 
  "T_ISBACKOUTGROUP         " CHAR(1 BYTE) DEFAULT CHR(0)
*/
/*
Поле                      Русское название (для сообщения об ошибке)
T_KIND_ACTION             Вид шага
T_DAYOFFSET               Смещение во времени
T_SCALE                   Масштаб смещения во времени
T_DAYFLAG                 Признак рабочих дней
T_CALENDARID              Ссылка на календарь
T_SYMBOL                  Символ шага
T_PREVIOUS_STEP           Предыдущий шаг
T_MODIFICATION            Признак редактирования проводок шага
T_CARRY_MACRO             Макрос формирования проводок
T_PRINT_MACRO             Макрос печати документов
T_POST_MACRO              Макрос пост обработки
T_NOTINUSE                Признак закрытого шага
T_FIRSTSTEP               Признак выполнения при инициализации
T_NAME                    Название шага
T_DATEKINDID              Ид вида даты
T_REV                     Признак отсчета смещения назад
T_AUTOEXECUTESTEP         Признак автоматического выполнения
T_ONLYHANDCARRY           Только ручная проводка счета
T_ISALLOWFOROPER          Операционист
T_OPERORGROUP             Признак группы
T_RESTRICTEARLYEXECUTION  Признак "Не выполнять раньше планируемой даты"
T_USERTYPES               Пользовательские типы
T_INITDATEKINDID          Инициализировать вид даты
T_ASKFORDATE              Запрашивать дату
T_BACKOUT                 Опер. или группы, которым разрешен откат шага
T_ISBACKOUTGROUP          Признак группы отката
T_MASSEXECUTEMODE         Режим массового выполнения
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 29; /*количество полей в одной таблице*/
  array FieldName;
  var strResCompare : string;

  FieldName( 0 ) = "Вид шага";
  FieldName( 1 ) = "Смещение во времени";
  FieldName( 2 ) = "Масштаб смещения во времени";
  FieldName( 3 ) = "Признак рабочих дней";
  FieldName( 4 ) = "Ссылка на календарь";
  FieldName( 5 ) = "Символ шага";
  FieldName( 6 ) = "Предыдущий шаг";
  FieldName( 7 ) = "Признак редактирования проводок шага";
  FieldName( 8 ) = "Макрос формирования проводок";
  FieldName( 9 ) = "Макрос печати документов";
  FieldName( 10 ) = "Макрос пост обработки";
  FieldName( 11 ) = "Признак закрытого шага";
  FieldName( 12 ) = "Признак выполнения при инициализации";
  FieldName( 13 ) = "Название шага";
  FieldName( 14 ) = "Ид вида даты";
  FieldName( 15 ) = "Признак отсчета смещения назад";
  FieldName( 16 ) = "Признак автоматического выполнения";
  FieldName( 17 ) = "Только ручная проводка счета";
  FieldName( 18 ) = "Операционист";
  FieldName( 19 ) = "Признак группы";
  FieldName( 20 ) = "Признак \"Не выполнять раньше планируемой даты\"";
  FieldName( 21 ) = "Пользовательские типы";
  FieldName( 22 ) = "Инициализировать вид даты";
  FieldName( 23 ) = "Запрашивать дату";
  FieldName( 24 ) = "Опер. или группы, которым разрешен откат шага";
  FieldName( 25 ) = "Признак группы отката";
  FieldName( 26 ) = "Режим массового выполнения";
  
  sqlString = "SELECT " +
              "  t1.T_BLOCKID               , " +
              "  t1.T_NUMBER_STEP           , " +
              "  t1.T_KIND_ACTION           , " +
              "  t1.T_DAYOFFSET             , " +
              "  t1.T_SCALE                 , " +
              "  t1.T_DAYFLAG               , " +
              "  t1.T_CALENDARID            , " +
              "  t1.T_SYMBOL                , " +
              "  t1.T_PREVIOUS_STEP         , " +
              "  t1.T_MODIFICATION          , " +
              "  t1.T_CARRY_MACRO           , " +
              "  t1.T_PRINT_MACRO           , " +
              "  t1.T_POST_MACRO            , " +
              "  t1.T_NOTINUSE              , " +
              "  t1.T_FIRSTSTEP             , " +
              "  t1.T_NAME                  , " +
              "  t1.T_DATEKINDID            , " +
              "  t1.T_REV                   , " +
              "  t1.T_AUTOEXECUTESTEP       , " +
              "  t1.T_ONLYHANDCARRY         , " +
              "  t1.T_ISALLOWFOROPER        , " +
              "  t1.T_OPERORGROUP           , " +
              "  t1.T_RESTRICTEARLYEXECUTION, " +
              "  t1.T_USERTYPES             , " +
              "  t1.T_INITDATEKINDID        , " +
              "  t1.T_ASKFORDATE            , " +
              "  t1.T_BACKOUT               , " +
              "  t1.T_ISBACKOUTGROUP        , " +
              "  t1.T_MASSEXECUTEMODE       , " +

              "  t2.T_BLOCKID               , " +
              "  t2.T_NUMBER_STEP           , " +
              "  t2.T_KIND_ACTION           , " +
              "  t2.T_DAYOFFSET             , " +
              "  t2.T_SCALE                 , " +
              "  t2.T_DAYFLAG               , " +
              "  t2.T_CALENDARID            , " +
              "  t2.T_SYMBOL                , " +
              "  t2.T_PREVIOUS_STEP         , " +
              "  t2.T_MODIFICATION          , " +
              "  t2.T_CARRY_MACRO           , " +
              "  t2.T_PRINT_MACRO           , " +
              "  t2.T_POST_MACRO            , " +
              "  t2.T_NOTINUSE              , " +
              "  t2.T_FIRSTSTEP             , " +
              "  t2.T_NAME                  , " +
              "  t2.T_DATEKINDID            , " +
              "  t2.T_REV                   , " +
              "  t2.T_AUTOEXECUTESTEP       , " +
              "  t2.T_ONLYHANDCARRY         , " +
              "  t2.T_ISALLOWFOROPER        , " +
              "  t2.T_OPERORGROUP           , " +
              "  t2.T_RESTRICTEARLYEXECUTION, " +
              "  t2.T_USERTYPES             , " +
              "  t2.T_INITDATEKINDID        , " +
              "  t2.T_ASKFORDATE            , " +
              "  t2.T_BACKOUT               , " +
              "  t2.T_ISBACKOUTGROUP        , " +
              "  t2.T_MASSEXECUTEMODE         " +
              
              "FROM doprostep_dbt t1 JOIN doprostep_dbt t2 " +
              "ON ( t2.t_BlockID = " + BlockID_2 + " AND t1.T_NUMBER_STEP = t2.T_NUMBER_STEP ) " +
              "WHERE t1.t_BlockID = " + BlockID_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFieldsExt( rs, 2, numFields, 27, FieldName, @strResCompare ))
      PrintDiffersOPROSTEP( rs.value(0), rs.value(numFields), rs.value(1), strResCompare );
    end;
  end;
end;

macro CompareOPROSTEPNotExist( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = "SELECT s.T_BLOCKID, s.T_NUMBER_STEP " + 
              "FROM DOPROSTEP_DBT s " +
              "WHERE s.T_BLOCKID = " + BlockID_1 +
              "AND s.T_NUMBER_STEP NOT IN ( " +
              "SELECT T_NUMBER_STEP " +
              "FROM DOPROSTEP_DBT " +
              "WHERE T_BLOCKID = " + BlockID_2 +
              ") " +
              "UNION " +
              "SELECT s.T_BLOCKID, s.T_NUMBER_STEP " + 
              "FROM DOPROSTEP_DBT s " +
              "WHERE s.T_BLOCKID = " + BlockID_2 +
              "AND s.T_NUMBER_STEP NOT IN ( " +
              "SELECT T_NUMBER_STEP " +
              "FROM DOPROSTEP_DBT " +
              "WHERE T_BLOCKID = " + BlockID_1 +
              ")";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPROSTEP( rs.value(0), rs.value(1) )
  end;
end;

/*Сравнить данные таблицы "Фазы операционного дня для шага" OPROPHASE*/
macro CompareOPROPHASE( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID      NUMBER(10)                     NOT NULL,
  T_NUMBER_STEP  NUMBER(5)                      NOT NULL,
  T_DOCKIND      NUMBER(5)                      NOT NULL,
  T_MINPHASE     NUMBER(5),
  T_MAXPHASE     NUMBER(5)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 4; /*количество полей в одной таблице*/

  sqlString = "SELECT " +
              "t1.T_BLOCKID    , " +
              "t1.T_NUMBER_STEP, " +
              "t1.T_DOCKIND    , " +
              "t1.T_MAXPHASE   , " +

              "t2.T_BLOCKID    , " +
              "t2.T_NUMBER_STEP, " +
              "t2.T_DOCKIND    , " +
              "t2.T_MAXPHASE     " +  

              "FROM doprophase_dbt t1 JOIN doprophase_dbt t2 " +
              "ON ( t2.t_BlockID = " + BlockID_2 + " AND t1.T_NUMBER_STEP = t2.T_NUMBER_STEP  AND t1.T_DOCKIND = t2.T_DOCKIND ) " +
              "WHERE t1.t_BlockID = " + BlockID_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFields( rs, 3, numFields ))
      PrintDiffersOPROPHASE( BlockID_1, BlockID_2, rs.value(2), rs.value(1) );
    end;
  end;
end;

macro CompareOPROPHASENotExist( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID      NUMBER(10)                     NOT NULL,
  T_NUMBER_STEP  NUMBER(5)                      NOT NULL,
  T_DOCKIND      NUMBER(5)                      NOT NULL,
  T_MINPHASE     NUMBER(5),
  T_MAXPHASE     NUMBER(5)
*/
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, s.T_DOCKIND, " + BlockID_2 + " as OTHERBLOCK " + 
              "FROM DOPROPHASE_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_1 +
              "AND (s.T_NUMBER_STEP, s.T_DOCKIND) NOT IN ( " +
              "SELECT T_NUMBER_STEP, s.T_DOCKIND " + 
              "FROM DOPROPHASE_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_2 +
              ") " +
              "UNION " +
              "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, T_DOCKIND, " + BlockID_1 + " as OTHERBLOCK " + 
              "FROM DOPROPHASE_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_2 +
              "AND (s.T_NUMBER_STEP, s.T_DOCKIND) NOT IN ( " +
              "SELECT T_NUMBER_STEP, T_DOCKIND " + 
              "FROM DOPROPHASE_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_1 +
              ") "; 

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPROPHASE( rs.value(0), rs.value(2), rs.value(1), rs.value(3) );
  end;
end;

/*Сравнить данные таблицы "Настройка строчек для шага операции" OPRLINE*/
macro CompareOPRLINE( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID      NUMBER(10)                     NOT NULL,
  T_NUMBER_STEP  NUMBER(5)                      NOT NULL,
  T_CODE         VARCHAR2(15 BYTE)              NOT NULL,
  T_DOCKIND      NUMBER(5),
  T_SORT         NUMBER(5),
*/
/*
Поле      Русское название (для сообщения об ошибке)
T_DOCKIND Вид формируемого документа
T_SORT    Порядок проводок
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 5; /*количество полей в одной таблице*/
  array FieldName;
  var strResCompare : string;

  FieldName( 0 ) = "Вид формируемого документа";
  FieldName( 1 ) = "Порядок проводок";

  sqlString = "SELECT " +
              "t1.T_BLOCKID    , " +    
              "t1.T_NUMBER_STEP, " +
              "t1.T_CODE       , " +
              "t1.T_DOCKIND    , " +  
              "t1.T_SORT       , " +
              
              "t2.T_BLOCKID    , " +    
              "t2.T_NUMBER_STEP, " +
              "t2.T_CODE       , " +
              "t2.T_DOCKIND    , " +  
              "t2.T_SORT         " +
              
              "FROM doprline_dbt t1 JOIN doprline_dbt t2 " +
              "ON ( t2.t_BlockID = " + BlockID_2 + " AND t1.T_NUMBER_STEP = t2.T_NUMBER_STEP AND t1.T_CODE = t2.T_CODE ) " +
              "WHERE t1.t_BlockID = " + BlockID_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFieldsExt( rs, 3, numFields, 2, FieldName, @strResCompare ))
      PrintDiffersOPRLINE( rs.value(0), rs.value(numFields), rs.value(2), rs.value(1), strResCompare );
    end;
  end;
end;

/*Сравнить данные таблицы "Настройка строчек для шага операции" OPRLINE*/
macro CompareOPRLINENotExist( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID      NUMBER(10)                     NOT NULL,
  T_NUMBER_STEP  NUMBER(5)                      NOT NULL,
  T_CODE         VARCHAR2(15 BYTE)              NOT NULL,
  T_DOCKIND      NUMBER(5),
  T_SORT         NUMBER(5),
  T_RESERVE      VARCHAR2(197 BYTE)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 6; /*количество полей в одной таблице*/

  sqlString = "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, T_CODE, " + BlockID_2 + " as OTHERBLOCK " + 
              "FROM DOPRLINE_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_1 +
              "AND (s.T_NUMBER_STEP, s.T_CODE) NOT IN ( " +
              "SELECT T_NUMBER_STEP, T_CODE " + 
              "FROM DOPRLINE_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_2 +
              ") " +
              "UNION " +
              "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, T_CODE, " + BlockID_1 + " as OTHERBLOCK " + 
              "FROM DOPRLINE_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_2 +
              "AND (s.T_NUMBER_STEP, s.T_CODE) NOT IN ( " +
              "SELECT T_NUMBER_STEP, T_CODE " + 
              "FROM DOPRLINE_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_1 +
              ") ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPRLINE( rs.value(0), rs.value(2), rs.value(1), rs.value(3) );
  end;
end;

/*Сравнить данные таблицы "Выражение строчки для шага операции" OPREXPR*/
macro CompareOPREXPR( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID       NUMBER(10)                    NOT NULL,
  T_NUMBER_STEP   NUMBER(5)                     NOT NULL,
  T_LINECODE      VARCHAR2(15 BYTE)             NOT NULL,
  T_FIELDNUMBER   NUMBER(5)                     NOT NULL,
  T_EXPRESSION    VARCHAR2(254 BYTE),
  T_MODIFICATION  NUMBER(5),
  T_RESERVE       VARCHAR2(197 BYTE)
*/
/*
Поле            Русское название (для сообщения об ошибке)
T_EXPRESSION    Выражение
T_MODIFICATION  Признак редактирования поля
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var cmd : RsdCommand;
  var numFields = 6; /*количество полей в одной таблице*/
  array FieldName;
  var strResCompare : string;

  FieldName( 0 ) = "Выражение";
  FieldName( 1 ) = "Признак редактирования поля";

  sqlString = "SELECT " +
              "t1.T_BLOCKID     , " +     
              "t1.T_NUMBER_STEP , " +    
              "t1.T_LINECODE    , " +    
              "t1.T_FIELDNUMBER , " +    
              "t1.T_EXPRESSION  , " +    
              "t1.T_MODIFICATION, " +    
              
              "t2.T_BLOCKID     , " +     
              "t2.T_NUMBER_STEP , " +    
              "t2.T_LINECODE    , " +    
              "t2.T_FIELDNUMBER , " +    
              "t2.T_EXPRESSION  , " +    
              "t2.T_MODIFICATION  " +    
              
              "FROM doprexpr_dbt t1 JOIN doprexpr_dbt t2 " +
              "ON ( t2.t_BlockID = " + BlockID_2 + " AND t1.T_NUMBER_STEP = t2.T_NUMBER_STEP AND t1.T_LINECODE = t2.T_LINECODE AND t1.T_FIELDNUMBER = t2.T_FIELDNUMBER ) " +
              "WHERE t1.t_BlockID = " + BlockID_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFieldsExt( rs, 4, numFields, 2, FieldName, @strResCompare ))
      PrintDiffersOPREXPR( rs.value(0), rs.value(numFields), rs.value(2), rs.value(3), rs.value(1), strResCompare );
    end;
  end;
end;

/*Сравнить данные таблицы "Выражение строчки для шага операции" OPREXPR*/
macro CompareOPREXPRNotExist( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID       NUMBER(10)                    NOT NULL,
  T_NUMBER_STEP   NUMBER(5)                     NOT NULL,
  T_LINECODE      VARCHAR2(15 BYTE)             NOT NULL,
  T_FIELDNUMBER   NUMBER(5)                     NOT NULL,
  T_EXPRESSION    VARCHAR2(254 BYTE),
  T_MODIFICATION  NUMBER(5),
  T_RESERVE       VARCHAR2(197 BYTE)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var cmd : RsdCommand;

  sqlString = "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, T_LINECODE, T_FIELDNUMBER, " + BlockID_2 + " as OTHERBLOCK " + 
              "FROM DOPREXPR_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_1 +
              "AND (s.T_NUMBER_STEP, s.T_LINECODE, s.T_FIELDNUMBER) NOT IN ( " +
              "SELECT T_NUMBER_STEP, T_LINECODE, T_FIELDNUMBER " + 
              "FROM DOPREXPR_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_2 +
              ") " +
              "UNION " +
              "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, T_LINECODE, T_FIELDNUMBER, " + BlockID_1 + " as OTHERBLOCK " +
              "FROM DOPREXPR_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_2 +
              "AND (s.T_NUMBER_STEP, s.T_LINECODE, s.T_FIELDNUMBER) NOT IN ( " +
              "SELECT T_NUMBER_STEP, T_LINECODE, T_FIELDNUMBER " + 
              "FROM DOPREXPR_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_1 +
              ") "; 

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPREXPR( rs.value(0), rs.value(2), rs.value(3), rs.value(1), rs.value(4) );
  end;
end;

/*Сравнить данные таблицы "Настройка комиссий по виду операции" OPRKSFCM*/
macro CompareOPRKSFCM( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID       NUMBER(10)                    NOT NULL,
  T_NUMBER_STEP   NUMBER(5)                     NOT NULL,
  T_ACTION        NUMBER(5)                     NOT NULL,
  T_FEETYPE       NUMBER(5)                     NOT NULL,
  T_COMMNUMBER    NUMBER(5)                     NOT NULL,
  T_NUMBER        NUMBER(5),
  T_AUTOFORMDOCS  CHAR(1 BYTE),
  T_RESERVE       VARCHAR2(199 BYTE)
*/
/*
Поле            Русское название (для сообщения об ошибке)
T_NUMBER        Номер комиссии по шагу для сортировки
T_AUTOFORMDOCS  Автоматически формировать документы
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var cmd : RsdCommand;
  var numFields = 7; /*количество полей в одной таблице*/
  var Action = "";
  array FieldName;
  var strResCompare : string;

  FieldName( 0 ) = "Номер комиссии по шагу для сортировки";
  FieldName( 1 ) = "Автоматически формировать документы";

  sqlString = "SELECT " +
              "t1.T_BLOCKID     , " +
              "t1.T_NUMBER_STEP , " +
              "t1.T_ACTION      , " +
              "t1.T_FEETYPE     , " +
              "t1.T_COMMNUMBER  , " +
              "t1.T_NUMBER      , " +
              "t1.T_AUTOFORMDOCS, " +
              
              "t2.T_BLOCKID     , " +
              "t2.T_NUMBER_STEP , " +
              "t2.T_ACTION      , " +
              "t2.T_FEETYPE     , " +
              "t2.T_COMMNUMBER  , " +
              "t2.T_NUMBER      , " +
              "t2.T_AUTOFORMDOCS  " +
              
              "FROM doprksfcm_dbt t1 JOIN doprksfcm_dbt t2 " +
              "ON ( t2.t_BlockID = " + BlockID_2 + " AND t1.T_NUMBER_STEP = t2.T_NUMBER_STEP AND t1.T_ACTION = t2.T_ACTION AND t1.T_FEETYPE = t2.T_FEETYPE AND t1.T_COMMNUMBER = t2.T_COMMNUMBER ) " +
              "WHERE t1.t_BlockID = " + BlockID_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFieldsExt( rs, 5, numFields, 2, FieldName, @strResCompare ))
      if( rs.value(2) == 1 )
        Action = "расчета";
      else
        Action = "оплаты";
      end;
      PrintDiffersOPRKSFCM( rs.value(0), rs.value(numFields), Action, rs.value(4), rs.value(1), strResCompare );
    end;
  end;
end;

/*Сравнить данные таблицы "Настройка комиссий по виду операции" OPRKSFCM*/
macro CompareOPRKSFCMNotExist( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID       NUMBER(10)                    NOT NULL,
  T_NUMBER_STEP   NUMBER(5)                     NOT NULL,
  T_ACTION        NUMBER(5)                     NOT NULL,
  T_FEETYPE       NUMBER(5)                     NOT NULL,
  T_COMMNUMBER    NUMBER(5)                     NOT NULL,
  T_NUMBER        NUMBER(5),
  T_AUTOFORMDOCS  CHAR(1 BYTE),
  T_RESERVE       VARCHAR2(199 BYTE)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var cmd : RsdCommand;
  var Action = "";

  sqlString = "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, s.T_ACTION, s.T_FEETYPE, s.T_COMMNUMBER, " + BlockID_2 + " as OTHERBLOCK " + 
              "FROM DOPRKSFCM_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_1 +
              "AND (s.T_NUMBER_STEP, s.T_ACTION, s.T_FEETYPE, s.T_COMMNUMBER) NOT IN ( " +
              "SELECT T_NUMBER_STEP, T_ACTION, T_FEETYPE, T_COMMNUMBER " + 
              "FROM DOPRKSFCM_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_2 +
              ") " +
              "UNION " +
              "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, s.T_ACTION, s.T_FEETYPE, s.T_COMMNUMBER, " + BlockID_1 + " as OTHERBLOCK " + 
              "FROM DOPRKSFCM_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_2 +
              "AND (s.T_NUMBER_STEP, s.T_ACTION, s.T_FEETYPE, s.T_COMMNUMBER) NOT IN ( " +
              "SELECT T_NUMBER_STEP, T_ACTION, T_FEETYPE, T_COMMNUMBER " +
              "FROM DOPRKSFCM_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_1 +
              ") ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( rs.value(2) == 1 )
      Action = "расчета";
    else
      Action = "оплаты";
    end;
    PrintNotExistOPRKSFCM( rs.value(0), Action, rs.value(4), rs.value(1), rs.value(5) );
  end;
end;

/*Сравнить данные таблицы "Настройка показа шагов и документов" OPRSHOW*/
macro CompareOPRSHOW( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID         NUMBER(10)                  NOT NULL,
  T_NUMBER_STEP     NUMBER(5)                   NOT NULL,
  T_OPER            NUMBER(5)                   NOT NULL,
  T_NOSHOWSTEPDOCS  CHAR(1 BYTE),
  T_RESERVE         VARCHAR2(8 BYTE)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 4; /*количество полей в одной таблице*/

  sqlString = "SELECT " +
              "t1.T_BLOCKID       , " +
              "t1.T_NUMBER_STEP   , " +
              "t1.T_OPER          , " +
              "t1.T_NOSHOWSTEPDOCS, " +
              
              "t2.T_BLOCKID       , " +
              "t2.T_NUMBER_STEP   , " +
              "t2.T_OPER          , " +
              "t2.T_NOSHOWSTEPDOCS  " +
              
              "FROM doprshow_dbt t1 JOIN doprshow_dbt t2 " +
              "ON ( t2.t_BlockID = " + BlockID_2 + " AND t1.T_NUMBER_STEP = t2.T_NUMBER_STEP AND t1.T_OPER = t2.T_OPER ) " +
              "WHERE t1.t_BlockID = " + BlockID_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFields( rs, 3, numFields ))
      PrintDiffersOPRSHOW( rs.value(0), rs.value(numFields), rs.value(1), rs.value(2) );
    end;
  end;
end;

/*Сравнить данные таблицы "Настройка показа шагов и документов" OPRSHOW*/
macro CompareOPRSHOWNotExist( BlockID_1 : integer, Name_1 : string, BlockID_2 : integer, Name_2 : string )
/*
  T_BLOCKID         NUMBER(10)                  NOT NULL,
  T_NUMBER_STEP     NUMBER(5)                   NOT NULL,
  T_OPER            NUMBER(5)                   NOT NULL,
  T_NOSHOWSTEPDOCS  CHAR(1 BYTE),
  T_RESERVE         VARCHAR2(8 BYTE)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var cmd : RsdCommand;

  sqlString = "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, T_OPER, " + BlockID_2 + " as OTHERBLOCK " + 
              "FROM DOPRSHOW_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_1 +
              "AND (s.T_NUMBER_STEP, s.T_OPER) NOT IN ( " +
              "SELECT T_NUMBER_STEP, T_OPER " + 
              "FROM DOPRSHOW_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_2 +
              ") " +
              "UNION " +
              "SELECT s.T_BLOCKID, s.T_NUMBER_STEP, T_OPER, " + BlockID_1 + " as OTHERBLOCK " + 
              "FROM DOPRSHOW_DBT s " + 
              "WHERE s.T_BLOCKID = " + BlockID_2 +
              "AND (s.T_NUMBER_STEP, s.T_OPER) NOT IN ( " +
              "SELECT T_NUMBER_STEP, T_OPER " + 
              "FROM DOPRSHOW_DBT " + 
              "WHERE T_BLOCKID = " + BlockID_1 +
              ") "; 

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPRSHOW( rs.value(0), rs.value(1), rs.value(2), rs.value(3) );
  end;
end;

/*1.Сравнить данные таблицы "Блок шагов" OPRBLOCK */
macro CompareOPRBLOCK( BlockID_1 : integer, BlockID_2 : integer )
/*
Поле      Русское название (для сообщения об ошибке)
T_NAME    Наименование
T_DOCKIND Вид документа
*/

  var savecountDiffers, deltacountDiffers : integer;
  var Version1, Version2 : string;
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 6; /*количество полей в одной таблице*/
  array FieldName;
  var strResCompare : string;

  savecountDiffers = countDiffers;

  FieldName( 0 ) = "Наименование";
  FieldName( 1 ) = "Вид документа";

  sqlString = "SELECT " +
              "  t1.t_BlockID, t1.t_Name, t1.t_Dockind, t1.t_Parent, t1.t_Upgrade, t1.t_Version, " +
              "  t2.t_BlockID, t2.t_Name, t2.t_Dockind, t2.t_Parent, t2.t_Upgrade, t2.t_Version  " +
              "FROM doprblock_dbt t1 FULL OUTER JOIN doprblock_dbt t2 " +
              "ON ( t2.t_BlockID = " + BlockID_2 + " ) " +
              "WHERE t1.t_BlockID = " + BlockID_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( rs.value(5) == NULLVAL ) Version1 = ""; else Version1 = rs.value(5); end;
    if( rs.value(5+numFields) == NULLVAL ) Version2 = ""; else Version2 = rs.value(5+numFields); end;

    PrintCompareType( 0, BlockID_1, Version1, rs.value(1), 
                         BlockID_2, Version2, rs.value(1+numFields) );

    if( CompareFieldsExt( rs, 1, numFields, 2, FieldName, @strResCompare ))
      PrintDiffersOPRBLOCK( rs.value(0), rs.value(numFields), strResCompare );
    end;

    CompareOPRSBLCK(  BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );
    CompareOPRSBLCKDef(  BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );
    CompareOPROSTEP(  BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );
    CompareOPROSTEPNotExist(  BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );
    CompareOPROPHASE( BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );
    CompareOPROPHASENotExist( BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );
    CompareOPRKSFCM(  BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );
    CompareOPRKSFCMNotExist(  BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );
    CompareOPRSHOW(   BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );
    CompareOPRSHOWNotExist(   BlockID_1, rs.value(1), BlockID_2, rs.value(1+numFields) );

  end;

  deltacountDiffers = countDiffers - savecountDiffers;
  countDiffers = deltacountDiffers;

  PrintFooter();

  countDiffers = saveCountDiffers + deltacountDiffers;
end;

/*конец сравнения блоков*/


/*начало сравнения видов операций*/
/*2.Сравнить данные таблицы "Проверка документа в начале операции" OPRCHDOC*/
macro CompareOPRCHDOC( KindOperation_1 : integer, KindOperation_2 : integer )
/*
  T_KIND_OPERATION  NUMBER(5)                   NOT NULL,
  T_CHECKMASK       RAW(500),
  T_RESERVE         VARCHAR2(99 BYTE)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 2; /*количество полей в одной таблице*/

  sqlString = "SELECT " +
              "t1.T_KIND_OPERATION," +
              "t1.T_CHECKMASK     ," +
              
              "t2.T_KIND_OPERATION," +
              "t2.T_CHECKMASK      " +
              
              "FROM doprchdoc_dbt t1 JOIN doprchdoc_dbt t2 " +
              "ON ( t2.T_KIND_OPERATION = " + KindOperation_2 + " ) " +
              "WHERE t1.T_KIND_OPERATION = " + KindOperation_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFields( rs, 1, numFields ))
      PrintDiffersOPRCHDOC( rs.value(0), rs.value(numFields) );
    end;
  end;
end;

/*2.Сравнить данные таблицы "Проверка документа в начале операции" OPRCHDOC*/
macro CompareOPRCHDOCNotExist( KindOperation_1 : integer, KindOperation_2 : integer )
/*
  T_KIND_OPERATION  NUMBER(5)                   NOT NULL,
  T_CHECKMASK       RAW(500),
  T_RESERVE         VARCHAR2(99 BYTE)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 2; /*количество полей в одной таблице*/

  sqlString = "SELECT s.T_KIND_OPERATION " + 
              "FROM DOPRCHDOC_DBT s " + 
              "WHERE s.T_KIND_OPERATION = " + KindOperation_1 +
              "AND s.T_KIND_OPERATION NOT IN ( " +
              "SELECT T_KIND_OPERATION " + 
              "FROM DOPRCHDOC_DBT " + 
              "WHERE T_KIND_OPERATION = " + KindOperation_2 +
              ") " +
              "UNION " +
              "SELECT s.T_KIND_OPERATION " + 
              "FROM DOPRCHDOC_DBT s " + 
              "WHERE s.T_KIND_OPERATION = " + KindOperation_2 +
              "AND s.T_KIND_OPERATION NOT IN ( " +
              "SELECT T_KIND_OPERATION " + 
              "FROM DOPRCHDOC_DBT " + 
              "WHERE T_KIND_OPERATION = " + KindOperation_1 +
              ") "; 

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPRCHDOC( rs.value(0) );
  end;
end;

/*3.Сравнить данные таблицы "Статус при создании операции" OPRINIST*/
macro CompareOPRINIST( KindOperation_1 : integer, Name_1 : string, KindOperation_2 : integer, Name_2 : string )
/*
  T_KIND_OPERATION  NUMBER(5)                   NOT NULL,
  T_STATUSKINDID    NUMBER(10)                  NOT NULL,
  T_NUMVALUE        NUMBER(5)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var cmd : RsdCommand;
  var numFields = 3; /*количество полей в одной таблице*/

  sqlString = "SELECT " +
              "t1.T_KIND_OPERATION," +
              "t1.T_STATUSKINDID  ," +
              "t1.T_NUMVALUE      ," +
              
              "t2.T_KIND_OPERATION," +
              "t2.T_STATUSKINDID  ," +
              "t2.T_NUMVALUE       " +
              
              "FROM doprinist_dbt t1 JOIN doprinist_dbt t2 " +
              "ON ( t2.T_KIND_OPERATION = " + KindOperation_2 + " AND t1.t_StatusKindID = t2.t_StatusKindID ) " +
              "WHERE t1.T_KIND_OPERATION = " + KindOperation_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFields( rs, 2, numFields ))
      PrintDiffersOPRINIST( rs.value(0), rs.value(numFields), rs.value(1) );
    end;
  end;
end;

/*3.Сравнить данные таблицы "Статус при создании операции" OPRINIST*/
macro CompareOPRINISTNotExist( KindOperation_1 : integer, Name_1 : string, KindOperation_2 : integer, Name_2 : string )
/*
  T_KIND_OPERATION  NUMBER(5)                   NOT NULL,
  T_STATUSKINDID    NUMBER(10)                  NOT NULL,
  T_NUMVALUE        NUMBER(5)
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var cmd : RsdCommand;
  var numFields = 3; /*количество полей в одной таблице*/

  sqlString = "SELECT s.T_KIND_OPERATION, s.T_STATUSKINDID, " + KindOperation_2 + " as OTHEROPER " + 
              "FROM DOPRINIST_DBT s " + 
              "WHERE s.T_KIND_OPERATION = " + KindOperation_1 +
              "AND s.T_STATUSKINDID NOT IN ( " +
              "SELECT T_STATUSKINDID " + 
              "FROM DOPRINIST_DBT " +
              "WHERE T_KIND_OPERATION = " + KindOperation_2 +
              ") " +
              "UNION " +
              "SELECT s.T_KIND_OPERATION, s.T_STATUSKINDID, " + KindOperation_1 + " as OTHEROPER " + 
              "FROM DOPRINIST_DBT s " + 
              "WHERE s.T_KIND_OPERATION = " + KindOperation_2 +
              "AND s.T_STATUSKINDID NOT IN ( " +
              "SELECT T_STATUSKINDID " + 
              "FROM DOPRINIST_DBT " +
              "WHERE T_KIND_OPERATION = " + KindOperation_1 +
              ") "; 

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPRINIST( rs.value(0), rs.value(2) );
  end;
end;

macro BlocksToOperations( KindOperation_1 : integer, KindOperation_2 : integer )
  var sqlString : string;

  sqlString = "SELECT DISTINCT x.BlockID_1, x.BlockID_2 FROM (SELECT b1.T_BLOCKID as BlockID_1, b2.T_BLOCKID as BlockID_2 " +
              "FROM DOPROBLCK_DBT ob1 " + 
              "JOIN DOPROBLCK_DBT ob2 ON (ob1.T_KIND_OPERATION = " + KindOperation_1 + " AND ob2.T_KIND_OPERATION = " + KindOperation_2 + " ) " +
              "JOIN DOPRBLOCK_DBT b1 ON (ob1.T_BLOCKID = b1.T_BLOCKID) " +
              "JOIN DOPRBLOCK_DBT b2 ON (ob2.T_BLOCKID = b2.T_BLOCKID) " +
              "WHERE b1.T_NAME = b2.T_NAME " +
              "AND b1.T_DOCKIND = b2.T_DOCKIND ) x"; 
  return sqlString;
end;

macro ConditionsToOperations( KindOperation_1 : integer, KindOperation_2 : integer )
  var sqlString : string;

  sqlString = "SELECT DISTINCT y.OperBlockID_1, y.OperBlockID_2 FROM (SELECT o1.T_OPERBLOCKID as OperBlockID_1, o2.T_OPERBLOCKID as OperBlockID_2 " + 
              "FROM DOPROBLCK_DBT o1 " +
              "JOIN DOPROBLCK_DBT o2 ON (o1.T_KIND_OPERATION = " + KindOperation_1 +
              "AND o2.T_KIND_OPERATION = " + KindOperation_2 +
              "AND (o1.T_BLOCKID, o2.T_BLOCKID) IN ( " + BlocksToOperations( KindOperation_1, KindOperation_2 ) + " ) " +
              "AND o1.T_SORT = o2.T_SORT)) y ";
  return sqlString;
end;

macro ConditionsToBlocks( KindOperation_1 : integer, KindOperation_2 : integer, BlockID_1 : integer, BlockID_2 : integer )
  var sqlString : string;

  sqlString = "SELECT DISTINCT y.OperBlockID_1, y.OperBlockID_2 FROM (SELECT o1.T_OPERBLOCKID as OperBlockID_1, o2.T_OPERBLOCKID as OperBlockID_2 " + 
              "FROM DOPROBLCK_DBT o1 " +
              "JOIN DOPROBLCK_DBT o2 ON (o1.T_KIND_OPERATION = " + KindOperation_1 +
              " AND o2.T_KIND_OPERATION = " + KindOperation_2 +
              " AND o1.T_BLOCKID = " + BlockID_1 +
              " AND o2.T_BLOCKID = " + BlockID_2 +
              " AND o1.T_SORT = o2.T_SORT)) y ";
  return sqlString;
end;

/*Сравнить данные таблицы "Настройка блока для вида операции" OPROBLCK*/
macro CompareOPROBLCK( KindOperation_1 : integer, Name_1 : string, KindOperation_2 : integer, Name_2 : string )
/*
  T_OPERBLOCKID          NUMBER(10)             NOT NULL,
  T_KIND_OPERATION       NUMBER(5)              NOT NULL,
  T_BLOCKID              NUMBER(10)             NOT NULL,
  T_SORT                 NUMBER(5)              NOT NULL,
  T_NOTINUSE             CHAR(1 BYTE),
  T_NOINSERT             CHAR(1 BYTE),
  T_NOREPLACE            CHAR(1 BYTE),
  T_ISMANUAL             CHAR(1 BYTE),
  T_SYMBOLSFORINSERTION  VARCHAR2(16 BYTE),
  T_SYMBOL               CHAR(1 BYTE)
*/
/*
Поле                  Русское название (для сообщения об ошибке)
T_NOTINUSE            Признак неиспользуемости
T_NOINSERT            Запрет на вставку раздвижкой
T_NOREPLACE           Запрет на вставку заменой
T_NOCLOSEINSERT       Запрет на вставку в закрытые операции
T_ISMANUAL            Ручной запуск
T_SYMBOLSFORINSERTION Допустимые символы шагов для вставки
T_SYMBOL              Символ цепочки
*/
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 11; /*количество полей в одной таблице*/
  array FieldName;
  var strResCompare : string;

  FieldName( 0 ) = "Признак неиспользуемости";
  FieldName( 1 ) = "Запрет на вставку раздвижкой";
  FieldName( 2 ) = "Запрет на вставку заменой";
  FieldName( 3 ) = "Запрет на вставку в закрытые операции";
  FieldName( 4 ) = "Ручной запуск";
  FieldName( 5 ) = "Допустимые символы шагов для вставки";
  FieldName( 6 ) = "Символ цепочки";

  sqlString = "SELECT " +
              "t1.T_OPERBLOCKID        ," +
              "t1.T_KIND_OPERATION     ," +
              "t1.T_BLOCKID            ," +
              "t1.T_SORT               ," +    
              "t1.T_NOTINUSE           ," +
              "t1.T_NOINSERT           ," +
              "t1.T_NOREPLACE          ," +
              "t1.T_NOCLOSEINSERT      ," +
              "t1.T_ISMANUAL           ," +
              "t1.T_SYMBOLSFORINSERTION," +
              "t1.T_SYMBOL             ," +
              
              "t2.T_OPERBLOCKID        ," +
              "t2.T_KIND_OPERATION     ," +
              "t2.T_BLOCKID            ," +
              "t2.T_SORT               ," +    
              "t2.T_NOTINUSE           ," +
              "t2.T_NOINSERT           ," +
              "t2.T_NOREPLACE          ," +
              "t2.T_NOCLOSEINSERT      ," +
              "t2.T_ISMANUAL           ," +
              "t2.T_SYMBOLSFORINSERTION," +
              "t2.T_SYMBOL              " +
              
              "FROM doproblck_dbt t1 JOIN doproblck_dbt t2 " +
              "ON ( t1.T_OPERBLOCKID, t2.T_OPERBLOCKID ) IN ( " + ConditionsToOperations( KindOperation_1, KindOperation_2 ) + " )";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFieldsExt( rs, 4, numFields, 7, FieldName, @strResCompare ))
      PrintDiffersOPROBLCK( rs.value(1), rs.value(1+numFields), rs.value(2), rs.value(2+numFields), rs.value(3), strResCompare );
    end;
  end;
end;

/*Сравнить данные таблицы "Настройка блока для вида операции" OPROBLCK*/
macro CompareSingleOPROBLCKNotExist( KindOperation_1 : integer, KindOperation_2 : integer, BlockID_1 : integer, BlockID_2 : integer, OperBlockID_1 : integer, OperBlockID_2 : integer )
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = "SELECT s.T_KIND_OPERATION, s. T_OPERBLOCKID, s.T_SORT, s.T_BLOCKID, " + KindOperation_2 + " as OTHEROPER " +
              "FROM DOPROBLCK_DBT s " + 
              "WHERE s.T_KIND_OPERATION = " + KindOperation_1 +
              "AND s.T_BLOCKID = " + BlockID_1 +
              "AND s.T_OPERBLOCKID = " + OperBlockID_1 +
              "AND s.T_SORT NOT IN ( " +
              "SELECT T_SORT " + 
              "FROM DOPROBLCK_DBT " +
              "WHERE T_KIND_OPERATION = " + KindOperation_2 +
              "AND T_BLOCKID = " + BlockID_2 +
              "AND T_OPERBLOCKID = " + OperBlockID_2 +
              ") " +
              "UNION " +
              "SELECT s.T_KIND_OPERATION, s. T_OPERBLOCKID, s.T_SORT, s.T_BLOCKID, " + KindOperation_1 + " as OTHEROPER " + 
              "FROM DOPROBLCK_DBT s " + 
              "WHERE s.T_KIND_OPERATION = " + KindOperation_2 +
              "AND s.T_BLOCKID = " + BlockID_2 +
              "AND s.T_OPERBLOCKID = " + OperBlockID_2 +
              "AND s.T_SORT NOT IN ( " +
              "SELECT T_SORT " + 
              "FROM DOPROBLCK_DBT " +
              "WHERE T_KIND_OPERATION = " + KindOperation_1 +
              "AND T_BLOCKID = " + BlockID_1 +
              "AND T_OPERBLOCKID = " + OperBlockID_1 +
              ") "; 

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    PrintNotExistOPROBLCK( rs.value(0), rs.value(2), rs.value(1), rs.value(3), rs.value(4) );
  end;
end;

/*Сравнить данные таблицы "Настройка блока для вида операции" OPROBLCK*/
macro CompareOPROBLCKNotExist( KindOperation_1 : integer, Name_1 : string, KindOperation_2 : integer, Name_2 : string )
  var sqlString : string;
  var rs : RsdRecordset;
  var sqlString_ : string;
  var rs_ : RsdRecordset;

  sqlString = BlocksToOperations( KindOperation_1, KindOperation_2 );

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );
  while( rs.moveNext())

    sqlString_ = ConditionsToBlocks( KindOperation_1, KindOperation_2, rs.value(0), rs.value(1) );

    cmd_ = RsdCommand( sqlString_ );
    cmd_.NullConversion = true;
    rs_ = RsdRecordset( cmd_ );
  
    while( rs_.moveNext())
      CompareSingleOPROBLCKNotExist( KindOperation_1, KindOperation_2, rs.value(0), rs.value(1), rs_.value(0), rs_.value(1) )
    end;
  end;
end;

/*Сравнить данные таблицы "Условие выполнения блока" OPRCBLCK*/
macro CompareSingleOPRCBLCKNotExist( OperBlockID_1 : integer, OperBlockID_2 : integer )
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = "SELECT DISTINCT s.T_OPERBLOCKID, s.T_STATUSKINDID, " + OperBlockID_2 + " as OTHEROPER " + 
              "FROM DOPRCBLCK_DBT s " + 
              "WHERE s.T_OPERBLOCKID = " + OperBlockID_1 +
              "AND s.T_STATUSKINDID NOT IN ( " +
              "SELECT T_STATUSKINDID " + 
              "FROM DOPRCBLCK_DBT " +
              "WHERE T_OPERBLOCKID = " + OperBlockID_2 +
              ") " +
              "UNION " +
              "SELECT DISTINCT s.T_OPERBLOCKID, s.T_STATUSKINDID, " + OperBlockID_1 + " as OTHEROPER " + 
              "FROM DOPRCBLCK_DBT s " + 
              "WHERE s.T_OPERBLOCKID = " + OperBlockID_2 +
              "AND s.T_STATUSKINDID NOT IN ( " +
              "SELECT T_STATUSKINDID " + 
              "FROM DOPRCBLCK_DBT " +
              "WHERE T_OPERBLOCKID = " + OperBlockID_1 +
              ") "; 

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())   
    PrintNotExistOPRCBLCK( rs.value(1), rs.value(0) );
  end;
end;

/*Сравнить данные таблицы "Условие выполнения блока" OPRCBLCK*/
macro CompareOPRCBLCKNotExist( KindOperation_1 : integer, Name_1 : string, KindOperation_2 : integer, Name_2 : string )
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = ConditionsToOperations( KindOperation_1, KindOperation_2 );

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );
  while( rs.moveNext())
    CompareSingleOPRCBLCKNotExist( rs.value(0), rs.value(1) )
  end;
end;

/*Сравнить данные таблицы "Условие выполнения блока" OPRCBLCK*/
macro CompareOPRCBLCK( KindOperation_1 : integer, Name_1 : string, KindOperation_2 : integer, Name_2 : string )

/*
Поле        Русское название (для сообщения об ошибке)
T_NUMVALUE  Числовое значение
T_CONDITION Условие
*/
/*Данные берем из OPROBLCK*/
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 4; /*количество полей в одной таблице*/
  array FieldName;
  var strResCompare : string;

  FieldName( 0 ) = "Числовое значение";
  FieldName( 1 ) = "Условие";

  sqlString = "SELECT " +
              "t1.T_OPERBLOCKID        ," +
              "t1.T_STATUSKINDID       ," +
              "t1.T_NUMVALUE           ," +
              "t1.T_CONDITION          ," +
              
              "t2.T_OPERBLOCKID        ," +
              "t2.T_STATUSKINDID       ," +
              "t2.T_NUMVALUE           ," +
              "t2.T_CONDITION           " +
              
              "FROM doprcblck_dbt t1 JOIN doprcblck_dbt t2 " +
              "ON ( (t1.T_OPERBLOCKID, t2.T_OPERBLOCKID) IN ( " + ConditionsToOperations( KindOperation_1, KindOperation_2 ) + " ) " +
              " AND t1.T_STATUSKINDID = t2.T_STATUSKINDID ) ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( CompareFieldsExt( rs, 2, numFields, 2, FieldName, @strResCompare ))
      PrintDiffersOPRCBLCK( KindOperation_1, KindOperation_2, rs.value(0), rs.value(numFields), strResCompare );
    end;
  end;
end;

/*6.Сравнить блоки если установлен флаг сравнения*/
macro CompareBlocksIfNeed( KindOperation_1 : integer, KindOperation_2 : integer )
/*Данные берем из OPROBLCK*/
  var sqlString : string;
  var rs : RsdRecordset;

  sqlString = BlocksToOperations( KindOperation_1, KindOperation_2 );

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    CompareOPRBLOCK( rs.value(0), rs.value(1) );
  end;
end;

/*1.Сравнить данные таблицы "Вид операции" OPRKOPER*/
macro CompareOPRKOPER( Block : integer, KindOperation_1 : integer, KindOperation_2 : integer )
/*
  T_KIND_OPERATION  NUMBER(5)                   NOT NULL,
  T_DOCKIND         NUMBER(5)                   NOT NULL,
  T_NOTINUSE        CHAR(1 BYTE),
  T_INITMACRO       VARCHAR2(79 BYTE),
  T_SYSTYPES        VARCHAR2(16 BYTE),
  T_NAME            VARCHAR2(79 BYTE),
  T_SHORTNAME       VARCHAR2(15 BYTE),
  T_UPGRADE         CHAR(1 BYTE),
  T_ISMAINTANANCE   CHAR(1 BYTE),
  T_PARENT          NUMBER(10),
  T_VERSION         VARCHAR2(15 BYTE)
*/
/*
Поле            Русское название (для сообщения об ошибке)
T_DOCKIND       Вид первичного документа
T_NOTINUSE      Признак закрытой операции
T_INITMACRO     Макрос инициализации
T_SYSTYPES      Системные типы
T_NAME          Название операции
T_SHORTNAME     Краткое название
T_ISMAINTANANCE Операция сопровождения
*/
  var Version1, Version2 : string;
  var sqlString : string;
  var rs : RsdRecordset;
  var numFields = 9; /*количество полей в одной таблице*/
  array FieldName;
  var strResCompare : string;

  FieldName( 0 ) = "Вид первичного документа";
  FieldName( 1 ) = "Признак закрытой операции";
  FieldName( 2 ) = "Макрос инициализации";
  FieldName( 3 ) = "Системные типы";
  FieldName( 4 ) = "Название операции";
  FieldName( 5 ) = "Краткое название";
  FieldName( 6 ) = "Операция сопровождения";

  sqlString = "SELECT " +
              "t1.T_KIND_OPERATION, " +
              "t1.T_DOCKIND       , " +
              "t1.T_NOTINUSE      , " +
              "t1.T_INITMACRO     , " +
              "t1.T_SYSTYPES      , " +
              "t1.T_NAME          , " +
              "t1.T_SHORTNAME     , " +
              "t1.T_ISMAINTANANCE , " +
              "t1.T_VERSION       , " +
              
              "t2.T_KIND_OPERATION, " +
              "t2.T_DOCKIND       , " +
              "t2.T_NOTINUSE      , " +
              "t2.T_INITMACRO     , " +
              "t2.T_SYSTYPES      , " +
              "t2.T_NAME          , " +
              "t2.T_SHORTNAME     , " +
              "t2.T_ISMAINTANANCE , " +
              "t2.T_VERSION         " +
              
              "FROM doprkoper_dbt t1 FULL OUTER JOIN doprkoper_dbt t2 " +
              "ON ( t2.T_KIND_OPERATION = " + KindOperation_2 + " ) " +
              "WHERE t1.T_KIND_OPERATION = " + KindOperation_1 + "; ";

  cmd = RsdCommand( sqlString );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.moveNext())
    if( rs.value(8) == NULLVAL ) Version1 = ""; else Version1 = rs.value(8); end;
    if( rs.value(8+numFields) == NULLVAL ) Version2 = ""; else Version2 = rs.value(8+numFields); end;

    PrintCompareType( 1, KindOperation_1, Version1, rs.value(5), 
                         KindOperation_2, Version2, rs.value(5+numFields) );

    if( CompareFieldsExt( rs, 1, numFields, 7, FieldName, @strResCompare ))
      PrintDiffersOPRKOPER( rs.value(0), rs.value(numFields), strResCompare );
    end;

    CompareOPRCHDOC( KindOperation_1, KindOperation_1 );
    CompareOPRCHDOCNotExist( KindOperation_1, KindOperation_1 );
    CompareOPRINIST( KindOperation_1, rs.value(5), KindOperation_2, rs.value(5+numFields) );
    CompareOPRINISTNotExist( KindOperation_1, rs.value(5), KindOperation_2, rs.value(5+numFields) );
    CompareOPROBLCK( KindOperation_1, rs.value(5), KindOperation_2, rs.value(5+numFields) );
    CompareOPROBLCKNotExist( KindOperation_1, rs.value(5), KindOperation_2, rs.value(5+numFields) );
    CompareOPRCBLCK( KindOperation_1, rs.value(5), KindOperation_2, rs.value(5+numFields) );
    CompareOPRCBLCKNotExist( KindOperation_1, rs.value(5), KindOperation_2, rs.value(5+numFields) );

    if( Block == 1 )
      CompareBlocksIfNeed( KindOperation_1, KindOperation_2 );
    end;
  end;

  PrintFooter();

end;
/*конец сравнения видов операций*/


macro ПротоколСравненияБлоковОпераций( Type : integer, Block : integer, ElemID_1 : integer, ElemID_2 : integer ) : bool

  countDiffers = 0;

  PrintHeader( Type, Block );

  if( Type == 0 )
    CompareOPRBLOCK( ElemID_1, ElemID_2 );
  else
    CompareOPRKOPER( Block, ElemID_1, ElemID_2 );
  end;

  return true;
end;
