import cb_sql, rsd, oralib, likepy, globals, rsexts, osfile;

private var _outString;

private Macro _collectOutProc (str)
   if (_outString)
      _outString = _outString + " " + trim (str);
   else
      _outString = trim (str);
      _outString = StrSubst(_outString,"\n","");
   end;
end;

macro CaptureOutput
   _outString = null;
   SetOutHandler (@_collectOutProc);
end;

macro StopCaptureOutput
   var retVal = _outString;
   _outString = null;
   SetOutHandler;
   return retVal;
end;

macro GetDprtName(DprtID)
  var query;
  var rs;
  var params : TArray;
  var DprtName = "";

  CaptureOutput;
[
SELECT t_Name
  FROM ddp_dep_dbt
 WHERE t_Code = :DprtID
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("DprtID", DprtID)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    DprtName = rs.value(0);
  end;
  return DprtName;
end;

macro GetDprtPartyName(DprtID)
  var query;
  var rs;
  var params : TArray;
  var DprtPartyName = "";

  CaptureOutput;
[
SELECT dp.t_Name, pt.t_Name
  FROM ddp_dep_dbt dp, dparty_dbt pt
 WHERE dp.t_Code = :DprtID AND pt.t_PartyID = dp.t_PartyID
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("DprtID", DprtID)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    DprtPartyName = rs.value(1);
  end;
  return DprtPartyName;
end;

macro GetDprtPartyShortName(DprtID)
  var query;
  var rs;
  var params : TArray;
  var DprtPartyShortName = "";

  CaptureOutput;
[
SELECT dp.t_Name, pt.t_shortname
  FROM ddp_dep_dbt dp, dparty_dbt pt
 WHERE dp.t_Code = :DprtID AND pt.t_PartyID = dp.t_PartyID
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("DprtID", DprtID)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    DprtPartyShortName = rs.value(1);
  end;
  return DprtPartyShortName;
end;

macro GetEAStorageDir(DprtID)
  var query;
  var rs;
  var params : TArray;
  var EAStorageDir = "";

  CaptureOutput;
[
SELECT t_eastoragedir
  FROM ddp_dep_dbt
 WHERE t_Code = :DprtID
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("DprtID", DprtID)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    EAStorageDir = rs.value(0);
  end;
  return EAStorageDir;
end;

macro GetOperName(OperID)
  var query;
  var rs;
  var params : TArray;
  var OperName = "";

  CaptureOutput;
[
SELECT t_Name
  FROM dperson_dbt
 WHERE t_Oper = :OperID
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("OperID", OperID)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    OperName = rs.value(0);
  end;
  return OperName;
end;

private macro _GetRegDefaultKindOfDisk()
  var stat;
  var kind;
  GetRegistryValue("EA\\EDTODEV\\DEFAULTKINDOFDISK", V_INTEGER, kind, stat);
  return kind;
end;

macro _GetOperMediaKind(StoreUnitType)
  var query;
  var rs;
  var params : TArray;
  var MediaKind = 0;

  CaptureOutput;
[
SELECT t_MediaKind
  FROM dedstunitusermedia_dbt
 WHERE t_StoreUnitType = :StoreUnitType 
   AND t_Oper = :OperID
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("OperID", {oper})
                    ,SQLParam("StoreUnitType", StoreUnitType)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    MediaKind = rs.value(0);
  end;

  return MediaKind;
end;

macro GetMediaKindName(StoreUnitType)
  var query;
  var rs;
  var params : TArray;
  var MediaKind = 0;
  var MediaKindName = "";

  MediaKind = _GetOperMediaKind(StoreUnitType);

  if(MediaKind == 0)
    MediaKind = _GetRegDefaultKindOfDisk();
  end;

  CaptureOutput;
[
SELECT t_Name
  FROM dllvalues_dbt
 WHERE t_List = 3535 
   AND t_Element = :MediaKind
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("MediaKind", MediaKind)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    MediaKindName = rs.value(0);
  end;

  return MediaKindName;
end;

macro GetMediaKindSize(StoreUnitType)
  var query;
  var rs;
  var params : TArray;
  var MediaKind = 0;
  var MediaKindName = "";

  MediaKind = _GetOperMediaKind(StoreUnitType);

  if(MediaKind == 0)
    MediaKind = _GetRegDefaultKindOfDisk();
  end;

  CaptureOutput;
[
SELECT t_Code
  FROM dllvalues_dbt
 WHERE t_List = 3535 
   AND t_Element = :MediaKind
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("MediaKind", MediaKind)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    MediaKindName = rs.value(0);
  end;

  return MediaKindName;
end;

macro GetStoreUnitTypeName(StoreUnitType)
  var query;
  var rs;
  var params : TArray;
  var StoreUnitTypeName = "";

  CaptureOutput;
[
SELECT t_Name
  FROM dedstunittype_dbt
 WHERE t_StoreUnitType = :StoreUnitType
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("StoreUnitType", StoreUnitType)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    StoreUnitTypeName = rs.value(0);
  end;

  return StoreUnitTypeName;
end;

macro GetStoreUnitTypeCompleteCondition(StoreUnitType)
  var query;
  var rs;
  var params : TArray;
  var CompleteCondition = 0;

  CaptureOutput;
[
SELECT t_CompleteCondition
  FROM dedstunittype_dbt
 WHERE t_StoreUnitType = :StoreUnitType
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("StoreUnitType", StoreUnitType)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    CompleteCondition = rs.value(0);
  end;

  return CompleteCondition;
end;

macro GetCompleteConditionName(CompleteCondition)
  var query;
  var rs;
  var params : TArray;
  var CompleteConditionName = "";

  CaptureOutput;
[
SELECT t_szNameAlg
  FROM dnamealg_dbt
 WHERE t_iTypeAlg = 7505
   AND t_iNumberAlg = :CompleteCondition
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("CompleteCondition", CompleteCondition)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    CompleteConditionName = rs.value(0);
  end;

  return CompleteConditionName;
end;

/*Функция конвертирует текстовый файл в WIN кодировку*/
macro ConvertToANSI(PathToFileOEM : string, PathToFileANSI : string)

  var stat = true;

  file FileOEM() txt;         /* Текстовый файл в DOS кодировке до конвертации */
  file FileANSI() txt write;  /* Текстовый файл в WIN кодировке после конвертации */
  
  /*Открыть файл для чтения*/
  stat = Open(FileOEM, PathToFileOEM);
  if(not stat)
    msgbox("Ошибка открытия файла для чтения|" + PathToFileOEM);
    stat = false;
  else
    /*Открыть файл для записи*/
    stat = Open(FileANSI, PathToFileANSI);
    if(not stat)
      msgbox("Ошибка открытия файла для записи|" + PathToFileANSI);
      stat = false;
    else

      while(Next(FileOEM))
        FileANSI.str = ToANSI(FileOEM.str);
        /*Чтобы работала ToANSI нужно установить в rsreq.ini FORCE_OEM_ANSI_CVT = Y*/
        Insert(FileANSI);
      end;

      Close(FileANSI);
    end;

    Close(FileOEM);
  end;

  return stat;
end;

macro GetDocTotal(edstunitlog)
  var doctotal = 0;
  var query;
  var rs;
  var params : TArray;

  CaptureOutput;
[
SELECT COUNT(*) FROM dedoc_dbt edoc
 WHERE edoc.t_StoreUnitLogID = :StoreUnitLogID
];
  query = StopCaptureOutput;
  params = makeArray(SQLParam("StoreUnitLogID", edstunitlog.StoreUnitLogID)
                    );
  rs = execSQLselect(query, params, true);
  if(rs and rs.moveNext())
    doctotal = int(rs.value(0));
  end;
  return doctotal;
end;

