/*
    Библиотека макрофункций для работы с массивами (TArray).

    Функции:
        ArrCreate - создание массива по набору значений.
        ArrCopy - копирование массива.
        ArrFind - поиск по значения в массиве ( линейный O(n) )
        arrAdd  - присоединение одного массива в другому
*/

/* Создаёт массив и инициализирует его заданными значениями.
   Значения задаются в параметрах, количество любое, допускаются NULL-значения.
*/
MACRO ArrCreate( )
    var arr = TArray;
    var i = 0;
    var val;
    while( GetParm( i, val ) )
        arr[i] = val;
        i = i + 1;
    end;

    return arr;
END;

// Создаёт копию массива
// !!! В дальнейшем следует расширить функциональность, сделав следующие параметры:
//     src, dst, fromSrc, fromDst, count.
MACRO ArrCopy( src )
    var dst = TArray;
    var i = 0;
    while( i < src.size )
        dst[i] = src[i];
        i = i + 1;
    end;
    return dst;
END;

// Поиск значения в массиве. Возвращает индекс. Отрицательное число, если не найдено.
MACRO ArrFind( arr, val )
    var i = 0;
    while( i < arr.size )
        if( arr[i] == val )
            return i;
        end;
        i = i + 1;
    end;
    return -1;
END;

//возвращает arr + add
macro arrAdd(arr, add)
    var addSize = add.size;
    var i = 0;
    while (i < addSize)
        arr(arr.size) = add(i);
        i = i + 1;
    end;
    return arr;               
end;