/*-------------------------------------------------------------------------
          €¢â®¬ â¨§¨à®¢ ­­ ï ¡ ­ª®¢áª ï á¨áâ¥¬  RS-Bank v6.0.020
                 Copyright (c) R-Style Software Lab

  ˆ¬ï ä ©«         : mpcreprt.mac

  ¨¡«¨®â¥ª        : 

  Ž¯¨á ­¨¥         : ¥ç âì ®âç¥â®¢ ¯à®£­®§  ¨ à á¯®àï¦¥­¨ï
                     ¯® ®¯¥à æ¨ï¬

  à®£à ¬¬¨áâ      : „ãàï£¨­ …¢£¥­¨© (DEA)

  ‘®§¤ ­           : 02.03.2009
-------------------------------------------------------------------------*/
IMPORT RsbDataSet,  CTInter,  globals, library, FIInter;
    
var   DateCalculateBegin, 
      DateCalculateEnd,
      ContractID,
      ContractBoffice,
      ContractNumber,
      ContractAccount,
      OperNum,
      Schedkind,
      DateMin,
      OperName,
      Daily,
      OpKind,
      OperId,
      DocID,
      ServiceID,
      OperDate,
      contr,
      flagFirstRow;         

RECORD contract( prccontract );
RECORD Document(arhdoc);


// ®¤ª çª  ­ §¢ ­¨ï íª-®ä¨á 
PRIVATE MACRO PumpBO(BO)
   var cmd, RS;
   cmd = RSDCommand( " select t_code from dllvalues_dbt where t_list = 1118 and t_element = ? " ) ; 
   cmd.addParam( "", RSDBP_IN, BO );
   cmd.execute();
   RS = TRsbDataSet(cmd);
   if (RS.movenext() )
      ContractBoffice = Rs.code;
   end;
END;


/***************************************************************************** 
   «®ª äã­ªæ¨© ¯¥ç â¨ ¯à®£­®§  ¯® ®¯¥à æ¨ï¬                               
******************************************************************************/

// ¥ç âì è ¯ª¨ ¯à®£­®§ 
PRIVATE MACRO PrintHead()
      [           ###############################################]({Name_Bank});
   if ({OperDprt} != {OperDprtNode})
      [           ###############################################]({OperDprt}:l);
   end;
      [      ];
   if (Schedkind == 1)
      [                      à®£­®§ à áç¥â  ¯à®æ¥­â®¢ ];
   end;
   if (Schedkind == 2)
      [                      à®£­®§ ­ ç¨á«¥­¨ï ¯à®æ¥­â®¢ ];
   end;
   if (Schedkind == 3)
      [                      à®£­®§ ®¯« âë ¯à®æ¥­â®¢ ];
   end;
      [   ];
      [  „ â  ­ ç «  à áç¥â :    ##########](Date(DateCalculateBegin):c);
      [  „ â  ®ª®­ç ­¨ï à áç¥â : ##########](Date(DateCalculateEnd):c);
      [  à®æ¥­â­ë© ¤®£®¢®à:     #### ####](ContractBoffice,ContractNumber);
      [  ‹¨æ¥¢®© áç¥â:           ####################](ContractAccount);
      [  „ â  à áç¥â :        ##########](Date({curdate}):c);
      [   ];
      [ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿];
      [³  ç «ì­ ï ¤ â  ³ Š®­¥ç­ ï ¤ â  ³ —¨á«® ³     Žáâ â®ª      ³ ‘â ¢ª  ¢ £®¤  ³   ‘ã¬¬        ³ ” ªâ. ¤ â   ³   ” ªâ. áã¬¬   ³];
      [³                ³               ³ ¤­¥©  ³                  ³               ³   ¯à®æ¥­â®¢   ³ ®¯¥à æ¨¨    ³   ¯à®æ¥­â®¢    ³];
END;


// ¥ç âì ¤­  ¯à®£­®§ 
PRIVATE MACRO PrintBottom(Days,TotalSum,SumFact)
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
      [³ ˆâ®£® ¯® à áç¥âã:                                                                                                        ³];
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
  if (Schedkind == 1) 
      [³################³###############³###### ³                  ³               ³############## ³             ³                ³]
      (Date(DateCalculateBegin):c, Date(DateCalculateEnd):c, Days, TotalSum:0:5:z); 
  else 
      [³################³###############³###### ³                  ³               ³############## ³             ³ ############## ³]
      (Date(DateCalculateBegin):c, Date(DateCalculateEnd):c, Days, TotalSum:0:5, SumFact); 
  end;
      [ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];
      [   ];
      [  Ž¯¥à æ¨®­¨áâ:     #### #########](OperNum,OperName);
END;


// ¥ç âì ®¤­®£® ¤­ï
PRIVATE MACRO PrintDayLine(rs, Sum)
      if (flagFirstRow)
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
      else
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];      
      end;
      [³################³###############³#######³##################³###############³###############³             ³                ³]
      (Date(rs.STARTDATE):c, Date(rs.ENDDATE):c, rs.DAYSNUM, rs.Rest, rs.Rate:15:*,rs.Point, Sum:0:5:z);   
END;   


// ¥ç âì § ¯¨á¨ ª «¥­¤ à­®£® £à ä¨ª 
PRIVATE MACRO PrintGraphRecord(rs, Days,Summ)
   var DateReal;

   if (ValType(rs.DATEREAL) != V_UNDEF)
      DateReal = Date(rs.DATEREAL);
   else
      DateReal = "";
   end;
   if (Daily == 0)
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];  
   end;
      [³################³###############³#######³                  ³               ³###############³#############³################³]
      (Date(rs.PERIODBEGINDATE):c, Date(rs.PERIODENDDATE):c, Days, Summ:0:5:z, DateReal:c:z, rs.SUMFACT:z); 
END;                                                       


// ¥ç âì ¯®¤§ £®«®¢ª  ¤«ï § ¯¨á¨ ¤®­ ç¨á«¥­¨ï
PRIVATE MACRO PrintAddChargeHead(void)
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
      [³ ‘âà®ª  ¤®­ ç¨á«¥­¨ï:                                                                                                     ³];
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
END;


// ¥ç âì ¯®¤§ £®«®¢ª  ¤«ï § ¯¨á¨ £à ä¨ª 
PRIVATE MACRO PrintSubHead(void)
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
   if (Schedkind == 1)
      [³ ® £à ä¨ªã à áçñâ :                                                                                                      ³];
   end;                                                     
   if (Schedkind == 2)
      [³ ® £à ä¨ªã ­ ç¨á«¥­¨ï:                                                                                                   ³];
   end;
   if (Schedkind == 3)
      [³ ® £à ä¨ªã ®¯« âë:                                                                                                       ³];
   end;
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
END;


// ¥ç âì áã¬¬ë ¥¦¥¤­¥¢­®£® à áç¥â  
PRIVATE MACRO PrintTempDailyItog(TotalSumR,i,BegDate,EndDate)
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
      [³ ® ¥¦¥¤­¥¢­®¬ã à áçñâã:                                                                                                  ³];
      [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
      [³################³###############³#######³                  ³               ³###############³             ³                ³]
      (Date(BegDate):c, Date(EndDate):c, i, TotalSumR:0:5:z);    
END;


//  áç¥â ®¤­®£® ¯¥à¨®¤  
PRIVATE MACRO CalcOnePeriod(RS, Schedkind, flagPeriodCalc, Itog:@money)

   var DDate, BegDate, EndDate,
       cmd,cmd2,rs2,
       i = 0,
       TotalSum = $0,
       ISum = $0,
       stat = 0;
   stat = 0;
   DDate = RS.Date;
   BegDate = RS.PeriodBeginDate;
   EndDate = RS.PeriodEndDate;

   //­¨ç¥£® ­¥ ­ è«¨
   if (DDate == date (0,0,0))
      stat = 1;
   end;

   if (stat == 0)
      cmd = RSDCommand( "{ ? = call RSB_PERCENT.PRC_CALCPERCENTVALUES ( ?, ?, ?, ?, ? ) }" );
      cmd.addParam( "retval", RSDBP_OUT, V_INTEGER );
      cmd.addParam( "Sum", RSDBP_OUT, V_NUMERIC );
      cmd.addParam( "", RSDBP_IN, ContractID );
      cmd.addParam( "", RSDBP_IN, BegDate );
      cmd.addParam( "", RSDBP_IN, EndDate );
      cmd.addParam( "", RSDBP_IN, Daily );
      cmd.execute();   
      Itog = cmd.value( "Sum" );

      if (Daily == 1)   // ¥á«¨ ¥¦¥¤­¥¢­ë© à áç¥â - â® ¢ë¢®¤¨¬ ¢á¥ áâà®ª¨
         Itog = $0;
         cmd2 = RSDCommand( "select T_STARTDATE,T_ENDDATE,T_DAYSNUM,T_REST,T_RATE,T_SUM,T_POINT from DPRCCALCPRCVAL_TMP" );
         cmd2.execute();
         rs2 = TRsbDataSet(cmd2);
         
         while( rs2.movenext() )
            ISum = rs2.Sum;
            if ((flagPeriodCalc) and (Schedkind != 1))
               ISum = round(ISum,2);
            end; 
            Itog = Itog + ISum;
            PrintDayLine(rs2,ISum);
            flagFirstRow = false;
            i = i + 1;
         end;
      end;
   end;                                      
END;                                         


// ¥ç âì ®âçñâ  ¯à®£­®§  à áçñâ  ¯à®æ¥­â®¢
MACRO MpcPrognosisGenReport( ContractBuf, ScheduleKind, DateCalcBegin, DateCalcEnd, isDaily )

   var Data, 
       cmd_mindate, RS_mindate,
       RS, cmd,
       flagPeriodCalc = false,
       iSum = $0,
       iDays = 0,
       TotalSum = $0,
       TotalDays = 0,
      FactSum = $0,
      Summa = $0;
   
   SetBuff( contract, ContractBuf );
   DateCalculateBegin   = DateCalcBegin; 
   DateCalculateEnd     = DateCalcEnd;
   Schedkind            = ScheduleKind;
   ContractID           = contract.ContractID;
   PumpBO(contract.BackOffice);
   ContractNumber = contract.Number; 
   ContractAccount = contract.Account; 

   flagFirstRow = false;

   if (isDaily == 88)
      Daily = 1;
   else
      Daily = 0;
   end;
   OperNum = {oper};
   OperName = {Name_Oper};
   cmd_mindate = RSDCommand( " select min(T_DATE) as mindate from DPRCCNTSCHED_DBT " +
       "where T_CONTRACTID = ? and T_SCHEDULEKIND = ? and T_SPECIALTYPE = 0 " +
       "and (T_DATEREAL is NULL or T_DATEREAL = TO_DATE('01.01.0001')) " +
       "and T_PERIODBEGINDATE >= ? and T_PERIODENDDATE <= ? ") ; 

   cmd_mindate.addParam( "", RSDBP_IN, ContractID );
   cmd_mindate.addParam( "", RSDBP_IN, Schedkind );
   cmd_mindate.addParam( "", RSDBP_IN, DateCalculateBegin );
   cmd_mindate.addParam( "", RSDBP_IN, DateCalculateEnd );
   cmd_mindate.execute();

   RS_mindate = TRsbDataSet(cmd_mindate);
   if (RS_mindate.movenext() )
      DateMin = RS_mindate.mindate;
   end;

   PrintHead();
                               
   cmd = RSDCommand( "select T_DATE, T_PERIODBEGINDATE, T_PERIODENDDATE, T_SPECIALTYPE, T_SUMCALC, T_SUMFACT, T_DATEREAL from DPRCCNTSCHED_DBT " +
                      "where T_CONTRACTID = ? and T_SCHEDULEKIND = ? and T_PERIODENDDATE <= ? " +
                      "and T_PERIODBEGINDATE >= ? order by T_PERIODBEGINDATE " );
   cmd.addParam( "", RSDBP_IN, ContractID );
   cmd.addParam( "", RSDBP_IN, Schedkind );
   cmd.addParam( "", RSDBP_IN, DateCalculateEnd );
   cmd.addParam( "", RSDBP_IN, DateCalculateBegin );

   cmd.execute();

   RS = TRsbDataSet(cmd);

   while( RS.movenext())

      iDays = Date(RS.PERIODENDDATE) - Date(RS.PERIODBEGINDATE) + 1;

      if (ValType(DateMin) != V_UNDEF)
         if (RS.Date < DateMin)
            flagPeriodCalc = true;
         else
            flagPeriodCalc = false;
         end;
      else
         flagPeriodCalc = true;
      end;      

      if (Daily == 1) // ¥¦¥¤­¥¢­ë© à áç¥â
      
         if (Rs.SPECIALTYPE != 1) 
            CalcOnePeriod(RS, Schedkind, flagPeriodCalc, @iSum);
         end;
         
         if ((RS.SUMCALC != iSum) and (flagPeriodCalc))
            if (SchedKind != 1)
               iSum = round(iSum);
            end;
            PrintTempDailyItog(iSum, iDays, Rs.PERIODBEGINDATE, Rs.PERIODENDDATE);
            iSum = RS.SUMCALC;
         end;     

         if (Rs.SPECIALTYPE != 1)
            PrintSubHead();
         else
            PrintAddChargeHead(); 
         end;

         flagFirstRow = true;
         
      else           // ®¡ëç­ë© à áç¥â
         
         if ((flagPeriodCalc == false) and (Rs.SPECIALTYPE != 1))
            CalcOnePeriod(RS, Schedkind, flagPeriodCalc, @iSum);
            if (SchedKind != 1)
               iSum = round(iSum);
            end;
         else
            if (ValType(RS.SUMCALC) != V_UNDEF)
               iSum = RS.SUMCALC;
            else
               iSum = $0;
            end;
         end;
         
      end;            
      
      PrintGraphRecord(RS, iDays, iSum);
      
      TotalSum = TotalSum + iSum;
      TotalDays = TotalDays + iDays;
      
      if (ValType(RS.SUMCALC) != V_UNDEF)
         Summa = Summa + RS.SUMCALC;
      end;
      if (ValType(RS.SUMFACT) != V_UNDEF)
       FactSum = FactSum + RS.SUMFACT;
     end;
         
   end;   
   
   TotalDays =  Date(DateCalculateEnd) - Date(DateCalculateBegin) + 1 ;

   PrintBottom(TotalDays, TotalSum, FactSum); 
END;                                       


/*****************************************************************************
   «®ª äã­ªæ¨© ¯¥ç â¨ à á¯®àï¦¥­¨© ¯® ®¯¥à æ¨ï¬
******************************************************************************/

// ¥ç âì è ¯ª¨ à á¯®àï¦¥­¨ï
PRIVATE MACRO CarryPrintHead()              
   [             ############################################################]({Name_Bank}:c);
   if ({OperDprt} != {OperDprtNode})
   [             ############################################################]({OperDprt}:c);
   end;
   [      ];
   if (OpKind == 4521)
   [        á¯®àï¦¥­¨¥ ­  ¯à®¢¥¤¥­¨¥ ®¯¥à æ¨¨ ­ ç¨á«¥­¨ï ¯à®æ¥­â®¢ ];
   end;
   if (OpKind == 4522)
   [        á¯®àï¦¥­¨¥ ­  ¯à®¢¥¤¥­¨¥ ®¯¥à æ¨¨ ®¯« âë ¯à®æ¥­â®¢ ];
   end;
   if (OpKind == 4523)
   [        á¯®àï¦¥­¨¥ ­  ¯à®¢¥¤¥­¨¥ ®¯¥à æ¨¨ ¤®­ ç¨á«¥­¨ï ¯à®æ¥­â®¢ ];
   end;
   if (OpKind == 4524)
   [        á¯®àï¦¥­¨¥ ­  ¯à®¢¥¤¥­¨¥ ®¯¥à æ¨¨ à¥ª« áá¨ä¨ª æ¨¨  ªâ¨¢  ¯à®æ¥­â®¢ ];
   end;
   if (OpKind == 4525)
   [        á¯®àï¦¥­¨¥ ­  ¯à®¢¥¤¥­¨¥ ®¯¥à æ¨¨ ¢ë­®á  ­  ¯à®áà®çªã ¯à®æ¥­â®¢ ];
   end;
   [   ];
   [  à®æ¥­â­ë© ¤®£®¢®à:      #### ####](ContractBoffice,ContractNumber);
   [  ‹¨æ¥¢®© áç¥â:            #########################](ContractAccount:l);
   [  „ â  ­ ç «  ¤®£®¢®à :    ##########](Date(DateCalculateBegin):c);
   [  „ â  ®ª®­ç ­¨ï ¤®£®¢®à : ##########](Date(DateCalculateEnd):c);
   [   ];
   [  „ â  ®¯¥à æ¨¨:         ##########](Date(OperDate):c);
   [   ];
   [ÚÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄ¿];
   [³ üü   ³         ‘çñâ ¤¥¡¥â          ³ ‚ «îâ  ³  ‘ã¬¬   ³        ‘çñâ ªà¥¤¨â          ³  ‚ «îâ   ³   ‘ã¬¬      ³];
   [³      ³                             ³ ¤¥¡¥â  ³  ¤¥¡¥â  ³                             ³  ªà¥¤¨â  ³  ªà¥¤¨â     ³];
END;


// ¥ç âì áâà®ª¨ à á¯®àï¦¥­¨ï
PRIVATE MACRO PrintLineCarryRep (Document, first)
   if (first)
   [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
   else
   [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
   end;
   [³######³#############################³########³#########³#############################³##########³#############³]
   (Document.Number:c, Document.PayerAccount:c, ®«ãç¨âìŠ®¤”¨­ˆ­(Document.PayerFIID):c, Document.PayerSum:c, Document.ReceiverAccount:c, ®«ãç¨âìŠ®¤”¨­ˆ­(Document.ReceiverFIID):c, Document.ReceiverSum:c );
   [³      ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
   [³      ³#######################################################################################################³](Document.Ground:w);
END;


// ¥ç âì ¤­  à á¯®àï¦¥­¨ï
PRIVATE MACRO CarryPrintBottom()
   [ÀÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];
   [   ];
   [  ################# ]("®¤¯¨á¨: ");
   [  Ž¯¥à æ¨®­¨áâ:     #### #########](OperNum,OperName);
END;


// ”ã­ªæ¨ï ä®à¬¨àã¥â ¤ ­­ë¥ à á¯®àï¦¥­¨ï
PRIVATE MACRO PrintLinesCarry()
   var  RS, cmd, first;

   
   cmd = RSDCommand( "select * FROM DPRCOPRDOCS_DBT OD " +
                      "where OD.T_DOCID = ?") ;   
   cmd.addParam( "", RSDBP_IN, DocID );
   cmd.execute();
   
   RS = TRsbDataSet(cmd);
   first = true;
   
   while ( RS.movenext() )
      PrintLineCarryRep(RS, first);
      first = false;
   end;

END;


// ‡ ¯®«­¥­¨¥ ¯®«¥© è ¯ª¨
PRIVATE MACRO MpcPumpFieldsForCarryHead()
   var  Data, RS, cmd;
   
   OperNum = {oper};
   OperName = {Name_Oper};
   cmd = RSDCommand( " select  cnt.t_backoffice, cnt.t_number, cnt.t_account, cnt.t_begindate, cnt.t_enddate, t.t_operdate " + 
     " from dprccontract_dbt cnt, dprccntopr_dbt t " + 
     " where cnt.t_contractid = t.T_CONTRACTID and t.t_docid = ? and t_operkind = ? ") ; 
   cmd.addParam( "", RSDBP_IN, DocID );
   cmd.addParam( "", RSDBP_IN, OpKind );

   cmd.execute();

   RS = TRsbDataSet(cmd);
   if (RS.movenext() )
      ContractBoffice = RS.backoffice;
      ContractNumber = RS.number;
      ContractAccount = RS.account;
      DateCalculateBegin = RS.begindate;
      DateCalculateEnd = RS.enddate;
      OperDate = RS.operdate;
   end;                                      
END;


// ¥ç âì à á¯®àï¦¥­¨ï ¯® ®¯¥à æ¨¨
MACRO MpcCarryGenReport( DocIDLocal, OperKindLocal )
   DocID = DocIDLocal;
   OpKind = OperKindLocal;
   MpcPumpFieldsForCarryHead();
   PumpBO(ContractBoffice);
   CarryPrintHead();
   PrintLinesCarry();
   CarryPrintBottom();
END;


// ¥ç âì à á¯®àï¦¥­¨© ¨§ ¬ áá®¢ëå ®¯¥à æ¨©
MACRO MpcSrvCarryGenReport ( ServiceIDLocal, OperKindLocal )
   var RS, cmd;
       ServiceID = ServiceIDLocal;
       OpKind = OperKindLocal;

   cmd = RSDCommand( " select T_DOCID from dprcsrvdoc_dbt " +
        " where t_serviceid = ? ") ; 
   cmd.addParam( "", RSDBP_IN, ServiceIDLocal );
   cmd.execute();
   
   RS = TRsbDataSet(cmd);
   while (RS.movenext() )
     MpcCarryGenReport(RS.docid, OperKindLocal);
   end; 
END;

