/*ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป*/
/*บ           €ขโฎฌ โจงจเฎข ญญ ๏ ก ญชฎขแช ๏ แจแโฅฌ  RS-Bank v5.1              บ*/
/*บ               Copyright (c) R-Style Software Lab 2001-2004                บ*/
/*บ                                                                           บ*/
/*บ ฌ๏ ไ ฉซ      or_worm.mac                                                 บ*/
/*บ                                                                           บ*/
/*บ ฏจแ ญจฅ      ”ใญชๆจจ คซ๏ เ กฎโ๋ แ ไ ฉซ ฌจ ญ  โฅเฌจญ ซฅ                   บ*/
/*บ                                                                           บ*/
/*บ เฎฃเ ฌฌจแโ   ใฅข ‘..                                                   บ*/
/*บ                                                                           บ*/
/*บ ‘ฎงค ญ        21.08.2003                                                  บ*/
/*บ                                                                           บ*/
/*ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ*/

/* เฎขฅเช  ขฅเแจจ จญแโเใฌฅญโ  ญ  โฅเฌจญ ซฅ */
macro GetVerInstr(_FileName:string)

  FILE VerInstrFileTerm() txt;  
  var RetValue:string  = "";
  var FlagComm:bool = FALSE;
  var stat    :bool    = TRUE ;

  if( ExistFile(toANSI(_FileName)) )
      if( Open(VerInstrFileTerm, _FileName, "lcansi") )
          while( stat AND Next(VerInstrFileTerm) )

              if( FlagComm AND (Trim(VerInstrFileTerm.Str)) )
                  RetValue = VerInstrFileTerm.Str;
                  stat = FALSE;
              end;

              if( Trim(VerInstrFileTerm.Str) == "/*" )
                  FlagComm = TRUE;
              end;
          end;
      end;
  end;
  return RetValue;

end; /* GetVerInstr */
//ชฎเเฅชโจเฎขช  คฅญฅฃ คซ๏ 5.50
macro CorrectMoney(m):double
    return Double(m);     
end;


/**/