/*
 $Name: rsmexectest.mac
 $Module: ЦБ
 $Description: Разное
*/

import BankInter, iabsr, iabsdw, RsbDataset, rcw;

const MemOrder                = 0;
const CashOrder               = 1;
const PaymentOrder            = 2;
const PaymentOrderBB          = 3;
const CurrencyPaymentOrder    = 4;
const CurrencyPaymentOrderBB  = 5;
const CurrencyBuyOrder        = 6;
const CurrencySaleOrder       = 7;
const CurrencyConversionOrder = 8;

var ErrorMessage = "";

macro GetCurrencyCodeFromAccount(Account : string)
       
    var FICode = "";
    
    FICode = SubStr(Account, 6, 3);
    
    return int(FICode);
end;

macro getObject(obj, className)
    var PropID;

    if (not IsEqClass(className, obj))
        ErrorMessage = "Ошибка при создании объекта класса " + className + ". ";

        if (ValType(GenClassName(obj)) != V_UNDEF)
            
            if (GenPropID(obj, "what") >= 0)
                ErrorMessage = className + ": " + obj.what;                
            end;
        end; 
          
        RunError(ErrorMessage);    
    end;

    return obj;
end;

macro str2bool(str)
   if (strUpr(str) == "X")
      return true;
   end;
   if (strUpr(str) == "TRUE")
      return true;
   end;

   return false;
end;

macro GetBankCount()
   var ds = TRsbDataSet("SELECT count(*) BankCount FROM dparty_dbt t, dpartcode_dbt " +
"partcode, dpartyown_dbt partyown WHERE (partyown.t_PartyID=t.t_PartyID AND partyown.t_PartyKind=2 AND " +
"partyown.t_SubKind=0 AND nvl(t.t_Locked, 'w') <> 'X' AND t.t_LegalForm=1 AND t.t_PartyID=partcode.t_PartyID(+) AND " +
"partcode.t_CodeKind(+)=3)");
   if (ds.MoveNext())
        return ds.BankCount;
   end;

   return -1;
end;

macro getDocKind(flowDirection)
   var fd = int(flowDirection);
   if (fd == 2)
      return 430;
   elif (fd == 1)
      return 440;
   end;
end;

macro TestRead(Account, Chapter, dateBegin, dateEnd)
    var IABS;       
    var ICurBank;   
    var ICurrency;  
    var IAccount;   
    var IExtract; 

    var CurrencyCode = GetCurrencyCodeFromAccount(Account); 
    
    IABS       = getObject(ABSGetInterface(), "IABS");
    ICurBank   = getObject(IABS.GetCurrentBank(), "IABSCurrentBank");
    ICurrency  = getObject(IABS.GetCurrencyByISO(CurrencyCode), "IABSCurrency");
    IAccount   = getObject(ICurBank.getAccount(Account, ICurrency, Chapter), "IABSInBankAccount");
    IExtract   = getObject(IAccount.GetExtract(date(dateBegin), date(dateEnd)), "IABSAccountExtract");

    return IExtract;

    OnError(Error)
       ErrorMessage = ErrorMessage;
       println(ErrorMessage);
       return ErrorMessage;
end;

macro TestReadBnkRepl()
    var iAbs;
    var lstBank; //IABSObjectList 
    
    iAbs = getObject(ABSGetInterface(), "IABS");
    lstBank = getObject(iAbs.GetBankList(), "IABSObjectList");

    return lstBank;

    OnError(Error)
       ErrorMessage = ErrorMessage;
       println(ErrorMessage);
       return ErrorMessage;
end;

private macro findCurrency(codeCurr)
  var FI = TBFile("fininstr.dbt", "w", 1);
  FI.rec.FI_CODE = codeCurr;
  if (not FI.getEQ())
     ErrorMessage = "Ошибка: Невозможно найти валюту с кодом '" + codeCurr + "'.";
     RunError(ErrorMessage);
  end;
end;

private macro checkCurrency(codeCurr)
   if ((not codeCurr) or (codeCurr == ""))
      ErrorMessage = "Ошибка: Не задан код валюты.";
      RunError(ErrorMessage);
   end;

   findCurrency(codeCurr);
 
end;

/*
macro TestWrite(DocKind, OriginalSystem, OriginalSystemID)
    var IABSDirectWrite;
    var IABSDWMetaClass;
    var IABSDWOrder;
    var ParmValue;
    var bResult = false;
    var CashSym;

    var oABS        = ABSGetInterface();
    var CurrentBank = oABS.GetCurrentBank();
    
    IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");
    
    
    DocKind = int(DocKind);

    if   (DocKind == MemOrder)
        
        IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWMemorialOrder"), "IABSMetaClass");
        IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWMemorialOrder");
        
        GetParm(3,  IABSDWOrder.Payer.Bank.BIC);
        
        if (strlen(IABSDWOrder.Payer.Bank.BIC) == 0)
            GetParm(4,  IABSDWOrder.Payer.Bank.SWIFT);
        end;

        GetParm(5,  IABSDWOrder.Payer.Number);
        
        GetParm(6,  IABSDWOrder.Payer.Client.Id);

        GetParm(7,  IABSDWOrder.Receiver.Bank.BIC);
        
        if (strlen(IABSDWOrder.Receiver.Bank.BIC) == 0)
            GetParm(8,  IABSDWOrder.Receiver.Bank.SWIFT);
        end;
        
        GetParm(9,  IABSDWOrder.Receiver.Number);
        
        GetParm(10, IABSDWOrder.Receiver.Client.Id);
        
        GetParm(11,  ParmValue);
        IABSDWOrder.Amount = money(ParmValue);
        
        GetParm(12,  ParmValue);
        checkCurrency(ParmValue);
        IABSDWOrder.Currency.ISO = int(ParmValue);
        
        GetParm(13, ParmValue);
        IABSDWOrder.Date = date(ParmValue);
                        
        GetParm(14, ParmValue);
        IABSDWOrder.Oper = int(ParmValue);
        
        GetParm(15, IABSDWOrder.Number);        
        
        GetParm(16, IABSDWOrder.Ground); 
        
        GetParm(17, ParmValue);
        IABSDWOrder.DefOperationKind = int(ParmValue);
               
        GetParm(18, ParmValue);
        IABSDWOrder.PackNumber = int(ParmValue);
        
        GetParm(19, ParmValue);
        IABSDWOrder.Chapter = int(ParmValue);
        
        GetParm(20, ParmValue);
        IABSDWOrder.Origin = int(ParmValue);
        
        // Вставка документа
        bResult = IABSDWOrder.insert();
        
    elif (DocKind == CashOrder)
    
	 IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCashOrder"), "IABSMetaClass");
        IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCashOrder");

        GetParm(41, ParmValue);
        IABSDWOrder.Origin = int(ParmValue);
        
        GetParm(3,  IABSDWOrder.Payer.Bank.BIC);
        
        if (strlen(IABSDWOrder.Payer.Bank.BIC) == 0)
            GetParm(4,  IABSDWOrder.Payer.Bank.SWIFT);
        end;
                
        GetParm(5,  IABSDWOrder.Payer.Number);
        
        GetParm(6,  IABSDWOrder.Payer.Client.Id);
        
        GetParm(7,  IABSDWOrder.Receiver.Bank.BIC);
        
        if (strlen(IABSDWOrder.Receiver.Bank.BIC) == 0)
            GetParm(8,  IABSDWOrder.Receiver.Bank.SWIFT);
        end;
        
        GetParm(9,  IABSDWOrder.Receiver.Number);
        
        GetParm(10, IABSDWOrder.Receiver.Client.Id);        
        
        GetParm(11,  ParmValue);
        IABSDWOrder.Amount = money(ParmValue);
        
        GetParm(12,  ParmValue);
        checkCurrency(ParmValue);
        IABSDWOrder.Currency.ISO = int(ParmValue);
                
        GetParm(13, ParmValue);
        IABSDWOrder.Date = date(ParmValue);
                
        GetParm(14, ParmValue);
        IABSDWOrder.Oper = int(ParmValue);   
        
        GetParm(15, IABSDWOrder.Number);
               
        GetParm(16, IABSDWOrder.Ground);                
        
        GetParm(17, ParmValue);
        IABSDWOrder.DefOperationKind = int(ParmValue);
        
        GetParm(18, ParmValue);
        IABSDWOrder.flowDirection = int(ParmValue);
        
        GetParm(19, ParmValue);
        IABSDWOrder.InSymbol.symbol = ParmValue;
        
        GetParm(20, ParmValue);
        IABSDWOrder.OutSymbol.symbol = ParmValue;
        
        GetParm(21, IABSDWOrder.Payer.Client.Name);
        
        GetParm(22, IABSDWOrder.Payer.Client.INN);
        
        GetParm(23, IABSDWOrder.Payer.Bank.Name);
        
        GetParm(24, IABSDWOrder.Receiver.Client.Name);
        
        GetParm(25, IABSDWOrder.Receiver.Client.INN);
        
        GetParm(26, IABSDWOrder.Receiver.Bank.Name);
        
        
        // Вставка документа
        bResult = IABSDWOrder.insert();
        
    elif ((DocKind == PaymentOrder) or (DocKind == PaymentOrderBB))
    
	 IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWPaymentOrder"), "IABSMetaClass");
        IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWPaymentOrder");

        GetParm(50, ParmValue);
        IABSDWOrder.Origin = int(ParmValue);
        
        GetParm(3,  IABSDWOrder.Payer.Bank.BIC);
        
        if (strlen(IABSDWOrder.Payer.Bank.BIC) == 0)
            GetParm(4,  IABSDWOrder.Payer.Bank.SWIFT);
        end;
        
        GetParm(5,  IABSDWOrder.Payer.Number);
        
        GetParm(6,  IABSDWOrder.Payer.Client.Id);
        
        GetParm(7,  IABSDWOrder.Receiver.Bank.BIC);
        
        if (strlen(IABSDWOrder.Receiver.Bank.BIC) == 0)
            GetParm(8,  IABSDWOrder.Receiver.Bank.SWIFT);
        end;
        
        GetParm(9,  IABSDWOrder.Receiver.Number);
        
        GetParm(10,  IABSDWOrder.Receiver.Client.Id);        
        
        GetParm(11,  ParmValue);
        IABSDWOrder.Sum = money(ParmValue);
        
        GetParm(12, ParmValue);
        IABSDWOrder.Date = date(ParmValue);
        
        GetParm(13, ParmValue);
        IABSDWOrder.bankDate = date(ParmValue);
                
        GetParm(14, ParmValue);
        IABSDWOrder.paymentDate = date(ParmValue);
                
        GetParm(15, ParmValue);
        IABSDWOrder.Oper = int(ParmValue);
        
        GetParm(16, IABSDWOrder.Number);
        
        GetParm(17, IABSDWOrder.Ground);  
        
        GetParm(18, IABSDWOrder.OperationKind);
        
        GetParm(19, IABSDWOrder.Payer.Client.Name);
        
        GetParm(20, IABSDWOrder.Payer.Client.INN);
        
        GetParm(21, IABSDWOrder.Payer.Bank.Name);
        
        GetParm(22, IABSDWOrder.Receiver.Client.Name);
        
        GetParm(23, IABSDWOrder.Receiver.Client.INN);
        
        GetParm(24, IABSDWOrder.Receiver.Bank.Name);
        
        GetParm(25, ParmValue);
        IABSDWOrder.paymentPriority = int(ParmValue);
        
        GetParm(26, IABSDWOrder.taxPayerStatus);
        
        GetParm(27, IABSDWOrder.BudgetCode);
        
        GetParm(28, IABSDWOrder.taxPaymentGround);
        
        GetParm(29, IABSDWOrder.taxPeriod);
        
        GetParm(30, IABSDWOrder.taxDocNumber);
        
        GetParm(31, IABSDWOrder.taxDocDate);
        
        GetParm(32, IABSDWOrder.taxPaymentType);
        
        GetParm(33, IABSDWOrder.OKATO);
        // SCR 133676 
        GetParm(34, ParmValue);
        IABSDWOrder.DefOperationKind = int(ParmValue);
        // SCR 133676 
        GetParm(35, ParmValue);
        IABSDWOrder.valueDate = date(ParmValue);


        
        // Вставка документа
        if (DocKind == PaymentOrder)
            bResult = IABSDWOrder.insert();
        else
            bResult = IABSDWOrder.insertForBB();
        end;
                
    elif ((DocKind == CurrencyPaymentOrder) or (DocKind == CurrencyPaymentOrderBB))
    
	 IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCurrencyPaymentOrder"), "IABSMetaClass");
        IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCurrencyPaymentOrder");

        GetParm(51, ParmValue);
        IABSDWOrder.Origin = int(ParmValue);

        GetParm(52, ParmValue);
        IABSDWOrder.paymentDate = date(ParmValue);
        
        GetParm(3,  IABSDWOrder.Payer.Bank.BIC);

        if (strlen(IABSDWOrder.Payer.Bank.BIC) == 0)
            GetParm(4,  IABSDWOrder.Payer.Bank.SWIFT);
        end;

        GetParm(5,  IABSDWOrder.Payer.Number);
        
        GetParm(6,  IABSDWOrder.Payer.Client.Id);
        
        GetParm(7,  IABSDWOrder.Receiver.Bank.BIC);
        
        if (strlen(IABSDWOrder.Receiver.Bank.BIC) == 0)
            GetParm(8,  IABSDWOrder.Receiver.Bank.SWIFT);
        end;
                
        GetParm(9,  IABSDWOrder.Receiver.Number);
        
        GetParm(10,  IABSDWOrder.Receiver.Client.Id);        
        
        GetParm(11,  ParmValue);
        IABSDWOrder.Sum = money(ParmValue);
        
        GetParm(12, ParmValue);
        checkCurrency(ParmValue);
        IABSDWOrder.Currency.ISO = int(ParmValue);

        GetParm(13, ParmValue);
        checkCurrency(ParmValue);
        IABSDWOrder.Payer.Currency.ISO = int(ParmValue);
           
        GetParm(14, ParmValue);
        checkCurrency(ParmValue);
        IABSDWOrder.Receiver.Currency.ISO = int(ParmValue);
                       
        GetParm(15, ParmValue);
        IABSDWOrder.Date = date(ParmValue);
        
        GetParm(16, ParmValue);
        IABSDWOrder.BankDate = date(ParmValue);
                       
        GetParm(17, ParmValue);
        IABSDWOrder.ValueDate = date(ParmValue);
                
        GetParm(18, ParmValue);
        IABSDWOrder.Oper = int(ParmValue);
        
        GetParm(19, IABSDWOrder.Number);
        
        GetParm(20, IABSDWOrder.Ground);                
        
        GetParm(21, IABSDWOrder.Payer.Client.Name);
        
        GetParm(22, IABSDWOrder.Payer.Client.INN);
        
        GetParm(23, IABSDWOrder.Payer.Bank.Name);
        
        GetParm(24, IABSDWOrder.Receiver.Client.Name);
        
        GetParm(25, IABSDWOrder.Receiver.Client.INN);
        
        GetParm(26, IABSDWOrder.Receiver.Bank.Name);
                       
        GetParm(27, IABSDWOrder.intermediaryBank.Name);
        
        GetParm(28, IABSDWOrder.intermediaryBank.ID);
        
        GetParm(29, IABSDWOrder.intermediaryBank.BIC);
        
        if (strlen(IABSDWOrder.intermediaryBank.BIC) == 0)
            GetParm(30, IABSDWOrder.intermediaryBank.SWIFT);   
        end;

        GetParm(31, ParmValue);
        IABSDWOrder.IsBankChargesOur = str2bool(ParmValue);

        GetParm(32, ParmValue);
        IABSDWOrder.ComissCharges = int(ParmValue);

        GetParm(33, ParmValue);
        IABSDWOrder.IsCorrespChargesOur = str2bool(ParmValue);

        // SCR 133676 
        /*GetParm(34, ParmValue);
        IABSDWOrder.OperationKind = int(ParmValue);*/

        //GetParm(35, ParmValue);
        GetParm(34, ParmValue);
        IABSDWOrder.DefOperationKind = int(ParmValue);
        
        // Вставка документа
        if (DocKind == CurrencyPaymentOrder)
            bResult = IABSDWOrder.insert();
        else
            bResult = IABSDWOrder.insertForBB();
        end;     
        
    elif ((DocKind == CurrencyBuyOrder) or (DocKind == CurrencySaleOrder) or (DocKind == CurrencyConversionOrder))
    
        if   (DocKind == CurrencyBuyOrder)
            IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCurrencyBuyOrder"), "IABSMetaClass");
            IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCurrencyBuyOrder");
            GetParm(47, ParmValue);
            IABSDWOrder.Origin = int(ParmValue);
        elif (DocKind == CurrencySaleOrder)
            IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCurrencySaleOrder"), "IABSMetaClass");
            IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCurrencySaleOrder");
            GetParm(47, ParmValue);
            IABSDWOrder.Origin = int(ParmValue);
        elif (DocKind == CurrencyConversionOrder) 
            IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCurrencyConversionOrder"), "IABSMetaClass");
            IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCurrencyConversionOrder");
            GetParm(46, ParmValue);
            IABSDWOrder.Origin = int(ParmValue);

            GetParm(47, ParmValue);
            IABSDWOrder.IsSale = str2bool(ParmValue);

        end;              
        
        GetParm(3,  IABSDWOrder.Payer.Bank.BIC);
        
        if (strlen(IABSDWOrder.Payer.Bank.BIC) == 0)
            GetParm(4,  IABSDWOrder.Payer.Bank.SWIFT);
        end;
                
        GetParm(5,  IABSDWOrder.Payer.Number);
        
        GetParm(6,  IABSDWOrder.Payer.Client.Id);
        
        GetParm(7,  IABSDWOrder.Receiver.Bank.BIC);
        
        if (strlen(IABSDWOrder.Payer.Bank.BIC) == 0)
            GetParm(8,  IABSDWOrder.Receiver.Bank.SWIFT);
        end;
                
        GetParm(9,  IABSDWOrder.Receiver.Number);
        
        GetParm(10, IABSDWOrder.Receiver.Client.Id);        
        
        GetParm(11,  ParmValue);
        IABSDWOrder.Sum = money(ParmValue);
        
        GetParm(12, ParmValue);
        checkCurrency(ParmValue);
        IABSDWOrder.Currency.ISO = int(ParmValue);
        
        GetParm(13, ParmValue);
        IABSDWOrder.Payer.Currency.ISO = int(ParmValue);

        GetParm(14, ParmValue);
        IABSDWOrder.Receiver.Currency.ISO = int(ParmValue);

	if (DocKind != CurrencyConversionOrder) 
           GetParm(15, ParmValue);        
           IABSDWOrder.Rate = double(ParmValue);
        end;
        
        GetParm(16, IABSDWOrder.Date);
        IABSDWOrder.Date = date(ParmValue);
                
        GetParm(17, ParmValue); 
        IABSDWOrder.BankDate = date(ParmValue);
               
        GetParm(18, ParmValue);        
        IABSDWOrder.ValueDate = date(ParmValue);
        
        GetParm(19, ParmValue);
        IABSDWOrder.Oper = int(ParmValue);
        
        GetParm(20, IABSDWOrder.Number);
        
        if (DocKind != CurrencySaleOrder)
           GetParm(21, IABSDWOrder.Ground);
        end;
        
        GetParm(22, IABSDWOrder.GroundCode);            
        
        GetParm(23, ParmValue);
        IABSDWOrder.DefOperationKind = int(ParmValue);
        
        GetParm(24, IABSDWOrder.Payer.Client.Name);
        
        GetParm(25, IABSDWOrder.Payer.Client.INN);
       
        GetParm(26, IABSDWOrder.Payer.Bank.Name);
        
        GetParm(27, IABSDWOrder.Receiver.Client.Name);
        
        GetParm(28, IABSDWOrder.Receiver.Client.INN);
        
        GetParm(29, IABSDWOrder.Receiver.Bank.Name);
        
	 if   ((DocKind == CurrencyBuyOrder) or (DocKind == CurrencySaleOrder))
	
            GetParm(30, ParmValue);
            IABSDWOrder.nationalSum = money(ParmValue);
            
            GetParm(32, ParmValue);
            IABSDWOrder.RateType = int(ParmValue);

        
        elif (DocKind == CurrencyConversionOrder) 

            GetParm(30, ParmValue);
            IABSDWOrder.convSum = money(ParmValue);
            
            GetParm(31, ParmValue);
            checkCurrency(ParmValue);
            IABSDWOrder.convCurrency.ISO = int(ParmValue);
        
        end;
        
        // Вставка документа
        bResult = IABSDWOrder.insert();     
               
    end;
    
    // проверка результата выполнения вставки
    if (ValType(bResult) != V_BOOL)        
        
        ErrorMessage = "Ошибка при вставке документа ";

        if (ValType(GenClassName(bResult)) != V_UNDEF)
            
            if (GenPropID(bResult, "what") >= 0)
                ErrorMessage = ErrorMessage + ": " + bResult.what;                
            end;
        end; 
          
        RunError(ErrorMessage);    
    else
        
        if (bResult == false)
            ErrorMessage = "Ошибка при вставке документа ";
            RunError(ErrorMessage);   
        end;
        
    end;
    
    return IABSDWOrder;    
    
    OnError(Error)
        println(ErrorMessage);
        return ErrorMessage;
end;                     
*/
/*

//Мемориальный ордер
//TestWrite("0", "TestSystem", "TestSystemID", "044525986", "", "40702810200000000003", "CC0001000004", "044525986", "", "40702810000000000012", "CC0001000017", 
//          "15.15", "810", "04.01.2008", "100", "1515", "Основание", "4001", "1", "1", "1");


//Кассовый ордер
//msgbox(TestWrite("1", "asdfsa", "1231002", 
//          "", "", "20202810777000000001", "", "", "", "40704810077000000001", "", 
//          "15.15", "810", date(17,08,2010), "1112", "1002", "osnov", "4001", "2", "", " 40", 
//          "", "", "", "", "", ""));


//Рублевый платеж РКО и ББ
//TestWrite("2", "TestSystem", "TestSystemID", 
//          "044525986", "", "40702810200000000003", "CC0001000004", "044525986", "", "40702810000000000012", "CC0001000017",  
//          "15.15", "04.01.2008", "04.01.2008", "04.01.2008", "100", "1515", "Основание", "Э", 
//          "ООО \"Торговая компания \"Смайл\"", "0411017642", "", "СтрЮР", "1234567000", ""
//          "3", "", "", "taxGround", "", "", "", "", "OKATO");


//Валютный платеж РКО и ББ
//var obj = TestWrite("4", "TestSystem", "TestSystemID5", "", "", "20202840000000000003", "", "", "", "30101810200000000777", "",  
//         "15.15", "840", "840", "840", "01.11.2009", "01.11.2009", "01.11.2009", "1112", "1515", "Основание", 
//          "", "", "", "", "", "", 
//          "", "", "", "", 0, true, true, "" );

// Поручение на конверсию валюты
//TestWrite(CurrencyConversionOrder, "TestSystem", "TestSystemID", "044525986", "", "40702810200000000054", "CC0001000002", "044525986", "", "40702840200000000840", "CC0001000017",  
//          "15.15", "840", "810", "840", "25.05", "04.01.2008", "04.01.2008", "04.01.2008", "100", "1515", "Основание", "10", "",
//          "ООО \"Горно-Строй\"", "", "", "Получатель в ВУЗ банк", "", "", "400");
    
*/

//Валютный платеж РКО и ББ
/*
var obj = TestWrite("4", "aaa118", "aaa118", "044550001", "BANKRUMM", "40702840500020000001", "CC0001000013", "044550001", "BANKRUMM", "40702978700000000001", "2",  
         "5", "840", "840", "840", "01.02.2009", "01.02.2009", "01.02.2009", "1112", "130", "fghjj", 
         "Экспорт 1", "2323232323", "Bank1", "Bank1", "4261834590", "Bank1", 
         "", "", "", "", "true", "0", "", "4001" );
*/



macro RevokeDocument(DocID:string)
    var IABSDirectWrite;
    var bResult = false;
    var ErrorMessage;
    var doc:IABSDocument;
    var dw:IABSDirectWrite;
    var LongMessage = false;
    
    dw = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");
    doc = getObject(dw.GetDocument(DocID), "IABSDocument");

    bResult = doc.revoke();
    
    // проверка результата выполнения отзыва
    if (ValType(bResult) != V_BOOL)        
        
        ErrorMessage = "Ошибка при отзыве документа";

        if (ValType(GenClassName(bResult)) != V_UNDEF)
            
            if (GenPropID(bResult, "what") >= 0)
                ErrorMessage = ErrorMessage + ": " + bResult.what;                
            end;
        end; 
          
        LongMessage = true;  
        RunError(ErrorMessage);    
    end;
    
    return bResult;     
    
    OnError(Error)
        if(LongMessage == false)
         ErrorMessage = Error.Message;
        end;
        println(ErrorMessage);
        return ErrorMessage;
end;

/* привести строковый параметр к нужному типу (RsDataTypes)*/
macro convertParm(parm:string, type:integer)
   var b:bool;
   if (type == 0)
      return parm;
   elif (type == 5)
      return int(parm);
   elif (type == 20)
      return money(parm);
   elif (type == 7)
      return double(parm);
   elif (type == 10)
      if (StrUpr(trim(parm)) == "TRUE")
         return true;
      elif (StrUpr(trim(parm)) == "FALSE")
         return false;
      else
         b = parm;
         return b;
      end;
   elif (type == 11)
      return Date(parm);
   elif (type == 12)
      return Time(parm);
   end;

   /* дефолтное значение - строка (8)*/
   return parm;

end;

/********************************************************************************************************* 
 * Макрофункции создания DLM объектов. Имя макрофункции указывается в аттрибуте createMethod тега DLMObject
 * в файле dlm_ini.xml 
 **********************************************************************************************************/
/////////////////////////////////////////////////////////////////
MACRO CheckResult(obj, ClassType)
   if (ValType(obj) == V_STRING)
      ErrorMessage = obj;
      RunError(obj);
   end;

   if (IsEqClass("IABSError", obj))
      ErrorMessage = obj.what;
      RunError(obj.what);
   end;

   if ((ValType(obj) == V_UNDEF) OR (obj == null))
      ErrorMessage = "Ошибка создания экземпляра интерфейса " + ClassType;
      RunError(ErrorMessage);
   end;

   return obj;
END;
/////////////////////////////////////////////////////////////////
MACRO GetIABS()
   var absObj = CheckResult(getObject(ABSGetInterface(), "IABS"));

   return absObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetCurrentBank()
   var iabs = CheckResult(GetIABS());

   var retObj = CheckResult(iabs.GetCurrentBank());
   
   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetCurrencyByISO(iso)
   var iabs = CheckResult(GetIABS());
   var retObj = CheckResult(iabs.GetCurrencyByISO(iso));

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetBankByBIC(bic)
   var iabs = CheckResult(GetIABS());
   var retObj = CheckResult(iabs.GetBankByBIC(bic));

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetAccount(number, iso, chapter)
   var curBank = CheckResult(GetCurrentBank());
   var curr = CheckResult(GetCurrencyByISO(iso));

   var retObj = CheckResult(curBank.GetAccount(number, curr, chapter));

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetInBankCurrencyByISO(iso)
   var curBank = CheckResult(GetCurrentBank());

   var retObj = CheckResult(curBank.GetCurrencyByISO(iso));

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetCurrencyRateType(iso, id)
   var curr = CheckResult(GetInBankCurrencyByISO(iso));

   var retObj = CheckResult(curr.GetRateType(id));

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetRateTypeDominant()
   var curBank = CheckResult(GetCurrentBank());

   var retObj = CheckResult(curBank.GetRateTypeDominant());

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetVersionInfo()
   var o = CheckResult(getIABS());

   return o.VersionInfo;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetRateType(id)
   var curBank = CheckResult(GetCurrentBank());

   var retObj = CheckResult(curBank.GetRateType(id));

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetInBankClient(code)
   var curBank = CheckResult(GetCurrentBank());

   var retObj = CheckResult(curBank.GetClient(code));

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetDocument(ID)
   var curBank = CheckResult(GetCurrentBank());

   var retObj = CheckResult(curBank.GetDocument(ID));

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////
MACRO GetForWrite_MemorialOrder(OriginalSystem, OriginalSystemID)
    
   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWMemorialOrder"), "IABSMetaClass");
   var IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWMemorialOrder");

   return IABSDWOrder;

   OnError(Error)
      return ErrorMessage;
END;

/////////////////////////////////////////////////////////////////
MACRO GetForWrite_CashOrder(OriginalSystem, OriginalSystemID)
    
   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCashOrder"), "IABSMetaClass");
   var IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCashOrder");

   return IABSDWOrder;

   OnError(Error)
      return ErrorMessage;
END;

/////////////////////////////////////////////////////////////////
MACRO GetForWrite_PaymentOrder(OriginalSystem, OriginalSystemID)
    
   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWPaymentOrder"), "IABSMetaClass");
   var IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWPaymentOrder");

   return IABSDWOrder;

   OnError(Error)
      return ErrorMessage;
END;

/////////////////////////////////////////////////////////////////
MACRO GetForWrite_CurrencyPaymentOrder(OriginalSystem, OriginalSystemID)
    
   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCurrencyPaymentOrder"), "IABSMetaClass");
   var IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCurrencyPaymentOrder");

   return IABSDWOrder;

   OnError(Error)
      return ErrorMessage;
END;

/////////////////////////////////////////////////////////////////
MACRO GetForWrite_CurrBuyOrder(OriginalSystem, OriginalSystemID)
    
   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCurrencyBuyOrder"), "IABSMetaClass");
   var IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCurrencyBuyOrder");

   return IABSDWOrder;

   OnError(Error)
      return ErrorMessage;
END;

/////////////////////////////////////////////////////////////////
MACRO GetForWrite_CurrSaleOrder(OriginalSystem, OriginalSystemID)
    
   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCurrencySaleOrder"), "IABSMetaClass");
   var IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCurrencySaleOrder");

   return IABSDWOrder;

   OnError(Error)
      return ErrorMessage;
END;

/////////////////////////////////////////////////////////////////
MACRO GetForWrite_CurrConvOrder(OriginalSystem, OriginalSystemID)
    
   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWCurrencyConversionOrder"), "IABSMetaClass");
   var IABSDWOrder     = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWCurrencyConversionOrder");

   return IABSDWOrder;

   OnError(Error)
      return ErrorMessage;
END;

/////////////////////////////////////////////////////////////////
MACRO GetForWrite_BankOrder(OriginalSystem, OriginalSystemID)    

   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWBankOrder"), "IABSMetaClass");

   var IABSDWOrder = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWBankOrder");

   return IABSDWOrder;

   OnError(Error)
      return ErrorMessage;
END;

/////////////////////////////////////////////////////////////////
MACRO GetForWrite_BilFactura(OriginalSystem, OriginalSystemID)    

   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWBilFactura"), "IABSMetaClass");

   var IABSDWOrder = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWBilFactura");

 //  var IABSDWMetaClassLine = getObject(IABSDirectWrite.GetMetaClass("IABSDWBilFacturaLine"), "IABSMetaClass");

 //  var FacturaLine = getObject(IABSDirectWrite.CreateDocument("", "", IABSDWMetaClassLine), "IABSDWBilFacturaLine");

 //  IABSDWOrder.FacturaLines[0] = FacturaLine;

   return IABSDWOrder;

   OnError(Error)
      return ErrorMessage;
END;

/////////////////////////////////////////////////////////////////
MACRO GetForWrite_Accept(OriginalSystem, OriginalSystemID)    

   var IABSDirectWrite = getObject(ABSDirectWriteGetInterface(), "IABSDirectWrite");

   var IABSDWMetaClass = getObject(IABSDirectWrite.GetMetaClass("IABSDWAccept"), "IABSMetaClass");

   var IABSDWAccept = getObject(IABSDirectWrite.CreateDocument(OriginalSystem, OriginalSystemID, IABSDWMetaClass), "IABSDWAccept");

   return IABSDWAccept;

   OnError(Error)
      return ErrorMessage;
END;
/////////////////////////////////////////////////////////////////////
MACRO GetBalanceAccount(code, planID, chapter, isCurrency)

   var curBank = CheckResult(GetCurrentBank());
   var retObj = CheckResult(curBank.GetBalanceAccount(code, planID, chapter, isCurrency));

   return retObj;

   OnError(Error)
      return ErrorMessage;
END;

