import sfcomcat;

private record SfContrRec ("sfcontr.dbt");
private record SfConComRec ("sfconcom.dbt");

macro SfGetCatAccount( SfContr, FIID_CommSum, CatCode, SfConCom, IsForMacro, AccFIID )

  var SfComPD : SfComPrimDoc;
  var SfConComPD : SfConComPrimDoc;
  var Account:string;
  var FIID = -1;

  const PlusNDS_CatCode  = "+„‘";
  const MinusNDS_CatCode = "-„‘";

  if( (IsForMacro != NULL) AND (IsForMacro == true) )
    copy( SfContrRec, SfContr );
    if( SfConCom != NULL )
      copy( SfConComRec, SfConCom );
    end;
  else
    setbuff( SfContrRec, SfContr );
    if( SfConCom != NULL )
      setbuff( SfConComRec, SfConCom );
    end;
  end;

  if( (PlusNDS_CatCode == CatCode) OR (MinusNDS_CatCode == CatCode) )
    SfComPD = SfComPrimDoc( 87, SfContrRec );
    FIID = NATCUR;
    Account = SfComPD.FindAndOpenAccount( CatCode, NULL, FIID );
  else
    SfConComPD = SfConComPrimDoc( 83, SfConComRec, SfContrRec, FIID_CommSum );
    FIID = SfContrRec.PayFIID;
    Account = SfConComPD.FindAndOpenAccount( CatCode, NULL, FIID );
  end;
  
  if(Parmcount() >= 6)
    SetParm(5, FIID);
  end;

  return Account;
end;

