/*
  ’ á®¤¥à¦ é¨¥ ­ ç¨á«¥­­ë¥ ¨ ­¥ ­ ç¨á«¥­­ë¥ ª®¬¨áá¨¨
*/

import BankInter, "globals.mac", RSD;

private macro PrintFooter()
[ÀÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÙ];
end;

private macro PrintHeader()
[

            ’ á®¤¥à¦ é¨¥ ­ ç¨á«¥­­ë¥ ¨ ­¥ ­ ç¨á«¥­­ë¥ ª®¬¨áá¨¨];
[ÚÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ¿];
[³ ®¬¥à ’ ³ „ â  ’  ³ « â¥«ìé¨ª                                       ³ ®«ãç â¥«ì                                       ³ ˆ¤.      ³];
[ÃÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´];
end;

private macro PrintInvoice( rs : RsdRecordSet )

[³##########³##########³##################################################³##################################################³##########³] 
  ( rs.value( 0 ), string(rs.value( 1 )), rs.value( 2 ), rs.value( 3 ), rs.value( 4 ));
[³          ³          ³                                                  ³                                                  ³          ³];

end;

private macro MakeSqlQuery() : string

  var sqlString : string;

  sqlString = "SELECT " +
              "  sfi.t_DocNumber, " +
              "  sfi.t_InvoiceDate, " +
              "  sfi.t_PayerName, " +
              "  sfi.t_BeneName, " +
              "  sfi.t_InvoiceID " +
              "FROM dsfinv_dbt sfi " +
              "WHERE sfi.t_InvoiceID IN ( " +
              
              "  SELECT DISTINCT d1.t_InvoiceID " +
              "  FROM dsfinv_dbt d1 " +
              "  JOIN dsfdefcom_dbt d2 ON (d1.t_InvoiceID = d2.t_InvoiceID) " +
              "  WHERE d1.t_IsIncluded = 'X' " +
              "  AND (d2.t_IsIncluded <> 'X' OR d2.t_IsIncluded IS NULL) " +
              
              ") " +
              "ORDER BY sfi.t_DocNumber ";

  return sqlString;        

end;

private macro PrintContext()

  var strSql : string;
  var cmd : RsdCommand;
  var rs : RsdRecordset;
  
  strSql = MakeSqlQuery();  

  cmd = RsdCommand( strSql );
  cmd.NullConversion = true;
  rs = RsdRecordset( cmd );

  while( rs.MoveNext())
    PrintInvoice( rs );
  end;

end;

macro PrintReport( outname )
  if( valtype( outname ) == V_STRING )
    SetOutput( outname, true );
  end;

  PrintHeader();

  PrintContext();

  PrintFooter();
  if( valtype( outname ) == V_STRING )
    SetOutput( null, true );
  end;
end;