import rcw;
import rsd;
import rsbdataset;


class TWsLlclsval(_element : integer, _code : string, _name : string, _classificator : integer)
  var Element       = _element;
  var Code          = _code;
  var Name          = _name;
  var Classificator = _classificator;
end;

MACRO GetListLlclsval(Classificator:integer, Mode)
   var p;

   if(Classificator <= 0)
     RunError("Не задан вид классификатора");
   end;
   
   var result = TArray();
   var query = " SELECT llv.t_element, llv.t_code, llv.t_name " +
               "   FROM dllvalues_dbt llv, dllclsval_dbt cls "
               "  WHERE llv.t_list = cls.t_list "
               "    AND llv.t_element = cls.t_element "
               "    AND cls.t_classificator = " + string(Classificator) +
               " ORDER BY llv.t_element";

   var ds = TRsbDataSet(query, RSDVAL_CLIENT, RSDVAL_STATIC);

   while (ds.MoveNext())
      p = TWsLlclsval(ds.Element, ds.Code, ds.Name, Classificator);

      result.value(result.Size) = p;
   end;

   return result;
END;

/* Создание объекта TWsLlclsval через параметры */
macro CreatellClassifFromParam
(
  Element, 
  Code,
  Name,
  Classificator
)
  var llClassifItem : TWsLlclsval;

  llClassifItem.Element  = Element;
  llClassifItem.Code     = Code;
  llClassifItem.Name     = Name;
  llClassifItem.Classificator = Classificator;

  return llClassifItem;
end;

/* Создание объекта TWsLlclsval из базы */
macro CreatellClassifFromAppServ(List, Element, Classificator)
  var p;

  var query = "select llv.* from dllvalues_dbt llv, dllclsval_dbt cls where llv.t_List = " + string(List) + " AND llv.t_Element = " + string(Element) + " AND cls.t_classificator = " + string(Classificator);

  var ds = TRsbDataSet(query, RSDVAL_CLIENT, RSDVAL_STATIC);
                      
  if (ds.MoveNext())
    p = TWsLlclsval();

    p.Element       = Element;
    p.Code    = ds.T_Code;
    p.Name    = ds.T_Name;
    p.Classificator = Classificator;
  else
    return null;
  end;

  return p;
end;             

macro LookUp( Classificator,
              sub                 : string,
              listLen             : integer):TArray

  var result = TArray();
  var p;

  var query = "select llv.* from dllvalues_dbt llv, dllclsval_dbt cls where llv.t_list = cls.t_list AND llv.t_element = cls.t_element and cls.t_classificator = " + string(Classificator) + " AND llv.t_Element ";

  query = query + " LIKE LOWER ('%' || ? || '%') ";

  if( listLen != 0 )

    query = query + " AND ROWNUM < " + string(listLen);

  end;

  var cmd = RSDCommand(query);
  
  cmd.addParam( "", RSDBP_IN, sub );
      
  cmd.NullConversion = true;
  
  cmd.Execute();

  var ds = TRsbDataSet( cmd );

  while (ds.moveNext())

    p = TWsLlclsval();

    p.Element = ds.T_Element;
    p.Code    = ds.T_Code;
    p.Name    = ds.T_Name;
    p.Classificator = Classificator;

    result.value(result.Size) = p;

  end;

  return result;

end; 
