/*
$Name:        ws_party_lib.mac
$Module:      Ядро ГКБО
$Description: Классы макроса реализации сервисов получения данных о клиентах
*/

/* Атрибуты субъекта (для скроллинга) */
class TWsGenericParty
  VAR Code            :string;   // Код субъекта заданного вида
  VAR LegalForm       :integer;  // Вид субъекта
  var Name            :string;   // Полное наименование субъекта 
  var ShortName       :string;
  var Name_           :string;   // Наименование субъекта заданного вида
  var Id              :integer;  // Идентификатор субъекта
  var ProductCount    :integer;
  var Changed         :date;
  var LastChangedDate :date;     // Дата последнего изменения
  var LastChangedTime :time;     // Время последнего изменения
end;

// Класс объекта входного параметра сервиса получения списка субъектов.
class TInputParamGetPartyList
  var ListKind  :integer; // Вид списка субъектов	
  var CodeKind  :integer;	// Вид кода субъектов для отображения в списке субъектов.	
  var NameKind  :integer;	// Вид наименования субъектов для отображения в списке субъектов.	
  var PartyID   :integer;	// Идентификатор субъекта, выбранного (установленного ранее) в виджете.	Если задан, то сервис должен вернуть ту страницу данных, на которой отображается указанный субъект.
  var PageIndex :integer;	// Номер страницы	
  var PageSize  :integer;	// Размер страницы, количество строк на странице	
end;

// Класс объекта выходного параметра сервиса получения списка субъектов.
class TOutputParamGetPartyList
  var PartyList;          // Array<TPartyListItem>		Список субъектов.	
  var ListTitle	:string;  //	dpartylst_dbt.t_listtitle	Наименование вида списка субъектов ListKind	
  var ItemCount	:integer; //	Общее количество субъектов попадающих под условия выборки.	Необходимо для механизма паджинации.
  var PageIndex	:integer; //	Номер страницы отображаемой в скроллинге субъектов. Вернуть номер страницы, на которую приходится местоположение субъекта с ид. PartyID, переданного во входном параметре сервиса. Если PartyID не задан, то номер страницы PageIndex, переданного во входном параметре сервиса	Необходимо для механизма паджинации.
end;

/* Атрибуты физического лица */
class TWsPersn
  var LastName : string; /* Фамилия. */
  var FirstName : string; /* Имя */
  var Patronymic : string; /* Отчество */
  var Action : string; /* Действие. */
  var BirthDate : date; /* Дата рождения */
  var BirthPlace : string; /* Место рождения */
  var Male : integer; /* Пол. */
  var Ethnos : string; /* Национальность */
  var IsEmployer : bool; /* Признак частного предпринимателя. */
  var OKPO : string; /* ОКПО */
  var LicenceNumber : string; /* Номер лицензии для част. предприн-ля */
  var LicenceDate : date; /* Дата выдачи лицензии */
  var RegionBorn : string; /* Код региона места рождения. */
  var RaionBorn : string; /* Район места рождения */
  var PlaceBorn : string; /* Населенный пункт места рождения */
  var PlaceWork : string; /* Место работы и должность */
  var DeathDate : date; /* Дата смерти (окончания обслуживания) */
  var IsGroupAuthor : bool; /* Признак наличия генеральной доверенности. По умолчанию false. */
  var IsGroupwil : bool; /* Признак наличия группового завещания. По умолчанию false. */
  var PensCardNumber : string; /* Номер пенсионного удостоверения */
  var PensCardDate : date; /* Дата выдачи пенсионного удостоверения */
  var IsNotResident : bool; /* Признак нерезидентности. */
  var NRCountry : string; /* Код страны нерезидента */
  var IsOffshoreResident : bool; /* Признак резидента оффшорной зоны. */
  var SectionPeople : integer; /* Категория населения. */
  var IsLiterate : bool; /* Признак неграмотности. По умолчанию false. */
  var IsSpecialAccess : bool; /* Признак специального доступа к клиенту. По умолчанию false. */
  var IsInterRelated : bool; /* Признак взаимосвязанного клиента. По умолчанию false. */
  var TaxInstitution : integer; /* Налоговая инспекция */
  var TaxRegDate : date; /* Дата регистрации в налог.инспекции */
  var SetAccSearchAlg : integer; /* Алгоритм поиска СПИ: Брать или не брать СПИ из СПИ субъекта. */
  var UserField1      : string; /* Поле пользователя 1 */
  var UserField2      : string; /* Поле пользователя 2 */
  var UserField3      : string; /* Поле пользователя 3 */
  var UserField4      : string; /* Поле пользователя 4 */
  var SysType         : string; /* Системные  */
  var UserType        : string; /* Пользовательские типы */
  var lawSubject      : string; /* Cубъект права */
  var IsLocked        : integer; /*Признак закрытого субъекта*/
end;

/* Атрибуты юридического лица */
class TWsInst
  var ShortName : string; /* Сокращенное наименование */
  var FullName : string; /* Наименование. */
  var Action : string; /* Действие. */
  var IsNotResident : bool; /* Признак нерезидентности. */
  var NRCountry : string; /* Код страны нерезидента */
  var IsOffshoreResident : bool; /* Признак резидента оффшорной зоны. */
  var SuperiorID : integer; /* Идентификатор вышестоящей или объемлющей организации */
  var TaxInstitution : integer; /* Налоговая инспекция */
  var TaxRegDate : date; /* Дата регистрации в налог.инспекции */
  var SetAccSearchAlg : integer; /* Алгоритм поиска СПИ: Брать или не брать СПИ из СПИ субъекта. */
  var OKPO : string; /* ОКПО */
  var UserField1 : string; /* Поле пользователя 1. */
  var UserField2 : string; /* Поле пользователя 2. */
  var UserField3 : string; /* Поле пользователя 3. */
  var UserField4 : string; /* Поле пользователя 4. */
  var SysType         : string; /* Системные  */
  var UserType        : string; /* Пользовательские типы */
  var lawSubject      : string; /* Cубъект права */
  var IsLocked        : integer; /*Признак закрытого субъекта*/
end;


/* Атрибуты клиента по виду обслуживния */
class TWsClient
  var ServKind : integer; /* Вид обслуживания */
  var Department : integer; /* Филиал, в котором обслуживается клиент.  */
  var StartDate : date; /* Дата начала обслуживания. */
  var FinishDate : date; /* Дата окончания обслуживания. */
  var OperNum : integer; /* Номер операциониста */
  var OperName : string; /* ФИО операциониста */
  var Action : string; /* Действие с видом обслуживания субъекта */
end;

/* Атрибуты кодов субъекта */
class TWsPartyCode
  var CodeKind : integer; /* Вид кода субъекта экономики */
  var Code : string; /* Код */
  var FromDate : date; /* Дата начала действия. */
  var Action : string; /* Действие с кодом субъекта:  */
end;

/* Атрибуты адреса субъекта */
class TWsAdres
  var Type : TArray; /* Тип адреса.  */
  var Action : string; /* Действие */
  var Country : string; /* Код страны */
  var Territory : string; /* Код территории */
  var PostIndex : string; /* Индекс */
  var CodeRegion : string; /* Адм.-тер. единица региона */
  var Region : string; /* Регион */
  var RegionNumber : string; /* Числовой код региона */
  var CodeProvince : string; /* Адм-тер. единица области */
  var Province : string; /* Область */
  var CodeDistrict : string; /* Адм.-тер. единица района */
  var District : string; /* Район */
  var CodePlace : string; /* Адм.-тер. единица населенного пункта */
  var Place : string; /* Населенный пункт */
  var CodeStreet : string; /* Адм.-тер. единица улицы */
  var Street : string; /* Улица */
  var House : string; /* Дом */
  var NumCorps : string; /* Корпус */
  var Flat : string; /* Квртира */
  var Adress : string; /* Почтовый адрес */
  var Kladr : string; /* Код КЛАДР */
  var Okato : string; /* Код ОКАТО */

  Type = TArray;
end;

/* Атрибуты контактной информации */
class TWsContactInfo
  var Kind : integer; /* Вид контакта */
  var Category : integer; /* Характер контакта */
  var Value : string; /* Значение контакта */
  var AdresType : integer; /* Тип адреса. В RS-Bank'е контактная информация хранится вместе с адресом субъекта. */
  var Action : string; /* Действие */
  var PhoneNumber2 : string; /* Дополнительный телефонный номер */
  var MobileProvider : string; /* Наименование мобильного оператора */
  var RS_Mail_Country : integer; /* Страна RS-Mail */
  var RS_Mail_Region : integer; /* Регион RS-Mail */
  var RS_Mail_Node : integer; /* Узел RS-Mail */
end;

/* Атрибуты документа, удост. личность */
class TWsPaper
  var Kind : string; /* Код вида документа по справочнику "Виды документов, удостоверяющих личность налогоплательщика" */
  var Action : string; /* Действие. */
  var Series : string; /* Серия */
  var Number : string; /* Номер */
  var IssuedDate : date; /* Дата выдачи документа */
  var Issuer : string; /* Наименование организации, выдавшей документ */
  var IssuerCode : string; /* Код подразделения, выдавшего документ */
  var IsMain : bool; /* Признак основного документа. */
  var CountryLat2 : string; /* Двухбуквенный код страны, выдавшей ДУЛ */
  var ValidToDate : date; /* Дата окончания действия документа */
end;

/* Атрибуты рег. документа */
class TWsRegDoc
  var RegDocKind : string; /* Вид регистрационного документа */
  var RegPartyKind : string; /* Вид регистрационного органа */
  var Action : string; /* Действие. */
  var RegDocNumber : string; /* Регистрационный номер */
  var Series : string; /* Серия регистрационного документа */
  var Number : string; /* Номер регистрационного документа */
  var DocDate : date; /* Дата регистрационного документа. */
  var StartDate : date; /* Дата начала действия документа */
  var FinishDate : date; /* Дата окончания действия документа */
  var RegPlace : string; /* Место регистрации */
  var IsMain : bool; /* Признак "Основной регистрационный документ". */
  var IsClosed : bool; /* Признак "Регистрация недействительна". */
end;

/* Атрибуты примечания */
class TWsNote
  var NoteKind : integer; /* Вид примечания */
  var Action : string; /* Действие с примечанием:  */
  var NoteText : string; /* Текст примечания */
  var Date : date; /* Дата ввода/изменения примечания */
end;

/* Атрибуты сотрудника */
class TWsOfficer
  var PersonID        : integer; /*Ид. клиента физ.лица, сотрудника Клиента*/
  var OfficeID        : integer; /*Ид. подразделения в орг.структуре*/
  var PhoneNumber     : string;  /*Телефон сотрудника*/
  var IsFirstPerson   : string;  /*Признак 1-го лица*/
  var IsSecondPerson  : string;  /*Признак 2-го лица*/
  var IsMatOtvPerson  : string;  /*Признак наличия материальной ответственности*/
  var HasSignRight    : string;  /*Признак наличия полномочий подписи зарплатного проекта*/
  var IsTempSignature : string;  /*Признак наличия права временной подписи*/
  var Post            : string;  /*Название должности*/
  var DateFrom        : date;    /*Дата начала полномочий*/
  var DateTo          : date;    /*Дата окончания полномочий*/
end;

/* Атрибуты псевдонима */
class TWsPartyAlias
  var PartyNameID : integer; /* Код вида наименования */
  var Name        : string; /* Псевдоним  */
end;

/* Атрибуты физического лица со всеми дочерними сущностями */
class (TWsPersn) TWsPersnFull

 var ClientParam; /*: TWsClient*/   /* Параметры клиента вида обслуживания. */
 var Codes; /*: TArray*/            /* Коды субъекта (массив структур TWsPartyCode). */
 var Adresses; /*: TArray*/         /* Адреса субъекта (массив структур TWsAdres). */
 var Contacts; /*: TArray*/         /* Контакты субъекта (массив структур TWsContactInfo). */
 var PersnPapers; /*: TArray*/      /* Документы, удостоверяющие личность личность (массив структур TWsPaper). */
 var RegDocs; /*: TArray*/          /* Регистрационные документы (массив структур TWsRegDoc). */
 var PartyNotes; /*: TArray*/       /* Примечания субъекта (массив структур TWsNote). */
 var PersnNotes; /*: TArray*/       /* Примечания физ. лица (массив структур TWsNote). */
end;

/* Атрибуты клиента TWsGateClient */
class TWsGateClient
  var BIC             : string;  /* БИК */
  var szShortName     : string;  /* Субъект: Краткое наименование субъекта экономики. */
  var Name_Client     : string;  /* Субъект: Полное наименование субъекта. */
  var szOkpo          : string;  /* Субъект:  Код ОКПО. */
  var szSysType       : string;  /* Субъект: Строка системных типов. */
  var szUserType      : string;  /* Субъект: Строка пользовательских типов. */
  var inn             : string;  /* Субъект: Значение вида кода "ИНН". */
  var Change_Date     : date;    /* Дата ввода/изменения примечания */
  var Change_DatePrev : date;    /* Дата ввода/изменения примечания */
  var UserField1      : string;  /* Субъект: Пользовательское поле 1. */
  var UserField2      : string;  /* Субъект: Пользовательское поле 2. */
  var UserField3      : string;  /* Субъект: Пользовательское поле 3. */
  var UserField4      : string;  /* Субъект: Пользовательское поле 4. */
  var bdTaxRegDate    : date;    /* Субъект: Дата регистрации в налоговой инспекции. */
  var NotResident     : string;  /* Субъект: Признак нерезидентности. */
  var iTaxInstitution : integer; /* Субъект: Ссылка на налоговое учреждение, в котором зарегистрирован субъект. */
  var iCarryOper      : integer; /* Клиент: Операционист, закрепленный за клиентом по данному виду обслуживания. */
  var bdStartDate     : date;    /* Клиент: Дата начала обслуживания. */
  var bdFinishDate    : date;    /* Клиент: Дата окончания обслуживания. */
  var szCountry       : string;  /* СубъектЮридический адрес: Русский код страны. */
  var lPostIndex      : string;  /* Юридический адрес: Индекс. */
  var szRepublic      : string;  /* Юридический адрес: Город. */
  var szRegion        : string;  /* Юридический адрес: Регион. */
  var szCity          : string;  /* Юридический адрес: Населенный пункт. */
  var szAddress       : string;  /* Юридический адрес: Строка с адресом. */
  var szPhoneNumber   : string;  /* Юридический адрес: Телефон. */
  var szPhoneNumber2  : string;  /* Юридический адрес: Дополнительный телефон. */
  var szTelegraph     : string;  /* Юридический адрес: Телеграф. */
  var szTelexNumber   : string;  /* Юридический адрес: Телекс. */
  var LastName        : string;  /* Фамилия. */
  var Name            : string;  /* Имя. */
  var Patronymic      : string;  /* Отчество. */
  var BirthDate       : date;    /* День рождения. */
  var Sex             : integer; /* Пол. */
  var IsEmployer      : string;  /* Признак индивидуального предпринимателя. */
  var Nationality     : string;  /* Национальность. */
  var Appointment     : string;  /* Должность. */

end;

/* Атрибуты структуры TWsGetClientListRequest */
class TWsGetClientListRequest

  var PersnMainData: TWsPersn; /* Данные физ.лица */
  var IdentityDoc  : TWsPaper; /* Данные ДУЛ */
  var Rows       : integer; /* Количество строк в ответе */
  var Oper       : integer; /* Пользователь */
  var Department : integer; /* Подразделение банка. */

end;

/* Атрибуты структуры TWsGetClientListResponse */
class TWsGetClientListResponse

  var PartyID    : integer; /* ИД субъекта. Идентификатор физ.лица в RS-Bank */
  var PersnMainData: TWsPersn; /* Данные физ.лица */
  var IdentityDoc  : TArray  ; /* Данные ДУЛ */
  var Addresses    : TArray  ; /* <TWsAdres>	Список адресов */
  var Contacts     : TArray  ; /* <TWsContactInfo>	Список контактов */

end;

/* Атрибуты структуры TWsGetClientDataRequest - структура входного параметра сервиса GetClientData*/
class TWsGetClientDataRequest
 
  var PartyID    : integer     ; /* Идентификатор субъекта	Обязательно наличие хотя бы одного заданного поля	+/-	*/
  var PartyCode  : TWsPartyCode; /* Код субъекта		-/+	*/
  var Oper       : integer     ; /* Идентификатор пользователя в RS-Bank */
  var Department : integer     ; /* Идентификатор подразделения в RS-Bank */

end;

/* Атрибуты структуры TWsGetClientDataResponse - cтруктура выходного параметра сервиса GetClientData.*/
class  TWsGetClientDataResponse

  var PartyID     : integer ; /* ИД субъекта.   +*/
  var Persn       /*: TWsPersn*/; /* Параметры физ.лица     В зависимости от вида субъекта заполняется одно из полей        +/-     */
  var Inst        /*: TWsInst */; /* Параметры юр.лица              -/+     */
  var Codes       : TArray  ; /* Array<TWsPartyCode> Список кодов субъектов */
  var Clients     : TArray  ; /* Array<TWsClient> Параметры обслуживания */
  var PersnPapers : TArray  ; /* Array<TWsPaper> Список ДУЛ */
  var Addresses	  : TArray  ; /* Array<TWsAdres> Список адресов */
  var Contacts	  : TArray  ; /* <TWsContactInfo>Список контактов */
  var RegDocs     : TArray  ; /* <TWsRegDoc> Список рег.документов */
  var PartyNotes  : TArray  ; /* <TWsNote> Примечания субъекта */
  var PersnNotes  : TArray  ; /* <TWsNote> Примечания физ.лица */
  var Officer     : TArray  ; /* <TWsOfficer> Сотрудники клиента */
  var PartyName   : TArray  ; /* <TWsPartyAlias> Псевдонимы клиента */

end;

/* Атрибуты СПИ (структура TWsSettAcc) */
class  TWsSettAcc
    var Action	         : String;  // Действие над СПИ
    var Order	         : Integer; // Порядок сортировки
    var Description	     : String;  // Описание СПИ
    var FICode	         : String;  // Код валюты счета.
    var Chapter	         : Integer; // Номер главы счета
    var Account	         : String;  // Номер счета
    var FIKind	         : Integer; // Вид ФИ
    var BankCodeKind	 : Integer; // Вид кода банка
    var BankCode	     : String;  // Код банка
    var BankCorrCodeKind : Integer; // Вид кода банка корреспондента
    var BankCorrCode     : String;  // Код банка корреспондента
    var CorrAcc	         : String;  // Корр. Счет
    var ShortName	     : String;  // Код СПИ
    var NoAccept	     : Bool;    // Признак <Без акцепта>
end; 

const WS_ERR_FLDNOTSET      = 21380; /* Не задано обязательное поле: <название поля> */
const WS_ERR_FLDNOTCORRECT  = 21381; /* Задано некорректное значение поля: <названия поля> */
const WS_ERR_PARTY_NOTFOUND = 21382; /* Не найден субъект экономики */
const WS_ERR_CODE_NOTFOUND  = 21368; /* Не найден код субъекта экономики */

