/*
$Name: IbrDynamicSource.mac
$Module: Отчеты банка
$Description: Данные и метаданные для формирования динамичных структур в веб-интерфейсе
*/

/**
 * Класс хранения как данных так и метаинформации
 */
class TIbrDynamicSource()

    /**
     * Метаданные
     */
    private var metaList: TArray = TArray();

    /**
     * Данные
     */
    private var dataList: TArray = TArray();

    /**
     * Описание
     */
    macro initialize(metaListParameter: TArray, dataListParameter: TArray)

        if (metaListParameter == NULL)

            throw_web
            (
                TIbrUndefinedValueException
                (
                    "TIbrDynamicSource::initialize",
                    "metaListParameter"
                )
            );

        end;

        if (dataListParameter == NULL)

            throw_web
            (
                TIbrUndefinedValueException
                (
                    "TIbrDynamicSource::initialize",
                    "dataListParameter"
                )
            );

        end;

        metaList = metaListParameter;
        dataList = dataListParameter;

        /**
         * Признак наличия атрибута, привязанного к полю
         */
        var isExistsBinding: Bool = FALSE;

        for (var meta, metaList)

            if (meta.getBinding())

                isExistsBinding = TRUE;

            end;

        end;

        if (NOT isExistsBinding)

            throw_web(TIbrException(TIbrResource().message.LIST_NO_BINDING));

        end;

    end;

end;
