/*
$Name: IbrReportWeb.mac
$Module: Отчеты банка
$Description: Транспортный класс отчета для веб-интефрейса
*/

/**
 * Класс отчета универсальной панели
 * Транспортный класс, для веб-интефрейса
 */
class TIbrReportWeb()

    /**
     * Идентификатор
     */
    var identifierReport: Integer = 0;

    /**
     * Наименование отчета
     */
    var name: String = "";

    /**
     * Отображаемое наименование отчета
     */
    var nameDisplayed: String = "";

    /**
     * Макрофайл сервисов отчета
     */
    var macroFile: String = "";

    /**
     * Сервис выполнения отчета
     */
    var serviceExecute: String = "";

    /**
     * Сервис проверки (валидации) полей отчета
     */
    var serviceValidate: String = "";

    /**
     * Признак пользовательского отчета
     */
    var isUser: Bool = FALSE;

    /**
     * Дерево декораций
     * TArray of TIbrDecorationWeb
     */
    var decorationList: TArray = TArray;

    /**
     * Список операций отчета
     * TArray of TIbrOperationWeb
     */
    var operationList: TArray = TArray();

    /**
     * Заполнить знчениями из источника данных
     *
     * @param dataSet Object Набор данных
     */
    macro initialize(dataSet: Object)

        if (dataSet == NULL)

            throw_web(TIbrUndefinedValueException("TIbrReportWeb::initialize", "dataSet"));

        end;

        execExp("TIbrReport().initialize(this, dataSet)");


    end;

    /**
     * Удаление отчета
     *
     * @return True, если отчет удален, иначе - False
     */
    macro delete(): Bool

        return execExp("TIbrReport().delete(this)");

    end;

    /**
     * Изменить параметры отчета
     *
     * @param newReportWeb TIbrReportWeb Новые параметры отчета
     *
     * @return TRUE, если значения изменены успешно, иначе - FASLE
     */
    macro update(newReportWeb: TIbrReportWeb): Bool

        return execExp("TIbrReport().update(this, newReportWeb)");

    end;

    macro toString()
        var s = "Report: "
                               + String(identifierReport)
                       + " - " + String(name)
                       + " - " + String(nameDisplayed)
                       + " - " + String(macroFile)
                       + " - " + String(serviceExecute)
                       + " - " + String(serviceValidate)
                       + " - " + String(isUser)
                ;
        qsort(decorationList, "cmpIbrObj");
        for (var d, decorationList)
            s = s + "\n" + String(d);
        end;
        return s;
    end;
end;
