/* 
ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
º à®¥ªâ: RS-Loans                                                            º
º €¢â®à : ’¥à¥é¥­ª® ”.‘.                                                      º
º „ â   : 27.09.2010                                                          º
º SCR   : 127324                                                              º
ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
 */

 import SbCrdInter, total;

///////////////////////////////////////////////////////////////////////////////
// ”ã­ªæ¨ï ¯à®¢¥àª¨ ¤ ­­ëå
//  à ¬¥âàë: ®¬¥àŽ¯¥à æ¨¨: ¯® ã¬®«ç ­¨î "55 ‚®§­¨ª­®¢¥­¨¥ Ž¢¥à¤à äâ ", ¬®¦­® ¨§¬¥­¨âì ¢ ¬ ªà®á¥ ¨«¨ •
//            „ â Ž¯¥à æ¨¨ : ¤ â  ®¯¥à æ¨¨
//            ‘“„          : áâà®ª  ®£à ­¨ç¥­¨© ‘“„. ’ ¡«¨æ  DCREDIT_C_DBT ¨¬¥¥â  «¨ á C
//            ‘®®¡é¥­¨¥    : áî¤  ¯¨è¥¬ á®®¡é¥­¨¥ ®¡ ®è¨¡ª¥
// ‚®§¢à â: Š®¤ ®è¨¡ª¨, ¦¥« â¥«ì­® ¨§ bank.msg
//
MACRO FillPayment(
                  ®¬¥àŽ¯¥à æ¨¨: INTEGER, 
                  „ â Ž¯¥à æ¨¨ : DATE, 
                  ‘“„          : STRING,
                  ‘®®¡é¥­¨¥    : STRING
                 )
   VAR RSDcmd = NULL,
       retval: INTEGER = 0;

   ‘®®¡é¥­¨¥ = "";

   RSDcmd = RsdCommand (RslDefCon, "BEGIN ? := RSO_LoansPay.FillPaymentForPay (?,?,?,?); END;");

   RSDcmd.addParam( "retval", RSDBP_RETVAL, V_INTEGER );
   RSDcmd.addParam ("TypeOp", 3);        RSDcmd.value ("TypeOp") = ®¬¥àŽ¯¥à æ¨¨;
   RSDcmd.addParam ("DateOp", RSDBP_IN); RSDcmd.value ("DateOp") = „ â Ž¯¥à æ¨¨;
   RSDcmd.addParam ("SUD",    RSDBP_IN); RSDcmd.value ("SUD")    = ‘“„;
   RSDcmd.addParam ("MSG",    RSDBP_OUT, V_STRING, 256);

   RSDcmd.execute();

   IF ((retval = RSDcmd.value("retval", NULL, V_INTEGER)) != 0) 
      SetParm(3, SQL_NVL(RSDcmd.value ("MSG"), V_STRING));
      RETURN retval;
   END;

   // ®¬¥à ®¯¥à æ¨¨ ¬®¦¥â ¡ëâì ¨§¬¥­¥­ ¢ •, ¯¥à¥¤ ¤¨¬ ¢ á¨è­¨ª
   SetParm(0, SQL_NVL(RSDcmd.value ("TypeOp"), V_INTEGER));

   RETURN 0;

   onError(er)
      // Žè¨¡ª¨ RSD ®â¤¥«ì­ ï ¯¥á­ï
      IF (RslDefEnv.ErrorCount > 0)
         SetParm(3, RslDefEnv.error(0).descr);
         RETURN RslDefEnv.error(0).code;
      END;
      SetParm(3, er.Message);
      RETURN er.Code;
END;