MACRO СоответствиеВидаЗадолженностиРегистру(DutyStageID:integer)
    VAR RegID : integer = 0;

    IF  (DutyStageID == DS_EXPPERCFINE)      /* неустойка по просроченным процентам */
        RegID = TDR_EXPPERC;                 /* просроченные проценты               */
    ELIF(DutyStageID == DS_EXPDUTYFINE)      /* неустойка попросроченным платежам   */
        RegID = TDR_EXPREST;                 /* просроченная задолженность          */
    ELIF(DutyStageID == DS_EXPPERC)          /* просроченные %%                     */
        RegID = TDR_EXPPERC;                 /* просроченные проценты               */
    ELIF(DutyStageID == DS_PERC)             /* Начисленные %%                      */
        RegID = TDR_MAINREST;                /* осн. долг                           */
    ELIF(DutyStageID == DS_ADDPERC)          /* Доначисленные %%                    */
        RegID = TDR_MAINREST;                /* осн. долг                           */
    ELIF(DutyStageID == DS_EXPDUTY)          /* просроченная задолженность          */
        RegID = TDR_EXPREST;                 /* просроченная задолженность          */
    ELIF(DutyStageID == DS_FINE)             /* единовременные штрафы               */
        RegID = TDR_PENNY;                   /* единовременные штрафы               */
    ELIF(DutyStageID == DS_DUTY)             /* основной долг                       */
        RegID = TDR_MAINREST;                /* осн. долг                           */
    ELIF(DutyStageID == DS_LOANACCOPKOMISS)  /* комиссия за операции по сс. счету   */
        RegID = TDR_MAINREST;                /* осн. долг                           */
    ELIF(DutyStageID == DS_LOANACCOPEXPKOMISSFINE) /* неустойка по просроч. комис. за оп. по сс. счету   */
        RegID = TDR_LOANACCEXPKOMISS;              /* просроченная комиссия за ведение ссудного счета    */
    ELIF(DutyStageID == DS_LOANACCOPEXPKOMISS)     /* просроч. комиссия за опер. по сс. счету            */
        RegID = TDR_LOANACCEXPKOMISS;              /* просроченная комиссия за ведение ссудного счета    */
    ELIF(DutyStageID == DS_NOLIMITKOMISS)          /* комиссия за неисп. лимит                           */
        RegID = TCLTR_LIMDUTY;                     /* неиспользованный лимит задолженности               */
    ELIF(DutyStageID == DS_NOLIMITEXPKOMISS)       /* просроч. комис. за неисп. лимит                    */
        RegID = TDR_NOLIMITEXPKOMISS;              /* просроченная комиссия за неиспользованный лимит    */
    ELIF(DutyStageID == DS_NOLIMITEXPKOMISSFINE)   /* неустойка по просроч. комис. за неисп. лимит       */
        RegID = TDR_NOLIMITEXPKOMISS;              /* Просроченная комиссия за неиспользованный лимит    */
    ELIF(DutyStageID == DS_CREDLINEOPENLIMITKOMISS)/* комиссия за откр. лимит                            */
        RegID = TDR_LIMPAY;                        /* лимит выдачи                                       */
    ELIF(DutyStageID == DS_CRLINEOPENLIMEXPKOMISS) /* просроч. комис. за откр. лимит                     */
        RegID = TDR_OPENLIMITEXPKOMISS;            /* просроченная комиссия за открытый лимит            */
    ELIF(DutyStageID == DS_CRLINEOPENLIMEXPKOMISSFINE)   /* неустойка по просроч. комис. за откр. лимит  */
        RegID = TDR_OPENLIMITEXPKOMISS;            /* Просроченная комиссия за открытый лимит            */
    ELIF(DutyStageID == DS_NOOVCRDEXPPERCFINE)     /* неустойка по просроч. %% по неразреш. ОД           */
        RegID = TDR_EXPPERC_OV;                    /* Просроченные % по неразрешенному ОД                */
    ELIF(DutyStageID == DS_NOOVCRDEXPPAYFINE)      /* неустойка по просроч. платежам по неразреш. ОД     */
        RegID = TDR_OV;                            /* просроченный неразрешенный ОД                      */
    ELIF(DutyStageID == DS_NOOVCRDPERCENT)         /* Начисленные %% по неразреш. ОД                     */
        RegID = TDR_LIM;                           /* История неразрешенного ОД                          */
    ELIF(DutyStageID == DS_ADDNOOVCRDPERCENT)      /* Доначисленные %% по неразреш. ОД                   */
        RegID = TDR_LIM;                           /* История неразрешенного ОД                          */
    ELIF(DutyStageID == DS_NOOVCRDEXPDUTY)         /* просроч. задолж. по неразреш. ОД                   */
        RegID = TDR_OV;                            /* просроченный неразрешенный ОД                      */
    ELIF(DutyStageID == DS_NOOVCRD)                /* неразреш. ОД                                       */
        RegID = TDR_LIM;                           /* История неразрешенного ОД                          */
    ELIF(DutyStageID == DS_NOOVCRDEXPPERC)         /* просроч. %% по неразреш. ОД                        */
        RegID = TDR_EXPPERC_OV;                    /* просроченные % по неразрешенному ОД                */
    ELIF (DutyStageID == DS_DEBITSELLS)            /* Задолженность продавца         */
        RegID = TDR_DEBSELL;                       /* Собственные средства заемщика  */
    ELIF (DutyStageID == DS_WRITEOFFPERC)          /* Списанные с баланса % */
        RegID = TREG_WRITTEN_OFF_PERC;             /* Счет списанных с баланса % по кредиту */
    ELIF (DutyStageID == DS_WRITEOFFDUTY)          /* Списанный с баланса ОД */
        RegID = TREG_WRITTEN_OFF_CRD;              /* Счет списанной с баланса ссудной задолженности по кредиту */
    ELIF(DutyStageID == DS_PAYEDGUARKOMISS)            /*Комиссия за выданную гарантию*/
        RegID = TDR_PAYEDGUARANTEE;                    /*История выданной гарантии*/
    ELIF(DutyStageID == DS_PAYEDGUAREXPKOMISSFINE)     /*Неустойка за просроченную комиссию за выданную гарантию*/
        RegID = TDR_PAYEDGUARANTEEEXPKOMISS;           /*Просроченная комиссия за выданную гарантию*/
    ELIF(DutyStageID == DS_PAYMGUARPERCENT)            /*Начисленные проценты по оплаченной гарантии*/
        RegID = TDR_PAYMGUARANTEE;                     /*История оплаченной гарантии*/
    ELIF(DutyStageID == DS_PAYMGUAREXPPERC)            /*Просроченные % оплаченной гарантии*/
        RegID = TDR_PAYMGUARANTEEEXPPERC;              /*Просроченные % оплаченной гарантии*/
    ELIF(DutyStageID == DS_PAYMGUAREXPPERCFINE)        /*Неустойка просроченных % оплаченной гарантии*/
        RegID = TDR_PAYMGUARANTEEEXPPERC;              /*Просроченные % оплаченной гарантии*/
    ELIF(DutyStageID == DS_EXPPAYMGUARFINE)            /*Неустойка просроченной оплаченной гарантии*/
        RegID = TDR_EXPPAYMGUARANTEE                   /*История просроченной оплаченной гарантии*/
    ELIF(DutyStageID == DS_EXPPAYMGUARANTEE)           /*Просроченная оплаченная гарантия*/
        RegID = TDR_EXPPAYMGUARANTEE                   /*История просроченной оплаченной гарантии*/
    ELIF(DutyStageID == DS_PAYMGUARANTEE)              /*Оплаченная гарантия*/
        RegID = TDR_PAYMGUARANTEE                      /*История оплаченной гарантии*/
    ELIF(DutyStageID == DS_PAYMGUARADDPERC)            /*Доначисленные % по оплаченной гарантии*/
        RegID = TDR_PAYMGUARANTEE;                     /*История оплаченной гарантии*/
//    ELIF(DutyStageID == DS_GENAGREEMENT43)         /*Комиссия за открытый лимит ГС*/
//        RegID = TDR_LIMPAY;                        /*лимит выдачи                                        */
//    ELIF(DutyStageID == DS_GENAGREEMENT44)         /*Просроченная комиссия за открытый лимит ГС          */
//        RegID = TDR_OPENLIMITEXPKOMISS;            /* просроченная комиссия за открытый лимит            */
//    ELIF(DutyStageID == DS_GENAGREEMENT45)         /*Неустойки по просроченной комиссии за открытый лимит ГС*/
//        RegID = TDR_OPENLIMITEXPKOMISS;            /* Просроченная комиссия за открытый лимит            */
    END;

    RETURN RegID;
END;


/*
Функция по виду задолженности возвращает тип входящего платежа
*/
MACRO IncomePaymentType(DS_Type)

    var PayType = 0;

    IF (
        (DS_Type == DS_EXPPERCFINE)            OR (DS_Type == DS_EXPDUTYFINE)                OR (DS_Type == DS_FINE)                 OR
        (DS_Type == DS_LOANACCOPEXPKOMISSFINE) OR (DS_Type == DS_CRLINEOPENLIMEXPKOMISSFINE) OR (DS_Type == DS_NOLIMITEXPKOMISSFINE) OR
        (DS_Type == DS_NOOVCRDEXPPERCFINE)     OR (DS_Type == DS_NOOVCRDEXPPAYFINE)
       )
       PayType = LPM_FAIL;
    ELIF (
          (DS_Type == DS_EXPPERC)                OR (DS_Type == DS_NOOVCRDEXPPERC)     OR (DS_Type == DS_LOANACCOPEXPKOMISS) OR
          (DS_Type == DS_CRLINEOPENLIMEXPKOMISS) OR (DS_Type == DS_NOLIMITEXPKOMISS)
         )
       PayType = LPM_EXPPERC;
    ELIF (
          (DS_Type == DS_PERC)              OR (DS_Type == DS_ADDPERC)                 OR
          (DS_Type == DS_LOANACCOPKOMISS)   OR (DS_Type == DS_CREDLINEOPENLIMITKOMISS) OR
          (DS_Type == DS_NOLIMITKOMISS)     OR (DS_Type == DS_NOOVCRDPERCENT)          OR
          (DS_Type == DS_ADDNOOVCRDPERCENT) OR (DS_Type == DS_WRITEOFFPERC)
         )
       PayType = LPM_PERC;
    ELIF ((DS_Type == DS_DUTY) OR (DS_Type == DS_NOOVCRD) OR (DS_Type == DS_WRITEOFFDUTY))
       PayType = LPM_CRD;
    ELIF ((DS_Type == DS_EXPDUTY) OR (DS_Type == DS_NOOVCRDEXPDUTY))
       PayType = LPM_EXPCRD;
    ELSE
       PayType = 0;
    END;

    return PayType;
END;

MACRO СоответствиеВидаЗадолженностиВидуСтавки(DutyStageID:integer)
    VAR RateID : integer = 0;

    IF  (DutyStageID == DS_EXPPERCFINE)                /*неустойка по просроченным процентам*/
        RateID = TRU_EXPPERC;                          /*неустойки по просрочке %*/
    ELIF(DutyStageID == DS_EXPDUTYFINE)                /*неустойка попросроченным платежам*/
        RateID = TRU_EXPCRD;                           /*неустойки по просрочке ОД*/
    ELIF(DutyStageID == DS_PERC)                       /*Начисленные %%*/
        RateID = TRU_CRD;                              /*по ОД*/
    ELIF(DutyStageID == DS_ADDPERC)                    /*Доначисленные %%*/
        RateID = TRU_CRD;                              /*по ОД*/
    ELIF(DutyStageID == DS_LOANACCOPKOMISS)            /*комиссия за операции по сс. счету*/
        RateID = TRU_LOANACCOPER;                      /*за операции по сс. счету*/
    ELIF(DutyStageID == DS_LOANACCOPEXPKOMISS)         /*просроченная комиссия за операции по сс. счету*/
        RateID = TRU_LOANACCOPER;                      /*за операции по сс. счету*/
    ELIF(DutyStageID == DS_LOANACCOPEXPKOMISSFINE)     /*неустойка по просроч. комис. за оп. по сс. счету*/
        RateID = TRU_EXPLOANACCOPERPAY;                /*неустойки по просрочке опл. за оп. по сс. счету*/
    ELIF(DutyStageID == DS_NOLIMITKOMISS)              /*комиссия за неисп. лимит*/
        RateID = TRU_NOLIMIT;                          /*за неиспользованный лимит*/
    ELIF(DutyStageID == DS_NOLIMITEXPKOMISS)           /*просроченная комиссия за неисп. лимит*/
        RateID = TRU_NOLIMIT;                          /*за неиспользованный лимит*/
    ELIF(DutyStageID == DS_NOLIMITEXPKOMISSFINE)       /*неустойка по просроч. комис. за неисп. лимит*/
        RateID = TRU_EXPNOLIMITPAY;                    /*неустойки по просрочке оплаты за неисп. лимит*/
    ELIF(DutyStageID == DS_NOOVCRDEXPPERCFINE)         /*неустойка по просроч. %% по неразреш. ОД*/
        RateID = TRU_EXPPERC_OV;                       /*Просроченные % по неразрешенному ОД*/
    ELIF(DutyStageID == DS_NOOVCRDEXPPAYFINE)          /*неустойка по просроч. платежам по неразреш. ОД*/
        RateID = TRU_OV;                               /*Просроченный неразрешенный ОД*/
    ELIF(DutyStageID == DS_NOOVCRDPERCENT)             /*Начисленные %% по неразреш. ОД*/
        RateID = TRU_LIM;                              /*История неразрешенного ОД*/
    ELIF(DutyStageID == DS_ADDNOOVCRDPERCENT)          /*Доначисленные %% по неразреш. ОД*/
        RateID = TRU_LIM;                              /*История неразрешенного ОД*/
    ELIF(DutyStageID == DS_CRLINEOPENLIMEXPKOMISSFINE) /*Неустойка по просроч. комиссии за открытый лимит КЛ*/
        RateID = TRU_EXPOPENLIMITPAY;                  /*неустойки по просрочке оплаты за открытый лимит*/
    ELIF(DutyStageID == DS_PAYEDGUARKOMISS)            /*Комиссия за выданную гарантию*/
        RateID = TRU_PAYEDGUARKOMISS;                  /*Комиссия за выдачу гарантии*/
    ELIF(DutyStageID == DS_PAYEDGUAREXPKOMISS)         /*Просроченная комиссия за выданную гарантию*/
        RateID = TRU_PAYEDGUARKOMISS;                  /*Комиссия за выдачу гарантии*/
    ELIF(DutyStageID == DS_PAYEDGUAREXPKOMISSFINE)     /*Неустойка за просроченную комиссию за выданную гарантию*/
        RateID = TRU_PAYEDGUARKOMISSEXP;               /*Неустойка за просрочку комиссии за выданную гарантию*/
    ELIF(DutyStageID == DS_PAYMGUARPERCENT)            /*Начисленные проценты по оплаченной гарантии*/
        RateID = TRU_PAYMGUAR;                         /*% по оплаченной гарантии*/
    ELIF(DutyStageID == DS_PAYMGUAREXPPERCFINE)        /*Неустойка просроченных % оплаченной гарантии*/
        RateID = TRU_PAYMGUAREXPPERC;                  /*Неустойка за просрочку % оплаченной гарантии*/
    ELIF(DutyStageID == DS_EXPPAYMGUARFINE)            /*Неустойка просроченной оплаченной гарантии*/
        RateID = TRU_PAYMGUAREXP;                      /*Неустойка за просрочку оплаченной гарантии*/
    ELIF(DutyStageID == DS_PAYMGUARANTEE)              /*Оплаченная гарантия*/
        RateID = TRU_PAYMGUAR;                         /*% по оплаченной гарантии*/
    ELIF(DutyStageID == DS_PAYMGUARADDPERC)            /*Доначисленные % по оплаченной гарантии*/
        RateID = TRU_PAYMGUAR;                         /*% по оплаченной гарантии*/
//    ELIF(DutyStageID == DS_GENAGREEMENT45)             /*Неустойки по просроченной комиссии за открытый лимит ГС*/
//        RateID = TRU_EXPOPENLIMITPAY;                  /*неустойки по просрочке оплаты за открытый лимит*/
    END;
    RETURN RateID;
END;