/*---------------------------------------------------------------------------------
                     Библиотека интерпретируемых модулей

 Filename    : opn_crd.mac
 Description : Создание документа при открытии договора

 Programmer  : ROV
 11.09.98    : Создан
-----------------------------------------------------------------------------------*/
import SbCrdInter;

record ШагОперации ("step_op.dbt",  "loans.def");     /* Запись шага операции */
record Документ    ("doc_acc.dbt",  "loans.def");     /* Буфер документа      */
record Операция    ("crd_op.dbt",   "loans.def");     /* Операция по договору */
record Договор     ("credit_c.dbt", "loans.def");
record Сумма       ("SUM.",         "loans.def");

macro ВыполнитьШаг (OperDate, Sum, Data)
  setbuff(Сумма, Sum);
  if ((ШагОперации.ObjectID_D == 0) or (ШагОперации.ObjectID_C == 0))
      Документ.CarrySum = 0;
  else
     Документ.CarrySum = $1;
  end;
  return СоздатьДокумент(Документ);
end;
