/*
  $Name:        mnsgdroo.mac
  $Module:      MBR
  $Description: Генерация учетного объекта по сообщению ROO
*/
/****************************************************************************/
/*                   R-Style SoftWare Lab, RS-Bank 6.0                      */
/****************************************************************************/
/*                  Подсистема "Межбанковские расчеты"                      */
/* Генерация учетного объекта по сообщению ROO                              */
/*                                                                          */
/*  Имя файла: mnsgdroo.mac                                                 */
/*  Создан:    21.12.09                                  Шлемина С.В.       */
/****************************************************************************/

import OprInter, "wlmnstls.mac", "wldoc.mac", oralib, likepy, FIInter, "fnsRegDecAl_RP.mac";

/* Информация о счете */
class ConstructROO
 var
  IdFile       :string,      
  IdDoc        :string,       
  ВидРеш       :integer,
  НомРешПр     :string,
  ДатаРешПр    :string,
  КодНО        :string,
  НомРешОт     :string,
  ДатаРешОт    :string,
  НомФ         :string,
  НаимНО       :string,
  КласЧинРук   :string,
  ФИОРук       :string,
  НомРешВзыск  :string,
  ДатаРешВзыск :string,
  INN          :string,
  KPP          :string,
  НаимНП       :string,
  ФИОИП        :string,
  БИК          :string,
  НаимКО       :string,
  АдрНП        :string,
  ДолжнОтпр    :string,                                      
  ФамОтпр      :string,                                      
  ТелОтпр      :string,                                      
            
  AccKindList = Tarray,  
  AccList = Tarray,
  
  WasCall      :bool;

  ВидРеш       = 0;
  НомРешПр = ДатаРешПр = КодНО = НомРешОт = НомФ = ДатаРешОт = НаимНО = КласЧинРук = ФИОРук = НомРешВзыск = ДатаРешВзыск = 
  INN = KPP = НаимНП = ФИОИП = БИК = НаимКО = АдрНП = ДолжнОтпр = ФамОтпр = ТелОтпр = "";

  WasCall      = false;

end;

macro Fill_IDFile(val, ROO)
  ROO.IdFile = val;
  return true;
end;

macro Fill_IDDoc(val, ROO)
  ROO.IdDoc = val;
  return true;
end;

macro Fill_NumC(val, ROO)
  ROO.НомРешОт = val;
  return true;
end;

macro Fill_DateC(val, ROO)
  ROO.ДатаРешОт= val;
  return true;
end;
macro Fill_NumD(val, ROO)
  ROO.НомРешПр= val;
  return true;
end;
macro Fill_DateD(val, ROO)
  ROO.ДатаРешПр= val;
  return true;
end;
macro Fill_CodeNO(val, ROO)
  ROO.КодНО= val;
  return true;
end;
macro Fill_VidR(val, ROO)
  ROO.ВидРеш= val;
  return true;
end;

macro Fill_NameNO(val, ROO)
  ROO.НаимНО = val;
  return true;
end;

macro Fill_HeadRange(val, ROO)
  ROO.КласЧинРук = val;
  return true;
end;

macro Fill_NomF(val, ROO )
  ROO.НомФ = val;
  return TRUE;
end;


macro Fill_HeadFIO(val, ROO)
  ROO.ФИОРук = val;
  return true;
end;

macro Fill_NumV(val, ROO)
  ROO.НомРешВзыск = val;
  return true;
end;

macro Fill_DateV(val, ROO)
  ROO.ДатаРешВзыск = val;
  return true;
end;

macro Fill_INN(val, ROO)
  ROO.INN = val;
  return true;
end;

macro Fill_KPP(val, ROO)
  ROO.KPP = val;
  return true;
end;

macro Fill_NameNP(val, ROO)
  ROO.НаимНП = val;
  return true;
end;

macro Fill_FIOIP(val, ROO)
  ROO.ФИОИП = val;
  return true;
end;

macro Fill_AddrNP(val, ROO)
  ROO.АдрНП = val;
  return true;
end;

macro Fill_BIC(val, ROO)
  ROO.БИК = val;
  return true;
end;

macro Fill_NameKO(val, ROO)
  ROO.НаимКО = val;
  return true;
end;

macro Fill_RespPost(val, ROO)
  ROO.ДолжнОтпр = val;
  return TRUE;
end;

macro Fill_RespFIO(val, ROO)
  ROO.ФамОтпр = val;
  return TRUE;
end;

macro Fill_RespTel(val, ROO)
  ROO.ТелОтпр = val;
  return TRUE;
end;

macro Fill_AccKind(val, ROO)
  ROO.AccKindList[ROO.AccKindList.Size] = val;
  return true;
end;

macro Fill_Acc(val, ROO)
  ROO.AccList[ROO.AccList.Size] = val;
  return true;
end;

/* Заполнение списка полей формы  IPB*/
var FldIDFile  = ТПолеМНС( "ИдФайл",        "Fill_IDFile"    ),
    FldIDDoc   = ТПолеМНС( "ИдДок",         "Fill_IDDoc"     ),
    FldNumC    = ТПолеМНС( "НомРешОт",      "Fill_NumC"      ),
    FldDateC   = ТПолеМНС( "ДатаРешОт",     "Fill_DateC"     ),
    FldNumD    = ТПолеМНС( "НомРешПр",      "Fill_NumD"      ),
    FldDateD   = ТПолеМНС( "ДатаРешПр",     "Fill_DateD"     ),
    FldCodeNO  = ТПолеМНС( "КодНО",         "Fill_CodeNO"    ),
    FldVidR    = ТПолеМНС( "ВидРеш",        "Fill_VidR"      ),

    FldNameNO    = ТПолеМНС( "НаимНО",      "Fill_NameNO"    ),
    FldHeadRange = ТПолеМНС( "КласЧинРук",  "Fill_HeadRange" ),
    FldHeadFIO   = ТПолеМНС( "ФИОРук",      "Fill_HeadFIO"   ),
    FldNumV      = ТПолеМНС( "НомРешВзыск", "Fill_NumV"      ),
    FldDateV     = ТПолеМНС( "ДатаРешВзыск","Fill_DateV"     ),
    FldINN       = ТПолеМНС( "ИНННП",       "Fill_INN"       ),
    FldKPP       = ТПолеМНС( "КППНП",       "Fill_KPP"       ),
    FldNameNP    = ТПолеМНС( "НаимНП",      "Fill_NameNP"    ),
    FldFIOIP     = ТПолеМНС( "ФИОИП",       "Fill_FIOIP"     ),
    FldAddrNP    = ТПолеМНС( "АдрНП",       "Fill_AddrNP"    ),
    FldNomF      = ТПолеМНС( "НомФ",        "Fill_NomF"      ),
    FldBIC       = ТПолеМНС( "БИК",         "Fill_BIC"       ),
    FldNameKO    = ТПолеМНС( "НаимКО",      "Fill_NameKO"    ),

    FldRespPost  = ТПолеМНС( "ДолжнОтпр",   "Fill_RespPost"  ),
    FldRespFIO   = ТПолеМНС( "ФамОтпр",     "Fill_RespFIO"   ),
    FldRespTel   = ТПолеМНС( "ТелОтпр",     "Fill_RespTel"   ),

    FldAccKind   = ТПолеМНС( "ВидСч",       "Fill_AccKind"   ),
    FldAcc       = ТПолеМНС( "НомСч",       "Fill_Acc"       );    
    
    ;    

macro Construct(ROO)
  var field_name, field_value, fldd, i;
  if(ROO.WasCall)
    return true;
  end;
  /* Последовательно считываем поля и заполняем лексемы */
  while(СчитатьПоле(field_name, field_value))  
      i = IndexMNS(field_name);
      if (i != -1)
         fldd = ПоляМНС.Value(i);    
         fldd.ОбработатьПолеФормы( field_value, ROO ); 
      end;
  end;
  if(not IsOprMultiExec)
    ROO.WasCall = True;
  end;
  return TRUE;
end; /* Construct */

/* Релиз ROO */
macro GenDoc( addrMes )
  SetBuff( wlmes, addrMes );
  PrintLog(2,"Генерация учетного объекта по сообщению ROO");
  
  var ROO = ConstructROO();
  Construct(ROO);

  var error = 0, inn = IfThenElse( ROO.KPP == "", ROO.INN, ROO.INN + "/" + ROO.KPP ), DecID = 0, count = 0, acc = "";
 
  file f_wlsess(wlsess) key 0;
  f_wlsess.SessionID = wlmes.SessionID;
  GetEQ(f_wlsess);
  
  /* Если при загрузке не определился внутренний абонент, то создаем подтверждение банка с ошибкой */
  if( wlmes.InsideAbonentID <= 0 )

    var ErrList = RsbWlError(0);

    var wlerr_buf = TRecHandler("wlerror.dbt");
    wlerr_buf.rec.Code         = "31";
    wlerr_buf.rec.Description  = "Электронный документ ошибочно направлен налоговым органом не в тот банк (филиал банка). В банке "+
                                 ПолучитьБИКГоловногоФилиала( {OurBank} ) + " нет филиала с БИК " + ROO.БИК + " и номером " + ROO.НомФ;
    ErrList.Insert( wlerr_buf );
    /* Параметры создаваемого УО */
    var ResultID = 0;
    var ErrCode = FNS_RP_CANNOT_EXECUTED_BANK;
    var ErrDescription = Bnk_GetLLValuesName(OBJTYPE_WLRESCODE_MNS, ErrCode);

    if( not ВставитьПодтверждениеБанкаФНС( wlmes, ErrCode, ErrDescription, ErrList, "", -1, 0, "", "", -1, 0, "", "", NULL, NULL, ResultID ) )
      std.msg( "Ошибка при вставке подтверждения банка" );
      return FALSE;
    end;
    /*Связь подтверждения с входящим сообщением */
    var meslnk = TRecHandler("wlmeslnk.dbt");
    meslnk.rec.MesID   = wlmes.MesID;
    meslnk.rec.Direct  = "X";/*WLD_MES_IN*/
    meslnk.rec.ObjID   = ResultID;
    meslnk.rec.ObjKind = OBJTYPE_MESDEFECT;
    var MesLnkObj = RsbWlMesLnk( meslnk.rec.ObjKind, meslnk.rec.ObjID, meslnk.rec.Direct );            
    MesLnkObj.Insert( meslnk );
    MesLnkObj.Save();
    return TRUE;
  end;

  ClearRecord(wlregdec);
  
  /* Заполнение учетных буферов */
  wlregdec.Type                     = WLD_TYPE_REGDEC_ROO;
  wlregdec.OriginatorCodeKind       = PTCK_MNS;
  wlregdec.OriginatorCode           = ROO.КодНО;
  wlregdec.OriginatorName           = ROO.НаимНО; 
  wlregdec.OriginatorID             = ПолучитьКодСубъекта( wlregdec.OriginatorCode, wlregdec.OriginatorCodeKind, error );
  wlregdec.RecipientID              = wlmes.InsideAbonentID;
  wlregdec.RecipientCodeKind        = wlmes.InsideAbonentCodeKind;
  wlregdec.RecipientCode            = wlmes.InsideAbonentCode;
  wlregdec.RecipientName            = Bnk_GetPartyName(wlregdec.RecipientID);
  wlregdec.Number                   = ROO.НомРешОт; 
  wlregdec.Date                     = ROO.ДатаРешОт; 
  wlregdec.DeliveryDate             = f_wlsess.BankDate; 
  wlregdec.Kind                     = ROO.ВидРеш; 
  wlregdec.ClientName               = IfThenElse( ROO.НаимНП == "", StrSubSt( ROO.ФИОИП, ",", " " ), ROO.НаимНП ); 
  wlregdec.ClientINN                = ROO.INN; 
  wlregdec.ClientKPP                = ROO.KPP; 
  wlregdec.ClientID                 = GetClientForRegDec(ROO.INN/*, ROO.KPP*/);
  wlregdec.LnkDocNumber             = ROO.НомРешПр; 
  wlregdec.LnkDocDate               = ROO.ДатаРешПр; 
  wlregdec.RespPersonPost           = ROO.ДолжнОтпр; 
  wlregdec.RespPersonFIO            = ROO.ФамОтпр; 
  wlregdec.RespPersonTel            = ROO.ТелОтпр; 
  wlregdec.ClientType               = IfThenElse(strlen(wlregdec.ClientINN) == 12, RO_CLIENTTYPE_PERSN_EMPLOYER, RO_CLIENTTYPE_INST);

  if( not ВставитьРешениеРегистрационногоОргана( wlregdec, DecID ) )
    std.msg("Ошибка при вставке решения регистрационного органа");
    return false;
  end;

  DeleteWlRepClm( DecID );

  if( DecID > 0 )
    while(count < ROO.AccList.size)
      acc = ROO.AccList.value(count);
      ClearRecord( wlacclnk );
      wlacclnk.ObjectID      = DecID;
      wlacclnk.ObjectType    = OBJTYPE_DECISION;
      wlacclnk.Account       = acc;
      wlacclnk.FIID          = ПолучитьКодФинИн( substr( acc, 6, 3 ) );
      wlacclnk.Chapter       = 1;
      if( not ВставитьСвязанныйСчет( wlacclnk ) )
        std.msg("Ошибка при вставке связанного счета");
        return false;
      end;
      count = count + 1;
    end;
  end;
  
  return true;

  OnError(er) /* Обработка ошибок времени выполнения */
    ExeptionMessage(er);
    return FALSE;
end;