/*
  $Name:        mnsgdrpo.mac
  $Module:      MBR
  $Description: Генерация учетного объекта по сообщению RPO
*/
/****************************************************************************/
/*                   R-Style SoftWare Lab, RS-Bank 6.0                      */
/****************************************************************************/
/*                  Подсистема "Межбанковские расчеты"                      */
/* Генерация учетного объекта по сообщению RPO                              */
/*                                                                          */
/*  Имя файла: mnsgdrpo.mac                                                 */
/*  Создан:    21.12.09                                  Шлемина С.В.       */
/****************************************************************************/

import OprInter, "wlmnstls.mac", "wldoc.mac", oralib, likepy, FIInter, "fnsRegDecAl_RP.mac";

/* Информация о счете */
class ConstructRPO
 var
  IdFile            :string,      
  IdDoc             :string,       
  INN               :string,
  KPP               :string,
  НаимНП            :string,
  ФИОИП             :string,
  НаимКО            :string,
  НомФ              :string,
  БИК               :string,
  НомРешПр          :string,
  ДатаРешПр         :string,
  СумВзыск          :money,
  НомРешВзыск       :string,
  ДатаРешВзыск      :string,
  НаимПрич          :string,
  Обстоят           :string,
  КодНО             :string,                                      
  НаимНО            :string,                                      
  КодОснов          :string,
  КласЧинРук        :string,                                      
  ФИОРук            :string,                                      
  ДолжРук           :string,
  АдрНП             :string,                                      
  ДолжнОтпр         :string,                                      
  ФамОтпр           :string,                                      
  ТелОтпр           :string,                                      

  AccKindList = Tarray,
  AccList     = Tarray,
  WasCalled         :bool;

  INN = KPP = НаимНП = ФИОИП = НаимКО = НомФ = БИК = НомРешПр = ДатаРешПр = НомРешВзыск = ДатаРешВзыск = НаимПрич = Обстоят = КодНО = 
  НаимНО = КодОснов = КласЧинРук = ФИОРук = ДолжРук = АдрНП = ДолжнОтпр = ФамОтпр = ТелОтпр = "";
  СумВзыск    = 0.0;
  WasCalled   = false;  
end;

macro Fill_IDFile(val, RPO)
  RPO.IDFile = val;
  return TRUE;
end;

macro Fill_IDDoc(val, RPO)
  RPO.IDDoc = val;
  return TRUE;
end;

macro Fill_NumD(val, RPO)
  RPO.НомРешПр = val;
  return TRUE;
end;

macro Fill_DateD(val, RPO)
  RPO.ДатаРешПр = val;
  return TRUE;
end;
macro Fill_CodeNO(val, RPO)
  RPO.КодНО = val;
  return TRUE;
end;

macro Fill_NameP(val, RPO)
  RPO.НаимПрич = val;
  return TRUE;
end;

macro Fill_INN(val, RPO)
  RPO.INN = val;
  return TRUE;
end;

macro Fill_KPP(val, RPO)
  RPO.KPP = val;
  return TRUE;
end;

macro Fill_NameNP(val, RPO)
  RPO.НаимНП = val;
  return TRUE;
end;

macro Fill_FIOIP(val, RPO)
  RPO.ФИОИП = val;
  return TRUE;
end;

macro Fill_Obst(val, RPO)
  RPO.Обстоят = val;
  return TRUE;
end;

macro Fill_BIC(val, RPO)
  RPO.БИК = val;
  return TRUE;
end;

macro Fill_NameKO(val, RPO)
  RPO.НаимКО = val;
  return TRUE;
end;

macro Fill_NomF(val, RPO)
  RPO.НомФ = val;
  return TRUE;
end;

macro Fill_SumV(val, RPO)
  RPO.СумВзыск = val;
  return TRUE;
end;

macro Fill_NumV(val, RPO)
  RPO.НомРешВзыск = val;
  return TRUE;
end;

macro Fill_DateV(val, RPO)
  RPO.ДатаРешВзыск = val;
  return TRUE;
end;

macro Fill_NameNO(val, RPO)
  RPO.НаимНО = val;
  return TRUE;
end;

macro Fill_GrCode(val, RPO)
  RPO.КодОснов = val;
  return TRUE;
end;

macro Fill_HeadRange(val, RPO)
  RPO.КласЧинРук = val;
  return TRUE;
end;

macro Fill_HeadFIO(val, RPO)
  RPO.ФИОРук = val;
  return TRUE;
end;

macro Fill_HeadPost(val, RPO)
  RPO.ДолжРук = val;
  return TRUE;
end;

macro Fill_AddrNP(val, RPO)
  RPO.АдрНП = val;
  return TRUE;
end;

macro Fill_RespPost(val, RPO)
  RPO.ДолжнОтпр = val;
  return TRUE;
end;

macro Fill_RespFIO(val, RPO)
  RPO.ФамОтпр = val;
  return TRUE;
end;

macro Fill_RespTel(val, RPO)
  RPO.ТелОтпр = val;
  return TRUE;
end;

macro Fill_AccKind(val, RPO)
  RPO.AccKindList[RPO.AccKindList.Size] = val;
  return TRUE;
end;

macro Fill_Acc(val, RPO)
  RPO.AccList[RPO.AccList.Size] = val;
  return TRUE;
end;

var FldIDFile    = ТПолеМНС( "ИдФайл",      "Fill_IDFile"    ),
    FldIDDoc     = ТПолеМНС( "ИдДок",       "Fill_IDDoc"     ),
    FldNumD      = ТПолеМНС( "НомРешПр",    "Fill_NumD"      ),
    FldDateD     = ТПолеМНС( "ДатаРешПр",   "Fill_DateD"     ),
    FldCodeNO    = ТПолеМНС( "КодНО",       "Fill_CodeNO"    ),
    FldNameP     = ТПолеМНС( "НаимПрич",    "Fill_NameP"     ),
    FldINN       = ТПолеМНС( "ИНННП",       "Fill_INN"       ),
    FldKPP       = ТПолеМНС( "КППНП",       "Fill_KPP"       ),
    FldNameNP    = ТПолеМНС( "НаимНП",      "Fill_NameNP"    ),
    FldFIOIP     = ТПолеМНС( "ФИОИП",       "Fill_FIOIP"     ),
    FldObst      = ТПолеМНС( "Обстоят",     "Fill_Obst"      ),
    FldBIC       = ТПолеМНС( "БИК",         "Fill_BIC"       ),
    FldNameKO    = ТПолеМНС( "НаимКО",      "Fill_NameKO"    ),
    FldNomF      = ТПолеМНС( "НомФ",        "Fill_NomF"      ),
    FldSumV      = ТПолеМНС( "СумВзыск",    "Fill_SumV"      ),
    FldNumV      = ТПолеМНС( "НомРешВзыск", "Fill_NumV"      ),
    FldDateV     = ТПолеМНС( "ДатаРешВзыск","Fill_DateV"     ),

    FldNameNO    = ТПолеМНС( "НаимНО",      "Fill_NameNO"    ),
    FldGrCode    = ТПолеМНС( "КодОснов",    "Fill_GrCode"    ),
    FldHeadRange = ТПолеМНС( "КласЧинРук",  "Fill_HeadRange" ),
    FldHeadFIO   = ТПолеМНС( "ФИОРук",      "Fill_HeadFIO"   ),
    FldHeadPost  = ТПолеМНС( "ДолжРук",     "Fill_HeadPost"  ),
    FldAddrNP    = ТПолеМНС( "АдрНП",       "Fill_AddrNP"    ),

    FldRespPost  = ТПолеМНС( "ДолжнОтпр",    "Fill_RespPost"  ),
    FldRespFIO   = ТПолеМНС( "ФамОтпр",     "Fill_RespFIO"   ),
    FldRespTel   = ТПолеМНС( "ТелОтпр",     "Fill_RespTel"   ),

    FldAccKind   = ТПолеМНС( "ВидСч",       "Fill_AccKind"   ),        
    FldAcc       = ТПолеМНС( "НомСч",       "Fill_Acc"       );    

macro Construct(RPO)
  var field_name, field_value, fldd, i;
  if(RPO.WasCalled)
    return true;
  end;
  /* Последовательно считываем поля и заполняем лексемы */
  while(СчитатьПоле(field_name, field_value))  
      i = IndexMNS(field_name);
      if (i != -1)
         fldd = ПоляМНС.Value(i);    
         fldd.ОбработатьПолеФормы( field_value, RPO ); 
      end;
  end;
  if(not IsOprMultiExec)
    RPO.WasCalled = true;
  end;
  return TRUE;
end; /* Construct */

macro GenDoc( addrMes )

  SetBuff( wlmes, addrMes );
  PrintLog(2,"Генерация учетного объекта по сообщению RPO");
  
  var RPO = ConstructRPO();
  Construct(RPO);

  var error = 0, inn = IfThenElse( RPO.KPP == "", RPO.INN, RPO.INN + "/" + RPO.KPP ), DecID = 0, count = 0, acc = "";

  file f_wlsess(wlsess) key 0;
  f_wlsess.SessionID = wlmes.SessionID;
  GetEQ(f_wlsess);
  
  /* Если при загрузке не определился внутренний абонент, то создаем подтверждение банка с ошибкой */
  if( wlmes.InsideAbonentID <= 0 )

    var ErrList = RsbWlError(0);

    var wlerr_buf = TRecHandler("wlerror.dbt");
    wlerr_buf.rec.Code         = "31";
    wlerr_buf.rec.Description  = "Электронный документ ошибочно направлен налоговым органом не в тот банк (филиал банка). В банке "+
                                 ПолучитьБИКГоловногоФилиала( {OurBank} ) + " нет филиала с БИК " + RPO.БИК + " и номером " + RPO.НомФ;
    ErrList.Insert( wlerr_buf );
    /* Параметры создаваемого УО */
    var ResultID = 0;
    var ErrCode = FNS_RP_CANNOT_EXECUTED_BANK;
    var ErrDescription = Bnk_GetLLValuesName(OBJTYPE_WLRESCODE_MNS, ErrCode);

    if( not ВставитьПодтверждениеБанкаФНС( wlmes, ErrCode, ErrDescription, ErrList, "", -1, 0, "", "", -1, 0, "", "", NULL, NULL, ResultID ) )
      std.msg( "Ошибка при вставке подтверждения банка" );
      return FALSE;
    end;
    /*Связь подтверждения с входящим сообщением */
    var meslnk = TRecHandler("wlmeslnk.dbt");
    meslnk.rec.MesID   = wlmes.MesID;
    meslnk.rec.Direct  = "X";/*WLD_MES_IN*/
    meslnk.rec.ObjID   = ResultID;
    meslnk.rec.ObjKind = OBJTYPE_MESDEFECT;
    var MesLnkObj = RsbWlMesLnk( meslnk.rec.ObjKind, meslnk.rec.ObjID, meslnk.rec.Direct );            
    MesLnkObj.Insert( meslnk );
    MesLnkObj.Save();
    return TRUE;
  end;
  ClearRecord(wlregdec);
  
  /* Заполнение учетных буферов */
  wlregdec.Type                     = WLD_TYPE_REGDEC_RPO;
  wlregdec.OriginatorCodeKind       = PTCK_MNS;
  wlregdec.OriginatorCode           = RPO.КодНО;
  wlregdec.OriginatorName           = RPO.НаимНО; 
  wlregdec.OriginatorID             = ПолучитьКодСубъекта( wlregdec.OriginatorCode, wlregdec.OriginatorCodeKind, error );
  wlregdec.RecipientID              = wlmes.InsideAbonentID;
  wlregdec.RecipientCodeKind        = wlmes.InsideAbonentCodeKind;
  wlregdec.RecipientCode            = wlmes.InsideAbonentCode;
  wlregdec.RecipientName            = Bnk_GetPartyName(wlregdec.RecipientID);
  wlregdec.Number                   = RPO.НомРешПр; 
  wlregdec.Date                     = RPO.ДатаРешПр; 
  wlregdec.DeliveryDate             = f_wlsess.BankDate; 
  wlregdec.Amount                   = RPO.СумВзыск; 
  wlregdec.ClientName               = IfThenElse( RPO.НаимНП == "", StrSubSt( RPO.ФИОИП, ",", " " ), RPO.НаимНП );
  wlregdec.ClientINN                = RPO.INN; 
  wlregdec.ClientKPP                = RPO.KPP; 
  wlregdec.ClientID                 = GetClientForRegDec(RPO.INN/*, RPO.KPP*/);
  wlregdec.Ground                   = RPO.НаимПрич; 
  wlregdec.Description              = RPO.Обстоят; 
  wlregdec.RespPersonPost           = RPO.ДолжнОтпр; 
  wlregdec.RespPersonFIO            = RPO.ФамОтпр; 
  wlregdec.RespPersonTel            = RPO.ТелОтпр; 
  wlregdec.ClientType               = IfThenElse(strlen(wlregdec.ClientINN) == 12, RO_CLIENTTYPE_PERSN_EMPLOYER, RO_CLIENTTYPE_INST);

  if( not ВставитьРешениеРегистрационногоОргана( wlregdec, DecID ) )
    std.msg("Ошибка при вставке решения регистрационного органа");
    return false;
  end;

  DeleteWlRepClm( DecID );

  if( DecID > 0 )
    while(count < RPO.AccList.size)
      acc = RPO.AccList.value(count);
      ClearRecord( wlacclnk );
      wlacclnk.ObjectID      = DecID;
      wlacclnk.ObjectType    = OBJTYPE_DECISION;
      wlacclnk.Account       = acc;
      wlacclnk.FIID          = ПолучитьКодФинИн( substr( acc, 6, 3 ) );
      wlacclnk.Chapter       = 1;
      if( not ВставитьСвязанныйСчет( wlacclnk ) )
        std.msg("Ошибка при вставке связанного счета");
        return false;
      end;
      count = count + 1;
    end;
  end;
  
  return true;

  OnError(er) /* Обработка ошибок времени выполнения */
    ExeptionMessage(er);
    return FALSE;
end;