/*
$Name: swgm202c.mac
$Module: Межбанковские расчеты
$Description: Генерация сообщения по SWIFT MT202COV
*/

import "swgenmes.mac";
const  Relise = "202COV";

private macro IsOutPaym(RsPaym)
  if((RsPaym.ReceiverGroup == PAYMENTS_GROUP_EXTERNAL)  and (RsPaym.PayerGroup == PAYMENTS_GROUP_INTERNAL))
    return true;
  end;

  return false;
end;

macro GenMes( addrMes, addrPm, addrOldMes )
  var IsTransit, field_value, Tag, PaymentDetails, fld33B, fld32A;
  var ОстатокПоля70;
  var Recreate = false;
  var RsPaym;
  RECORD rcv(pmroute);
  RECORD ocb(pmroute);
  RECORD irb(pmroute);
  Record oldwlMes (wlmes);
  SetBuff( wlmes,  addrMes );
  SetBuff( wlpmpaym, addrPm );
  if( ValType(AddrOldMes) == V_MEMADDR )
     SetBuff( Oldwlmes,  addrOldMes );
     Recreate = true;
  end;

  PrintLog(2,"Генерация сообщения по МТ202COV");
  RsPaym = RsbPayment( wlpmpaym.PaymentID );
  
  IsTransit = (((RsPaym.PayerGroup == PAYMENTS_GROUP_EXTERNAL) AND (RsPaym.ReceiverGroup == PAYMENTS_GROUP_EXTERNAL)));  
  var InMesID = 0;
  var OutPaym = IsOutPaym(RsPaym);
  var IsChild = PM_PaymentIsChildTransit( RsPaym.PaymentID );
  if(IsTransit)
    InMesID = getInMesIDByPayment(RsPaym);
  end;

  var CommissCode = GetCommisCode (RsPaym.ComissCharges);

  if( not УстановитьКонтекстБлока( "Sequence A" ) )
    RunError("|Ошибка при установке контекста блока 'A'");
  end;

  //Последовательность A  
  /* 20 - номер транзакции (документа) */
  ЗаписатьПолеЛог( TransactionReferenceNumberField, wlmes.TRN );

  /* 21 - Ссылка на документ или сделку */
  if ( not IsChild and OutPaym)
    WriteFieldEx  (RelatedReferenceField, wlmes.RelatedRef, Recreate, OldwlMes );
  elif(IsChild  and (isTransit or OutPaym) and InMesID)
    field_value = "";
    if(not ПолучитьПоле( InMesID, RelatedReferenceField, field_value ))
      InitError();
    end;     
    WriteFieldEx  (RelatedReferenceField, field_value, Recreate, OldwlMes );
  end;

  /* 32A - дата валютирования, код валюты, сумма */
  field_value = GetSWIFTDate( RsPaym.OutTransferDate ) +
                FillCurrencyOriginalOrderedAmountField( RsPaym );
  WriteFieldEx  (ValueDateCurrencyCodeAmountField_A, field_value, Recreate, OldwlMes );

  /* 52a - банк приказодателя */
  field_value = FillOrderingInstitutionField(RsPaym, Tag, null, "202COV" );

  if(field_value)
    ЗаписатьПолеВБлок( OrderingInstitutionField+Tag, "52a", field_value, Recreate, OldwlMes );
    if( not УстановитьКонтекстБлока( ".." ) )
      RunError("|Ошибка при установке контекста блока 'Sequence A' ");
    end;
  end;

  /* 53a - корреспондент отправителя */
  Tag = SWIFT_Tag_A;
  field_value = FillSenderCorrespondentField(RsPaym, Tag );     

  if(field_value)
    ЗаписатьПолеВБлок( Sender_sCorrespondentField+Tag, "53a", field_value, Recreate, OldwlMes );
    if( not УстановитьКонтекстБлока( ".." ) )
      RunError("|Ошибка при установке контекста блока 'Sequence A' ");
    end;
  end;

  /* 54a - корреспондент получателя */
  Tag = SWIFT_Tag_A;
  field_value = FillReceiverCorrespondentField(RsPaym, Tag );     

  if(field_value)
    ЗаписатьПолеВБлок( Receiver_sCorrespondentField+Tag, "54a", field_value, Recreate, OldwlMes );
    if( not УстановитьКонтекстБлока( ".." ) )
      RunError("|Ошибка при установке контекста блока 'Sequence A' ");
    end;
  end;

  /* 56a - банк посредник */
  Tag = "";
  field_value = FillIntermediaryField(RsPaym, Tag, NULL, "MT202COV" );

  if(field_value)
    ЗаписатьПолеВБлок( IntermediaryField+Tag, "56a", field_value, Recreate, OldwlMes );
    if( not УстановитьКонтекстБлока( ".." ) )
      RunError("|Ошибка при установке контекста блока 'Sequence A' ");
    end;
  end;

  /* 57a - банк бенефициара */
  Tag = "";
  field_value = FillAccountWithInstitutionField(RsPaym, Tag, NULL, "MT202COV" );

  if(field_value)
    ЗаписатьПолеВБлок( AccountWithInstitutionField+Tag, "57a", field_value, Recreate, OldwlMes);
    if( not УстановитьКонтекстБлока( ".." ) )
      RunError("|Ошибка при установке контекста блока 'Sequence A' ");
    end;
  end;

  Tag = "";
  field_value = FillBeneficiaryInstitutionField(RsPaym, Tag, NULL, "MT202COV" );

  if(field_value)
    ЗаписатьПолеВБлок( BeneficiaryInstitutionField+Tag, "58a", field_value, Recreate, OldwlMes);
    if( not УстановитьКонтекстБлока( ".." ) )
      RunError("|Ошибка при установке контекста блока 'Sequence A' ");
    end;
  end;                                                                                                     

  /* 72 - информация для банка-получателя */
  PaymentDetails = "";
  StrChangeRusXSet(RsPaym.Ground, PaymentDetails);
  field_value = FillInformationOfPaymentField(RsPaym, ALLOWCODES_MT202_STANDART, PaymentDetails);

  WriteFieldEx  (SenderToReceiverInformationField, field_value, Recreate, OldwlMes );
  
  if( not УстановитьКонтекстБлока() )
     RunError("|Ошибка при установке нулевого контекста блока");
  end;
  
  if( not УстановитьКонтекстБлока( "Sequence B" ) )
      RunError("|Ошибка при установке контекста блока 'B'");
  end;

  //Последовательность B
  if(IsTransit  or (OutPaym and IsChild))
    field_value = "";
    if(InMesID)
      
      ПолучитьПоле( InMesID, OrderingCustomerField, field_value );       
      if(field_value)
        ЗаписатьПолеВБлок( OrderingCustomerField + Tag, "50a", field_value, Recreate, OldwlMes);
        if( not УстановитьКонтекстБлока( ".." ) )
          RunError("|Ошибка при установке контекста блока 'Sequence B' ");
        end;
      end;

      ПолучитьПоле( InMesID, OrderingInstitutionField, field_value );
      if(field_value)
        ЗаписатьПолеВБлок( OrderingInstitutionField+Tag, "52a", field_value, Recreate, OldwlMes);
        if( not УстановитьКонтекстБлока( ".." ) )
          RunError("|Ошибка при установке контекста блока 'Sequence B' ");
        end;
      end;

      ПолучитьПоле( InMesID, IntermediaryField, field_value );
      if(field_value)
        ЗаписатьПолеВБлок( IntermediaryField+Tag, "56a", field_value, Recreate, OldwlMes);
        if( not УстановитьКонтекстБлока( ".." ) )
          RunError("|Ошибка при установке контекста блока 'Sequence B' ");
        end;
      end;

      ПолучитьПоле( InMesID, AccountWithInstitutionField, field_value );
      if(field_value)
        ЗаписатьПолеВБлок( AccountWithInstitutionField+Tag, "57a", field_value, Recreate, OldwlMes);
        if( not УстановитьКонтекстБлока( ".." ) )
          RunError("|Ошибка при установке контекста блока 'Sequence B' ");
        end;
      end;

      ПолучитьПоле( InMesID, BeneficiaryCustomerField, field_value );
      if(field_value)
        ЗаписатьПолеВБлок( BeneficiaryCustomerField, "59a", field_value, Recreate, OldwlMes);
        if( not УстановитьКонтекстБлока( ".." ) )
          RunError("|Ошибка при установке контекста блока 'Sequence B' ");
        end;
      end;

      ПолучитьПоле( InMesID, DetailsOfPaymentField, field_value );
      WriteFieldEx(DetailsOfPaymentField, field_value, Recreate, OldwlMes );

      ПолучитьПоле( InMesID, SenderToReceiverInformationField, field_value );
      WriteFieldEx(SenderToReceiverInformationField, field_value, Recreate, OldwlMes );

      ПолучитьПоле( InMesID, CurrencyOriginalOrderedAmountField, field_value );
      WriteFieldEx(CurrencyOriginalOrderedAmountField, field_value, Recreate, OldwlMes );
    end;
  else    
    /* 50A - приказодатель */
    field_value = FillOrderingCustomerField103( RsPaym, Tag );
    if ( field_value=="" )
      std.out( 2, "PaymentID: " + RsPaym.PaymentID );
      RunError( "|Не найден плательщик" );
    else
      ЗаписатьПолеВБлок( OrderingCustomerField + Tag, "50a", field_value, Recreate, OldwlMes);
      if( not УстановитьКонтекстБлока( ".." ) )
        RunError("|Ошибка при установке контекста блока 'Sequence B' ");
      end;
    end;

    /* 52a - банк приказодателя */
    field_value = FillOrderingInstitutionField(RsPaym, Tag );

    if(field_value)
      ЗаписатьПолеВБлок( OrderingInstitutionField+Tag, "52a", field_value, Recreate, OldwlMes);
      if( not УстановитьКонтекстБлока( ".." ) )
        RunError("|Ошибка при установке контекста блока 'Sequence B' ");
      end;
    end;

    /* 56a - банк посредник */
    Tag = "";
    field_value = FillIntermediaryField(RsPaym, Tag, null, "MT202COV" );                                              

    if(field_value)
      ЗаписатьПолеВБлок( IntermediaryField+Tag, "56a", field_value, Recreate, OldwlMes);
      if( not УстановитьКонтекстБлока( ".." ) )
        RunError("|Ошибка при установке контекста блока 'Sequence B' ");
      end;
    end;

    /* 57a - банк бенефициара */
    Tag = "";
    field_value = FillAccountWithInstitutionField(RsPaym, Tag, null, "MT202COV" );

    if(field_value)
      ЗаписатьПолеВБлок( AccountWithInstitutionField+Tag, "57a", field_value, Recreate, OldwlMes);
      if( not УстановитьКонтекстБлока( ".." ) )
        RunError("|Ошибка при установке контекста блока 'Sequence B' ");
      end;
    end;
    
    /* 59 - бенефициар */
    field_value = FillBeneficiaryCopyExternalFld(RsPaym);
    if (field_value != "")
      ЗаписатьПолеВБлок( BeneficiaryCustomerField, "59a", field_value, Recreate, OldwlMes);
    end;
    if (field_value == "")
      if((RsPaym.Receiver < 0) and (RsPaym.ReceiverCode !="" and RsPaym.ReceiverCodeKind ))
        field_value = FillBeneficiaryCustomerField_A( RsPaym );
        if(field_value != "")
          ЗаписатьПолеВБлок( BeneficiaryCustomerField_A, "59a", field_value, Recreate, OldwlMes);
        end;

      elif(RsPaym.Receiver > -1)
        if(RsPaym.ReceiverCode !="" and RsPaym.ReceiverCodeKind )
          field_value = FillBeneficiaryCustomerField_A( RsPaym );
          if(field_value != "")
            ЗаписатьПолеВБлок( BeneficiaryCustomerField_A, "59a", field_value, Recreate, OldwlMes);
          end;
        else
          field_value = FillBeneficiaryCustomerField_F(RsPaym);
          if(field_value != "")
            ЗаписатьПолеВБлок( BeneficiaryCustomerField_F, "59a", field_value, Recreate, OldwlMes);
          end;  
        end;
      else
        field_value = FillBeneficiaryCustomerField( RsPaym );
        if ( field_value!="" )
          ЗаписатьПолеВБлок( BeneficiaryCustomerField, "59a", field_value, Recreate, OldwlMes);  
        end;
      end;       
    end;  

    if(field_value != "")
      if( not УстановитьКонтекстБлока( ".." ) )
        RunError("|Ошибка при установке контекста блока 'Sequence B' ");
      end;
    end;
    
    /* 70  - информация для бенефициара */
    field_value = FillDetailsOfPaymentField( RsPaym, ALLOWCODES70_MT103_STANDART, ОстатокПоля70 );
    WriteFieldEx  (DetailsOfPaymentField, field_value, Recreate, OldwlMes );
    
    /* 72 - информация для банка-получателя */
    if (not IsAllowCode(ALLOWCODES_MT103_STANDART, Field72CodesNZP))
      ОстатокПоля70 = "";
    end;
    field_value = FillInformationOfPaymentField(RsPaym, ALLOWCODES_MT103_STANDART, ОстатокПоля70 );
    if( field_value != "" )
      WriteFieldEx  (SenderToReceiverInformationField, field_value, Recreate, OldwlMes );
    end;
    
    /* 33B - Инструктируемая сумма, валюта */
    WriteField33B( RsPaym, InMesID, CommissCode, Recreate, OldwlMes );

  end;

  return TRUE; /* Успешное завершение */

  OnError(er) /* обработка ошибок */
    ExeptionMessage(er);
    return FALSE;
end;
