/*
  $Name:         ufgd807.mac
  $Module:       Межбанковские расчеты
  $Description:  Генерация УО "Информационное сообщение" по сообщениям УФЭБС ED807
*/

import "ufgendoc.mac", PTInter, likepy, oralib, "pmlib.mac", wltools, bnk_dttmfrmt, bnk_dirfile, bnk_common, convED807;

const RegPath_УДАЛИТЬ_XML_ED807 = "МЕЖБАНКОВСКИЕ РАСЧЕТЫ\\УФЭБС\\УДАЛИТЬ_XML_ED807";

private class TPartInfo
  var PartNo:          integer, /*Номер части*/
      PartQuantity:    integer, /*Количество частей*/
      PartAggregateID: string;  /*Уникальный идентификатор совокупности частей*/
 
  macro Construct()
    PartAggregateID = "";
    PartNo = PartQuantity = 0;
  end;

  Construct();
end;

private class TInitialED
  var EDNo:       integer,   /*Номер ЭС в течение опердня для исходного ЭСИС*/
      EDDate:     date,      /*Дата составления ЭС для исходного ЭСИС*/
      EDAuthor:   string;    /*Уникальный идентификатор составителя ЭС для исходного ЭСИС*/

  macro Construct()
    EDNo = 0;
    EDDate = date(0,0,0);
    EDAuthor = "";
  end;

  Construct();
end;

private class TRstr /*Структура ограничений участника*/
  var Rstr:     string, /*Код ограничения, наложенного на участника*/
      RstrDate: date;   /*Дата начала действия ограничения*/

  macro Construct()
    Rstr = "";
    RstrDate = date(0,0,0);
  end;

  Construct();
end;

private class TAccRstr /*Структура ограничений операций по счету*/
  var AccRstr:     string, /*Код ограничения операций по счету*/
      AccRstrDate: date;   /*Дата начала действия ограничения по счету*/

  macro Construct()
    AccRstr = "";
    AccRstrDate = date(0,0,0);
  end;

  Construct();
end;

private class TSWBIC /*БИК (СФИФТ), соответствующих участнику*/
  var SWBIC:        string, /*БИК (СВИФТ) (по справочнику СВИФТ, стандарт ИСО 9362)*/
      DefaultSWBIC: string; /*Признак использования БИК (СВИФТ) по умолчанию*/

  macro Construct()
    SWBIC = DefaultSWBIC = "";
  end;

  Construct();
end;

private class TAccount /*Информация о счете участника перевода денежных средств*/
  var Account:               string, /*Номер счета*/
      RegulationAccountType: string, /*Тип счета*/
      CK:                    string, /*Контрольный ключ*/
      AccountCBRBIC:         string, /*БИК ПБР, обслуживающего счет участника перевода*/
      DateIn:                date, /*Дата открытия счета*/
      DateOut:               date, /*Дата исключения информации о счете участника*/
      AccountStatus:         string, /*Статус счета*/
      AccRstrList:           TArray; /*Перечень ограничений операций по счету*/
      
  macro Construct()
    Account = RegulationAccountType = CK = AccountCBRBIC = AccountStatus = "";
    DateIn = DateOut = date(0,0,0);
    AccRstrList = TArray();
  end;

  Construct();
end;

class TDirectParticipantAccount /*БИК и счет прямого участника*/
  var BIC:     string, /*БИК прямого участника*/
      Account: string; /*Счет прямого участника*/

  macro Construct()
    Account = BIC = "";
  end;

  Construct();
end;

class TParticipantInfo /*Информация об участнике*/
  var NameP:                       string, /*Наименование участника*/
      EnglName:                     string, /*Наименование участника на английском языке*/
      RegN:                        string, /*Регистрационный порядковый номер*/
      CntrCd:                      string, /*Код страны*/
      Rgn:                         string, /*Код территории*/
      Ind:                         string, /*Индекс*/
      Tnp:                         string, /*Тип населенного пункта*/
      Nnp:                         string, /*Наименование населенного пункта*/
      Adr:                         string, /*Адрес*/
      PrntBIC:                     string, /*БИК головной организации*/
      DateIn:                      date,   /*Дата включения в состав участников перевода*/
      DateOut:                     date,   /*Дата исключения информации об участнике*/
      PtType:                      string, /*Тип участника перевода*/
      Srvcs:                       string, /*Доступные сервисы перевода денежных средств*/
      XchType:                     string, /*Участник обмена*/
      UID:                         string, /*УИС*/
      NPSParticipant:              string, /*Признак участия в ПС БР*/
      ToNPSDate:                   date,   /*Дата включения в список участников ПС БР*/
      ParticipantStatus:           string, /*Статус участника*/
      RstrList:                    TArray, /*Перечень ограничений участника*/
      DirectParticipantAccount:    variant;/*БИК и счет прямого участника*/
      
  macro Construct()
    NameP = EnglName = RegN = CntrCd = Rgn = Ind = Tnp = Nnp = Adr = PrntBIC = PtType = Srvcs = XchType = UID = NPSParticipant = ParticipantStatus = "";
    DateIn = DateOut = ToNPSDate = date(0,0,0);
    RstrList = TArray();
    DirectParticipantAccount = null;
  end;

  Construct();
end;

class TBICDirectoryEntry /*Запись в справочнике БИК*/
  var BIC:             string,  /*БИК участника*/
      ChangeType:      string,  /*Тип изменения*/
      ParticipantInfo: variant, /*Информация об участнике*/
      SWBICS:          TArray,  /*Перечень БИК (СФИФТ), соответствующих участнику*/
      Accounts:        TArray;  /*Информация о счетах участника перевода денежных средств*/
            
  macro Construct()
    BIC = ChangeType = "";
    ParticipantInfo = null;
    SWBICS = TArray();
    Accounts = TArray();
  end;

  Construct();
end;

class TED807MessageFields /*Поля сообщения ED807*/
  var isXMLExists:        bool; /*Флаг наличия данных из прикрепленного XML-файла*/

  var EDNo:              integer,    /*Номер ЭПД в течение опердня*/
      EDDate:            date,       /*Дата составления ЭПД*/
      EDAuthor:          string,     /*Уникальный идентификатор составителя ЭПД*/
      EDReceiver:        string,     /*Уникальный идентификатор получателя ЭС*/
      CreationReason:    string,     /*Код причины формирования ЭСИС*/
      CreationDateTime:  string,     /*Дата и время создания ЭС в формате YYYY-MM-DDThh:mm:ssZ*/
      InfoTypeCode:      string,     /*Вид представления информации*/
      PartInfo:          variant,    /*Информация о части*/
      InitialED:         variant,    /*Идентификаторы исходного ЭСИС*/
      BICDirectoryEntry: TArray;     /*Записи в Справочнике БИК*/

  macro Construct()
    isXMLExists = false;
    EDNo = 0;
    EDDate = date(0,0,0);
    EDAuthor = EDReceiver = CreationReason = InfoTypeCode = CreationDateTime = "";
    BICDirectoryEntry = TArray();
    PartInfo = null;
    InitialED = null;
  end; 

  Construct();
end;

// Макрос чтения полей сообщения ED807
// Входные параметры: ED807MessageFields - структура полей сообщения ED807
macro ReadED807MessageFields( ED807MessageFields:@TED807MessageFields, xml ) : bool
  var fieldname = "", fieldvalue = "", blockname = "";
  var isNeedXMLParse : bool = false;
  var stat : bool = false;
  if( valtype(xml) != V_UNDEF )
    isNeedXMLParse = true;
  end;

  /*Считываем только то, что хранится в полях релиза*/
  while( СчитатьПоле(fieldname, fieldvalue, blockname) )
    if(blockname == "")
      if(fieldname == "EDNo")
        ED807MessageFields.EDNo = int( fieldvalue );
      elif(fieldname == "EDDate")
        ED807MessageFields.EDDate = ToDate( fieldvalue );
      elif(fieldname == "EDAuthor")
        ED807MessageFields.EDAuthor = fieldvalue;
      elif(fieldname == "EDReceiver")
        ED807MessageFields.EDReceiver = fieldvalue;
      elif(fieldname == "CreationReason")
        ED807MessageFields.CreationReason = fieldvalue;
      elif(fieldname == "CreationDateTime")
        ED807MessageFields.CreationDateTime = fieldvalue;
      elif(fieldname == "InfoTypeCode")
        ED807MessageFields.InfoTypeCode = fieldvalue;
      end;
    elif(blockname == "PartInfo")
      if(fieldname == beginField)
        ED807MessageFields.PartInfo = TPartInfo();
      elif(fieldname == "PartNo")
        ED807MessageFields.PartInfo.PartNo = int( fieldvalue );
      elif(fieldname == "PartQuantity")
        ED807MessageFields.PartInfo.PartQuantity = int( fieldvalue );
      elif(fieldname == "PartAggregateID")
        ED807MessageFields.PartInfo.PartAggregateID = fieldvalue;
      end;
    elif(blockname == "InitialED")
      if(fieldname == beginField)
        ED807MessageFields.InitialED = TInitialED();    
      elif(fieldname == "EDNo")
        ED807MessageFields.InitialED.EDNo = int( fieldvalue );
      elif(fieldname == "EDDate")
        ED807MessageFields.InitialED.EDDate = ToDate( fieldvalue );
      elif(fieldname == "EDAuthor")
        ED807MessageFields.InitialED.EDAuthor = fieldvalue;
      end;
    end; 
  end; // while ( СчитатьПоле(fieldname, fieldvalue, blockname) )

  /*Считываем данные прикрепленного XML-файла, если он есть*/
  if( isNeedXMLParse )
    var XmlAttrsElemsArray : TArray;
    stat = GetXMLElementsAndAttributesArray( xml, @XmlAttrsElemsArray, NodeED807 );
    if( stat )
      ED807MessageFields.isXMLExists = true;
      for( var XmlAttrElem, XmlAttrsElemsArray )
        if(XmlAttrElem.BlockName == "BICDirectoryEntry")
          if(XmlAttrElem.FieldName == beginField)
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size] = TBICDirectoryEntry();
          elif(XmlAttrElem.FieldName == "BIC")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].BIC = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "ChangeType")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ChangeType = XmlAttrElem.FieldValue;
          end;
        elif(XmlAttrElem.BlockName == "BICDirectoryEntry\\ParticipantInfo")
          if(XmlAttrElem.FieldName == beginField)
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo = TParticipantInfo();
          elif(XmlAttrElem.FieldName == "NameP")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.NameP = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "EnglName")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.EnglName = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "RegN")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.RegN = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "CntrCd")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.CntrCd = XmlAttrElem.FieldValue;                                  
          elif(XmlAttrElem.FieldName == "Rgn")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.Rgn = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "Ind")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.Ind = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "Tnp")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.Tnp = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "Nnp")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.Nnp = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "Adr")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.Adr = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "PrntBIC")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.PrntBIC = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "DateIn")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.DateIn = ToDate( XmlAttrElem.FieldValue );
          elif(XmlAttrElem.FieldName == "DateOut")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.DateOut = ToDate( XmlAttrElem.FieldValue );
          elif(XmlAttrElem.FieldName == "PtType")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.PtType = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "Srvcs")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.Srvcs = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "XchType")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.XchType = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "UID")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.UID = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "NPSParticipant")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.NPSParticipant = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "ToNPSDate")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.ToNPSDate = ToDate( XmlAttrElem.FieldValue );
          elif(XmlAttrElem.FieldName == "ParticipantStatus")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.ParticipantStatus = XmlAttrElem.FieldValue;
          end;
        elif(XmlAttrElem.BlockName == "BICDirectoryEntry\\ParticipantInfo\\RstrList")
          if(XmlAttrElem.FieldName == beginField)
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.RstrList[
              ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.RstrList.size] = TRstr();
          elif(XmlAttrElem.FieldName == "Rstr")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.RstrList[
              ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.RstrList.size - 1].Rstr = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "RstrDate")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.RstrList[
              ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.RstrList.size - 1].RstrDate = ToDate( XmlAttrElem.FieldValue );
          end;
        elif(XmlAttrElem.BlockName == "BICDirectoryEntry\\ParticipantInfo\\DirectParticipantAccount")
          if(XmlAttrElem.FieldName == beginField)
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.DirectParticipantAccount = TDirectParticipantAccount();
          elif(XmlAttrElem.FieldName == "BIC")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.DirectParticipantAccount.BIC = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "Account")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].ParticipantInfo.DirectParticipantAccount.Account = XmlAttrElem.FieldValue;
          end;
        elif(XmlAttrElem.BlockName == "BICDirectoryEntry\\SWBICS")
          if(XmlAttrElem.FieldName == beginField)
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].SWBICS[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].SWBICS.size] = TSWBIC();
          elif(XmlAttrElem.FieldName == "SWBIC")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].SWBICS[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].SWBICS.size - 1].SWBIC = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "DefaultSWBIC")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].SWBICS[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].SWBICS.size - 1].DefaultSWBIC = XmlAttrElem.FieldValue;
          end;
        elif(XmlAttrElem.BlockName == "BICDirectoryEntry\\Accounts")
          if(XmlAttrElem.FieldName == beginField)
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size] = TAccount();
          elif(XmlAttrElem.FieldName == "Account")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].Account = XmlAttrElem.FieldValue;          
          elif(XmlAttrElem.FieldName == "RegulationAccountType")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].RegulationAccountType = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "CK")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].CK = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "AccountCBRBIC")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].AccountCBRBIC = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "DateIn")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].DateIn = ToDate( XmlAttrElem.FieldValue );
          elif(XmlAttrElem.FieldName == "DateOut")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].DateOut = ToDate( XmlAttrElem.FieldValue );
          elif(XmlAttrElem.FieldName == "AccountStatus")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[ED807MessageFields.BICDirectoryEntry[
              ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].AccountStatus = XmlAttrElem.FieldValue;
          end;
        elif(XmlAttrElem.BlockName == "BICDirectoryEntry\\Accounts\\AccRstrList")
          if(XmlAttrElem.FieldName == beginField)
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[
              ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].AccRstrList[
                ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[
                  ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].AccRstrList.size] = TAccRstr();
          elif(XmlAttrElem.FieldName == "AccRstr")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[
              ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].AccRstrList[
                ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[
                  ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].AccRstrList.size - 1].AccRstr = XmlAttrElem.FieldValue;
          elif(XmlAttrElem.FieldName == "AccRstrDate")
            ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[
              ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].AccRstrList[
                ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts[
                  ED807MessageFields.BICDirectoryEntry[ED807MessageFields.BICDirectoryEntry.size - 1].Accounts.size - 1].AccRstrList.size - 1].AccRstrDate = ToDate( XmlAttrElem.FieldValue );
          end;
        end;
      end;
    else
      isNeedXMLParse = false;
    end;
  end;

  return TRUE;
end;

macro GenDoc( addrMes )
  var FileDirectory = Bnk_GetTxtFileDir();
  var Narrative : string = "";
  SetBuff( wlmes, addrMes );
  ClearRecord( wlinfo );
  PrintLog( 2, "Генерация информационного сообшения по ED807" );

  var ED807MessageFields = TED807MessageFields();
  ReadED807MessageFields( @ED807MessageFields );

  var tmpPartyID = 0;
  
  wlinfo.TRN                = wlmes.Trn;
  wlinfo.RelatedRef         = wlmes.RelatedRef;
  wlinfo.Direct             = "X"; /*WLD_MES_IN*/

  wlinfo.OriginatorCode     = ED807MessageFields.EDAuthor;
  wlinfo.OriginatorCodeKind = PTCK_UIS; 
  tmpPartyID = 0;
  tmpPartyID = GetCodeOwnerID( wlinfo.OriginatorCodeKind, wlinfo.OriginatorCode );
  if( tmpPartyID > 0 )
    wlinfo.OriginatorID       = tmpPartyID;
    wlinfo.OriginatorName     = Bnk_GetPartyName( wlinfo.OriginatorID );
  end;

  wlinfo.RecipientCode      = wlmes.InsideAbonentCode;
  wlinfo.RecipientCodeKind  = wlmes.InsideAbonentCodeKind;
  tmpPartyID = 0;
  tmpPartyID = GetCodeOwnerID( wlinfo.RecipientCodeKind, wlinfo.RecipientCode ); 
  if( tmpPartyID > 0 )
    wlinfo.RecipientID        = tmpPartyID;
    wlinfo.RecipientName      = Bnk_GetPartyName( wlinfo.RecipientID );
  end;
  
  Narrative = "CreationReason (код причины формирования ЭС): " + ED807MessageFields.CreationReason + " " + 
              GetWlcodeDescription( TYPE_CODE_UFBS_ED807_CREATIONREASON, ED807MessageFields.CreationReason ) + "\n";

  var CreationDate = "", CreationTime = "";
  DivideYYYY_MM_DDThhmmssZToDateTime( ED807MessageFields.CreationDateTime, @CreationDate, @CreationTime );
  Narrative = Narrative + "CreationDate (дата создания ЭС): " + CreationDate + " " + 
                          "CreationTime (время создания ЭС): " + CreationTime + "\n";

  Narrative = Narrative + "InfoTypeCode (вид информации): " + ED807MessageFields.InfoTypeCode + " " + 
                          GetWlcodeDescription( TYPE_CODE_UFBS_ED807_INFOTYPECODE, ED807MessageFields.InfoTypeCode ) + "\n";

  if( ED807MessageFields.PartInfo != null )            
    Narrative = Narrative +  "PartInfo (информация о части): " + " номер части " + ED807MessageFields.PartInfo.PartNo + 
                                                                 ", количество частей " + ED807MessageFields.PartInfo.PartQuantity +
                                                                 ", уникальный идентификатор совокупности частей " + ED807MessageFields.PartInfo.PartAggregateID + "\n";
  end;
  
  if( not ВставитьИнфСообщение( wlinfo, Narrative ) )
    std.msg( "Ошибка при генерации УО по сообщению ED807" );
    return FALSE;
  end;

  /*Обновление справочника БИК*/
  var stat = true;
  var ErrMsg = "";

  var ImageID = 0;
  var sWlMesID : string = makeObjectID( OBJTYPE_MES, null, wlmes );
  ImageID = Bnk_GetImageID( OBJTYPE_MES, sWlMesID, WLD_MES_IMGTYPE_XML_FILE );
  if( ImageID > 0 )
    /* Записываем прикрепленный ED807 во временный XML-файл */
    var tmpXMLFileName = FileDirectory + "\\" + wlmes.TRN + ".xml";
    stat = WEB_ShowImageByID( ImageID, tmpXMLFileName );
    if( stat )
      var InitialMesID = GetOutMesIdInOperDprt( TRANSP_UFBS, wlmes.RelatedRef );
      stat = not RunImportED807( tmpXMLFileName, wlmes.MesID, InitialMesID );
    end;
    /* Удаляем временный XML-файл с ED807 */
    RemoveFile( tmpXMLFileName );
  else
    stat = false;
  end;

  if( stat )
    var NeedDelFile : bool = Bnk_GetRegistryValue( RegPath_УДАЛИТЬ_XML_ED807, V_BOOL, false );
    if( NeedDelFile and ImageID ) /*Удаляем прикрепленный объект*/
      stat = WEB_DeleteImage( ImageID );
    end;
  else
    std.msg( "Не удалось обновить данные Справочника БИК в списке субъектов. Ошибка: " + ErrMsg );
    return FALSE;
  end;

  return TRUE;

  OnError(er) /* Обработка ошибок времени выполнения */
    std.msg(String(er.Message, "|Модуль: ", er.Module, " Строка: ", er.Line));
    return FALSE;
end;