/****************************************************************************/
/*                   R-Style SoftWare Lab, RS-Bank 5.1                      */
/****************************************************************************/
/*                  Подсистема "Межбанковские расчеты"                      */
/*  Проверка сквитованности платежа                                         */
/*                                                                          */
/*  Имя файла: w110_210.mac                                                 */
/*  Создан:  17.05.00                                        Алешин А.В.    */
/****************************************************************************/
import InsCarryDoc, BankInter, OprInter, RMInter, "rmconst.mac", "wlglobal.mac", "cbsttls.mac";

RECORD Corschem( corschem );

var PaymentObj:RsbPayment;

const DEBET  = "Д",
      KREDIT = "К";

const Menu1 = "Поместить в картотеку";
const Menu2 = "Вернуть отправителю";
const Menu3 = "Вернуть на повторную обработку";
const ActionName = "Действие:";

/**********************************/
/* Выполнение шага                */
/**********************************/
macro ExecuteCaseStep( Kind_Operation, Number_Step, first, KindDoc )
  var stat:integer = 0, KvitType:bool, Cancel:string, menu_item;

     Cancel=KVIT_NORMAL;

  if( GetOprStatus(OPR_PAYM_KVT) != OPR_PM_ST_UNKVIT ) /* Переход к шагу "Обработка исходящего" */
     if ( Cancel==KVIT_NORMAL )
       if ( УстановитьСтатусыПлатежа(OPR_PAYM_STATE, OPR_PM_ST_CLOSE) )
          MsgBox("Возникла ошибка при смене статусов операции платежа");
          return 1;
       end;
       PaymentObj.PropStatus = PM_PROP_CLOSED;
       PaymentObj.Paymstatus = PM_FINISHED;
       return "";
     else
        /* Была квитовка отказом */
        if ( Corschem.IsNostro="X" )
           menu_item = Opr_MakeChoice(Menu1, Menu2, Menu3, ActionName);
        else
           menu_item = Opr_MakeChoice(Menu2, Menu3, ActionName);
           if ( menu_item>=0 )
              menu_item = menu_item + 1;
           end;
        end;
        PaymentObj.PropStatus =  PM_PROP_CORREJECTED; 
        if ( menu_item==0 ) /* Поместить в картотеку */
/*          if ( УстановитьСтатусыПлатежа(OPR_PAYM_DO, OPR_PM_ST_NOSTRO_CARD) )
             MsgBox("Возникла ошибка при смене статусов операции платежа");
             return 1;
          end;*/
        elif ( menu_item==1 ) /* Вернуть отправителю */
          if ( УстановитьСтатусыПлатежа(OPR_PAYM_DO, OPR_PM_ST_RETURN) )
             MsgBox("Возникла ошибка при смене статусов операции платежа");
             return 1;
          end;
        elif ( menu_item==2 ) /* Вернуть на повторную обработку */
          PaymentObj.PropStatus = PM_PROP_READY;
          if ( УстановитьСтатусыПлатежа(OPR_PAYM_DO, OPR_PM_ST_POS) )
             MsgBox("Возникла ошибка при смене статусов операции платежа");
             return 1;
          end;
        else
          return 1;
        end;
        return "";
     end;
  else
     return string(НомерШагаКвитовкаМБРИсходящего);  /* Несквитованный */
  end;
end;