/****************************************************************************/
/*                   R-Style SoftWare Lab, RS-Bank 5.1                      */
/****************************************************************************/
/*                  Подсистема "Межбанковские расчеты"                      */
/*                                                                          */
/*  Выписка МЦИ о состоянии корсчета                                        */
/*                                                                          */
/*  Создан:     15.03.2001                                                  */
/*  Программист Бурцев А.А.                                                 */
/****************************************************************************/

import "wlmcgd.mac", FIInter;

macro GenDoc( addrMes )
  var error, Currency, val;

  SetBuff( wlmes, addrMes );

  PrintLog(2,"Генерация выписки по E0008");

  ClearRecord(wlhead);

  if( not СчитатьПоле( FormFldDoc, val ) )
    return FALSE;
  end;

  /* Заполнение учетных буферов */
  wlhead.FIID         = 0;
  wlhead.Corschem     = ПолучитьКорсхемуПоУмолчанию( wlmes.OutsideAbonentID, wlhead.FIID, 1 );
  if( wlhead.Corschem == -1 )
    Currency = ПолучитьКодФинИн(wlhead.FIID, error);
    if ( error )
       Currency = "???";
    end;
    std.msg( "Не определена схема расчетов для респондента по валюте " + Currency );
    return FALSE;
  end;

  wlhead.Number       = Trim(substr(val,6,10));
  wlhead.Account      = substr(val,51,20);
  wlhead.DateIn       = СчитатьДату(val,72);
  wlhead.DateOut      = СчитатьДату(val,100);
  wlhead.RestIn       = moneyL(substr(val,81, 18))/100;
  wlhead.RestOut      = moneyL(substr(val,109,18))/100;

  if( not ВставитьЗаголовокВыписки( wlhead ) )
    std.msg("Ошибка при сохранении заголовка выписки");
    return FALSE;
  end;

  return TRUE;

  OnError(er) /* обработка ошибок времени выполнения */
    ExeptionMessage(er);
    return FALSE;
end;


