/*
$Name:          f401PartView.mac
$Module:        Отчеты ЦБ
$Description:   Форма 401. Печатное представления разделов.
*/

/**
 * Форма 401. Печатное представление раздела 1.
 *
 * @since 20.11.2018
 * @author ABP
 * @version 6.20.031.054
 */
class (RcbPartView) TF401Part1View_4212(reportView)
    private var m_rowsData : Object;
    private var m_isPartHeaderNotPrinted : Bool;
    private var m_bankName : String;
    private var m_unappropriated : Object; // таблица для строки с нераспределенной прибылью (убытком)

    private macro getRowName(code)
        for (var row, m_rowsData)
            if (row.code == code)
                return row.name;
            end;
        end;
        return null;
    end;

    private macro initialize()
        m_table.addColumn("1", 05, AL_CENTER);
        m_table.addColumn("2", 22, AL_LEFT);
        m_table.addColumn("3", 13, AL_RIGHT);
        m_table.addColumn("4", 13, AL_RIGHT);
        m_table.addColumn("5", 13, AL_RIGHT);
        m_table.addColumn("6", 13, AL_RIGHT);
        m_table.addColumn("7", 13, AL_RIGHT);
        m_table.addColumn("8", 13, AL_RIGHT);

        m_table.setUseColumnNumbering(false);
    end;

    private macro getSheetIndexText(sheetIndex, sheetsAmount)
        return "Наименование кредитной организации " + m_bankName + ". Стр." + sheetIndex + " из " + sheetsAmount;
    end;

    macro getWidth(sheetsAmount)
        return max(m_table.getSumLen(), strlen(getSheetIndexText(sheetsAmount, sheetsAmount)));
    end;

    macro printHead()
        m_isPartHeaderNotPrinted = true;
        m_reportView.getNamesZone().clearExcludeAttributes();
    end;

    macro printSheetHead(sheetsAmount, sheetIndex, nrCode, currencyCode)
        macro formatCode(code)
            var str = "";
            for (var char, strTransferByWord(code, 1))
                str = str + "│  " + char + "  ";
            end;
            return substr(str, 2);
        end;

        var reportWidth = getWidth(sheetsAmount);

        sheetIndex = sheetIndex + 1;
        setParm(2, sheetIndex);
        println();
        println(strAlign(getSheetIndexText(sheetIndex, sheetsAmount), reportWidth, STR_ALIGN_LEFT));

        if (m_isPartHeaderNotPrinted)
            println();
            println(strAlign("Раздел 1. Движение иностранных активов отчитывающегося банка и доходы, начисленные к получению по ним", reportWidth, STR_ALIGN_CENTER));
            m_isPartHeaderNotPrinted = false;
        end;

        [ ];
        [┌─────────────────┐  ┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐];
        [│Код нерезидента  │  │###########################################################################################################│](formatCode(nrCode));
        [└─────────────────┘  ├─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┤];
        [                     │           │     │                 │     │                 │     │       вид       │     │   предприятие   │];
        [                     │    тип    │  /  │     сектор      │  /  │     страна      │  /  │   деятельности  │  /  │  специального   │];
        [                     │           │     │                 │     │                 │     │                 │     │   назначения    │];
        [                     └───────────┴─────┴─────────────────┴─────┴─────────────────┴─────┴─────────────────┴─────┴─────────────────┘];
        [ ];
        [┌─────────────────┐  ┌─────┬─────┬─────┐];
        [│Код валюты актива│  │#################│](formatCode(currencyCode));
        [└─────────────────┘  └─────┴─────┴─────┘];

        println();
        m_reportView.getNamesZone().printUnitName(reportWidth);
        [┌───────┬────────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┐];
        [│Номер  │Наименование показателя │  Остаток на   │  Изменение    │  Изменение    │    Прочие     │  Остаток на   │ Начисленные   │];
        [│строки │                        │    начало     │  активов в    │  активов в    │  изменения    │    конец      │  проценты и   │];
        [│       │                        │  отчетного    │  результате   │  результате   │    активов    │  отчетного    │ объявленные   │];
        [│       │                        │    периода    │   операций    │переоценки (гр.│               │   периода     │ дивиденды в   │];
        [│       │                        │               │               │5 - гр.1 -гр.2 │               │               │   отчетном    │];
        [│       │                        │               │               │    - гр.4)    │               │               │    периоде    │];
        [│       │                        ├───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];
        [│       │                        │       1       │       2       │       3       │       4       │       5       │       6       │];
        [├───────┼────────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];

        m_table.setEmpty();
    end;

    macro printString(rowCode, value)
        var valueArray = RcbArray();
        valueArray.push_back(rowCode);
        valueArray.push_back(getRowName(rowCode));
        valueArray.push_back(ternary(value.getIncomeRest().isDefined(), value.getIncomeRest().currentAsString, ""));

        if (rowCode == "А30")
            m_table.printBottom();
            [ ];
            [┌───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────┐];
            m_unappropriated.printStringTransferByWord(valueArray);
        else
            valueArray.push_back(ternary(value.getTurns().isDefined(), value.getTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getRevaluationTurns().isDefined(), value.getRevaluationTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getOtherTurns().isDefined(), value.getOtherTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getOutgoingRest().isDefined(), value.getOutgoingRest().currentAsString, ""));
            if ((rowCode == "А1") or (rowCode == "А2"))
                valueArray.push_back(strAlign("X", m_table.getAColumns()[m_table.getAColumns().size-1].getLen()/2+m_table.getIndent(), STR_ALIGN_LEFT));
            else
                valueArray.push_back(ternary(value.getInterests().isDefined(), value.getInterests().currentAsString, ""));
            end;
            printString(valueArray);
        end;
    end;

    macro printBottom()
        m_unappropriated.printBottom();
    end;

    private macro constructorTF401Part1View_4212(reportView)
        initRcbPartView(TF401Global().getPart1Id(), reportView);
        m_rowsData = TF401Part1RowsData();
        m_isPartHeaderNotPrinted = null;
        m_bankName = trim(m_reportView.getNamesZone().getLendingAgencyName());

        m_unappropriated = CTableReport();
        m_unappropriated.addColumn("1", m_table.getAColumns()[0].getLen(), AL_CENTER);
        var unappropriatedColLength = m_table.getWidthBeforeCol(m_table.getAColumns().size-1)
                                    - 2*m_table.getIndent()
                                    - m_unappropriated.getAColumns()[0].getLen()
                                    - 2*m_unappropriated.getIndent()
                                    - ternary(not m_unappropriated.getShadow(), 1, 0)
                                    - ternary(not m_unappropriated.getInShadow(), 1*1/*количество предшествующих колонок*/, 0);
        m_unappropriated.addColumn("2", unappropriatedColLength, AL_LEFT);
        m_unappropriated.addColumn("3", m_table.getAColumns()[m_table.getAColumns().size-1].getLen(), AL_RIGHT);
        m_unappropriated.setUseColumnNumbering(false);
    end;

    constructorTF401Part1View_4212(reportView);
end;

/**
 * Форма 401. Печатное представление раздела 1.
 *
 * @since 14.01.2019
 * @author ABP
 * @version 6.20.031.054
 */
class (RcbPartView) TF401Part1View_4927(reportView)
    private var m_rowsData : Object;
    private var m_isPartHeaderNotPrinted : Bool;
    private var m_bankName : String;
    private var m_unappropriated : Object; // таблица для строки с нераспределенной прибылью (убытком)

    private macro getRowName(code)
        for (var row, m_rowsData)
            if (row.code == code)
                return row.name;
            end;
        end;
        return null;
    end;

    private macro initialize()
        m_table.addColumn("1", 05, AL_CENTER);
        m_table.addColumn("2", 22, AL_LEFT);
        m_table.addColumn("3", 13, AL_RIGHT);
        m_table.addColumn("4", 13, AL_RIGHT);
        m_table.addColumn("5", 13, AL_RIGHT);
        m_table.addColumn("6", 13, AL_RIGHT);
        m_table.addColumn("7", 13, AL_RIGHT);
        m_table.addColumn("8", 13, AL_RIGHT);

        m_table.setUseColumnNumbering(false);
    end;

    private macro getSheetIndexText(sheetIndex, sheetsAmount)
        return "Наименование кредитной организации " + m_bankName + ". Стр." + sheetIndex + " из " + sheetsAmount;
    end;

    macro getWidth(sheetsAmount)
        return max(m_table.getSumLen(), strlen(getSheetIndexText(sheetsAmount, sheetsAmount)));
    end;

    macro printHead()
        m_isPartHeaderNotPrinted = true;
        m_reportView.getNamesZone().clearExcludeAttributes();
    end;

    macro printSheetHead(sheetsAmount, sheetIndex, nrCode, currencyCode)
        macro formatCode(code)
            var str = "";
            for (var char, strTransferByWord(code, 1))
                str = str + "│  " + char + "  ";
            end;
            return substr(str, 2);
        end;

        var reportWidth = getWidth(sheetsAmount);

        sheetIndex = sheetIndex + 1;
        setParm(2, sheetIndex);
        println();
        println(strAlign(getSheetIndexText(sheetIndex, sheetsAmount), reportWidth, STR_ALIGN_LEFT));

        if (m_isPartHeaderNotPrinted)
            println();
            println(strAlign("Раздел 1. Движение иностранных активов уполномоченного банка и доходы, начисленные к получению по ним", reportWidth, STR_ALIGN_CENTER));
            m_isPartHeaderNotPrinted = false;
        end;

        [ ];
        [┌─────────────────┐  ┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐];
        [│Код нерезидента  │  │###########################################################################################################│](formatCode(nrCode));
        [└─────────────────┘  ├─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┤];
        [                     │           │     │                 │     │                 │     │       вид       │     │   предприятие   │];
        [                     │    тип    │  /  │     сектор      │  /  │     страна      │  /  │   деятельности  │  /  │  специального   │];
        [                     │           │     │                 │     │                 │     │                 │     │   назначения    │];
        [                     └───────────┴─────┴─────────────────┴─────┴─────────────────┴─────┴─────────────────┴─────┴─────────────────┘];
        [ ];
        [┌─────────────────┐  ┌─────┬─────┬─────┐];
        [│Код валюты актива│  │#################│](formatCode(currencyCode));
        [└─────────────────┘  └─────┴─────┴─────┘];

        println();
        m_reportView.getNamesZone().printUnitName(reportWidth);
        [┌───────┬────────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┐];
        [│Номер  │Наименование показателя │  Остаток на   │  Изменение    │  Изменение    │    Прочие     │  Остаток на   │ Начисленные   │];
        [│строки │                        │    начало     │  активов в    │  активов в    │  изменения    │    конец      │  проценты и   │];
        [│       │                        │  отчетного    │  результате   │  результате   │    активов    │  отчетного    │ объявленные   │];
        [│       │                        │    периода    │   операций    │переоценки (гр.│               │   периода     │ дивиденды в   │];
        [│       │                        │               │               │5 - гр.1 -гр.2 │               │               │   отчетном    │];
        [│       │                        │               │               │    - гр.4)    │               │               │    периоде    │];
        [│       │                        ├───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];
        [│       │                        │       1       │       2       │       3       │       4       │       5       │       6       │];
        [├───────┼────────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];

        m_table.setEmpty();
    end;

    macro printString(rowCode, value)
        var valueArray = RcbArray();
        valueArray.push_back(rowCode);
        valueArray.push_back(getRowName(rowCode));
        valueArray.push_back(ternary(value.getIncomeRest().isDefined(), value.getIncomeRest().currentAsString, ""));

        if (rowCode == "А30")
            m_table.printBottom();
            [ ];
            [┌───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────┐];
            m_unappropriated.printStringTransferByWord(valueArray);
        else
            valueArray.push_back(ternary(value.getTurns().isDefined(), value.getTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getRevaluationTurns().isDefined(), value.getRevaluationTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getOtherTurns().isDefined(), value.getOtherTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getOutgoingRest().isDefined(), value.getOutgoingRest().currentAsString, ""));
            if ((rowCode == "А1") or (rowCode == "А2"))
                valueArray.push_back(strAlign("X", m_table.getAColumns()[m_table.getAColumns().size-1].getLen()/2+m_table.getIndent(), STR_ALIGN_LEFT));
            else
                valueArray.push_back(ternary(value.getInterests().isDefined(), value.getInterests().currentAsString, ""));
            end;
            printString(valueArray);
        end;
    end;

    macro printBottom()
        m_unappropriated.printBottom();
    end;

    private macro constructorTF401Part1View_4927(reportView)
        initRcbPartView(TF401Global().getPart1Id(), reportView);
        m_rowsData = TF401Part1RowsData();
        m_isPartHeaderNotPrinted = null;
        m_bankName = trim(m_reportView.getNamesZone().getLendingAgencyName());

        m_unappropriated = CTableReport();
        m_unappropriated.addColumn("1", m_table.getAColumns()[0].getLen(), AL_CENTER);
        var unappropriatedColLength = m_table.getWidthBeforeCol(m_table.getAColumns().size-1)
                                    - 2*m_table.getIndent()
                                    - m_unappropriated.getAColumns()[0].getLen()
                                    - 2*m_unappropriated.getIndent()
                                    - ternary(not m_unappropriated.getShadow(), 1, 0)
                                    - ternary(not m_unappropriated.getInShadow(), 1*1/*количество предшествующих колонок*/, 0);
        m_unappropriated.addColumn("2", unappropriatedColLength, AL_LEFT);
        m_unappropriated.addColumn("3", m_table.getAColumns()[m_table.getAColumns().size-1].getLen(), AL_RIGHT);
        m_unappropriated.setUseColumnNumbering(false);
    end;

    constructorTF401Part1View_4927(reportView);
end;

/**
 * Форма 401. Печатное представление раздела 2.
 *
 * @since 20.11.2018
 * @author ABP
 * @version 6.20.031.054
 */
class (RcbPartView) TF401Part2View_4212(reportView)
    private var m_rowsData : Object;
    private var m_isPartHeaderNotPrinted : Bool;
    private var m_bankName : String;
    private var m_unappropriated : Object; // таблица для строки с нераспределенной прибылью (убытком)

    private macro getRowName(code)
        for (var row, m_rowsData)
            if (row.code == code)
                return row.name;
            end;
        end;
        return null;
    end;

    private macro initialize()
        m_table.addColumn("1", 05, AL_CENTER);
        m_table.addColumn("2", 22, AL_LEFT);
        m_table.addColumn("3", 13, AL_RIGHT);
        m_table.addColumn("4", 13, AL_RIGHT);
        m_table.addColumn("5", 13, AL_RIGHT);
        m_table.addColumn("6", 13, AL_RIGHT);
        m_table.addColumn("7", 13, AL_RIGHT);
        m_table.addColumn("8", 13, AL_RIGHT);

        m_table.setUseColumnNumbering(false);
    end;

    private macro getSheetIndexText(sheetIndex, sheetsAmount)
        return "Наименование кредитной организации " + m_bankName + ". Стр." + sheetIndex + " из " + sheetsAmount;
    end;

    macro getWidth(sheetsAmount)
        return max(m_table.getSumLen(), strlen(getSheetIndexText(sheetsAmount, sheetsAmount)));
    end;

    macro printHead()
        m_isPartHeaderNotPrinted = true;
        m_reportView.getNamesZone().clearExcludeAttributes();
    end;

    macro printSheetHead(sheetsAmount, sheetIndex, nrCode, currencyCode)
        macro formatCode(code)
            var str = "";
            for (var char, strTransferByWord(code, 1))
                str = str + "│  " + char + "  ";
            end;
            return substr(str, 2);
        end;

        var reportWidth = getWidth(sheetsAmount);

        sheetIndex = sheetIndex + 1;
        setParm(2, sheetIndex);
        println();
        println(strAlign(getSheetIndexText(sheetIndex, sheetsAmount), reportWidth, STR_ALIGN_LEFT));

        if (m_isPartHeaderNotPrinted)
            println();
            println(strAlign("Раздел 2. Движение иностранных пассивов (обязательств перед нерезидентами) и доходы, начисленные к выплате по ним", reportWidth, STR_ALIGN_CENTER));
            m_isPartHeaderNotPrinted = false;
        end;

        [ ];
        [┌─────────────────┐  ┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐];
        [│Код нерезидента  │  │###########################################################################################################│](formatCode(nrCode));
        [└─────────────────┘  ├─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┤];
        [                     │           │     │                 │     │                 │     │       вид       │     │   предприятие   │];
        [                     │    тип    │  /  │     сектор      │  /  │     страна      │  /  │   деятельности  │  /  │  специального   │];
        [                     │           │     │                 │     │                 │     │                 │     │   назначения    │];
        [                     └───────────┴─────┴─────────────────┴─────┴─────────────────┴─────┴─────────────────┴─────┴─────────────────┘];
        [ ];
        [┌──────────────────┐  ┌─────┬─────┬─────┐];
        [│Код валюты пассива│  │#################│](formatCode(currencyCode));
        [└──────────────────┘  └─────┴─────┴─────┘];

        println();
        m_reportView.getNamesZone().printUnitName(reportWidth);
        [┌───────┬────────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┐];
        [│Номер  │Наименование показателя │  Остаток на   │  Изменение    │  Изменение    │    Прочие     │  Остаток на   │ Начисленные   │];
        [│строки │                        │    начало     │  пассивов в   │  пассивов в   │  изменения    │    конец      │  проценты и   │];
        [│       │                        │  отчетного    │  результате   │  результате   │   пассивов    │  отчетного    │ объявленные   │];
        [│       │                        │    периода    │   операций    │переоценки (гр.│               │   периода     │ дивиденды в   │];
        [│       │                        │               │               │5 - гр.1 -гр.2 │               │               │   отчетном    │];
        [│       │                        │               │               │    - гр.4)    │               │               │    периоде    │];
        [│       │                        ├───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];
        [│       │                        │       1       │       2       │       3       │       4       │       5       │       6       │];
        [├───────┼────────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];

        m_table.setEmpty();
    end;

    macro printString(rowCode, value)
        var valueArray = RcbArray();
        valueArray.push_back(rowCode);
        valueArray.push_back(getRowName(rowCode));
        valueArray.push_back(ternary(value.getIncomeRest().isDefined(), value.getIncomeRest().currentAsString, ""));

        if (rowCode == "П30")
            m_table.printBottom();
            [ ];
            [┌───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────┐];
            m_unappropriated.printStringTransferByWord(valueArray);
        else
            valueArray.push_back(ternary(value.getTurns().isDefined(), value.getTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getRevaluationTurns().isDefined(), value.getRevaluationTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getOtherTurns().isDefined(), value.getOtherTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getOutgoingRest().isDefined(), value.getOutgoingRest().currentAsString, ""));
            valueArray.push_back(ternary(value.getInterests().isDefined(), value.getInterests().currentAsString, ""));
            printString(valueArray);
        end;
    end;

    macro printBottom()
        m_unappropriated.printBottom();
    end;

    private macro constructorTF401Part2View_4212(reportView)
        initRcbPartView(TF401Global().getPart2Id(), reportView);
        m_rowsData = TF401Part2RowsData();
        m_isPartHeaderNotPrinted = null;
        m_bankName = trim(m_reportView.getNamesZone().getLendingAgencyName());

        m_unappropriated = CTableReport();
        m_unappropriated.addColumn("1", m_table.getAColumns()[0].getLen(), AL_CENTER);
        var unappropriatedColLength = m_table.getWidthBeforeCol(m_table.getAColumns().size-1)
                                    - 2*m_table.getIndent()
                                    - m_unappropriated.getAColumns()[0].getLen()
                                    - 2*m_unappropriated.getIndent()
                                    - ternary(not m_unappropriated.getShadow(), 1, 0)
                                    - ternary(not m_unappropriated.getInShadow(), 1*1/*количество предшествующих колонок*/, 0);
        m_unappropriated.addColumn("2", unappropriatedColLength, AL_LEFT);
        m_unappropriated.addColumn("3", m_table.getAColumns()[m_table.getAColumns().size-1].getLen(), AL_RIGHT);
        m_unappropriated.setUseColumnNumbering(false);
    end;

    constructorTF401Part2View_4212(reportView);
end;

/**
 * Форма 401. Печатное представление раздела 2.
 *
 * @since 14.01.2019
 * @author ABP
 * @version 6.20.031.054
 */
class (RcbPartView) TF401Part2View_4927(reportView)
    private var m_rowsData : Object;
    private var m_isPartHeaderNotPrinted : Bool;
    private var m_bankName : String;
    private var m_unappropriated : Object; // таблица для строки с нераспределенной прибылью (убытком)

    private macro getRowName(code)
        for (var row, m_rowsData)
            if (row.code == code)
                return row.name;
            end;
        end;
        return null;
    end;

    private macro initialize()
        m_table.addColumn("1", 05, AL_CENTER);
        m_table.addColumn("2", 22, AL_LEFT);
        m_table.addColumn("3", 13, AL_RIGHT);
        m_table.addColumn("4", 13, AL_RIGHT);
        m_table.addColumn("5", 13, AL_RIGHT);
        m_table.addColumn("6", 13, AL_RIGHT);
        m_table.addColumn("7", 13, AL_RIGHT);
        m_table.addColumn("8", 13, AL_RIGHT);

        m_table.setUseColumnNumbering(false);
    end;

    private macro getSheetIndexText(sheetIndex, sheetsAmount)
        return "Наименование кредитной организации " + m_bankName + ". Стр." + sheetIndex + " из " + sheetsAmount;
    end;

    macro getWidth(sheetsAmount)
        return max(m_table.getSumLen(), strlen(getSheetIndexText(sheetsAmount, sheetsAmount)));
    end;

    macro printHead()
        m_isPartHeaderNotPrinted = true;
        m_reportView.getNamesZone().clearExcludeAttributes();
    end;

    macro printSheetHead(sheetsAmount, sheetIndex, nrCode, currencyCode)
        macro formatCode(code)
            var str = "";
            for (var char, strTransferByWord(code, 1))
                str = str + "│  " + char + "  ";
            end;
            return substr(str, 2);
        end;

        var reportWidth = getWidth(sheetsAmount);

        sheetIndex = sheetIndex + 1;
        setParm(2, sheetIndex);
        println();
        println(strAlign(getSheetIndexText(sheetIndex, sheetsAmount), reportWidth, STR_ALIGN_LEFT));

        if (m_isPartHeaderNotPrinted)
            println();
            for (var str, strTransferByWord("Раздел 2. Движение иностранных пассивов (обязательств перед нерезидентами) уполномоченного банка и доходы, начисленные к выплате по ним", reportWidth, STR_ALIGN_CENTER))
                println(str);
            end;
            m_isPartHeaderNotPrinted = false;
        end;

        [ ];
        [┌─────────────────┐  ┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐];
        [│Код нерезидента  │  │###########################################################################################################│](formatCode(nrCode));
        [└─────────────────┘  ├─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┼─────┼─────┴─────┴─────┤];
        [                     │           │     │                 │     │                 │     │       вид       │     │   предприятие   │];
        [                     │    тип    │  /  │     сектор      │  /  │     страна      │  /  │   деятельности  │  /  │  специального   │];
        [                     │           │     │                 │     │                 │     │                 │     │   назначения    │];
        [                     └───────────┴─────┴─────────────────┴─────┴─────────────────┴─────┴─────────────────┴─────┴─────────────────┘];
        [ ];
        [┌──────────────────┐  ┌─────┬─────┬─────┐];
        [│Код валюты пассива│  │#################│](formatCode(currencyCode));
        [└──────────────────┘  └─────┴─────┴─────┘];

        println();
        m_reportView.getNamesZone().printUnitName(reportWidth);
        [┌───────┬────────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┐];
        [│Номер  │Наименование показателя │  Остаток на   │  Изменение    │  Изменение    │    Прочие     │  Остаток на   │ Начисленные   │];
        [│строки │                        │    начало     │  пассивов в   │  пассивов в   │  изменения    │    конец      │  проценты и   │];
        [│       │                        │  отчетного    │  результате   │  результате   │   пассивов    │  отчетного    │ объявленные   │];
        [│       │                        │    периода    │   операций    │переоценки (гр.│               │   периода     │ дивиденды в   │];
        [│       │                        │               │               │5 - гр.1 -гр.2 │               │               │   отчетном    │];
        [│       │                        │               │               │    - гр.4)    │               │               │    периоде    │];
        [│       │                        ├───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];
        [│       │                        │       1       │       2       │       3       │       4       │       5       │       6       │];
        [├───────┼────────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];

        m_table.setEmpty();
    end;

    macro printString(rowCode, value)
        var valueArray = RcbArray();
        valueArray.push_back(rowCode);
        valueArray.push_back(getRowName(rowCode));
        valueArray.push_back(ternary(value.getIncomeRest().isDefined(), value.getIncomeRest().currentAsString, ""));

        if (rowCode == "П30")
            m_table.printBottom();
            [ ];
            [┌───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────┐];
            m_unappropriated.printStringTransferByWord(valueArray);
        else
            valueArray.push_back(ternary(value.getTurns().isDefined(), value.getTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getRevaluationTurns().isDefined(), value.getRevaluationTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getOtherTurns().isDefined(), value.getOtherTurns().currentAsString, ""));
            valueArray.push_back(ternary(value.getOutgoingRest().isDefined(), value.getOutgoingRest().currentAsString, ""));
            valueArray.push_back(ternary(value.getInterests().isDefined(), value.getInterests().currentAsString, ""));
            printString(valueArray);
        end;
    end;

    macro printBottom()
        m_unappropriated.printBottom();
    end;

    private macro constructorTF401Part2View_4927(reportView)
        initRcbPartView(TF401Global().getPart2Id(), reportView);
        m_rowsData = TF401Part2RowsData();
        m_isPartHeaderNotPrinted = null;
        m_bankName = trim(m_reportView.getNamesZone().getLendingAgencyName());

        m_unappropriated = CTableReport();
        m_unappropriated.addColumn("1", m_table.getAColumns()[0].getLen(), AL_CENTER);
        var unappropriatedColLength = m_table.getWidthBeforeCol(m_table.getAColumns().size-1)
                                    - 2*m_table.getIndent()
                                    - m_unappropriated.getAColumns()[0].getLen()
                                    - 2*m_unappropriated.getIndent()
                                    - ternary(not m_unappropriated.getShadow(), 1, 0)
                                    - ternary(not m_unappropriated.getInShadow(), 1*1/*количество предшествующих колонок*/, 0);
        m_unappropriated.addColumn("2", unappropriatedColLength, AL_LEFT);
        m_unappropriated.addColumn("3", m_table.getAColumns()[m_table.getAColumns().size-1].getLen(), AL_RIGHT);
        m_unappropriated.setUseColumnNumbering(false);
    end;

    constructorTF401Part2View_4927(reportView);
end;

/**
 * Форма 401. Печатное представление подраздела 3.1.
 *
 * @since 31.05.2019
 * @author ABP
 * @version 6.20.031.057
 */
class (RcbPartView) TF401Part31View_4927(reportView)
    private var m_rowsData : Object;
    private var m_bankName : String;

    private macro getRowName(code)
        for (var row, m_rowsData)
            if (row.code == code)
                return row.name;
            end;
        end;
        return null;
    end;

    private macro initialize()
        m_table.addColumn("01", 06, AL_CENTER);
        m_table.addColumn("02", 05, AL_LEFT);
        m_table.addColumn("03", 11, AL_LEFT);
        m_table.addColumn("04", 13, AL_RIGHT);
        m_table.addColumn("05", 13, AL_RIGHT);
        m_table.addColumn("06", 13, AL_RIGHT);
        m_table.addColumn("07", 13, AL_RIGHT);
        m_table.addColumn("08", 13, AL_RIGHT);
        m_table.addColumn("09", 13, AL_RIGHT);
        m_table.addColumn("10", 13, AL_RIGHT);
        m_table.addColumn("11", 13, AL_RIGHT);
        m_table.addColumn("12", 13, AL_RIGHT);
        m_table.addColumn("13", 13, AL_RIGHT);
        m_table.addColumn("14", 13, AL_RIGHT);
        m_table.addColumn("15", 13, AL_RIGHT);

        m_table.setUseColumnNumbering(true);
    end;

    private macro getSheetIndexText(sheetIndex, sheetsAmount)
        return "Наименование кредитной организации " + m_bankName + ". Стр." + sheetIndex + " из " + sheetsAmount;
    end;

    macro getWidth(sheetsAmount)
        return max(m_table.getSumLen(), strlen(getSheetIndexText(sheetsAmount, sheetsAmount)));
    end;

    macro printHead(sheetsAmount, sheetIndex)
        var reportWidth = getWidth(sheetsAmount);

        sheetIndex = sheetIndex + 1;
        setParm(2, sheetIndex);
        println();
        println(strAlign(getSheetIndexText(sheetIndex, sheetsAmount), reportWidth, STR_ALIGN_LEFT));
        println();
        println(strAlign("Раздел 3. Производные финансовые инструменты", reportWidth, STR_ALIGN_CENTER));

//        m_reportView.getNamesZone().clearExcludeAttributes();
    end;

    macro printSheetHead(sheetsAmount)
        var reportWidth = getWidth(sheetsAmount);

        println();
        println(strAlign("Подраздел 3.1. Опционы и фьючерсы", reportWidth, STR_ALIGN_CENTER));

        println();
        m_reportView.getNamesZone().printUnitName(reportWidth);
        [┌────────┬───────┬─────────────┬───────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────┬───────────────────────────────┐];
        [│        │       │             │                             Опционы, выписанные                               │                             Опционы, купленные                                │      Опционы и фьючерсы,      │];
        [│        │       │             │                               на нерезидентов                                 │                               у нерезидентов                                  │     заключенные на биржах     │];
        [│        │       │             ├───────────────┬───────────────────────────────────────────────┬───────────────┼───────────────┬───────────────────────────────────────────────┬───────────────┼───────────────────────────────┤];
        [│        │       │             │               │             Изменения в отчетном              │               │               │             Изменения в отчетном              │               │         Отклонения по         │];
        [│        │       │             │               │                    периоде                    │               │               │                    периоде                    │               │             марже             │];
        [│        │       │             │               ├───────────────┬───────────────┬───────────────┤               │               ├───────────────┬───────────────┬───────────────┤               ├───────────────┬───────────────│];
        [│ Номер  │ Код   │  Резидент   │  Остаток на   │  Изменения в  │  Переоценка   │    Прочие     │  Остаток на   │  Остаток на   │  Изменения в  │  Переоценка   │    Прочие     │  Остаток на   │ Полученные от │  Выплаченные  │];
        [│ строки │валюты │             │    начало     │  результате   │(гр.8 - гр.4 - │  изменения    │    конец      │    начало     │  результате   │(гр.13 - гр.9 -│  изменения    │    конец      │ нерезидентов  │ нерезидентам  │];
        [│        │       │             │  отчетного    │   операций    │гр.5 - гр.7)   │               │  отчетного    │  отчетного    │   операций    │гр.10 - гр.12) │               │  отчетного    │               │               │];
        [│        │       │             │    периода    │               │               │               │   периода     │    периода    │               │               │               │   периода     │               │               │];
        [├────────┼───────┼─────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];

        m_table.setEmpty();
    end;

    macro printString(value)
        var valueArray = RcbArray();

        valueArray.push_back(value.getRowCode());
        valueArray.push_back(value.getCurrencyCode());
        valueArray.push_back(value.getNrCode());
        valueArray.push_back(value.getIncomeRest().currentAsString);
        valueArray.push_back(value.getTurns().currentAsString);
        valueArray.push_back(value.getRevaluationTurns().currentAsString);
        valueArray.push_back(ternary((value.getNrCode() != "Прочие"), value.getOtherTurns().currentAsString, "X"));
        valueArray.push_back(value.getOutgoingRest().currentAsString);
        valueArray.push_back(value.getRtGroup2IncomeRest().currentAsString);
        valueArray.push_back(value.getRtGroup2Turns().currentAsString);
        valueArray.push_back(value.getRtGroup2RevaluationTurns().currentAsString);
        valueArray.push_back(ternary((value.getNrCode() != "Прочие"), value.getRtGroup2OtherTurns().currentAsString, "X"));
        valueArray.push_back(value.getRtGroup2OutgoingRest().currentAsString);
        valueArray.push_back(value.getStockOptionReceived().currentAsString);
        valueArray.push_back(value.getStockOptionPaid().currentAsString);

        printString(valueArray);
    end;

    macro printBottom()
        m_table.printBottom();
    end;

    private macro constructorTF401Part31View_4927(reportView)
        initRcbPartView(TF401Global().getPart31Id(), reportView);
        m_rowsData = TF401Part31RowsData();
        m_bankName = trim(m_reportView.getNamesZone().getLendingAgencyName());
    end;

    constructorTF401Part31View_4927(reportView);
end;

/**
 * Форма 401. Печатное представление подраздела 3.2.
 *
 * @since 31.05.2019
 * @author ABP
 * @version 6.20.031.057
 */
class (RcbPartView) TF401Part32View_4927(reportView)
    private var m_rowsData : Object;
    private var m_bankName : String;

    private macro getRowName(code)
        for (var row, m_rowsData)
            if (row.code == code)
                return row.name;
            end;
        end;
        return null;
    end;

    private macro initialize()
        m_table.addColumn("01", 06, AL_CENTER);
        m_table.addColumn("02", 05, AL_LEFT);
        m_table.addColumn("03", 11, AL_LEFT);
        m_table.addColumn("04", 13, AL_LEFT);
        m_table.addColumn("05", 13, AL_RIGHT);
        m_table.addColumn("06", 13, AL_RIGHT);
        m_table.addColumn("07", 13, AL_RIGHT);
        m_table.addColumn("08", 13, AL_RIGHT);
        m_table.addColumn("09", 13, AL_RIGHT);
        m_table.addColumn("10", 13, AL_RIGHT);
        m_table.addColumn("11", 13, AL_RIGHT);
        m_table.addColumn("12", 13, AL_RIGHT);
        m_table.addColumn("13", 13, AL_RIGHT);
        m_table.addColumn("14", 13, AL_RIGHT);

        m_table.setUseColumnNumbering(true);
    end;

    private macro getSheetIndexText(sheetIndex, sheetsAmount)
        return "Наименование кредитной организации " + m_bankName + ". Стр." + sheetIndex + " из " + sheetsAmount;
    end;

    macro getWidth(sheetsAmount)
        return max(m_table.getSumLen(), strlen(getSheetIndexText(sheetsAmount, sheetsAmount)));
    end;

    macro printHead(sheetsAmount, sheetIndex)
        var reportWidth = getWidth(sheetsAmount);

        sheetIndex = sheetIndex + 1;
        setParm(2, sheetIndex);
        println();
        println(strAlign(getSheetIndexText(sheetIndex, sheetsAmount), reportWidth, STR_ALIGN_LEFT));
        println();
        println(strAlign("Раздел 3. Производные финансовые инструменты", reportWidth, STR_ALIGN_CENTER));

//        m_reportView.getNamesZone().clearExcludeAttributes();
    end;

    macro printSheetHead(sheetsAmount)
        var reportWidth = getWidth(sheetsAmount);

        println();
        println(strAlign("Подраздел 3.2. Внебиржевые производные финансовые инструменты: процентные, валютные свопы и форварды, прочие контракты форвардного типа", reportWidth, STR_ALIGN_CENTER));

        println();
        m_reportView.getNamesZone().printUnitName(reportWidth);
        [┌────────┬───────┬─────────────┬───────────────┬───────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────┐];
        [│        │       │             │               │                Внебиржевые производные финансовые инструменты                 │                            Прочие срочные сделки                              │];
        [│        │       │             │               ├───────────────┬───────────────────────────────────────────────┬───────────────┼───────────────┬───────────────────────────────────────────────┬───────────────┤];
        [│        │       │             │               │               │             Изменения в отчетном              │               │               │             Изменения в отчетном              │               │];
        [│        │       │             │               │               │                    периоде                    │               │               │                    периоде                    │               │];
        [│        │       │             │               │               ├───────────────┬───────────────┬───────────────┤               │               ├───────────────┬───────────────┬───────────────┤               │];
        [│ Номер  │ Код   │  Резидент   │  Требования   │  Остаток на   │  Изменения в  │  Переоценка   │    Прочие     │  Остаток на   │  Остаток на   │  Изменения в  │  Переоценка   │    Прочие     │  Остаток на   │];
        [│ строки │валюты │             │(обязательства)│    начало     │  результате   │(гр.9 - гр.5 - │  изменения    │    конец      │    начало     │  результате   │(гр.14 - гр.10-│  изменения    │    конец      │];
        [│        │       │             │               │  отчетного    │   операций    │гр.6 - гр.8)   │               │  отчетного    │  отчетного    │   операций    │гр.11 - гр.13) │               │  отчетного    │];
        [│        │       │             │               │    периода    │               │               │               │   периода     │    периода    │               │               │               │   периода     │];
        [├────────┼───────┼─────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤];

        m_table.setEmpty();
    end;

    macro printString(value)
        var valueArray = RcbArray();

        valueArray.push_back(value.getRowCode());
        valueArray.push_back(value.getCurrencyCode());
        valueArray.push_back(value.getNrCode());
        valueArray.push_back(value.getClaimName());
        valueArray.push_back(value.getIncomeRest().currentAsString);
        valueArray.push_back(value.getTurns().currentAsString);
        valueArray.push_back(value.getRevaluationTurns().currentAsString);
        valueArray.push_back(ternary((value.getNrCode() != "Прочие"), value.getOtherTurns().currentAsString, "X"));
        valueArray.push_back(value.getOutgoingRest().currentAsString);
        valueArray.push_back(value.getRtGroup2IncomeRest().currentAsString);
        valueArray.push_back(value.getRtGroup2Turns().currentAsString);
        valueArray.push_back(value.getRtGroup2RevaluationTurns().currentAsString);
        valueArray.push_back(ternary((value.getNrCode() != "Прочие"), value.getRtGroup2OtherTurns().currentAsString, "X"));
        valueArray.push_back(value.getRtGroup2OutgoingRest().currentAsString);

        printString(valueArray);
    end;

    macro printBottom()
        m_table.printBottom();
    end;

    private macro constructorTF401Part32View_4927(reportView)
        initRcbPartView(TF401Global().getPart32Id(), reportView);
        m_rowsData = TF401Part32RowsData();
        m_bankName = trim(m_reportView.getNamesZone().getLendingAgencyName());
    end;

    constructorTF401Part32View_4927(reportView);
end;
