/*
$Name:          f501Attribute.mac
$Module:        Отчеты ЦБ
$Description:   Форма 501. Класс атрибута.
*/

/**
* Форма 501. Атрибут для раздела 1.
* Хранит идентификатор и значение в виде объекта класса, реализующего IF501AttibuteValue
*/

class (RcbAttributeBase) TF501Attribute(id : String, part : Object, value : Object)
    private var m_attributeValue : IF501AttributeValue;

    macro makeId(p1)
        var id;

        if (isEqClass("RcbCompositeValue", p1))
            id = p1.fieldValue("НомЛС").currentAsString;
        else
            id = p1;
        end;

        return id;
    end;

    /**
    * Получить значение атрибута
    */
    macro getValue() : IF501AttributeValue
        return m_attributeValue;
    end;

    /**
    * Проверка существования значения атрибута
    */
    macro isDefined() : Bool
        var isDefinedValue = false;

        if (m_attributeValue != null)
            isDefinedValue = m_attributeValue.isDefined();
        end;

        return isDefinedValue;
    end;

    macro isZero() : Bool
        return m_attributeValue.isZero();
    end;

    macro removeStorage()
        m_attributeValue.removeStorage();
    end;

    private macro constructorTF501AttributePart1(id : String, part : Object, value : Object)
        if (id == null) // ничего не создаём, экземпляр нужен только для вызова "статического" метода makeId
            return;
        end;

        if (value == null)
            value = part.getPartCompositeValue().addValue();
        end;

        if (isEqClass("RcbCompositeValue", value))
            initRcbAttributeBase(id, part, value);
            m_attributeValue = objectFactoryInstance.createAttributeValue(part, value);
        else
            initRcbAttributeBase(id, part, value.getStorage());
            m_attributeValue = value;
        end;
    end;

    constructorTF501AttributePart1(id, part, value);
end;

/**
* Форма 501. Атрибут для раздела 1.
* Хранит идентификатор и значение в виде объекта класса, реализующего IF501AttibuteValue
*/
class (TF501Attribute) TF501AttributePart1(id : String, part : Object, value : Object)
    macro makeId(p1)
        var id;

        if (isEqClass("RcbCompositeValue", p1))
            id = p1.fieldValue("НомЛС").currentAsString;
        else
            id = p1;
        end;

        return id;
    end;

    private macro constructorTF501AttributePart1(id : String, part : Object, value : Object)
        initTF501Attribute(id, part, value);
    end;

    constructorTF501AttributePart1(id, part, value);
end;

/**
* Форма 501. Атрибут для раздела 2.
* Хранит идентификатор и значение в виде объекта класса, реализующего IF501AttibuteValue
*/
class (TF501Attribute) TF501AttributePart2(id : String, part : Object, value : Object)
    macro makeId(p1)
        var id;

        if (isEqClass("RcbCompositeValue", p1))
            id = p1.fieldValue("НомЛС").currentAsString;
        else
            id = p1;
        end;

        return id;
    end;

    private macro constructorTF501AttributePart2(id : String, part : Object, value : Object)
        initTF501Attribute(id, part, value);
    end;

    constructorTF501AttributePart2(id, part, value);
end;

/**
* Форма 501. Атрибут для раздела 1 Ввод.
* Хранит идентификатор и значение в виде объекта класса, реализующего IF501AttibuteValue
*/
class (TF501Attribute) TF501AttributePart1UserInput(id : String, part : Object, value : Object)
    macro makeId(p1)
        var id;

        if (isEqClass("RcbCompositeValue", p1))
            id = p1.fieldValue("НомЛС_ввод").currentAsString;
        else
            id = p1;
        end;

        return id;
    end;

    private macro constructorTF501AttributePart1UserInput(id : String, part : Object, value : Object)
        initTF501Attribute(id, part, value);
    end;

    constructorTF501AttributePart1UserInput(id, part, value);
end;

/**
* Форма 501. Атрибут для раздела 2 Ввод.
* Хранит идентификатор и значение в виде объекта класса, реализующего IF501AttibuteValue
*/
class (TF501Attribute) TF501AttributePart2UserInput(id : String, part : Object, value : Object)
    macro makeId(p1)
        var id;

        if (isEqClass("RcbCompositeValue", p1))
            id = p1.fieldValue("НомЛС_ввод").currentAsString;
        else
            id = p1;
        end;

        return id;
    end;

    private macro constructorTF501AttributePart2UserInput(id : String, part : Object, value : Object)
        initTF501Attribute(id, part, value);
    end;

    constructorTF501AttributePart2UserInput(id, part, value);
end;
