import email_notifyfun, oralib, likepy; /* Функционал работы с e-mail уведомлениями */
/* Стырено у интеграции */

private const UNIVERSAL_ERROR_CODE = -10001;

/*------------------------------------------------------*/
/* Функция получения значения свойства заданного класса */
/* Если передана пустая строка, то функция вернет NULL  */
/*------------------------------------------------------*/
private macro uTryToGetPropS(obj:object, propName:string)
   var ret;
   ret = genGetProp(obj, propName);
   if(ValType(ret) == V_STRING)
      if(StrLen(ret) == 0)
         ret = NULL;
      end;
   elif(ValType(ret) == V_DATE)
      if(ret == date(0, 0, 0))
         ret = NULL;
      end;
   end;
   return ret;

   onError
      return NULL
end;

//Сгенерировать список адресов
macro GetContact (grpName, dep, FlagTxt)
 var sql;
 var ContactArr = TArray();
 var str = "";

 if (valtype(dep) == V_UNDEF)
   dep = {OperDprt};
 end;

 sql = " select trim(contact.t_value) mail "
     + "from dacsgroup_dbt grp, dacsgroupoper_dbt lnk, dperson_dbt person, dcontact_dbt contact "
     + "where grp.t_name = :1 "
     + "      and grp.t_groupid = lnk.t_groupid "
     + "      and person.t_oper = lnk.t_oper "
     + "      and person.t_partyid = contact.t_partyid  "
     + "      and contact.t_contactkind = 5 /*вид связи - e-mail*/ "
     + "      and contact.t_contacttype = 1001 /*тип связи - рабочий*/ "
     + "      and person.t_codedepart = :2 "
     + "order by lnk.t_oper  ";
 sql = ExecSqlSelect(sql, MakeArray(SqlParam("1", trim(grpName)), SqlParam("2", dep)), false);

 while (sql.MoveNext() )
   if ((valtype(FlagTxt) != V_UNDEF) and FlagTxt)
     str = str + sql.value("mail") + "; ";
   else
     ContactArr(ContactArr.Size) = sql.value("mail");
   end;
 end;

 return IfThenElse(FlagTxt, str, ContactArr);
onerror()
 return null;
End;

/*------------------------------------------*/
/* Класс для хранения полного текста ошибки */
/*------------------------------------------*/
private class usr_err_obj(p_err_msg, p_err_code)
   private var v_prop_list = TArray();
   private var v_err_code = "";
   var v_err_msg = "";

   /* Конструктор */
   private macro init_err_obj_params(p_err_msg, p_err_code)
      if(ValType(p_err_msg) != V_UNDEF)
         v_err_msg = string(p_err_msg);
      end;
      if(ValType(p_err_code) != V_UNDEF)
         v_err_code = string(p_err_code);
      end;
   end;

   /* Поиск свойства с заданным именем в заданном объекте */
   private macro try_to_find_prop(p_err_obj, p_prop_name, p_use_exist)
      var v_ret = false;
      var v_cntr_list = 0;

      if((ValType(p_use_exist) == V_UNDEF))
         v_prop_list.size = 0;
         v_prop_list = TArray(GetObjProps(p_err_obj, true));
      else
         if(not p_use_exist)
            v_prop_list.size = 0;
            v_prop_list = TArray(GetObjProps(p_err_obj, true));
         end;
      end;

      while((not v_ret) and (v_prop_list.size > v_cntr_list))
         if(v_prop_list.value(v_cntr_list) == p_prop_name)
            v_ret = true;
         end;
         v_cntr_list = v_cntr_list + 1;
      end;

      if(ValType(p_use_exist) == V_UNDEF)
         v_prop_list.size = 0;
      end;

      return v_ret;
   end;

   /* Получить v_err_msg */
   macro get_err_msg()
      return v_err_msg;
   end;

   /* Получить v_err_code */
   macro get_err_code()
      return v_err_code;
   end;

   /* Получить служебное сообщение из объекта ошибки */
   macro obtain_err_msg(p_err_obj)
      private var actx_code, actx_text, actx_msg;
      private var v_err_obj = NULL;

      /* Первый вызов try_to_find_prop() собирает массив свойств */
      if(try_to_find_prop(p_err_obj, "AxCode", false))
         actx_code = uTryToGetPropS(p_err_obj, "AxCode");
      else
         actx_code = 0;
      end;
      if(try_to_find_prop(p_err_obj, "Message", true))
         actx_text = uTryToGetPropS(p_err_obj, "Message");
      else
         actx_text = "0";
      end;
      if(try_to_find_prop(p_err_obj, "AxMes", true))
         actx_msg = uTryToGetPropS(p_err_obj, "AxMes");
      else
         actx_msg = "0";
      end;
      if(actx_code == 0)
         if(try_to_find_prop(p_err_obj, "Err", true))
            v_err_obj = uTryToGetPropS(p_err_obj, "Err");
            if(ValType(v_err_obj) == V_GENOBJ)
               if(try_to_find_prop(v_err_obj, "v_err_msg"))
                  v_err_msg = uTryToGetPropS(v_err_obj, "v_err_msg");
                  if(ValType(v_err_msg) == V_UNDEF)
                     v_err_msg = actx_text;
                  end;
               else
                  v_err_msg = actx_text;
               end;
            else
               v_err_msg = actx_text;
            end;
         else
            v_err_msg = actx_text;
         end;
      else
         v_err_msg = string(actx_text, ": Code: ", actx_code, "; Text: ", actx_msg);
      end;

      return v_err_msg;
   end;

   /* Получить код ошибки */
   macro obtain_err_code(p_err_obj, p_def_code)
      private var v_err_obj = NULL;

      /* При каждом вызове try_to_find_prop() массив свойств пересобирается */
      /* Если обрабатывается объект этого класса */
      if(try_to_find_prop(p_err_obj, "Err"))
         v_err_obj = uTryToGetPropS(p_err_obj, "Err");
         if(ValType(v_err_obj) == V_GENOBJ)
            if(try_to_find_prop(v_err_obj, "v_err_msg"))
               v_err_code = p_err_obj.err.get_err_code();
            end;
         end;
      end;

      /* Остальные объекты */
      if(strlen(v_err_code) == 0)
         if(ValType(p_def_code) != V_UNDEF)
            v_err_code = p_def_code;
         else
            if(try_to_find_prop(p_err_obj, "Code"))
               v_err_code = uTryToGetPropS(p_err_obj, "Code");
               if(ValType(v_err_code) == V_UNDEF)
                  v_err_code = UNIVERSAL_ERROR_CODE;
               end;
            else
               v_err_code = UNIVERSAL_ERROR_CODE;
            end;
         end;
      end;

      return v_err_code;
   end;

   macro obtain_err_axcode_exactly(p_err_obj, p_def_val)
      private var v_err_axcode;

      if(try_to_find_prop(p_err_obj, "AxCode"))
         v_err_axcode = uTryToGetPropS(p_err_obj, "AxCode");
      else
         if(ValType(p_def_val) == V_UNDEF)
            v_err_axcode = 0;
         else
            v_err_axcode = p_def_val;
         end;
      end;

      return v_err_axcode;
   end;

   macro obtain_err_message_exactly(p_err_obj, p_def_val)
      private var v_err_message;

      if(try_to_find_prop(p_err_obj, "Message"))
         v_err_message = uTryToGetPropS(p_err_obj, "Message");
      else
         if(ValType(p_def_val) == V_UNDEF)
            v_err_message = "0";
         else
            v_err_message = p_def_val;
         end;
      end;

      return v_err_message;
   end;

   macro obtain_err_axmes_exactly(p_err_obj, p_def_val)
      private var v_err_axmes;

      if(try_to_find_prop(p_err_obj, "AxMes"))
         v_err_axmes = uTryToGetPropS(p_err_obj, "AxMes");
      else
         if(ValType(p_def_val) == V_UNDEF)
            v_err_axmes = "0";
         else
            v_err_axmes = p_def_val;
         end;
      end;

      return v_err_axmes;
   end;

   init_err_obj_params(p_err_msg, p_err_code);
end; /* class usr_err_obj() */

/*-------------------------------------------------------*/
/* Обертка для функционала работы с e-mail уведомлениями */
/*-------------------------------------------------------*/
class email_proc_env()
   private var vg_is_error;
   private var vg_service_msg;
   /* Чтобы лишний раз не вычислять длину строки */
   private var vg_is_msg_text; /* Признак не пустого текста */
   private var vg_is_email_list; /* Признак не пустого списка адресов */

   private var vg_msg_head;   /* Заголовок письма */
   private var vg_msg_text;   /* Текст письма */
   private var vg_email_list; /* Список адресов получателей */
   private var vg_attach_list; /* Список вложений */

   /* Метод получения текста сервисного сообщения */
   macro get_service_msg()
      return vg_service_msg;
   end;

   macro m_get_error_status()
      return vg_is_error;
   end;

   /* Задать заголовок письма */
   macro m_set_msg_head(p_msg_head)
      vg_msg_head = p_msg_head;
   end;

   /* Очистить текст письма */
   macro m_clear_msg_text()
      vg_msg_text = "";
      vg_is_msg_text = false;
   end;

   /* Очистить список адресатов */
   macro m_clear_email_list()
      vg_email_list = "";
      vg_is_email_list = false;
   end;

   /* Добавить новую строку к тексту письма */
   macro m_add_row_to_msg_text(p_add_text)
      if(strlen(p_add_text) > 0)
         if(vg_is_msg_text)
            vg_msg_text = string(vg_msg_text, "\n", p_add_text);
         else
            vg_msg_text = p_add_text;
            vg_is_msg_text = true;
         end;
      end;
   end;

   /* Добавить новый адрес к списку получателей письма */
   macro m_add_email_to_list(p_add_email)
      if(strlen(p_add_email) > 0)
         if(vg_is_email_list)
            vg_email_list = string(vg_email_list, ";", p_add_email);
         else
            vg_email_list = p_add_email;
            vg_is_email_list = true;
         end;
      end;
   end;

   /* Добавить путь к файлу, который нужно приаттачить к письму */
   macro m_add_attach_to_list(p_add_attach)
      if(strlen(p_add_attach) > 0)
         vg_attach_list(vg_attach_list.size) = p_add_attach;
      end;
   end;
   /*----------------------------------------------*/
   /* Метод сохранения сообщения в БД для отправки */
   /*     Письма будут отправлены планировщиком    */
   /*----------------------------------------------*/
   macro m_save_to_submit()
      vg_is_error = false;
      /* Сохранение в БД */
      AddNotifyToDbt(vg_msg_head, vg_msg_text, vg_email_list, vg_attach_list);

   onError(err)
      vg_is_error = true;
      vg_service_msg = usr_err_obj.obtain_err_msg(err);
   end;

   /*---------------------------------------------*/
   /*             Метод отправки писем            */
   /* Будут отправлены все не отправленные письма */
   /*---------------------------------------------*/
   macro m_submit_email()
      vg_is_error = false;
      /* Отправка писем */
      SendNotyfyToEmail(/*fromCnv:bool, interface_mode:bool*/);

   onError(err)
      vg_is_error = true;
      vg_service_msg = usr_err_obj.obtain_err_msg(err);
   end;

   /* Конструктор */
   private macro m_init_prime()
      vg_is_error = true;
      vg_service_msg = "";
      vg_msg_head = "";
      vg_msg_text = "";
      vg_is_msg_text = false;
      vg_email_list = "";
      vg_is_email_list = false;
      vg_attach_list = TArray();
   end;

   m_init_prime();
end; /* class email_proc_env() */