import pm_setst, cbsttls, PTInter, CashInter, "pm_answerret.mac", "pmfm.mac";

var PaymentObj:RsbPayment;


MACRO ExecuteStep( doc, paymDoc )

  /*Заполнение причины отказа должно быть в ИР*/
  if(msgboxex("Отвергнуть платеж?", MB_YES + MB_NO, IND_NO) == IND_YES)
    PaymentObj.Notes.AddNote(PM_NOTEKIND_DENIALGROUND, "Какая-то причина отказа")
    //PaymentObj.Notes.DelNote(PM_NOTEKIND_DENIALGROUND);
  end;

  /*Смотрим на примечание и отвергаем/закрываем платеж*/
  if(strlen(PaymentObj.Notes.ReadNote(PM_NOTEKIND_DENIALGROUND, {curdate})) > 0)
    /*Отвергаем платеж*/
    PaymentObj.PaymStatus = 100/*Отвергнутый платеж*/;  
    if(УстановитьСтатусыПлатежа(OPR_PAYM_DO, 11/*Возврат*/))
      msgbox("Ошибка при установке сегментов статуса экземпляра операции");
      return 1;
    end;
  else
    /*Закрываем платеж*/
    if(УстановитьСтатусыПлатежа(OPR_PAYM_STATE, 3/*Закрыт*/))
      msgbox("Ошибка при установке сегментов статуса экземпляра операции");
      return 1;
    end;
  end;

  return 0;
END;


