declare
  i integer;
  j integer;
begin
  /*вычисление максимального номера*/
  SELECT max(t.t_number) into i FROM dmccateg_dbt t WHERE t.t_leveltype = 1;
  i := i + 1;
  /*вставка категории*/
  INSERT INTO dmccateg_dbt (T_ID,T_NUMBER,T_CODE,T_NAME,T_GROUPID,T_LEVELTYPE,T_UPDATEMODE,T_PERIODKIND,T_PERIODGROUPNUM,T_PARAM1,T_CLASS1,T_PARAM2,T_CLASS2,T_PARAM3,T_CLASS3,T_PARAM4,T_CLASS4,T_PARAM5,
    T_CLASS5,T_PARAM6,T_CLASS6,T_PARAM7,T_CLASS7,T_PARAM8,T_CLASS8,T_MASK,T_ATTRMASK,T_CURTYPE,T_OPTIONAL,T_NOTINUSE,T_UPGRADE,T_DONTUPDATE,T_PAIRCATID,T_INDEXDATEUNIT,T_RESERVE) 
    VALUES (0,i,'ТехническийСчетПасс','ТехническийСчетПасс',0,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'55555ВВВК00000000001',0,4,chr(88),null,null,null,0,0,null) returning t_id into j;
  dbms_output.put_line(j);  
  /*вставка шаблона - первого*/  
  INSERT INTO dmctempl_dbt (T_CATID,T_NUMBER,T_VALUE1,T_VALUE2,T_VALUE3,T_VALUE4,T_VALUE5,T_VALUE6,T_VALUE7,T_VALUE8,T_CHAPTER,T_BALANCE,T_MASK,T_KIND_ACCOUNT,T_GROUPNUM,T_HASPERIOD,T_NOTAUTO,
    T_ISCLOSE,T_ACCOUNTCLIENT,T_TYPEACCOUNT,T_RESERVE) 
    VALUES (j,1,-1,-1,-1,-1,-1,-1,-1,-1,1,'55555',null,'П',0,null,chr(88),null,0,null,null);
  /*вставка системных счетов*/
  /*рублевый*/
  INSERT INTO dmcaccdoc_dbt (T_ID,T_ISCOMMON,T_DOCKIND,T_DOCID,T_CATID,T_CATNUM,T_CHAPTER,T_ACCOUNT,  
    T_CURRENCY,T_TEMPLNUM,T_GROUPNUM,T_PERIODID,T_ACTIVATEDATE,T_DISABLINGDATE,T_ISUSABLE,T_FIID,T_OWNER,
    T_PLACE,T_ISSUER,T_KIND_ACCOUNT,T_CENTR,T_CENTROFFICE,T_ACTIONDATE,
    T_FIID2,T_CLIENTCONTRID,T_BANKCONTRID,
    T_MARKETPLACEID,T_MARKETPLACEOFFICEID,T_FIROLE,T_INDEXDATE,T_DEPARTMENTID,T_CONTRACTOR,T_BRANCH,
    T_CORRDEPARTMENTID,T_CURRENCYEQ,T_CURRENCYEQ_RATETYPE,T_CURRENCYEQ_RATEDATE,T_CURRENCYEQ_RATEEXTRA,T_MCBRANCH) 
    VALUES (0,chr(88),0,0,j,i,1,'55555810400000000001',  
    0,1,0,0,to_date('09012024','ddmmyyyy'),to_date('01011001','ddmmyyyy'),chr(88),-1,-1,
    -1,-1,null,-1,-1,to_date('09012024','ddmmyyyy'),
            -1,-1,-1,
            -1,-1,0,-1,1,-1,1,
            0,-1,0,0,0,1);
  /*доллар*/          
  INSERT INTO dmcaccdoc_dbt (T_ID,T_ISCOMMON,T_DOCKIND,T_DOCID,T_CATID,T_CATNUM,T_CHAPTER,T_ACCOUNT,  
    T_CURRENCY,T_TEMPLNUM,T_GROUPNUM,T_PERIODID,T_ACTIVATEDATE,T_DISABLINGDATE,T_ISUSABLE,T_FIID,T_OWNER,
    T_PLACE,T_ISSUER,T_KIND_ACCOUNT,T_CENTR,T_CENTROFFICE,T_ACTIONDATE,
    T_FIID2,T_CLIENTCONTRID,T_BANKCONTRID,
    T_MARKETPLACEID,T_MARKETPLACEOFFICEID,T_FIROLE,T_INDEXDATE,T_DEPARTMENTID,T_CONTRACTOR,T_BRANCH,
    T_CORRDEPARTMENTID,T_CURRENCYEQ,T_CURRENCYEQ_RATETYPE,T_CURRENCYEQ_RATEDATE,T_CURRENCYEQ_RATEEXTRA,T_MCBRANCH) 
    VALUES (0,chr(88),0,0,j,i,1,'55555840700000000001',  
    7,1,0,0,to_date('09012024','ddmmyyyy'),to_date('01011001','ddmmyyyy'),chr(88),-1,-1,
    -1,-1,null,-1,-1,to_date('09012024','ddmmyyyy'),
            -1,-1,-1,
            -1,-1,0,-1,1,-1,1,
            0,-1,0,0,0,1);
  /*евро*/
  INSERT INTO dmcaccdoc_dbt (T_ID,T_ISCOMMON,T_DOCKIND,T_DOCID,T_CATID,T_CATNUM,T_CHAPTER,T_ACCOUNT,  
    T_CURRENCY,T_TEMPLNUM,T_GROUPNUM,T_PERIODID,T_ACTIVATEDATE,T_DISABLINGDATE,T_ISUSABLE,T_FIID,T_OWNER,
    T_PLACE,T_ISSUER,T_KIND_ACCOUNT,T_CENTR,T_CENTROFFICE,T_ACTIONDATE,
    T_FIID2,T_CLIENTCONTRID,T_BANKCONTRID,
    T_MARKETPLACEID,T_MARKETPLACEOFFICEID,T_FIROLE,T_INDEXDATE,T_DEPARTMENTID,T_CONTRACTOR,T_BRANCH,
    T_CORRDEPARTMENTID,T_CURRENCYEQ,T_CURRENCYEQ_RATETYPE,T_CURRENCYEQ_RATEDATE,T_CURRENCYEQ_RATEEXTRA,T_MCBRANCH) 
    VALUES (0,chr(88),0,0,j,i,1,'55555978300000000001',  
    8,1,0,0,to_date('09012024','ddmmyyyy'),to_date('01011001','ddmmyyyy'),chr(88),-1,-1,
    -1,-1,null,-1,-1,to_date('09012024','ddmmyyyy'),
            -1,-1,-1,
            -1,-1,0,-1,1,-1,1,
            0,-1,0,0,0,1);
  /*фунт*/
  INSERT INTO dmcaccdoc_dbt (T_ID,T_ISCOMMON,T_DOCKIND,T_DOCID,T_CATID,T_CATNUM,T_CHAPTER,T_ACCOUNT,  
    T_CURRENCY,T_TEMPLNUM,T_GROUPNUM,T_PERIODID,T_ACTIVATEDATE,T_DISABLINGDATE,T_ISUSABLE,T_FIID,T_OWNER,
    T_PLACE,T_ISSUER,T_KIND_ACCOUNT,T_CENTR,T_CENTROFFICE,T_ACTIONDATE,
    T_FIID2,T_CLIENTCONTRID,T_BANKCONTRID,
    T_MARKETPLACEID,T_MARKETPLACEOFFICEID,T_FIROLE,T_INDEXDATE,T_DEPARTMENTID,T_CONTRACTOR,T_BRANCH,
    T_CORRDEPARTMENTID,T_CURRENCYEQ,T_CURRENCYEQ_RATETYPE,T_CURRENCYEQ_RATEDATE,T_CURRENCYEQ_RATEEXTRA,T_MCBRANCH) 
    VALUES (0,chr(88),0,0,j,i,1,'55555826300000000001',  
    20,1,0,0,to_date('09012024','ddmmyyyy'),to_date('01011001','ddmmyyyy'),chr(88),-1,-1,
    -1,-1,null,-1,-1,to_date('09012024','ddmmyyyy'),
            -1,-1,-1,
            -1,-1,0,-1,1,-1,1,
            0,-1,0,0,0,1);
            
  /*Юань*/
  INSERT INTO dmcaccdoc_dbt (T_ID,T_ISCOMMON,T_DOCKIND,T_DOCID,T_CATID,T_CATNUM,T_CHAPTER,T_ACCOUNT,  
    T_CURRENCY,T_TEMPLNUM,T_GROUPNUM,T_PERIODID,T_ACTIVATEDATE,T_DISABLINGDATE,T_ISUSABLE,T_FIID,T_OWNER,
    T_PLACE,T_ISSUER,T_KIND_ACCOUNT,T_CENTR,T_CENTROFFICE,T_ACTIONDATE,
    T_FIID2,T_CLIENTCONTRID,T_BANKCONTRID,
    T_MARKETPLACEID,T_MARKETPLACEOFFICEID,T_FIROLE,T_INDEXDATE,T_DEPARTMENTID,T_CONTRACTOR,T_BRANCH,
    T_CORRDEPARTMENTID,T_CURRENCYEQ,T_CURRENCYEQ_RATETYPE,T_CURRENCYEQ_RATEDATE,T_CURRENCYEQ_RATEEXTRA,T_MCBRANCH) 
    VALUES (0,chr(88),0,0,j,i,1,'55555156300000000001',  
    11,1,0,0,to_date('09012024','ddmmyyyy'),to_date('01011001','ddmmyyyy'),chr(88),-1,-1,
    -1,-1,null,-1,-1,to_date('09012024','ddmmyyyy'),
            -1,-1,-1,
            -1,-1,0,-1,1,-1,1,
            0,-1,0,0,0,1);
            
  /*Швейцарский Франк*/
  INSERT INTO dmcaccdoc_dbt (T_ID,T_ISCOMMON,T_DOCKIND,T_DOCID,T_CATID,T_CATNUM,T_CHAPTER,T_ACCOUNT,  
    T_CURRENCY,T_TEMPLNUM,T_GROUPNUM,T_PERIODID,T_ACTIVATEDATE,T_DISABLINGDATE,T_ISUSABLE,T_FIID,T_OWNER,
    T_PLACE,T_ISSUER,T_KIND_ACCOUNT,T_CENTR,T_CENTROFFICE,T_ACTIONDATE,
    T_FIID2,T_CLIENTCONTRID,T_BANKCONTRID,
    T_MARKETPLACEID,T_MARKETPLACEOFFICEID,T_FIROLE,T_INDEXDATE,T_DEPARTMENTID,T_CONTRACTOR,T_BRANCH,
    T_CORRDEPARTMENTID,T_CURRENCYEQ,T_CURRENCYEQ_RATETYPE,T_CURRENCYEQ_RATEDATE,T_CURRENCYEQ_RATEEXTRA,T_MCBRANCH) 
    VALUES (0,chr(88),0,0,j,i,1,'55555756700000000001',  
    19,1,0,0,to_date('09012024','ddmmyyyy'),to_date('01011001','ddmmyyyy'),chr(88),-1,-1,
    -1,-1,null,-1,-1,to_date('09012024','ddmmyyyy'),
            -1,-1,-1,
            -1,-1,0,-1,1,-1,1,
            0,-1,0,0,0,1);            
            
  commit;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(sqlerrm);
end;
/