
DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724WRTAVR_DBT_IDX0';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE D724WRTAVR_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/

CREATE TABLE D724WRTAVR_DBT (
    T_SESSIONID NUMBER(10)
  , T_CONTRID NUMBER(10)
  , T_CONTR_GROUPID VARCHAR2(100)
  , T_PARTYID NUMBER(10)
  , T_CLIENT_GROUPID VARCHAR2(100)
  , T_DEALID NUMBER(10)
  , T_WRTIN CHAR(1)
  , T_ISAVR CHAR(1)
  , T_DATE DATE
  , T_FIID NUMBER(10)
  , T_QNTY NUMBER(32,12)
  , T_TOTALCOST NUMBER(32,12)
)
/

CREATE INDEX D724WRTAVR_DBT_IDX0 ON D724WRTAVR_DBT (T_SESSIONID, T_CONTR_GROUPID, T_CLIENT_GROUPID)
/


DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724WRTMONEY_DBT_IDX0';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE D724WRTMONEY_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/

CREATE TABLE D724WRTMONEY_DBT (
    T_SESSIONID NUMBER(10)
  , T_CONTRID NUMBER(10)
  , T_CONTR_GROUPID VARCHAR2(100)
  , T_PARTYID NUMBER(10)
  , T_CLIENT_GROUPID VARCHAR2(100)
  , T_NPTXOPID NUMBER(10)
  , T_WRTIN CHAR(1)
  , T_DATE DATE
  , T_FIID NUMBER(10)
  , T_SUM NUMBER(32,12)
  , T_SUMRUB NUMBER(32,12)
)
/

CREATE INDEX D724WRTMONEY_DBT_IDX0 ON D724WRTMONEY_DBT (T_SESSIONID, T_CONTR_GROUPID, T_CLIENT_GROUPID)
/


DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724FIREST_DBT_IDX0';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE D724FIREST_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/


CREATE TABLE D724FIREST_DBT (
    T_SESSIONID NUMBER(10)
  , T_CONTRID NUMBER(10)
  , T_CONTR_GROUPID VARCHAR2(100)
  , T_PARTYID NUMBER(10)
  , T_CLIENT_GROUPID VARCHAR2(100)
  , T_FIID NUMBER(10)
  , T_QNTY NUMBER(32,12)
  , T_TOTALCOST NUMBER(32,12)
)
/

CREATE INDEX D724FIREST_DBT_IDX0 ON D724FIREST_DBT (T_SESSIONID, T_CONTR_GROUPID, T_CLIENT_GROUPID, T_FIID)
/

DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724CONTR_DBT_IDX0';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724CONTR_DBT_IDX1';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724CONTR_DBT_IDX2';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE D724CONTR_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/


CREATE TABLE D724CONTR_DBT (
    T_SESSIONID NUMBER(10)
  , T_PARTY NUMBER(10)
  , T_SF_ID NUMBER(10)
  , T_SF_NUMBER VARCHAR2(20)
  , T_SF_BEG DATE
  , T_SF_END DATE
  , T_SF_SERVKIND NUMBER(5)
  , T_SF_SUBKIND NUMBER(5)
  , T_IIS NUMBER(5)
  , T_BANKROLE NUMBER(5)
  , T_GROUP_CONTR NUMBER(5)
  , T_CONTR_GROUPID VARCHAR2(100)
)
/

CREATE INDEX D724CONTR_DBT_IDX0 ON D724CONTR_DBT (T_SESSIONID, T_IIS, T_BANKROLE, T_GROUP_CONTR)
/

CREATE INDEX D724CONTR_DBT_IDX1 ON D724CONTR_DBT (T_SESSIONID, T_CONTR_GROUPID)
/

CREATE INDEX D724CONTR_DBT_IDX2 ON D724CONTR_DBT (T_SESSIONID, T_SF_ID, T_PARTY)
/


DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724CLIENT_DBT_IDX0';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724CLIENT_DBT_IDX1';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724CLIENT_DBT_IDX2';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE D724CLIENT_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/


CREATE TABLE D724CLIENT_DBT (
    T_SESSIONID NUMBER(10)
  , T_PARTYID NUMBER(10)
  , T_SHORTNAME VARCHAR2(60)
  , T_NAME VARCHAR2(320)
  , T_TYPE_FL NUMBER(5)
  , T_CLIENTCODE VARCHAR2(35)
  , T_KI NUMBER(5)
  , T_ACTIVECLIENT NUMBER(5)
  , T_CODE_OKATO VARCHAR2(5)
  , T_CODE_OKSM VARCHAR2(3)
  , T_CLIENT_GROUPID VARCHAR2(100)
)
/

CREATE INDEX D724CLIENT_DBT_IDX0 ON D724CLIENT_DBT (T_SESSIONID, T_TYPE_FL, T_KI, T_ACTIVECLIENT, T_CODE_OKSM, T_CODE_OKATO)
/

CREATE INDEX D724CLIENT_DBT_IDX1 ON D724CLIENT_DBT (T_SESSIONID, T_CLIENT_GROUPID)
/

CREATE INDEX D724CLIENT_DBT_IDX2 ON D724CLIENT_DBT (T_SESSIONID, T_PARTYID)
/

DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724PFI_DBT_IDX0';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE D724PFI_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/

CREATE TABLE D724PFI_DBT (
    T_SESSIONID NUMBER(10)
  , T_CONTRID NUMBER(10)
  , T_CONTR_GROUPID VARCHAR2(100)
  , T_PARTYID NUMBER(10)
  , T_CLIENT_GROUPID VARCHAR2(100)
  , T_DOCKIND NUMBER(5)
  , T_DOCID NUMBER(10)
  , T_EXTCODE VARCHAR2(35)
  , T_EXTNAME VARCHAR2(60)
  , T_PFINAME VARCHAR2(50)
  , T_AMOUNT NUMBER(32,12)
  , T_DIR NUMBER(5)
  , T_COSTPFI NUMBER(32,12)
  , T_GUARANTY NUMBER(32,12)
  , T_COSTPFI_FO NUMBER(32,12)
)
/

CREATE INDEX D724PFI_DBT_IDX0 ON D724PFI_DBT (T_SESSIONID, T_CLIENT_GROUPID, T_CONTR_GROUPID, T_PFINAME, T_EXTCODE, T_EXTNAME, T_DIR)
/

DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724ARREAR_DBT_IDX0';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE D724ARREAR_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/

CREATE TABLE D724ARREAR_DBT (
    T_SESSIONID NUMBER(10)
  , T_CONTRID NUMBER(10)
  , T_CONTR_GROUPID VARCHAR2(100)
  , T_PARTYID NUMBER(10)
  , T_CLIENT_GROUPID VARCHAR2(100)
  , T_DOCKIND NUMBER(5)
  , T_DOCID NUMBER(10)
  , T_KIND NUMBER(5)
  , T_SUBKIND NUMBER(5)
  , T_KINDREPO NUMBER(5)
  , T_CONTRACTORID NUMBER(10)
  , T_VALUE NUMBER(32, 12)
)
/

CREATE INDEX D724ARREAR_DBT_IDX0 ON D724ARREAR_DBT (T_SESSIONID, T_CONTR_GROUPID, T_CLIENT_GROUPID, T_KIND, T_SUBKIND, T_KINDREPO, T_CONTRACTORID)
/


DECLARE
    E_INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_INDEX_NOT_EXISTS, -1418);
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX D724ACCREST_DBT_IDX0';
EXCEPTION 
    WHEN E_INDEX_NOT_EXISTS THEN NULL;
END;
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE D724ACCREST_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/

CREATE TABLE D724ACCREST_DBT (
    T_SESSIONID NUMBER(10)
  , T_CONTRID NUMBER(10)
  , T_CONTR_GROUPID VARCHAR2(100)
  , T_PARTYID NUMBER(10)
  , T_CLIENT_GROUPID VARCHAR2(100)
  , T_FI_KIND NUMBER(5)
  , T_ACCOUNT VARCHAR2(25)
  , T_CHAPTER NUMBER(5)
  , T_FIID NUMBER(10)
  , T_AMOUNT_FIID NUMBER(32,12)
  , T_AMOUNT_RUR NUMBER(32,12)
)
/

CREATE INDEX D724ACCREST_DBT_IDX0 ON D724ACCREST_DBT (T_SESSIONID, T_CONTR_GROUPID, T_CLIENT_GROUPID, T_FI_KIND, T_FIID)
/






