--Регулярный скрипт установки уровня риска "КСУР"/"КНУР" на открытых ДБО ФЛ без установленного уровня риска
BEGIN
  INSERT INTO DOBJATCOR_DBT (T_OBJECTTYPE, T_GROUPID, T_ATTRID, T_OBJECT, T_GENERAL, T_VALIDFROMDATE, T_OPER, T_VALIDTODATE, T_ISAUTO)
  (SELECT 207, 103, CASE WHEN SF.T_DATECONC <= TO_DATE('31/03/2025','DD/MM/YYYY') THEN 2 ELSE 4 END, LPAD(DL.T_DLCONTRID, 34, '0'), CHR(88), TRUNC(SYSDATE), 1, TO_DATE('31/12/9999','DD/MM/YYYY'), CHR(88)
     FROM DDLCONTR_DBT DL, DSFCONTR_DBT SF, DPARTY_DBT PT
    WHERE DL.T_SFCONTRID = SF.T_ID
      AND SF.T_DATECLOSE = TO_DATE('01/01/0001','DD/MM/YYYY')
      AND PT.T_PARTYID = SF.T_PARTYID
      AND PT.T_LEGALFORM = 2 /*ФЛ*/
      AND NOT EXISTS (SELECT 1 FROM DOBJATCOR_DBT WHERE T_OBJECTTYPE = 207 AND T_GROUPID = 103 AND T_OBJECT = LPAD(DL.T_DLCONTRID, 34, '0'))
  );
END;
/