--Добавление полей
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDL_PFICREDITRISK_TMP ADD T_NCRISSUER VARCHAR2(60) DEFAULT CHR(1)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDL_PFICREDITRISK_TMP ADD T_NCRSECUR VARCHAR2(60) DEFAULT CHR(1)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDL_PFICREDITRISK_TMP ADD T_NRAISSUER VARCHAR2(60) DEFAULT CHR(1)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDL_PFICREDITRISK_TMP ADD T_NRASECUR VARCHAR2(60) DEFAULT CHR(1)';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/
