--Временная таблица
CREATE GLOBAL TEMPORARY TABLE DDVDEALTRN_TMP
(
  T_ID            NUMBER(10),
  T_ID_OPERATION  NUMBER(10),
  T_ID_STEP       NUMBER(10),
  T_DEALID        NUMBER(10),
  T_ACCTRNID      NUMBER(10)
)
ON COMMIT PRESERVE ROWS
/
