/*Добавление в справочник*/
BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7341,0,'Новая запись',20,5,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7341,1,'Обработано',20,5,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7341,2,'Ошибка валидации',20,5,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7341,3,'Ошибка обработки',20,5,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7341,4,'Отклонено',20,5,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

