DECLARE
   ex_table_exists EXCEPTION;
   PRAGMA EXCEPTION_INIT(ex_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE  DNPTXSLICEOBJ_DBT
                        (
                          T_OBJID          NUMBER(10)                   NOT NULL,
                          T_OBJSID         NUMBER(10)                   NOT NULL,
                          T_SLICEID        NUMBER(10)                   NOT NULL,
                          T_DATE           DATE                         NOT NULL,
                          T_CLIENT         NUMBER(10)                   NOT NULL,
                          T_DIRECTION      NUMBER(5)                    DEFAULT 1,
                          T_LEVEL          NUMBER(5)                    NOT NULL,
                          T_USER           CHAR(1 BYTE)                 DEFAULT chr(0),
                          T_KIND           NUMBER(5)                    NOT NULL,
                          T_SUM            NUMBER(32,12)                DEFAULT 0,
                          T_CUR            NUMBER(10)                   DEFAULT 0,
                          T_SUM0           NUMBER(32,12)                DEFAULT 0,
                          T_ANALITICKIND1  NUMBER(5)                    DEFAULT 0,
                          T_ANALITIC1      NUMBER(10)                   DEFAULT -1,
                          T_ANALITICKIND2  NUMBER(5)                    DEFAULT 0,
                          T_ANALITIC2      NUMBER(10)                   DEFAULT -1,
                          T_ANALITICKIND3  NUMBER(5)                    DEFAULT 0,
                          T_ANALITIC3      NUMBER(10)                   DEFAULT -1,
                          T_ANALITICKIND4  NUMBER(5)                    DEFAULT 0,
                          T_ANALITIC4      NUMBER(10)                   DEFAULT -1,
                          T_ANALITICKIND5  NUMBER(5)                    DEFAULT 0,
                          T_ANALITIC5      NUMBER(10)                   DEFAULT -1,
                          T_ANALITICKIND6  NUMBER(5)                    DEFAULT 0,
                          T_ANALITIC6      NUMBER(10)                   DEFAULT -1,
                          T_COMMENT        VARCHAR2(256 BYTE)           DEFAULT chr(1),
                          T_FROMOUTSYST    CHAR(1 BYTE)                 DEFAULT CHR(0),
                          T_OUTSYSTCODE    VARCHAR2(35 BYTE)            DEFAULT CHR(1),
                          T_OUTOBJID       VARCHAR2(30 BYTE)            DEFAULT CHR(1),
                          T_SOURCEOBJID    NUMBER(10)                   DEFAULT 0,
                          T_TAXPERIOD      NUMBER(10)                   DEFAULT 0,
                          T_TECHNICAL      CHAR(1)                      DEFAULT CHR(0)
                        )';
                                  
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_OBJID IS ''Идентификатор оригинала объекта''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_OBJSID IS ''Идентификатор объекта''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_SLICEID IS ''Идентификатор среза''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_DATE IS ''Дата объекта''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_CLIENT IS ''Идентификатор клиента''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_DIRECTION IS ''Направление''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_LEVEL IS ''Уровень''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_USER IS ''Пользовательский объект''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_KIND IS ''Вид''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_SUM IS ''Сумма''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_CUR IS ''Номинал''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_SUM0 IS ''Сумма в рублях''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITICKIND1 IS ''Вид аналитики 1''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITIC1 IS ''Аналитика 1''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITICKIND2 IS ''Вид аналитики 2''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITIC2 IS ''Аналитика 2''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITICKIND3 IS ''Вид аналитики 3''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITIC3 IS ''Аналитика 3''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITICKIND4 IS ''Вид аналитики 4''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITIC4 IS ''Аналитика 4''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITICKIND5 IS ''Вид аналитики 5''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITIC5 IS ''Аналитика 5''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITICKIND6 IS ''Вид аналитики 6''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_ANALITIC6 IS ''Аналитика 6''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_COMMENT IS ''Комментарий''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_FROMOUTSYST IS ''Из внешней системы''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_OUTSYSTCODE IS ''Код внешней системы''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_OUTOBJID IS ''Идентификатор внешнего объекта''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_TAXPERIOD IS ''Налоговый период''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_SOURCEOBJID IS ''Идентификатор объекта-источника''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN  DNPTXSLICEOBJ_DBT.T_TECHNICAL IS ''Технический объект''';

  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICEOBJ_DBT_IDX0';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DNPTXSLICEOBJ_DBT_IDX0 ON  DNPTXSLICEOBJ_DBT (T_OBJSID)';
  
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICEOBJ_DBT_IDX1';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX  DNPTXSLICEOBJ_DBT_IDX1 ON  DNPTXSLICEOBJ_DBT (T_DATE)';

  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICEOBJ_DBT_IDX2';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX  DNPTXSLICEOBJ_DBT_IDX2 ON  DNPTXSLICEOBJ_DBT (T_KIND, T_ANALITICKIND1, T_ANALITIC1, T_DATE)';

  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICEOBJ_DBT_IDX3';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX  DNPTXSLICEOBJ_DBT_IDX3 ON  DNPTXSLICEOBJ_DBT (T_KIND, T_ANALITICKIND2, T_ANALITIC2, T_DATE)';

  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICEOBJ_DBT_IDX4';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX  DNPTXSLICEOBJ_DBT_IDX4 ON  DNPTXSLICEOBJ_DBT (T_ANALITICKIND6, T_ANALITIC6)';

  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICEOBJ_DBT_IDX5';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX  DNPTXSLICEOBJ_DBT_IDX5 ON  DNPTXSLICEOBJ_DBT (T_SLICEID)';

  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICEOBJ_DBT_IDX6';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX  DNPTXSLICEOBJ_DBT_IDX6 ON  DNPTXSLICEOBJ_DBT (T_USER)';

  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICEOBJ_DBT_IDXA';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX  DNPTXSLICEOBJ_DBT_IDXA ON  DNPTXSLICEOBJ_DBT (T_CLIENT, T_KIND, T_DATE)';

  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE DNPTXSLICEOBJ_DBT_SEQ';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE  DNPTXSLICEOBJ_DBT_SEQ
          START WITH 1
          MAXVALUE 9999999999999999999999999999
          MINVALUE 1
          NOCYCLE
          CACHE 20
          NOORDER
          NOKEEP
          NOSCALE
          GLOBAL';

EXCEPTION
   WHEN ex_table_exists
   THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER  DNPTXSLICEOBJ_DBT_t0_ainc
 BEFORE INSERT OR UPDATE OF T_OBJSID ON  DNPTXSLICEOBJ_DBT FOR EACH ROW
DECLARE
 v_id INTEGER;
BEGIN
 IF (:new.T_OBJSID = 0 OR :new.T_OBJSID IS NULL) THEN
 SELECT DNPTXSLICEOBJ_DBT_SEQ.nextval INTO :new.T_OBJSID FROM dual;
 ELSE
 select last_number into v_id from user_sequences where sequence_name = upper ('DNPTXSLICEOBJ_DBT_SEQ');
 IF :new.T_OBJSID >= v_id THEN
 RAISE DUP_VAL_ON_INDEX;
 END IF;
 END IF;
END;
/