/*Изменения в DCDRECORDS_DBT*/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE DCDRECORDS_DBT MODIFY T_REQUESTTIME DATE';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DCDRECORDS_DBT ADD T_REQUESTDATE DATE DEFAULT TO_DATE(''01.01.0001'',''DD.MM.YYYY'')';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DCDRECORDS_DBT.T_REQUESTDATE IS ''Дата запроса''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/