-- Добавить поля в таблицу "DCDRECORDS_DBT"
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DCDRECORDS_DBT ADD T_STATUS NUMBER(5)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DCDRECORDS_DBT.T_STATUS IS ''Статус обработки записи''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DCDRECORDS_DBT ADD T_ERROR VARCHAR2(4000)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DCDRECORDS_DBT.T_ERROR IS ''Описание ошибки''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DCDRECORDS_DBT ADD T_PARTYID NUMBER(10)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DCDRECORDS_DBT.T_PARTYID IS ''Идентификатор субъекта в СОФРе''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DCDRECORDS_DBT ADD T_CONTRACTID NUMBER(10)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DCDRECORDS_DBT.T_CONTRACTID IS ''Идентификатор договора клиента в СОФРе''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DCDRECORDS_DBT ADD T_FIID NUMBER(10)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DCDRECORDS_DBT.T_FIID IS ''Идентификатор фин.инструмента в СОФРе''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DCDRECORDS_DBT_IDX3';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DCDRECORDS_DBT_IDX3 ON DCDRECORDS_DBT (
   T_CLIENTID_OBJECTID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DCDRECORDS_DBT_IDX4';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DCDRECORDS_DBT_IDX4 ON DCDRECORDS_DBT (
   T_PARTYID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DCDRECORDS_DBT_IDX5';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DCDRECORDS_DBT_IDX5 ON DCDRECORDS_DBT (
   T_STATUS ASC
)
/

