BEGIN
  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7340, 1, 1, 3, 2);
  
  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7340, 2, 23, 3, 2);
END;