DECLARE
  v_ID       NUMBER := 0;
  v_ParentID NUMBER := 0;
BEGIN
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = (SELECT T_KEYID FROM DREGPARM_DBT WHERE T_PARENTID = 0 AND LOWER(T_NAME) = LOWER('‘•')) AND LOWER(T_NAME) = LOWER('…‘… ‘‹“†‚€…');

  IF(v_ParentId <> 0) THEN 
    INSERT INTO DREGPARM_DBT (T_KEYID,T_PARENTID,T_NAME,T_TYPE,T_GLOBAL,T_DESCRIPTION,T_SECURITY,T_ISBRANCH,T_TEMPLATE)
                      VALUES (0,v_ParentID,'‹‡',0,CHR(0),CHR(1),CHR(0),CHR(0),CHR(1)) returning T_KEYID INTO v_ID;

    INSERT INTO DREGVAL_DBT (T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX)
                     VALUES (v_ID,0,0,CHR(0),0,0,0,'');

    v_ParentId := v_ID;
    IF(v_ParentId <> 0) THEN 
      INSERT INTO DREGPARM_DBT (T_KEYID,T_PARENTID,T_NAME,T_TYPE,T_GLOBAL,T_DESCRIPTION,T_SECURITY,T_ISBRANCH,T_TEMPLATE)
                        VALUES (0,v_ParentID,'…”‘ „……›• „‚',2,'X','ΰ¥δ¨ªα ¤«ο ―®¤¬¥­ο¥¬λε ª®¤®Ά',CHR(0),CHR(0),CHR(1)) returning T_KEYID INTO v_ID;
     
      INSERT INTO DREGVAL_DBT (T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX)
                       VALUES (v_ID,0,0,CHR(0),0,0,0,to_blob(utl_raw.cast_to_raw('CLT_')));

      INSERT INTO DREGPARM_DBT (T_KEYID,T_PARENTID,T_NAME,T_TYPE,T_GLOBAL,T_DESCRIPTION,T_SECURITY,T_ISBRANCH,T_TEMPLATE)
                        VALUES (0,v_ParentID,'„……›… „›  ‡€ƒ“‡…',2,'X','‘―¨α®ª ª®¤®Ά, βΰ¥΅γξι¨ε ―®¤¬¥­λ ¤«ο ª«¨¥­βαª¨ε α¤¥«®ª',CHR(0),CHR(0),CHR(1)) returning T_KEYID INTO v_ID;
     
      INSERT INTO DREGVAL_DBT (T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX)
                       VALUES (v_ID,0,0,CHR(0),0,0,0,to_blob(utl_raw.cast_to_raw('SLV, GLD')));
    END IF;
  END IF;
END;
/