-- Таблица "DNPTXTRANSFBUDG_DBT"
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DNPTXTRANSFBUDG_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DNPTXTRANSFBUDG_DBT (
    T_NPTXOP_LINK       NUMBER(10)  NOT NULL
  , T_MONTH             NUMBER(5)   DEFAULT 1
  , T_DATEFROM_TRANSF   NUMBER(5)   DEFAULT 1
  , T_DATETO_TRANSF     NUMBER(5)   DEFAULT 1
)
/

COMMENT ON TABLE  DNPTXTRANSFBUDG_DBT                   IS 'Операции перечисления НДФЛ в бюджет. Доп поля к dnptxop_dbt'/
COMMENT ON COLUMN DNPTXTRANSFBUDG_DBT.T_NPTXOP_LINK     IS 'Ссылка на dnptxop_dbt'/
COMMENT ON COLUMN DNPTXTRANSFBUDG_DBT.T_MONTH           IS 'Месяц выполнения операции'/
COMMENT ON COLUMN DNPTXTRANSFBUDG_DBT.T_DATEFROM_TRANSF IS 'Число начала '/
COMMENT ON COLUMN DNPTXTRANSFBUDG_DBT.T_DATETO_TRANSF   IS 'Day From'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXTRANSFBUDG_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXTRANSFBUDG_DBT_IDX0 ON DNPTXTRANSFBUDG_DBT (
   T_NPTXOP_LINK ASC)
/