/*Добавление значений настроек*/
DECLARE
  v_ID       NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('УНКД_ОБРАБОТ_ОБЛИГАЦ_ИНДЕКС_НОМ');

  DELETE FROM DREGVAL_DBT WHERE T_KEYID = v_ID;

  INSERT INTO DREGVAL_DBT(T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX )
  VALUES(v_ID,0,0,'',0,88,0,'');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/
