DECLARE
   ex_table_exists EXCEPTION;
   PRAGMA EXCEPTION_INIT(ex_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE DNPTXREGKIND_DBT
                                  (T_NPTXKIND   NUMBER(10)
                                  )';
                                  
  EXECUTE IMMEDIATE 'COMMENT ON TABLE DNPTXREGKIND_DBT IS ''„ ¤«ο ΰ¥£¨αβΰ  „”‹''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXREGKIND_DBT.T_NPTXKIND IS ''‚¨¤ „''';
  
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXREGKIND_DBT_IDX0';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DNPTXREGKIND_DBT_IDX0 ON DNPTXREGKIND_DBT (T_NPTXKIND)';
  
EXCEPTION
   WHEN ex_table_exists
   THEN NULL;
END;
/
