DECLARE
   ex_table_exists EXCEPTION;
   PRAGMA EXCEPTION_INIT(ex_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE  DNPTXSLICE_DBT
                            (
                              T_SLICEID        NUMBER(10)                   NOT NULL,
                              T_DATEFROM       DATE                         NOT NULL,
                              T_DATETO         DATE                         NOT NULL,
                              T_SYSDATE        DATE                         NOT NULL,
                              T_SLICENUM       NUMBER(10)                   NOT NULL,
                              T_REPORTID       NUMBER(10)                   NOT NULL
                            )';
                                  
  EXECUTE IMMEDIATE 'COMMENT ON TABLE DNPTXSLICE_DBT IS ''Срезы НДФЛ''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSLICE_DBT.T_SLICEID IS ''Идентификатор среза''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSLICE_DBT.T_DATEFROM IS ''Дата начала среза''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSLICE_DBT.T_DATETO IS ''Дата окончания среза''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSLICE_DBT.T_SYSDATE IS ''Системная дата''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSLICE_DBT.T_SLICENUM IS ''Номер среза''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXSLICE_DBT.T_REPORTID IS ''Идентификатор отчета 6-НДФЛ''';
  
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICE_DBT_IDX0';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DNPTXSLICE_DBT_IDX0 ON DNPTXSLICE_DBT (T_SLICEID)';
  
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX DNPTXSLICE_DBT_IDX1';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX  DNPTXSLICE_DBT_IDX1 ON  DNPTXSLICE_DBT (T_DATEFROM, T_DATETO)';

  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE DNPTXSLICE_DBT_SEQ';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE  DNPTXSLICE_DBT_SEQ
    START WITH 1
    MAXVALUE 9999999999999999999999999999
    MINVALUE 1
    NOCYCLE
    CACHE 20
    NOORDER
    NOKEEP
    NOSCALE
    GLOBAL';

EXCEPTION
   WHEN ex_table_exists
   THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER  DNPTXSLICE_DBT_t0_ainc
 BEFORE INSERT OR UPDATE OF T_SLICEID ON  DNPTXSLICE_DBT FOR EACH ROW
DECLARE
 v_id INTEGER;
BEGIN
 IF (:new.T_SLICEID = 0 OR :new.T_SLICEID IS NULL) THEN
 SELECT DNPTXSLICE_DBT_SEQ.nextval INTO :new.T_SLICEID FROM dual;
 ELSE
 select last_number into v_id from user_sequences where sequence_name = upper ('DNPTXSLICE_DBT_SEQ');
 IF :new.T_SLICEID >= v_id THEN
 RAISE DUP_VAL_ON_INDEX;
 END IF;
 END IF;
END;
/
