DROP TABLE D_SEM02_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE D_SEM02_TMP
(
  T_ID_MB_SEM02        NUMBER(10),
  T_ID_MB_REQUISITES   NUMBER(10),
  T_ID_PROCESSING_LOG  NUMBER(10),
  T_TRADEDATE          DATE,
  T_TRADESESSIONDATE   DATE,
  T_SESSIONNO          VARCHAR2(1),
  T_RECNO              NUMBER(10),
  T_ORDERNO            VARCHAR2(20),
  T_STATUS             VARCHAR2(1),
  T_BUYSELL            VARCHAR2(1),
  T_SECURITYID         VARCHAR2(12),
  T_PRICETYPE          VARCHAR2(4),
  T_CURRENCYID         VARCHAR2(3),
  T_PRICE              NUMBER(32,12),
  T_QUANTITY           NUMBER(10),
  T_ENTRYTIME          DATE,
  T_AMENDTIME          DATE,
  T_BROKERREF          VARCHAR2(20),
  T_REPORATE           NUMBER(32,12),
  T_CLIENTCODE         VARCHAR2(12),
  T_TRDACCID           VARCHAR2(12),
  T_REPOVALUE          NUMBER(32,12),
  T_ORDTYPECODE        VARCHAR2(4),
  T_PARTYID            NUMBER(10),
  T_SFCONTRID          NUMBER(10),
  T_ISSEB              NUMBER(5),
  T_OBJECTID           NUMBER(10),
  T_ISREPO             NUMBER(5),
  T_VCLIENTCODE        VARCHAR2(12),
  T_FIID               NUMBER(10),
  T_FILESESSIONNO      NUMBER(5),
  T_UNDERWR            NUMBER(5)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON COLUMN D_SEM02_TMP.T_FILESESSIONNO IS 'Номер сессии из наименования файла'
/

COMMENT ON COLUMN D_SEM02_TMP.T_UNDERWR IS 'Признак Андеррайтинга или Агента по приобретению облигаций'
/

CREATE UNIQUE INDEX D_SEM02_TMP_IDX0 ON D_SEM02_TMP
(T_ID_MB_SEM02)
/

CREATE INDEX D_SEM02_TMP_IDX1 ON D_SEM02_TMP
(T_ORDERNO)
/

CREATE INDEX D_SEM02_TMP_IDX2 ON D_SEM02_TMP
(T_VCLIENTCODE)
/

CREATE INDEX D_SEM02_TMP_IDX3 ON D_SEM02_TMP
(T_SECURITYID)
/

CREATE INDEX D_SEM02_TMP_IDX4 ON D_SEM02_TMP
(T_TRADEDATE)
/

CREATE INDEX D_SEM02_TMP_IDX5 ON D_SEM02_TMP
(T_TRDACCID)
/