/* ──────────────────────────────────────────────────────────────────────────┐
   RS-Bank V6                                                 R-Style Softlab
   Файл подсистемы "Регламентированная отчетность"

   Классы протокола расчета отчета

   CREATED : 08.12.08 Ser.
└─────────────────────────────────────────────────────────────────────────- */
/**
 * Абстрактный класс представления протокола данных
 */
class RcbDataProtocolView(id : String, isInnerBorders : Bool, offset : Integer)
    /**
     * Идентификатор
     */
    private var m_id    = id;

    /**
     * Выводить ли внутренние границы колонок, поумолчанию выводим
     */
    private var m_isInnerBorders = nvl(isInnerBorders, true);

    /**
     * Отступ от левого края
     */
    private var m_offset = nvl(isInnerBorders, 0);

    /**
     * Таблица для вывода информации
     */
    private var m_table = CTableReport(m_offset, false, not m_isInnerBorders);

    macro getWidth()
        m_table.getSumLen();
    end;

    macro getId()
        return m_id;
    end;

    macro printHead()
        throw(TPureVirtualMethodCallException("RcbDataProtocolView::printHead"));
    end;

    macro printString()
        throw(TPureVirtualMethodCallException("RcbDataProtocolView::printString"));
    end;

    macro printItog()
        throw(TPureVirtualMethodCallException("RcbDataProtocolView::printItog"));
    end;

    macro printBottom()
        throw(TPureVirtualMethodCallException("RcbDataProtocolView::printBottom"));
    end;

    macro printSeparator()
        throw(TPureVirtualMethodCallException("RcbDataProtocolView::printSeparator"));
    end;

    private macro initialize()
        throw(TPureVirtualMethodCallException("RcbDataProtocolView::initialize"));
    end;

    initialize();
end;

/**
 * Класс протокола расчета
 */
class (TProtocolView) RcbCalculateProtocolView(reportName : String, protocolName : String)
    initTProtocolView(nvl(protocolName, "ПРОТОКОЛ РАСЧЕТА"), reportName);
    /**
     * Контейнер для хранения представлений протокола для конкретного ИД
     */
    private var m_dataProtocolViewPull = RcbArray();

    /**
     * Вернуть представление протокола для требуемого ИД

     * @param     Id идентификатор протокола (совпадает с идентификатором ИД)
     *
     * @return    возвращает требуемое представление протокола данных
     */
    macro getDataProtocolView(id : String) : RcbDataProtocolView

        m_dataProtocolViewPull.moveFirst();

        while (m_dataProtocolViewPull.moveNext())
            if (m_dataProtocolViewPull.getCurrentItem().getId() == id)
                return m_dataProtocolViewPull.getCurrentItem();
            end;
        end;

        return null;
    end;

    private macro initialize()
        throw(TPureVirtualMethodCallException("RcbCalculateProtocolView::initialize"));
    end;

    initialize();
end;