/*
$Name:          ReportNormalizationAlgorithm.mac
$Module:        Регламентируемая отчетность
$Description:   Класс для работы с алгоритмами нормализации
*/

const JAVA_MMB_NORMALIZER = 1;
const CPP_MMB_NORMALIZER  = 2;
const JAVA_SM_NORMALIZER  = 3;

const IS_CPP_NORMALIZER = true;

class TReportNormalizationAlgorithm()
    var m_reportNormalizationAlgorithm;

    macro setReportNormalizationAlgorithm(reportNormalizationAlgorithm : integer)
        m_reportNormalizationAlgorithm = reportNormalizationAlgorithm;
    end;

    macro getReportNormalizationAlgorithm() : Integer
        return m_reportNormalizationAlgorithm;
    end;

    private macro constructorTReportNormalizationAlgorithm()
        if (rcbApplication.currentReport.normalizationAlgorithm == RCB_NA_MMB)
            if (IS_CPP_NORMALIZER)
                m_reportNormalizationAlgorithm = CPP_MMB_NORMALIZER;
            else
                m_reportNormalizationAlgorithm = JAVA_MMB_NORMALIZER;
            end;
        elif(rcbApplication.currentReport.normalizationAlgorithm == RCB_NA_SM)
             m_reportNormalizationAlgorithm = JAVA_SM_NORMALIZER;
        else
             m_reportNormalizationAlgorithm = CPP_MMB_NORMALIZER;
        end;
    end;

    constructorTReportNormalizationAlgorithm();
end;

/**
 * Точка доступа
 */
const NormalizationAlgorithm: Object = TReportNormalizationAlgorithm();
