/* ──────────────────────────────────────────────────────────────────────────┐
   RS-Bank V6                                                 R-Style Softlab
   Файл подсистемы "Регламентированная отчетность"

   Расчет формы 118 по данным Loans

   MODIFICATIONS:
   NOTES:

└─────────────────────────────────────────────────────────────────────────- */
import rcb_bo;
import rcb_lib;
import RsbObjFactory;
import DepartmentFilter;
import ReptCBInter;

private macro processCreditPart()
    var part = rcbGetObject("RcbCreditPart118");

    part.setFilter("isOpenedAtEndDate = 1 AND " + rcbBranchAndDepartmentFieldFilter().getAsSqlString("creditFNCash", "creditTerritorialStruct")); 
    
    var mapper = TRSVoxMapper("df118_tmp");

    mapper.addLink("backOffice",          "t_backOffice");
    mapper.addLink("creditNumber",        "t_contractNumber");
    mapper.addLink("creditOpenDate",      "t_contractOpenDate");
    mapper.addLink("reportColumn",        "t_column");
    mapper.addLink("rest",                "t_rest");
    mapper.addLink("contractorId",        "t_partyId");
    mapper.addLink("contractorFullName",  "t_partyName");
    mapper.addLink("contractorGvz",       "t_gvz");
    mapper.addLink("calculateValue",      "t_calculateValue");
    mapper.addLink("reserve",             "t_reserve");
    mapper.addLink("restWithoutReserve",  "t_woReserve");
    mapper.addLink("krv",                 "t_krv");
    mapper.addLink("kra",                 "t_kra");
    mapper.addLink("weightedAssets",      "t_weightedAssets");
    mapper.addLink("krvWithoutRisk",      "t_krvWoRisk");
    mapper.addLink("creditEquivalent",    "t_equivalent");
    mapper.addLink("contractorCode",      "t_partyCode");
    mapper.addLink("contractorRelation",  "t_bankRelation");
    mapper.addLink("contractorOwnership", "t_ownershipPattern");

    part.toTable(mapper);
end;

private macro processDelayRegister()
    var register = rcbGetObject("RcbRegister118_1");

    register.setFilter(rcbBranchAndDepartmentFieldFilter().getAsSqlString("creditFNCash", "creditTerritorialStruct")); 
    
    var mapper = TRSVoxMapper("df118_tmp");

    mapper.addLink("backOffice",             "t_backOffice");
    mapper.addLink("creditNumber",           "t_contractNumber");
    mapper.addLink("creditOpenDate",         "t_contractOpenDate");
    mapper.addLink("trancheCbAccountNumber", "t_account");
    mapper.addLink("reportColumn",           "t_column");
    mapper.addLink("roubleRest",             "t_rest");
    mapper.addLink("creditContractorId",     "t_partyId");
    mapper.addLink("contractorFullName",     "t_partyName");
    mapper.addLink("contractorGvz",          "t_gvz");
    mapper.addLink("calculateValue",         "t_calculateValue");
    mapper.addLink("creditDelayedRvpsSum",   "t_reserve");
    mapper.addLink("restWithoutRvps",        "t_woReserve");
    mapper.addLink("kra",                    "t_kra");
    mapper.addLink("weightedAssets",         "t_weightedAssets");
    mapper.addLink("delayTerm",              "t_term");
    mapper.addLink("contractorCode",         "t_partyCode");
    mapper.addLink("contractorRelation",     "t_bankRelation");
    mapper.addLink("contractorOwnership",    "t_ownershipPattern");

    register.toTable(mapper);
end;

private macro processGuaranteeRegister()
    var register = rcbGetObject("RcbRegister118_2");

    register.setFilter(rcbBranchAndDepartmentFieldFilter().getAsSqlString("creditFNCash", "creditTerritorialStruct")); 
    
    var mapper = TRSVoxMapper("df118_tmp");

    mapper.addLink("backOffice",             "t_backOffice");
    mapper.addLink("creditNumber",           "t_contractNumber");
    mapper.addLink("creditOpenDate",         "t_contractOpenDate");
    mapper.addLink("trancheCbAccountNumber", "t_account");
    mapper.addLink("reportColumn",           "t_column");
    mapper.addLink("roubleRest",             "t_rest");
    mapper.addLink("creditContractorId",     "t_partyId");
    mapper.addLink("contractorFullName",     "t_partyName");
    mapper.addLink("contractorGvz",          "t_gvz");
    mapper.addLink("calculateValue",         "t_calculateValue");
    mapper.addLink("creditRvpSum",           "t_reserve");
    mapper.addLink("restWithoutRvp",         "t_woReserve");
    mapper.addLink("krv",                    "t_krv");
    mapper.addLink("kra",                    "t_kra");
    mapper.addLink("weightedAssets",         "t_weightedAssets");
    mapper.addLink("krvWithoutRisk",         "t_krvWoRisk");
    mapper.addLink("creditEquivalent",       "t_equivalent");
    mapper.addLink("contractorCode",         "t_partyCode");
    mapper.addLink("contractorRelation",     "t_bankRelation");
    mapper.addLink("contractorOwnership",    "t_ownershipPattern");

    register.toTable(mapper);
end;

private macro processCredit()
    var credit = rcbGetObject("RcbCredit118");

    credit.setFilter( rcbBranchAndDepartmentFieldFilter().getAsSqlString("fncash", "territorialStruct") 
                    + " AND conversionsCount != 0"); 
    
    var mapper = TRSVoxMapper("df118_tmp");

    mapper.addLink("backOffice",            "t_backOffice");
    mapper.addLink("number",                "t_contractNumber");
    mapper.addLink("openDate",              "t_contractOpenDate");
    mapper.addLink("reportColumn",          "t_column");
    mapper.addLink("contractorId",          "t_partyId");
    mapper.addLink("contractorFullName",    "t_partyName");
    mapper.addLink("contractorGvz",         "t_gvz");
    mapper.addLink("contractorCode",        "t_partyCode");
    mapper.addLink("contractorRelation",    "t_bankRelation");
    mapper.addLink("contractorOwnership",   "t_ownershipPattern");
    mapper.addLink("conversionsCount",      "t_conversionsCount");

    credit.toTable(mapper);
end;

private macro calculate()
    message("Ждите. Идёт обработка частей кредитных договоров...");
    processCreditPart();

    message("Ждите. Идёт обработка просроченных кредитных договоров...");
    processDelayRegister();

    message("Ждите. Идёт обработка гарантий...");
    processGuaranteeRegister();

    message("Ждите. Идёт обработка кредитных договоров...");
    processCredit();
end;

private macro main()
    var bo_loans  = TBackOffice(BOLOANS);
    var tunetable = TTuneTable("dt118_dbt", "t_backOffice");
    if (tuneTable.hasDataFor(bo_loans))
        calculate();
    end;
end;

main();

УстановитьФлагВозврата(OK_MACRO_FLAG);
exit(1);
