/*
$Name:          f128Normalizer.mac
$Module:        Регламентируемая отчетность
$Description:   Форма 128. Нормализатор
*/

import rcbimport;
import ReptcbCommon;
import ReportNormalizer;
import ReportLinearRelation;
import RcbCoreINter;

class (TProtocolView) T128NormalizationProtocolView()
    initTProtocolView("ПРОТОКОЛ ПРОЦЕДУРЫ НОРМАЛИЗАЦИИ");

    private var m_isHeadPrinted = false;
    private var m_isSaparatorPrinted = false;

    macro printNullData()
        [    Корректировок округленных значений символов не потребовалось.];
    end;

    macro beginProtocol()
        setProtocolOutput();
        printHead();
    end;

    macro printSeparatorLine()
        if(m_isSaparatorPrinted)
            [├───────────────────────────────┼────────────────┼─────────────┼─────────────────┼──────────┤];
        end;
    end;

    macro endProtocol()
        if (m_isHeadPrinted)
            [└───────────────────────────────┴────────────────┴─────────────┴─────────────────┴──────────┘];
            [ ];
        end;
        if (m_isEmpty)
            printNullData();
        end;
        resetProtocolOutput();
    end;

    macro printReportAbsence(report)
        printLine("Отсутствует рассчитанная форма " + report.form.name + " за период " + report.context.period.beginDate + " - " + report.context.period.endDate,
                  "В процессе нормализации сходимость с данными этой формы не реализована.",
                  "");
    end;

    macro printString(str : String, exact : Money, scaled : Double)
        var floored = floor(Double(exact) / rcbApplication.currentReport.multiplier + 0.5);

        if (not m_isHeadPrinted)
            [┌───────────────────────────────┬───────────────────────────────────────────────────────────┐];
            [│                               │                          Значение                         │];
            [│         атрибут отчета        ├────────────────┬─────────────┬─────────────────┬──────────┤];
            [│                               │ Действительное │ Округленное │ Нормализованное │ Разность │];
            [├───────────────────────────────┼────────────────┼─────────────┼─────────────────┼──────────┤];
            m_isHeadPrinted = true;
            m_isSaparatorPrinted = true;
        end;

        [│###############################│################│#############│#################│##########│]
        (str, exact, floored : 0 : 0, scaled : 0 : 0, abs(floored - scaled) : 0 : 0);

        m_isEmpty = false;
    end;
end;

class (ReportNormalizer) T128Normalizer(protocolView)

    initReportNormalizer(rcbApplication.currentReport.multiplier);

    private var m_forRulesFirstStringVariablesArray : RcbArray;
    private var m_forRulesSixthStringVariablesArray : RcbArray;
    private var m_forNormSixthVariablesArray        : RcbArray;
    private var m_report;
    private var m_protocolView  = protocolView;

    private macro initVariablesArrays()
        m_forRulesFirstStringVariablesArray = RcbArray().initialize(
        //1 part
        arrCreate("Ф128_810_ФЛ_1_1_С__К_", "Ф128_810_ФЛ_1_2_С__К_", "Ф128_810_ФЛ_1_3_С__К_", "Ф128_810_ФЛ_1_4_С__К_"),
        arrCreate("Ф128_810_ЮЛ_1_1_С__К_", "Ф128_810_ЮЛ_1_2_С__К_", "Ф128_810_ЮЛ_1_3_С__К_", "Ф128_810_ЮЛ_1_4_С__К_"),
        arrCreate("Ф128_810_КО_1_1_С__МК", "Ф128_810_КО_1_2_С__МК", "Ф128_810_КО_1_3_С__МК", "Ф128_810_КО_1_4_С__МК"),
        arrCreate("Ф128_810_НФ_1_1_С__УВ", "Ф128_810_НФ_1_2_С__УВ", "Ф128_810_НФ_1_3_С__УВ", "Ф128_810_НФ_1_4_С__УВ"),
        arrCreate("Ф128_810_КО_1_1_С__УВ", "Ф128_810_КО_1_2_С__УВ", "Ф128_810_КО_1_3_С__УВ", "Ф128_810_КО_1_4_С__УВ"),
        //2 part
        arrCreate("Ф128_840_ФЛ_1_1_С__К_", "Ф128_840_ФЛ_1_2_С__К_", "Ф128_840_ФЛ_1_3_С__К_", "Ф128_840_ФЛ_1_4_С__К_"),
        arrCreate("Ф128_840_ЮЛ_1_1_С__К_", "Ф128_840_ЮЛ_1_2_С__К_", "Ф128_840_ЮЛ_1_3_С__К_", "Ф128_840_ЮЛ_1_4_С__К_"),
        arrCreate("Ф128_840_КО_1_1_С__МК", "Ф128_840_КО_1_2_С__МК", "Ф128_840_КО_1_3_С__МК", "Ф128_840_КО_1_4_С__МК"),
        //3 part
        arrCreate("Ф128_978_ФЛ_1_1_С__К_", "Ф128_978_ФЛ_1_2_С__К_", "Ф128_978_ФЛ_1_3_С__К_", "Ф128_978_ФЛ_1_4_С__К_"),
        arrCreate("Ф128_978_ЮЛ_1_1_С__К_", "Ф128_978_ЮЛ_1_2_С__К_", "Ф128_978_ЮЛ_1_3_С__К_", "Ф128_978_ЮЛ_1_4_С__К_"),
        arrCreate("Ф128_978_КО_1_1_С__МК", "Ф128_978_КО_1_2_С__МК", "Ф128_978_КО_1_3_С__МК", "Ф128_978_КО_1_4_С__МК"));

        m_forRulesSixthStringVariablesArray = RcbArray().initialize(
        //1 part
        arrCreate("Ф128_810_ФЛ_1___С__К_", "Ф128_810_ФЛ_2___С__К_", "Ф128_810_ФЛ_3___С__К_", "Ф128_810_ФЛ_4___С__К_", "Ф128_810_ФЛ_5___С__К_", "Ф128_810_ФЛ_6___С__К_"),
        arrCreate("Ф128_810_ЮЛ_1___С__К_", "Ф128_810_ЮЛ_2___С__К_", "Ф128_810_ЮЛ_3___С__К_", "Ф128_810_ЮЛ_4___С__К_", "Ф128_810_ЮЛ_5___С__К_", "Ф128_810_ЮЛ_6___С__К_"),
        arrCreate("Ф128_810_КО_1___С__МК", "Ф128_810_КО_2___С__МК", "Ф128_810_КО_3___С__МК", "Ф128_810_КО_4___С__МК", "Ф128_810_КО_5___С__МК", "Ф128_810_КО_6___С__МК"),
        arrCreate("Ф128_810_НФ_1___С__УВ", "Ф128_810_НФ_2___С__УВ", "Ф128_810_НФ_3___С__УВ", "Ф128_810_НФ_4___С__УВ", "Ф128_810_НФ_5___С__УВ", "Ф128_810_НФ_6___С__УВ"),
        arrCreate("Ф128_810_КО_1___С__УВ", "Ф128_810_КО_2___С__УВ", "Ф128_810_КО_3___С__УВ", "Ф128_810_КО_4___С__УВ", "Ф128_810_КО_5___С__УВ", "Ф128_810_КО_6___С__УВ"),
        //2 part
        arrCreate("Ф128_840_ФЛ_1___С__К_", "Ф128_840_ФЛ_2___С__К_", "Ф128_840_ФЛ_3___С__К_", "Ф128_840_ФЛ_4___С__К_", "Ф128_840_ФЛ_5___С__К_", "Ф128_840_ФЛ_6___С__К_"),
        arrCreate("Ф128_840_ЮЛ_1___С__К_", "Ф128_840_ЮЛ_2___С__К_", "Ф128_840_ЮЛ_3___С__К_", "Ф128_840_ЮЛ_4___С__К_", "Ф128_840_ЮЛ_5___С__К_", "Ф128_840_ЮЛ_6___С__К_"),
        arrCreate("Ф128_840_КО_1___С__МК", "Ф128_840_КО_2___С__МК", "Ф128_840_КО_3___С__МК", "Ф128_840_КО_4___С__МК", "Ф128_840_КО_5___С__МК", "Ф128_840_КО_6___С__МК"),
        //3 part
        arrCreate("Ф128_978_ФЛ_1___С__К_", "Ф128_978_ФЛ_2___С__К_", "Ф128_978_ФЛ_3___С__К_", "Ф128_978_ФЛ_4___С__К_", "Ф128_978_ФЛ_5___С__К_", "Ф128_978_ФЛ_6___С__К_"),
        arrCreate("Ф128_978_ЮЛ_1___С__К_", "Ф128_978_ЮЛ_2___С__К_", "Ф128_978_ЮЛ_3___С__К_", "Ф128_978_ЮЛ_4___С__К_", "Ф128_978_ЮЛ_5___С__К_", "Ф128_978_ЮЛ_6___С__К_"),
        arrCreate("Ф128_978_КО_1___С__МК", "Ф128_978_КО_2___С__МК", "Ф128_978_КО_3___С__МК", "Ф128_978_КО_4___С__МК", "Ф128_978_КО_5___С__МК", "Ф128_978_КО_6___С__МК"));

        m_forNormSixthVariablesArray = RcbArray().initialize(
        //part 1
        "Ф128_810_ФЛ_И___С__К_", "Ф128_810_ЮЛ_И___С__К_", "Ф128_810_КО_И___С__МК", "Ф128_810_НФ_И___С__УВ", "Ф128_810_КО_И___С__УВ",
        //part 2
        "Ф128_840_ФЛ_И___С__К_", "Ф128_840_ЮЛ_И___С__К_", "Ф128_840_КО_И___С__МК",
        //part 3
        "Ф128_978_ФЛ_И___С__К_", "Ф128_978_ЮЛ_И___С__К_", "Ф128_978_КО_И___С__МК");
    end;

    private macro initializeNode(currentNode, id, exact : Money)
        var node = currentNode.addNode(id);
        node.setExact(nvl(exact, 0.0));
        node.recalculateScaled();

        return node;
    end;

    private macro addRules(norm)
        var currentColumnItem;
        var currentStringItem;
        var stringNode;
        var columnNode;
        var i,j;

        //первая строка
        i = 0;
        m_forRulesSixthStringVariablesArray.moveFirst();
        while (m_forRulesSixthStringVariablesArray.moveNext())
            currentStringItem = m_forRulesSixthStringVariablesArray.getCurrentItem()[0]; //имя переменной для первой строки
            stringNode        = initializeNode(norm, "node_" + toAnsi(currentStringItem, true), m_report.attributeValue(currentStringItem).exact);
            j =0;
            while (j < m_forRulesFirstStringVariablesArray[i]().size)
                currentColumnItem = m_forRulesFirstStringVariablesArray[i][j];
                columnNode        = initializeNode(stringNode, "node_" + toAnsi(currentColumnItem, true), m_report.attributeValue(currentColumnItem).exact);
                j = j+1;
            end;
            i = i+1;
        end;

        //итого
        i = 0;
        m_forNormSixthVariablesArray.moveFirst();
        while (m_forNormSixthVariablesArray.moveNext())
            currentStringItem = m_forNormSixthVariablesArray.getCurrentItem();
            stringNode        = initializeNode(norm, "node_" + toAnsi(currentStringItem, true), m_report.attributeValue(currentStringItem).exact);
            j = 0;
            while (j < m_forRulesSixthStringVariablesArray[i]().size)
                currentColumnItem = m_forRulesSixthStringVariablesArray[i][j];
                columnNode        = initializeNode(stringNode, "node_" + toAnsi(currentColumnItem, true), m_report.attributeValue(currentColumnItem).exact);
                j = j+1;
            end;
            i = i+1;
        end;
    end;

    private macro saveScaledValue(attribute, value)
        if (ValType(attribute.scaled) == V_DOUBLE)
            attribute.scaled = double(value);
        elif (ValType(attribute.scaled) == V_MONEY)
            attribute.scaled = money(value);
        else
            attribute.scaled = int(value);
        end;
    end;

    private macro nullingPairPercentVariable(summAttributeVariable)
        var percentAttributeVariable;
        var percentVariableName;
        var summVariableName          = summAttributeVariable.attribute.id;

        if ((Index(summVariableName, "_71_") == 0) and
            (Index(summVariableName, "_72_") == 0) and
            (Index(summVariableName, "_И_")  == 0) and
            (summAttributeVariable.scaled    == 0))
                percentVariableName      = StrSubst(summVariableName, "_С_", "_%_");
                percentAttributeVariable = m_report.attributeValue(percentVariableName);
                saveScaledValue(percentAttributeVariable, 0);
        end;
    end;

    private macro saveNormValues(norm)
        var currentAttributeValue;
        var formVariableName;
        var attributeValueIterator = m_report.createAttributeValueIterator();

        attributeValueIterator.moveFirst();
        while (not attributeValueIterator.isDone())
            currentAttributeValue = attributeValueIterator.currentItem();
            formVariableName      = currentAttributeValue.attribute.id;

            if (norm.Node("node_" + formVariableName) != null)
                if (norm.Node("node_" + formVariableName).getScaled() != floor(Double(nvl(currentAttributeValue.exact, 0.0))/m_report.multiplier + 0.5))
                     m_protocolView.printSeparatorLine();
                     m_protocolView.printString(formVariableName, norm.Node("node_" + formVariableName).getExact(), norm.Node("node_" + formVariableName).getScaled());
                end;
                saveScaledValue(currentAttributeValue, norm.Node("node_" + formVariableName).getScaled());
            end;

            if (Index(formVariableName, "_%_") == 0)
                nullingPairPercentVariable(currentAttributeValue);
            end;

            attributeValueIterator.moveNext();
        end;
    end;

    macro showProtocol()
        var protocol            = TSummaryProtocolView();
        var protocolDescription = "ПРОТОКОЛ ПРОЦЕДУРЫ НОРМАЛИЗАЦИИ";

        protocol.add(TProtocolView(protocolDescription));
        protocol.show();
    end;

    private macro initialize()
        m_report = rcbApplication.currentReport;
        initVariablesArrays();
    end;

    macro execute()
        var norm = ReportNormalizer(m_report.multiplier);

        m_protocolView.beginProtocol();

        addRules(norm);
        norm.normalize();

        if (norm.isNormalized() == false)
            m_protocolView.printLine("Данные нормализовать не удалось(см. протокол " + getLogFilePath() + ").");
            m_protocolView.endProtocol();
            showProtocol();
            return;
        end;

        saveNormValues(norm);

        m_protocolView.endProtocol();

        RcbApplication.TransactionManager.commit();

        showProtocol();
    end;

    initialize();
end;

class (T128Normalizer) T128Normalizer3006(protocolView)

    initT128Normalizer(protocolView);

    private macro initVariablesArrays()
        m_forRulesFirstStringVariablesArray = RcbArray().initialize(
        //1 part
        arrCreate("Ф128_810_ФЛ_1_1_С__К_", "Ф128_810_ФЛ_1_2_С__К_", "Ф128_810_ФЛ_1_3_С__К_", "Ф128_810_ФЛ_1_4_С__К_"),
        arrCreate("Ф128_810_ФЛ_1_1_СА_К_", "Ф128_810_ФЛ_1_2_СА_К_", "Ф128_810_ФЛ_1_3_СА_К_", "Ф128_810_ФЛ_1_4_СА_К_"),
        arrCreate("Ф128_810_ЮЛ_1_1_С__К_", "Ф128_810_ЮЛ_1_2_С__К_", "Ф128_810_ЮЛ_1_3_С__К_", "Ф128_810_ЮЛ_1_4_С__К_"),
        arrCreate("Ф128_810_ЮЛ_1_1_СП_К_", "Ф128_810_ЮЛ_1_2_СП_К_", "Ф128_810_ЮЛ_1_3_СП_К_", "Ф128_810_ЮЛ_1_4_СП_К_"),
        arrCreate("Ф128_810_КО_1_1_С__МК", "Ф128_810_КО_1_2_С__МК", "Ф128_810_КО_1_3_С__МК", "Ф128_810_КО_1_4_С__МК"),
        arrCreate("Ф128_810_НФ_1_1_С__УВ", "Ф128_810_НФ_1_2_С__УВ", "Ф128_810_НФ_1_3_С__УВ", "Ф128_810_НФ_1_4_С__УВ"),
        arrCreate("Ф128_810_КО_1_1_С__УВ", "Ф128_810_КО_1_2_С__УВ", "Ф128_810_КО_1_3_С__УВ", "Ф128_810_КО_1_4_С__УВ"),
        //2 part
        arrCreate("Ф128_840_ФЛ_1_1_С__К_", "Ф128_840_ФЛ_1_2_С__К_", "Ф128_840_ФЛ_1_3_С__К_", "Ф128_840_ФЛ_1_4_С__К_"),
        arrCreate("Ф128_840_ФЛ_1_1_СА_К_", "Ф128_840_ФЛ_1_2_СА_К_", "Ф128_840_ФЛ_1_3_СА_К_", "Ф128_840_ФЛ_1_4_СА_К_"),
        arrCreate("Ф128_840_ЮЛ_1_1_С__К_", "Ф128_840_ЮЛ_1_2_С__К_", "Ф128_840_ЮЛ_1_3_С__К_", "Ф128_840_ЮЛ_1_4_С__К_"),
        arrCreate("Ф128_840_ЮЛ_1_1_СП_К_", "Ф128_840_ЮЛ_1_2_СП_К_", "Ф128_840_ЮЛ_1_3_СП_К_", "Ф128_840_ЮЛ_1_4_СП_К_"),
        arrCreate("Ф128_840_КО_1_1_С__МК", "Ф128_840_КО_1_2_С__МК", "Ф128_840_КО_1_3_С__МК", "Ф128_840_КО_1_4_С__МК"),
        //3 part
        arrCreate("Ф128_978_ФЛ_1_1_С__К_", "Ф128_978_ФЛ_1_2_С__К_", "Ф128_978_ФЛ_1_3_С__К_", "Ф128_978_ФЛ_1_4_С__К_"),
        arrCreate("Ф128_978_ФЛ_1_1_СА_К_", "Ф128_978_ФЛ_1_2_СА_К_", "Ф128_978_ФЛ_1_3_СА_К_", "Ф128_978_ФЛ_1_4_СА_К_"),
        arrCreate("Ф128_978_ЮЛ_1_1_С__К_", "Ф128_978_ЮЛ_1_2_С__К_", "Ф128_978_ЮЛ_1_3_С__К_", "Ф128_978_ЮЛ_1_4_С__К_"),
        arrCreate("Ф128_978_ЮЛ_1_1_СП_К_", "Ф128_978_ЮЛ_1_2_СП_К_", "Ф128_978_ЮЛ_1_3_СП_К_", "Ф128_978_ЮЛ_1_4_СП_К_"),
        arrCreate("Ф128_978_КО_1_1_С__МК", "Ф128_978_КО_1_2_С__МК", "Ф128_978_КО_1_3_С__МК", "Ф128_978_КО_1_4_С__МК"));

        m_forRulesSixthStringVariablesArray = RcbArray().initialize(
        //1 part
        arrCreate("Ф128_810_ФЛ_1___С__К_", "Ф128_810_ФЛ_2___С__К_", "Ф128_810_ФЛ_3___С__К_", "Ф128_810_ФЛ_4___С__К_", "Ф128_810_ФЛ_5___С__К_", "Ф128_810_ФЛ_6___С__К_"),
        arrCreate("Ф128_810_ФЛ_1___СА_К_", "Ф128_810_ФЛ_2___СА_К_", "Ф128_810_ФЛ_3___СА_К_", "Ф128_810_ФЛ_4___СА_К_", "Ф128_810_ФЛ_5___СА_К_", "Ф128_810_ФЛ_6___СА_К_"),
        arrCreate("Ф128_810_ЮЛ_1___С__К_", "Ф128_810_ЮЛ_2___С__К_", "Ф128_810_ЮЛ_3___С__К_", "Ф128_810_ЮЛ_4___С__К_", "Ф128_810_ЮЛ_5___С__К_", "Ф128_810_ЮЛ_6___С__К_"),
        arrCreate("Ф128_810_ЮЛ_1___СП_К_", "Ф128_810_ЮЛ_2___СП_К_", "Ф128_810_ЮЛ_3___СП_К_", "Ф128_810_ЮЛ_4___СП_К_", "Ф128_810_ЮЛ_5___СП_К_", "Ф128_810_ЮЛ_6___СП_К_"),
        arrCreate("Ф128_810_КО_1___С__МК", "Ф128_810_КО_2___С__МК", "Ф128_810_КО_3___С__МК", "Ф128_810_КО_4___С__МК", "Ф128_810_КО_5___С__МК", "Ф128_810_КО_6___С__МК"),
        arrCreate("Ф128_810_НФ_1___С__УВ", "Ф128_810_НФ_2___С__УВ", "Ф128_810_НФ_3___С__УВ", "Ф128_810_НФ_4___С__УВ", "Ф128_810_НФ_5___С__УВ", "Ф128_810_НФ_6___С__УВ"),
        arrCreate("Ф128_810_КО_1___С__УВ", "Ф128_810_КО_2___С__УВ", "Ф128_810_КО_3___С__УВ", "Ф128_810_КО_4___С__УВ", "Ф128_810_КО_5___С__УВ", "Ф128_810_КО_6___С__УВ"),
        //2 part
        arrCreate("Ф128_840_ФЛ_1___С__К_", "Ф128_840_ФЛ_2___С__К_", "Ф128_840_ФЛ_3___С__К_", "Ф128_840_ФЛ_4___С__К_", "Ф128_840_ФЛ_5___С__К_", "Ф128_840_ФЛ_6___С__К_"),
        arrCreate("Ф128_840_ФЛ_1___СА_К_", "Ф128_840_ФЛ_2___СА_К_", "Ф128_840_ФЛ_3___СА_К_", "Ф128_840_ФЛ_4___СА_К_", "Ф128_840_ФЛ_5___СА_К_", "Ф128_840_ФЛ_6___СА_К_"),
        arrCreate("Ф128_840_ЮЛ_1___С__К_", "Ф128_840_ЮЛ_2___С__К_", "Ф128_840_ЮЛ_3___С__К_", "Ф128_840_ЮЛ_4___С__К_", "Ф128_840_ЮЛ_5___С__К_", "Ф128_840_ЮЛ_6___С__К_"),
        arrCreate("Ф128_840_ЮЛ_1___СП_К_", "Ф128_840_ЮЛ_2___СП_К_", "Ф128_840_ЮЛ_3___СП_К_", "Ф128_840_ЮЛ_4___СП_К_", "Ф128_840_ЮЛ_5___СП_К_", "Ф128_840_ЮЛ_6___СП_К_"),
        arrCreate("Ф128_840_КО_1___С__МК", "Ф128_840_КО_2___С__МК", "Ф128_840_КО_3___С__МК", "Ф128_840_КО_4___С__МК", "Ф128_840_КО_5___С__МК", "Ф128_840_КО_6___С__МК"),
        //3 part
        arrCreate("Ф128_978_ФЛ_1___С__К_", "Ф128_978_ФЛ_2___С__К_", "Ф128_978_ФЛ_3___С__К_", "Ф128_978_ФЛ_4___С__К_", "Ф128_978_ФЛ_5___С__К_", "Ф128_978_ФЛ_6___С__К_"),
        arrCreate("Ф128_978_ФЛ_1___СА_К_", "Ф128_978_ФЛ_2___СА_К_", "Ф128_978_ФЛ_3___СА_К_", "Ф128_978_ФЛ_4___СА_К_", "Ф128_978_ФЛ_5___СА_К_", "Ф128_978_ФЛ_6___СА_К_"),
        arrCreate("Ф128_978_ЮЛ_1___С__К_", "Ф128_978_ЮЛ_2___С__К_", "Ф128_978_ЮЛ_3___С__К_", "Ф128_978_ЮЛ_4___С__К_", "Ф128_978_ЮЛ_5___С__К_", "Ф128_978_ЮЛ_6___С__К_"),
        arrCreate("Ф128_978_ЮЛ_1___СП_К_", "Ф128_978_ЮЛ_2___СП_К_", "Ф128_978_ЮЛ_3___СП_К_", "Ф128_978_ЮЛ_4___СП_К_", "Ф128_978_ЮЛ_5___СП_К_", "Ф128_978_ЮЛ_6___СП_К_"),
        arrCreate("Ф128_978_КО_1___С__МК", "Ф128_978_КО_2___С__МК", "Ф128_978_КО_3___С__МК", "Ф128_978_КО_4___С__МК", "Ф128_978_КО_5___С__МК", "Ф128_978_КО_6___С__МК"));

        m_forNormSixthVariablesArray = RcbArray().initialize(
        //part 1
        "Ф128_810_ФЛ_И___С__К_", "Ф128_810_ФЛ_И___СА_К_", "Ф128_810_ЮЛ_И___С__К_", "Ф128_810_ЮЛ_И___СП_К_", "Ф128_810_КО_И___С__МК", "Ф128_810_НФ_И___С__УВ", "Ф128_810_КО_И___С__УВ",
        //part 2
        "Ф128_840_ФЛ_И___С__К_", "Ф128_840_ФЛ_И___СА_К_", "Ф128_840_ЮЛ_И___С__К_", "Ф128_840_ЮЛ_И___СП_К_", "Ф128_840_КО_И___С__МК",
        //part 3
        "Ф128_978_ФЛ_И___С__К_", "Ф128_978_ФЛ_И___СА_К_", "Ф128_978_ЮЛ_И___С__К_", "Ф128_978_ЮЛ_И___СП_К_", "Ф128_978_КО_И___С__МК");
    end;

    /**
     * Добавить линейное отношение для граф (3,5,7,9).
     * @param STRING currentNameItem Наименование текущего элемента(переменной).
     * @param ReportNormalizer normalizator Нормализатор.
     * Выполняет следующие ограничения: графа3 >= графа5, графа7 >= графа9.
     */
    private macro addRelationForColumn(currentNameItem: String, normalizator: ReportNormalizer)
        /**
         * Наименование графы 3 или 7.
         */
        var currentNameItemColumn37: String = "";

        if (index(currentNameItem, "_СА_К_") != 0)                                  /* note: является графой 5 */
            currentNameItemColumn37 = strSubSt(currentNameItem,"_СА_К_","_С__К_")   /* note: графа 3           */
        elif (index(currentNameItem, "_СП_К_") != 0)                                /* note: является графой 9 */
            currentNameItemColumn37 = strSubSt(currentNameItem,"_СП_К_","_С__К_")   /* note: графа 7           */
        else
            return;
        end;

        var relation = ReportLinearRelation(RCB_RS_GREATER_OR_EQUAL);
        relation.rhs.plus(normalizator.addNode(toAnsi("node_" + currentNameItem, true)));
        relation.lhs.plus(normalizator.addNode(toAnsi("node_" + currentNameItemColumn37, true)));
        normalizator.addRelation(relation);

        return;
    end;

    /**
     * Добавить правила нормализации.
     * Строится дерево узлов. Также добавляются линейные отношения для граф 3-5 и 7-9.
     * @param norm Нормализатор.
     */
    private macro addRules(norm)
        var currentColumnItem;
        var currentStringItem;
        var stringNode;
        var columnNode;
        var i,j;

        /**
         * Линейное отношение.
         */
        var relation;

        //первая строка
        i = 0;
        m_forRulesSixthStringVariablesArray.moveFirst();
        while (m_forRulesSixthStringVariablesArray.moveNext())
            currentStringItem = m_forRulesSixthStringVariablesArray.getCurrentItem()[0]; //имя переменной для первой строки
            stringNode        = initializeNode(norm, "node_" + toAnsi(currentStringItem, true), m_report.attributeValue(currentStringItem).exact);
            j =0;
            while (j < m_forRulesFirstStringVariablesArray[i]().size)
                currentColumnItem = m_forRulesFirstStringVariablesArray[i][j];
                columnNode        = initializeNode(stringNode, "node_" + toAnsi(currentColumnItem, true), m_report.attributeValue(currentColumnItem).exact);
                addRelationForColumn(currentColumnItem, norm);
                j = j+1;
            end;
            i = i+1;
        end;

        //итого
        i = 0;
        m_forNormSixthVariablesArray.moveFirst();
        while (m_forNormSixthVariablesArray.moveNext())
            currentStringItem = m_forNormSixthVariablesArray.getCurrentItem();
            stringNode        = initializeNode(norm, "node_" + toAnsi(currentStringItem, true), m_report.attributeValue(currentStringItem).exact);
            j = 0;
            while (j < m_forRulesSixthStringVariablesArray[i]().size)
                currentColumnItem = m_forRulesSixthStringVariablesArray[i][j];
                columnNode        = initializeNode(stringNode, "node_" + toAnsi(currentColumnItem, true), m_report.attributeValue(currentColumnItem).exact);
                addRelationForColumn(currentColumnItem, norm);
                j = j+1;
            end;
            i = i+1;
        end;
    end;

    private macro nullingPairPercentVariable(summAttributeVariable)
        var percentAttributeVariable;
        var percentVariableName;
        var summVariableName          = summAttributeVariable.attribute.id;

        if ((Index(summVariableName, "_71_") == 0) and
            (Index(summVariableName, "_72_") == 0) and
            (Index(summVariableName, "_И_")  == 0) and
            (summAttributeVariable.scaled    == 0))
                percentVariableName      = strSubst(StrSubst(summVariableName, "_С_", "_%_"), "_СА", "_%А") ;
                percentAttributeVariable = m_report.attributeValue(percentVariableName);
                saveScaledValue(percentAttributeVariable, 0);
        end;
    end;

    private macro saveNormValues(norm)
        var currentAttributeValue;
        var formVariableName;
        var attributeValueIterator = m_report.createAttributeValueIterator();

        attributeValueIterator.moveFirst();
        while (not attributeValueIterator.isDone())
            currentAttributeValue = attributeValueIterator.currentItem();
            formVariableName      = currentAttributeValue.attribute.id;

            if (norm.Node("node_" + toAnsi(formVariableName, true)) != null)
                if (norm.Node("node_" + toAnsi(formVariableName, true)).getScaled() != floor(Double(nvl(currentAttributeValue.exact, 0.0))/m_report.multiplier + 0.5))
                     m_protocolView.printSeparatorLine();
                     m_protocolView.printString(formVariableName, norm.Node("node_" + toAnsi(formVariableName, true)).getExact(),
                                                norm.Node("node_" + toAnsi(formVariableName, true)).getScaled());
                end;
                saveScaledValue(currentAttributeValue, norm.Node("node_" + toAnsi(formVariableName, true)).getScaled());
            end;

            if (Index(formVariableName, "_%") == 0)
                nullingPairPercentVariable(currentAttributeValue);
            end;

            attributeValueIterator.moveNext();
        end;
    end;

end;

class (T128Normalizer3006) T128Normalizer4212(protocolView)
    initT128Normalizer3006(protocolView);

    private macro initVariablesArrays()
        m_forRulesFirstStringVariablesArray = RcbArray().initialize(
        //1 part
        arrCreate("Ф128_810_ФЛ_1_1_С__К_", "Ф128_810_ФЛ_1_2_С__К_", "Ф128_810_ФЛ_1_3_С__К_", "Ф128_810_ФЛ_1_4_С__К_"),
        arrCreate("Ф128_810_ФЛ_1_1_СА_К_", "Ф128_810_ФЛ_1_2_СА_К_", "Ф128_810_ФЛ_1_3_СА_К_", "Ф128_810_ФЛ_1_4_СА_К_"),
        arrCreate("Ф128_810_ЮЛ_1_1_С__К_", "Ф128_810_ЮЛ_1_2_С__К_", "Ф128_810_ЮЛ_1_3_С__К_", "Ф128_810_ЮЛ_1_4_С__К_"),
        arrCreate("Ф128_810_ЮЛ_1_1_СП_К_", "Ф128_810_ЮЛ_1_2_СП_К_", "Ф128_810_ЮЛ_1_3_СП_К_", "Ф128_810_ЮЛ_1_4_СП_К_"),
        //2 part
        arrCreate("Ф128_840_ФЛ_1_1_С__К_", "Ф128_840_ФЛ_1_2_С__К_", "Ф128_840_ФЛ_1_3_С__К_", "Ф128_840_ФЛ_1_4_С__К_"),
        arrCreate("Ф128_840_ФЛ_1_1_СА_К_", "Ф128_840_ФЛ_1_2_СА_К_", "Ф128_840_ФЛ_1_3_СА_К_", "Ф128_840_ФЛ_1_4_СА_К_"),
        arrCreate("Ф128_840_ЮЛ_1_1_С__К_", "Ф128_840_ЮЛ_1_2_С__К_", "Ф128_840_ЮЛ_1_3_С__К_", "Ф128_840_ЮЛ_1_4_С__К_"),
        arrCreate("Ф128_840_ЮЛ_1_1_СП_К_", "Ф128_840_ЮЛ_1_2_СП_К_", "Ф128_840_ЮЛ_1_3_СП_К_", "Ф128_840_ЮЛ_1_4_СП_К_"),
        //3 part
        arrCreate("Ф128_978_ФЛ_1_1_С__К_", "Ф128_978_ФЛ_1_2_С__К_", "Ф128_978_ФЛ_1_3_С__К_", "Ф128_978_ФЛ_1_4_С__К_"),
        arrCreate("Ф128_978_ФЛ_1_1_СА_К_", "Ф128_978_ФЛ_1_2_СА_К_", "Ф128_978_ФЛ_1_3_СА_К_", "Ф128_978_ФЛ_1_4_СА_К_"),
        arrCreate("Ф128_978_ЮЛ_1_1_С__К_", "Ф128_978_ЮЛ_1_2_С__К_", "Ф128_978_ЮЛ_1_3_С__К_", "Ф128_978_ЮЛ_1_4_С__К_"),
        arrCreate("Ф128_978_ЮЛ_1_1_СП_К_", "Ф128_978_ЮЛ_1_2_СП_К_", "Ф128_978_ЮЛ_1_3_СП_К_", "Ф128_978_ЮЛ_1_4_СП_К_"));

        m_forRulesSixthStringVariablesArray = RcbArray().initialize(
        //1 part
        arrCreate("Ф128_810_ФЛ_1___С__К_", "Ф128_810_ФЛ_2___С__К_", "Ф128_810_ФЛ_3___С__К_", "Ф128_810_ФЛ_4___С__К_", "Ф128_810_ФЛ_5___С__К_", "Ф128_810_ФЛ_6___С__К_"),
        arrCreate("Ф128_810_ФЛ_1___СА_К_", "Ф128_810_ФЛ_2___СА_К_", "Ф128_810_ФЛ_3___СА_К_", "Ф128_810_ФЛ_4___СА_К_", "Ф128_810_ФЛ_5___СА_К_", "Ф128_810_ФЛ_6___СА_К_"),
        arrCreate("Ф128_810_ЮЛ_1___С__К_", "Ф128_810_ЮЛ_2___С__К_", "Ф128_810_ЮЛ_3___С__К_", "Ф128_810_ЮЛ_4___С__К_", "Ф128_810_ЮЛ_5___С__К_", "Ф128_810_ЮЛ_6___С__К_"),
        arrCreate("Ф128_810_ЮЛ_1___СП_К_", "Ф128_810_ЮЛ_2___СП_К_", "Ф128_810_ЮЛ_3___СП_К_", "Ф128_810_ЮЛ_4___СП_К_", "Ф128_810_ЮЛ_5___СП_К_", "Ф128_810_ЮЛ_6___СП_К_"),
        //2 part
        arrCreate("Ф128_840_ФЛ_1___С__К_", "Ф128_840_ФЛ_2___С__К_", "Ф128_840_ФЛ_3___С__К_", "Ф128_840_ФЛ_4___С__К_", "Ф128_840_ФЛ_5___С__К_", "Ф128_840_ФЛ_6___С__К_"),
        arrCreate("Ф128_840_ФЛ_1___СА_К_", "Ф128_840_ФЛ_2___СА_К_", "Ф128_840_ФЛ_3___СА_К_", "Ф128_840_ФЛ_4___СА_К_", "Ф128_840_ФЛ_5___СА_К_", "Ф128_840_ФЛ_6___СА_К_"),
        arrCreate("Ф128_840_ЮЛ_1___С__К_", "Ф128_840_ЮЛ_2___С__К_", "Ф128_840_ЮЛ_3___С__К_", "Ф128_840_ЮЛ_4___С__К_", "Ф128_840_ЮЛ_5___С__К_", "Ф128_840_ЮЛ_6___С__К_"),
        arrCreate("Ф128_840_ЮЛ_1___СП_К_", "Ф128_840_ЮЛ_2___СП_К_", "Ф128_840_ЮЛ_3___СП_К_", "Ф128_840_ЮЛ_4___СП_К_", "Ф128_840_ЮЛ_5___СП_К_", "Ф128_840_ЮЛ_6___СП_К_"),
        //3 part
        arrCreate("Ф128_978_ФЛ_1___С__К_", "Ф128_978_ФЛ_2___С__К_", "Ф128_978_ФЛ_3___С__К_", "Ф128_978_ФЛ_4___С__К_", "Ф128_978_ФЛ_5___С__К_", "Ф128_978_ФЛ_6___С__К_"),
        arrCreate("Ф128_978_ФЛ_1___СА_К_", "Ф128_978_ФЛ_2___СА_К_", "Ф128_978_ФЛ_3___СА_К_", "Ф128_978_ФЛ_4___СА_К_", "Ф128_978_ФЛ_5___СА_К_", "Ф128_978_ФЛ_6___СА_К_"),
        arrCreate("Ф128_978_ЮЛ_1___С__К_", "Ф128_978_ЮЛ_2___С__К_", "Ф128_978_ЮЛ_3___С__К_", "Ф128_978_ЮЛ_4___С__К_", "Ф128_978_ЮЛ_5___С__К_", "Ф128_978_ЮЛ_6___С__К_"),
        arrCreate("Ф128_978_ЮЛ_1___СП_К_", "Ф128_978_ЮЛ_2___СП_К_", "Ф128_978_ЮЛ_3___СП_К_", "Ф128_978_ЮЛ_4___СП_К_", "Ф128_978_ЮЛ_5___СП_К_", "Ф128_978_ЮЛ_6___СП_К_"));

        m_forNormSixthVariablesArray = RcbArray().initialize(
        //part 1
        "Ф128_810_ФЛ_И___С__К_", "Ф128_810_ФЛ_И___СА_К_", "Ф128_810_ЮЛ_И___С__К_", "Ф128_810_ЮЛ_И___СП_К_",
        //part 2
        "Ф128_840_ФЛ_И___С__К_", "Ф128_840_ФЛ_И___СА_К_", "Ф128_840_ЮЛ_И___С__К_", "Ф128_840_ЮЛ_И___СП_К_",
        //part 3
        "Ф128_978_ФЛ_И___С__К_", "Ф128_978_ФЛ_И___СА_К_", "Ф128_978_ЮЛ_И___С__К_", "Ф128_978_ЮЛ_И___СП_К_");
    end;
end;

macro executeNormalizationOperation()
    RcbApplication.currentReport.reload();

    if   (rcbApplication.currentReport.context.period.endDate >= RCB_I4212_DATE)
        T128Normalizer4212(T128NormalizationProtocolView()).execute();
    elif (rcbApplication.currentReport.context.period.endDate >= RCB_I3006_DATE2)
        T128Normalizer3006(T128NormalizationProtocolView()).execute();
    else
        T128Normalizer(T128NormalizationProtocolView()).execute();
    end;
end;

macro showProtocolView()
    T128Normalizer(T128NormalizationProtocolView()).showProtocol();
end;

установитьФлагВозврата(OK_MACRO_FLAG);
exit(1);
