/*
$Name:        p_f501.mac
$Module:      Регламентируемая отчетность.
$Description: Форма 501. Расчет формы.
*/
/*─────────────────────────────────────────────────────────────────────────────────────────────────┐
  RS-Bank V6                                                                        R-Style Softlab
  Файл подсистемы "Регламентируемая отчетность"

  Расчет формы 501.

  Создан: 16.10.2006 - Ser.
└─────────────────────────────────────────────────────────────────────────────────────────────────*/
/*
 *  Общебанковские интеры и модули
 */
import rsbDataSet;
import param;
/*
 *  Интеры и модели подсистемы
 */
import reptCbInter;
import rcbCoreInter;
import RcbPrintableView;
import rcbImport;
import rcbconst;
import or_rep_h;
import CbReport_h;
import com_f501;

const F501_REPORT_FORMAT_TXT = "txt";
const F501_REPORT_FORMAT_XLS = "xls";

private var numPage         = 1;

class TFilter()
    macro isSuitable(v : Object)
        return (   (v.fieldValue("ОстВход").scaled  != 0)
                or (v.fieldValue("ОбДебет").scaled  != 0)
                or (v.fieldValue("ОбКредит").scaled != 0)
                or (v.fieldValue("ОстИсход").scaled != 0))
    end;
end;

class TFilterManualInput()
    macro isSuitable(v : Object)
        return ((   (v.fieldValue("ОстВход_ввод").scaled     != 0)
                or  (v.fieldValue("ОбДебет_ввод").scaled     != 0)
                or  (v.fieldValue("ОбКредит_ввод").scaled    != 0)
                or  (v.fieldValue("ОстИсход_ввод").scaled    != 0))
                and (v.fieldValue("КодКлиента_ввод").current != "")
                and (valType(v.fieldValue("НаимКО").current) != V_UNDEF)
                and (v.fieldValue("НомЛС_ввод").current      != "")
                and (v.fieldValue("НомБС_ввод").current      != "")
                and (v.fieldValue("ДатаИспОб_ввод").current  != "")
               )
    end;
end;

/**
 *  Параметры отчета
 */
class TParameters()
    private var sortBalance = false;
    private var sortClient  = 0;

    private macro constructor()
        GetRegistryValue("REPTREG\\REP_GROUPS\\ФОРМА 501\\СОРТИРОВКА\\ПО БАЛАНСОВЫМ", V_BOOL, sortBalance, NULL);
        GetRegistryValue("REPTREG\\REP_GROUPS\\ФОРМА 501\\СОРТИРОВКА\\ПО КЛИЕНТАМ", V_INTEGER, sortClient, NULL);
    end;

    macro isSortBalance()
        return sortBalance;
    end;

    macro isSortClient()
        return (sortClient == 5);
    end;

    constructor();
end;

/**
 *  Сортировщик
 *  @since 6.00.020.29
 *  @author Dmitry Shestakov
 */
class TSorter()
    private var parameters;

    /**
     *  функция для сортировки (оператор меньше)
     */
    macro isLess(v1, v2)
        var client:string;

        if (parameters.isSortClient())
            client = "НаимКО";
        else
            client = "КодКО";
        end;

        if (parameters.isSortBalance())
            if (v1.fieldValue("НомБС").exact < v2.fieldValue("НомБС").exact)
                return true;
            elif (v1.fieldValue("НомБС").exact == v2.fieldValue("НомБС").exact)
                if (v1.fieldValue(client).exact < v2.fieldValue(client).exact)
                    return true;
                elif (v1.fieldValue(client).exact == v2.fieldValue(client).exact)
                    if (v1.fieldValue("НомЛС").exact < v2.fieldValue("НомЛС").exact)
                        return true;
                    end;
                end;
            end;

            return false;
        else
            if (v1.fieldValue(client).exact < v2.fieldValue(client).exact)
                return true;
            elif (v1.fieldValue(client).exact == v2.fieldValue(client).exact)
                if (v1.fieldValue("НомЛС").exact < v2.fieldValue("НомЛС").exact)
                    return true;
                end;
            end;

            return false;
        end;
    end;

    private macro constructorTSorter()
        parameters = TParameters();
    end;

    constructorTSorter()
end;

class TSorterManualInput()
    private var parameters;

    /**
     *  функция для сортировки (оператор меньше)
     */
    macro isLess(v1, v2)
        var client:string;

        if (parameters.isSortClient())
            client = "НаимКО";
        else
            client = "КодКО";
        end;
        if (parameters.isSortBalance())
            if (v1.fieldValue("НомБС_ввод").exact < v2.fieldValue("НомБС_ввод").exact)
                return true;
            elif (v1.fieldValue("НомБС_ввод").exact == v2.fieldValue("НомБС_ввод").exact)
                if (v1.fieldValue(client).exact < v2.fieldValue(client).exact)
                    return true;
                elif (v1.fieldValue(client).exact == v2.fieldValue(client).exact)
                    if (v1.fieldValue("НомЛС_ввод").exact < v2.fieldValue("НомЛС_ввод").exact)
                        return true;
                    end;
                end;
            end;
            return false;
        else
            if (v1.fieldValue(client).exact < v2.fieldValue(client).exact)
                return true;
            elif (v1.fieldValue(client).exact == v2.fieldValue(client).exact)
                if (v1.fieldValue("НомЛС_ввод").exact < v2.fieldValue("НомЛС_ввод").exact)
                    return true;
                end;
            end;
            return false;
        end;
    end;

    private macro constructorTSorter()
        parameters = TParameters();
    end;

    constructorTSorter()
end;

/**
 *  Класс вывода таблицы формы 501
 *  @since 6.00.020.29
 *  @author Dmitry Shestakov
 */
private class TTableView_I2121()
    private var m_table;

    macro getWidth()
        return m_table.getSumLen() + 1;
    end;

    macro printHead()
        [┌─────┬────────────────────────────┬────────────┬───────┬──────────┬──────────────────────┬───────────┬─────────────────────────────────┬───────────────┬─────────────┬────────┐];
        [│Номер│Наименование  кредитной     │  Регистра- │Код    │Номер     │Номер отдельного      │Остаток на │      Обороты по счетам за       │Остаток на     │Дата         │Процент-│];
        [│ п/п │организации, привлекшей     │  ционный   │страны │балансово-│лицевого счета        │начало     │      отчетный месяц             │конец          │исполнения   │ная     │];
        [│     │(разместившей) денежные     │  номер     │нахож- │го счета, │                      │месяца     │                                 │месяца         │обязатель-   │ставка  │];
        [│     │средства                    │  (код      │дения  │на котором│                      │           │                                 │               │ства         │        │];
        [│     │                            │  СВИФТ)    │кредит-│отражены  │                      │           │                                 │               │             │        │];
        [│     │                            │            │ной    │привлечен-│                      │           │                                 │               │             │        │];
        [│     │                            │            │органи-│ные       │                      │           │                                 │               │             │        │];
        [│     │                            │            │зации  │(размещен-│                      │           │                                 │               │             │        │];
        [│     │                            │            │       │ные)      │                      │           │                                 │               │             │        │];
        [│     │                            │            │       │средства  │                      │           ├────────────────┬────────────────┤               │             │        │];
        [│     │                            │            │       │          │                      │           │    Дебетовый   │   Кредитовый   │               │             │        │];
        [├─────┼────────────────────────────┼────────────┼───────┼──────────┼──────────────────────┼───────────┼────────────────┼────────────────┼───────────────┼─────────────┼────────┤];
        [│  1  │              2             │      3     │   4   │    5     │          6           │     7     │        8       │        9       │       10      │      11     │   12   │];
        [├─────┴────────────────────────────┴────────────┴───────┴──────────┴──────────────────────┴───────────┴────────────────┴────────────────┴───────────────┴─────────────┴────────┤];
        [│                                         I.  СВЕДЕНИЯ О ПРЕДОСТАВЛЕННЫХ МЕЖБАНКОВСКИХ КРЕДИТАХ (РАЗМЕЩЕННЫХ ДЕПОЗИТАХ)                                                        │];
        [├─────┬────────────────────────────┬────────────┬───────┬──────────┬──────────────────────┬───────────┬────────────────┬────────────────┬───────────────┬─────────────┬────────┤];
    end;

    macro printPartHead()
        [├─────┴────────────────────────────┴────────────┴───────┴──────────┴──────────────────────┴───────────┴────────────────┴────────────────┴───────────────┴─────────────┴────────┤];
        [│                                           II.  СВЕДЕНИЯ О ПОЛУЧЕННЫХ МЕЖБАНКОВСКИХ КРЕДИТАХ (ПРИВЛЕЧЕННЫХ ДЕПОЗИТАХ)                                                         │];
        [├─────┬────────────────────────────┬────────────┬───────┬──────────┬──────────────────────┬───────────┬────────────────┬────────────────┬───────────────┬─────────────┬────────┤];
    end;

    macro printBottom()
        m_table.printBottom();
    end;

    macro print(dataSource)
        dataSource.setFilter(TFilter());
        dataSource.setSortOrder(TSorter());
        dataSource.moveFirst();

        var i = 0;
        var structValue;
        var stringNumber;

        while (not dataSource.isDone())
            if (i > 0)
                m_table.printString();
            end;
            i = i + 1;
            structValue = dataSource.currentItem();
            stringNumber = ternary(((rcbApplication().currentReport().context.period.EndDate < RCB_I2121_DATE) or
                                    (int(structValue.fieldValue("ПризнакРЕПО").exact) == 0)),
                                   string(i), string(i + "*"));
            m_table.printStringTransferByWord( stringNumber,
                 structValue.fieldValue("НаимКО").currentAsString,
                 structValue.fieldValue("РегНом").currentAsString,
                 structValue.fieldValue("КодСтр").currentAsString,
                 structValue.fieldValue("НомБС").currentAsString,
                 structValue.fieldValue("ОтчНомЛС").currentAsString,
                 structValue.fieldValue("ОстВход").currentAsString,
                 structValue.fieldValue("ОбДебет").currentAsString,
                 structValue.fieldValue("ОбКредит").currentAsString,
                 structValue.fieldValue("ОстИсход").currentAsString,
                 structValue.fieldValue("ДатаИспОб").currentAsString,
                 string((structValue.fieldValue("ПрСтавка").current):0:2) );

            dataSource.next();
        end;
    end;

    private macro constructorTTableView()
        m_table = CTableReport();

        var columnWidth = arrCreate(3, 26, 10, 5, 8, 20, 9, 14, 14, 13, 11, 6);
        var columnAlign = arrCreate(AL_CENTER, AL_LEFT, AL_CENTER, AL_CENTER, AL_CENTER, AL_CENTER,
                                    AL_RIGHT, AL_RIGHT, AL_RIGHT, AL_RIGHT, AL_RIGHT, AL_RIGHT);
        var i = 0;
        while (i < columnWidth.size)
            m_table.AddColumn( "", columnWidth[i], columnAlign[i] );
            i = i + 1;
        end;
    end;

    constructorTTableView();
end;

macro isFirstRecordLess(structValue, structValueManualInput)
    var flag = false;
    var parameters = TParameters();

    if (parameters.isSortBalance())
        if (structValue.fieldValue("НомБС").currentAsString == structValueManualInput.fieldValue("НомБС_ввод").currentAsString)
            if (structValue.fieldValue("КодКО").currentAsString > structValueManualInput.fieldValue("КодКО").currentAsString)
                flag = false;
            else
                flag = true;
            end;
        elif (structValue.fieldValue("НомБС").currentAsString > structValueManualInput.fieldValue("НомБС_ввод").currentAsString)
            flag = false;
        else
            flag = true;
        end;
    elif (parameters.isSortClient())
        if (structValue.fieldValue("НаимКО").currentAsString == structValueManualInput.fieldValue("НаимКО").currentAsString)
            if (structValue.fieldValue("НомЛС").currentAsString > structValueManualInput.fieldValue("НомЛС_ввод").currentAsString)
                flag = false;
            else
                flag = true;
            end;
        elif (structValue.fieldValue("НаимКО").currentAsString > structValueManualInput.fieldValue("НаимКО").currentAsString)
            flag = false;
        else
            flag = true;
        end;
    else
        if (structValue.fieldValue("КодКО").currentAsString == structValueManualInput.fieldValue("КодКО").currentAsString)
            if (structValue.fieldValue("НомЛС").currentAsString > structValueManualInput.fieldValue("НомЛС_ввод").currentAsString)
                flag = false;
            else
                flag = true;
            end;
        elif (structValue.fieldValue("КодКО").currentAsString > structValueManualInput.fieldValue("КодКО").currentAsString)
            flag = false;
        else
            flag = true;
        end;
    end;

    return flag;
end;

private class (TTableView_I2121) TTableView_I2332()
    initTTableView_I2121;

    macro printHead()
        [┌──────┬────────────────────────────┬────────────┬───────┬──────────┬──────────────────────┬───────────┬─────────────────────────────────┬───────────────┬─────────────┬────────┐];
        [│Номер │Наименование  кредитной     │  Регистра- │Код    │Номер     │Номер отдельного      │Остаток на │      Обороты по счетам за       │Остаток на     │Дата         │Процент-│];
        [│строки│организации, привлекшей     │  ционный   │страны │балансово-│лицевого счета        │начало     │      отчетный месяц             │конец          │исполнения   │ная     │];
        [│      │(разместившей) денежные     │  номер     │нахож- │го счета, │                      │месяца     │                                 │месяца         │обязатель-   │ставка  │];
        [│      │средства                    │  (код      │дения  │на котором│                      │           │                                 │               │ства         │        │];
        [│      │                            │  СВИФТ)    │кредит-│отражены  │                      │           │                                 │               │             │        │];
        [│      │                            │            │ной    │привлечен-│                      │           │                                 │               │             │        │];
        [│      │                            │            │органи-│ные       │                      │           │                                 │               │             │        │];
        [│      │                            │            │зации  │(размещен-│                      │           │                                 │               │             │        │];
        [│      │                            │            │       │ные)      │                      │           │                                 │               │             │        │];
        [│      │                            │            │       │средства  │                      │           ├────────────────┬────────────────┤               │             │        │];
        [│      │                            │            │       │          │                      │           │    Дебетовый   │   Кредитовый   │               │             │        │];
        [├──────┼────────────────────────────┼────────────┼───────┼──────────┼──────────────────────┼───────────┼────────────────┼────────────────┼───────────────┼─────────────┼────────┤];
        [│   1  │              2             │      3     │   4   │    5     │          6           │     7     │        8       │        9       │       10      │      11     │   12   │];
        [├──────┴────────────────────────────┴────────────┴───────┴──────────┴──────────────────────┴───────────┴────────────────┴────────────────┴───────────────┴─────────────┴────────┤];
        [│                                          I.  СВЕДЕНИЯ О ПРЕДОСТАВЛЕННЫХ МЕЖБАНКОВСКИХ КРЕДИТАХ (РАЗМЕЩЕННЫХ ДЕПОЗИТАХ)                                                        │];
        [├──────┬────────────────────────────┬────────────┬───────┬──────────┬──────────────────────┬───────────┬────────────────┬────────────────┬───────────────┬─────────────┬────────┤];
    end;

    macro printPartHead()
        [├──────┴────────────────────────────┴────────────┴───────┴──────────┴──────────────────────┴───────────┴────────────────┴────────────────┴───────────────┴─────────────┴────────┤];
        [│                                            II.  СВЕДЕНИЯ О ПОЛУЧЕННЫХ МЕЖБАНКОВСКИХ КРЕДИТАХ (ПРИВЛЕЧЕННЫХ ДЕПОЗИТАХ)                                                         │];
        [├──────┬────────────────────────────┬────────────┬───────┬──────────┬──────────────────────┬───────────┬────────────────┬────────────────┬───────────────┬─────────────┬────────┤];
    end;

    macro print(dataSource, dataSourceManualInput)
        dataSource.setFilter(TFilter());
        dataSource.setSortOrder(TSorter());
        dataSource.moveFirst();

        dataSourceManualInput.setFilter(TFilterManualInput());
        dataSourceManualInput.setSortOrder(TSorterManualInput());
        dataSourceManualInput.moveFirst();

        var i = 0;
        var structValue;
        var stringNumber;
        var stringRate;
        var client:string;
        var structValueManualInput;
        var i2 = 0;

        while (not dataSource.isDone())

            structValue = dataSource.currentItem();
            structValueManualInput = dataSourceManualInput.currentItem();

            while ((not dataSourceManualInput.isDone()) and (not isFirstRecordLess(structValue, structValueManualInput)))
                i = i + 1;
                if (i > 0)
                    m_table.printString();
                end;

                i2 = i;

                if((structValueManualInput.fieldValue("ххх_ввод").currentAsString == "***") AND (structValueManualInput.fieldValue("НомЛС_ввод").currentAsString != ""))
                    i2 = string(i + "***");
                end;

                m_table.printStringTransferByWord( i2,
                                                   structValueManualInput.fieldValue("НаимКО").currentAsString,
                                                   structValueManualInput.fieldValue("РегНом").currentAsString,
                                                   structValueManualInput.fieldValue("КодСтр").currentAsString,
                                                   structValueManualInput.fieldValue("НомБС_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("НомЛС_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ОстВход_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ОбДебет_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ОбКредит_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ОстИсход_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ДатаИспОб_ввод").currentAsString,
                                                   string((structValueManualInput.fieldValue("ПрСтавка_ввод").current):0:2));
                dataSourceManualInput.next();
                structValueManualInput = dataSourceManualInput.currentItem();
            end;

            if (i > 0)
                m_table.printString();
            end;

            i = i + 1;
            if(int(structValue.fieldValue("ПризнакРЕПО").exact) == 1)
                stringNumber = string(i + "*");
            elif(int(structValue.fieldValue("ПризнакГД").exact) == 1)
                stringNumber = string(i + "**");
            else
                stringNumber = string(i);
            end;
            stringRate = ternary((int(structValue.fieldValue("ПризнакГД").exact) == 0),string((structValue.fieldValue("ПрСтавка").current):0:2),"");
            m_table.printStringTransferByWord( stringNumber,
                                               structValue.fieldValue("НаимКО").currentAsString,
                                               structValue.fieldValue("РегНом").currentAsString,
                                               structValue.fieldValue("КодСтр").currentAsString,
                                               structValue.fieldValue("НомБС").currentAsString,
                                               structValue.fieldValue("НомЛС").currentAsString,
                                               structValue.fieldValue("ОстВход").currentAsString,
                                               structValue.fieldValue("ОбДебет").currentAsString,
                                               structValue.fieldValue("ОбКредит").currentAsString,
                                               structValue.fieldValue("ОстИсход").currentAsString,
                                               structValue.fieldValue("ДатаИспОб").currentAsString,
                                               stringRate);

            dataSource.next();
        end;
        while (not dataSourceManualInput.isDone())
            if (i > 0)
                m_table.printString();
            end;
            i = i + 1;
            structValue = dataSourceManualInput.currentItem();

            i2 = i;

            if ((structValue.fieldValue("ххх_ввод").currentAsString == "***") AND (structValue.fieldValue("НомЛС_ввод").currentAsString != ""))
                i2 = string(i + "***");
            end;

            m_table.printStringTransferByWord( i2,
                                               structValue.fieldValue("НаимКО").currentAsString,
                                               structValue.fieldValue("РегНом").currentAsString,
                                               structValue.fieldValue("КодСтр").currentAsString,
                                               structValue.fieldValue("НомБС_ввод").currentAsString,
                                               structValue.fieldValue("НомЛС_ввод").currentAsString,
                                               structValue.fieldValue("ОстВход_ввод").currentAsString,
                                               structValue.fieldValue("ОбДебет_ввод").currentAsString,
                                               structValue.fieldValue("ОбКредит_ввод").currentAsString,
                                               structValue.fieldValue("ОстИсход_ввод").currentAsString,
                                               structValue.fieldValue("ДатаИспОб_ввод").currentAsString,
                                               string((structValue.fieldValue("ПрСтавка_ввод").current):0:2));
            dataSourceManualInput.next();
        end;
    end;

    private macro constructorTTableView()
        m_table = CTableReport();

        var columnWidth = arrCreate(4, 26, 10, 5, 8, 20, 9, 14, 14, 13, 11, 6);
        var columnAlign = arrCreate(AL_CENTER, AL_LEFT, AL_CENTER, AL_CENTER, AL_CENTER, AL_CENTER,
                                    AL_RIGHT, AL_RIGHT, AL_RIGHT, AL_RIGHT, AL_RIGHT, AL_RIGHT);
        var i = 0;
        while (i < columnWidth.size)
            m_table.AddColumn( "", columnWidth[i], columnAlign[i] );
            i = i + 1;
        end;
    end;
end;

private class (TTableView_I2332) TTableView_I3129()
    initTTableView_I2332;

    macro print(dataSource, dataSourceManualInput, partId)

        dataSource.setFilter(TFilter());
        dataSource.setSortOrder(TSorter());
        dataSource.moveFirst();

        dataSourceManualInput.setFilter(TFilterManualInput());
        dataSourceManualInput.setSortOrder(TSorterManualInput());
        dataSourceManualInput.moveFirst();

        var i = 0;
        var structValue;
        var stringNumber;
        var stringRate;
        var client:string;
        var structValueManualInput;
        var i2 = 0;
        while (not dataSource.isDone())

            structValue = dataSource.currentItem();
            structValueManualInput = dataSourceManualInput.currentItem;

            while ((not dataSourceManualInput.isDone()) and (not isFirstRecordLess(structValue, structValueManualInput)))
                i = i + 1;
                if (i > 0)
                    m_table.printString();
                end;

                i2 = i;

                if((structValueManualInput.fieldValue("ххх_ввод").currentAsString == "***") AND (structValueManualInput.fieldValue("НомЛС_ввод").currentAsString != ""))
                    i2 = string(i + "***");
                end;

                m_table.printStringTransferByWord( i2,
                                                   structValueManualInput.fieldValue("НаимКО").currentAsString,
                                                   structValueManualInput.fieldValue("РегНом").currentAsString,
                                                   structValueManualInput.fieldValue("КодСтр").currentAsString,
                                                   structValueManualInput.fieldValue("НомБС_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("НомЛС_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ОстВход_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ОбДебет_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ОбКредит_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ОстИсход_ввод").currentAsString,
                                                   structValueManualInput.fieldValue("ДатаИспОб_ввод").currentAsString,
                                                   string((structValueManualInput.fieldValue("ПрСтавка_ввод").current):0:2));
                dataSourceManualInput.next();
                structValueManualInput = dataSourceManualInput.currentItem();
            end;

            if (i > 0)
                m_table.printString();
            end;

            i = i + 1;
            if(int(structValue.fieldValue("ПризнакРЕПО").exact) == 1)
                stringNumber = string(i + "*");
            elif(int(structValue.fieldValue("ПризнакГД").exact) == 1)
                stringNumber = string(i + "**");
            elif(int(structValue.fieldValue("ПризнакТретьеЛицо").exact) == 1)
                stringNumber = string(i + "***");
            elif((rcbApplication().currentReport().attributeValue("Ф501_" + partId  + "ввод").fieldValue("ххх_ввод").currentAsString == "***") and
                 (structValue.fieldValue("НомЛС").currentAsString == rcbApplication().currentReport().attributeValue("Ф501_" + partId  + "ввод").fieldValue("НомЛС_ввод").currentAsString))
                stringNumber = string(i + "***");
            else
                stringNumber = string(i);
            end;
            stringRate = ternary((int(structValue.fieldValue("ПризнакГД").exact) == 0),string((structValue.fieldValue("ПрСтавка").current):0:2),"");
            m_table.printStringTransferByWord( stringNumber,
                                               structValue.fieldValue("НаимКО").currentAsString,
                                               structValue.fieldValue("РегНом").currentAsString,
                                               structValue.fieldValue("КодСтр").currentAsString,
                                               structValue.fieldValue("НомБС").currentAsString,
                                               structValue.fieldValue("НомЛС").currentAsString,
                                               structValue.fieldValue("ОстВход").currentAsString,
                                               structValue.fieldValue("ОбДебет").currentAsString,
                                               structValue.fieldValue("ОбКредит").currentAsString,
                                               structValue.fieldValue("ОстИсход").currentAsString,
                                               structValue.fieldValue("ДатаИспОб").currentAsString,
                                               stringRate);

            dataSource.next();
        end;

        while (not dataSourceManualInput.isDone())
            if (i > 0)
                m_table.printString();
            end;
            i = i + 1;

            i2 = i;

            structValue = dataSourceManualInput.currentItem();

            if((structValue.fieldValue("ххх_ввод").currentAsString == "***") AND (structValue.fieldValue("НомЛС_ввод").currentAsString != ""))
                i2 = string(i + "***");
            end;

            m_table.printStringTransferByWord( i2,
                                               structValue.fieldValue("НаимКО").currentAsString,
                                               structValue.fieldValue("РегНом").currentAsString,
                                               structValue.fieldValue("КодСтр").currentAsString,
                                               structValue.fieldValue("НомБС_ввод").currentAsString,
                                               structValue.fieldValue("НомЛС_ввод").currentAsString,
                                               structValue.fieldValue("ОстВход_ввод").currentAsString,
                                               structValue.fieldValue("ОбДебет_ввод").currentAsString,
                                               structValue.fieldValue("ОбКредит_ввод").currentAsString,
                                               structValue.fieldValue("ОстИсход_ввод").currentAsString,
                                               structValue.fieldValue("ДатаИспОб_ввод").currentAsString,
                                               string((structValue.fieldValue("ПрСтавка_ввод").current):0:2));
            dataSourceManualInput.next();
        end;
    end;
end;

private class (TTableView_I3129) TTableView_I4212()
    initTTableView_I3129();

    macro print(dataSource, dataSourceManualInput, partId)
        var structValue;
        var stringNumber;
        var stringRate;
        var client:string;
        var structValueManualInput;
        var i  = 0;
        var i2 = 0;

        dataSource.setFilter(TFilter());
        dataSource.setSortOrder(TSorter());
        dataSource.moveFirst();

        dataSourceManualInput.setFilter(TFilterManualInput());
        dataSourceManualInput.setSortOrder(TSorterManualInput());
        dataSourceManualInput.moveFirst();

        while (not dataSource.isDone())
            structValue            = dataSource.currentItem();
            structValueManualInput = dataSourceManualInput.currentItem();

            while (    (not dataSourceManualInput.isDone())
                   and (not isFirstRecordLess(structValue, structValueManualInput)))
                i = i + 1;
                if (i > 0)
                    m_table.printString();
                end;

                i2 = i;

                if (    (structValueManualInput.fieldValue("ххх_ввод").currentAsString == "***")
                    and (structValueManualInput.fieldValue("НомЛС_ввод").currentAsString != ""))
                    i2 = string(i + "***");
                end;

                m_table.printStringTransferByWord(i2,
                                                  structValueManualInput.fieldValue("НаимКО").currentAsString,
                                                  structValueManualInput.fieldValue("РегНом").currentAsString,
                                                  structValueManualInput.fieldValue("КодСтр").currentAsString,
                                                  structValueManualInput.fieldValue("НомБС_ввод").currentAsString,
                                                  structValueManualInput.fieldValue("НомЛС_ввод").currentAsString,
                                                  structValueManualInput.fieldValue("ОстВход_ввод").currentAsString,
                                                  structValueManualInput.fieldValue("ОбДебет_ввод").currentAsString,
                                                  structValueManualInput.fieldValue("ОбКредит_ввод").currentAsString,
                                                  structValueManualInput.fieldValue("ОстИсход_ввод").currentAsString,
                                                  structValueManualInput.fieldValue("ДатаИспОб_ввод").currentAsString,
                                                  string((structValueManualInput.fieldValue("ПрСтавка_ввод").current):0:2),
                                                  ternary(partId == 1, structValueManualInput.fieldValue("ЛицоПоОбрем_ввод").currentAsString, "X"),
                                                  ternary(partId == 1, structValueManualInput.fieldValue("ИдентификаторОбрем_ввод").currentAsString, "X"),
                                                  ternary(partId == 1, structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString, "X"),
                                                  ternary(partId == 1, ternary(structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString != "",
                                                                               structValueManualInput.fieldValue("ОстатокПоСчетуОбрем_ввод").currentAsString, ""), "X     "),
                                                  ternary(partId == 1, structValueManualInput.fieldValue("ДатаПогашения_ввод").currentAsString, "X"));
                dataSourceManualInput.next();
                structValueManualInput = dataSourceManualInput.currentItem();
            end;

            if (i > 0)
                m_table.printString();
            end;

            i = i + 1;

            if   (int(structValue.fieldValue("ПризнакРЕПО").exact) == 1)
                stringNumber = string(i + "*");
            elif (int(structValue.fieldValue("ПризнакГД").exact) == 1)
                stringNumber = string(i + "**");
            elif (int(structValue.fieldValue("ПризнакТретьеЛицо").exact) == 1)
                stringNumber = string(i + "***");
            elif (    (rcbApplication().currentReport().attributeValue("Ф501_" + partId  + "ввод").fieldValue("ххх_ввод").currentAsString == "***")
                  and (structValue.fieldValue("НомЛС").currentAsString == rcbApplication().currentReport().attributeValue("Ф501_" + partId  + "ввод").fieldValue("НомЛС_ввод").currentAsString))
                stringNumber = string(i + "***");
            else
                stringNumber = string(i);
            end;

            stringRate = ternary((int(structValue.fieldValue("ПризнакГД").exact) == 0),string((structValue.fieldValue("ПрСтавка").current):0:2),"");
            m_table.printStringTransferByWord(stringNumber,
                                              structValue.fieldValue("НаимКО").currentAsString,
                                              structValue.fieldValue("РегНом").currentAsString,
                                              structValue.fieldValue("КодСтр").currentAsString,
                                              structValue.fieldValue("НомБС").currentAsString,
                                              structValue.fieldValue("НомЛС").currentAsString,
                                              structValue.fieldValue("ОстВход").currentAsString,
                                              structValue.fieldValue("ОбДебет").currentAsString,
                                              structValue.fieldValue("ОбКредит").currentAsString,
                                              structValue.fieldValue("ОстИсход").currentAsString,
                                              structValue.fieldValue("ДатаИспОб").currentAsString,
                                              stringRate,
                                              ternary(partId == 1, structValue.fieldValue("ЛицоПоОбрем").currentAsString, "X"),
                                              ternary(partId == 1, structValue.fieldValue("ИдентификаторОбрем").currentAsString, "X"),
                                              ternary(partId == 1, structValue.fieldValue("ВидОбрем").currentAsString, "X"),
                                              ternary(partId == 1, ternary(structValue.fieldValue("ВидОбрем").currentAsString != "", structValue.fieldValue("ОстатокПоСчетуОбрем").currentAsString, ""), "X     "),
                                              ternary(partId == 1, structValue.fieldValue("ДатаПогашения").currentAsString, "X"));

            dataSource.next();
        end;

        while (not dataSourceManualInput.isDone())
            if (i > 0)
                m_table.printString();
            end;

            i = i + 1;
            i2 = i;
            structValue = dataSourceManualInput.currentItem();

            if (    (structValue.fieldValue("ххх_ввод").currentAsString == "***")
                and (structValue.fieldValue("НомЛС_ввод").currentAsString != ""))
                i2 = string(i + "***");
            end;

            m_table.printStringTransferByWord(i2,
                                              structValue.fieldValue("НаимКО").currentAsString,
                                              structValue.fieldValue("РегНом").currentAsString,
                                              structValue.fieldValue("КодСтр").currentAsString,
                                              structValue.fieldValue("НомБС_ввод").currentAsString,
                                              structValue.fieldValue("НомЛС_ввод").currentAsString,
                                              structValue.fieldValue("ОстВход_ввод").currentAsString,
                                              structValue.fieldValue("ОбДебет_ввод").currentAsString,
                                              structValue.fieldValue("ОбКредит_ввод").currentAsString,
                                              structValue.fieldValue("ОстИсход_ввод").currentAsString,
                                              structValue.fieldValue("ДатаИспОб_ввод").currentAsString,
                                              string((structValue.fieldValue("ПрСтавка_ввод").current):0:2),
                                              ternary(partId == 1, structValueManualInput.fieldValue("ЛицоПоОбрем_ввод").currentAsString, "X"),
                                              ternary(partId == 1, structValueManualInput.fieldValue("ИдентификаторОбрем_ввод").currentAsString, "X"),
                                              ternary(partId == 1, structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString, "X"),
                                              ternary(partId == 1, ternary(structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString != "",
                                                                           structValueManualInput.fieldValue("ОстатокПоСчетуОбрем_ввод").currentAsString, ""), "X     "),
                                              ternary(partId == 1, structValueManualInput.fieldValue("ДатаПогашения_ввод").currentAsString, "X"));
            dataSourceManualInput.next();
        end;
    end;

    macro printHead()
    [┌──────┬────────────────────────────┬─────────────┬───────┬──────────┬──────────────────────┬──────────────┬───────────────────────────┬─────────────┬─────────────┬────────┬───────────────────────────────────┬───────────────────────────────────────────┐];
    [│Номер │   Наименование кредитной   │Регистрацион-│  Код  │  Номер   │   Номер отдельного   │   Остаток    │    Обороты за отчетный    │   Остаток   │    Дата     │Процент-│       Наличие обременения         │        Обязательство, по которому         │];
    [│строки│        организации,        │  ный номер  │страны │балансово-│    лицевого счета    │      на      │      месяц, тыс. руб.     │     на      │ исполнения  │  ная   │                                   │         осуществлено обременение          │];
    [│      │ привлекшей (разместившей)  │ (код СВИФТ) │ места │го счета, │                      │начало месяца,│                           │конец месяца,│обязательства│ ставка │                                   │                                           │];
    [│      │     денежные средства      │             │нахож- │на котором│                      │  тыс. руб.   │                           │  тыс. руб.  │             │        ├─────────────────────┬─────────────┼────────────────┬─────────────┬────────────┤];
    [│      │                            │             │ дения │ отражены │                      │              │                           │             │             │        │ наименование лица,  │идентификатор│      вид       │ стоимость,  │    срок    │];
    [│      │                            │             │кредит-│привлечен-│                      │              │                           │             │             │        │  в пользу которого  │    лица     │                │  тыс. руб.  │ погашения  │];
    [│      │                            │             │  ной  │ные (раз- │                      │              │                           │             │             │        │    осуществлено     │             │                │             │            │];
    [│      │                            │             │органи-│мещенные) │                      │              ├─────────────┬─────────────┤             │             │        │     обременение     │             │                │             │            │];
    [│      │                            │             │ зации │ средства │                      │              │  Дебетовый  │ Кредитовый  │             │             │        │                     │             │                │             │            │];
    [├──────┼────────────────────────────┼─────────────┼───────┼──────────┼──────────────────────┼──────────────┼─────────────┼─────────────┼─────────────┼─────────────┼────────┼─────────────────────┼─────────────┼────────────────┼─────────────┼────────────┤];
    [│   1  │             2              │      3      │   4   │    5     │          6           │      7       │      8      │      9      │     10      │     11      │   12   │          13         │     14      │       15       │     16      │     17     │];
    [├──────┴────────────────────────────┴─────────────┴───────┴──────────┴──────────────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────┴─────────────────────┴─────────────┴────────────────┴─────────────┴────────────┤];
    [│                                                                                  Раздел I. Сведения о предоставленных межбанковских кредитах (размещенных депозитах)                                                                                      │];
    [├──────┬────────────────────────────┬─────────────┬───────┬──────────┬──────────────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────┬─────────────────────┬─────────────┬────────────────┬─────────────┬────────────┤];
    end;

    macro printPartHead()
    [├──────┴────────────────────────────┴─────────────┴───────┴──────────┴──────────────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────┴─────────────────────┴─────────────┴────────────────┴─────────────┴────────────┤];
    [│                                                                                    Раздел II. Сведения о полученных межбанковских кредитах (привлеченных депозитах)                                                                                       │];
    [├──────┬────────────────────────────┬─────────────┬───────┬──────────┬──────────────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────┬─────────────────────┬─────────────┬────────────────┬─────────────┬────────────┤];
    end;

    private macro constructorTTableView()
        m_table = CTableReport();

        var columnWidth = arrCreate(4, 26, 11, 5, 8, 20, 12, 11, 11, 11, 11, 6, 19, 11, 14, 11, 10);
        var columnAlign = arrCreate(AL_CENTER, AL_LEFT, AL_CENTER, AL_CENTER, AL_CENTER, AL_CENTER,
                                    AL_RIGHT, AL_RIGHT, AL_RIGHT, AL_RIGHT, AL_RIGHT, AL_RIGHT,
                                    AL_CENTER, AL_CENTER, AL_CENTER, AL_RIGHT, AL_CENTER);

        var i = 0;
        while (i < columnWidth.size)
            m_table.AddColumn("", columnWidth[i], columnAlign[i]);
            i = i + 1;
        end;
    end;
end;

private class (TTableView_I4212) TTableView_5456()
    initTTableView_I4212();

    macro print(dataSource, dataSourceManualInput, partId)
        var structValue;
        var stringNumber;
        var stringRate;
        var client:string;
        var structValueManualInput;
        var i  = 0;
        var i2 = 0;

        dataSource.setFilter(TFilter());
        dataSource.setSortOrder(TSorter());
        dataSource.moveFirst();

        if (partId != 3)
            dataSourceManualInput.setFilter(TFilterManualInput());
            dataSourceManualInput.setSortOrder(TSorterManualInput());
            dataSourceManualInput.moveFirst();
        end;

        while (not dataSource.isDone())
            structValue                = dataSource.currentItem();
            
            if (partId != 3)
                structValueManualInput = dataSourceManualInput.currentItem();

                while (    (not dataSourceManualInput.isDone())
                    and (not isFirstRecordLess(structValue, structValueManualInput)))
                    i = i + 1;
                    if (i > 0)
                        m_table.printString();
                    end;

                    i2 = i;

                    if (    (partId == 1)
                        and (structValueManualInput.fieldValue("ххх_ввод").currentAsString == "***")
                        and (structValueManualInput.fieldValue("НомЛС_ввод").currentAsString != ""))
                        i2 = string(i + "***");
                    end;

                    m_table.printStringTransferByWord(i2,
                                                    structValueManualInput.fieldValue("НаимКО").currentAsString,
                                                    structValueManualInput.fieldValue("РегНом").currentAsString,
                                                    structValueManualInput.fieldValue("КодСтр").currentAsString,
                                                    structValueManualInput.fieldValue("НомБС_ввод").currentAsString,
                                                    structValueManualInput.fieldValue("НомЛС_ввод").currentAsString,
                                                    structValueManualInput.fieldValue("ОстВход_ввод").currentAsString,
                                                    structValueManualInput.fieldValue("ОбДебет_ввод").currentAsString,
                                                    structValueManualInput.fieldValue("ОбКредит_ввод").currentAsString,
                                                    structValueManualInput.fieldValue("ОстИсход_ввод").currentAsString,
                                                    structValueManualInput.fieldValue("ДатаИспОб_ввод").currentAsString,
                                                    string((structValueManualInput.fieldValue("ПрСтавка_ввод").current):0:2),
                                                    ternary(partId == 1, structValueManualInput.fieldValue("ЛицоПоОбрем_ввод").currentAsString,        "X"),
                                                    ternary(partId == 1, structValueManualInput.fieldValue("ИдентификаторОбрем_ввод").currentAsString, "X"),
                                                    ternary(partId == 1, structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString,           "X"),
                                                    ternary(partId == 1, ternary(structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString != "",
                                                                                 structValueManualInput.fieldValue("ОстатокПоСчетуОбрем_ввод").currentAsString, ""), "X     "),
                                                    ternary(partId == 1, structValueManualInput.fieldValue("ДатаПогашения_ввод").currentAsString,      "X"));
                    dataSourceManualInput.next();
                    structValueManualInput = dataSourceManualInput.currentItem();
                end;
            end;

            if (i > 0)
                m_table.printString();
            end;

            i = i + 1;

            // "ПризнакСчетSecurities" не проверяем поскольку "ПризнакРЕПО" заполняется таким образом:
            // если счет является счетом Securities, то значение "ПризнакРЕПО" берем из представления repSecuritiesAccounts_vw
            // если же счет не является счетом Securities, то "ПризнакРЕПО" = 1, если на л/с установлена категория "Категории для отчетности / Форма 501" со значением "РЕПО"
            // иначе "ПризнакРЕПО" = 0
            if (partId != 3)
                if   (int(structValue.fieldValue("ПризнакРЕПО").exact) == 1)
                    stringNumber = string(i + "*");
                elif (int(structValue.fieldValue("ПризнакГД").exact) == 1)
                    stringNumber = string(i + "**");
                elif ((int(structValue.fieldValue("ПризнакТретьеЛицо").exact) == 1) and (partId == 1))
                    stringNumber = string(i + "***");
                else
                    stringNumber = string(i);
                end;
            else
                stringNumber = string(i + "*");
            end;

            stringRate = ternary((int(structValue.fieldValue("ПризнакГД").exact) == 0), string((structValue.fieldValue("ПрСтавка").current):0:2), "");
            m_table.printStringTransferByWord(stringNumber,
                                              structValue.fieldValue("НаимКО").currentAsString,
                                              structValue.fieldValue("РегНом").currentAsString,
                                              structValue.fieldValue("КодСтр").currentAsString,
                                              structValue.fieldValue("НомБС").currentAsString,
                                              structValue.fieldValue("НомЛС").currentAsString,
                                              structValue.fieldValue("ОстВход").currentAsString,
                                              ternary(partId != 3, structValue.fieldValue("ОбДебет").currentAsString,            "X"),
                                              ternary(partId != 3, structValue.fieldValue("ОбКредит").currentAsString,           "X"),
                                              structValue.fieldValue("ОстИсход").currentAsString,
                                              ternary(partId != 3, structValue.fieldValue("ДатаИспОб").currentAsString,          "X"),
                                              ternary(partId != 3, stringRate,                                                   "X"),
                                              ternary(partId == 1, structValue.fieldValue("ЛицоПоОбрем").currentAsString,        "X"),
                                              ternary(partId == 1, structValue.fieldValue("ИдентификаторОбрем").currentAsString, "X"),
                                              ternary(partId == 1, structValue.fieldValue("ВидОбрем").currentAsString,           "X"),
                                              ternary(partId == 1, ternary(structValue.fieldValue("ВидОбрем").currentAsString != "", structValue.fieldValue("ОстатокПоСчетуОбрем").currentAsString, ""), "X     "),
                                              ternary(partId == 1, structValue.fieldValue("ДатаПогашения").currentAsString,      "X"));

            dataSource.next();
        end;

        if (partId != 3)
            while (not dataSourceManualInput.isDone())
                if (i > 0)
                    m_table.printString();
                end;

                i = i + 1;
                i2 = i;
                structValue = dataSourceManualInput.currentItem();

                if (    (partId == 1)
                    and (structValue.fieldValue("ххх_ввод").currentAsString == "***")
                    and (structValue.fieldValue("НомЛС_ввод").currentAsString != ""))
                    i2 = string(i + "***");
                end;

                m_table.printStringTransferByWord(i2,
                                                structValue.fieldValue("НаимКО").currentAsString,
                                                structValue.fieldValue("РегНом").currentAsString,
                                                structValue.fieldValue("КодСтр").currentAsString,
                                                structValue.fieldValue("НомБС_ввод").currentAsString,
                                                structValue.fieldValue("НомЛС_ввод").currentAsString,
                                                structValue.fieldValue("ОстВход_ввод").currentAsString,
                                                structValue.fieldValue("ОбДебет_ввод").currentAsString,
                                                structValue.fieldValue("ОбКредит_ввод").currentAsString,
                                                structValue.fieldValue("ОстИсход_ввод").currentAsString,
                                                structValue.fieldValue("ДатаИспОб_ввод").currentAsString,
                                                string((structValue.fieldValue("ПрСтавка_ввод").current):0:2),
                                                ternary(partId == 1, structValueManualInput.fieldValue("ЛицоПоОбрем_ввод").currentAsString,        "X"),
                                                ternary(partId == 1, structValueManualInput.fieldValue("ИдентификаторОбрем_ввод").currentAsString, "X"),
                                                ternary(partId == 1, structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString,           "X"),
                                                ternary(partId == 1, ternary(structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString != "",
                                                                             structValueManualInput.fieldValue("ОстатокПоСчетуОбрем_ввод").currentAsString, ""), "X     "),
                                                ternary(partId == 1, structValueManualInput.fieldValue("ДатаПогашения_ввод").currentAsString,      "X"));
                dataSourceManualInput.next();
            end;
        end;
    end;

    macro printPart3Head()
    [├──────┴────────────────────────────┴─────────────┴───────┴──────────┴──────────────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────┴─────────────────────┴─────────────┴────────────────┴─────────────┴────────────┤];
    [│                                                                 Раздел III. Сведения о средствах, привлеченных в рамках сделок, заключаемых на бирже с участием центрального контрагента                                                                  │];
    [├──────┬────────────────────────────┬─────────────┬───────┬──────────┬──────────────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────┬─────────────────────┬─────────────┬────────────────┬─────────────┬────────────┤];
    end;
end;

/**
 *  Класс вывода отчета по форме 501
 *  @since 6.00.020.29
 *  @author Dmitry Shestakov
 */
private class (RcbReportView) TReportView_I2121()
    var m_tableView;

    macro getTableView() : Object
        return m_tableView;
    end;

    macro getWidth()
        return m_tableView.getWidth();
    end;

    objectFactoryInstance = RcbObjectFactoryBase();

    private macro constructorTReportView()
        initRcbReportView("СВЕДЕНИЯ О МЕЖБАНКОВСКИХ КРЕДИТАХ И ДЕПОЗИТАХ",
                          "0409501", RCB_PK_MONTH, DATE_OUT_PERIOD_FORMAT);

        m_tableView = TTableView_I2121();
    end;

    constructorTReportView();
end;

private class (TReportView_I2121) TReportView_I2332()
    initTReportView_I2121();

    private macro constructorTReportView()
        initRcbReportView("СВЕДЕНИЯ О МЕЖБАНКОВСКИХ КРЕДИТАХ И ДЕПОЗИТАХ",
                          "0409501", arrCreate(RCB_PK_MONTH, RCB_PK_DAY), DATE_OUT_PERIOD_FORMAT);

        m_tableView = TTableView_I2332();
    end;
end;

private class (TReportView_I2332) TReportView_I3129()
    initTReportView_I2332();
    m_tableView = TTableView_I3129();
end;

private class (TReportView_I3129) TReportView_I4212()
    private macro constructorTReportView();
        initTReportView_I3129();
        m_tableView = TTableView_I4212();
        excludeAttribute(AC_FORM_UNIT);
    end;

    constructorTReportView();
end;

private class (TReportView_I4212) TReportView_5456()
    private macro constructorTReportView();
        initRcbReportView("СВЕДЕНИЯ О МЕЖБАНКОВСКИХ КРЕДИТАХ И ДЕПОЗИТАХ",
                          "0409501", arrCreate(RCB_PK_HALFYEAR, RCB_PK_QUARTER, RCB_PK_MONTH, RCB_PK_DAY), DATE_OUT_PERIOD_FORMAT);
        m_tableView = TTableView_5456();
        excludeAttribute(AC_FORM_UNIT);
    end;

    constructorTReportView();
end;


private class (TSignatureZone_4212) TSignatureZoneExcel()
    initTSignatureZone_4212();

    macro getFirstPersonName()
        return m_firstPersonName;
    end;

    macro getSecondPersonName()
        return m_secondPersonName;
    end;

    macro getExecutorName()
        return m_executorName;
    end;

    macro getExecutorPhoneNumber()
        return m_executorPhoneNumber;
    end;

    macro getReportIssueDate()
        return m_reportIssueDate;
    end;
end;

private class (TNamesZone_4212) TNamesZoneExcel(formName : String, formOkudCode : String, formPeriodicity, periodFormat : Integer)
    initTNamesZone_4212(formName, formOkudCode, formPeriodicity, periodFormat);
    macro getFormName()
        return m_formName;
    end;
end;

/**
 *  Печатное представление Excel Формы 501
 *  @since 6.00.020.31
 *  @author MFB
 */
private class (CB_CReportTemplate)TF501ExcelPrintableView(formName : String, formOkudCode : String, formPeriodicity, periodFormat : Integer)
    private var m_lendingAgencyCodeZone = null;
    private var m_namesZone             = null;
    private var m_signatureZone         = null;
    private var m_report;
    private var m_start                 = true;
    private var arrayHeightsStrigs : RcbArray;

    // расчет кол-ва пунктов для высоты строки в Excel
    private macro calculateHeightStringExcel(str : String)
        var tmpArrayBankName    = StrCut(Trim(NVL(str, "")), " ");
        var tmpStr;
        var multiplierHeightStr = 1;
        var currentStrPos       = 0;
        const pointsToStep      = 12; // кол-во пунктов на одну строку
        const maxLettersInStr   = 15; // максимальное кол-во символов в одной ячейке, графы 2 "Наименование КО" в шаблонах Excel для формы 501

        var tmpEnum = tmpArrayBankName.createEnum();
        var it = 0;
        while (it < tmpArrayBankName.size())
            tmpEnum.next();
            tmpStr = tmpEnum.item();
            if ((strLen(tmpStr) > maxLettersInStr))
                multiplierHeightStr = multiplierHeightStr + int(Round((strLen(tmpStr) / maxLettersInStr), 0, 2));
                currentStrPos       = maxLettersInStr - mod(strLen(tmpStr), maxLettersInStr) + 1;
            else
                if   ((strLen(tmpStr) + currentStrPos) > maxLettersInStr)
                    multiplierHeightStr = multiplierHeightStr + 1;
                    currentStrPos       = strLen(tmpStr) + 1;
                elif ((strLen(tmpStr) + currentStrPos) == maxLettersInStr)
                    multiplierHeightStr = ternary(it != tmpArrayBankName.size() - 1, multiplierHeightStr + 1, multiplierHeightStr);
                    currentStrPos       = 0;
                else
                    currentStrPos       = (strLen(tmpStr) + currentStrPos) + 1;
                end;
            end;
            it = it + 1;
        end;

        return (pointsToStep * multiplierHeightStr);
    end;

    // Необходимо, что бы два разных столбца при конвертации из .csv в Excel не слипались. 
    // Подобное имеет место быть, если последним символом в строке являются кавычки.
    private macro fixStringForExcel(str)
        if (substr(str, strLen(str)) == "\"")
            return str + " ";
        else
            return str;
        end;
    end;

    private macro printLendingAgencyCodeZone()
        PrintFormatString(null,
                          "okatoCode",           m_lendingAgencyCodeZone.getOkato(),
                          "okpoCode",            m_lendingAgencyCodeZone.getOkpo(),
                          "regNumber",           m_lendingAgencyCodeZone.getRegistrationNumber()
                          );

    end;

    private macro printNamesZone()
        var periodicity = m_namesZone.getFormPeriodicity();
        PrintFormatString(null,
                          "reportName",          m_namesZone.getFormName(),
                          "periodKind",          periodicity, //ternary(rcbApplication().currentReport.context.period.kind == RCB_PK_MONTH, "Месячная", ""),
                          "reportPeriod",        m_namesZone.getPeriodName(),
                          "organisationName",    m_namesZone.getLendingAgencyName(),
                          "organisationAddress", m_namesZone.getLendingAgencyPostalAdress(),//,
                          "okudCode",            m_namesZone.getOkudString(0)
                         );
    end;

    private macro printSignatureZone()
        PrintFormatString(null,
                          "boss",          m_signatureZone.getFirstPersonName(),
                          "book",          m_signatureZone.getSecondPersonName(),
                          "executor",      m_signatureZone.getExecutorName(),
                          "number",        m_signatureZone.getExecutorPhoneNumber(),
                          "executionDate", string(m_signatureZone.getReportIssueDate() : f : m)
                          );
    end;

    macro PrintMode():INTEGER
       return DL_OUTREPORT_EXCEL;
    end;

    private macro PrintHead()
    end;

    private macro BeginReport( /* NumCopy:INTEGER */ )
        SetNumberPage("Страница ", numPage);
    end;

    private macro EndReport()
        SetXLSXFormat();

        arrayHeightsStrigs.moveFirst();
        while(arrayHeightsStrigs.moveNext())
            setRowHeight(arrayHeightsStrigs.getCurrentItem()[0], arrayHeightsStrigs.getCurrentItem()[1]);
        end;
    end;

    /**
     * Печать строки таблицы
     */
    private macro printPartTableLine(partPrefix, row, orgName, swift, countryCode,
                                     balance, account, inRest, debet, credit, outRest, date, rate,
                                     encumName, encumId, encumType, encumValue, encumTerm)
        PrintTableLine(partPrefix + "Row",         row,         null,
                       partPrefix + "OrgName",     orgName,     null,
                       partPrefix + "Swift",       swift,       null,
                       partPrefix + "CountryCode", countryCode, null,
                       partPrefix + "Balance",     balance,     null,
                       partPrefix + "Account",     account,     null,
                       partPrefix + "InRest",      inRest,      null,
                       partPrefix + "Debet",       debet,       null,
                       partPrefix + "Credit",      credit,      null,
                       partPrefix + "OutRest",     outRest,     null,
                       partPrefix + "Date",        date,        null,
                       partPrefix + "Rate",        rate,        null,
                       partPrefix + "EncumName",   encumName,   null,
                       partPrefix + "EncumId",     encumId,     null,
                       partPrefix + "EncumType",   encumType,   null,
                       partPrefix + "EncumValue",  encumValue,  null,
                       partPrefix + "EncumTerm",   encumTerm,   null);
    end;

    private macro printPart(dataSource, dataSourceManualInput, partId, stringPos : @Integer)
        // 27 - номер строки за шаблона для 501 формы, с которой начинается ввод данных (при этом в Excel эта строка 26. Нумерация строк в инструменте с нуля..?)
        defaultParm(stringPos, 27);

        SetActiveSheet("Отчет");
        var partPrefix = "p" + partId;

        RegisterTable(partPrefix + "Table", null /*header*/,
                      partPrefix + "Row",
                      partPrefix + "OrgName",
                      partPrefix + "Swift",
                      partPrefix + "CountryCode",
                      partPrefix + "Balance",
                      partPrefix + "Account",
                      partPrefix + "InRest",
                      partPrefix + "Debet",
                      partPrefix + "Credit",
                      partPrefix + "OutRest",
                      partPrefix + "Date",
                      partPrefix + "Rate",
                      partPrefix + "EncumName",
                      partPrefix + "EncumId",
                      partPrefix + "EncumType",
                      partPrefix + "EncumValue",
                      partPrefix + "EncumTerm");

        var structValue;
        var stringNumber;
        var stringRate;
        var client : string;
        var structValueManualInput;
        var i  = 0;
        var i2 = 0;
        var isEmpty = true;

        dataSource.setFilter(TFilter());
        dataSource.setSortOrder(TSorter());
        dataSource.moveFirst();

        dataSourceManualInput.setFilter(TFilterManualInput());
        dataSourceManualInput.setSortOrder(TSorterManualInput());
        dataSourceManualInput.moveFirst();

        while(not dataSource.isDone())
            isEmpty = false;
            structValue            = dataSource.currentItem();
            structValueManualInput = dataSourceManualInput.currentItem();

            while (    (not dataSourceManualInput.isDone())
                   and (not isFirstRecordLess(structValue, structValueManualInput)))
                i = i + 1;

                i2 = i;

                if (    (structValueManualInput.fieldValue("ххх_ввод").currentAsString == "***")
                    and (structValueManualInput.fieldValue("НомЛС_ввод").currentAsString != ""))
                    i2 = string(i + "***");
                end;

                printPartTableLine(partPrefix,
                                   i2,
                                   fixStringForExcel(structValueManualInput.fieldValue("НаимКО").currentAsString),
                                   structValueManualInput.fieldValue("РегНом").currentAsString,
                                   structValueManualInput.fieldValue("КодСтр").currentAsString,
                                   structValueManualInput.fieldValue("НомБС_ввод").currentAsString,
                                   structValueManualInput.fieldValue("НомЛС_ввод").currentAsString,
                                   structValueManualInput.fieldValue("ОстВход_ввод").currentAsString,
                                   structValueManualInput.fieldValue("ОбДебет_ввод").currentAsString,
                                   structValueManualInput.fieldValue("ОбКредит_ввод").currentAsString,
                                   structValueManualInput.fieldValue("ОстИсход_ввод").currentAsString,
                                   structValueManualInput.fieldValue("ДатаИспОб_ввод").currentAsString,
                                   string((structValueManualInput.fieldValue("ПрСтавка_ввод").current):0:2),
                                   ternary(partId == 1, structValueManualInput.fieldValue("ЛицоПоОбрем_ввод").currentAsString, "X"),
                                   ternary(partId == 1, structValueManualInput.fieldValue("ИдентификаторОбрем_ввод").currentAsString, "X"),
                                   ternary(partId == 1, structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString, "X"),
                                   ternary(partId == 1, ternary(structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString != "",
                                                                structValueManualInput.fieldValue("ОстатокПоСчетуОбрем_ввод").currentAsString, ""), "X     "),
                                   ternary(partId == 1, structValueManualInput.fieldValue("ДатаПогашения_ввод").currentAsString, "X"));

                arrayHeightsStrigs.push_back(RcbArray());
                arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][0] = stringPos;
                arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][1] = calculateHeightStringExcel(structValueManualInput.fieldValue("НаимКО").currentAsString);
                stringPos = stringPos + 1;

                dataSourceManualInput.moveNext();
                structValueManualInput = dataSourceManualInput.currentItem();
            end;

            i = i + 1;

            if   (int(structValue.fieldValue("ПризнакРЕПО").exact) == 1)
                stringNumber = string(i + "*");
            elif (int(structValue.fieldValue("ПризнакГД").exact) == 1)
                stringNumber = string(i + "**");
            elif (int(structValue.fieldValue("ПризнакТретьеЛицо").exact) == 1)
                stringNumber = string(i + "***");
            elif (    (rcbApplication().currentReport().attributeValue("Ф501_" + partId  + "ввод").fieldValue("ххх_ввод").currentAsString == "***")
                  and (structValue.fieldValue("НомЛС").currentAsString == rcbApplication().currentReport().attributeValue("Ф501_" + partId  + "ввод").fieldValue("НомЛС_ввод").currentAsString))
                stringNumber = string(i + "***");
            else
                stringNumber = string(i);
            end;

            stringRate = ternary((int(structValue.fieldValue("ПризнакГД").exact) == 0),string((structValue.fieldValue("ПрСтавка").current):0:2),"");

            printPartTableLine(partPrefix,
                               stringNumber,
                               fixStringForExcel(structValue.fieldValue("НаимКО").currentAsString),
                               structValue.fieldValue("РегНом").currentAsString,
                               structValue.fieldValue("КодСтр").currentAsString,
                               structValue.fieldValue("НомБС").currentAsString,
                               structValue.fieldValue("НомЛС").currentAsString,
                               structValue.fieldValue("ОстВход").currentAsString,
                               structValue.fieldValue("ОбДебет").currentAsString,
                               structValue.fieldValue("ОбКредит").currentAsString,
                               structValue.fieldValue("ОстИсход").currentAsString,
                               structValue.fieldValue("ДатаИспОб").currentAsString,
                               stringRate,
                               ternary(partId == 1, structValue.fieldValue("ЛицоПоОбрем").currentAsString, "X"),
                               ternary(partId == 1, structValue.fieldValue("ИдентификаторОбрем").currentAsString, "X"),
                               ternary(partId == 1, structValue.fieldValue("ВидОбрем").currentAsString, "X"),
                               ternary(partId == 1, ternary(structValue.fieldValue("ВидОбрем").currentAsString != "", structValue.fieldValue("ОстатокПоСчетуОбрем").currentAsString, ""), "X     "),
                               ternary(partId == 1, structValue.fieldValue("ДатаПогашения").currentAsString, "X"));

            arrayHeightsStrigs.push_back(RcbArray());
            arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][0] = stringPos;
            arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][1] = calculateHeightStringExcel(structValue.fieldValue("НаимКО").currentAsString);
            stringPos = stringPos + 1;

            dataSource.moveNext();
        end;

        while (not dataSourceManualInput.isDone())
            isEmpty = false;
            i = i + 1;
            i2 = i;
            structValue = dataSourceManualInput.currentItem();

            if (    (structValue.fieldValue("ххх_ввод").currentAsString == "***")
                and (structValue.fieldValue("НомЛС_ввод").currentAsString != ""))
                i2 = string(i + "***");
            end;

            printPartTableLine(partPrefix,
                               i2,
                               fixStringForExcel(structValue.fieldValue("НаимКО").currentAsString),
                               structValue.fieldValue("РегНом").currentAsString,
                               structValue.fieldValue("КодСтр").currentAsString,
                               structValue.fieldValue("НомБС_ввод").currentAsString,
                               structValue.fieldValue("НомЛС_ввод").currentAsString,
                               structValue.fieldValue("ОстВход_ввод").currentAsString,
                               structValue.fieldValue("ОбДебет_ввод").currentAsString,
                               structValue.fieldValue("ОбКредит_ввод").currentAsString,
                               structValue.fieldValue("ОстИсход_ввод").currentAsString,
                               structValue.fieldValue("ДатаИспОб_ввод").currentAsString,
                               string((structValue.fieldValue("ПрСтавка_ввод").current):0:2),
                               ternary(partId == 1, structValueManualInput.fieldValue("ЛицоПоОбрем_ввод").currentAsString, "X"),
                               ternary(partId == 1, structValueManualInput.fieldValue("ИдентификаторОбрем_ввод").currentAsString, "X"),
                               ternary(partId == 1, structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString, "X"),
                               ternary(partId == 1, ternary(structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString != "",
                                                            structValueManualInput.fieldValue("ОстатокПоСчетуОбрем_ввод").currentAsString, ""), "X     "),
                               ternary(partId == 1, structValueManualInput.fieldValue("ДатаПогашения_ввод").currentAsString, "X"));

            arrayHeightsStrigs.push_back(RcbArray());
            arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][0] = stringPos;
            arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][1] = calculateHeightStringExcel(structValue.fieldValue("НаимКО").currentAsString);
            stringPos = stringPos + 1;

            dataSourceManualInput.next();
        end;

        EndTable();
        return (not isEmpty);
    end;

    /**
     * Печать Раздела 1
     */
    private macro printPart1(attribute, userInputAttribute, stringPos : @Integer)
        var dataExists = printPart(attribute.createValueIterator(), userInputAttribute.createValueIterator(), 1, @stringPos);
    end;

    /**
     * Печать Раздела 2
     */
    private macro printPart2(attribute, userInputAttribute, stringPos : @Integer)
        var dataExists = printPart(attribute.createValueIterator(), userInputAttribute.createValueIterator(), 2, @stringPos);
    end;

    private macro create()
        printLendingAgencyCodeZone();
        printNamesZone();
        var stringPos = 27;
        printPart1(m_report.attributeValue("Ф501_1"), m_report.attributeValue("Ф501_1ввод"), @stringPos);
        stringPos = stringPos + 2;
        printPart2(m_report.attributeValue("Ф501_2"), m_report.attributeValue("Ф501_2ввод"), @stringPos);
        printSignatureZone();
    end;

    macro print()
        Run();
        /**
         * Список файлов печати (*.xls)
         */
        var reportFileNameList = GetFullReportFileNames();
        var i: Integer = 0;
        while (i < reportFileNameList.size)
            RepTxtFilesQueue().add(reportFileNameList[i]);
            i = i + 1;
        end;
    end;

    private macro initializeVariables(formName : String, formOkudCode : String, formPeriodicity, periodFormat : Integer)
        m_lendingAgencyCodeZone  = TLendingAgencyCodeZone();
        m_namesZone              = TNamesZoneExcel(formName, formOkudCode, formPeriodicity, periodFormat);
        m_signatureZone          = TSignatureZoneExcel();
        m_report                 = rcbApplication().currentReport();
    end;

    private macro constructorTF501ExcelPrintableView(formName : String, formOkudCode : String, formPeriodicity, periodFormat : Integer)
        initCB_CReportTemplate( null, "f501Template.xlsx", null, rcbWebCommon_isWebSystem());
        initializeVariables(formName, formOkudCode, formPeriodicity, periodFormat);
        // восстановим оригинальную функцию
        ReplaceMacro("isStandalone");
    end;

    constructorTF501ExcelPrintableView(formName, formOkudCode, formPeriodicity, periodFormat);
end;

private class (TF501ExcelPrintableView)TF501ExcelPrintableView_I5456(formName : String, formOkudCode : String, formPeriodicity, periodFormat : Integer)

    private macro printPart(dataSource, dataSourceManualInput, partId, stringPos : @Integer)
        // 29 - номер строки за шаблона для 501 формы, с которой начинается ввод данных (при этом в Excel эта строка 26. Нумерация строк в инструменте с нуля..?)
        defaultParm(stringPos, 29);

        SetActiveSheet("Отчет");
        var partPrefix = "p" + partId;

        RegisterTable(partPrefix + "Table", null /*header*/,
                      partPrefix + "Row",
                      partPrefix + "OrgName",
                      partPrefix + "Swift",
                      partPrefix + "CountryCode",
                      partPrefix + "Balance",
                      partPrefix + "Account",
                      partPrefix + "InRest",
                      partPrefix + "Debet",
                      partPrefix + "Credit",
                      partPrefix + "OutRest",
                      partPrefix + "Date",
                      partPrefix + "Rate",
                      partPrefix + "EncumName",
                      partPrefix + "EncumId",
                      partPrefix + "EncumType",
                      partPrefix + "EncumValue",
                      partPrefix + "EncumTerm");

        var structValue;
        var stringNumber;
        var stringRate;
        var client:string;
        var structValueManualInput;
        var i  = 0;
        var i2 = 0;
        var isEmpty = true;

        dataSource.setFilter(TFilter());
        dataSource.setSortOrder(TSorter());
        dataSource.moveFirst();

        if (partId != 3)
            dataSourceManualInput.setFilter(TFilterManualInput());
            dataSourceManualInput.setSortOrder(TSorterManualInput());
            dataSourceManualInput.moveFirst();
        end;

        while(not dataSource.isDone())
            isEmpty     = false;
            structValue = dataSource.currentItem();

            if (partId != 3)
                structValueManualInput = dataSourceManualInput.currentItem();

                while (    (not dataSourceManualInput.isDone())
                       and (not isFirstRecordLess(structValue, structValueManualInput)))
                    i = i + 1;

                    i2 = i;

                    if (    (partId == 1)
                        and (structValueManualInput.fieldValue("ххх_ввод").currentAsString == "***")
                        and (structValueManualInput.fieldValue("НомЛС_ввод").currentAsString != ""))
                        i2 = string(i + "***");
                    end;

                    printPartTableLine(partPrefix,
                                       i2,
                                       fixStringForExcel(structValueManualInput.fieldValue("НаимКО").currentAsString),
                                       structValueManualInput.fieldValue("РегНом").currentAsString,
                                       structValueManualInput.fieldValue("КодСтр").currentAsString,
                                       structValueManualInput.fieldValue("НомБС_ввод").currentAsString,
                                       structValueManualInput.fieldValue("НомЛС_ввод").currentAsString,
                                       structValueManualInput.fieldValue("ОстВход_ввод").currentAsString,
                                       structValueManualInput.fieldValue("ОбДебет_ввод").currentAsString,
                                       structValueManualInput.fieldValue("ОбКредит_ввод").currentAsString,
                                       structValueManualInput.fieldValue("ОстИсход_ввод").currentAsString,
                                       structValueManualInput.fieldValue("ДатаИспОб_ввод").currentAsString,
                                       string((structValueManualInput.fieldValue("ПрСтавка_ввод").current):0:2),
                                       ternary(partId == 1, structValueManualInput.fieldValue("ЛицоПоОбрем_ввод").currentAsString,        "X"),
                                       ternary(partId == 1, structValueManualInput.fieldValue("ИдентификаторОбрем_ввод").currentAsString, "X"),
                                       ternary(partId == 1, structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString,           "X"),
                                       ternary(partId == 1, ternary(structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString != "",
                                                                    structValueManualInput.fieldValue("ОстатокПоСчетуОбрем_ввод").currentAsString, ""), "X     "),
                                       ternary(partId == 1, structValueManualInput.fieldValue("ДатаПогашения_ввод").currentAsString,      "X"));

                    arrayHeightsStrigs.push_back(RcbArray());
                    arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][0] = stringPos;
                    arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][1] = calculateHeightStringExcel(structValueManualInput.fieldValue("НаимКО").currentAsString);
                    stringPos = stringPos + 1;

                    dataSourceManualInput.moveNext();
                    structValueManualInput = dataSourceManualInput.currentItem();
                end;
            end;

            i = i + 1;

            // "ПризнакСчетSecurities" не проверяем поскольку "ПризнакРЕПО" заполняется таким образом:
            // если счет является счетом Securities, то значение "ПризнакРЕПО" берем из представления repSecuritiesAccounts_vw
            // если же счет не является счетом Securities, то "ПризнакРЕПО" = 1, если на л/с установлена категория "Категории для отчетности / Форма 501" со значением "РЕПО"
            // иначе "ПризнакРЕПО" = 0
            if (partId != 3)
                if   (int(structValue.fieldValue("ПризнакРЕПО").exact) == 1)
                    stringNumber = string(i + "*");
                elif (int(structValue.fieldValue("ПризнакГД").exact) == 1)
                    stringNumber = string(i + "**");
                elif ((int(structValue.fieldValue("ПризнакТретьеЛицо").exact) == 1) and (partId == 1))
                    stringNumber = string(i + "***");
                else
                    stringNumber = string(i);
                end;
            else
                stringNumber = string(i + "*");
            end;

            stringRate = ternary((int(structValue.fieldValue("ПризнакГД").exact) == 0),string((structValue.fieldValue("ПрСтавка").current):0:2),"");

            printPartTableLine(partPrefix,
                               stringNumber,
                               fixStringForExcel(structValue.fieldValue("НаимКО").currentAsString),
                               structValue.fieldValue("РегНом").currentAsString,
                               structValue.fieldValue("КодСтр").currentAsString,
                               structValue.fieldValue("НомБС").currentAsString,
                               structValue.fieldValue("НомЛС").currentAsString,
                               structValue.fieldValue("ОстВход").currentAsString,
                               ternary(partId != 3, structValue.fieldValue("ОбДебет").currentAsString,            "X"),
                               ternary(partId != 3, structValue.fieldValue("ОбКредит").currentAsString,           "X"),
                               structValue.fieldValue("ОстИсход").currentAsString,
                               ternary(partId != 3, structValue.fieldValue("ДатаИспОб").currentAsString,          "X"),
                               ternary(partId != 3, stringRate,                                                   "X"),
                               ternary(partId == 1, structValue.fieldValue("ЛицоПоОбрем").currentAsString,        "X"),
                               ternary(partId == 1, structValue.fieldValue("ИдентификаторОбрем").currentAsString, "X"),
                               ternary(partId == 1, structValue.fieldValue("ВидОбрем").currentAsString,           "X"),
                               ternary(partId == 1, ternary(structValue.fieldValue("ВидОбрем").currentAsString != "", 
                                                            structValue.fieldValue("ОстатокПоСчетуОбрем").currentAsString, ""), "X     "),
                               ternary(partId == 1, structValue.fieldValue("ДатаПогашения").currentAsString,      "X"));

            arrayHeightsStrigs.push_back(RcbArray());
            arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][0] = stringPos;
            arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][1] = calculateHeightStringExcel(structValue.fieldValue("НаимКО").currentAsString);
            stringPos = stringPos + 1;
            
            dataSource.moveNext();
        end;

        if(partId != 3)
            while (not dataSourceManualInput.isDone())
                isEmpty = false;
                i = i + 1;
                i2 = i;
                structValue = dataSourceManualInput.currentItem();

                if (    (partId == 1)
                    and (structValue.fieldValue("ххх_ввод").currentAsString == "***")
                    and (structValue.fieldValue("НомЛС_ввод").currentAsString != ""))
                    i2 = string(i + "***");
                end;

                printPartTableLine(partPrefix,
                                   i2,
                                   fixStringForExcel(structValue.fieldValue("НаимКО").currentAsString),
                                   structValue.fieldValue("РегНом").currentAsString,
                                   structValue.fieldValue("КодСтр").currentAsString,
                                   structValue.fieldValue("НомБС_ввод").currentAsString,
                                   structValue.fieldValue("НомЛС_ввод").currentAsString,
                                   structValue.fieldValue("ОстВход_ввод").currentAsString,
                                   structValue.fieldValue("ОбДебет_ввод").currentAsString,
                                   structValue.fieldValue("ОбКредит_ввод").currentAsString,
                                   structValue.fieldValue("ОстИсход_ввод").currentAsString,
                                   structValue.fieldValue("ДатаИспОб_ввод").currentAsString,
                                   string((structValue.fieldValue("ПрСтавка_ввод").current):0:2),
                                   ternary(partId == 1, structValueManualInput.fieldValue("ЛицоПоОбрем_ввод").currentAsString,        "X"),
                                   ternary(partId == 1, structValueManualInput.fieldValue("ИдентификаторОбрем_ввод").currentAsString, "X"),
                                   ternary(partId == 1, structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString,           "X"),
                                   ternary(partId == 1, ternary(structValueManualInput.fieldValue("ВидОбрем_ввод").currentAsString != "",
                                                                structValueManualInput.fieldValue("ОстатокПоСчетуОбрем_ввод").currentAsString, ""), "X     "),
                                   ternary(partId == 1, structValueManualInput.fieldValue("ДатаПогашения_ввод").currentAsString,      "X"));

                arrayHeightsStrigs.push_back(RcbArray());
                arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][0] = stringPos;
                arrayHeightsStrigs[arrayHeightsStrigs.getCount() - 1][1] = calculateHeightStringExcel(structValue.fieldValue("НаимКО").currentAsString);
                stringPos = stringPos + 1;

                dataSourceManualInput.next();
            end;
        end;

        EndTable();
        return (not isEmpty);
    end;

    /**
     * Печать Раздела 3
     */
    private macro printPart3(attribute, userInputAttribute, stringPos : @Integer)
        var dataExists = printPart(attribute.createValueIterator(), NULL, 3, @stringPos);
    end;

    private macro create()
        // 29 - номер строки за шаблона для 501 формы, с которой начинается ввод данных (при этом в Excel эта строка 26. Нумерация строк в инструменте с нуля..?)
        var stringPos = 29;

        printLendingAgencyCodeZone();
        printNamesZone();    
        printPart1(m_report.attributeValue("Ф501_1"), m_report.attributeValue("Ф501_1ввод"), @stringPos);
        stringPos = stringPos + 1;
        printPart2(m_report.attributeValue("Ф501_2"), m_report.attributeValue("Ф501_2ввод"), @stringPos);
        stringPos = stringPos + 1;
        printPart3(m_report.attributeValue("Ф501_3"), NULL, @stringPos);
        printSignatureZone();
    end;

    private macro constructorTF501ExcelPrintableView_I5456(formName : String, formOkudCode : String, formPeriodicity, periodFormat : Integer)
        initCB_CReportTemplate( null, "f501Template_5456.xlsx", null, rcbWebCommon_isWebSystem());
        initializeVariables(formName, formOkudCode, formPeriodicity, periodFormat);
        // восстановим оригинальную функцию
        ReplaceMacro("isStandalone");
    end;

    constructorTF501ExcelPrintableView_I5456(formName, formOkudCode, formPeriodicity, periodFormat);
end;

class (RcbReportView) TF501ExcelView()
    private var m_excelPrintView;

    macro print()
        m_excelPrintView.print();
    end;

    private macro constructorTF501ExcelView()
        initRcbReportView("СВЕДЕНИЯ О МЕЖБАНКОВСКИХ КРЕДИТАХ И ДЕПОЗИТАХ",
                          "0409501", arrCreate(RCB_PK_MONTH, RCB_PK_DAY), DATE_OUT_PERIOD_FORMAT);
        m_excelPrintView = TF501ExcelPrintableView("СВЕДЕНИЯ О МЕЖБАНКОВСКИХ КРЕДИТАХ И ДЕПОЗИТАХ",
                                                   "0409501", arrCreate(RCB_PK_MONTH, RCB_PK_DAY), DATE_OUT_PERIOD_FORMAT);
    end;

    constructorTF501ExcelView();
end;

class (TF501ExcelView) TF501ExcelView_I5456()
    private macro constructorTF501ExcelView_I5456()
        initRcbReportView("СВЕДЕНИЯ О МЕЖБАНКОВСКИХ КРЕДИТАХ И ДЕПОЗИТАХ",
                          "0409501", arrCreate(RCB_PK_MONTH, RCB_PK_DAY), DATE_OUT_PERIOD_FORMAT);
        m_excelPrintView = TF501ExcelPrintableView_I5456("СВЕДЕНИЯ О МЕЖБАНКОВСКИХ КРЕДИТАХ И ДЕПОЗИТАХ",
                                                   "0409501", arrCreate(RCB_PK_HALFYEAR, RCB_PK_QUARTER, RCB_PK_MONTH, RCB_PK_DAY), DATE_OUT_PERIOD_FORMAT);
    end;

    constructorTF501ExcelView_I5456();
end;


/**
 *  Класс управления выводом отчета по форме 501
 *  @since 6.00.020.29
 *  @author Dmitry Shestakov
 */
private class TPrintController_I2121()
    private var m_view;
    private var m_dataSource1;
    private var m_dataSource2;

    private macro printReportData()
        var table = m_view.getTableView();

        table.printHead();
        table.print(m_dataSource1);
        table.printPartHead();
        table.print(m_dataSource2);
        table.printbottom();
    end;

    private macro isEmpty()
        return ((m_dataSource1.count + m_dataSource2.count) == 0);
    end;

    macro print()
        m_view.setReportWidth(ternary(isEmpty(), 80, m_view.getWidth()));
        m_view.printLendingAgencyCodeZone();
        m_view.printNamesZone();

        if (isEmpty())
            m_view.printNullDataZone();
        else
            printReportData();
        end;

        m_view.printSignatureZone();
    end;

    private macro constructorTPrintController()
        m_view        = TReportView_I2121();
        m_dataSource1 = rcbApplication().currentReport().attributeValue("Ф501_1").createValueIterator();
        m_dataSource2 = rcbApplication().currentReport().attributeValue("Ф501_2").createValueIterator();
    end;

    constructorTPrintController();
end;

private class (TPrintController_I2121) TPrintController_I2332()
    initTPrintController_I2121;
    var m_dataSourceManualInput1;
    var m_dataSourceManualInput2;

    macro print()
        m_view.setReportWidth(ternary(isEmpty(), 80, m_view.getWidth()));
        m_view.changePrintZone(MC_LEADING_AGENCY_NAME_WHITHOUT_BRANCH);
        m_view.printLendingAgencyCodeZone();
        m_view.printNamesZone();
        if (isEmpty())
            m_view.printNullDataZone();
        else
            printReportData();
        end;
        m_view.printSignatureZone();
    end;

    private macro constructorTPrintController()
        m_view                   = TReportView_I2332();
        m_dataSource1            = rcbApplication().currentReport().attributeValue("Ф501_1").createValueIterator();
        m_dataSource2            = rcbApplication().currentReport().attributeValue("Ф501_2").createValueIterator();
        m_dataSourceManualInput1 = rcbApplication().currentReport().attributeValue("Ф501_1ввод").createValueIterator();
        m_dataSourceManualInput2 = rcbApplication().currentReport().attributeValue("Ф501_2ввод").createValueIterator();
    end;

    private macro printReportData()
        var table = m_view.getTableView();
        table.printHead();
        table.print(m_dataSource1, m_dataSourceManualInput1);
        table.printPartHead();
        table.print(m_dataSource2, m_dataSourceManualInput2);
        table.printbottom();
    end;
end;

private class (TPrintController_I2332) TPrintController_I3129()
    initTPrintController_I2332();

    m_view = TReportView_I3129();

    private macro printReportData()
        var table = m_view.getTableView();
        table.printHead();
        table.print(m_dataSource1, m_dataSourceManualInput1, "1");
        table.printPartHead();
        table.print(m_dataSource2, m_dataSourceManualInput2, "2");
        table.printbottom();
    end;
end;

private class (TPrintController_I3129) TPrintController_I4212()
    macro print()
        m_view.setOutputFile(false);
        m_view.setReportWidth(ternary(isEmpty(), 80, m_view.getWidth()));
        m_view.printLendingAgencyCodeZone();
        m_view.printNamesZone("Полное или сокращенное фирменное наименование кредитной организации ");

        if (isEmpty())
            m_view.printNullDataZone();
        else
            printReportData();
        end;

        m_view.printSignatureZone();

        m_view.resetOutputFile();
        m_view.show();
    end;

    private macro ctorTPrintController_I4212()
        initTPrintController_I3129();

        m_view = TReportView_I4212();
    end;

    ctorTPrintController_I4212();
end;

private class (TPrintController_I4212) TPrintController_I5456()
    private var m_dataSource3;

    private macro printReportData()
        var table = m_view.getTableView();
        table.printHead();
        table.print(m_dataSource1, m_dataSourceManualInput1, "1");
        table.printPartHead();
        table.print(m_dataSource2, m_dataSourceManualInput2, "2");
        table.printPart3Head();
        table.print(m_dataSource3, NULL,                     "3");
        table.printbottom();
    end;

    macro print()
        m_view.setOutputFile(false);
        m_view.setReportWidth(ternary(isEmpty(), 80, m_view.getWidth()));
        m_view.printLendingAgencyCodeZone();
        m_view.printNamesZone("Полное или сокращенное фирменное наименование кредитной организации ");

        if (isEmpty())
            m_view.printNullDataZone();
        else
            printReportData();
        end;

        m_view.printSignatureZone();

        m_view.resetOutputFile();
        m_view.show();
    end;

    private macro ctorTPrintController_I5456()
        initTPrintController_I4212();

        m_view = TReportView_5456();
        m_dataSource1            = rcbApplication().currentReport().attributeValue("Ф501_1").createValueIterator();
        m_dataSource2            = rcbApplication().currentReport().attributeValue("Ф501_2").createValueIterator();
        m_dataSource3            = rcbApplication().currentReport().attributeValue("Ф501_3").createValueIterator();
        m_dataSourceManualInput1 = rcbApplication().currentReport().attributeValue("Ф501_1ввод").createValueIterator();
        m_dataSourceManualInput2 = rcbApplication().currentReport().attributeValue("Ф501_2ввод").createValueIterator();
    end;

    ctorTPrintController_I5456();
end;

/**
 *  Класс управления выводом отчета по форме 501 в Excel
 */
private class (TPrintController_I4212) TExcelPrintController()

    macro print()
        m_view.print();
    end;

    private macro constructorTExcelPrintController()
        initTPrintController_I4212();
        m_view = TF501ExcelView();
    end;
    constructorTExcelPrintController();

end;

private class (TPrintController_I5456) TExcelPrintController_I5456()

    macro print()
        m_view.print();
    end;

    private macro constructorTExcelPrintController()
        initTPrintController_I5456();
        m_view = TF501ExcelView_I5456();
    end;
    constructorTExcelPrintController();

end;

/***************************************************************************************************
 *  Основная функция
 **************************************************************************************************/
private macro main()
    const FORMAT_LABEL   = "-fmt:";
    var fmtIndex = index(cmdArgs, FORMAT_LABEL);
    var format   = subStr(cmdArgs, fmtIndex + strLen(FORMAT_LABEL), 3);

    if   (   (rcbApplication().currentReport().context.period.EndDate >= RCB_I5456_DATE) 
          or (is5456RSHBChangesProject() and (rcbApplication().currentReport().context.period.EndDate >= RCB_I5456_DATE_F501)))
        if   (format == F501_REPORT_FORMAT_TXT)
            TPrintController_I5456().print();
        elif (format == F501_REPORT_FORMAT_XLS)
            TExcelPrintController_I5456().print();
        end;
    elif (rcbApplication().currentReport().context.period.EndDate >= RCB_I4212_DATE)
        if   (format == F501_REPORT_FORMAT_TXT)
            TPrintController_I4212().print();
        elif (format == F501_REPORT_FORMAT_XLS)
            TExcelPrintController().print();
        end;
    elif (rcbApplication().currentReport().context.period.EndDate >= RCB_I3129_DATE)
        TPrintController_I3129().print();
    elif (rcbApplication().currentReport().context.period.EndDate >= RCB_I2332_DATE)
        TPrintController_I2332().print();
    else
        TPrintController_I2121().print();
    end;
end;
/***************************************************************************************************
 *  Вызов осуществляется системной операцией
 **************************************************************************************************/
//exit(0);
установитьФлагВозврата(OK_MACRO_FLAG);
exit(1);
