/*───────────────────────────────────────────────────────────────────────────┐
  RS-Bank V6                                                  R-Style Softlab
  Файл подсистемы "Регламентируемая отчетность"

  Печать приложения 14. Глава 2.
└───────────────────────────────────────────────────────────────────────────*/
import pr_PRL14;

CLASS (RRG_PRL14_Report) RRG_PRL14_Report2()

    private
    Macro Constructor()
        InitRRG_PRL14_Report();
    End;

    Constructor();

END;
