prod:
  hosts:
    sgo-ap605:
      ansible_host: 10.26.87.5
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_scheme: https
      ansible_winrm_transport: certificate
      ansible_winrm_cert_pem: .cicd/client-cert.pem
      ansible_winrm_cert_key_pem: .cicd/client-cert.pem
      ansible_winrm_server_cert_validation: ignore
    sgo-ap608:
      ansible_host: 10.26.87.6
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_scheme: https
      ansible_winrm_transport: certificate
      ansible_winrm_cert_pem: .cicd/client-cert.pem
      ansible_winrm_cert_key_pem: .cicd/client-cert.pem
      ansible_winrm_server_cert_validation: ignore
    sgo-ap1180:
      ansible_host: 10.26.87.9
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_scheme: https
      ansible_winrm_transport: certificate
      ansible_winrm_cert_pem: .cicd/client-cert.pem
      ansible_winrm_cert_key_pem: .cicd/client-cert.pem
      ansible_winrm_server_cert_validation: ignore
