/*****************************************************************************/
/*                                                           R-Style Softlab */
/*                                                                           */
/*               Отчет по номиналам за дату                                  */
/*                                                                           */
/*  Create : Belohonov P.V.                                                  */
/*  Date   : 05.04.2019                                                      */
/*****************************************************************************/
import RsbFormsInter, globals, Календарь, sp_class, captureoutput;

private const FT_INT32  = 1;
private const FT_STRING = 7;
private const FT_DATE   = 9;

var ExitCode:integer, FProcPanel:TRsbPanel, Rep, rn = 1, sheet = 1;

private var _sqlString:string;

macro print_header(Type, Header_str)
 
// var EXCEL_MONEY = "\"# ##0,0000\"";
  var EXCEL_MONEY = "\"##0,0000;-##0,0000;##0,0000\"";
  Rep.SetExecute("iBook.Sheets(1).Columns(4).NumberFormat = "+EXCEL_MONEY+";");
  Rep.SetExecute("iBook.Sheets(1).Columns(8).NumberFormat = "+EXCEL_MONEY+";");
  Rep.SetExecute("iBook.Sheets(1).Columns(10).NumberFormat = "+EXCEL_MONEY+";");
  Rep.SetExecute("iBook.Sheets(1).Columns(12).NumberFormat = "+EXCEL_MONEY+";");
 
  Rep.AddEmptyStr();
  Rep.AddEmptyStr();

  Rep.AddPrintCell("гос.рег",            14, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("ISIN",                    12, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("Текущий номинал",    10, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("Валюта номинала",                   3, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("Краткое наименование",              22, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("Полное наименование",              22, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("Рыночная",              10, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("%",              1, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("Блумберг",              10, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("%",              1, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("Мотивированное суждение",              10, null, "c:ex_FS(b):ex_B(tblr)");
  Rep.AddPrintCell("%",              1, null, "c:ex_FS(b):ex_B(tblr)");
  
  Rep.AddStr();
end;

macro PrintStr(lsin, ISIN, curnom, cur, def, name, c1,r1,c2,r2,c3,r3)
 
    
  Rep.AddPrintCell(lsin,      14, null, "r:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(isin,      12, null, "c:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(curnom,      10, null, "c:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(cur,          3, null, "c:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(def, 22, null, "r:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(name,  22, null, "r:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(c1,        10, null, "c:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(r1,   1, null, "c:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(c2,        10, null, "c:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(r2,   1, null, "c:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(c3,        10, null, "c:ex_FS():ex_B(tblr)");
  Rep.AddPrintCell(r3,   1, null, "c:ex_FS():ex_B(tblr)");
  Rep.AddStr();
  
end;


private macro GetRate(fromfiid, tofiid, type, pdate, percasis, isrelative:@string )
var RetVal = 0.0;
var sql = 
"declare "+
"FUNCTION GetRate( pFromFI IN NUMBER " +
"                 ,pToFI    IN NUMBER " +
"                 ,pType    IN NUMBER " +
"                 ,pbdate   IN DATE " +
"                 ,PercAsIs in NUMBER DEFAULT 0  " +
"                 ,IsRelative out varchar2  " +
"                ) " +
"  RETURN NUMBER " +
"IS " +
"  v_Rate     NUMBER; " +
"  v_IsRelative char := chr(0); " +
"  v_RateID   NUMBER; " +
"  v_RateDate DATE; " +
"BEGIN " +
"  v_Rate := RSI_RSB_FIInstr.FI_GetRate( pFromFI, pToFI, pType, pbdate, pbdate-to_date('01.01.0001','DD.MM.YYYY'), 0, v_RateID, v_RateDate ); " +
"  if( v_Rate <= 0 ) then " +
"     v_Rate := RSI_RSB_FIInstr.FI_GetRate( pFromFI, -1, pType, pbdate, pbdate-to_date('01.01.0001','DD.MM.YYYY'), 0, v_RateID, v_RateDate ); " +
"  end if; isRelative := chr(0); " +
"      BEGIN " +
"         SELECT t_IsRelative " +
"           INTO v_IsRelative " +
"           FROM dratedef_dbt " +
"          WHERE t_rateid = v_RateID AND t_isinverse != CHR (88); " +
"      EXCEPTION " +
"         WHEN no_data_found " +
"         THEN " +
"            v_isrelative :=chr(88); " +
"      END; " 
"  if(v_RateID > 0)then " +
"    begin " +
"      select t_rate/power(10,t_point)/t_scale, t_IsRelative   " +
"      into v_Rate, v_IsRelative " +
"      from dratedef_dbt " +
"      where t_rateid = v_RateID and " +
"            t_isinverse != chr(88) and " +
"            t_sincedate = v_RateDate; " +
"    exception when others then " +
"      begin " +
"        select t_rate/power(10,t_point)/t_scale " +
"        into v_Rate " +
"        from dratehist_dbt t " +
"        where t_rateid = v_RateID and " +
"              t_isinverse != chr(88) and " +
"              t_sincedate = (select max(v_RateDate) from dratehist_dbt where t_rateid = t.t_rateid and t_sincedate <= v_ratedate); " +
"      exception when others then " +
"        null; " +
"      end; " +
"    end; " +
"    if (PercAsIS = 0) and (v_IsRelative = chr(88)) then  " +
"       v_Rate := RSB_FIINSTR.FI_GETNOMINALONDATE(pFromFI, v_RateDate)*v_Rate/100; " +
"    end if; " +
"  end if; " +
" " +
"  isRelative := nvl(v_IsRelative,chr(0));" +
"  return v_Rate; " +
"EXCEPTION " +
"  when OTHERS then isRelative := chr(0); return 0.0; " +
"END; " +
"BEGIN " + 
" :retval := GetRate(:fromfiid,:tofiid, :type, :pdate, :percasis, :isrelative); " + 
"End; ";
var cmd = RsdCommand(sql);
    cmd.addparam("retval",     rsdbp_out, v_double);
    cmd.addparam("fromfiid",   rsdbp_in,  fromfiid);
    cmd.addparam("tofiid",     rsdbp_in,  tofiid);
    cmd.addparam("type",       rsdbp_in,  type);
    cmd.addparam("pdate",      rsdbp_in,  pdate);
    cmd.addparam("percasis",   rsdbp_in,  percasis);
    cmd.addparam("isrelative", rsdbp_out, V_STRING);
    cmd.execute();
if (valtype(cmd.value("isrelative")) == 26) isrelative = strfor(0) else isrelative = cmd.value("isrelative"); end;
return cmd.value("retval");
end;


macro GetData(BegDate)
  
  var rs, cmd;
var sql = 
"SELECT A.T_ISIN, " +
"       A.T_LSIN, " +
"       RSB_FIINSTR.FI_GETNOMINALONDATE(F.T_FIID, "+GetSqlDate(BegDate)+") CURNOM, " +
"       (select t_ccy from dfininstr_dbt where t_fiid = f.t_facevaluefi) cur, "
"       F.T_DEFINITION, " +
"       F.T_NAME, f.t_fiid " +
"  FROM DFININSTR_DBT F, DAVOIRISS_DBT A " +
" WHERE A.T_FIID = F.T_FIID AND F.T_FI_KIND = 2 " +
" AND RSB_FIINSTR.FI_AVRKINDSGETROOT(F.T_FI_KIND,F.T_AVOIRKIND) IN (17,20, 16, 10) and a.t_spisclosed <> chr(88) "; 
  
  cmd = RSDCommand(sql);
//  cmd.AddParam("1", RSDBP_IN, BegDate);
  rs = RSDRecordset(cmd, RSDVAL_CLIENT, RSDVAL_STATIC);

  var c1,r1,c2,r2,c3,r3;
  var cnt = 0;
   InitProgress(SQL_GetNRecs(sql),"Номиналы за дату", "Номиналы за дату");
  while(rs and rs.MoveNext())
    c1 = GetRate(rs.value("t_fiid"), natcur, 1, begdate, 1, @r1 );
    c2 = GetRate(rs.value("t_fiid"), natcur, 23, begdate, 1, @r2 );
    c3 = GetRate(rs.value("t_fiid"), natcur, 1001, begdate, 1, @r3 );
    PrintStr(rs.value("t_lsin"), rs.value("t_isin"), rs.value("curnom"), rs.value("cur"), 
             rs.value("t_definition"), rs.value("t_name"), c1,r1,c2,r2,c3,r3);
    UseProgress(cnt=cnt+1);
  end;
  RemProgress;
end;

class(TRsbPanel) DatePanel()

  var LBegDate:TRsbLabel, ,
      FieldBegDate:TRsbEditField, ,
      BegDate:date = date(0,0,0);

  InitTRsbPanel();
  SetCaption("Выберите дату отчета");
  SetStatus("~Esc~ Выход ~F3~ Календарь ~F2~ Выполнить ~F9~ Выполнить");
  SetSize(28, 4);
  SetPosition(45,10);
  
  LBegDate = TRsbLabel(3, 2, "За дату:");
  addLabel(LBegDate);
  
  FieldBegDate = TRsbEditField(FT_DATE);
  FieldBegDate.setPosition(15,2);
  FieldBegDate.setSize(10,1);
  FieldBegDate.Name = "BegDate";
  FieldBegDate.bindValue( this, "BegDate" );
  FieldBegDate.value = {Curdate};
  addControl(FieldBegDate);
  
  
  addEventHandler(RSB_EV_KEY_PRESSED, R2M(this, "KeyEvent"));//KeyEvent
  
  
  macro KeyEvent(RsbEvent:Object)
    var focusedControl;
    
    if (rsbEvent.KeyCode == 27)//ESC
      this.Close(rsbEvent.KeyCode);
    elif ((rsbEvent.KeyCode == 316) or (rsbEvent.KeyCode == 323))//F2 or F9
      BegDate = FieldBegDate.value;
      this.Close(rsbEvent.KeyCode);
    elif (rsbEvent.KeyCode == 317)//F3
      focusedControl = this.focusedControl();
      if(focusedControl.Name == "BegDate")
        BegDate = GetDateByCalendar(BegDate);
        FieldBegDate.Value = BegDate;
      end;
    end;
  end;
  
end;


FProcPanel = DatePanel();
ExitCode = FProcPanel.Run();

if(ExitCode)
  Rep = CMakeReport("┌┬┬┬┬┬┬┬┬┬┬┬┐");
  Rep.SetDefaultFontName("Times New Roman");
  Rep.SetDefaultFontSize(12);
  Rep.SetFlagShowGrid(true);

  Rep.SetExecute("iBook.Sheets("+sheet+").Rows("+rn+").WrapText = false;");
  Rep.AddEmptyStr();
  Rep.AddEmptyStr();
  Rep.AddPrintCell("Номиналы за дату " + FProcPanel.BegDate, 101, null, "c:ex_FS(b):ex_B()");
  Rep.AddStr();

  print_header();
  GetData(FProcPanel.BegDate);

  Rep.PrintWinRep("Отчет");
  Rep.SetZoomType(ZOOM_TYPE_A4L);
  Rep.SetWinRepOutput();
  Rep.ShowWinRep();

end;
exit(1);


/*IMPORt CB_SQL, globals;

var d = {curdate};
 getdate(d,"");
var sql = 
"SELECT A.T_ISIN, " +
"       A.T_LSIN, " +
"       RSB_FIINSTR.FI_GETNOMINALONDATE(F.T_FIID," + getsqldate(d)  + ") CURNOM, " +
"       (select t_ccy from dfininstr_dbt where t_fiid = f.t_facevaluefi) cur, "
"       F.T_DEFINITION, " +
"       F.T_NAME " +
"  FROM DFININSTR_DBT F, DAVOIRISS_DBT A " +
" WHERE A.T_FIID = F.T_FIID AND F.T_FI_KIND = 2 " +
" AND RSB_FIINSTR.FI_AVRKINDSGETROOT(F.T_FI_KIND,F.T_AVOIRKIND) IN (17,20, 16, 10) and a.t_spisclosed <> chr(88) "; 
       var cmd1 = RSDCommand(sql);
var       rs1 = RSDRecordset(cmd1 , null, RSDVAL_STATIC );

       if (RunScroll (rs1)); //,arnum+1, col1, "test" ,"EvProc"," роводки к ыгрузке.  " + sql_GetNRecs(sql_) + "шт.", "F3 - Фильтр:  " + bottom_txt , true, 1, 1))
       //   return rs1;
      end;
 */




