
private file attr("objattr.dbt") key 0;
var AcceptedActionCategory;


/*вызывается при ручной установке по F2 из списка категорий объекта или из списка установленных атрибутов категории объекта*/
macro CheckAttributeManual(ObjectType : integer, GroupID : integer, CodeList : string, NumInList : string) : bool
  // return false; //в случае ошибки
  return true; //в случае успешной проверки
end;

/*вызывается при установке признака выбором по F9 из списка категорий объекта или из списка установленных атрибутов категории объекта*/
macro CheckAttribute(ObjectType : integer, GroupID : integer, AttrID : integer, dttr2, fff4,fff6,fff7)
  AcceptedActionCategory = GetGlobalParameter ("AcceptedActionCategory", true);
  return AcceptedActionCategory; 
end;     

/*удаление признака категории для объекта*/
macro CheckCategoryDelete(param1,GroupID,ObjectType,ObjectID,param2,AttrID_new, param3)
  msgbox("Удаление значения категории невозможно");
  return 0;
end;

macro CheckCategorySet(param1,GroupID,ObjectType,ObjectID,param2,AttrID_new, param3, f1,f2,f3,f4)
   var ObjCat;
   var AttrID_old = 0;
   var IsAttr, stat;
  
   record attr("objattr.dbt") key 0;

   AcceptedActionCategory = true;

   ObjCat = RsbObjCategories(ObjectType, ObjectID);   // текущее значение
   IsAttr = ObjCat.IsAttrPresense(GroupID, 1, null, null, null, date()); // установлено ли "да" GetFirst, GetMainAttr не подходят

   if (IsAttr)
      msgbox("Установлено значение Да, другие значения установить невозможно");
      AcceptedActionCategory = false;
   else
      AcceptedActionCategory = true;
   end;

   SetGlobalParameter ("AcceptedActionCategory", AcceptedActionCategory);
   return true;
end;