/*
$Name:        od04.mac
$Module:      Ценные бумаги
$Description: Таблица ОД_4: Cделки c иностранной валютой, драгоценными металлами, ценными бумагами и иными базисными активами, отражаемые по главе Г баланса, по состоянию на отчетную дату, а также производные финансовые инструменты, не отраженные по Главе Г
$Programmer:  Кротов А.
*/
import od04_panel, ReportUser, bnk_dttmfrmt, "scservop.mac";
import captureoutput;


PRIVATE CLASS (TX_ReportUser) od04_Report
  var m_BeginDate/*, m_EndDate*/;

  /*Создание отчета*/
  PRIVATE MACRO Create()

    /*Счет по маске*/
    macro AccountMask(acc)
      if(strlen(acc) <= 1)
        return "-";
      elif(strlen(acc) != 20)
        return acc;
      else
        return substr(acc,1,5) + "-" + substr(acc,6,3) + "-" + substr(acc,9,1) + "-" + substr(acc,10,4) + "-" + substr(acc,14);
      end;
    end;

    /*Балансовый счет*/
    macro AccountBal(acc)
      if(strlen(acc) < 5)
        return "-";
      else
        return substr(acc,1,5);
      end;
    end;

    /*Валюта счета*/
    macro AccountCur(acc)
      if(strlen(acc) < 8)
        return "-";
      else
        return substr(acc,6,3);
      end;
    end;

    /*Итоги дня по ПФИ*/
    macro Get_position_interest (fiid, dt)
      var m_cmd, m_RS, result_position = 0;
      StartCaptureOutput();
      [
        select t_shortposition - t_longposition as res_pos
        from ddvfiturn_dbt fiturn
        where t_fiid = :fiid and
              t_clientcontr = 0 and
              t_date = (select max(t_date)
                        from ddvfiturn_dbt f
                        where f.t_fiid = fiturn.t_fiid and
                              f.t_department = fiturn.t_department and
                              f.t_broker = fiturn.t_broker and
                              f.t_clientcontr = fiturn.t_clientcontr and
                              f.t_genagrid = fiturn.t_genagrid and
                              f.t_date <= :edt)
      ];
      m_cmd = RsdCommand(EndCaptureOutput());
      m_cmd.AddParam("fiid", RSDBP_IN, fiid);
      m_cmd.AddParam("edt", RSDBP_IN, dt);
      m_cmd.Execute();
      m_RS = TRsbDataSet(m_cmd);
      if (m_RS.movenext() )
        result_position = m_RS.value("res_pos");
      end;
      return result_position;
    End;

    /*Строка по срочнмоу рынку*/
    macro InsSR(iname, md, idrawingdate, ma1, ma2, ifi_code, ifacename, ar1, ar2, am);
      var d, a1, ba1, a2, ba2, bs = "SALE", i, pos_interest = 0;
      i = 0;
      while(i < md.size)
        if(i == 0)
          d = string(md[i]:f);
        else
          d = d + " /" + string(md[i]:f);
        end;
        i = i + 1;
      end;
      i = 0;
      while(i < ma1.size)
        if(i == 0)
          a1 = AccountMask(ma1[i]);
          ba1 = substr(ma1[i], 1, 5);
        else
          a1 = a1 + ", " + ma1[i];
          ba1 = ba1 + ", " + substr(ma1[i], 1, 5);
        end;
        i = i + 1;
      end;
      i = 0;
      while(i < ma2.size)
        if(i == 0)
          a2 = AccountMask(ma2[i]);
          ba2 = substr(ma2[i], 1, 5);
        else
          a2 = a2 + ", " + ma2[i];
          ba2 = ba2 + ", " + substr(ma2[i], 1, 5);
        end;
        i = i + 1;
      end;

      if(am < 0)
        bs = "BUY";
        am = -am;
      end;
      PrintTableLine(
            /* 1*/ "row1_1", iname, null, 
            /* 2*/ "row1_2", iname, null, 
            /* 3*/ "row1_3", "Банк НКЦ АО", null, 
            /* 4*/ "row1_4", "ПФИ", null, 
            /* 5*/ "row1_5", bs, null, 
            /* 6*/ "row1_6", "Беспоставочная", null, 
            /* 7*/ "row1_7", d, null, 
            /* 8*/ "row1_8", DDpMMpYYYY(date(idrawingdate)), null, 
            /* 9*/ "row1_9", "-", null, 
            /*10*/ "row1_10", a1, null, 
            /*11*/ "row1_11", ba1, null, 
            /*12*/ "row1_12", ifi_code, null, 
            /*13*/ "row1_13", ifacename, null, 
            /*14*/ "row1_14", am, null, 
            /*15*/ "row1_15", ar1, null, 
            /*16*/ "row1_16", "-", null, 
            /*17*/ "row1_17", "-", null, 
            /*18*/ "row1_18", "", null, 
            /*19*/ "row1_19", a2, null, 
            /*20*/ "row1_20", ba2, null, 
            /*21*/ "row1_21", ifacename, null, 
            /*22*/ "row1_22", am, null, 
            /*23*/ "row1_23", ar2, 2, 
            /*24*/ "row1_24", "-", null, 
            /*25*/ "row1_25", "-", null, 
            /*26*/ "row1_26", "", null, 
            /*27*/ "row1_27", "-", null, 
            /*28*/ "row1_28", "-", null, 
            /*29*/ "row1_29", "-", null, 
            /*30*/ "row1_30", "", null, 
            /*31*/ "row1_31", "", null, 
            /*32*/ "row1_32", "", null, 
            /*33*/ "row1_33", "Y", null, 
            /*34*/ "row1_34", "", null, 
            /*35*/ "row1_35", "", null, 
            /*36*/ "row1_36", "", null, 
            /*37*/ "row1_37", "", null, 
            /*38*/ "row1_38", "Y", null, 
            /*39*/ "row1_39", "", null, 
            /*40*/ "row1_40", "БИРЖА", null);
    end;


/*Точка входа*/
    var cnt;
    var m_cmd, m_RS_perc, m_cmd_perc, m_que_perc;

    /*Отключаем все индикаторы*/
    if(m_UseTemplate)
      m_ObjTemplateXLS.SetFlagShowIndicator(false);
    else
      __BUG_Global_m_ObjTemplateXLS.SetFlagShowIndicator(false);
    end;
    m_ProgressIndicator = CreateProgressIndicator(true);

    /*Даты отчета*/
    if(m_Form.GetFieldValue(PNFLD_PERIOD) < 13)
      /*Задан месяц*/
      m_BeginDate = date(1, m_Form.GetFieldValue(PNFLD_PERIOD), FormData.Year);
      m_EndDate = DateAfterCalenMonths(m_BeginDate, 1) - 1;
    else 
      /*Задан квартал*/
      m_BeginDate = date(1, (m_Form.GetFieldValue(PNFLD_PERIOD) - 12 - 1) * 3 + 1, FormData.Year);
      m_EndDate = DateAfterCalenMonths(m_BeginDate, 3) - 1;
    end;

/*Лист "Реестр ПФИ на отчетную дату"*/
    SetActiveSheet("Реестр ПФИ на отчетную дату");
    PrintFormatString("", "reportname", "Таблица ОД_4 ""Cделки c иностранной валютой, драгоценными металлами, ценными бумагами и иными базисными активами, отражаемые по главе Г баланса, по состоянию на " + string(date(m_EndDate+1):f) + ", а также производные финансовые инструменты, не отраженные по Главе Г""");
    var curUSD = $0;
    convsum(curUSD, $100, m_EndDate, 7, 0);
    curUSD = double(curUSD) / 100;
    PrintFormatString("", "reportcur", curUSD);
    RegisterTable( "row1_0", "",
             /* 1*/ "row1_1", 
             /* 2*/ "row1_2", 
             /* 3*/ "row1_3", 
             /* 4*/ "row1_4", 
             /* 5*/ "row1_5", 
             /* 6*/ "row1_6", 
             /* 7*/ "row1_7", 
             /* 8*/ "row1_8", 
             /* 9*/ "row1_9", 
             /*10*/ "row1_10", 
             /*11*/ "row1_11", 
             /*12*/ "row1_12", 
             /*13*/ "row1_13", 
             /*14*/ "row1_14", 
             /*15*/ "row1_15", 
             /*16*/ "row1_16", 
             /*17*/ "row1_17", 
             /*18*/ "row1_18", 
             /*19*/ "row1_19", 
             /*20*/ "row1_20", 
             /*21*/ "row1_21", 
             /*22*/ "row1_22", 
             /*23*/ "row1_23", 
             /*24*/ "row1_24", 
             /*25*/ "row1_25", 
             /*26*/ "row1_26", 
             /*27*/ "row1_27", 
             /*28*/ "row1_28", 
             /*29*/ "row1_29", 
             /*30*/ "row1_30", 
             /*31*/ "row1_31", 
             /*32*/ "row1_32", 
             /*33*/ "row1_33", 
             /*34*/ "row1_34", 
             /*35*/ "row1_35", 
             /*36*/ "row1_36", 
             /*37*/ "row1_37", 
             /*38*/ "row1_38", 
             /*39*/ "row1_39", 
             /*40*/ "row1_40");
    this.AutoFilter(6, "B", "AO");
    StartCaptureOutput();
    [
      select case when t_demandaccount = chr(1) then '-'
                  else t_demandaccount
             end t_demandaccount,
             t_demandsum, 
             case when t_demandsum > 0 and t_demandfiid > 0 then round(rsi_rsb_fiinstr.convsum(t_demandsum,t_demandfiid,0,edt),2) 
                  else t_demandsum 
             end t_demandsumRUR,  
             case when t_demandsum > 0 then case when t_demandfiid > 0 then round(rsi_rsb_fiinstr.convsum(1,t_demandfiid,0,edt),4) else 1 end
                  else 0 
             end t_demandrate,  
             case when t_liabilityaccount = chr(1) then '-'
                  else t_liabilityaccount
             end t_liabilityaccount, 
             t_liabilitysum, 
             case when t_liabilitysum > 0 and t_liabilityfiid > 0 then round(rsi_rsb_fiinstr.convsum(t_liabilitysum,t_liabilityfiid,0,edt),2) 
                  else t_liabilitysum 
             end t_liabilitysumRUR,  
             case when t_liabilitysum > 0 then case when t_liabilityfiid > 0 then round(rsi_rsb_fiinstr.convsum(1,t_liabilityfiid,0,edt),4) else 1 end 
                  else 0 
             end t_liabilityrate,  
             t_type
      from (select t_begdate, t_enddate, 
                   sum(t_demandsum) t_demandsum, sum(t_liabilitysum) t_liabilitysum, 
                   max(t_demandaccount) t_demandaccount, max(t_liabilityaccount) t_liabilityaccount, 
                   max(t_demandfiid) t_demandfiid, max(t_liabilityfiid) t_liabilityfiid, 
                   'ПРОЦЕНТНЫЙ ПЕРИОД ('||to_char(row_number() over(order by t_begdate), 'fm999')||' '||t_rate||')' t_type
            from (select dvnpmgr.t_begdate, 
                         dvnpmgr.t_enddate, 
                         case when dvnpmgr.t_demandsum > 0 then abs(rsi_rsb_account.RestAC((select t_account from dmcaccdoc_dbt where t_catnum = 5133 and t_docid = dvnpmgr.t_id and t_dockind = 4811 and t_activatedate < edt and ( ( T_DISABLINGDATE > edt) or (T_DISABLINGDATE = to_date('01.01.0001','DD.MM.YYYY')) )), dvnfi.t_fiid , edt, 4, 0)) else 0 end as t_demandsum, 
                         case when dvnpmgr.t_liabilitysum > 0 then abs(rsi_rsb_account.RestAC((select t_account from dmcaccdoc_dbt where t_catnum = 5134 and t_docid = dvnpmgr.t_id and t_dockind = 4811 and t_activatedate < edt and ( ( T_DISABLINGDATE > edt) or (T_DISABLINGDATE = to_date('01.01.0001','DD.MM.YYYY')) )), dvnfi.t_fiid , edt, 4, 0)) else 0 end as t_liabilitysum, 
                         case when dvnpmgr.t_side = 2 then (select t_account from dmcaccdoc_dbt where t_catnum = 5133 and t_docid = dvnpmgr.t_id and t_dockind = 4811 and t_activatedate < edt and ( ( T_DISABLINGDATE > edt) or (T_DISABLINGDATE = to_date('01.01.0001','DD.MM.YYYY')) )) 
                              else chr(1) 
                         end t_demandaccount, 
                         case when dvnpmgr.t_side = 1 then  (select t_account from dmcaccdoc_dbt where t_catnum = 5134 and t_docid = dvnpmgr.t_id and t_dockind = 4811 and t_activatedate < edt and ( ( T_DISABLINGDATE > edt) or (T_DISABLINGDATE = to_date('01.01.0001','DD.MM.YYYY')) ))
                              else chr(1) end t_liabilityaccount, 
                         case when dvnpmgr.t_side = 2 then dvnfi.t_fiid 
                              else -1 
                         end t_demandfiid, 
                         case when dvnpmgr.t_side = 1 then dvnfi.t_fiid 
                              else -1 
                         end t_liabilityfiid, 
                         case when dvnfi.t_rateid > 0 then 'плав' 
                              else 'фикс' 
                         end t_rate
                  from ddvnpmgr_dbt dvnpmgr
                  join (select :dialid dialid, :bdt bdt, :edt edt from dual) on 1=1
                  join ddvnfi_dbt dvnfi on dvnfi.t_dealid = dvnpmgr.t_dealid and
                                           dvnpmgr.t_side = decode(dvnfi.t_type,0,1,2)
                  where dvnpmgr.t_dealid in (:dialid) and DVNPMGR.T_ENDDATE >  :bdt) /*PNV i-support 496376 только те платежи, которые на внебалансе на отчетную дату*/
            WHERE ((t_demandsum != 0) or (t_liabilitysum !=0))group by t_begdate, t_enddate, t_rate)
      join (select :bdt bdt, :edt edt from dual) on t_enddate >= bdt 
      order by t_begdate    
    ];
    m_que_perc = EndCaptureOutput();
    StartCaptureOutput();
    [
      select count(1) over() t_cnt,
             t_id, t_code, t_extcode, t_contragentname, t_dealkind, t_dealtype, t_exectype, t_dealdate, t_execdate, t_rate, /*PNV 508081*/
             t_definition, t_ficodeT, t_ficodeO,
             t_accountT, t_accountTfiid, t_amountT, case when fi_kind = 1 or t_accountT = chr(1) then t_amountTRUR else t_accountTrestRUR end t_amountTRUR, t_ratefiidT, 
             t_accountO, t_accountOfiid, t_amountO, case when fi_kind = 1 or t_accountO = chr(1) then t_amountORUR else t_accountOrestRUR end t_amountORUR, t_ratefiidO, 
             t_isresident, t_isnetting, t_genagr, t_account453, t_account454,
             t_restaccount453, 
             t_restaccount454, dealpart,  /*PNV 508081*/
             is_sec_dealtype, is_need_rest_g_o, is_need_rest_g_t, totalcost
      from (select fi_kind,
                   t_id, t_code, t_extcode, t_contragentname, t_dealkind, t_dealtype, t_exectype, t_dealdate, t_execdate, t_rate, 
                   t_definition, t_ficodeT, t_ficodeO,
                   t_accountT, t_accountTfiid, t_amountT, t_amountTRUR, t_accountTrest, case when t_accountTfiid = 0 then t_accountTrest else abs(round(rsi_rsb_fiinstr.convsum(t_accountTrest, t_accountTfiid, 0, edt), 2)) end t_accountTrestRUR, t_ratefiidT, 
                   t_accountO, t_accountOfiid, t_amountO, t_amountORUR, t_accountOrest, case when t_accountOfiid = 0 then t_accountOrest else abs(round(rsi_rsb_fiinstr.convsum(t_accountOrest, t_accountOfiid, 0, edt), 2)) end t_accountOrestRUR, t_ratefiidO, 
                   t_isresident, t_isnetting, t_genagr, t_account453, t_account454,
                   t_restaccount453, 
                   t_restaccount454, dealpart,  /*PNV 508081*/
                   is_sec_dealtype, is_need_rest_g_o, is_need_rest_g_t, totalcost
            from (select edt, fi_kind,
                        t_id, t_code, t_extcode, t_contragentname, t_dealkind, t_dealtype, t_exectype, t_dealdate, t_execdate, t_rate, 
                        t_definition, t_ficodeT, t_ficodeO,
                        t_accountT, t_accountTfiid, t_amountT, t_amountTRUR, abs(rsb_account.restall(t_accountT, 4, t_accountTfiid, edt)) t_accountTrest, t_ratefiidT, 
                        t_accountO, t_accountOfiid, t_amountO, t_amountORUR, abs(rsb_account.restall(t_accountO, 4, t_accountOfiid, edt)) t_accountOrest, t_ratefiidO, 
                        t_isresident, t_isnetting, t_genagr, t_account453, t_account454,
                        case when t_account453 != chr(1) then abs(rsb_account.restall(t_account453, 1, 0, edt)) else 0 end t_restaccount453, 
                        case when t_account454 != chr(1) then abs(rsb_account.restall(t_account454, 1, 0, edt)) else 0 end t_restaccount454, dealpart,  /*PNV 508081*/
                        is_sec_dealtype,
                        (case when is_sec_dealtype > 0 then 
                                                           (select count(1) 
                                                                         from dmcaccdoc_dbt accdoc 
                                                                        where accdoc.t_docid = tmp.t_id 
                                                                          and accdoc.t_dockind = 101
                                                                          and accdoc.t_account = t_accountO
                                                                          and accdoc.t_catid = 476
                                                                      ) 
                              else 0 end) is_need_rest_g_o,
                        (case when is_sec_dealtype > 0 then 
                                                           (select count(1) 
                                                                         from dmcaccdoc_dbt accdoc 
                                                                        where accdoc.t_docid = tmp.t_id 
                                                                          and accdoc.t_dockind = 101
                                                                          and accdoc.t_account = t_accountT
                                                                          and accdoc.t_catid = 477
                                                                      )
                              else 0 end) is_need_rest_g_t,
                        totalcost
                  from(select bdt,
                              edt,
                              case when dvndeal.fi_kind in (1,6, 3) then 1 else 2 end fi_kind,
                              dvndeal.t_id t_id, 
                              dvndeal.t_code t_code,
                              dvndeal.t_extcode t_extcode,
                              nvl(contragent.t_shortname,chr(1)) t_contragentname,
                              case when (dvndeal.fi_kind in (1,6) and dvndeal.t_dealtype not in ('P')) then case when dvndeal.t_dealtype in ('O','U','S','D') then case when dvndeal.t_type = 1 then 'покупка' else 'продажа' end ||' '|| dvndeal.t_ccyT||' за '||dvndeal.t_ccyO else '-' end
                                   else case when dvndeal.t_ispfi = chr(88) then 'ПФИ' else 'срочная' end
                              end t_dealkind,
                              case when dvndeal.fi_kind in (1,6,3) then
                                        case when dvndeal.t_dealtype = 'P' then case when dvndeal.t_fiidT = dvndeal.t_fiidO then 'ПРОЦЕНТНЫЙ СВОП' else 'ВАЛЮТНО-ПРОЦЕНТНЫЙ СВОП' end
                                             when dvndeal.t_dealtype = 'O' then 'OPTION' 
                                             when dvndeal.t_dealtype = 'U' then case when dvndeal.t_ispfi = chr(88) then 'FORWARD PFI' else 'FORWARD' end
                                             when dvndeal.t_dealtype = 'S' then case when dvndeal.t_ispfi = chr(88) then 'SWAP PFI' else 'SWAP' end 
                                             when dvndeal.t_dealtype = 'D' then case when dvndeal.t_periodcls = 0 then 'TODAY' 
                                                                                     when dvndeal.t_periodcls = 1 then 'TOMORROW' 
                                                                                     when dvndeal.t_periodcls = 2 then 'SPOT' 
                                                                                     else 'T+'||to_char(nvl(dvndeal.t_periodcls,0),'fm99999')
                                                                                end 
                                             else '-' 
                                        end
                                   else case when dvndeal.t_type = 1 then 'BUY' else 'SALE' end
                              end t_dealtype, 
                              case when dvndeal.t_exectypeT = 1 or dvndeal.t_dockind = 4813/*Конверсионная сделка ФИССиКО*/ then 'ПОСТАВОЧНАЯ' 
                                   else 'БЕСПОСТАВОЧНАЯ' 
                              end t_exectype,
                              dvndeal.t_date t_dealdate,
                              dvndeal.t_execdate t_execdate,
                              case when dvndeal.fi_kind in (1,6) and dvndeal.t_dealtype in ('O','U','S','D') then dvndeal.t_priceT 
                                   else 0 
                              end t_rate,
                              case when fininstrT.t_fi_kind = 2 then fininstrT.t_definition
                                   when fininstrO.t_fi_kind = 2 then fininstrO.t_definition
                                   else '-'
                              end t_definition, 
                              case when fininstrT.t_fi_kind = 2 then fininstrO.t_ccy
                                   when fininstrO.t_fi_kind = 2 then fininstrT.t_ccy
                                   else fininstrT.t_codeinaccount
                              end t_ficodeT, 
                              case when fininstrT.t_fi_kind = 2 then fininstrT.t_definition
                                   when fininstrO.t_fi_kind = 2 then fininstrO.t_definition
                                   else fininstrO.t_codeinaccount
                              end t_ficodeO, 
                              (select nvl(max(mcaccdoc.t_account),chr(0)) 
                               from dmcaccdoc_dbt mcaccdoc
                               where mcaccdoc.t_dockind = dvndeal.t_dockind and
                                     mcaccdoc.t_docid = dvndeal.t_id and
                                     mcaccdoc.t_catid in (460,477,616) and
                                     ((fininstrT.t_fi_kind != 2 and mcaccdoc.t_currency = dvndeal.t_fiidT) or (fininstrT.t_fi_kind = 2 and mcaccdoc.t_currency = fininstrT.t_facevaluefi) or (fininstrT.t_fi_kind = 3 and mcaccdoc.t_currency = fininstrT.t_facevaluefi)) and
                                     mcaccdoc.t_chapter = 4 and
                                     mcaccdoc.t_activatedate <= edt and
                                     (mcaccdoc.t_disablingdate = to_date('01.01.0001','dd.mm.yyyy') or mcaccdoc.t_disablingdate > edt)) t_accountT,
                              case when fininstrT.t_fi_kind != 2 then dvndeal.t_fiidT else fininstrT.t_facevaluefi end t_accountTfiid,
                          case when dvndeal.fi_kind in (1,6, 2, 3) then dvndeal.t_amountT
                                     else  dvndeal.t_amountO  
                              end t_amountT,
                              case    when dvndeal.t_fiidT = 0 then dvndeal.t_amountT
                                   when fininstrT.t_fi_kind = 2 then case when fininstrT.t_facevaluefi = 0 then  round(dvndeal.t_amountT * fininstrT.t_facevalue, 2)  else round(rsi_rsb_fiinstr.convsum(dvndeal.t_amountT * fininstrT.t_facevalue,fininstrT.t_facevaluefi,0,edt),2) end
                                   when fininstrT.t_fi_kind = 3 and dvndeal.t_fiidO = 0  then dvndeal.t_amountT
                                   else round(rsi_rsb_fiinstr.convsum(dvndeal.t_amountT,dvndeal.t_fiidT,0,edt),2) 
                              end t_amountTRUR,
                              case when dvndeal.fi_kind in (1,6) then
                                   case when dvndeal.t_fiidT = 0 then 1
                                        else round(rsi_rsb_fiinstr.convsum(1,dvndeal.t_fiidT,0,edt),4)
                                   end 
                                   else 0 
                               end t_ratefiidT,
                              (select nvl(max(mcaccdoc.t_account),chr(0)) 
                               from dmcaccdoc_dbt mcaccdoc
                               where mcaccdoc.t_dockind = dvndeal.t_dockind and
                                     mcaccdoc.t_docid = dvndeal.t_id and
                                     mcaccdoc.t_catid in (461,476,617) and
                                     --((dvndeal.fi_kind in (1,6) and mcaccdoc.t_catid in (461,476,617)) or (dvndeal.fi_kind not in (1,6) and mcaccdoc.t_catid in (460,477,616))) and
                                     ((fininstrO.t_fi_kind != 2 and mcaccdoc.t_currency = dvndeal.t_fiidO) or (fininstrO.t_fi_kind = 2 and mcaccdoc.t_currency = fininstrO.t_facevaluefi) or (fininstrO.t_fi_kind = 3 and mcaccdoc.t_currency = fininstrO.t_facevaluefi)) and
                                     mcaccdoc.t_chapter = 4 and
                                     mcaccdoc.t_activatedate <= edt and 
                                     (mcaccdoc.t_disablingdate = to_date('01.01.0001','dd.mm.yyyy') or mcaccdoc.t_disablingdate > edt)) t_accountO,
                              case when fininstrO.t_fi_kind != 2 then dvndeal.t_fiidO 
                                   else fininstrO.t_facevaluefi 
                              end t_accountOfiid,
                              case when dvndeal.fi_kind in (1,6, 3) or fininstrO.t_fi_kind = 2 then dvndeal.t_amountO 
                                   else  dvndeal.t_amountT  
                              end t_amountO,
                              case when dvndeal.t_fiidT = 0  and dvndeal.fi_kind = 3 then dvndeal.t_amountO
                                   when dvndeal.t_fiidO = 0 then dvndeal.t_amountO
                                   when fininstrO.t_fi_kind = 2 then case when fininstrO.t_facevaluefi = 0 then round(dvndeal.t_amountO * fininstrO.t_facevalue, 2) else round(rsi_rsb_fiinstr.convsum(dvndeal.t_amountO * fininstrO.t_facevalue,fininstrO.t_facevaluefi,0,edt),2) end
                                   else round(rsi_rsb_fiinstr.convsum(dvndeal.t_amountO,dvndeal.t_fiidO,0,edt),2) 
                              end t_amountORUR,
                              case when dvndeal.fi_kind in (1,6) then
                              case when dvndeal.t_fiidO = 0 then 1
                                   else round(rsi_rsb_fiinstr.convsum(1,dvndeal.t_fiidO,0,edt),4)
                              end else 0 end t_ratefiidO,
                              case when contragent.t_notresident is null then '-' when contragent.t_notresident = chr(88) then 'N' 
                                   else 'Y' 
                              end t_isresident,
                              case when fininstrO.t_fi_kind = 2 or fininstrT.t_fi_kind = 2 then 
                                        case when dvndeal.t_marketkind = 0 then 'N' else 'Y' end
                                   else 
                                        case when dvndeal.t_netting = chr(88) then 'Y' 
                                             else 'N'
                                        end
                              end t_isnetting,
                              case when dvndeal.fi_kind != 2 then  
                                        case when dl_genagr.t_code is null then '-' 
                                             else dl_genagr.t_code||' от '||to_char(dl_genagr.t_start,'dd.mm.yyyy') 
                                        end 
                                   else case when dvndeal.t_marketkind = 0 then 'ВНЕБИРЖА' else 'БИРЖА' end
                              end t_genagr,
                             (select nvl(max(mcaccdoc.t_account),chr(0)) 
                              from dmcaccdoc_dbt mcaccdoc
                              where mcaccdoc.t_dockind = dvndeal.t_dockind and
                                    mcaccdoc.t_docid = dvndeal.t_id and
                                    mcaccdoc.t_catid = 453 and
                                    mcaccdoc.t_currency = 0 and
                                    mcaccdoc.t_chapter = 1 and
                                    mcaccdoc.t_activatedate <= edt and
                                    (mcaccdoc.t_disablingdate = to_date('01.01.0001','dd.mm.yyyy') or mcaccdoc.t_disablingdate > edt)) t_account453,
                             (select nvl(max(mcaccdoc.t_account),chr(0)) 
                              from dmcaccdoc_dbt mcaccdoc
                              where mcaccdoc.t_dockind = dvndeal.t_dockind and
                                    mcaccdoc.t_docid = dvndeal.t_id and
                                    mcaccdoc.t_catid = 454 and
                                    mcaccdoc.t_currency = 0 and
                                    mcaccdoc.t_chapter = 1 and
                                    mcaccdoc.t_activatedate <= edt and
                                    (mcaccdoc.t_disablingdate = to_date('01.01.0001','dd.mm.yyyy') or mcaccdoc.t_disablingdate > edt)) t_account454, dealpart, /*PNV 508081*/
                             (case when dvndeal.t_dealtype = 'B' and dvndeal.t_dockind = 101 THEN 1 
                                   when dvndeal.t_dealtype = 'S' and dvndeal.t_dockind = 101 THEN 2
                                   else 0 end ) is_sec_dealtype,
                             totalcost
                       from(--Процентный СВОП (только валюта)
                            select bdt, edt, typ, fininstrT.t_fi_kind fi_kind,
                                   -- Сделка
                                   dvndeal.t_id, dvndeal.t_code, dvndeal.t_extcode, dvndeal.t_contractor, dvndeal.t_netting, dvndeal.t_date, dvndeal.t_dockind, 
                                   dvndeal.t_type, 'P' t_dealtype, dvndeal.t_ispfi, dvndeal.t_genagrid, dvndeal.t_periodcls, dvndeal.t_marketkind,
                                   greatest(dvnfiT.t_execdate, dvnfiT.t_paydate, dvnfiO.t_execdate, dvnfiO.t_paydate) t_execdate,
                                   -- Требования
                                   dvnfiT.t_exectype t_exectypeT,
                                   fininstrT.t_fiid t_fiidT,
                                   fininstrT.t_ccy t_ccyT, 
                                   dvnfiT.t_amount t_amountT,
                                   dvnfiT.t_price t_priceT,
                                   -- Обязательста
                                   fininstrO.t_fiid t_fiidO,
                                   fininstrO.t_ccy t_ccyO, 
                                   dvnfiO.t_amount t_amountO, 1 dealpart,  /*PNV 508081*/
                                   0 totalcost
                            from ddvndeal_dbt dvndeal 
                            join (select :bdt bdt, :edt edt, :typ typ from dual) on 1=1
                            join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvndeal.t_kind and 
                                                           regexp_like(oprkoper.t_systypes, 'P'/*Процентный СВОП*/)
                            join ddvnfi_dbt dvnfiT on dvnfiT.t_dealid = dvndeal.t_id and 
                                                      dvnfiT.t_type = 2 
                            join dfininstr_dbt fininstrT on fininstrT.t_fiid = dvnfiT.t_fiid and 
                                                            fininstrT.t_fi_kind = 1
                            join ddvnfi_dbt dvnfiO on dvnfiO.t_dealid = dvndeal.t_id and 
                                                      dvnfiO.t_type = 0
                            join dfininstr_dbt fininstrO on fininstrO.t_fiid = dvnfiO.t_fiid and 
                                                            fininstrO.t_fi_kind = 1  
                            where dvndeal.t_dockind = 199/*Внебиржевая сделка с ПИ*/ and t_client = -1 and 
                                  dvndeal.t_date <= edt and 
                                  dvndeal.t_state >= 1 and
                                  typ in (0,1)
                            union all
                            -- Форвард (любой актив за валюту)
                            select bdt, edt, typ, fininstrT.t_fi_kind fi_kind,
                                   -- Сделка
                                   dvndeal.t_id, dvndeal.t_code, dvndeal.t_extcode, dvndeal.t_contractor, dvndeal.t_netting, dvndeal.t_date, dvndeal.t_dockind, 
                                   dvndeal.t_type, 'U' t_dealtype, dvndeal.t_ispfi, dvndeal.t_genagrid, dvndeal.t_periodcls, dvndeal.t_marketkind,
                                   greatest(dvnfiT.t_execdate, dvnfiT.t_paydate) t_execdate,
                                   -- Требования
                                   dvnfiT.t_exectype t_exectypeT,
                                   case when dvndeal.t_type != 1 then fininstrO.t_fiid else fininstrT.t_fiid end t_fiidT,
                                   fininstrT.t_ccy t_ccyT, 
                                   case when dvndeal.t_type != 1 then decode(dvnfiT.t_cost, 0, dvnfiT.t_price*dvnfiT.t_amount, dvnfiT.t_cost)  else dvnfiT.t_amount end t_amountT,
                                   dvnfiT.t_price t_priceT,
                                   -- Обязательста
                                   case when dvndeal.t_type != 1 then fininstrT.t_fiid else fininstrO.t_fiid end t_fiidO,
                                   fininstrO.t_ccy t_ccyO, 
                                   case when dvndeal.t_type != 1 then dvnfiT.t_amount else decode(dvnfiT.t_cost, 0, dvnfiT.t_price*dvnfiT.t_amount, dvnfiT.t_cost)  end t_amountO, 1 dealpart,  /*PNV 508081*/
                                   0 totalcost
                            from ddvndeal_dbt dvndeal 
                            join (select :bdt bdt, :edt edt, :typ typ from dual) on 1=1
                            join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvndeal.t_kind and 
                                                           regexp_like(oprkoper.t_systypes, '[U]'/*Форвард*/)
                            join ddvnfi_dbt dvnfiT on dvnfiT.t_dealid = dvndeal.t_id and 
                                                      dvnfiT.t_type = 0 
                            join dfininstr_dbt fininstrT on fininstrT.t_fiid = dvnfiT.t_fiid and 
                                                            ((fininstrT.t_fi_kind in (1,6,7) and typ in (0,1)) or (fininstrT.t_fi_kind in (2) and typ in (0,2)))
                            join dfininstr_dbt fininstrO on fininstrO.t_fiid = dvnfiT.t_pricefiid and 
                                                            fininstrO.t_fi_kind = 1  
                            where dvndeal.t_dockind = 199/*Внебиржевая сделка с ПИ*/ and t_client = -1 and
                                  dvndeal.t_date <= edt and 
                                  dvndeal.t_state >= 1
                            union all
                            -- Опцион (любой актив за валюту)
                            select bdt, edt, typ, fininstrT.t_fi_kind fi_kind,
                                   -- Сделка
                                   dvndeal.t_id, dvndeal.t_code, dvndeal.t_extcode, dvndeal.t_contractor, dvndeal.t_netting, dvndeal.t_date, dvndeal.t_dockind, 
                                   case when (dvndeal.t_optiontype = 1 and dvndeal.t_type = 2) or (dvndeal.t_optiontype = 2 and dvndeal.t_type = 1) then 1 else 2 end t_type, 'O' t_dealtype, dvndeal.t_ispfi, dvndeal.t_genagrid, dvndeal.t_periodcls, dvndeal.t_marketkind,
                                   greatest(dvnfiT.t_execdate, dvnfiT.t_paydate) t_execdate,
                                   -- Требования
                                   dvnfiT.t_exectype t_exectypeT,
                                   case when (dvndeal.t_optiontype = 1 and dvndeal.t_type = 1) or (dvndeal.t_optiontype = 2 and dvndeal.t_type = 2) then fininstrO.t_fiid else fininstrT.t_fiid end t_fiidT,
                                   fininstrT.t_ccy t_ccyT, 
                               case when ((fininstrO.t_fi_kind = 3) or (fininstrT.t_fi_kind = 3)) then dvnfiT.t_amount --Для опционов на индекс
                                    when (dvndeal.t_optiontype = 1 and dvndeal.t_type = 1) or (dvndeal.t_optiontype = 2 and dvndeal.t_type = 2) then dvnfiT.t_cost 
                               else dvnfiT.t_amount end t_amountT,
                                   dvnfiT.t_price t_priceT,
                                   -- Обязательста
                                   case when (dvndeal.t_optiontype = 1 and dvndeal.t_type = 1) or (dvndeal.t_optiontype = 2 and dvndeal.t_type = 2) then fininstrT.t_fiid else fininstrO.t_fiid end t_fiidO,
                                   fininstrO.t_ccy t_ccyO, 
                               case when ((fininstrO.t_fi_kind = 3) or (fininstrT.t_fi_kind = 3)) then dvnfiT.t_amount --Для опционов на индекс
                                    when (dvndeal.t_optiontype = 1 and dvndeal.t_type = 1) or (dvndeal.t_optiontype = 2 and dvndeal.t_type = 2) then dvnfiT.t_amount 
                               else dvnfiT.t_cost end t_amountO,
                                   1 dealpart,  /*PNV 508081*/
                               0 totalcost
                            from ddvndeal_dbt dvndeal 
                            join (select :bdt bdt, :edt edt, :typ typ from dual) on 1=1
                            join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvndeal.t_kind and 
                                                           regexp_like(oprkoper.t_systypes, '[O]'/*Опцион*/)
                            join ddvnfi_dbt dvnfiT on dvnfiT.t_dealid = dvndeal.t_id and 
                                                      dvnfiT.t_type = 0 
                            join dfininstr_dbt fininstrT on fininstrT.t_fiid = dvnfiT.t_fiid and 
                                                            ((fininstrT.t_fi_kind in (1,6, 3, 7) and typ in (0,1)) or (fininstrT.t_fi_kind in (2) and typ in (0,2)))
                            join dfininstr_dbt fininstrO on fininstrO.t_fiid = dvnfiT.t_pricefiid and 
                                                            fininstrO.t_fi_kind = 1  
                            where dvndeal.t_dockind = 199/*Внебиржевая сделка с ПИ*/ and t_client = -1 and
                                  dvndeal.t_date <= edt and 
                                  dvndeal.t_state >= 1
                            union all
                            -- Валютный СВОП - первая нога (валюта и драгметалл)
                            select bdt, edt, typ, fininstrT.t_fi_kind fi_kind,
                                   -- Сделка
                                   dvndeal.t_id, dvndeal.t_code, dvndeal.t_extcode, dvndeal.t_contractor, dvndeal.t_netting, dvndeal.t_date, dvndeal.t_dockind, 
                                   case when dvndeal.t_type = 5 then 1 else dvndeal.t_type end t_type , 'S' t_dealtype, dvndeal.t_ispfi, dvndeal.t_genagrid, dvndeal.t_periodcls, dvndeal.t_marketkind,
                                   greatest(dvnfiT.t_execdate, dvnfiT.t_paydate) t_execdate,
                                   -- Требования
                                   dvnfiT.t_exectype t_exectypeT,
                                   case when dvndeal.t_type != 5 then fininstrO.t_fiid else fininstrT.t_fiid end t_fiidT,
                                   fininstrT.t_ccy t_ccyT, 
                                   case when dvndeal.t_type = 5 /*!= AAI*/then dvnfiT.t_amount else dvnfiT.t_cost end t_amountT,
                                   dvnfiT.t_price t_priceT,
                                   -- Обязательста
                                   case when dvndeal.t_type != 5 then fininstrT.t_fiid else fininstrO.t_fiid end t_fiidO,
                                   fininstrO.t_ccy t_ccyO, 
                                   case when dvndeal.t_type != 5 then dvnfiT.t_amount else dvnfiT.t_cost end t_amountO, 1 dealpart,  /*PNV 508081*/
                                   0 totalcost
                            from ddvndeal_dbt dvndeal 
                            join (select :bdt bdt, :edt edt, :typ typ from dual) on 1=1
                            join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvndeal.t_kind and 
                                                           regexp_like(oprkoper.t_systypes, '[H|S]'/*Валютный СВОП*/)
                            join ddvnfi_dbt dvnfiT on dvnfiT.t_dealid = dvndeal.t_id and 
                                                      dvnfiT.t_type = 0 
                            join dfininstr_dbt fininstrT on fininstrT.t_fiid = dvnfiT.t_fiid and 
                                                            fininstrT.t_fi_kind in (1,6)
                            join dfininstr_dbt fininstrO on fininstrO.t_fiid = dvnfiT.t_pricefiid and 
                                                            fininstrO.t_fi_kind = 1  
                            where dvndeal.t_dockind in (199/*Внебиржевая сделка с ПИ*/, 4813/*Конверсионная сделка ФИССиКО*/) and t_client = -1 and
                                  dvndeal.t_date <= edt and 
                                  dvndeal.t_state >= 1 and
                                  typ in (0,1)
                            union all
                            -- Валютный ПФИ - вторая нога (валюта и драгметалл)                                                    
                            select bdt, edt, typ, fininstrT.t_fi_kind fi_kind,
                                   -- Сделка
                                   dvndeal.t_id,dvndeal.t_code, dvndeal.t_extcode,  dvndeal.t_contractor, dvndeal.t_netting, dvndeal.t_date, dvndeal.t_dockind, 
                                   case when dvndeal.t_type != 5 then 1 else dvndeal.t_type end t_type, 'S' t_dealtype, dvndeal.t_ispfi, dvndeal.t_genagrid, dvndeal.t_periodcls, dvndeal.t_marketkind,
                                   greatest(dvnfiT.t_execdate, dvnfiT.t_paydate) t_execdate,
                                   -- Требования
                                   dvnfiT.t_exectype t_exectypeT,
                                   case when dvndeal.t_type = 5 then fininstrO.t_fiid else fininstrT.t_fiid end t_fiidT,
                                   fininstrT.t_ccy t_ccyT, 
                                   case when dvndeal.t_type <>/* = AAI*/ 5  then dvnfiT.t_amount else dvnfiT.t_cost end t_amountT,
                                   dvnfiT.t_price t_priceT,
                                   -- Обязательста
                                   case when dvndeal.t_type = 5 then fininstrT.t_fiid else fininstrO.t_fiid end t_fiidO,
                                   fininstrO.t_ccy t_ccyO, 
                                   case when dvndeal.t_type = 5 then dvnfiT.t_amount else dvnfiT.t_cost end t_amountO, 2 dealpart,  /*PNV 508081*/
                                   0 totalcost
                            from ddvndeal_dbt dvndeal 
                            join (select :bdt bdt, :edt edt, :typ typ from dual) on 1=1
                            join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvndeal.t_kind and 
                                                           regexp_like(oprkoper.t_systypes, '[H|S]'/*Валютный СВОП*/)
                            join ddvnfi_dbt dvnfiT on dvnfiT.t_dealid = dvndeal.t_id and 
                                                      dvnfiT.t_type = 2 
                            join dfininstr_dbt fininstrT on fininstrT.t_fiid = dvnfiT.t_fiid and 
                                                            fininstrT.t_fi_kind in (1,6)
                            join dfininstr_dbt fininstrO on fininstrO.t_fiid = dvnfiT.t_pricefiid and 
                                                            fininstrO.t_fi_kind = 1  
                            where dvndeal.t_dockind in (199/*Внебиржевая сделка с ПИ*/, 4813/*Конверсионная сделка ФИССиКО*/) and t_client = -1 and
                                  dvndeal.t_date <= edt and 
                                  dvndeal.t_state >= 1 and
                                  typ in (0,1)
                            union all
                            -- Покупка/продажа конверсионной операцией (валюта за драгметалл, драгметалл за валюту и валюта за валюту)
                            select bdt, edt, typ, fininstrT.t_fi_kind fi_kind,
                                   -- Сделка
                                   dvndeal.t_id, dvndeal.t_code, dvndeal.t_extcode, dvndeal.t_contractor, dvndeal.t_netting, dvndeal.t_date, dvndeal.t_dockind, 
                                   dvndeal.t_type, 'D' t_dealtype, dvndeal.t_ispfi, dvndeal.t_genagrid, dvndeal.t_periodcls, dvndeal.t_marketkind,
                                   greatest(dvnfiT.t_execdate, dvnfiT.t_paydate) t_execdate,
                                   -- Требования
                                   dvnfiT.t_exectype t_exectypeT,
                                   case when dvndeal.t_type != 1 then fininstrO.t_fiid else fininstrT.t_fiid end t_fiidT,
                                   fininstrT.t_ccy t_ccyT, 
                                   case when dvndeal.t_type != 1 then dvnfiT.t_cost else dvnfiT.t_amount end t_amountT,
                                   dvnfiT.t_price t_priceT,
                                   -- Обязательста
                                   case when dvndeal.t_type != 1 then fininstrT.t_fiid else fininstrO.t_fiid end t_fiidO,
                                   fininstrO.t_ccy t_ccyO, 
                                   case when dvndeal.t_type != 1 then dvnfiT.t_amount else dvnfiT.t_cost end t_amountO, 1 dealpart,  /*PNV 508081*/
                                   0 totalcost
                            from ddvndeal_dbt dvndeal 
                            join (select :bdt bdt, :edt edt, :typ typ from dual) on 1=1
                            join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvndeal.t_kind and ( regexp_like(oprkoper.t_systypes, 'D'/*Покупка/продажа*/) or regexp_like(oprkoper.t_systypes, 'C'/*банкнотная*/))
                            join ddvnfi_dbt dvnfiT on dvnfiT.t_dealid = dvndeal.t_id and 
                                                      dvnfiT.t_type = 0 
                            join dfininstr_dbt fininstrT on fininstrT.t_fiid = dvnfiT.t_fiid and 
                                                            fininstrT.t_fi_kind in (1,6)
                            join dfininstr_dbt fininstrO on fininstrO.t_fiid = dvnfiT.t_pricefiid and 
                                                            fininstrO.t_fi_kind in (1,6) and
                                                            fininstrO.t_fiid != fininstrT.t_fiid    

                            where dvndeal.t_dockind = 4813/*Конверсионная сделка ФИССиКО*/ and  t_client = -1 and
                                  dvndeal.t_date <= edt and 
                                  dvndeal.t_state >= 1 and
                                  typ in (0,1)
                            union all
                            -- Покупка/продажа сделкой Т+ (любой актив за валюту)
                            select bdt, edt, typ, fininstrT.t_fi_kind fi_kind,
                                   -- Сделка
                                   dvndeal.t_id, dvndeal.t_code, dvndeal.t_extcode, dvndeal.t_contractor, dvndeal.t_netting, dvndeal.t_date, dvndeal.t_dockind, 
                                   dvndeal.t_type, 'D' t_dealtype, dvndeal.t_ispfi, dvndeal.t_genagrid, dvndeal.t_periodcls, dvndeal.t_marketkind,
                                   greatest(dvnfiT.t_execdate, dvnfiT.t_paydate) t_execdate,
                                   -- Требования
                                   dvnfiT.t_exectype t_exectypeT,
                                   case when dvndeal.t_type != 1 then fininstrO.t_fiid else fininstrT.t_fiid end t_fiidT,
                                   fininstrT.t_ccy t_ccyT, 
                                   case when dvndeal.t_type != 1 then dvnfiT.t_cost else dvnfiT.t_amount end t_amountT,
                                   dvnfiT.t_price t_priceT,
                                   -- Обязательста
                                   case when dvndeal.t_type != 1 then fininstrT.t_fiid else fininstrO.t_fiid end t_fiidO,
                                   fininstrO.t_ccy t_ccyO, 
                                   case when dvndeal.t_type != 1 then dvnfiT.t_amount else dvnfiT.t_cost end t_amountO, 1 dealpart,  /*PNV 508081*/
                                   0 totalcost
                            from ddvndeal_dbt dvndeal 
                            join (select :bdt bdt, :edt edt, :typ typ from dual) on 1=1
                        /*    join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvndeal.t_kind and 
                                                           regexp_like(oprkoper.t_systypes, 'D')*/
                            join ddvnfi_dbt dvnfiT on dvnfiT.t_dealid = dvndeal.t_id and 
                                                      dvnfiT.t_type = 0 
                            join dfininstr_dbt fininstrT on fininstrT.t_fiid = dvnfiT.t_fiid and 
                                                            ((fininstrT.t_fi_kind in (1,6) and typ in (0,1)) or (fininstrT.t_fi_kind in (2) and typ in (0,2)))
                            join dfininstr_dbt fininstrO on fininstrO.t_fiid = dvnfiT.t_pricefiid and 
                                                            fininstrO.t_fi_kind = 1  
                            where dvndeal.t_dockind = 4815/*Сделка Т+3*/ and t_client = -1 and
                                  dvndeal.t_date <= edt and 
                                  dvndeal.t_state >= 1
                            union all
                            -- Сделки покупки/продажи БОЦБ
                            select bdt, edt, typ, 2 fi_kind,
                                   -- Сделка
                                   dl_tick.t_dealid t_id,
                                   dl_tick.t_dealcode t_code,
                                   dl_tick.t_dealcodets t_extcode,
                                   dl_tick.t_partyid t_contractor,
                                   case when dl_tick.t_netting = 0 then chr(0) else chr(88) end t_netting,
                                   dl_tick.t_dealdate t_date,
                                   dl_tick.t_bofficekind t_dockind, 
                                   case when deal.t_dealtype = 'B' then 1 else 2 end t_type,
                                   deal.t_dealtype,
                                   chr(0) t_ispfi,
                                   -1 t_genagrid,
                                   0 t_periodcls,
                                   deal.t_marketkind,
                                   deal.t_execdate,
                                   -- Требования
                                   1 t_exectypeT,
                                   case when deal.t_dealtype = 'B' then dl_leg.t_pfi else dl_leg.t_cfi end t_fiidT,
                                   chr(0) t_ccyT, 
                                   case when deal.t_dealtype = 'B' then dl_leg.t_principal else dl_leg.t_totalcost end t_amountT,
                                   0 t_priceT,
                                   -- Обязательста
                                   case when deal.t_dealtype = 'S' then dl_leg.t_pfi else dl_leg.t_cfi end t_fiidO,
                                   chr(0) t_ccyO, 
                                   case when deal.t_dealtype = 'S' then dl_leg.t_principal else dl_leg.t_totalcost end t_amountO, 1 dealpart, /*PNV 508081*/
                                   dl_leg.t_totalcost totalcost
                            from (select bdt, edt, typ, 
                                         dl_tick.t_dealid, 
                                         rsb_brkrep_u.GetExecDateWOCalendar(dl_tick.t_bofficekind, dl_tick.t_dealid, 1) t_execdate,
                                         case when regexp_like(oprkoper.t_systypes, 'B') then 'B' else 'S' end t_dealtype,
                                         case when regexp_like(oprkoper.t_systypes, 'X') then 1 else 0 end t_marketkind
                                  from ddl_tick_dbt dl_tick
                                  join (select :bdt bdt, :edt edt, :typ typ from dual) on 1=1
                                  join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dl_tick.t_dealtype and regexp_like(oprkoper.t_systypes, '[B|S]'/*Покупка/Продажа*/)
                                  where dl_tick.t_bofficekind = 101 and
                                        dl_tick.t_clientid = -1 and
                                        dl_tick.t_dealdate <= edt and
                                        dl_tick.t_originid != ascii('Ю') and
                                        typ in (0,2)) deal
                            join ddl_tick_dbt dl_tick on dl_tick.t_dealid = deal.t_dealid
                            join ddl_leg_dbt dl_leg on dl_leg.t_dealid = deal.t_dealid
                            where deal.t_execdate > edt) dvndeal
                       join dfininstr_dbt fininstrT on fininstrT.t_fiid = dvndeal.t_fiidT  
                       join dfininstr_dbt fininstrO on fininstrO.t_fiid = dvndeal.t_fiidO  
                       left join dparty_dbt contragent on contragent.t_partyid = dvndeal.t_contractor
                       left join ddl_genagr_dbt dl_genagr on dvndeal.fi_kind != 2 and 
                                                             dl_genagr.t_genagrid = dvndeal.t_genagrid
                       where dvndeal.t_execdate > edt ) tmp ))
      order by fi_kind, t_dealtype, t_code
    ];
    m_cmd = RsdCommand(EndCaptureOutput());
    m_cmd.AddParam("bdt", RSDBP_IN, m_BeginDate);
    m_cmd.AddParam("edt", RSDBP_IN, m_EndDate);
    if(m_Form.GetFieldValue(PNFLD_CURRENCY) == "X")
      if(m_Form.GetFieldValue(PNFLD_SECURITY) == "X")
        m_cmd.AddParam("typ", RSDBP_IN, 0);
      else
        m_cmd.AddParam("typ", RSDBP_IN, 1);
      end;
    else
      m_cmd.AddParam("typ", RSDBP_IN, 2);
    end;

    m_cmd.Execute();
    m_RS = TRsbDataSet(m_cmd);
    cnt = 0;
    var Account, RestAccount;
    while(m_RS.movenext)
      if(cnt == 0)
        InitProgress(int(m_RS.value("t_cnt")), "Ждите...", "Формирование таблицы \"ОД_4\"");
      end;
      cnt = cnt + 1;
      /*Счет ПФИ*/
      if((m_RS.value("t_account453") != "") and (m_RS.value("t_restaccount453") != 0))
        Account = m_RS.value("t_account453");
        RestAccount = m_RS.value("t_restaccount453");
      elif((m_RS.value("t_account454") != "") and (m_RS.value("t_restaccount454") != 0))
        Account = m_RS.value("t_account454");
        RestAccount = m_RS.value("t_restaccount454");
      else
        Account = null;
        RestAccount = null;
      end;
     /*PNV 508081*/
      if ( (m_RS.value("dealpart") == 1) and (index(m_RS.value("t_extcode"), "SWP") > 0) )
          RestAccount = null;
      end;
    /*PNV 508081*/

      var restO = m_RS.value("t_amountORUR");
      var restT = m_RS.value("t_amountTRUR");

      if (m_RS.value("is_sec_dealtype") > 0)
        if ( m_RS.value("is_need_rest_g_o") > 0 )
          restO = m_RS.value("totalcost") + GetSumTrnOverFromDocs (m_RS.value("t_id"), 101, m_EndDate, IIF((m_RS.value("is_sec_dealtype") == 1), false, true));
          if ( m_RS.value("t_accountOfiid") != 0 )
            convsum(restO, restO, m_EndDate, m_RS.value("t_accountOfiid"), 0);
          end;
        end;
        if ( m_RS.value("is_need_rest_g_t") > 0 )
          restT = m_RS.value("totalcost") + GetSumTrnOverFromDocs (m_RS.value("t_id"), 101, m_EndDate, IIF((m_RS.value("is_sec_dealtype") == 1), true, false));
          if ( m_RS.value("t_accountTfiid") != 0 )
            convsum(restT, restT, m_EndDate, m_RS.value("t_accountTfiid"), 0);
          end;
        end;
      end;
      /*Выводим строку отчета*/
      PrintTableLine(
            /* 1*/ "row1_1", m_RS.value("t_extcode"), null, 
            /* 2*/ "row1_2", m_RS.value("t_code"), null, 
            /* 3*/ "row1_3", m_RS.value("t_contragentname"), null, 
            /* 4*/ "row1_4", m_RS.value("t_dealkind"), null, 
            /* 5*/ "row1_5", m_RS.value("t_dealtype"), null, 
            /* 6*/ "row1_6", m_RS.value("t_exectype"), null, 
            /* 7*/ "row1_7", DDpMMpYYYY(date(m_RS.value("t_dealdate"))), null, 
            /* 8*/ "row1_8", DDpMMpYYYY(date(m_RS.value("t_execdate"))), null, 
            /* 9*/ "row1_9", m_RS.value("t_rate"), 4, 
            /*10*/ "row1_10", AccountMask(m_RS.value("t_accountT")), null, 
            /*11*/ "row1_11", AccountBal(m_RS.value("t_accountT")), null, 
            /*12*/ "row1_12", m_RS.value("t_ficodeT"), null, 
            /*13*/ "row1_13", m_RS.value("t_definition"), null, 
            /*14*/ "row1_14", m_RS.value("t_amountT"), 2, 
            /*15*/ "row1_15", restT, 2, 
            /*16*/ "row1_16", m_RS.value("t_ratefiidT"), 4, 
            /*17*/ "row1_17", "-", null, 
            /*18*/ "row1_18", "", null, 
            /*19*/ "row1_19", AccountMask(m_RS.value("t_accountO")), null, 
            /*20*/ "row1_20", AccountBal(m_RS.value("t_accountO")), null, 
            /*21*/ "row1_21", m_RS.value("t_ficodeO"), null, 
            /*22*/ "row1_22", m_RS.value("t_amountO"), 2, 
            /*23*/ "row1_23", restO, 2, 
            /*24*/ "row1_24", "-", null, 
            /*25*/ "row1_25", m_RS.value("t_ratefiidO"), 4, 
            /*26*/ "row1_26", "", null, 
            /*27*/ "row1_27", AccountMask(Account), null, 
            /*28*/ "row1_28", AccountBal(Account), null, //AccountCur(Account), null, 
            /*29*/ "row1_29", RestAccount, 2, 
            /*30*/ "row1_30", "", null, 
            /*31*/ "row1_31", "", null, 
            /*32*/ "row1_32", "", null, 
            /*33*/ "row1_33", m_RS.value("t_isresident"), null, 
            /*34*/ "row1_34", "", null, 
            /*35*/ "row1_35", "", null, 
            /*36*/ "row1_36", "", null, 
            /*37*/ "row1_37", "", null, 
            /*38*/ "row1_38", m_RS.value("t_isnetting"), null, 
            /*39*/ "row1_39", "", null, 
            /*40*/ "row1_40", m_RS.value("t_genagr"), null);
      /*Процентые периоды для процентных свопов*/
      if((m_RS.value("t_dealtype") == "ПРОЦЕНТНЫЙ СВОП") or (m_RS.value("t_dealtype") == "ВАЛЮТНО-ПРОЦЕНТНЫЙ СВОП"))
        m_cmd_perc = RsdCommand(m_que_perc);
        m_cmd_perc.AddParam("dialid", RSDBP_IN, m_RS.value("t_id"));
        m_cmd_perc.AddParam("bdt", RSDBP_IN, m_BeginDate);
        m_cmd_perc.AddParam("edt", RSDBP_IN, m_EndDate);
        m_cmd_perc.Execute();
        m_RS_perc = TRsbDataSet(m_cmd_perc);
        while(m_RS_perc.movenext)
          /*Выводим строку отчета*/
          PrintTableLine(
                /* 1*/ "row1_1", m_RS.value("t_extcode"), null, 
                /* 2*/ "row1_2", m_RS.value("t_code"), null, 
                /* 3*/ "row1_3", m_RS.value("t_contragentname"), null, 
                /* 4*/ "row1_4", "-", null, 
                /* 5*/ "row1_5", m_RS_perc.value("t_type"), null, 
                /* 6*/ "row1_6", "-", null, 
                /* 7*/ "row1_7", "-", null, 
                /* 8*/ "row1_8", "-", null, 
                /* 9*/ "row1_9", "-", null, 
                /*10*/ "row1_10", m_RS_perc.value("t_demandaccount"), null, 
                /*11*/ "row1_11", AccountBal(m_RS_perc.value("t_demandaccount")), null, 
                /*12*/ "row1_12", AccountCur(m_RS_perc.value("t_demandaccount")), null, 
                /*13*/ "row1_13", "-", null, 
                /*14*/ "row1_14", m_RS_perc.value("t_demandsum"), null, 
                /*15*/ "row1_15", m_RS_perc.value("t_demandsumRUR"), null, 
                /*16*/ "row1_16", m_RS_perc.value("t_demandrate"), null, 
                /*17*/ "row1_17", "-", null, 
                /*18*/ "row1_18", "-", null, 
                /*19*/ "row1_19", m_RS_perc.value("t_liabilityaccount"), null, 
                /*20*/ "row1_20", AccountBal(m_RS_perc.value("t_liabilityaccount")), null, 
                /*21*/ "row1_21", AccountCur(m_RS_perc.value("t_liabilityaccount")), null, 
                /*22*/ "row1_22", m_RS_perc.value("t_liabilitysum"), null, 
                /*23*/ "row1_23", m_RS_perc.value("t_liabilitysumRUR"), null, 
                /*24*/ "row1_24", "-", null, 
                /*25*/ "row1_25", m_RS_perc.value("t_liabilityrate"), null, 
                /*26*/ "row1_26", "-", null, 
                /*27*/ "row1_27", "", null, 
                /*28*/ "row1_28", "-", null, 
                /*29*/ "row1_29", "-", 2, 
                /*30*/ "row1_30", "", null, 
                /*31*/ "row1_31", "", null, 
                /*32*/ "row1_32", "", null, 
                /*33*/ "row1_33", m_RS.value("t_isresident"), null, 
                /*34*/ "row1_34", "", null, 
                /*35*/ "row1_35", "", null, 
                /*36*/ "row1_36", "", null, 
                /*37*/ "row1_37", "", null, 
                /*38*/ "row1_38", m_RS.value("t_isnetting"), null, 
                /*39*/ "row1_39", "", null, 
                /*40*/ "row1_40", m_RS.value("t_genagr"), null);
        end;
      end;
      UseProgress(cnt);
    end;
    if(cnt > 0)
      RemProgress();
    end;
    /*Для ценных бумаг кусок по срочному рынку*/
    if(m_Form.GetFieldValue(PNFLD_SECURITY) == "X")
      StartCaptureOutput();
      [
        select dvdeal.t_fiid, 
               dvdeal.t_name, 
               dvdeal.t_date, 
               dvdeal.t_drawingdate,
               dvdeal.t_accountS1, 
               abs(case when dvdeal.t_parentfi = 0 then rsb_account.restall(t_accountS1, 4, dvdeal.t_parentfi, edt) 
                        else round(rsi_rsb_fiinstr.convsum(rsb_account.restall(t_accountS1, 4, dvdeal.t_parentfi, edt),dvdeal.t_parentfi,0,edt),2) 
                   end) t_restaccountS1, 
               dvdeal.t_accountS2, 
               abs(case when dvdeal.t_parentfi = 0 then rsb_account.restall(t_accountS2, 4, dvdeal.t_parentfi, edt) 
                        else round(rsi_rsb_fiinstr.convsum(rsb_account.restall(t_accountS2, 4, dvdeal.t_parentfi, edt),dvdeal.t_parentfi,0,edt),2) 
                   end) t_restaccountS2, 
               parentfininstr.t_ccy t_fi_code, 
               dvdeal.t_facename,
               dvdeal.t_amount
        from (select edt, 
                     dvdeal.t_parentfi, 
                     dvdeal.t_accountS1, 
                     dvdeal.t_accountS2,
                     dvdeal.t_date t_date, 
                     dvdeal.t_name t_name, 
                     dvdeal.t_fiid t_fiid, 
                     dvdeal.t_drawingdate t_drawingdate, 
                     case when dvdeal.t_facename is null then chr(1) 
                          else 'Контракт на '||dvdeal.t_facename 
                     end t_facename, 
                     sum(case when dvdeal.t_type = 'S' then dvdeal.t_amount 
                              else -dvdeal.t_amount 
                         end) t_amount
              from (select edt, 
                           fininstr.t_parentfi t_parentfi, 
                           dvdeal.t_code, 
                           oprkoper.t_dockind t_dockind, 
                           dvdeal.t_type t_type, 
                           dvdeal.t_date t_date, 
                           dvdeal.t_fiid t_fiid, 
                           fininstr.t_name t_name, 
                           fininstr.t_drawingdate t_drawingdate, 
                           fininstrface.t_name t_facename, 
                           dvdeal.t_amount,
                           (select nvl(max(mcaccdoc.t_account),chr(0)) 
                            from dmcaccdoc_dbt mcaccdoc
                            where mcaccdoc.t_dockind = oprkoper.t_dockind and
                                  mcaccdoc.t_docid = dvdeal.t_id and
                                  mcaccdoc.t_catnum in (5053/*+Форвард, дрейф1*/) and
                                  mcaccdoc.t_currency = fininstr.t_parentfi  and
                                  mcaccdoc.t_chapter = 4 and
                                  mcaccdoc.t_activatedate <= edt and
                                  (mcaccdoc.t_disablingdate = to_date('01.01.0001','dd.mm.yyyy') or mcaccdoc.t_disablingdate > edt)) t_accountS1,
                           (select nvl(max(mcaccdoc.t_account),chr(0)) 
                            from dmcaccdoc_dbt mcaccdoc
                            where mcaccdoc.t_dockind = oprkoper.t_dockind and
                                  mcaccdoc.t_docid = dvdeal.t_id and
                                  mcaccdoc.t_catnum in (5054/*-Форвард, дрейф1*/) and
                                  mcaccdoc.t_currency = fininstr.t_parentfi  and
                                  mcaccdoc.t_chapter = 4 and
                                  mcaccdoc.t_activatedate <= edt and
                                  (mcaccdoc.t_disablingdate = to_date('01.01.0001','dd.mm.yyyy') or mcaccdoc.t_disablingdate > edt)) t_accountS2
                    from ddvdeal_dbt dvdeal
                    join (select :bdt bdt, :edt edt from dual) on 1=1
                    join dfininstr_dbt fininstr on fininstr.t_fiid = dvdeal.t_fiid and 
                                                   fininstr.t_drawingdate > edt  
                    left join dfininstr_dbt fininstrface on fininstrface.t_fiid = fininstr.t_facevaluefi 
                    join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvdeal.t_kind
              where dvdeal.t_date between bdt and edt and
                    dvdeal.t_clientcontr = 0 and
                    dvdeal.t_type in ('S','B')) dvdeal
              group by edt, dvdeal.t_parentfi, dvdeal.t_accountS1, dvdeal.t_accountS2, dvdeal.t_date, dvdeal.t_fiid, dvdeal.t_name, dvdeal.t_drawingdate, dvdeal.t_facename) dvdeal
        join dfininstr_dbt parentfininstr on parentfininstr.t_fiid = dvdeal.t_parentfi
        order by dvdeal.t_fiid, dvdeal.t_date
      ];
      m_cmd = RsdCommand(EndCaptureOutput());
      m_cmd.AddParam("bdt", RSDBP_IN, m_BeginDate);
      m_cmd.AddParam("edt", RSDBP_IN, m_EndDate);
      m_cmd.Execute();
      m_RS = TRsbDataSet(m_cmd);
      var ma1 = tarray(), ma2 = tarray(), md = tarray(), ar1 = 0, ar2 = 0, am = 0;
      var lastfiid = null, i;
      var iname, idrawingdate, ifi_code, ifacename, pos_interest;
      while(m_RS.movenext)
        if(lastfiid == null)
          lastfiid = m_RS.value("t_fiid");
          iname = m_RS.value("t_name");
          idrawingdate = m_RS.value("t_drawingdate");
          ifi_code = m_RS.value("t_fi_code");
          ifacename = m_RS.value("t_facename");
        elif(lastfiid != m_RS.value("t_fiid"))
          if(am != 0)
            pos_interest = Get_position_interest(lastfiid, m_EndDate);
            InsSR(iname, md, idrawingdate, ma1, ma2, ifi_code, ifacename, ar1, ar2, pos_interest); //Simanov. По ПФИ нужно не движение за месяц, а итоги на конец отчётного периода
          end;
          ma1 = tarray();
          ma2 = tarray();
          md = tarray();
          ar1 = 0;
          ar2 = 0;
          am = 0;
          lastfiid = m_RS.value("t_fiid");
          iname = m_RS.value("t_name");
          idrawingdate = m_RS.value("t_drawingdate");
          ifi_code = m_RS.value("t_fi_code");
          ifacename = m_RS.value("t_facename");
        end;
        if(m_RS.value("t_restaccountS1") > 0)
          i = 0;
          while(i < ma1.size)
            if(ma1[i] == m_RS.value("t_accountS1"))
              break;
            end;
            i = i + 1;
          end;
          if(i == ma1.size)
            ma1[ma1.size] = m_RS.value("t_accountS1");
            ar1 = ar1 + m_RS.value("t_restaccountS1");
          end;
        end;
        if(m_RS.value("t_restaccountS2") > 0)
          i = 0;
          while(i < ma2.size)
            if(ma2[i] == m_RS.value("t_accountS2"))
              break;
            end;
            i = i + 1;
          end;
          if(i == ma2.size)
            ma2[ma2.size] = m_RS.value("t_accountS2");
            ar2 = ar2 + m_RS.value("t_restaccountS2");
          end;
        end;
        i = 0;
        while(i < md.size)
          if(md[i] == date(m_RS.value("t_date")))
            break;
          end;
          i = i + 1;
        end;
        if(i == md.size)
          md[md.size] = date(m_RS.value("t_date"));
        end;
        am = am + m_RS.value("t_amount");
      end;
      if((lastfiid != null) and (am != 0))
        pos_interest = Get_position_interest(lastfiid, m_EndDate);
        InsSR(iname, md, idrawingdate, ma1, ma2, ifi_code, ifacename, ar1, ar2, pos_interest); //Simanov. По ПФИ нужно не движение за месяц, а итоги на конец отчётного периода
      end;
    end;
    EndTable();
  END;
  
  initTX_RegistrReport(od04_Panel(), "od04.xlsx", true, null, null, true, true);

END;

/*Точка входа*/
var r = od04_Report();
r.InitReport("ОД04", null);
r.Run();

exit(1);
