import RSD, globals;
import BankInter, dlquery, cb_sql, oralib, likepy;

const K_ENTER   = 13;
//const K_ESC     = 27;
const K_F3      = 317;
const K_F2      = 316;
const K_F8      = 322;
const K_F9      = 323;


PRIVATE MACRO AddCol (ar, fld, head, width, rdonly, ty, dp)
   var ind = ar.size;
   if (ind > 0) ind = ar.size / 6 ; end;
   ar.value (ind * 6)     = fld;
   ar.value (ind * 6 + 1) = head;
   ar.value (ind * 6 + 2) = width;
   ar.value (ind * 6 + 3 ) = 2;//rdonly;   // fldType
   ar.value (ind * 6 + 4 ) = dp;//   decPoint
   ar.value (ind * 6 + 5 ) = 0;   // reserv
END;

macro Scroll
   var sql, cmd1, rs1, col1, need = true,Column = TArray(),i, ColumnValue, ColumnName, NumColumns = 0, cond = "";

   var ErrAr = TArray(), inprocess, inprocessprogress, SaveNum = 0;

   macro EvProc(rs, cmd, id, key)
     var  CM_DEFAULT = null, err;
     
//msgbox(key);
      if (cmd == DLG_INIT)
      elif(cmd == DLG_MSELSTART)
      elif(cmd == DLG_MSELEND)
      elif(cmd == DLG_MSEL)
      elif ((cmd == DLG_KEY)and(key == K_F8)/* and ({oper} == 1)*/)
         return CM_IGNORE;
      elif ((cmd == DLG_KEY)and(key == 18))
      elif ((cmd == DLG_KEY)and(key == K_ESC))
         return 2;
      end;

     return CM_DEFAULT;
   end;

   col1 = TArray;   

 //  AddCol (col1, "kind",        "Вид",   4 ,  2, -1);
   AddCol (col1, "T_account",        "Счет",   18 ,  2, -1);
   AddCol (col1,  "T_ccy",        "Валюта",    10,  2, -1 );
   AddCol (col1,  "T_open_date",  "Дата открытия счета",    8,  2, -1);
   AddCol (col1,  "T_number",     " Номер договора",    15, 2, -1);
//   AddCol (col1,  "T_dateclose",  "Дата закрытия договора",    8,  2, -1);
   AddCol (col1,  "T_nameaccount",     "Наименование счета ",    25, -1);
   AddCol (col1,  "T_name",     " Клиент ",    25, -1);
   AddCol (col1, "rest",        "Остаток",   18 ,  2, 2);
   while (need)
      need = false;
      sql = 
   "select rownum,t.*, RSB_ACCOUNT.RESTALL(t.t_account, t.t_chapter, t.t_code_currency, trunc(sysdate)) rest  from ( " +
   "SELECT   " +
   "       a.t_open_close, " +
   "       a.t_close_date, " +
   "       a.t_open_date, " +
   "       a.t_nameaccount, " +
   "       (select t_ccy from dfininstr_dbt where t_fiid = a.t_code_currency) t_ccy, " +
   "       a.t_code_currency, " +
   "       sf.t_number, " +
   "       sf.t_dateclose, " +
   "       sf.t_name, " +
   "       s.t_account, " +
   "       s.t_chapter, " +
   "       decode(s.t_chapter,1,'БУ',21,'ВУ ДС',22,'ВУ ЦБ') kind " +
   "  FROM dsettacc_dbt s, " +
   "       dsfssi_dbt ss, " +
   "       dsfcontr_dbt sf, " +
   "       daccount_dbt a " +
   " WHERE     s.t_settaccid = ss.t_setaccid " +
   "       AND ss.t_objecttype = 659 " +
   "       AND ss.t_objectid = sf.t_id " +
   "       AND sf.t_dateclose = TO_DATE ('01010001', 'ddmmyyyy') " +
   "       AND a.t_account = s.t_account " +
   "       AND a.t_chapter = s.t_chapter " +
/*   "union all " +
   "SELECT a.t_open_close,        " +
   "       a.t_close_date, " +
   "       (select decode(t_ccy,chr(1),t_definition, t_ccy) t_ccy from dfininstr_dbt where t_fiid = a.t_code_currency) t_ccy, " +
   "       a.t_code_currency, " +
   "       sf.t_number, " +
   "       sf.t_dateclose, " +
   "       sf.t_name, " +
   "       mc.t_account, " +
   "       mc.t_chapter, " +
   "       decode(a.t_chapter,1,'БУ',21,'ВУ ДС',22,'ВУ ЦБ') kind " +
   "  FROM dmcaccdoc_dbt mc, dsfcontr_dbt sf, daccount_dbt a " +
   " WHERE    " 
   "           mc.t_chapter in (21,22) " +
   "       AND mc.t_iscommon = CHR (88) " +
   "       AND sf.t_id = mc.t_clientcontrid " +
   "       AND a.t_account = mc.t_account " +
   "       AND a.t_chapter = mc.t_chapter " +
   "       AND sf.t_dateclose <> TO_DATE ('01010001', 'ddmmyyyy') " +
   "       AND INSTR (a.t_open_close, 'З') = 0 " +
 */  "union all " +
   "SELECT a.t_open_close,        " +
   "       a.t_close_date, " +
   "       a.t_open_date, " +
   "       a.t_nameaccount, " +
   "       (select t_ccy from dfininstr_dbt where t_fiid = a.t_code_currency) t_ccy, " +
   "       a.t_code_currency, " +
   "       sf.t_number, " +
   "       sf.t_dateclose, " +
   "       sf.t_name, " +
   "       mc.t_account, " +
   "       mc.t_chapter, " +
   "       decode(a.t_chapter,1,'БУ',21,'ВУ ДС',22,'ВУ ЦБ') kind " +
   "  FROM dmcaccdoc_dbt mc, dsfcontr_dbt sf, daccount_dbt a " +
   " WHERE     " 
   " t_catnum = 5087 " +
   "       AND mc.t_iscommon = CHR (88) " +
   "       AND sf.t_id = mc.t_clientcontrid " +
   "       AND a.t_account = mc.t_account " +
   "       AND a.t_chapter = mc.t_chapter "  +
   "       AND sf.t_dateclose = TO_DATE ('01010001', 'ddmmyyyy') " +
   "      ) t";
/*   if ({oper} != 1)
      sql = sql + " where t.t_chapter in (1) "
   end;*/
   var d = {curdate};
   if (GetDate(d, "Укажите дату открытия счетов. \n Нажмите Esc, чтобы посмотреть все счета"))
      sql = sql + " where t.t_open_date = " + GetSqlDate(d);
   end;
   sql = sql + "        order by t.t_open_date" ;

 
      cmd1 = RSDCommand(sql);
      rs1 = RSDRecordset(cmd1 , null, RSDVAL_STATIC );
      while (RunScroll (rs1,col1.size/6, col1, "test" ,"EvProc"," Открытые счета "," ", true, 1, 1))
        cmd1 = RSDCommand(sql);
        rs1 = RSDRecordset(cmd1 , null, RSDVAL_STATIC );
      end;
   end;

return null;

end;

Scroll;
exit(1);