IMPORT /*Global, RsbFormsInter, "cb_sql.mac", PTInter, "dlquery.mac", rsd,*/ CTInter;

const K_Enter = 13;
  const K_F9    = 323;
  const K_F3    = 317;
  const K_F2    = 316;
  const K_Alt_F3= 362;

private macro L_Z( num, len )
    var str1, len1;
    str1 = trim( string( num ) );
    len1 = strlen( str1 );
    if ( len1 >= len ) return str1;
    else  return  mkstr("0", len-len1 ) + str1;
    end;
end;

macro AD_Scroll( Select:STRING, Header:STRING, X:INTEGER, Y:INTEGER /*...*/):RsdRecordset

    var  rs     = RsdRecordset( Select, null, RSDVAL_STATIC ),
        Column = TArray(),
        i, ColumnValue, ColumnName, ColumnWidth, NumColumns = 0;

    macro EvProc( rs, cmd, id, key )
      if( (cmd == DLG_KEY) and (key == K_ENTER) )
         return CM_SELECT;
      end;
      return CM_DEFAULT;
    end;
    
    /* атрибуты полей */
    macro AddColumn( ar,ind, fld, head, Width )
       ar.value( ind * 6 + 0 ) = fld;  // fieldName
       ar.value( ind * 6 + 1 ) = head; // header 
       ar.value( ind * 6 + 2 ) = Width; // width
       ar.value( ind * 6 + 3 ) = 2;    // fldType (2 = FBT)
       ar.value( ind * 6 + 4 ) = null; // decPoint
       ar.value( ind * 6 + 5 ) = 0;    // reserv
       NumColumns = NumColumns + 1;
    end;
   
    i = 4;
    while( GetParm(i, ColumnValue ) AND GetParm(i+1, ColumnName) AND GetParm(i+2, ColumnWidth) )              
       AddColumn( Column, NumColumns, ColumnValue, ColumnName, ColumnWidth );
       i = i + 3;
    end;   

    if( rs.moveNext() )
      if( RunScroll( rs, NumColumns, Column, null, @EvProc, Header, "Esc Выход F4 Поиск Enter Выбор", true, X, Y, null, 25 ) )
         return rs;
      end;
    end;

    return null;
  END;

CLASS (tRsbPanel) pnl_ConfirmTransport (_DealID)
  private const FT_STRING = 7;

  
  var TransportKind, DataSource, DealTransportKind;
  var bofficekind;
   var NumKind:integer;
  var size_x, position_x;
  var size_y, position_y;

  var dealid = _dealid;  

  macro GetTransport(DealID, TransportKind:@String,DataSource:@string, DealTransportKind:@string)
   
    TransportKind = "";
    DataSource    = "";
    var sql, cmd, rs;
  
   SQL = "SELECT T.T_CONFTPID,t.t_bofficekind, " +
          "       CASE WHEN w.t_name IS NULL THEN 'Не задано' ELSE w.t_name END " +
          "          t_Kind " +
          "  FROM ddl_tick_dbt t LEFT JOIN DWLTRANSP_DBT w ON w.t_tpid = T.T_CONFTPID " +
          " WHERE T.T_DEALID = :dp1  " ;
    cmd = RSDCommand(sql);       
    cmd.addparam("", rsdbp_in,  DealID);
    rs = rsdrecordset(cmd, rsdval_client, rsdval_static);
    if (rs.movenext)
      DealTransportKind = rs.value("t_Kind");
      bofficekind = rs.value("t_bofficekind")
    end;

   sql = "SELECT ATR.T_NAME "+
           "FROM dobjatcor_dbt ac, dobjattr_dbt atr "+
           "  WHERE     AC.T_OBJECTTYPE = ATR.T_OBJECTTYPE "+
           "  AND AC.T_GROUPID = ATR.T_GROUPID "+
           "  AND AC.T_ATTRID = ATR.T_ATTRID "+
           "  and AC.T_GROUPID = 201 "+
           "  and AC.T_OBJECTTYPE = 101 and ac.T_OBJECT = ?";
    cmd = RSDCommand(sql);       
    cmd.addparam("", rsdbp_in, L_Z( DealID, 34 ));
    rs = rsdrecordset(cmd, rsdval_client, rsdval_static);
    if (rs.movenext)
      TransportKind = rs.value("t_name");
      DataSource    = "Данные получены из значения категории на сделке";
      return 1;
    end;

    SQL = "SELECT t.t_dealid, " +
      "       T.T_GENAGRID, " +
      "       T_CONFIRMMETHOD, " +
      "       DW.T_NAME " +
      "  FROM ddl_tick_dbt t " +
      "       LEFT JOIN ddl_genagr_dbt ga " +
      "          ON T.T_GENAGRID = GA.T_GENAGRID " +
      "       LEFT JOIN DWLTRANSP_DBT dw " +
      "          ON T_CONFIRMMETHOD = DW.T_TPID " +
      " WHERE T_CONFIRMMETHOD > 0 and t.t_dealid = ?; " ;
    cmd = RSDCommand(sql);       
    cmd.addparam("", rsdbp_in,  DealID);
    rs = rsdrecordset(cmd, rsdval_client, rsdval_static);
    if (rs.movenext)
      TransportKind = rs.value("t_name");
      DataSource    = "Данные получены из ген.соглашения по сделке";
      return 1;
    end;
   return 0;
  end;

  InitTRSBPanel();
  Caption = "Транспорт подтверждения.";
  Status  = "~ESC~Выход  ~F9~Выполнить  ~F3~Выбор ";
    size_x     = 50 ;
    size_y     = 7 ; 
    position_x = 30 ;
    position_y = 10 ;
  if (not GetTransport(DealID, @TransportKind, @DataSource, @DealTransportKind))
     size_y     = 5 ;   
  end;
  setSize(size_x,size_y);
  SetPosition(position_x,position_y);
  var lbl_ConfirmKind, pConfirmKind;
  var lbl_DataSource,  pDataSource;
  var lbl_DealConfirmKind,pDealConfirmKind, lbl_Separator;
  var curstr = 0;
  var cmd_upd;

   curstr = curstr + 1;
    lbl_DealConfirmKind = TRSBLabel(2, curstr,"Вид транспорта для подтверждения в сделке:");
      addlabel (lbl_DealConfirmKind);
  
    pDealConfirmKind = TRSBEditField (FT_String);
    pDealConfirmKind.setPosition(40,curstr);
    pDealConfirmKind.setSize(8,1);
    pDealConfirmKind.name = "pDealConfirmKind";
    pDealConfirmKind.textLength = 12; 
    pDealConfirmKind.editable = false; 
    pDealConfirmKind.focusable = false; 
    pDealConfirmKind.value = DealTransportKind;
     addControl(pDealConfirmKind);
   curstr = curstr + 1;
   lbl_Separator = TRSBLabel(2, curstr,"------------------------------------------------------------------");
      addlabel (lbl_Separator);
    
   curstr = curstr + 1;
    lbl_ConfirmKind = TRSBLabel(2, curstr,"Вид транспорта для подтверждения в параметрах сделки:");
      addlabel (lbl_ConfirmKind);
  
    pConfirmKind = TRSBEditField (FT_String);
    pConfirmKind.setPosition(40,curstr);
    pConfirmKind.setSize(8,1);
    pConfirmKind.name = "pConfirmKind";
    pConfirmKind.textLength = 12; 
   // pConfirmKind.editabled = false; 
    pConfirmKind.value = TransportKind;
    pConfirmKind.focusable = false; 
     addControl(pConfirmKind);
 
    addEventHandler (RSB_EV_Key_Pressed, R2M(this,"on_KeyPressed"));
    if (TransportKind != "")
   /*   curstr = curstr + 1;
      lbl_DataSource = TRSBLabel(2, curstr,"Источник данных по виду транспорта:");
        addlabel (lbl_DataSource);*/
      curstr = curstr + 1;
      pDataSource = TRSBEditField (FT_String);
      pDataSource.setPosition(2,curstr);
      pDataSource.setSize(46,2);
      pDataSource.name = "pDataSource";
      pDataSource.textLength = 68;  
      pDataSource.enabled = false;
      pDataSource.value = DataSource;
       addControl(pDataSource);
    end;

    macro on_KeyPressed(ev)
        var errflag = 0;
        var Choise, sql,CatErr, cmd;
       

        if (ev.KeyCode == K_F3)

         sql = " select t_name, case when t_tpid = 51 then 3 when  t_tpid = 2 then 1 when t_tpid = 3  then 2 end t_number from DWLTRANSP_DBT tp where t_tpid in (51,2,3);";
          
             Choise = AD_Scroll(sql, "Виды транспорта", 10, 5,"T_name", "Наименование", 40);    
          
           if (Choise != null)
               pConfirmKind.value = Choise.value("T_name"); 
               NumKind = Choise.value("T_number");
               this.redraw;                 
           end;
            this.redraw; 
     
        if(valtype(ev.source.parent) != V_UNDEF)
           if (ev.source.name == "pConfirmKind")
           sql = " select t_name, case when t_tpid = 51 then 3 when  t_tpid = 2 then 1 when t_tpid = 3  then 2 end t_number from DWLTRANSP_DBT tp where t_tpid in (51,2,3);";
          
             Choise = AD_Scroll(sql, "Виды транспорта", 10, 5,"T_name", "Наименование", 40);    
          
           if (Choise != null)
               pConfirmKind.value = Choise.value("T_name"); 
               NumKind = Choise.value("T_number");
               this.redraw;                 
           end;
            this.redraw; 
           end;
        end;
        elif (ev.KeyCode == K_F9)
           var objecttype = 101;
           if ((bofficekind == 4830) and (bofficekind == 4831) and (bofficekind == 4832))
             objecttype = 180;
           end;
           if( (not DisconnectObjAttr( objecttype, L_Z( DealID, 34 ), 201 )) 
             OR
             (not ConnectObjAttr( CatErr, objecttype, L_Z( DealID, 34 ), 201, NumKind )) 
             OR
             (CatErr != 0)
           )
            msgbox("Ошибка при установке категории ВИД ТРАНСПОРТА" );
                         
            return 1;
           end;
           cmd_upd = RSDCommand("update ddl_tick_dbt t set T.T_CONFTPID = (select dwl.t_tpid  from  DWLTRANSP_DBT dwl where t_name = ? and rownum = 1) where T.T_DEALID = ?");
           cmd_upd.addparam("", rsdbp_in, pConfirmKind.value);
           cmd_upd.addparam("", rsdbp_in, DealID);
           cmd_upd.execute();
           this.close(1);
           //this.redraw; 
                  
        elif((ev.keyCode == K_F2) )
          if (THIS.Bond_Amount.value == 0)
        
          end;      
        
        end;
    end; 
 
  
END; //CLASS 

macro exec_ConfirmKind(dealid)
 // var dealid;
  //getParm (0,dealid);
  var pnlCnfKind:TRSBpanel = pnl_ConfirmTransport(dealid);
  pnlCnfKind.run();
  
end;


//exec_ConfirmKind;