/*
$Name:        w475.mac
$Module:      Ценные бумаги
$Description: Отчет о результатах брокерского обслуживания для ДРРК
$Programmer:  Кротов А.
*/
import BankInter/*, FIInter*/, w475_panel, ReportUser;

PRIVATE CONST BROKERREP_DL_SETTLOPER = 2030; //Расчетная операция ВУ
PRIVATE CONST POI_MODE = True; //POI - параметр формирования файла по технологии  Apache POI

 //Поиск сумм списания/зачисления по расчетным операциям ВУ по аналогии с отчетом Брокера
 var ServKindSub;
  PRIVATE MACRO GetClientInAccSum(AccNumber:string, CodeCur:integer, ClientID:integer,m_BeginDate, m_DateEnd, isIN:bool)
    var query, cmd, DataSet;
    var Sum = $0;
    query = " SELECT NVL (SUM(RSI_RSB_FIInstr.ConvSum(dl_acc.t_sum,dl_acc.t_fiid,0,dl_acc.t_valuedate,1)),0) AS InOutSum              " +
            "   FROM ddl_acc_dbt dl_acc,                                  " +
            "        doproper_dbt oproper,                                " +
            "        doprdocs_dbt oprdocs,                                " +
            "        dacctrn_dbt acctrn                                   " +
            "  WHERE     dl_acc.t_fikind = ?                        " +
            "        AND dl_acc.t_fiid = ?                        " +
            "        AND dl_acc.t_operkind = ?                    " +
            "        AND dl_acc.t_opertype = 1                            " +
            "        AND dl_acc.t_client = ?                      " +
            "        AND dl_acc.t_dockind = ?                     " +
            "        AND dl_acc.t_valuedate >= ?                   " +
            "        AND dl_acc.t_valuedate <= ?                   " +
            "        AND dl_acc.t_dockind = oproper.t_dockind             " +
            "        AND LPAD (DL_ACC.T_ID, 10, 0) = oproper.t_documentid " +
            "        AND oprdocs.t_id_operation = oproper.t_id_operation  " +
            "        AND OPRDOCS.T_ACCTRNID = acctrn.t_acctrnid           ";
    if(isIN)
        query = query + " AND ACCTRN.T_ACCOUNT_RECEIVER = :accNumber ";
    else
        query = query + " AND ACCTRN.T_ACCOUNT_PAYER = :accNumber ";
    end;

    cmd = DL_RSDCommand(query);
    cmd.AddParam(FIKIND_CURRENCY);
    cmd.AddParam(CodeCur);
    cmd.AddParam(BROKERREP_DL_SETTLOPER);
    cmd.AddParam(ClientID);
    cmd.AddParam(DL_CALCOPER);
    cmd.AddParam(m_BeginDate);
    cmd.AddParam(m_DateEnd);
    cmd.AddParam(AccNumber); // 

    DataSet = cmd.Execute();

    if(DataSet.moveNext())
          Sum = DataSet.InOutSum;
    end;

    return Sum;
  end;

 PRIVATE MACRO GetServKind(_ContrID:integer, _sfcontrid)
           var query,cmd,DataSet;
          var  serv_kind;
          if (_sfcontrid != null)
           query =  "select distinct sf.t_servkind , sf.t_servkindsub             "+
                            "from ddlcontrmp_dbt mp, dsfcontr_dbt sf  "+
                            "where mp.t_sfcontrid = sf.t_id                         "+
                            "and mp.t_dlcontrid = ?                                      "+
                           " and nvl(MP.T_SFCONTRID,0) = ?";
               cmd = DL_RSDCommand(query);
               cmd.AddParam(_ContrID);
                cmd.AddParam(_sfcontrid);
                DataSet = cmd.execute();
              if (DataSet.moveNext())
                 serv_kind =  DataSet.t_servkind;
                 ServKindSub = DataSet.t_servkindsub; 
              end;
            end;
           return serv_kind;
 END;

 PRIVATE MACRO GetAccFromSubContr(m_BeginDate, m_DateEnd,ContrID:integer,  _sfcontrid, IsOut:bool)
         var query, cmd, DataSet;
         var AccNum, _ServKind;
         var AccSum =$0 ;
         var CodeCur,_ClientID;
         var isIN = false;
         if (_sfcontrid != null)
            query = "select ac.t_account, ac.t_code_currency, sf.t_partyid    "+
                     "           from DDLCONTRMP_DBT MP, DSFCONTR_DBT SF, DACCOUNT_DBT AC, DSETTACC_DBT SA, DSFSSI_DBT SI "+
                     "           where MP.T_DLCONTRID = ?                          "+
                     "                 AND SF.T_ID = MP.T_SFCONTRID                "+
                     "                 AND nvl (SF.T_SERVKIND,0) = ?               "+
                     "                 AND SF.T_SERVKINDSUB = ?                    "+
                     "                 AND SI.T_OBJECTTYPE = 659                   "+
                     "                 AND SI.T_OBJECTID = LPAD(SF.T_ID, 10, '0')  "+
                     "                 AND SA.T_SETTACCID = SI.T_SETACCID          "+
                     "                 AND AC.T_ACCOUNT = SA.T_ACCOUNT            "+
                     "                 AND AC.T_CHAPTER = SA.T_CHAPTER             "+
                     "                 AND AC.T_CODE_CURRENCY = SA.T_FIID        "+
                     "                 AND AC.T_BALANCE IN (30601, 30606)                  ";
                     cmd = DL_RSDCommand(query);
                     cmd.AddParam(ContrID);
                     
                     _ServKind = GetServKind(ContrID,_sfcontrid);
                     
                     cmd.AddParam(_ServKind);
                     cmd.AddParam(ServKindSub);
                     DataSet = cmd.execute();
                     while(DataSet.moveNext())
                         if ( IsOut == true) 
                                AccNum = DataSet.t_account;
                                _ClientID = DataSet.t_partyid;
                                CodeCur = DataSet.t_code_currency;
                                AccSum = AccSum+  GetClientInAccSum(AccNum, CodeCur, _ClientID, m_BeginDate, m_DateEnd,true);
                         else
                               AccNum = DataSet.t_account;
                               _ClientID = DataSet.t_partyid;
                               CodeCur = DataSet.t_code_currency;
                              AccSum  = AccSum +  GetClientInAccSum(AccNum, CodeCur, _ClientID,m_BeginDate, m_DateEnd,false);
                         end;                     
                     end;
            end;
          return AccSum;  
 END;

//Chesnokov D.S. Определим дату рождения для клиента по договору, если нет то пусто
 PRIVATE MACRO GetBornDate(sfc_id)
   var sql, rs, cmd;
   sql = "SELECT pt.t_born AS born_date " +
         "  FROM W475_TMP t " +
         "  JOIN dsfcontr_dbt sfc ON t.t_sfcontrid = sfc.t_id " +
         "  LEFT JOIN dpersn_dbt pt ON pt.t_personid = sfc.t_partyid " +
         " WHERE t.t_sfcontrid = :id";
         
   cmd = RsdCommand(sql);
   cmd.AddParam("id", RSDBP_IN, sfc_id);
   rs = RsdRecordSet(cmd, RSDVAL_CLIENT, RSDVAL_STATIC);
   
   if(rs and rs.MoveNext())
     if(valtype(rs.value("born_date", null, V_DATE)) == V_DATE)
       return rs.value("born_date", null, V_DATE);
     end;
   end;
   
   return "";
 END;

/**************************************************************/


PRIVATE CLASS (TX_ReportUser) W475_Report
  var m_BeginDate, m_DateEnd, m_IsShowReport;

  private macro PrintHeadSwap( _PastePos:integer )
     SetActiveSheet("Расшифровка РЕПО_СВОП");
     PrintFormatString( "", "ReportName4", "Расшифровка сделок СПЕЦ РЕПО/СПЕЦ СВОП");

     RegisterTable( "ReportRow4", "",
             /* 1*/ "Field01_02", 
             /* 2*/ "Field16_02", 
             /* 3*/ "Field02_02", 
             /* 4*/ "Field03_02", 
             /* 5*/ "Field04_02", 
             /* 6*/ "Field05_02", 
             /* 7*/ "Field06_02", 
             /* 8*/ "Field07_02", 
             /* 9*/ "Field08_02", 
             /* 10*/ "Field09_02", 
             /* 11*/ "Field10_02",
             /* 12*/ "Field11_02",
             /* 13*/ "Field12_02",
             /* 14*/ "Field13_02",
             /* 15*/ "Field14_02",
             /* 16*/ "Field15_02");

     SetActiveSheet("Расшифровка РЕПО_СВОП");
  end;

  private macro PrintEndSwap()
    message("Вывод в EXCEL");
    EndTable();
  end;

  /*Создание отчета*/
  PRIVATE MACRO Create()

/*Точка входа*/
    var query, row = 0, dognum = 0, subdognum, dlcontrid = 0;
    var m_dognum, m_contrnumber, m_contrdatebegin, m_planname, m_clientname, m_clientcode, m_depname, m_restperc, m_borndate = "", m_cft_kod;
    var m_DS;
    var errmsg;


    /*Даты начала и окончания периода отчета*/
    m_BeginDate = FormData.BeginDate;
    m_DateEnd   = FormData.EndDate;
    m_IsShowReport = (m_Form.GetFieldValue(P_W475_ShowReport) == "X");

    RSDCommand("delete W475_TMP").execute();
    //MZ>>
    RSDCommand(" declare n number; "+
			" begin select count(*) into n from user_tab_columns t where  t.TABLE_NAME='W475_TMP' and t.COLUMN_NAME = 'T_PARTYID' ; "+
			" if n = 0 then "+
			" execute immediate 'alter table W475_TMP add T_PARTYID number'; "+
			" end if; select count(*) into n from user_tab_columns t where  t.TABLE_NAME='W475_TMP' and t.COLUMN_NAME = upper('born_date') ; "+
			" if n = 0 then "+
			" execute immediate 'alter table W475_TMP add born_date date'; "+
			" end if; select count(*) into n from user_tab_columns t where  t.TABLE_NAME='W475_TMP' and t.COLUMN_NAME = upper('t_ComSumBank') ; "+
			" if n = 0 then "+
			" execute immediate 'alter table W475_TMP add t_ComSumBank number'; "+
			" end if; select count(*) into n from user_tab_columns t where  t.TABLE_NAME='W475_TMP' and t.COLUMN_NAME = upper('t_ComSumBankRepo') ; "+
			" if n = 0 then "+
			" execute immediate 'alter table W475_TMP add t_ComSumBankRepo number'; "+
			" end if; select count(*) into n from user_tab_columns t where  t.TABLE_NAME='W475_TMP' and t.COLUMN_NAME = upper('kod_cft') ; "+
			" if n = 0 then "+
			" execute immediate 'alter table W475_TMP add kod_cft varchar2(35)'; "+
			" end if; "+
            " end;").execute();
	//MZ
    query = " INSERT INTO W475_TMP (t_dlcontrid,t_sfcontrid,t_contrnumber,t_contrdatebegin,t_planname,t_clientname,t_clientcode,t_depname,t_marketname,t_sfcontridsm,t_sfcontridfm,t_sfcontridom,t_sfcontridcm,t_depcode, "
          + "                       T_FINNAME, T_DS_PLUS, T_DS_MINUS, T_TURNSUM, T_TURNSUMREPO, T_TURNSUMSVOP, T_DS_IN, T_DS_OUT, T_P_PLUS, T_P_MINUS, T_P_IN, T_P_OUT, T_COMSUM, T_COMSUMREPO, T_SPECIAL_REPO, T_COMSUMSVOP, T_VAL_SVOP,t_partyid,born_date, t_ComSumBank, t_ComSumBankRepo, kod_cft ) " //MZ
          + "(select t_dlcontrid, t_sfcontrid, "
          + "        /*(select t_number from dsfcontr_dbt where t_id = t_sfcontrid) GAA:503753, 04.02.2020*/ t_contrnumber, t_contrdatebegin, t_planname, t_clientname, t_clientcode, t_depname, t_marketname, "
          + "        t_sfcontridsm, t_sfcontridfm, t_sfcontridom, t_sfcontridcm, "
          + "        t_depcode, " // Golovkin
          + "        chr(1),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,tt2.t_partyid,pt.t_born AS born_date, 0, 0, nvl(dpc.t_code,'Не найден код ЦФТ') " //MZ
          + "   from (select /*+ USE_NL(SFCONTRCM,SFCONTROM,SFCONTRFM,SFCONTRSM,DP_DEP) */ t_dt1, t_dt2, "
          + "             t_dlcontrid, t_department, t_partyid, nvl(t_sfcontridsm, nvl(t_sfcontridfm, nvl(t_sfcontridom, t_sfcontridcm))) t_sfcontrid, "
          + "             t_contrnumber, t_contrdatebegin, t_planname, t_clientname, t_clientcode, /*t_depname,*/ t_marketname, "
          // Golovkin Наименование филиала
          + "             (select ptdep.t_name " 
          + "                from dparty_dbt ptdep, ddp_dep_dbt dpdep "
          + "               where dpdep.t_name = t_depcode "
          + "                 and dpdep.t_partyid = ptdep.t_partyid "
          + "             ) t_depname, "
          + "             t_depcode, " 
          + "             nvl(t_sfcontridsm, 0) t_sfcontridsm, "
          + "             nvl(t_sfcontridfm, 0) t_sfcontridfm, "
          + "             nvl(t_sfcontridom, 0) t_sfcontridom, "
          + "             nvl(t_sfcontridcm, 0) t_sfcontridcm  "
          + "      from (select t_dt1, t_dt2, "
          + "                   dlcontr.t_dlcontrid t_dlcontrid, "
          + "                   sfcontr.t_id t_sfcontrid, "
          + "                   sfcontr.t_department t_department, "
          + "                   sfcontr.t_partyid t_partyid, "
          + "                   sfcontr.t_number t_contrnumber, "
          + "                   sfcontr.t_datebegin t_contrdatebegin, "
          + "                   nvl(sfplan.t_name,chr(1)) t_planname, "
          + "                   nvl(case "
          + "                             when party.t_name <> chr(34) then "
          + "                              party.t_name "
          + "                             else "
          + "                              chr(1) "
          + "                           end, "
          + "                           chr(1)) t_clientname, "
//          + "                   NVL(dlcontrmp.t_mpcode, chr(1)) t_clientcode," // Golovkin 
           + "                  nvl((select t_code from ddlobjcode_dbt where t_objecttype = 207 and t_codekind = 1 /*and t_state = 0*/ and t_objectid = dlcontrmp.t_dlcontrid),chr(1)) t_clientcode, "
          // Golovkin код филиала
          + "                     case when SubStr(sfcontr.t_number,3,1) = '-' or SubStr(sfcontr.t_number,3,1) = '/' then  "
          + "                          SubStr( sfcontr.t_number,1,2)   "
          + "                     else '00' "
          + "                     end||'00' t_depcode, "

          + "                   case when sfcontrsm.t_id is not null then 'Фондовый' "
          + "                        when sfcontrfm.t_id is not null then 'Срочный' "
          + "                        when sfcontrom.t_id is not null then 'Внебиржевой' "
          + "                        when sfcontrcm.t_id is not null then 'Валютный' "
          + "                        else chr(1) end t_marketname, "
          + "                   sfcontrsm.t_id t_sfcontridsm, "
          + "                   sfcontrfm.t_id t_sfcontridfm, "
          + "                   sfcontrom.t_id t_sfcontridom, "
          + "                   sfcontrcm.t_id t_sfcontridcm "
          + "            from dsfcontr_dbt sfcontr "
          + "            join (select ? t_dt1, ? t_dt2 from dual) on 1 = 1 and sfcontr.t_partyid != 1"
          + "            join dset_sfc_u_tmp_ set_sfc_u on set_sfc_u.t_contrid = sfcontr.t_id and "
          + "                                             set_sfc_u.t_setflag = chr(88) "
          + "            join ddlcontr_dbt dlcontr on dlcontr.t_sfcontrid = sfcontr.t_id "
          + "            join ddlcontrmp_dbt dlcontrmp on dlcontrmp.t_dlcontrid = dlcontr.t_dlcontrid "
          + "            left join dparty_dbt party on party.t_partyid = sfcontr.t_partyid "
          + "            left join dsfcontrplan_dbt sfcontrplan on sfcontrplan.t_sfcontrid = dlcontrmp.t_sfcontrid and "
          + "                                                      sfcontrplan.t_begin <= t_dt2 and "
          + "                                                      (sfcontrplan.t_end = to_date('01.01.0001','dd.mm.yyyy') or "
          + "                                                       sfcontrplan.t_end >= t_dt2) "
          + "            left join dsfplan_dbt sfplan on sfplan.t_sfplanid = sfcontrplan.t_sfplanid "
          + "            left join dobjcode_dbt objcode on objcode.t_objecttype = 3 and "
          + "                                              objcode.t_codekind = 8 and "
          + "                                              objcode.t_objectid = party.t_partyid and "
          + "                                              objcode.t_bankdate <= t_dt2 and "
          + "                                              (objcode.t_bankclosedate = to_date('01.01.0001','dd.mm.yyyy') or "
          + "                                               objcode.t_bankclosedate >= t_dt2) "
          + "            left join ddp_dep_dbt dp_dep on dp_dep.t_code = sfcontr.t_department "
          + "            left join dsfcontr_dbt sfcontrsm on sfcontrsm.t_id = dlcontrmp.t_sfcontrid and "
          + "                                                sfcontrsm.t_servkind = 1/*Фондовый дилинг*/ and "
          + "                                                sfcontrsm.t_servkindsub = 8/*Биржевой рынок*/ "
          + "            left join dsfcontr_dbt sfcontrfm on sfcontrfm.t_id = dlcontrmp.t_sfcontrid and "
          + "                                   sfcontrfm.t_servkind = 15/*Срочные контракты*/  "
          + "                               and    sfcontrfm.t_servkindsub = 8/*Биржевой рынок*/ "     
          + "            left join dsfcontr_dbt sfcontrom on sfcontrom.t_id = dlcontrmp.t_sfcontrid and "
          + "                                                sfcontrom.t_servkind = 1/*Фондовый дилинг*/ and "
          + "                                                sfcontrom.t_servkindsub = 9/*Внебиржевой рынок*/ "
          + "            left join dsfcontr_dbt sfcontrcm on sfcontrcm.t_id = dlcontrmp.t_sfcontrid and "
          + "                      sfcontrcm.t_servkind = 21/*Валютный дилинг*/) "       
          + "      where (1 = 0 ";


    if(m_Form.GetFieldValue(P_W475_StockMarket) == "X")
      query = query
          + "             or t_sfcontridsm is not null";
    end;
    if(m_Form.GetFieldValue(P_W475_FuturesMarket) == "X")
      query = query
          + "             or t_sfcontridfm is not null";
    end;
    if(m_Form.GetFieldValue(P_W475_OverTheCounterMarket) == "X")
      query = query
          + "             or t_sfcontridom is not null";
    end;
    if(m_Form.GetFieldValue(P_W475_CurrencyMarket) == "X")
      query = query
          + "             or t_sfcontridcm is not null";
    end;
    query = query + " ) ) tt2 left join dpersn_dbt pt ON pt.t_personid = t_partyid " + 
                            " left join DPARTCODE_DBT dpc on dpc.t_partyid=tt2.t_partyid and dpc.t_codekind=101 " + 
                    ") ";

    m_DS = RSDCommand(query);
    m_DS.AddParam("dt1", RSDBP_IN, m_BeginDate);
    m_DS.AddParam("dt2", RSDBP_IN, m_DateEnd);

    //BegAction(1, "0/21 Отбор данных");
    InitProgress(21, "Формирование отчета", "Формирование отчета");
    message("0/21 Отбор данных");
    //msgbox("main  " + time());
    m_DS.Execute();
debugbreak;

    //RSDCommand("delete from W475_TMP t where t.t_contrnumber not in ('63/67-18533694')").execute(); /// !!!!!!!!!!!!!!!!!!!!!!!! KS Убрать!!!
    /* Обновление временной таблицы */
    var cmdUpdateTmp;
//    cmdUpdateTmp = RsdCommand(" create table W475_TMP_kot as select * from W475_TMP" );
//    cmdUpdateTmp.execute();
    if (m_Form.GetFieldValue(P_W475_FuturesMarket) == "X") // KS Для срочного рынка уточним t_Sfcontrid
      cmdUpdateTmp = RsdCommand("UPDATE W475_TMP W475  " +
                                "   SET t_Sfcontrid =                                                           " +
                                "       (select max(sfcontr.t_id)                                               " +
                                "          From dsfcontr_dbt sfcontr,                                           " +
                                "               dsfcontr_dbt sfcontr2,                                          " +
                                "               ddlcontr_dbt dlcontr                                            " +
                                "         where sfcontr.t_ServKind in (15 /*15 Срочные контракты (ФИССИКО)*//*, 21 Валютный дилинг*/)   " + // KS 20.03.2020 /*pnv 526409*/
                                "           and (sfcontr.t_DateClose = to_date('01.01.0001', 'dd.mm.yyyy') or   " +
                                "               sfcontr.t_DateClose >= ?)                                       " +
                                "           and sfcontr2.t_ServKind = 0                                         " +
                                "           and (sfcontr2.t_DateClose = to_date('01.01.0001', 'dd.mm.yyyy') or  " +
                                "               sfcontr2.t_DateClose >= ?)                                      " +
                            //    "           and sfcontr.t_partyid = sfcontr2.t_partyid                          " +
                                "           and sfcontr2.t_id = dlcontr.t_sfcontrid                             " +
                                "           and dlcontr.t_dlcontrid = W475.T_dlcontrid                        " +
                               "         and sfcontr.t_id in (select contr.T_SFCONTRID from  DDLCONTRMP_DBT contr where contr.t_dlcontrid =  dlcontr.t_dlcontrid) )    "+/*CHVA*/
                                " where W475.t_Sfcontrid is null");
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
      cmdUpdateTmp.execute();
    end;  
 //MZ>>
// Обновление данных после уточнения используемы при печати (см.ниже )
    cmdUpdateTmp = RsdCommand(
                   " UPDATE W475_TMP t   " +
                   "    SET t_contrnumber =  " +
                   "       (select d.t_number from dsfcontr_dbt d where d.t_id =  t.t_Sfcontrid) ");
                   
    cmdUpdateTmp.execute();
 //MZ
    /* 1  t_finname */
    message("1/21  Наименования бумаг");
    cmdUpdateTmp = RsdCommand(
                   " UPDATE W475_TMP " +
                   "    SET t_finname =                                              " +
                   "           (SELECT rsb_struct.getstring (t_text)                 " +
                   "              FROM dnotetext_dbt                                 " +
                   "             WHERE     t_notekind = 150                          " +
                   "                   AND t_objecttype = 207                        " +
                   "                   AND t_documentid = LPAD (t_dlcontrid, 34, 0)) ");
                   
    //EndAction;
    //BegAction(1, "1/21 Наименования бумаг");
    UseProgress(1);
    cmdUpdateTmp.execute();
  //  msgbox("1  "+time());


    /* 2  t_ds_plus */
    message("2/21  Суммы зачислений и списаний ");
    cmdUpdateTmp = RsdCommand(
/*MZ>>                  " UPDATE W475_TMP                                                                                                " +
                   "    SET t_ds_plus =                                                                                             " +
                   "           (SELECT NVL(SUM(RSI_RSB_FIInstr.ConvSum(nptxop.t_outsum,nptxop.t_currency,0,nptxop.T_OPERDATE,1)),0) " +
                   "              FROM dnptxop_dbt nptxop                                                                           " +
                   "             WHERE nptxop.t_dockind = 4607                                                                      " +
                   "                   AND nptxop.t_subkind_operation = 10 /*зачисление*/                                           " +
                   "                   AND nptxop.t_status = 2                                                                      " +
                   "                   AND nptxop.t_operdate BETWEEN ? AND ?                                                        " +
                   "                   AND nptxop.t_contract = t_sfcontrid)                                                         ");
*/  
                   " MERGE INTO W475_TMP w475                                                                                           " +
                   "      using  (SELECT nptxop.t_contract , "+
				   "            NVL(SUM(decode(nptxop.t_subkind_operation,10,RSI_RSB_FIInstr.ConvSum(nptxop.t_outsum,nptxop.t_currency,0,nptxop.T_OPERDATE,1),0)),0) rest_plus, " +
				   "            NVL(SUM(decode(nptxop.t_subkind_operation,20,RSI_RSB_FIInstr.ConvSum(nptxop.t_outsum,nptxop.t_currency,0,nptxop.T_OPERDATE,1),0)),0) rest_minus " +
                   "              FROM dnptxop_dbt nptxop, ddlrq_dbt rq                                                                           " +
                   "             WHERE nptxop.t_dockind = 4607                                                                      " +
                   "                   AND nptxop.t_subkind_operation in( 10,20) /*зачисление и списание*/                                     " +
                   "                   AND nptxop.t_status = 2                                      " +
                   "                   AND rq.t_dockind = nptxop.t_dockind                          " +
                   "                   AND rq.t_docid = nptxop.t_id                                 " +
                   "                   AND rq.t_state != 7                                          " +
                   "                   AND nptxop.t_operdate BETWEEN ? AND ? group by nptxop.t_contract ) r "+
                   "      ON (r.t_contract = w475.t_sfcontrid )                                     " +
                   "  WHEN MATCHED THEN                                                             " +
                   "  UPDATE SET W475.t_ds_plus = R.REST_plus, W475.t_ds_minus = R.REST_minus        ");


    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    //EndAction;
    //BegAction(1, "2/21 Суммы зачислений");
    UseProgress(2);
    cmdUpdateTmp.execute();
   // msgbox("2  "+time());


    /* 3  t_ds_minus */
    message("3/21  Суммы списаний");
    cmdUpdateTmp = RsdCommand(
                   " UPDATE W475_TMP " +
                   "    SET t_ds_minus =                                                                                                    " +
                   "                (SELECT NVL (SUM (RSI_RSB_FIInstr.ConvSum (nptxop.t_outsum,nptxop.t_currency,0,nptxop.T_OPERDATE,1)),0) " +
                   "             FROM dnptxop_dbt nptxop                                                                                    " +
                   "            WHERE     nptxop.t_dockind = 4607                                                                           " +
                   "                  AND nptxop.t_subkind_operation = 20 /*списание*/                                                      " +
                   "                  AND nptxop.t_status = 2                                                                               " +
                   "                  AND nptxop.t_operdate BETWEEN ? AND ?                                                                 " +
                   "                  AND nptxop.t_contract = t_sfcontrid)                                                                  ");
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
//    EndAction;
//    BegAction(1, "3/21 Суммы списаний");
//         UseProgress(3);
//MZ СМ выше    cmdUpdateTmp.execute();
     /*CHVA*/
         /**************************************/
   //Получаем id договора и апдейтим суммы с учетом операций РОВУ
      var query2,cmd2,DataSet2;
      var dlcontr = 0, ds_plus=$0,ds_minus=$0;
      var _sfcontrid;
      query2 = "select  *  "+                    /*AVN*/
               "from  W475_TMP t where t.t_sfcontrid in (select t_clientcontr from ddl_acc_dbt where t_fikind = 1 and t_opertype = 1 and t_date between ? and ? ) ";
      cmd2 = DL_RSDCommand(query2);
      cmd2.addParam(m_BeginDate);
      cmd2.addParam(m_DateEnd);
      DataSet2 = cmd2.execute();
      while (DataSet2.moveNext())
        if (DataSet2.t_sfcontrid != null) 
           ds_plus = DataSet2.t_ds_plus +GetAccFromSubContr(m_BeginDate, m_DateEnd, DataSet2.t_dlcontrid, DataSet2.t_sfcontrid, true);
           ds_minus = DataSet2.t_ds_minus+ GetAccFromSubContr(m_BeginDate, m_DateEnd,DataSet2.t_dlcontrid, DataSet2.t_sfcontrid, false);
       
           cmdUpdateTmp = RsdCommand(
          
           " UPDATE W475_TMP   " +
           "    SET t_ds_plus =  ? " +
           "              , t_ds_minus = ? " +
           "    WHERE  t_sfcontrid = ? ");
            cmdUpdateTmp.addParam("",RSDBP_IN,ds_plus);
            cmdUpdateTmp.addParam("",RSDBP_IN,ds_minus);
            cmdUpdateTmp.addParam("",RSDBP_IN,DataSet2.t_sfcontrid); /*AVN*/
            UseProgress(3);
            cmdUpdateTmp.execute();
        end;
      end;
 /*CHVA*/   
    /************************************/
    
 //   msgbox(time());
 
    /* 4  t_turnsum */
    message("4/21  t_turnsum");
    cmdUpdateTmp = RsdCommand(
                   " MERGE INTO W475_TMP w475  " +
                   "       using (SELECT /*+ cardinality(w 100)*/ dl_tick.t_clientcontrid, NVL (SUM (decode( dlrq.t_type, 3, decode (rsb_secur.IsSale(rsb_secur.get_operationgroup(rsb_secur.get_opersystypes(dl_tick.t_dealtype, dl_tick.t_bofficekind))), 1, 1, -1), 1)*RSI_RSB_FIInstr.ConvSum(dlrq.t_factamount, dlrq.t_fiid, 0, dlrq.t_factdate, 1)),0) rest" + 
                   "             FROM  W475_TMP w join ddl_tick_dbt dl_tick on w.t_sfcontrid = dl_tick.t_clientcontrid          " +
                   "                  JOIN ddlrq_dbt dlrq                                                                       " +
                   "                  ON     dlrq.t_dockind = dl_tick.t_bofficekind                                             " +
                   "                     AND dlrq.t_docid = dl_tick.t_dealid                                                    " +
                   "                     AND dlrq.t_subkind = 0                                                                 " +
                   "                     AND dlrq.t_type IN (2,3)                                                               " +
                   "                     AND dlrq.t_kind IN (0, 1)                                                              " +
                   "            WHERE     dl_tick.t_bofficekind in(101,117)                                                     " + // Golovkin 25.04.2019 и погашения сюда же
                   "                  AND dlrq.t_factdate BETWEEN ? AND ? group by dl_tick.t_clientcontrid) r "
                   " ON (r.t_clientcontrid = w475.t_sfcontrid )                                                  " +
                   "  WHEN MATCHED THEN                                                                                  " +
                   "  UPDATE SET W475.T_turnsum = R.REST                                                               ");

    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
//    EndAction;
//    BegAction(1, "4/21 Оборотов всего");
    UseProgress(4);
    cmdUpdateTmp.execute();
//    msgbox("4  "+time());

    /* 5  t_turnsumrepo */
    message("5/21  t_turnsumrepo");
    cmdUpdateTmp = RsdCommand(
                   " MERGE INTO W475_TMP w475                                                                                           " +
                   "       using (SELECT d.t_SfContrID, NVL (SUM (decode( dlrq.t_type, 3, decode (Opr.IsSale, 1, 1, -1), 1)*RSI_RSB_FIInstr.ConvSum(dlrq.t_factamount, dlrq.t_fiid, 0, dlrq.t_factdate, 1)),0) rest" + 
                   "             FROM  W475_TMP d, " +
                   "                   ( select t_Kind_Operation, "+
                   "                            rsb_secur.IsRepo (rsb_secur.get_operationgroup (rsb_secur.get_opersystypes (t_Kind_Operation,t_DocKind))) as IsRepo, "+
                   "                            rsb_secur.IsSale (rsb_secur.get_operationgroup (rsb_secur.get_opersystypes (t_Kind_Operation,t_DocKind))) as IsSale "+
                   "                       from doprkoper_dbt "+
                   "                      where t_DocKind = 101 "+
                   "                   ) Opr, " +
                   "                   ddl_tick_dbt dl_tick                                                                   " +
                   "                  JOIN ddlrq_dbt dlrq                                                                       " +
                   "                  ON     dlrq.t_dockind = dl_tick.t_bofficekind                                             " +
                   "                     AND dlrq.t_docid = dl_tick.t_dealid                                                    " +
                   "                     AND dlrq.t_subkind = 0                                                                 " +
                   "                     AND dlrq.t_type IN (2,3)                                                               " +
                   "                     AND dlrq.t_kind IN (0, 1)                                                              " +
                   "                     AND dlrq.t_factdate BETWEEN ? AND ? "+
                   "            WHERE d.t_SfContrID is not NULL AND d.t_SfContrID > 0                                           " +
                   "                  AND dl_tick.t_bofficekind = 101                                                           " + 
                   "                  AND dl_tick.t_ClientID = d.t_PartyID         " +
                   "                  AND dl_tick.t_ClientContrID = d.t_SfContrID         " +
                   "                  AND Opr.t_Kind_Operation = dl_tick.t_DealType       " +
                   "                  AND Opr.IsRepo != 0 "+
                   "                  group by d.t_SfContrID) r "
                   " ON (r.t_SfContrID = w475.t_sfcontrid )                                                  " +
                   "  WHEN MATCHED THEN                                                                                  " +
                   "  UPDATE SET W475.T_turnsumrepo = R.REST                                                               ");
                                                                                                                                 
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
  //  EndAction;
  //  BegAction(1, "5/21 В том числе по РЕПО");
    UseProgress(5);
    cmdUpdateTmp.execute();
//    msgbox("5  "+time());
    //PDV 080620
    message("6/21  t_sum_svop");
      if(m_Form.GetFieldValue(P_W475_CurrencyMarket) == "X")
       cmdUpdateTmp = RsdCommand(
                     " MERGE INTO W475_TMP W475                                                                                          " +
                     "  using (select /*+use_hash(dvd,dvnfi) */ dvn.t_clientcontr t_id,                                                                            " +
                     "                nvl(sum(dvnfi.t_cost),0) t_sum_svop                       " +
                     "           from ddvndeal_dbt dvn, ddvnfi_dbt dvnfi                                                                 " +
                     "          where  dvn.t_kind = 32715 and dvn.t_type in (3,5,6,7) and dvn.t_id = dvnfi.t_dealid and dvnfi.t_type = 0 " +
                     "              and dvn.t_client !=1 and dvn.t_state in(1,2)                                                         " +
                     "              and dvnfi.t_execdate between ? AND ?                                                                 " +
                     "          group by dvn.t_clientcontr) R                                                                            " +
                     "  ON (R.t_id = W475.T_sfcontrid)                                                                                   " +
                     "  WHEN MATCHED THEN                                                                                                " +
                     "    UPDATE SET W475.t_turnsumsvop = R.t_sum_svop ");
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
      UseProgress(6);
      cmdUpdateTmp.execute();      
      end;
 
    /* 7  t_ds_in */
    message("7/21  t_ds_in_out");

    cmdUpdateTmp = RsdCommand(

                      
                   " MERGE INTO W475_TMP W475   " +
                      "    using (SELECT  t_id, " +
                     "                    case  " +
                     "                           when (t_servkind <> 1/*Фондовый дилинг */  or  t_servkindsub <> 8/*Биржевой рынок */                                               " +
                     "                             or (select count(*) from ddlcontrmp_dbt dlcontm where dlcontm.t_sfcontrid = q.t_id and dlcontm.t_marketid = 151337) > 0)           " +
                     "                              and   RSB_SECUR.GetGeneralMainObjAttr(659,LPAD (t_id, 10, '0'),102, to_date('31122999','ddmmyyyy'))  = 1                        " +
                     "                            then 0                                                                                                                            " +   
                     "                           else NVL (ABS (SUM (RSB_FIInstr.ConvSum (rest_in,t_code_currency,0,? ,1))),0)                                                      " +
                     "                     end rest_in,                                                                                                                             " +   
                     "                     case                                                                                                                                     " +         
                     "                           when (t_servkind <> 1/*Фондовый дилинг */  or  t_servkindsub <> 8/*Биржевой рынок */                                               " +
                     "                             or (select count(*) from ddlcontrmp_dbt dlcontm where dlcontm.t_sfcontrid = q.t_id and dlcontm.t_marketid = 151337) > 0)           " +
                     "                              and   RSB_SECUR.GetGeneralMainObjAttr(659,LPAD (t_id, 10, '0'),102, to_date('31122999','ddmmyyyy'))  = 1                        " +
                     "                             then 0                                                                                                                           " +   
                     "                           else NVL (ABS (SUM (RSB_FIInstr.ConvSum ( rest_out,t_code_currency,0,?,1))),0)                                                     " +
                     "                     end rest_out                                                                                                                             " +    
                      "            from (select /*+ leading(w sf ss s a) cardinality(w 100) */  sf.t_id ,a.t_account, a.t_chapter, a.t_code_currency, sf.t_servkind, sf.t_servkindsub " +
                      "                   ,RSB_ACCOUNT.RESTALL(a.t_account, a.t_chapter, a.t_code_currency, ?) rest_in " +
                      "                   ,RSB_ACCOUNT.RESTALL(a.t_account, a.t_chapter, a.t_code_currency, ?) rest_out " +
                      "                  FROM dsettacc_dbt s,                 " +
                      "                    dsfssi_dbt ss,                     " +
                      "                    dsfcontr_dbt sf,                   " +
                      "                    daccount_dbt a,                    " +
                      "                     W475_TMP w                        " +
                      "                  WHERE s.t_settaccid = ss.t_setaccid  " +
                      "                    AND ss.t_objecttype = 659          " +
                      "                    AND ss.t_objectid = sf.t_id        " +
                      "                    AND a.t_account = s.t_account      " +
                      "                    AND a.t_chapter = s.t_chapter      " +
                      "                    AND a.t_chapter = 1                " +
                      "                    AND sf.t_id = w.t_sfcontrid      ) q" + // MZ
                      "             where rest_in != 0 or  rest_out != 0                       " +
					           "            group by t_id,t_servkind,t_servkindsub) R                    " +
                      "  ON (R.t_id = W475.T_sfcontrid)                                        " +
                      "  WHEN MATCHED THEN    " +
                      "    UPDATE SET W475.T_DS_IN  = R.REST_IN," +
                      "               W475.T_DS_OUT = R.REST_OUT "); 

    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate-1);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate-1);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
     //  EndAction;
  //  BegAction(1, "7/21 Входящие остатки");
    UseProgress(7);
    cmdUpdateTmp.execute();
    //msgbox("7  "+time());
                     
    /* 8  t_ds_out */
    message("8/21  t_ds_out");
    cmdUpdateTmp = RsdCommand(    
                   " MERGE INTO W475_TMP W475  " +
                   "    using (SELECT  /*+ cardinality(w 100)*/ sf.t_id, " +
                   "                   case                              " + 
                   "                           when (t_servkind <> 1/*Фондовый дилинг */  or  t_servkindsub <> 8/*Биржевой рынок */                                                             " +
                   "                             or (select count(*) from ddlcontrmp_dbt dlcontm where dlcontm.t_sfcontrid = sf.t_id and dlcontm.t_marketid = 151337) > 0)                      " +
                   "                              and   RSB_SECUR.GetGeneralMainObjAttr(659,LPAD (t_id, 10, '0'),102, to_date('31122999','ddmmyyyy'))  = 1                                      " +      
                   "                         then 0                                                                                                                                             " +     
                   "                     else NVL (ABS (SUM (RSB_FIInstr.ConvSum (RSB_ACCOUNT.RESTALL (a.t_account,a.t_chapter,a.t_code_currency,?),a.t_code_currency,0,?,1))),0)               " + 
                   "                   end rest                                                                                                                                                 " +    
                   "             FROM dsettacc_dbt s,                  " +
                   "                  dsfssi_dbt ss,                   " +
                   "                  dsfcontr_dbt sf,                 " +
                   "                  daccount_dbt a,                   " +
                   "                  W475_TMP w                        " +
                   "            WHERE     s.t_settaccid = ss.t_setaccid " +
                   "                  AND ss.t_objecttype = 659         " +
                   "                  AND ss.t_objectid = sf.t_id       " +
                   "                  AND a.t_account = s.t_account     " +
                   "                  AND a.t_chapter = s.t_chapter     " +
                   "                  AND a.t_chapter = 1               " +
                   "                  AND sf.t_id = w.t_sfcontrid       " + // MZ
                   "                  group by sf.t_id,t_servkind,      " +  
                   "                           t_servkindsub) R         " +
                   "  ON (R.t_id = W475.T_sfcontrid)                    " +
                   "  WHEN MATCHED THEN                                 " +
                   "  UPDATE SET W475.T_DS_OUT = R.REST                 ");

    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
   // EndAction;
   // BegAction(1, "8/21 Исходящие остатки");
    UseProgress(9);
//    cmdUpdateTmp.execute();
   // msgbox("8  "+time());
   
  
// KS 17.06.2019 Для срочного рынка вх/исх остатки
    cmdUpdateTmp = RsdCommand(
                   " MERGE INTO W475_TMP W475                                                                                                        " +
                   "  using (select sfcontr.t_id t_id,                                                                                               " +
                   "                 case when  RSB_SECUR.GetGeneralMainObjAttr(659,LPAD (sfcontr.t_id, 10, '0'),102, to_date('31122999','ddmmyyyy'))  = 1                                                       " + 
                   "                       then 0                                                                                                    " + 
                   "                     else                                                                                                        " + 
                   "                       nvl(sum(rsb_account.restall(acc.t_account, acc.t_chapter, acc.t_code_currency, ? - 1, 0)),0)              " + 
                   "                 end REST_IN,                                                                                                    " +
                   "                 case when  RSB_SECUR.GetGeneralMainObjAttr(659,LPAD (sfcontr.t_id, 10, '0'),102, to_date('31122999','ddmmyyyy'))  = 1                                                       " + 
                   "                       then 0                                                                                                    " + 
                   "                     else                                                                                                        " + 
                   "                       nvl(sum(rsb_account.restall(acc.t_account, acc.t_chapter, acc.t_code_currency, ? , 0)),0)                 " + 
                   "                 end REST_OUT                                                                                                    " +
                   "                   from dsfssi_dbt ssi                                                                                                          " +
                   "                   join dsettacc_dbt sa on sa.t_SettAccID = ssi.t_SetAccID                                                                      " +
                   "                   join daccount_dbt acc on acc.t_Account = sa.t_Account and                                                                    " +
                   "                                     acc.t_Chapter = sa.t_Chapter and                                                                           " +
                   "                                     acc.t_Code_Currency = sa.t_FIID                                                                            " +
//                   "                   join dsfcontr_dbt sfcontr on sfcontr.t_ServKind in (15/*15 Срочные контракты (ФИССИКО)*/, 21/*Валютный дилинг*/) and       " + // KS 20.03.2020
                   "                   join dsfcontr_dbt sfcontr on sfcontr.t_ServKind in (15/*15 Срочные контракты (ФИССИКО)*/) and         " + // KS 20.03.2020
                   "                                                (sfcontr.t_DateClose = to_date('01.01.0001','dd.mm.yyyy') or sfcontr.t_DateClose >= ?)          " +
                   "                   join dsfcontr_dbt sfcontr2 on sfcontr2.t_ServKind = 0 and                                                                    " +
                   "                                                 (sfcontr2.t_DateClose = to_date('01.01.0001','dd.mm.yyyy') or sfcontr2.t_DateClose >= ?)       " +
                   "                   join ddlcontr_dbt dlcontr on sfcontr2.t_id = dlcontr.t_sfcontrid AND dlcontr.t_iis <> 'X'                                    " + /*22.01.2020 RAS:496347*/
                   "                   where  ssi.t_ObjectID = to_char(sfcontr.t_id,'FM0000000000')                                                                 " +
                   "                     and SSI.T_OBJECTTYPE = 659 "+ //MZ
                   "                  AND sfcontr.t_id in (select t_sfcontrid from W475_TMP)                                        " + // MZ
                   "                     and  sfcontr.t_partyid = sfcontr2.t_partyid                                                                                " +
                   "                   group by sfcontr.t_id) R                                                                            " +
                   "  ON (R.t_id = W475.T_sfcontrid)                                                                                                 " +
                   "  WHEN MATCHED THEN                                                                                                              " +
                   "    UPDATE SET W475.T_DS_IN  = R.REST_IN," +
                   "               W475.T_DS_OUT = R.REST_OUT ");
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    UseProgress(8);
    cmdUpdateTmp.execute();

    if((m_Form.GetFieldValue(P_W475_StockMarket)          != "X")and
       (m_Form.GetFieldValue(P_W475_FuturesMarket)        == "X")and
       (m_Form.GetFieldValue(P_W475_OverTheCounterMarket) != "X")and
       (m_Form.GetFieldValue(P_W475_CurrencyMarket)       != "X"))
      RSDCommand("delete from W475_TMP where T_DS_IN = T_DS_OUT or t_contrnumber = '0000'").execute();
    end;

    /* 9  t_p_plus */
    message("9/21  t_p_plus_minus");
    cmdUpdateTmp = RsdCommand(
                   " MERGE INTO W475_TMP w475                                                                                                              " +
                   "    using      (SELECT dl_tick.t_clientcontrid,"+ //MZ
                   "				  NVL (SUM (ROUND (decode(dlrq.t_kind,0,rsb_secur.SC_ConvSumTypeRep (dlrq.t_factamount,dlrq.t_fiid,0,0,12,dlrq.t_factdate),0), 2)),0) rest_plus, " +
				   "				  NVL (SUM (ROUND (decode(dlrq.t_kind,1,rsb_secur.SC_ConvSumTypeRep (dlrq.t_factamount,dlrq.t_fiid,0,0,12,dlrq.t_factdate),0), 2)),0) rest_minus " +
                   "             FROM ddl_tick_dbt dl_tick                                                                                        " +
                   "                  JOIN ddlrq_dbt dlrq                                                                                         " +
                   "                  ON     dlrq.t_dockind = dl_tick.t_bofficekind                                                               " +
                   "                     AND dlrq.t_docid = dl_tick.t_dealid                                                                      " +
                   "                     AND dlrq.t_dealpart = 1                                                                                  " +
                   "                     AND dlrq.t_subkind = 1                                                                                   " +
                   "                     AND dlrq.t_type = 8                                                                                      " +
                   "                     AND dlrq.t_kind in (0,1)                                                                                 " + //MZ
                   "            WHERE      dl_tick.t_bofficekind = 127                                                                            " +
                   "                  AND dl_tick.t_clientcontrid in (select t_sfcontrid from W475_TMP)                                           " + // KS Оптимизация
                   "                  AND dlrq.t_factdate BETWEEN ? AND ? group by dl_tick.t_clientcontrid ) r                                    " +
                   "            ON (r.t_clientcontrid = w475.t_sfcontrid and t_sfcontridfm = 0) " +
                   "            when matched then " +
                   "            UPDATE SET t_p_plus = r.rest_plus, t_p_minus = r.rest_minus   "); //MZ
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    //EndAction;
    //BegAction(1, "9/21 Зачисления бумаг");
    UseProgress(9);
    cmdUpdateTmp.execute();
   // msgbox("9  "+time());

 /* 10  t_p_minus */
    message("10/21  t_p_minus");
    cmdUpdateTmp = RsdCommand(
                   " MERGE INTO W475_TMP w475                                                                                                              " +
                   "    using      (SELECT /*+ cardinality(d 100)*/ d.t_SfContrID, NVL (SUM (ROUND (rsb_secur.SC_ConvSumTypeRep (dlrq.t_factamount,dlrq.t_fiid,0,0,12,dlrq.t_factdate), 2)),0) rest" +
                   "             FROM W475_TMP d, ddl_tick_dbt dl_tick                " +
                   "                  JOIN ddlrq_dbt dlrq                             " +
                   "                  ON     dlrq.t_dockind = dl_tick.t_bofficekind   " +
                   "                     AND dlrq.t_docid = dl_tick.t_dealid          " +
                   "                     AND dlrq.t_dealpart = 1                      " +
                   "                     AND dlrq.t_subkind = 1                       " +
                   "                     AND dlrq.t_type = 8                          " +
                   "                     AND dlrq.t_kind = 1                          " +
                   "                     AND dlrq.t_factdate BETWEEN ? AND ? "+
                   "            WHERE d.t_SfContrID is not NULL AND d.t_SfContrID > 0     "+
                   "              AND dl_tick.t_bofficekind = 127                                                                             " +
                   "              AND dl_tick.t_ClientID = d.t_PartyID "+
                   "              AND dl_tick.t_ClientContrID = d.t_SfContrID "+
                   "            group by d.t_SfContrID ) r                                                                        "
                   "            ON (r.t_SfContrID = w475.t_sfcontrid and t_sfcontridfm = 0) "+
                   "            when matched then "+
                   "            UPDATE SET t_p_minus = r.rest   ");

    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
//    EndAction;
//    BegAction(1, "10/21 Списания бумаг");
//    UseProgress(11);
// MZ Перенес выше     cmdUpdateTmp.execute();
//    msgbox("10  "+time());

 
    /* 11  t_p_in */
    message("11/21  t_p_in");
    cmdUpdateTmp = RsdCommand(
                   "  MERGE INTO W475_TMP w475                                                                           " +
                   "  USING ( SELECT T_CONTRACT, NVL(T_SUM - CASE WHEN T_SUM != 0 THEN T_NKD ELSE 0 END,0) AS T_SUM      " +
                   "            FROM (SELECT /*+ leading(w PMWRTCL FIN) cardinality(w 100) */ PMWRTCL.T_CONTRACT,                            " +
                   "                         sum(nvl(round(t_amount* (select GetRate(PMWRTCL.t_fiid, 0,? - 1) from dual), 2), 0)) AS T_SUM,  " + //MZ
                   "                         sum(nvl(round(t_amount* (select getNKdAmount(PMWRTCL.t_fiid,? - 1,0) from dual),2),0)) AS T_NKD " + // Golovkin 24.04.2019 минус нкд //MZ
                   "          FROM DPMWRTCL_DBT PMWRTCL, DFININSTR_DBT FIN , W475_TMP  w  " +
                   "          WHERE (? - 1) BETWEEN PMWRTCL.T_BEGDATE AND PMWRTCL.T_ENDDATE " +
                   "            AND PMWRTCL.T_FIID = FIN.T_FIID   " +
                   "            AND t_amount != 0                 " + //MZ
                   "            and PMWRTCL.T_CONTRACT = w.t_sfcontrid " + // MZ
                   "            and PMWRTCL.T_PARTY = w.t_partyid " + // MZ
                   "          GROUP BY PMWRTCL.T_CONTRACT         " +
                   "        )) PMWRTCLSUM                         " +
                   "  ON (T_SFCONTRID = PMWRTCLSUM.T_CONTRACT)    " +
                   "  WHEN MATCHED THEN                           " +
                   "  UPDATE SET T_P_IN = PMWRTCLSUM.T_SUM        ");
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
//    EndAction;
//    BegAction(1, "11/21 Вложения бумаг входящий");
    UseProgress(10);
    cmdUpdateTmp.execute();
    //msgbox("11  "+time());

    /* 12  t_p_out */
    message("12/21  t_p_out");
    cmdUpdateTmp = RsdCommand(
                  "  UPDATE W475_TMP w475                                                                      " +
                 /*  "  SET w475.T_P_OUT = (SELECT NVL(T_SUM - CASE WHEN T_SUM != 0 THEN T_NKD ELSE 0 END,0) AS T_SUM " +
                   "                        FROM (SELECT sum(nvl(round(t_amount*(select GetRate(PMWRTCL.t_fiid, 0, ?) from dual), 2), 0)) AS T_SUM, " + //MZ
                   "                                     sum(nvl(round(t_amount* (select getNKdAmount(PMWRTCL.t_fiid,?,0) from dual),2),0)) AS T_NKD " + //MZ // Golovkin 24.04.2019 минус нкд */
		     		"   SET w475.T_P_OUT = (SELECT NVL(SUM (T_SUM - CASE WHEN T_SUM != 0 THEN T_NKD ELSE 0 END),0) AS T_SUM " +
					"                       FROM (SELECT nvl(round(t_amount*(select GetRate(PMWRTCL.t_fiid, 0, ?) from dual), 2), 0) AS T_SUM, " + //MZ
					"                                    nvl(round(t_amount* (select getNKdAmount(PMWRTCL.t_fiid,?,0) from dual),2),0) AS T_NKD " + //MZ // Golovkin 24.04.2019 минус нкд
                   "                                FROM DPMWRTCL_DBT PMWRTCL, DFININSTR_DBT FIN "+
                   "                               WHERE PMWRTCL.T_PARTY = w475.t_PartyID "+
                   "                                 AND PMWRTCL.T_CONTRACT = w475.t_SfContrID " +
                   "                                 AND PMWRTCL.T_BEGDATE <= ?       " +
                   "                                 AND PMWRTCL.T_ENDDATE >= ?   " +
                   "                                 AND PMWRTCL.T_AMOUNT != 0    " +
                   "                                 AND FIN.T_FIID = PMWRTCL.T_FIID         " +
                   "                              ))                                              ");

    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
   // EndAction;
   // BegAction(1, "12/21 Вложения бумаг исходящий");
    UseProgress(11);
    cmdUpdateTmp.execute();
    //msgbox("12  "+time());
   
// KS 17.06.2019 Для срочного рынка обороты за период
    message("12/21  t_turnsum");
    cmdUpdateTmp = RsdCommand(
                   " MERGE INTO W475_TMP W475  " +
                   "  using (select /*+ cardinality(w 100)*/ sfcontr.t_id t_id, nvl(sum(t_buy),0) t_buy, nvl(sum(t_sale),0) t_sale                                     " +
                   "           from ddvfiturn_dbt dvfiturn                                                                                           " +
                   "           join dsfcontr_dbt sfcontr on sfcontr.t_ServKind in (15/*15 Срочные контракты (ФИССИКО)*/, 21/*Валютный дилинг*/) and  " + // KS 20.03.2020
                   "                                        (sfcontr.t_DateClose = to_date('01.01.0001','dd.mm.yyyy') or sfcontr.t_DateClose >= ?)and" +
                   "                                       dvfiturn.t_clientcontr = sfcontr.t_id                                                     " +
                   "           join dsfcontr_dbt sfcontr2 on sfcontr2.t_ServKind = 0 and                                                             " +
                   "                                         (sfcontr2.t_DateClose = to_date('01.01.0001','dd.mm.yyyy') or sfcontr.t_DateClose >= ?) " +
                   "           join ddlcontr_dbt dlcontr on sfcontr2.t_id = dlcontr.t_sfcontrid AND dlcontr.t_iis <> 'X'                             " + /*22.01.2020 RAS:496347 */
                   "           join W475_TMP W on  sfcontr.t_id =  W.T_sfcontrid                                                                     " +
                   "           where sfcontr.t_partyid = sfcontr2.t_partyid and                                                                       " +
                   "                t_date between ? and ?                                                                                           " +
                   "          group by sfcontr.t_id) R                                                                                               " +
                   "  ON (R.t_id = W475.T_sfcontrid)                                                                                                 " +
                   "  WHEN MATCHED THEN                                                                                                              " +
                   "    UPDATE SET W475.t_turnsum = R.t_buy + R.t_sale ");
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    UseProgress(12);
    cmdUpdateTmp.execute();

// KS 23.03.2020 Для валютного рынка обороты за период
    if(m_Form.GetFieldValue(P_W475_CurrencyMarket) == "X")
      message("12/21  t_turnsum 2");

      cmdUpdateTmp = RsdCommand(
                     " MERGE INTO W475_TMP w475                                                   " +
                     "      USING (  SELECT dvn.t_clientcontr     t_clientcontrid,                " +
                     "                      NVL (SUM (RSI_RSB_FIInstr.ConvSum (dvnfi.t_cost,      " +
                     "                                                         dvnfi.t_pricefiid, " +
                     "                                                         0,                 " +
                     "                                                         dvn.t_date,        " +
                     "                                                         0)),               " +
                     "                           0) REST                                          " +
                     "                 FROM ddvndeal_dbt dvn, ddvnfi_dbt dvnfi                    " +
                     "                WHERE     dvn.t_date BETWEEN :1                             " +
                     "                                         AND :2                             " +
                     "                      AND dvn.t_dvkind IN (3, 6, 7)                         " +
                     "                      AND dvn.t_state IN (1, 2)                             " +
                     "                      AND dvnfi.t_dealid = dvn.t_id                         " +
                     "             GROUP BY dvn.t_clientcontr) r                                  " +
                     "         ON (r.t_clientcontrid = w475.t_sfcontrid)                          " +
                     " WHEN MATCHED                                                               " +
                     " THEN                                                                       " +
                     "     UPDATE SET W475.t_turnsum = R.REST                                     ");
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
       UseProgress(13);
	  cmdUpdateTmp.execute();
    end;

    /* 13  t_comsum */
    message("13/21  t_comsum");
    cmdUpdateTmp = RsdCommand(
             " MERGE INTO W475_TMP w475  " +
             "      USING ( select /*+ cardinality(d 100)*/ DLC.T_CONTRACT t_id , NVL (SUM (RSI_RSB_FIInstr.ConvSum (dlc.t_sum,cm.t_fiid_comm,0,dlc.t_factpaydate,1)),0) t_comsum " +
             "              FROM W475_TMP d join ddlcomis_dbt dlc  on  DLC.T_CONTRACT = d.t_sfcontrid                                        " +
             "                   JOIN dsfcomiss_dbt cm ON cm.t_FeeType = dlc.t_Feetype AND cm.t_Number = dlc.t_ComNumber AND cm.t_ReceiverID = ? " +
             "             WHERE  dlc.t_DocKind in (101, 4813)                                      " + // KS 20.03.2020 + 4813
             "                   AND dlc.t_factpaydate between ? AND ?  group by DLC.T_CONTRACT ) r " +
             "         ON (r.t_id = w475.t_sfcontrid)                          " +
             " WHEN MATCHED                                                               " +
             " THEN                                                                       " +
             "     UPDATE SET w475.t_comsum = R.t_comsum                                  ");

// Golovkin 25.04.2019 отбираем комиссии банка
//               "  UPDATE W475_TMP d  " +
//                  "     SET d.t_comsum =                                                                                                                " +
//                  "           (SELECT NVL (SUM (RSI_RSB_FIInstr.ConvSum (dlc.t_sum,cm.t_fiid_comm,0,dlc.t_factpaydate,1)),0)                          " +
//                  "              FROM ddlcomis_dbt dlc                                                                                                " +
//                  "                   JOIN dsfcomiss_dbt cm ON cm.t_FeeType = dlc.t_Feetype AND cm.t_Number = dlc.t_ComNumber AND cm.t_ReceiverID = ? " +
//                  "             WHERE     dlc.t_DocKind in (101, 4813)                                                                                " + // KS 20.03.2020 + 4813
//                  "                   AND DLC.T_CONTRACT = d.t_sfcontrid                                                                                " +
//                  "                   AND dlc.t_factpaydate between ? AND ? )                                                                         ");
    cmdUpdateTmp.AddParam("", RSDBP_IN, {ourbank});
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
   // EndAction;
   // BegAction(1, "13/21 Сумма комиссий");
    UseProgress(14);
    cmdUpdateTmp.execute();
    //msgbox("13  "+time());
    
// KS 17.06.2019 Для срочного рынка - комиссия брокера
//    cmdUpdateTmp = RsdCommand(" create table W475_TMP_kot as select * from W475_TMP" );
    cmdUpdateTmp.execute();
    cmdUpdateTmp = RsdCommand(
                   " MERGE INTO W475_TMP W475                                                                                                          " +
                   "  using (select sfcontr.t_id t_id, nvl(sum(t_sum),0) t_sumbr                                                                " +
                   "           from ddvdeal_dbt dvdeal                                                                                                 " +
                   "           join dsfcontr_dbt sfcontr on sfcontr.t_ServKind in (15/*15 Срочные контракты (ФИССИКО)*/, 21/*Валютный дилинг*/) and    " + // KS 20.03.2020
                   "                                        (sfcontr.t_DateClose = to_date('01.01.0001','dd.mm.yyyy') or sfcontr.t_DateClose >= ?) and " +
                   "                                        dvdeal.t_clientcontr = sfcontr.t_id                                                        " +
                   "           join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvdeal.t_kind and                                            " +
                   "                                          regexp_like(oprkoper.t_systypes, '[U|O]') and                                            " +
                   "                                          regexp_like(oprkoper.t_systypes, '[B|S]')                                                " +
                   "           left join doproper_dbt oproper on oproper.t_kind_operation = dvdeal.t_kind and                                          " +
                   "                                             oproper.t_documentid = lpad(dvdeal.t_id, 34, '0')                                     " +
                   "           join dsfcontr_dbt sfcontr2 on sfcontr2.t_ServKind = 0 and                                                               " +
                   "                                         (sfcontr2.t_DateClose = to_date('01.01.0001','dd.mm.yyyy') or sfcontr2.t_DateClose >= ?)  " +
                   "           join ddlcontr_dbt dlcontr on sfcontr2.t_id = dlcontr.t_sfcontrid AND dlcontr.t_iis <> 'X'                               " + /*22.01.2020 RAS:496347*/
                   "           join ddvdlcom_dbt dvdlcom on dvdlcom.t_dealid = dvdeal.t_id                                                             " +
                   "           join dsfcomiss_dbt sfcomiss on sfcomiss.t_comissid = dvdlcom.t_comissid                                                 " +
                   "           join ddp_dep_dbt dp_dep on dp_dep.t_partyid = sfcomiss.t_receiverid                                                     " +
                   "          where dvdeal.t_state > 0 and                                                                                             " +
                   "                dvdeal.t_date <= ? and                                                                                             " +
                   "                (oproper.t_end_date is null or oproper.t_end_date >= ?) and                                                        " +
                   "                sfcontr.t_partyid = sfcontr2.t_partyid                                                                             " +
                   "           group by sfcontr.t_id) R                                                                                         " +
                   "  ON (R.t_id = W475.T_sfcontrid)                                                                                                 " +
                   "  WHEN MATCHED THEN                                                                                                              " +
                   "    UPDATE SET W475.t_comsum = R.t_sumbr ");
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    UseProgress(15);

    cmdUpdateTmp.execute();

/* Хороший селект для комиссий по валютному рынку, да и вообще... На будущее
select sum(dlc.t_sum)
  from ddlcomis_dbt dlc, dsfcomiss_dbt sfc, ddvndeal_dbt dvn
 where dlc.t_docid = dvn.t_id
   and dlc.t_dockind = dvn.t_dockind
   and dlc.t_feetype = sfc.t_feetype
   and dlc.t_comnumber = sfc.t_number
   and dvn.t_client = 134399
   and dvn.t_clientcontr = 30448
   and dvn.t_date between to_date('17012020', 'DDMMYYYY') AND to_date('21012020', 'DDMMYYYY')
   and dvn.t_dvkind in (3, 6, 7)
   and dvn.t_state in (1, 2)
--   and upper(sfc.t_code) like 'МСКБ_ВБ_ДН%'
*/


    /* 14  t_comsumrepo */
    message("14/21  t_comsumrepo");
    cmdUpdateTmp = RsdCommand(
                   " MERGE INTO W475_TMP W475  " +
                   "  using ( SELECT /*+ cardinality(d 100)*/ DLC.T_CONTRACT t_id , NVL (SUM (RSI_RSB_FIInstr.ConvSum (dlc.t_sum, cm.t_fiid_comm,0,dlc.t_factpaydate,1)),0)  t_comsumrepo " +
                   "          FROM W475_TMP d, ddl_tick_dbt dl_tick, ddlcomis_dbt dlc                                                                         " +
                   "                  JOIN dsfcomiss_dbt cm ON cm.t_FeeType = dlc.t_Feetype AND cm.t_Number  = dlc.t_ComNumber AND cm.t_ReceiverID = ? " +
                   "             WHERE     dl_tick.t_BOfficeKind = 101                                                                                 " +
                   "                   AND dl_tick.t_ClientID > 0 " +
                   "                   AND dlc.t_DocKind = dl_tick.t_bofficekind " +
                   "                   AND dlc.t_docid = dl_tick.t_dealid "+
                   "                   AND DLC.T_CONTRACT = d.t_sfcontrid                                                                                " +
                   "                   AND dlc.t_factpaydate  BETWEEN ? AND ?                                                                          " +
                   "                   AND rsb_secur.IsRepo (rsb_secur.get_operationgroup (rsb_secur.get_opersystypes (dl_tick.t_dealtype,dl_tick.t_bofficekind))) != 0 "+
				   "           group by DLC.T_CONTRACT) r "+
                   "  ON (R.t_id = W475.T_sfcontrid)                                                                                                 " +
                   "  WHEN MATCHED THEN                                                                                                              " +
                   "    UPDATE SET W475.t_comsumrepo = R.t_comsumrepo " );



                   // Golovkin 25.04.2019 отбираем комиссии банка по РЕПО
//                   "  UPDATE W475_TMP d " +
//                   "     SET d.t_comsumrepo =  " +
//                   "           (SELECT  NVL (SUM (RSI_RSB_FIInstr.ConvSum (dlc.t_sum, cm.t_fiid_comm,0,dlc.t_factpaydate,1)),0)                        " +
//                   "              FROM  ddl_tick_dbt dl_tick, ddlcomis_dbt dlc                                                                         " +
//                   "                  JOIN dsfcomiss_dbt cm ON cm.t_FeeType = dlc.t_Feetype AND cm.t_Number  = dlc.t_ComNumber AND cm.t_ReceiverID = ? " +
//                   "             WHERE     dl_tick.t_BOfficeKind = 101                                                                                 " +
//                   "                   AND dl_tick.t_ClientID > 0 " +
//                   "                   AND dlc.t_DocKind = dl_tick.t_bofficekind " +
//                   "                   AND dlc.t_docid = dl_tick.t_dealid "+
//                   "                   AND DLC.T_CONTRACT = d.t_sfcontrid                                                                                " +
//                   "                   AND dlc.t_factpaydate  BETWEEN ? AND ?                                                                          " +
//                   "                   AND rsb_secur.IsRepo (rsb_secur.get_operationgroup (rsb_secur.get_opersystypes (dl_tick.t_dealtype,dl_tick.t_bofficekind))) != 0) ");
    cmdUpdateTmp.AddParam("", RSDBP_IN, {ourbank});
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
   // EndAction;
   // BegAction(1, "14/21 Комиссии Репо");
    UseProgress(16);
    cmdUpdateTmp.execute();
    //msgbox("14  "+time());  
      
      /* 15  t_comsumsvop */           
      message("15/21  t_comsumsvop");
      if(m_Form.GetFieldValue(P_W475_CurrencyMarket) == "X") 
      cmdUpdateTmp = RsdCommand(
			  //PDV  08.06.20  
                     " MERGE INTO W475_TMP W475                                                                                                        " +
                     "  using (select dvn.t_clientcontr t_id, sum(dlc.t_sum) t_svop_sum                                                                " +
                     "            from ddlcomis_dbt dlc, dsfcomiss_dbt sfc, ddvndeal_dbt dvn                                                           " +
                     "        where dlc.t_docid = dvn.t_id and dlc.t_dockind = dvn.t_dockind and dlc.t_feetype = sfc.t_feetype                         " +
                     "             and dlc.t_comnumber = sfc.t_number and dvn.t_date between ? AND ? and dvn.t_dvkind in (3, 6, 7)                      " +
                     "             and dvn.t_state in (1, 2) and upper(sfc.t_code) like 'МСКБ_ВБ_СП%'                                                  " +
                     "         group by dvn.t_clientcontr)R " +                                                                          
                     "  ON (R.t_id = W475.T_sfcontrid)                                                                                                 " +
                     "  WHEN MATCHED THEN                                                                                                              " +
                     "  UPDATE SET W475.T_COMSUMSVOP = R.t_svop_sum ");
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);   
    // EndAction;
    // BegAction(1, "15/21 Комиссии СВОП");
      cmdUpdateTmp.execute();
     end;

    /* 16  t_special_repo */
    message("17/21  t_special_repo");
    cmdUpdateTmp = RsdCommand(
          "MERGE INTO W475_TMP  W475 " +
          "     USING (  SELECT /*+ cardinality(d 100)*/ d.t_SfContrID, " +
          "                     NVL (SUM (RSI_RSB_FIInstr.ConvSum (dlrq.t_factamount, " +
          "                                                        dlrq.t_fiid, " +
          "                                                        0, " +
          "                                                        dlrq.t_factdate, " +
          "                                                        1 " +
          "                                                       )), " +
          "                          0 " +
          "                         ) " +
          "                        sumperc " +
          "                FROM W475_TMP d, "+
          "                     (select t_Kind_Operation, " +
          "                             rsb_secur.IsRepo(rsb_secur.get_operationgroup (rsb_secur.get_opersystypes(t_Kind_Operation, t_DocKind))) as IsRepo"+
          "                        from doprkoper_dbt "+
          "                       where t_DocKind = 101 "+
          "                     ) Opr, " +
          "                     ddl_tick_dbt dl_tick " +
          "                     JOIN " +
          "                        ddlrq_dbt dlrq " +
          "                     ON     dlrq.t_dockind = dl_tick.t_bofficekind " +
          "                        AND dlrq.t_docid = dl_tick.t_dealid " +
          "                        AND dlrq.t_subkind = 0 " +
          "                        AND dlrq.t_type = 3 " +
          "                        AND dlrq.t_kind = 1 " +
          "                        AND dlrq.t_factdate BETWEEN :begdate AND :enddate " +
          "               WHERE d.t_SfContrID is not NULL AND d.t_SfContrID > 0 " +
          "                     AND dl_tick.t_bofficekind = 101 " +
          "                     AND dl_tick.t_ClientID = d.t_PartyID "+
          "                     AND dl_tick.t_ClientContrID = d.t_SfContrID "+
          "                     AND Opr.t_Kind_Operation = dl_tick.t_DealType "+
          "                     AND Opr.IsRepo != 0 " +
          "                     AND EXISTS " +
          "                            (SELECT 1 " +
          "                               FROM dobjatcor_dbt atcor " +
          "                              WHERE     atcor.t_objecttype = 101 " +
          "                                    AND atcor.t_groupid = 103 " +
          "                                    AND atcor.t_object = LPAD (dl_tick.t_dealid, 34, 0) " +
          "                                    AND atcor.t_attrid = " +
          "                                           (SELECT objattr.t_attrid " +
          "                                              FROM DOBJATTR_DBT objattr " +
          "                                             WHERE atcor.t_objecttype = " +
          "                                                      objattr.t_objecttype " +
          "                                                   AND atcor.t_groupid = " +
          "                                                          objattr.t_groupid " +
          "                                                   AND LOWER (objattr.t_name) = " +
          "                                                          'да')) " +
          "            GROUP BY d.t_SfContrID) r " +
          "        ON (r.t_SfContrID = W475.t_sfcontridsm " +
          "            AND 1 = " +
          "                   CASE " +
          "                      WHEN W475.T_SFCONTRIDSM = 0 THEN 0 " +
          "                      WHEN r.t_SfContrID = W475.T_SFCONTRIDSM THEN 1 " +
          "                      ELSE 0 " +
          "                   END) " +
          "WHEN MATCHED " +
          "THEN " +
          "   UPDATE SET W475.t_special_repo = r.sumperc " );
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
//    EndAction;
//    BegAction(1, "16/21 Специальные Репо");
    UseProgress(17);
    cmdUpdateTmp.execute();   
    //msgbox("16  "+time());  

    
        //PDV 080620
       message("17/21  t_sum_svop");
       if(m_Form.GetFieldValue(P_W475_CurrencyMarket) == "X")
       cmdUpdateTmp = RsdCommand(
                     " MERGE INTO W475_TMP W475 " +
                     "  using (SELECT /*+ cardinality(w 100)*/ a.t_id t_id1,(sum(b.cost)-sum(a.cost)) T_sum_val "+
                     "           FROM W475_TMP w join (select dvn.t_clientcontr t_id,dvnfi.t_cost cost, dvn.t_id deal  "+
                     "                   from ddvnfi_dbt dvnfi, ddvndeal_dbt dvn  "+                                                                                 
                     "                   where dvn.t_kind = 32715 and dvn.t_type = 6 and dvn.t_id = dvnfi.t_dealid and dvnfi.t_type= 0 and dvnfi.t_execdate between :D AND :D1 and dvn.t_date >= :D  and dvn.t_state = 2  " +
                     "                 union    " +
                     "                 select dvn.t_clientcontr t_id,dvnfi.t_cost cost, dvn.t_id deal  " +
                     "                   from ddvnfi_dbt dvnfi, ddvndeal_dbt dvn  " +
                     "                   where dvn.t_kind = 32715 and dvn.t_type = 5 and dvn.t_id = dvnfi.t_dealid and dvnfi.t_type= 2 and dvnfi.t_execdate between :D AND :D1 and dvn.t_date >= :D  and dvn.t_state = 2  " +             
                     "                ) a  on w.T_sfcontrid = a.t_id " +
                     "           INNER JOIN (select dvn.t_clientcontr t_id,dvnfi.t_cost cost, dvn.t_id deal  " +
                     "                         from ddvnfi_dbt dvnfi, ddvndeal_dbt dvn " +
                     "                         where dvn.t_kind = 32715 and dvn.t_type = 6 and dvn.t_id = dvnfi.t_dealid and dvnfi.t_type= 2 and dvn.t_state = 2  " +
                     "                       union  " +
                     "                       select dvn.t_clientcontr t_id,dvnfi.t_cost cost, dvn.t_id deal  " +
                     "                         from ddvnfi_dbt dvnfi, ddvndeal_dbt dvn  " +
                     "                         where dvn.t_kind = 32715 and dvn.t_type = 5 and dvn.t_id = dvnfi.t_dealid and dvnfi.t_type= 0 and dvn.t_state = 2  " +    
                     "                       ) b " +
                     "           ON a.deal = b.deal " +
                     "  group by a.t_id   )R "+                     
                     "  ON (R.t_id1 = W475.T_sfcontrid)  " +
                     "  WHEN MATCHED THEN                " +
                     "  UPDATE SET W475.T_VAL_SVOP = R.t_sum_val ");
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
      cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
      UseProgress(18);
      cmdUpdateTmp.execute();
      end;
    // Golovkin Название договора, если УК
    message("19/21  t_clientname");
    cmdUpdateTmp = RsdCommand(
                   " UPDATE W475_TMP w  " +
                   "    SET T_CLIENTNAME = (SELECT T_NAME                             " +
                   "                          FROM DSFCONTR_DBT SF                    " +
                   "                         WHERE SF.t_id = w.t_Sfcontrid)           " +
                   "  WHERE EXISTS                                                    " +
                   "           (SELECT 1                                              " +
                   "              FROM DSFCONTR_DBT SF, DPARTYOWN_DBT PO              " +
                   "             WHERE SF.t_id = w.t_Sfcontrid                    " +
                   "               AND po.t_PartyID = sf.t_partyid AND po.t_partykind = 65) ");
  //  EndAction;
  //  BegAction(1,"18/21 Корректировка наименований");
    UseProgress(19);
    cmdUpdateTmp.execute();
   // msgbox("18  "+time());

//    EndAction;

    /*   t_comsumBank Комиссия уплаченная банком по сделкам клиента не репо */
    message("20/21  t_comsumBank");
    cmdUpdateTmp = RsdCommand(
                  "  UPDATE W475_TMP d                                                                                                                  " +
                  "     SET d.t_comsumBank =                                                                                                                " +
                  "           ((SELECT NVL (SUM (RSI_RSB_FIInstr.ConvSum (dlc.t_sum,cm.t_fiid_comm,0,dlc.t_factpaydate,1)),0)                         " +
                  "              FROM ddl_tick_dbt tick, ddlcomis_dbt dlc,                                                                             " +
                  "                    dsfcomiss_dbt cm  " +
                  "             WHERE tick.t_BOfficeKind = 101 "+
                  "               AND tick.t_ClientID = d.t_PartyID "+
                  "               AND tick.T_clientcontrid = d.t_sfcontrid                                                                          " +
                  "               AND dlc.t_DocKind = tick.t_bofficekind AND dlc.t_docid = tick.t_dealid AND dlc.T_ISBANKEXPENSES = 'X'                                                              " + 
                  "               AND cm.t_FeeType = dlc.t_Feetype AND cm.t_Number = dlc.t_ComNumber AND cm.t_ReceiverID != ?                            " +
                  "               AND rsb_secur.IsRepo (rsb_secur.get_operationgroup (rsb_secur.get_opersystypes (tick.t_dealtype,tick.t_bofficekind))) = 0  " +
                  "               AND dlc.t_factpaydate between ? AND ? ) +                                                                           " +
                  "           (SELECT NVL (SUM (RSI_RSB_FIInstr.ConvSum (dlc.t_sum,cm.t_fiid_comm,0,dlc.t_factpaydate,1)),0)                          " +
                  "              FROM ddlcomis_dbt dlc, ddvndeal_dbt tick,                                                                            " +
                  "                    dsfcomiss_dbt cm                                                                                               " +
                  "             WHERE dlc.t_DocKind = 4813 AND dlc.T_ISBANKEXPENSES = 'X'                                                             " + 
                  "               AND cm.t_FeeType = dlc.t_Feetype AND cm.t_Number = dlc.t_ComNumber AND cm.t_ReceiverID != ?                         " +
                  "               AND tick.T_client = d.t_partyid                                                                                     " +
                  "               AND tick.T_clientcontr = d.t_sfcontrid                                                                                " +
                  "               and tick.t_dockind =   dlc.t_DocKind AND tick.t_id = dlc.t_docid                                                    " +
                  "               AND dlc.t_factpaydate between ? AND ? ))                                                                            ");

    cmdUpdateTmp.AddParam("", RSDBP_IN, {ourbank});
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, {ourbank});
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.execute();

    //Добавим сюда срочку
    message("20/21  t_comsumBank 2");
    cmdUpdateTmp = RsdCommand(
                   " MERGE INTO W475_TMP W475                                                                                                          " +
                   "  using (select sfcontr.t_id t_id, nvl(sum(t_sum),0) t_sumbr                                                                       " +
                   "           from ddvdeal_dbt dvdeal                                                                                                 " +
                   "           join dsfcontr_dbt sfcontr on sfcontr.t_ServKind in (15/*15 Срочные контракты (ФИССИКО)*/, 21/*Валютный дилинг*/) and    " + 
                   "                                        (sfcontr.t_DateClose = to_date('01.01.0001','dd.mm.yyyy') or sfcontr.t_DateClose >= ?) and " +
                   "                                        dvdeal.t_clientcontr = sfcontr.t_id                                                        " +
                   "           join doprkoper_dbt oprkoper on oprkoper.t_kind_operation = dvdeal.t_kind and                                            " +
                   "                                          regexp_like(oprkoper.t_systypes, '[U|O]') and                                            " +
                   "                                          regexp_like(oprkoper.t_systypes, '[B|S]')                                                " +
                   "           left join doproper_dbt oproper on oproper.t_kind_operation = dvdeal.t_kind and                                          " +
                   "                                             oproper.t_documentid = lpad(dvdeal.t_id, 34, '0')                                     " +
                   "           join dsfcontr_dbt sfcontr2 on sfcontr2.t_ServKind = 0 and                                                               " +
                   "                                         (sfcontr2.t_DateClose = to_date('01.01.0001','dd.mm.yyyy') or sfcontr2.t_DateClose >= ?)  " +
                   "           join ddlcontr_dbt dlcontr on sfcontr2.t_id = dlcontr.t_sfcontrid AND dlcontr.t_iis <> 'X'                               " + 
                   "           join ddvdlcom_dbt dvdlcom on dvdlcom.t_dealid = dvdeal.t_id AND dvdlcom.T_ISBANKEXPENSES = 'X'                          " +
                   "           join dsfcomiss_dbt sfcomiss on sfcomiss.t_comissid = dvdlcom.t_comissid and sfcomiss.t_ReceiverID != ?                  " +
                   "           join ddp_dep_dbt dp_dep on dp_dep.t_partyid = sfcomiss.t_receiverid                                                     " +
                   "          where dvdeal.t_state > 0 and                                                                                             " +
                   "                dvdeal.t_date <= ? and                                                                                             " +
                   "                (oproper.t_end_date is null or oproper.t_end_date >= ?) and                                                        " +
                   "                sfcontr.t_partyid = sfcontr2.t_partyid                                                                             " +
                   "           group by sfcontr.t_id) R                                                                                                " +
                   "  ON (R.t_id = W475.T_sfcontrid)                                                                                                   " +
                   "  WHEN MATCHED THEN                                                                                                                " +
                   "    UPDATE SET W475.t_comsumBank = W475.t_comsumBank + R.t_sumbr ");                                                                     
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, {ourbank});
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    UseProgress(20);
    cmdUpdateTmp.execute();

    /*   t_comsumBankRepo Комиссия уплаченная банком по сделкам клиента по сделкам репо */
    message("21/21  t_comsumBankRepo");
    cmdUpdateTmp = RsdCommand(
                  "  UPDATE W475_TMP d " +
                  "     SET d.t_comsumBankRepo =                                                                               " +
                  "           (SELECT NVL (SUM (RSI_RSB_FIInstr.ConvSum (dlc.t_sum,cm.t_fiid_comm,0,dlc.t_factpaydate,1)),0)   " +
                  "              FROM ddl_tick_dbt tick, ddlcomis_dbt dlc, dsfcomiss_dbt cm   " +
                  "             WHERE tick.t_BOfficeKind = 101 "+
                  "               AND tick.t_ClientID = d.t_PartyID "+
                  "               AND tick.T_clientcontrid = d.t_sfcontrid " +
                  "               AND rsb_secur.IsRepo (rsb_secur.get_operationgroup (rsb_secur.get_opersystypes (tick.t_dealtype,tick.t_bofficekind))) != 0  " +
                  "               AND dlc.t_DocKind = tick.t_bofficekind AND dlc.t_docid = tick.t_dealid  " +
                  "               AND dlc.T_ISBANKEXPENSES = 'X'                                                              " + 
                  "               AND cm.t_FeeType = dlc.t_Feetype AND cm.t_Number = dlc.t_ComNumber AND cm.t_ReceiverID != ? " +
                  "                   AND dlc.t_factpaydate between ? AND ? ) ");
    cmdUpdateTmp.AddParam("", RSDBP_IN, {ourbank});
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_BeginDate);
    cmdUpdateTmp.AddParam("", RSDBP_IN, m_DateEnd);
    UseProgress(21);
    cmdUpdateTmp.execute();


    RemProgress;

    //m_RS = TRsbDataSet(m_DS);
    InitProgress(-1,"Печать...","Печать...");
    message("Печать...");

/*Отключаем все индикаторы*/
    if(m_UseTemplate)
      m_ObjTemplateXLS.SetFlagShowIndicator(false);
    else
      __BUG_Global_m_ObjTemplateXLS.SetFlagShowIndicator(false);

    end;
    //m_ProgressIndicator = CreateProgressIndicator(true);

     /* Курсы */    
    var usd_rate = 0.0, eur_rate = 0.0;
    var rate_cmd = RSDCommand(" select RSI_RSB_FIInstr.ConvSum (10000, 7 ,0, ? ,1)/10000 usdrate,  RSI_RSB_FIInstr.ConvSum (10000, 8 ,0, ? ,1)/10000 eurrate from dual " );
        rate_cmd.AddParam("",RSDBP_IN,m_DateEnd);
        rate_cmd.AddParam("",RSDBP_IN,m_DateEnd);
    var rate_rs = RsdRecordSet(rate_cmd);
    if (rate_rs.movenext())
       usd_rate = rate_rs.value("usdrate");
       eur_rate = rate_rs.value("eurrate");
    end;


/*Лист "Результаты БО для ДРРК"*/
    SetActiveSheet("Результаты БО для ДРРК");
    PrintFormatString( "", "ReportName1", "Результаты брокерского обслуживания клиентов за период с " + m_BeginDate + " по " + m_DateEnd);
    PrintFormatString( "", "ReportName2", "Курсы валют для  расчетов USD: " +string(usd_rate:8:4)+ "  Euro: " + string(eur_rate:8:4));

    SetActiveSheet("Результаты БО для ДРРК");

    RegisterTable( "ReportRow", "",
            /* 1*/ "Field01", 
            /* 2*/ "Field25", 
            /* 3*/ "Field02", 
            /* 4*/ "Field03", 
            /* 5*/ "Field04", 
            /* 6*/ "Field05", 
            /* 7*/ "FieldBorn",
            /* 8*/ "Field06", 
            /* 9*/ "Field07", 
            /* 10*/ "Field08", 
            /* 11*/ "Field09", 
            /*12*/ "Field10", 
            /*13*/ "Field11", 
            /*14*/ "Field12", 
            /*15*/ "Field13", 
            /*16*/ "Field14", 
            /*17*/ "Field15", 
            /*18*/ "Field16", 
            /*19*/ "Field17", 
            /*20*/ "Field18", 
            /*21*/ "Field19", 
            /*22*/ "Field20", 
            /*23*/ "Field21", 
            /*24*/ "Field21_1",
            /*25*/ "Field21_2",
            /*26*/ "Field22", 
            /*27*/ "Field22_1", 
            /*28*/ "Field22_2", 
            /*29*/ "Field23", 
            /*30*/ "Field24");

    SetActiveSheet("Результаты БО для ДРРК");

    m_RS = TRsbDataSet("SELECT * FROM W475_TMP order by t_clientname, t_contrnumber, t_dlcontrid, t_marketname");
    while(m_RS.MoveNext())
     /* if(dlcontrid != m_RS.value("t_dlcontrid"))
        if((dlcontrid > 0) and (subdognum > 1))
          this.MergeRow("Field01", "Field01", row - subdognum, row - 1, 15);
          this.MergeRow("Field02", "Field02", row - subdognum, row - 1, 15);
          this.MergeRow("Field03", "Field03", row - subdognum, row - 1, 15);
          this.MergeRow("Field04", "Field04", row - subdognum, row - 1, 15);
          this.MergeRow("Field05", "Field05", row - subdognum, row - 1, 15);
          this.MergeRow("Field06", "Field06", row - subdognum, row - 1, 15);
          this.MergeRow("Field07", "Field07", row - subdognum, row - 1, 15);
        end;*/
        dlcontrid = m_RS.value("t_dlcontrid");
        dognum = dognum + 1;
        subdognum = 1;
        m_dognum = dognum;
        m_contrnumber = m_RS.value("t_contrnumber");
        m_cft_kod = m_RS.value("kod_cft");  
        m_contrdatebegin = date(m_RS.value("t_contrdatebegin"));
        m_planname = m_RS.value("t_planname");
        m_clientname = m_RS.value("t_clientname");
        m_clientcode = m_RS.value("t_clientcode");
        m_depname = m_RS.value("t_depname");
		//MZ>>
        //m_borndate = GetBornDate(m_RS.value("t_sfcontrid"));
        m_borndate = m_RS.value("born_date");
	    //MZ
		/* 
	 else
        subdognum = subdognum + 1;
        m_dognum = "";
        m_contrnumber = "";
        m_cft_kod = ""; 
        m_contrdatebegin = "";
        m_planname = "";
        m_clientname = "";
        m_clientcode = "";
        m_depname = "";
      end;*/
      /*Активы*/

      //Golovkin Изменение стоимости активов
      var АктивыКлиентаНаНачалоПериода = (m_RS.value("t_ds_in")  + m_RS.value("t_p_in")),
          АктивыКлиентаНаКонецПериода  = (m_RS.value("t_ds_out") + m_RS.value("t_p_out")),   
          ЗачислениеДСнаБрокерскийСчет = m_RS.value("t_ds_plus"),
          ВыводДСсБрокерскогоСчета = m_RS.value("t_ds_minus"),
          ЗачислениеЦБнаСчетДепоИзСторДепозит = m_RS.value("t_p_plus"),
          ВыводЦБсоСчетаДепоВСторДепозит = m_RS.value("t_p_minus");
      var sfcontrid = 0, m_RS1;/*GAA:503753*/

      if((АктивыКлиентаНаНачалоПериода+ЗачислениеДСнаБрокерскийСчет+ЗачислениеЦБнаСчетДепоИзСторДепозит) > 0)
        m_restperc = (АктивыКлиентаНаКонецПериода-
                      АктивыКлиентаНаНачалоПериода-
                      ЗачислениеДСнаБрокерскийСчет-
                      ЗачислениеЦБнаСчетДепоИзСторДепозит+
                      ВыводДСсБрокерскогоСчета+
                      ВыводЦБсоСчетаДепоВСторДепозит) /
                     (АктивыКлиентаНаНачалоПериода+
                      ЗачислениеДСнаБрокерскийСчет+
                      ЗачислениеЦБнаСчетДепоИзСторДепозит);
      else
        m_restperc = 0;
      end;

      /*Строка отчета*/
      PrintTableLine(
          /* 1*/ "Field01", m_dognum, null,  
          /* 2*/ "Field25", m_cft_kod, null,  
          /* 3*/ "Field02", m_contrnumber, null,
          /* 4*/ "Field03", m_contrdatebegin, null,
          /* 5*/ "Field04", m_planname, null,
          /* 6*/ "Field05", m_clientname, null,
          /* 7*/ "FieldBorn", m_borndate, null,
          /* 8*/ "Field06", m_clientcode, null,
          /* 9*/ "Field07", m_depname, null,
//        /* 8*/ "Field08", "Пока не заполняем", null, // Golovkin t_depcode
          /* 10*/ "Field08", m_RS.value("t_depcode"), null, // 
          /*11*/ "Field09", m_RS.value("t_finname"), null,
          /*12*/ "Field10", m_RS.value("t_marketname"), null,
          /*13*/ "Field11", m_RS.value("t_ds_plus"), null,//2,
          /*14*/ "Field12", m_RS.value("t_p_plus"), null,//2,
          /*15*/ "Field13", m_RS.value("t_ds_minus"), null,//2,
          /*16*/ "Field14", m_RS.value("t_p_minus"), null,//2,
          /*17*/ "Field15", m_RS.value("t_ds_plus") + m_RS.value("t_p_plus") - m_RS.value("t_ds_minus") - m_RS.value("t_p_minus"), null,//2,
          /*18*/ "Field16", m_RS.value("t_ds_in") + m_RS.value("t_p_in"), null,//2,
          /*19*/ "Field17", m_RS.value("t_ds_out") + m_RS.value("t_p_out"), null,//2,
          /*20*/ "Field18", m_restperc, null,
          /*21*/ "Field19", m_RS.value("t_turnsum")-m_RS.value("t_turnsumrepo") - m_RS.value("t_turnsumsvop"), null,//2,
          /*22*/ "Field20", m_RS.value("t_turnsumrepo"), null,//2,
          /*23*/ "Field21",   m_RS.value("t_comsum") + m_RS.value("t_comsumsvop") - m_RS.value("t_comsumrepo"), null,//2,
          /*24*/ "Field21_1", m_RS.value("t_comsumBank"), null,//2,
          /*25*/ "Field21_2", m_RS.value("t_comsum") + m_RS.value("t_comsumsvop") - m_RS.value("t_comsumrepo") - m_RS.value("t_comsumBank"), null,//2,
          /*26*/ "Field22", 0 + m_RS.value("t_comsumrepo"), null,//2,
          /*27*/ "Field22_1", m_RS.value("t_comsumBankRepo"), null,//2,
          /*28*/ "Field22_2", 0 + m_RS.value("t_comsumrepo") - m_RS.value("t_comsumBankRepo"), null,//2,
          /*29*/ "Field23", m_RS.value("t_special_repo") + m_RS.value("t_val_svop"), null,//2,
          /*30*/ "Field24", m_RS.value("t_comsum") - m_RS.value("t_comsumBank")+m_RS.value("t_special_repo")+ m_RS.value("t_val_svop") + m_RS.value("t_comsumsvop") - m_RS.value("t_comsumBankRepo"), null);//2);
      row = row + 1;
      UseProgress(row);
    end;

 //MZ Перенес ниже   RemProgress;

/*    
    message("MergeRow");
    if((dlcontrid > 0) and (subdognum > 1))
      this.MergeRow("Field01", "Field01", row - subdognum, row - 1, 15);
      this.MergeRow("Field02", "Field02", row - subdognum, row - 1, 15);
      this.MergeRow("Field03", "Field03", row - subdognum, row - 1, 15);
      this.MergeRow("Field04", "Field04", row - subdognum, row - 1, 15);
      this.MergeRow("Field05", "Field05", row - subdognum, row - 1, 15);
      this.MergeRow("Field06", "Field06", row - subdognum, row - 1, 15);
      this.MergeRow("Field07", "Field07", row - subdognum, row - 1, 15);
    end;
*/

    m_RS = null;
    m_RS = TRsbDataSet("SELECT nvl(sum(t_ds_plus),0) t_ds_plus, " + 
                        "  nvl(sum(t_p_plus),0) t_p_plus, " + 
                        "  nvl(sum(t_ds_minus),0) t_ds_minus, " + 
                        "  nvl(sum(t_p_minus),0) t_p_minus, " + 
                        "  nvl(sum(t_ds_plus + t_p_plus - t_ds_minus - t_p_minus),0) f15, " + 
                        "  nvl(sum(t_ds_in + t_p_in),0) f16, " + 
                        "  nvl(sum(t_ds_out + t_p_out),0) f17, " + 
                        "  nvl(sum(t_turnsum-t_turnsumrepo-t_turnsumsvop),0) t_turnsum, " + 
                        "  nvl(sum(t_turnsumrepo),0) t_turnsumrepo, " + 
                        "  nvl(sum(t_turnsumsvop),0) t_turnsumsvop, " +
                        "  nvl(sum(t_comsum),0) t_comsum, " + 
                        "  nvl(sum(t_comsumrepo),0) t_comsumrepo, " +
                        "  nvl(sum(t_comsumsvop),0) t_comsumsvop, " + 
                        "  nvl(sum(t_special_repo),0) t_special_repo, " +
                        "  nvl(sum(t_val_svop),0) t_val_svop, " + 
                        "  nvl(sum(t_comsum + t_special_repo +t_val_svop +t_comsumsvop - t_comsumBank - t_comsumBankRepo),0) f24, " + 
                        "  nvl(sum(t_comsumBank),0) f23, " + 
                        "  nvl(sum(t_comsumBankRepo),0) f25 " + 
                        " FROM W475_TMP order by t_clientname, t_contrnumber, t_dlcontrid, t_marketname");
    if(m_RS.MoveNext())
          АктивыКлиентаНаНачалоПериода = m_RS.value("f16");
          АктивыКлиентаНаКонецПериода  = m_RS.value("f17");   
          ЗачислениеДСнаБрокерскийСчет = m_RS.value("t_ds_plus");
          ВыводДСсБрокерскогоСчета = m_RS.value("t_ds_minus");
          ЗачислениеЦБнаСчетДепоИзСторДепозит = m_RS.value("t_p_plus");
          ВыводЦБсоСчетаДепоВСторДепозит = m_RS.value("t_p_minus");
 

      if((АктивыКлиентаНаНачалоПериода+ЗачислениеДСнаБрокерскийСчет+ЗачислениеЦБнаСчетДепоИзСторДепозит) > 0)
        m_restperc = (АктивыКлиентаНаКонецПериода-
                      АктивыКлиентаНаНачалоПериода-
                      ЗачислениеДСнаБрокерскийСчет-
                      ЗачислениеЦБнаСчетДепоИзСторДепозит+
                      ВыводДСсБрокерскогоСчета+
                      ВыводЦБсоСчетаДепоВСторДепозит) /
                     (АктивыКлиентаНаНачалоПериода+
                      ЗачислениеДСнаБрокерскийСчет+
                      ЗачислениеЦБнаСчетДепоИзСторДепозит);
      else
        m_restperc = 0;
      end;

      PrintTableLine(
          /* 1*/ "Field01", "", null,
          /* 2*/ "Field25", "", null,
          /* 3*/ "Field02", "", null,
          /* 4*/ "Field03", "", null,
          /* 5*/ "Field04", "", null,
          /* 6*/ "Field05", "", null,
          /* 7*/ "FieldBorn", "", null, //Chesnokov D.S. Определим дату рождения для клиента по договору, если нет то пусто
          /* 8*/ "Field06", "", null,
          /* 9*/ "Field07", "", null,
          /* 10*/ "Field08", "", null, // 
          /*11*/ "Field09", "", null,
          /*12*/ "Field10", "", null,
          /*13*/ "Field11", m_RS.value("t_ds_plus"), null,//2,
          /*14*/ "Field12", m_RS.value("t_p_plus"), null,//2,
          /*15*/ "Field13", m_RS.value("t_ds_minus"), null,//2,
          /*16*/ "Field14", m_RS.value("t_p_minus"), null,//2,
          /*17*/ "Field15", m_RS.value("f15"), null,//2,
          /*18*/ "Field16", m_RS.value("f16"), null,//2,
          /*19*/ "Field17", m_RS.value("f17"), null,//2,
          /*20*/ "Field18", m_restperc, null,
          /*21*/ "Field19", m_RS.value("t_turnsum"), null,//2,
          /*22*/ "Field20", m_RS.value("t_turnsumrepo"), null,//2,
          /*23*/ "Field21", m_RS.value("t_comsum")+ m_RS.value("t_comsumsvop") - m_RS.value("t_comsumrepo"), null,//2,
          /*24*/ "Field21_1", m_RS.value("f23"), null,//2,
          /*25*/ "Field21_2", m_RS.value("t_comsum") + m_RS.value("t_comsumsvop") - m_RS.value("t_comsumrepo") - m_RS.value("f23"), null,//2,
          /*26*/ "Field22", 0 + m_RS.value("t_comsumrepo"), null,//2,
          /*27*/ "Field22_1", 0 + m_RS.value("f25"), null,//2,
          /*28*/ "Field22_2", 0 + m_RS.value("t_comsumrepo") - m_RS.value("f25"), null,//2,
          /*29*/ "Field23", m_RS.value("t_special_repo")+ m_RS.value("t_val_svop"), null,//2, 
          /*30*/ "Field24", m_RS.value("f24"), null);//2);
    end;
    EndTable();

    //MZ>>
    RemProgress;
    row = 0 ;
    InitProgress(-1,"Печать расшифровок..."," Печать расшифровок...");
    //MZ

    /*Зоркин По требованию конечных пользователей добавлена расшифровка сумм отраженных в колонках "Активы Клиента на начало отчетного периода (ДС+ЦБ)" и "Активы Клиента на конец отчетного периода (ДС+ЦБ)"*/
    m_RS = TRsbDataSet("SELECT * FROM W475_TMP order by t_clientname, t_contrnumber, t_dlcontrid, t_marketname");

    dognum = 0;
    SetActiveSheet("Расшифровка");
    PrintFormatString( "", "ReportName3", "Расшифровка активов клиентов на начало и конец периода");

    RegisterTable( "ReportRow2", "",
            /* 1*/ "Field01_01", 
            /* 2*/ "Field07_01", 
            /* 3*/ "Field02_01", 
            /* 4*/ "Field03_01", 
            /* 5*/ "Field04_01", 
            /* 6*/ "Field05_01", 
            /* 7*/ "Field06_01");

    SetActiveSheet("Расшифровка");

    while(m_RS.MoveNext())
        dognum = dognum + 1;
        subdognum = 1;
        m_dognum = dognum;
        m_contrnumber = m_RS.value("t_contrnumber");
        m_cft_kod = m_RS.value("kod_cft");
        
        sfcontrid = m_RS.value("t_sfcontrid");

        /*Строка отчета*/
        PrintTableLine(
            /* 1*/ "Field01_01", m_dognum, null,
            /* 2*/ "Field07_01", m_cft_kod, null,
            /* 3*/ "Field02_01", m_contrnumber, null,
            /* 4*/ "Field03_01", m_RS.value("t_ds_in"), null,
            /* 5*/ "Field04_01", m_RS.value("t_p_in"), null,
            /* 6*/ "Field05_01", m_RS.value("t_ds_out"), null,
            /* 7*/ "Field06_01", m_RS.value("t_p_out"), null);//2);

        row = row + 1;
        sfcontrid = 0;/*GAA: 503753*/
        UseProgress(row);
    end;

    RemProgress; 
    EndTable(); 

    var SQL, rs1, SQL1, rs2; 
    SQL = null; 
    dognum = 0;

    InitProgress(-1,"Печать расшифровок сделок СПЕЦ РЕПО/СПЕЦ СВОП..."," Печать расшифровок сделок СПЕЦ РЕПО/СПЕЦ СВОП...");
    PrintHeadSwap(0);

    if(m_Form.GetFieldValue(P_W475_StockMarket) == "X")  
      SQL =  " select (select t_name from dparty_dbt p      " +
                          " where p.t_partyid = dl_tick.t_clientid) name1, (select t_number from dsfcontr_dbt sf where sf.t_id =  dl_tick.t_clientcontrid) contr, dl_tick.t_dealcode deal, ( select t_name from dfininstr_dbt f   " +
                          "  where f.t_fiid = dl_leg.t_pfi) fininstr,  " +
                          "   (Select p.t_shortname from dparty_dbt p, dfininstr_dbt f    " +
                          "  where F.T_ISSUER = p.t_partyid and f.t_fiid = dl_leg.t_pfi) issuer,  " +
                          "  dl_leg.t_principal amount, " +
                          "  case when dl_leg.t_legkind=0  then 'Покупка РЕПО ч. 1'    " +
                          "          when dl_leg.t_legkind=2 then 'Продажа РЕПО ч. 2'  " +
                          "  end as type,    " +
                          "  dl_leg.t_cost cost,    " +
                          "  (select case when sum(t_sum) !=0 then sum(t_sum) else 0  end as com from ddlcomis_dbt                                                                                 " +
                          "  where t_docid = dl_leg.t_dealid  and t_receiverid = 0 and dl_leg.t_legkind = 0) com_bank ,                           " +
                          "  (select case when sum(t_sum) !=0 then sum(t_sum) else 0  end as com from ddlcomis_dbt                                                                                 " +
                          "  where t_docid = dl_leg.t_dealid  and t_receiverid = -1 and dl_leg.t_legkind = 0) com_birj,                           " +
                          "  (select sum(Ipart.cost - IIpart.cost) doxod from (select  t_cost cost, t_dealid from ddl_leg_dbt a where a.t_legkind = 0 and a.t_dealid =  dl_leg.t_dealid) Ipart                           " +
                          "   join                                                                                                                " +
                          "  (select  t_cost cost, t_dealid  from ddl_leg_dbt a where a.t_legkind = 2 and a.t_dealid =  dl_leg.t_dealid) IIpart   " +                        
                          "  on Ipart.t_dealid = IIpart.t_Dealid) doxod,                                                                           " +
                          "  dl_leg.T_INCOMERATE rate,                                                                                           " +
                                                  " dl_tick.t_dealdate begdate,              " +
                          " dl_leg.t_expiry enddate, dpc.t_code kod_cft                  " +
                          "  from ddl_leg_dbt dl_leg, ddl_tick_dbt dl_tick  " +
                          "  left join dpartcode_dbt dpc on dpc.t_partyid = dl_tick.t_clientid and dpc.t_codekind = 101 " +
                          " where dl_leg.t_expiry between :D and :D1 and T_DEALTYPE = 12122 and dl_tick.t_dealdate >= :D2   " +
                          "  and dl_leg.t_dealid = dl_tick.t_dealid and t_dealstatus = 20         " +
                          "  and t_clientcontrid != 0       " +
                          "  AND EXISTS                               " +
                          "       (SELECT 1                     " +
                          "          FROM dobjatcor_dbt atcor       " +
                          "         WHERE     atcor.t_objecttype = 101    " +
                          "               AND atcor.t_groupid = 103       " +
                          "               AND atcor.t_object = LPAD (dl_tick.t_dealid, 34, 0)  " +
                          "               AND atcor.t_attrid =                                  " +
                          "                      (SELECT objattr.t_attrid                       " +
                          "                         FROM DOBJATTR_DBT objattr                   " +
                          "                        WHERE atcor.t_objecttype =                   " +
                          "                                 objattr.t_objecttype                " +
                          "                              AND atcor.t_groupid =                  " +
                          "                                     objattr.t_groupid               " +
                          "                              AND LOWER (objattr.t_name) =           " +
                          "                                     'да'))                          " +
                          "                                                                    order by dl_tick.t_clientcontrid, dl_tick.t_dealcode,dl_leg.t_expiry "; 
                           
         m_RS = RSDCommand(SQL);                                                                            
         m_RS.AddParam("D", RSDBP_IN, m_BeginDate);
         m_RS.AddParam("D1", RSDBP_IN, m_DateEnd);  
         m_RS.AddParam("D2", RSDBP_IN, m_BeginDate);

         rs1 = RSDRecordset(m_RS);

         while(rs1.MoveNext())

            dognum = dognum + 1;
            subdognum = 1;
            m_dognum = dognum;
            m_cft_kod = rs1.value("kod_cft");
   
            PrintTableLine(
            /* 1*/ "Field01_02", m_dognum, null,
            /* 2*/ "Field16_02", m_cft_kod, null,
            /* 3*/ "Field02_02", rs1.value("name1"), null,
            /* 4*/ "Field03_02", rs1.value("contr"), null,
            /* 5*/ "Field04_02", rs1.value("deal"), null,
            /* 6*/ "Field05_02", rs1.value("fininstr"), null,
            /* 7*/ "Field06_02", rs1.value("issuer"), null,
            /* 8*/ "Field07_02", rs1.value("amount"), null,
            /* 9*/ "Field08_02", rs1.value("type"), null,
            /* 10*/ "Field09_02", rs1.value("cost"), null,
             	       
            /* 11*/ "Field10_02", rs1.value("com_bank"), null,
            /* 12*/ "Field11_02", rs1.value("com_birj"), null,
            /* 13*/ "Field12_02", rs1.value("doxod"), null,
            /* 14*/ "Field13_02", rs1.value("rate"), null,
         
            /* 15*/ "Field14_02",date (rs1.value("begdate")), null,
            /* 16*/ "Field15_02",date (rs1.value("enddate")), null);//2);
	         
            row = row + 1;
            sfcontrid = 0;
            UseProgress(row);
         end;
    end;

    if(m_Form.GetFieldValue(P_W475_CurrencyMarket) == "X")

      SQL1 = "    select (select t_name from dparty_dbt p   " +
             " where p.t_partyid = dvn.t_client) name1, (select t_number from dsfcontr_dbt sf where sf.t_id = dvn.t_clientcontr) contr, dvn.t_code deal, " +
             " ( select t_name from dfininstr_dbt f                                                                                                      " +
             "  where f.t_fiid = dvnfi.t_fiid) fininstr,                                                                                                  " +
             "    (Select p.t_shortname from dparty_dbt p, dfininstr_dbt f                                                                               " +
             "  where F.T_ISSUER = p.t_partyid and f.t_fiid = dvnfi.t_fiid) issuer,                                                                      " +
             "  dvnfi.t_amount amount,                                                                                                                   " +
             "   case when dvn.t_type = 6 and  dvnfi.t_type= 0  then 'Продажа СВОП ч. 1'                                                                 " +
             "          when dvn.t_type = 6 and  dvnfi.t_type= 2  then 'Покупка СВОП ч. 2'                                                               " +
             "          when dvn.t_type = 5 and  dvnfi.t_type= 0  then 'Покупка СВОП ч. 1'                                                               " +
             "          when dvn.t_type = 5 and  dvnfi.t_type= 2  then 'Продажа СВОП ч. 2'                                                               " +
             "  end as type,                                                                                                                             " +
             "  dvnfi.t_cost cost,                                                                                                                       " +

             "  (select case when sum(t_sum) !=0 then sum(t_sum) else 0  end as com from ddlcomis_dbt   com                                                                                               " +
             "  where t_docid = dvn.t_id and com.t_dockind =199  and t_receiverid = 0 and  dvnfi.t_type= 0) com_bank ,                                   " +
             "  (select case when sum(t_sum) !=0 then sum(t_sum) else 0  end as com from ddlcomis_dbt   com                                                                                               " +
             "  where t_docid = dvn.t_id and com.t_dockind =199  and t_receiverid = -1 and  dvnfi.t_type= 0 ) com_birj,                                  " +
             "  (select sum(Ipart.cost - IIpart.cost) doxod from (select  t_cost cost, t_dealid from ddvnfi_dbt a where a.t_type= 0 and a.t_dealid =  dvnfi.t_dealid) Ipart " +
             "  join                                                                                                                                     " +
             "  (select  t_cost cost, t_dealid  from ddvnfi_dbt a where a.t_type= 2 and a.t_dealid =  dvnfi.t_dealid) IIpart                             " +
             "  on Ipart.t_dealid = IIpart.t_Dealid)doxod,                                                                                               " +
             "  dvnfi.t_rate rate,                                                                                                                       " +

             "  dvn.t_date begdate,                                                                                                                      " +
             "  dvnfi.t_execdate enddate, dpc.t_code kod_cft                                                                                             " +
             " from ddvnfi_Dbt dvnfi, ddvndeal_Dbt dvn                                                                                                   " +
             "  left join dpartcode_dbt dpc on dpc.t_partyid = dvn.t_client and dpc.t_codekind = 101                                                     " +
             "  where dvn.t_kind = 32715                                                                                                                 " +
             "  and dvn.t_id = dvnfi.t_dealid                                                                                                            " +
             "  and dvnfi.t_execdate between :D AND :D1 and dvn.t_date >= :D2  and dvn.t_state = 2                                                       " +
             " order by dvn.t_clientcontr, dvn.t_code,  dvnfi.t_execdate                                                                                  ";

         m_RS1 = RSDCommand(SQL1);                                                                            
         m_RS1.AddParam("D", RSDBP_IN, m_BeginDate);
         m_RS1.AddParam("D1", RSDBP_IN, m_DateEnd);  
         m_RS1.AddParam("D2", RSDBP_IN, m_BeginDate);
         rs2 = RSDRecordset(m_RS1);
                     
         while(rs2.MoveNext())

             dognum = dognum + 1;
             subdognum = 1;
             m_dognum = dognum;
             m_cft_kod = rs2.value("kod_cft");
             PrintTableLine(
             /* 1*/ "Field01_02", m_dognum, null,
             /* 2*/ "Field16_02", m_cft_kod, null,
             /* 3*/ "Field02_02", rs2.value("name1"), null,
             /* 4*/ "Field03_02", rs2.value("contr"), null,
             /* 5*/ "Field04_02", rs2.value("deal"), null,
             /* 6*/ "Field05_02", rs2.value("fininstr"), null,
             /* 7*/ "Field06_02", "", null,
             /* 8*/ "Field07_02", rs2.value("amount"), null,
             /* 9*/ "Field08_02", rs2.value("type"), null,
             /* 10*/ "Field09_02", rs2.value("cost"), null,
   
             /* 11*/ "Field10_02", money(rs2.value("com_bank")), null,
             /* 12*/ "Field11_02", money(rs2.value("com_birj")), null,
             /* 13*/ "Field12_02", rs2.value("doxod"), null,
             /* 14*/ "Field13_02", rs2.value("rate"), null,
   
   
             /* 15*/ "Field14_02",date (rs2.value("begdate")), null,
             /* 16*/ "Field15_02",date (rs2.value("enddate")), null);//2);
   
             row = row + 1;
             sfcontrid = 0;/*GAA: 503753*/
             UseProgress(row);
         end;                   
    end;

    RemProgress; //MZ

    PrintEndSwap();

  END;

  MACRO CReport_Show( NumCopy:INTEGER)
    CReport_Show( NumCopy, m_IsShowReport);

    if((NOT m_IsShowReport) AND (GetFullReportFileNames().size > 0))
       MsgBox("Отчет сформирован! Путь к файлу: " + GetFullReportFileNames()[0]);
    end;

  END;
  
  initTX_RegistrReport(W475_Panel(), "Report_W475.xlsx", NULL,NULL, NULL, POI_MODE, TRUE);

END;

/*Точка входа*/
var defprec = SetDefPrec(12);
var r = W475_Report();
r.InitReport("Результаты брокерского обслуживания для ДРРК", null);
r.Run();
message("Конец");
SetDefPrec(defprec);

exit(1);