/*Таблица DBRKREPACTIVEDERIV_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPACTIVEDERIV_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPACTIVEDERIV_TMP
(
  T_FIKIND            VARCHAR2(35),
  T_FINAME            VARCHAR2(50),
  T_INREST            NUMBER(32,12),
  T_INCOSTREST        NUMBER(32,12),
  T_INGUARANTY        NUMBER(32,12),
  T_BUY               NUMBER(32,12),
  T_SALE              NUMBER(32,12),
  T_OUTREST           NUMBER(32,12),
  T_OUTCOSTREST       NUMBER(32,12),
  T_OUTGUARANTY       NUMBER(32,12),
  T_INPLANREST        NUMBER(32,12),
  T_INPLANCOSTREST    NUMBER(32,12),
  T_OUTPLANREST       NUMBER(32,12),
  T_OUTPLANCOSTREST   NUMBER(32,12),
  T_ISITOG            CHAR(1),
  T_SERVKIND          NUMBER(5),
  T_SERVKINDSUB       NUMBER(5)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPACTIVEDERIV_TMP IS 'Данные для ОБ. Оценка позиции по ПФИ'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_FIKIND IS 'Наименование вида финансового инструмента'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_FINAME IS 'Название финансового инструмента'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_INREST IS 'Количество на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_INCOSTREST IS 'Стоимость в руб. на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_INGUARANTY IS 'Гарантийное обеспечение на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_BUY IS 'Количество зачислено'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_SALE IS 'Количество списано'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_OUTREST IS 'Количество на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_OUTCOSTREST IS 'Стоимость в руб. на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_OUTGUARANTY IS 'Гарантийное обеспечение на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_INPLANREST IS 'Плановый остаток на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_INPLANCOSTREST IS 'Стоимость планового остатка в руб. на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_OUTPLANREST IS 'Плановый остаток на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_OUTPLANCOSTREST IS 'Cтоимость планового остатка в руб. на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_ISITOG IS 'Признак итоговой строки'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPACTIVEDERIV_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/