/*Таблица DBRKREPCURDEAL_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPCURDEAL_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPCURDEAL_TMP
(
  T_DEALID            NUMBER(10),
  T_CLIENTID          NUMBER(10),
  T_CONTRID           NUMBER(10),
  T_PART              NUMBER(5),
  T_PLANID            NUMBER(10),
  T_ISITOG            CHAR(1),
  T_CONCDATE          VARCHAR2(20),
  T_EXECDATE          DATE,
  T_CODETS            VARCHAR2(30),
  T_MARKETPLACE       VARCHAR2(35),
  T_INSTRUMENT        VARCHAR2(30),
  T_DEALKIND          VARCHAR2(10),
  T_VOLUME            NUMBER(32,12),
  T_REQPRICE          NUMBER(32,12),
  T_PRICE             NUMBER(32,12),
  T_BASECURR          VARCHAR2(3),
  T_CONTRCURR         VARCHAR2(3),
  T_BASESUM           NUMBER(32,12),
  T_CONTRSUM          NUMBER(32,12),
  T_CONTRSUMRUB       NUMBER(32,12),
  T_BROKERCOMISSCONTR NUMBER(32,12),
  T_BROKERCOMISSRUB   NUMBER(32,12),
  T_MARKETCOMISS      NUMBER(32,12),
  T_DEALTYPE          VARCHAR2(12),
  T_CONTRACTOR        VARCHAR2(60),
  T_LIABILITYBASE     NUMBER(32,12),
  T_LIABILITYCONTR    NUMBER(32,12),
  T_NOTE              VARCHAR2(35),
  T_SERVKIND          NUMBER(5),
  T_SERVKINDSUB       NUMBER(5),
  T_MARKETID          NUMBER(10)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPCURDEAL_TMP IS 'Данные для ОБ. Сделки валютного рынка'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_DEALID IS 'Идентификатор сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_CLIENTID IS 'Идентификатор клиента'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_CONTRID IS 'Идентификатор договора обслуживания клиента'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_PART IS 'Раздел отчета'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_PLANID IS 'Тарифный план'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_ISITOG IS 'Признак итоговой строки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_CONCDATE IS 'Дата и время заключения сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_EXECDATE IS 'Дата исполнения сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_CODETS IS 'Номер сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_MARKETPLACE IS 'Наименование места заключения сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_INSTRUMENT IS 'Наименование финансового инструмента'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_DEALKIND IS 'Вид сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_VOLUME IS 'Объем сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_REQPRICE IS 'Цена заявки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_PRICE IS 'Цена сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_BASECURR IS 'Буквенный код валюты сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_CONTRCURR IS 'Буквенный код валюты расчетов'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_BASESUM IS 'Сумма в валюте сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_CONTRSUM IS 'Сумма в валюте расчетов'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_CONTRSUMRUB IS 'Сумма расчетов в рублях'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_BROKERCOMISSCONTR IS 'Комиссия брокера в валюте расчетов'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_BROKERCOMISSRUB IS 'Комиссия брокера, руб'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_MARKETCOMISS IS 'Комиссия, компенсирующая биржевые сборы, руб.'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_DEALTYPE IS 'Тип сделки: Безадресная или Адресная'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_CONTRACTOR IS 'Контрагент'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_LIABILITYBASE IS 'Обязательства в валюте сделки'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_LIABILITYCONTR IS 'Обязательства в валюте расчетов'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_NOTE IS 'Примечание'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/
COMMENT ON COLUMN DBRKREPCURDEAL_TMP.T_MARKETID IS 'Идентификатор биржи'
/