BEGIN
  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7549, 1, '1 квартал', 14, 4);
  
  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7549, 2, 'Полугодие', 14, 4);
  
  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7549, 3, 'Девять месяцев', 14, 4);
  
  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7549, 4, 'Год', 14, 4);
END;