/*Таблица DBRKREPACTIVEAVOIR_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPACTIVEAVOIR_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPACTIVEAVOIR_TMP
(
  T_NAME            VARCHAR2(50),
  T_ISINLSIN        VARCHAR2(35),
  T_FACEVALUEFICCY  VARCHAR2(3),
  T_INREST          NUMBER(32,12),
  T_INCOURSE        FLOAT(53),
  T_INCOURSEFICCY   VARCHAR2(3),
  T_INNKD           NUMBER(32,12),
  T_INCOSTREST      NUMBER(32,12),
  T_BUY             NUMBER(32,12),
  T_SALE            NUMBER(32,12),
  T_OUTREST         NUMBER(32,12),
  T_OUTCOURSE       FLOAT(53),
  T_OUTCOURSEFICCY  VARCHAR2(3),
  T_OUTNKD          NUMBER(32,12),
  T_OUTCOSTREST     NUMBER(32,12),
  T_INPLANREST      NUMBER(32,12),
  T_INPLANCOSTREST  NUMBER(32,12),
  T_OUTPLANREST     NUMBER(32,12),
  T_OUTPLANCOSTREST NUMBER(32,12),
  T_ISITOG          CHAR(1),
  T_SERVKIND        NUMBER(10),
  T_SERVKINDSUB     NUMBER(5)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPACTIVEAVOIR_TMP IS 'Данные для ОБ. Оценка позиции по ЦБ и НЕФИ'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_NAME IS 'Наименование ценной бумаги'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_ISINLSIN IS 'ISIN /номер гос.регистрации'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_FACEVALUEFICCY IS 'Буквенный код валюты номинала'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_INREST IS 'Количество на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_INCOURSE IS 'Значение котировки на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_INCOURSEFICCY IS 'Буквенный код валюты котировки на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_INNKD IS 'НКД на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_INCOSTREST IS 'Рыночная стоимость в руб. на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_BUY IS 'Количество зачислено'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_SALE IS 'Количество списано'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_OUTREST IS 'Количество на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_OUTCOURSE IS 'Значение котировки на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_OUTCOURSEFICCY IS 'Буквенный код валюты котировки на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_OUTNKD IS 'НКД на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_OUTCOSTREST IS 'Рыночная стоимость в руб. на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_INPLANREST IS 'Плановый остаток на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_INPLANCOSTREST IS 'Рыночная стоимость планового остатка на начало периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_OUTPLANREST IS 'Плановый остаток на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_OUTPLANCOSTREST IS 'Рыночная стоимость планового остатка на конец периода'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_ISITOG IS 'Признак итоговой строки'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPACTIVEAVOIR_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/