/*Таблица DBRKREPDEBT_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPDEBT_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPDEBT_TMP
(
  T_TYPE         NUMBER(5),
  T_TEXT         VARCHAR2(100),
  T_ORIGINDATE   DATE,
  T_PAYDATE      DATE,
  T_CURRENCY     NUMBER(10),
  T_CCY          VARCHAR2(3),
  T_SUM          NUMBER(32,12),
  T_ISTOTAL      CHAR(1),
  T_ISITOG       CHAR(1),
  T_ONDATE       DATE
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPDEBT_TMP IS 'Данные для ОБ. Обязательства перед банком'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_TYPE IS 'Вид обязательства'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_TEXT IS 'Наименование обязательства или период'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_ORIGINDATE IS 'Дата возникновения задолженности'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_PAYDATE IS 'Плановая дата оплаты'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_CURRENCY IS 'Идентификатор валюты'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_CCY IS 'Буквенный код валюты по ISO'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_SUM IS 'Сумма обязательства'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_ISTOTAL IS 'Признок итоговой строки по виду обязательства'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_ISITOG IS 'Признак итоговой строки'
/
COMMENT ON COLUMN DBRKREPDEBT_TMP.T_ONDATE IS 'Дата сбора информации по обязательствам'
/
