/*Таблица DBRKREPACCITOG_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPACCITOG_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPACCITOG_TMP
(
  T_CURRENCY     NUMBER(10),
  T_CCY          VARCHAR2(15),
  T_ISITOG       CHAR(1),
  T_SERVKIND     NUMBER(5),
  T_SERVKINDSUB  NUMBER(10),
  T_MARKETID     NUMBER(10),
  T_MARKETNAME   VARCHAR2(100),
  T_INREST       NUMBER(32,12),
  T_OUTREST      NUMBER(32,12),
  T_PLANREST     NUMBER(32,12)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPACCITOG_TMP IS 'Данные для ОБ. Оценка денежной позиции'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_CURRENCY IS 'Идентификатор валюты'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_CCY IS 'Буквенный код валюты по ISO'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_ISITOG IS 'Признак итоговой строки'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_MARKETID IS 'Идентификатор биржи'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_MARKETNAME IS 'Наименование торговой площадки'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_INREST IS 'Входящий остаток'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_OUTREST IS 'Исходящий остаток'
/
COMMENT ON COLUMN DBRKREPACCITOG_TMP.T_PLANREST IS 'Плановый остаток'
/