/*Таблица DBRKREPDEAL_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPDEAL_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPDEAL_TMP (
    T_CLIENTID NUMBER(10)
  , T_CONTRID NUMBER(10)
  , T_PART NUMBER(5)
  , T_PLANID NUMBER(10)
  , T_ISITOG CHAR(1)
  , T_DIRECTION NUMBER(5)
  , T_A05_D DATE
  , T_A05_T DATE
  , T_A06 DATE
  , T_A07 VARCHAR2(30)
  , T_A08 VARCHAR2(30)
  , T_A09 VARCHAR2(35)
  , T_A10 VARCHAR2(9)
  , T_A11 VARCHAR2(60)
  , T_A12 VARCHAR2(35)
  , T_A13 FLOAT(53)
  , T_A13_I FLOAT(53)
  , T_A14 VARCHAR2(3)
  , T_A14_C NUMBER(10)
  , T_A15 NUMBER(32,12)
  , T_A16 NUMBER(32,12)
  , T_A17 NUMBER(32,12)
  , T_A18 NUMBER(32,12)
  , T_A19 VARCHAR2(3)
  , T_A19_C NUMBER(10)
  , T_A20 NUMBER(32,12)
  , T_A21 NUMBER(32,12)
  , T_A22 NUMBER(32,12)
  , T_A23 VARCHAR2(14)
  , T_A24 VARCHAR2(60)
  , T_A25 VARCHAR2(35)
  , T_A26 NUMBER(32,12)
  , T_A27 NUMBER(32,12)
  , T_A28 NUMBER(32,12)
  , T_A29 NUMBER(32,12)
  , T_A30 VARCHAR2(3)
  , T_A31 DATE
  , T_A32_1 NUMBER(32,12)
  , T_A32_2 NUMBER(10)
  , T_A33_1 NUMBER(32,12)
  , T_A33_2 NUMBER(10)
  , T_A33_3 NUMBER(32,12)
  , T_A34 NUMBER(32,12)
  , T_A35 NUMBER(32,12)
  , T_FIID NUMBER(10)
  , T_A95 FLOAT(53)
  , T_A95_M VARCHAR2(35)
  , T_SERVKIND NUMBER(5)
  , T_SERVKINDSUB NUMBER(5)
  , T_MARKETID NUMBER(10)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPDEAL_TMP IS 'Данные для отчета брокера. Сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_CLIENTID IS 'Идентификатор клиента'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_CONTRID IS 'Идентификатор договора обслуживания клиента'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_PART IS 'Раздел отчета'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_PLANID IS 'Тарифный план'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_ISITOG IS 'Признак итоговой строки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_DIRECTION IS 'Направление (покупка или продажа)'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A05_D IS 'Дата заключения сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A05_T IS 'Время заключения сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A06 IS 'Дата исполнения сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A07 IS 'Номер сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A08 IS 'Номер сделки в ТС'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A09 IS 'Код торговой площадки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A10 IS 'Вид сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A11 IS 'Краткое наименование эмитента'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A12 IS 'LSIN или ISIN'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A13 IS 'Цена сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A13_I IS 'Ставка РЕПО'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A14 IS 'Валюта сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A14_C IS 'Идентификатор валюты сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A15 IS 'Количество бумаг'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A16 IS 'Сумма сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A17 IS 'Сумма сделки в рублях'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A18 IS 'Комиссия брокера'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A19 IS 'Валюта комиссии брокера'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A19_C IS 'Идентификатор валюты комиссии брокера'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A20 IS 'Комиссия торговой площадки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A21 IS 'Комиссия клирингово центра'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A22 IS 'Комиссия за ИТС (в т.ч. НДС)'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A23 IS 'Тип сделки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A24 IS 'Краткое наименование контрагента'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A25 IS 'Код контрагента'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A26 IS 'Сумма НКД'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A27 IS 'Сумма НКД в рублях'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A28 IS 'Обязательство по ДС'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A29 IS 'Обязательство по ЦБ'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A30 IS 'Валюта итоговой строки'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A31 IS 'Дата проведения платежа'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A32_1 IS 'Выплата купонного дохода'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A32_2 IS 'Валюта выплаты'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A33_1 IS 'Сумма компенсационного взноса'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A33_2 IS 'Валюта платежа'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A33_3 IS 'Сумма КВ в рублях'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A34 IS 'Сумма купонного дохода и КВ по денежным средствам'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A35 IS 'Сумма КВ по ценным бумагам'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_FIID IS 'Идентификатор ценной бумаги'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A95 IS 'Цена поручения'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_A95_M IS 'Примечание'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/
COMMENT ON COLUMN DBRKREPDEAL_TMP.T_MARKETID IS 'Идентификатор биржи'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DBRKREPDEAL_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX DBRKREPDEAL_TMP_IDX0 ON DBRKREPDEAL_TMP (
   T_CLIENTID ASC
  ,T_CONTRID ASC
  ,T_PART ASC
  ,T_PLANID ASC
  ,T_ISITOG ASC
)
/