/*Таблица DBRKREPINACC_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPINACC_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPINACC_TMP (
    T_CLIENTID NUMBER(10)
  , T_CONTRID NUMBER(10)
  , T_ISITOG CHAR(1)
  , T_PLACEID NUMBER(10)
  , T_FIID NUMBER(10)
  , T_A53 VARCHAR2(35)
  , T_A54 VARCHAR2(60)
  , T_A55 NUMBER(32,12)
  , T_A55_1 NUMBER(32,12)
  , T_A56 NUMBER(32,12)
  , T_A56_1 NUMBER(32,12)
  , T_A56_2 NUMBER(32,12)
  , T_A57 NUMBER(32,12)
  , T_A57_1 NUMBER(32,12)
  , T_A57_2 NUMBER(32,12)
  , T_A58 NUMBER(32,12)
  , T_A58_1 NUMBER(32,12)
  , T_A59 FLOAT(53)
  , T_A59_1 NUMBER(10)
  , T_A60 NUMBER(32,12)
  , T_A61 NUMBER(32,12)
  , T_A62 NUMBER(32,12)
  , T_A63 NUMBER(32,12)
  , T_SERVKIND NUMBER(5)
  , T_SERVKINDSUB NUMBER(5)
  , T_MARKETID NUMBER(10)
) 
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPINACC_TMP IS 'Данные для отчета брокера. ВУ'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_CLIENTID IS 'Идентификатор клиента'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_CONTRID IS 'Идентификатор договора обслуживания'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_ISITOG IS 'Признак итоговой строки'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_PLACEID IS 'Идентификатор места хранения'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_FIID IS 'Идентификатор ценной бумаги'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A53 IS 'Номер гос. регистрации/ ISIN'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A54 IS 'Код выпуска цб'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A55 IS 'Входящий остаток'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A55_1 IS 'Входящий остаток план.'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A56 IS 'Зачислено'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A56_1 IS 'Зачислено исходящий план.'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A56_2 IS 'Зачислено входящий план.'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A57 IS 'Списано'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A57_1 IS 'Списано исходящий план.'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A57_2 IS 'Списано входящий план.'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A58 IS 'Исходящий остаток'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A58_1 IS 'Исходящий остаток план.'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A59 IS 'Котировка'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A59_1 IS 'Валюта котировки'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A60 IS 'Стоимость'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A61 IS 'Стоимость в рублях'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A62 IS 'НКД'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_A63 IS 'НКД в рублях'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/
COMMENT ON COLUMN DBRKREPINACC_TMP.T_MARKETID IS 'Идентификатор биржи'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DBRKREPINACC_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX DBRKREPINACC_TMP_IDX0 ON DBRKREPINACC_TMP (
   T_CLIENTID ASC
  ,T_CONTRID ASC
  ,T_PLACEID ASC
  ,T_FIID ASC
  ,T_ISITOG ASC
)
/