/*Таблица DBRKREPACC_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPACC_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPACC_TMP
(
  T_ACCOUNTID NUMBER(10),   
  T_SERVKIND NUMBER(5),     
  T_SERVKINDSUB NUMBER(10), 
  T_MARKETID NUMBER(10),    
  T_INREST NUMBER(32,12),   
  T_OUTREST NUMBER(32,12),  
  T_INPLANREST NUMBER(32,12), 
  T_OUTPLANREST NUMBER(32,12)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPACC_TMP IS 'Данные для отчета брокера. Счета'
/
COMMENT ON COLUMN DBRKREPACC_TMP.T_ACCOUNTID IS 'Идентификатор счета'
/
COMMENT ON COLUMN DBRKREPACC_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPACC_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/
COMMENT ON COLUMN DBRKREPACC_TMP.T_MARKETID IS 'Идентификатор биржи'
/
COMMENT ON COLUMN DBRKREPACC_TMP.T_INREST IS 'Входящий остаток'
/
COMMENT ON COLUMN DBRKREPACC_TMP.T_OUTREST IS 'Исходящий остаток'
/
COMMENT ON COLUMN DBRKREPACC_TMP.T_INPLANREST IS 'Входящий плановый остаток'
/
COMMENT ON COLUMN DBRKREPACC_TMP.T_OUTPLANREST IS 'Исходящий плановый остаток'
/