/*Таблица DBRKREPSVODINFO_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPSVODINFO_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPSVODINFO_TMP
(
  T_NAME        VARCHAR2(100),
  T_INSUM       NUMBER(32,12),
  T_OUTSUM      NUMBER(32,12),
  T_DIFFERENCE  NUMBER(32,12),
  T_SERVKIND    NUMBER(5),
  T_SERVKINDSUB NUMBER(5),
  T_ISITOG      CHAR(1)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPSVODINFO_TMP IS 'Данные для ОБ. Сводная информация'
/
COMMENT ON COLUMN DBRKREPSVODINFO_TMP.T_NAME IS 'Наименование раздела'
/
COMMENT ON COLUMN DBRKREPSVODINFO_TMP.T_INSUM IS 'Сумма на начало периода'
/
COMMENT ON COLUMN DBRKREPSVODINFO_TMP.T_OUTSUM IS 'Сумма на конец периода'
/
COMMENT ON COLUMN DBRKREPSVODINFO_TMP.T_DIFFERENCE IS 'Изменение за период'
/
COMMENT ON COLUMN DBRKREPSVODINFO_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPSVODINFO_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/
COMMENT ON COLUMN DBRKREPSVODINFO_TMP.T_ISITOG IS 'Признак итоговой строки'
/