BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DPORTFOLIO_TMP ADD (UNKD_WITH_COUPON_TMP number(31,12))';
    EXECUTE IMMEDIATE 'ALTER TABLE DPORTFOLIO_TMP ADD (COUPON_AMOUNT_TMP number(31,12))';
    EXECUTE IMMEDIATE 'ALTER TABLE DPORTFOLIO_TMP ADD (DISCOUNT_AMOUNT_TMP number(31,12))';
    EXECUTE IMMEDIATE 'ALTER TABLE DPORTFOLIO_TMP ADD (PREMIUM_AMOUNT_TMP number(31,12))';
END;
/

BEGIN
    UPDATE DPORTFOLIO_TMP
       SET UNKD_WITH_COUPON_TMP = UNKD_WITH_COUPON,
           COUPON_AMOUNT_TMP = COUPON_AMOUNT,
           DISCOUNT_AMOUNT_TMP = DISCOUNT_AMOUNT,
           PREMIUM_AMOUNT_TMP = PREMIUM_AMOUNT;

    UPDATE DPORTFOLIO_TMP
       SET UNKD_WITH_COUPON = NULL,
           COUPON_AMOUNT = NULL,
           DISCOUNT_AMOUNT = NULL,
           PREMIUM_AMOUNT = NULL;

    COMMIT;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DPORTFOLIO_TMP MODIFY (UNKD_WITH_COUPON NUMBER(32,12),COUPON_AMOUNT NUMBER(32,12),DISCOUNT_AMOUNT NUMBER(32,12),PREMIUM_AMOUNT NUMBER(32,12))';
END;
/

BEGIN
    UPDATE DPORTFOLIO_TMP
       SET UNKD_WITH_COUPON = UNKD_WITH_COUPON_TMP,
           COUPON_AMOUNT = COUPON_AMOUNT_TMP,
           DISCOUNT_AMOUNT = DISCOUNT_AMOUNT_TMP,
           PREMIUM_AMOUNT = PREMIUM_AMOUNT_TMP;

    COMMIT;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DPORTFOLIO_TMP DROP(UNKD_WITH_COUPON_TMP)';
    EXECUTE IMMEDIATE 'ALTER TABLE DPORTFOLIO_TMP DROP(COUPON_AMOUNT_TMP)';
    EXECUTE IMMEDIATE 'ALTER TABLE DPORTFOLIO_TMP DROP(DISCOUNT_AMOUNT_TMP)';
    EXECUTE IMMEDIATE 'ALTER TABLE DPORTFOLIO_TMP DROP(PREMIUM_AMOUNT_TMP)';
END;
/