/*Таблица DBRKREPDVDEAL_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPDVDEAL_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPDVDEAL_TMP
(
  T_DEALID              NUMBER(10),
  T_CLIENTID            NUMBER(10),
  T_CONTRID             NUMBER(10),
  T_PART                NUMBER(5),
  T_PLANID              NUMBER(10),
  T_ISITOG              CHAR(1),
  T_CODE                VARCHAR2(30),
  T_CONCDATE            VARCHAR2(20),
  T_FIKIND              VARCHAR2(35),
  T_FINAME              VARCHAR2(50),
  T_DEALKIND            VARCHAR2(10),
  T_MARKETPLACE         VARCHAR2(35),
  T_CLRDATE             DATE,
  T_REQPRICE            NUMBER(32,12),
  T_PRICEFUTURESORBONUS NUMBER(32,12),
  T_PRICEOPTION         NUMBER(32,12),
  T_AMOUNT              NUMBER(32,12),
  T_DEALSUMRUB          NUMBER(32,12),
  T_MARGINRUB           NUMBER(32,12),
  T_MARKETCOMISS        NUMBER(32,12),
  T_BROKERCOMISSRUB     NUMBER(32,12),
  T_NOTE                VARCHAR2(35),
  T_SERVKIND            NUMBER(5),
  T_SERVKINDSUB         NUMBER(5),
  T_MARKETID            NUMBER(10)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPDVDEAL_TMP IS 'Данные для ОБ. Сделки срочного рынка'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_DEALID IS 'Идентификатор сделки'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_CLIENTID IS 'Идентификатор клиента'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_CONTRID IS 'Идентификатор договора обслуживания клиента'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_PART IS 'Раздел отчета'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_PLANID IS 'Тарифный план'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_ISITOG IS 'Признак итоговой строки'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_CODE IS 'Номер сделки'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_CONCDATE IS 'Дата и время заключения сделки'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_FIKIND IS 'Вид финансового инструмента'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_FINAME IS 'Наименование финансового инструмента'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_DEALKIND IS 'Вид сделки'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_MARKETPLACE IS 'Наименование места заключения сделки'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_CLRDATE IS 'Дата расчётов по сделке'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_REQPRICE IS 'Цена заявки'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_PRICEFUTURESORBONUS IS 'Цена одного фьючерсного контракта (размер премии по опциону)'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_PRICEOPTION IS 'Цена исполнения по опциону'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_AMOUNT IS 'Количество'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_DEALSUMRUB IS 'Сумма сделки в рублях'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_MARGINRUB IS 'Вариационная маржа, руб.'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_MARKETCOMISS IS 'Комиссия, компенсирующая биржевые сборы, руб.'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_BROKERCOMISSRUB IS 'Комиссия брокера, руб'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_NOTE IS 'Примечание'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_SERVKIND IS 'Вид обслуживания'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/
COMMENT ON COLUMN DBRKREPDVDEAL_TMP.T_MARKETID IS 'Идентификатор биржи'
/