BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DSCSRVREPCNTR_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DSCSRVREPCNTR_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DSCSRVREPCNTR_DBT_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DSCSRVREPCNTR_TMP
(
  T_SERVDOCID      NUMBER(10),
  T_DLCONTRID      NUMBER(10),
  T_DLCONTRNUMBER  VARCHAR2(100 BYTE),
  T_CLIENTNAME     VARCHAR2(300 BYTE),
  T_CLIENTCODE     VARCHAR2(100 BYTE),
  T_EKK            VARCHAR2(100 BYTE),
  T_GROUPNUMBER    NUMBER(10),
  T_ROWNUM         NUMBER(10)
) ON COMMIT PRESERVE ROWS
/

CREATE TABLE DSCSRVREPCNTR_DBT
(
  T_ID             NUMBER(10)                   NOT NULL,
  T_SERVDOCID      NUMBER(10),
  T_DLCONTRID      NUMBER(10),
  T_DLCONTRNUMBER  VARCHAR2(100 BYTE),
  T_CLIENTNAME     VARCHAR2(300 BYTE),
  T_CLIENTCODE     VARCHAR2(100 BYTE),
  T_EKK            VARCHAR2(100 BYTE),
  T_GROUPNUMBER    NUMBER(10),
  T_ROWNUM         NUMBER(10),
  CONSTRAINT DSCSRVREPCNTR_DBT_IDX0 PRIMARY KEY (T_ID)
)
/

CREATE UNIQUE INDEX DSCSRVREPCNTR_DBT_IDX1 ON DSCSRVREPCNTR_DBT
(T_SERVDOCID, T_DLCONTRID)
/

CREATE SEQUENCE DSCSRVREPCNTR_DBT_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER "DSCSRVREPCNTR_DBT_T0_AINC" 
 BEFORE INSERT OR UPDATE OF t_id ON DSCSRVREPCNTR_DBT FOR EACH ROW
DECLARE
 v_id INTEGER;
BEGIN
 IF (:new.t_id = 0 OR :new.t_id IS NULL) THEN
 SELECT dscsrvrepcntr_dbt_seq.nextval INTO :new.t_id FROM dual;
 ELSE
 select last_number into v_id from user_sequences where sequence_name = 'DSCSRVREPCNTR_DBT_SEQ';
 IF :new.t_id >= v_id THEN
 RAISE DUP_VAL_ON_INDEX;
 END IF;
 END IF;
END;
/