BEGIN
  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 1, 'С 1 по 22 января', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 2, 'С 23 по 31 января', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 3, 'С 1 по 22 февраля', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 4, 'С 23 по 28(29) февраля', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 5, 'С 1 по 22 марта', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 6, 'С 23 по 31 марта', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 7, 'С 1 по 22 апреля', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 8, 'С 23 по 30 апреля', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 9, 'С 1 по 22 мая', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 10, 'С 23 по 31 мая', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 11, 'С 1 по 22 июня', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 12, 'С 23 по 30 июня', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 13, 'С 1 по 22 июля', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 14, 'С 23 по 31 июля', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 15, 'С 1 по 22 августа', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 16, 'С 23 по 31 августа', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 17, 'С 1 по 22 сентября', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 18, 'С 23 по 30 сентября', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 19, 'С 1 по 22 октября', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 20, 'С 23 по 31 октября', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 21, 'С 1 по 22 ноября', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 22, 'С 23 по 30 ноября', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 23, 'С 1 по 22 декабря', 50, 24);

  INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
  VALUES (7548, 24, 'С 23 по 31 декабря', 50, 24);
END;