/*
$Name:         vsbnrattr_pawn_form.mac
$Module:       Векселя банка
$Description:  Отчет "Залоги векселей" - форма ввода данных
*/

IMPORT "DlRepForm_h.mac";

// Номера полей в форме отчета
CONST
    PNFLD_REGBNR_PAWN_IN    = 0, // По дате принятия в залог за период
    PNFLD_REGBNR_PAWN_OUT   = 1, // По дате выбытия из залога за период
    PNFLD_REGBNR_BEGINDATE  = 2, // дата начала
    PNFLD_REGBNR_ENDDATE    = 3; // дата окончания

/*Конечная дата выпуска отчета*/
PRIVATE MACRO FldProc_EndDate( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT ):INTEGER
    var SaveFldRealValue = FldRealValue;
    var sign = DL_FldProc_EndDate(pThis, Cmd, Key, @FldShowValue, @FldRealValue);

    if((Cmd == DLG_KEY) AND (Key == 13) )
        if (SaveFldRealValue != FldShowValue)
        pThis.SetLinkedValue( DL_PNFLD_ENDDATE, FldShowValue );
        end;
        return CM_IGNORE;
    end;

    return sign;
END;

CLASS ( DL_CPanel ) VS_BnrAttr_Pawn_Panel()
    PRIVATE MACRO Init()
        
        AddFieldProc( 0, PNFLD_REGBNR_PAWN_IN,      DL_PNFLD_CHECKBOX,  @DL_FldProc_CheckBox,  SET_CHAR );
        AddFieldProc( 0, PNFLD_REGBNR_PAWN_OUT,     DL_PNFLD_CHECKBOX,  @DL_FldProc_CheckBox,  UNSET_CHAR );
        AddFieldProc( 0, PNFLD_REGBNR_BEGINDATE,    DL_PNFLD_BEGINDATE, @DL_FldProc_BeginDate, {curdate});
        AddFieldProc( 0, PNFLD_REGBNR_ENDDATE,      DL_PNFLD_ENDDATE,   @FldProc_EndDate,   {curdate} );
    END;

    PRIVATE MACRO Check():BOOL
      if( (this.GetFieldValue( PNFLD_REGBNR_PAWN_IN ) == UNSET_CHAR) and
         (this.GetFieldValue( PNFLD_REGBNR_PAWN_OUT ) == UNSET_CHAR))
          msgbox("Необходимо выбрать хотя бы один параметр (принятие в завлог/выбытие из залога) для выпуска отчета.");
          return false;
      end;

      if( (this.GetFieldValue( PNFLD_REGBNR_PAWN_IN ) == SET_CHAR) and
         (this.GetFieldValue( PNFLD_REGBNR_PAWN_OUT ) == SET_CHAR) and (this.GetFieldValue( PNFLD_REGBNR_BEGINDATE ) != this.GetFieldValue( PNFLD_REGBNR_ENDDATE )))
          msgbox("Невозможно выпустить отчет с такими параметрами за период. Допустимо только в дату.");
          return false;
      end;

        return true;
    END;

    initDL_CPanel( "vs_rep.lbr", "REP_PAWN" );
END;
