/*──────────────────────────────────────────────────────────────────────────┐
  RS-Bank 5.1                                          R-Style Software Lab

  File Name   : vsrep.mac
  Programmer  : Велигжанин А.В.
  Comment     : Печать распоряжений и мем. ордеров.
└───────────────────────────────────────────────────────────────────────────*/
Import vsprros, vsprrvp, vsprrcp, vsprrkp, vsprint;

/*  Отчет, выполняемый на шаге
      parm(0) - action
      parm(1) - ID_Operation
      parm(2) - ID_Step
      parm(3) - isMulti
      parm(4) - mode
*/
MACRO vsrep(parm)
var
   needROS, needRVP, mode = parm(4), ok = false;

   if((ValType(mode) != V_STRING) OR (mode == ""))
     mode = "СПО"; 
   else
     mode = StrUpr(mode);
   end;

   needROS = (Index(mode, "С") != 0);
   needRVP = (Index(mode, "П") != 0);
   if(needRVP)
     needROS = true; /* если печатаем проводки, то может быть открывались счета? попытаемся и их напечатать*/
   end;

   if(needROS) /* распоряжение на открытие счетов */
      if(ROS(parm)) 
         ok = true;
         println("\f");
      end;
   end;

   if(needRVP) /* распоряжение на выполнение проводок */
      if(RVP(parm)) 
         ok = true;
         println("\f");
      end;
   end;

   if(Index(mode, "О") != 0) /* мемориальный ордер */
      if(MO(parm)) 
         ok = true;
         println("\f");
      end;
   end;

   if(Index(mode, "Б") != 0) /* распоряжение на банковский валютный платеж */
      if(RBCP(parm))
         ok = true;
         println("\f");
      end;
   end;
        
   if(Index(mode, "К") != 0) /* распоряжение на клиентский валютный платеж */
      if(RKCP(parm))
         ok = true;
         println("\f");
      end;
   end;

   if(Index(mode, "S") != 0) /* распоряжение на перечисление средств */
      if(RPS(parm))
         ok = true;
         println("\f");
      end;
   end;

   return ok;
END;

