/*
$Name:         vsregister.mac
$Module:       Векселя банка
$Description:  Отчет_Регистр по собственным векселям
$Autor:        Речкалов И.К.
*/
IMPORT "ws_txreportform.mac", "dlregister_form.mac", "ws_dprt.mac";
Import dlmisc, vslib, vsreplib;
    
PRIVATE VAR WebMenuItem; // Информация о запуске отчета из веб
PRIVATE VAR WebFormData;
PRIVATE VAR VSRegister_Form;

PRIVATE CONST VS_STATUS_NONE    = 0,//Отложен
              VS_STATUS_CREATED = 10,//Оформлен
              VS_STATUS_ISSUED  = 20,//Выдан
              VS_STATUS_DEPOSIT = 25,//В залоге
              VS_STATUS_REPAYED = 30,//Погашен
              VS_STATUS_REBUYED = 40;//Выкуплен
PRIVATE CONST ALG_PC_BASIS = 2317;

var PeriodTypeOpen  = 1;
var PeriodTypeClose = 2;
var i = 0; //номер учётного периода

PRIVATE CONST 
  ANAME = "valA",
  A01   = 1,
  A02   = 2,
  A03   = 3,
  A04   = 4,
  A05   = 5,
  A06   = 6,
  A07   = 7,
  A08   = 8,
  A09   = 9,
  A10   = 10,
  A11   = 11,
  A12   = 12,
  A12_1 = 13,
  A13   = 14,
  A14   = 15,
  A15   = 16,
  A16   = 17,
  A17   = 18,
  A18   = 19,
  A19   = 20,
  A20   = 21,
  A21   = 22,
  A22   = 23,
  A23   = 24,
  A24   = 25,
  A25   = 26,
  A26   = 27,
  A27   = 28,
  A28   = 29,
  A29   = 30,
  A30   = 31,
  A31   = 32,
  A32   = 33,
  A33   = 34,
  A34   = 35,
  A35   = 36,
  A36   = 37,
  A37   = 38,
  A38   = 39,
  A39   = 40,
  A40   = 41,
  A41   = 42,
  A42   = 43,
  A43   = 44,
  A44   = 45,
  A45   = 46,
  A46   = 47,
  A47   = 48,
  A48   = 49,
  A49   = 50,
  AMAX  = 51; //Верхняя граница при добавление/удаление сдвигать

private const NoDataTxt = "ДАННЫХ НЕТ";

// столбцы в таблице
private var   C_Dummy1   = "A";
private var   C_A1       = "B";
private var   C_A2       = "C";
private var   C_A3       = "D";
private var   C_A4       = "E";
private var   C_A5       = "F";
private var   C_A6       = "G";
private var   C_A7       = "H";
private var   C_A8       = "I";
private var   C_A9       = "J";
private var   C_A10      = "K";
private var   C_A11      = "L";
private var   C_A12      = "M";
private var   C_A12_1    = "N";
private var   C_A13      = "O";
private var   C_A14      = "P";
private var   C_A15      = "Q";
private var   C_A16      = "R";
private var   C_A17      = "S";
private var   C_A18      = "T";
private var   C_A19      = "U";
private var   C_A20      = "V";
private var   C_A21      = "W";
private var   C_A22      = "X";
private var   C_A23      = "Y";
private var   C_A24      = "Z";
private var   C_A25      = "AA";
private var   C_A26      = "AB";
private var   C_A27      = "AC";
private var   C_A28      = "AD";
private var   C_A29      = "AE";
private var   C_A30      = "AF";
private var   C_A31      = "AG";
private var   C_A32      = "AH";
private var   C_A33      = "AI";
private var   C_A34      = "AJ";
private var   C_A35      = "AK";
private var   C_A36      = "AL";
private var   C_A37      = "AM";
private var   C_A38      = "AN";
private var   C_A39      = "AO";
private var   C_A40      = "AP";
private var   C_A41      = "AQ";
private var   C_A42      = "AR";
private var   C_A43      = "AS";
private var   C_A44      = "AT";
private var   C_A45      = "AU";
private var   C_A46      = "AV";
private var   C_A47      = "AW";
private var   C_A48      = "AX";
private var   C_A49      = "AY";
private var   C_NU_1     = "AZ";
private var   C_NU_2     = "BA";
private var   C_K_1      = "BB";

private macro Oper_rshb():string
  var fio = GetPersnFIOByID(GetOperRecByID({oper}).PartyID);
  if(fio == "")
     return GetOperRecByID({oper}).Name;
  else
     return ConvetFIO_Report(fio);
  end;  
end;

  /********************************************************************************/
  /*  Особенности:                                                                */
  /*  1. Поскольку некоторые поля зависят друг от друга, а язык интерпретируемый, */  
  /*     постольку некоторые поля группами рассчитываются после получения выборки */
  /*  2.                                                                          */  
  /*  3.                                                                          */  
  /*  4.                                                                          */  
  /********************************************************************************/
  CLASS ReportData()
    var 
        valA1,  
        valA2,  
        valA3,  
        valA4,  
        valA5,  
        valA6,  
        valA7,  
        valA8,  
        valA9,  
        valA10, 
        valA11, 
        valA12,
        valA13, 
        valA14, 
        valA15, 
        valA16, 
        valA17, 
        valA18, 
        valA19, 
        valA20, 
        valA21, 
        valA22, 
        valA23, 
        valA24, 
        valA25, 
        valA26, 
        valA27, 
        valA28, 
        valA29, 
        valA30, 
        valA31, 
        valA32, 
        valA33, 
        valA34, 
        valA35, 
        valA36, 
        valA37, 
        valA38, 
        valA39, 
        valA40,
        valA41,
        valA42,
        valA43,
        valA44,
        valA45,
        valA46,
        valA47,
        valA48,
        valA49,
        valA50;

    macro set_A(Num, val, err)
      var stat = 0;
      if(Num < AMAX)
        GenSetProp(this, ANAME + Num, val);
      else 
        stat = 1;
      end; 
      SetParm( 3, stat );
    end;

    macro get_A(Num, err)
      var stat = 0;

      if(Num < AMAX)
        SetParm( 1, stat );
        return IIF( VALTYPE(GenGetProp(this, ANAME + Num)) != V_UNDEF, GenGetProp(this, ANAME + Num), "");
      else
        stat = 1;
      end;
      SetParm( 2, stat );
    end;

    macro ClearData()
      var i = 1;
      
      while (i < AMAX)
        GenSetProp(this,ANAME+i,NULL);
        i=i+1;
      end;
    end;

    private macro Constructor()
      ClearData();
    end;

    Constructor();
  END;

  //не нашёл степерь числа в RSL... пусть будет вот так
  MACRO _POWER ( src_base, src_power )
    var i_P;
    i_p = src_power;
    var accum = 1;
    while ( i_p > 0 )
      accum = accum * src_base;
      i_p = i_p - 1;
    end;
    return accum;
  END;

  private macro GetOrderByOprDoc(DocKind:integer, DocumentId:integer, BCID:integer, RetDocKind:@integer, RetDocumentId:@integer)
    RetDocKind = 0;
    RetDocumentId = 0;
    var Query = 
       " SELECT opr.T_DOCKIND, TO_NUMBER (opr.T_DOCUMENTID) AS T_DOCUMENTID"
      +"   FROM doprdocs_dbt odoc, DOPROPER_DBT opr"
      +"  WHERE     odoc.t_DocumentID = LTRIM (TO_CHAR (?, '0000000000'))"
      +"        AND odoc.t_DocKind = ?"
      +"        AND opr.t_ID_Operation = odoc.t_ID_Operation";
    var cmd = RSDCommand(Query);
    cmd.addParam( "", RSDBP_IN, DocumentId );
    cmd.addParam( "", RSDBP_IN, DocKind );
    cmd.execute(); 
    var ds = TRsbDataSet(cmd);
    if (not ds.MoveNext())
      return false;
    end;
    if (ds.DocKind == DL_VSSTORAGEORDER)
      Query =  "SELECT ORD.T_DOCKIND as t_DocKind, ORD.T_CONTRACTID as t_DocumentId"
              +"  FROM ddl_order_dbt ord, doproper_dbt opr, doprstep_dbt step"
              +" WHERE     ord.t_ContractId ="
              +"              (SELECT lnk.t_ContractId"
              +"                 FROM DOPROPER_DBT oper, dvsordlnk_dbt lnk"
              +"                WHERE     oper.t_DocKind IN ("+DL_VEKSELORDER+", "+DL_VSBARTERORDER+", "+DL_VSSALE+")"
              +"                      AND LPAD (lnk.t_ContractID, 10, '0') ="
              +"                             oper.t_DocumentID"
              +"                      AND lnk.t_DocKind = oper.t_DocKind"
              +"                      AND lnk.t_BCID = ?"
              +"                      AND oper.T_START_DATE <= (select T_CREATEDATE from DDL_ORDER_DBT where T_CONTRACTID = ?))"
              +"       AND ord.t_ContractId <> ?"
              +"       AND opr.t_DocKind = ord.t_DocKind"
              +"       AND opr.t_DocumentId = LPAD (ord.t_ContractId, 10, '0')"
              +"       AND step.t_ID_Operation = opr.t_ID_Operation"
              +"       AND (   (step.t_Symbol = 'М' AND ord.t_DocKind = "+DL_VSBARTERORDER+")"
              +"            OR (step.t_Symbol = 'О' AND ord.t_DocKind IN ("+DL_VSSALE+", "+DL_VEKSELORDER+")))"
              +"       AND step.T_ISEXECUTE = ?"
              +"       AND ROWNUM = 1;";
      cmd = RSDCommand(Query);
      cmd.addParam( "", RSDBP_IN, BCID );
      cmd.addParam( "", RSDBP_IN, ds.DocumentId );
      cmd.addParam( "", RSDBP_IN, ds.DocumentId );
      cmd.addParam( "", RSDBP_IN, SET_CHAR );
      cmd.execute();
      ds = TRsbDataSet(cmd);
      if (not ds.MoveNext())
        return false;
      end;
      RetDocKind = ds.DocKind;
      RetDocumentId = ds.DocumentId;
    else
      RetDocKind = ds.DocKind;
      RetDocumentId = ds.DocumentId;
    end;
    return true;
  end;

  private macro GetPlanRepayDate(BCID)
    var fd = VSBannerFD(DL_VSBANNER, BCID);
    return DL_GetBnrPlanRepayDate(fd.getbnr(), fd.getleg())
  end;

CLASS TableLineStruct()
 var _A01,
     _A02,
     _A03,
     _A04,
     _A05,
     _A06,
     _A07,
     _A08,
     _A09,
     _A10,
     _A11,
     _A12,
     _A12_1,
     _A13,
     _A14,
     _A15,
     _A16,
     _A17,
     _A18,
     _A19,
     _A20,
     _A21,
     _A22,
     _A23,
     _A24,
     _A25,
     _A26,
     _A27,
     _A28,
     _A29,
     _A30,
     _A31,
     _A32,
     _A33,
     _A34,
     _A35,
     _A36,
     _A37,
     _A38,
     _A39,
     _A40,
     _A41,
     _A42,
     _A43,
     _A44,
     _A45,
     _A46,
     _A47,
     _A48,
     _A49;
END;  
  
CLASS RegistryPeriod ( src_VekselID, src_PeriodDateBegin, src_PeriodDateEnd, src_PeriodType, src_IssueOrdId, src_RepId ) 
  var
  VekselID:INTEGER,
  PeriodDateBegin:DATE,
  PeriodDateEnd:DATE,
  PeriodType:INTEGER,
  IssueId:INTEGER,
  RepId:INTEGER;

  VekselID = src_VekselID;
  PeriodDateBegin = src_PeriodDateBegin;
  PeriodDateEnd = src_PeriodDateEnd ;
  PeriodType = src_PeriodType;
  IssueId = src_IssueOrdId;
  RepId = src_RepId;
END;

PRIVATE CLASS ( DL_CReportTemplate ) VS_Register_Report( Form:DL_CPanel, TemplateName:STRING, UseCSV:BOOL, IsWebService:BOOL, ReportHashCode:INTEGER, FocreFormatRep:INTEGER )
  PRIVATE CONST
    LineTypeData  = 0,
    LineTypeTotal = 2,
    LineType3     = 3;//в том числе
  var
    m_BeginDate:DATE,                //дата начала отчётного периода
    m_EndDate:DATE,                  //дата окончания отчётного периода
    m_CurCurrencyList,
    m_SelectedDepartamentList,
    m_Query:STRING,
    m_DataSetBanners,
    m_CmdQuery,
    m_CmdQueryFinnaly,
    m_NRecsBNRS:INTEGER,
    m_QueryFinnaly:STRING,    
    m_SubQueryFinnaly:STRING,    
    m_DataSetQueryFinnaly,       
    m_RegistryPeriodArray,
    m_FinalStatus,
    m_FinalState,
    m_TotalLineObj,
    m_fd,
    m_leg,
    m_bnr,
    m_isВексельДисконтный:BOOL,
    m_isВексельПроцентный:BOOL,
    m_Data,
    m_DataSize = 0;

  var m_form_Period        : Integer;  // Период для отчетной даты
  var m_form_Year          : Integer;  // Год, к которому относится отчетный период
  var m_form_AddItog       : Bool;     // Нарастающим итогом
  var NumStr_N1 :integer;
  var m_CopyAutoSumRange;

  var //значения полей, вычисления которых выполняют похожи участки кода. 
      //созданы для уменьшения дублирования кода
    m_N1_A3,  //Тип векселя
    m_N1_A4,  //Дата составления векселя
    m_N1_A6,  //Номинал векселя, в валюте но-минала 
    m_N1_A8,  //Дата погашения векселя в соот-ветствии с условиями выпуска векселя
    m_N1_A9,  //Плановый срок обращения век-селя, в днях
    
    m_N1_A10,  //Процентная ставка по условиям выпуска процентного векселя / расчетная ставка для дисконтно-го векселя, % годовых
    m_N1_A13,  //Цена размещения векселя, в валюте номинала
    m_N1_A14,  //Дисконт в соответствии с усло-виями размещения дисконтного векселя, в валюте номинала
    m_N1_A44,  //Размер процентной ставки <A43> на дату фактической выдачи векселя <A12>.
    m_N1_A45;  //Предельное значение ставки, % годовых
    
  var
    m_N1_A25_TOTAL = 0.0,
    m_N1_A26_TOTAL = 0.0,
    m_N1_A27_TOTAL = 0.0,
    m_N1_A28_TOTAL = 0.0,
    m_N1_A29_TOTAL = 0.0,
    m_N1_A30_TOTAL = 0.0,
    m_N1_A31_TOTAL = 0.0,
    m_N1_A40_TOTAL = 0.0,
    m_N1_A6_TOTAL  = 0.0,
    m_N1_A13_TOTAL = 0.0,
    m_N1_A14_TOTAL = 0.0,
    m_N1_A16_TOTAL = 0.0,
    m_N1_A17_TOTAL = 0.0,
    m_N1_A18_TOTAL = 0.0,
    m_N1_A23_TOTAL = 0.0,
    m_N1_A20_TOTAL = 0.0,
    m_N1_A21_TOTAL = 0.0;
    
   PRIVATE CONST НОМЕР_НАЧАЛЬНОЙ_СТРОКИ_СУММ_rshb = 13;
   PRIVATE CONST НОМЕР_СТРОКИ_ИТОГОВЫХ_СУММ_rshb = 7;
   
   macro sumBeginLine()
      return НОМЕР_НАЧАЛЬНОЙ_СТРОКИ_СУММ_rshb;
   end;

   macro FullRange(sheet, col):string
      var s:string = "";
      var e:integer = sumBeginLine() + MAXROWSHEET;
      if((sheet == null) or (sheet = ""))
         s = "";
      else
         s = "'" + sheet + "'!";
      end;
      s = s + "$" + col + "$" + sumBeginLine();
      s = s + ":$" + col + "$" + e;
      return s;
   end;

   macro GetColRange(sheet, col, rangeSize):string
      var s:string = "";
      var e:integer = sumBeginLine() + rangeSize - 1;
      if(rangeSize < 1) 
         return "";
      end;
      if((sheet == null) or (sheet = ""))
         s = "";
      else
         s = "'" + sheet + "'!";
      end;
      s = s + "$" + col + "$" + sumBeginLine();
      s = s + ":$" + col + "$" + e;
      return s;
   end;

   MACRO Set_SUMFormula(FirstColumn, point )
      var Formula = "";
      var SheetName = "";

      if (point == null) point = 2; end;

      if (m_UseTemplate)
         SheetName = m_ObjTemplateXLS.SheetName();

         if (m_ObjTemplateXLS.ExcelLanguageInterface != EXCEL_INTERFACE_RUS) 
              Formula = "ROUND(SUM(";
          else                  
              Formula = "ОКРУГЛ(СУММ(";
         end;

         return "="+Formula+FirstColumn+");"+point+")";
      end;
   END;

   macro FSum_Col(sheet, col, rangeSize)
      var range;
      if(rangeSize == null)
        range = FullRange(sheet, col);
      else
        range = GetColRange(sheet, col, rangeSize);
      end;

      return this.Set_SUMFormula( range );
   end;

   macro GetItogCell(Col):string
      return "$"+Col+"$"+НОМЕР_СТРОКИ_ИТОГОВЫХ_СУММ_rshb;
   end;

   macro SetCopyAutoSumRange(r)
      m_CopyAutoSumRange = r;
   end;

   macro PrintLineAutoSumma()
      VAR Address, CellAddr, StrSumm;
      VAR i = 0, OldSheet;
      var FirstRange, FirstAddr;
      var numCell = 0;
      var BeginRow = 1;
    
      if((m_CopyAutoSumRange == null) or (m_CopyAutoSumRange == ""))
         return;
      end;

      if( not m_UseTemplate )
        return;
      end;
      if(m_ObjTemplateXLS.UsePOI())
        return;
      end;

      if( m_ItogLineName != NULL ) // в первой строке таблицы
        OldSheet = m_ObjTemplateXLS.SheetName();
        m_ObjTemplateXLS.SheetChange( m_FirstSheetName );
      end;

      FirstRange = m_ObjTemplateXLS.sheet.Range( m_CopyAutoSumRange );
      FirstAddr  = CAddressDiapazon( FirstRange.Address );

      while( i < m_NumCellAutoSumm.Size )

        numCell = NC( m_NumCellAutoSumm[i] );
        Address = FirstAddr.GetCell(0, numCell );

        m_ObjTemplateXLS.SetValue_NameCell( Address, m_FormulaSumm[i] );
        i = i + 1;
      end;

      if( m_ItogLineName != NULL ) // в первой строке таблицы
        m_ObjTemplateXLS.SheetChange( OldSheet );
      end;

   end;

  PRIVATE MACRO GetFormulaSumm()
    VAR i = 0, StrSumm = "", BeginRow, CellAddr;
    
    while( i < m_NumCellAutoSumm.Size )

        CellAddr = m_ReportTable.AddressDiapazon.GetCell( 0, NC( m_NumCellAutoSumm[i] ) );

        if( m_ReportTable.AddressDiapazon.GetNumbRow() > 0 )
          StrSumm = m_ReportTable.GetFormulaSumm( CellAddr, null, m_ReportTable.bRowTable, m_ReportTable.bRowTable+m_ReportTable.AddressDiapazon.GetNumbRow()-1 );
        else
          StrSumm = "";
        end;

        if( m_FormulaSumm[i] == null ) /*для первой вкладки*/
          m_FormulaSumm[i] = "";
        elif( substr(StrSumm, 1,1) == "=" )
          StrSet( StrSumm, 1, "+" );
        end;
        m_FormulaSumm[i] = m_FormulaSumm[i] + StrSumm;
        i = i + 1;
    end;
  END;

    
  PRIVATE MACRO InitVariables()
    var y, y2;

    if( m_IsWebService )
      m_BeginDate = WebFormData.BeginDate;
      m_EndDate   = WebFormData.EndDate;
      m_CurCurrencyList = WebFormData.CurFIIDList;
      m_SelectedDepartamentList = WebFormData.CurDepartmentList;
      m_form_Period = WebFormData.Period;
      m_form_Year =  WebFormData.Year;
      m_form_AddItog = WebFormData.AddItog;

    else
      m_BeginDate = VSRegister_Form.GetFieldValue(PNFLD_DLREGREP_BEGINDATE);
      m_EndDate   = VSRegister_Form.GetFieldValue(PNFLD_DLREGREP_ENDDATE);
      if (VSRegister_Form.GetFieldValue(PNFLD_DLREGREP_FI) != ALLFININSTR)
        m_CurCurrencyList = TArray();
        var fininstr = Tbfile("fininstr.dbt", "R", 0);
        fininstr.Clear();
        fininstr.rec.FIID = VSRegister_Form.GetFieldValue(PNFLD_DLREGREP_FI);
        fininstr.GetEQ();
        m_CurCurrencyList[m_CurCurrencyList.size] = TWsFinInstr(fininstr.rec.fiid, null, fininstr.rec.fi_code, fininstr.rec.fi_kind, null, fininstr.rec.name);
      end;
      if (VSRegister_Form.GetFieldValue(PNFLD_DLREGREP_DEPARTCODE) != -1)
        m_SelectedDepartamentList = TArray();
        var Dprt:TWsDepartment;
        Dprt.Code = VSRegister_Form.GetFieldValue(PNFLD_DLREGREP_DEPARTCODE);
        Dprt.PartyName = DL_GetDepartmentNameByCode(Dprt.Code);
        m_SelectedDepartamentList[m_SelectedDepartamentList.size] = Dprt;
      end;

      // getfromform
      VSRegister_Form.GetFieldValue( PNFLD_DLREGREP_YEAR, @y, @y2 );
      m_form_Year =  y2;

      VSRegister_Form.GetFieldValue( PNFLD_DLREGREP_PERIOD, @y, @y2 );
      m_form_Period = y2;

      VSRegister_Form.GetFieldValue( PNFLD_DLREGREP_GROWTH, @y, @y2 );
      if(y2 == "X")
         m_form_AddItog = true;
      else
         m_form_AddItog = false;
      end;
    end;
    m_RegistryPeriodArray = TArray();
    m_TotalLineObj = TableLineStruct();
    m_Data = TArray;

    m_NRecsBNRS = 0;
    NumStr_N1 = 0;
  END;
  
  PRIVATE MACRO DataExist()
    return m_NRecsBNRS > 0;
  END;
 
  PRIVATE MACRO PrintMode():INTEGER
     return DL_OUTREPORT_EXCEL;
  END;

  PRIVATE MACRO SetSqlDataQuery()
    /***********************************************************/
    /* берём векселя, не погашенные к началу отчётного периода */
    /* и имеющие на конец отчётного периода статусы:           */
    /* "Выдан", "Выкуплен" или "Погашен"                       */
    /***********************************************************/
    var _index = 0;
    var DepStr = "";
    if ( ( m_SelectedDepartamentList != NULL ) and ( m_SelectedDepartamentList.size > 0 ) )
      while  (_index < m_SelectedDepartamentList.size)
        if (_index > 0 )
          DepStr = DepStr + ",";
        end;
        DepStr = DepStr + m_SelectedDepartamentList[_index].Code;
        _index = _index + 1;
      end;
    end;

    var PFIStr = "";
    var _indexPFI = 0;
    if ( ( m_CurCurrencyList != NULL ) and ( m_CurCurrencyList.size > 0 ) )
      while  (_indexPFI < m_CurCurrencyList.size)
        if (_indexPFI > 0 )
          PFIStr = PFIStr + ",";
        end;
        PFIStr = PFIStr + m_CurCurrencyList[_indexPFI].FIID;
        _indexPFI = _indexPFI + 1;
      end;
    end;
    
    m_Query =           " SELECT bnr.t_bcid, ";
    m_Query = m_Query + "         legbnr.t_pfi, ";
    m_Query = m_Query + "         rsb_bill.GetBNRFirstDate (bnr.t_bcid, lnk.t_ContractID) FirstDate ";
    m_Query = m_Query + "   FROM dvsbanner_dbt Bnr, ";
    m_Query = m_Query + "         dvsordlnk_dbt lnk, ";
    m_Query = m_Query + "         ddl_leg_dbt legbnr ";
    m_Query = m_Query + "   WHERE lnk.t_BCID = bnr.t_BCID ";
    m_Query = m_Query + "     AND rsb_bill.GetVSBnrStatusOnDate(bnr.t_bcid, ?) != ? ";
    m_Query = m_Query + "     AND rsb_bill.GetVSBnrStatusOnDate(bnr.t_bcid, ?) IN (?, ?, ?, ?) ";
    m_Query = m_Query + "     AND lnk.t_DocKind IN (109, 113, 124, 114) ";
    m_Query = m_Query + "     AND legbnr.t_DealId = Bnr.t_bcid ";
    m_Query = m_Query + "     AND legbnr.t_LegKind = 1 ";
    m_Query = m_Query + "     AND lnk.t_ContractID IN (SELECT TO_NUMBER (opr.T_DOCUMENTID) AS T_DOCUMENTID ";
    m_Query = m_Query + "                               FROM doprdocs_dbt odoc, DOPROPER_DBT opr ";
    m_Query = m_Query + "                               WHERE odoc.t_DocumentID = (SELECT CASE ";
    m_Query = m_Query + "                                                                 WHEN rsb_bill.GetVSBnrStatusOnDate(bnr.t_bcid, ?) in (20, 25) ";
    m_Query = m_Query + "                                                                 THEN (SELECT LTRIM ( TO_CHAR ( MAX ( BnrHist.t_id), '0000000000')) DocID ";
    m_Query = m_Query + "                                                                         FROM dvsbnrbck_dbt BnrHist ";
    m_Query = m_Query + "                                                                       WHERE BnrHist.t_BCID = Bnr.t_bcid ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_BCStatus = 'X' ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_NewabcStatus = 20 ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_OldabcStatus != 20 ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_OldabcStatus != 25 ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_ChangeDate <= ?) ";
    m_Query = m_Query + "                                                               WHEN rsb_bill.GetVSBnrStatusOnDate(bnr.t_bcid, ?) = 0 ";
    m_Query = m_Query + "                                                               THEN (SELECT LTRIM ( TO_CHAR ( MIN (BnrHist.t_id), '0000000000')) DocID ";
    m_Query = m_Query + "                                                                       FROM dvsbnrbck_dbt BnrHist ";
    m_Query = m_Query + "                                                                       WHERE BnrHist.t_BCID = Bnr.t_bcid ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_BCStatus = 'X' ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_NewabcStatus = 20 ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_OldabcStatus != 20 ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_OldabcStatus != 25 ";
    m_Query = m_Query + "                                                                         AND BnrHist.t_ChangeDate BETWEEN ?  ";
    m_Query = m_Query + "                                                                                                     AND ?) ";
    m_Query = m_Query + "                                                         END FROM DUAL) ";
    m_Query = m_Query + "                                 AND odoc.t_DocKind = 191 ";
    m_Query = m_Query + "                                 AND opr.t_ID_Operation = odoc.t_ID_Operation) ";

    if (DepStr != "")
      m_Query = m_Query + "  AND Bnr.t_Department in ("+DepStr+") ";
    end;
    if (PFIStr != "")
      m_Query = m_Query + "  and legbnr.t_PFI in ("+PFIStr+") ";
    end;
    m_Query = m_Query + " GROUP BY bnr.t_bcid, lnk.t_ContractID, legbnr.t_PFI ";
    m_Query = m_Query + " ORDER BY legbnr.t_PFI, FirstDate ";
  END;

  PRIVATE MACRO SetSqlDataSet()    
    m_CmdQuery = RSDCommand("SELECT COUNT(*) nRecs FROM (" + m_Query + ")");
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_REPAYED );
    m_CmdQuery.addParam( "", RSDBP_IN, m_EndDate );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_REPAYED );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_ISSUED );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_REBUYED );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_DEPOSIT );
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, m_EndDate );
    m_CmdQuery.execute(); 
    
    var  tm_dataSet = TRsbDataSet(m_CmdQuery);
    if ( tm_dataSet.moveNext() )
        m_NRecsBNRS = Int(tm_dataSet.nRecs);
    else
        m_NRecsBNRS = 0;
    end;

 
  
    m_CmdQuery = RSDCommand(m_Query);
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_REPAYED );
    m_CmdQuery.addParam( "", RSDBP_IN, m_EndDate );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_REPAYED );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_ISSUED );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_REBUYED );
    m_CmdQuery.addParam( "", RSDBP_IN, VS_STATUS_DEPOSIT );
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, m_BeginDate );
    m_CmdQuery.addParam( "", RSDBP_IN, m_EndDate );
    m_CmdQuery.execute();    
    
    m_DataSetBanners = TRsbDataSet( m_CmdQuery );
       
  END;
  
  PRIVATE MACRO SetRegistryPeriodsForBanner( srcBnrID )
    var local_period;
    m_RegistryPeriodArray.size = 0;
    var PeriodDateBegin:date;
    var PeriodDateEnd:date;
    var planRepayDate:date;
    PeriodDateBegin = ZeroDate;    
    PeriodDateEnd = ZeroDate;
    planRepayDate = GetPlanRepayDate(srcBnrID);
    var isValidPeriod:BOOL;
    var isCorrecting:BOOL;
    var issueOrderId:integer;
    var repOrderId:integer;
    issueOrderId = 0;
    repOrderId = 0;
    //изначально период неподходящий, очевидно, и исправлять никого не надо.
    isValidPeriod = false;
    isCorrecting  = false;
    
    /*****************************************************************************/
    /* просмотр истории векселя от "начал времён" до окончания отчётного периода */
    /*****************************************************************************/
    var Query =         "   select BnrHist.t_ID, BnrHist.t_ChangeDate, BnrHist.t_NewabcStatus status, BnrHist.t_OldabcStatus prev_status ";
        Query = Query + "     from dvsbnrbck_dbt BnrHist ";
        Query = Query + "    where BnrHist.t_BCID = ? ";
        Query = Query + "      and BnrHist.t_BCStatus = 'X' ";        
        Query = Query + "      and BnrHist.t_ChangeDate <= ? ";        
        Query = Query + " order by BnrHist.t_ChangeDate, BnrHist.t_ID ";
    var cmd = RSDCommand( Query );
    cmd.addParam( "", RSDBP_IN, srcBnrID );
    cmd.addParam( "", RSDBP_IN, m_EndDate );
    cmd.execute(); 
    var DS = TRsbDataSet( cmd );
    /*****************************************************************/    
    /* здесь небольшой велосипед:                                    */
    /* необходимо учесть возможность начала действия статуса "Выдан" */
    /* до начала отчётного периода                                   */
    /* а так же действие статуса "Выдан" на конец отчётного периода  */
    /*****************************************************************/
    
    /*комментарии внутри алгоритма вынес наверх:*/
    
    /*******************************************************/
    /* если вексель в ту или иную дату стал "выданным"     */
    /* то, очевидно, считаем, что нашли начало             */
    /* приняв за то, что историчная целостность сохранена, */
    /* проверку на корректность истории векселя не делаем  */
    /*******************************************************/

    /*******************************************************/
    /* если вексель в ту или иную перестал быть "выданным" */
    /* то, очевидно, считаем, что нашли конец              */
    /* приняв за то, что историчная целостность сохранена, */
    /* проверку на корректность истории векселя не делаем  */
    /*******************************************************/
    
    /***********************************************************************************/
    /* Однако велосипед не был бы им, если бы не одно но:                              */
    /* Если вексель перестал быть "выданным" и вновь стал таковым в одну и ту же дату, */
    /* то Учётный Период продолжается.                                                 */
    /* В Банке, заказавшего этот отчёт, у клиентов одинаковые условия налогообложения. */
    /* принимаем за истину, что историчная целостность сохранена,                      */
    /* проверку на корректность истории векселя не делаем                              */
    /***********************************************************************************/
    
    /******************************************************************/
    /* итого, алгоритм работает в режиме "вставил-скорректировал"     */
    /* то есть, предварительно каждый найденный период считаем верным */
    /******************************************************************/
    MACRO СброситьПериоды_и_Флаги()
      isValidPeriod = false;
      PeriodDateBegin = ZeroDate;    
      PeriodDateEnd = ZeroDate;
      isCorrecting = false;
      issueOrderId = 0;
      repOrderId = 0;
    END;

    while ( DS.MoveNext )
      if ( ( DS.status == VS_STATUS_ISSUED ) and ( DS.prev_status != VS_STATUS_ISSUED ) )     //изменился на "выдан"
          if ( ( PeriodDateBegin == ZeroDate ) and ( PeriodDateEnd == ZeroDate ) )
            GetOrderByOprDoc(DL_VSBNRBCK, DS.Id, srcBnrID, NULL, @issueOrderId);
            PeriodDateBegin = DS.ChangeDate;
            isValidPeriod = true;
          else
            /*в противном случае - корректировка предыдущего периода:                   */
            /* сдвигаем его окончание до конча отчётного периода и переводим в открытый */
            if (m_RegistryPeriodArray.size > 0)
              m_RegistryPeriodArray[m_RegistryPeriodArray.size - 1].PeriodDateEnd = m_EndDate;
              m_RegistryPeriodArray[m_RegistryPeriodArray.size - 1].PeriodType = PeriodTypeOpen;
              isCorrecting = true;  /*корректировка нужна */
              isValidPeriod = false;/*вставка    не нужна */
            end;
          end;
      end;
      
      if ( ( DS.prev_status == VS_STATUS_ISSUED ) and ( ( DS.status == VS_STATUS_REPAYED) or ( DS.status == VS_STATUS_REBUYED ) ) )//изменился с  "выдан" на "погашен" или "выкуплен"
        if (m_BeginDate > DS.ChangeDate)
          СброситьПериоды_и_Флаги;
        else
          if   ( isValidPeriod == true )
            /*окончание для нового учётного периода*/
            PeriodDateEnd =DS.ChangeDate;
            GetOrderByOprDoc(DL_VSBNRBCK, DS.Id, srcBnrID, NULL, @repOrderId);
          elif ( isCorrecting == true )
            if (m_RegistryPeriodArray.size > 0)
              /*окончание для предыдущего учётного периода*/
              m_RegistryPeriodArray[m_RegistryPeriodArray.size - 1].PeriodDateEnd = DS.ChangeDate;
              m_RegistryPeriodArray[m_RegistryPeriodArray.size - 1].PeriodType = PeriodTypeClose;
              /*корректировка закончена, сбрасываемся на дефолт*/
              СброситьПериоды_и_Флаги;
            end;
          end;
        end;
      end;
      
      if ( ( isValidPeriod == true ) and ( PeriodDateBegin != ZeroDate ) and ( PeriodDateEnd != ZeroDate ) )
        m_RegistryPeriodArray[m_RegistryPeriodArray.size] = RegistryPeriod( srcBnrID, PeriodDateBegin, PeriodDateEnd, PeriodTypeClose, issueOrderId, repOrderId);
        СброситьПериоды_и_Флаги;
      end;
    end;
    /***********************************************************/
    /*ds находится на последней позиции её анализируем отдельно*/
    /***********************************************************/
    if ( ( isValidPeriod == true ) and ( PeriodDateBegin != ZeroDate ) )
        m_RegistryPeriodArray[m_RegistryPeriodArray.size] = RegistryPeriod(srcBnrID, PeriodDateBegin, min(m_EndDate,planRepayDate), PeriodTypeOpen, issueOrderId, repOrderId);
        СброситьПериоды_и_Флаги;
    end;
    
  END;
  PRIVATE MACRO Вычислить_A3_A8_A9()
    //составные части для "ТИП векселя":
    var _FirstSymbols:STRING;
    var _SecondSymbols:STRING;
    var _ThirdSymbols:STRING;
    var date_repay_cond;
    var days_before_repay;

    m_N1_A4 = SQL_ConvTypeDate( m_DataSetQueryFinnaly.IssueDate );
    _FirstSymbols = ""; _SecondSymbols = ""; _ThirdSymbols = "";

    if (m_isВексельПроцентный)
      _FirstSymbols = "П";
    elif (m_isВексельДисконтный)
      _FirstSymbols = "Д";
    else
      _FirstSymbols = "Б";
    end;

    if ( m_DataSetQueryFinnaly.BCTermFormula == VS_TERMF_FIXEDDAY)               //День. На определенный день      
      _SecondSymbols = "ос";
      date_repay_cond = SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Maturity );
      days_before_repay = date_repay_cond - date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate);
    end;
    if ( m_DataSetQueryFinnaly.BCTermFormula == VS_TERMF_INATIME)                //Период. Во столько-то времени от составления      
      _SecondSymbols = "свс";
      date_repay_cond = SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Maturity );
      days_before_repay = date_repay_cond - date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate);
    end;
    if ( m_DataSetQueryFinnaly.BCTermFormula == VS_TERMF_ATSIGHT)                //По предъявлении. По предъявлении

      _SecondSymbols = "пп";
      /*******************************/
      /*небольшой алгоритм для       */
      /*расширения "по предъявлении" */
      /*******************************/
      if( ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Maturity ) < SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) // Просто по предъявлении
      and ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry ) < SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) )
            _ThirdSymbols = "";
            date_repay_cond = m_N1_A4;
            days_before_repay = date_repay_cond - date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate) + DaysInYearByBasis( m_DataSetQueryFinnaly.leg_Basis, date_repay_cond, true );
      else        
        if( ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry ) < SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) // По предъявлении, но не ранее
        and ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Maturity ) >= SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) )
            _ThirdSymbols = "нн";
            date_repay_cond = SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Maturity ); // "не ранее даты"
            if( date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate) < date(1,1,2011) )
              days_before_repay = date_repay_cond - date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate);
              if( days_before_repay < 0 )
                days_before_repay = 0;
              end;
            else
              days_before_repay = date_repay_cond - date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate) + DaysInYearByBasis( m_DataSetQueryFinnaly.leg_Basis, date_repay_cond, true );
            end; 
        elif( ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry ) >= SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) // По предъявлении, но не позднее
          and ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Maturity ) < SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) )            
            _ThirdSymbols = "нп";
            date_repay_cond = SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry );
            days_before_repay = date_repay_cond - date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate);
        else // По предъявлении, но не ранее и не позднее
            _ThirdSymbols = "нннп";
            date_repay_cond = SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry );
            days_before_repay = date_repay_cond - date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate);
        end;
      end;
    end;
    if ( m_DataSetQueryFinnaly.BCTermFormula == VS_TERMF_DURING)
      //От предъявления. Во столько-то времени от предъявления
      _SecondSymbols = "свп";
      date_repay_cond = m_N1_A4;
      days_before_repay = date_repay_cond - date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate) + DaysInYearByBasis( m_DataSetQueryFinnaly.leg_Basis, date_repay_cond, true );
    end;
    
    
    m_N1_A3 = _FirstSymbols + _SecondSymbols + _ThirdSymbols;
    m_N1_A8 = date_repay_cond;
    m_N1_A9 = days_before_repay;
  END;
  PRIVATE MACRO Вычислить_А6_А10_А13_А14();//для уменьшение дублирования кода
    m_N1_A6 = m_DataSetQueryFinnaly.leg_Principal;
    m_N1_A13 = m_DataSetQueryFinnaly.ISSUEpaym_Amount;//цена размещения векселя из платежа
    if ( m_isВексельПроцентный )
      m_N1_A14 = null;
      m_N1_A10 = m_DataSetQueryFinnaly.leg_Price;
    else      
      m_N1_A14 = m_N1_A6 - m_N1_A13;//Дисконт в соответствии с усло-виями размещения дисконтного векселя, в валюте номинала
      m_N1_A10 = (m_N1_A14 / m_N1_A13 ) / m_N1_A9 * DaysInYearByBasis( m_DataSetQueryFinnaly.leg_Basis, date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate), true) * 100; //Процентная ставка по условиям выпуска процентного векселя / расчетная ставка для дисконтного векселя, % годовых
    end;
  END;
  PRIVATE MACRO Вычислить_A44_A45();
    var StRate;
    if( not СтавкаРефинансированияЦБ(NATCUR, date(m_DataSetQueryFinnaly.ISSUEpaym_ValueDate), StRate) )
      //return Error("Не найдена ставка рефинансирования ЦБ РФ на ", date(DataSet.DatePay2Fact));
      m_N1_A44 = 0.0;
      m_N1_A45 = 0.0;
    else
      m_N1_A44 = StRate;           /*вал.расч = вал.цены. смотрим - рубли ли это*/
      m_N1_A45 = StRate * IIF(  (m_DataSetQueryFinnaly.leg_PFI == NATCUR) ,1.25 ,0.7 );
    end;
  END;
  PRIVATE MACRO ПровестиДополнительныеВычисления()
    /****************************************************/
    /* узнаем статус векселя на конец ОТЧЕТНОГО периода */
    /****************************************************/
    var Query = " select rsb_bill.GetVSBnrStatusOnDate( ?,? ) FinalStatus, rsb_bill.GetVABnrStateOnDate( ?,? ) FinalState from dual ";
    var cmd = RSDCommand(Query);

    cmd.addParam( "", RSDBP_IN, m_DataSetBanners.BCID );
    cmd.addParam( "", RSDBP_IN, m_EndDate );
    cmd.addParam( "", RSDBP_IN, m_DataSetBanners.BCID );
    cmd.addParam( "", RSDBP_IN, m_EndDate );
    cmd.execute();
    var cmdData = TRsbDataSet(cmd);
    if( cmdData.MoveNext() )
      m_FinalStatus = SQL_ConvTypeInteger(cmdData.FinalStatus);
      m_FinalState = SQL_ConvTypeInteger(cmdData.FinalState);
    end;
    /***************************************************************************/
    /* заполенине структур, используемых при вызове функций из других макросов */
    /***************************************************************************/
    m_fd = VSBannerFD(DL_VSBANNER, m_DataSetQueryFinnaly.BCID);
    m_leg = m_fd.getleg();
    m_bnr = m_fd.getbnr();
    /***************************************************/
    /* заполение флагов процентый / дисконтынй вексель */
    /***************************************************/
    if (ВексельДисконтный (m_leg,m_bnr))
      m_isВексельДисконтный = true;
    else
      m_isВексельДисконтный = false;
    end;

    if (ВексельПроцентный (m_DataSetQueryFinnaly.leg_Formula, m_DataSetQueryFinnaly.leg_Price))
      m_isВексельПроцентный = true;
    else
      m_isВексельПроцентный = false;
    end;    
  END;
    
  PRIVATE MACRO GetFullDepNameByCurrOper():STRING
    var Query = " Select pt.t_name from dparty_dbt pt                                   "+
                "        join ddp_dep_dbt dep on dep.t_partyId = pt.t_partyId           "+
                "        join dperson_dbt ps  on dep.t_code    = ps.t_codedepart        "+
                "                            and  ps.t_oper    = " + {oper};
    var DepName;
    var cmd = RSDCommand(Query);
        cmd.execute();      
    var cmdData = TRsbDataSet(cmd);
    if( cmdData.MoveNext() )
          DepName   = cmdData.name;
    end;
    return DepName;                
  END;
    
  PRIVATE MACRO GetDepNameByCurrOper():STRING
    var Query = " Select pt.t_shortname from dparty_dbt pt                              "+
                "        join ddp_dep_dbt dep on dep.t_partyId = pt.t_partyId           "+
                "        join dperson_dbt ps  on dep.t_code    = ps.t_codedepart        "+
                "                            and  ps.t_oper    = " + {oper};
    var DepName;
    var cmd = RSDCommand(Query);
        cmd.execute();
    var cmdData = TRsbDataSet(cmd);
    if( cmdData.MoveNext() )
          DepName   = cmdData.shortname;
    end;
    return DepName;
                
  END;

  PRIVATE MACRO GetTypeVekselString():STRING    
    var _FirstSymbols:STRING;
    var _SecondSymbols:STRING;
    var _ThirdSymbols:STRING;
    _FirstSymbols = ""; _SecondSymbols = ""; _ThirdSymbols = "";
    
    if (m_isВексельПроцентный)
      _FirstSymbols = "П";
    else
      _FirstSymbols = "Д";
    end;
        
    if ( m_DataSetQueryFinnaly.BCTermFormula == VS_TERMF_FIXEDDAY)
      //День. На определенный день
      _SecondSymbols = "ос";
    end;
    if ( m_DataSetQueryFinnaly.BCTermFormula == VS_TERMF_INATIME)
      //Период. Во столько-то времени от составления
      _SecondSymbols = "свс";
    end;
    if ( m_DataSetQueryFinnaly.BCTermFormula == VS_TERMF_ATSIGHT)
      //По предъявлении. По предъявлении
      _SecondSymbols = "пп";
      /*******************************/
      /*небольшой алгоритм для       */
      /*расширения "по предъявлении" */
      /*******************************/
      if( ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Maturity ) < SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) // Просто по предъявлении
      and ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry ) < SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) )
            _ThirdSymbols = "";
      else        
        if( ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry ) < SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) // По предъявлении, но не ранее
        and ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Maturity ) >= SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) )
            _ThirdSymbols = "нн";
        elif( ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry ) >= SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) // По предъявлении, но не позднее
          and ( SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Maturity ) < SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start ) ) )
            _ThirdSymbols = "нп";
        else // По предъявлении, но не ранее и не позднее
            _ThirdSymbols = "нннп";
        end;
      end;
    end;
    if ( m_DataSetQueryFinnaly.BCTermFormula == VS_TERMF_DURING)
      //От предъявления. Во столько-то времени от предъявления
      _SecondSymbols = "свп";
    end;
    return _FirstSymbols + _SecondSymbols + _ThirdSymbols;
  END;
  PRIVATE MACRO _getINN(INN)
    var innKpp = StrSubst(INN,"\\","/");
    var rinn="";
    if (SplitFullINN (innKpp, rinn, NULL) == 0)
      return rinn;
    else
      return innKpp;
    end;
  END;
  
  PRIVATE MACRO _getKPP(INN)
    var innKpp = StrSubst(INN,"\\","/");
    var rkpp="";
    if (SplitFullINN (innKpp, NULL, rkpp) == 0)
      return rkpp;
    else
      return innKpp;
    end;
  END;
  
  /*****************************************/
  /* Блок вычисления значений полей отчёта */
  /*****************************************/
  
  PRIVATE MACRO N1_H0_1()
    return date_as_string( 1, m_BeginDate, false );
  END;
  PRIVATE MACRO N1_H0_2()
    return date_as_string( 1, m_EndDate, false );
  END;
  PRIVATE MACRO N1_H0_A()
    return GetFullDepNameByCurrOper();
  END;
  PRIVATE MACRO N1_H0_В()  //ИНН
    var INN="";
    INN = ПолучитьКодСубъекта({ourbank}, PTCK_INN );
    return _getINN(INN);
  END;
  PRIVATE MACRO N1_H0_C()  //КПП
    var INN="";
    INN = ПолучитьКодСубъекта({ourbank}, PTCK_INN );
    return _getKPP(INN);    
  END;
  PRIVATE MACRO N1_H0_3()
    if (  (m_CurCurrencyList == NULL) or (m_CurCurrencyList.size == 0) or (m_CurCurrencyList.size > 1) ) 
      return " " ;
    else
      return m_CurCurrencyList[0].CodeList;
    end;
  END;  
  PRIVATE MACRO N1_H0_4()    
    if (  (m_CurCurrencyList == NULL) or (m_CurCurrencyList.size == 0) or (m_CurCurrencyList.size > 1) ) 
      return " " ;
    else
      return m_CurCurrencyList[0].Name;
    end;
  END;
  PRIVATE MACRO N1_H1()
    if ( ( m_SelectedDepartamentList == NULL ) or (m_SelectedDepartamentList.size == 0) or ( m_SelectedDepartamentList.Size > 1) )
      return " " ;
    else
      return m_SelectedDepartamentList[0].PartyName;
    end;
  END;

/////////////////////////////////////


  PRIVATE MACRO GetFromForm_GROWTH()
    return m_form_AddItog;
  END;

  PRIVATE MACRO GetFromForm_PERIOD()
    return m_form_Period;
  END;


   macro GetYear():string
     return string(m_form_Year);
   end;

   macro GetPeriodCode():string
      var code = "";
      var p, p2;
      var gr:bool = false;

      gr = GetFromForm_GROWTH();
      p2 = GetFromForm_PERIOD();
      if((p2 == 13) or (gr and (p2 == 3)))
         code = "21";
      elif(gr and ((p2 == 14) or (p2 == 6)))
         code = "31";
      elif(gr and ((p2 == 15) or (p2 == 9)))
         code = "33";
      elif(gr and ((p2 == 16) or (p2 == 12)))
         code = "34";
      end;

      return code;
   end;

   macro GetPeriodTxt():string
      const ytxt = " ГОДА";
      const y2txt = " ГОД";
      const mtxt = " МЕСЯЦЕВ ";
      const m2txt = " МЕСЯЦА ";
      const qtxt = " КВАРТАЛ ";

      var code = "";
      var p, p2;
      var gr:bool = false;
      var y = GetYear();

      gr = GetFromForm_GROWTH();
      p2 = GetFromForm_PERIOD();
      if((p2 == 13) or (gr and (p2 == 3))) // 1 кв
         code = "1"+qtxt+y+ytxt;
      elif(gr and ((p2 == 14) or (p2 == 6)))
         code = "I ПОЛУГОДИЕ " + y + ytxt;
      elif(gr and ((p2 == 15) or (p2 == 9)))
         code = "9" + mtxt + y + ytxt;
      elif(gr and ((p2 == 16) or (p2 == 12)))
         code = y + y2txt;
      elif((p2 == 1))
         code = StrUpr( MonName(p2) ) + " " + y + ytxt;
      elif(gr and (p2 > 1) and (p2 < 5))
         code = string(p2) + m2txt + y + ytxt;
      elif(gr and (p2 > 4) and (p2 < 12))
         code = string(p2) + mtxt + y + ytxt;
      elif((not gr) and (p2 > 13) and (p2 < 17))
         code = string(p2-12) + qtxt + y + ytxt;
      elif((not gr) and (p2 > 0) and (p2 < 13))
         code = StrUpr( MonName(p2) ) + " " + y + ytxt;
      end;

      return code;
   end;

//////////////////////////////////////

  PRIVATE MACRO N1_FilialText()
    if ( ( m_SelectedDepartamentList == NULL ) or (m_SelectedDepartamentList.size == 0) or ( m_SelectedDepartamentList.Size > 1) )
      return " " ;
    else
      return "Филиал";
    end;
  END;
  PRIVATE MACRO N1_Text1()
    if (  (m_CurCurrencyList == NULL) or (m_CurCurrencyList.size == 0) or (m_CurCurrencyList.size > 1) ) 
      return " " ;
    else
      return "Валюта номинала векселя:";
    end;  
  END;
  
  PRIVATE MACRO N1_A1():STRING
    return m_DataSetQueryFinnaly.DepCode;
  END;
  PRIVATE MACRO N1_A2():STRING
    return  Trim(m_DataSetQueryFinnaly.BCSeries) + " " + Trim(m_DataSetQueryFinnaly.BCNumber);
  END;
  PRIVATE MACRO N1_A3():STRING
    return m_N1_A3;
  END;
  PRIVATE MACRO N1_A4():DATE
    return m_N1_A4;
  END;
  PRIVATE MACRO N1_A5():STRING
    return m_DataSetQueryFinnaly.NominalFin_CCY;
  END;  
  PRIVATE MACRO N1_A6():MONEY    // Номинал векселя в валюте номинала
    return m_N1_A6;
  END; 
  PRIVATE MACRO N1_A7():STRING   // Признак эффективности платежа (оговорка эффективного платежа - ОЭП)
    if(m_DataSetQueryFinnaly.leg_PFI != NATCUR)
      if ( m_DataSetQueryFinnaly.PayFIID == ALLFININSTR )
        return "Нет";      
      else
        return "Да";
      end;
    end;
  END;
  PRIVATE MACRO N1_A8():DATE     // Дата погашения векселя в соот-ветствии с условиями выпуска векселя
    return m_N1_A8;
  END;
  PRIVATE MACRO N1_A9():STRING   // Плановый срок обращения век-селя, в днях
    return m_N1_A9;
  END;
  PRIVATE MACRO N1_A10():DOUBLE  // Процентная ставка по условиям выпуска процентного векселя / расчетная ставка для дисконтно-го векселя, % годовых
    return m_N1_A10;
  END;  
  PRIVATE MACRO N1_A11():STRING // Базис начисления процента (дисконта)
    return NameAlg(ALG_PC_BASIS, m_DataSetQueryFinnaly.leg_Basis)
  END;    
  PRIVATE MACRO N1_A12():DATE    // Дата размещения векселя (дата привлечения денежных средств)
    return m_DataSetQueryFinnaly.ISSUEpaym_ValueDate;
  END;  
  PRIVATE MACRO N1_A12_1():DATE  // Дата начала начисления процентов       
    if (m_isВексельПроцентный)
      return m_DataSetQueryFinnaly.leg_InterestStart;
    else
      return NULL;
    end;
  END;
  PRIVATE MACRO N1_A13():DOUBLE  // Цена размещения векселя, в валюте номинала
    return m_N1_A13;
  END;  
  PRIVATE MACRO N1_A14():DOUBLE  // Дисконт в соответствии с усло-виями размещения дисконтного векселя, в валюте номинала
    return m_N1_A14;
  END;  
  PRIVATE MACRO N1_A15():DOUBLE  // Курс валюты номинала, уста-новленный Банком России на дату размещения векселя, в рублях
    var _stat;
    var Rate = $0;
    var scale:integer;scale = 0;
    var point:integer;point = 0;    
    if (  m_DataSetQueryFinnaly.leg_PFI != NATCUR )

     _stat = FI_GetRateOnDate( NATCUR,                        // Котируемый ФИ
                               m_DataSetQueryFinnaly.leg_PFI, // Базовый ФИ
                               N1_A12,                        // дата курса
                               7,                             // Вид курса ЦБ РФ
                               @Rate,                         // Курс
                               @scale,                        // масштаб
                               @point                         // округление
                             );
      return Rate / _POWER(10,point);
    else
      return 1;    
    end;
  END;
  PRIVATE MACRO N1_A16():DOUBLE  // Номинал векселя на дату раз-мещения, в рублях
    return N1_A6 * N1_A15;
  END;
  PRIVATE MACRO N1_A17():DOUBLE  // Цена размещения векселя, в рублях
    return N1_A13 * N1_A15;
  END;
  PRIVATE MACRO N1_A18():DOUBLE  // Дисконт в соответствии с усло-виями размещения дисконтного векселя, в рублях
    if ( m_isВексельПроцентный )
      return 0.0;
    else
      return N1_A14*N1_A15;
    end;
  END;
  PRIVATE MACRO N1_A19()         // Дата фактического погашения (выкупа) векселя
    return IIF ( m_RegistryPeriodArray[i].PeriodType == PeriodTypeClose, m_RegistryPeriodArray[i].PeriodDateEnd , " " );
  END;  
  PRIVATE MACRO N1_A20()         // Цена погашения (выкупа) векселя, в валюте номинала
    return IIF ( m_RegistryPeriodArray[i].PeriodType == PeriodTypeClose, m_DataSetQueryFinnaly.REPvsordlnk_BCCost , " " );
  END;  
  PRIVATE MACRO N1_A21()         // Цена погашения (выкупа) вексе-ля, в рублях
    
    if ( N1_A20 == " ")
      return " ";
    else
      if ( m_DataSetQueryFinnaly.REPvsordlnk_BCCFI == NATCUR )
        return m_DataSetQueryFinnaly.REPvsordlnk_BCCost;
      else
        var Rate = $0;
        var scale:integer;scale = 0;
        var point:integer;point = 0;
        
        var КастыльФИ_ID:integer; КастыльФИ_ID = 0;
        КастыльФИ_ID = m_DataSetQueryFinnaly.REPvsordlnk_BCCFI;//простите чтец кода, но, как выяснилось на практике, в rsl иногда приходится вот так.

        FI_GetRateOnDate( NATCUR,                                 // Котируемый ФИ
                          КастыльФИ_ID,                           // Базовый ФИ
                          m_RegistryPeriodArray[i].PeriodDateEnd, // дата курса
                          7,                                      // Вид курса ЦБ РФ
                          @Rate,                                  // Курс
                          @scale,                                 // масштаб
                          @point                                  // округление
                        );
        return Rate / _POWER(10,point) * m_DataSetQueryFinnaly.REPvsordlnk_BCCost;
      end;
    end;
    
  END;    
  PRIVATE MACRO N1_A22()         // Количество дней, за которые начислены проценты (дисконт) по состоянию на конец текущего отчетного (налогового) периода / дату погашения (выкупа) 
    var result = 0;
    if ( (m_FinalStatus == VS_STATUS_REPAYED) AND ( m_DataSetQueryFinnaly.BCTermFormula == VS_TERMF_ATSIGHT) ) 
      if ( (SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry ) >= SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Start )) AND
           (SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry ) < m_RegistryPeriodArray[i].PeriodDateEnd) ) // По предъявлении, но не позднее
        result = SQL_ConvTypeDate( m_DataSetQueryFinnaly.leg_Expiry ) - IIF ( m_isВексельПроцентный, N1_A12_1, N1_A12 );
      else
        result = m_RegistryPeriodArray[i].PeriodDateEnd - IIF ( m_isВексельПроцентный, N1_A12_1, N1_A12 );
      end;
    else
      result = m_RegistryPeriodArray[i].PeriodDateEnd - IIF ( m_isВексельПроцентный, N1_A12_1, N1_A12 );
    end;

    return IIF(result > int(N1_A9), N1_A9, result);
  END;
  PRIVATE MACRO N1_A23()         // Сумма расходов, учитываемая при налогообложении прибыли - по состоянию на конец текущего отчетного (налогового) периода / дату погашения (выкупа) вексе-ля, всего, в валюте номинала
    
    var Sum = 0.0;//да, у заказчика этого отчёта не бывает процентно-дисконтных векселей. Но вдруг будут - на будущее
    var SumPrcnt = 0.0;
    var SumDscnt = 0.0;

    var VDate = m_RegistryPeriodArray[i].PeriodDateEnd ;

    if (N1_A19 == " ")
      if (m_isВексельПроцентный)
        SumPrcnt = SumPrcnt + ПолучитьСуммуПроцетовНаДату( VDate, m_DataSetQueryFinnaly.BCID, m_leg );      
      end;
      
      if (m_isВексельДисконтный)
        SumDscnt = SumDscnt + ПолучитьСуммуДисконтаНаДату( VDate, m_bnr, m_leg );      
      end;
      Sum = SumPrcnt + SumDscnt;
    else
      if (N1_A20 > N1_A13)
        Sum = N1_A20 - N1_A13;
      end;
    end;

    return round(Sum, 2);
  END;
  PRIVATE MACRO N1_A24()         // Курс валюты номинала, уста-новленный Банком России на конец текущего отчетного (нало-гового) периода / дату погашения (выкупа) векселя, в рублях
    var _stat;
    var Rate = $0;
    var scale:integer;scale = 0;
    var point:integer;point = 0;    
    if (  m_DataSetQueryFinnaly.leg_PFI != NATCUR )

     _stat = FI_GetRateOnDate( NATCUR,                                 // Котируемый ФИ
                               m_DataSetQueryFinnaly.leg_PFI,          // Базовый ФИ
                               m_RegistryPeriodArray[i].PeriodDateEnd, // дата курса
                               7,                                      // Вид курса ЦБ РФ
                               @Rate,                                  // Курс
                               @scale,                                 // масштаб
                               @point                                  // округление
                             );
      return Rate / _POWER(10,point);
    else
      return 1;    
    end;
  END;  
  PRIVATE MACRO N1_A25()         // Сумма расходов, учитываемая при налогообложении прибыли, - по состоянию на конец текущего отчетного (налогового) периода / дату погашения (выкупа) вексе-ля, всего, в рублях (наращен-ные)
     return N1_A23 * N1_A24;
  END;    
  PRIVATE MACRO N1_A26()         // Сумма расходов в виде процен-тов, учтенная при налогообло-жении прибыли в предыдущих налоговых периодах, в рублях (предыдущие)
    var S;
    var Sum = 0;//да, у заказчика этого отчёне не бывает процентно-дисконтных векселей. Но вдруг будут - на будущее
    if (N1_A12 < m_BeginDate)
      var VDate = m_BeginDate - 1;
      if (m_isВексельПроцентный)
        Sum = Sum + ПолучитьСуммуПроцетовНаДату( VDate, m_DataSetQueryFinnaly.BCID, m_leg );      
      end;
      
      if (m_isВексельДисконтный)
        Sum = Sum + ПолучитьСуммуДисконтаНаДату( VDate, m_bnr, m_leg );      
      end;
    end;

    if (  m_DataSetQueryFinnaly.leg_PFI != NATCUR )
      var _stat;
      var Rate = $0;
      var scale:integer;scale = 0;
      var point:integer;point = 0;  
      _stat = FI_GetRateOnDate( NATCUR,                        // Котируемый ФИ
                                m_DataSetQueryFinnaly.leg_PFI, // Базовый ФИ
                                m_BeginDate - 1,               // дата курса
                                7,                             // Вид курса ЦБ РФ
                                @Rate,                         // Курс
                                @scale,                        // масштаб
                                @point                         // округление
                               );
      S = Rate / _POWER(10,point);
    else
      S = 1;
    end;
    
    return Sum * S;
  END;  
  PRIVATE MACRO N1_A27()         // Сумма расходов, учитываемая при налогообложении прибыли в текущем отчетном (налоговом) периоде, в рублях
     return N1_A25 - N1_A26;
  END;  
  PRIVATE MACRO N1_A28()         // Сумма доходов, учитываемая при налогообложении прибыли в текущем отчетном (налоговом) периоде, в рублях    
     if(N1_A20 != " ")
      if ( N1_A13 > N1_A20 )
        return ABS((N1_A13 - N1_A20) * N1_A24);
      end;
      return 0;
     end;
     return " ";
  END;  
  PRIVATE MACRO N1_A29()         // Курсовая разница по векселям, не погашенным (не выкуплен-ным) Банком по состоянию на конец предыдущего налогового периода, в рублях
    var S;
    var Sum = 0.0;

    var StatusOnPrevPeriod = 0;

    var Query = " select rsb_bill.GetVSBnrStatusOnDate( ?,? ) StatusOnPrevPeriod from dual ";
    var cmd = RSDCommand(Query);

    cmd.addParam( "", RSDBP_IN, m_DataSetQueryFinnaly.BCID );
    cmd.addParam( "", RSDBP_IN, m_BeginDate - 1 );

    var cmdData = TRsbDataSet(cmd);
    if( cmdData.MoveNext() )
      StatusOnPrevPeriod = cmdData.StatusOnPrevPeriod
    end;

    if( StatusOnPrevPeriod == VS_STATUS_ISSUED )

      if (  m_DataSetQueryFinnaly.leg_PFI != NATCUR )
        var _stat;
        var Rate = $0;
        var scale:integer;scale = 0;
        var point:integer;point = 0;  
        _stat = FI_GetRateOnDate( NATCUR,                        // Котируемый ФИ
                                  m_DataSetQueryFinnaly.leg_PFI, // Базовый ФИ
                                  m_BeginDate - 1,               // дата курса
                                  7,                             // Вид курса ЦБ РФ
                                  @Rate,                         // Курс
                                  @scale,                        // масштаб
                                  @point                         // округление
                                );
        S = Rate / _POWER(10,point);
      else
        S = 1;    
      end;
      Sum = IIF(m_isВексельПроцентный, N1_A6 * (S - N1_A15), N1_A13 * (S - N1_A15));
    end;

    return Sum;
  END;
  PRIVATE MACRO N1_A30()         // Курсовая разница по векселям, погашенным (выкупленным) Банком в текущем отчетном (налоговом) периоде, в рублях  
    if( m_RegistryPeriodArray[i].PeriodType == PeriodTypeClose )
      return IIF(m_isВексельПроцентный, N1_A6 * (N1_A24 - N1_A15),  N1_A13 * (N1_A24 - N1_A15))
    end;
    return " ";
  END;
  PRIVATE MACRO N1_A31()         // Курсовая разница по векселям, не погашенным (не выкуплен-ным) Банком по состоянию на конец текущего отчетного (нало-гового) периода, в рублях
    if( (m_RegistryPeriodArray[i].PeriodType == PeriodTypeOpen) AND (m_DataSetQueryFinnaly.leg_PFI != NATCUR) AND (N1_A7 == "Да") )
      return IIF ( m_isВексельПроцентный, N1_A6 * (N1_A24 - N1_A15), N1_A13 * (N1_A24 - N1_A15));
    end;
    return " ";
  END;
  PRIVATE MACRO N1_A32():STRING  // Контрагент, который приобрел вексель
    return m_DataSetQueryFinnaly.Client_ShortName_Buyer;
  END;
  PRIVATE MACRO N1_A33():STRING  // Страна регистрации контрагента, который приобрел вексель
    return m_DataSetQueryFinnaly.Country_FullName_Buyer;
  END;  
  PRIVATE MACRO N1_A34():STRING  // ИНН контрагента, который при-обрел вексель
    var innKpp = StrSubst(ПолучитьКодСубъекта(m_DataSetQueryFinnaly.ClientID_Buyer, PTCK_INN ),"\\","/");
    var inn="";
    if (SplitFullINN (innKpp, inn, NULL) == 0)
      return inn;
    else
      return innKpp;
    end;
  END;  
  PRIVATE MACRO N1_A35():STRING  // Контрагент, который предъявил вексель к платежу
    if (m_DataSetQueryFinnaly.ClientID_Seller != -1 )
      return m_DataSetQueryFinnaly.Client_ShortName_Seller;
    else
      return " ";
    end;    
  END;    
  PRIVATE MACRO N1_A36():STRING  // Страна регистрации контрагента, который предъявил вексель к платежу	Наименование страны регистрации последнего векселедержателя, из карточки клиента. 
    if (m_DataSetQueryFinnaly.ClientID_Seller != -1 )
      return m_DataSetQueryFinnaly.Country_FullName_Seller;
    else
      return " ";
    end;    
  END;  
  PRIVATE MACRO N1_A37():STRING  // ИНН контрагента, который предъявил вексель к платежу
    var seller = SQL_ConvTypeInteger(m_DataSetQueryFinnaly.ClientID_Seller);
    if (seller != -1 )
      var innKpp = StrSubst(ПолучитьКодСубъекта(seller, PTCK_INN ),"\\","/");
      var inn="";
      if (SplitFullINN (innKpp, inn, NULL) == 0)
        return inn;
      else
        return innKpp;
      end;
    else
      return " ";
    end;
  END;
  PRIVATE MACRO N1_A38():STRING  // Поля A38,39,41,42 заполняются на текущий момент вручную 
    return " ";
  END;
  PRIVATE MACRO N1_A39():STRING
    return " ";
  END;
  PRIVATE MACRO N1_A40()         // Превышение фактической сум-мы расходов в виде процентов над суммой расходов, рассчи-танной исходя из предельной ставки
    var Sum = 0.0;//да, у заказчика этого отчёта не бывает процентно-дисконтных векселей. Но вдруг будут - на будущее
    var SumPrcnt = 0.0;
    var SumDscnt = 0.0;
    var SumLimit = 0.0;
    var retval   = 0.0;
    var VDate = m_EndDate;

    if(m_N1_A45 < N1_A10)
      if (m_isВексельПроцентный)
        SumPrcnt = SumPrcnt + ПолучитьСуммуПроцетовНаДату( VDate, m_DataSetQueryFinnaly.BCID, m_leg );      
      end;
      
      if (m_isВексельДисконтный)
        SumDscnt = SumDscnt + ПолучитьСуммуДисконтаНаДату( VDate, m_bnr, m_leg );      
      end;
      Sum = SumPrcnt + SumDscnt;
      if ( m_N1_A10 != 0)
        SumLimit = Sum * m_N1_A45 / m_N1_A10;
      end;
      
      if ( ( Sum != 0 ) and ( SumLimit !=0 ) )    
        retval = (Sum - SumLimit) / Sum * 100;//%     
      end;
    end;
    
    return retval;    
  END;
  PRIVATE MACRO N1_A41():STRING
    return " ";
  END;
  PRIVATE MACRO N1_A42():STRING
    return " ";
  END;
  PRIVATE MACRO N1_A43():STRING
    return "Ставка рефинансирования ЦБ";
  END;  
  PRIVATE MACRO N1_A44()         // Размер ставки, % годовых
    return m_N1_A44;
  END;
  PRIVATE MACRO N1_A45()         // Предельное значение ставки, % годовых
    return m_N1_A45; 
  END;
  PRIVATE MACRO N1_A46():STRING
    var Счет;
    ПолучитьСчетВекселя("Наш вексель", m_fd, Счет, VS_FNDACC);
    return Счет;
  END;
  PRIVATE MACRO N1_A47():STRING
    if (StrBrk(m_FinalState,"И"))
      var Счет;
      ПолучитьСчетВекселя("СВексель к исполнению", m_fd, Счет, VS_FNDACC);
      return Счет;
    else
      return " ";
    end;
  END;
  PRIVATE MACRO N1_A48():STRING
    if (m_isВексельПроцентный and ( m_FinalStatus == VS_STATUS_ISSUED ) or ( m_FinalStatus == VS_STATUS_REBUYED ) )
      var Счет;
      ПолучитьСчетВекселя("Обяз%,СВексель", m_fd, Счет, VS_FNDACC);
      return Счет;
    else
      return " ";
    end;
  END;
  PRIVATE MACRO N1_A49():STRING
    if (m_isВексельДисконтный and ( m_FinalStatus == VS_STATUS_ISSUED ) or ( m_FinalStatus == VS_STATUS_REBUYED ) )
      var Счет;
      ПолучитьСчетВекселя("Дисконт, Свексель", m_fd, Счет, VS_FNDACC);
      return Счет;
    else
      return " ";
    end;
  END;

  PRIVATE MACRO N1_A25_TOTAL()
    return m_N1_A25_TOTAL;
  END;
  PRIVATE MACRO N1_A26_TOTAL()
    return m_N1_A26_TOTAL;
  END;
  PRIVATE MACRO N1_A27_TOTAL()
    return m_N1_A27_TOTAL;
  END;
  PRIVATE MACRO N1_A28_TOTAL()
    return m_N1_A28_TOTAL;
  END;
  PRIVATE MACRO N1_A29_TOTAL()
    return m_N1_A29_TOTAL;
  END;
  PRIVATE MACRO N1_A30_TOTAL()
    return m_N1_A30_TOTAL;
  END;
  PRIVATE MACRO N1_A31_TOTAL()
    return m_N1_A31_TOTAL;
  END;
  PRIVATE MACRO N1_A40_TOTAL()
    return m_N1_A40_TOTAL;
  END;

  PRIVATE MACRO N1_A6_TOTAL()
    return m_N1_A6_TOTAL;
  END;
  PRIVATE MACRO N1_A13_TOTAL()
    return m_N1_A13_TOTAL;
  END;
  PRIVATE MACRO N1_A14_TOTAL()
    return m_N1_A14_TOTAL;
  END;
  PRIVATE MACRO N1_A16_TOTAL()
    return m_N1_A16_TOTAL;
  END;
  PRIVATE MACRO N1_A17_TOTAL()
    return m_N1_A17_TOTAL;
  END;
  PRIVATE MACRO N1_A18_TOTAL()
    return m_N1_A18_TOTAL;
  END;
  PRIVATE MACRO N1_A23_TOTAL()
    return m_N1_A23_TOTAL;
  END;
  PRIVATE MACRO N1_A20_TOTAL()
    return m_N1_A20_TOTAL;
  END;
  PRIVATE MACRO N1_A21_TOTAL()
    return m_N1_A21_TOTAL;
  END;

  PRIVATE MACRO F_NU1():string
    var strNum = string(1+NumStr_N1);  
    return SetIFFormula(C_A30+strNum, "-"+C_A30+strNum, "0", " < 0", null);
  END;

  PRIVATE MACRO F_NU2():string
    var strNum = string(1+NumStr_N1);  
    return SetIFFormula(C_A30+strNum, C_A30+strNum, "0", " > 0", null);
  END;

  PRIVATE MACRO F_K1():string
      var strNum = string(1+NumStr_N1);
     return "="+C_A30+strNum+"-("+C_NU_2+strNum+"-"+C_NU_1+strNum+")";
  END;

  PRIVATE MACRO ДобавитьДанныеДляОбщейСтроки()
    m_N1_A25_TOTAL = m_N1_A25_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A25) != "", round(m_Data[m_DataSize - 1].get_A(A25), 2), 0);
    m_N1_A26_TOTAL = m_N1_A26_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A26) != "", round(m_Data[m_DataSize - 1].get_A(A26), 2), 0);
    m_N1_A27_TOTAL = m_N1_A27_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A27) != "", round(m_Data[m_DataSize - 1].get_A(A27), 2), 0);
    m_N1_A28_TOTAL = m_N1_A28_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A28) != "", round(m_Data[m_DataSize - 1].get_A(A28), 2), 0);
    m_N1_A29_TOTAL = m_N1_A29_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A29) != "", round(m_Data[m_DataSize - 1].get_A(A29), 2), 0);
    m_N1_A30_TOTAL = m_N1_A30_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A30) != "", round(m_Data[m_DataSize - 1].get_A(A30), 2), 0);
    m_N1_A31_TOTAL = m_N1_A31_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A31) != "", round(m_Data[m_DataSize - 1].get_A(A31), 2), 0);
    m_N1_A40_TOTAL = m_N1_A40_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A40) != "", round(m_Data[m_DataSize - 1].get_A(A40), 2), 0);

    //Добавлено в рамках 273684 
    m_N1_A6_TOTAL = m_N1_A6_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A06) != "", round(m_Data[m_DataSize - 1].get_A (A06), 2), 0);
    m_N1_A13_TOTAL = m_N1_A13_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A13) != "", round(m_Data[m_DataSize - 1].get_A(A13), 2), 0);
    m_N1_A14_TOTAL = m_N1_A14_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A14) != "", round(m_Data[m_DataSize - 1].get_A(A14), 2), 0);
    m_N1_A16_TOTAL = m_N1_A16_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A16) != "", round(m_Data[m_DataSize - 1].get_A(A16), 2), 0);
    m_N1_A17_TOTAL = m_N1_A17_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A17) != "", round(m_Data[m_DataSize - 1].get_A(A17), 2), 0);
    m_N1_A18_TOTAL = m_N1_A18_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A18) != "", round(m_Data[m_DataSize - 1].get_A(A18), 2), 0);
    m_N1_A23_TOTAL = m_N1_A23_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A23) != "", round(m_Data[m_DataSize - 1].get_A(A23), 2), 0);

    m_N1_A20_TOTAL = m_N1_A20_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A20) != "", round(m_Data[m_DataSize - 1].get_A(A20), 2), 0);
    m_N1_A21_TOTAL = m_N1_A21_TOTAL + IIF(m_Data[m_DataSize - 1].get_A(A21) != "", round(m_Data[m_DataSize - 1].get_A(A21), 2), 0);

  END;
  
  PRIVATE MACRO PrintReportHead()
    PrintFormatString(  null,         
                        "N1_H0_A", N1_H0_A,
                        "N1_FilialText", N1_FilialText,
                        "N1_H1"  , N1_H1,
                        "N1_H0_В", N1_H0_В,
                        "N1_H0_C", N1_H0_C,
                        "N1_H0_1"  , N1_H0_1,
                        "N1_H0_2"  , N1_H0_2,
                        "N1_Text1" , N1_Text1,
                        "N1_H0_3"  , N1_H0_3,
                        "N1_H0_4"  , N1_H0_4
                     );                                    
  END;

  PRIVATE MACRO PrintRepHeader_rshb_common( Header, Prefix )

    PrintFormatString( Header,
                      Prefix + "Операционист",  Oper_rshb(),
                      Prefix + "Year",          GetYear(),
                      Prefix + "PeriodCode",    GetPeriodCode(),
                      Prefix + "PeriodTxt",     GetPeriodTxt()
                    );

  end;

  PRIVATE MACRO PrintLineNoData()
     PrintTableLine( "N1_A1", NoDataTxt, null);
  END;



  PRIVATE MACRO RegTable()
       RegisterTable("N1_MainTable", "N1_RepHeader",
                     "N1_Dummy1" ,
                     "N1_A1"     ,
                     "N1_A2"     ,
                     "N1_A3"     ,
                     "N1_A4"     ,
                     "N1_A5"     ,
                     "N1_A6"     ,
                     "N1_A7"     ,
                     "N1_A8"     ,
                     "N1_A9"     ,
                     "N1_A10"    ,
                     "N1_A11"    ,
                     "N1_A12"    ,
                     "N1_A12_1"  ,
                     "N1_A13"    ,
                     "N1_A14"    ,
                     "N1_A15"    ,
                     "N1_A16"    ,
                     "N1_A17"    ,
                     "N1_A18"    ,
                     "N1_A19"    ,
                     "N1_A20"    ,
                     "N1_A21"    ,
                     "N1_A22"    ,                     
                     "N1_A23"    ,
                     "N1_A24"    ,
                     "N1_A25"    ,
                     "N1_A26"    ,
                     "N1_A27"    ,
                     "N1_A28"    ,
                     "N1_A29"    ,
                     "N1_A30"    ,
                     "N1_A31"    ,
                     "N1_A32"    ,                     
                     "N1_A33"    ,
                     "N1_A34"    ,
                     "N1_A35"    ,
                     "N1_A36"    ,
                     "N1_A37"    ,
                     "N1_A38"    ,
                     "N1_A39"    ,
                     "N1_A40"    ,
                     "N1_A41"    ,
                     "N1_A42"    ,                     
                     "N1_A43"    ,
                     "N1_A44"    ,
                     "N1_A45"    ,
                     "N1_A46"    ,
                     "N1_A47"    ,
                     "N1_A48"    ,
                     "N1_A49"    ,
                     "N1_NU_1"   ,
                     "N1_NU_2"   ,
                     "N1_K_1"               
                   );

    SetCellAutoSumma("Itog", "N1_A6","N1_A13","N1_A14","N1_A16","N1_A17","N1_A18","N1_A20","N1_A21","N1_A23","N1_A25","N1_A26","N1_A27","N1_A28","N1_A29","N1_A30",
                             "N1_A31","N1_A40","N1_NU_1","N1_NU_2","N1_K_1");
    SetCopyAutoSumRange("A7:BB7");
    NumStr_N1 = 0;
  END;
   
  PRIVATE MACRO BeginReport( NumCopy:INTEGER )
    InitVariables();    
    SetSqlDataQuery();
    SetSqlDataSet();    
  END;

  PRIVATE MACRO ПечататьСтрокуТаблицы( LineType, j )
  
    if ( LineType == LineTypeData )

      PrintTableLine( "N1_A1"     , m_Data[j].get_A(A01),   null,
                      "N1_A2"     , m_Data[j].get_A(A02),   null,
                      "N1_A3"     , m_Data[j].get_A(A03),   null,
                      "N1_A4"     , m_Data[j].get_A(A04),   null,
                      "N1_A5"     , m_Data[j].get_A(A05),   null,
                      "N1_A6"     , m_Data[j].get_A(A06),   null,
                      "N1_A7"     , m_Data[j].get_A(A07),   null,
                      "N1_A8"     , m_Data[j].get_A(A08),   null,
                      "N1_A9"     , m_Data[j].get_A(A09),   null,
                      "N1_A10"    , m_Data[j].get_A(A10),   null,
                      "N1_A11"    , m_Data[j].get_A(A11),   null,
                      "N1_A12"    , m_Data[j].get_A(A12),   null,
                      "N1_A12_1"  , m_Data[j].get_A(A12_1),  null,
                      "N1_A13"    , m_Data[j].get_A(A13),   null,
                      "N1_A14"    , m_Data[j].get_A(A14),   null,
                      "N1_A15"    , m_Data[j].get_A(A15),   null,
                      "N1_A16"    , m_Data[j].get_A(A16),   null,
                      "N1_A17"    , m_Data[j].get_A(A17),   null,
                      "N1_A18"    , m_Data[j].get_A(A18),   null,
                      "N1_A19"    , m_Data[j].get_A(A19),   null,
                      "N1_A20"    , m_Data[j].get_A(A20),   null,
                      "N1_A21"    , m_Data[j].get_A(A21),   null,
                      "N1_A22"    , m_Data[j].get_A(A22),   null,                    
                      "N1_A23"    , m_Data[j].get_A(A23),   null,
                      "N1_A24"    , m_Data[j].get_A(A24),   null,
                      "N1_A25"    , m_Data[j].get_A(A25),   null,
                      "N1_A26"    , m_Data[j].get_A(A26),   null,
                      "N1_A27"    , m_Data[j].get_A(A27),   null,
                      "N1_A28"    , m_Data[j].get_A(A28),   null,
                      "N1_A29"    , m_Data[j].get_A(A29),   null,
                      "N1_A30"    , m_Data[j].get_A(A30),   null,
                      "N1_A31"    , m_Data[j].get_A(A31),   null,
                      "N1_A32"    , m_Data[j].get_A(A32),   null,                    
                      "N1_A33"    , m_Data[j].get_A(A33),   null,
                      "N1_A34"    , m_Data[j].get_A(A34),   null,
                      "N1_A35"    , m_Data[j].get_A(A35),   null,
                      "N1_A36"    , m_Data[j].get_A(A36),   null,
                      "N1_A37"    , m_Data[j].get_A(A37),   null,
                      "N1_A38"    , m_Data[j].get_A(A38),   null,
                      "N1_A39"    , m_Data[j].get_A(A39),   null,
                      "N1_A40"    , m_Data[j].get_A(A40),   null,
                      "N1_A41"    , m_Data[j].get_A(A41),   null,
                      "N1_A42"    , m_Data[j].get_A(A42),   null,                    
                      "N1_A43"    , m_Data[j].get_A(A43),   null,
                      "N1_A44"    , m_Data[j].get_A(A44),   null,
                      "N1_A45"    , m_Data[j].get_A(A45),   null,
                      "N1_A46"    , m_Data[j].get_A(A46),   null,
                      "N1_A47"    , m_Data[j].get_A(A47),   null,
                      "N1_A48"    , m_Data[j].get_A(A48),   null,
                      "N1_A49"    , m_Data[j].get_A(A49),   null,

                      "N1_NU_1"   , IIF((m_Data[j].get_A(A30) == " "), " ", F_NU1()), null,  
                      "N1_NU_2"   , IIF((m_Data[j].get_A(A30) == " "), " ", F_NU2()), null,  
                      "N1_K_1"    , IIF((m_Data[j].get_A(A30) == " "), " ", F_K1()),  null  
                    );                  
      ExternalSetCellPoint("N1_A16", 2);                    
      NumStr_N1 = NumStr_N1 + 1;                    
    end;
    
    if ( LineType == LineTypeTotal )
             PrintTableLine( "N1_A1"     , "ВСЕГО",        null,
                             "N1_A2"     , "",             null,
                             "N1_A3"     , "",             null,
                             "N1_A4"     , "",             null,
                             "N1_A5"     , "",             null,
                             "N1_A6"     , N1_A6_TOTAL,    null,
                             "N1_A7"     , "",             null,
                             "N1_A8"     , "",             null,
                             "N1_A9"     , "",             null,
                             "N1_A10"    , "",             null,
                             "N1_A11"    , "",             null,
                             "N1_A12"    , "",             null,
                             "N1_A12_1"  , "",             null,
                             "N1_A13"    , N1_A13_TOTAL,   null,
                             "N1_A14"    , N1_A14_TOTAL,   null,
                             "N1_A15"    , "",             null,
                             "N1_A16"    , N1_A16_TOTAL,   null,
                             "N1_A17"    , N1_A17_TOTAL,   null,
                             "N1_A18"    , N1_A18_TOTAL,   null,
                             "N1_A19"    , "",             null,
                             "N1_A20"    , N1_A20_TOTAL,   null,
                             "N1_A21"    , N1_A21_TOTAL,   null,
                             "N1_A22"    , "",             null,
                             "N1_A23"    , N1_A23_TOTAL,   null,
                             "N1_A24"    , "",             null,
                             "N1_A25"    , N1_A25_TOTAL,   null,
                             "N1_A26"    , N1_A26_TOTAL,   null,
                             "N1_A27"    , N1_A27_TOTAL,   null,
                             "N1_A28"    , N1_A28_TOTAL,   null,
                             "N1_A29"    , N1_A29_TOTAL,   null,
                             "N1_A30"    , N1_A30_TOTAL,   null,
                             "N1_A31"    , N1_A31_TOTAL,   null,
                             "N1_A32"    , "",             null,
                             "N1_A33"    , "",             null,
                             "N1_A34"    , "",             null,
                             "N1_A35"    , "",             null,
                             "N1_A36"    , "",             null,
                             "N1_A37"    , "",             null,
                             "N1_A38"    , "",             null,
                             "N1_A39"    , "",             null,
                             "N1_A40"    , N1_A40_TOTAL,   null,
                             "N1_A41"    , "",             null,
                             "N1_A42"    , "",             null,
                             "N1_A43"    , "",             null,
                             "N1_A44"    , "",             null,
                             "N1_A45"    , "",             null,
                             "N1_A46"    , "",             null,
                             "N1_A47"    , "",             null,
                             "N1_A48"    , "",             null,
                             "N1_A49"    , "",             null 
                        );    
    end;
    
    if ( LineType == LineType3 )
      PrintTableLine( "N1_A1"     , "в том числе:",   null);
    end;
  
  END;

  macro ДобавитьСтрокуДаных()
    m_Data[m_DataSize - 1].set_A(A01  ,   IIF(VALTYPE(N1_A1)      != V_UNDEF, N1_A1,         ""));
    m_Data[m_DataSize - 1].set_A(A02  ,   IIF(VALTYPE(N1_A2)      != V_UNDEF, N1_A2,         ""));
    m_Data[m_DataSize - 1].set_A(A03  ,   IIF(VALTYPE(N1_A3)      != V_UNDEF, N1_A3,         ""));
    m_Data[m_DataSize - 1].set_A(A04  ,   IIF(VALTYPE(N1_A4)      != V_UNDEF, N1_A4,         ""));
    m_Data[m_DataSize - 1].set_A(A05  ,   IIF(VALTYPE(N1_A5)      != V_UNDEF, N1_A5,         ""));
    m_Data[m_DataSize - 1].set_A(A06  ,   IIF(VALTYPE(N1_A6)      != V_UNDEF, N1_A6,         ""));
    m_Data[m_DataSize - 1].set_A(A07  ,   IIF(VALTYPE(N1_A7)      != V_UNDEF, N1_A7,         ""));
    m_Data[m_DataSize - 1].set_A(A08  ,   IIF(VALTYPE(N1_A8)      != V_UNDEF, N1_A8,         ""));
    m_Data[m_DataSize - 1].set_A(A09  ,   IIF(VALTYPE(N1_A9)      != V_UNDEF, N1_A9,         ""));
    m_Data[m_DataSize - 1].set_A(A10  ,   IIF(VALTYPE(N1_A10)     != V_UNDEF, N1_A10,        ""));
    m_Data[m_DataSize - 1].set_A(A11  ,   IIF(VALTYPE(N1_A11)     != V_UNDEF, N1_A11,        ""));
    m_Data[m_DataSize - 1].set_A(A12  ,   IIF(VALTYPE(N1_A12)     != V_UNDEF, N1_A12,        ""));
    m_Data[m_DataSize - 1].set_A(A12_1,   IIF(VALTYPE(N1_A12_1)   != V_UNDEF, N1_A12_1,      ""));
    m_Data[m_DataSize - 1].set_A(A13  ,   IIF(VALTYPE(N1_A13)     != V_UNDEF, N1_A13,         ""));
    m_Data[m_DataSize - 1].set_A(A14  ,   IIF(VALTYPE(N1_A14)     != V_UNDEF, N1_A14,         ""));
    m_Data[m_DataSize - 1].set_A(A15  ,   IIF(VALTYPE(N1_A15)     != V_UNDEF, N1_A15,         ""));
    m_Data[m_DataSize - 1].set_A(A16  ,   IIF(VALTYPE(N1_A16)     != V_UNDEF, N1_A16,         ""));
    m_Data[m_DataSize - 1].set_A(A17  ,   IIF(VALTYPE(N1_A17)     != V_UNDEF, N1_A17,         ""));
    m_Data[m_DataSize - 1].set_A(A18  ,   IIF(VALTYPE(N1_A18)     != V_UNDEF, N1_A18,         ""));
    m_Data[m_DataSize - 1].set_A(A19  ,   IIF(VALTYPE(N1_A19)     != V_UNDEF, N1_A19,         ""));
    m_Data[m_DataSize - 1].set_A(A20  ,   IIF(VALTYPE(N1_A20)     != V_UNDEF, N1_A20,         ""));
    m_Data[m_DataSize - 1].set_A(A21  ,   IIF(VALTYPE(N1_A21)     != V_UNDEF, N1_A21,         ""));
    m_Data[m_DataSize - 1].set_A(A22  ,   IIF(VALTYPE(N1_A22)     != V_UNDEF, N1_A22,         ""));
    m_Data[m_DataSize - 1].set_A(A23  ,   IIF(VALTYPE(N1_A23)     != V_UNDEF, N1_A23,         ""));
    m_Data[m_DataSize - 1].set_A(A24  ,   IIF(VALTYPE(N1_A24)     != V_UNDEF, N1_A24,         ""));
    m_Data[m_DataSize - 1].set_A(A25  ,   IIF(VALTYPE(N1_A25)     != V_UNDEF, N1_A25,         ""));
    m_Data[m_DataSize - 1].set_A(A26  ,   IIF(VALTYPE(N1_A26)     != V_UNDEF, N1_A26,         ""));
    m_Data[m_DataSize - 1].set_A(A27  ,   IIF(VALTYPE(N1_A27)     != V_UNDEF, N1_A27,         ""));
    m_Data[m_DataSize - 1].set_A(A28  ,   IIF(VALTYPE(N1_A28)     != V_UNDEF, N1_A28,         ""));
    m_Data[m_DataSize - 1].set_A(A29  ,   IIF(VALTYPE(N1_A29)     != V_UNDEF, N1_A29,         ""));
    m_Data[m_DataSize - 1].set_A(A30  ,   IIF(VALTYPE(N1_A30)     != V_UNDEF, N1_A30,         ""));
    m_Data[m_DataSize - 1].set_A(A31  ,   IIF(VALTYPE(N1_A31)     != V_UNDEF, N1_A31,         ""));
    m_Data[m_DataSize - 1].set_A(A32  ,   IIF(VALTYPE(N1_A32)     != V_UNDEF, N1_A32,         ""));
    m_Data[m_DataSize - 1].set_A(A33  ,   IIF(VALTYPE(N1_A33)     != V_UNDEF, N1_A33,         ""));
    m_Data[m_DataSize - 1].set_A(A34  ,   IIF(VALTYPE(N1_A34)     != V_UNDEF, N1_A34,         ""));
    m_Data[m_DataSize - 1].set_A(A35  ,   IIF(VALTYPE(N1_A35)     != V_UNDEF, N1_A35,         ""));
    m_Data[m_DataSize - 1].set_A(A36  ,   IIF(VALTYPE(N1_A36)     != V_UNDEF, N1_A36,         ""));
    m_Data[m_DataSize - 1].set_A(A37  ,   IIF(VALTYPE(N1_A37)     != V_UNDEF, N1_A37,         ""));
    m_Data[m_DataSize - 1].set_A(A38  ,   IIF(VALTYPE(N1_A38)     != V_UNDEF, N1_A38,         ""));
    m_Data[m_DataSize - 1].set_A(A39  ,   IIF(VALTYPE(N1_A39)     != V_UNDEF, N1_A39,         ""));
    m_Data[m_DataSize - 1].set_A(A40  ,   IIF(VALTYPE(N1_A40)     != V_UNDEF, N1_A40,         ""));
    m_Data[m_DataSize - 1].set_A(A41  ,   IIF(VALTYPE(N1_A41)     != V_UNDEF, N1_A41,         ""));
    m_Data[m_DataSize - 1].set_A(A42  ,   IIF(VALTYPE(N1_A42)     != V_UNDEF, N1_A42,         ""));
    m_Data[m_DataSize - 1].set_A(A43  ,   IIF(VALTYPE(N1_A43)     != V_UNDEF, N1_A43,         ""));
    m_Data[m_DataSize - 1].set_A(A44  ,   IIF(VALTYPE(N1_A44)     != V_UNDEF, N1_A44,         ""));
    m_Data[m_DataSize - 1].set_A(A45  ,   IIF(VALTYPE(N1_A45)     != V_UNDEF, N1_A45,         ""));
    m_Data[m_DataSize - 1].set_A(A46  ,   IIF(VALTYPE(N1_A46)     != V_UNDEF, N1_A46,         ""));
    m_Data[m_DataSize - 1].set_A(A47  ,   IIF(VALTYPE(N1_A47)     != V_UNDEF, N1_A47,         ""));
    m_Data[m_DataSize - 1].set_A(A48  ,   IIF(VALTYPE(N1_A48)     != V_UNDEF, N1_A48,         ""));
    m_Data[m_DataSize - 1].set_A(A49  ,   IIF(VALTYPE(N1_A49)     != V_UNDEF, N1_A49,         ""));
  end;
  
  PRIVATE MACRO ОбнулитьДанныеДляОбщейСтроки()
    m_N1_A25_TOTAL = 0;
    m_N1_A26_TOTAL = 0;
    m_N1_A27_TOTAL = 0;
    m_N1_A28_TOTAL = 0;
    m_N1_A29_TOTAL = 0;
    m_N1_A30_TOTAL = 0;
    m_N1_A31_TOTAL = 0;
    m_N1_A40_TOTAL = 0;
    //Добавлено в рамках 273684 
    m_N1_A6_TOTAL = 0;
    m_N1_A13_TOTAL = 0;
    m_N1_A14_TOTAL = 0;
    m_N1_A16_TOTAL = 0;
    m_N1_A17_TOTAL = 0;
    m_N1_A18_TOTAL = 0;
    m_N1_A23_TOTAL = 0;

    m_N1_A20_TOTAL = 0;
    m_N1_A21_TOTAL = 0;
  END;

  PRIVATE MACRO ВывестиСтроки()
    if(m_DataSize > 0)
      var j = 0;

      while(j < m_DataSize)
        ПечататьСтрокуТаблицы ( LineTypeData, j );
        m_Data[j].ClearData();
        j = j + 1;
      end;
      m_Data.size = 0;
      m_DataSize = 0;
      ОбнулитьДанныеДляОбщейСтроки();
    end;
  END;

  PRIVATE MACRO CReport_NoDataMsg()
    if (not m_IsWebService)
      msgbox("Нет данных для формирования отчета");
    end;
  END;

  macro SetAutoSize() //Автоматическая ширина для столбцов
     m_ObjTemplateXLS.SetAutoFit("C:BB", m_ObjTemplateXLS.SheetName());             
  end;

  MACRO SetOnAutoFilter(range)
    if( ExistsSheet( m_ObjTemplateXLS.SheetName() ) )
       m_ObjTemplateXLS.SetAutoFilter(range, m_ObjTemplateXLS.SheetName());
    end;
  END;

  MACRO PrintHeader_rshb_supl(rangeSize)

     PrintFormatString( null,
                       GetItogCell(C_A6),      FSum_Col(null, C_A6, rangeSize),
                       GetItogCell(C_A13),     FSum_Col(null, C_A13, rangeSize),
                       GetItogCell(C_A14),     FSum_Col(null, C_A14, rangeSize),
                       GetItogCell(C_A16),     FSum_Col(null, C_A16, rangeSize),
                       GetItogCell(C_A17),     FSum_Col(null, C_A17, rangeSize),
                       GetItogCell(C_A18),     FSum_Col(null, C_A18, rangeSize),
                       GetItogCell(C_A20),     FSum_Col(null, C_A20, rangeSize),
                       GetItogCell(C_A21),     FSum_Col(null, C_A21, rangeSize),
                       GetItogCell(C_A23),     FSum_Col(null, C_A23, rangeSize),
                       GetItogCell(C_A25),     FSum_Col(null, C_A25, rangeSize),
                       GetItogCell(C_A26),     FSum_Col(null, C_A26, rangeSize),
                       GetItogCell(C_A27),     FSum_Col(null, C_A27, rangeSize),
                       GetItogCell(C_A28),     FSum_Col(null, C_A28, rangeSize),
                       GetItogCell(C_A29),     FSum_Col(null, C_A29, rangeSize),
                       GetItogCell(C_A30),     FSum_Col(null, C_A30, rangeSize),
                       GetItogCell(C_A31),     FSum_Col(null, C_A31, rangeSize),
                       GetItogCell(C_A40),     FSum_Col(null, C_A40, rangeSize),
                       GetItogCell(C_NU_1),    FSum_Col(null, C_NU_1, rangeSize),
                       GetItogCell(C_NU_2),    FSum_Col(null, C_NU_2, rangeSize),
                       GetItogCell(C_K_1),     FSum_Col(null, C_K_1, rangeSize)
                     );

  END;

  PRIVATE MACRO Create( NumCopy:INTEGER )
    VAR ProgressIndicator, header;
    VAR ProgressValue = CTxProgressValue();
    VAR progr = 0;

    this.SetActiveSheet( "АР-07-18" );  // "Отчет"

    PrintRepHeader_rshb_common(null, "H1_");    
    RegTable();      

    /* для каждого векселя */
    if ( DataExist() )
      ProgressValue.Maximum = m_NRecsBNRS;
      ProgressValue.Current = 0;
 
      if( m_IsWebService )
        header = "Формирование отчета " + WebMenuItem.szNameItem;
      else
        InitProgress( m_NRecsBNRS, "Идет формирование отчета", "Регистр по собственным векселям" );
      end;
      ProgressIndicator = CreateProgressIndicator(true);
      ProgressIndicator.Start(ProgressValue.Maximum, header, header);
    end;
    var curBnrIndex = 0;
    var CurCurrency = -1;
    if (DataExist())
      while ( m_DataSetBanners.MoveNext() )
        /*************************************************/
        /* задать учётные периоды для очередного векселя */
        /*************************************************/
        SetRegistryPeriodsForBanner ( m_DataSetBanners.BCID );
        /**********************************************/
        /*необходимо получить:                        */
        /* Данные о самом векселе       dvsbanner_dbt */
        /* Данные о "транже" векселя    ddl_leg_dbt   */
        /* Данные о размещении векселя  dvsordlnk_dbt */
        /*                                            */
        /*                                            */
        /*                                            */
        /**********************************************/
        /**********************************************/
        /* Погашение может быть, а может и не быть    */
        /* ( в случае открытого учётного периода )    */
        /* Выборка в любом случае должна сработать    */
        /* практика показывает, что достаточно найти  */ 
        /* doproper_dbt c T_COMPLETED = 'X' и         */
        /* 02/04/2019 = конец УП.                     */
        /* Но, возможно, нужно будет смотреть шаги    */
        /**********************************************/
        i = 0;
        if(CurCurrency == -1)
          CurCurrency = m_DataSetBanners.PFI;
        elif(CurCurrency != m_DataSetBanners.PFI)
          ВывестиСтроки();
          CurCurrency = m_DataSetBanners.PFI;
        end;

        while ( i < m_RegistryPeriodArray.size )         
          m_SubQueryFinnaly = " WITH SubQ as ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + " (select distinct Bnr.t_Department, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        Bnr.t_BCSeries, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        Bnr.t_BCNumber,";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        Bnr.t_BCTermFormula, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        Bnr.t_BCTermFormat, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        Bnr.t_IssueDate, ";        
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_Start leg_Start, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_Expiry leg_Expiry, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_Maturity leg_Maturity, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_Formula leg_Formula, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_Price / POWER( 10, leg.t_Point ) AS leg_Price, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_Principal leg_Principal, ";        
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_Basis leg_Basis, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_Diff leg_Diff, ";      
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_InterestStart leg_InterestStart, "; //Дата начала начисления процентов             
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        leg.t_PFI leg_PFI, "; //Валюта номинала
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        NominalFin.t_CCY NominalFin_CCY, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        REPvsordlnk.t_BCCost REPvsordlnk_BCCost, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        REPvsordlnk.t_BCCFI REPvsordlnk_BCCFI, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        PartyClientSeller.t_ShortName Client_ShortName_Seller, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        PartyClientSeller.t_PartyID ClientID_Seller, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        case when PartyClientSeller.t_NRCountry = CHR(1) ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "             then ' ' ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "             else NVL( (select Country.t_FullName from dcountry_dbt Country where Country.t_CodeLAT3 = PartyClientSeller.t_NRCountry), ' ') ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        end Country_FullName_Seller ";       
                 
          m_SubQueryFinnaly = m_SubQueryFinnaly + "   from dvsbanner_dbt Bnr, ";       
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        ddl_leg_dbt leg, ";       
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        dparty_dbt PartyClientSeller,";      
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        dfininstr_dbt NominalFin, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        dvsordlnk_dbt REPvsordlnk, ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "        ddl_order_dbt REPord ";
      
          m_SubQueryFinnaly = m_SubQueryFinnaly + "  where Bnr.t_BCID = ? ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "    and leg.t_LegKind = " + LEG_KIND_VSBANNER + " ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "    and leg.t_DealID = Bnr.t_BCID ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "    and leg.t_PFI = NominalFin.t_FIID ";
          
          m_SubQueryFinnaly = m_SubQueryFinnaly + "    and REPvsordlnk.t_BCID = Bnr.t_BCID  ";        
          m_SubQueryFinnaly = m_SubQueryFinnaly + "    and REPord.t_ContractID = REPvsordlnk.t_ContractID ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "    and REPord.t_ContractID = ? ";
          m_SubQueryFinnaly = m_SubQueryFinnaly + "    and PartyClientSeller.t_PartyID = REPord.t_Contractor )";
      
          
        
          m_QueryFinnaly =                  " select Bnr.t_Department, ";
          m_QueryFinnaly = m_QueryFinnaly + "        TRIM(Bnr.t_BCSeries) as BCSeries, ";
          m_QueryFinnaly = m_QueryFinnaly + "        TRIM(Bnr.t_BCNumber) as BCNumber,";
          m_QueryFinnaly = m_QueryFinnaly + "        Bnr.t_BCTermFormula, ";
          m_QueryFinnaly = m_QueryFinnaly + "        Bnr.t_BCTermFormat, ";
          m_QueryFinnaly = m_QueryFinnaly + "        Bnr.t_IssueDate, ";        
          m_QueryFinnaly = m_QueryFinnaly + "        Bnr.t_BCID, ";
          m_QueryFinnaly = m_QueryFinnaly + "        Bnr.t_PayFIID, ";              //валюта платежа при эмиссии
          m_QueryFinnaly = m_QueryFinnaly + "        PartyDep.t_name DepName, ";
          m_QueryFinnaly = m_QueryFinnaly + "        dep.T_NAME DepCode, ";
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_Start leg_Start, ";
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_Expiry leg_Expiry, ";
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_Maturity leg_Maturity, ";
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_Formula leg_Formula, ";
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_Price / POWER( 10, leg.t_Point ) AS leg_Price, ";
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_Principal leg_Principal, ";        
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_Basis leg_Basis, ";
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_Diff leg_Diff, ";      
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_InterestStart leg_InterestStart, "; //Дата начала начисления процентов             
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_PFI leg_PFI, "; //Валюта номинала
          m_QueryFinnaly = m_QueryFinnaly + "        leg.t_ID leg_ID, "; //
          m_QueryFinnaly = m_QueryFinnaly + "        NominalFin.t_CCY NominalFin_CCY, ";
          m_QueryFinnaly = m_QueryFinnaly + "        ISSUEvsordlnk.t_BCCost ISSUEvsordlnk_BCCost, ";                                            
          m_QueryFinnaly = m_QueryFinnaly + "        ISSUEvsordlnk.t_BCCFI ISSUEvsordlnk_BCCFI, ";        
          m_QueryFinnaly = m_QueryFinnaly + "        ISSUEvsordlnk.t_BCCost ISSUEpaym_Amount, ";
          m_QueryFinnaly = m_QueryFinnaly + "        ISSUEvsordlnk.t_BCCFI ISSUEpaym_FIID, ";
          m_QueryFinnaly = m_QueryFinnaly + "        rsb_bill.GetBNRFirstDate(Bnr.t_BCID,ISSUEord.t_ContractID) ISSUEpaym_ValueDate, ";
          m_QueryFinnaly = m_QueryFinnaly + "        PartyClientBuyer.t_ShortName Client_ShortName_Buyer, ";
          m_QueryFinnaly = m_QueryFinnaly + "        PartyClientBuyer.t_PartyID ClientID_Buyer, ";
          m_QueryFinnaly = m_QueryFinnaly + "        NVL( (select Country.t_FullName from dcountry_dbt Country where Country.t_CodeLAT3 = PartyClientBuyer.t_NRCountry), ' ') Country_FullName_Buyer, ";
          m_QueryFinnaly = m_QueryFinnaly + "        ISSUEord.t_ContractID ISSUEord_ContractID, ";
          m_QueryFinnaly = m_QueryFinnaly + "        NVL( (select REPvsordlnk_BCCost from SubQ),-1 ) REPvsordlnk_BCCost, ";         
          m_QueryFinnaly = m_QueryFinnaly + "        ROUND( NVL( (select REPvsordlnk_BCCFI from SubQ), 0 ), 0 ) REPvsordlnk_BCCFI,   ";//и всё равно trsbdataset считает, что это Double... я в шоке, каст тоже не помог
          m_QueryFinnaly = m_QueryFinnaly + "        NVL( ( select Client_ShortName_Seller from SubQ), ' ') Client_ShortName_Seller, ";
          m_QueryFinnaly = m_QueryFinnaly + "        NVL( ( select ClientID_Seller from SubQ), -1)  ClientID_Seller, ";
          m_QueryFinnaly = m_QueryFinnaly + "        NVL( ( select Country_FullName_Seller from SubQ ), ' ') Country_FullName_Seller ";           
          
          m_QueryFinnaly = m_QueryFinnaly + "   from dvsbanner_dbt Bnr,     ";
          m_QueryFinnaly = m_QueryFinnaly + "        dparty_dbt PartyDep,   ";
          m_QueryFinnaly = m_QueryFinnaly + "        dparty_dbt PartyClientBuyer,";
          m_QueryFinnaly = m_QueryFinnaly + "        ddp_dep_dbt dep,       ";
          m_QueryFinnaly = m_QueryFinnaly + "        ddl_leg_dbt leg,       ";
          m_QueryFinnaly = m_QueryFinnaly + "        dfininstr_dbt NominalFin, ";
          m_QueryFinnaly = m_QueryFinnaly + "        dvsordlnk_dbt ISSUEvsordlnk, ";
          m_QueryFinnaly = m_QueryFinnaly + "        ddl_order_dbt ISSUEord   ";
      
          m_QueryFinnaly = m_QueryFinnaly + "  where Bnr.t_BCID = ? ";
          m_QueryFinnaly = m_QueryFinnaly + "    and dep.t_partyId = PartyDep.t_partyId ";
          m_QueryFinnaly = m_QueryFinnaly + "    and dep.t_code = Bnr.t_Department ";
          m_QueryFinnaly = m_QueryFinnaly + "    and leg.t_LegKind = " + LEG_KIND_VSBANNER + " ";
          m_QueryFinnaly = m_QueryFinnaly + "    and leg.t_DealID = Bnr.t_BCID ";
          m_QueryFinnaly = m_QueryFinnaly + "    and leg.t_PFI = NominalFin.t_FIID ";
          m_QueryFinnaly = m_QueryFinnaly + "    and ISSUEvsordlnk.t_BCID = Bnr.t_BCID  ";        
          m_QueryFinnaly = m_QueryFinnaly + "    and ISSUEvsordlnk.t_ContractID = ISSUEord.t_ContractID  ";
          m_QueryFinnaly = m_QueryFinnaly + "    and ISSUEord.t_ContractID = ? ";
          m_QueryFinnaly = m_QueryFinnaly + "    and PartyClientBuyer.t_PartyID = ISSUEord.t_Contractor ";;
          
          m_CmdQueryFinnaly = RSDCommand(m_SubQueryFinnaly + m_QueryFinnaly);
      
          m_CmdQueryFinnaly.addParam( "", RSDBP_IN, m_DataSetBanners.BCID );
          m_CmdQueryFinnaly.addParam( "", RSDBP_IN, m_RegistryPeriodArray[i].RepId );
          m_CmdQueryFinnaly.addParam( "", RSDBP_IN, m_DataSetBanners.BCID );
          m_CmdQueryFinnaly.addParam( "", RSDBP_IN, m_RegistryPeriodArray[i].IssueId );
          m_CmdQueryFinnaly.execute();    
          m_DataSetQueryFinnaly = TRsbDataSet( m_CmdQueryFinnaly );
          
          if ( m_DataSetQueryFinnaly.MoveNext() )
            m_Data[m_DataSize] = ReportData();
            m_DataSize = m_DataSize + 1;
            ПровестиДополнительныеВычисления();
            Вычислить_A3_A8_A9();      //для уменьшение дублирования кода
            Вычислить_А6_А10_А13_А14();//для уменьшение дублирования кода
            Вычислить_A44_A45();       //для уменьшение дублирования кода
            ДобавитьСтрокуДаных();
            ДобавитьДанныеДляОбщейСтроки();
          end;
          i = i + 1;
        end;
        ProgressValue.Current = ProgressValue.Current + 1;
        ProgressIndicator.Update(ProgressValue.Current,ProgressValue.Maximum); // всего 3 парамера Update(index, count, text)
        if (not m_IsWebService)
          progr = progr + 1;
          UseProgress( progr );
        end;
      end;
      ВывестиСтроки();
      ProgressIndicator.Stop();
      if (not m_IsWebService)
        RemProgress();
      end;
      EndTable();//без этого не работает. После вывода данных, нужно вызвать вот эту функцию....
      PrintHeader_rshb_supl(NumStr_N1); 
      SetOnAutoFilter("B12:BR12");
      SetAutoSize();
      ReplaceFormulaAndCalculate();
    else // no data
      PrintLineNoData();
      EndTable();
    END;  
  end;
 
  initDL_CReportTemplate( Form, TemplateName, UseCSV, IsWebService, ReportHashCode, NULL, NULL );
END;

MACRO ReportRunEx(
  IsWebService    : Bool
 ,FormData      //: CTxReportForm
 ,ReportHashCode  : Integer
 ,menuItem      //: WsMenuItem
)
  var stat = true;
  var FullReportFileNames = TArray();
  var Register_Report;

  if( not IsWebService )
    VSRegister_Form = DL_Register_Panel("VSREGREP");
  else
    WebMenuItem = menuItem;
    if( ValType( FormData ) != V_UNDEF )
      WebFormData = FormData;
    else
      stat = false;
    end;
  end;

  while( stat )
    if( not IsWebService )
      stat = VSRegister_Form.Run();
    end;

    if( stat )
      Register_Report = VS_Register_Report( null, "report_vs_register.xlsx", null, IsWebService, null );
      Register_Report.Run();

      if( IsWebService )
        Dl_CallInsertStat(DL_OUTREPORT_EXCEL, menuItem.iCaseItem, menuItem.iIdentProgram, menuItem.szNameItem);
        FullReportFileNames = Register_Report.GetFullReportFileNames();
        stat = false;
      else
        DL_CallInsertStat(DL_OUTREPORT_EXCEL);
      end;
    end;
  end;

  return FullReportFileNames;
END;