DECLARE
  maxval NUMBER := 0;
BEGIN
  SELECT MAX (t_id) + 1
  INTO maxval
  FROM dsfdef_dbt
  WHERE t_feetype = 6;

  EXECUTE IMMEDIATE 'drop SEQUENCE DSFDEF_DBT_SINGLE_SEQ';
  EXECUTE IMMEDIATE 'CREATE SEQUENCE DSFDEF_DBT_SINGLE_SEQ START WITH '||maxval||' MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER' ;
END;
/
