--Добавление новых полей в таблицу событий СНОБ
DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXTOTALBASE_DBT ADD T_SENDDATE DATE DEFAULT TO_DATE(''01.01.0001'',''DD.MM.YYYY'')';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXTOTALBASE_DBT.T_SENDDATE IS ''Дата отправки''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXTOTALBASE_DBT ADD T_SENDTIME DATE DEFAULT TO_DATE(''01.01.0001 00:00:00'',''DD.MM.YYYY HH24:MI:SS'')';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXTOTALBASE_DBT.T_SENDTIME IS ''Время отправки''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXTOTALBASE_DBT ADD T_CANCELDATE DATE DEFAULT TO_DATE(''01.01.0001'',''DD.MM.YYYY'')';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXTOTALBASE_DBT.T_CANCELDATE IS ''Дата отмены''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXTOTALBASE_DBT ADD T_CANCELTIME DATE DEFAULT TO_DATE(''01.01.0001 00:00:00'',''DD.MM.YYYY HH24:MI:SS'')';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXTOTALBASE_DBT.T_CANCELTIME IS ''Время отмены''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/



