/*на некоторых стендах может не быть U_TARIF_DLCONTR_DBT, и это нормально, поэтому ошибку глушу*/
DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE U_TARIF_DLCONTR_DBT'; 
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE U_TARIF_DLCONTR_TMP (t_DlContrID NUMBER(10)) ON COMMIT PRESERVE ROWS
/

CREATE UNIQUE INDEX U_TARIF_DLCONTR_TMP_IDX0 ON U_TARIF_DLCONTR_TMP (t_DlContrID ASC)
/
