DECLARE
  v_cnt NUMBER;
  v_sequenceName VARCHAR2(40) := 'UPMBISCOTTO_DBT_SEQ';
  v_startValue INTEGER;
BEGIN
  SELECT COUNT(1) 
    INTO v_cnt 
    FROM user_sequences
   WHERE UPPER(sequence_name) = v_sequenceName;
  
  IF v_cnt = 0 THEN
    SELECT COUNT(*)+1 INTO v_startValue FROM UPMBISCOTTO_DBT; 
   
    EXECUTE IMMEDIATE 'CREATE SEQUENCE '||v_sequenceName||' '||
                      'START WITH '||TO_CHAR(v_startValue)||' '||
                      'MAXVALUE 999999999999999999999999999 '||
                      'MINVALUE 1 NOCYCLE NOCACHE NOORDER';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER UPMBISCOTTO_DBT_AINC
  BEFORE INSERT OR UPDATE OF T_PMID ON UPMBISCOTTO_DBT FOR EACH ROW
DECLARE
BEGIN
  IF (:NEW.T_PMID = 0 OR :NEW.T_PMID IS NULL) AND :NEW.T_DOCKIND = -900 THEN
    SELECT UPMBISCOTTO_DBT_SEQ.NEXTVAL INTO :NEW.T_PMID FROM DUAL;
  END IF;
END;
/