--Добавление новых полей в таблицу событий СНОБ
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDLREP701_TMP DROP COLUMN t_contractorname';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDLREP701_TMP DROP COLUMN t_addgrflag';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDLREP701_TMP DROP COLUMN t_lei_contractor';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDLREP701_TMP DROP COLUMN t_inn_contractor';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDLREP701_TMP DROP COLUMN t_contractorid';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DDLREP701_TMP DROP COLUMN t_ismoneymarket';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DELETE FROM dregval_dbt WHERE t_keyid = (select t_keyid from dregparm_dbt where t_name=''ДАТА АКТ. Ф. 0409701 (6406-У)'')';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DELETE FROM dregparm_dbt WHERE t_name=''ДАТА АКТ. Ф. 0409701 (6406-У)''';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
