DECLARE
  v_ID       NUMBER := 0;
  v_ParentID NUMBER := 0;
BEGIN

  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = 0 AND LOWER(T_NAME) = LOWER('COMMON');
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('çÑîã');
  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('ìóÖí áÄíêÄí èêéòãõï ãÖí');

  UPDATE DREGPARMSTORY_DBT SET T_DATEEND = TO_DATE('31.12.2024', 'DD.MM.YYYY') WHERE T_KEYID = v_ID and T_DATEBEGIN = TO_DATE('01.01.0001', 'DD.MM.YYYY');
  
  UPDATE DREGVAL_DBT SET T_LINTVALUE = 0 WHERE T_KEYID = v_ID AND T_REGKIND = 0 AND T_OBJECTID = 0;

  INSERT INTO DREGPARMSTORY_DBT(T_ID, T_KEYID, T_DATEBEGIN, T_DATEEND, T_INTVALUE, T_DOUBLEVALUE, T_BOOLVALUE, T_STRINGVALUE)
       VALUES (0, v_ID, TO_DATE('01.01.2025', 'DD.MM.YYYY'), TO_DATE('31.12.9999', 'DD.MM.YYYY'), 0, 0, CHR(0), CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/