-- Таблица "DNPTXMATCHINOUTCH_DBT"

CREATE TABLE DNPTXMATCHINOUTCH_DBT (
    T_ID NUMBER(10)
  , T_MATCHID NUMBER(10)
  , T_DATEEND DATE
  , T_DATEEND_OLD DATE
  , T_OPER NUMBER(10)
  , T_DATEREC DATE
)
/

COMMENT ON TABLE DNPTXMATCHINOUTCH_DBT IS 'История таблицы соотв. кодов дох. и выч.'
/
COMMENT ON COLUMN DNPTXMATCHINOUTCH_DBT.T_ID IS 'Идентификатор'
/
COMMENT ON COLUMN DNPTXMATCHINOUTCH_DBT.T_MATCHID IS 'Идентификатор из таблицы соотвествия'
/
COMMENT ON COLUMN DNPTXMATCHINOUTCH_DBT.T_DATEEND IS 'Новая дата окончания'
/
COMMENT ON COLUMN DNPTXMATCHINOUTCH_DBT.T_DATEEND_OLD IS 'Прежняя дата окончания'
/
COMMENT ON COLUMN DNPTXMATCHINOUTCH_DBT.T_OPER IS 'Пользователь'
/
COMMENT ON COLUMN DNPTXMATCHINOUTCH_DBT.T_DATEREC IS 'Дата изменения'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXMATCHINOUTCH_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXMATCHINOUTCH_DBT_IDX0 ON DNPTXMATCHINOUTCH_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXMATCHINOUTCH_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXMATCHINOUTCH_DBT_IDX1 ON DNPTXMATCHINOUTCH_DBT (
   T_MATCHID ASC
)
/

CREATE SEQUENCE DNPTXMATCHINOUTCH_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DNPTXMATCHINOUTCH_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXMATCHINOUTCH_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXMATCHINOUTCH_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXMATCHINOUTCH_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
