/*Создание временной таблицы*/
CREATE GLOBAL TEMPORARY TABLE DNPTXREFLOSSCLLIST_TMP
(
  T_CLIENTID_CFT   VARCHAR2(35),
  T_CLIENTID_SOFR  NUMBER(10),
  T_ISERROR        CHAR(1),
  T_MESSAGE        VARCHAR2(250)
)
ON COMMIT PRESERVE ROWS
/


CREATE INDEX DNPTXREFLOSSCLLIST_TMP_IDX1 ON DNPTXREFLOSSCLLIST_TMP
(T_CLIENTID_SOFR, T_ISERROR)
/