/*
$Name:             blncslfi.mac
$Module:           АРНУ
$Description:      Отчет "Доходы и расходы от реализации ц/б"
*/

import "sccomiss.mac", "spRepFn2.mac", "globals.mac", "DLReport_h.mac", "or_rep_h.mac", "Blncslfi_Form.mac";
import RsbDataSet;

private const ALG_SCTX_LOTORIGIN = 7306;

/* Флажки для отладки. */
private const
   Debug_ShowInnerDealCode = false; /* показывать внутренние коды сделок */

private const Date67 = date(14, 7, 2005);

private const ALL_FI = -1,
              SHARE = 1,
              DEPO_RECEIPT = 2,
              BOND  = 3;

//виды печатных секций отчета
private const REPSECTION_CIRCULATE    = 0,  //обращающиеся на ОРЦБ
              REPSECTION_NOTCIRCULATE = 1,  //не обращающиеся на ОРЦБ
              REPSECTION_ISSUERCORPOP = 2;  //корпоративные действия эмитента

private const NOTEKIND_SECDEAL_REG_DEAL = 14;
private var T_ISO:T_ISO_Collector;
private var fininstr = TRecHandler( "fininstr" );

private var ReportHeader =
"\n\n#######################################################################################################################################################\n" +
"#########################################\n" +
"###########################################################################################################################################################\n" +
"\n" +
"за период: ########################\n" +
"по сделкам с ценными бумагами: ############################\n" +
"                               ############################\n" +
"############################\n";

private var
   Table = "┌─────────────────────────┬───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┬─────────┬─────────┐\n" +
           "│   Наименование ценных   │Валюта │                                                                                               ПРИОБРЕТЕНИЕ                                                                                                                                      │                              ВЫПЛАТЫ ОТ ЭМИТЕНТА                            │                                                                                                 РЕАЛИЗАЦИЯ                                                                                              │                         ИТОГИ                          │                                                     КОРРЕКТИРОВКА                                                          │  Вид  │Взаимоза-│Взаимоза-│\n" +
           "│          бумаг          │ номи- ├────────────────────────┬─────────┬────────────┬─────────┬───────────┬───────────┬─────────────────────────────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬──────────┬──────────┬───────┬───────┼──────────────────────────┬─────────────────────────┬────────────────────────┼──────────────────────┬────────┬──────────────────────┬────────┬───────────┬───────────┬──────────────────────┬──────────────────────┬──────────────────┬──────────────────┬──────────┬──────────┬───────┼──────────────────┬──────────────────┬──────────────────┼─────────────────────────────┬──────────────────────────┬─────────────────────────────┬─────────────────────────────────────┤ связи │висимость│висимость│\n" +
           "│                         │ нала  │Наименование контрагента│  Дата   │     №      │  Дата   │  Количе-  │  Номинал  │                                             │                                     │                                     │ Валюта   │ Затраты, │Являет-│Участие│НКД, учтенный для целей   │ НКД, полученный от      │    Сумма частичного    │     Наименование     │  Дата  │          №           │  Дата  │ Количест- │  Номинал  │         Цена         │         Цена         │    Стоимость     │       НКД        │ Валюта   │ Затраты, │Являет-│    Стоимость     │       НКД        │      Всего       │         Контрольный         │   Организатор торговли   │       Даты котировок        │          Сумма отклонения           │ сделок│контр-   │контраген│\n" +
           "│                         │       │       по сделке        │заключе -│  договора  │приобре- │ ство, шт. │           │          Цена приобретения (за ед.)         │        Стоимость приобретения       │                 НКД                 │ цены/    │  связан- │ся     │в      │налогообложения в преды-  │эмитента при погашении   │   погашения номинала,  │      контрагента     │ заключ.│       договора       │реализа-│  во, шт.  │           │      реализации      │      реализации      │    реализации    │                  │ цены/    │ связанные│ся     │                  │                  │                  │         интервал цен        │                          │                             │          от рыночной цены           │       │агента по│та по сде│\n" +
           "│                         │       │                        │  ния    │            │ тения   │           │           │                                             │                                     │                                     │ валюта   │   ные с  │урегу- │дейст- │дущем налоговом периоде,  │купонов в отчетном (нало-│ полученная от эмитента,│       по сделке      │ сделки/│                      │  ции   │           │           │       (за ед.)       │       (за ед.)       │                  │                  │ валюта   │с реализа-│урегу- │                  │                  │                  │                             │                          │                             │                                     │       │сделке ре│лке при- │\n" +
           "│                         │       │                        │ сделки  │            │ ценных  │           │           ├──────────────────────┬──────────────────────┼──────────────────┬──────────────────┼──────────────────┬──────────────────┤ расчетов │ приобре- │лирую- │виях   │но не полученный от эми-  │говом) периоде (кроме    │           руб.         │                      │ погаш. │                      │        │           │           │         /вал.        │         /руб.        │                  │                  │ расчетов │   цией   │лирую- │                  │                  │                  ├──────────────┬──────────────┼────────────┬─────────────┼──────────────┬──────────────┼──────────────────┬──────────────────┤       │ализации │обретения│\n" +
           "│                         │       │                        │         │            │  бумаг  │           │           │          вал.        │         руб.         │       вал.       │       руб.       │       вал.       │       руб.       │          │  тением  │щей    │эмитен-│тента на начало отчетного │ купона, полученного при │                        │                      │        │                      │        │           │           │                      │                      │                  │                  │          │   бумаг  │щей    │                  │                  │                  │     макс.    │     мин.     │    макс.   │     мин.    │     макс.    │     мин.     │       пок.       │       прод.      │       │с нашим  │с нашим  │\n" +
           "│                         │       │                        │         │            │         │           │           │                      │                      │                  │                  │                  │                  │          │    ц/б   │сделкой│та     │(налогового) периода, руб.│ погашении бумаги), руб. │                        │                      │        │                      │        │           │           │                      │                      │                  │                  │          │          │сделкой│                  │                  │                  │              │              │            │             │              │              │                  │                  │       │банком   │банком   │\n" +
           "├─────────────────────────┼───────┼────────────────────────┼─────────┼────────────┼─────────┼───────────┼───────────┼──────────────────────┼──────────────────────┼──────────────────┼──────────────────┼──────────────────┼──────────────────┼──────────┼──────────┼───────┼───────┼──────────────────────────┼─────────────────────────┼────────────────────────┼──────────────────────┼────────┼──────────────────────┼────────┼───────────┼───────────┼──────────────────────┼──────────────────────┼──────────────────┼──────────────────┼──────────┼──────────┼───────┼──────────────────┼──────────────────┼──────────────────┼──────────────┼──────────────┼────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼──────────────────┼───────┼─────────┼─────────┤\n" +
           "│           1             │   2   │            3           │    4    │     5      │    6    │     7     │     8     │           9          │          10          │        11        │        12        │        13        │        14        │    15    │    16    │   17  │   18  │            19            │            20           │           21           │          22          │   23   │          24          │   25   │     26    │     27    │          28          │          29          │        30        │        31        │    32    │    33    │   34  │        35        │        36        │        37        │      38      │      39      │     40     │     41      │      42      │      43      │        44        │        45        │   46  │   47    │   48    │\n" +
           "├─────────────────────────┼───────┼────────────────────────┼─────────┼────────────┼─────────┼───────────┼───────────┼──────────────────────┼──────────────────────┼──────────────────┼──────────────────┼──────────────────┼──────────────────┼──────────┼──────────┼───────┼───────┼──────────────────────────┼─────────────────────────┼────────────────────────┼──────────────────────┼────────┼──────────────────────┼────────┼───────────┼───────────┼──────────────────────┼──────────────────────┼──────────────────┼──────────────────┼──────────┼──────────┼───────┼──────────────────┼──────────────────┼──────────────────┼──────────────┼──────────────┼────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼──────────────────┼───────┼─────────┼─────────┤";

PRIVATE VAR m_Report;
PRIVATE VAR m_IsWebService = false;
PRIVATE VAR WebMenuItem; // Информация о запуске отчета из веб

private const
   /* Различные строки. */
   RepName1 = "Расчет доходов и расходов от реализации (выбытия) ценных бумаг (государственные и муниципальные ценные бумаги)",
   RepName2 = "Расчет доходов и расходов от реализации (выбытия) ценных бумаг (кроме государственных и муниципальных ценных бумаг, векселей и деп. сертификатов)",
   Itog1    = "Итого по разделу \"Операции с ценными бумагами, обращающимися на ОРЦБ\"",
   Itog2    = "Итого по разделу \"Операции с ценными бумагами, не обращающимися на ОРЦБ\"",
   Itog3    = "Итого по разделу \"Действия эмитента\"",
   Itog4    = "Итого по разделу \"Корпоративные действия эмитента\"",
   Title1   = "Операции с ценными бумагами, обращающимися на ОРЦБ",
   Title2   = "Операции с ценными бумагами, не обращающимися на ОРЦБ",
   Title3   = "Действия эмитента",
   Title4   = "Корпоративные действия эмитента",
   StatLine       = "Отчет \"Доходы и расходы от реализации ц/б\"",
   TitleCirc       = "Выпуск отчета по бумагам, обращающимся на ОРЦБ",
   TitleNotCirc    = "Выпуск отчета по бумагам, не обращающимся на ОРЦБ",
   TitleIssuerCorpOp = "Выпуск отчета по бумагам, прошедшим корпоративные действия эмитента";

/* Класс для хранения наименований филиалов.
      _DepID   - филиал
      _DepName - наименование */
private class TAllParty( _PartyID, _PartyName, _InterDepend )
   var
      PartyID     = _PartyID,
      PartyName   = _PartyName,
      InterDepend = _InterDepend;
end;

/* Массив для хранения наименований филиалов.
   Элементы массива - классы TAllDep. Реализован как наследник от TArray.
   Дополнительные методы:
      ClearArray  - очистить массив.
      Get_Dep  - получить имя. */
private class (TArray) T_Party_Collector

   /* Очистить массив. */
   macro ClearArray()
      this.Size = 0;
   end;

   /* Найти наименование данного филиала. */
   macro Get_Party( PartyID, InterDepend:@string )

      var PartyRec = TRecHandler("party.dbt");
      var
         Counter = 0, PartyName = "";

      InterDepend = "";

      /* Ищем в массиве нужный субъект. */      
      while( (Counter < this.Size) and (this.(Counter).PartyID != PartyID) )
         Counter = Counter + 1;
      end;

      if( (Counter < this.Size) and (this.(Counter).PartyID == PartyID) )
         /* Нашли подходящую запись. Возьмем наименование из нее. */
         PartyName   = this.(Counter).PartyName;
         InterDepend = this.(Counter).InterDepend;
      else
         /* Запись не нашли. Нужно вставить запись в конец массива. */
         if( ПолучитьСубъекта(PartyID, PartyRec) == 0 )
           PartyName = PartyRec.rec.Name;
           DL_GetObjAttrName(OBJTYPE_PARTY, PARTY_ATTR_GROUP_UNICHANGE, DL_GetMainObjAttr(PartyRec, PARTY_ATTR_GROUP_UNICHANGE, OBJTYPE_PARTY ),
                             null, null, @InterDepend);
           InterDepend = IIF(InterDepend=="1","Да","Нет");
         end;

         /* Вставим запись в конец массива. */
         this.(this.Size) = TAllParty( PartyID, PartyName, InterDepend );
      end;

      return PartyName;

   end;
end; 

private class FiidNomOnDate(_FIID:integer,_OnDate:Date,_Nominal)

   var FIID,
       OnDate,
       Nominal;

   FIID    = _FIID;  
   OnDate  = _OnDate;
   Nominal = _Nominal;

end;

private var T_PARTY:T_Party_Collector;
private var NomOnDateBuy:FiidNomOnDate;
private var NomOnDateSale:FiidNomOnDate;

class (TBaseReportData)SourceData( _Period:integer, _Year:integer, _GrowingItog:bool, 
                                   _CirculateInMarket:bool, _NotCirculateInMarket:bool, _IssuerCorpOp:bool,
                                   _NominateInRUR:bool, _NotNominateInRUR:bool,
                                   _Avr_Kind, _AvrID, _AvrGroup, 
                                   _LnkBuySale:bool, _LnkCloseShortPos:bool, _IsGos:bool )

   var
      GrowingItog    = _GrowingItog,            /*Нарастающим итогом*/
      CircInMark     = _CirculateInMarket,      /*Обращается на ОРЦБ*/
      NotCircInMark  = _NotCirculateInMarket,   /*Не обращаются на ОРЦБ*/
      IssuerCorpOp   = _IssuerCorpOp,           /*Участие в корпоративных действиях эмитента*/
      NominateInRUR = _NominateInRUR,           /*Номинированные в RUR*/
      NotNominateInRUR = _NotNominateInRUR,     /*Номинированные в иностранной валюте*/
      Avr_Kind,                                 /*Вид бумажки*/
      AvrID,                                    /*Код бумажки*/
      AvrGroup,                                 /*Группа НУ бумажки*/
      LnkBuySale        = _LnkBuySale,
      LnkCloseShortPos  = _LnkCloseShortPos,
      IsGos = _IsGos;                           /* Отчет по госуд. ц/б */
   var
      BegDate,                      /* Дата начала периода */
      EndDate,                      /* Дата конца периода */
      RepBegDate,                   /* Дата начала периода без нарастающего итога */
      RepEndDate,                   /* Дата конца периода без нарастающего итога */
      PrevBegDate,                  /* Дата начала предшествующего периода */
      PrevEndDate,                  /* Дата конца предшествующего периода */
      PeriodName;                   /* Наименование периода */

   var
      WasPrintInRep     = false,    /* Была печать данных в отчете */
      WasPrintInPart    = false,    /* Была печать данных в разделе */
      WasPrintPartHead  = false;    /* Была печать названия подраздела */

   var 
      IsBond = false, IsShare = false, IsCoupAvoir = false, IsAvrKindBond_AD = false;

   var UniqStr   = TUniqStrCollector;

   if( ValType(AvrID) == V_Integer )
     Avr_Kind = IIF(_Avr_Kind <= 0, ALL_FI, _Avr_Kind); /*Вид бумажки*/
     AvrID = IIF(_AvrID <= 0, ALL_FI, _AvrID);          /*Код бумажки*/
     AvrGroup = IIF(_AvrGroup <= 0, ALL_FI, _AvrGroup); /*Группа НУ бумажки*/
   else
     Avr_Kind = _Avr_Kind; /*Вид бумажки*/
     AvrID = _AvrID;       /*Код бумажки*/
     AvrGroup = _AvrGroup; /*Группа НУ бумажки*/
   end;

   macro SetWasPrintLot()
      this.WasPrintInRep   = true;
      this.WasPrintInPart  = true;
   end;

   macro AfterPrintNewPart()
      this.WasPrintInPart     = false;
      this.WasPrintPartHead   = false; 
   end;

   /* Конструктор */
   initTBaseReportData( true );
   T_ISO.ClearArray();
   T_PARTY.ClearArray();

   Period_GetInterval( _Period, _Year, @BegDate, @EndDate, _GrowingItog );
   Period_GetInterval( _Period, _Year, @RepBegDate, @RepEndDate, false );

   /* прошедший период */
   if( (_Period > 1) and (_Period != 13) ) /* не январь и не 1-й квартал */
     Period_GetInterval( _Period-1, _Year, @PrevBegDate, @PrevEndDate, _GrowingItog );
   else
     Period_GetInterval( 16, _Year-1, @PrevBegDate, @PrevEndDate, _GrowingItog );
   end;
   PeriodName = PeriodName_GetMonthsAndQuart( _Period, _Year, _GrowingItog );
end;

/* Класс для хранения итоговых данных */
class SummaryData
   var
      Summ_Buy_RUR     = $0,    /* Стоимость купленных ц/б, руб. */
      Summ_Buy_VAL     = $0,    /* Стоимость купленных ц/б, вал. */
      NKD_Buy_RUR      = $0,    /* Сумма НКД, уплаченная по лоту покупки, руб. */
      NKD_Buy_VAL      = $0,    /* Сумма НКД, уплаченная по лоту покупки, вал. */
      Outlay_Buy       = $0,    /* Затраты, связанные с приобретением ц/б */
      Summ_Sale        = $0,    /* Стоимость проданых ц/б */
      NKD_Sale         = $0,    /* Сумма НКД, уплаченная по лоту продажи */
      Outlay_Sale      = $0,    /* Затраты, связанные с приобретением ц/б */
      Amount           = $0,    /* ИТОГИ / гр.Стоимость */
      NKD              = $0,    /* ИТОГИ / гр.НКД */
      All              = $0,    /* ИТОГИ / гр.Всего */
      DevReceipts      = $0,    /* Сумма отклонения выручки */
      DevOutlays       = $0,    /* Сумма отклонения затрат */
      NKD_26           = $0,    /* НКД, учтенный для целей налогообложения в предыдущем налоговом периоде, но не полученный от эмитента на начало отчетного (налогового) периода - Сумма, руб*/
      NKD_27           = $0,    /* НКД, полученный от эмитента при погашении купонов в отчетном (налоговом) периоде (кроме купона, полученного при погашении бумаги), руб.*/
      Partly_28        = $0;    /* Сумма частичном погашении номинала, полученная от эмитен-та, руб.*/

   /* Метод: прибавить к себе SummaryData */
   macro Add( Summand )
      this.Summ_Buy_RUR     = this.Summ_Buy_RUR     + Summand.Summ_Buy_RUR;   //F6
      this.NKD_Buy_RUR      = this.NKD_Buy_RUR      + Summand.NKD_Buy_RUR;    //F7
      this.Outlay_Buy       = this.Outlay_Buy       + Summand.Outlay_Buy;     //F8
      this.Summ_Sale        = this.Summ_Sale        + Summand.Summ_Sale;      //F15
      this.NKD_Sale         = this.NKD_Sale         + Summand.NKD_Sale;       //F16
      this.Outlay_Sale      = this.Outlay_Sale      + Summand.Outlay_Sale;    //F17
      
      this.Amount           = this.Amount           + Summand.Amount;         //F18
      this.NKD              = this.NKD              + Summand.NKD;            //F19
      this.All              = this.All              + Summand.All;            //F20
      
      this.DevReceipts      = this.DevReceipts      + Summand.DevReceipts;    //F24а
      this.DevOutlays       = this.DevOutlays       + Summand.DevOutlays;     //F24б

      this.NKD_26           = this.NKD_26           + Summand.NKD_26   ;      //F26
      this.NKD_27           = this.NKD_27           + Summand.NKD_27   ;      //F27
      this.Partly_28        = this.Partly_28        + Summand.Partly_28;      //F28
   end;
end;

/* Класс для хранения данных одной строки отчета.
   Наследуется от SummaryData. */
class (SummaryData) ReportData
   var
      SfContr_Buy             = null,     /* Номер договора покупки */
      Date_Buy                = null,     /* Фактическая дата поставки ц/б */
      Amount_Buy              = $0,       /* Количество ценных бумаг в лоте покупки */
      dblPrice_Buy_RUR        = $0,       /* Цена одной ц/б в нац.валюте (double) */
      strPrice_Buy_RUR_Print  = "",       /* Строка цены одной ц/б в нац.валюте (double) для печати*/
      dblPrice_Buy_VAL        = $0,       /* Цена одной ц/б в ин. валюте (double) */
      strPrice_Buy_VAL_Print  = "",       /* Строка цены одной ц/б в ин. валюте (double) для печати*/
      DealDate_Sale           = null,     /* Дата заключения сделки продажи */
      DealDate_Buy            = null,     /* Дата заключения сделки приобретения */
      SfContr_Sale            = null,     /* Номер договора продажи */
      Date_Sale               = null,     /* Фактическая дата поставки ц/б */
      Amount_Sale             = $0,       /* Количество ценных бумаг в лоте продажи */
      dblPrice_Sale           = 0,        /* Цена одной ц/б в нац.валюте (double) */
      dblPrice_Sale_Print     = 0,        /* Цена одной ц/б в нац.валюте (double) для печати*/
      strPrice_SaleVal_Print  = "",       /* Строка цены одной ц/б в валюте (double) для печати*/
      OriginName              = "";       // Происхождение

   /* Вызов конструктора базового класса */
   InitSummaryData;
end;

private var Data;

MACRO getTaxGroup(FIID)
        
        var stat = 0;

        var query = "SELECT t_taxgroup FROM davoiriss_dbt WHERE davoiriss_dbt.t_FIID = " + string(FIID);
                                     
        var rsbDataSet = TRsbDataSet(query);
        if( rsbDataSet.MoveNext() )
           stat = rsbDataSet.taxGroup;
        end;

        return stat;
   
END;

macro PrintHeadReport( NumRep )
   var
      INN = "", KPP = "",
      BankName = "",
      RepNum = IIF(Data.IsGos, 6, 7);

   SplitFullINN(ПолучитьКодСубъекта({OurBank}, PTCK_INN), INN, KPP);
  
   if( INN != "" )
      INN = " ИНН " + INN;
   end;

   if( KPP != "" )
      KPP = " КПП " + KPP;
   end;

   BankName = GetPartyByID({OurBank}, true).Name + "  " + INN + KPP;

   m_Report.SetActiveSheet( string(NumRep) );

   m_Report.PrintFormatString( ReportHeader,
                               "N1_BankName:l", BankName,
                               "N1_RegNum:l", "Аналитический регистр налогового учета №" + RepNum,
                               "N1_RegName", IIF(Data.IsGos, RepName1, RepName2),
                               "N1_PeriodName", Data.PeriodName,
                               "N1_CircInMarket", IIF(Data.CircInMark,   "[X]", "[ ]")+" обращающимися на ОРЦБ",
                               "N1_NotCircInMarket", IIF(Data.NotCircInMark,"[X]", "[ ]")+" не обращающимися на ОРЦБ",
                               "N1_IssuerCorpOp", IIF(Data.IssuerCorpOp,"[X]", "[ ]")+IIF(Data.IsGos, " по действиям эмитента", " по корпоративным действиям эмитента")
                             );

   m_Report.RegisterTable( "N_MainTable", Table,
                           "N_SecName",               /*  1  А1    */
                           "N_FaceFiCode",            /*  2  А0    */
                           "N_BuyContrName",          /*  3  А1а   */
                           "N_BuyDealDate",           /*  4  А1б   */
                           "N_BuyDealCode",           /*  5  А2    */
                           "N_BuyDate",               /*  6  А3    */
                           "N_BuyAmount",             /*  7  A4    */
                           "N_NomB",                  /*  8  NomB  */
                           "N_BuyPrirceCur",          /*  9  А5а   */
                           "N_BuyPrirceRUR",          /* 10  А5б   */
                           "N_BuyCostCur",            /* 11  А6а   */
                           "N_BuyCostRUR",            /* 12  А6б   */
                           "N_BuyNKDCur",             /* 13  А7а   */
                           "N_BuyNKDRUR",             /* 14  А7б   */
                           "N_BuyVCVR",               /* 15  А7-1  */
                           "N_BuyComSum",             /* 16  А8    */
                           "N_BuyRegulat",            /* 17  A9    */
                           "N_TGO",                   /* 18        */
                           "N_NKDAcc",                /* 19  A26   */
                           "N_NKDGot",                /* 20  A27   */
                           "N_Partly",                /* 21  A28   */
                           "N_SaleContrName",         /* 22  А10а  */
                           "N_SaleDealDate",          /* 23  A10   */
                           "N_SaleDealCode",          /* 24  A11   */
                           "N_SaleDate",              /* 25  A12   */
                           "N_SaleAmount",            /* 26  A13   */
                           "N_NomS",                  /* 27  NomS  */
                           "N_SalePrirceCur",         /* 28  A14-1 */
                           "N_SalePrirceRUR",         /* 29  A14-2 */
                           "N_SaleTotalCostCur",      /* 30  A15   */
                           "N_SaleNKDCur",            /* 31  A16   */
                           "N_SaleVCVR",              /* 32  А16-1 */
                           "N_SaleComSum",            /* 33  A17   */
                           "N_SaleRegulat",           /* 34  A17а  */
                           "N_TotPriceSum",           /* 35  A18   */
                           "N_TotNKD",                /* 36  A19   */
                           "N_TotSum",                /* 37  A20   */
                           "N_MaxPrice",              /* 38  A21b  */
                           "N_MinPrice",              /* 39  A21а  */
                           "N_MaxMarket",             /* 40  A23   */
                           "N_MinMarket",             /* 41  A22   */
                           "N_MaxDate",               /* 42  A29   */
                           "N_MinDate",               /* 43  A30   */
                           "N_DevOutlays",            /* 44  А24б  */
                           "N_DevReceipts",           /* 45  А24а  */
                           "N_LnkType",               /* 46  А43   */
                           "N_DepS",
                           "N_DepB"
                         );      
end;

private macro PrintTableLine(IsItog,NumRep,
                             /*  1  А1    */ f01,
                             /*  2  А0    */ f02,
                             /*  3  А1а   */ f03,
                             /*  4  А1б   */ f04,
                             /*  5  А2    */ f05,
                             /*  6  А3    */ f06, 
                             /*  7  A4    */ f07, f07_1,
                             /*  8  NomB  */ f08,
                             /*  9  А5а   */ f09,
                             /* 10  А5б   */ f10,
                             /* 11  А6а   */ f11,
                             /* 12  А6б   */ f12,
                             /* 13  А7а   */ f13,
                             /* 14  А7б   */ f14,
                             /* 15  А7-1  */ f15,
                             /* 16  А8    */ f16,
                             /* 17  A9    */ f17,
                             /* 18  A29   */ f18,
                             /* 19  A26   */ f19,
                             /* 20  A27   */ f20,
                             /* 21  A28   */ f21,
                             /* 22  А10а  */ f22,
                             /* 23  A10   */ f23,
                             /* 24  A11   */ f24,
                             /* 25  A12   */ f25,
                             /* 26  A13   */ f26,
                             /* 27  NomS  */ f27,
                             /* 28  A14-1 */ f28,
                             /* 29  A14-2 */ f29,
                             /* 30  A15   */ f30,
                             /* 31  A16   */ f31,
                             /* 32  А16-1 */ f32,
                             /* 33  A17   */ f33,
                             /* 34  A17а  */ f34,
                             /* 35  A18   */ f35,
                             /* 36  A19   */ f36,
                             /* 37  A20   */ f37,
                             /* 38  A21b  */ f38,
                             /* 39  A21а  */ f39,
                             /* 40  A23   */ f40,
                             /* 41  A22   */ f41,
                             /* 42  A29   */ f42,
                             /* 43  A30   */ f43,
                             /* 44  А24б  */ f44,
                             /* 45  А24а  */ f45,
                             /* 46  А43   */ f46,
                             /* 46  А43   */ f47,
                                             f48
                            )

  if( not IsItog )           
  var Precision = 0;
  if( IsHaveFractPart(f26) OR IsHaveFractPart(f07) )
     Precision = f07_1;
  end;
     m_Report.PrintTableLine( "N_SecName",          f01,   null,  /*  1  А1    */
                              "N_FaceFiCode",       f02,   null,  /*  2  А0    */
                              "N_BuyContrName",     f03,   null,  /*  3  А1а   */
                              "N_BuyDealDate",      f04,   null,  /*  4  А1б   */
                              "N_BuyDealCode",      f05,   null,  /*  5  А2    */
                              "N_BuyDate",          f06,   null,  /*  6  А3    */
                              "N_BuyAmount",        f07,   Precision, /*  7  A4    */
                              "N_NomB",             f08,   null,  /*  8  NomB  */
                              "N_BuyPrirceCur",     f09,   null,  /*  9  А5а   */
                              "N_BuyPrirceRUR",     f10,   null,  /* 10  А5б   */
                              "N_BuyCostCur",       f11,   null,  /* 11  А6а   */
                              "N_BuyCostRUR",       f12,   null,  /* 12  А6б   */
                              "N_BuyNKDCur",        f13,   null,  /* 13  А7а   */
                              "N_BuyNKDRUR",        f14,   null,  /* 14  А7б   */
                              "N_BuyVCVR",          f15,   null,  /* 15  А7-1  */
                              "N_BuyComSum",        f16,   null,  /* 16  А8    */
                              "N_BuyRegulat",       f17,   null,  /* 17  A9    */
                              "N_TGO",              f18,   null,  /* 18  A29   */
                              "N_NKDAcc",           f19,   null,  /* 19  A26   */
                              "N_NKDGot",           f20,   null,  /* 20  A27   */
                              "N_Partly",           f21,   null,  /* 21  A28   */
                              "N_SaleContrName",    f22,   null,  /* 22  А10а  */
                              "N_SaleDealDate",     f23,   null,  /* 23  A10   */
                              "N_SaleDealCode",     f24,   null,  /* 24  A11   */
                              "N_SaleDate",         f25,   null,  /* 25  A12   */
                              "N_SaleAmount",       f26,   Precision,  /* 26  A13   */
                              "N_NomS",             f27,   null,  /* 27  NomS  */
                              "N_SalePrirceCur",    f28,   null,  /* 28  A14-1 */
                              "N_SalePrirceRUR",    f29,   null,  /* 29  A14-2 */
                              "N_SaleTotalCostCur", f30,   null,  /* 30  A15   */
                              "N_SaleNKDCur",       f31,   null,  /* 31  A16   */
                              "N_SaleVCVR",         f32,   null,  /* 32  А16-1 */
                              "N_SaleComSum",       f33,   null,  /* 33  A17   */
                              "N_SaleRegulat",      f34,   null,  /* 34  A17а  */
                              "N_TotPriceSum",      f35,   null,  /* 35  A18   */
                              "N_TotNKD",           f36,   null,  /* 36  A19   */
                              "N_TotSum",           f37,   null,  /* 37  A20   */
                              "N_MaxPrice",         f38,   null,  /* 38  A21b  */
                              "N_MinPrice",         f39,   null,  /* 39  A21а  */
                              "N_MaxMarket",        f40,   null,  /* 40  A23   */
                              "N_MinMarket",        f41,   null,  /* 41  A22   */
                              "N_MaxDate",          f42,   null,  /* 42  A29   */
                              "N_MinDate",          f43,   null,  /* 43  A30   */
                              "N_DevOutlays",       f44,   null,  /* 44  А24б  */
                              "N_DevReceipts",      f45,   null,  /* 45  А24а  */
                              "N_LnkType",          f46,   null,  /* 46  А43   */
                              "N_DepS",             f47,   null,  /* 46  А43   */
                              "N_DepB",             f48,   null   /* 46  А43   */
                            );
  else
     if( m_Report.PrintMode() == DL_OUTREPORT_EXCEL )
        m_Report.merge("N_SecName", "N_BuyAmount");
     end;

     m_Report.PrintTableLine( "N_SecName",          f01,   null,  /*  1  А1    */
                              "N_BuyCostCur",       f11,   null,  /* 11  А6а   */
                              "N_BuyCostRUR",       f12,   null,  /* 12  А6б   */
                              "N_BuyNKDCur",        f13,   null,  /* 13  А7а   */
                              "N_BuyNKDRUR",        f14,   null,  /* 14  А7б   */
                              "N_BuyVCVR",          f15,   null,  /* 15  А7-1  */
                              "N_BuyComSum",        f16,   null,  /* 16  А8    */
                              "N_BuyRegulat",       f17,   null,  /* 17  A9    */
                              "N_NKDAcc",           f18,   null,  /* 18  A26   */
                              "N_NKDGot",           f19,   null,  /* 19  A27   */
                              "N_Partly",           f20,   null,  /* 20  A28   */
                              "N_SaleContrName",    f21,   null,  /* 21  А10а  */
                              "N_SaleDealDate",     f22,   null,  /* 22  A10   */
                              "N_SaleDealCode",     f23,   null,  /* 23  A11   */
                              "N_SaleDate",         f24,   null,  /* 24  A12   */
                              "N_SaleAmount",       f25,   null,  /* 25  A13   */
                              "N_NomS",             f26,   null,  /* 26  NomS  */
                              "N_SalePrirceCur",    f27,   null,  /* 27  A14-1 */
                              "N_SalePrirceRUR",    f28,   null,  /* 28  A14-2 */
                              "N_SaleTotalCostCur", f29,   null,  /* 29  A15   */
                              "N_SaleNKDCur",       f30,   null,  /* 30  A16   */
                              "N_SaleVCVR",         f31,   null,  /* 31  А16-1 */
                              "N_SaleComSum",       f32,   null,  /* 32  A17   */
                              "N_SaleRegulat",      f33,   null,  /* 33  A17а  */
                              "N_TotPriceSum",      f34,   null,  /* 34  A18   */
                              "N_TotNKD",           f35,   null,  /* 35  A19   */
                              "N_TotSum",           f36,   null,  /* 36  A20   */
                              "N_MaxPrice",         f37,   null,  /* 37  A21b  */
                              "N_MinPrice",         f38,   null,  /* 38  A21а  */
                              "N_MaxMarket",        f39,   null,  /* 39  A23   */
                              "N_MinMarket",        f40,   null,  /* 40  A22   */
                              "N_MaxDate",          f41,   null,  /* 41  A29   */
                              "N_MinDate",          f42,   null,  /* 42  A30   */
                              "N_DevOutlays",       f43,   null,  /* 43  А24б  */
                              "N_DevReceipts",      f44,   null,  /* 44  А24а  */
                              "N_LnkType",          f45,   null,  /* 45  А43   */
                              "N_DepS",             f46,   null,  /* 46  А43   */
                              "N_DepB",             f47,   null   /* 46  А43   */
                            );
  end;
end;

/* Печать итоговой строки. */
private macro PrintSummary( NumRep, Summary, RepSection, FullItog, IsGos )
   var Itog = "";
   
   macro DoPrint( Title )
      PrintTableLine( true, NumRep,
                     /*  1  А1    */ Title,
                     /*  2  А0    */ "",
                     /*  3  А1а   */ "",
                     /*  4  А1б   */ "",
                     /*  5  А2    */ "",
                     /*  6  А3    */ "",
                     /*  7  A4    */ "", "",
                     /*  8  NomB  */ "",
                     /*  9  А5а   */ "",
                     /* 10  А5б   */ "",
                     /* 11  А6а   */ "",
                     /* 12  А6б   */ Summary.Summ_Buy_RUR,
                     /* 13  А7а   */ "",
                     /* 14  А7б   */ Summary.NKD_Buy_RUR,
                     /* 15  А7-1  */ "",
                     /* 16  А8    */ Summary.Outlay_Buy,
                     /* 17  A29   */ "",
                     /* 18  A26   */ Summary.NKD_26,
                     /* 19  A27   */ Summary.NKD_27,
                     /* 20  A28   */ Summary.Partly_28,
                     /* 21  А10а  */ "",
                     /* 22  A10   */ "",
                     /* 23  A11   */ "",
                     /* 24  A12   */ "",
                     /* 25  A13   */ "",
                     /* 26  NomS  */ "",
                     /* 27  A14-1 */ "",
                     /* 28  A14-2 */ "",
                     /* 29  A15   */ Summary.Summ_Sale,
                     /* 30  A16   */ Summary.NKD_Sale,
                     /* 31  А16-1 */ "",
                     /* 32  A17   */ Summary.Outlay_Sale,
                     /* 33  A17а  */ "",
                     /* 34  A18   */ Summary.Amount,
                     /* 35  A19   */ Summary.NKD,
                     /* 36  A20   */ Summary.All,
                     /* 37  A21b  */ "",
                     /* 38  A21а  */ "",
                     /* 39  A23   */ "",
                     /* 40  A22   */ "",
                     /* 41  A29   */ "",
                     /* 42  A30   */ "",
                     /* 43  А24б  */ Summary.DevOutlays,
                     /* 44  А24а  */ Summary.DevReceipts,
                     /* 45  А43   */ "",
                                     "",
                                     "",
                                     "" );
    end;

   if( FullItog )
      DoPrint( "ВСЕГО" );
   else
      if( RepSection == REPSECTION_CIRCULATE )
        Itog = Itog1;
      elif( RepSection == REPSECTION_NOTCIRCULATE )
        Itog = Itog2;
      elif( RepSection == REPSECTION_ISSUERCORPOP )
        Itog = iif(IsGos, Itog3, Itog4);
      end;

      DoPrint( Itog );
   end;

end;

macro PrintKindOperation( RepSection, IsGos )
   var Title = "";
   if( not Data.WasPrintPartHead )

     if( m_Report.PrintMode() == DL_OUTREPORT_EXCEL )
       m_Report.merge("N_SecName", "N_LnkType");
     end;

     if( RepSection == REPSECTION_CIRCULATE )
       Title = Title1;
     elif( RepSection == REPSECTION_NOTCIRCULATE )
       Title = Title2;
     elif( RepSection == REPSECTION_ISSUERCORPOP )
       Title = iif(IsGos, Title3, Title4);
     end;

     m_Report.PrintTableLine( "N_SecName", Title, null );
     Data.WasPrintPartHead = true;
   end;
end;

private macro PrePrint( RepSection, IsGos );
   PrintKindOperation( RepSection, IsGos );
end;

private macro FI_IsAvrKindBond_AD(FIID)
   var Query;
   var select = RSDCommand("select count(1) amount " +
                            " from  dfiwarnts_dbt " +
                            "where  t_FIID = ? " + 
                            "  and  t_IsPartial = 'X'");

   select.addParam( "", RSDBP_IN, FIID );
   select.execute();

   Query = TRsbDataSet(select);
   if( Query.MoveNext() )
       if( Query.amount > 0 )
           return true;
       end;
   end;
   return false;
end;

/* найти погашеаемый купон за период */
macro GetDrawingCoupon(FIID, BegDate, EndDate, WarntDate)
  var sql, rsd;

  sql = RSDCommand("   SELECT warnt.t_DrawingDate "
                 + "     FROM dfiwarnts_dbt warnt "
                 + "    WHERE warnt.t_FIID = ? and "
                 + "          warnt.t_IsPartial != 'X' and "
                 + "          warnt.t_DrawingDate > ? and "
                 + "          warnt.t_DrawingDate < ? ");

  sql.addParam( "", RSDBP_IN, FIID );
  sql.addParam( "", RSDBP_IN, BegDate );
  sql.addParam( "", RSDBP_IN, EndDate );
  sql.execute();
    
  rsd = TRsbDataSet(sql);
  if(rsd.MoveNext())
    if( ValType(WarntDate) != V_UNDEF )
      WarntDate = SQL_ConvTypeDate(rsd.DrawingDate);
      SetParm(4, WarntDate);
    end;
    return true;
  end;

  return false;
end;

/* Расчет даты заключения сделки.
   Выводится максимальная дата изменений условий сделки, в которых изменялась цена. 
   Если таких изменений нет, то выводится дата заключения сделки */
private macro ДатаЗаклСделки(tick, leg)
  var Part,
      rsd, sql, v_break = false, v_IsLast = true,
      DealDate = tick.DealDate,
      LegPrice = ЧислоCЗаданнойТочностью(leg.Price,12),
      CurPrice;

  /* определяем часть сделки */
  if( leg.LegKind == LEG_KIND_DL_TICK )
    Part = 1;
  else
    Part = 2;
  end;

  /* перебираем все изменения условий, начиная с конца */
  sql = RSDCommand(" SELECT t_OldChangeDate, t_OldChangeKind, t_OldPrice1, t_OldPrice2 "
                 +   " FROM dsptkchng_dbt "
                 + "  WHERE t_DealID = ? "
                 + "  ORDER BY t_OldInstance DESC ");

  sql.addParam( "", RSDBP_IN, tick.DealID );
  sql.execute();

  rsd = TRsbDataSet(sql);

  while( rsd.MoveNext() and (not v_break) )
    CurPrice = ЧислоCЗаданнойТочностью(iif(Part==1,rsd.OldPrice1,rsd.OldPrice2),12);

    if( CurPrice != LegPrice )
      /* нашли изменение цены */
      if( v_IsLast )
        if( tick.ChangeKind != 4 )
          /* это "ручное" измнение, подходит */
          DealDate = tick.ChangeDate;
          v_break = true;
        else
          /* это "пересчет сумм", нужно искать дальше */
          LegPrice = CurPrice;
        end;
      else
        if( rsd.OldChangeKind != 4 )
          /* это "ручное" измнение, подходит */
          DealDate = SQL_ConvTypeDate(rsd.OldChangeDate);
          v_break = true;
        else
          /* это "пересчет сумм", нужно искать дальше */
          LegPrice = CurPrice;
        end;
      end;
    end;
    v_IsLast = false;
  end;

  /* на всякий случай */
  if( DealDate == date(0,0,0) )
    DealDate = tick.DealDate
  end;

  return DealDate;
end;

/* Печать одной строки отчета о лоте покупки и лоте продажи.
      rsd         -  выборка
      Summary     -  итоги по разделу*/

private macro PrintLine( _rsd,
                         Summary, 
                         RepSection, 
                         RepNum, IsGos
                       )
   var
      RegDeal_Buy,  RegDeal_Sale;

   var
      FaceValueFI    = fininstr.rec.FaceValueFI, /* валюта номинала */
      Buy_CFI        = -1,       /* валюта цены сделки покупки */
      Buy_Amount     = 0.0,    /* к-во ц/б в сделке покупки */
      Sale_Amount    = 0.0,
      Sale_CFI       = -1,      /* валюта цены сделки продажи */
      D              = ReportData(),
      LinkType       = _rsd.LnkType,
      BuyContrName   = "",
      SaleContrName  = "",
      ConvertToPrc   = true,
      v_КП           = 0.0,
      v_КК           = 0.0,
      NomB           = 0.0, 
      NomS           = 0.0, 
      Дв             = ZeroDate, 
      Дкуп           = ZeroDate, 
      PriceB         = 0.0, 
      PriceS         = 0.0,
      LinkTypeStr    = "",
      K              = 0.0;

   var FDBuy    = null,
       FDSale   = null;
   var BuyDeal    = TRecHandler("dl_tick"),
       SaleDeal   = TRecHandler("dl_tick");

   var rsd, sql;

   var InterDepend_S = "", InterDepend_B = "";
   var NomdateSale = Date(0,0,0);
   /* Получаем затраты, связанные с реализацией или приобретением.
      ТЗ: Комиссии включаются в сумму затрат, только если они оплачены.
         FD          - FirstDoc
         CourseDate  - дата, по курсу на которую переводим сумму в рубли */
   macro ЗатратыСвязанныеСПриобрРеализ( FD, CourseDate )

      /* Получить предварительные затраты для лота по сделке. Для сделок
         из двух частей считаем, что предварительные затраты относятся к
         только к лоту по первой части.
         Предварительные затраты хранятся всегда в рублях. */
      macro GetPreOutlay( FD )
         if( GetLegKindByLotDeal(FD.pmwrtsum.rec, FD.tick.rec) == LEG_KIND_DL_TICK )
            return FD.tick.rec.PreOutlay;
         else
            return $0;
         end;
      end;

      var
         DivSummAgent = $0, DivSummBank = $0, cmd;

      /* комисии посреднику и регистрационный сбор.
         Суммы переводим в рубли на
         дату фактическую дату оплаты комиссии.*/
      VAR sum_agent = $0, nds_agent = $0;                                                              

      /*вообще, если не ошибаюсь, сюда приходят сделки только из одной части, но на всякий случай для 2 ч регсбор имеем возможность брать*/
      SP_GetSumCom( sum_agent, nds_agent, null, null,
                    FD.tick.rec.BofficeKind, FD.tick.rec.DealID, null, null, null, 0, 1,   
                    1, 0, 1, 1, null, NATCUR, true, IIF(GetLegKindByLotDeal(FD.pmwrtsum.rec, FD.tick.rec) == LEG_KIND_DL_TICK,true,false),
                    IIF(GetLegKindByLotDeal(FD.pmwrtsum.rec, FD.tick.rec) == LEG_KIND_DL_TICK_BACK,true,false)
                  );

      /* Распределенные оплаченные комисси */
      ПолучитьСуммуРаспределенныхКомиссийПоСделке(
            FD.tick.rec, DivSummAgent, null, DivSummBank, null,
            null, null, NATCUR, CourseDate, 1 );

      if(FD.tick.rec.BOfficeKind == DL_AVRWRT)
      
        sql = "SELECT t_sum FROM ddlsum_dbt WHERE t_dockind = " + FD.tick.rec.BOfficeKind + 
              " AND t_docid = " + FD.tick.rec.DealID + " AND t_kind = 1100";    /* затраты по зачислению */
        cmd = TrsbDataSet(sql);
        if(cmd.movenext())
           DivSummBank = DivSummBank + DoubleToMoney(cmd.t_sum);
        end;
      end;

      return   GetPreOutlay(FD)
               + sum_agent
               + DivSummAgent + DivSummBank;
   end;

   macro ConvMPriceToRUR(CFI:integer, PaymentID:integer, MarketPrice:double, DateMarket:date)
     var Curs = "";
     var MPrice = MarketPrice;
   
     if( FaceValueFI == NATCUR )
        if( CFI != NATCUR )
           Curs = readNoteForObject( OBJTYPE_DLRQ, L_Z( PaymentID, 10 ), 44 );
           /*если примечание было задано, то в самой ХП уже конвертнули*/
           if( (ValType(Curs) == V_UNDEF) or (Curs == "") or (Curs <= 0.) )
              /*из валюты цены переводим в рубли*/
              SmartConvertSumDbl(MPrice, MPrice, DateMarket, CFI, NATCUR, false);
           end;
        end;
     else
        /*из валюты номинала переводим в рубли*/
        SmartConvertSumDbl(MPrice, MPrice, DateMarket, FaceValueFI, NATCUR, false);
     end;
   
     return MPrice;
   end;

   GetDealByID( _rsd.buyDealID, false, false, BuyDeal );
   FDBuy  = SPFirstDoc( BuyDeal, IsBackExec(BuyDeal.rec, IIF(_rsd.buyType==TXLOTS_BUY, SP_EXECUTE_STEP_BUY, SP_EXECUTE_STEP_SALE)) );
   Buy_CFI = FDBuy.dl_leg.rec.CFI;
   Buy_Amount = FDBuy.dl_leg.rec.Principal;

   GetDealByID( _rsd.saleDealID, false, false, SaleDeal );
   FDSale = SPFirstDoc( SaleDeal, IsBackExec(SaleDeal.rec, IIF(_rsd.saleType==TXLOTS_SALE, SP_EXECUTE_STEP_SALE, SP_EXECUTE_STEP_BUY)) );
   Sale_CFI = FDSale.dl_leg.rec.CFI;
   Sale_Amount = FDSale.dl_leg.rec.Principal;

   //A29    Участие в действиях эмитента
   if(_rsd.BuyOrigin != TXLOTORIGIN_DEAL)
     D.OriginName = DL_GetNameAlg( ALG_SCTX_LOTORIGIN, _rsd.BuyOrigin );
   end;;

   /* A15 - Дата реализации ц/б */
   /* A6 - Количество, шт. */
   D.Date_Sale   = SQL_ConvTypeDate(_rsd.saleDate);
   D.Amount_Sale = D.Amount_Buy = money(_rsd.Amount);

   /* Информацию в раздел "приобретение" выводим */

   /* A4 - № договора */
   D.SfContr_Buy = IIF(Debug_ShowInnerDealCode, _rsd.BuyDealCode, _rsd.BuyDealCodeTS);

   /* A5 - дата приобретения */
   D.Date_Buy        = SQL_ConvTypeDate(_rsd.buyDate);

   InterDepend_B = "";
   InterDepend_S = "";

   BuyContrName = T_PARTY.Get_Party(GetContrInDeal(FDBuy.tick.rec),@InterDepend_B);

   if( GetContrInDeal(FDBuy.tick.rec) == GetContrInDeal(FDSale.tick.rec) )
      SaleContrName = BuyContrName;
      InterDepend_S = InterDepend_B;
   else
      SaleContrName = T_PARTY.Get_Party(GetContrInDeal(FDSale.tick.rec),@InterDepend_S);
   end;

   D.DealDate_Buy = ДатаЗаклСделки(FDBuy.tick.rec, FDBuy.dl_leg.rec);

   //NomB
   if( (NomOnDateBuy.FIID == fininstr.rec.FIID) and (NomOnDateBuy.OnDate == D.Date_Buy) )
      NomB = NomOnDateBuy.Nominal;
   else
      NomB = GetFaceValue( fininstr.rec.FIID, D.Date_Buy, true, false );
      NomOnDateBuy = FiidNomOnDate(fininstr.rec.FIID,D.Date_Buy,NomB);
   end;

   //А6а
   if(_rsd.BuyOrigin == TXLOTORIGIN_GLOBCONVERT)
     if (Buy_CFI != NATCUR)
       //_rsd.BuyCost = Стоимость без НКД в ВЦ
       D.Summ_Buy_VAL = _rsd.BuyCost/_rsd.buyAmount * D.Amount_Buy;
     end;
   else
     if (Buy_CFI != NATCUR)
       if(_rsd.BuyOrigin == TXLOTORIGIN_DEAL)
         K = FDBuy.dl_leg.rec.Principal;
       else
         K = _rsd.buyAmount;
       end;
       D.Summ_Buy_VAL = FDBuy.dl_leg.rec.Cost / K * D.Amount_Buy;
     end;
   end;

   //А6б
   if(_rsd.BuyOrigin == TXLOTORIGIN_GLOBCONVERT)
     if (Buy_CFI == NATCUR)
       //_rsd.BuyCost = Стоимость без НКД в ВЦ
       D.Summ_Buy_RUR = _rsd.BuyCost/_rsd.buyAmount * D.Amount_Buy;
     else
       SmartConvertSumDbl( D.Summ_Buy_RUR, D.Summ_Buy_VAL, D.Date_Buy,
                           Buy_CFI, NATCUR, false );
     end; 
   else
     if(_rsd.BuyOrigin == TXLOTORIGIN_DEAL)
       K = FDBuy.dl_leg.rec.Principal;
     else
       K = _rsd.buyAmount;
     end;

     if (Buy_CFI == NATCUR)
        D.Summ_Buy_RUR = FDBuy.dl_leg.rec.Cost / K * D.Amount_Buy;
     else
        SmartConvertSumDbl( D.Summ_Buy_RUR, D.Summ_Buy_VAL, IIF(D.Date_Buy > Date67, D.Date_Buy, Date67),
                            Buy_CFI, NATCUR, false );
     end;
   end;

   //А5а
   if(_rsd.BuyOrigin == TXLOTORIGIN_GLOBCONVERT)
     //_rsd.BuyCost = Стоимость без НКД в ВЦ
     if( Data.IsBond )
       D.dblPrice_Buy_VAL = _rsd.BuyCost/(_rsd.buyAmount*NomB) * 100;
       D.strPrice_Buy_VAL_Print = StrSubst(string(D.dblPrice_Buy_VAL:0:4), ".", ",");
     else
       D.dblPrice_Buy_VAL = _rsd.BuyCost/_rsd.buyAmount;
       D.strPrice_Buy_VAL_Print = StrSubst(string(D.dblPrice_Buy_VAL:0:4), ".", ",");
     end;
   else
     if( Data.IsShare )
        if(Buy_CFI != NATCUR)
           D.dblPrice_Buy_VAL = FDBuy.dl_leg.rec.Price;
           D.strPrice_Buy_VAL_Print = StrSubst(string(D.dblPrice_Buy_VAL:0:4), ".", ",");
        end;
     elif( Data.IsBond )
        ConvertToPrc = true;
        D.dblPrice_Buy_VAL = FDBuy.dl_leg.rec.Price;
        if( IsRelativePrice( FDBuy.tick.rec, FDBuy.dl_leg.rec ) )
           ConvertToPrc = false;
        end;

        if(ConvertToPrc)
           if(FaceValueFI != Buy_CFI)
              SmartConvertSumDbl( D.dblPrice_Buy_VAL, D.dblPrice_Buy_VAL, IIF(D.Date_Buy > Date67, D.Date_Buy, Date67),
                                  Buy_CFI, FaceValueFI, false );
           end;
         
           if( NomB != 0.0 )
              D.dblPrice_Buy_VAL = D.dblPrice_Buy_VAL / NomB * 100.0;
           end;
        end;

        D.strPrice_Buy_VAL_Print = StrSubst(string(D.dblPrice_Buy_VAL:0:4), ".", ",");
     end;
   end;

   //А5б
   if(_rsd.BuyOrigin == TXLOTORIGIN_DEAL)
     D.dblPrice_Buy_RUR = FDBuy.dl_leg.rec.Price;
     if( IsRelativePrice( FDBuy.tick.rec, FDBuy.dl_leg.rec ) )
       D.dblPrice_Buy_RUR = D.dblPrice_Buy_RUR / 100.0 * NomB;
     end;

     if( Buy_CFI != NATCUR )
        if(FaceValueFI == NATCUR)
           SmartConvertSumDbl( D.dblPrice_Buy_RUR, D.dblPrice_Buy_RUR, D.Date_Buy,
                               Buy_CFI, NATCUR, false );
        else
           SmartConvertSumDbl( D.dblPrice_Buy_RUR, D.dblPrice_Buy_RUR, IIF(D.Date_Buy > Date67, D.Date_Buy, Date67),
                               Buy_CFI, NATCUR, false );
        end;
     end;
   elif(_rsd.BuyOrigin == TXLOTORIGIN_GLOBCONVERT)
     //_rsd.BuyCost = Стоимость без НКД в ВЦ
     D.dblPrice_Buy_RUR = _rsd.BuyCost/(_rsd.buyAmount);
     SmartConvertSumDbl( D.dblPrice_Buy_RUR, D.dblPrice_Buy_RUR, D.Date_Buy,
                         Buy_CFI, NATCUR, false );
   elif(_rsd.BuyOrigin == TXLOTORIGIN_MODIFFACEVALUE)
     D.dblPrice_Buy_RUR = D.Summ_Buy_RUR/_rsd.buyAmount;
   end;
   D.strPrice_Buy_RUR_Print = string(D.dblPrice_Buy_RUR);


   //А7а, А7б
   if( Data.IsCoupAvoir )
      if ((LinkType == TXLNK_DELIVER) AND 
          (D.Date_Buy < Data.BegDate) AND
          (GetDrawingCoupon(fininstr.rec.FIID, D.Date_Buy, date(Data.BegDate)) ) 
         )
         D.NKD_Buy_VAL = $0;
         D.NKD_Buy_RUR = $0;
      else
         if (FaceValueFI != NATCUR)
            if(_rsd.BuyOrigin != TXLOTORIGIN_DEAL)
              SmartConvertSumDbl( D.NKD_Buy_VAL, _rsd.BuyNKD /*в ВН*/, D.Amount_Buy,
                                  FaceValueFI, Buy_CFI, false );

              SmartConvertSumDbl( D.NKD_Buy_RUR, D.NKD_Buy_VAL, D.Amount_Buy,
                                  Buy_CFI, NATCUR, false );
            else
              D.NKD_Buy_VAL = FDBuy.dl_leg.rec.NKD / FDBuy.dl_leg.rec.Principal * D.Amount_Buy;
              SmartConvertSumDbl( D.NKD_Buy_RUR, D.NKD_Buy_VAL, IIF(D.Date_Buy > Date67, D.Date_Buy, Date67),
                                  FaceValueFI, NATCUR, false );
            end;
         else
            D.NKD_Buy_RUR = FDBuy.dl_leg.rec.NKD / FDBuy.dl_leg.rec.Principal * D.Amount_Buy;

         end;
      end;
   end;

   /* А8 - затраты, связанные с приобретением */
   if(_rsd.BuyOrigin == TXLOTORIGIN_DEAL)
     D.Outlay_Buy = ЗатратыСвязанныеСПриобрРеализ(FDBuy, D.Date_Buy) / FDBuy.dl_leg.rec.Principal * D.Amount_Buy;
   end;

   /* A9, A17а - Если примечание вида "Урегулирование сделки" для сделки 
                покупки заполнено, то выводится значок "V". 
                Если примечание не заполнено, то поле не заполняется.*/
   if( readNoteForObject(OBJTYPE_SECDEAL, UniID(FDBuy.tick,OBJTYPE_SECDEAL), NOTEKIND_SECDEAL_REG_DEAL) )
     RegDeal_Buy = "V";
   else
     RegDeal_Buy = "";
   end;

   if( readNoteForObject(OBJTYPE_SECDEAL, UniID(FDSale.tick,OBJTYPE_SECDEAL), NOTEKIND_SECDEAL_REG_DEAL) )
     RegDeal_Sale = "V";
   else
     RegDeal_Sale = "";
   end;

   /*ВЫПЛАТЫ ОТ ЭМИТЕНТА*/

   /*A26*/
   if( Data.IsCoupAvoir and (D.Date_Buy < Data.BegDate) ) 

      sql = RSDCommand("   SELECT warnt.t_FirstDate "
                     + "     FROM dfiwarnts_dbt warnt "
                     + "    WHERE warnt.t_FIID = ? and "
                     + "          warnt.t_IsPartial != 'X' and "
                     + "          warnt.t_FirstDate <= ? and "
                     + "          warnt.t_DrawingDate >= ? ");

      sql.addParam( "", RSDBP_IN, fininstr.rec.FIID );
      sql.addParam( "", RSDBP_IN, Data.BegDate-1 );
      sql.addParam( "", RSDBP_IN, Data.BegDate );
      sql.execute();

      rsd = TRsbDataSet(sql);
      if(rsd.MoveNext())
         if( ValType(rsd.FirstDate) != V_UNDEF )
           Дкуп = SQL_ConvTypeDate(rsd.FirstDate) - 1;
         else
           Дкуп = date(1,1,1900);
         end;
      else
         Дкуп = date(1,1,1900);
      end;

      if (LinkType == TXLNK_DELIVER)
         Дв = maxDate(Дкуп, D.Date_Buy);
      else
         Дв = maxDate(Дкуп, D.Date_Sale);
      end;

      D.NKD_26 = НКД(fininstr.rec.FIID, D.Amount_Buy, Data.BegDate-1) - 
                 НКД(fininstr.rec.FIID, D.Amount_Buy, Дв);
      if (FaceValueFI != NATCUR)
         SmartConvertSumDbl( D.NKD_26, D.NKD_26, Data.BegDate-1,
                             FaceValueFI, NATCUR, false );
      end;

   end;

   /*A27*/
   if( Data.IsCoupAvoir ) 
      D.NKD_27 = GetCouponSumByPeriod_Rub( fininstr.rec.FIID, D.Amount_Buy, 
                                           IIF(LinkType == TXLNK_DELIVER, max(Data.BegDate, D.Date_Buy+1), max(Data.BegDate, D.Date_Sale+1)), 
                                           IIF(LinkType == TXLNK_DELIVER, D.Date_Sale, D.Date_Buy), 
                                           FaceValueFI, null, fininstr.rec.DrawingDate );
   end;

   /*A28*/
   if (Data.IsAvrKindBond_AD)
      if (LinkType == TXLNK_DELIVER)
         D.Partly_28 = GetPartialSumByPeriod_Rub( fininstr.rec.FIID, D.Amount_Buy, D.Date_Buy+1, D.Date_Sale,
                                                  null, fininstr.rec.DrawingDate );
      else
         D.Partly_28 = GetPartialSumByPeriod_Rub( fininstr.rec.FIID, D.Amount_Buy, D.Date_Sale+1, D.Date_Buy,
                                                  null, fininstr.rec.DrawingDate );
      end;
   end;

   /* Информацию в раздел "реализация" выводим */

   /* A13 - дата заключения */
   /* Берем не FDSale.DateArray[DATE_DEALDATE], а dl_tick.DealDate.
      Т.к. они могут быть не равны, когда dl_tick.DealDate приходится на
      выходной. */
   D.DealDate_Sale = ДатаЗаклСделки(FDSale.tick.rec, FDSale.dl_leg.rec);

   /* A11 - № договора */
   D.SfContr_Sale = IIF(Debug_ShowInnerDealCode, _rsd.SaleDealCode, _rsd.SaleDealCodeTS);

   //NomS
   if(_rsd.SaleOrigin != TXLOTORIGIN_MODIFFACEVALUE)
      NomdateSale = D.Date_Sale;
   else
      NomdateSale = D.Date_Sale-1;
   end;

   if( (NomOnDateSale.FIID == fininstr.rec.FIID) and (NomOnDateSale.OnDate == NomdateSale) )
      NomS = NomOnDateSale.Nominal;
   elif( (NomOnDateBuy.FIID == fininstr.rec.FIID) and (NomOnDateBuy.OnDate == NomdateSale) )
      NomS = NomOnDateBuy.Nominal;
   else
      NomS = GetFaceValue( fininstr.rec.FIID, NomdateSale, true, false );
      NomOnDateSale = FiidNomOnDate(fininstr.rec.FIID,NomdateSale,NomS);
   end;

   if(_rsd.SaleOrigin  != TXLOTORIGIN_DEAL)
     D.strPrice_SaleVal_Print = D.strPrice_Buy_VAL_Print;
     D.dblPrice_Sale_Print    = D.strPrice_Buy_RUR_Print;
   else
     if( Data.IsShare )
        if(Sale_CFI != NATCUR)
           D.dblPrice_Sale = FDSale.dl_leg.rec.Price;
           D.strPrice_SaleVal_Print = StrSubst(string(D.dblPrice_Sale:0:4), ".", ",");
        end;
     elif( Data.IsBond )
        ConvertToPrc = true;
        D.dblPrice_Sale = FDSale.dl_leg.rec.Price;
        if( IsRelativePrice(FDSale.tick.rec, FDSale.dl_leg.rec) )
           ConvertToPrc = false;
        end;

        if( ConvertToPrc )
           if(FaceValueFI != Sale_CFI)
              SmartConvertSumDbl( D.dblPrice_Sale, D.dblPrice_Sale, D.Date_Sale,
                                  Sale_CFI, FaceValueFI, false );
           end;
           
           if( NomS != 0.0 )
              D.dblPrice_Sale = D.dblPrice_Sale / NomS * 100.0;
           end;
        end;
                                    
        D.strPrice_SaleVal_Print = StrSubst(string(D.dblPrice_Sale:0:4), ".", ",");
     end;

     D.dblPrice_Sale_Print = FDSale.dl_leg.rec.Price;
     if( IsRelativePrice(FDSale.tick.rec, FDSale.dl_leg.rec) )
        D.dblPrice_Sale_Print = D.dblPrice_Sale_Print / 100 * NomS;
     end;

     if( Sale_CFI != NATCUR )
        SmartConvertSumDbl( D.dblPrice_Sale_Print, D.dblPrice_Sale_Print, D.Date_Sale ,
                            Sale_CFI, NATCUR, false);
     end;
   end;

   /* A15 */
   if(_rsd.SaleOrigin != TXLOTORIGIN_DEAL)
     D.Summ_Sale = D.Summ_Buy_RUR;
   else
     D.Summ_Sale = FDSale.dl_leg.rec.Cost / FDSale.dl_leg.rec.Principal * D.Amount_Sale;
     if (Sale_CFI != NATCUR)
        SmartConvertSumDbl( D.Summ_Sale, D.Summ_Sale, D.Date_Sale,
                            Sale_CFI, NATCUR, false );
     end;
   end;

   /* A16 */
   if(_rsd.SaleOrigin == TXLOTORIGIN_DEAL)
     if( Data.IsCoupAvoir )
        if (((LinkType == TXLNK_CLSREPO) or (LinkType == TXLNK_CLSLOAN)) AND 
            (D.Date_Sale < Data.BegDate) AND
            (GetDrawingCoupon(fininstr.rec.FIID, D.Date_Sale, date(Data.BegDate)) ) 
           )
           D.NKD_Sale = $0;
        else

           D.NKD_Sale = FDSale.dl_leg.rec.NKD / FDSale.dl_leg.rec.Principal * D.Amount_Sale;
           /*по ограничениям реализации ТЗ валюта НКД должно быть == или валюте цены или (если валюта цены выражена в % номинала) валюте номинала*/
           if ( (D.NKD_Sale!=0.0) and (FDSale.dl_leg.rec.NKDFIID != NATCUR) )
               SmartConvertSumDbl( D.NKD_Sale, D.NKD_Sale, D.Date_Sale/*A12*/,
                                   FDSale.dl_leg.rec.NKDFIID, NATCUR, false );
           end;

           /*Если сумма купона в операции погашения равна нулю, то еще плюс <A4>*(Купон, выплата которого равна дате операции погашения  в рублях по курсу на дату выплаты купона.*/                                                      
           if( (FDSale.tick.rec.BofficeKind == DL_RETIREMENT) and (FDSale.dl_leg.rec.NKD == $0) )
              D.NKD_Sale = D.Amount_Buy * GetCouponSumByPeriod_Rub( fininstr.rec.FIID, 1, 
                                                                    FDSale.tick.rec.DealDate, 
                                                                    FDSale.tick.rec.DealDate );
           end;

        end;
     end;
   else
     //НКД по анкете ц/б на дату <А12> по количеству <А4>
     D.NKD_Sale = НКД(fininstr.rec.FIID, D.Amount_Buy/*A4*/, D.Date_Sale/*A12*/);
     if (FaceValueFI != NATCUR)
         SmartConvertSumDbl( D.NKD_Sale, D.NKD_Sale, D.Date_Sale/*A12*/,
                             FaceValueFI, NATCUR, false );
     end;
   end;

   /* A17 - затраты, связанные с реализацией ц/б */
   if(_rsd.SaleOrigin == TXLOTORIGIN_DEAL)
     D.Outlay_Sale = ЗатратыСвязанныеСПриобрРеализ(FDSale, D.Date_Sale) / FDSale.dl_leg.rec.Principal * D.Amount_Sale;
   end;

   /*ИТОГИ*/

   /* A18 - стоимость */
   /* A19 - НКД */
   /* A20 - Всего */
   if(LinkType != TXLNK_DELIVER)
     D.NKD_27    = -D.NKD_27;
     D.Partly_28 = -D.Partly_28;
   end;

   D.Amount = D.Summ_Sale + D.Partly_28 - D.Outlay_Buy - D.Outlay_Sale - D.Summ_Buy_RUR;
   if ( ((LinkType == TXLNK_DELIVER) and (D.Date_Buy < Data.BegDate)) or 
        ((LinkType != TXLNK_DELIVER) and (D.Date_Sale < Data.BegDate)) 
      )

      D.NKD = D.NKD_Sale + D.NKD_27 - D.NKD_Buy_RUR;

      if ( LinkType == TXLNK_DELIVER)
         D.NKD = D.NKD - D.NKD_26;
      else
         D.NKD = D.NKD + D.NKD_26;
      end;

   else
      D.NKD = D.NKD_Sale - D.NKD_Buy_RUR + D.NKD_27;
   end;

   D.All    = D.Amount + D.NKD;

   /* А24а, А24б  - сумма отклонения фактической выручки от реализ. ниже рын. цены */
   if( Data.IsShare )
      v_КП = 1.0;
      v_КК = 1.0;
   elif( Data.IsBond )
      if( fininstr.rec.FaceValueFI != NATCUR ) 
         SmartConvertSumDbl( v_КП, NomS / 100, D.Date_Sale, fininstr.rec.FaceValueFI, NATCUR, false);
         SmartConvertSumDbl( v_КК, NomB / 100, D.Date_Buy, fininstr.rec.FaceValueFI, NATCUR, false);
      else
         v_КП = NomS / 100;
         v_КК = NomB / 100;
      end;
   end;

   if( Data.IsShare )
      if( fininstr.rec.FaceValueFI == NATCUR ) 
         PriceB = D.dblPrice_Buy_RUR;
         PriceS = D.dblPrice_Sale_Print;
      else
         SmartConvertSumDbl( PriceB, D.dblPrice_Buy_VAL, D.DealDate_Buy, Buy_CFI, NATCUR, false);
         SmartConvertSumDbl( PriceS, D.dblPrice_Sale, D.DealDate_Sale, Sale_CFI, NATCUR, false);
      end;

   elif( Data.IsBond )
      PriceB = D.dblPrice_Buy_VAL;
      PriceS = D.dblPrice_Sale;
   end;

   D.DevOutlays = $0;
   D.DevReceipts = $0;
   /*Если поле A23 = "факт", т.е. в качестве максимальной цены в контрольном интервале 
     необ-ходимо брать цену приобретения в рублях,  то в поле выводим значение А5б.*/
   if( _rsd.BuyMarket == "факт" )/*отклонений в этом случае нет*/
      _rsd.BuyMarketPrice = D.dblPrice_Buy_RUR;
   else
      /*Для акций, деп. Расписок и паев при необходимости курс ценной бумаги переводится в рубли, 
        по курсу на дату заключения сделки покупки.*/
      if( Data.IsShare )
         _rsd.BuyMarketPrice = ConvMPriceToRUR(Buy_CFI,_rsd.BuyPmID,_rsd.BuyMarketPrice,SQL_ConvTypeDate(_rsd.BuyDateMarket));
      end;

      if( PriceB > SQL_ConvTypeSum(_rsd.BuyMarketPrice) )
         D.DevOutlays = money( (PriceB - SQL_ConvTypeSum(_rsd.BuyMarketPrice)) * D.Amount_Buy * v_КК );
      end;
   end;

   if( _rsd.SaleMarket == "факт" )/*отклонений в этом случае нет*/
      _rsd.SaleMarketPrice = D.dblPrice_Sale_Print;
   else
      /*Для акций, деп. Расписок и паев при необходимости курс ценной бумаги переводится в рубли, 
        по курсу на дату заключения сделки продажи.*/
      if( Data.IsShare )
         _rsd.SaleMarketPrice = ConvMPriceToRUR(Sale_CFI,_rsd.SalePmID,_rsd.SaleMarketPrice,SQL_ConvTypeDate(_rsd.SaleDateMarket));
      end;
 
      if( PriceS < SQL_ConvTypeSum(_rsd.SaleMarketPrice) ) 
         D.DevReceipts = money( (SQL_ConvTypeSum(_rsd.SaleMarketPrice) - PriceS) * D.Amount_Sale * v_КП );
      end;
   end;

   /*А43*/
   LinkTypeStr = "";
   if (LinkType == TXLNK_CLSREPO)
      LinkTypeStr = "ЗКПР";

   elif (LinkType == TXLNK_CLSLOAN)
      LinkTypeStr = "ЗКПК";
   end;

   var КонтрольныйИнтервалЦенМакс = iif(_rsd.BuyOrigin == TXLOTORIGIN_DEAL, SQL_ConvTypeSum(_rsd.BuyMarketPrice), "");
   var КонтрольныйИнтервалЦенМин  = iif(_rsd.SaleOrigin == TXLOTORIGIN_DEAL, SQL_ConvTypeSum(_rsd.SaleMarketPrice), ""); 
   КонтрольныйИнтервалЦенМакс = StrSubst(string(КонтрольныйИнтервалЦенМакс:0:4), ".", ",");
   КонтрольныйИнтервалЦенМин  = StrSubst(string(КонтрольныйИнтервалЦенМин:0:4), ".", ",");
   if(Data.IsBond)
     КонтрольныйИнтервалЦенМакс = IIF( КонтрольныйИнтервалЦенМакс != "", КонтрольныйИнтервалЦенМакс + "%" , "" );
     КонтрольныйИнтервалЦенМин  = IIF( КонтрольныйИнтервалЦенМин  != "", КонтрольныйИнтервалЦенМин  + "%" , "" );
   end;

   PrePrint( RepSection, IsGos );
   PrintTableLine(false, RepNum,
                  /*  1  А1    */ fininstr.rec.Name,
                  /*  2  А0    */ T_ISO.Get_ISO(fininstr.rec.FaceValueFI),
                  /*  3  А1а   */ BuyContrName,
                  /*  4  А1б   */ iif(_rsd.BuyOrigin == TXLOTORIGIN_DEAL, date_as_string(1, D.DealDate_Buy), ""),
                  /*  5  А2    */ D.SfContr_Buy,
                  /*  6  А3    */ date_as_string(1,D.Date_Buy),
                  /*  7  A4    */ D.Amount_Buy, fininstr.rec.SumPrecision,
                  /*  8  NomB  */ NomB,
                  /*  9  А5а   */ D.strPrice_Buy_VAL_Print,
                  /* 10  А5б   */ D.strPrice_Buy_RUR_Print,
                  /* 11  А6а   */ D.Summ_Buy_VAL,
                  /* 12  А6б   */ D.Summ_Buy_RUR,
                  /* 13  А7а   */ D.NKD_Buy_VAL,
                  /* 14  А7б   */ D.NKD_Buy_RUR,
                  /* 15  А7-1  */ T_ISO.Get_ISO(Buy_CFI) + "/" + T_ISO.Get_ISO(FDBuy.dl_leg.rec.PayFIID),
                  /* 16  А8    */ D.Outlay_Buy,
                  /* 17  A9    */ RegDeal_Buy,
                  /* 18  A29   */ D.OriginName,
                  /* 19  A26   */ D.NKD_26,
                  /* 20  A27   */ D.NKD_27,
                  /* 21  A28   */ D.Partly_28,
                  /* 22  А10а  */ SaleContrName,
                  /* 23  A10   */ iif(_rsd.SaleOrigin == TXLOTORIGIN_DEAL, date_as_string(1,D.DealDate_Sale), ""),
                  /* 24  A11   */ D.SfContr_Sale,
                  /* 25  A12   */ date_as_string(1,D.Date_Sale),
                  /* 26  A13   */ D.Amount_Sale,
                  /* 27  NomS  */ NomS,
                  /* 28  A14-1 */ D.strPrice_SaleVal_Print,
                  /* 29  A14-2 */ D.dblPrice_Sale_Print,
                  /* 30  A15   */ D.Summ_Sale,
                  /* 31  A16   */ D.NKD_Sale,
                  /* 32  А16-1 */ iif(_rsd.SaleOrigin == TXLOTORIGIN_DEAL, (T_ISO.Get_ISO(Sale_CFI) + "/" + T_ISO.Get_ISO(FDSale.dl_leg.rec.PayFIID)), (T_ISO.Get_ISO(Buy_CFI) + "/" + T_ISO.Get_ISO(FDBuy.dl_leg.rec.PayFIID))),
                  /* 33  A17   */ D.Outlay_Sale,
                  /* 34  A17а  */ RegDeal_Sale,
                  /* 35  A18   */ D.Amount,
                  /* 36  A19   */ D.NKD,
                  /* 37  A20   */ D.All,
                  /* 38  A21b  */ КонтрольныйИнтервалЦенМакс,
                  /* 39  A21а  */ КонтрольныйИнтервалЦенМин,
                  /* 40  A23   */ iif(_rsd.BuyOrigin == TXLOTORIGIN_DEAL, _rsd.BuyMarket, ""),
                  /* 41  A22   */ iif(_rsd.SaleOrigin == TXLOTORIGIN_DEAL, _rsd.SaleMarket, ""),
                  /* 42  A29   */ iif(_rsd.BuyOrigin == TXLOTORIGIN_DEAL, SQL_ConvTypeDate(_rsd.BuyDateMarket), ""),
                  /* 43  A30   */ iif(_rsd.SaleOrigin == TXLOTORIGIN_DEAL, SQL_ConvTypeDate(_rsd.SaleDateMarket), ""),
                  /* 44  А24б  */ iif(_rsd.BuyOrigin == TXLOTORIGIN_DEAL, D.DevOutlays, ""),
                  /* 45  А24а  */ iif(_rsd.SaleOrigin == TXLOTORIGIN_DEAL, D.DevReceipts, ""),
                  /* 46  А43   */ LinkTypeStr,
                                  InterDepend_S,
                                  InterDepend_B
               );

   /* Формируем итоговые результаты */
   Summary.Add( D );

   Data.SetWasPrintLot;

   return true;
end;

PRIVATE MACRO Get_str_PaymDate(Type, DealPart, str)
     var sql_PlanDate:String = 
        " (NVL( (SELECT min(dlrq.t_PlanDate) " +
        "          FROM ddlrq_dbt dlrq, ddl_tick_dbt Deal " + 
        "         WHERE Deal.t_DealID = "+str+".t_DealID " +
        "          AND dlrq.t_DocKind    = Deal.t_BOfficeKind " +
        "          AND dlrq.t_DocID = Deal.t_DealID " +
        "          AND dlrq.t_Type    = " + string(Type) + 
        "          AND dlrq.t_DealPart = " + string(DealPart) + 
        "          AND dlrq.t_FactDate = TO_DATE('01-01-0001','DD-MM-YYYY') " +
        "       ), TO_DATE('01-01-0001','DD-MM-YYYY') ) " +
        " ) ";

     var sql_FactDate:String = 
        " (NVL( (SELECT min(dlrq.t_FactDate) " +
        "          FROM ddlrq_dbt dlrq, ddl_tick_dbt Deal " + 
        "         WHERE Deal.t_DealID = "+str+".t_DealID " +
        "           AND dlrq.t_DocKind    = Deal.t_BOfficeKind " +
        "           AND dlrq.t_DocID = Deal.t_DealID " +
        "           AND dlrq.t_Type    = " + string(Type) + 
        "           AND dlrq.t_DealPart    = " + string(DealPart) + 
        "           AND dlrq.t_State = " + string(DLRQ_STATE_EXEC) +
        "           AND dlrq.t_FactDate > TO_DATE('01-01-0001','DD-MM-YYYY') " +
        "       ), TO_DATE('01-01-0001','DD-MM-YYYY') ) " +
        " ) ";

     return 
        " (DECODE( " +
             sql_FactDate + ", " +                   // Выражение
        "    TO_DATE('01-01-0001','DD-MM-YYYY'), " + // search1
             sql_PlanDate + ", " +                   // result1
             sql_FactDate + ") " +                   // default
        " ) ";
END;

/* Перебор обращающихся или не обращающихся на ОРЦБ бумаг и печать
   отчета.
      AllSummary  -  класс для сбора итогов */
private macro ПереборБумагИПечать( RepSection, AllSummary, RepNum )
   var
      Summary     = SummaryData(),
      Progress    = TProgressBar;
   var title= "";
   var oldName = "";
   var AddWhere = "";
   var i = 0;
   var ProgressValue = CTxProgressValue();
 
   var sql, sql_count, sql_sel, iCount, rsd,  rsd_sql_count, rsd_sql_sel, str_TypeLnk = "", PrevFIID;

   Data.AfterPrintNewPart();

   if (Data.LnkBuySale and Data.LnkCloseShortPos)
      str_TypeLnk = " lnk.t_Type IN (" + TXLNK_DELIVER + ", " + TXLNK_CLSREPO + ", " + TXLNK_CLSLOAN + ") and ";

   elif (Data.LnkBuySale and (not Data.LnkCloseShortPos))
      str_TypeLnk = " lnk.t_Type = " + TXLNK_DELIVER + " and ";

   elif ((not Data.LnkBuySale) and Data.LnkCloseShortPos)
      str_TypeLnk = " lnk.t_Type IN (" + TXLNK_CLSREPO + ", " + TXLNK_CLSLOAN + ") and ";

   else
      str_TypeLnk = " 0 = 1 and ";
   end;

   /* перебор налоговых связей */
   sql_count = " SELECT count(1) iCount ";

   sql_sel = " SELECT sale.t_FIID, sale.t_Type saleType, sale.t_Amount saleAmount, buy.t_Origin as BuyOrigin, sale.t_Origin as SaleOrigin,"
           +        " sale.t_DealID saleDealID, sale.t_ID saleID, sale.t_DealCode saleDealCode, buy.t_GoID BuyGoID, sale.t_GoID SaleGoID, "
           +        " sale.t_DealCodeTS saleDealCodeTS, buy.t_DealID buyDealID, buy.t_ID buyID, buy.t_Type buyType, "
           +        " buy.t_Amount buyAmount, buy.t_RQID BuyPmID, sale.t_RQID SalePmID, "
           +        " (CASE WHEN buy.t_Origin = "+TXLOTORIGIN_DEAL+" THEN "+Get_str_PaymDate(DLRQ_TYPE_DELIVERY, 1, "buy")+" ELSE buy.t_BuyDate END) as buyDate, "
           +        " (CASE WHEN sale.t_Origin = "+TXLOTORIGIN_DEAL+" THEN "+Get_str_PaymDate(DLRQ_TYPE_DELIVERY, 1, "sale")+" ELSE sale.t_SaleDate END) as saleDate, "
           +        " buy.t_DealCode buyDealCode, buy.t_DealCodeTS buyDealCodeTS, "
           +        " lnk.t_Amount, lnk.t_Type LnkType, lnk.t_Date lnkDate, "

           +        " rsb_sctx.TXGetLotNKD(buy.t_ID) as BuyNKD, "
           +        " rsb_sctx.TXGetLotCost(buy.t_ID) as BuyCost, "
           +        " Rsb_SCTX.GetMarketPrice( sale.t_ID, buy.t_ID ) AS SaleMarketPrice, "
           +        " Rsb_SCTX.GetMarketPrice( buy.t_ID, 0 ) AS BuyMarketPrice, "
           +        " Rsb_SCTX.GetMarket( sale.t_ID, buy.t_ID ) AS SaleMarket, "
           +        " Rsb_SCTX.GetMarket( buy.t_ID, 0 ) AS BuyMarket, "
           +        " Rsb_SCTX.GetDateMarket( buy.t_ID, 0 ) AS BuyDateMarket, "
           +        " Rsb_SCTX.GetDateMarket( sale.t_ID, buy.t_ID ) AS SaleDateMarket ";

   sql =  " FROM dsctxlnk_dbt lnk, dsctxlot_dbt sale, dsctxlot_dbt CurSale, dsctxlot_dbt currbuy, dsctxlot_dbt buy,"
       +       " dfininstr_dbt fin, davrkinds_dbt avrk, davoiriss_dbt avoir "
       + " WHERE " + str_TypeLnk
       +       " lnk.t_Date >= ? and "
       +       " lnk.t_Date <= ? and "
       +       " CurSale.t_ID = lnk.t_SaleId and "
       +       " CurSale.t_BegLotID = sale.t_ID and "
       +       " currbuy.t_ID = lnk.t_BuyId and"
       +       " buy.t_ID = currbuy.t_BegLotID and "
       +       " fin.t_FIID = buy.t_FIID and "
       +       " fin.t_FIID = avoir.t_FIID and "
       +       " avrk.t_FI_Kind = 2 and "
       +       " avrk.t_AvoirKind = fin.t_AvoirKind and "
       +       " avrk.t_FI_Kind = fin.t_FI_Kind and "
       +       " avrk.t_IsEmissive = 'X' and "
       +       " buy.t_VirtualType = " + TXVDEAL_REAL + " and "
       +       " sale.t_VirtualType = " + TXVDEAL_REAL;

   if(( ValType(Data.AvrID) == V_Integer ) and  (Data.AvrID > 0 ))
      sql = sql + " and sale.t_FIID = ? ";
   elif(( ValType(Data.AvrID) != V_Integer ))
     i = 0;
     AddWhere = ""; 
     while( i < Data.AvrID.Size )
       if(AddWhere == "" )
         AddWhere = string(Data.AvrID[i]);
       else
         AddWhere = AddWhere + ", " + string(Data.AvrID[i]) ;
       end;
       i = i + 1;
     end;
     if( AddWhere != "") 
       sql  = sql + " and sale.t_FIID in (" + AddWhere + ") ";
     end;
   end;

   if( (Data.NominateInRUR == "X") and (Data.NotNominateInRUR == "X") )
     /* если установлены оба признака, то это значит все ц\б, и условия не накладываем */
   else
      if( (Data.NominateInRUR != "X") and (Data.NotNominateInRUR != "X") )
         sql = sql + " AND 1 <> 1 "; /* ничего не отбираем */
      else
         if( Data.NominateInRUR == "X" )
            sql = sql
                      + " AND fin.t_FaceValueFI = " + string(NATCUR);
         end;
         if( Data.NotNominateInRUR == "X" )
            sql = sql
                      + " AND fin.t_FaceValueFI <> " + string(NATCUR)
                      + " AND fin.t_FaceValueFI <> -1 ";
         end;
      end;
   end;

   if(( ValType(Data.AvrGroup) == V_Integer ) and ( Data.AvrGroup > 0 ))
      sql = sql + " and avoir.t_TaxGroup = ? ";
   elif( ValType(Data.AvrGroup) != V_Integer )
     i = 0;
     AddWhere = ""; 
     while( i < Data.AvrGroup.Size )
       if(AddWhere == "" )
         AddWhere = string(Data.AvrGroup[i]);
       else
         AddWhere = AddWhere + ", " + string(Data.AvrGroup[i]) ;
       end;
       i = i + 1;
     end;
     if( AddWhere != "") 
       sql  = sql + " and avoir.t_TaxGroup in (" + AddWhere + ") ";
     end;
   end;

   //sql = sql + " and avoir.t_TaxGroup " + IIF(RepNum == 6, TAX6, TAX7) ;   
   sql = sql + " and (avoir.t_TaxGroup " + IIF(RepNum == 6, TAX6, TAX7) + " or avoir.t_TaxGroup = 0) "; 

   if( RepSection == REPSECTION_CIRCULATE )
      sql = sql + " AND Rsb_SCTX.ifMarket( sale.t_ID, buy.t_ID ) = 'X' "
                + " AND sale.t_Origin = " + TXLOTORIGIN_DEAL;
   elif( RepSection == REPSECTION_NOTCIRCULATE )
      sql = sql + " AND NVL(Rsb_SCTX.ifMarket( sale.t_ID, buy.t_ID ),chr(0)) != 'X' "
                + " AND sale.t_Origin = " + TXLOTORIGIN_DEAL;
   elif( RepSection == REPSECTION_ISSUERCORPOP )
      sql = sql + " AND sale.t_Origin <> " + TXLOTORIGIN_DEAL;
   end;

   if( (ValType(Data.Avr_Kind) == V_Integer) or (ValType(Data.Avr_Kind) == V_Bool) or (ValType(Data.Avr_Kind) == V_String))
   if( not Data.IsGos )
      if( Data.Avr_Kind > 0 )
        if( Data.Avr_Kind == SHARE )/*акции и паи*/
          sql = sql + " and (RSB_FIInstr.FI_AvrKindsEQ(fin.t_FI_Kind, "+AVOIRISSKIND_SHARE+", fin.t_AvoirKind) = 1 "
                    + "      or RSB_FIInstr.FI_AvrKindsEQ(fin.t_FI_Kind, "+AVOIRISSKIND_INVESTMENT_SHARE+", fin.t_AvoirKind) = 1 )";
        elif( Data.Avr_Kind == DEPO_RECEIPT )/*ДР*/
          sql = sql + " and RSB_FIInstr.FI_AvrKindsEQ(fin.t_FI_Kind, "+AVOIRISSKIND_DEPOSITORY_RECEIPT+", fin.t_AvoirKind) = 1 ";
        elif( Data.Avr_Kind == BOND )/*Облигации*/
          sql = sql + " and RSB_FIInstr.FI_AvrKindsEQ(fin.t_FI_Kind, "+AVOIRISSKIND_BOND+", fin.t_AvoirKind) = 1 ";
        end;
      end;
   else/*только Облигации*/
      if( Data.Avr_Kind > 0)
         sql = sql + " and RSB_FIInstr.FI_AvrKindsEQ(fin.t_FI_Kind, "+Data.Avr_Kind+", fin.t_AvoirKind) = 1 ";
      else
         sql = sql + " and RSB_FIInstr.FI_AvrKindsEQ(fin.t_FI_Kind, "+AVOIRISSKIND_BOND+", fin.t_AvoirKind) = 1 ";
      end;
   end;
   else
     i = 0;
     AddWhere = ""; 
     while( i < Data.Avr_Kind.Size )
       if(AddWhere == "" )
         AddWhere = string(Data.Avr_Kind[i]);
       else
         AddWhere = AddWhere + ", " + string(Data.Avr_Kind[i]) ;
       end;
       i = i + 1;
     end;
     if( AddWhere != "") 
       sql  = sql + " and fin.t_AvoirKind in (" + AddWhere + ") ";
     end;
   end;

   sql = sql
       + " ORDER BY sale.t_FIID, "
       +          " lnk.t_Date, "
       +          " sale.t_SaleDate, "
       +          " sale.t_DealDate, "
       +          " sale.t_DealTime ";
   
   /* подсчет кол-ва строк */
   rsd_sql_count = RSDCommand(sql_count + sql);
   rsd_sql_count.addParam( "", RSDBP_IN, Data.BegDate );
   rsd_sql_count.addParam( "", RSDBP_IN, Data.EndDate );
   if(( ValType(Data.AvrID) == V_Integer ) and ( Data.AvrID > 0 ))
      rsd_sql_count.addParam( "", RSDBP_IN, Data.AvrID );
   end;

   if(( ValType(Data.AvrGroup) == V_Integer ) and ( Data.AvrGroup > 0 ))
      rsd_sql_count.addParam( "", RSDBP_IN, Data.AvrGroup );
   end;

   rsd_sql_count.execute();
   
   rsd = TRsbDataSet(rsd_sql_count);
   if( rsd.MoveNext() )
     iCount = int(rsd.iCount);
   else
     iCount = -1;
   end;

   if( RepSection == REPSECTION_CIRCULATE )
     title = TitleCirc;
   elif( RepSection == REPSECTION_NOTCIRCULATE )
     title = TitleNotCirc;
   elif( RepSection == REPSECTION_ISSUERCORPOP )
     title = TitleIssuerCorpOp;
   end;

   ProgressValue.Maximum = iCount;
   ProgressValue.Current = 0;

   var ProgressIndicator = CreateProgressIndicator(m_IsWebService);

   if( m_IsWebService )
     var header = "Формирование отчета " + WebMenuItem.szNameItem;
     ProgressIndicator.Start(ProgressValue.Maximum, header, header);
   else
     ProgressIndicator.Start(ProgressValue.Maximum, StatLine, title);
   end;

   rsd_sql_sel = RSDCommand(sql_sel + sql);
   rsd_sql_sel.addParam( "", RSDBP_IN, Data.BegDate );
   rsd_sql_sel.addParam( "", RSDBP_IN, Data.EndDate );
   if(( ValType(Data.AvrID) == V_Integer ) and ( Data.AvrID > 0 ))
      rsd_sql_sel.addParam( "", RSDBP_IN, Data.AvrID );
   end;

   if(( ValType(Data.AvrGroup) == V_Integer ) and ( Data.AvrGroup > 0 ))
      rsd_sql_sel.addParam( "", RSDBP_IN, Data.AvrGroup );
   end;

   rsd_sql_sel.execute();

   rsd = TRsbDataSet(rsd_sql_sel);

   PrevFIID = -1;
   
   while(rsd.MoveNext())

      if( ( getTaxGroup(rsd.FIID) == 0) AND (ПолучитьФинИн( rsd.FIID, fininstr ) == 0) )
         if((oldName != fininstr.rec.Name))
            oldName = fininstr.rec.Name;
            msgbox( "Для ценной бумаги с наименованием \"" + fininstr.rec.Name + "\" не задана группа налогового учета" );
         end;
      else
         if (rsd.FIID != PrevFIID)
            PrevFIID = rsd.FIID;
            if (ПолучитьФинИн( rsd.FIID, fininstr ) == 0)
               Data.IsBond = FI_IsBond(fininstr);
         
               if (Data.IsBond)
                  Data.IsCoupAvoir = FI_IsCouponAvoiriss( fininstr );
                  Data.IsShare = false;
                  Data.IsAvrKindBond_AD = FI_IsAvrKindBond_AD(rsd.FIID);
               else
                  Data.IsCoupAvoir = false;
                  Data.IsShare = true;
                  Data.IsAvrKindBond_AD = false;
               end;
            end;
         end;

      PrintLine( rsd,
                 Summary, 
                 RepSection, 
                 RepNum, Data.IsGos );
      end;   

      ProgressValue.Current = ProgressValue.Current + 1;
      ProgressIndicator.Update(ProgressValue.Current,ProgressValue.Maximum); // всего 3 парамера Update(index, count, text)
   end;   

   ProgressIndicator.Stop();

   /* Подсчет итогов и печать */
   AllSummary.Add( Summary );

   if( Data.WasPrintInPart )
      PrintSummary( RepNum, Summary, RepSection, false, Data.IsGos );
   end;

end;

/* Строим отчет. */
private macro DoReport( NumRep )
   var
      AllSummary     = SummaryData();  /* итоговые данные */

   /* Шапка отчета */
   PrintHeadReport(NumRep);

   if( (Data.CircInMark) or (Data.NotCircInMark) or (Data.IssuerCorpOp) )
      if( Data.CircInMark )
        ПереборБумагИПечать( REPSECTION_CIRCULATE, AllSummary, NumRep );
      end;

      if( Data.NotCircInMark )
        ПереборБумагИПечать( REPSECTION_NOTCIRCULATE, AllSummary, NumRep );
      end;
       
      if( Data.IssuerCorpOp )
        ПереборБумагИПечать( REPSECTION_ISSUERCORPOP, AllSummary, NumRep );
      end;
   end;

   /* Печатаем итоговые строки */
   if( Data.WasPrintInRep )
      m_Report.m_IsDataExist = true;
      PrintSummary( NumRep, AllSummary, false, true, Data.IsGos );
   else
      if(m_IsWebService == false)
      msgbox( "Нет данных, удовлетворяющих параметрам отчета" );
   end;
end;
end;

/* Отчет "Доходы и расходы от реализации ц/б (кроме гос. и муниципальных)" */
macro ReportRunNGos(     Report:OBJECT,
                     Period: integer,
                     Year: integer,
                     GrowingItog: bool, 
                     CirculateInMarket: bool,
                     NotCirculateInMarket: bool,
                     IssuerCorpOp: bool,
                     NominateInRUR: bool,
                     NotNominateInRUR: bool,
                     AvAll,                           /* Все бумажки */
                     AvShare: bool,                   /* Акции */
                     AvDeposReceipt: bool,            /* Депозит. расписки */
                     AvBond: bool,                    /* Облигации */
                     AvrID,
                     AvrGroup,
                     LnkBuySale: bool,
                     LnkCloseShortPos: bool,
                     IsWebService: bool,
                     WebMenuItem_
                     )
  /* Определяем Avr_Kind */
  var AvrKind;

  if(( ValType(AvAll) == V_String) or ( ValType(AvAll) == V_BOOL))
    if( AvAll )
      AvrKind = ALL_FI;
    elif( AvShare )
      AvrKind = SHARE;
    elif( AvDeposReceipt )
      AvrKind = DEPO_RECEIPT;
    else
      AvrKind = BOND;
    end;
  else
    AvrKind = AvAll;
  end;

  NomOnDateBuy = FiidNomOnDate(-1,Date(0,0,0),0);
  NomOnDateSale = FiidNomOnDate(-1,Date(0,0,0),0);

  Data = SourceData( Period, Year, GrowingItog, CirculateInMarket, 
                     NotCirculateInMarket, IssuerCorpOp, NominateInRUR, NotNominateInRUR,
                     AvrKind, AvrID, AvrGroup, LnkBuySale, LnkCloseShortPos, false );

  m_Report = Report;
  m_IsWebService = IsWebService;
  WebMenuItem = WebMenuItem_;

  /* печатаем отчет */
  DoReport(7);

  m_Report.EndTable();
  m_Report.AddStandardFooter( "N_" );
end;

/* Отчет "Доходы и расходы от реализации гос. и муниципальных ц/б" */
macro ReportRunGos(  Report:OBJECT,
                     Period: integer,
                     Year: integer,
                     GrowingItog: bool,
                     CirculateInMarket: bool,
                     NotCirculateInMarket: bool,
                     IssuerCorpOp: bool,
                     NominateInRUR: bool,
                     NotNominateInRUR: bool,
                     AvrID,
                     Bond_Kind,
                     AvrGroup,
                     LnkBuySale: bool,
                     LnkCloseShortPos: bool,
                     IsWebService:bool,
                     WebMenuItem_
                     )

  NomOnDateBuy = FiidNomOnDate(-1,Date(0,0,0),0);
  NomOnDateSale = FiidNomOnDate(-1,Date(0,0,0),0);

  Data = SourceData(Period, Year, GrowingItog, CirculateInMarket, 
                    NotCirculateInMarket, IssuerCorpOp, NominateInRUR, NotNominateInRUR,
                    Bond_Kind, AvrID, AvrGroup, LnkBuySale, LnkCloseShortPos, true );

  m_Report = Report;
  m_IsWebService = IsWebService;
  WebMenuItem = WebMenuItem_;

  /* печатаем отчет */
  DoReport(6);

  m_Report.EndTable();
  m_Report.AddStandardFooter( "N_" );
end;
