/*
$Name:        BrokerRepRSHB_Report.mac
$Module:      Ценные бумаги
$Description: Отчет брокера РСХБ. 
              Формирование отчета.
*/

import "DLReport_h.mac", "dlreport.mac", "dlQuery.mac", "scsrvrepfun.mac", "sc_inacc.mac";
import "dpstdrep.mac", "dl_util_xml_obj.mac", "dl_util_poi_obj.mac";
import "dvserv.mac", "dlcontrfunc.mac";
import "lim_utils.mac";

CONST DIRECTION_NO   = 0; //Направления нет (для итоговых строк)
CONST DIRECTION_BUY  = 1; //Покупка
CONST DIRECTION_SALE = 2; //Продажа

//Группы данных данных
CONST BROKERREP_PART_DEALINPERIOD = 1; //СДЕЛКИ, ЗАКЛЮЧЕННЫЕ В ПЕРИОД С : ПО :
CONST BROKERREP_PART_REPOINPERIOD = 2; //СДЕЛКИ РЕПО, ЗАКЛЮЧЕННЫЕ В ПЕРИОД С : ПО :
CONST BROKERREP_PART_EXECDEAL     = 3; //СДЕЛКИ, ЗАКЛЮЧЕННЫЕ И ИСПОЛНЕННЫЕ НА
CONST BROKERREP_PART_REPODEAL     = 4; //СДЕЛКИ РЕПО, ЗАКЛЮЧЕННЫЕ И ИСПОЛНЕННЫЕ НА
CONST BROKERREP_PART_EXECREPO     = 4; //СДЕЛКИ РЕПО, ЗАКЛЮЧЕННЫЕ И ИСПОЛНЕННЫЕ НА
CONST BROKERREP_PART_CANCELDEAL   = 5; //СДЕЛКИ, ЗАКЛЮЧЕННЫЕ И ОТМЕНЕННЫЕ В ПЕРИОД
CONST BROKERREP_PART_CANCELREPO   = 6; //СДЕЛКИ РЕПО, ЗАКЛЮЧЕННЫЕ И ОТМЕНЕННЫЕ В ПЕРИОД

//Виды расчетных операций
CONST BROKERREP_CALCOP_RECEPCLCUR = 6; //Прием от клиента д/с
CONST BROKERREP_CALCOP_RETURNCLCUR = 7; //Возврат клиенту д/с

CONST BROKERREP_DL_SETTLOPER = 2030; //Расчетная операция ВУ
CONST ALG_SCREPPERIODKIND = 3169;
CONST BROKERREP_ERRMAILTEMPL_NOREQ = 1; //Шаблон письма об отсутствующих заявках-поручениях

var messagesBuffer = TArray();
// пользовательские функции>
/*Дату в строку*/
macro GetDateS(dt:date)
  var i;
  datesplit(dt, i);
  if(i < 10)
    return "0" + substr(string(dt),2);
  else
    return string(dt);
  end;
end;

macro GetCDS()
  var cmd, DataSet;
  cmd = DL_RSDCommand("select trunc(sysdate) dt from dual");
  DataSet = cmd.execute();
  DataSet.moveNext();
  return date(DataSet.dt);
end;

macro MsgboxReplace()
  ReplaceMacro("Msgbox", "MsgboxCatch");
  messagesBuffer.size = 0;
end;
 
macro MsgboxCatch(message)
  messagesBuffer[messagesBuffer.size] = message;
end;
 
macro MsgboxRestore()
  ReplaceMacro("Msgbox");
 
  if (messagesBuffer.size > 0)
    for (var i, 0, messagesBuffer.size - 1)
      Msgbox(messagesBuffer[i]);
    end;
  end;
end;
 
macro IsExcelError(): Bool
  var result: Bool = false;
  var excelErrorSign: String = "800A03EC";
 
  if (messagesBuffer.size > 0)
    for (var i, 0, messagesBuffer.size - 1)
      if (Index(messagesBuffer[i], excelErrorSign) > 0)
        result = true;
        Break;
      end;
    end;
  end;
 
  return result;
end;

CLASS CBrokerRepRSHBErrMail (_Subject, _Body)
  var Subject = _Subject;
  var Body = _Body;
END;

// <пользовательские функции

CLASS CBrokerRepRSHBParams(_IsNew)
  var IsNew = false;
  if ((ValType(_IsNew) == V_BOOL) and (_IsNew == true))
    IsNew = true;
  end;

  private macro GetOurAddress():string
    var Address:string = "";

    var cmd = DL_RSDCommand("select t_Adress from dadress_dbt where t_PartyID = ? and t_Type = "+PTADDR_LEGAL);
    cmd.AddParam({ourbank});

    var DataSet = cmd.Execute();
    if(DataSet.moveNext())
      Address = DataSet.Adress;
    end;

    return Address;
  end;

  private macro GetOurINN():string
    var INNAndKPP:string = "";

    var cmd = DL_RSDCommand("select t_Code from dobjcode_dbt where t_ObjectType = "+OBJTYPE_PARTY+" and t_CodeKind = "+PTCK_INN+" and t_ObjectID = ? and t_State = 0");
    cmd.AddParam({ourbank});

    var DataSet = cmd.Execute();
    if(DataSet.moveNext())
      INNAndKPP = DataSet.Code;
    end;

    return INNAndKPP;
  end;  

  var ReportDate:date    = {curdate},                //Дата сервисной операции
      PeriodKind:integer = SC_REPPERIODKIND_DAY,     // Вид периода
      BegDate:date       = {curdate},                // Начальная дата
      EndDate:date       = {curdate},                // Конечная дата
      ClientID:integer   = -1,                       // Клиент
      DlContrID:integer  = 0,                        // ДБО
      SrvRepId:integer   = 0,                        // Id операции
      IsMarket:bool      = true,                     // по биржевым сделкам?
      IsOutMarket:bool   = false,                    // по внебиржевым сделкам?
      IsFiMovement:bool  = true,                     // по движению ФИ?
      IsNotZeroRest:bool = false,                    // по ненулевым остаткам?
      ShowPlanRest:bool  = IIF(IsNew, true, false),  // показывать плановые исходящие остатки
      ShowEmpty:bool     = IIF(IsNew, true, false),  // показывать пустые пункты при отсутствии данных
      IsApp:bool         = true,                     // апострофы?
      PdfFormat:bool     = true,                     // печатать в PDF
      ExcelFormat:bool   = false,                    // печатать в Excel

      ShowFile:bool      = false,                    // показать отчет
      InCnv              = false,                    // признак того, что отчет формируется в конвейере
      InServOp           = false,                    // признак того, что отчет формируется в сервисной операции
      NoData:bool        = false,                    // Нет данных для выпуска отчета
      NoReq:bool         = false,                    // Нет заявок-поручений по сделкам клиента
//dan
      SignerParty        = -1,                       //номер операциониста подписанта. Из примечания на субъекте будет браться путь к скану подписи
//dan
      RepData            = TArray(),                 // массив данных о сформированных файлах
      ErrMails           = TArray(),                 // массив с сообщениями об ошибке

      CourseCurVisible:bool = IIF(IsNew, true, false), //mva biq-12110 настройка "Отображение валюты котировки в Отчете Брокера"

      //Параметры нашего банка вынесены в общие парматеры отчета, чтобы не подтягивать их для каждого клиента отдельно
      OurAddress:string  = GetOurAddress(),      // адрес нашего банка
      OurINN:string      = GetOurINN();          // ИНН/КПП нашего банка
END;

// dan>
CLASS RepImgUnit(v_TegClass:String, v_SheetNum:integer, v_TegName:String)
  var TegClass:String = v_TegClass;
  var TegSheet        = v_SheetNum;
  var TegName:String  = v_TegName;
END;
// <dan

MACRO AmountPrecision(Amount):INTEGER
  if(IsHaveFractPart(ABS(Amount))) 
     return 6;
  else
     return 0;
  end;
END;
