/*
$Name:        conv020.mac
$Module:      Ценные бумаги
$Description: Операция конвертации ц/б. Шаг актуализации счетов
*/

import InsCarryDoc, "sp_categ.mac", "sp_catac.mac", "sp_car.mac";

macro ExecuteStep( doc, FDoc)
  
  record deal(dl_tick);
  var    FD, FD_in, dat;

  SetBuff( deal, FDoc );
  FD = SPFirstDoc( deal );
  GetOprDate( DATE_CONVAVR_BEGIN, dat );

  FD_in = SPFirstDoc( deal, true );

  /*Вставка лота*/
  if( not ОбновитьЛот( FD.pmwrtsum, PM_WRTSUM_UPDTMODE_CREATE, dat, FD ) )
     msgbox("Ошибка при создании лота");
     return 1;
  end;

  /*Вставка лота*/
  if( not ОбновитьЛот( FD_in.pmwrtsum, PM_WRTSUM_UPDTMODE_CREATE, dat, FD_in ) )
     msgbox("Ошибка при создании лота");
     return 1;
  end;

  return 0;
end;
