/**
  @file: 		mac\dlng\secur\nptxwrt170.mac
  @brief: 		Шаг 3: Ожидание ответа из ЦФТ, блок 203712
  # menu
  - БО ЦБ\Сервисные операции\Операция списания и зачисления денежных средств
  # changelog
  |date       |author         |tasks                                       |note
  |-----------|---------------|--------------------------------------------|-------------------------------------------------------------
  |2025.10.10 |Васильев Н.А.  |AVT_BOSS-104                                |

*/

import "u_common_email_utils.mac", "cblogger2.mac", "mmlib.mac";
import Refill_CreatePayment;
import Refill_Class;
import InsCarryDoc;


   const C_TIME_EXPIRED = 10; // минут
   const C_ERROR_CODE_EXPIRED = -1001;
   const C_ERROR_CODE_FATAL = -2002;
   const C_EMAIL_GRP = 16;
   const C_REG_EMAIL = "РСХБ\\Брокерское обслуживание\\Письма при ожидании ответа ЦФТ";

private macro Error( ErrStr:STRING ):INTEGER
  DL_NPTX_PutMsg( ErrStr );
  MsgBox( ErrStr );
  return 1;
end;

private macro getId(ID_Operation, FDoc)
         var cmd = DL_RSDCommand("SELECT to_number(TRIM(t_documentid)) as id FROM doproper_dbt p  JOIN dnptxop_dbt n " +
                                 "ON n.t_id = TO_NUMBER(TRIM(p.t_documentid)) "+
                                 "WHERE p.t_id_operation = ?  AND p.t_dockind = ?;");
         cmd.AddParam(ID_Operation);
         cmd.AddParam(FDoc);
         var DataSet = cmd.Execute();
         while (DataSet.moveNext())
          return SQL_ConvTypeInteger(DataSet.id);
         end;
         return 0;
end;


/* рассылка просроченных событий */
private MACRO sendMes(opID) 
var activity, err, sql, sql_upd, sql_upd_step, ds, cmd_upd, cmd_upd_step;
      GetRegistryValue(C_REG_EMAIL, V_BOOL, activity, err);
      if(activity)
         var count_errors = 0;
         var list_paymentid_str = "";
         sql = String("select s.*, rowid from UNPTXOP_PAYMENT_LINK_DBT s \n"+
                     " where s.t_nptxopid = " + opID + "\n"+
                     " and t_responseid = "+C_ERROR_CODE_EXPIRED+    "\n"+
                     " and t_errorcode = "+C_ERROR_CODE_EXPIRED        );
         sql_upd = String(" update UNPTXOP_PAYMENT_LINK_DBT  \n"+
                        "   set t_errorcode = :pcode       \n"+
                        " where rowid = :r                  ");
         sql_upd_step = String(" INSERT INTO UNPTXOP_PAYMENT_LINK_STEP_DBT  \n"+
                              "  (T_STEPID, T_REFILLID, T_SYSTEMDATE, T_ACTION, T_COMMENT, T_OPER)  \n"+
                              " VALUES (0, :prefillid, sysdate, 99, 'Ответ на отправку платежа просрочен', :poper) ");

         ds = TRsbDataSet(sql);
         while (ds.movenext())
            count_errors = count_errors + 1;
            list_paymentid_str = String(list_paymentid_str, " ", ds.paymentid, " \n");
            cmd_upd = RSDCommand(sql_upd);
            cmd_upd.AddParam("pcode", RSDBP_IN, C_ERROR_CODE_FATAL);
            cmd_upd.AddParam("r", RSDBP_IN, ds.rowid);
            cmd_upd.execute();
            cmd_upd.close();
            cmd_upd_step = RSDCommand(sql_upd_step);
            cmd_upd_step.AddParam("prefillid", RSDBP_IN, ds.refillid);
            cmd_upd_step.AddParam("poper", RSDBP_IN, {oper});
            cmd_upd_step.execute();
            cmd_upd_step.close();
         end;

         if (count_errors > 0)
            var v_email_processor = c_email_proc_env();
            v_email_processor.m_set_msg_head("СОФР - Выгрузка подкрепления счетов НКЦ");
            v_email_processor.m_add_row_to_msg_text("Не получен ответ за "+C_TIME_EXPIRED+" минут на выгруженные платежи. Список Id платежей СОФР: ");
            v_email_processor.m_add_row_to_msg_text(list_paymentid_str);
            v_email_processor.m_save_to_submit_grp(C_EMAIL_GRP, true);
            v_email_processor.m_submit_email_synch();
         end;
      end;
END;

 /* проверка созданных событий на выгрузку */
private MACRO checkCreatedEventsForUnloading(opID)
var sql, cmd;
      sql = String(" declare                                                                          \n"+
                  "     v_recid number(10);                                                           \n"+
                  "     OBJTYPE_PAYMENT number(10):= 501;                                             \n"+
                  "     v_rec UREFILL_DBT%rowtype;                                                    \n"+
                  "     v_oper number(10) := :poper;                                                  \n"+
                  " begin                                                                             \n"+
                  "     for c in (select d.*, rowid from UNPTXOP_PAYMENT_LINK_DBT d                   \n"+
                  "                                 where t_eventid = 0 and d.t_nptxopid = :pid) loop \n"+
                  "         v_recid  := - 1;                                                          \n"+
                  "         begin                                                                     \n"+
                  "             select t_recid into v_recid                                           \n"+
                  "               from utableprocessevent_dbt u                                       \n"+
                  "              where t_objecttype = OBJTYPE_PAYMENT                                 \n"+
                  "                and t_objectid = c.t_paymentid                                     \n"+
                  "                and t_recid = (select max(t_recid) from utableprocessevent_dbt u2  \n"+
                  "                                where u2.t_objecttype = u.t_objecttype             \n"+
                  "                                  and u2.t_objectid = u.t_objectid);               \n"+
                  "         exception                                                                 \n"+
                  "             when no_data_found then                                               \n"+
                  "                        v_recid := -1;                                             \n"+
                  "         end;                                                                      \n"+
                  "         if v_recid > 0 then                                                       \n"+
                  "             update UNPTXOP_PAYMENT_LINK_DBT                                       \n"+
                  "                 set t_eventid = v_recid                                           \n"+
                  "              where rowid = c.rowid;                                               \n"+
                  "             INSERT INTO UNPTXOP_PAYMENT_LINK_STEP_DBT                             \n"+
                  "                (T_STEPID, T_REFILLID, T_SYSTEMDATE, T_ACTION, T_COMMENT, T_OPER)  \n"+
                  "             VALUES (0, c.t_refillid, sysdate, 40, 'Отправка платежа ', v_oper);   \n"+
                  "             begin                                                                 \n"+
                  "               select * into v_rec                                                 \n"+
                  "                 from UREFILL_DBT                                                  \n"+
                  "                where t_id = c.t_refillid;                                         \n"+
                  "               INSERT INTO UREFILL_STEP_DBT                                        \n"+
                  "                     (T_STEPID, T_REFILLID, T_DATE_OPERATION, T_SYSTEMDATE,        \n"+
                  "                      T_ACTION, T_COMMENT, T_OPER)                                 \n"+
                  "               VALUES (0, v_rec.t_id, v_rec.t_date_operation, sysdate,             \n"+
                  "                      :paction, :pcomment, v_oper);                                \n"+
                  "             exception                                                             \n"+
                  "               when no_data_found then null;                                       \n"+
                  "             end;                                                                  \n"+
                  "         end if;                                                                   \n"+
                  "    end loop;                                                                      \n"+
                  " end;                                                                              ");
      cmd = RSDCommand(sql);
      cmd.AddParam("pid",    RSDBP_IN, opID);
      cmd.AddParam("poper", RSDBP_IN, {oper});
      cmd.AddParam("paction", RSDBP_IN, C_STEP_ACTION_PROCESS_STATUS);
      cmd.AddParam("pcomment", RSDBP_IN, "");
      cmd.execute();
      cmd.close();
END;

   /* проверка времени обработки созданных событий */
private MACRO checkCreatedEventsForTime(opID)
var sql, cmd, ds, stat = 0;
      sql = String(" declare                                                                             \n"+
                  "    v_messageid number(10) :=0;                                                       \n"+
                  "    v_error varchar2(2000 byte);                                                      \n"+
                  "    v_code number(10);                                                                \n"+
                  "    TIME_EXPIRED number(10) := :ptime;                                                \n"+
                  "    CODE_EXPIRED number(10) := :pcode;                                                \n"+
                  "    v_rec UREFILL_DBT%rowtype;                                                        \n"+
                  "    v_oper number(10) := :poper;                                                      \n"+
                  " begin                                                                                \n"+
                  "    for c in (select u.*, l.rowid, l.t_refillid                                       \n"+
                  "                from UNPTXOP_PAYMENT_LINK_DBT l,                                      \n"+
                  "                     UTABLEPROCESSEVENT_DBT u                                         \n"+
                  "               where l.t_eventid = u.t_recid  and l.t_nptxopid = :pid                 \n"+
                  "                 and t_responseid = 0) loop                                           \n"+
                  "       v_messageid := 0;                                                              \n"+
                  "       v_error := '';                                                                 \n"+
                  "       v_code := 0;                                                                   \n"+
                  "       if c.t_status = 4 then                                                         \n"+
                  "          v_messageid := c.t_messageid;                                               \n"+
                  "          v_error := 'OK';                                                            \n"+
                  "       elsif c.t_status = 5 then                                                      \n"+
                  "          v_messageid := -1;                                                          \n"+
                  "          v_error := c.t_resulttext;                                                  \n"+
                  "          v_code := c.t_resultcode;                                                   \n"+
                  "       else                                                                           \n"+
                  "          if c.t_timestamp < (sysdate - NUMTODSINTERVAL(TIME_EXPIRED, 'MINUTE')) then \n"+
                  "             v_messageid := CODE_EXPIRED;                                             \n"+
                  "             v_error := 'Ответ не получен за '||TIME_EXPIRED||' минут';               \n"+
                  "             v_code := CODE_EXPIRED;                                                  \n"+
                  "          end if;                                                                     \n"+
                  "       end if;                                                                        \n"+
                  "       update UNPTXOP_PAYMENT_LINK_DBT                                                \n"+
                  "          set t_responseid = v_messageid,                                             \n"+
                  "              t_errorcode = v_code,                                                   \n"+
                  "              t_errortext = v_error                                                   \n"+
                  "        where rowid = c.rowid;                                                        \n"+
                  "       if v_messageid <> 0 then                                                       \n"+
                  "         INSERT INTO UNPTXOP_PAYMENT_LINK_STEP_DBT                                    \n"+
                  "            (T_STEPID, T_REFILLID, T_SYSTEMDATE, T_ACTION, T_COMMENT, T_OPER)         \n"+
                  "         VALUES (0, c.t_refillid, sysdate, 50, SUBSTR('Ответ на отправку платежа '||v_error, 1, 200), v_oper); \n"+
                  "       end if;                                                                        \n"+
                  "       if c.t_status = 4 then                                                         \n"+
                  "          begin                                                                       \n"+
                  "             select * into v_rec                                                      \n"+
                  "               from UREFILL_DBT                                                       \n"+
                  "              where t_id = c.t_refillid;                                              \n"+
                  "             INSERT INTO UREFILL_STEP_DBT                                             \n"+
                  "                (T_STEPID, T_REFILLID, T_DATE_OPERATION, T_SYSTEMDATE,                \n"+
                  "                 T_ACTION, T_COMMENT, T_OPER)                                         \n"+
                  "             VALUES (0, v_rec.t_id, v_rec.t_date_operation, sysdate,                  \n"+
                  "                     :paction, :pcomment, v_oper);                                    \n"+
                  "             update UREFILL_DBT                                                       \n"+
                  "                set t_status = :pstatus, t_status_name = :pstatusname                 \n"+
                  "              where t_id = v_rec.t_id;                                                \n"+
                  "          exception                                                                   \n"+
                  "             when no_data_found then null;                                            \n"+
                  "          end;                                                                        \n"+
                  "       end if;                                                                        \n"+
                  "    end loop;                                                                         \n"+
                  " end;                                                                                  ");
      cmd = RSDCommand(sql);
      cmd.AddParam("pid",      RSDBP_IN, opID);
      cmd.Addparam("ptime", RSDBP_IN, C_TIME_EXPIRED);
      cmd.Addparam("pcode", RSDBP_IN, C_ERROR_CODE_EXPIRED);
      cmd.AddParam("poper", RSDBP_IN, {oper});
      cmd.AddParam("paction", RSDBP_IN, C_STEP_ACTION_CLOSE);
      cmd.AddParam("pcomment", RSDBP_IN, "");
      cmd.AddParam("pstatus", RSDBP_IN, C_REFILL_ACTION_CLOSED);
      cmd.AddParam("pstatusname", RSDBP_IN, refill_GetStatusName(C_REFILL_ACTION_CLOSED));
      cmd.execute();
      cmd.close();
      //отправка письма, если ответа нет больше 10 минут
      sql = String("select 1 from UNPTXOP_PAYMENT_LINK_DBT l \n"+ 
                    "join UTABLEPROCESSEVENT_DBT u on u.t_recid = l.t_eventid \n"+
                    " where l.t_nptxopid = " + opID + " \n"+
                    " and l.t_responseid = " + C_ERROR_CODE_EXPIRED + " \n");
      var ds2 = TRsbDataSet(sql);
      if(ds2.movenext())
         sendMes(opID);
         stat = 1;
      else 
         //если ответа нет меньше или равно 10 минут, то необходимо проверить есть ли уже запись на выполнение операции в funcobj.
         //если нет, то отправить отложенное сообщение через QManager на повторное воспроизведение операции 
         sql = String("select 1 from UNPTXOP_PAYMENT_LINK_DBT l \n"+ 
                     "join UTABLEPROCESSEVENT_DBT u on u.t_recid = l.t_eventid \n"+
                     " where l.t_nptxopid = " + opID + " \n"+
                     " and l.t_responseid = 0 \n"+                    
                     " and u.t_timestamp >= (sysdate - NUMTODSINTERVAL(" + C_TIME_EXPIRED + ",'MINUTE'));");            
         ds = TRsbDataSet(sql);
         if(ds.moveNext())
            sql = String("select 1 from dfuncobj_dbt \n"+
                        " where t_funcid    = 11503 \n"+
                        "   and t_objectid  = " + opID + "\n"+ 
                        "   and t_objecttype = 4600");
            var ds3 = TRsbDataSet(sql);
            if(ds3.moveNext())
            else 
               // sql = String("it_q_message.load_msg(p_message_type => it_q_message.C_C_MSG_TYPE_R," +
               //                                   " p_delivery_type => it_q_message.C_C_MSG_DELIVERY_A,"+
               //                                   " p_ServiceName => 'ExecuteCode', p_MESSBODY => 'call insertOperation(" + opID + ", 4600)', p_delay => 600);");
               // cmd = RSDCommand(sql);
               // cmd.execute();
               // cmd.close();
            end;
            stat = 1;
         end;

      end;                
      return stat;
END;

MACRO ExecuteStep(kind_oper, DocKind, FDoc, ID_Operation, ID_Step )

   var opID = getId(ID_Operation, FDoc);
   Array Text;
   Array Buttons;
         var cmd, stat;
         var sql = String("select 1  from UREFILL_DBT r  join UNPTXOP_PAYMENT_LINK_DBT l on l.t_refillid = r.t_id  where l.t_nptxopid = " + opID +" and r.t_status = 2 ");
         var ds = TRsbDataSet(sql); 

         if (ds.MoveNext())
               if( not InsertOprStatus(484131, 2)) //Установить ИРК = Завершено
                  return Error( "Ошибка при установке статуса вида \"Установить ИРК \" операции" );
               end;
               return 0;
         else 
            /* проверка созданных событий на выгрузку */
            checkCreatedEventsForUnloading(opID);
            /* проверка времени обработки созданных событий */
            stat = checkCreatedEventsForTime(opID);
            if((stat == 1) and ({oper} == 9997))
               return 1;
            end;
            if((stat == 0) and ({oper} == 9997))
                  if( not InsertOprStatus(484131, 2)) //Установить ИРК = Завершено
                     return Error( "Ошибка при установке статуса вида \"Установить ИРК \" операции" );
                  end;
                  return 0;
            end;
            if ({oper} != 9997)
               var Action;
               Text(0) = "Выполнить шаг с исполнением проводок?";
               Buttons(0) = "    Да    ";
               Buttons(1) = "    Нет   ";
               Buttons(2) = "  Отмена  ";
               Action = ConfWin(Text, Buttons, 2);

               if (Action == 0)
                  if( not InsertOprStatus(484131, 2)) //Установить ИРК = Завершено
                     return Error( "Ошибка при установке статуса вида \"Установить ИРК \" операции" );
                  end;
                  return 0;
               elif (Action == 1)
                  if( not InsertOprStatus(484131, 3)) //Установить ИРК = Отказано
                     return Error( "Ошибка при установке статуса вида \"Установить ИРК \" операции" );
                  end;
                  return 0;
               end;

              return 1;
            end;

          return 1;
         end;

      return 1;   
end;
