/*
$Name:        nptxcalc104.mac
$Module:      Ценные бумаги
$Description: Отмена прежних записей о событиях СНОБ
*/
IMPORT "secinter.mac", "nptxcalcfun.mac", "dlcontrsc.mac";

private macro Error( err, ErrStr:STRING ):INTEGER
  DL_NPTX_PutMsg( ErrStr );
  if(err)
    MsgBox( ErrStr );
  end;
  return err;
end;

macro ExecuteStep( kind_oper, FDoc, DocKind, ID_Operation, ID_Step )
  record nptxop("nptxop");
  var ErrStr = "";
  var Year = 0;
  var err = 0;
  var НОБ_опер = $0, НОБ_30 = $0, НОБ_13 = $0, НОБ_15 = $0;
  var taxe = $0, taxe15 = $0;
  var TxArr = TArray();
  var query, cmd, DataSet;
  var STB = TRecHandler("nptxtotalbase.dbt");

  SetBuff( nptxop, FDoc );

  DateSplit(nptxop.OperDate, null, null, Year);

  if(nptxop.Recalc == SET_CHAR)
    err = ExecCancelSTBinCalcNDFLop(nptxop, ID_Operation, ID_Step, @ErrStr);
  end;

  if(not err)
    err = DL_NPTX_SaveTbMes();
  end;

  if(ErrStr)
    err = Error(err, ErrStr);
  end;

  return err;
end;

/* Макрос постобработки */
MACRO PostStep (CommitOrRollback, /*1-выполнение шага,2 -отакат шага*/
                errTrn,        /* Статус выполнения шага-!0-произошла ошибка */
                FDoc,          /* Указатель на первичный документ */
                ID_Operation,  /* Номер экземпляра операции */
                Num_Step,      /* Номер шага операции(из настроек) */
                Kind_Operation,/* Вид операции */
                KindDoc,       /* Вид первичного документа */
                KindStep,      /* Вид шага операции */
                ID_Step)       /* Номер шага операции */

  record nptxop("nptxop");
  var ErrStr = "";
  var err = 0;

  SetBuff( nptxop, FDoc );

  if(CommitOrRollback == 2)
    err = STB_RollbackSendToStorOnStep(nptxop.DocKind, nptxop.ID, ID_Operation, ID_Step, @ErrStr);
    if(ErrStr != "")
      msgbox(ErrStr);
    end;
  end;

  return err;
END;
