/*
$Name:        nptxpit2.mac
$Module:      Ценные бумаги
$Description: Отчет "2-НДФЛ по ц/б"
*/
IMPORT "nptxpit2_form.mac", "RegistrReport.mac", "dl_xml.mac", "dlerr_log.mac", "RepPersonalIncomeTax.mac", "TaxReportBase.mac";

PRIVATE VAR Form;
PRIVATE VAR ErrLog = ErrorLoger();
PRIVATE VAR Rep;
PRIVATE VAR IsClient;
PRIVATE CONST POI_MODE = TRUE;    //при печати использовать POI
PRIVATE CONST POI_SIZE_PACK = 250;
Private VAR ItogSym;

PRIVATE MACRO CheckOperNum( opNum )
  var lenght = strlen(opNum);
  var i = 0, count = -1;
  var numStr = "0123456789";

  while(i < lenght)                                              

   if( Index(numStr, substr(opNum, lenght - i, 1)) )
      count = i;
    else
      return count; 
   end; 
    i = i + 1;
  end;
                                                          
  return count;
END;

PRIVATE MACRO getMonthNPTX (_month)
  VAR Month ;
  if( (string(_month) == "10") OR (string(_month) == "11") OR(string(_month) == "12"))
    return  _month;
  else
    return "0"+string(_month);
  end;

END;

PRIVATE CLASS (NPTXRepCalcCommon) NPTXRepCalc( _RepDate, _Investor )

  private var m_LastOpCode;
  private var m_TaxDue1Arr = TArray(); //Итоговые значение по справке с признаком 1
  private var m_PrintArrForSign2 = TArray();

  MACRO MinusG_618()
     if( m_MinusG_618 == null )
        if( (m_InfoRate == INFORATE_TOTAL) and (this.ResidenceStatus() == 1) )
           m_MinusG_618 = GetRubSumByClientOperDocKind(this.ClientID(), string(TXOBJ_MINUSG_618), date(1,1,m_CurrYear), m_RepDate, DL_CALCNDFL, null, GetTypeContract()) + //созданные в операциях расчета НОБ
                          GetRubSumByClientOperDocKind(this.ClientID(), string(TXOBJ_MINUSG_618), date(1,1,m_CurrYear), m_RepDate, 0 /*только пользовательские*/, null, GetTypeContract());
        else
           m_MinusG_618 = $0;
        end;
     end;
     return m_MinusG_618;
  END;

  MACRO MinusG_619()
    if (m_MinusG_619 == null)
      if ((m_InfoRate == INFORATE_TOTAL) and (this.ResidenceStatus() == 1) 
          and (IIS_CONTRACTS == SET_CHAR))
        m_MinusG_619 = GetRubSumByClientOperDocKind(this.ClientID(),
                                                    string(TXOBJ_MINUSG_619),
                                                    date(1,1,m_CurrYear),
                                                    m_RepDate,
                                                    DL_CALCNDFL,
                                                    null,
                                                    1)
                       + GetRubSumByClientOperDocKind(this.ClientID(),
                                                      string(TXOBJ_MINUSG_619),
                                                      date(1,1,m_CurrYear),
                                                      m_RepDate,
                                                      0,
                                                      null,
                                                      1);
        else
          m_MinusG_619 = $0;
        end;
     end;
     return m_MinusG_619;
  END;

  MACRO TaxDue_n(index)
    return m_ArrCodeParms[index].TaxDue;
  END;

  PRIVATE MACRO ДобавитьПараметры( InfoRate, PSCode, PSCodeStr, MSCode, MSCodeStr )

    var PSnnn = $0, MSnnn = $0;

//    PSnnn = this.PSnnn(InfoRate, PSCode, PSCodeStr);
    PSnnn = this.PSnnn(InfoRate, PSCode, PSCodeStr, IIF(( (PSCode==1011) OR (PSCode==2800)), true, false), this.Rate(m_InfoRate));
    MSnnn = this.MSnnn(InfoRate, MSCode, MSCodeStr);

    if( ((PSCode != null ) or (MSnnn != $0)) and (((PSnnn != null) and (PSnnn != 0)) or (MSnnn != null) and (MSnnn != 0)) )
       if(m_CurrSign == 1)
          AddInArrCodeParms(m_ArrCodeParms, Month(m_BeginDate), PSCode, PSnnn, MSCode, MSnnn, 0.0, 0.0, 0.0, 0.0, 0.0, Rate(InfoRate), (PSnnn-MSnnn));
       elif(m_CurrSign == 2)
          AddInArrCodeParms(m_ArrCodeParms, Month(m_BeginDate), PSCode, (PSnnn-MSnnn), NULL, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Rate(InfoRate), (PSnnn-MSnnn));
       end;

       m_PlusSum  = m_PlusSum  + PSnnn;
       m_MinusSum = m_MinusSum + MSnnn;
    end;
  END;

  PRIVATE MACRO РассчитатьИтоговыеЗначения(RateIndexes)
    var TotalPlus = "";
    var TotalMinus = "";

    var j = 0;
    while(j < RateIndexes.Size)
      if(m_InfoRate != 0)
        m_ArrCodeParms[RateIndexes[j]].TaxPaid = this.GetTaxPaid(m_InfoRate);
      end;
  
      TotalPlus     = m_ArrCodeParms[RateIndexes[j]].PlusSum;
      TotalMinus    = m_ArrCodeParms[RateIndexes[j]].MinusSum;
  
      if( m_CurrSign == 1 )
        m_ArrCodeParms[RateIndexes[j]].TaxBaseSum = max((TotalPlus - TotalMinus /*- MinusG_618()
                           - MinusG_619()*/),0);
  
        m_ArrCodeParms[RateIndexes[j]].TaxCalculated = round(m_ArrCodeParms[RateIndexes[j]].Rate * m_ArrCodeParms[RateIndexes[j]].TaxBaseSum/100.0, 0) - PaidGeneral_0() - PaidSpecial_0(false);
  
        m_ArrCodeParms[RateIndexes[j]].TaxDue = 0;
        if(m_ArrCodeParms[RateIndexes[j]].TaxPaid < m_ArrCodeParms[RateIndexes[j]].TaxCalculated)
          m_ArrCodeParms[RateIndexes[j]].TaxDue = m_ArrCodeParms[RateIndexes[j]].TaxCalculated - m_ArrCodeParms[RateIndexes[j]].TaxPaid;
        end;
  
        m_TaxDue1Arr[RateIndexes[j]] = m_ArrCodeParms[RateIndexes[j]].TaxDue;
  
        m_ArrCodeParms[RateIndexes[j]].TaxToReturnDue = 0;
        if(m_ArrCodeParms[RateIndexes[j]].TaxPaid > m_ArrCodeParms[RateIndexes[j]].TaxCalculated)
          m_ArrCodeParms[RateIndexes[j]].TaxToReturnDue = m_ArrCodeParms[RateIndexes[j]].TaxPaid - m_ArrCodeParms[RateIndexes[j]].TaxCalculated;
        end;
      end;
      
      if(m_CurrSign == 2)
        m_ArrCodeParms[RateIndexes[j]].TaxDue = m_TaxDue1Arr[RateIndexes[j]];
        
        //m_ArrCodeParms[RateIndexes[j]].TaxBaseSum = TotalPlus;
        m_ArrCodeParms[RateIndexes[j]].TaxBaseSum = max((TotalPlus - TotalMinus /*- MinusG_618()
                                                        - MinusG_619()*/),0);

        m_ArrCodeParms[RateIndexes[j]].TaxToReturnDue = 0;
        
        m_ArrCodeParms[RateIndexes[j]].TaxCalculated = m_ArrCodeParms[RateIndexes[j]].TaxDue;
        m_ArrCodeParms[RateIndexes[j]].TaxPaid = 0;
      end;
  
      j = j + 1;
    end;

  END;

  PRIVATE MACRO РассчитатьДоходыИВычеты(RateIndexes)
    var arr = TArray();
    var РНБ = $0, ЧНБ = $0;
    var i = 0, j = 0, k = 0, z = 0;

    if(RateIndexes == NULL)
      RateIndexes = TArray();
    end;
    
    m_PlusSum  = $0; 
    m_MinusSum = $0;

    m_BeginDate = date(1,1,m_CurrYear);

    //собрать значения доходов и вычетов
    if(m_CurrSign == 1)
      while(m_BeginDate <= m_RepDate)
        if(this.Month(m_BeginDate) == 12)
          m_EndDate = date(1,1,m_CurrYear+1)-1; //последний день года
        else
          m_EndDate = date(1,this.Month(m_BeginDate)+1,m_CurrYear)-1; //последний день месяца
        end;

        ДобавитьВсеПараметры(false, RateIndexes);
        РассчитатьИтоговыеЗначения(RateIndexes);
        РассчитатьПараметрыДляПечати(RateIndexes);

        m_BeginDate = m_EndDate + 1; //переходим в следующий месяц
      end;
    end;

    if( m_CurrSign == 2 )
      //разносим отрицательные ЧНБ 
      var index = -1;
      if(m_InfoRate != 0)
        index = IndexOfRate(m_ArrCodeParms, Rate(m_InfoRate));
        if(index >= 0)
          AddRateIndex(RateIndexes, index);
        end;
      end;

      i = 0;
      while(i < RateIndexes.Size)
        arr.Size = 0;
        j = 0;
        while( j < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr.Size )
          
          //по следующим месяцам того же кода дохода
          if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ < 0.0)
          
            k = j + 1;
            while((k < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr.size()) and (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ < 0.0))
              if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode == m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSCode) and
                 (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ > 0.0)
                )
                if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ >= abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ))
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ - abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ);
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes[0].MSnnn = m_ArrCodeParms[i].NPTXCodeParmArr[j].PSnnn;
                  end;
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusSum + abs(m_ArrCodeParms[i].NPTXCodeParmArr[j].ЧНБ);
                  end;
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ = 0.0;
                else
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ + m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ;
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSnnn + Abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ);
                  end;
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSnnn;
                  end;
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ = 0.0;
                end;
              end;
              k = k + 1;
            end;
          end;
  
          //по предыдущим месяцам того же кода дохода
          if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ < 0.0)
            k = j - 1;
            while((k >= 0) and (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ < 0.0))
              if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode == m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSCode) and
                 (m_ArrCodeParms[i].NPTXCodeParmArr[k].ЧНБ > 0.0)
                )
                if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ >= abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ))
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ - abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ);
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSnnn;
                  end;
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes[0].MSnnn + abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ);
                  end;
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ = 0.0;
                else
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ + m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ;
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSnnn + Abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ);
                  end;
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSnnn;
                  end;
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ = 0.0;
                end;
              end;
              k = k - 1;
            end;
          end;
  
          //по такому же, а потом следующим месяцам любых кодов дохода
          if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ < 0.0)
            k = j;
            while((k < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr.size()) and (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ < 0.0))
              if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode != m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSCode) and
                 (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ > 0.0)
                )
                if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ >= abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ))
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ - abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ);
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSnnn;
                  end;
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes[0].MSnnn + abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ);
                  end;
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ = 0.0;
                else
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ + m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ;
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSnnn + Abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ);
                  end;
                  if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes.Size > 0)
                     m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MinusCodes[0].MSnnn = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSnnn;
                  end;
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ = 0.0;
                end;
              end;
              k = k + 1;
            end;
          end;

          //по предыдущим месяцам любых кодов дохода
          if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ < 0.0)
            k = j - 1;
            while((k >= 0) and (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ < 0.0))
              if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode != m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSCode) and
                 (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ > 0.0)
                )
                if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ >= abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ))
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ - abs(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ);
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ = 0.0;
                else
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ + m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ;
                  m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].ЧНБ = 0.0;
                end;
              end;

              k = k - 1;
            end;
          end;

          j = j + 1;
        end;

        if(m_InfoRate == INFORATE_TOTAL)
          //Выстраиваем суммы следующей последовательности - сначала коды 2640 и 2641 помесячно (в возрастающем хронологическом порядке)
          var TotalRateIndex = IndexOfRate(m_ArrCodeParms, Rate(INFORATE_TOTAL));
          j = 0;
          while(j < m_ArrCodeParms[TotalRateIndex].NPTXCodeParmArr.size)
            if((m_ArrCodeParms[TotalRateIndex].NPTXCodeParmArr[j].PSCode == 2640) or (m_ArrCodeParms[TotalRateIndex].NPTXCodeParmArr[j].PSCode == 2641))
              arr[arr.size] = NPTXPlusCodeParm(m_ArrCodeParms[TotalRateIndex].NPTXCodeParmArr[j].Month, m_ArrCodeParms[TotalRateIndex].NPTXCodeParmArr[j].PSCode,
                                               m_ArrCodeParms[TotalRateIndex].NPTXCodeParmArr[j].PSnnn, m_ArrCodeParms[TotalRateIndex].NPTXCodeParmArr[j].ЧНБ);
            end;

            j = j + 1;
          end;
        end;

        //теперь все остальные
        j = 0;
        while(j < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr.Size)
          if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode != 2640) and (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode != 2641)) //для 9/15 этих кодов не бывает, а для общей они уже занесены
            arr[arr.size] = NPTXPlusCodeParm(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].Month, m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode,
                                             m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSnnn, m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].ЧНБ);
          end;
  
          j = j + 1;
        end;

        РНБ = 100.0 * TaxDue_n(RateIndexes[i]) / m_ArrCodeParms[RateIndexes[i]].Rate;

        /*В текстовом виде данные отличаются от Excel, необходимо пересчитать новые значения
          общей суммы дохода и налоговой базы после корректировки строк */
        var m_PlusSum_n = 0.0;
        var m_MinusSum_n = 0.0;
        
        //массив сформирован - теперь "снизу" начнет корректировать строки в зависимости от вхождения в ЧНБ
        if(arr.size())
          z = arr.size()-1;
          while(z >= 0)
/*            if((arr[z].PSCode != NULL) AND (РНБ > $0))
              ЧНБ = arr[z].ЧНБ;
              if(ЧНБ > РНБ)
                arr[z].PSnnn = РНБ;
                РНБ = $0;
              else
                arr[z].PSnnn = ЧНБ;
                РНБ = РНБ - ЧНБ;
              end;  
            else
              arr[z].PSnnn = NULL;
            end;
*/
            /*Считаем новое значения общей суммы*/
            if(NOT (arr[z].PSnnn == NULL))
               m_PlusSum_n = m_PlusSum_n + arr[z].PSnnn;
            end;
            /*if(NOT (arr[z].MSnnn == NULL))
               m_MinusSum_n = m_MinusSum_n + arr[z].MSnnn;
            end;*/

            var l = 0;
            while(l < arr[z].MinusCodes.Size)
               m_MinusSum_n = m_MinusSum_n + arr[z].MinusCodes[l].MSnnn;
               l = l + 1;
            end;
  
            z = z - 1;
          end;
        end;

        m_ArrCodeParms[RateIndexes[i]].PlusSum = m_PlusSum_n;
        m_ArrCodeParms[RateIndexes[i]].MinusSum = m_MinusSum_n;
        
        m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr = TArray(arr);

        i = i + 1;
      end;

      РассчитатьИтоговыеЗначения(RateIndexes);
    end;

    if( m_CurrSign == 1 )
      
      /*i = 0;
      while( i < RateIndexes.size() )

        //разносим расходы по месяцам, если они больше доходов 
        j = 0;
        while(j < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr.size())
           //по предыдущим месяцам того же кода дохода
           if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN > m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN)
             k = j - 1;
             while((k >= 0) and (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN > m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN))
               if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode == m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSCode) and
                  (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN)
                 )
                 if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN) >= (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN))               
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN + (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN);
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN;
                 //else /*PDV 530179*/
//                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParm[k].PSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN);
//                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN;
                 end;
               end;
               k = k - 1;
             end;
           end;
   
           //по следующим месяцам того же кода дохода     // Возможно, что данная часть не нужна(для следующих месяцев), сделана для аналогии с признаком 2
           if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN > m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN)
             k = j + 1;
             while((k < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr.size()) and (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN > m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN))
               if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode == m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSCode) and
                  (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN)
                 )
                 if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN) >= (m_ArrCodeParms[Rateindexes[i]].NPTXCodeParmArr[j].MSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN))               
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN + (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN);
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN;
                 else
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN);
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN;
                 end;
               end;
               k = k + 1;
             end;
           end;
   
           //по предыдущим месяцам другого кода дохода
           if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN > m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN)
             k = j - 1;
             while((k >= 0) and (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN > m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN))
               if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode != m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSCode) and
                  (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN)
                 )
                 if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN) >= (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN))               
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN + (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN);
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN;
                 else
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN);
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN;
                 end;
               end;
               k = k - 1;
             end;
           end;
   
           //по следующим месяцам другого кода дохода        // Возможно, что данная часть не нужна(для следующих месяцев), сделана для аналогии с признаком 2
           if(m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN > m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN)
             k = j + 1;
             while((k < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr.size()) and (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN > m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN))
               if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSCode != m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSCode) and                  
                  (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN < m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN)
                 )
                 if((m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN) >= (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN))               
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN + (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN);
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].PSNNN;
                 else
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[j].MSNNN - (m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN - m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN);
                   m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].MSNNN = m_ArrCodeParms[RateIndexes[i]].NPTXCodeParmArr[k].PSNNN;
                 end;
               end;
               k = k + 1;
             end;
           end;
           j = j + 1;
        end;
        i = i + 1;
      end;*/
      РассчитатьИтоговыеЗначения(RateIndexes);
    end;

    return RateIndexes;
  END; 

  MACRO ClearData()
    ClearData();
    m_LastOpCode = null;
    m_TaxDue1Arr.size = 0;
  END;

  MACRO CalcData(InfoRate, Sign, RateIndexes)
    var TaxDue1Arr = TArray();
    m_CurrSign = Sign;
    m_InfoRate = InfoRate;

    TaxDue1Arr = TArray(m_TaxDue1Arr);
    m_CurrSign = Sign; 
    m_TaxDue1Arr = TArray(TaxDue1Arr);
    RateIndexes = РассчитатьДоходыИВычеты(RateIndexes);
    return RateIndexes;
  END;

  MACRO GetLastNPTOCode()
    var query, Select, DataSet;
    
    if(m_LastOpCode == NULL)
      query =   " select t_Code as OpCode from dnptxop_dbt "
              + "  where t_DocKind = ? "
              + "    and t_Client = ? "
              + "    and t_OperDate <= ? "
              + "  order by t_OperDate desc";

      Select =  RsdCommand(query);
      Select.addParam( "", RSDBP_IN, DL_CALCNDFL );
      Select.addParam( "", RSDBP_IN, this.ClientID() );
      Select.addParam( "", RSDBP_IN, m_RepDate );

      DataSet = TRsbDataSet(Select);
      if(DataSet.moveNext())
        m_LastOpCode = DataSet.OpCode;
      end;
    end;

    return m_LastOpCode;
  END;

  MACRO PrintNumOper()
    var operNum = 0;
    if(Form.GetFieldValue( PNFLD_TXPIT2_SING_NUM ) == UNSET_CHAR)
       operNum =  GetLastNPTOCode();
    else
       operNum = GetPrintNumber(Form.GetFieldValue( PNFLD_TXPIT2_NUMBER_OPER));
    end;

    return operNum;
  END;
       
  MACRO MinusSum()
    return m_MinusSum;
  END;      
  
  InitNPTXRepCalcCommon(_RepDate, _Investor, true, null, null, false, false);
END;

PRIVATE CLASS (TaxReportBase) NPTX_Pit2_Report_Base(TemplName)
  
  PRIVATE CONST FORMULA = "formula=";
  PRIVATE CONST DecimalSeparator = GetLocaleInfo(0,LOCALE_SDECIMAL, false );
  var m_RepDate;
  var m_RepCalc, m_LastOpCode;
  var m_CurrSheetName = "";
  var m_FirstPos = 0, m_LastPos = 0;
  var m_CurrSign = 0;
  var NeedBreak = false;
  var GeneratedFilesCount = 0;
  
  MACRO CReport_DataExist()
    return not NeedBreak;
  END;
  
  PRIVATE MACRO PrintMode():INTEGER
     return Form.GetFieldValue( PNFLD_TXPIT2_PRINTMETHOD );
  END;
  
  PRIVATE MACRO BeginReport( NumCopy:INTEGER )
    CreateTotalBook();
  END;

  PRIVATE MACRO EndReport()
    if (not NeedBreak)
    if((POI_MODE) AND (ItogSym!=""))
      SetLastTotalBookName(ItogSym);
      ItogSym = "";
    end;
    SaveTotalBook();
    if( m_UseTemplate )
      ReplaceAndCalculate( FORMULA, "=" );
    end;
    else
       m_ObjTemplateXLS.SheetDelete(1);
    end;
  END;

  PRIVATE MACRO FormulaSUM():string
     var RetVal = "";
     if( m_ObjTemplateXLS.ExcelLanguageInterface != EXCEL_INTERFACE_RUS )
        RetVal = "SUM";
     else
        RetVal = "СУММ";
     end;

     return RetVal;
  END;

  PRIVATE MACRO FormulaMAX():string
     var RetVal = "";
     if( m_ObjTemplateXLS.ExcelLanguageInterface != EXCEL_INTERFACE_RUS )
        RetVal = "MAX";
     else
        RetVal = "МАКС";
     end;

     return RetVal;
  END;

  PRIVATE MACRO FormulaIF():string
     var RetVal = "";
     if( m_ObjTemplateXLS.ExcelLanguageInterface != EXCEL_INTERFACE_RUS )
        RetVal = "IF";
     else
        RetVal = "ЕСЛИ";
     end;

     return RetVal;
  END;

  PRIVATE MACRO FormulaROUND():string
     var RetVal = "";
     if( m_ObjTemplateXLS.ExcelLanguageInterface != EXCEL_INTERFACE_RUS )
        RetVal = "ROUND";
     else
        RetVal = "ОКРУГЛ";
     end;

     return RetVal;
  END;

  MACRO ReplaceSeparator( Str:@string, Separator:string )
     if( DecimalSeparator != Separator)
        var index_ = Index(Str, Separator);
        while( (index_ != 0) and (index_ <= strlen(Str)) )
           Str = substr(Str, 1, index_ - 1) + DecimalSeparator + substr(Str, index_ + 1, strlen(Str) - 1);
           index_ = Index(Str, Separator);
        end;
     end;
  END;

  PRIVATE MACRO F( Str:string ):string

     /* заменим разделитель целой и дробной частей */
     ReplaceSeparator( @Str, "." );
     ReplaceSeparator( @Str, "," );

     return FORMULA + Str;
  END;

  PRIVATE MACRO ПечататьЗаголовок(Отступ)//переопределять
  END;

  PRIVATE MACRO ПечататьЗаголовокПриложения(Отступ)
  END;

  PRIVATE MACRO ПечататьСправку(InfoRate)//переопределять
  END;

  PRIVATE MACRO ПечататьПриложение(InfoRate)
  END;

  PRIVATE MACRO ПечататьИТОГ(InfoRate)//переопределять
  END;

  PRIVATE MACRO ПечататьИТОГПриложения(InfoRate)
  END;

  macro GetFilesCount(): Integer
    return GeneratedFilesCount;
  end;

  PRIVATE MACRO Create()
    var query, Num = 0, count = 0;
    var InvestorArray = Form.GetFieldValue( PNFLD_TXPIT2_INVESTORCODE);
    var Sign1 = Form.GetFieldValue( PNFLD_TXPIT2_SIGN1);
    var Sign2 = Form.GetFieldValue( PNFLD_TXPIT2_SIGN2);
    var PrevName = "", CurrName = "", CntEqualNames = 1;
    var IsPrintSign2 = false;
    var i = 0, j = 0, k = 0;
    var arr;

    m_RepDate = date(Form.GetFieldValue(PNFLD_TXPIT2_ENDDATE));

    m_RepCalc = NPTXRepCalc(m_RepDate, InvestorArray);
    SetActiveSheet( IIF(m_RepDate <= date(31, 12, 2017), "2-НДФЛ", "Справка"));
    count = m_RepCalc.Count();  
    
    if( count > 0)
	  GeneratedFilesCount = 1;
      var numCount = CheckOperNum( Form.GetFieldValue( PNFLD_TXPIT2_NUMBER_OPER));
      if( (Form.GetFieldValue( PNFLD_TXPIT2_SING_NUM ) == SET_CHAR) and
          ( numCount < 0) )
        if(not GetTrue(true, "Последовательная нумерация невозможна.|Продолжить?"))
           NeedBreak = true;  
           return;
        end;
      end;

      Num = 0;
      Var PoiNum = 0;
      InitProgress( count, "2-НДФЛ по ц/б", "2-НДФЛ по ц/б" );
      var Sym= "";      
      var Sym_= "";      
      var OldSym= ""; 
      var isFirst = true;     
      while( m_RepCalc.Next() )
        //для каждого клиента обновляем список примечаний по ставке физ.нерез. по дивидендам
        m_RepCalc.Refresh_TaxDivValArray();
        m_RepCalc.ClearData();
        
        m_RepCalc.m_countOfNum  = numCount;
        
        m_CurrSign = 0;
   
        var CurrSheetName = m_RepCalc.GetCurrName();
        IF(POI_MODE)
          if(isFirst)
            Sym = Substr(CurrSheetName,1,3);
          end;
            Sym_ = Substr(CurrSheetName,1,3);
          ItogSym = Sym + "-" + Sym_;
          IF ( PoiNum == POI_SIZE_PACK )
            SaveSubTotalBook(ItogSym,false);
            CreateTotalBook();
            GeneratedFilesCount = GeneratedFilesCount + 1;
            PoiNum = 1;
            isFirst = true;
          ELSE
            PoiNum = PoiNum + 1;
            isFirst = false;
          END;
          OldSym =Sym;
        END;
        UseNewSheetInTotalBook();
        
        if(sign1 == SET_CHAR)
          m_CurrSign = 1;
         
          /****************************************************/
          /* изменено:                                        */
          /*справка 1 для ставки 9 (15)%   заменяется на      */
          /* справка для ставки 9%                            */
          /* и справки для КАЖДОГО значения примечания        */
          /* "Налоговая ставка для дивидендов в депозитарии"  */
          /* за период отчёта                                 */        
          /****************************************************/
          
          /* Если короче:                                    */
          /* Вначале отчитываемся по всем из m_TaxDivValArray*/
          /* затем по НКРФ (15%)                             */
          
          /* 9% / ставке по дивидендам для нерезидентов. %*/

          if (m_RepCalc.m_TaxDivValArray.size > 0)
            while (m_RepCalc.m_TaxDivValArrayCurIndex < m_RepCalc.m_TaxDivValArray.size)
              m_RepCalc.CalcData(INFORATE9_NOTRES_DIV, m_CurrSign);
              m_RepCalc.m_TaxDivValArrayCurIndex = m_RepCalc.m_TaxDivValArrayCurIndex + 1;
            end;
          end;
          /* последний посчитанный не обрабатывается в основном цикле                       */
          /* причина - особенности реализации, доступа к элементу массива по индексу и т.д. */
          /*         послединй посчитанный - будет по НКРФ                                  */ 
          m_RepCalc.CalcData(INFORATE9_NOTRES_DIV, m_CurrSign);

          //справка по общей ставке
          m_RepCalc.CalcData(INFORATE_TOTAL, m_CurrSign);

          //справка по ставке 35%(только для резидентов)
          if( m_RepCalc.ResidenceStatus() == 1 )/*по ставке 35%(только для резидентов)*/
             m_RepCalc.CalcData(INFORATE_35, m_CurrSign);
          end;

          var DepoRateIndexes = TArray();
          if(m_RepCalc.IsDepoClient())
            DepoRateIndexes = m_RepCalc.CalcData(0, m_CurrSign);
          end;

          j = 0;
          while(j < m_RepCalc.m_PrintArrCodeParms.Size)
           // if(m_RepCalc.PlusSum(j) > 0)
              m_CurrSheetName = CurrSheetName + " " + string(m_RepCalc.m_PrintArrCodeParms[j].Rate) + "% по общ.";
              UseNewSheetInTotalBook();
              ПечататьЗаголовок(2);
  
              ПечататьСправку(j);
  
              ПечататьИТОГ(j);
  
              if(m_RepDate > date("01.01.2018"))
                 k = 0;
  
                 while(k < m_RepCalc.m_PrintArrCodeParms[j].NPTXCodeParmArr.size())
                    ПечататьЗаголовокПриложения(j);
                    k = ПечататьПриложение(m_RepCalc.m_PrintArrCodeParms[j].NPTXCodeParmArr, k);
                    ПечататьИТОГПриложения();
                 end;
              end;
  
              IsPrintSign2 = true;
          //  end;
            j = j + 1;
          end;

        end;

        if( sign2 == SET_CHAR )
          m_CurrSign = 2;

          //справка для ставки 9 (15)%
          m_RepCalc.CalcData(INFORATE9_NOTRES_DIV, m_CurrSign);

          //справка по общей ставке
          m_RepCalc.CalcData(INFORATE_TOTAL, m_CurrSign);

          if(m_RepCalc.IsDepoClient())
            m_RepCalc.CalcData(0, m_CurrSign, DepoRateIndexes);
          end;
  
          j = 0;
          while(j < m_RepCalc.m_ArrCodeParms.Size)
            if(m_RepCalc.TaxDue(j) > 0)
              m_CurrSheetName = CurrSheetName + " " + string(m_RepCalc.m_ArrCodeParms[j].Rate) + "% по общ.";
              ПечататьЗаголовок(2);
  
              ПечататьСправку(j);
  
              ПечататьИТОГ(j);
  
              if(m_RepDate > date("01.01.2018"))
                 k = 0;
  
                 while(k < m_RepCalc.m_ArrCodeParms[j].NPTXCodeParmArr.size())
                    ПечататьЗаголовокПриложения(j);
                    k = ПечататьПриложение(m_RepCalc.m_ArrCodeParms[j].NPTXCodeParmArr, k);
                    ПечататьИТОГПриложения();
                 end;
              end;
  
              IsPrintSign2 = true;
            end;
            j = j + 1;
          end;
        end;
        m_RepCalc.m_count = m_RepCalc.m_count + 1;

        UseProgress( Num = Num + 1 );
      end; 

      RemProgress();

      if((sign1 == UNSET_CHAR) and (sign2 == SET_CHAR) and (IsPrintSign2 == false))
        PrintFormatString( NULL, "N1_MsgNotData", "Нет данных, удовлетворяющих параметрам отчета", null);
        CopyAllSheetInTotalBook( IIF(m_RepDate <= date(31, 12, 2017), "2-НДФЛ", "Справка"), false, "N1_MsgNotData", 0 );
      end;

    else
      PrintFormatString( NULL, "N1_MsgNotData", "Нет данных, удовлетворяющих параметрам отчета", null);
      CopyAllSheetInTotalBook( IIF(m_RepDate <= date(31, 12, 2017), "2-НДФЛ", "Справка"), false, "N1_MsgNotData", 0 );
    end;

  END;

  initDL_CReportTemplate( NULL, TemplName , null, null, null, POI_MODE);
END; //NPTX_Pit2_Report_Base

PRIVATE CLASS (NPTX_Pit2_Report_Base) NPTX_Pit2_Report_2018
  var NumPage = 1;
  var OldClientID = -1, OldClientIDApp = -1;
  var NumPageApp = 1;

  PRIVATE MACRO ПечататьЗаголовок(Отступ)
    var OurInn = m_RepCalc.OurInn();
    var OurKPP = m_RepCalc.OurKPP();
    var OperNdfl = m_RepCalc.PrintNumOper();
    var Year = m_RepCalc.CurrYear();
    var Indication = m_CurrSign;
    var OurFNScode = m_RepCalc.OurFNScode();
    var OurName = m_RepCalc.OurName();
    var OurOKTMO = DL_StrCut( m_RepCalc.OurOKTMO(), 11, "-", true );
    var OurPhone = m_RepCalc.OurPhone();

    if(m_RepCalc.ClientID() == OldClientID)
       NumPage = Numpage + 1;
    else
       NumPage = 1;
       OldClientID = m_RepCalc.ClientID();
    end;


    SetActiveSheet("Справка");

    PrintOneRow("N1_OurInn", OurInn, 12);

    PrintOneRow("N1_OurKPP", OurKPP, 9);

    var NumPageStr = L_Z(NumPage, 3);
    PrintOneRow("N1_NumPage", NumPageStr, 3);

    PrintOneRow("N1_OperNdfl", OperNdfl, 7);

    PrintOneRow("N1_Year", string(Year), 4);

    PrintOneRow("N1_Indication", string(Indication), 1);

    PrintOneRow("N1_OurFNScode", OurFNScode, 4);

    PrintOneRow("N1_OurName", OurName, 120);

    PrintOneRow("N1_OurOKTMO", OurOKTMO, 11);

    PrintOneRow("N1_OurPhone", OurPhone, 20);

    CopyAllSheetInTotalBook("Справка", false, "N1_Header", Отступ, m_CurrSheetName);

  END;

  PRIVATE MACRO ПечататьЗаголовокПриложения(Index)
    if(m_RepCalc.ClientID() == OldClientIDApp)
       NumPageApp = NumPageApp + 1;
    else
       NumPageApp = 1;
       OldClientIDApp = m_RepCalc.ClientID();
    end;
    var NumPageStr = L_Z(NumPageApp, 3);

    SetActiveSheet("Приложение");

    PrintOneRow("N2_OurInn", m_RepCalc.OurInn(), 12);
    PrintOneRow("N2_OurKPP", m_RepCalc.OurKPP(), 9);
    PrintOneRow("N2_NumPage", NumPageStr, 3);
    PrintOneRow("N2_OperNdfl", m_RepCalc.PrintNumOper(), 7);
    PrintOneRow("N2_Year", string(m_RepCalc.CurrYear()), 4);
    PrintOneRow("N2_Rate", string(Int(m_RepCalc.m_PrintArrCodeParms[Index].Rate)), 2);

    CopyAllSheetInTotalBook("Приложение", false, "N2_Header", 0, m_CurrSheetName + "_Приложение");
  END;

  PRIVATE MACRO ПечататьРаздел1()
    PrintOneRow("N1_ClientINN", m_RepCalc.ClientInn(), 12);
    PrintOneRow("N1_SecondName", m_RepCalc.LastName(), 36);
    PrintOneRow("N1_FirstName", m_RepCalc.FirstName(), 36);
    PrintOneRow("N1_MiddleName", m_RepCalc.MiddleName(), 36);
    PrintOneRow("N1_ResidenceStatus", string(m_RepCalc.ResidenceStatus()), 1);

    var Day, Month, Year;
    DateSplit(Date(m_RepCalc.DateBirth()), Day, Month, Year);
    Day = L_Z(Day, 2);
    Month = L_Z(Month, 2);
    PrintOneRow("N1_DateBirth", Day + Month + Year, 8);

    PrintOneRow("N1_Citizenship", string(m_RepCalc.Citizenship()), 3);
    PrintOneRow("N1_DocumentType", string(m_RepCalc.DocumentType()), 2);
    PrintOneRow("N1_DocumentNumber", string(m_RepCalc.DocumentNumber()), 20);

    CopyAllSheetInTotalBook("Справка", false, "N1_Part1", 0, m_CurrSheetName);
  END;

  PRIVATE MACRO ПечататьРаздел2(Index)
    PrintOneRow("N1_Rate", string(Int(m_RepCalc.m_PrintArrCodeParms[Index].Rate)), 2);
    PrintOneSumRow("N1_TotalPlus", money(m_RepCalc.PlusSum(Index)), 17, true);
    PrintOneSumRow("N1_TaxBaseSum", money(m_RepCalc.TaxBaseSum(Index)), 17, true);
    PrintOneSumRow("N1_TaxPaid", Round(money(m_RepCalc.TaxPaid(Index)), 0), 11, false);
    PrintOneSumRow("N1_TaxCalculated", Round(money(m_RepCalc.TaxCalculated(Index)), 0), 12, false);
    PrintOneSumRow("N1_TaxToReturnDue", Round(money(m_RepCalc.TaxToreturnDue(Index)), 0), 11, false);
    PrintOneSumRow("N1_TaxPaid2", Round(m_RepCalc.TaxPaid(Index), 0), 11, false);
    PrintOneSumRow("N1_TaxDue", Round(money(m_RepCalc.TaxDue(Index)), 0), 11, false);

    CopyAllSheetInTotalBook("Справка", false, "N1_Part2", 0, m_CurrSheetName);
  END;

  PRIVATE MACRO ПечататьРаздел3()
    var MinusG_618 = m_RepCalc.MinusG_618(), MinusG_619 = m_RepCalc.MinusG_619();
    var n = 1;
    if(m_CurrSign != 2)
       if(MinusG_618 != 0)
          PrintOneRow("N1_CodeMS1_", "618", 3);
          PrintOneSumRow("N1_MSnnn" + n + "_", MinusG_618, 9, true);
          n = n + 1;
       end;
       if(MinusG_619 != 0)
          n = 2;
          PrintOneRow("N1_CodeMS2_", "619", 3);
          PrintOneSumRow("N1_MSnnn" + n + "_", MinusG_619, 9, true);
       end;
    end;

    CopyAllSheetInTotalBook("Справка", false, "N1_Part3", 0, m_CurrSheetName);
  END;

  PRIVATE MACRO ПечататьИтог()
    if(NumPage == 1)
        PrintOneRow("N1_FirstPerson", m_RepCalc.FirstPerson(), 120);
    end;

    CopyAllSheetInTotalBook("Справка", false, "N1_Footer", 0, m_CurrSheetName);
  END;

  PRIVATE MACRO ПечататьСправку(Index)
    ПечататьРаздел1();
    ПечататьРаздел2(Index);
    ПечататьРаздел3();
  END;

  PRIVATE MACRO ПечататьПриложение(arr, i)
    var j = 0;

    while( (i < arr.size()) and (j < 15) )
      if( ((arr[i].PSnnn == null) or (arr[i].PSnnn == $0)) and (arr[i].MinusCodes.Size == 0) )
           //не печатать
      else
        PrintOneRow("N2_Month" + string(j + 1) + "_", string(iif((arr[i].Month != null) and (arr[i].PSCode != null) and ((arr[i].PSnnn != 0) or (arr[i].MSnnn != 0)), arr[i].Month, "")), 2);
        PrintOneRow("N2_PlusCode" + string(j + 1) + "_", string(iif((arr[i].PSCode != null) and (arr[i].PSnnn != 0), arr[i].PSCode, "")), 4);
        PrintOneSumRow("N2_PlusSum" + string(j + 1) + "_", iif((arr[i].PSnnn != null) and (arr[i].PSCode != null)  and (arr[i].PSnnn != 0), Money(arr[i].PSnnn), ""), 17, true);
        if(arr[i].MinusCodes.Size > 0)
           PrintOneRow("N2_MinusCode" + string(j + 1) + "_", string(iif((arr[i].MinusCodes[0].MSCode != null)  and (arr[i].MinusCodes[0].MSnnn != 0), arr[i].MinusCodes[0].MSCode, "")), 3);
           PrintOneSumRow("N2_MinusSum" + string(j + 1) + "_", iif((arr[i].MinusCodes[0].MSnnn != null) and (arr[i].MinusCodes[0].MSCode != null) and (arr[i].MinusCodes[0].MSnnn != 0), Money(arr[i].MinusCodes[0].MSnnn), ""), 16, true);
           var k = 1;
           while(k < arr[i].MinusCodes.Size)
              PrintOneRow("N2_MinusCode" + string(j + 1) + "_", string(iif((arr[i].MinusCodes[k].MSCode != null)  and (arr[i].MinusCodes[k].MSnnn != 0), arr[i].MinusCodes[k].MSCode, "")), 3);
              PrintOneSumRow("N2_MinusSum" + string(j + 1) + "_", iif((arr[i].MinusCodes[k].MSnnn != null) and (arr[i].MinusCodes[k].MSCode != null) and (arr[i].MinusCodes[k].MSnnn != 0), Money(arr[i].MinusCodes[k].MSnnn), ""), 16, true);
              k = k + 1;
              j = j + 1;
           end;
        else
           PrintOneRow("N2_MinusCode" + string(j + 1) + "_", "", 3);
           PrintOneSumRow("N2_MinusSum" + string(j + 1) + "_", "", 16, true);
        end;
      end;

      i = i + 1;
      j = j + 1;
    end;

    CopyAllSheetInTotalBook("Приложение", false, "N2_Data", 0, m_CurrSheetName + "_Приложение");

    return i;
  END;

  PRIVATE MACRO ПечататьИТОГПриложения()
    CopyAllSheetInTotalBook("Приложение", false, "N2_Footer", 0, m_CurrSheetName + "_Приложение");
  END;

  initNPTX_Pit2_Report_Base("Report_NPTXPit2_2018.xls" );
END;

PRIVATE CLASS (NPTX_Pit2_Report_Base) NPTX_Pit2_Report_2018_Client
  var NumPage = 1;
  var OldClientID = -1;

  PRIVATE MACRO ПечататьЗаголовок()
    var day, month, year;

    SetActiveSheet("Справка");
    
    datesplit(m_RepDate, day, month, year);
    day = L_Z(day, 2);
    month = L_Z(month, 2);
    PrintFormatString(NULL, "N1_Year", M_RepCalc.CurrYear());
    PrintFormatString(NULL, "N1_PrintDate1", day,
                            "N1_PrintDate2", month,
                            "N1_PrintDate3", string(year));

    CopyAllSheetInTotalBook(NULL, false, "N1_Header", 0, m_CurrSheetName);
  END;

  PRIVATE MACRO ПечататьРаздел1()
    PrintFormatString(NULL, "N1_OurOKTMO", m_RepCalc.OurOKTMO(),
                            "N1_OurPhone", m_RepCalc.OurPhone(),
                            "N1_OurInn",   m_RepCalc.OurInn(),
                            "N1_OurKPP",   m_RepCalc.OurKPP(),
                            "n1_OurName",  m_RepCalc.OurName()
                            );

    CopyAllSheetInTotalBook(NULL, false, "N1_Part1", 0, m_CurrSheetName);
  END;

  PRIVATE MACRO ПечататьРаздел2()
    PrintFormatString(NULL, "N1_ClientINN",       m_RepCalc.ClientInn(),
                            "N1_SecondName",      m_RepCalc.LastName(),
                            "N1_FirstName",       m_RepCalc.FirstName(),
                            "N1_MiddleName",      m_RepCalc.MiddleName(),
                            "N1_ResidenceStatus", m_RepCalc.ResidenceStatus(),
                            "N1_DateBirth",       m_RepCalc.Datebirth(),
                            "N1_CitizenShip",     m_RepCalc.Citizenship(),
                            "N1_DocumentType",    m_RepCalc.DocumentType(),
                            "N1_DocumentNumber",  m_RepCalc.DocumentNumber()
                            );

    CopyAllSheetInTotalBook(NULL, false, "N1_Part2", 0, m_CurrSheetName);
  END;

  PRIVATE MACRO ПечататьРаздел3(Index, arr)
    PrintFormatString(NULL, "N1_Rate", Int(m_RepCalc.m_PrintArrCodeParms[Index].Rate));
    var i = 0;
    var j = 1;
    
    while((i < arr.size()) and (j <= 30))
       if(arr[i].MinusCodes.Size > 0)
          PrintFormatString(NULL, "N1_Month" + string(j),      arr[i].Month,
                                  "N1_PlusCode" + string(j),   arr[i].PSCode,
                                  "N1_PSnnn" + string(j),      arr[i].PSnnn,
                                  "N1_MinusCode" + string(j),  IIF(arr[i].MinusCodes[0].MSCode != NULL, arr[i].MinusCodes[0].MSCode, ""),
                                  "N1_MSnnn" + string(j),      IIF(arr[i].MinusCodes[0].MSnnn > 0.0, arr[i].MinusCodes[0].MSnnn, ""));

          var k = 0;
          while(k < arr[i].MinusCodes.Size)
             j = j + 1;
             PrintFormatString(NULL, "N1_Month" + string(j),      arr[i].Month,
                                     "N1_PlusCode" + string(j),   arr[i].PSCode,
                                     "N1_PSnnn" + string(j),      arr[i].PSnnn,
                                     "N1_MinusCode" + string(j),  IIF(arr[i].MinusCodes[k].MSCode != NULL, arr[i].MinusCodes[k].MSCode, ""),
                                     "N1_MSnnn" + string(j),      IIF(arr[i].MinusCodes[k].MSnnn > 0.0, arr[i].MinusCodes[k].MSnnn, ""));

             k = k + 1;
          end;
       else
          PrintFormatString(NULL, "N1_Month" + string(j),      arr[i].Month,
                                  "N1_PlusCode" + string(j),   arr[i].PSCode,
                                  "N1_PSnnn" + string(j),      arr[i].PSnnn,
                                  "N1_MinusCode" + string(j),  "",
                                  "N1_MSnnn" + string(j),      "");
       end;

       i = i + 1;
       j = j + 1;
    end;

    CopyAllSheetInTotalBook(NULL, false, "N1_Part3", 0, m_CurrSheetName);

  END;

  PRIVATE MACRO ПечататьРаздел4()
    CopyAllSheetInTotalBook(NULL, false, "N1_Table4Header", 0, m_CurrSheetName);

    RegisterTable("N1_Table4", NULL,
                  "N1_CodeD1",
                  "N1_SumD1");

     if ((IIS_CONTRACTS == "X") and (OTHER_CONTRACTS == "X"))
        PrintTableLine("N1_CodeD1", IIF( m_RepCalc.MinusG_618() != 0,"618",""), null,
                       "N1_SumD1",  m_RepCalc.MinusG_618(), null,
                       "N1_CodeD2", IIF( m_RepCalc.MinusG_619()!= 0, "619",""), null,
                       "N1_SumD2",  m_RepCalc.MinusG_619(), null,
                       "N1_CodeD3",  "", null,
                       "N1_SumD3",  "", null,
                       "N1_CodeD4",  "", null,
                       "N1_SumD4",  "", null);
     elif ((IIS_CONTRACTS == "X") and (OTHER_CONTRACTS != "X"))
       PrintTableLine("N1_CodeD1", IIF( m_RepCalc.MinusG_619()!= 0, "619",""), null,
                      "N1_SumD1",  m_RepCalc.MinusG_619(), null,
                      "N1_CodeD2",  "", null,
                      "N1_SumD2",  "", null,
                      "N1_CodeD3",  "", null,
                      "N1_SumD3",  "", null,
                      "N1_CodeD4",  "", null,
                      "N1_SumD4",  "", null);
     elif ((IIS_CONTRACTS != "X") and (OTHER_CONTRACTS == "X"))
       PrintTableLine("N1_CodeD1", IIF(m_RepCalc.MinusG_618() != 0,"618",""), null,
                      "N1_SumD1",  m_RepCalc.MinusG_618(), null,
                      "N1_CodeD2",  "", null,
                      "N1_SumD2",  "", null,
                      "N1_CodeD3",  "", null,
                      "N1_SumD3",  "", null,
                      "N1_CodeD4",  "", null,
                      "N1_SumD4",  "", null);
     end;

     EndTable();
     CopyAllSheetInTotalBook("Справка", false, GetTableRange(), 0, m_CurrSheetName);
  END;

  PRIVATE MACRO ПечататьРаздел5(Index)
     PrintFormatString(NULL, "N1_TotalPlus", m_RepCalc.PlusSum(Index),
                             "N1_TaxBaseSum", m_RepCalc.TaxBaseSum(Index),
                             "N1_TaxCalculated", Round(m_RepCalc.TaxCalculated(Index),0),
                             "N1_TaxPaid", Round(m_RepCalc.TaxPaid(Index),0),
                             "N1_TaxPaid1", Round(m_RepCalc.TaxPaid(Index),0),
                             "N1_Znp", Round(m_RepCalc.Znp(Index),0),
                             "N1_TaxToReturnDue", Round(m_RepCalc.TaxToReturnDue(Index),0)
                      );

     CopyAllSheetInTotalBook("Справка", false, "N1_Part5", 0, m_CurrSheetName, true);
  END;

  PRIVATE MACRO ПечататьРаздел6(Index:Integer)
     PrintFormatString(NULL, "N1_TotalPlus_NoTax", string(ExtRound(Min(ExtRound(m_RepCalc.TaxDue(Index), 0) / m_RepCalc.m_PrintArrCodeParms[Index].Rate * 100, m_RepCalc.TaxBaseSum(Index)), NULL, true)),
                             "N1_TaxDue", m_RepCalc.TaxDue(Index));
  END;

  MACRO ПечататьСправку(Index, arr)
    ПечататьРаздел1();
    ПечататьРаздел2();
    ПечататьРаздел3(Index, arr);
    ПечататьРаздел4();
    ПечататьРаздел5(Index);
    ПечататьРаздел6(Index);
  END;

  MACRO ПечататьИтог()
    PrintFormatString(NULL, "N1_FirstPerson", m_RepCalc.FirstPerson());
    CopyAllSheetInTotalBook("Справка", false, "N1_Footer", 0, m_CurrSheetName, true);
  END;

  MACRO Create()
    var query, Num = 0, count = 0;
    var InvestorArray = Form.GetFieldValue( PNFLD_TXPIT2_INVESTORCODE);
    var Sign1 = Form.GetFieldValue( PNFLD_TXPIT2_SIGN1);
    var Sign2 = Form.GetFieldValue( PNFLD_TXPIT2_SIGN2);
    var PrevName = "", CurrName = "", CntEqualNames = 1;
    var IsPrintSign2 = false;
    var i = 0, j = 0;
    var RateIndex = 0;
    var arr;

    m_RepDate = date(Form.GetFieldValue(PNFLD_TXPIT2_ENDDATE));

    m_RepCalc = NPTXRepCalc(m_RepDate, InvestorArray);
   
    SetActiveSheet("Справка");
    count = m_RepCalc.Count();  
    
    if( count > 0)
      GeneratedFilesCount = 1;
      var numCount = CheckOperNum( Form.GetFieldValue( PNFLD_TXPIT2_NUMBER_OPER));
      if( (Form.GetFieldValue( PNFLD_TXPIT2_SING_NUM ) == SET_CHAR) and
          ( numCount < 0) )
        if(not GetTrue(true, "Последовательная нумерация невозможна.|Продолжить?"))
           NeedBreak = true;  
           return;
        end;
      end;

      InitProgress( count, "Справка 2-НДФЛ для выдачи клиенту", "Справка 2-НДФЛ для выдачи клиенту" );
      Var PoiNum = 0;
      var Sym= "";      
      var Sym_= "";      
      var OldSym= ""; 
      var isFirst = true;     
      
      while( m_RepCalc.Next() )
        m_RepCalc.ClearData();
        m_RepCalc.m_countOfNum  = numCount;
        
        m_CurrSign = 0;

        m_CurrSheetName = m_RepCalc.GetCurrName();
        IF(POI_MODE)
          if(isFirst)
            Sym = Substr(m_CurrSheetName,1,3);
          end;
            Sym_ = Substr(m_CurrSheetName,1,3);
          ItogSym = Sym + "-" + Sym_;
          IF ( PoiNum == POI_SIZE_PACK)
            SaveSubTotalBook(ItogSym,false);
            CreateTotalBook();
			GeneratedFilesCount = GeneratedFilesCount + 1;
            PoiNum = 1;
            isFirst = true;
          ELSE
            PoiNum = PoiNum + 1;
            isFirst = false;
          END;
          OldSym =Sym;
        END;
        
        if(sign1 == SET_CHAR)
          m_CurrSign = 1;
         
          //справка для ставки 9 (15)%
          m_RepCalc.CalcData(INFORATE9_15, m_CurrSign);
      
          //справка по общей ставке
          m_RepCalc.CalcData(INFORATE_TOTAL, m_CurrSign);

          //справка по ставке 35%(только для резидентов)
          if( m_RepCalc.ResidenceStatus() == 1 )/*по ставке 35%(только для резидентов)*/
             m_RepCalc.CalcData(INFORATE_35, m_CurrSign);
          end;

          var DapoRateIndexes = TArray();
          if(m_RepCalc.IsDepoClient())
             DapoRateIndexes = m_RepCalc.CalcData(0, m_CurrSign, DapoRateIndexes);
          end;

          j = 0;
          while(j < m_RepCalc.m_PrintArrCodeParms.Size)
             if(m_RepCalc.PlusSum(j) != $0)
                UseNewSheetInTotalBook();
                ПечататьЗаголовок();
                ПечататьСправку(j, m_RepCalc.m_PrintArrCodeParms[j].NPTXCodeParmArr);
                ПечататьИТОГ();
             end;
             j = j + 1;
          end;
        end;

        if( sign2 == SET_CHAR )
          m_CurrSign = 2;
          
          //справка для ставки 9 (15)%
          m_RepCalc.CalcData(INFORATE9_15, m_CurrSign);

          //справка по общей ставке
          m_RepCalc.CalcData(INFORATE_TOTAL, m_CurrSign);

          if(m_RepCalc.IsDepoClient())
             m_RepCalc.CalcData(0, m_CurrSign, DapoRateIndexes);
          end;

          j = 0;
          while(j < m_RepCalc.m_ArrCodeParms.Size)
            if(m_RepCalc.TaxDue(j) > $0)  
              ПечататьЗаголовок();
              ПечататьСправку(j, m_RepCalc.m_ArrCodeParms[j].NPTXCodeParmArr);
              ПечататьИТОГ();
  
              IsPrintSign2 = true;
            end;
            j = j + 1;
          end;
        end;
        m_RepCalc.m_count = m_RepCalc.m_count + 1;

        UseProgress( Num = Num + 1 );
      end; 

      RemProgress();

      if((sign1 == UNSET_CHAR) and (sign2 == SET_CHAR) and (IsPrintSign2 == false))
        PrintFormatString( NULL, "N1_MsgNotData", "Нет данных, удовлетворяющих параметрам отчета", null);
        CopyAllSheetInTotalBook( IIF(m_RepDate <= date(31, 12, 2017), "2-НДФЛ", "Справка"), false, "N1_MsgNotData", 0 );
      end;

    else
      PrintFormatString( NULL, "N1_MsgNotData", "Нет данных, удовлетворяющих параметрам отчета", null);
      CopyAllSheetInTotalBook( IIF(m_RepDate <= date(31, 12, 2017), "2-НДФЛ", "Справка"), false, "N1_MsgNotData", 0 );
    end;

  END;

  initNPTX_Pit2_Report_Base("Report_NPTXPit2_2018_Client.xls");
END;

PRIVATE CLASS (NPTX_Pit2_Report_Base) NPTX_Pit2_Report_2015
  

  PRIVATE MACRO ПечататьЗаголовок(Отступ)
    
    PrintFormatString(NULL,
                      "N1_Year",       m_RepCalc.CurrYear(), // год
                      "N1_OperNdfl",   m_RepCalc.PrintNumOper(), // № операции 
                      "N1_PrintDate",  m_RepDate,  // Дата формирования отчета

                      "N1_Indication", m_CurrSign, // признак справки
                      "N1_OurFNScode", m_RepCalc.OurFNScode(),   // ИФНС (код)

                      "N1_OurOKTMO",     DL_StrCut( m_RepCalc.OurOKTMO(), 11, "-", true ),     // Код ОКТМО
                      "N1_OurPhone",     m_RepCalc.OurPhone(),     // Телефон
                      "N1_OurINN",       m_RepCalc.OurInn(), // ИНН
                      "N1_OurKPP",       m_RepCalc.OurKpp(), // КПП
                      "N1_OurName",      m_RepCalc.OurName(),      // Наименование организации

                      "N1_ClientINN",        m_RepCalc.ClientINN(),          // ИНН в Российской Федерации 
                      "N1_ClientINN2",       m_RepCalc.ClientINN2(),         // ИНН в стране гражданства
                      "N1_SurName",          m_RepCalc.LastName(),           // Фамилия
                      "N1_Name",             m_RepCalc.FirstName(),          // Имя
                      "N1_MiddleName",       m_RepCalc.MiddleName(),         // Отчество
                      "N1_ResidenceStatus",  m_RepCalc.ResidenceStatus(),    // Статус налогоплательщика
                      "N1_DateBirth",        m_RepCalc.DateBirth(),          // Дата рождения 
                      "N1_Citizenship",      m_RepCalc.Citizenship(),        // Гражданство
                      "N1_DocumentType",     m_RepCalc.DocumentType(),       // Вид документа, удостове-ряющего личность 
                      "N1_DocumentNumber",   m_RepCalc.DocumentNumber(),     // Серия, номер документа

                      "N1_OrgCode", "",  // Форма реорганизации (ликвидации)
                      "N1_OrgInn",  "",  // ИНН реорганизованной организации
                      "N1_OrgKPP",  ""); // КПП реорганизованной организации

    CopyAllSheetInTotalBook( m_CurrSheetName, false, "N1_Header", Отступ, m_CurrSheetName, true );
  END;


  PRIVATE MACRO ПечататьСправку(Index)
    var i = 0;

    m_FirstPos = 0; 
    m_LastPos = 0;

    //распечатать
    PrintFormatString( NULL,
                       "N1_Rate", m_RepCalc.m_PrintArrCodeParms[Index].Rate // Ставка
                     );

    CopyAllSheetInTotalBook(m_CurrSheetName, false, "N1_Table3Header", 1, m_CurrSheetName, true);

    //пока что комментирую как неиспользуемое
    //m_FirstPos = GetLastPosition(m_CurrSheetName);

    RegisterTable( "N1_Table3", NULL,
                   "N1_Month",
                   "N1_CodePS",
                   "N1_PSnnn",
                   "N1_CodeMS",
                   "N1_MSnnn"
                 );

    while( i < m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr.Size )

      // Строка с кодом дохода выводится в отчет, если сумма дохода не нулевая или если сумма дохода нулевая и хотя бы одна из сумм вычета, входящих в одну группу с этой строкой дохода ненулевая. 
      // Если сумма вычета нулевая, то в отчет не выводится информация с кодом вычета.    
      // Если код вычета не стоит в одной строке с кодом дохода и сумма вычета нулевая, то строка с таким кодом вычета в отчет не выводится.

      if( ((m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].PSnnn == null) or (m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].PSnnn == $0)) and
          ((m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].MSnnn == null) or (m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].MSnnn == $0)) )
         //не печатать
      else

        PrintTableLine( "N1_Month",   iif(m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].PSCode != null, m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].Month, null), null,
                        "N1_CodePS",  m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].PSCode, null,
                        "N1_PSnnn",   m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].PSnnn,  null,
                        NULL,         NULL,          NULL,    //без этого съезжают поля
                        NULL,         NULL,          NULL,    //без этого съезжают поля
                        "N1_CodeMS",  m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].MSCode, null,
                        "N1_MSnnn",   m_RepCalc.m_PrintArrCodeParms[Index].NPTXCodeParmArr[i].MSnnn,  null
                      );
      end;

      i = i + 1;
    end;

    EndTable();
    CopyAllSheetInTotalBook( m_CurrSheetName, false, GetTableRange(), 0, m_CurrSheetName, true );

    //раздел 4.
    if( m_CurrSign == 1 )
      CopyAllSheetInTotalBook(m_CurrSheetName, false, "N1_Table4Header", 1, m_CurrSheetName, true);

      RegisterTable("N1_Table4", NULL,
                    "N1_CodeD1",
                    "N1_SumD1");

      if ((IIS_CONTRACTS == "X") and (OTHER_CONTRACTS == "X"))
        PrintTableLine("N1_CodeD1", IIF( (m_RepCalc.MinusG_618() > 0), "618", ""), null,
                       "N1_SumD1",  m_RepCalc.MinusG_618(), null,
                       "N1_CodeD1", IIF( m_RepCalc.MinusG_619()!= 0, "619",""), null,
                       "N1_SumD1",  m_RepCalc.MinusG_619(), null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null);
      elif ((IIS_CONTRACTS == "X") and (OTHER_CONTRACTS != "X"))
        PrintTableLine("N1_CodeD1", IIF( m_RepCalc.MinusG_619()!= 0, "619",""), null,
                       "N1_SumD1",  m_RepCalc.MinusG_619(), null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null);
      elif ((IIS_CONTRACTS != "X") and (OTHER_CONTRACTS == "X"))
        PrintTableLine("N1_CodeD1", IIF(m_RepCalc.MinusG_618()!= 0,"618",""), null,
                       "N1_SumD1",  m_RepCalc.MinusG_618(), null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null,
                       "",  "", null);
      end;

       EndTable();
       CopyAllSheetInTotalBook(m_CurrSheetName, false, GetTableRange(), 0, m_CurrSheetName, true);

       CopyAllSheetInTotalBook(m_CurrSheetName, false, "N1_Table4Footer", 0, m_CurrSheetName, true);
    end;
    //пока что комментирую как неиспользуемое
    //m_LastPos = GetLastPosition(m_CurrSheetName) - 1;

  END;


  PRIVATE MACRO ПечататьИТОГ(Index)
    var LastPosition = GetLastPosition(m_CurrSheetName);
    var TotalPlus = "";
    var TotalMinus = "";
    var NumInList = "", TaxPaid = "";
    var TaxBaseSum = "", TaxCalculated = "", TaxDue = "", TaxToReturnDue;

    var PosTotalPlus     = LastPosition+2;
    var PosTaxBaseSum    = LastPosition+3;
    var PosTaxCalculated = LastPosition+4;
    var PosTaxPaid       = LastPosition+5;

    TaxPaid        = m_RepCalc.TaxPaid(Index);
    TotalPlus      = m_RepCalc.PlusSum(Index);
    TotalMinus     = m_RepCalc.MinusSum(Index);
    TaxBaseSum     = m_RepCalc.TaxBaseSum(Index);
    TaxCalculated  = m_RepCalc.TaxCalculated(Index);
    TaxDue         = m_RepCalc.TaxDue(Index);
    TaxToReturnDue = m_RepCalc.TaxToReturnDue(Index);

    PrintFormatString( NULL,
                       "N1_TotalPlus",     TotalPlus,  //Общая сумма дохода 
                       "N1_TaxPaid",       Round(TaxPaid, 0),
                       "N1_TaxBaseSum",    TaxBaseSum, //Налоговая база
                       "N1_TaxPaid1",      Round(TaxPaid, 0),
                       "N1_TaxCalculated", Round(TaxCalculated, 0), //Сумма налога исчисленная 
                       "N1_TaxToReturnDue",Round(TaxToReturnDue, 0),
                       "N1_TaxDue",        Round(TaxDue, 0)
                       
                     );

    CopyAllSheetInTotalBook( m_CurrSheetName, false, "N1_TotalSumm", 1, m_CurrSheetName, true );

    PrintFormatString( NULL,
                       "N1_First_Person",  m_RepCalc.FirstPerson()
                     );

    CopyAllSheetInTotalBook( m_CurrSheetName, false, "N1_Footer", 1, m_CurrSheetName, true );
  END;

  initNPTX_Pit2_Report_Base("Report_NPTXPit2_2015.xls" );
END; //NPTX_Pit2_Report_2015


PRIVATE CLASS (DL_XML) NPTX_Pit2_XML()
  private var m_FileNode;
  private var m_RepDate;
  private var m_RepCalc;
  private var m_CurrSign;

  PRIVATE MACRO GetFileName()
    var RefID, Num;
    var Year, Month, Day;

    if(m_FileName == NULL)
      if( GetReferenceIDByType( 134, 1, RefID) )
         ErrLog.LogError( "Не найден описатель референса" );
      elif( GenerateReference( RefID, Num ) )
         ErrLog.LogError( "Ошибка при генерации референса по описателю " + string(RefID) );
      end;
      
      //R_T
      m_FileName = "NO_NDFL2";

      //A_K
      m_FileName = m_FileName + "_" + m_RepCalc.OurFNScode();

      //O
      m_FileName = m_FileName + "_" + m_RepCalc.OurInn()+m_RepCalc.OurKPP();

      //GGGGMMDD
      datesplit({curdate}, Day, Month, Year); 
      m_FileName = m_FileName + "_" + string(Year) + string(L_Z(Month,2)) + string(L_Z(Day,2));

      m_FileName = m_FileName + "_" + Num;
    end;
    
    return m_FileName;
  END;


  PRIVATE MACRO СоздатьУзелФайл()
    return CreateNode("Файл",
                      "ИдФайл",   GetFileName(),
                      "ВерсПрог", "RS-Bank",
                      "ВерсФорм", "5.06"
                     );
  END;

  PRIVATE MACRO СоздатьУзелСвРекв()
    var УзелСвРекв =  CreateNode("СвРекв",
                                 "ОКТМО",    m_RepCalc.OurOKTMO(),
                                 "ОтчетГод", m_RepCalc.CurrYear(),
                                 "ПризнакФ", m_CurrSign 
                                );

    var УзелСвЮЛ = CreateNode("СвЮЛ",
                              "ИННЮЛ", m_RepCalc.OurInn(),
                              "КПП",   m_RepCalc.OurKPP());

    var ЭлемСвРеоргЮЛТип = CreateElement("СвРеоргЮЛТип",
                                      "ФормРеорг", "___",
                                      "ИННЮЛ", "",
                                      "КПП", "");

    var УзелСвФЛ = CreateNode("___СвФЛ");
    
    УзелСвЮЛ.appendChild(ЭлемСвРеоргЮЛТип);
    УзелСвРекв.appendChild(УзелСвЮЛ);
    УзелСвРекв.appendChild(УзелСвФЛ );

    return УзелСвРекв;
  END;

  PRIVATE MACRO СоздатьУзелСвНА()
    var УзелСвНА = CreateNode("СвНА",
                              "ОКТМО", m_RepCalc.OurOKTMO(),
                              "Тлф",   m_RepCalc.OurPhone()
                             );

    var УзелСвНАЮЛ = CreateNode("СвНАЮЛ",
                                   "НаимОрг", m_RepCalc.OurName(),
                                   "ИННЮЛ",   m_RepCalc.OurInn(),
                                   "КПП",     m_RepCalc.OurKPP()
                                  );

    var ЭлемСвРеоргЮЛТип = CreateElement("СвРеоргЮЛТип",
                                      "ФормРеорг", "",
                                      "ИННЮЛ", "",
                                      "КПП", "");

    УзелСвНАЮЛ.appendChild(ЭлемСвРеоргЮЛТип);
    УзелСвНА.appendChild(УзелСвНАЮЛ);

    return УзелСвНА;
  END;

  PRIVATE MACRO СоздатьУзелПолучДох()
    var УзелПолучДох = null;
    УзелПолучДох = CreateNode("ПолучДох",
                              "ИННФЛ",    m_RepCalc.ClientINN(),
                              "ИННИно",   m_RepCalc.ClientINN2(),
                              "Статус",   m_repCalc.ResidenceStatus(),
                              "ДатаРожд", string(m_RepCalc.DateBirth():f),
                              "Гражд",    m_RepCalc.Citizenship()
                             );

    var ЭлемФИОТип = CreateElement("ФИОТип",
                                   "Фамилия",  m_RepCalc.LastName,
                                   "Имя",      m_RepCalc.FirstName,
                                   "Отчество", m_RepCalc.MiddleName
                                  ); 

    var ЭлемУдЛичнФЛ = CreateElement("УдЛичнФЛ",
                                     "КодУдЛичн", m_RepCalc.DocumentType(),
                                     "СерНомДок", m_RepCalc.DocumentNumber()
                                    ); 


    УзелПолучДох.appendChild(ЭлемФИОТип);
    УзелПолучДох.appendChild(ЭлемУдЛичнФЛ);

    return УзелПолучДох;
  END;

  PRIVATE MACRO СоздатьУзлыСведДох(InfoRate)
    var arr, i = 0;
    var УзлыСведДох  = null, УзелДохВыч = null, УзелСвСумДох = null, УзелНалВычССИ = null;
    var ЭлемСвСумВыч = null, ЭлемПредВычССИ = null, ЭлемСумИтНалПер = null;

    while( i < m_RepCalc.m_PrintArrCodeParms.Size() )
       if( (m_RepCalc.TaxDue(i) > $0) or (m_CurrSign == 1) ) //не должно формироваться, если TaxDue == 0 и признак 2

          var j = 0;
          while( j < m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr.Size() )

             if( ((m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].PSnnn == null) or (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].PSnnn == $0)) and
                 ((m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn == null) or (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn == $0)) )
                //не печатать
             else
                if( УзлыСведДох.Size() < i )
                   УзлыСведДох[i] = CreateNode("СведДох",
                                               "Ставка", ЧислоCЗаданнойТочностью(m_RepCalc.m_PrintArrCodeParms[i].Rate,0)
                                              );

                   УзелДохВыч = CreateNode("ДохВыч");
                end;

                if( arr[i].PSCode != null )
                   УзелСвСумДох = CreateNode("СвСумДох",
                                             "Месяц",    getMonthNPTX(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].Month),
                                             "КодДоход", m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].PSCode, 
                                             "СумДоход", ЧислоCЗаданнойТочностью(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].PSnnn, 2) 
                                            );
                end;
               
                if( УзелСвСумДох != null )
                   if( (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSCode != null) and (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn != null) and
                       (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn != $0) ) //пустые (нулевые) расходы выгружать не нужно
                     if(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSCode == null)
                       m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSCode = "___";
                        end;
                      if(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn == null)
                        m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn = $0;
                      end;
                      ЭлемСвСумВыч = CreateElement("СвСумВыч",
                                                   "КодВычет", m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSCode,
                                                   "СумВычет", ЧислоCЗаданнойТочностью(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn, 2)
                                                  );
                      УзелСвСумДох.appendChild(ЭлемСвСумВыч);
                   end;

                   УзелДохВыч.appendChild(УзелСвСумДох);
                end;
             end;

             if( УзлыСведДох[i] != null )
//                УзлыСведДох[i].appendChild(УзелДохВыч);

                var need_618 = 0;
                var need_619 = 0;
                if ((IIS_CONTRACTS == "X") and (OTHER_CONTRACTS == "X"))
                  need_618 = 1;
                  need_619 = 1;
                elif ((IIS_CONTRACTS != "X") and (OTHER_CONTRACTS == "X"))
                  need_618 = 1;
                elif ((IIS_CONTRACTS == "X") and (OTHER_CONTRACTS != "X"))
                  need_619 = 1;
                end;

/*                if (need_618 == 1)
                  if( m_RepCalc.MinusG_618() > 0 )
                     УзелНалВычССИ = CreateNode("НалВычССИ");
                     if( УзелНалВычССИ != null )
                        ЭлемПредВычССИ = CreateElement("ПредВычССИ",
                                                       "КодВычет", "618",
                                                       "СумВычет", ЧислоCЗаданнойТочностью(m_RepCalc.MinusG_618(),2)
                                                      );
                        УзелНалВычССИ.appendChild(ЭлемПредВычССИ);
                     end;
                     УзлыСведДох[i].appendChild(УзелНалВычССИ);
                  end;
                end;

                if (need_619 == 1)
                  if (m_RepCalc.MinusG_619() > 0)
                     УзелНалВычССИ = CreateNode("НалВычССИ");
                     if (УзелНалВычССИ != null)
                        ЭлемПредВычССИ = CreateElement("ПредВычССИ",
                                                       "КодВычет", "619",
                                                       "СумВычет", 
                                                        ЧислоCЗаданнойТочностью(
                                                          m_RepCalc.MinusG_619(), 2));
                        УзелНалВычССИ.appendChild(ЭлемПредВычССИ);
                     end;
                     УзлыСведДох[i].appendChild(УзелНалВычССИ);
                  end;
                end;
*/
                if(m_CurrSign == 1)
                   ЭлемСумИтНалПер = CreateElement("СумИтНалПер",
                                                   "СумДохОбщ",     ЧислоCЗаданнойТочностью(m_RepCalc.PlusSum(i),2),
                                                   "НалБаза",       ЧислоCЗаданнойТочностью(m_RepCalc.TaxBaseSum(i), 2),
                                                   "НалИсчисл",     ЧислоCЗаданнойТочностью(m_RepCalc.TaxCalculated(i),0),
                                                   "АвансПлатФикс", "0",
                                                   "НалУдерж",      ЧислоCЗаданнойТочностью( m_RepCalc.TaxPaid(i),0),
                                                   "НалПеречисл",   ЧислоCЗаданнойТочностью( m_RepCalc.TaxPaid(i),0),
                                                   "НалУдержЛиш",   ЧислоCЗаданнойТочностью(m_RepCalc.TaxToReturnDue(i),0),
                                                   "НалНеУдерж",    ЧислоCЗаданнойТочностью(m_RepCalc.TaxDue(i),0)
                                                  );
                elif(m_CurrSign == 2)
                   ЭлемСумИтНалПер = CreateElement("СумИтНалПер",
                                                   "СумДохОбщ",     ЧислоCЗаданнойТочностью(m_RepCalc.PlusSum(i),2),
                                                   "НалБаза",       ЧислоCЗаданнойТочностью(m_RepCalc.TaxBaseSum(i), 2),
                                                   "НалИсчисл",     ЧислоCЗаданнойТочностью(m_RepCalc.TaxCalculated(i),0),
                                                   "АвансПлатФикс", "0",
                                                   "НалУдерж",      ЧислоCЗаданнойТочностью( m_RepCalc.TaxPaid(i),0),
                                                   "НалПеречисл",   ЧислоCЗаданнойТочностью( m_RepCalc.TaxPaid(i),0)
                                                   );

                end;
                УзлыСведДох[i].appendChild(ЭлемСумИтНалПер);
                УзлыСведДох[i].appendChild(УзелДохВыч);
             end;

             j = j + 1;
          end;
       end;

       i = i + 1;
    end;

    return УзлыСведДох;
  END;

  PRIVATE MACRO СоздатьУзелПодписант()
    var УзелПодписант = CreateNode("Подписант",
                                   "ПрПодп", 1
                                  );

    var ЭлемФИО = CreateElement("ФИО",
                                "Фамилия",  m_RepCalc.FirstPersonLastName(),
                                "Имя",      m_RepCalc.FirstPersonFirstName(),
                                "Отчество", m_RepCalc.FirstPersonMiddleName()
                               );

    УзелПодписант.appendChild(ЭлемФИО);

    return УзелПодписант;
  END;


  PRIVATE MACRO СоздатьУзелДокумент()
    var УзелДокумент = null;
    var УзелСвНА     = СоздатьУзелСвНА();
    var УзелПолучДох = СоздатьУзелПолучДох();
    var УзлыСведДох = null;
    var УзелПодписант = null;
    var УзелНДФЛ2 = null;

    УзелДокумент = CreateNode("Документ",
                              "КНД",      "1151078",
                              "ДатаДок",  string(m_RepDate:f),
                              "НомСпр",   m_RepCalc.PrintNumOper(),
                              "ОтчетГод", m_RepCalc.CurrYear(),
                              "Признак",  m_CurrSign, 
                              "НомКорр",  "00",
                              "КодНО",    m_RepCalc.OurFNScode()
                             );
    m_RepCalc.CalcData(INFORATE9_NOTRES_DIV, m_CurrSign);
    m_RepCalc.CalcData(INFORATE_TOTAL, m_CurrSign);
    m_RepCalc.CalcData(INFORATE_35, m_CurrSign);
    m_RepCalc.CalcData(0, m_CurrSign);

    УзлыСведДох = СоздатьУзлыСведДох();

    УзелПодписант = СоздатьУзелПодписант();
    УзелДокумент.appendChild(УзелПодписант);
 
    УзелДокумент.appendChild(УзелСвНА);
    УзелДокумент.appendChild(УзелПолучДох);

    var i = 0;
    while(i < УзлыСведДох.Size())
       if(УзлыСведДох[i] != NULL)
         УзелДокумент.appendChild(УзлыСведДох[i]);
       end;
    end;

    return УзелДокумент;
  END;

  PRIVATE MACRO CreateXML()
    var stat = CreateXML();
    
    m_FileNode = null;

    return stat;
  END;

  PRIVATE MACRO SaveXML()

    if(m_FileNode != null)
      AddMainNode(m_FileNode);

      RemoveEmpty();

      SaveXML();

      ErrLog.LogError("Сформирован файл " + GetFileName()+".xml");
    end;
  END;

  MACRO Run( Sign )
    var count = 0;
    var InvestorArray = Form.GetFieldValue(PNFLD_TXPIT2_INVESTORCODE);
    var InOneFile = Form.GetFieldValue(PNFLD_TXPIT2_XMLINONEFILE);
    var УзелДокумент;
    var УзелСвРекв;
    var Attr;
    var i = 0, fileiter = 1;
    var isFirst = true;
    var stat = true;
    var IsClient = Form.GetFieldValue(TXFLD_TXPIT2_ISCLIENT);

    m_RepDate = date(Form.GetFieldValue(PNFLD_TXPIT2_ENDDATE));
    m_CurrSign = Sign;

    m_RepCalc = NPTXRepCalc(m_RepDate, InvestorArray);

    count = m_RepCalc.Count();  
    if( count > 0)
      
      if(InOneFile == SET_CHAR)
        stat = CreateXML();
      end;

      if(stat)
        InitProgress( count, "2-НДФЛ по ц/б", "2-НДФЛ по ц/б"+iif(m_CurrSign==1, " - Признак 1", " - Признак 2") );
       
        while((stat) and (m_RepCalc.Next()))
          
          if(InOneFile == UNSET_CHAR)
            isFirst = true;
            stat = CreateXML();
          elif(i == 3000*fileiter)
            SaveXML();
            stat = CreateXML();
            fileiter = fileiter + 1;
            isFirst = true;
          end;

          if(stat)
            УзелДокумент = СоздатьУзелДокумент();
            if(УзелДокумент != null)
              if(isFirst == true)
                m_FileNode = СоздатьУзелФайл();
                isFirst = false;

                УзелСвРекв = СоздатьУзелСвРекв();
                m_FileNode.appendChild(УзелСвРекв);
              end;

              if(m_FileNode != null)
                m_FileNode.appendChild(УзелДокумент);
              end;
              m_RepCalc.m_count = m_RepCalc.m_count + 1;
            end;

            if(InOneFile == UNSET_CHAR)
              SaveXML();
            end;
          end;

          UseProgress( i = i + 1);
        end;

        RemProgress();

        if(InOneFile == SET_CHAR)
          SaveXML();
        end;
      end;
    end;
  END;

END;  //NPTX_Pit2_XML

PRIVATE CLASS (DL_XML) NPTX_Pit2_2018_XML()
  private var m_FileNode;
  private var m_RepDate;
  private var m_RepCalc;
  private var m_CurrSign;

  PRIVATE MACRO GetFileName()
    var RefID, Num,m = 0;
    var Year, Month, Day;

    if(m_FileName == NULL)
      if( GetReferenceIDByType( 134, 1, RefID) )
         ErrLog.LogError( "Не найден описатель референса" );
      elif( GenerateReference( RefID, Num ) )
         ErrLog.LogError( "Ошибка при генерации референса по описателю " + string(RefID) );
      end;
      
      //R_T
      m_FileName = "NO_NDFL2";

      //A_K
      m_FileName = m_FileName + "_" + m_RepCalc.OurFNScode();

      //O
      m_FileName = m_FileName + "_" + m_RepCalc.OurInn()+m_RepCalc.OurKPP();

      //GGGGMMDD
      datesplit({curdate}, Day, Month, Year); 
      m_FileName = m_FileName + "_" + string(Year) + string(L_Z(Month,2)) + string(L_Z(Day,2));

      m_FileName = m_FileName + "_" + Num;
      
end;
     if(m_CurrSign == 1)
        m = m_FileName + "_Pr1";
	 return m;
	end;
      if(m_CurrSign == 2)
        m = m_FileName + "_Pr2";
	 return m;
    end;

  END;


  PRIVATE MACRO СоздатьУзелФайл()
    return CreateNode("Файл",
                      "ИдФайл",   GetFileName(),
                      "ВерсПрог", "RS-Bank",
                      "ВерсФорм", "5.06"
                     );
  END;

  PRIVATE MACRO СоздатьУзелСвНА()
    var УзелСвНА = CreateNode("СвНА",
                              "ОКТМО", m_RepCalc.OurOKTMO(),
                              "Тлф",   m_RepCalc.OurPhone()
                             );

    var УзелСвНАЮЛ = CreateNode("СвНАЮЛ",
                                   "НаимОрг", m_RepCalc.OurName(),
                                   "ИННЮЛ",   m_RepCalc.OurInn(),
                                   "КПП",     m_RepCalc.OurKPP()
                                  );

    var ЭлемСвРеоргЮЛ = CreateElement("СвРеоргЮЛ",
                                      "ФормРеорг", "",
                                      "ИННЮЛ", "",
                                      "КПП", "");

    УзелСвНАЮЛ.appendChild(ЭлемСвРеоргЮЛ);
    УзелСвНА.appendChild(УзелСвНАЮЛ);

    return УзелСвНА;
  END;

  PRIVATE MACRO СоздатьУзелПолучДох()
    var УзелПолучДох = null;
      УзелПолучДох = CreateNode("ПолучДох",
                                "ИННФЛ",    m_RepCalc.ClientINN(),
                                "Статус",   m_repCalc.ResidenceStatus(),
                                "ДатаРожд", string(m_RepCalc.DateBirth():f),
                                "Гражд",    m_RepCalc.Citizenship()
                               );
    
    var ЭлемФИОТип = CreateElement("ФИО",
                                   "Фамилия",  m_RepCalc.LastName,
                                   "Имя",      m_RepCalc.FirstName,
                                   "Отчество", m_RepCalc.MiddleName
                                  ); 

    var ЭлемУдЛичнФЛ = CreateElement("УдЛичнФЛ",
                                     "КодУдЛичн", m_RepCalc.DocumentType(),
                                     "СерНомДок", m_RepCalc.DocumentNumber()
                                    ); 


    УзелПолучДох.appendChild(ЭлемФИОТип);
    УзелПолучДох.appendChild(ЭлемУдЛичнФЛ);

    return УзелПолучДох;
  END;

  PRIVATE MACRO СоздатьУзлыСведДох(InfoRate)
    var arr, i = 0;
    var УзлыСведДох  = TArray(), УзелДохВыч = null, УзелСвСумДох = null, УзелНалВычССИ = null;
    var ЭлемСвСумВыч = null, ЭлемПредВычССИ = null, ЭлемСумИтНалПер = null;

    while( i < m_RepCalc.m_PrintArrCodeParms.Size() )
       if( (m_RepCalc.TaxDue(i) > $0) or (m_CurrSign == 1) ) //не должно формироваться, если TaxDue == 0 и признак 2
          var j = 0;
          while(j < m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr.Size())
             if( ((m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].PSnnn == null) or (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].PSnnn == $0)) and
                 ((m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn == null) or (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn == $0)) )
                //не печатать
             else
                if( УзлыСведДох.Size() <= i )
                   УзлыСведДох[i] = CreateNode("СведДох",
                                               "Ставка", ЧислоCЗаданнойТочностью(m_RepCalc.m_PrintArrCodeParms[i].Rate,0)
                                              );

                   УзелДохВыч = CreateNode("ДохВыч");
                end;

                if( m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].PSCode != null )
                   УзелСвСумДох = CreateNode("СвСумДох",
                                             "Месяц",    getMonthNPTX(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].Month),
                                             "КодДоход", m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].PSCode, 
                                             "СумДоход", ЧислоCЗаданнойТочностью(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].PSnnn, 2) 
                                            );
                end;
               
                if( УзелСвСумДох != null )
                   if( (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSCode != null) and (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j] != null)
                       and (m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn != $0) ) //пустые (нулевые) расходы выгружать не нужно
                      if(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSCode == null)
                        m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSCode = "___";
                      end;
                      if(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn == null)
                        m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn = $0;
                      end;
                      ЭлемСвСумВыч = CreateElement("СвСумВыч",
                                                   "КодВычет", m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSCode,
                                                   "СумВычет", ЧислоCЗаданнойТочностью(m_RepCalc.m_PrintArrCodeParms[i].NPTXCodeParmArr[j].MSnnn, 2)
                                                  );
                      УзелСвСумДох.appendChild(ЭлемСвСумВыч);
                   end;

                   УзелДохВыч.appendChild(УзелСвСумДох);
                end;

                if( УзлыСведДох[i] != null )
//                   УзлыСведДох[i].appendChild(УзелДохВыч);

                   var need_618 = 0;
                   var need_619 = 0;
                   if ((IIS_CONTRACTS == "X") and (OTHER_CONTRACTS == "X"))
                     need_618 = 1;
                     need_619 = 1;
                   elif ((IIS_CONTRACTS != "X") and (OTHER_CONTRACTS == "X"))
                     need_618 = 1;
                   elif ((IIS_CONTRACTS == "X") and (OTHER_CONTRACTS != "X"))
                     need_619 = 1;
                   end;

/*                   if (need_618 == 1)
                     if( m_RepCalc.MinusG_618() > 0 )
                        УзелНалВычССИ = CreateNode("НалВычССИ");
                        if( УзелНалВычССИ != null )
                           ЭлемПредВычССИ = CreateElement("ПредВычССИ",
                                                          "КодВычет", "618",
                                                          "СумВычет", ЧислоCЗаданнойТочностью(m_RepCalc.MinusG_618(),2)
                                                         );
                           УзелНалВычССИ.appendChild(ЭлемПредВычССИ);
                        end;
                        УзлыСведДох[i].appendChild(УзелНалВычССИ);
                     end;
                   end;

                   if (need_619 == 1)
                     if (m_RepCalc.MinusG_619() > 0)
                        УзелНалВычССИ = CreateNode("НалВычССИ");
                        if (УзелНалВычССИ != null)
                           ЭлемПредВычССИ = CreateElement("ПредВычССИ",
                                                          "КодВычет", "619",
                                                          "СумВычет", 
                                                           ЧислоCЗаданнойТочностью(
                                                             m_RepCalc.MinusG_619(), 2));
                           УзелНалВычССИ.appendChild(ЭлемПредВычССИ);
                        end;
                        УзлыСведДох[i].appendChild(УзелНалВычССИ);
                     end;
                   end;
*/
                   if(m_CurrSign == 1)
                      ЭлемСумИтНалПер = CreateElement("СумИтНалПер",
                                                      "СумДохОбщ",     ЧислоCЗаданнойТочностью(m_RepCalc.PlusSum(i),2),
                                                      "НалБаза",       ЧислоCЗаданнойТочностью(m_RepCalc.TaxBaseSum(i), 2),
                                                      "НалИсчисл",     ЧислоCЗаданнойТочностью(m_RepCalc.TaxCalculated(i),0),
                                                      "АвансПлатФикс", "0",
                                                      "НалУдерж",      ЧислоCЗаданнойТочностью( m_RepCalc.TaxPaid(i),0),       
                                                      "НалПеречисл",   ЧислоCЗаданнойТочностью( m_RepCalc.TaxPaid(i),0),      
                                                      "НалУдержЛиш",   ЧислоCЗаданнойТочностью(m_RepCalc.TaxToReturnDue(i),0),
                                                      "НалНеУдерж",    ЧислоCЗаданнойТочностью(m_RepCalc.TaxDue(i),0)
                                                     );
                   elif(m_CurrSign == 2)
                      ЭлемСумИтНалПер = CreateElement("СумИтНалПер",
                                                      "СумДохОбщ",     ЧислоCЗаданнойТочностью(m_RepCalc.PlusSum(i),2),
                                                      "НалБаза",       ЧислоCЗаданнойТочностью(m_RepCalc.TaxBaseSum(i), 2),
                                                      "НалИсчисл",     ЧислоCЗаданнойТочностью(m_RepCalc.TaxCalculated(i),0),
                                                      "АвансПлатФикс", "0",
                                                      "НалУдерж",      ЧислоCЗаданнойТочностью( m_RepCalc.TaxPaid(i),0),       
                                                      "НалПеречисл",   ЧислоCЗаданнойТочностью( m_RepCalc.TaxPaid(i),0)
                                                     );
                   end;

                   УзлыСведДох[i].appendChild(ЭлемСумИтНалПер);
                   УзлыСведДох[i].appendChild(УзелДохВыч);
                end;
             end;

             j = j + 1;
          end;
       end;

       i = i + 1;
    end;

    return УзлыСведДох;
  END;

  PRIVATE MACRO СоздатьУзелПодписант()
    var УзелПодписант = CreateNode("Подписант",
                                   "ПрПодп", 1
                                  );

    var ЭлемФИО = CreateElement("ФИО",
                                "Фамилия",  m_RepCalc.FirstPersonLastName(),
                                "Имя",      m_RepCalc.FirstPersonFirstName(),
                                "Отчество", m_RepCalc.FirstPersonMiddleName()
                               );

    УзелПодписант.appendChild(ЭлемФИО);

    return УзелПодписант;
  END;

  PRIVATE MACRO СоздатьУзелНДФЛ2()
    var УзелНДФЛ2, УзелПолучДох, УзелСведДох915, УзелСведДохОбщ, УзелСведДох35;
    
    УзелНДФЛ2 = CreateNode("НДФЛ-2",
                           "НомСпр", m_RepCalc.PrintNumOper(),
                           "НомКорр", "00");

    УзелПолучДох = СоздатьУзелПолучДох();
    УзелНДФЛ2.appendChild(УзелПолучДох);

    m_RepCalc.CalcData(INFORATE9_15, m_CurrSign);
    m_RepCalc.CalcData(INFORATE_TOTAL, m_CurrSign);
    m_RepCalc.CalcData(INFORATE_35, m_CurrSign);
    m_RepCalc.CalcData(0, m_CurrSign);

    var УзлыСведДох = СоздатьУзлыСведДох();

    var i = 0;
    while(i < УзлыСведДох.Size())
       if(УзлыСведДох[i] != null)
         УзелНДФЛ2.appendChild(УзлыСведДох[i]);
       end;
       i = i + 1;
    end;

//    УзелНДФЛ2.appendChild(УзелПолучДох);
    return УзелНДФЛ2;
  END;

  PRIVATE MACRO СоздатьУзелДокумент()
    var УзелДокумент = null;
    var УзелСвНА     = СоздатьУзелСвНА();
    var УзелСведДох915  = null, УзелСведДохОбщ = null, УзелСведДох35 = null;
    var УзелПодписант = null;

    УзелДокумент = CreateNode("Документ",
                              "КНД",      "1151078",
                              "ДатаДок",  string(m_RepDate:f),
                              "ОтчетГод", m_RepCalc.CurrYear(),
                              "Признак",  m_CurrSign, 
                              "КодНО",    m_RepCalc.OurFNScode()
                             );

    УзелДокумент.appendChild(УзелСвНА);
    УзелПодписант = СоздатьУзелПодписант();
    УзелДокумент.appendChild(УзелПодписант);

    return УзелДокумент;
  END;

  PRIVATE MACRO CreateXML()
    var stat = CreateXML();
    
    m_FileNode = null;

    return stat;
  END;

  PRIVATE MACRO SaveXML()

    if(m_FileNode != null)
      AddMainNode(m_FileNode);

      RemoveEmpty();

      SaveXML();
       CopyFile(substr(GetTxtFileName(GetFileName()),1,index(getTxtFileName(GetFileName()),".",3)-1)+".xml", 
           //"$C:\\SOFR\\EXPORT\\"+GetFileName()+".xml");
           "$txtfile\\"+GetFileName()+".xml");
      ErrLog.LogError("Сформирован файл " + GetFileName()+".xml");
    end;
  END;

  MACRO Run( Sign )
    var count = 0;
    var InvestorArray = Form.GetFieldValue(PNFLD_TXPIT2_INVESTORCODE);
    var InOneFile = Form.GetFieldValue(PNFLD_TXPIT2_XMLINONEFILE);
    var УзелДокумент, УзелНДФЛ2;
    var УзелСвРекв;
    var Attr;
    var i = 0, fileiter = 1;
    var isFirst = true;
    var stat = true;
    var IsClient = Form.GetFieldValue(TXFLD_TXPIT2_ISCLIENT);
    var numCount = CheckOperNum( Form.GetFieldValue( PNFLD_TXPIT2_NUMBER_OPER));

    m_RepDate = date(Form.GetFieldValue(PNFLD_TXPIT2_ENDDATE));
    m_CurrSign = Sign;

    m_RepCalc = NPTXRepCalc(m_RepDate, InvestorArray);

    count = m_RepCalc.Count();  
    if( count > 0)
      
      if(InOneFile == SET_CHAR)
        stat = CreateXML();
      end;

      if(stat)
        InitProgress( count, "2-НДФЛ по ц/б", "2-НДФЛ по ц/б"+iif(m_CurrSign==1, " - Признак 1", " - Признак 2") );
       
        while((stat) and (m_RepCalc.Next()))

          m_RepCalc.ClearData();
          if(InOneFile == UNSET_CHAR)
            isFirst = true;
            stat = CreateXML();
          elif(i == 3000*fileiter)
            SaveXML();
            stat = CreateXML();
            fileiter = fileiter + 1;
            isFirst = true;
          end;

          if(stat)
            m_RepCalc.m_countOfNum = numCount;

            УзелНДФЛ2 = СоздатьУзелНДФЛ2();

            if(УзелНДФЛ2 != null)
              if((isFirst == true))
                УзелДокумент = СоздатьУзелДокумент();
                if(УзелДокумент != null)
                  m_FileNode = СоздатьУзелФайл();
                  if(m_FileNode != null)
                    m_FileNode.appendChild(УзелДокумент);
                  end;
                  isFirst = false;
                end;
              end;
              УзелДокумент.appendChild(УзелНДФЛ2);
            end;

            m_RepCalc.m_count = m_RepCalc.m_count + 1;

            if(InOneFile == UNSET_CHAR)
              SaveXML();
            end;
          end;

          UseProgress( i = i + 1);
        end;

        RemProgress();

        if(InOneFile == SET_CHAR)
          SaveXML();
        end;
      end;
    end;
  END;

END;  //NPTX_Pit2_2018_XML

Form = NPTX_Pit2_Panel();
private var RepDate;

while(Form.Run())

  Rep = CMakeReport();
  ErrLog.InitErrLog( Rep, true );
  Dl_CallInsertStat( Form.GetFieldValue( PNFLD_TXPIT2_PRINTMETHOD ) );

  IIS_CONTRACTS = Form.GetFieldValue( PNFLD_TXPIT2_CONTR_IIS);
  OTHER_CONTRACTS = Form.GetFieldValue( PNFLD_TXPIT2_CONTR_OTHER);

  IsClient = Form.GetFieldValue( TXFLD_TXPIT2_ISCLIENT);

  RepDate = date(Form.GetFieldValue(PNFLD_TXPIT2_ENDDATE));

  if(Form.GetFieldValue( PNFLD_TXPIT2_PRINTMETHOD ) == DL_OUTREPORT_XML)
    var Sign1 = Form.GetFieldValue( PNFLD_TXPIT2_SIGN1);
    var Sign2 = Form.GetFieldValue( PNFLD_TXPIT2_SIGN2);
    var XmlRep = NULL;

    //При формировании в XML будем отдельно вести протокол в Excel, куда запишем ошибки и имена сформированных файлов
    Rep.GetCurSheet().SheetName = "Сообщения";
    ErrLog.StartErrLog();

    if(RepDate <= NPTX_NEW_TIPI_DATE_2018)
      XmlRep = NPTX_Pit2_XML();
    else
      XmlRep = NPTX_Pit2_2018_XML();
    end;

    if(Sign1 == SET_CHAR)
      XmlRep.Run(1);
    end;
    if(Sign2 == SET_CHAR)
      XmlRep.Run(2);
    end;

    ErrLog.FinishErrLog();

    //Напечатать протокол
    ErrLog.ShowErrLog(true);
    Rep.SetZoomType( ZOOM_TYPE_A4L );// альбомная ориентация
    Rep.PrintWinRep();
    Rep.ShowWinRep();

  else
    if((RepDate >= NPTX_NEW_TIPI_DATE_2015) and (RepDate <= NPTX_NEW_TIPI_DATE_2018))
      NPTX_Pit2_Report_2015().Run();
    elif(RepDate > NPTX_NEW_TIPI_DATE_2018)
	  var report = NPTX_Pit2_Report_2018();
      report.SetIsShowAppl(false);
      report.Run();
	  var FilesCount = report.GetFilesCount;
      if(IsClient == SET_CHAR)
        report = NPTX_Pit2_Report_2018_Client();
	    report.SetIsShowAppl(false);
	    report.Run();
		FilesCount = FilesCount + report.GetFilesCount;
      end;
	  if (FilesCount == 0) 
	    MsgBox("Нет данных для формирования отчета");
	  else
	    if (GetTrue(true, "Сформировано " + FilesCount + " файла(ов)|Открыть папку для просмотра файлов?"))
	      if (isStandAlone())
		    var DirName:string = "", StrErr :string = "";
            
            GetRegistryValue( "BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\TEXTDIR", V_STRING, DirName, StrErr );

            if( NOT DirName )
              DirName = GetIniString( "TEXTDIR" );
            end;

            if( NOT DirName ) 
			  DirName = GetEnv("TEMP");
              if( NOT DirName )
                DirName = GetEnv("TMP");
              end;
            else
              if( SubStr(DirName, 1, 1) == "." )
                DirName = GetCurDir(false) + "\\" + DirName;
              end;
            end;
			startProg("explorer.exe", DirName);
		  else
			startProg("$explorer.exe", GetCurDir(true) + "\\" + SubStr(toAnsi(NameDirTerm), 2));
	      end;
		end;
	  end;
    else
      MsgBox("Формирование отчета в формате Excel за периоды ранее 2015 года не предусмотрено");
    end;
  end;
  
end;

exit(1);
