/*
$Name:        nptxnkdreqdias_rep.mac
$Module:      Ценные бумаги
$Description: Формирование ежедневного отчета об обработке запроса от Диасофта об уплаченном НКД
*/
import "sprepfun.mac", "sqlconv.mac", "CbReport_h.mac", "scsrvrepfun.mac", "func_lib.mac", "nptxnkdreqdiasrun.mac";


PRIVATE CLASS (DL_CReportTemplate) Sp_NPTXNKDReqDias_Report(RepDate:date)
  private var m_RepDate = RepDate;
  
  PRIVATE MACRO BeginReport()
    SetIsShowAppl(false); //Всегда не показываем отчет на экран
    
    CreateTotalBook();
  END;

  MACRO PrintMode():INTEGER
    return DL_OUTREPORT_EXCEL;
  END;

  PRIVATE MACRO EndReport()
    SaveTotalbook();
    ReplaceAndCalculate();
  END;

  PRIVATE MACRO CreateSheetReqDias()
    var SheetName = "Запросы Диасофт";
    var query, cmd, DataSet;
    
    SetActiveSheet(SheetName);

    PrintFormatString( NULL, "N1_RepDate", m_RepDate);

    CopyAllSheetInTotalBook(SheetName, false, "N1_Header", 0, SheetName);

    RegisterTable( "N1_MainTable", NULL,
                   "N1_ID",        
                   "N1_GUID",  
                   "N1_GUIDResp",      
                   "N1_RequestDate",   
                   "N1_RequestTime",   
                   "N1_PaymentID",     
                   "N1_PaymentActionName",     
                   "N1_FixingDate",    
                   "N1_ClientID",      
                   "N1_AgreementNumber",       
                   "N1_IsIIS", 
                   "N1_MarketPlace",   
                   "N1_ISINRegNumber", 
                   "N1_CouponNumber",  
                   "N1_CouponStartDate",       
                   "N1_CouponEndDate", 
                   "N1_CreateDate",    
                   "N1_CreateTime",    
                   "N1_ChangeDate",    
                   "N1_ChangeTime",    
                   "N1_ErrorCode",     
                   "N1_Error", 
                   "N1_Sum",   
                   "N1_PartyID",       
                   "N1_ContractID",    
                   "N1_FIID"
                  );

    query =   " select ds.*, na.t_szNameAlg as PaymentActionName "
            + "   from dnptxnkdreqdias_dbt ds "
            + "        left join dnamealg_dbt na on na.t_iTypeAlg = 7339 and na.t_iNumberAlg = ds.t_PaymentAction "
            + "  where ds.t_RequestDate = ? "
            + " order by ds.t_ID ASC";

    cmd = DL_RSDCommand(query);

    cmd.AddParam(m_RepDate);

    DataSet = cmd.Execute();

    while(DataSet.moveNext())
      PrintTableLine( "N1_ID",               DataSet.ID,                    null,
                      "N1_GUID",             DataSet.GUID,                  null,
                      "N1_GUIDResp",         DataSet.GUIDResp,              null,
                      "N1_RequestDate",      date(DataSet.RequestDate),     null,
                      "N1_RequestTime",      time(DataSet.RequestTime),     null,
                      "N1_PaymentID",        DataSet.PaymentID,             null,
                      "N1_PaymentActionName",DataSet.PaymentActionName,     null,
                      "N1_FixingDate",       date(DataSet.FixingDate),      null,
                      "N1_ClientID",         DataSet.ClientID,              null,
                      "N1_AgreementNumber",  DataSet.AgreementNumber,       null,
                      "N1_IsIIS",            DataSet.IsIIS,                 null,
                      "N1_MarketPlace",      DataSet.MarketPlace,           null,
                      "N1_ISINRegNumber",    DataSet.ISINRegNumber,         null,
                      "N1_CouponNumber",     DataSet.CouponNumber,          null,
                      "N1_CouponStartDate",  date(DataSet.CouponStartDate), null,
                      "N1_CouponEndDate",    date(DataSet.CouponEndDate),   null,
                      "N1_CreateDate",       date(DataSet.CreateDate),      null,
                      "N1_CreateTime",       time(DataSet.CreateTime),      null,
                      "N1_ChangeDate",       date(DataSet.ChangeDate),      null,
                      "N1_ChangeTime",       time(DataSet.ChangeTime),      null,
                      "N1_ErrorCode",        DataSet.ErrorCode,             null,
                      "N1_Error",            DataSet.Error,                 null,
                      "N1_Sum",              DataSet.Sum,                   null,
                      "N1_PartyID",          DataSet.PartyID,               null,
                      "N1_ContractID",       DataSet.ContractID,            null,
                      "N1_FIID",             DataSet.FIID,                  null
                    );
    end;

    EndTable();
    CopyAllSheetInTotalBook(SheetName, false, GetTableRange(), 0, SheetName);
  END;

  PRIVATE MACRO CreateSheetNDR()
    var SheetName = "Объекты НДР";
    var query, cmd, DataSet;
    
    SetActiveSheet(SheetName);

    CopyAllSheetInTotalBook(SheetName, false, "N2_Header", 0, SheetName);

    RegisterTable( "N2_MainTable", NULL,
                   "N2_Date",       
                   "N2_ClientName",    
                   "N2_Direction",     
                   "N2_Level", 
                   "N2_IsUser",        
                   "N2_TaxPeriod",     
                   "N2_TaxBaseKind",   
                   "N2_Kind",  
                   "N2_Sum",   
                   "N2_Cur",   
                   "N2_Sum0",  
                   "N2_KindAnalitic1", 
                   "N2_Analitic",      
                   "N2_KindAnalitic2", 
                   "N2_Analitic2",     
                   "N2_KindAnalitic3", 
                   "N2_Analitic3",     
                   "N2_KindAnalitic4", 
                   "N2_Analitic4",     
                   "N2_KindAnalitic5", 
                   "N2_Analitic5",     
                   "N2_KindAnalitic6", 
                   "N2_Analitic6",     
                   "N2_FromOutSystStr",        
                   "N2_OutSystCode",   
                   "N2_OutObjID",      
                   "N2_Technical"
                  );

    query =   " select /*+ leading(ds dnptxnkdreqdias_dbt)*/ "
            + "        obj.t_Date, "
            + "        pt.t_ShortName as ClientName,  "
            + "        NVL(dir_na.t_szNameAlg, CHR(1)) as DirectionName, "
            + "        obj.t_Level, "
            + "        NVL(usr_na.t_szNameAlg, CHR(1)) as IsUser, "
            + "        obj.t_TaxPeriod, "
            + "        knd.t_TaxBaseKind, "
            + "        knd.t_Code as KindCode, "
            + "        obj.t_Sum, "
            + "        cr.t_Ccy as CurCode, "
            + "        obj.t_Sum0, "
            + "        NVL(val1.t_Code, CHR(1)) as KindAnalitic1, "
            + "        NVL(tk.t_DealCode, CHR(1)) as StrAnalitic1, "
            + "        NVL(val2.t_Code, CHR(1)) as KindAnalitic2, "
            + "        TO_CHAR(obj.t_Analitic2) as StrAnalitic2, "
            + "        NVL(val3.t_Code, CHR(1)) as KindAnalitic3, "
            + "        NVL(fin.t_FI_Code, CHR(1)) as StrAnalitic3, "
            + "        NVL(val4.t_Code, CHR(1)) as KindAnalitic4, "
            + "        NVL(mr_na.t_szNameAlg, CHR(1)) as StrAnalitic4, "
            + "        NVL(val5.t_Code, CHR(1)) as KindAnalitic5, "
            + "        NVL(attr.t_FullName, CHR(1)) as StrAnalitic5, "
            + "        NVL(val6.t_Code, CHR(1)) as KindAnalitic6, "
            + "        NVL(sf.t_Number, CHR(1)) as StrAnalitic6, "
            + "        NVL(out_na.t_szNameAlg, CHR(1)) as FromOutSystStr, "
            + "        obj.t_OutSystCode, "
            + "        obj.t_OutObjID, "
            + "        NVL(tech_na.t_szNameAlg, CHR(1)) as TechnicalStr "
            + "   from dnptxnkdreqdias_dbt ds, dnptxlnkdiaspay_dbt dp, "
            + "        dnptxobj_dbt obj "
            + "          left join dnamealg_dbt dir_na on dir_na.t_iTypeAlg = 7328 and dir_na.t_iNumberAlg = obj.t_Direction "
            + "          left join dnamealg_dbt usr_na on usr_na.t_iTypeAlg = 7329 and usr_na.t_iNumberAlg = (case when obj.t_User = 'X' then 1 else 2 end) "
            + "          left join dllvalues_dbt val1 on val1.t_List = 3519 and val1.t_Element = obj.t_AnaliticKind1 "
            + "          left join ddl_tick_dbt tk on tk.t_DealID = obj.t_Analitic1 "
            + "          left join dllvalues_dbt val2 on val2.t_List = 3519 and val2.t_Element = obj.t_AnaliticKind2 "
            + "          left join dllvalues_dbt val3 on val3.t_List = 3519 and val3.t_Element = obj.t_AnaliticKind3 "
            + "          left join dfininstr_dbt fin on fin.t_FIID = obj.t_Analitic3 and obj.t_Analitic3 > 0 "
            + "          left join dllvalues_dbt val4 on val4.t_List = 3519 and val4.t_Element = obj.t_AnaliticKind4 "
            + "          left join dnamealg_dbt mr_na on mr_na.t_iTypeAlg = 7330 and mr_na.t_iNumberAlg = obj.t_Analitic4  "
            + "          left join dllvalues_dbt val5 on val5.t_List = 3519 and val5.t_Element = obj.t_AnaliticKind5 "
            + "          left join dobjattr_dbt attr on attr.t_ObjectType = " + OBJTYPE_AVOIRISS + " and attr.t_GroupID = " + OBJGROUP_AVRNPTXGROUP + " and attr.t_NumInList = TO_CHAR(obj.t_Analitic5)"
            + "          left join dllvalues_dbt val6 on val6.t_List = 3519 and val6.t_Element = obj.t_AnaliticKind6 "
            + "          left join dsfcontr_dbt sf on sf.t_ID = obj.t_Analitic6 "
            + "          left join dnamealg_dbt out_na on out_na.t_iTypeAlg = 7329 and out_na.t_iNumberAlg = (case when obj.t_FromOutSyst = 'X' then 1 else 2 end) "
            + "          left join dnamealg_dbt tech_na on tech_na.t_iTypeAlg = 7329 and tech_na.t_iNumberAlg = (case when obj.t_Technical = 'X' then 1 else 2 end) "
            + "        , dparty_dbt pt, dnptxkind_dbt knd, dfininstr_dbt cr "
            + "  where ds.t_RequestDate = ? "
            + "    and ds.t_PaymentAction = 1 "
            + "    and dp.t_PaymentID = ds.t_PaymentID "
            + "    and obj.t_ObjID = dp.t_NKDBTSObjID "
            + "    and pt.t_PartyID = obj.t_Client "
            + "    and knd.t_Element = obj.t_Kind "
            + "    and cr.t_FIID = obj.t_Cur "
            + " order by obj.t_ObjID ASC"; 

    cmd = DL_RSDCommand(query);

    cmd.AddParam(m_RepDate);

    DataSet = cmd.Execute();

    while(DataSet.moveNext())
      PrintTableLine( "N2_Date",          date(DataSet.Date),      null,
                      "N2_ClientName",    DataSet.ClientName,      null,
                      "N2_Direction",     DataSet.DirectionName,   null,
                      "N2_Level",         DataSet.Level,           null,
                      "N2_IsUser",        DataSet.IsUser,          null,
                      "N2_TaxPeriod",     DataSet.TaxPeriod,       null,
                      "N2_TaxBaseKind",   DataSet.TaxBaseKind,     null,
                      "N2_Kind",          DataSet.KindCode,        null,
                      "N2_Sum",           DataSet.Sum,             null,
                      "N2_Cur",           DataSet.CurCode,         null,
                      "N2_Sum0",          DataSet.Sum0,            null,
                      "N2_KindAnalitic1", DataSet.KindAnalitic1,   null,
                      "N2_Analitic1",     DataSet.StrAnalitic1,    null,
                      "N2_KindAnalitic2", DataSet.KindAnalitic2,   null,
                      "N2_Analitic2",     DataSet.StrAnalitic2,    null,
                      "N2_KindAnalitic3", DataSet.KindAnalitic3,   null,
                      "N2_Analitic3",     DataSet.StrAnalitic3,    null,
                      "N2_KindAnalitic4", DataSet.KindAnalitic4,   null,
                      "N2_Analitic4",     DataSet.StrAnalitic4,    null,
                      "N2_KindAnalitic5", DataSet.KindAnalitic5,   null,
                      "N2_Analitic5",     DataSet.StrAnalitic5,    null,
                      "N2_KindAnalitic6", DataSet.KindAnalitic6,   null,
                      "N2_Analitic6",     DataSet.StrAnalitic6,    null,
                      "N2_FromOutSystStr",DataSet.FromOutSystStr,  null,
                      "N2_OutSystCode",   DataSet.OutSystCode,     null,
                      "N2_OutObjID",      DataSet.OutObjID,        null, 
                      "N2_Technical",     DataSet.TechnicalStr,    null
                    );
    end;

    EndTable();
    CopyAllSheetInTotalBook(SheetName, false, GetTableRange(), 0, SheetName);
  END;

  PRIVATE MACRO Create()
    
    CreateSheetReqDias();

    CreateSheetNDR();
    
  END;

  MACRO Run()
    Run();

    for (var fileName, GetFullReportFileNames())
      return fileName;
    end;

    return "";
  END;

  initDL_CReportTemplate( NULL, "Report_TxNKDReqDias.xlsx", true, null, null, true ); 
END;


macro CreateNKDReqDiasRep()
  var cmd, DataSet, query = "";
  var RepDate = date(0,0,0);

  if(НаправлятьОтчетУНКДДиасофт() == false)
    return 0;
  end;

  cmd = DL_RSDCommand("select sysdate dt from dual");

  DataSet = cmd.execute();
  DataSet.moveNext();

  DtTmSplit(DataSet.dt, RepDate, null);

  RepDate = RepDate - 1;
  
  var RepObj = Sp_NPTXNKDReqDias_Report(RepDate);

  var FullFileNameXLSX = RepObj.Run();

  RepObj = NULL;

  if(not isStandAlone())
    FullFileNameXLSX = "$"+FullFileNameXLSX;
  end;
  
  if(FullFileNameXLSX != "")
    var day, mon, year;
    var hour, min, sec;
    var FileName, FileExt;
    
    DateSplit(date(), day, mon, year);
    TimeSplit(time(), hour, min, sec);
    
    var FromDir = SplitFile(FullFileNameXLSX, FileName, FileExt);
    
    var NewFileNameXLSX = "Отчет_по_обработке_запросов_Диасофта_УНКД_"+string(day:o:2)+string(mon:o:2)+string(year)+"_"+string(hour:f:2)+string(min:f:2)+string(sec:f:2) + ".xlsx";

    if(not RenameFile(FullFileNameXLSX, FromDir+NewFileNameXLSX))
      msgbox("Ошибка при переименовании файла отчета");
    else
      //Отправка файла
      var EMails = ПолучателиОтчетаУНКДДиасофт();

      if(EMails != "")
        var emailText, Subject, v_email_processor;
          
        query =   " select "
                + "        (select count(1) "
                + "           from dnptxnkdreqdias_dbt "
                + "          where t_RequestDate = ? "
                + "            and t_PaymentAction = 1 "
                + "        ) as CntReq, "
                + "        (select count(1) "
                + "           from dnptxnkdreqdias_dbt "
                + "          where t_RequestDate = ? "
                + "            and t_PaymentAction = 0 "
                + "        ) as CntRollback, "
                + "        (select count(1) "
                + "           from dnptxnkdreqdias_dbt "
                + "          where t_RequestDate = ? "
                + "            and t_PaymentAction = 1 "
                + "            and t_GUIDResp <> CHR(1) "
                + "        ) as CntRespReq, "
                + "        (select count(1) "
                + "           from dnptxnkdreqdias_dbt "
                + "          where t_RequestDate = ? "
                + "            and t_PaymentAction = 0 "
                + "            and t_GUIDResp <> CHR(1) "
                + "        ) as CntRespRollback, "
                + "        (select count(1) "
                + "           from dnptxnkdreqdias_dbt ds, dnptxlnkdiaspay_dbt dp "
                + "          where ds.t_RequestDate = ? "
                + "            and ds.t_PaymentAction = 1 "
                + "            and dp.t_PaymentID = ds.t_PaymentID "
                + "            and dp.t_NKDBTSObjID > 0 "
                + "        ) CntObj "
                + "   from dual ";
        
        cmd = DL_RSDCommand(query);

        cmd.AddParam(RepDate);
        cmd.AddParam(RepDate);
        cmd.AddParam(RepDate);
        cmd.AddParam(RepDate);
        cmd.AddParam(RepDate);

        DataSet = cmd.Execute();
        DataSet.moveNext();

        Subject = "Обработка запросов Диасофта об уплаченном НКД за " + string(RepDate:f);

        emailText =   "<div>"
                    + "За "+string(RepDate:f)
                    + "<br>"
                    + "<br>Всего входящих сообщений от Диасофта: " + int(DataSet.CntReq + DataSet.CntRollback)
                    + "<br>"
                    + "<br>из них запрос УНКД: " + int(DataSet.CntReq)
                    + "<br>из них откат выплаты: " + int(DataSet.CntRollback)
                    + "<br>"
                    + "<br>Всего направлено ответных сообщений в Диасофт: " + int(DataSet.CntRespReq + DataSet.CntRespRollback) 
                    + "<br>"
                    + "<br>из них ответы на запрос УНКД: " + int(DataSet.CntRespReq)
                    + "<br>из них ответы на откат выплаты: " + int(DataSet.CntRespRollback)
                    + "<br>"
                    + "<br>Всего сформировано объектов НДР 2-го уровня вида 'NkdB_TS': " + int(DataSet.CntObj)
                    + "</div>";

        v_email_processor = c_email_proc_env();

        v_email_processor.m_add_email_to_list(EMails);

        v_email_processor.m_set_msg_head(Subject);
        v_email_processor.m_add_row_to_msg_text(emailText);

        if(NewFileNameXLSX != "")
          v_email_processor.m_add_attach_to_list(FromDir+NewFileNameXLSX);
        end;

        v_email_processor.m_save_to_submit_synch(true);
        v_email_processor.m_submit_email_synch();

      end;
    end;
  end;
end;
