/*
$Name:        od03_Report.mac
$Module:      Ценные бумаги
$Description: [ОД_3] Реестр сделок РЕПО
*/


import it_utils ;

macro Rep_OD_03()
  var ReportDate = {curdate};
  var msg,XLSfile,XLSfileName, SessionID = 0 ;
  var  FileDir = IT_GetPatchTxtFile()+"\\";

  if (not GetDate(ReportDate))
    return 1;
  end;

  BegAction(0, "Сбор данных и формирование отчета \nПоиск сделок РЕПО");

  var Rsd = RsdCommand(" begin ? := RPRT_OD3.make_report(?,?); end;" );
  Rsd.addParam("SessionID",RSDBP_OUT,V_NUMERIC);
  Rsd.addParam("",RSDBP_IN,ReportDate);
  Rsd.addParam("errmsg",RSDBP_OUT,V_STRING, 2000);
  Rsd.execute();
  EndAction();

  SessionID =  Rsd.value("SessionID") ; 
  if ( SessionID <= 0 )
     msgbox(Rsd.value("errmsg"));
     return 1;
  end ;

   Rsd = RsdCommand("select id_file,file_name ,part_no from ITT_FILE t where t.file_code = it_file.get_constant_str('C_FILE_CODE_REP_OD3') and t.sessionid = ? order by part_no");
   Rsd.addParam("", RSDBP_IN, SessionID);
   Rsd.Execute();
   var DS   = TRsbDataSet(Rsd);
   while (DS.movenext())
     XLSfile = IT_FILE_CSVgetXLSfile(DS.id_file,"Report_OD3.xls","bodyline",@msg,FileDir,false) ;
     if ( not XLSfile)
       RemProgress();
       msgbox(msg);
       return 1;
     end ;
	 XLSfile.SetValue_NameCell("reportdate", ReportDate);
	 if (Ds.part_no > 1)
	     XLSfile.SetValue_NameCell("part", (string(int(Ds.part_no))+" ч."));
     end;
     SplitFile( (Ds.File_Name), XLSfileName );

	 XLSfile.SaveAsTemplate(XLSfileName,true);
   end;
   Rsd = RsdCommand("delete  from ITT_FILE t where t.file_code = it_file.get_constant_str('C_FILE_CODE_REP_OD3') and t.sessionid = ?");
   Rsd.addParam("", RSDBP_IN, SessionID);
   Rsd.Execute();
   
   EndAction ;
   RemProgress();

onerror(er)
  EndAction();
  RemProgress();
  MsgBox (er.Message);
End;

Rep_OD_03();
exit(1);