/*******************************************************************************
 DESCRIPTION  :   Отчет ""
 PROGRAMMED BY:   Сагиян С.Г.
 CREATION DATE:    18.07.2019
*******************************************************************************/
IMPORT  "spCache.mac", "od1_form.mac", "DLReport_h.mac", PtInter, "dlreport.mac", "cb_sql.mac", "sprepfun.mac", "oralib", "MoCommon.mac","ws_txreportform.mac";;

PRIVATE VAR   T_Dep:T_Dep_Collector;

PRIVATE VAR   OD1_Form;
PRIVATE VAR   OD1_Report;
PRIVATE VAR   WebMenuItem; // Информация о запуске отчета из веб

PRIVATE VAR   NFinRez;
PRIVATE VAR   NNDFL;

PRIVATE VAR ReportHeader = " \n"; 
                                                                                                                                                                                                                                                                                                                             
PRIVATE VAR TableHeader = " \n"; 

                                                                                                                                   
PRIVATE CLASS (DL_CReportTemplate) SP_OD1_Report( Form:DL_CPanel, TemplateName:STRING, UseCSV:BOOL, IsWebService:BOOL, ReportHashCode:INTEGER )
  PRIVATE VAR F0_6, F0_9, F0_11; /*суммы строки "Итого"*/
  PRIVATE VAR m_TotalAmountPoint = 0;
  PRIVATE VAR v_account = "", v_amount;
  var RS;
  VAR RepDate;
  var cmdtemp, rstemp;

  PRIVATE VAR v_BuyCost, v_BuyNKD, v_BuyTotalCost, v_SaleCost, v_SaleNKD, v_SaleTotalCost, v_ComS, v_ComB, v_FinRez;
  PRIVATE VAR v_s_BuyCost, v_s_BuyNKD, v_s_BuyTotalCost, v_s_SaleCost, v_s_SaleNKD, v_s_SaleTotalCost, v_s_ComS, v_s_ComB, v_s_FinRez;
  VAR PrevFI, PrevS;
  VAR         ProgressValue = CTxProgressValue();

  PRIVATE VAR m_IsDataExist = false; /*для Web, если нет данных, то ничего не показываем*/
/* не показывать пустые отчет в Web*/
  MACRO CReport_DataExist()
    if(m_IsWebService == true )
      return (m_IsDataExist or ReportHasError() );
    else
      return true;                   /*в EW показываем листы всегда*/
    end;
  END;

	



  PRIVATE MACRO PrintMode():INTEGER
     return DL_OUTREPORT_EXCEL;
  END;

  PRIVATE MACRO PrintLine( P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30,P31,P32,P33,P34,P35,P36,P37,P38,P39,P40,P41,P42,P43,P44,P45,P46,P47,P48,P49,P50,P51,P52,P53,P54,P55,P56)

     this.PrintTableLine( 

          /*1 */     "FICode",      P1  , null, 
          /*2 */     "Filial",      P2  , null, 
          /*3 */     "AccBal",      P3  , null, 
          /*4 */     "Acc",         P4  , null, 
          /*5 */     "FIName",      P5  , null, 
          /*6 */     "Seria",       P6  , null, 
          /*7 */     "Emitent",     P7  , null, 
          /*8 */     "ISIN",        P8  , null, 
          /*9 */     "GosReg",      P9  , null, 
          /*10*/     "NomFI",       P10 , null, 
          /*11*/     "Amount",      P11 , null, 
          /*12*/     "NominalRUR",  P12 , null, 
          /*13*/     "Nominal",     P13 , null, 
          /*14*/     "BalCostRUR",  P14 , null, 
          /*15*/     "SumRUR",      P15 , null, 
          /*16*/     "UNKD",        P16 , null, 
          /*17*/     "PKD",         P17 , null, 
          /*18*/     "Premia",      P18 , null, 
          /*19*/     "Discont",     P19 , null, 
          /*20*/     "Pereots",     P20 , null, 
          /*21*/     "Reserv",      P21 , null, 
          /*22*/     "BalCost",     P22 , null,
          /*23*/     "TT1",	    P23 , null,
          /*24*/     "TT2",	    P24 , null,
          /*25*/     "TT3",	    P25 , null,
          /*26*/     "TT4",	    P26 , null, 
          /*27*/     "Bcost",       P27 , null, 
          /*28*/     "LastCost",    P28 , null, 
          /*29*/     "Dohod",       P29 , null, 
          /*30*/     "DrawingDate", P30 , null, 
          /*31*/     "CoupProc",    P31 , null, 
          /*32*/     "CoupPeriod",  P32 , null, 
          /*33*/     "NearDate",    P33 , null, 
          /*34*/     "DayS",        P34 , null, 
          /*35*/     "Cost1",       P35 , null, 
          /*36*/     "Cost2",       P36 , null, 
          /*37*/     "Cost3",       P37 , null, 
          /*38*/     "Country1",    P38 , null, 
          /*39*/     "Country2",    P39 , null, 
          /*40*/     "Country3",    P40 , null, 
          /*41*/     "Portf",       P41 , null, 
          /*42*/     "AgName",      P42 , null, 
          /*43*/     "FIRate",      P43 , null, 
          /*44*/     "DohodEff",    P44 , null, 
          /*45*/     "ReservMSFO",  P45 , null, 
          /*46*/     "FPRSBU1",     P46 , null, 
          /*47*/     "FPRSBU2",     P47 , null, 
          /*48*/     "PereotsChange", P48 , null, 
          /*49*/     "NaDoh",       P49 , null, 
          /*50*/     "NaRash",      P50 , null, 
          /*51*/     "FPRSBU3",     P51 , null, 
          /*52*/     "Comment",     P52 , null, 
          /*53*/     "RatePlace",   P53 , null, 
          /*54*/     "ActPlace",    P54 , null, 
          /*55*/     "Ierarh",      P55 , null, 
          /*56*/     "Cost4",       P56 , null
	  
	  
	  
	  
       );      

  END;

  macro AccRest(acc, pfiid, pdate)
      var sql = " select rsb_account.RestA(t_account, ?, 1, 1) rest from dmcaccdoc_dbt where t_account like ? and t_iscommon=chr(88) and t_fiid=? ";

      var cmd = rsdCommand(sql);
      cmd.addParam("", RSDBP_IN, pdate);
      cmd.addParam("", RSDBP_IN, acc);
      cmd.addParam("", RSDBP_IN, pfiid);
      cmd.Execute();
      var getData = TRsbDataSet(cmd);
      
      if(getData.MoveNext)
       return abs(getData.Value(0)); 
      else 
       return 0;
      end;
  end;





    macro getESTRESERVE(fininstr, Data)
  
     var RetVal = $0.0;  
     var sql = 
         "SELECT  DISTINCT(t_account), RSB_ACCOUNT.RESTALL(t_account, t_chapter,t_currency, ? ) " +
         "  FROM dmcaccdoc_dbt ";
      if (RS.PORTFOLIO == 2)
         sql = sql +
         " WHERE t_catnum IN (1457, 1458) AND t_templnum = 5 and t_iscommon = CHR (88) AND t_fiid = ? " ;
      elif (RS.PORTFOLIO == 5)
         sql = sql +
         " WHERE t_catnum IN (1457, 1458) AND t_templnum in (1,3) and t_iscommon = CHR (88) AND t_fiid = ? " ; /*PDV 512006  */
      else
       //  sql = sql +
       //  " WHERE t_catnum IN (1457, 1458) and and t_templnum = 3 t_iscommon = CHR (88) AND t_fiid = ? " ;
        return 0;
      end;                                                                            
      var cmd = rsdCommand(sql);
      cmd.addParam("", RSDBP_IN, repDate);
      cmd.addParam("", RSDBP_IN, RS.FIID);
//	cmd.addParam("", RSDBP_IN, RS.FIID);
     // cmd.addParam("", RSDBP_IN, RS.ACCOUNT);
      cmd.Execute();
      var getData = TRsbDataSet(cmd);
      
      while(getData.MoveNext)
        RetVal = RetVal + getData.Value(1);  
      end;
      return RetVal; 
       
  /*     
     var sql = " SELECT  SUM (NVL (ESTRESERVE, 0)) ESTRESERVE" +
               "         FROM DPORTFOLIO_TMP t " +
               "         Where t.t_portfid = ? and t.t_fiid = ? and t.t_account =  ? and t.report_dt = ?" +
               "     GROUP BY T_PORTFID, " +
               "              T_FIID, " +
               "              T_PARTYID, " +
               "              T_AVKINDSHNAME, " +
               "              T_ACCOUNT, " +
               "              T_BALANCE ";

      var cmd = rsdCommand(sql);
      cmd.addParam("", RSDBP_IN, RS.PORTFOLIO);
      cmd.addParam("", RSDBP_IN, RS.FIID);
      cmd.addParam("", RSDBP_IN, RS.ACCOUNT);
      cmd.addParam("", RSDBP_IN, repDate);
      cmd.Execute();
      var getData = TRsbDataSet(cmd);
      
      if(getData.MoveNext)
       return getData.Value(0);  
      else 
       return 0;
      end;
          */
      // onError
      //  return 0;

    End;



    macro getCORRINTTOEIR (fininstr, Data)
/*    var RetVal = $0.0;  
     var sql = 
         "SELECT  t_account, RSB_ACCOUNT.RESTALL(t_account, t_chapter,t_currency, ? ) rest  " +
         "  FROM dmcaccdoc_dbt " +
         " WHERE t_catnum IN (1418, 1417) AND t_iscommon = CHR (88) AND t_fiid = ? " ;
      var cmd = rsdCommand(sql);
      cmd.addParam("", RSDBP_IN, repDate);
      cmd.addParam("", RSDBP_IN, RS.FIID);
      cmd.Execute();
      var getData = TRsbDataSet(cmd);
      
      while(getData.MoveNext)
        RetVal = RetVal + getData.Value(1);  
      end;
      return RetVal;*/


     var sql = " SELECT  SUM (NVL (CORRINTTOEIR, 0)) CORRINTTOEIR " +
               "         FROM DPORTFOLIO_TMP t " +
               "         Where t.t_portfid = ? and t.t_fiid = ? and t.t_account =  ? and t.report_dt = ?" +
               "     GROUP BY T_PORTFID, " +
               "              T_FIID, " +
               "              T_PARTYID, " +
               "              T_AVKINDSHNAME, " +
               "              T_ACCOUNT, " +
               "              T_BALANCE ";

      var cmd = rsdCommand(sql);
      cmd.addParam("", RSDBP_IN, RS.PORTFOLIO);
      cmd.addParam("", RSDBP_IN, RS.FIID);
      cmd.addParam("", RSDBP_IN, RS.ACCOUNT);
      cmd.addParam("", RSDBP_IN, repDate);
      cmd.Execute();
      var getData = TRsbDataSet(cmd);
      
      if(getData.MoveNext)
       return getData.Value(0);  
      else 
       return 0;
      end;
           
    End;







  PRIVATE MACRO GetRate(fi, rtype, ddate)
     VAR cmd1, rs1, cmd2, rs2;
     cmd1 = RSDCommand("select t_rate/power(10,t_point) RetVal, t_sincedate RetDate from dratedef_dbt rh where t_otherfi = ? and t_type = ? and rh.t_sincedate <= ? ");

     cmd1.AddParam( "", RSDBP_IN, fi );	  
     cmd1.AddParam( "", RSDBP_IN, rtype );	  
     cmd1.AddParam( "", RSDBP_IN, ddate );	  

     RS1 = TRsbDataSet( cmd1 );
     IF ((RS1.MoveNext) and ( RS1.RetDate <= ddate))
		return rs1.RetVal;
     else
	     cmd2 = RSDCommand("select t_rate/power(10,t_point) RetVal from dratehist_dbt rh where rh.t_rateid in " +
                       " (select t_rateid from dratedef_Dbt where t_otherfi=? and t_type=?) " + 
                       " and  rh.t_sincedate = (select max(l.t_sincedate) from dratehist_dbt l where l.t_rateid = rh.t_rateid and l.t_sincedate <= ?) ");

	     cmd2.AddParam( "", RSDBP_IN, fi );	  
	     cmd2.AddParam( "", RSDBP_IN, rtype );	  
	     cmd2.AddParam( "", RSDBP_IN, ddate );	  
	     RS2 = TRsbDataSet( cmd2 );
	     IF (RS2.MoveNext)
		return rs2.RetVal;        
	     end;
	     return 0;
     end;

  END;


  PRIVATE MACRO GetRateAccur(fi, rtype, ddate)
     VAR cmd1, rs1, cmd2, rs2;
     cmd1 = RSDCommand("select t_rate/power(10,t_point) RetVal from dratehist_dbt rh where rh.t_rateid in " +
                       " (select t_rateid from dratedef_Dbt where t_otherfi=? and t_type=?) " + 
                       " and  rh.t_sincedate =  ? ");

     cmd1.AddParam( "", RSDBP_IN, fi );	  
     cmd1.AddParam( "", RSDBP_IN, rtype );	  
     cmd1.AddParam( "", RSDBP_IN, ddate );	  

     RS1 = TRsbDataSet( cmd1 );
     IF (RS1.MoveNext)
		return rs1.RetVal;
     else
	     cmd2 = RSDCommand("select t_rate/power(10,t_point) RetVal from dratedef_dbt rh where t_otherfi = ? and t_type = ? and rh.t_sincedate = ? ");

	     cmd2.AddParam( "", RSDBP_IN, fi );	  
	     cmd2.AddParam( "", RSDBP_IN, rtype );	  
	     cmd2.AddParam( "", RSDBP_IN, ddate );	  
	     RS2 = TRsbDataSet( cmd2 );
	     IF (RS2.MoveNext)
		return rs2.RetVal;        
	     end;
	     return 0;
     end;

  END;



  PRIVATE MACRO BeginReport()

     VAR AvrKindShowValue = "";

     this.SetActiveSheet( "Лист1" );


                               

     this.PrintFormatString( ReportHeader,
                     "H0_1"  , OD1_Form.GetFieldValue( PNFLD_OD1_DATE )
                   );

     this.PrintFormatString( ReportHeader,
                     "HO_USD"  , GetRate( 7, 7, OD1_Form.GetFieldValue( PNFLD_OD1_DATE ))
                   );
     this.PrintFormatString( ReportHeader,
                     "H0_EUR"  , GetRate( 8, 7, OD1_Form.GetFieldValue( PNFLD_OD1_DATE ))
                   );


     this.RegisterTable( "MainTable", "",

          /*1 */     "FICode",
          /*2 */     "Filial",
          /*3 */     "AccBal",
          /*4 */     "Acc",
          /*5 */     "FIName",
          /*6 */     "Seria",
          /*7 */     "Emitent",
          /*8 */     "ISIN",
          /*9 */     "GosReg",
          /*10*/     "NomFI",
          /*11*/     "Amount",
          /*12*/     "NominalRUR",
          /*13*/     "Nominal",
          /*14*/     "BalCostRUR",
          /*15*/     "SumRUR",
          /*16*/     "UNKD",
          /*17*/     "PKD",
          /*18*/     "Premia",
          /*19*/     "Discont",
          /*20*/     "Pereots",
          /*21*/     "Reserv",
          /*22*/     "BalCost",
          /*23*/     "TT1",
          /*24*/     "TT2",
          /*25*/     "TT3",
          /*26*/     "TT4",  
          /*27*/     "Bcost",
          /*28*/     "LastCost",
          /*29*/     "Dohod",
          /*30*/     "DrawingDate",
          /*31*/     "CoupProc",
          /*32*/     "CoupPeriod",
          /*33*/     "NearDate",
          /*34*/     "DayS",
          /*35*/     "Cost1",
          /*36*/     "Cost2",
          /*37*/     "Cost3",
          /*38*/     "Country1",
          /*39*/     "Country2",
          /*40*/     "Country3",
          /*41*/     "Portf",
          /*42*/     "AgName",
          /*43*/     "FIRate",
          /*44*/     "DohodEff",
          /*45*/     "ReservMSFO",
          /*46*/     "FPRSBU1",
          /*47*/     "FPRSBU2",
          /*48*/     "PereotsChange",
          /*49*/     "NaDoh",
          /*50*/     "NaRash",
          /*51*/     "FPRSBU3",
          /*52*/     "Comment",
          /*53*/     "RatePlace",
          /*54*/     "ActPlace",
          /*55*/     "Ierarh",
          /*56*/     "Cost4"
	 	    
	  	    
	  	    
	  
       );      

  END;

  MACRO ПечататьПромежуточныеИтоги()
/*
     SetSubtotal(12, 11 + MAXROWSHEET,
                 "K8",    
                 "S8"
                 );
*/
  END;

  PRIVATE MACRO EndReport()
     this.EndTable();
     ПечататьПромежуточныеИтоги();
//     this.AddStandardFooter( "" );
  END;



  /*
		511-П_Признак активности и ликвидности рынка (да/нет)
	*/
    private macro get511SignLiquidMarket(inSecID)
        var sql="select a.t_name "+
                "from dobjattr_dbt a "+
                "join dobjatcor_dbt c on a.t_objecttype = c.t_objecttype and a.t_groupid = c.t_groupid and a.t_attrid = c.t_attrid "+
                "where c.t_objecttype = 12 "+   //ценная бумага
                  "and c.t_groupid = 64 "+     //категория 511-П_Признак активности и ликвидности рынка
                  "and c.t_object = lpad( :inSecID, 10, '0') "+
                  "and c.t_validtodate = to_date('31.12.9999', 'dd.mm.yyyy')";

	    var cmd = rsdCommand(sql);
	    cmd.addParam(":inSecID", RSDBP_IN, inSecID);
	    cmd.Execute();
	    var getData = TRsbDataSet(cmd);

        var rs = rsdRecordSet(cmd);
        if (rs.MoveNext)
            return rs.Value(0);
        else
            return "---";
        end;

    end;

  /*
		511-П_Уровень иерархии оценки (1/2/3)
	*/
    private macro get511GradeLevel(inSecID)
        var sql="select a.t_name "+
                "from dobjattr_dbt a "+
                "join dobjatcor_dbt c on a.t_objecttype = c.t_objecttype and a.t_groupid = c.t_groupid and a.t_attrid = c.t_attrid "+
                "where c.t_objecttype = 12 "+   //ценная бумага
                  "and c.t_groupid = 65 "+     //категория 511-П_Уровень иерархии оценки
                  "and c.t_object = lpad( :inSecID, 10, '0') "+
                  "and c.t_validtodate = to_date('31.12.9999', 'dd.mm.yyyy')";

	    var cmd = rsdCommand(sql);
	    cmd.addParam(":inSecID", RSDBP_IN, inSecID);
	    cmd.Execute();
	    var getData = TRsbDataSet(cmd);

        var rs = rsdRecordSet(cmd);
        if (rs.MoveNext)
            return rs.Value(0);
        else
            return "---";
        end;

    end;





    /*
      Получить Открытое количество ЦБ
    */

    macro getAvarAmount

     if (v_amount > 0) return v_amount;
     end;     
  
     var sql = " SELECT  SUM (NVL (T_AVRAMOUNT, 0)) T_AVRAMOUNT " +
               "         FROM DPORTFOLIO_TMP t " +
               "         Where t.t_portfid = ? and t.t_fiid = ? and t.t_account =  ? and t.report_dt = ?" +
               "     GROUP BY T_PORTFID, " +
               "              T_FIID, " +
               "              T_PARTYID, " +
               "              T_AVKINDSHNAME, " +
               "              T_ACCOUNT, " +
               "              T_BALANCE ";

      var cmd = rsdCommand(sql);
      cmd.addParam("", RSDBP_IN, rs.PORTFOLIO);
      cmd.addParam("", RSDBP_IN, rs.FIID);
      cmd.addParam("", RSDBP_IN, rs.ACCOUNT_NUMBER_2);
      cmd.addParam("", RSDBP_IN, repDate);
      cmd.Execute();
      var getData = TRsbDataSet(cmd);
      
      if(getData.MoveNext)
		v_amount = getData.Value(0);
       		return v_amount;  
      else 
       return 0;
      end;

      // onError
      //  return 0;

    End;





  PRIVATE MACRO FICode   
	return rs.avrcode;  
  END;
  
  PRIVATE MACRO Filial   
	return "0000";
	return rs.depname;  
  END;  

  PRIVATE MACRO AccBal   
	return rs.ACCOUNT_NUMBER_1;  
  END;  

  PRIVATE MACRO Acc   
	return rs.ACCOUNT_NUMBER_2;  
  END;  

  PRIVATE MACRO FIName   
	return rs.kname;  
  END;  

  PRIVATE MACRO Seria   
	return rs.avrname;  
  END;  

  PRIVATE MACRO Emitent   
	return rs.issuer; // + " (" + rs.issuerid + ")";  
  END;  

  PRIVATE MACRO ISIN   
	return rs.isin;  
  END;  

  PRIVATE MACRO GosReg   
	return rs.lsin;  
  END;  

  PRIVATE MACRO NomFI   
	return rs.currency;  
  END;  

  PRIVATE MACRO Amount   

	return getAvarAmount;
	return rs.amount;  
  END;  

  PRIVATE MACRO NominalRUR   
	var RetVal;
	if (rs.facevaluefi != NATCUR)
	        SmartConvertSumDbl(RetVal, rs.NominalVal*amount, repdate, rs.facevaluefi, NATCUR, false);
	else 
		RetVal = rs.NominalVal*amount;
	end;
	return RetVal;  
  END;  

  PRIVATE MACRO Nominal   
	if (rs.facevaluefi != NATCUR)
		return rs.NominalVal*amount;
	end;
	return 0;  
  END;  

  PRIVATE MACRO BalCostRUR
	var RetVal;

return rs.BalCost;

	if (rs.facevaluefi != NATCUR)
	        //SmartConvertSumDbl(RetVal, rs.BalCost, repdate, rs.facevaluefi, NATCUR, false);
		RetVal = rs.BalCost;
	else 
		return 0;
	end;
  END;  

  PRIVATE MACRO SumRUR   

	return rs.dealcostsum;

/*	var RetVal;
	if (rs.facevaluefi != NATCUR)
	        SmartConvertSumDbl(RetVal, rs.Summ, repdate, rs.currency, NATCUR, false);
	else 
		RetVal = rs.Summ;
	end;
	return RetVal; 
*/
  END;  

  PRIVATE MACRO UNKD   
	return rs.unkd_with_coupon; 	
  END;  

  PRIVATE MACRO PKD   
	return rs.COUPON_AMOUNT; 
  END;  

  PRIVATE MACRO Premia   
	return rs.premium_amount; 
  END;  

  PRIVATE MACRO Discont   
	return rs.discount_amount; 
  END;  

  PRIVATE MACRO Pereots   
	return rs.overvalue; 
  END;  

  PRIVATE MACRO Reserv
 //if (rs.fiid == 15346)/*PDV 512006  */
   /*if (rs.facevaluefi != NATCUR)
        return   rs.reserve_amount/GetRate( 7, 7, repdate);
      else MAA: 512799 */
	return rs.reserve_amount;
    //end; 
  END;    
 
  PRIVATE MACRO BalCost 
	var RetVal;
	if (rs.facevaluefi != NATCUR)  
	        SmartConvertSumDbl(RetVal, rs.BalCost, repdate, NATCUR, rs.facevaluefi, false);
		return RetVal;  
	else 
		return 0;
	end;
  END;  

  PRIVATE MACRO Bcost   
	return "";  
  END; 

  PRIVATE MACRO LastCost   
        var cl;
       if ((rs.T_FIID == 2354) OR (rs.T_FIID == 1508) OR (rs.T_FIID == 1556) OR (rs.T_FIID == 2432) OR (rs.T_FIID == 854) OR (rs.T_FIID == 1573)  OR (rs.T_FIID == 1464))  /*AVN: 522381 */ 
                 cl = GetRate(rs.fiid, 4, repdate);  // Средневзвешенная
         else                                                                                   
	       if (rs.T_FIID == 1953)
			 cl = 0; //дефолтная бумага
                else
			if ((rs.avoirkind == 28) OR (rs.avoirkind == 39) OR (rs.avoirkind == 41) OR (rs.avoirkind == 43))  
	       	        cl = GetRate(rs.fiid, 23, repdate);    // Блумберг
	       		if (cl == 0)                                                                               
	       		        cl = GetRate(rs.fiid, 4, repdate);  // Средневзвешенная
	       		end;                                                                                       
	       		if (cl == 0)                                                                               
	       		        cl = GetRate(rs.fiid, 1001, repdate);  // Мотивированное суждение 
	       		end;                                                                                       
	       	else                                                                                               
	       	        cl = GetRate(rs.fiid, 1001, repdate);     // Мотивированное суждение 
	       		if (cl == 0)                                                                               
	       		        cl = GetRate(rs.fiid, 4, repdate);  // Средневзвешенная
			end;
	       		 if (cl == 0)                                                              
			        cl = GetRate(rs.fiid, 23, repdate);  // Блумберг
	       		end;                                                                                       
	             end;
		end;                                                                                               
      end;
	return cl;      

  END;  

  PRIVATE MACRO Dohod   
	return "";  
  END;  

  PRIVATE MACRO DrawingDate   
	return rs.t_DrawingDate;  
  END;  


 PRIVATE MACRO dmain
	if (rs.d1 != 0) return RS.d1;
	elif (rs.d2 != 0) return RS.d2;
	else return 0;
	end;
  END;


  PRIVATE MACRO CoupProc   
	var rate = rs.coupincomerate;
	var vol = rs.coupincomevolume;
	if (rate == 0) 
              if ( dmain == 0 ) 
			return 0;
	       end;
		rate = round(vol / rs.NominalVal * 100 * 365 / dmain, 2);
	end; 

	return rate;   
  END;  

  PRIVATE MACRO CoupPeriod_try
        var RetVal;
	var d = dmain;
	var h, j;
	var counter = 0;  // если сразу не найдем период, надо поимкать предыдущий купон и посмотреть на его период.

	while (counter < 2)
		if   ((d > 27) and (d < 33) ) RetVal = "ежемесячный";
		elif ((d > 70) and (d < 95) ) RetVal = "ежеквартальный";
		elif ((d > 170) and (d < 190) ) RetVal = "полугодовой";
		elif ((d > 359) and (d < 365) ) RetVal = "годовой";
		else 
	
			h = RSDCommand("select (w1.t_drawingdate - w1.t_firstdate + 1) days from  dfiwarnts_dbt w1 where  t_ispartial = CHR (0) and  w1.t_fiid=" + rs.fiid + " and w1.t_drawingdate = " +
	                 " (SELECT MAX (t.t_drawingdate) FROM dfiwarnts_dbt t WHERE t.t_fiid = w1.t_fiid AND t_ispartial = CHR (0) AND t.t_drawingdate < " + GetSQLDate( RepDate ) + ")");
	     		j = TRSBDataSet(h);
	     		if (j.movenext)
				d = j.days;
			end;
			counter = counter - 1;
		end;
		counter = counter + 2;
	end;


	return RetVal;  
  END;  

  PRIVATE MACRO CoupPeriod
	return CoupPeriod_try;
  END;  


  PRIVATE MACRO NearDate   
	return rs.coupdrawingdate;  
  END;  

  PRIVATE MACRO DayS   
	return rs.days;  
  END;  

  PRIVATE MACRO Cost1   
	return LastCost;
  END;  

  PRIVATE MACRO Cost2   
	return "";  
  END;  

  PRIVATE MACRO Cost3   
	return "";  
  END;  

  PRIVATE MACRO Country1   
	if (rs.flag_mez > 0) 
		return "";  
	end;

	if (rs.issuer_country == "Российская Федерация")
		return "Россия";  
	end;
	return "";
  END;  

  PRIVATE MACRO Country2   
	if (rs.flag_mez > 0) 
		return "";  
	end;

	if (rs.issuer_country != "Российская Федерация")
		return rs.issuer_country;  
	end;
	return "";
  END;  

  PRIVATE MACRO Country3   
	if (rs.flag_mez > 0) 
		return "Международная организация";
	else 
		return "";  
	end;
  END;  

  PRIVATE MACRO Portf   
	return "";  
  END;  

  PRIVATE MACRO AgName   
	return "";  
  END;  

  PRIVATE MACRO FIRate   
	return rs.ISSUE_RATING_SP;  
  END;  

  PRIVATE MACRO DohodEff   
	return "";  
  END;  

  PRIVATE MACRO ReservMSFO   
	return "";  
  END;  

  PRIVATE MACRO FPRSBU1   
	return "";  
  END;  

  PRIVATE MACRO FPRSBU2   
	return "";  
  END;  

  PRIVATE MACRO PereotsChange   
	return "";  
  END;  

  PRIVATE MACRO NaDoh   
	return "";  
  END;  

  PRIVATE MACRO NaRash   
	return "";  
  END;  

  PRIVATE MACRO FPRSBU3   
	return "";  
  END;  

  PRIVATE MACRO Comment   
	return "";  
  END;  

  PRIVATE MACRO RatePlace   
	return "";  
  END;  

  PRIVATE MACRO ActPlace   
	return get511SignLiquidMarket(rs.fiid);  
  END;  

  PRIVATE MACRO Ierarh   
	return get511GradeLevel(rs.fiid);  
  END;  

  PRIVATE MACRO Cost4   
	return "";  
  END;  









                
  PRIVATE MACRO Create()

     VAR dl_leg      = TRecHandler( "dl_leg.dbt" );

     VAR DataQuery;
     VAR DealBuy;
     VAR AddWhere:string = "";

     VAR AvrFIID:integer, AvrKind:integer;       
     VAR QntySold:money = $0, SumBvpr:money = $0;
     VAR NKD:money = $0;
     VAR BuyDealTime:time, BuyPrice:double = 0.0;
     VAR StrNumbDeal1, StrNumbDeal2;
     VAR IsBlock;
            
     OD1_Form.GetFieldValue( PNFLD_OD1_DATE, @RepDate );

     NFinRez = 0;
     NNDFL = 0;

     // Проверка наличия данных
     cmdtemp = RSDCommand("select * from tRSHB_Portfolio_PKL_2CHD where report_dt = ?");
     cmdtemp.AddParam("", RSDBP_IN, RepDate);
     rstemp = TRSBDataSet(cmdtemp);
     if (not rstemp.movenext)
	 cmdtemp = RSDCommand("begin rsFillPortfolio (?); end;");
         cmdtemp.addParam( "", RSDBP_IN, repDate );
         cmdtemp.Execute();
     end;




     DataQuery = "select e.portfolio, codes.t_code avrcode, substr(e.account_number_2,10,4)  depname, e.account_number_2  account, nvl(round(war.t_incomerate,t_incomepoint), 0) coupincomerate, nvl(war.t_incomevolume, 0) coupincomevolume, " +
		 " e.*, fi.t_fiid, fi.t_facevaluefi, fi.t_avoirkind avoirkind, e.balance_price BalCost, (select count(*) from dpartyown_dbt where t_partykind=52 and t_partyid=fi.t_issuer ) flag_mez, fi.t_issuer issuerid, " +
		 "rsi_rsb_fiinstr.ConvSum((select sum(y.amount) from DPORTFOLIO_TMP y where y.t_account=e.account_number_2  and y.t_fiid=fi.t_fiid and y.t_portfid=e.portfolio and y.report_dt = e.report_dt), fi.t_facevaluefi ,0," + GetSQLDate( RepDate ) + ") dealcostsum, " +
		 " nvl((war.t_drawingdate - war.t_firstdate + 1), 0) as d1, " +
        	 " nvl((select w1.t_drawingdate - w1.t_firstdate + 1 from  dfiwarnts_dbt w1 where  t_ispartial = CHR (0) and  fi.t_fiid = w1.t_fiid  and w1.t_drawingdate = " +
                 " (SELECT MIN (t.t_drawingdate) FROM dfiwarnts_dbt t WHERE t.t_fiid = fi.t_fiid AND t_ispartial = CHR (0)  AND t.t_drawingdate > " + GetSQLDate( RepDate ) + ")), 0) as d2, " +

		 "nvl(to_char(war.t_drawingdate,'dd.mm.yyyy'),'') coupdrawingdate, to_char(e.repay_dt,'dd.mm.yyyy') t_drawingdate, fi.t_fi_code, e.fi_group kname, /*e.security_name*/ fi.t_name avrname, e.issuer issuer, e.isin isin, e.reg_number lsin, e.currency facevaluefi, rsb_fiinstr.FI_GetNominalOnDate(fi.t_fiid, " + GetSQLDate( RepDate ) + ", 0) NominalVal, (war.t_drawingdate - " + GetSQLDate( RepDate ) + ") days " +
		 "from tRSHB_Portfolio_PKL_2CHD e, dfiwarnts_dbt war, dobjcode_dbt codes, dfininstr_Dbt fi, davrkinds_dbt kinds, davoiriss_dbt avr " +
		 "where e.report_dt = " + GetSQLDate( RepDate ) + " and fi.t_fiid = war.t_fiid(+) and war.t_ispartial(+)=chr(0) and   war.t_drawingdate(+) >= " + GetSQLDate( RepDate ) + " and war.t_firstdate(+) <= " + GetSQLDate( RepDate ) +  
		 " and codes.t_objectid(+)=fi.t_fiid and codes.t_codekind(+)=103 and t_objecttype(+)=9 and fi.t_fiid = avr.t_fiid " +
		 "and e.isin=avr.t_isin   and avr.t_isin <> chr(1) and kinds.t_fi_kind=2 and fi.t_avoirkind=kinds.t_avoirkind and kinds.t_root=17 and e.account_number_2 like '50%'" +
//" and fi.t_fiid=1937 " +
		 " union " +

     		 "select e.portfolio, codes.t_code avrcode, substr(e.account_number_2,10,4)  depname, e.account_number_2  account, nvl(round(war.t_incomerate,t_incomepoint), 0) coupincomerate, nvl(war.t_incomevolume, 0) coupincomevolume, " +
		 " e.*, fi.t_fiid, fi.t_facevaluefi, fi.t_avoirkind avoirkind, e.balance_price BalCost, (select count(*) from dpartyown_dbt where  t_partykind=52 and t_partyid=fi.t_issuer  ) flag_mez, fi.t_issuer issuerid, " +
		 "rsi_rsb_fiinstr.ConvSum((select sum(y.amount) from DPORTFOLIO_TMP y where y.t_account=e.account_number_2 and y.t_fiid=fi.t_fiid  and y.t_portfid=e.portfolio  and y.report_dt = e.report_dt), fi.t_facevaluefi ,0," + GetSQLDate( RepDate ) + ") dealcostsum, " +

		 " nvl((war.t_drawingdate - war.t_firstdate + 1), 0) as d1, " +
        	 " nvl((select w1.t_drawingdate - w1.t_firstdate + 1 from  dfiwarnts_dbt w1 where  t_ispartial = CHR (0) and  fi.t_fiid = w1.t_fiid  and w1.t_drawingdate = " +
                 " (SELECT MIN (t.t_drawingdate) FROM dfiwarnts_dbt t WHERE t.t_fiid = fi.t_fiid AND t_ispartial = CHR (0)  AND t.t_drawingdate > " + GetSQLDate( RepDate ) + ")), 0) as d2, " +

		 "nvl(to_char(war.t_drawingdate,'dd.mm.yyyy'),'') coupdrawingdate, to_char(e.repay_dt,'dd.mm.yyyy') t_drawingdate, fi.t_fi_code, e.fi_group kname, /*e.security_name*/ fi.t_name avrname, e.issuer issuer, e.isin isin, e.reg_number lsin, e.currency facevaluefi, rsb_fiinstr.FI_GetNominalOnDate(fi.t_fiid, " + GetSQLDate( RepDate ) + ", 0) NominalVal, (war.t_drawingdate - " + GetSQLDate( RepDate ) + ") days " +
		 "from tRSHB_Portfolio_PKL_2CHD e, dfiwarnts_dbt war, dobjcode_dbt codes, dfininstr_Dbt fi, davrkinds_dbt kinds " +
		 "where e.report_dt = " + GetSQLDate( RepDate ) + " and fi.t_fiid = war.t_fiid(+) and war.t_ispartial(+)=chr(0) and   war.t_drawingdate(+) >= " + GetSQLDate( RepDate ) + " and war.t_firstdate(+) <= " + GetSQLDate( RepDate ) +  
		 "and codes.t_objectid(+)=fi.t_fiid and codes.t_codekind(+)=103 and t_objecttype(+)=9 " +
		 "and fi.t_name = e.security_name and kinds.t_fi_kind=2 and fi.t_avoirkind=kinds.t_avoirkind and kinds.t_root=17 and e.account_number_2 like '50%'" +
//" and fi.t_fiid=1937 " +
		 " order by account ";







     ProgressValue.Maximum = SQL_GetNRecs( DataQuery );
     ProgressValue.Current = 0;

     var ProgressIndicator = CreateProgressIndicator(m_IsWebService);

     if( m_IsWebService and (WebMenuItem != null) )
       var header = "Формирование отчета " + WebMenuItem.szNameItem;
       ProgressIndicator.Start(ProgressValue.Maximum, header, header);
     else
       ProgressIndicator.Start(ProgressValue.Maximum,"\"Остаток ценных бумаг в портфеле\"" , HTML_StSheetName);
     end;
     PrevFi = 0;
     PrevS = 0;
     v_s_BuyCost = 0; v_s_BuyNKD = 0; v_s_BuyTotalCost = 0; v_s_SaleCost = 0; v_s_SaleNKD = 0; v_s_SaleTotalCost = 0; v_s_ComS = 0; v_s_ComB = 0; v_s_FinRez = 0;

     RS = TRsbDataSet( DataQuery );
     while( RS.MoveNext() )
    

	  v_account = "";
	  v_amount = 0;

          m_IsDataExist = true;
          PrintLine( 
          /*1 */     FICode,
          /*2 */     Filial,
          /*3 */     AccBal,
          /*4 */     Acc,
          /*5 */     FIName,
          /*6 */     Seria,
          /*7 */     Emitent,
          /*8 */     ISIN,
          /*9 */     GosReg,
          /*10*/     NomFI,
          /*11*/     Amount,
          /*12*/     NominalRUR,
          /*13*/     Nominal,
          /*14*/     BalCostRUR,
          /*15*/     SumRUR,
          /*16*/     UNKD,
          /*17*/     PKD,
          /*18*/     Premia,
          /*19*/     Discont,
          /*20*/     Pereots,
          /*21*/     Reserv,
          /*22*/     BalCost,
          /*23*/     getCORRINTTOEIR(RS.fiid, RepDate),  
          /*24*/     getESTRESERVE(RS.fiid, RepDate),    
          /*25*/     0,                                  
          /*26*/     AccRest("50905%", RS.fiid, RepDate), 
          /*27*/     Bcost,
          /*28*/     LastCost,
          /*29*/     Dohod,
          /*30*/     DrawingDate,
          /*31*/     CoupProc,
          /*32*/     CoupPeriod,
          /*33*/     NearDate,
          /*34*/     DayS,
          /*35*/     Cost1,
          /*36*/     Cost2,
          /*37*/     Cost3,
          /*38*/     Country1,
          /*39*/     Country2,
          /*40*/     Country3,
          /*41*/     Portf,
          /*42*/     AgName,
          /*43*/     FIRate,
          /*44*/     DohodEff,
          /*45*/     ReservMSFO,
          /*46*/     FPRSBU1,
          /*47*/     FPRSBU2,
          /*48*/     PereotsChange,
          /*49*/     NaDoh,
          /*50*/     NaRash,
          /*51*/     FPRSBU3,
          /*52*/     Comment,
          /*53*/     RatePlace,
          /*54*/     ActPlace,
          /*55*/     Ierarh,
          /*56*/     Cost4
	  
	  
	  
	  
    );

        ProgressValue.Current = ProgressValue.Current + 1;
        ProgressIndicator.Update(ProgressValue.Current,ProgressValue.Maximum);
     end;
     ProgressIndicator.Stop();

  END;
  
  initDL_CReportTemplate( Form, TemplateName, UseCSV, IsWebService, ReportHashCode );
END;

MACRO ReportRunEx(
  IsWebService    : Bool
 ,FormData      //: CTxReportForm
 ,ReportHashCode  : Integer
 ,menuItem      //: WsMenuItem
)
  var stat = true;
  var FullReportFileNames = TArray();
  WebMenuItem = menuItem;

  OD1_Form = DL_OD1_Panel();

  stat = OD1_Form.Run();

  if( stat )
      OD1_Report = SP_OD1_Report( null, "OLD_Report_OD_1.xls", null, IsWebService, ReportHashCode );
      OD1_Report.Run();

      Dl_CallInsertStat( DL_OUTREPORT_EXCEL );
  end;

  return FullReportFileNames;
END;
