/*******************************************************************************
 DESCRIPTION  :   Отчет "Расшифровка 401 в части долговых ценных бумаг"
 PROGRAMMED BY:   Сагиян С.Г.
 CREATION DATE:    12.02.2019
*******************************************************************************/
IMPORT "spCache.mac", "r1_401_form.mac", "DLReport_h.mac", PtInter, "dlreport.mac", "cb_sql.mac", "sprepfun.mac", "oralib", "MoCommon.mac","ws_txreportform.mac";;
//import "sccomiss.mac", "spRepFun.mac"

PRIVATE VAR   T_Dep:T_Dep_Collector;

PRIVATE VAR   OD1_Form;
PRIVATE VAR   OD1_Report;
PRIVATE VAR   WebMenuItem; // Информация о запуске отчета из веб

PRIVATE VAR   NFinRez;
PRIVATE VAR   NNDFL;

PRIVATE VAR ReportHeader = " \n"; 
                                                                                                                                                                                                                                                                                                                             
PRIVATE VAR TableHeader = " \n"; 

                                                                                                                                    
PRIVATE CLASS (DL_CReportTemplate) SP_OD1_Report( Form:DL_CPanel, TemplateName:STRING, UseCSV:BOOL, IsWebService:BOOL, ReportHashCode:INTEGER )
  PRIVATE VAR F0_6, F0_9, F0_11; /*суммы строки "Итого"*/
  PRIVATE VAR m_TotalAmountPoint = 0;
  PRIVATE VAR v_account = "";
  var RS, RS1;
  VAR RepDate, BeginDate, EndDate;

  PRIVATE VAR v_BuyCost, v_BuyNKD, v_BuyTotalCost, v_SaleCost, v_SaleNKD, v_SaleTotalCost, v_ComS, v_ComB, v_FinRez;
  PRIVATE VAR v_s_BuyCost, v_s_BuyNKD, v_s_BuyTotalCost, v_s_SaleCost, v_s_SaleNKD, v_s_SaleTotalCost, v_s_ComS, v_s_ComB, v_s_FinRez;
  VAR v_Acc;
  VAR         ProgressValue = CTxProgressValue();

  PRIVATE VAR m_IsDataExist = false; /*для Web, если нет данных, то ничего не показываем*/
/* не показывать пустые отчет в Web*/
  MACRO CReport_DataExist()
    if(m_IsWebService == true )
      return (m_IsDataExist or ReportHasError() );
    else
      return true;                   /*в EW показываем листы всегда*/
    end;
  END;

  PRIVATE MACRO PrintMode():INTEGER
     return DL_OUTREPORT_EXCEL;
  END;

  PRIVATE MACRO PrintLine( P1,P2,P3,P4,P5,P6,P7,P8,P9)

     this.PrintTableLine( 

          /*1 */     "OpDate",      P1  , null, 
          /*2 */     "Acc",      P2  , null, 
          /*3 */     "Emitent",      P3  , null, 
          /*4 */     "ISIN",         P4  , null, 
          /*5 */     "FiCode",      P5  , null, 
          /*6 */     "FiVal",       P6  , null, 
          /*7 */     "OperType",     P7  , null, 
          /*8 */     "Contractor",        P8  , null, 
          /*9 */     "TotalCost",      P9  , null
       );      

  END;


  PRIVATE MACRO PrintLine1( P1,P2,P3,P4,P5,P6,P7,P8,P9)

     this.PrintTableLine( 

          /*1 */     "OpDate:b",      P1  , null, 
          /*2 */     "Acc:b",      P2  , null, 
          /*3 */     "Emitent:b",      P3  , null, 
          /*4 */     "ISIN:b",         P4  , null, 
          /*5 */     "FiCode:b",      P5  , null, 
          /*6 */     "FiVal:b",       P6  , null, 
          /*7 */     "OperType:b",     P7  , null, 
          /*8 */     "Contractor:b",        P8  , null, 
          /*9 */     "TotalCost:b",      P9  , null
       );      

  END;   



  PRIVATE MACRO BeginReport()

     VAR AvrKindShowValue = "";

     this.SetActiveSheet( "Лист1" );
     
     VAR cmd1, rs1;


     cmd1 = RSDCommand("select to_char(d,'dd.mm.yyyy') begindate, to_char(d + interval '1' month, 'dd.mm.yyyy') enddate from  (select  to_date( '01.'|| to_char( ? , 'mm.yyyy'), 'dd.mm.yyyy') d from dual)");
     cmd1.AddParam( "", RSDBP_IN, OD1_Form.GetFieldValue( PNFLD_OD1_DATE ) );	  
     RS1 = TRsbDataSet( cmd1 );
     RS1.MoveNext;
     BeginDate = RS1.BeginDate;
     EndDate = RS1.EndDate;


                               

     this.PrintFormatString( ReportHeader,
                     "H0_1"  , BeginDate + " - " + EndDate 
                   );


     this.RegisterTable( "MainTable", "",

          /*1 */     "OpDate",
          /*2 */     "Acc",
          /*3 */     "Emitent",
          /*4 */     "ISIN",
          /*5 */     "FiCode",
          /*6 */     "FiVal",
          /*7 */     "OperType",
          /*8 */     "Contractor",
          /*9 */     "TotalCost"
       );      

  END;

  MACRO ПечататьПромежуточныеИтоги()
/*
     SetSubtotal(12, 11 + MAXROWSHEET,
                 "K8",    
                 "S8"
                 );
*/
  END;

  PRIVATE MACRO EndReport()
     this.EndTable();
     ПечататьПромежуточныеИтоги();
//     this.AddStandardFooter( "" );
  END;


  PRIVATE MACRO OpDate
	return rs.DealDate;
  END;

  PRIVATE MACRO Acc
     return rs1.Acc;
  END;

  PRIVATE MACRO Emitent
	return rs.Emitent;
  END;

  PRIVATE MACRO ISIN
	return rs.ISIN;
  END;

  PRIVATE MACRO FiCode
	return rs.sec_code;
  END;

  PRIVATE MACRO FiVal
	return rs.FiVal;
  END;

  PRIVATE MACRO OperType

	if (rs1.ground== Null)
	return " Зачисление на счет вложений ценной бумаги при покупке по сделке ";
	else
	return rs1.ground + " (" + rs.dealid + ")"; 
	end;	
  END;

  PRIVATE MACRO Contractor
	return rs.Contractor;
  END;

  PRIVATE MACRO TotalCost
	return rs1.summ;
  END;


  MACRO GetDealSUMM(dealid, facevalfi/*GAA: 509683*/, dealtype, dealpart)
	var cmd, rs, query;
	query = 
		"SELECT T.T_ACCOUNT_PAYER, T.T_ACCOUNT_RECEIVER, t.t_fiid_receiver, t.t_sum_payer summ1, t_sum_receiver summ2, t_fiid_payer fiid1, t_fiid_receiver fiid2, t_ground  FROM dacctrn_dbt t " +
		"WHERE ( (t.t_AccTrnID IN  (SELECT docs.t_AccTrnID FROM doprdocs_dbt docs, doproper_dbt opr WHERE     opr.t_DocKind = 101 AND opr.t_DocumentID = LPAD (?, 34, chr(48)) AND docs.t_ID_Operation = opr.t_ID_Operation AND docs.t_DocKind = 1)  " +
		"OR t.t_AccTrnID IN (SELECT grdoc.t_DocID FROM ddlgrdeal_dbt grdeal, ddlgrdoc_dbt grdoc WHERE     grdeal.t_DocKind = 101 AND grdeal.t_DocID = ? AND grdoc.t_GrDealID = grdeal.t_ID AND grdoc.t_DocKind = 1))) ";
  //               "and ( substr(t_account_payer, 1, 3) = '474' and substr(t_account_receiver, 1, 3) = '474')  ";
        /*GAA: 509683*/
        if (dealtype == 12127/*ПРЕПО*/)
           if (dealpart == 2)
              query = query +"and ( substr(t_account_payer, 1, 3) = '315' and substr(t_account_receiver, 1, 5) = '47404')  ";
           else
              query = query +"and ( substr(t_account_payer, 1, 5) = '47404' and substr(t_account_receiver, 1, 3) = '315')  ";           
           end;
        else
            query = query +"and ( substr(t_account_payer, 1, 3) = '474' and substr(t_account_receiver, 1, 3) = '474')  ";
        end;/*GAA*/

	cmd = RSDCommand( Query );
	cmd.AddParam( "", RSDBP_IN, dealid );	  
	cmd.AddParam( "", RSDBP_IN, dealid );	  
	rs = TRsbDataSet( cmd );
	if ( rs.movenext )	
	        if (rs.fiid1 == facevalfi)  return rs.summ1;
		else return rs.summ2;
		end;
	end;
  END;



  PRIVATE MACRO Create()

     VAR DataQuery, DataQuery1;
     VAR cmd, cmd1;
     VAR DealBuy;
     VAR AddWhere:string = "";

     VAR AvrFIID:integer, AvrKind:integer;       
     VAR QntySold:money = $0, SumBvpr:money = $0;
     VAR NKD:money = $0;
     VAR BuyDealTime:time, BuyPrice:double = 0.0;
     VAR StrNumbDeal1, StrNumbDeal2;
     VAR IsBlock;
     VAR SUMM_SUM;
            
//     OD1_Form.GetFieldValue( PNFLD_OD1_DATE, @RepDate );

     NFinRez = 0;
     NNDFL = 0;

     DataQuery ="select distinct fi.t_definition def, to_char(tick.t_dealdate,'dd.mm.yyyy') t_dealdate, tick.t_bofficekind, tick.t_dealcode, tick.t_dealid dealid, t_dealtype, leg.T_LEGKIND  dealpart, tick.T_CLOSEDATE/*leg.T_MATURITY PDV 512564 */  datepart, /*GAA:509683*/pat.t_shortname emitent, avr.t_isin isin, (select t_code from dobjcode_Dbt where t_codekind=103 and t_objecttype=9 and rownum=1 and t_objectid=fi.t_fiid) sec_code, facevalfi.t_iso_number FiVal,  facevalfi.t_fiid facevalfi,  contrpat.t_shortname Contractor, " +
                /*GAA:509683*/
                "  (CASE when tick.t_dealtype = 12127 /*ПРЕПО*/ then "+
                "       case when   leg.T_LEGKIND = 0 then 'Оплата ценных бумаг по 1 ч. сделки Прямое РЕПО на бирже без признания ц/б №'|| tick.t_dealcode "+
                "            else 'Оплата второй части сделки прямого РЕПО без прек. признания №'|| tick.t_dealcode||' с ЦБ '||fi.t_definition end         "+/*GAA*/
		" when tick.t_dealtype in (2162,12143,12144,12183,32732) then 'Сделка покупки '|| tick.t_dealcode else 'Сделка продажи '|| tick.t_dealcode end) dealcode1 " +
  
		"from ddl_tick_dbt tick, dparty_dbt pat, dfininstr_dbt fi, davoiriss_dbt avr, dparty_dbt contrpat, dfininstr_Dbt facevalfi, ddl_leg_dbt leg "+
		"where tick.t_pfi = fi.t_fiid and fi.t_fiid = avr.t_fiid "+
		"and facevalfi.t_fiid = fi.t_facevaluefi "+
		"and fi.t_issuer = pat.t_partyid and pat.t_notresident=chr(88) "+/*GAA:521140 - кто-то зачем-то закоментил and pat.t_notresident=chr(88). Как так-то!? */
		"and tick.t_dealtype in (2162,2172,12143,12144,12153,12154,12183,12193 ,12127,32732, 32742) " + //GAA:509631, new: 12127(ПРЕПО бирж)+ GAA:521140, new 32742 (Возврат ц/б в ДУ)
		"and tick.t_partyid = contrpat.t_partyid(+) "+
		"and  (contrpat.t_notresident=chr(0) or contrpat.t_notresident is null) "+
		"and t_bofficekind=101 and leg.t_dealid=tick.t_dealid and leg.t_expiry >=  " + GetSQLDate( BeginDate ) + " and leg.t_expiry <  " + GetSQLDate( EndDate ) + " order by tick.t_dealid, leg.T_LEGKIND  /*GAA:509683 1*/";

     DataQuery1 = "SELECT                 /*+LEADING(grdeal) INDEX(grdeal ddlgrdeal_dbt_idx1)*/      t.t_fiid_payer, t.t_account_payer acc, sum(t.t_sum_payer) summ, "+
//                 substr(   max(t.t_ground), 1, instr( max(t.t_ground), ?)-2 ) 
                " case when ?/*t_dealtype*/ = 12127 /*ПРЕПО*/ then max(t.t_ground) else SUBSTR (MAX (t.t_ground), 1, INSTR (MAX (t.t_ground), ?) - 2)end "+ /*GAA:509683*/
                " t_ground, t.T_DATE_CARRY    FROM dacctrn_dbt t " +//// GAA: 504077 , t.T_DATE_CARRY 
		"WHERE (t.t_acctrnid >= -2147483648)  AND ( (t.t_AccTrnID IN  (SELECT docs.t_AccTrnID FROM doprdocs_dbt docs, doproper_dbt opr WHERE     opr.t_DocKind = 101 AND opr.t_DocumentID = LPAD (?, 34, 0) AND docs.t_ID_Operation = opr.t_ID_Operation AND docs.t_DocKind = 1) " +
		"OR t.t_AccTrnID IN (SELECT grdoc.t_DocID FROM ddlgrdeal_dbt grdeal, ddlgrdoc_dbt grdoc WHERE     grdeal.t_DocKind = 101 AND grdeal.t_DocID = ? AND grdoc.t_GrDealID = grdeal.t_ID AND grdoc.t_DocKind = 1))) " +
//		"and substr(t_account_payer, 1, 5) = any('50210','50211','50110', '50109 ', '50208','50207') "+
                " AND SUBSTR (t_account_payer, 1, 5)  IN ('50108', '50109', '50110', '50209', '50210', '50211', '50405', '50406', '50407', '50607', '50608', '50707', '50708') "+    /* MAA: iSupport - 524401 */
                " and t.T_DATE_CARRY = ?"+  /*GAA:509683*/
                " group by t.t_fiid_payer, t.t_account_payer, t.T_DATE_CARRY " +    // GAA: 504077 , t.T_DATE_CARRY // 06.02.2020 RAS: 504873, добавил счета '50110', '50109'//GAA: 509631, new: 50208 
		"union " +
		"SELECT                 /*+LEADING(grdeal) INDEX(grdeal ddlgrdeal_dbt_idx1)*/       t.t_fiid_receiver, t.t_account_receiver acc, sum(t.t_sum_receiver),"+
// substr(   max(t.t_ground), 1, instr( max(t.t_ground), ?)-2 ) 
                " case when ?/*t_dealtype*/ = 12127 /*ПРЕПО*/ then max(t.t_ground) else SUBSTR (MAX (t.t_ground), 1, INSTR (MAX (t.t_ground), ?) - 2)end "+/*GAA:509683*/
                " t_ground, t.T_DATE_CARRY  FROM dacctrn_dbt t " + // GAA: 504077 , t.T_DATE_CARRY 
		"WHERE (t.t_acctrnid >= -2147483648)  AND ( (t.t_AccTrnID IN  (SELECT docs.t_AccTrnID FROM doprdocs_dbt docs, doproper_dbt opr WHERE     opr.t_DocKind = 101 AND opr.t_DocumentID = LPAD (?, 34, 0) AND docs.t_ID_Operation = opr.t_ID_Operation AND docs.t_DocKind = 1) " +
		"OR t.t_AccTrnID IN (SELECT grdoc.t_DocID FROM ddlgrdeal_dbt grdeal, ddlgrdoc_dbt grdoc WHERE     grdeal.t_DocKind = 101 AND grdeal.t_DocID = ? AND grdoc.t_GrDealID = grdeal.t_ID AND grdoc.t_DocKind = 1))) " +
//		"and substr(t_account_receiver, 1, 5) = any ('50210','50211', '50110', '50109', '50208','50207')"+
                " AND SUBSTR (t_account_receiver, 1, 5)  IN ('50108', '50109', '50110', '50209', '50210', '50211', '50405', '50406', '50407', '50607', '50608', '50707', '50708') "+   /* MAA: iSupport - 524401 */
                " and t.T_DATE_CARRY = ?"+   
                " group by t.t_fiid_receiver, t.t_account_receiver, t.T_DATE_CARRY " +  // GAA: 504077 , t.T_DATE_CARRY // 06.02.2020 RAS: 504873, добавил счета '50110', '50109''//GAA: 509631, new: 50208 
		"ORDER BY acc ";   


     ProgressValue.Maximum = SQL_GetNRecs( DataQuery );
     ProgressValue.Current = 0;
     
     var ProgressIndicator = CreateProgressIndicator(m_IsWebService);
     
     if( m_IsWebService and (WebMenuItem != null) )
       var header = "Формирование отчета " + WebMenuItem.szNameItem;
       ProgressIndicator.Start(ProgressValue.Maximum, header, header);
     else
       ProgressIndicator.Start(ProgressValue.Maximum,"\"Расшифровка 401 в части долговых ценных бумаг\"" , HTML_StSheetName);
     end;

     RS = TRsbDataSet( DataQuery );
     while( RS.MoveNext() )
          SUMM_SUM = 0;
	  cmd1 = RSDCommand( DataQuery1 );
	  cmd1.AddParam( "", RSDBP_IN, RS.t_dealtype );	  /*GAA:509683*/
	  cmd1.AddParam( "", RSDBP_IN, RS.def );
	  cmd1.AddParam( "", RSDBP_IN, RS.dealid );	  
	  cmd1.AddParam( "", RSDBP_IN, RS.dealid );	  
//	  cmd1.AddParam( "", RSDBP_IN, RS.t_dealtype ); /*GAA:509683*/
//	  cmd1.AddParam( "", RSDBP_IN, RS.t_dealtype ); /*GAA:509683*/
	  cmd1.AddParam( "", RSDBP_IN, RS.datepart ); /*GAA:509683*/

	  cmd1.AddParam( "", RSDBP_IN, RS.t_dealtype ); /*GAA:509683*/
	  cmd1.AddParam( "", RSDBP_IN, RS.def );
	  cmd1.AddParam( "", RSDBP_IN, RS.dealid );	  
	  cmd1.AddParam( "", RSDBP_IN, RS.dealid );
//	  cmd1.AddParam( "", RSDBP_IN, RS.t_dealtype ); /*GAA:509683*/
//	  cmd1.AddParam( "", RSDBP_IN, RS.t_dealtype ); /*GAA:509683*/
	  cmd1.AddParam( "", RSDBP_IN, RS.datepart ); /*GAA:509683*/
	  RS1 = TRsbDataSet( cmd1 );
//m_IsDataExist = true;
          while( RS1.MoveNext() )
           if ((RS.t_dealtype == 32732)  or (RS.t_dealtype == 32742))  /*PDV 517873*/ /*GAA: 521140, вернул правки из темы 517873 + new:or (RS.t_dealtype == 32742)*/    
	          m_IsDataExist = true;
	          PrintLine( 
	          /*1 */     date(RS1.DATE_CARRY), //OpDate,  //GAA: 504077
	          /*2 */     Acc,
	          /*3 */     Emitent,
	          /*4 */     ISIN,
	          /*5 */     FICode,
	          /*6 */     FiVal,
	          /*7 */     OperType,
	          /*8 */    "ООО РСХБ Упаравление Активами" ,
	          /*9 */     TotalCost );

		  SUMM_SUM = SUMM_SUM + RS1.summ;
           else
	          m_IsDataExist = true;
	          PrintLine( 
	          /*1 */     date(RS1.DATE_CARRY), //OpDate,  //GAA: 504077
	          /*2 */     Acc,
	          /*3 */     Emitent,
	          /*4 */     ISIN,
	          /*5 */     FICode,
	          /*6 */     FiVal,
	          /*7 */     OperType,
	          /*8 */     Contractor,
	          /*9 */     TotalCost );
		
		  SUMM_SUM = SUMM_SUM + RS1.summ;

 	   end; 
 	 end; 
         if (m_IsDataExist) 
            if ((RS.t_dealtype == 32732) or (RS.t_dealtype == 32742))  /*PDV 517873*/ /*GAA: 521140, вернул правки из темы 517873 + new:or (RS.t_dealtype == 32742)*/    
//		PrintLine1( "","","","","","",RS.dealcode1,"",GetDealSUMM(rs.dealid, rs.facevalfi));
		PrintLine1( "","","","","","",RS.dealcode1,"",/*GetDealSUMM(rs.dealid, rs.facevalfi,RS.t_dealtype, rs.dealpart)*/ SUMM_SUM);/*GAA:509683*/
		m_IsDataExist = false;
             else 
		PrintLine1( "","","","","","",RS.dealcode1,"",GetDealSUMM(rs.dealid, rs.facevalfi,RS.t_dealtype, rs.dealpart));/*GAA:509683*/
		m_IsDataExist = false;
             end;
	 end;

        ProgressValue.Current = ProgressValue.Current + 1;
        ProgressIndicator.Update(ProgressValue.Current,ProgressValue.Maximum);
     end;
     ProgressIndicator.Stop();

  END;
  
  initDL_CReportTemplate( Form, TemplateName, UseCSV, IsWebService, ReportHashCode );
END;

MACRO ReportRunEx(
  IsWebService    : Bool
 ,FormData      //: CTxReportForm
 ,ReportHashCode  : Integer
 ,menuItem      //: WsMenuItem
)
  var stat = true;
  var FullReportFileNames = TArray();
  WebMenuItem = menuItem;

  OD1_Form = DL_OD1_Panel();

  stat = OD1_Form.Run();

  if( stat )
      OD1_Report = SP_OD1_Report( null, "Report_401_1.xls", null, IsWebService, ReportHashCode );
      OD1_Report.Run();

      Dl_CallInsertStat( DL_OUTREPORT_EXCEL );
  end;

  return FullReportFileNames;
END;
