/*******************************************************************************
 DESCRIPTION  :   Отчет "Доходы и расходы по операциям неттинга" (НУ) - форма ввода данных
 PROGRAMMED BY:   Никольская В.В.
 CREATION DATE:   11.02.08
*******************************************************************************/
import "secinter.mac", "DlRepForm_h.mac", "globals.mac";

CONST PNFLD_OPNETREG_PERIOD          = 0,
      PNFLD_OPNETREG_YEAR            = 1, 
      PNFLD_OPNETREG_GROWINGSUMM     = 2, 
      PNFLD_OPNETREG_FACERUR         = 3, 
      PNFLD_OPNETREG_FACECUR         = 4, 
      PNFLD_OPNETREG_CIRCINMARKET    = 5, 
      PNFLD_OPNETREG_NOTCIRCINMARKET = 6, 
      PNFLD_OPNETREG_STATEAV         = 7, 
      PNFLD_OPNETREG_MUNICIPALAV     = 8,
      PNFLD_OPNETREG_CORPORATIVEAV   = 9,
      PNFLD_OPNETREG_NATIONALAV      = 10, 
      PNFLD_OPNETREG_FOREIGNAV       = 11, 
      PNFLD_OPNETREG_ALLAV           = 12, 
      PNFLD_OPNETREG_SHAREAV         = 13, 
      PNFLD_OPNETREG_DEPOSAV         = 14, 
      PNFLD_OPNETREG_BONDAV          = 15, 
      PNFLD_OPNETREG_APPOSTR         = 16; 


CONST H_PNFLD_ALLAV      = 20,
      H_PNFLD_SHAREAV    = 21,
      H_PNFLD_DEPOSAV    = 22,
      H_PNFLD_BONDAV     = 23;

MACRO FldProc_AllAv( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT):INTEGER
  if( Cmd == DLG_INIT ) /*Установка значения в поле*/
     FldShowValue = FldRealValue;
  elif( (Cmd == DLG_KEY) AND (Key == KEY_SPACE) )
     if( FldRealValue != "X" )
        FldRealValue = FldShowValue = "X";
        pThis.SetLinkedValue(H_PNFLD_SHAREAV,"");
        pThis.SetLinkedValue(H_PNFLD_DEPOSAV,"");
        pThis.SetLinkedValue(H_PNFLD_BONDAV,"");
     end;
  end;
  return CM_DEFAULT;
END;

MACRO FldProc_ShareAv( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT):INTEGER
  if( Cmd == DLG_INIT ) /*Установка значения в поле*/
     FldShowValue = FldRealValue;
  elif( (Cmd == DLG_KEY) AND (Key == KEY_SPACE) )
     if( FldRealValue != "X" )
        FldRealValue = FldShowValue = "X";
        pThis.SetLinkedValue(H_PNFLD_DEPOSAV,"");
        pThis.SetLinkedValue(H_PNFLD_BONDAV,"");
        pThis.SetLinkedValue(H_PNFLD_ALLAV,"");
     end;
  end;
  return CM_DEFAULT;
END;

MACRO FldProc_DeposAv( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT):INTEGER
  if( Cmd == DLG_INIT ) /*Установка значения в поле*/
     FldShowValue = FldRealValue;
  elif( (Cmd == DLG_KEY) AND (Key == KEY_SPACE) )
     if( FldRealValue != "X" )
        FldRealValue = FldShowValue = "X";
        pThis.SetLinkedValue(H_PNFLD_BONDAV,"");
        pThis.SetLinkedValue(H_PNFLD_ALLAV,"");
        pThis.SetLinkedValue(H_PNFLD_SHAREAV,"");
     end;
  end;
  return CM_DEFAULT;
END;

MACRO FldProc_BondAv( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT):INTEGER
  if( Cmd == DLG_INIT ) /*Установка значения в поле*/
     FldShowValue = FldRealValue;
  elif( (Cmd == DLG_KEY) AND (Key == KEY_SPACE) )
     if( FldRealValue != "X" )
        FldRealValue = FldShowValue = "X";
        pThis.SetLinkedValue(H_PNFLD_ALLAV,"");
        pThis.SetLinkedValue(H_PNFLD_SHAREAV,"");
        pThis.SetLinkedValue(H_PNFLD_DEPOSAV,"");
     end;
  end;
  return CM_DEFAULT;
END;

PRIVATE MACRO Default( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT ):INTEGER
  FldShowValue = FldRealValue;
  return CM_DEFAULT;
END;

CLASS (DL_CPanel) SP_OpNetReg_Panel()

  PRIVATE MACRO Init()
     VAR CurMonth, Year, Month;

     DateSplit( {curdate}, null, CurMonth, Year );

     AddFieldProc( 0, PNFLD_OPNETREG_PERIOD,          DL_PNFLD_PERIOD,       @DL_FldProc_Period,   ((CurMonth-1)/3 + 1) + 12, 18, 4 );/*умолч - текущий период в кварталах*/
     AddFieldProc( 0, PNFLD_OPNETREG_YEAR,            DL_PNFLD_YEAR,         @DL_FldProc_Year,     Year );/*умолч - текущий год*/

     AddFieldProc( 0, PNFLD_OPNETREG_GROWINGSUMM,     DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );

     AddFieldProc( 0, PNFLD_OPNETREG_FACERUR,         DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );
     AddFieldProc( 0, PNFLD_OPNETREG_FACECUR,         DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );

     AddFieldProc( 0, PNFLD_OPNETREG_CIRCINMARKET,    DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );
     AddFieldProc( 0, PNFLD_OPNETREG_NOTCIRCINMARKET, DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );
 
     AddFieldProc( 0, PNFLD_OPNETREG_STATEAV,         DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );
     AddFieldProc( 0, PNFLD_OPNETREG_MUNICIPALAV,     DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );
     AddFieldProc( 0, PNFLD_OPNETREG_CORPORATIVEAV,   DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" ); 

     AddFieldProc( 0, PNFLD_OPNETREG_NATIONALAV,      DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );
     AddFieldProc( 0, PNFLD_OPNETREG_FOREIGNAV,       DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );

     AddFieldProc( 0, PNFLD_OPNETREG_ALLAV,           H_PNFLD_ALLAV,         @FldProc_AllAv,       "X" );
     AddFieldProc( 0, PNFLD_OPNETREG_SHAREAV,         H_PNFLD_SHAREAV,       @FldProc_ShareAv,     "" );
     AddFieldProc( 0, PNFLD_OPNETREG_DEPOSAV,         H_PNFLD_DEPOSAV,       @FldProc_DeposAv,     "" );
     AddFieldProc( 0, PNFLD_OPNETREG_BONDAV,          H_PNFLD_BONDAV,        @FldProc_BondAv,      "" );

     AddFieldProc( 0, PNFLD_OPNETREG_APPOSTR,         DL_PNFLD_CHECKBOX,     @DL_FldProc_CheckBox, "X" );
  END;

  PRIVATE MACRO Check():BOOL
     return true;
  END;

  initDL_CPanel( "sp_res.lbr", "REPOPNET" ); 
END;