/*
$Name:         rtcp099.mac
$Module:       Ценные бумаги
$Description:  Операции погашения купона/ ЧП Шаг - закрытие операции
*/
import "sp_class.mac";

macro ExecuteStep( docum, ticket )

 record deal(dl_tick);
 var FD;

 SetBuff( deal, ticket ); 
 FD = SPFirstDoc( deal );
 if(FD.ExistRqMoney(DLRQ_TYPE_PAYMENT))   
    if( ( not IsBROKER(FD.Group) ) AND (FD.tick.rec.Flag1 != SET_CHAR) OR (FD.tick.rec.CarryWrt == UNSET_CHAR))
       if( FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.State != DLRQ_STATE_EXEC )
          MsgBox("Не выполнен шаг получения средств");
          return 1;
       end;
    end;
  
    if( ТОЗакрыто( FD.GetRQ(DLRQ_TYPE_PAYMENT) ) != true) 
       MsgBox( "ТО по оплате не закрыт.|Возможно выполнены не все проводки по оплате ц/б." );
       return 1;
    end;
 end;
 if( FD.ЕстьНеиспТО() )
    MsgBox("Обработаны не все ТО по операции");
    return 1;
 end;

 return 0;

end;
