/*
$Name:         securown010.mac
$Module:       Ценные бумаги
$Description:  Шаг настройки операции
*/
/* Используется для операций:
     3143 - Покупка ц/б СЭБ
     3153 - Продажа ц/б СЭБ
*/
IMPORT InsCarryDoc, "sp_class.mac", "oprmassexec.mac", "sp_car2.mac", "SPQICheckOper.mac";

PRIVATE MACRO __ExecuteStep( FD:SPFirstDoc ):INTEGER
  var err = 0;

  if( FD != NULL ) // единичное исполнение
     DefineOprDate( FD.GetKindDate(DATE_DEALDATE),        FD.DateArray[DATE_DEALDATE]         );
     DefineOprDate( FD.GetKindDate(DATE_DEALEXEC),        FD.DateArray[DATE_DEALSETAVOIRISS]  );
     DefineOprDate( FD.GetKindDate(DATE_DEALSETAVOIRISS), FD.DateArray[DATE_DEALSETAVOIRISS]  );
     DefineOprDate( FD.GetKindDate(DATE_DEALPAY),         FD.DateArray[DATE_DEALPAY]          );
     DefineOprDate( FD.GetKindDate(DATE_DEALBEGINEXEC),   FD.DateArray[DATE_DEALBEGINEXEC]    );

  else // массовое исполнение
    VAR OperDate = SP_MassOperDate(DL_SECUROWN);

    OperDate.Insert( DATE_DEALDATE,        "t_DealDate" );
    OperDate.Insert( DATE_DEALEXEC,        "t_DealSetAvoiriss" );
    OperDate.Insert( DATE_DEALSETAVOIRISS, "t_DealSetAvoiriss" );
    OperDate.Insert( DATE_DEALPAY,         "t_DealPay" );
    OperDate.Insert( DATE_DEALBEGINEXEC,   "t_DealBeginExec" );

    err = OperDate.Execute( "Шаг настройки операции. Установка планируемых дат операций." );
    if(err)
      return err;
    end;
  end; 

  if( УстановитьНачальныйСтатусСделки( FD ) )
     return 1;
  end;

  return 0;
END;

MACRO executeParamStep( kind_oper, BOf_kind, FDoc, ID_Operation, ID_Step )
  record  deal(dl_tick);
  var     FD;

  SetBuff( deal, FDoc ); 
  FD = SPFirstDoc( deal, false, true );

  return __ExecuteStep( FD );
END;

/* Массовое исполнение БИРЖЕВЫХ сделок с одной частью. В дистрибутиве это операция
  2143 - Покупка ц/б биржевая
*/
MACRO MassExecuteStep()
  return __ExecuteStep( NULL );
END;
