/*
$Name:        sp_carbacc.mac
$Module:      Ценные бумаги
$Description: Функции для проводок покупки ценных бумаг
*/
IMPORT "sp_catac.mac", "sp_caracc.mac";

PRIVATE MACRO UserGetBppCOst(Parentid)
    var Select, DataSet, Query;
    Query = "select sum(t_cost) - (sum(t_begbonus) - sum(t_bonus) )scost from dpmwrtsum_dbt where t_parent = ? and t_state = 1 ";
    Select = DL_RSDCommand(Query);
    Select.AddParam(Parentid);
    DataSet = Select.Execute(Query);

    if(DataSet.MoveNext())
       return  DataSet.scost;
    end;

   return 0;
End;

MACRO БУ_УчетБалансовойСтоимостиБумагПриПокупке( FD, Dп, _chapter )
  
  var AnotherSum = $0, NKD_PayFIID = $0, Bonus0 = $0, Bonus0_PayFIID = $0,
      dS = $0, СуммаУчетаВБалансе_ВР = $0, СуммаСделкиНаДатуУчета_ВЦ = $0, СуммаСделкиНаДатуПоставки_ВР = $0, 
      CatDebet, CatForvard, CatNKD, DebetFIID = NULL, SummaDebet = NULL,
      FIRoleDeb = NULL, FIRoleCred = NULL, FIRoleNKD = NULL,
      DelimNKD = $0, DelimNKD_PayFIID = $0, DelimNKD_CFIFIID = $0,
      PayFIID = FD.GetPayFIID(), AnotherFIID, 
      CredFIID = PayFIID,
      Dу = FD.DateArray[DATE_DEALBEGINEXEC],  /* дата учета */
      DVSSCost = $0, DVSSCost_PayFIID = $0, CFIPayFIID = false, CFIFaceFIID = false;
  var chapter:integer = 1;
  var BaseSum = $0;
  var FiIsBond = FI_IsBond(FD.fininstr);

  Var Ground = "";
  PRIVATE VAR fininstr = TRecHandler( "fininstr" );
  if( _chapter != null )
     chapter = _chapter;
  end;

   ПолучитьФинИн( FD.tick.rec.PFI, fininstr );

  /*У паев все проще, т.к. нет валюты номинала (всегда RUR) и нет просрочек*/
  if( FD.Kind == DL_INVESTSHARE ) /*Паи*/
     CatForvard = "+Расчеты";
     if( FD.ТипПортфеля() == KINDPORT_CONTR )
        CatDebet = "Наш портфель ПКУ, ц/б";
     else
        CatDebet   = "Наш портфель ц/б";
     end;

     FIRoleDeb = GetFIRoleByPortfolio(FD.pmwrtsum.rec.GroupID);

     /*Проводка должна быть на стоимость ц/б в НацВ по курсу на Dп из формы ввода операции.*/
     DebetFIID    =  NATCUR;
     AnotherSum   =  NULL;
     AnotherFIID  =  NULL;

     if( SmartConvertSum( SummaDebet, FD.dl_leg.rec.TotalCost, Dп, FD.dl_leg.rec.CFI, DebetFIID, true ) != true )
        return 1;
     end;    

  else

     if( FD.Kind != DL_TRUSTDOC )
        if( FD.ТипПортфеля() == KINDPORT_CONTR )
           CatDebet = "Наш портфель ПКУ, ц/б";
        else
           CatDebet   = "Наш портфель ц/б";
        end;

        FIRoleDeb = GetFIRoleByPortfolio(FD.pmwrtsum.rec.GroupID);

        if(ТОБылоПросрочено(FD.GetRQ(DLRQ_TYPE_DELIVERY) ) ) /*ТО не снято с просрочки*/
           CatForvard = IIF(IsBasket(FD.Group), "Треб. с н.с., корзина", "Треб. с н.с.");
        else
           CatForvard = "+Форвард, расчеты";
        end; 

        DebetFIID = null;                 
        SummaDebet = null;
        AnotherSum = null;
        AnotherFIID  = null;

     /*ветка для сделок с ц/б ДУ*/
     else

        CatNKD    = "-НКД ДУ";
        FIRoleNKD = FIROLE_NKD;

        CatDebet  = "Портфель ДУ";
        FIRoleDeb = FIROLE_BA; 

        if( FD.ВедетсяБалансУчетПоСделке() )
            CatForvard  =  "+Расчеты, ДУ";
            FIRoleCred  =  FIROLE_FIREQ;
            CredFIID    =  FD.FaceFIID;
        else
            CatForvard  =  "-Расчеты, ДУ";
            FIRoleCred  =  FIROLE_CA;
            CredFIID    =  PayFIID;
        end;
     end;

     if( FD.dl_leg.rec.CFI == PayFIID )
        CFIPayFIID = true; //Ct
     end;

     if( (not CFIPayFIID) and (FD.dl_leg.rec.CFI == FD.FaceFIID) )
        CFIFaceFIID = true; //Dt
     end;

     if( FD.ExistRqMoney == true )

        BaseSum = FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.Amount;
        if(FD.ExistAvance)
          BaseSum = BaseSum + FD.GetRQ(DLRQ_TYPE_AVANCE).rec.Amount;
        elif(FD.ExistDeposit)
          BaseSum = BaseSum + FD.GetRQ(DLRQ_TYPE_DEPOSIT).rec.Amount;
        end;

        /*отконвертить сумму базовых сумм платежей аванса/задатка и контрактива из ВЦ в ВР по курсу даты учета*/
        if( SmartConvertSum( СуммаУчетаВБалансе_ВР, BaseSum, Dу, FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.FIID, PayFIID, true ) != true )
           return 1;
        end;    

        if( CFIFaceFIID )
           SummaDebet = BaseSum;
        end;

        if((FiIsBond == false) and (FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.FIID != FD.GetAccFIID(CatDebet)))
          if( SmartConvertSum(SummaDebet, BaseSum, Dу, FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.FIID, FD.GetAccFIID(CatDebet), true ) != true )
            return 1;
          end;
        end;

        /*  Получаем сумму сделки на дату учета (сумма которая ставится на баланс).      */
        if( ПолучитьЦеновыеУсловияСделки( FD.tick, Dу-1, FD.IsBack, null, null, null, СуммаСделкиНаДатуУчета_ВЦ ) == false )
           return 1;
        end; 
        if( СуммаСделкиНаДатуУчета_ВЦ != FD.dl_leg.rec.TotalCost )

           /*был пересчет параметров сделки при изменении сроков уже после постановки сделки на баланс*/
           if( SmartConvertSum( СуммаСделкиНаДатуПоставки_ВР, FD.dl_leg.rec.TotalCost, Dп, FD.dl_leg.rec.CFI, PayFIID, true ) != true )
              return 1;
           end;    

           dS = СуммаУчетаВБалансе_ВР - СуммаСделкиНаДатуПоставки_ВР;
           СуммаУчетаВБалансе_ВР = СуммаСделкиНаДатуПоставки_ВР;

           if( CFIFaceFIID )
              SummaDebet = FD.dl_leg.rec.TotalCost;
           end;

           if((FiIsBond == false) and (FD.dl_leg.rec.CFI != FD.GetAccFIID(CatDebet)))
             if( SmartConvertSum(SummaDebet, FD.dl_leg.rec.TotalCost, Dу, FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.FIID, FD.GetAccFIID(CatDebet), true ) != true )
               return 1;
             end;
           end;

           if( dS > 0 )
              if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                   "-Маржа, ц/б", CatForvard,   /* Деб , КатегКредит*/
                                                   Dп,                    /* Дата */
                                                   chapter,               /* Глава */
                                                   null,                  /* Валюта */
                                                   null,                  /* Сумма дебет*/
                                                   INPCARRY,              /* Result_Carry */
                                                   " 1",                  /* Kind_Oper */
                                                   FD.tick.rec.DealCode,  /* Numb_Document */
                                                   "Учет расходов от изменения сроков поставки после постановки сделки на баланс",           /* Ground */
                                                   null, 
                                                   null, null,
                                                   NATCUR, PayFIID,
                                                   PayFIID, ABS(dS)
                                                 )
                )
                  return 1;
              end;
           elif( dS < 0 )
              if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                   CatForvard, "+Маржа, ц/б",  /* Деб , КатегКредит*/
                                                   Dп,                    /* Дата */
                                                   chapter,                  /* Глава */
                                                   PayFIID,                  /* Валюта */
                                                   ABS(dS),                  /* Сумма дебет*/
                                                   INPCARRY,              /* Result_Carry */
                                                   " 1",                  /* Kind_Oper */
                                                   FD.tick.rec.DealCode,  /* Numb_Document */
                                                   "Учет доходов от изменения сроков поставки после постановки сделки на баланс",           /* Ground */
                                                   null,
                                                   null, null,
                                                   PayFIID,NATCUR 
                                                 )
                )
                  return 1;
              end;
           end;
        end;
     else
        if( SmartConvertSum( СуммаУчетаВБалансе_ВР, FD.dl_leg.rec.TotalCost, Dп, FD.dl_leg.rec.CFI, PayFIID, true ) != true )
           return 1;
        end;    

        if( CFIFaceFIID )
           SummaDebet = FD.dl_leg.rec.TotalCost;
        end;    
     end;

  end; /*FD.tick.rec.BofficeKind == DL_INVESTSHARE*/

  if ((not IsREPO(FD.Group)) and (FD.Kind != DL_TRUSTDOC))

     Bonus0 = SP_GetBonusSum( FD );
     if( not CFIFaceFIID )
        if( SmartConvertSum( Bonus0_PayFIID, Bonus0, Dп, FD.FaceFIID, PayFIID, true ) != true )
           return 1;
        end;    
     end;    

     if( (FD.dl_leg.rec.NKD > 0.) AND ОтдельныйУчетУплНКД() )
        DelimNKD = FD.dl_leg.rec.NKD;
        if( not CFIFaceFIID  )
           if( SmartConvertSum(DelimNKD_PayFIID, DelimNKD, Dп, FD.NKDFIID(), PayFIID, true) != true )
              return 1;
           end;
        else
           if( SmartConvertSum(DelimNKD_CFIFIID, DelimNKD, Dп, FD.NKDFIID(), FD.dl_leg.rec.CFI, true) != true )
              return 1;
           end;
        end;
     end;

     if( FD.tick.rec.IsPFI )
        DVSSCost = money(FD.GetDVSSCostOnDate(Dп));

     /*DVSSCost всегда в рублях*/
        if((FiIsBond == false) and (FD.dl_leg.rec.CFI != FD.GetAccFIID(CatDebet)))
          if( SmartConvertSum(DVSSCost, DVSSCost, Dп, NATCUR, FD.GetAccFIID(CatDebet), true) != true )
             return 1;
          end;
        elif( CFIFaceFIID )
       if( SmartConvertSum(DVSSCost, DVSSCost, Dп, NATCUR, FD.FaceFIID, true) != true )
          return 1;
       end;
     else
       if( SmartConvertSum(DVSSCost, DVSSCost, Dп, NATCUR, PayFIID, true) != true )
          return 1;
       end;
     end;
     end;

     if( FD.Kind != DL_INVESTSHARE )
        if((FiIsBond == false) and (FD.dl_leg.rec.CFI != FD.GetAccFIID(CatDebet)))
           SummaDebet = SummaDebet + DVSSCost;
           DebetFIID  = FD.GetAccFIID(CatDebet);
        elif( CFIFaceFIID )
           SummaDebet = SummaDebet - Bonus0 - DelimNKD_CFIFIID + DVSSCost;
           DebetFIID = FD.FaceFIID;
        else
           AnotherSum = СуммаУчетаВБалансе_ВР - Bonus0_PayFIID - DelimNKD_PayFIID + DVSSCost;
           AnotherFIID  = PayFIID;            
        end;
     end;
  end;

  if( CatDebet == "Наш портфель ПКУ, ц/б" )
     if( SummaDebet != NULL )
        if( SmartConvertSum(SummaDebet, SummaDebet, Dп, DebetFIID, NATCUR, true) != true )
           return 1;
        end;
     end;
     DebetFIID = NATCUR;
  end;

  if( CatDebet == "Наш портфель ц/б" )
     if( SummaDebet != NULL )
        if( SmartConvertSum(SummaDebet, SummaDebet, Dп, DebetFIID, FD.GetAccFIID(CatDebet), true) != true )
           return 1;
        end;
     end;
     DebetFIID = FD.GetAccFIID(CatDebet);
  end;

  
  Ground = "Зачисление на счет вложений ценной бумаги"  + GetFinName(fininstr.rec) + " при покупке по сделке " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate; 
  if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                       CatDebet, CatForvard,           /* Деб , КатегКредит*/
                                       Dп,                             /* Дата */
                                       chapter,                        /* Глава */
                                       DebetFIID,                      /* Валюта */
                                       SummaDebet,                     /* Сумма дебет*/
                                       INPCARRY,                       /* Result_Carry */
                                       " 1",                           /* Kind_Oper */
                                       FD.tick.rec.DealCode,           /* Numb_Document */
                                       Ground/*"Учет в балансе купленных ц/б"*/, /* Ground */
                                       null,
                                       FIRoleDeb, FIRoleCred,
                                       DebetFIID, CredFIID,
                                       AnotherFIID, AnotherSum
                                     )
    )
     return 1;
  end;

  if ((DelimNKD > 0.) AND ОтдельныйУчетУплНКД() and (not IsREPO(FD.Group)) and (FD.Kind != DL_TRUSTDOC))

     FIRoleDeb = GetFIRoleByPortfolio( FD.pmwrtsum.rec.GroupID);

     Ground = "Зачисление на счет УНКД ценной бумаги " + GetFinName(fininstr.rec) + " при покупке по сделке " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate;

     if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                          "Уплаченный НКД", CatForvard, /* Деб , КатегКредит*/
                                          Dп,                           /* Дата */
                                          chapter,                      /* Глава */
                                          FD.NKDFIID(),                 /* Валюта */
                                          DelimNKD,                     /* Сумма дебет*/
                                          INPCARRY,                     /* Result_Carry */
                                          " 1",                         /* Kind_Oper */
                                          FD.tick.rec.DealCode,         /* Numb_Document */
                                          Ground/*"Учет суммы НКД"*/,             /* Ground */
                                          null, 
                                          FIRoleDeb, FIRoleCred,
                                          FD.FaceFIID, CredFIID
                                        )
       )
         return 1;
     end;
  end;

  if ( (Bonus0 > 0.) and (not IsREPO(FD.Group)) and (FD.Kind != DL_TRUSTDOC))

     FIRoleDeb = GetFIRoleByPortfolioBonus(FD.pmwrtsum.rec.GroupID);
     Ground = "Зачисление премии на счет учета премии по ценной бумаге " + GetFinName(fininstr.rec) + " при покупке по сделке " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate;

     if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                          "Премия, ц/б", CatForvard, /* Деб , КатегКредит*/
                                          Dп,                        /* Дата */
                                          chapter,                   /* Глава */
                                          FD.FaceFIID,               /* Валюта */
                                          Bonus0,                    /* Сумма дебет*/
                                          INPCARRY,                  /* Result_Carry */
                                          " 1",                      /* Kind_Oper */
                                          FD.tick.rec.DealCode,      /* Numb_Document */
                                          Ground/*"Учет суммы премии"*/,       /* Ground */
                                          null, 
                                          FIRoleDeb, FIRoleCred,
                                          FD.FaceFIID, CredFIID
                                        )
       )
         return 1;
     end;
  end;

  return 0; 
END;

/* Делаем проводки по оплате ц/б (без просрочки) при покупке.
   Платеж по контрактиву должен быть актуализирован, счет контрагента заполнен.
   Возвращаем false в случае ошибки.
      FD          -  SPFirstDoc по сделке
      ChangeDate  -  дата изменения
      */
macro БУ_СделатьПроводкиПоОплате_БезПросрочки_ПриПокупке( FD, ChangeDate )

   var chapter:integer = 1, Bonus0 = $0, NKD = $0;
   var PayerAccountBuff = TRecHandler( "account" );
   var ReceiverAccountBuff = TRecHandler( "account" );
   var PayFIID_Bonus0 = $0, PayFIID_NKD = $0, PayAmount = $0;

   /*
   if (ОтдельныйУчетУплНКД() and 
       (not IsREPO(FD.Group)) and 
       (FD.Kind != DL_TRUSTDOC) and
       (not IsClientDeal(FD.tick.rec)) and /* Отсюда и ниже - условия, при которых в платеже по к/а счет "Наш портфель ц/б" из MACRO ЗаполнитьНашСчетВПлатежеПоКонтрактиву( FD, dat ) */
       (FD.BuySale == DEAL_TYPE_BUY) and
       (not FD.ВедетсяБалансУчетПоСделке()) and
       (not FD.ExistBack) and
       (not FD.DealAsResultDVExe)
      )

      var PayerCateg:string;

      if(ПолучитьНашСчетТОПоОплате( FD.GetRQ(DLRQ_TYPE_PAYMENT), FD, ChangeDate, PayerAccountBuff, ReceiverAccountBuff, @PayerCateg ) != 0)
        return 1;
      end;

      if(ПолучитьСчетКонтрагентаПоТООплаты( FD.GetRQ(DLRQ_TYPE_PAYMENT), FD, ChangeDate, PayerAccountBuff, ReceiverAccountBuff ) != 0)
        return 1;
      end;

      Bonus0 = SP_GetBonusSum( FD );

      var FaceFIIDRqAmount = $0;
      var ВалютаСуммы:integer = FD.ВалютаНоминалаПКУ(PayerCateg);

      SmartConvertSum(FaceFIIDRqAmount, FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.Amount, FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.PlanDate, FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.FIID, ВалютаСуммы, false);

      SmartConvertSum(PayAmount, FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.Amount, FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.PlanDate, FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.FIID, FD.GetPayFIID(), false);

      SmartConvertSum(PayFIID_Bonus0, Bonus0, FD.GetRQ(DLRQ_TYPE_DELIVERY).rec.PlanDate, FD.FaceFIID(), FD.GetPayFIID(), false);/*ВР*/

      if( (FD.dl_leg.rec.NKD > 0.) AND ОтдельныйУчетУплНКД() )
         NKD = FD.dl_leg.rec.NKD;
         SmartConvertSum(PayFIID_NKD, NKD, FD.GetRQ(DLRQ_TYPE_DELIVERY).rec.PlanDate, FD.NKDFIID(), FD.GetPayFIID(), false);/*ВР*/
      end;

      /*в проводке по ДТ будет "Наш портфель"*/
      if(not БУ_ПроводкаПоКатегориямУчета( FD,
                                           PayerAccountBuff, ReceiverAccountBuff,/* КатегДеб , КатегКредит*/
                                           ChangeDate,           /* Дата */
                                           1,                    /* Глава */
                                           FD.GetPayFIID(),      /* Валюта */
                                           PayAmount - PayFIID_Bonus0 - PayFIID_NKD, /* Сумма в ВН*/
                                           INPCARRY,             /* Result_Carry */
                                           " 1",                 /* Kind_Oper */
                                           "",                   /* Numb_Document */
                                           "Сумма ТО по оплате", 0,null,null,
                                           ВалютаСуммы, FD.GetPayFIID(),    /* валюты счетов: Дт - Кт */
                                           ВалютаСуммы, FaceFIIDRqAmount - Bonus0 - NKD
                                         )
        )
         return 1;
      end;

      /*учет НКД на отдельном счете*/
      if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                           "Уплаченный НКД", ReceiverAccountBuff,/* КатегДеб , КатегКредит*/
                                           ChangeDate,          /* Дата */
                                           1,                   /* Глава */
                                           FD.FaceFIID(),       /* Валюта */
                                           NKD,                 /* Сумма  */
                                           INPCARRY,             /* Result_Carry */
                                           " 1",                 /* Kind_Oper */
                                           "",                   /* Numb_Document */
                                           "Сумма НКД", null,
                                           GetFIRoleByPortfolio( FD.pmwrtsum.rec.GroupID),null,
                                           FD.FaceFIID(), FD.GetPayFIID()    /* валюты счетов: Дт - Кт */ 
                                         )
        )
         return 1;
      end;

      if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                           "Премия, ц/б", ReceiverAccountBuff,/* КатегДеб , КатегКредит*/
                                           ChangeDate,          /* Дата */
                                           1,                   /* Глава */
                                           FD.FaceFIID(),       /* Валюта */
                                           Bonus0,               /* Сумма  */
                                           INPCARRY,             /* Result_Carry */
                                           " 1",                 /* Kind_Oper */
                                           "",                   /* Numb_Document */
                                           "Сумма премии", null,
                                           GetFIRoleByPortfolioBonus(FD.pmwrtsum.rec.GroupID), null,
                                           FD.FaceFIID(), FD.GetPayFIID()    /* валюты счетов: Дт - Кт */ 
                                          )
        )
         return 1;
      end;

   else*/
      /* Делаем одну проводку. */
      if( БУ_ОбработатьТОПоОплате( FD, ChangeDate ) != 0 )
         return 1;
      end;
   //end;

   return 0;
end;

private macro GetGrdealPlanDate(DocKind, DocID, Templum)
  var query, cmd, DataSet;
  var PlanDate = date(0,0,0);

  query =   " select t_PlanDate "
          + "   from ddlgrdeal_dbt "
          + "  where t_DocKind = ? "
          + "    and t_DocID = ? "
          + "    and t_TemplNum = ? ";
  cmd = DL_RSDCommand(query);
  cmd.AddParam(DocKind);
  cmd.AddParam(DocID);
  cmd.AddParam(Templum);

  DataSet = cmd.Execute();
  if(DataSet.moveNext())
    PlanDate = date(DataSet.PlanDate);
  end;

  return PlanDate;
end;

private macro ПолучитьСуммыКомпПоставок( dataSet, SummTP:@money, SummPPR:@money, SummPUDP:@money, SummOD:@money, SummPKU:@money, BonusTP:@money, BonusPPR:@money, BonusPUDP:@money, NKDTP:@money, NKDPPR:@money, NKDPUDP:@money, NKDOD:@money, SumBackKSU:@money,
                                         NotWrtBonusTP:@money, NotWrtBonusPPR:@money, NotWrtBonusPUDP:@money
                                       )
  while( dataSet.moveNext() )
     if( dataSet.Kind == DLSUM_KIND_COMPDEL_SUMTP )
        SummTP = SummTP + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_NKDTP )
        if( ОтдельныйУчетУплНКД() )
           NKDTP = NKDTP + dataSet.Sum;
        end;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_BONUSTP )
        BonusTP = BonusTP + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_SUM_NOTCARRY_BONUS_TRADE )
        NotWrtBonusTP = NotWrtBonusTP + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_SUMPPR )
        SummPPR = SummPPR + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_NKDPPR )
        if( ОтдельныйУчетУплНКД() )
           NKDPPR = NKDPPR + dataSet.Sum;
        end;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_BONUSPPR )
        BonusPPR = BonusPPR + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_SUM_NOTCARRY_BONUS_SALE )
        NotWrtBonusPPR = NotWrtBonusPPR + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_SUMPUDP )
        SummPUDP = SummPUDP + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_NKDPUDP )
        if( ОтдельныйУчетУплНКД() )
           NKDPUDP = NKDPUDP + dataSet.Sum;
        end;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_BONUSPUDP )
        BonusPUDP = BonusPUDP + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_SUM_NOTCARRY_BONUS_RETIRE )
        NotWrtBonusPUDP = NotWrtBonusPUDP + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_SUMOD )
        SummOD = SummOD + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_NKDOD )
        if( ОтдельныйУчетУплНКД() )
           NKDOD = NKDOD + dataSet.Sum;
        end;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_SUMPKU )
        SummPKU = SummPKU + dataSet.Sum;
     elif( dataSet.Kind == DLSUM_KIND_COMPDEL_SUMBACKKSU)
       SumBackKSU = SumBackKSU + dataSet.Sum;
     end;
  end;

  SummTP = SummTP - BonusTP;
  SummPPR = SummPPR - BonusPPR;
  SummPUDP = SummPUDP - BonusPUDP;

  if( ОтдельныйУчетУплНКД() )
     SummTP = SummTP - NKDTP;
     SummPPR = SummPPR - NKDPPR;
     SummPUDP = SummPUDP - NKDPUDP;
  end;
end;

//Определить сумму вложения по лоту, вернувшегося из БПП в портфель
private macro GetWrtSumByLot(SumID:integer, dat:date, Method):money
  var query, cmd, DataSet;
  var Summ = $0;
  
  //смотрим историю лота, чтобы получить значения в момент возврата лота из БПП в портфель
  //на самом лоте могут быть не актуальные суммы, т.к. он может быть списан, в том числе и частично, 
  //на него при средневзвесе могут быть распределены суммы с других лотов

  query =   " select v.t_Cost, v.t_Bonus, v.t_BegBonus, v.t_CostPFI, v.t_NKDAmount "
          + "   from dpmwrtsum_dbt lot, v_scwrthistex v, v_scwrthistex v1 "
          + "  where lot.t_SumID = ? "
          + "    and lot.t_Kind = " + PM_WRTSUM_KIND_RRWAB2
          + "    and v.t_SumID = lot.t_SumID "
          + "    and v.t_ChangeDate = ? "
          + "    and v.t_State = " + PM_WRTSUM_FORM
          + "    and v.t_ID_Operation = ? "
          + "    and v.t_ID_Step = - 1 " 
          + "    and v.t_Action <> " + PM_WRTSUM_UPDTMODE_CDELIVERY
          + "    and v1.t_SumID = v.t_SumID "
          + "    and v1.t_Instance = v.t_Instance - 1 "
          + "    and v1.t_State = " + PM_WRTSUM_SALE_BPP;

  cmd = DL_RSDCommand(query);
  cmd.AddParam(SumID);
  cmd.AddParam(dat);
  cmd.AddParam(ПроводкиБУ.GetServDocID());

  DataSet = cmd.Execute();
  if(DataSet.moveNext())
    Summ = Summ + DataSet.Cost + DataSet.Bonus - DataSet.BegBonus + DataSet.CostPFI;
    if(ОтдельныйУчетУплНКД() == false)
      Summ = Summ + DataSet.NKDAmount;
    end;
  end;

  return Summ;
end;

private macro GetSaleREPOCostBuyNat(SaleSumID:integer)
  var query, cmd, DataSet;
  var SumCostBuyNat = $0;

  query =   " select NVL(SUM(lnk.t_CostBuyNat),0) as SumCostBuyNat "
          + "   from dpmwrtlnk_dbt lnk "
          + "  where lnk.t_SaleID = ? ";  

  cmd = DL_RSDCommand(query);

  cmd.AddParam(SaleSumID);

  DataSet = cmd.Execute();

  if(DataSet.moveNext())
    SumCostBuyNat = money(DataSet.SumCostBuyNat);
  end;

  return SumCostBuyNat;
end;

macro БУ_УчетСебестоимостиВРЕПО( FD, dat:date, IsCompensWrt:bool, GrDealID:integer ):integer
  var Portfolio, IsOverdue = false, CatOD;
  var Summ = $0, SummTO = $0, TO_FIID, Dp;
  var SummTP = $0, SummPPR = $0, SummPUDP = $0, SummOD = $0, SummPKU = $0, SumBackKSU = $0;
  var NKD_PVO = $0, Bonus_PVO = $0;
  var BonusTP = $0, BonusPPR = $0, BonusPUDP = $0;
  var NotWrtBonusTP = $0, NotWrtBonusPPR = $0, NotWrtBonusPUDP = $0;
  var NKDTP = $0, NKDPPR = $0, NKDPUDP = $0, NKDOD = $0;
  var RSD, SQLQuery, cmd, cmd_inc;
  var ForRestAcc = 0;
  var CatBpp = "", CatNKDBpp = "";
  var Ground = "";
  var i = 0;
  var FDMGR;
  PRIVATE VAR fininstr = TRecHandler( "fininstr" );

  private record CredAcc( account );

  /*только для собственных сделок*/ 
  if( IsClientDeal(FD.tick.rec) ) 
     return 0;
  end;
  if( IsCompensWrt )
     var DlRq = TRecHandler("dlrq.dbt");
     if( ПолучитьТОПоСтрокеГрафика(GrDealID, DLRQ_TYPE_COMPDELIVERY, DlRq) != 0 )
        return 1;
     end;

     cmd = DL_RSDCommand(" select t_Kind, t_Sum " +
                         "   from ddlsum_dbt  " +
                         "  Where t_DocKind  = ? " +
                         "    and t_DocID    = ? " +
                         "    and t_Date     = ? " + 
                         "    and t_Currency = ? " +
                         "    and t_FIID     = ? " );

     cmd.AddParam(29/*DLDOC_PAYMENT*/);
     cmd.AddParam(DlRq.rec.ID);
     cmd.AddParam(dat);
     cmd.AddParam(FD.fininstr.rec.FaceValueFI);
     cmd.AddParam(FD.CurPFI());

     ПолучитьСуммыКомпПоставок(cmd.Execute(), @SummTP, @SummPPR, @SummPUDP, @SummOD, @SummPKU, @BonusTP, @BonusPPR, @BonusPUDP, @NKDTP, @NKDPPR, @NKDPUDP, @NKDOD, @SumBackKSU, @NotWrtBonusTP, @NotWrtBonusPPR, @NotWrtBonusPUDP);

     ПроводкиБУ.ДобавитьCуммыПоПортфелюПоСделке(FD.tick.rec.DealID, -SummTP, -SummPPR, -SummPUDP, -SummPKU);
  else
     ПроводкиБУ.ПолучитьCуммыПоПортфелюПоСделке(FD.tick.rec.DealID, @SummTP, @SummPPR, @SummPUDP, @SummPKU);
  end;

  if( IsBUY(FD.Group) ) /*Если Обратное РЕПО*/
     if(IsLOAN(FD.Group))
       Dp = FD.GetRQ(DLRQ_TYPE_DELIVERY).rec.PlanDate;
     else
       Dp = FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.PlanDate;
     end;
     
     if( IsBasket(FD.Group) )
       SummTO   = FD.Cost(dat);
       TO_FIID  = NATCUR; /*стоимость обеспечения задается в рублях*/
       if( SmartConvertSum( Summ, SummTO, dat, TO_FIID, FD.FaceFIID(), true ) != true )
          return 1;
       end;    
       Summ = Summ + FD.NKD(dat);
     else
       if( (Dp <= dat) and (not IsLOAN(FD.Group)) )
          if( FD.ExistAvance() )
             SummTO = FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.Amount + FD.GetRQ(DLRQ_TYPE_AVANCE).rec.Amount;
          else
             SummTO = FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.Amount;
          end;
          TO_FIID = FD.GetRQ(DLRQ_TYPE_PAYMENT).rec.FIID;
       else
          SummTO  = FD.dl_leg.rec.TotalCost;
          TO_FIID = FD.dl_leg.rec.CFI;
       end;

       if( SmartConvertSum( Summ, SummTO, dat, TO_FIID, FD.FaceFIID(), true ) != true )
          return 1;
       end;    
     end;

     ПолучитьФинИн( FD.tick.rec.PFI, fininstr );
     Ground = "ЦБ " + GetFinName(fininstr.rec) + ", полученные по операциям, совершаемым на возвратной основе,  РЕПО № " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate + ", контр. " + UserGetPartyShortName(FD.tick.rec.partyid) + ", кол-во бумаг " + UserGetKol(FD.dl_leg.rec.principal, fininstr.rec.avoirkind);
//'ЦБ Татнфт 3ао, полученные по операциям, совершаемым на возвратной основе,  РЕПО № 2850025191 от 02/07/2018, контр. НКО НКЦ (АО), кол-во бумаг 900
     if( not БУ_ПроводкаПоКатегориямУчета( FD, 
                                           "ВнебалСчетКорресп", IIF(IsBasket(FD.Group), "Ц/б, Корзина ПВО", "Ц/б, ПВО"),  /* Деб , КатегКредит*/
                                           dat,                              /* Дата */
                                           3,                                /* Глава */
                                           FD.FaceFIID(),                    /* Валюта */
                                           Summ,                             /* Сумма дебет*/
                                           INPCARRY,                         /* Result_Carry */
                                           " 1",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,             /* Numb_Document */
                                           Ground/*"Учет стоимости ц/б"*/,             /* Ground */
                                           null, 
                                           null, null,
                                           NATCUR, FD.FaceFIID()
                                         )
       )
         return 1;
     end;
  else
     /*Если Прямое РЕПО*/
     var Delivery1PlanDate = GetGrdealPlanDate(FD.tick.rec.BOfficeKind, FD.tick.rec.DealID, DLGR_TEMPL_DELIVERY);
     var Delivery2PlanDate = GetGrdealPlanDate(FD.tick.rec.BOfficeKind, FD.tick.rec.DealID, DLGR_TEMPL_DELIVERY2);
     var CoupPlanDate      = GetGrdealPlanDate(FD.tick.rec.BOfficeKind, FD.tick.rec.DealID, DLGR_TEMPL_COUP);
     var PartRepPlanDate   = GetGrdealPlanDate(FD.tick.rec.BOfficeKind, FD.tick.rec.DealID, DLGR_TEMPL_PARTREP);
     var SumEquivalentCarry = null;
     var Method = FD.GetMethodWriteOff();

     var AcCurSec = УЧЕТ_ВАЛЮТНЫХ_ДОЛЕВЫХ_ЦБ(),
         IsBondFI = FI_IsBond(FD.fininstr),
         SumDeb, SumCred, CarFIID, CarFIID2;

     ForRestAcc = 0;
     if((Delivery1PlanDate == Delivery2PlanDate) OR 
        ((CoupPlanDate != date(0,0,0)) and (CoupPlanDate == Delivery2PlanDate)) OR
        ((PartRepPlanDate != date(0,0,0)) and (PartRepPlanDate == Delivery2PlanDate))
       )
       ForRestAcc = GETRESTACC_CREDIT;
     end;

     if( ExistNOSS( FD.avoiriss, dat ) )
        Portfolio = KINDPORT_TRADE;
     else
        Portfolio = KINDPORT_SALE;
     end;

     if( ТОБылоПросрочено(FD.GetRQ(DLRQ_TYPE_DELIVERY)) )
       IsOverdue = true;
     end;

     if(ВедениеСчетовБПППоВыпуску() == true)
       CatBpp    = "Наш портфель ц/б";
       CatNKDBpp = "Уплаченный НКД";
     else
       CatBpp    = IIF(IsBasket(FD.Group), "Ц/б, Корзина БПП", "Ц/б, БПП");
       CatNKDBpp = IIF(IsBasket(FD.Group), "Уплач. НКД, Корзина БПП", "Уплаченный НКД, БПП");
     end;

     if( FD.IsExistAccount(CatBpp, null, true, GetFIRoleByPortfolio(KINDPORT_TRADE, null, null, true, IsOverdue), CredAcc, null, dat) )
        Summ = $0;
        if( IsCompensWrt )
           Summ = SummTP;
        else
           if(ВедениеСчетовБПППоВыпуску() == true)
             ForRestAcc = null;

             i = 0;
             while( FD.pmwrtsum(i) != null )
               if( FD.pmwrtsum(i).rec.Portfolio==KINDPORT_TRADE )
                  Summ = Summ + GetWrtSumByLot(FD.pmwrtsum(i).rec.SumID, dat, Method);
               end; 
               i = i + 1;
             end;
           else
           if(ForRestAcc)
              Summ = $0;
           else
              Summ = Abs(GetRestAccount(CredAcc, dat)) + SummTP;
           end;
        end;
        end;

        SumEquivalentCarry = null;

        CarFIID = FD.GetAccFIID("Наш портфель ц/б");
        // *Если ц/б с идентификаторм T_FIID текущего лота 2ч НЕ является облигацией И её валюта номинала НЕ равна НацВ И <Учет валютных долевых ц/б> имеет значение 0 (т.е. в рублях),
        // то сумма для проводки <Учет стоимости ц/б> (Наш портфель (ВУ) - ЦБ_БПП (ВН)) определяется следующим образом:
        if( IsREPO(FD.Group) and IsSALE(FD.Group) and (AcCurSec == 0) and
            (IsBondFI == false) and (FD.FaceFIID() != NATCUR) )
           SumCred = Abs(Summ);
           CarFIID2 = FD.FaceFIID();

           SumDeb = GetSaleREPOCostBuyNat(FD.pmwrtsum.rec.Parent);

        // *Для остальных случаев для данной проводки остается имеющаяся реализация
        else
           SumDeb = Abs(Summ);
           SumCred = null;
           CarFIID2 = null;

           if((AcCurSec != 0) and (IsBondFI == false) and (FD.FaceFIID() != NATCUR))
             SumEquivalentCarry = GetSaleREPOCostBuyNat(FD.pmwrtsum.rec.Parent);
           end;

        end;
/*КД Тут надо писать подмену счетов по переходящим сделкам прямого репо*/

        if( (ForRestAcc) or (SumDeb != $0) ) 
           ground = "Перенос балансовой стоимости ЦБ " + GetFinName(FD.fininstr.rec) + " со счета вложений для проданных без прек. признания по второй части сделки прямого РЕПО № " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate + " на счет вложений";

           if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                  "Наш портфель ц/б", CredAcc,      /* Деб , КатегКредит*/
                  dat,                              /* Дата */
                  1,                                /* Глава */
                  CarFIID,                          /* Валюта */
                  SumDeb,                           /* Сумма дебет*/
                  INPCARRY,                         /* Result_Carry */
                  " 1",                             /* Kind_Oper */
                  FD.tick.rec.DealCode,             /* Numb_Document */
                  ground, /*"Учет стоимости ц/б в ССПУ_ЦБ",*/   /* Ground */
                  ForRestAcc, 
                  GetFIRoleByPortfolio( KINDPORT_TRADE ), 
                  GetFIRoleByPortfolio( KINDPORT_TRADE, null, null, true, IsOverdue),
                  CarFIID, CarFIID2,
                  CarFIID2,                         /* Валюта2 */
                  SumCred,                          /* Сумма2 */
                  null, null, null, null, null, null, null,
                  null, null, null, null,
                  SumEquivalentCarry
                 ))
               return 1;
           end;
        end;
     end;

     if( FD.IsExistAccount(CatBpp, null, true, GetFIRoleByPortfolio(KINDPORT_SALE, null, null, true, IsOverdue), CredAcc, null, dat) )
        Summ = $0;
        
        if( IsCompensWrt )
           Summ = SummPPR;
        else
           if(ВедениеСчетовБПППоВыпуску() == true)
             ForRestAcc = null;

             i = 0;
             while( FD.pmwrtsum(i) != null )
               if( FD.pmwrtsum(i).rec.Portfolio==KINDPORT_SALE )
                  Summ = Summ + GetWrtSumByLot(FD.pmwrtsum(i).rec.SumID, dat, Method);   
               end; 
               i = i + 1;
             end;
           else
           if(ForRestAcc)
              Summ = $0;
           else
                 Summ = Abs(GetRestAccount(CredAcc, dat)) + SummPPR;
              end;
           end;
        end;

        CarFIID = FD.GetAccFIID("Наш портфель ц/б");
        // *Если ц/б с идентификаторм T_FIID текущего лота 2ч НЕ является облигацией И её валюта номинала НЕ равна НацВ И <Учет валютных долевых ц/б> имеет значение 0 (т.е. в рублях),
        // то сумма для проводки <Учет стоимости ц/б> (Наш портфель (ВУ) - ЦБ_БПП (ВН)) определяется следующим образом:
        if( IsREPO(FD.Group) and IsSALE(FD.Group) and (AcCurSec == 0) and
            (IsBondFI == false) and (FD.FaceFIID() != NATCUR) )
           SumCred = Abs(Summ);
           CarFIID2 = FD.FaceFIID();

           SumDeb = GetSaleREPOCostBuyNat(FD.pmwrtsum.rec.Parent);

        // *Для остальных случаев для данной проводки остается имеющаяся реализация
        else
           SumDeb = Abs(Summ);
           SumCred = null;
           CarFIID2 = null;
           
           if((AcCurSec != 0) and (IsBondFI == false) and (FD.FaceFIID() != NATCUR))
             SumEquivalentCarry = GetSaleREPOCostBuyNat(FD.pmwrtsum.rec.Parent);
           end;
        end;
		
        if( (ForRestAcc) or (SumDeb != $0) ) 
           ground = "Перенос балансовой стоимости ЦБ " + GetFinName(FD.fininstr.rec) + " со счета вложений для проданных без прек. признания по второй части сделки прямого РЕПО № " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate + " на счет вложений";
           if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                  "Наш портфель ц/б", CredAcc,      /* Деб , КатегКредит*/
                  dat,                              /* Дата */
                  1,                                /* Глава */
                  CarFIID,                          /* Валюта */
                  SumDeb,                           /* Сумма дебет*/
                  INPCARRY,                         /* Result_Carry */
                  " 1",                             /* Kind_Oper */
                  FD.tick.rec.DealCode,             /* Numb_Document */
                  ground/*"Учет стоимости ц/б в СССД_ЦБ"*/,   /* Ground */
                  ForRestAcc, 
                  GetFIRoleByPortfolio( KINDPORT_SALE ), 
                  GetFIRoleByPortfolio( KINDPORT_SALE, null, null, true, IsOverdue),
                  CarFIID, CarFIID2,
                  CarFIID2,                         /* Валюта2 */
                  SumCred,                          /* Сумма2 */
                  null, null, null, null, null, null, null,
                  null, null, null, null,
                  SumEquivalentCarry
                 ))
               return 1;
           end;
        end;
     end;

     if( FD.IsExistAccount(CatBpp, null, true, GetFIRoleByPortfolio(KINDPORT_RETIRE, null, null, true, IsOverdue), CredAcc, null, dat) )
        Summ = $0;
        
        if( IsCompensWrt )
           Summ = SummPUDP;
        else
           if(ВедениеСчетовБПППоВыпуску() == true)
             ForRestAcc = null;

             i = 0;
             while( FD.pmwrtsum(i) != null )
               if( FD.pmwrtsum(i).rec.Portfolio==KINDPORT_RETIRE )
                  Summ = Summ + GetWrtSumByLot(FD.pmwrtsum(i).rec.SumID, dat, Method);
               end; 
               i = i + 1;
             end;
           else
           if(ForRestAcc)
              Summ = $0;
           else
              Summ = Abs(GetRestAccount(CredAcc, dat)) + SummPUDP;
           end;
        end;
        end;
        if( (ForRestAcc) or (Summ != $0) ) 
           if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                  "Наш портфель ц/б", CredAcc,      /* Деб , КатегКредит*/
                  dat,                              /* Дата */
                  1,                                /* Глава */
                  FD.GetAccFIID("Наш портфель ц/б"),/* Валюта */
                  Abs(Summ),                        /* Сумма дебет*/
                  INPCARRY,                         /* Result_Carry */
                  " 1",                             /* Kind_Oper */
                  FD.tick.rec.DealCode,             /* Numb_Document */
                  "Перенос балансовой стоимости ЦБ " + GetFinName(FD.fininstr.rec) + " со счета вложений для проданных без прек. признания по второй части сделки прямого РЕПО № " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate + " на счет вложений",     /* Ground */
                  ForRestAcc, 
                  GetFIRoleByPortfolio( KINDPORT_RETIRE ), 
                  GetFIRoleByPortfolio( KINDPORT_RETIRE, null, null, true, IsOverdue )
                 ))
               return 1;
           end;
        end;
     end;

     if(ВедениеСчетовБПППоВыпуску() == true)
       CatBpp = "Наш портфель ПКУ, ц/б";
     else
       CatBpp = IIF(IsBasket(FD.Group), "Ц/б, Корзина ПКУ БПП", "Ц/б, ПКУ БПП");
     end;

     if( FD.IsExistAccount(CatBpp, null, true, GetFIRoleByPortfolio(KINDPORT_CONTR, null, null, true, IsOverdue), CredAcc, null, dat) )
        Summ = $0;

        if( IsCompensWrt )
           Summ = SummPKU;
        else
           if(ВедениеСчетовБПППоВыпуску() == true)
             ForRestAcc = null;

             i = 0;
             while( FD.pmwrtsum(i) != null )
               if( FD.pmwrtsum(i).rec.Portfolio==KINDPORT_CONTR )
                  Summ = Summ + GetWrtSumByLot(FD.pmwrtsum(i).rec.SumID, dat, Method);
               end; 
               i = i + 1;
             end;
           else
           if(ForRestAcc)
              Summ = $0;
           else
              Summ = Abs(GetRestAccount(CredAcc, dat)) + SummPKU;
           end;
        end;
        end;
        if( (ForRestAcc) or (Summ != $0) )
           if( not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                 "Наш портфель ПКУ, ц/б", CredAcc, /* Деб , КатегКредит*/
                                                 dat,                              /* Дата */
                                                 1,                                /* Глава */
                                                 NATCUR,                           /* Валюта */
                                                 Abs(Summ),                        /* Сумма дебет*/
                                                 INPCARRY,                         /* Result_Carry */
                                                 " 1",                             /* Kind_Oper */
                                                 FD.tick.rec.DealCode,             /* Numb_Document */
                                                 "Учет стоимости ц/б в ПКУ",       /* Ground */
                                                 ForRestAcc,
                                                 GetFIRoleByPortfolio(KINDPORT_CONTR),
                                                 GetFIRoleByPortfolio(KINDPORT_CONTR, null, null, true, IsOverdue)
                                                )
             )
               return 1;
           end;
        end;
     end;

     if( IsCompensWrt )
        if( ОтдельныйУчетУплНКД() )
           if( FD.ActualAccount(CatNKDBpp, null, true, GetFIRoleByPortfolio(KINDPORT_TRADE, null, null, true, IsOverdue), CredAcc, dat) ) 
              Summ = NKDTP;

              if( Summ != $0 ) 
                 if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                        "Уплаченный НКД", CredAcc,           /* Деб , КатегКредит*/
                        dat,                              /* Дата */
                        1,                                /* Глава */
                        FD.FaceFIID,                      /* Валюта */
                        Abs(Summ),                        /* Сумма дебет*/
                        INPCARRY,                         /* Result_Carry */
                        " 1",                             /* Kind_Oper */
                        FD.tick.rec.DealCode,             /* Numb_Document */
                        "Учет НКД в ССПУ_ЦБ",               /* Ground */
                        null, 
                        GetFIRoleByPortfolio( KINDPORT_TRADE, null, null, null, IsOverdue), 
                        GetFIRoleByPortfolio( KINDPORT_TRADE, null, null, true, IsOverdue)
                       ))
                     return 1;
                 end;
              end;
           end;

           if( FD.ActualAccount(CatNKDBpp, null, true, GetFIRoleByPortfolio(KINDPORT_SALE, null, null, true, IsOverdue), CredAcc, dat) ) 
              Summ = NKDPPR;
              
              if( Summ != $0 ) 
                 if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                        "Уплаченный НКД", CredAcc,           /* Деб , КатегКредит*/
                        dat,                              /* Дата */
                        1,                                /* Глава */
                        FD.FaceFIID,                      /* Валюта */
                        Abs(Summ),                        /* Сумма дебет*/
                        INPCARRY,                         /* Result_Carry */
                        " 1",                             /* Kind_Oper */
                        FD.tick.rec.DealCode,             /* Numb_Document */
                        "Учет НКД в СССД_ЦБ",               /* Ground */
                        null, 
                        GetFIRoleByPortfolio( KINDPORT_SALE, null, null, null, IsOverdue ), 
                        GetFIRoleByPortfolio( KINDPORT_SALE, null, null, true, IsOverdue )
                       ))
                     return 1;
                 end;
              end;
           end;

           if( FD.ActualAccount(CatNKDBpp, null, true, GetFIRoleByPortfolio(KINDPORT_RETIRE, null, null, true, IsOverdue), CredAcc, dat) )
              Summ = NKDPUDP;

              if( Summ != $0 ) 
                 if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                        "Уплаченный НКД", CredAcc,           /* Деб , КатегКредит*/
                        dat,                              /* Дата */
                        1,                                /* Глава */
                        FD.FaceFIID,                      /* Валюта */
                        Abs(Summ),                        /* Сумма дебет*/
                        INPCARRY,                         /* Result_Carry */
                        " 1",                             /* Kind_Oper */
                        FD.tick.rec.DealCode,             /* Numb_Document */
                        "Учет НКД в АС_ЦБ",             /* Ground */
                        null, 
                        GetFIRoleByPortfolio( KINDPORT_RETIRE, null, null, null, IsOverdue ), 
                        GetFIRoleByPortfolio( KINDPORT_RETIRE, null, null, true, IsOverdue )
                       ))
                     return 1;
                 end;
              end;
           end;

        end;

        if( FD.ActualAccount( "Премия, ц/б", null, true, GetFIRoleByPortfolioBonus(KINDPORT_TRADE, true), CredAcc, dat ) ) 
           Summ = BonusTP;

           if( Summ != $0 ) 
              if( not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                    "Премия, ц/б", CredAcc,           /* Деб , КатегКредит*/
                                                    dat,                              /* Дата */
                                                    1,                                /* Глава */
                                                    FD.FaceFIID,                      /* Валюта */
                                                    Abs(Summ),                        /* Сумма дебет*/
                                                    INPCARRY,                         /* Result_Carry */
                                                    " 1",                             /* Kind_Oper */
                                                    FD.tick.rec.DealCode,             /* Numb_Document */
                                                    "Учет премии в ССПУ_ЦБ",               /* Ground */
                                                    null, 
                                                    GetFIRoleByPortfolioBonus(KINDPORT_TRADE), 
                                                    GetFIRoleByPortfolioBonus(KINDPORT_TRADE, true)
                                                  )
                 )
                  return 1;
              end;
           end;
        end;
 
        if( FD.ActualAccount( "Премия, ц/б", null, true, GetFIRoleByPortfolioBonus(KINDPORT_SALE, true), CredAcc, dat ) ) 
           Summ = BonusPPR;

           if( Summ != $0 ) 
           If(IsBasket(FD.Group))
               ground = "Перенос Премии по ЦБ " + GetFinName(FD.fininstr.rec) + " со счета премии для проданных без прек. признания по сделке РЕПО с корзиной № " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate + " на счет вложений";
           else
               ground = "Перенос Премии по ЦБ " + GetFinName(FD.fininstr.rec) + " со счета премии для проданных без прек. признания по второй части сделки прямого РЕПО № " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate + " на счет вложений";
           end;
              if( not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                    "Премия, ц/б", CredAcc,           /* Деб , КатегКредит*/
                                                    dat,                              /* Дата */
                                                    1,                                /* Глава */
                                                    FD.FaceFIID,                      /* Валюта */
                                                    Abs(Summ),                        /* Сумма дебет*/
                                                    INPCARRY,                         /* Result_Carry */
                                                    " 1",                             /* Kind_Oper */
                                                    FD.tick.rec.DealCode,             /* Numb_Document */
                                                    ground/*"Учет премии в СССД_ЦБ"*/,               /* Ground */
                                                    null, 
                                                    GetFIRoleByPortfolioBonus(KINDPORT_SALE), 
                                                    GetFIRoleByPortfolioBonus(KINDPORT_SALE, true)
                                                  )
                )
                 return 1;
              end;
           end;
        end;

        if( FD.ActualAccount( "Премия, ц/б", null, true, GetFIRoleByPortfolioBonus(KINDPORT_RETIRE, true), CredAcc, dat ) ) 
           Summ = BonusPUDP;

           if( Summ != $0 ) 
              if( not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                    "Премия, ц/б", CredAcc,           /* Деб , КатегКредит*/
                                                    dat,                              /* Дата */
                                                    1,                                /* Глава */
                                                    FD.FaceFIID,                      /* Валюта */
                                                    Abs(Summ),                        /* Сумма дебет*/
                                                    INPCARRY,                         /* Result_Carry */
                                                    " 1",                             /* Kind_Oper */
                                                    FD.tick.rec.DealCode,             /* Numb_Document */
                                                    "Учет премии в АС_ЦБ",             /* Ground */
                                                    null, 
                                                    GetFIRoleByPortfolioBonus(KINDPORT_RETIRE),
                                                    GetFIRoleByPortfolioBonus(KINDPORT_RETIRE, true)
                                                  )
                )
                  return 1;
              end;
           end;
        end;

     else
        SQLQuery = DL_RSDCommand();

        var query = " select v.t_Portfolio Portfolio, NVL(SUM(v.t_BegBonus - v.t_Bonus + v.t_OldBonus), 0) RestBonus, "
                  + "        NVL(SUM(v.t_NKDAmount), 0) NKDAmount, NVL(SUM(v.t_NotWrtBonus), 0) NotWrtBonus"
                  + "   from v_scwrthistex v "
                  + "  where v.t_DocKind       = " + DLDOC_PAYMENT
                  + "    and v.t_DocID         = ? "
                  + "    and v.t_FIID          = ? "
                  + "    and v.t_Department    = ? "
                  + "    and v.t_State         = ? " 
                  + "    and v.t_ID_Operation  = ? "
                  + "    and v.t_ID_Step       = -1 "
                  + "    and v.t_Portfolio <>  " + KINDPORT_BACK
                  + "    and v.t_Action <> " + PM_WRTSUM_UPDTMODE_CDELIVERY
                  + "    and v.t_Instance      = ( select nvl(min(v2.t_Instance),0) " 
                  + "                                from v_scwrthistex v2 " 
                  + "                               where v2.t_SumID        = v.t_SumID " 
                  + "                                 and v2.t_State        = ? " 
                  + "                                 and v2.t_ID_Operation = v.t_ID_Operation " 
                  + "                                 and v2.t_ID_Step      = v.t_ID_Step ) "
                  + "    AND ( (SELECT COUNT (1) "
                  + "                  FROM v_scwrthistex v3 "
                  + "                 WHERE v3.t_SumID = v.t_SumID AND v3.t_Portfolio =  "+ KINDPORT_BASICDEBT 
                  + "                       AND v3.t_Instance =                  "
                  + "                              (SELECT MAX (v4.t_Instance)    "
                  + "                                 FROM v_scwrthistex v4        "
                  + "                                WHERE v4.t_SumID = v.t_SumID   "
                  + "                                      AND v4.t_Instance < v.t_Instance)) = 0) "   
                  + "     GROUP BY v.t_Portfolio ";

        SQLQuery.addParam( FD.GetRQ(DLRQ_TYPE_DELIVERY).rec.ID );
        SQLQuery.addParam( FD.CurPFI() );
        SQLQuery.addParam( FD.tick.rec.Department );
        SQLQuery.addParam( PM_WRTSUM_FORM );
        SQLQuery.addParam( ПроводкиБУ.GetServDocID() );
        SQLQuery.addParam( PM_WRTSUM_FORM );

        RSD = SQLQuery.Execute(query);
        while( RSD.MoveNext() )
           if(ВедениеСчетовБПППоВыпуску() == true)
             CatBpp = "Уплаченный НКД";
           else
             CatBpp = IIF(IsBasket(FD.Group), "Уплач. НКД, Корзина БПП", "Уплаченный НКД, БПП");
           end;
           
           if( ОтдельныйУчетУплНКД() AND
               FD.IsExistAccount(CatBpp, null, true, GetFIRoleByPortfolio(RSD.rec.Portfolio, null, null, true, IsOverdue), CredAcc, null, dat, FD.FaceFIID())
             )
              Ground = "Перенос УНКД " + GetFinName(FD.fininstr.rec) + " со счета УНКД для проданных без прек. признания по второй части сделки прямого РЕПО № " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate + " на счет УНКД ";
              if( not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                    "Уплаченный НКД", CredAcc, /* КатегДеб, КатегКредит */
                                                    dat,                       /* Дата */
                                                    1,                         /* Глава */
                                                    FD.FaceFIID(),             /* Валюта */
                                                    money(RSD.rec.NKDAmount),  /* Сумма */
                                                    INPCARRY,                  /* Result_Carry */
                                                    " 1",                      /* Kind_Oper */
                                                    "",                        /* Numb_Document */
                                                    Ground/*"Перевод НКД"*/,
                                                    null,
                                                    GetFIRoleByPortfolio(RSD.rec.Portfolio)
                                                  )
                )
                 return 1;
              end;
           end;

           Summ = money(RSD.rec.RestBonus);
           Ground = "Перенос уплаченной премии " + GetFinName(FD.fininstr.rec) + " со счета уплаченной премии для проданных без прек. признания по второй части сделки прямого РЕПО № " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate + " на счет премии ";

           if( not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                 "Премия, ц/б", "Премия, ц/б",             /* КатегДеб , КатегКредит*/
                                                 dat,                            /* Дата */
                                                 1,                              /* Глава */
                                                 FD.FaceFIID(),                  /* Валюта */
                                                 Summ,                           /* Сумма  */
                                                 INPCARRY,                       /* Result_Carry */
                                                 " 1",                           /* Kind_Oper */
                                                 "",                             /* Numb_Document */
                                                 ground, /*"Перевод остатка уплаченной премии",*/
                                                 null,
                                                 GetFIRoleByPortfolioBonus(RSD.rec.Portfolio),
                                                 GetFIRoleByPortfolioBonus(RSD.rec.Portfolio, true)  // БПП
                                               )
             )
              return 1;
           end;
        end;
     end;

     if (not БУ_ВыполнитьПроводкиПереводаНачисленногоДоходаВПрямомРЕПО(FD, dat, IsCompensWrt, GrDealID))
        return 1;
     end;

     if( (not IsOverdue) and (not IsCompensWrt) and ОтдельныйУчетУплНКД() )
        if(dat < GetSecurNewRepoDate()) //В новом учете РЕПО не выполняем
        
          ForRestAcc = 0;
          if(((CoupPlanDate != date(0,0,0)) and (CoupPlanDate == Delivery2PlanDate)) OR
             ((PartRepPlanDate != date(0,0,0)) and (PartRepPlanDate == Delivery2PlanDate)) 
            )
            ForRestAcc = GETRESTACC_CREDIT;
          end;

          /* ПР 2КАБ */
          SQLQuery = DL_RSDCommand();
          var q =   " SELECT NVL(SUM(Link.t_NKDBuyAmount), 0) NKD, NVL(SUM(Link.t_BegBonusChange + Link.t_OldBegBonusChange - Link.t_BonusBuy), 0) Bonus " 
                  + "   FROM DPMWRTLNK_DBT Link, DPMWRTSUM_DBT LotBuy, DPMWRTSUM_DBT LotSale2 "
                  + "  WHERE Link.T_SALEID      = ? "
                  + "    AND LotBuy.T_SUMID     = Link.T_BUYID  "
                  + "    AND LotBuy.t_Portfolio = ? "
                  + "    AND LotSale2.t_Parent  = LotBuy.t_SumID ";
          

          SQLQuery.addParam( FD.pmwrtsum.rec.Parent );
          SQLQuery.addParam( KINDPORT_BACK );

          if(GetSecurNewRepoDate() <= dat)         
            q = q + " AND LotSale2.t_Date >= ? ";
            SQLQuery.addParam( dat );
          end;
          
          RSD = SQLQuery.execute(q);

          if( RSD.MoveNext() )
             NKD_PVO   = money(RSD.rec.NKD);
             Bonus_PVO = money(RSD.rec.Bonus);
          end;

          if( FD.ActualAccount(IIF(IsBasket(FD.Group), "+ОД, Корзина", "+ОД"), null, true, null, CredAcc, dat, FD.FaceFIID ) ) 
             if(ForRestAcc)
               Summ = $0;
             else
               Summ = Abs(GetRestAccount( CredAcc, dat ));
             end;
             if( (ForRestAcc) OR (Summ != $0) ) 
                if (ОтдельныйУчетУплНКД())
                   if( FI_IsBond(FD.fininstr) )
                      if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                           "Уплаченный НКД", CredAcc,      /* КатегДеб , КатегКредит*/
                                                           dat,                            /* Дата */
                                                           1,                              /* Глава */
                                                           FD.FaceFIID(),                  /* Валюта */
                                                           NKD_PVO,                        /* Сумма  */
                                                           INPCARRY,                       /* Result_Carry */
                                                           " 1",                           /* Kind_Oper */
                                                           "",                             /* Numb_Document */
                                                           "Учёт суммы НКД",
                                                           null,
                                                           GetFIRoleByPortfolio( Portfolio ), null,
                                                           FD.FaceFIID, FD.FaceFIID
                                                         )
                        )
                          return 1;
                      end;
                      Summ = Summ - NKD_PVO;
                   end;

                   if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                        "Премия, ц/б", CredAcc,         /* КатегДеб , КатегКредит*/
                                                        dat,                            /* Дата */
                                                        1,                              /* Глава */
                                                        FD.FaceFIID(),                  /* Валюта */
                                                        Bonus_PVO,                      /* Сумма  */
                                                        INPCARRY,                       /* Result_Carry */
                                                        " 1",                           /* Kind_Oper */
                                                        "",                             /* Numb_Document */
                                                        "Учёт премии",
                                                        null,
                                                        GetFIRoleByPortfolioBonus(Portfolio), null,
                                                        FD.FaceFIID, FD.FaceFIID
                                                      ) 
                     )
                       return 1;
                   end;
                   Summ = Summ - Bonus_PVO;

                   if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                        "Наш портфель ц/б", CredAcc,    /* КатегДеб , КатегКредит*/
                                                        dat,                            /* Дата */
                                                        1,                              /* Глава */
                                                        FD.GetAccFIID("Наш портфель ц/б"),/* Валюта */
                                                        Summ,                           /* Сумма  */
                                                        INPCARRY,                       /* Result_Carry */
                                                        " 1",                           /* Kind_Oper */
                                                        "",                             /* Numb_Document */
                                                        "Учёт стоимости бумаг",
                                                        ForRestAcc,
                                                        GetFIRoleByPortfolio( Portfolio ), null,
                                                        FD.GetAccFIID("Наш портфель ц/б"), FD.FaceFIID
                                                      ) 
                     )
                       return 1;
                   end;
                else
                   if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                        "Премия, ц/б", CredAcc,         /* КатегДеб , КатегКредит*/
                                                        dat,                            /* Дата */
                                                        1,                              /* Глава */
                                                        FD.FaceFIID(),                  /* Валюта */
                                                        Bonus_PVO,                      /* Сумма  */
                                                        INPCARRY,                       /* Result_Carry */
                                                        " 1",                           /* Kind_Oper */
                                                        "",                             /* Numb_Document */
                                                        "Учёт премии",
                                                        null,
                                                        GetFIRoleByPortfolioBonus(Portfolio), null,
                                                        FD.FaceFIID, FD.FaceFIID
                                                      )
                     )
                       return 1;
                   end;

                   if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                                        "Наш портфель ц/б", CredAcc,    /* КатегДеб , КатегКредит*/
                                                        dat,                            /* Дата */
                                                        1,                              /* Глава */
                                                        FD.GetAccFIID("Наш портфель ц/б"),                  /* Валюта */
                                                        Summ - Bonus_PVO,               /* Сумма  */
                                                        INPCARRY,                       /* Result_Carry */
                                                        " 1",                           /* Kind_Oper */
                                                        "",                             /* Numb_Document */
                                                        "Учёт стоимости бумаг",
                                                        ForRestAcc,
                                                        GetFIRoleByPortfolio( Portfolio ), null,
                                                        FD.GetAccFIID("Наш портфель ц/б"), FD.FaceFIID
                                                       )
                     )
                       return 1;
                   end;
                end; /* if (ОтдельныйУчетУплНКД()) */
             end; /* if( Summ != $0 ) */
          end;
        end;
     elif( (not IsOverdue) and (IsCompensWrt) and (ОтдельныйУчетУплНКД()) )
        /* ПР 2ШВВ */
        if(dat < GetSecurNewRepoDate()) //В новом учете РЕПО не выполняем
          if( FD.ActualAccount(IIF(IsBasket(FD.Group), "+ОД, Корзина", "+ОД"), null, true, null, CredAcc, dat, FD.FaceFIID ) ) 
             if( FI_IsBond(FD.fininstr) )
                if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                       "Уплаченный НКД", CredAcc,      /* КатегДеб , КатегКредит*/
                       dat,                            /* Дата */
                       1,                              /* Глава */
                       FD.FaceFIID(),                  /* Валюта */
                       NKDOD,                        /* Сумма  */
                       INPCARRY,                       /* Result_Carry */
                       " 1",                           /* Kind_Oper */
                       "",                             /* Numb_Document */
                       "Учёт суммы НКД",
                       null,
                       GetFIRoleByPortfolio( Portfolio ), null,
                       FD.FaceFIID, FD.FaceFIID
                      ) 
                  )
                    return 1;
                end;
             end;

             if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                    "Наш портфель ц/б", CredAcc,             /* КатегДеб , КатегКредит*/
                    dat,                            /* Дата */
                    1,                              /* Глава */
                    FD.GetAccFIID("Наш портфель ц/б"),                  /* Валюта */
                    SummOD-NKDOD,                 /* Сумма  */
                    INPCARRY,                       /* Result_Carry */
                    " 1",                           /* Kind_Oper */
                    "",                             /* Numb_Document */
                    "Учёт стоимости бумаг",
                    NULL,
                    GetFIRoleByPortfolio( Portfolio ), null,
                    FD.GetAccFIID("Наш портфель ц/б"), FD.FaceFIID
                   ) 
               )
                 return 1;
             end;
          end;
        end;
     else
       if(dat < GetSecurNewRepoDate()) //В новом учете РЕПО не выполняем
         if( IsOverdue )
            CatOD = IIF(IsBasket(FD.Group), "Треб. с н.с., корзина", "Треб. с н.с.");
         else
            CatOD = IIF(IsBasket(FD.Group), "+ОД, Корзина", "+ОД");
         end;
         
         if( FD.ActualAccount( CatOD, null, true, null, CredAcc, dat, FD.FaceFIID ) ) 
            
            if( IsCompensWrt )
               Summ = SummOD;
            else
               Summ = GetRestAccount( CredAcc, dat );
            end;
            if( Summ != $0 ) 
               if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                      "Наш портфель ц/б", CredAcc,      /* Деб , КатегКредит*/
                      dat,                              /* Дата */
                      1,                                /* Глава */
                      FD.GetAccFIID("Наш портфель ц/б"),/* Валюта */
                      Abs(Summ),                        /* Сумма дебет*/
                      INPCARRY,                         /* Result_Carry */
                      " 1",                             /* Kind_Oper */
                      FD.tick.rec.DealCode,             /* Numb_Document */
                      "Учет стоимости ц/б в ОД",        /* Ground */
                      null, 
                      GetFIRoleByPortfolio( Portfolio ), null,
                      FD.GetAccFIID("Наш портфель ц/б"), FD.FaceFIID
                     ))
                   return 1;
               end;
            end;
         end;
       end;
     end;

     var FIRole;
     if( IsOverdue )
        FIRole = FIROLE_BA_OVERDUE;
     else
        FIRole = FIROLE_BA;
     end;

     if( FD.IsExistAccount(IIF(IsBasket(FD.Group), "Ц/б, ПВО_БПП, Корзина", "Ц/б, ПВО_БПП"), null, true, FIRole, CredAcc, null, dat) )
        ForRestAcc = 0;

        if( IsCompensWrt )
           if(IsDealKSU(FD.Group))
             Summ = SumBackKSU;
           else
             Summ = SummOD;
           end;
        else
           ForRestAcc = GETRESTACC_CREDIT;
           Summ = $0;
        end;

        ground = "Перенос балансовой стоимости бумаг " + GetFinName(fininstr.rec) + ", переданных из обратного в прямое репо " + UserGetDealCode(FD) + " от " + FD.tick.rec.dealdate;
        if( not БУ_ПроводкаПоКатегориямУчета( FD,
                                              "ВнебалСчетКорресп", CredAcc, /* КатегДеб, КатегКредит */
                                              dat,                          /* Дата */
                                              3,                            /* Глава */
                                              FD.FaceFIID(),                /* Валюта */
                                              Summ,                         /* Сумма */
                                              INPCARRY,                     /* Result_Carry */
                                              " 1",                         /* Kind_Oper */
                                              "",                           /* Numb_Document */
                                              ground/*"Учет суммы КП"*/,
                                              ForRestAcc,
                                              FIROLE_CA,
                                              FIRole,
                                              NATCUR, FD.FaceFIID()
                                            )
          )
           return 1;
        end;
     end;

  end;

  return 0; 
end;

macro БУ_ПроводкиПоОплатеПриПокупке(FD, dat)
  var PayerAccount = TRecHandler("account.dbt"); 
  var MarketAcc = "", Bonus0 = $0, NKD = $0, PayFIID_Bonus0 = $0, PayFIID_NKD = $0;
  var DebFIID = null, DebSum = null, Dp, Dknext, FaceFIIDRqAmount = $0;
  var rq_money = TRecHandler("dlrq.dbt");
  var rq_avoir = TRecHandler("dlrq.dbt");

  rq_money = FD.GetRQ(DLRQ_TYPE_PAYMENT);
  rq_avoir = FD.GetRQ(DLRQ_TYPE_DELIVERY);

  /*внебиржевая*/
  if(IsOUTEXCHANGE(FD.Group)) 
    if( (not IsClientDeal(FD.tick.rec)) AND 
        (FD.ExistDeposit == true) AND/*есть платеж задатка - выполним его зачет*/
        (rq_money.rec.State != DLRQ_STATE_OVERDUE) AND
        (not ТОБылоПросрочено(rq_money)) 
      )

       if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                            "-Форвард, расчеты", "+Расчеты", /* КатегДеб , КатегКредит*/
                                            dat,                    /* Дата  */
                                            1 ,                     /* Глава */
                                            FD.GetPayFIID(),        /* Валюта*/
                                            FD.GetRQPayAmount(DLRQ_TYPE_DEPOSIT, dat),   /* Сумма */
                                            INPCARRY,               /* Result_Carry   */
                                            " 1",                   /* Kind_Oper      */
                                            FD.tick.rec.DealCode,        /* Numb_Document */
                                            "Зачет суммы уплаченного задатка", /* Ground */
                                            null, null, null         
                                          )
         )
           return 1;
       end;         
    end; 
     
    /* Сделаем проводки по контрактиву. */
    if( БУ_СделатьПроводкиПоОплате_БезПросрочки_ПриПокупке(FD, dat) != 0)
       return 1;
    end;
  
  /*брокерская или биржевая*/
  elif( (IsBROKER(FD.Group)) OR (IsEXCHANGE(FD.Group))) 
    MarketAcc = ПолучитьКатегориюСчетаКонтрагента( FD, SP_RqIsSale( rq_money, FD.tick ) );

    if( (MarketAcc == "Корсчет") OR (IsClientDeal(FD.tick.rec)) OR (FD.ВедетсяБалансУчетПоСделке() == true) or FD.DealAsResultDVExe ) 

        if( БУ_СделатьПроводкиПоОплате_БезПросрочки_ПриПокупке(FD, dat) != 0)
          return 1;
        end;

    else
       if( not IsClientDeal(FD.tick.rec) )
          
          var PayerCateg:string;

          if(ПолучитьНашСчетТОПоОплате(rq_money, FD, dat, PayerAccount, PayerAccount, @PayerCateg, @PayerCateg) != 0 )
            return 1;
          end;

          if ((not IsREPO(FD.Group)) and 
              (FD.Kind != DL_TRUSTDOC) and
             (not IsClientDeal(FD.tick.rec)) and /* Отсюда и ниже - условия, при которых в платеже по к/а счет "Наш портфель ц/б" из MACRO ЗаполнитьНашСчетВПлатежеПоКонтрактиву( FD, dat ) */
              (FD.BuySale == DEAL_TYPE_BUY) and
              (not FD.ВедетсяБалансУчетПоСделке()) and
              (not FD.ExistBack)
             )

             Bonus0 = SP_GetBonusSum( FD );

             var ВалютаСуммы:integer = FD.ВалютаНоминалаПКУ(PayerCateg);

             SmartConvertSum(PayFIID_Bonus0, Bonus0,
                             rq_avoir.rec.PlanDate, FD.FaceFIID(), FD.GetPayFIID(), false);

             SmartConvertSum(FaceFIIDRqAmount, rq_money.rec.Amount,
                             rq_money.rec.PlanDate, rq_money.rec.FIID, ВалютаСуммы, false);

             if( (FD.dl_leg.rec.NKD > 0.) AND ОтдельныйУчетУплНКД() )
                NKD = FD.dl_leg.rec.NKD;
                SmartConvertSum(PayFIID_NKD, NKD, rq_avoir.rec.PlanDate, FD.NKDFIID(), FD.GetPayFIID(), false);
             end;
             
             DebFIID = ВалютаСуммы;
             DebSum = FaceFIIDRqAmount - Bonus0 - NKD;
          end; 

          /*проводка будет СчётДебета - "+Биржа"*/
          if(not БУ_ПроводкаПоКатегориямУчета( FD,
                                               PayerAccount, MarketAcc, /* Деб , КатегКредит*/
                                               dat,                     /* Дата */
                                               1,                       /* Глава */
                                               FD.GetPayFIID(),         /* Валюта */
                                               FD.GetRQPayAmount(DLRQ_TYPE_PAYMENT, dat) - PayFIID_Bonus0 - PayFIID_NKD, /* Сумма */
                                               INPCARRY,                /* Result_Carry */
                                               " 1",                    /* Kind_Oper */
                                               FD.tick.rec.DealCode,    /* Numb_Document */
                                               "Исполнение обязательств по оплате ц/б",/* Ground */
                                               null,
                                               null, null,
                                               null, FD.GetPayFIID(),
                                               DebFIID, DebSum
                                             )
            )
              return 1;
          end;

         /* /*учет НКД на отдельном счете*/
          if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                               "Уплаченный НКД", MarketAcc,/* КатегДеб , КатегКредит*/
                                               dat,                        /* Дата */
                                               1,                          /* Глава */
                                               FD.FaceFIID(),              /* Валюта */
                                               NKD,                        /* Сумма */
                                               INPCARRY,                   /* Result_Carry */
                                               " 1",                       /* Kind_Oper */
                                               FD.tick.rec.DealCode,       /* Numb_Document */
                                               "Сумма НКД",                /* Ground */
                                               null, GetFIRoleByPortfolio( FD.pmwrtsum.rec.GroupID), null,
                                               FD.FaceFIID(), FD.GetPayFIID()
                                             )
            )
              return 1;
          end;

          /*проводка будет "Премия, ц/б"  - "+Биржа"*/
          if(not БУ_ПроводкаПоКатегориямУчета( FD, 
                                               "Премия, ц/б", MarketAcc, /* Деб , КатегКредит*/
                                               dat,                      /* Дата */
                                               1,                        /* Глава */
                                               FD.FaceFIID(),            /* Валюта */
                                               Bonus0,                   /* Сумма */
                                               INPCARRY,                 /* Result_Carry */
                                               " 1",                     /* Kind_Oper */
                                               FD.tick.rec.DealCode,     /* Numb_Document */
                                               "Сумма премии",           /* Ground */
                                               null, GetFIRoleByPortfolioBonus(FD.pmwrtsum.rec.GroupID), null,
                                               FD.FaceFIID(), FD.GetPayFIID()
                                             )
            )
              return 1;
          end;*/
       end;
    end;

    if(IsTODAY(FD.Group))
      if( not БУ_СписатьРезерв( FD, Dat ) )
        return 1;
      end;
    end;

  end;

  return 0;
end;
