DECLARE

BEGIN

  UPDATE DNPTXOBJ_DBT OBJ
     SET OBJ.T_TAXPERIOD = EXTRACT(YEAR FROM OBJ.T_DATE)
   WHERE OBJ.T_LEVEL = 8
     AND OBJ.T_TAXPERIOD = 0
     AND OBJ.T_KIND = 1143
     AND OBJ.T_DATE >= TO_DATE('01.01.2021','DD.MM.YYYY');

END;
/
