/*Таблица DBRKREPCASHEMOVING_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPCASHEMOVING_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPCASHEMOVING_TMP
(
  T_CURRENCY    NUMBER(10),
  T_DATE        DATE,
  T_SERVKIND    NUMBER(5),
  T_SERVKINDSUB NUMBER(5),
  T_ISITOG      CHAR(1),
  T_ACCTRNID    NUMBER(10),
  T_OPERNAME    VARCHAR2(600),
  T_MARKETID    NUMBER(10),
  T_MARKETNAME  VARCHAR2(100),
  T_INSUM       NUMBER(32,12),
  T_OUTSUM      NUMBER(32,12),
  T_OUTNDS      NUMBER(32,12),
  T_REST        NUMBER(32,12),
  T_ACCOUNTID   NUMBER(10),
  T_ACCOUNT_PAYER VARCHAR2(25),
  T_ACCOUNT_RECEIVER VARCHAR2(25),
  T_GROUPTYPE 	VARCHAR2(200),
  T_ISGROUP   CHAR(1),
  T_PRINTDATE VARCHAR2(512)  
)
ON COMMIT PRESERVE ROWS
NOCACHE
/
