-- Таблица "DNPTXLNKDIASPAY_DBT"
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DNPTXLNKDIASPAY_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DNPTXLNKDIASPAY_DBT (
    T_ID NUMBER(10)
  , T_DATE DATE
  , T_CONFIRMDATE DATE
  , T_PARTYID NUMBER(10)
  , T_CONTRACTID NUMBER(10)
  , T_FIID NUMBER(10)
  , T_BUYID NUMBER(10)
  , T_NKDBUY NUMBER(32,12)
  , T_NKDSALE NUMBER(32,12)
  , T_SUM NUMBER(32,12)
  , T_COMMENT VARCHAR2(256)
  , T_PAYMENTID VARCHAR2(50)
  , T_NKDBTSOBJID NUMBER(10)
)
/

COMMENT ON TABLE DNPTXLNKDIASPAY_DBT IS 'Таблица учета УНКД'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_ID IS 'ID записи'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_DATE IS 'Дата создания записи'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_CONFIRMDATE IS 'Дата подтверждения'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_PARTYID IS 'Id субъекта в СОФР'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_CONTRACTID IS 'Id договора'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_FIID IS 'Id фин.инструмент'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_BUYID IS 'ID сделки покупки'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_NKDBUY IS 'Общая сумма НКД из сделки покупки'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_NKDSALE IS 'Сумма реализованного НКД из объекта НДР "NkdB" по связанной сделке продажи'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_SUM IS 'Сумма УНКД в НОБ, по клиенту'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_COMMENT IS 'Примечани'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_PAYMENTID IS 'ID выплаты из Диасофта из запроса'/
COMMENT ON COLUMN DNPTXLNKDIASPAY_DBT.T_NKDBTSOBJID IS 'Объект НДР "NkdB_TS"'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXLNKDIASPAY_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXLNKDIASPAY_DBT_IDX0 ON DNPTXLNKDIASPAY_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXLNKDIASPAY_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXLNKDIASPAY_DBT_IDX1 ON DNPTXLNKDIASPAY_DBT (
   T_PAYMENTID ASC
  ,T_BUYID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DNPTXLNKDIASPAY_DBT_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
   e_exist_seq EXCEPTION;
   PRAGMA EXCEPTION_INIT(  e_exist_seq,    -955 );
BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE DNPTXLNKDIASPAY_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
   WHEN e_exist_seq THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER DNPTXLNKDIASPAY_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXLNKDIASPAY_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXLNKDIASPAY_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXLNKDIASPAY_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
