/*„®΅ Ά«¥­¨¥ §­ η¥­¨© ­ αβΰ®¥ª*/
DECLARE
  v_ID       NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('……„€—€ “„ ‚ „€‘”’');

  DELETE FROM DREGVAL_DBT WHERE T_KEYID = v_ID;

  INSERT INTO DREGVAL_DBT(T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX )
  VALUES(v_ID,0,0,'',0,88,0,'');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
  v_ID       NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('€€‚‹’_’—…’_“„_„€‘”’');

  DELETE FROM DREGVAL_DBT WHERE T_KEYID = v_ID;

  INSERT INTO DREGVAL_DBT(T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX )
  VALUES(v_ID,0,0,'',0,88,0,'');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
  v_ID       NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE LOWER(T_NAME) = LOWER('‹“—€’…‹_’—…’€_“„_„€‘”’');

  DELETE FROM DREGVAL_DBT WHERE T_KEYID = v_ID;

  INSERT INTO DREGVAL_DBT(T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX )
  VALUES(v_ID,0,0,'',0,0,0,'597564616B6F76414E6940727368622E72753B476F72656C6F766145536540696E746563682E727368622E72753B62726F6B657240727368622E727500');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/
