-- Таблица "DDL_REPORT_TRANSFBALACC_TMP"
BEGIN
EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DDL_REPORT_TRANSFBALACC_TMP (
    T_IDENTPROG CHAR(1)
  , T_DEALID NUMBER(10)
  , T_DOCKIND NUMBER(5)
  , T_DEALCODE VARCHAR2(50)
  , T_NAME VARCHAR2(79)
  , T_DEALDATE DATE
  ,  T_BASIS NUMBER(5)
) ON COMMIT PRESERVE ROWS';

EXECUTE IMMEDIATE 'COMMENT ON TABLE DDL_REPORT_TRANSFBALACC_TMP IS ''Отчет перенос по счетам''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRANSFBALACC_TMP.T_IDENTPROG IS ''Идентификатор подсистемы''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRANSFBALACC_TMP.T_DEALID IS ''Идентификатор сделки''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRANSFBALACC_TMP.T_DOCKIND IS ''Вид документа''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRANSFBALACC_TMP.T_DEALCODE IS ''Код сделки''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRANSFBALACC_TMP.T_NAME IS ''Название операции''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRANSFBALACC_TMP.T_DEALDATE IS ''дата сделки''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDL_REPORT_TRANSFBALACC_TMP.T_BASIS IS ''Базис''';
END;
/
