--Временная таблица
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DNPTXOPSKIPFO_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE DNPTXOPSKIPFO_TMP
(
  T_DOCKIND           NUMBER(5),
  T_CLIENT            NUMBER(10),
  T_OPERDATE          DATE,
  T_CODE              VARCHAR2(25)
)
ON COMMIT PRESERVE ROWS';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXOPSKIPFO_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX DNPTXOPSKIPFO_TMP_IDX0 ON DNPTXOPSKIPFO_TMP (
   T_DOCKIND ASC
  ,T_CLIENT ASC
  ,T_OPERDATE ASC
  ,T_CODE ASC
)
/
