/*Таблица DBRKREPCASHEGROUPMOVING_TMP*/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DBRKREPCASHEGROUPMOVING_TMP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE GLOBAL TEMPORARY TABLE DBRKREPCASHEGROUPMOVING_TMP
(
  T_CURRENCY    NUMBER(10),
  T_DATE        DATE,
  T_PRINTDATE   VARCHAR2(512),
  T_OPERNAME    VARCHAR2(600),
  T_MARKETNAME  VARCHAR2(100),
  T_INSUM       NUMBER(32,12), 
  T_OUTSUM      NUMBER(32,12), 
  T_REST        NUMBER(32,12),   
  T_SERVKIND    NUMBER(5),
  T_SERVKINDSUB NUMBER(5),
  T_ISITOG      CHAR(1)    
)
ON COMMIT PRESERVE ROWS
NOCACHE
/
