/*Добавление в справочник*/
BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7339,0,'Отмена (откат) ранее запрошенного УНКД',40,2,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7339,1,'Запрос УНКД',40,2,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/