-- Таблица "DNPTXNKDREQDIAS_DBT"
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DNPTXNKDREQDIAS_DBT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DNPTXNKDREQDIAS_DBT (
    T_ID NUMBER(10)
  , T_GUID VARCHAR2(40)
  , T_GUIDRESP VARCHAR2(40)
  , T_REQUESTDATE DATE
  , T_REQUESTTIME DATE
  , T_PAYMENTID VARCHAR2(50)
  , T_PAYMENTACTION NUMBER(5)
  , T_FIXINGDATE DATE
  , T_CLIENTID VARCHAR2(50)
  , T_AGREEMENTNUMBER VARCHAR2(50)
  , T_ISIIS CHAR(1)
  , T_MARKETPLACE VARCHAR2(60)
  , T_ISINREGNUMBER VARCHAR2(50)
  , T_COUPONNUMBER VARCHAR2(15)
  , T_COUPONSTARTDATE DATE
  , T_COUPONENDDATE DATE
  , T_CREATEDATE DATE
  , T_CREATETIME DATE
  , T_CHANGEDATE DATE
  , T_CHANGETIME DATE
  , T_ERRORCODE NUMBER(5)
  , T_ERROR VARCHAR2(500)
  , T_SUM NUMBER(32,12)
  , T_PARTYID NUMBER(10)
  , T_CONTRACTID NUMBER(10)
  , T_FIID NUMBER(10)
)
/

COMMENT ON TABLE DNPTXNKDREQDIAS_DBT IS 'Таблица запросов УНКД по клиентам'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_ID IS 'ID записи в буфере'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_GUID IS 'Текстовый уникальный идентификатор GUID'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_GUIDRESP IS 'Сгенерированный уникальный GUID на стороне СОФР'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_REQUESTDATE IS 'Текущая дата отправки запроса'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_REQUESTTIME IS 'Текущее время отправки запроса'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_PAYMENTID IS 'ID для идентификации выплаты  для отправки отмены (отката) УНКД'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_PAYMENTACTION IS 'Действие с выплатой: 1 - запрос УНКД; 0 - отмена (откат) ранее запрошенного УНКД'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_FIXINGDATE IS 'Дата фиксации списка владельцев ЦБ'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_CLIENTID IS 'ID клиента в системе ЦФТ'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_AGREEMENTNUMBER IS 'Номер ДБО'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_ISIIS IS 'Признак ИИС: 1 - ИИС; 0 - не ИИС'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_MARKETPLACE IS 'Место хранения ЦБ: "NRD" - НРД; "SPB" - СПБ'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_ISINREGNUMBER IS 'ISIN или гос. регистрационный номер ЦБ в разрезе выпуска'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_COUPONNUMBER IS 'Номер купона по облигациям'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_COUPONSTARTDATE IS 'Дата начала купонного периода'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_COUPONENDDATE IS 'Дата окончания купонного периода'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_CREATEDATE IS 'Дата создания записи в буфере'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_CREATETIME IS 'Время создания записи в буфере'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_CHANGEDATE IS 'Дата последнего изменения записи в буфере'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_CHANGETIME IS 'Время последнего изменения записи в буфере'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_ERRORCODE IS 'Код ошибки'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_ERROR IS 'Текст ошибки'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_SUM IS 'Сумма УНКД'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_PARTYID IS 'Идентификатор субъекта в СОФР'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_CONTRACTID IS 'Идентификатор договора клиента в СОФР'/
COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_FIID IS 'Идентификатор фин.инструмента в СОФР'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXNKDREQDIAS_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXNKDREQDIAS_DBT_IDX0 ON DNPTXNKDREQDIAS_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXNKDREQDIAS_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXNKDREQDIAS_DBT_IDX1 ON DNPTXNKDREQDIAS_DBT (
   T_PARTYID ASC
  ,T_CONTRACTID ASC
  ,T_FIID ASC
  ,T_MARKETPLACE ASC
  ,T_FIXINGDATE ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXNKDREQDIAS_DBT_IDX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DNPTXNKDREQDIAS_DBT_IDX2 ON DNPTXNKDREQDIAS_DBT (
   T_GUID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXNKDREQDIAS_DBT_IDX3';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXNKDREQDIAS_DBT_IDX3 ON DNPTXNKDREQDIAS_DBT (
   T_REQUESTDATE ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE DNPTXNKDREQDIAS_DBT_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

DECLARE
   e_exist_seq EXCEPTION;
   PRAGMA EXCEPTION_INIT(  e_exist_seq,    -955 );
BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE DNPTXNKDREQDIAS_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER';
EXCEPTION
   WHEN e_exist_seq THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER DNPTXNKDREQDIAS_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTXNKDREQDIAS_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTXNKDREQDIAS_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTXNKDREQDIAS_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
