/*Добавление в справочник*/
DECLARE
BEGIN
  INSERT INTO DOPRKDOC_DBT(T_DOCKIND,T_PRIMARY,T_MODE,T_NAME,T_DBFILE,T_MACRONAME,T_CLASSMACRONAME,T_CLASSNAME,T_PARENTDOCKIND,T_MAXPHASE,T_PROGRAM,T_ORIGIN)
  VALUES(4651,CHR(0),0,'Запрос УНКД от Диасофта','nptxnkdreqdias.dbt',CHR(1),CHR(1),CHR(1),0,0,CHR(0),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/
