-- Таблица "DNPTXRETCONF_TMP"

CREATE GLOBAL TEMPORARY TABLE DNPTXRETCONF_TMP (
    T_TAXPERIOD NUMBER(5)
  , T_DATEPART1 DATE
  , T_DATEPART2 DATE
) ON COMMIT PRESERVE ROWS
/
COMMENT ON TABLE DNPTXRETCONF_TMP IS 'Временная настроечная таблица дат для отраж. возвр'/
COMMENT ON COLUMN DNPTXRETCONF_TMP.T_TAXPERIOD IS 'Налоговый период'/
COMMENT ON COLUMN DNPTXRETCONF_TMP.T_DATEPART1 IS 'Дата отсчета для раздела 1'/
COMMENT ON COLUMN DNPTXRETCONF_TMP.T_DATEPART2 IS 'Дата отсчета для раздела 2'/

