/*
$Name: ul_rates.mac
$Module: Универсальный загрузчик
$Description: Выходная структура котировок
*/

CLASS UL_RATES
  VAR
      FICode         = "",          //Код ФИ
      StartDate      = Date(0,0,0), //Дата начала действия курса
      RateKind       = 0,           //Вид курса
      Market_Place   = "",          //Торговая площадка
      PartyCodeKind  = 0,           //Вид кода для поиска торговой площадки
      Value          = "0.0";       //Значение курса      
END;

