/*Обновление полей в таблице DNPTXNKDREQDIAS_DBT*/
BEGIN
  UPDATE DNPTXNKDREQDIAS_DBT
  SET T_STATUS = 5 --Ошибка обработки
  WHERE T_STATUS IS NULL
  AND T_ERRORCODE IN (7, 8);
END;
/

BEGIN
  UPDATE DNPTXNKDREQDIAS_DBT
  SET T_STATUS = 4 --Ошибка валидации
  WHERE T_STATUS IS NULL
  AND T_ERRORCODE > 0;
END;
/

BEGIN
  UPDATE DNPTXNKDREQDIAS_DBT RD
  SET RD.T_STATUS = 1 --Ожидает подтверждения
  WHERE RD.T_STATUS IS NULL
  AND RD.T_ERRORCODE = 0
  AND RD.T_GUIDRESP <> CHR(1)
  AND EXISTS(SELECT 1 FROM DNPTXLNKDIASPAY_DBT DP WHERE DP.T_PAYMENTID = RD.T_PAYMENTID AND DP.T_NKDBTSOBJID = 0);
END;
/

BEGIN
  UPDATE DNPTXNKDREQDIAS_DBT RD
  SET RD.T_STATUS = 2 --Обработано
  WHERE RD.T_STATUS IS NULL
  AND RD.T_ERRORCODE = 0
  AND RD.T_GUIDRESP <> CHR(1)
  AND (EXISTS(SELECT 1 FROM DNPTXLNKDIASPAY_DBT DP WHERE DP.T_PAYMENTID = RD.T_PAYMENTID AND DP.T_NKDBTSOBJID > 0)
       OR NOT EXISTS(SELECT 1 FROM DNPTXLNKDIASPAY_DBT DP WHERE DP.T_PAYMENTID = RD.T_PAYMENTID));
END;
/

BEGIN
  UPDATE DNPTXNKDREQDIAS_DBT RD
  SET RD.T_STATUS = 0 --Новая запись
  WHERE RD.T_STATUS IS NULL
  AND RD.T_ERRORCODE = 0
  AND RD.T_GUIDRESP = CHR(1);
END;
/

