/*Таблица DBRKREPINACCTICK_TMP*/
CREATE GLOBAL TEMPORARY TABLE DBRKREPINACCTICK_TMP (
    T_DEALDATE DATE
  , T_BOFFICEKIND NUMBER(5)
  , T_DEALID NUMBER(10)
  , T_CLIENTID NUMBER(10)
  , T_PARTYID NUMBER(10)
  , T_SFCONTRID NUMBER(10)
  , T_SERVKINDSUB NUMBER(5)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE DBRKREPINACCTICK_TMP IS 'Данные для ОБ. Сделки для расчета'
/
COMMENT ON COLUMN DBRKREPINACCTICK_TMP.T_DEALDATE IS 'Дата заключения сделки'
/
COMMENT ON COLUMN DBRKREPINACCTICK_TMP.T_BOFFICEKIND IS 'Вид сделки'
/
COMMENT ON COLUMN DBRKREPINACCTICK_TMP.T_DEALID IS 'Идентификатор сделки'
/
COMMENT ON COLUMN DBRKREPINACCTICK_TMP.T_CLIENTID IS 'Идентификатор клиента'
/
COMMENT ON COLUMN DBRKREPINACCTICK_TMP.T_PARTYID IS 'Идентификатор контрагента'
/
COMMENT ON COLUMN DBRKREPINACCTICK_TMP.T_SFCONTRID IS 'Идентификатор субдоговора'
/
COMMENT ON COLUMN DBRKREPINACCTICK_TMP.T_SERVKINDSUB IS 'Подвид обслуживания'
/
