/*Добавление в справочник*/
BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7342,0,'Новая запись',20,6,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7342,1,'Ожидает подтверждения',20,6,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7342,2,'Обработано',20,6,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7342,3,'Ошибка валидации',20,6,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7342,4,'Ошибка обработки',20,6,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
   INSERT INTO DNAMEALG_DBT(T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG, T_RESERVE)
   VALUES(7342,5,'Не подтверждено',20,6,CHR(1));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

