/*Добавление полей в таблицу DNPTXNKDREQDIAS_DBT*/
ALTER TABLE DNPTXNKDREQDIAS_DBT MODIFY T_AGREEMENTNUMBER VARCHAR2(64)
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXNKDREQDIAS_DBT ADD T_GUIDRESULT VARCHAR2(40) DEFAULT CHR(1)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_GUIDRESULT IS ''Идентификатор полученного подтверждения''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_field EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_field, -1430);

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE DNPTXNKDREQDIAS_DBT ADD T_STATUS NUMBER(5)';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN DNPTXNKDREQDIAS_DBT.T_STATUS IS ''Статус обработки записи''';
   EXCEPTION WHEN e_exist_field THEN NULL;
END;
/

DECLARE
   e_exist_ind EXCEPTION;

   PRAGMA EXCEPTION_INIT( e_exist_ind, -955);

BEGIN
   EXECUTE IMMEDIATE 'CREATE INDEX DNPTXNKDREQDIAS_DBT_IDX4 ON DNPTXNKDREQDIAS_DBT (T_STATUS ASC)';
   EXCEPTION WHEN e_exist_ind THEN NULL;
END;
/

