BEGIN
    INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
    VALUES(7344, 1, 'Все клиенты', 27, 2);

    INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
    VALUES(7344, 2, 'Загрузить список клиентов', 27, 2);

    INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
    VALUES(7343, 1, 'ID СОФР', 11, 2);

    INSERT INTO DNAMEALG_DBT (T_ITYPEALG, T_INUMBERALG, T_SZNAMEALG, T_ILENNAME, T_IQUANTALG)
    VALUES(7343, 2, 'ID ЦФТ', 11, 2);
END;