--Копирование записей о рейтингах НРА и НКР для списка рейтингов отчётности в нац. валюте субъекта
BEGIN
  INSERT INTO DOBJATTR_DBT 
  SELECT T_OBJECTTYPE, 122 T_GROUPID, T_ATTRID, T_PARENTID, T_CODELIST, 
         T_NUMINLIST, T_NAMEOBJECT, T_CHATTR, T_LONGATTR, T_INTATTR, 
         T_NAME, T_FULLNAME, T_OPENDATE, T_CLOSEDATE, T_CLASSIFICATOR,
         T_CORRACTYPE, T_BALANCE, T_ISOBJECT
    FROM DOBJATTR_DBT 
   WHERE T_OBJECTTYPE = 3 AND T_GROUPID = 19 AND (T_ATTRID IN (379, 610) OR T_PARENTID IN (379, 610)); 
END;
/

--Копирование записей о рейтингах НРА и НКР для списка рейтингов отчётности в нац. валюте ц/б
BEGIN
  INSERT INTO DOBJATTR_DBT 
  SELECT T_OBJECTTYPE, 127 T_GROUPID, T_ATTRID, T_PARENTID, T_CODELIST, 
         T_NUMINLIST, T_NAMEOBJECT, T_CHATTR, T_LONGATTR, T_INTATTR, 
         T_NAME, T_FULLNAME, T_OPENDATE, T_CLOSEDATE, T_CLASSIFICATOR,
         T_CORRACTYPE, T_BALANCE, T_ISOBJECT
    FROM DOBJATTR_DBT 
   WHERE T_OBJECTTYPE = 12 AND T_GROUPID = 53 AND (T_ATTRID IN (379, 610) OR T_PARENTID IN (379, 610)); 
END;
/