/*
$Name: ws_lns_OperDuration.mac
$Module: WebLoans
$Description: Сервис для виджета операции "Изменение лимита"
*/
IMPORT SbCrdInter, RsbDataSet, commonutil, ws_LoansOperation;

MACRO lns_GetRestTransferWidget(LnsParm)
    var formstr = "";
    var ObjID = LnsParm[0].Value.ObjID;
    var ObjN = LnsParm[0].Value.ObjN;
    var SysOperID = LnsParm[1].Value.SysOperID;
    var TypeOperID = LnsParm[1].Value.TypeOperID;
    var OpDate = LnsParm[2].Value;
    var ReturnDate = LnsParm[3].Value;
    formstr = "<RsControls:RsUserControl " +
        "xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' " +
        "xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' " +
        "xmlns:d='http://schemas.microsoft.com/expression/blend/2008' " +
        "xmlns:mc='http://schemas.openxmlformats.org/markup-compatibility/2006' " +
        "xmlns:System='clr-namespace:System;assembly=mscorlib' " +
        "xmlns:RsControls='clr-namespace:RsControls;assembly=RsControls' " +
        "xmlns:UIBasic='clr-namespace:UIBasic;assembly=UIBasic' " +
        "mc:Ignorable='d' " +
        "x:Name='RootControl' " +
        "d:DesignHeight='300' d:DesignWidth='400'> " +
        "<Grid x:Name='LayoutRoot'> " +
        "        <Grid> " +
        "            <Grid.RowDefinitions> " +
        "                <RowDefinition Height='Auto'/> " +
        "                <RowDefinition Height='0'/> " +
        "            </Grid.RowDefinitions> " +
 /*     Далее идёт формирование одного элемента списка переноса остатка ОД
        для примера поставлены готовые значения. BlockArrow (стрелочкэ) я не нашёл в SL5
        поэтому оно закомментировано.
        "            <Border BorderThickness='0,0,0,1' > " +
        "                <Grid> " +
        "                    <Grid.RowDefinitions> " +
        "                        <RowDefinition Height='Auto'/> " +
        "                        <RowDefinition Height='5'/> " +
        "                        <RowDefinition Height='Auto'/> " +
        "                        <RowDefinition Height='*'/> " +
        "                    </Grid.RowDefinitions> " +
        "                    <Grid.ColumnDefinitions> " +
        "                        <ColumnDefinition Width='Auto'/> " +
        "                    </Grid.ColumnDefinitions> " +
        "                    <TextBlock  Text='Кредитный договор №125-45/15КД' Margin='0,0,12,0' /> " +
        "                    <StackPanel Grid.Row='2' Orientation='Horizontal'> " +
        "                        <TextBlock Text='45502 810 9 000154' Foreground='#FFBA6161' Margin='0,0,6,0' /> " +
        "                        <!--<BlockArrow  Orientation='Right' Stroke='#FFBA6161' UseLayoutRounding='False' Width='20' Height='6' Margin='0,0,6,0' /> --> " +
        "                        <TextBlock Text='45507 810 9 000154' Foreground='#FF5DAF69' Grid.Row='2' Margin='0,0,12,0'/> " +
        "                        <TextBlock Text='100 000' Margin='0,0,6,0'   /> " +
        "                        <TextBlock Text='RUR' /> " +
        "                    </StackPanel> " +
        "                </Grid> " +
        "            </Border> " + */
        "        </Grid> " +
        "    </Grid> " +
        "</RsControls:RsUserControl>";
    return formstr;
END;

MACRO lns_RunChDurationOperation(ObjID, ObjN, TypeOperID, OpDate, ReturnDate)
    var result: TWsMessage;
    record typeopBuff("type_op") btr;
    
    IF (Loans_FindTypeOp(0, TypeOperID, TypeOpBuff) != true)
         result.MsgText = "Выполнение операции. Не найдена операция " + TypeOperID;
         result.MsgID = -1;
         return result;
    END;
    
    result.MsgText = "Выполнение операции. Операция выполнена успешно.";
    result.MsgID = MakeOperation(ObjN, ObjID, TypeOpBuff.TypeOperNumber, 0, OpDate, 0, 0, ReturnDate);
    IF (result.MsgID == 0)
      result.MsgText = GetMO_LoansError;
      result.MsgID = -1*GetMO_ErrorID;
    END;
    return result;
END;

