/*
$Name: ws_lns_OperOpenCrd.mac
$Module: WebLoans
$Description: Сервис для виджета операции "Открытие договора/черновика договора из закрытого"
*/
IMPORT SbCrdInter, RsbDataSet, ws_LoansOperation;

CLASS CLnsClosedObj
    var ExistClosedEns = false; 
    var ExistClosedDuty = false;
END;


MACRO lns_ExistClosedEns(ObjN)
    var result = false;
    var ensCount = LnSelectValue ("SELECT COUNT (*) FROM dens_crd_dbt t1, denscontr_dbt t2 WHERE T1.T_ENSCONTRACTID_REF = T2.T_ENSCONTRACTID AND T2.T_ENSCONTRACTSTATUS = " + EC_CLOSE + " AND t1.T_CREDITNUMBER_REF = " + ObjN, V_INTEGER);
   
    if(ensCount > 0)
        result = true;
    end;
    
    return result;
END;

MACRO lns_ExistClosedDuty(ObjN)
    var result = false;
    var dutyCount = LnSelectValue ("SELECT count(*) FROM dduty_crd_dbt WHERE t_dutystate='З' AND T_CREDITNUMBER_REF = "+ ObjN, V_INTEGER);
   
    if(dutyCount > 0)
        result = true;
    end;
    
    return result;  
END;

MACRO lns_ExistClosedObj(ObjN)
    var result = CLnsClosedObj();
    result.ExistClosedEns = lns_ExistClosedEns(ObjN);
    result.ExistClosedDuty = lns_ExistClosedDuty(ObjN);
    return result;
END;
