/*
$Name: ws_lns_Settings.mac
$Module: WebLoans
$Description: НАстройки
*/

IMPORT BankInter, Globals, ws_validation;

PRIVATE CONST REGKEY_PRODUCTTREEMODE = "RS-LOANS\\WEB\\ДЕРЕВО_ПРОДУКТОВ_КЛИЕНТА\\ВАРИАНТ_СПИСКА";
PRIVATE CONST REGKEY_CLAIMTREEMODE   = "RS-LOANS\\WEB\\ДЕРЕВО_ПРОДУКТОВ_КЛИЕНТА\\СПИСОК ЗАЯВОК";
PRIVATE CONST REGKEY_CLAIMTREEDATE   = "RS-LOANS\\WEB\\ДЕРЕВО_ПРОДУКТОВ_КЛИЕНТА\\ДАТА АРХИВА ЗАЯВОК";

PRIVATE CONST SetRegErrorMessage = "Ошибка сохранения значения ключа реестра ";

CLASS CLnsSettings()
    VAR ProductTreeMode: integer = 0;            // Вид дерева продуктов клиента
    VAR ClaimTreeMode  : integer = 0;            // Состав дерева заявок
    VAR ClaimTreeDate  : DateTime = Date(0,0,0); // Дата архива заявок
END;

MACRO Lns_SaveSettings(LnsSettings)
    var result = WebResponseBuilder();
    if (LnsSettings != null)
        if (not SetRegistryValue(REGKEY_PRODUCTTREEMODE, Int(LnsSettings.ProductTreeMode)))
            result.AddErrorEx(1, MessageSeverity.RuntimeError, SetRegErrorMessage + REGKEY_PRODUCTTREEMODE);
        end;
        if (not SetRegistryValue(REGKEY_CLAIMTREEMODE, Int(LnsSettings.ClaimTreeMode)))
            result.AddErrorEx(1, MessageSeverity.RuntimeError, SetRegErrorMessage + REGKEY_CLAIMTREEMODE)
        end;
        if (not SetRegistryValue(REGKEY_CLAIMTREEDATE, String(Date(LnsSettings.ClaimTreeDate):f)))
            result.AddErrorEx(1, MessageSeverity.RuntimeError, SetRegErrorMessage + REGKEY_CLAIMTREEDATE)
        end;
    end;
    return result.Result;
END;