/*
$Name:          appl7ReportView.mac
$Module:        Регламентируемая отчетность
$Description:   Класс представления отчетной формы для приложения 7.
*/

import rcbimport;
import balanceAttribute;
import balanceReportParameters;

private CONST notError     = 9;  //для TErrorMessage()
private CONST notErrorSpod = 11; //для TErrorMessage()

/**
 * Класс представления отчетной формы.
 */
class (RcbReportView) TApplication7ReportView(withSpod : Bool, chapter : Integer, needCheck : Bool, applicationNumber)
    var m_tableReport;
    var reportWidth;
    var m_planNumber;
    private var m_withSpod:     bool = false;
    private var m_isPeriodYear: bool = false;
    private var m_isPrintSpod:  bool = false;

    /**
     * Настройка вида печати. (0 - все, 1 - по РПС, 2 - ненулевые)
     */
    private const PRINT_REGPATH = "REPTREG/REP_GROUPS/BALANCE_ACCOUNTS/ПЕЧАТЬ ФОРМЫ 101";

    /**
     * Все счета.
     */
    private const PRINT_KIND_ALL     = 0;

    /**
     * Счета по РПС.
     */
    private const PRINT_KIND_BWP     = 1;

    /**
     * Ненулевые счета.
     */
    private const PRINT_KIND_NOZ     = 2;

    /**
     * Ненулевые нормализованные.
     */
    private const PRINT_KIND_NOZ_NORMALIZED  = 3;

    /**
     * Вид печати счетов. (0 - все, 1 - по РПС, 2 - ненулевые)
     */
    private var   m_isPrintKind = PRINT_KIND_ALL;

    /**
     * Точность для главы Д.
     */
    private var m_precisionChapter5   : Integer;

    /**
     * Номер текущей главы.
     */
    private var m_chapter: Integer;

    /**
     * Корректна ли настройка реестра REPTREG/REP_GROUPS/BALANCE_ACCOUNTS/ПЕЧАТЬ ФОРМЫ 101
     */
    private var m_isCorrectly : Bool = true;
    private var m_printKind;

    private var m_applicationNumber : String;

    /**
     * Получить вид печати отчета.
     * @return Значение настройки. (0 - все, 1 - по РПС, 2 - ненулевые)
     */
    private macro getPrintKind()
        var val_type = V_UNDEF,
            err_code = 0,
            value    = PRINT_KIND_ALL;

        val_type = GetRegistryValue( PRINT_REGPATH, V_INTEGER, value, err_code );

        if ( (err_code != 0) OR (val_type != V_INTEGER) )
            MsgBox( "Ошибка чтения настройки|", PRINT_REGPATH );
            RepErrorsQueue().add(0, String("Ошибка чтения настройки|", PRINT_REGPATH));
            Exit(1);
        else
            m_printKind = value;
            if ((value < PRINT_KIND_ALL) OR (value > PRINT_KIND_NOZ_NORMALIZED))
                m_isCorrectly = false;
                value = PRINT_KIND_ALL;
            end;
        end;

        return value;
    end;

    private macro constructorTApplication7ReportView(withSpod, chapter, needCheck, applicationNumber)
        var viewName = "";

        defaultParm(applicationNumber, "7");

        if (withSpod)
            viewName = "a7s";
        else
            viewName = "a7" + chapter;
        end;

        initRcbReportView("",
                          viewName,
                          RCB_PK_PERIOD,
                          DATE_IN_PERIOD_FORMAT
                         );

        m_applicationNumber = applicationNumber;

        if ((valType(needCheck) == V_UNDEF) or needCheck)
            var currentReport = balanceGlobal().getRcbReport();
            var errorNotData;

            //определяем истинное значение настройки реестра REPTREG/REP_GROUPS/BALANCE_ACCOUNTS/ПЕЧАТЬ ФОРМЫ 101 (m_printKind)
            getPrintKind();

            //подготовка протокола расчета
            objectFactoryInstance.createCalculateProtocolView().setProtocolOutput(false);
            objectFactoryInstance.createCalculateProtocolView().printHead();

            //проверяем рассчитанность необходимых данных
            if (withSpod)
                errorNotData = notErrorSpod;                                                                       //сообщение 11
                //проверяем рассчитанность переменной "БАЛАНС"
                if (not TBaseBalanceAttribute("БАЛАНС", currentReport).isBalanceCalculated(0, currentReport.dimension))
                    errorNotData = 5;                                                                              //сообщение 5
                end;

                //проверяем рассчитанность переменной "СПОД"
                if (not TBaseBalanceAttribute("СПОД", currentReport).isSpodCalculated(currentReport.dimension))
                    errorNotData = ternary(errorNotData == notErrorSpod, 6, 7 + ternary(m_isCorrectly, 0, 10));    //сообщение 6, 7 или 17
                end;

                if (errorNotData == notErrorSpod)
                    errorNotData = errorNotData + ternary(m_isCorrectly, 0, 10);                                   //сообщение 21
                end;
            else
                errorNotData = notError;
                //проверяем рассчитанность переменной "БАЛАНС"
                if (not TBaseBalanceAttribute("БАЛАНС", currentReport).isBalanceCalculated(m_chapter, currentReport.dimension))
                    errorNotData = 4;                                                                              //сообщение 4
                end;
                errorNotData = errorNotData + ternary(m_isCorrectly, 0, 10);                                       //сообщение 4, 9, 14 или 19
            end;

            if ((errorNotData != 9) and (errorNotData != 11) and (errorNotData != 19) and (errorNotData != 21))
                objectFactoryInstance.createCalculateProtocolView().printLine(TErrorMessage(errorNotData, currentReport.dimension, currentReport.context.period.beginDate, currentReport.context.period.endDate, m_printKind, m_applicationNumber).getMessage());

                objectFactoryInstance.createCalculateProtocolView().resetProtocolOutput();
                objectFactoryInstance.createCalculateProtocolView().show();

                УстановитьФлагВозврата(STOP_PROC_FLG);
                exit(1);
            else
                objectFactoryInstance.createCalculateProtocolView().printLine(TErrorMessage(errorNotData, currentReport.dimension, currentReport.context.period.beginDate, currentReport.context.period.endDate, m_printKind, m_applicationNumber).getMessage());
                objectFactoryInstance.createCalculateProtocolView().resetProtocolOutput();
                objectFactoryInstance.createCalculateProtocolView().show();
            end;
        end;

        m_tableReport = CTableReport( 0, FALSE, TRUE );

        m_tableReport.addColumn( "", 5  );    /* Номер счета первого порядка */
        m_tableReport.addColumn( "", 5  );    /* Номер счета второго порядка */
        m_tableReport.addColumn( "", 25 );    /* Наименование счетов баланса */
        m_tableReport.addColumn( "", 18, AL_RIGHT );    /* Входящие остатки            */
        m_tableReport.addColumn( "", 18, AL_RIGHT );    /* Обороты по дебету в рублях  */
        m_tableReport.addColumn( "", 18, AL_RIGHT );    /* Обороты по дебету в валюте  */
        m_tableReport.addColumn( "", 18, AL_RIGHT );    /* Обороты по дебету итого     */
        m_tableReport.addColumn( "", 18, AL_RIGHT );    /* Обороты по кредиту в рублях */
        m_tableReport.addColumn( "", 18, AL_RIGHT );    /* Обороты по кредиту в валюте */
        m_tableReport.addColumn( "", 18, AL_RIGHT );    /* Обороты по кредиту итого    */
        m_tableReport.addColumn( "", 20, AL_RIGHT );    /* Исходящие остатки           */

        reportWidth = m_tableReport.getSumLen();
        setReportWidth(reportWidth);

        m_planNumber  = balanceParameters().getPlanNumber();

        m_isPeriodYear = rcbApplication().currentReport.context.period.kind == RCB_PK_YEAR;
        m_isPrintSpod  = withSpod AND (NOT m_isPeriodYear);
        m_withSpod     = withSpod;
        m_isPrintKind  = getPrintKind();
        m_chapter      = chapter;

        m_precisionChapter5   = balanceParameters().getPrecisionChapter5();
    end;

    /**
     * Указать точность для значения.
     * Количество знаков после запятой считывается из настройки реестра для главы Д.
     * @param value Значение, для которого применяем точность.
     * @return Если глава Д, то значение с изменненной точность, иначе точность не меняется.
     */
    private macro changePrecision(value)
        if (valType(value) == V_UNDEF)
            value = 0;
        end;

        if ((m_chapter == 5) AND (value != ""))
            return execExp("String(value" + ":0:" + m_precisionChapter5 + ")");
        else
            return value;
        end;
    end;

    macro printTableHeader()
    end;

    macro printTableBottom()
    end;

    macro printFreeString(str)
        var i = strlen(str);
        while (i < reportWidth)
            str = str + " ";
            i = i + 1;
        end;
        m_tableReport.printFreeString(str, true);
    end;

    macro printNamesZone()
    end;

    macro printLendingAgencyCodeZone()
        /*_____________________________________________________________________________________*/
        var bankName = TArray();
        var i;
        /*_____________________________________________________________________________________*/


        [#]( strAlign( "                              Приложение 7 ", ReportWidth, STR_ALIGN_RIGHT ) );
        [#]( strAlign( " к Правилам ведения бухгалтерского учета   ", ReportWidth, STR_ALIGN_RIGHT ) );
        [#]( strAlign( " в кредитных организациях, расположенных   ", ReportWidth, STR_ALIGN_RIGHT ) );
        [#]( strAlign( " на территории Российской Федерации        ", ReportWidth, STR_ALIGN_RIGHT ) );
        [ ];
        [#]( strAlign( " (Приложение к Положению Банка России      ", ReportWidth, STR_ALIGN_RIGHT ) );
        [#]( strAlign( " от 16 июля 2012 года N 385-П              ", ReportWidth, STR_ALIGN_RIGHT ) );
        [#]( strAlign( " \"О правилах ведения бухгалтерского учета ", ReportWidth, STR_ALIGN_RIGHT ) );
        [#]( strAlign( " в кредитных организациях, расположенных   ", ReportWidth, STR_ALIGN_RIGHT ) );
        [#]( strAlign( " на территории Российской Федерации\")     ", ReportWidth, STR_ALIGN_RIGHT ) );
        [ ];

        /*________________________________________________________________________________________*/

        [ ];
        /*________________________________________________________________________________________*/
        var periodName = RcbReportView("", "", RcbArray().initialize(RCB_PK_DAY, RCB_PK_MONTH, RCB_PK_QUARTER, RCB_PK_HALFYEAR, RCB_PK_PERIOD), DATE_IN_PERIOD_FORMAT).getNamesZone().getPeriodName();

        [#]( strAlign(        "Оборотная ведомость", ReportWidth, STR_ALIGN_CENTER ) );
        [#]( strAlign( "по счетам кредитной организации", ReportWidth, STR_ALIGN_CENTER ) );
        [#]( strAlign( periodName, ReportWidth, STR_ALIGN_CENTER ) );
    end;

    macro printSignatureZone()
        [   #                       _____________________  #                                                 #                       _____________________  #  ]( {Name_Boss}:l, {FIO_Boss}, {Name_Book}:l, {FIO_Book} );
        [                                                     ];
        [   #                                                 ]( trim( string( {curdate}:m ) ) );
        [─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────];
        [   Примечание: по балансовым счетам, не имеющим признака ( А или П ), сальдо   ];
        [               по которым на конец рабочего дня должно быть равно нулю,        ];
        [               обороты в ежедневной оборотной ведомости показываются в разделе ];
        [               "Актив" по дебету и кредиту в равных суммах.                    ];
    end;

    macro printChapterHeader(chapterName : String)
        var currentBeginPos = 1;
        var currentEndPos;
        var limit = StrLen(chapterName);
        var correction = 1;

        while (currentBeginPos <= limit)
            currentEndPos = StrBrk(substr(chapterName, currentBeginPos), "\n");
            if (currentEndPos == 0)
                currentEndPos = StrLen(substr(chapterName, currentBeginPos));
                correction = 0;
            end;
            PrintLn(strAlign(substr(chapterName, currentBeginPos, currentEndPos - correction), ReportWidth, STR_ALIGN_CENTER));
            currentBeginPos = currentBeginPos + currentEndPos;
        end;

        [┌─────────────────┬───────────────────────────┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┐];
        [│   Номер счета   │       Наименование        │  Входящие остатки  │                                                 Обороты за отчетный период                                                  │ Исходящие остатки  │];
        [│ первого(второго)│    разделов и счетов      │  на отчетную дату  ├──────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────┤  на отчетную дату  │];
        [│     порядка     │         баланса           │    (в рублях,      │                          по дебету                           │                           по кредиту                         │    (в рублях,      │];
        [├────────┬────────┤                           │иностранной валюте  ├────────────────────┬────────────────────┬────────────────────┼────────────────────┬────────────────────┬────────────────────┤иностранной валюте  │];
        [│первого │второго │                           │   и драгоценных    │      в рублях      │ иностранная валюта │        итого       │      в рублях      │ иностранная валюта │        итого       │   и драгоценных    │];
        [│порядка │порядка │                           │     металлах       │                    │   и драгоценные    │                    │                    │   и драгоценные    │                    │     металлах       │];
        [│        │        │                           │    в рублевом      │                    │      металлы в     │                    │                    │      металлы в     │                    │    в рублевом      │];
        [│        │        │                           │    эквиваленте)    │                    │рублевом эквиваленте│                    │                    │рублевом эквиваленте│                    │    эквиваленте)    │];
        [├────────┼────────┼───────────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤];
        [│    1   │   2    │            3              │          4         │          5         │          6         │          7         │          8         │          9         │         10         │         11         │];
        [├────────┴────────┴───────────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┤];
    end;

    macro printSeparator()
        m_tableReport.printFreeString("├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤");
    end;

    macro printTableString(balanceOrder, balance, nameBalance, _inItog, _dtRub, _dtCur, _dtItog, _ktRub, _ktCur, _ktItog, _outItog, _isPrintSpod, _nameSpod, _dSpodRub, _dSpodCur, _dSpodItog, _kSpodRub, _kSpodCur, _kSpodItog)
        var balance1, balance2;

        var inItog, dtRub, dtCur, dtItog, ktRub, ktCur, ktItog, outItog, isPrintSpod, nameSpod, dSpodRub, dSpodCur, dSpodItog, kSpodRub, kSpodCur, kSpodItog;

        isPrintSpod = _isPrintSpod;
        nameSpod    = _nameSpod;

        if (m_chapter == 5)
            dtRub    = "";
            dtCur    = "";
            ktRub    = "";
            ktCur    = "";
            dSpodRub = "";
            dSpodCur = "";
            kSpodRub = "";
            kSpodCur = "";
        else
            dtRub    = changePrecision(_dtRub  );
            dtCur    = changePrecision(_dtCur  );
            ktRub    = changePrecision(_ktRub  );
            ktCur    = changePrecision(_ktCur  );
            dSpodRub = changePrecision(_dSpodRub );
            dSpodCur = changePrecision(_dSpodCur );
            kSpodRub = changePrecision(_kSpodRub );
            kSpodCur = changePrecision(_kSpodCur );
        end;

        inItog    = changePrecision(_inItog );
        dtItog    = changePrecision(_dtItog );
        ktItog    = changePrecision(_ktItog );
        outItog   = changePrecision(_outItog);
        dSpodItog = changePrecision(_dSpodItog);
        kSpodItog = changePrecision(_kSpodItog);

        if (balanceOrder == 1)
            printFreeString("ИТОГО по счету первого порядка:");
            balance1 = balance;
            balance2 = "";
        else
            printFreeString("ИТОГО по счету второго порядка:");
            balance1 = "";
            balance2 = balance;
        end;

        m_tableReport.PrintStringTransferByWord(balance1, balance2, nameBalance, inItog, dtRub, dtCur, dtItog, ktRub, ktCur, ktItog, outItog);

        if (isPrintSpod)
            if ((dSpodRub != 0) OR (dSpodCur != 0) OR (dSpodItog != 0)  OR (kSpodRub != 0) OR (kSpodCur != 0) OR (kSpodItog != 0))
                printFreeString(nameSpod);
                m_tableReport.printString("", "", "", "", dSpodRub, dSpodCur, dSpodItog, kSpodRub, kSpodCur, kSpodItog, "");
            end;
        end;
        m_tableReport.PrintSeparator(true);
    end;

    macro printItog(nameItog, _inItog, _dtRub, _dtCur, _dtItog, _ktRub, _ktCur, _ktItog, _outItog, _isPrintSpod, _nameSpod, _dSpodRub, _dSpodCur, _dSpodItog, _kSpodRub, _kSpodCur, _kSpodItog)

        var inItog, dtRub, dtCur, dtItog, ktRub, ktCur, ktItog, outItog, isPrintSpod, nameSpod, dSpodRub, dSpodCur, dSpodItog, kSpodRub, kSpodCur, kSpodItog;

        isPrintSpod = _isPrintSpod;
        nameSpod    = _nameSpod;

        if (m_chapter == 5)
            dtRub    = "";
            dtCur    = "";
            ktRub    = "";
            ktCur    = "";
            dSpodRub = "";
            dSpodCur = "";
            kSpodRub = "";
            kSpodCur = "";
        else
            dtRub    = changePrecision(_dtRub  );
            dtCur    = changePrecision(_dtCur  );
            ktRub    = changePrecision(_ktRub  );
            ktCur    = changePrecision(_ktCur  );
            dSpodRub = changePrecision(_dSpodRub );
            dSpodCur = changePrecision(_dSpodCur );
            kSpodRub = changePrecision(_kSpodRub );
            kSpodCur = changePrecision(_kSpodCur );
        end;

        inItog    = changePrecision(_inItog );
        dtItog    = changePrecision(_dtItog );
        ktItog    = changePrecision(_ktItog );
        outItog   = changePrecision(_outItog);
        dSpodItog = changePrecision(_dSpodItog);
        kSpodItog = changePrecision(_kSpodItog);

        printFreeString(nameItog);

        m_tableReport.printString("", "", "", inItog, dtRub, dtCur, dtItog, ktRub, ktCur, ktItog, outItog);

        if (isPrintSpod)
            if ((dSpodRub != 0) OR (dSpodCur != 0) OR (dSpodItog != 0)  OR (kSpodRub != 0) OR (kSpodCur != 0) OR (kSpodItog != 0))
                printFreeString(nameSpod);
                m_tableReport.printString("", "", "", "", dSpodRub, dSpodCur, dSpodItog, kSpodRub, kSpodCur, kSpodItog, "");
            end;
        end;
    end;

    macro printKindHeader(kind)
        printFreeString(strAlign(kind, reportWidth, STR_ALIGN_CENTER));
    end;

    macro getValue(value, chapter)
        if (value == NULL)
            return 0;
        end;

        return value.exact;
    end;

    private macro GetPartitionName(chapter, partition)
        var query = " SELECT T_NAME_PART   "  +
                    "   FROM DPARTBLNC_DBT "  +
                    "  WHERE T_CHAPTER  =  " + chapter +
                    "    AND T_INUMPLAN =  " + m_planNumber +
                    "    AND T_PART     =  " + partition;

        var dataset = TRsbDataSet(query);

        if (dataset.moveNext() == true)
            return dataset.name_part;
        else
            return "";
        end;
    end;

    macro printChapter(chapter, chapterName)
        m_chapter = chapter;
        if (m_chapter != 1)
            m_isPrintSpod = false;
        end;

        var av = TBalanceAttribute("БАЛАНС");
        var currentPart;
        var sIn, sD, sDr, sDv, sK, sKr, sKv, sOut;
        var s9999_In, s9999_D, s9999_Dr, s9999_Dv, s9999_K, s9999_Kr, s9999_Kv, s9999_Out;
        var sPartIn, sPartD, sPartDr, sPartDv, sPartK, sPartKr, sPartKv, sPartOut;
        var sKindIn, sKindD, sKindDr, sKindDv, sKindK, sKindKr, sKindKv, sKindOut;
        var curIn, curD, curDr, curDv, curK, curKr, curKv, curOut;
        var balanceLevel1RestIn, balanceLevel1RestOut;
        var balanceLevel1Debit, balanceLevel1DebitRouble, balanceLevel1DebitForeign;
        var balanceLevel1Credit, balanceLevel1CreditRouble, balanceLevel1CreditForeign;
        var balanceLevel1DebitSpod, balanceLevel1DebitRoubleSpod, balanceLevel1DebitForeignSpod;
        var balanceLevel1CreditSpod, balanceLevel1CreditRoubleSpod, balanceLevel1CreditForeignSpod;
        var balanceOrder;
        var prevBalance = "00000";

        var spod = TBalanceAttribute("СПОД");
        var spodValue;
        var spodD       : Money, spodDr       : Money, spodDv       : Money,  /* note: СПОД по БС 1 порядка */
            spodK       : Money, spodKr       : Money, spodKv       : Money,
            spodIn      : Money;

        var sSpodPartD  : Money, sSpodPartDr  : Money, sSpodPartDv  : Money,  /* note: СПОД итоги по разделу */
            sSpodPartK  : Money, sSpodPartKr  : Money, sSpodPartKv  : Money;

        var sSpodD      : Money, sSpodDr      : Money, sSpodDv      : Money,  /* note: СПОД итоги по активу/пассиву */
            sSpodK      : Money, sSpodKr      : Money, sSpodKv      : Money;

        var sSpodTotalD : Money, sSpodTotalDr : Money, sSpodTotalDv : Money,  /* note: СПОД итоги по главе */
            sSpodTotalK : Money, sSpodTotalKr : Money, sSpodTotalKv : Money;

        /**
         * Наименование балансового счета 99996
         */
        var nameBalance99996: String = "";
        /**
         * Наименование балансового счета 99997
         */
        var nameBalance99997: String = "";

        printChapterHeader(chapterName);

        if (m_isPrintKind != PRINT_KIND_NOZ_NORMALIZED)
            av.createBalanceIterator(chapter, KIND_ACTIVE, (chapter != 5), m_isPrintKind == PRINT_KIND_NOZ, m_isPrintKind == PRINT_KIND_BWP);
        else
            av.createBalanceIterator(chapter, KIND_ACTIVE, false, true, false, false);
        end;
        av.sortIteratorByBalance();

        sIn = 0; sD = 0; sDr = 0; sDv = 0; sK = 0; sKr = 0; sKv = 0; sOut = 0;
        sKindIn = 0; sKindD = 0; sKindDr = 0; sKindDv = 0; sKindK = 0; sKindKr = 0; sKindKv = 0; sKindOut = 0;
        sPartIn = 0; sPartD = 0; sPartDr = 0; sPartDv = 0; sPartK = 0; sPartKr = 0; sPartKv = 0; sPartOut = 0;
        currentPart = 0;

        spodD       = 0.0; spodDr       = 0.0; spodDv       = 0.0; spodK       = 0.0; spodKr       = 0.0; spodKv       = 0.0;
        sSpodPartD  = 0.0; sSpodPartDr  = 0.0; sSpodPartDv  = 0.0; sSpodPartK  = 0.0; sSpodPartKr  = 0.0; sSpodPartKv  = 0.0;
        sSpodD      = 0.0; sSpodDr      = 0.0; sSpodDv      = 0.0; sSpodK      = 0.0; sSpodKr      = 0.0; sSpodKv      = 0.0;
        sSpodTotalD = 0.0; sSpodTotalDr = 0.0; sSpodTotalDv = 0.0; sSpodTotalK = 0.0; sSpodTotalKr = 0.0; sSpodTotalKv = 0.0;
        spodIn      = 0.0;

        balanceLevel1RestIn     = balanceLevel1RestOut = $0;
        balanceLevel1Debit      = balanceLevel1DebitRouble      = balanceLevel1DebitForeign      = $0;
        balanceLevel1Credit     = balanceLevel1CreditRouble     = balanceLevel1CreditForeign     = $0;
        balanceLevel1DebitSpod  = balanceLevel1DebitRoubleSpod  = balanceLevel1DebitForeignSpod  = $0;
        balanceLevel1CreditSpod = balanceLevel1CreditRoubleSpod = balanceLevel1CreditForeignSpod = $0;

        printKindHeader("Актив");
        while (av.next())

            /* не печатать счета ОВП */
            if (index(av.getBalance(), "ОВП") > 0)
                continue;
            end;

            if (av.getBalance == "99996")
                nameBalance99996 = av.getBalanceName();
            end;

            curIn  = getValue(av.getInRestActive(), chapter);
            curDr  = getValue(av.getDebetNatCur(), chapter);
            curDv  = getValue(av.getDebetCur(), chapter);
            curD   = getValue(av.getDebet(), chapter);
            curKr  = getValue(av.getCreditNatCur(), chapter);
            curKv  = getValue(av.getCreditCur(), chapter);
            curK   = getValue(av.getCredit(), chapter);
            curOut = getValue(av.getOutRestActive(), chapter);

            balanceOrder = ternary(strLen(av.getBalance()) == 3, 1, 2);

            spodValue = spod.getBalanceAttribute(NULL, av.getBalance(), false);

            if ((m_chapter != 1) AND (m_withSpod))
                spodIn = 0.0;
                spodDr = 0.0;
                spodDv = 0.0;
                spodD  = 0.0;
                spodKr = 0.0;
                spodKv = 0.0;
                spodK  = 0.0;
                sSpodPartD = 0.0;
                sSpodPartDr = 0.0;
                sSpodPartDv = 0.0;
                sSpodPartK = 0.0;
                sSpodPartKr = 0.0;
                sSpodPartKv = 0.0;
                sSpodD = 0.0;
                sSpodDr = 0.0;
                sSpodDv = 0.0;
                sSpodK = 0.0;
                sSpodKr = 0.0;
                sSpodKv = 0.0;
            else
                if (spodValue != NULL)
                    if (balanceOrder == 2)
                        if ((m_isPeriodYear) AND (m_withSpod))
                            spodIn = spodValue.fieldValue("currYearDebetRouble" ).exact  + spodValue.fieldValue("currYearDebetCover" ).exact -
                                     spodValue.fieldValue("currYearCreditRouble" ).exact - spodValue.fieldValue("currYearCreditCover" ).exact;

                            curIn = curIn + spodIn;

                            curDr = curDr - spodValue.fieldValue("currYearDebetRouble" ).exact;
                            curDv = curDv - spodValue.fieldValue("currYearDebetCover"  ).exact;
                            curD  = curD  - spodValue.fieldValue("currYearDebetRouble" ).exact - spodValue.fieldValue("currYearDebetCover").exact;
                            curKr = curKr - spodValue.fieldValue("currYearCreditRouble").exact;
                            curKv = curKv - spodValue.fieldValue("currYearCreditCover" ).exact;
                            curK  = curK  - spodValue.fieldValue("currYearCreditRouble").exact - spodValue.fieldValue("currYearCreditCover").exact;
                        else
                            spodDr = spodValue.fieldValue("nextYearDebetRouble" ).exact;
                            spodDv = spodValue.fieldValue("nextYearDebetCover"  ).exact;
                            spodD  = spodValue.fieldValue("nextYearDebetRouble" ).exact + spodValue.fieldValue("nextYearDebetCover").exact;
                            spodKr = spodValue.fieldValue("nextYearCreditRouble").exact;
                            spodKv = spodValue.fieldValue("nextYearCreditCover" ).exact;
                            spodK  = spodValue.fieldValue("nextYearCreditRouble").exact + spodValue.fieldValue("nextYearCreditCover").exact;

                            balanceLevel1DebitSpod        = balanceLevel1DebitSpod        + spodD;
                            balanceLevel1DebitRoubleSpod  = balanceLevel1DebitRoubleSpod  + spodDr;
                            balanceLevel1DebitForeignSpod = balanceLevel1DebitForeignSpod + spodDv;

                            balanceLevel1CreditSpod        = balanceLevel1CreditSpod        + spodK;
                            balanceLevel1CreditRoubleSpod  = balanceLevel1CreditRoubleSpod  + spodKr;
                            balanceLevel1CreditForeignSpod = balanceLevel1CreditForeignSpod + spodKv;
                        end;
                    end;
                else
                    spodIn = 0;
                    spodDr = 0;
                    spodDv = 0;
                    spodD  = 0;
                    spodKr = 0;
                    spodKv = 0;
                    spodK  = 0;
                end;
            end;

            if ((av.getPart().exact != currentPart) and (balanceOrder == 2))
                if (currentPart > 0)
                    printItog("ИТОГО по разделу " + currentPart, sPartIn, sPartDr, sPartDv,  sPartD, sPartKr, sPartKv, sPartK, sPartOut,
                                m_isPrintSpod, "В том числе СПОД ", sSpodPartDr, sSpodPartDv,  sSpodPartD, sSpodPartKr, sSpodPartKv, sSpodPartK);

                m_tableReport.PrintSeparator(true);
                end;

                if (av.getBalance() == "99998")
                    s9999_In  = curIn;
                    s9999_D   = curD;
                    s9999_Dr  = curDr;
                    s9999_Dv  = curDv;
                    s9999_K   = curK;
                    s9999_Kr  = curKr;
                    s9999_Kv  = curKv;
                    s9999_Out = curOut;
                end;
                currentPart = av.getPart().exact;
                printFreeString("                 РАЗДЕЛ " + currentPart + ". " + GetPartitionName(chapter, currentPart));
                printSeparator();
                sPartIn = 0; sPartD = 0; sPartDr = 0; sPartDv = 0; sPartK = 0; sPartKr = 0; sPartKv = 0; sPartOut = 0;
                sSpodPartDr = 0; sSpodPartDv = 0; sSpodPartD = 0; sSpodPartKr = 0; sSpodPartKv = 0; sSpodPartK = 0;
            end;

            if (balanceOrder == 2)
                balanceLevel1RestIn = balanceLevel1RestIn + curIn;
                balanceLevel1Debit = balanceLevel1Debit + curD;
                balanceLevel1DebitRouble = balanceLevel1DebitRouble + curDr;
                balanceLevel1DebitForeign = balanceLevel1DebitForeign + curDv;

                balanceLevel1Credit = balanceLevel1Credit + curK;
                balanceLevel1CreditRouble = balanceLevel1CreditRouble + curKr;
                balanceLevel1CreditForeign = balanceLevel1CreditForeign + curKv;
                balanceLevel1RestOut = balanceLevel1RestOut + curOut;
            end;

            /* не печатать итого по счету 999 первого порядка  */
            if (((balanceOrder != 1) and (av.getBalance() != "999")) or (av.getBalance() != "999"))
                if (balanceOrder == 1)
                    printTableString(balanceOrder, av.getBalance(), av.getBalanceName(),
                                     balanceLevel1RestIn,
                                     balanceLevel1DebitRouble,
                                     balanceLevel1DebitForeign,
                                     balanceLevel1Debit,
                                     balanceLevel1CreditRouble,
                                     balanceLevel1CreditForeign,
                                     balanceLevel1Credit,
                                     balanceLevel1RestOut,
                                     m_isPrintSpod, "В том числе СПОД ",
                                     balanceLevel1DebitRoubleSpod,
                                     balanceLevel1DebitForeignSpod,
                                     balanceLevel1DebitSpod,
                                     balanceLevel1CreditRoubleSpod,
                                     balanceLevel1CreditForeignSpod,
                                     balanceLevel1CreditSpod
                                    );
                elif (av.getBalance() != "99996")
                    if ((spodDr != 0) OR (spodDv != 0) OR ( spodD != 0) OR (spodKr != 0) OR (spodKv != 0) OR (spodK != 0))
                        printTableString(balanceOrder, av.getBalance(), av.getBalanceName(), curIn, curDr, curDv, curD, curKr, curKv, curK, curOut,
                                         m_isPrintSpod, "В том числе СПОД ", spodDr, spodDv,  spodD, spodKr, spodKv, spodK);
                    else
                        printTableString(balanceOrder, av.getBalance(), av.getBalanceName(), curIn, curDr, curDv, curD, curKr, curKv, curK, curOut, false);
                    end;
                end;
            end;

            if (av.getBalance() == "99996")
                s9999_In  = curIn;
                s9999_D   = curD;
                s9999_Dr  = curDr;
                s9999_Dv  = curDv;
                s9999_K   = curK;
                s9999_Kr  = curKr;
                s9999_Kv  = curKv;
                s9999_Out = curOut;
            end;

            if (balanceOrder == 2)
                sIn  = sIn  + curIn;
                sDr  = sDr  + curDr;
                sDv  = sDv  + curDv;
                sD   = sD   + curD;
                sKr  = sKr  + curKr;
                sKv  = sKv  + curKv;
                sK   = sK   + curK;
                sOut = sOut + curOut;

                sKindIn  = sKindIn  + curIn;
                sKindDr  = sKindDr  + curDr;
                sKindDv  = sKindDv  + curDv;
                sKindD   = sKindD   + curD;
                sKindKr  = sKindKr  + curKr;
                sKindKv  = sKindKv  + curKv;
                sKindK   = sKindK   + curK;
                sKindOut = sKindOut + curOut;

                sPartIn  = sPartIn  + curIn;
                sPartDr  = sPartDr  + curDr;
                sPartDv  = sPartDv  + curDv;
                sPartD   = sPartD   + curD;
                sPartKr  = sPartKr  + curKr;
                sPartKv  = sPartKv  + curKv;
                sPartK   = sPartK   + curK;
                sPartOut = sPartOut + curOut;

                if (spodValue != NULL)

                    sSpodPartDr = sSpodPartDr + spodDr;
                    sSpodPartDv = sSpodPartDv + spodDv;
                    sSpodPartD  = sSpodPartD  + spodD;
                    sSpodPartKr = sSpodPartKr + spodKr;
                    sSpodPartKv = sSpodPartKv + spodKv;
                    sSpodPartK  = sSpodPartK  + spodK;

                    sSpodDr = sSpodDr + spodDr;
                    sSpodDv = sSpodDv + spodDv;
                    sSpodD  = sSpodD  + spodD;
                    sSpodKr = sSpodKr + spodKr;
                    sSpodKv = sSpodKv + spodKv;
                    sSpodK  = sSpodK  + spodK;
                end;

                prevBalance = av.getBalance();
            else
                balanceLevel1RestIn     = balanceLevel1RestOut = $0;
                balanceLevel1Debit      = balanceLevel1DebitRouble      = balanceLevel1DebitForeign      = $0;
                balanceLevel1Credit     = balanceLevel1CreditRouble     = balanceLevel1CreditForeign     = $0;
                balanceLevel1DebitSpod  = balanceLevel1DebitRoubleSpod  = balanceLevel1DebitForeignSpod  = $0;
                balanceLevel1CreditSpod = balanceLevel1CreditRoubleSpod = balanceLevel1CreditForeignSpod = $0;
            end;
        end;

        if (currentPart > 0)
            printItog("ИТОГО по разделу " + currentPart, sPartIn, sPartDr, sPartDv,  sPartD, sPartKr, sPartKv, sPartK, sPartOut,
                      m_isPrintSpod, "В том числе СПОД ", sSpodPartDr, sSpodPartDv,  sSpodPartD, sSpodPartKr, sSpodPartKv, sSpodPartK);

            m_tableReport.PrintSeparator(true);
        end;

        if (chapter == 4)
            printTableString(2, "99996", nameBalance99996, s9999_In, s9999_Dr, s9999_Dv, s9999_D, s9999_Kr, s9999_Kv, s9999_K, s9999_Out, false);
            m_tableReport.PrintSeparator(true);
        end;

        printItog("ИТОГО по активу: ", sIn, sDr, sDv,  sD, sKr, sKv, sK, sOut,
                  m_isPrintSpod, "В том числе СПОД ", sSpodDr, sSpodDv,  sSpodD, sSpodKr, sSpodKv, sSpodK);
        m_tableReport.PrintSeparator(true);
        sSpodTotalDr = sSpodDr;
        sSpodTotalDv = sSpodDv;
        sSpodTotalD  = sSpodD;
        sSpodTotalKr = sSpodKr;
        sSpodTotalKv = sSpodKv;
        sSpodTotalK  = sSpodK;


        if (m_isPrintKind != PRINT_KIND_NOZ_NORMALIZED)
            av.createBalanceIterator(chapter, KIND_PASSIVE, (chapter != 5), m_isPrintKind == PRINT_KIND_NOZ, m_isPrintKind == PRINT_KIND_BWP);
        else
            av.createBalanceIterator(chapter, KIND_PASSIVE, false, true, false, false);
        end;
        av.sortIteratorByBalance();

        sKindIn = 0; sKindD = 0; sKindDr = 0; sKindDv = 0; sKindK = 0; sKindKr = 0; sKindKv = 0; sKindOut = 0;
        sPartIn = 0; sPartD = 0; sPartDr = 0; sPartDv = 0; sPartK = 0; sPartKr = 0; sPartKv = 0; sPartOut = 0;
        currentPart = 0;
        spodD      = 0.0; spodDr      = 0.0; spodDv      = 0.0; spodK      = 0.0; spodKr      = 0.0; spodKv      = 0.0;
        sSpodPartD = 0.0; sSpodPartDr = 0.0; sSpodPartDv = 0.0; sSpodPartK = 0.0; sSpodPartKr = 0.0; sSpodPartKv = 0.0;
        sSpodD     = 0.0; sSpodDr     = 0.0; sSpodDv     = 0.0; sSpodK     = 0.0; sSpodKr     = 0.0; sSpodKv     = 0.0;

        balanceLevel1RestIn     = balanceLevel1RestOut = $0;
        balanceLevel1Debit = balanceLevel1DebitRouble = balanceLevel1DebitForeign = $0;
        balanceLevel1Credit = balanceLevel1CreditRouble = balanceLevel1CreditForeign = $0;
        balanceLevel1DebitSpod = balanceLevel1DebitRoubleSpod = balanceLevel1DebitForeignSpod = $0;
        balanceLevel1CreditSpod = balanceLevel1CreditRoubleSpod = balanceLevel1CreditForeignSpod = $0;

        spod = TBalanceAttribute("СПОД");
        printKindHeader("Пассив");
        while (av.next())

            /* не печатать счета ОВП */
            if (index(av.getBalance(), "ОВП") > 0)
                continue;
            end;

            if (av.getBalance == "99997")
                nameBalance99997 = av.getBalanceName();
            end;

            curIn  = getValue(av.getInRestPassive(), chapter);
            curDr  = getValue(av.getDebetNatCur(), chapter);
            curDv  = getValue(av.getDebetCur(), chapter);
            curD   = getValue(av.getDebet(), chapter);
            curKr  = getValue(av.getCreditNatCur(), chapter);
            curKv  = getValue(av.getCreditCur(), chapter);
            curK   = getValue(av.getCredit(), chapter);
            curOut = getValue(av.getOutRestPassive(), chapter);
            balanceOrder = ternary(strLen(av.getBalance()) == 3, 1, 2);

            spodValue = spod.getBalanceAttribute(NULL, av.getBalance(), false);

            if ((m_chapter != 1) AND (m_withSpod))
                spodIn = 0.0;
                spodDr = 0.0;
                spodDv = 0.0;
                spodD  = 0.0;
                spodKr = 0.0;
                spodKv = 0.0;
                spodK  = 0.0;
                sSpodPartD = 0.0;
                sSpodPartDr = 0.0;
                sSpodPartDv = 0.0;
                sSpodPartK = 0.0;
                sSpodPartKr = 0.0;
                sSpodPartKv = 0.0;
                sSpodD = 0.0;
                sSpodDr = 0.0;
                sSpodDv = 0.0;
                sSpodK = 0.0;
                sSpodKr = 0.0;
                sSpodKv = 0.0;
            else
                if (spodValue != NULL)
                    if (balanceOrder == 2)
                        if ((m_isPeriodYear) AND (m_withSpod))
                            spodIn = - spodValue.fieldValue("currYearDebetRouble" ).exact - spodValue.fieldValue("currYearDebetCover" ).exact +
                                       spodValue.fieldValue("currYearCreditRouble").exact + spodValue.fieldValue("currYearCreditCover").exact;

                            curIn = curIn + spodIn;

                            curDr = curDr - spodValue.fieldValue("currYearDebetRouble" ).exact;
                            curDv = curDv - spodValue.fieldValue("currYearDebetCover"  ).exact;
                            curD  = curD  - spodValue.fieldValue("currYearDebetRouble" ).exact - spodValue.fieldValue("currYearDebetCover").exact;
                            curKr = curKr - spodValue.fieldValue("currYearCreditRouble").exact;
                            curKv = curKv - spodValue.fieldValue("currYearCreditCover" ).exact;
                            curK  = curK  - spodValue.fieldValue("currYearCreditRouble").exact - spodValue.fieldValue("currYearCreditCover").exact;
                        else
                            spodDr = spodValue.fieldValue("nextYearDebetRouble" ).exact;
                            spodDv = spodValue.fieldValue("nextYearDebetCover"  ).exact;
                            spodD  = spodValue.fieldValue("nextYearDebetRouble" ).exact + spodValue.fieldValue("nextYearDebetCover").exact;
                            spodKr = spodValue.fieldValue("nextYearCreditRouble").exact;
                            spodKv = spodValue.fieldValue("nextYearCreditCover" ).exact;
                            spodK  = spodValue.fieldValue("nextYearCreditRouble").exact + spodValue.fieldValue("nextYearCreditCover").exact;

                            balanceLevel1DebitSpod = balanceLevel1DebitSpod + spodD;
                            balanceLevel1DebitRoubleSpod = balanceLevel1DebitRoubleSpod + spodDr;
                            balanceLevel1DebitForeignSpod = balanceLevel1DebitForeignSpod + spodDv;

                            balanceLevel1CreditSpod = balanceLevel1CreditSpod + spodK;
                            balanceLevel1CreditRoubleSpod = balanceLevel1CreditRoubleSpod + spodKr;
                            balanceLevel1CreditForeignSpod = balanceLevel1CreditForeignSpod + spodKv;
                        end;
                    end;
                else
                    spodIn = 0;
                    spodDr = 0;
                    spodDv = 0;
                    spodD  = 0;
                    spodKr = 0;
                    spodKv = 0;
                    spodK  = 0;
                end;
            end;

            if ((av.getPart().exact != currentPart) and (balanceOrder == 2))
                if (currentPart > 0)
                    printItog("ИТОГО по разделу " + currentPart, sPartIn, sPartDr, sPartDv,  sPartD, sPartKr, sPartKv, sPartK, sPartOut,
                                m_isPrintSpod, "В том числе СПОД ", sSpodPartDr, sSpodPartDv,  sSpodPartD, sSpodPartKr, sSpodPartKv, sSpodPartK);

                    m_tableReport.PrintSeparator(true);
                end;

                if (av.getBalance() == "99999")
                    s9999_In  = curIn;
                    s9999_D   = curD;
                    s9999_Dr  = curDr;
                    s9999_Dv  = curDv;
                    s9999_K   = curK;
                    s9999_Kr  = curKr;
                    s9999_Kv  = curKv;
                    s9999_Out = curOut;
                end;
                currentPart = av.getPart().exact;
                printFreeString("                 РАЗДЕЛ " + currentPart + ". " + GetPartitionName(chapter, currentPart));

                m_tableReport.PrintSeparator(true);
                sPartIn = 0; sPartD = 0; sPartDr = 0; sPartDv = 0; sPartK = 0; sPartKr = 0; sPartKv = 0; sPartOut = 0;
                sSpodPartDr = 0; sSpodPartDv = 0; sSpodPartD = 0; sSpodPartKr = 0; sSpodPartKv = 0; sSpodPartK = 0;
            end;

            if (balanceOrder == 2)
                balanceLevel1RestIn = balanceLevel1RestIn + curIn;
                balanceLevel1Debit = balanceLevel1Debit + curD;
                balanceLevel1DebitRouble = balanceLevel1DebitRouble + curDr;
                balanceLevel1DebitForeign = balanceLevel1DebitForeign + curDv;

                balanceLevel1Credit = balanceLevel1Credit + curK;
                balanceLevel1CreditRouble = balanceLevel1CreditRouble + curKr;
                balanceLevel1CreditForeign = balanceLevel1CreditForeign + curKv;
                balanceLevel1RestOut = balanceLevel1RestOut + curOut;
            end;

            /* не печатать итого по счету 999 первого порядка */
            if (((balanceOrder != 1) and (av.getBalance() != "999")) or (av.getBalance() != "999"))
                if (balanceOrder == 1)
                    printTableString(balanceOrder, av.getBalance(), av.getBalanceName(),
                                     balanceLevel1RestIn,
                                     balanceLevel1DebitRouble,
                                     balanceLevel1DebitForeign,
                                     balanceLevel1Debit,
                                     balanceLevel1CreditRouble,
                                     balanceLevel1CreditForeign,
                                     balanceLevel1Credit,
                                     balanceLevel1RestOut,
                                     m_isPrintSpod, "В том числе СПОД ",
                                     balanceLevel1DebitRoubleSpod,
                                     balanceLevel1DebitForeignSpod,
                                     balanceLevel1DebitSpod,
                                     balanceLevel1CreditRoubleSpod,
                                     balanceLevel1CreditForeignSpod,
                                     balanceLevel1CreditSpod
                                    );
                elif (av.getBalance() != "99997")
                    if ((spodDr != 0) OR (spodDv != 0) OR ( spodD != 0) OR (spodKr != 0) OR (spodKv != 0) OR (spodK != 0))
                        printTableString(balanceOrder, av.getBalance(), av.getBalanceName(), curIn, curDr, curDv, curD, curKr, curKv, curK, curOut,
                                         m_isPrintSpod, "В том числе СПОД ", spodDr, spodDv,  spodD, spodKr, spodKv, spodK);
                    else
                        printTableString(balanceOrder, av.getBalance(), av.getBalanceName(), curIn, curDr, curDv, curD, curKr, curKv, curK, curOut, false);
                    end;
                end;
            end;

            if (av.getBalance() == "99997")
                s9999_In  = curIn;
                s9999_D   = curD;
                s9999_Dr  = curDr;
                s9999_Dv  = curDv;
                s9999_K   = curK;
                s9999_Kr  = curKr;
                s9999_Kv  = curKv;
                s9999_Out = curOut;
            end;

            if (balanceOrder == 2)
                sIn  = sIn  + curIn;
                sDr  = sDr  + curDr;
                sDv  = sDv  + curDv;
                sD   = sD   + curD;
                sKr  = sKr  + curKr;
                sKv  = sKv  + curKv;
                sK   = sK   + curK;
                sOut = sOut + curOut;

                sKindIn  = sKindIn  + curIn;
                sKindDr  = sKindDr  + curDr;
                sKindDv  = sKindDv  + curDv;
                sKindD   = sKindD   + curD;
                sKindKr  = sKindKr  + curKr;
                sKindKv  = sKindKv  + curKv;
                sKindK   = sKindK   + curK;
                sKindOut = sKindOut + curOut;

                sPartIn  = sPartIn  + curIn;
                sPartDr  = sPartDr  + curDr;
                sPartDv  = sPartDv  + curDv;
                sPartD   = sPartD   + curD;
                sPartKr  = sPartKr  + curKr;
                sPartKv  = sPartKv  + curKv;
                sPartK   = sPartK   + curK;
                sPartOut = sPartOut + curOut;

                if (spodValue != NULL)

                    sSpodPartDr = sSpodPartDr + spodDr;
                    sSpodPartDv = sSpodPartDv + spodDv;
                    sSpodPartD  = sSpodPartD  + spodD;
                    sSpodPartKr = sSpodPartKr + spodKr;
                    sSpodPartKv = sSpodPartKv + spodKv;
                    sSpodPartK  = sSpodPartK  + spodK;

                    sSpodDr = sSpodDr + spodDr;
                    sSpodDv = sSpodDv + spodDv;
                    sSpodD  = sSpodD  + spodD;
                    sSpodKr = sSpodKr + spodKr;
                    sSpodKv = sSpodKv + spodKv;
                    sSpodK  = sSpodK  + spodK;
                end;

                prevBalance = av.getBalance();
            else
                balanceLevel1RestIn     = balanceLevel1RestOut = $0;
                balanceLevel1Debit = balanceLevel1DebitRouble = balanceLevel1DebitForeign = $0;
                balanceLevel1Credit = balanceLevel1CreditRouble = balanceLevel1CreditForeign = $0;
                balanceLevel1DebitSpod = balanceLevel1DebitRoubleSpod = balanceLevel1DebitForeignSpod = $0;
                balanceLevel1CreditSpod = balanceLevel1CreditRoubleSpod = balanceLevel1CreditForeignSpod = $0;
            end;
        end;

        if (currentPart > 0)
            printItog("ИТОГО по разделу " + currentPart, sPartIn, sPartDr, sPartDv,  sPartD, sPartKr, sPartKv, sPartK, sPartOut,
                      m_isPrintSpod, "В том числе СПОД ", sSpodPartDr, sSpodPartDv,  sSpodPartD, sSpodPartKr, sSpodPartKv, sSpodPartK);
            m_tableReport.PrintSeparator(true);
        end;

        if (chapter == 4)
            printTableString(2, "99997", nameBalance99997, s9999_In, s9999_Dr, s9999_Dv, s9999_D, s9999_Kr, s9999_Kv, s9999_K, s9999_Out, false);
            m_tableReport.PrintSeparator(true);
        end;

        printItog("ИТОГО по пассиву: ", sKindIn, sKindDr, sKindDv,  sKindD, sKindKr, sKindKv, sKindK, sKindOut,
                  m_isPrintSpod, "В том числе СПОД ", sSpodDr, sSpodDv,  sSpodD, sSpodKr, sSpodKv, sSpodK);

        m_tableReport.PrintSeparator(true);


        printItog("ВСЕГО ОБОРОТОВ: ", "", sDr, sDv,  sD, sKr, sKv, sK, "",
                  m_isPrintSpod, "В том числе СПОД ", sSpodTotalDr + sSpodDr, sSpodTotalDv + sSpodDv, sSpodTotalD + sSpodD, sSpodTotalKr + sSpodKr, sSpodTotalKv + sSpodKv, sSpodTotalK + sSpodK);
        m_tableReport.PrintBottom();
    end;

    constructorTApplication7ReportView(withSpod, chapter, needCheck, applicationNumber);
end;

class (TApplication7ReportView) TApplication5ReportView_579(withSpod : Bool, chapter : Integer, needCheck : Bool)
    initTApplication7ReportView(withSpod, chapter, needCheck, "5");

    macro printLendingAgencyCodeZone()
        /*_____________________________________________________________________________________*/
        var bankName = TArray();
        var i;
        /*_____________________________________________________________________________________*/


        [#]( strAlign( "                           Приложение 5    ", ReportWidth, STR_ALIGN_RIGHT ));
        [#]( strAlign( " к Приложению к Положению Банка России     ", ReportWidth, STR_ALIGN_RIGHT ));
        [#]( strAlign( " от 27 февраля 2017 года N 579-П           ", ReportWidth, STR_ALIGN_RIGHT ));
        [#]( strAlign( "\"О плане счетов бухгалтерского учета      ", ReportWidth, STR_ALIGN_RIGHT ));
        [#]( strAlign( " в кредитных организациях и порядке его    ", ReportWidth, STR_ALIGN_RIGHT ));
        [#]( strAlign( " применения\"                              ", ReportWidth, STR_ALIGN_RIGHT ));
        [ ];

        /*________________________________________________________________________________________*/

        [ ];
        /*________________________________________________________________________________________*/
        var periodName = RcbReportView("", "", RcbArray().initialize(RCB_PK_DAY, RCB_PK_MONTH, RCB_PK_QUARTER, RCB_PK_HALFYEAR, RCB_PK_PERIOD), DATE_IN_PERIOD_FORMAT).getNamesZone().getPeriodName();

        [#]( strAlign(        "Оборотная ведомость", ReportWidth, STR_ALIGN_CENTER ) );
        [#]( strAlign( "по счетам кредитной организации", ReportWidth, STR_ALIGN_CENTER ) );
        [#]( strAlign( periodName, ReportWidth, STR_ALIGN_CENTER ) );
    end;

    macro printChapterHeader(chapterName : String)
        var currentBeginPos = 1;
        var currentEndPos;
        var limit = StrLen(chapterName);
        var correction = 1;

        while (currentBeginPos <= limit)
            currentEndPos = StrBrk(substr(chapterName, currentBeginPos), "\n");
            if (currentEndPos == 0)
                currentEndPos = StrLen(substr(chapterName, currentBeginPos));
                correction = 0;
            end;
            PrintLn(strAlign(substr(chapterName, currentBeginPos, currentEndPos - correction), ReportWidth, STR_ALIGN_CENTER));
            currentBeginPos = currentBeginPos + currentEndPos;
        end;

        [┌─────────────────┬───────────────────────────┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┐];
        [│   Номер счета   │       Наименование        │  Входящие остатки  │                                                 Обороты за отчетный период                                                  │ Исходящие остатки  │];
        [├────────┬────────┤    разделов и счетов      │  на отчетную дату  ├──────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────┤  на отчетную дату  │];
        [│первого │второго │         баланса           │    (в рублях,      │                          по дебету                           │                           по кредиту                         │    (в рублях,      │];
        [│порядка │порядка │                           │иностранной валюте  ├────────────────────┬────────────────────┬────────────────────┼────────────────────┬────────────────────┬────────────────────┤иностранной валюте  │];
        [│        │        │                           │   и драгоценных    │      в рублях      │ иностранная валюта │        итого       │      в рублях      │ иностранная валюта │        итого       │   и драгоценных    │];
        [│        │        │                           │     металлах       │                    │   и драгоценные    │                    │                    │   и драгоценные    │                    │     металлах       │];
        [│        │        │                           │    в рублевом      │                    │      металлы в     │                    │                    │      металлы в     │                    │    в рублевом      │];
        [│        │        │                           │    эквиваленте)    │                    │рублевом эквиваленте│                    │                    │рублевом эквиваленте│                    │    эквиваленте)    │];
        [├────────┼────────┼───────────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤];
        [│    1   │   2    │            3              │          4         │          5         │          6         │          7         │          8         │          9         │         10         │         11         │];
        [├────────┴────────┴───────────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┤];
    end;
end;
