/*
$Name:        BalanceDataSource.mac
$Module:      Регламентируемая отчетность
$Description: Форма Балансовые счета. Источник данных
*/

/**
 * Форма Балансовый отчет. Источник данных
 *
 * @since   07.03.2013
 * @author  Gromov
 * @version 6.00.020.31
 */

import RsbDataSet;
import rep_lib;
import cb_sql;
import rcbconst;
import balanceReportParameters;

/**
 * Данныe по балансу.
 */
class TBalanceDataSource(chapter)

    var m_chapter;
    /**
     * Получить данные отчета.
     */
    macro getBalanceDataSet()
        var queryText         = "";

        queryText = "SELECT * FROM ("
                         + "\n" + "SELECT CASE                                                                              "
                         + "\n" + "            WHEN bal.t_bdincludeBwp <= " + getSqlDate(balanceParameters().getDateOut())
                         + "\n" + "             AND (   (bal.t_bdexcludeBwp >= " + getSqlDate(balanceParameters().getDateIn()) + ")"
                         + "\n" + "                  OR (bal.t_bdExcludeBWP = " + getSqlDate(Date(0,0,0)) + ")                   "
                         + "\n" + "                 )                                                                        "
                         + "\n" + "            THEN 1                                                                        "
                         + "\n" + "            ELSE 0                                                                        "
                         + "\n" + "       END                               AS t_inBwp,                                      "
                         + "\n" + "       bal.t_part                        AS t_part,                                       "
                         + "\n" + "       bal.t_chapter                     AS t_chapter,                                    "
                         + "\n" + "       bal.t_kind_account                AS t_kind,                                       "
                         + "\n" + "       bal.t_balance                     AS t_balance,                                    "
                         + "\n" + "       NVL (bal.t_name_part, CHR (0))    AS t_balanceName,                                "
                         + "\n" + "       (blrept.t_dmInActiveR)            AS t_inActiveRest,                               "
                         + "\n" + "       CASE                             "
                         + "\n" + "           WHEN bal.t_balance LIKE '20308%'                                                   "
                         + "\n" + "             THEN 0                         "
                         + "\n" + "            ELSE blrept.t_dmInActiveR_R                                                   "
                         + "\n" + "       END          AS t_inActiveRest_R,                                                  "
                         + "\n" + "       CASE                             "
                         + "\n" + "           WHEN bal.t_balance LIKE '20308%'                                                   "
                         + "\n" + "             THEN blrept.t_dmInActiveR_R + blrept.t_dmInActiveR_V                         "
                         + "\n" + "            ELSE blrept.t_dmInActiveR_V                                                   "
                         + "\n" + "       END          AS t_inActiveRest_V,                                                  "
                         + "\n" + "       (blrept.t_dmInPassiveR)           AS t_inPassiveRest,                              "
                         + "\n" + "       (blrept.t_dmInPassiveR_R)         AS t_inPassiveRest_R,                            "
                         + "\n" + "       (blrept.t_dmInPassiveR_V)         AS t_inPassiveRest_V,                            "
                         + "\n" + "       (blrept.t_dmdebetr)               AS t_debet,                                      "
                         + "\n" + "       CASE                             "
                         + "\n" + "           WHEN bal.t_balance LIKE '20308%'                                                   "
                         + "\n" + "             THEN 0                         "
                         + "\n" + "            ELSE blrept.t_dmdebetr_R                                                   "
                         + "\n" + "       END          AS t_debetNatCur,                                                  "
                         + "\n" + "       CASE                             "
                         + "\n" + "           WHEN bal.t_balance LIKE '20308%'                                                   "
                         + "\n" + "             THEN blrept.t_dmdebetr_R + blrept.t_dmdebetr_V                         "
                         + "\n" + "            ELSE blrept.t_dmdebetr_V                                                   "
                         + "\n" + "       END          AS t_debetCur,                                                  "
                         + "\n" + "       (blrept.t_dmcreditr)              AS t_credit,                                     "
                         + "\n" + "       CASE                             "
                         + "\n" + "           WHEN bal.t_balance LIKE '20308%'                                                   "
                         + "\n" + "             THEN 0                         "
                         + "\n" + "            ELSE blrept.t_dmcreditr_R                                                   "
                         + "\n" + "       END          AS t_creditNatCur,                                                  "
                         + "\n" + "       CASE                             "
                         + "\n" + "           WHEN bal.t_balance LIKE '20308%'                                                   "
                         + "\n" + "             THEN blrept.t_dmcreditr_R + blrept.t_dmcreditr_V                         "
                         + "\n" + "            ELSE blrept.t_dmcreditr_V                                                   "
                         + "\n" + "       END          AS t_creditCur,                                                  "
                         + "\n" + "       (blrept.t_dmOutActiveR)           AS t_outActiveRest,                              "
                         + "\n" + "       CASE                             "
                         + "\n" + "           WHEN bal.t_balance LIKE '20308%'                                                   "
                         + "\n" + "             THEN 0                         "
                         + "\n" + "            ELSE blrept.t_dmOutActiveR_R                                                   "
                         + "\n" + "       END          AS t_outActiveRest_R,                                                  "
                         + "\n" + "       CASE                             "
                         + "\n" + "           WHEN bal.t_balance LIKE '20308%'                                                   "
                         + "\n" + "             THEN blrept.t_dmOutActiveR_R + blrept.t_dmOutActiveR_V                         "
                         + "\n" + "            ELSE blrept.t_dmOutActiveR_V                                                   "
                         + "\n" + "       END          AS t_outActiveRest_V,                                                  "
                         + "\n" + "       (blrept.t_dmOutPassiveR)          AS t_outPassiveRest,                             "
                         + "\n" + "       (blrept.t_dmOutPassiveR_R)        AS t_outPassiveRest_R,                           "
                         + "\n" + "       (blrept.t_dmOutPassiveR_V)        AS t_outPassiveRest_V,                           "
                         + "\n" + "       (blrept.t_dmfinaldebetr)          AS t_debetSpod,                                  "
                         + "\n" + "       (blrept.t_dmfinalcreditr)         AS t_creditSpod                                  "
                         + "\n" + "  FROM dblrept_tmp blrept                                                                 "
                         + "\n" + "       INNER JOIN dblblnc_tmp blblnc                                                      "
                         + "\n" + "          ON (blblnc.t_balance = blrept.t_balance                                         "
                         + "\n" + "              AND blblnc.t_chapter = blrept.t_ichapter)                                   "
                         + "\n" + "       RIGHT JOIN dbalance_dbt bal                                                        "
                         + "\n" + "          ON ( (    bal.t_chapter = blrept.t_ichapter                                     "
                         + "\n" + "                AND bal.t_balance = blrept.t_balance                                      "
                         + "\n" + "                AND bal.t_inumplan = blrept.t_inumplan)                                   "
                         + "\n" + "              OR (bal.t_bdIncludeBWP <= "  + getSqlDate(balanceParameters().getDateOut())
                         + "\n" + "                  AND (bal.t_bdExcludeBWP >= " + getSqlDate(balanceParameters().getDateIn())
                         + "\n" + "                       OR bal.t_bdExcludeBWP = TO_DATE ('01.01.0001', 'dd.mm.yyyy'))))        "
                         + "\n" + " WHERE     INSTR (bal.t_Type_Balance, 'T') = 0                                            "
                         + "\n" + "       AND bal.t_chapter = blrept.t_ichapter                                              "
                         + "\n" + "       AND bal.t_balance = blrept.t_balance                                               "
                         + "\n" + "       AND bal.t_inumplan = blrept.t_inumplan                                             "
                         + "\n" + "       AND bal.t_chapter = " + m_chapter
                         + "\n" + "UNION                                                                                     "
                         + "\n" + "SELECT 1 t_inBwp,                                                                         "
                         + "\n" + "       bal.t_part,                                                                        "
                         + "\n" + "       bal.t_chapter,                                                                     "
                         + "\n" + "       bal.t_kind_account t_kind,                                                         "
                         + "\n" + "       bal.t_balance,                                                                     "
                         + "\n" + "       NVL (bal.t_name_part, CHR (0)) balanceName,                                        "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0,                                                                                 "
                         + "\n" + "       0                                                                                  "
                         + "\n" + "  FROM dbalance_dbt bal                                                                   "
                         + "\n" + " WHERE     INSTR (bal.t_Type_Balance, 'T') = 0                                            "
                         + "\n" + "       AND bal.t_balance NOT LIKE '%ОВП%'                                                 "
                         + "\n" + "       AND bal.t_chapter = " + m_chapter
                         + "\n" + "       AND bal.t_inumPlan = " + balanceParameters().getPlanNumber()
                         + "\n" + "       AND LENGTH (bal.t_balance) > 2                                                     "
                         + "\n" + "       AND NOT EXISTS                                                                     "
                         + "\n" + "                  (SELECT 1                                                               "
                         + "\n" + "                     FROM dblrept_tmp blrept                                              "
                         + "\n" + "                    WHERE     bal.t_chapter = blrept.t_ichapter                           "
                         + "\n" + "                          AND bal.t_balance = blrept.t_balance                            "
                         + "\n" + "                          AND bal.t_inumplan = blrept.t_inumplan)                         "
                         + "\n" + "       AND bal.t_bdIncludeBWP <= " + getSqlDate(balanceParameters().getDateOut())
                         + "\n" + "       AND (bal.t_bdExcludeBWP >= " + getSqlDate(balanceParameters().getDateIn())
                         + "\n" + "            OR bal.t_bdExcludeBWP = TO_DATE ('01.01.0001', 'dd.mm.yyyy'))                     "
                         + "\n" + ") data                                                                                        "
                         + "\n" + "ORDER BY data.t_balance                                                                       ";

        var dataSet = TRsbDataSet(queryText);

        dataSet.setFieldType("t_inActiveRest", V_MONEY);
        dataSet.setFieldType("t_inActiveRest_R", V_MONEY);
        dataSet.setFieldType("t_inActiveRest_V", V_MONEY);
        dataSet.setFieldType("t_inPassiveRest", V_MONEY);
        dataSet.setFieldType("t_inPassiveRest_R", V_MONEY);
        dataSet.setFieldType("t_inPassiveRest_V", V_MONEY);
        dataSet.setFieldType("t_debet", V_MONEY);
        dataSet.setFieldType("t_debetNatCur", V_MONEY);
        dataSet.setFieldType("t_debetCur", V_MONEY);
        dataSet.setFieldType("t_credit", V_MONEY);
        dataSet.setFieldType("t_creditNatCur", V_MONEY);
        dataSet.setFieldType("t_creditCur", V_MONEY);
        dataSet.setFieldType("t_outActiveRest", V_MONEY);
        dataSet.setFieldType("t_outActiveRest_R", V_MONEY);
        dataSet.setFieldType("t_outActiveRest_V", V_MONEY);
        dataSet.setFieldType("t_outPassiveRest", V_MONEY);
        dataSet.setFieldType("t_outPassiveRest_R", V_MONEY);
        dataSet.setFieldType("t_outPassiveRest_V", V_MONEY);
        dataSet.setFieldType("t_debetSpod", V_MONEY);
        dataSet.setFieldType("t_creditSpod", V_MONEY);

        return dataSet;
    end;

    /**
     * Конструктор.
     */
    private macro constructor(chapter)
        m_chapter = chapter;
    end;

    constructor(chapter);
end;
