/*
$Name:          balanceCheck.mac
$Module:        Регламентируемая отчетность
$Description:   Форма Балансовые счета. Проверки баланса
*/

/**
 * Форма "Балансовые счета". Проверки баланса
 *
 * @since   6.20.031.021
 * @author  ABP
 * @version 1.0
 */

import RcbCoreInter;
import balanceGlobal;
import balanceAttribute;

private const MONEY_PRECISION = $0.000001;

private class TOffsettingAccountsChecker(chapter, offsettingAccount, offsettingAccountKind, excludedAccount, excludedAccountKind)
    private var m_chapter;
    private var m_chapterData;
    private var m_offsettingAccount;
    private var m_offsettingAccountKind;
    private var m_excludedAccount;
    private var m_excludedAccountKind;

    private var m_table;

    private macro constructor(chapter, offsettingAccount, offsettingAccountKind, excludedAccount, excludedAccountKind)
        m_chapter = chapter;
        m_chapterData = TBalanceAttribute("БАЛАНС").getCompositeValue("ГЛАВА" + chapter, chapter);
        m_offsettingAccount = offsettingAccount;
        m_offsettingAccountKind = offsettingAccountKind;
        m_excludedAccount = excludedAccount;
        m_excludedAccountKind = excludedAccountKind;

        m_table = CTableReport(0, false, false);
        m_table.addColumn("Счет", 25);
        m_table.addColumn("Остаток итог", 16);
//        m_table.addColumn("Остаток рубли", 16);
//        m_table.addColumn("Остаток валюта", 16);
    end;

    macro execute(header)
        var sumTotal = $0;
        var sumRouble = $0;
        var sumForeign = $0;

        m_table.printHead(header);

        var it = TBalanceAttribute("БАЛАНС");
        it.createBalanceIterator(m_chapter, m_excludedAccountKind, false, true, false);
        while (it.next())
            if (it.getBalance() == m_excludedAccount)
                continue;
            end;

//            m_table.printString(it.getBalance(), it.getOutRest().exact, it.getOutRestNatCur().exact, it.getOutRestCur().exact);
            m_table.printString(it.getBalance(), it.getOutRest().exact);

            sumTotal = sumTotal + it.getOutRest().exact;
            sumRouble = sumRouble + it.getOutRestNatCur().exact;
            sumForeign = sumForeign + it.getOutRestCur().exact;
        end;

        m_table.printSeparator();

        var columnKind = ternary(m_offsettingAccountKind == KIND_ACTIVE, TColumnKind().ACTIVE_OUT_REST, TColumnKind().PASSIVE_OUT_REST);
        var restTotal = it.getBalanceAttributeValue(m_chapter, m_offsettingAccount, columnKind, TRowKind().TOTAL);
        var restRouble = it.getBalanceAttributeValue(m_chapter, m_offsettingAccount, columnKind, TRowKind().ROUBLE);
        var restForeign = it.getBalanceAttributeValue(m_chapter, m_offsettingAccount, columnKind, TRowKind().CURRENCY);
//        m_table.printString(m_offsettingAccount, restTotal.exact, restRouble.exact, restForeign.exact);
        m_table.printString(m_offsettingAccount, restTotal.exact);

        m_table.printSeparator();

//        m_table.printString("Разница в остатках", string(sumTotal - restTotal.exact), string(sumRouble - restRouble.exact), string(sumForeign - restForeign.exact));
        m_table.printString("Разница в остатках", string(sumTotal - restTotal.exact));

        m_table.printBottom();
    end;

    constructor(chapter, offsettingAccount, offsettingAccountKind, excludedAccount, excludedAccountKind);
end;

private class TRowConvergence(chapter, kind, componentKind)
    private var m_chapter;
    private var m_kind;
    private var m_componentKind;

    private var m_table;
    private var m_kindString;

    private var m_hasDifference;

    private macro getInRest(attribute : Object)
        var rest = null;

        if (m_componentKind == TRowKind().TOTAL)
            rest = attribute.getInRest();
        elif (m_componentKind == TRowKind().ROUBLE)
            rest = attribute.getInRestNatCur();
        else // (m_componentKind == TRowKind().CURRENCY)
            rest = attribute.getInRestCur();
        end;

//        return rest.exact;
        return rest.scaled;
    end;

    private macro getOutRest(attribute : Object)
        var rest = null;

        if (m_componentKind == TRowKind().TOTAL)
            rest = attribute.getOutRest();
        elif (m_componentKind == TRowKind().ROUBLE)
            rest = attribute.getOutRestNatCur();
        else // (m_componentKind == TRowKind().CURRENCY)
            rest = attribute.getOutRestCur();
        end;

//        return rest.exact;
        return rest.scaled;
    end;

    private macro getDebit(attribute : Object)
        var rest = null;

        if (m_componentKind == TRowKind().TOTAL)
            rest = attribute.getDebet();
        elif (m_componentKind == TRowKind().ROUBLE)
            rest = attribute.getDebetNatCur();
        else // (m_componentKind == TRowKind().CURRENCY)
            rest = attribute.getDebetCur();
        end;

//        return rest.exact;
        return rest.scaled;
    end;

    private macro getCredit(attribute : Object)
        var rest = null;

        if (m_componentKind == TRowKind().TOTAL)
            rest = attribute.getCredit();
        elif (m_componentKind == TRowKind().ROUBLE)
            rest = attribute.getCreditNatCur();
        else // (m_componentKind == TRowKind().CURRENCY)
            rest = attribute.getCreditCur();
        end;

//        return rest.exact;
        return rest.scaled;
    end;

    macro execute(showProtocol : bool)
        defaultParm(showProtocol, true);

        m_table.setBufferPrint(not showProtocol);

        m_table.printHead("Проверка сходимости по строке счетов \"" + m_kindString + "\" для составляющей \"" + m_componentKind + "\" главы " + m_chapter);

        m_hasDifference = false;

        var it = TBalanceAttribute("БАЛАНС");
        it.createBalanceIterator(m_chapter, m_kind, false, false, false, true);
        while (it.next())
            var diff;

            var inRest = getInRest(it);
            var outRest = getOutRest(it);
            var debit = getDebit(it);
            var credit = getCredit(it);

            if (m_kind == KIND_ACTIVE)
                credit = -credit;
            else // (m_kind == KIND_PASSIVE)
                debit = -debit;
            end;

            diff = abs(inRest + debit + credit - outRest);
            if (diff <= MONEY_PRECISION)
                continue;
            end;

            m_hasDifference = true;
            m_table.printString(it.getBalance(), string(inRest:*:6), string(debit:*:6), string(credit:*:6), string(outRest:*:6), string(diff:*:12));
        end;

        m_table.printBottom();
    end;

    macro hasDifference()
        return m_hasDifference;
    end;

    private macro constructorTRowConvergence(chapter, kind, componentKind)
        m_chapter = chapter;
        m_kind = kind;
        m_componentKind = componentKind;

        m_table = CTableReport(0, false, false);
        m_table.addColumn("Счет", 25);
        m_table.addColumn("Входящий", 20);
        m_table.addColumn("Дебет", 20);
        m_table.addColumn("Кредит", 20);
        m_table.addColumn("Исходящий", 20);
        m_table.addColumn("Расхождение", 20);

        m_kindString = ternary(m_kind == KIND_ACTIVE, "Актив", "Пассив");
    end;

    constructorTRowConvergence(chapter, kind, componentKind);
end;

private class TColumnConvergence(chapter, kind, componentKind)
    private var m_chapter;
    private var m_kind;
    private var m_componentKind;

    private var m_table;
    private var m_kindString;

    private var m_hasDifference;

    private macro getInRest(attribute : Object)
        var rest = null;

        if (m_componentKind == TRowKind().TOTAL)
            rest = attribute.getInRest();
        elif (m_componentKind == TRowKind().ROUBLE)
            rest = attribute.getInRestNatCur();
        else // (m_componentKind == TRowKind().CURRENCY)
            rest = attribute.getInRestCur();
        end;

        return rest;
    end;

    private macro getOutRest(attribute : Object)
        var rest = null;

        if (m_componentKind == TRowKind().TOTAL)
            rest = attribute.getOutRest();
        elif (m_componentKind == TRowKind().ROUBLE)
            rest = attribute.getOutRestNatCur();
        else // (m_componentKind == TRowKind().CURRENCY)
            rest = attribute.getOutRestCur();
        end;

        return rest;
    end;

    private macro getDebit(attribute : Object)
        var rest = null;

        if (m_componentKind == TRowKind().TOTAL)
            rest = attribute.getDebet();
        elif (m_componentKind == TRowKind().ROUBLE)
            rest = attribute.getDebetNatCur();
        else // (m_componentKind == TRowKind().CURRENCY)
            rest = attribute.getDebetCur();
        end;

        return rest;
    end;

    private macro getCredit(attribute : Object)
        var rest = null;

        if (m_componentKind == TRowKind().TOTAL)
            rest = attribute.getCredit();
        elif (m_componentKind == TRowKind().ROUBLE)
            rest = attribute.getCreditNatCur();
        else // (m_componentKind == TRowKind().CURRENCY)
            rest = attribute.getCreditCur();
        end;

        return rest;
    end;

    private macro checkAndPrint(value, caption)
        var normalized = value.scaled;
        var scaled = value.recalculateScaled().scaled;
        var diff = abs(normalized - scaled);
        if (diff > MONEY_PRECISION)
            m_hasDifference = true;
            m_table.printString(caption, string(scaled:*:6), string(normalized:*:6), string(diff:*:12));
        end;
    end;

    macro execute(showProtocol : bool, multiplier : Double, precision : Integer)
        defaultParm(showProtocol, true);

        m_table.setBufferPrint(not showProtocol);

        m_table.printHead("Проверка сходимости по столбцу счетов \"" + m_kindString + "\" для составляющей \"" + m_componentKind + "\" главы " + m_chapter);

        m_hasDifference = false;

        var it = TBalanceAttribute("БАЛАНС");
        it.createBalanceIterator(m_chapter, m_kind, false, false, false, true);

        var inRestTotal = TValue($0, $0, multiplier, precision);
        var outRestTotal = TValue($0, $0, multiplier, precision);
        var debitTotal = TValue($0, $0, multiplier, precision);
        var creditTotal = TValue($0, $0, multiplier, precision);

        while (it.next())
            inRestTotal.plus(getInRest(it));
            outRestTotal.plus(getOutRest(it));
            debitTotal.plus(getDebit(it));
            creditTotal.plus(getCredit(it));
        end;

//        checkAndPrint(inRestTotal, "Входящий остаток");
//        checkAndPrint(debitTotal, "Дебетовый оборот");
//        checkAndPrint(creditTotal, "Кредитовый оборот");
        checkAndPrint(outRestTotal, "Исходящий остаток");

        m_table.printBottom();
    end;

    macro hasDifference()
        return m_hasDifference;
    end;

    private macro constructorTColumnConvergence(chapter, kind, componentKind)
        m_chapter = chapter;
        m_kind = kind;
        m_componentKind = componentKind;

        m_table = CTableReport(0, false, false);
        m_table.addColumn("Объект", 25);
        m_table.addColumn("Округленное значение", 25);
        m_table.addColumn("Нормализованное значение", 25);
        m_table.addColumn("Расхождение", 20);

        m_kindString = ternary(m_kind == KIND_ACTIVE, "Актив", "Пассив");
    end;

    constructorTColumnConvergence(chapter, kind, componentKind);
end;

private class TComponentConvergence(chapter)
    private var m_chapter;

    private var m_hasDifference;

    private var m_table;

    private macro checkComponent(caption, balance, rouble, currency, total)
        var diff = abs(rouble + currency - total);
        if (diff > MONEY_PRECISION)
            m_table.printString(balance, caption, string(rouble:*:6), string(currency:*:6), string(total:*:6), string(diff:*:12));
            m_hasDifference = true;
        end;
    end;

    macro execute(showProtocol : Bool)
        defaultParm(showProtocol, true);

        m_table.setBufferPrint(not showProtocol);

        m_table.printHead("Проверка сходимости компонент счетов главы " + m_chapter);

        m_hasDifference = false;

        var it = TBalanceAttribute("БАЛАНС");
        it.createBalanceIterator(m_chapter, KIND_ALL, false, false, false, true);
        while (it.next())
//            checkComponent("Вх. остаток", it.getBalance(), it.getInRestNatCur().exact, it.getInRestCur().exact, it.getInRest().exact);
//            checkComponent("Дебет", it.getBalance(), it.getDebetNatCur().exact, it.getDebetCur().exact, it.getDebet().exact);
//            checkComponent("Кредит", it.getBalance(), it.getCreditNatCur().exact, it.getCreditCur().exact, it.getCredit().exact);
//            checkComponent("Исх. остаток", it.getBalance(), it.getOutRestNatCur().exact, it.getOutRestCur().exact, it.getOutRest().exact);
            checkComponent("Вх. остаток", it.getBalance(), it.getInRestNatCur().scaled, it.getInRestCur().scaled, it.getInRest().scaled);
            checkComponent("Дебет", it.getBalance(), it.getDebetNatCur().scaled, it.getDebetCur().scaled, it.getDebet().scaled);
            checkComponent("Кредит", it.getBalance(), it.getCreditNatCur().scaled, it.getCreditCur().scaled, it.getCredit().scaled);
            checkComponent("Исх. остаток", it.getBalance(), it.getOutRestNatCur().scaled, it.getOutRestCur().scaled, it.getOutRest().scaled);
        end;

        m_table.printBottom();
    end;

    macro hasDifference()
        return m_hasDifference;
    end;

    private macro constructorTComponentConvergence(chapter)
        m_chapter = chapter;

        m_table = CTableReport(0, false, false);
        m_table.addColumn("Счет", 25);
        m_table.addColumn("Объект", 12);
        m_table.addColumn("Рубли", 20);
        m_table.addColumn("Эквивалент", 20);
        m_table.addColumn("Итоги", 20);
        m_table.addColumn("Расхождение", 20);
    end;

    constructorTComponentConvergence(chapter);
end;

class TBalanceChecker(chapter : Integer)
    private var m_chapter : Integer;
    private var m_hasDifference : Bool;

    macro execute(showProtocol : Bool, multiplier : Double, precision : Integer)
        var checker;

        if ((showProtocol == null) or showProtocol)
            println("--------------------------------------------------------------");
        end;

        checker = TRowConvergence(m_chapter, KIND_ACTIVE, TRowKind().TOTAL);
        checker.execute(showProtocol);
        m_hasDifference = m_hasDifference or checker.hasDifference();

        if (m_chapter != 5)
            checker = TRowConvergence(m_chapter, KIND_ACTIVE, TRowKind().ROUBLE);
            checker.execute(showProtocol);
            m_hasDifference = m_hasDifference or checker.hasDifference();

            checker = TRowConvergence(m_chapter, KIND_ACTIVE, TRowKind().CURRENCY);
            checker.execute(showProtocol);
            m_hasDifference = m_hasDifference or checker.hasDifference();
        end;

        checker = TRowConvergence(m_chapter, KIND_PASSIVE, TRowKind().TOTAL);
        checker.execute(showProtocol);
        m_hasDifference = m_hasDifference or checker.hasDifference();

        if (m_chapter != 5)
            checker = TRowConvergence(m_chapter, KIND_PASSIVE, TRowKind().ROUBLE);
            checker.execute(showProtocol);
            m_hasDifference = m_hasDifference or checker.hasDifference();

            checker = TRowConvergence(m_chapter, KIND_PASSIVE, TRowKind().CURRENCY);
            checker.execute(showProtocol);
            m_hasDifference = m_hasDifference or checker.hasDifference();
        end;

        checker = TColumnConvergence(m_chapter, KIND_ACTIVE, TRowKind().TOTAL);
        checker.execute(showProtocol, multiplier, precision);
        m_hasDifference = m_hasDifference or checker.hasDifference();

        if (m_chapter != 5)
            checker = TColumnConvergence(m_chapter, KIND_ACTIVE, TRowKind().ROUBLE);
            checker.execute(showProtocol, multiplier, precision);
            m_hasDifference = m_hasDifference or checker.hasDifference();

            checker = TColumnConvergence(m_chapter, KIND_ACTIVE, TRowKind().CURRENCY);
            checker.execute(showProtocol, multiplier, precision);
            m_hasDifference = m_hasDifference or checker.hasDifference();
        end;

        checker = TColumnConvergence(m_chapter, KIND_PASSIVE, TRowKind().TOTAL);
        checker.execute(showProtocol, multiplier, precision);
        m_hasDifference = m_hasDifference or checker.hasDifference();

        if (m_chapter != 5)
            checker = TColumnConvergence(m_chapter, KIND_PASSIVE, TRowKind().ROUBLE);
            checker.execute(showProtocol, multiplier, precision);
            m_hasDifference = m_hasDifference or checker.hasDifference();

            checker = TColumnConvergence(m_chapter, KIND_PASSIVE, TRowKind().CURRENCY);
            checker.execute(showProtocol, multiplier, precision);
            m_hasDifference = m_hasDifference or checker.hasDifference();
        end;

        if (m_chapter != 5)
            checker = TComponentConvergence(m_chapter);
            checker.execute(showProtocol);
            m_hasDifference = m_hasDifference or checker.hasDifference();
        end;
    end;

    macro hasDifference()
        return m_hasDifference;
    end;

    private macro constructorTBalanceChecker(chapter : Integer)
        m_chapter = chapter;
        m_hasDifference = false;
    end;

    constructorTBalanceChecker(chapter);
end;

//var checker;
//
//checker = TBalanceChecker(3);
//checker.execute();

//checker = TOffsettingAccountsChecker(3, "99998", KIND_ACTIVE, "99999", KIND_PASSIVE);
//checker.execute("Контроль остатков по счету 99998 в главе В");
//
//checker = TOffsettingAccountsChecker(3, "99999", KIND_PASSIVE, "99998", KIND_ACTIVE);
//checker.execute("Контроль остатков по счету 99999 в главе В");
//
//checker = TOffsettingAccountsChecker(4, "99996", KIND_ACTIVE, "99997", KIND_PASSIVE);
//checker.execute("Контроль остатков по счету 99996 в главе Г");
//
//checker = TOffsettingAccountsChecker(4, "99997", KIND_PASSIVE, "99996", KIND_ACTIVE);
//checker.execute("Контроль остатков по счету 99997 в главе Г");
