/*
$Name: dl_prol.mac
$Module: МБК
$Description: Пользовательская реализация пролонгации сделок
*/
import RSBDataSet,dlgCommon,funk,Календарь,fx_lib,fx_globals,dl_lib, dl_note_lib, mmpaymentcls;

private  var dealid,ndealid,sql,pzag,cmd2,datra,nmt,d0,sss,sd0,ss0,sql0,ik2,soob=" ",par1,par2,{curdate},rs5,pId2,sidk,zag,sdiller,rs02,datransh,datpr,su;
private var que,rez,jk=0,dealtype,partyid,nflag,Comment,docid,idop;

private  var col2=TArray();
private var oprdocs = Tbfile( "oprdocs.dbt", "W" );


array mas1,mas0;


MACRO MM_tick(par1,par2)  
  private var que,rs5,rez=0;
  que="select b.t_" +par2+"  from  ddl_tick_dbt b  where  b.t_bofficekind=102 and b.t_dealcode='"+par1+"'"; 
  rs5 = LnGetRecordSet(que);
  if(rs5 != null)
     if (rs5.moveNext) 
        rez=rs5.value(0);
     end;
  end;
  return rez;
END;


MACRO swkod(par1,par2)  
  private var que,rs5,rez=0;
  que="select t_code from dobjcode_dbt where t_objectid="+par1+" and t_state = 0  and t_codekind="+par2; 
  rs5 = LnGetRecordSet(que);
  if(rs5 != null)
     if (rs5.moveNext) 
        rez=rs5.value(0);
     end;
  end;
  return rez;
END;


MACRO swks(par1)  
  private var que,rs5,rez=0;
  que="select t_coracc  from dbankdprt_dbt where t_partyid="+par1; 
  rs5 = LnGetRecordSet(que);
  if(rs5 != null)
     if (rs5.moveNext) 
        rez=rs5.value(0);
     end;
  end;
  return rez;
END;


MACRO HIST_PROL(dealcode)

     dealid=MM_tick(dealcode,"dealid");
     dealtype=MM_tick(dealcode,"dealtype");
     partyid=MM_tick(dealcode,"partyid");

     ndealid=prol(dealid);
     if (ndealid == 0)
         ndealid=dealid;
     end;
     zag="История пролонгации по сделке  "+Fx_kontr(partyid,1);
     sql0="select a.t_dealid pId2 , (select aa.t_ccy from dfininstr_dbt aa where aa.t_fiid=e.t_pfi) nfiid,e.t_price/100 price, e.t_cost cost,";
     sql0=sql0+ " (select t_account from (select a1.t_account from  dmcaccdoc_dbt a1, dmccateg_dbt b1 where a1.t_dockind=102   and a1.t_docid=a.t_dealid and a1.t_catid=b1.t_id and b1.t_code='ОД' order by a1.t_activatedate desc, a1.t_id desc) where rownum = 1) schod, ";

     if ( dealtype == 12300  )
       sql0=sql0+ " (select distinct(a1.t_account) from  dmcaccdoc_dbt a1, dmccateg_dbt b1 where a1.t_dockind=102   and a1.t_docid=a.t_dealid and a1.t_catid=b1.t_id and b1.t_code='-% к погашению МБК' ) schp, ";
     else
       sql0=sql0+ " (select distinct(a1.t_account) from  dmcaccdoc_dbt a1, dmccateg_dbt b1 where a1.t_dockind=102   and a1.t_docid=a.t_dealid and a1.t_catid=b1.t_id and b1.t_code='+% к погашению МБК' ) schp, ";
     end;

     sql0=sql0+ "  c.t_shortname nam,a.t_dealcode dealcode ,e.t_maturity maturity, e.t_start nstart,e.t_principal su,to_char(e.t_maturity-e.t_start,'9999') srok";
     sql0=sql0+ "  from ddl_tick_dbt a ,  dparty_dbt c,  ddl_leg_dbt e ";
     sql0=sql0+ "  where  e.t_dealid=a.t_dealid and c.t_partyid=a.t_partyid "; 
     sql0=sql0+ " and (a.t_dealid = "+ndealid;
    rez=" ";
    par1=ndealid;

    jk=0;
    ik2=0;

    while (jk < 100 )
       que = "select to_number(a.t_DocumentID) from doprdocs_dbt a, doproper_dbt b where a.t_id_operation=b.t_id_operation and a.t_dockind=102 and b.t_dockind=102 and b.t_DocumentID=lpad("+par1+",34,'0')";
       rs5 = LnGetRecordset(que);
       if(rs5 != null)
         if (rs5.moveNext) 
            if (rs5.value(0) > 0 )
             rez=int(rs5.value(0));
             par1=rez;
             sql0=sql0+ " or a.t_dealid = "+rez;
             ik2=ik2+1;
            else
             jk=101;
            end;
         end;
       end;

       jk=jk+1;
    end;
     sql0=sql0+ ")  order by a.t_dealdate ";
     if (ik2 < 1 )
        return;
     end;
     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );



  macro EvProc2 (rs0, cmd2, id, key )

     if (cmd2 == DLG_INIT)	// Инициализация
        rs0.MoveFirst();          

        if (pId2 != "0")  // Надо найти запись
           while ( (rs0.value ("pId2") != pId2) And (Not rs0.EOF) )  
              rs0.Move(1, RELATIVE);
            end;
        end;
        GoToScroll(rs0, true);

     elif (cmd2 == DLG_KEY)
        pId2=rs0.value ("pId2");
 
        if(DLG_KEY_ENTER == Key)
          return CM_SELECT;

        elif(DLG_KEY_F9 == Key) 
          return CM_SELECT;
        end;
     end;
  end;


  AddCol (col2, 0, "dealcode","№ сделки", 8);
  AddCol (col2, 1, "nstart","Дата начала", 10);
  AddCol (col2, 2, "maturity","Дата окончания", 13);
  AddCol (col2, 3, "srok","Срок", 4);
  AddCol (col2, 4, "su","Cумма сделки", 15);
  AddCol (col2, 5, "nfiid","Вал", 3);
  AddCol (col2, 6, "price","Cтавка %%", 9);
  AddCol (col2, 7, "cost","Cумма %% ", 12);
  AddCol (col2, 8, "schod","Л/с по учету ОД", 18);
  AddCol (col2, 9, "schp","Л/с по учету %%", 18);
     sss=" ESC- Выход " ;
     while(RunScroll(cmd2, 10, col2, null, @EvProc2,zag,sss, null, 5, 15,122,45) )
     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );
    end;


end;



MACRO HIST_PL(ndealid)


     partyid=MM_tickid(ndealid,"partyid");

     zag="История изменения платежей по сделке                                                                                                              Параметры        ДО редакции / ПОСЛЕ редакции";

     sql0=" select a.t_paymentid pId2 ,";
     sql0=sql0+" (to_char(a.t_valuedate,'dd.mm.yyyy')||'/'||TRIM(to_char(a.t_valuedate2,'dd.mm.yyyy'))) dat1 ,";
     sql0=sql0+" (to_char(a.t_amount,'99,999,999,999.99')||'/'|| TRIM(to_char(a.t_amount2,'99,999,999,999.99'))) amount1,";

     sql0=sql0+"(case when b.t_purpose = 11 then 'Погашение %%' else 'Погашение ОД' end ) plat, ";


     sql0=sql0+"(select aa.t_ccy from dfininstr_dbt aa where aa.t_fiid=b.t_fiid) sfiid,";


     sql0=sql0+" ((select aa.t_code from dobjcode_dbt aa where aa.t_codekind=6 and aa.t_objectid=a.t_payerbankid )||'/'||(select aa.t_code from dobjcode_dbt aa where aa.t_codekind=6 and aa.t_objectid=a.t_payerbankid2 )) kod1 ,  ";
     sql0=sql0+" ((select aa.t_code from dobjcode_dbt aa where aa.t_codekind=6 and aa.t_objectid=a.t_receiverbankid )||'/'||(select aa.t_code from dobjcode_dbt aa where aa.t_codekind=6 and aa.t_objectid=a.t_receiverbankid2 )) kod11 ,to_char(a.t_dater,'dd.mm.yyyy') dat,a.t_oper oper";

     sql0=sql0+"  from DSTD_HISTPAYM_DBT a, DPMPAYM_DBT b where b.t_dockind=102 and b.t_documentid="+ndealid+" and a.t_paymentid=b.t_paymentid order by dat,oper ";
//      msgbox(sql0);
//     RETURN;
     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );


  macro EvProc22 (rs0, cmd2, id, key )

     if (cmd2 == DLG_INIT)	// Инициализация
        rs0.MoveFirst();          

        if (pId2 != "0")  // Надо найти запись
           while ( (rs0.value ("pId2") != pId2) And (Not rs0.EOF) )  
              rs0.Move(1, RELATIVE);
            end;
        end;
        GoToScroll(rs0, true);

     elif (cmd2 == DLG_KEY)
        pId2=rs0.value ("pId2");
 
        if(DLG_KEY_ENTER == Key)
          return CM_SELECT;

        elif(DLG_KEY_F9 == Key) 
          return CM_SELECT;
        end;
     end;
  end;



  AddCol (col2, 0, "plat","Вид платежа", 11);
  AddCol (col2, 1, "dat","Дата изменения", 12);
  AddCol (col2, 2, "oper","Автор редакции", 12);
  AddCol (col2, 3, "sfiid","Валюта", 5);
  AddCol (col2, 4, "dat1","Дата платежа", 25);
  AddCol (col2, 5, "amount1","Cумма", 30);
  AddCol (col2, 6, "kod1","Код Банка отправителя",45);
  AddCol (col2, 7, "kod11","Код Банка получателя",45);


     sss=" ESC- Выход " ;
     while(RunScroll(cmd2, 8, col2, null, @EvProc22,zag,sss, null, 0, 0,200,100) )
     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );
    end;

end;

MACRO ACC_SDEL(pa1)
     private var vsdel,datpr;

     datpr=СДАТ0({curdate});
     sql0="select  t_account pId2,t_account acc, (select aa.t_ccy from dfininstr_dbt aa where aa.t_fiid=t_currency) nfiid,(case when t_currency =0 then ";
     sql0=sql0+" to_char(rsb_account.resta(t_account, '"+datpr+"', t_chapter, 0),'999,999,999,999.00')  else   to_char(rsb_account.restac(t_account, t_currency, '"+datpr+"', t_chapter, 0),'999,999,999,999.00') ";
     sql0=sql0+"  end ) su  from dmcaccdoc_dbt  where  t_docid="+pa1+" and   t_dockind=102 and (t_catid=111 or t_catid=117 or t_catid=118)"; 
     //  msgbox(sql0);
     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );
  macro EvProc2 (rs0, cmd2, id, key )
     if (cmd2 == DLG_INIT)	// Инициализация
        rs0.MoveFirst();          
        if (pId2 != "0")  // Надо найти запись
           while ( (rs0.value ("pId2") != pId2) And (Not rs0.EOF) )  
              rs0.Move(1, RELATIVE);
            end;
        end;
        GoToScroll(rs0, true);

     elif (cmd2 == DLG_KEY)
        pId2=rs0.value ("pId2");
        if(DLG_KEY_ENTER == Key)
        elif(DLG_KEY_F9 == Key) 
          return CM_SELECT;
        end;
     end;
  end;


     AddCol (col2, 0, "acc","Счет", 20);
     AddCol (col2, 1, "nfiid","Вал", 3);
     AddCol (col2, 2, "su","Cумма остатка", 20);
     sss=" ESC- Выход " ;
     while(RunScroll(cmd2, 3, col2, null, @EvProc2,"Счета по сделке на "+datpr,"ESC- Выход", null,10,20,0,0) )
     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );
    end;

END;

MACRO PROL_SDEL(pa1,pa2,pa3,pa4,pa5)
     private var vsdel;
     if ( pa2 == 12300  )
         vsdel="Привлечения";
     else
         vsdel="Размещения";
     end;


     datpr={curdate};
     getdate(datpr,"Дата пролонгации",10);
     // datpr=СДАТ0({curdate});

     datpr=СДАТ0(datpr);

     zag="Возможные сделки для пролонгации сделки "+vsdel+" с контрагентом "+Fx_kontr(pa1,1);
     sql0="select a.t_dealid pId2 , a.t_dealcodets dealcodets, (select aa.t_ccy from dfininstr_dbt aa where aa.t_fiid=e.t_pfi) nfiid,e.t_price/100 price, e.t_cost cost,";
     sql0=sql0+ " (select distinct(a1.t_account) from  dmcaccdoc_dbt a1, dmccateg_dbt b1 where a1.t_dockind=102   and a1.t_docid=a.t_dealid and a1.t_catid=b1.t_id and b1.t_code='ОД' and rownum=1 ) schod, ";

     if ( pa2 == 12300  )
       sql0=sql0+ " (select distinct(a1.t_account) from  dmcaccdoc_dbt a1, dmccateg_dbt b1 where a1.t_dockind=102   and a1.t_docid=a.t_dealid and a1.t_catid=b1.t_id and b1.t_code='-% к погашению МБК' ) schp, ";
     else
       sql0=sql0+ " (select distinct(a1.t_account) from  dmcaccdoc_dbt a1, dmccateg_dbt b1 where a1.t_dockind=102   and a1.t_docid=a.t_dealid and a1.t_catid=b1.t_id and b1.t_code='+% к погашению МБК' ) schp, ";
     end;

     sql0=sql0+ "  c.t_shortname nam,a.t_dealcode dealcode ,e.t_maturity maturity, e.t_start nstart,e.t_principal su,to_char(e.t_maturity-e.t_start,'9999') srok";
     sql0=sql0+ "  from ddl_tick_dbt a ,  dparty_dbt c,  ddl_leg_dbt e ";
     // sql0=sql0+ "  where  e.t_dealid=a.t_dealid and c.t_partyid=a.t_partyid and e.t_maturity='"+datpr+"' and e.t_principal="+pa5+" and a.t_dealid != "+pa4; 
     sql0=sql0+ "  where  e.t_dealid=a.t_dealid and c.t_partyid=a.t_partyid and e.t_maturity='"+datpr+"' and  a.t_dealid != "+pa4; 

     sql0=sql0+ " and a.t_partyid= "+pa1+" and a.t_dealtype="+pa2+" and e.t_pfi="+pa3;
     //  msgbox(sql0);
     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );



  macro EvProc2 (rs0, cmd2, id, key )

     if (cmd2 == DLG_INIT)	// Инициализация
        rs0.MoveFirst();          

        if (pId2 != "0")  // Надо найти запись
           while ( (rs0.value ("pId2") != pId2) And (Not rs0.EOF) )  
              rs0.Move(1, RELATIVE);
            end;
        end;
        GoToScroll(rs0, true);

     elif (cmd2 == DLG_KEY)
        pId2=rs0.value ("pId2");
 
        if(DLG_KEY_ENTER == Key)
          if(DLG_KEY_ENTER == Key)  
            nflag=rs0.value ("pId2");
            return CM_CANCEL;
          end;



        elif(DLG_KEY_F9 == Key) 
          return CM_SELECT;
        end;
     end;
  end;


  AddCol (col2, 0, "dealcode","№ сделки", 8);
  AddCol (col2, 1, "dealcodets","Внеш № сделки", 8);
  AddCol (col2, 2, "nstart","Дата начала", 10);
  AddCol (col2, 3, "maturity","Дата окончания", 13);
  AddCol (col2, 4, "srok","Срок", 4);
  AddCol (col2, 5, "su","Cумма сделки", 15);
  AddCol (col2, 6, "nfiid","Вал", 3);
  AddCol (col2, 7, "price","Cтавка %%", 9);
  AddCol (col2, 8, "cost","Cумма %% ", 12);
  AddCol (col2, 9, "schod","Л/с по учету ОД", 18);
  AddCol (col2, 10, "schp","Л/с по учету %%", 18);
     sss=" ESC- Выход " ;
     while(RunScroll(cmd2, 11, col2, null, @EvProc2,zag,sss, null, 5, 15,122,45) )
     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );
    end;

end;

macro ChangePayms(paymentid, paymstatus, sum, newpaymid)
   var paym      = Tbfile( "pmpaym.dbt", "W" );
   var paymprop  = Tbfile( "pmprop.dbt", "W" );
   var paymprop2 = Tbfile( "pmprop.dbt", "W" );
   var pmrmprop  = Tbfile( "pmrmprop.dbt", "W" );
   var stat=true, Delta=$0;
   paym.rec.PaymentID = paymentid;
   if (not paym.GetEQ())
      return false;
   end;

   // если пролонгация полная, то просто меняем статус платежа
   if (sum == paym.rec.FUTUREPAYERAMOUNT)
      paym.rec.PAYMSTATUS = paymstatus;
      if (not paym.Update())
         return false;
      end;
      return true;
   else  // иначе меняем сумму платежа и дальше формируем новый платеж
      Delta = paym.rec.BASEAMOUNT-sum;
      paym.rec.AMOUNT =
      paym.rec.BASEAMOUNT =
      paym.rec.PAYAMOUNT =
      paym.rec.FUTUREPAYERAMOUNT =
      paym.rec.FUTURERECEIVERAMOUNT = Delta;
      if (not paym.Update())
         return false;
      end;
   end;
   
   paymprop.rec.PaymentID = paymentid;
   paymprop.rec.DebetCredit = 0;
   if (not paymprop.GetEQ())
      return false;
   end;

   paymprop2.rec.PaymentID = paymentid;
   paymprop2.rec.DebetCredit = 1;
   if (not paymprop2.GetEQ())
      return false;
   end;

   pmrmprop.rec.PaymentID = paymentid;
   if (not pmrmprop.GetEQ())
      return false;
   end;
                        
//  новый платеж
   paym.rec.PAYMENTID = 0;  
   paym.rec.VALUEDATE=datpr;

   paym.rec.AMOUNT =
   paym.rec.BASEAMOUNT =
   paym.rec.PAYAMOUNT =
   paym.rec.FUTUREPAYERAMOUNT =
   paym.rec.FUTURERECEIVERAMOUNT = sum;
   paym.rec.userfield1="";
   paym.rec.userfield2="";
   paym.rec.PAYMSTATUS = paymstatus;

   stat = paym.insert;
   if (not stat)
      return false;
   end;

//debet

   paymprop.rec.PAYMENTID = paym.rec.PAYMENTID;
   paymprop.rec.DEBETCREDIT = 0;
   paymprop.rec.TRANSFERDATE = paym.rec.VALUEDATE;
   stat = paymprop.insert;
   if (not stat)
      return false;
   end;
//credit
   paymprop2.rec.PAYMENTID = paym.rec.PAYMENTID ;
   paymprop2.rec.DEBETCREDIT = 1;
   paymprop2.rec.TRANSFERDATE = paym.rec.VALUEDATE;                
   stat = paymprop2.insert;
   if (not stat)
      return false;
   end;
//Реквизиты платежа         

   pmrmprop.rec.PAYMENTID = paym.rec.PAYMENTID ;
   pmrmprop.rec.DATE = 
   pmrmprop.rec.PAYDATE = 
   pmrmprop.rec.CLIENTDATE = datpr;
   stat = pmrmprop.insert;
   if (not stat)
      return false;
   end;

   SetParm(4, paym.rec.PAYMENTID);

   return stat;
end;

PRIVATE MACRO PROL_PM( )
   private  var que, rs, rs2, newpaymid = 0, dealid=nflag;
   que = "select * from dpmpaym_dbt where t_dockind=102 and t_purpose=10 and t_documentid ="+ string(DealId) + " and t_paymstatus=" + PM_READIED; 
   rs = LnGetRecordSet(que);
   if (rs.movenext())
      return ChangePayms(rs.value("t_paymentid"), PM_CARRYED_OUT_TO_PROLONG, su, newpaymid);
   end;
   
   return true; 
end;

macro _Create_pr()
   var stat=0;
   oprdocs.Clear; //SVE 30.07.2020 513741 
   oprdocs.rec.DOCKIND     =102;
   oprdocs.rec.DOCUMENTID  =docid;
   oprdocs.rec.ID_OPERATION=idop;
   //oprdocs.rec.ID_STEP= 6;    //SVE 20.05.2021 527240
   oprdocs.rec.PART   =2;
   stat = oprdocs.insert;   
   if (not stat)      
      RunError( "Ошибка при создании новой сделки 10" );
   end;
   
   if (not PROL_PM())
      RunError( "Ошибка при пролонгации платежей" );
   end;
   
   OnError( RslErrObj ) //А если ошибка - заполняем коммент
   Comment = RslErrObj.Message;      
   AbortTrn();
end;


MACRO ПРОЛОНГАЦИЯ(pa1)
    private var rez=0,ss,rs;
    ss=string(pa1);
    que = "select b.t_DocumentID from doprdocs_dbt a, doproper_dbt b where a.t_id_operation=b.t_id_operation and a.t_dockind=102 and b.t_dockind=102 and a.t_DocumentID=lpad('"+ss+"',34,'0')";
    rs = LnGetRecordset(que);
    if(rs != null)
      if (rs.moveNext) 
         rez=int(rs.value(0));
      end;
    end;
    return rez;
END;


MACRO SDEL_PROL(ndealid)
    private var que,rs5,rez=0;
       que = "select to_number(a.t_DocumentID) from doprdocs_dbt a, doproper_dbt b where a.t_id_operation=b.t_id_operation and a.t_dockind=102 and b.t_dockind=102 and b.t_DocumentID=lpad("+ndealid+",34,'0') and a.t_DocumentID != b.t_DocumentID";
       rs5 = LnGetRecordset(que);
       if(rs5 != null)
         if (rs5.moveNext) 
             rez=int(rs5.value(0));
         end;
       end;
       return rez;
END;

MACRO NEW_PROL(ndealid)
   private var npartyid,ndealtype,npfi,fflag,rs21,rs22,su0,v_money;

   fflag=Fx_tick(ndealid,"flag1",1);
   if ( fflag == "X" )
      msgbox("Сделка уже пролонгирована !");
      return;
   end;

   npartyid=Fx_tick(ndealid,"partyid",1);
   ndealtype=Fx_tick(ndealid,"dealtype",1);
   npfi=Fx_leg(ndealid,"pfi",1);
   su=Fx_leg(ndealid,"principal",1);

   nflag=0;
   PROL_SDEL(npartyid,ndealtype,npfi,ndealid,su);
   if ( nflag > 0)
     que="select t_id_operation,lpad("+ndealid+",34,'0')  from doproper_dbt where t_dockind=102 and t_DocumentID=lpad("+nflag+",34,'0')";
     rs21 = LnGetRecordSet(que);
     if(rs21 != null)
       if (rs21.moveNext)
         idop=rs21.value(0);
         docid=rs21.value(1);
         if (ProcessTrn(0,"_Create_pr"))
      //  if (_Create_pr() )
             //PaymMainSummUpd(nflag, su);        /*SVE 537390 28.01.2022 при полной пролонгации нужно также обновлять по предоставлению средств, чтобы он не исполнялся с проводкой*/
             su0=Fx_leg(nflag,"principal",1);
             if ( su  <  su0 )
                v_money=su;
                if ( SetNoteDifValue( nflag, 102, v_money) == 1)
              	  msgbox("НЕВЕРНО ВЫБРАНА СДЕЛКА !");
              	  return;                  	
                end;
            end;

             que="update ddl_tick_dbt set t_flag1='X' where t_dealid="+ndealid;
             rs22 = LnGetRecordSet(que);

             que="update ddl_tick_dbt set t_numberpack = 901 where t_dealid="+nflag;
             rs22 = LnGetRecordSet(que);

             MM_LinkAccounts(102, nflag, ndealid);

             /*
             que = "update dpmpaym_dbt SET t_paymstatus = 55 where t_paymstatus < 32000 and t_purpose = 10 and t_dockind=102 and t_documentid="+nflag;
             rs22 = LnGetRecordSet(que);*/
             msgbox("На сделке проставлен признак пролонгации !");



         else
             msgbox("Сделка не загружена");
             MSGBOX(Comment);
             return false;
         end;


       end;
     end;
  end;

END;


MACRO NEW_PROL2(ndealid)
   private var npartyid,ndealtype,npfi,fflag,rs21,rs22,su,su0,v_money;
   nflag=(ПРОЛОНГАЦИЯ(ndealid));

   que="update ddl_tick_dbt set t_numberpack = 0 where t_dealid="+nflag;
   rs22 = LnGetRecordSet(que);

   v_money = Fx_leg(nflag,"principal",1);

   que = "delete from dpmpaym_dbt where t_paymstatus = " + PM_CARRYED_OUT_TO_PROLONG + " and t_purpose = 10 and t_dockind=102 and t_baseamount != " + v_money + " and t_documentid="+nflag;
   rs22 = LnGetRecordSet(que);

   que = "update dpmpaym_dbt SET t_paymstatus = 1000 where t_paymstatus = " + PM_CARRYED_OUT_TO_PROLONG + " and t_purpose = 10 and t_dockind=102 and t_documentid="+nflag;
   rs22 = LnGetRecordSet(que);
 
   //PaymMainSummUpd( nflag, v_money );
   que = "update dpmpaym_dbt SET t_amount = " + v_money + " , t_baseamount = " + v_money + ",  t_payamount = " + v_money + ", t_futurebaseamount = " + v_money + ", t_FUTUREPAYERAMOUNT = " + v_money + ", t_FUTURERECEIVERAMOUNT = " + v_money;
   que=que+" where t_purpose = 10 and t_dockind=102 and t_documentid="+nflag; 
   rs22 = LnGetRecordSet(que);
   if ( SetNoteDifValue( nflag, 102, 0) == 1  )
   end;

   que="update ddl_tick_dbt set t_flag1=chr(0) where t_dealid="+ndealid;
   rs22 = LnGetRecordSet(que);
//SVE необходимо удалять записи из doprdocs_dbt при снятии признака пролонгации
   que = "delete from doprdocs_dbt where t_documentid = LPAd(" + ndealid + ", 34, '0') and t_dockind = 102 ";
   rs22 = LnGetRecordSet(que);

   que = "delete from dmcaccdoc_dbt where t_dockind = 102 and t_docid = " + ndealid;
   rs22 = LnGetRecordSet(que);

   msgbox("Признак пролонгации снят !");
END;

MACRO NEW_PROL3(ndealid)
   private var npartyid,ndealtype,npfi,fflag,rs21,rs22,su,su0,v_money;


             nflag=ndealid;

             que="update ddl_tick_dbt set t_numberpack = 0 where t_dealid="+nflag;
             rs22 = LnGetRecordSet(que);

             que = "update dpmpaym_dbt SET t_paymstatus = 1000 where t_paymstatus = 55 and t_purpose = 10 and t_dockind=102 and t_documentid="+nflag;
             rs22 = LnGetRecordSet(que);


             v_money = Fx_leg(nflag,"principal",1);
 
             PaymMainSummUpd( nflag, v_money );
             if ( SetNoteDifValue( nflag, 102, 0) == 1  )
             end;



END;


MACRO KL_SDEL(dealcode)

     dealid=MM_tick(dealcode,"dealid");
     dealtype=MM_tick(dealcode,"dealtype");
     if ( dealtype == 12305 )
       ndealid= 2306;
     else
       ndealid= 2301;
     end;

     zag="Сделка "+dealcode+" по Кредитной линии";
     sql0="select a.t_dealid pId2 ,  a.t_dealcode dealcode, a.t_dealdate dealdate ,  (select b.t_dealcode from ddl_tick_dbt b where b.t_parentid= a.t_dealid and b.t_dealcode='"+dealcode+"') sdel,";
     sql0=sql0+" (select b.t_dealdate from ddl_tick_dbt b where b.t_parentid= a.t_dealid and b.t_dealcode='"+dealcode+"') dasdel  from ddl_tick_dbt a  where a.t_bofficekind=208 and a.t_dealtype="+ndealid;

     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );



  macro EvProc2 (rs0, cmd2, id, key )

     if (cmd2 == DLG_INIT)	// Инициализация
        rs0.MoveFirst();          

        if (pId2 != "0")  // Надо найти запись
           while ( (rs0.value ("pId2") != pId2) And (Not rs0.EOF) )  
              rs0.Move(1, RELATIVE);
            end;
        end;
        GoToScroll(rs0, true);


     elif (cmd2 == DLG_KEY)
        pId2=rs0.value ("pId2");
 
        if(DLG_KEY_ENTER == Key)


          que="update ddl_tick_dbt set t_parentid="+pId2+" where  t_dealid="+dealid; 
          rs5 = LnGetRecordSet(que);
          return CM_SELECT;

        elif(DLG_KEY_F9 == Key) 
          return CM_SELECT;
        end;
     end;
  end;


  AddCol (col2, 0, "dealcode","№ Кредитной линии", 15);
  AddCol (col2, 1, "dealdate","Дата Кредитной линии", 20);
  AddCol (col2, 2, "sdel","Cделка", 15);
  AddCol (col2, 3, "dasdel","Дата сделки", 15);

     sss=" ENTER- Прекрепить сделку к КЛ   ESC- Выход " ;
     while(RunScroll(cmd2, 4, col2, null, @EvProc2,zag,sss, null, 5, 15,122,45) )
     cmd2 = RSDRecordset(sql0 , RSDVAL_CLIENT, RSDVAL_STATIC );
    end;


end;


