/*
Leplin 
Вставка текста согласования при досрочном закрытии депозита
T_OBJECTTYPE - Вид объекта (Сделка МБК=103)
T_NOTEKIND   - Тип пользовательского примечания для вида объекта =101
*/

import /* Simanov. Избавляемся от библиотеки CommonInter, */RSD, globals, funk;

macro makenote( DealId )

  private var T_DOCUMENTID,T_TEXT, cmd, que1;
  private var que, que0, rs0;
  const T_OBJECTTYPE= 103,
        T_NOTEKIND  = 101,
        T_DATE ={curdate},
        T_OPER={oper},
	 T_BRANCH={NumDprt};
  record tick( dl_tick );


  T_DOCUMENTID = DealID; 


  GetString(T_TEXT, "Введите текст согласования с ЦБ РФ!",128 , 5);

  que0=" from dnotetext_dbt where t_objecttype="+String(T_OBJECTTYPE)+" and t_notekind="+String(T_NOTEKIND)+" and t_documentid=lpad("+dealid+",34,'0') ";
  que="select count(*)"+que0; 
  rs0 = LnGetRecordSet(que);
  if(rs0 != null)
     if (rs0.moveNext) 
        if ( rs0.value(0) > 0 )
          que1 = " UPDATE DNOTETEXT_DBT  SET  T_TEXT=utl_raw.cast_to_raw(?), T_DATE=trunc(?) " + 
                 " WHERE T_OBJECTTYPE=? AND T_DOCUMENTID=LPAD(?, 34, '0') AND T_NOTEKIND=?"; 
          cmd = RSDCommand(que1); 
         
          cmd.addParam("", RSDBP_IN, T_TEXT);
          cmd.addParam("", RSDBP_IN, T_DATE);
	  cmd.addParam("", RSDBP_IN, T_OBJECTTYPE);
          cmd.addParam("", RSDBP_IN, T_DOCUMENTID);
	  cmd.addParam("", RSDBP_IN, T_NOTEKIND);
          cmd.execute();
	  return 0;

        else 
/*
	  que1 = " INSERT INTO DNOTETEXT_DBT  ( T_OBJECTTYPE, T_DOCUMENTID, T_NOTEKIND, T_OPER, T_DATE, T_TIME, T_TEXT, T_VALIDTODATE, T_BRANCH, T_NUMSESSION )" + 
                 " VALUES "+
                 "  ( ?, LPAD(?, 34, '0'), ?, ?, trunc(?), to_date('01010001'||to_char(sysdate,'hhmiss'),'DDMMYYYYhhmiss'), utl_raw.cast_to_raw(?), to_date('31129999','DDMMYYYY'), ?, 0 )"; 
          cmd = RSDCommand(que1);

	  cmd.addParam("", RSDBP_IN, T_OBJECTTYPE);
          cmd.addParam("", RSDBP_IN, T_DOCUMENTID);
	  cmd.addParam("", RSDBP_IN, T_OPER);
          cmd.addParam("", RSDBP_IN, T_DATE);
	  cmd.addParam("", RSDBP_IN, T_NOTEKIND);
          cmd.addParam("", RSDBP_IN, T_TEXT);
          cmd.execute();
*/
	  msgbox("Отсутствует примечание о согласовании с ЦБ РФ на сделке!");
  	  return 1;
 
        end;
     end;
  end;

end;


/*
INSERT INTO DNOTETEXT_DBT ( T_OBJECTTYPE, T_DOCUMENTID, T_NOTEKIND, T_OPER, T_DATE, T_TIME, T_TEXT, T_VALIDTODATE, T_BRANCH, T_NUMSESSION ) 
VALUES 
( v_NoteText.T_OBJECTTYPE, v_NoteText.T_DOCUMENTID, v_NoteText.T_NOTEKIND, v_NoteText.T_OPER, v_NoteText.T_DATE, v_NoteText.T_TIME, v_NoteText.T_TEXT,
                                     v_NoteText.T_VALIDTODATE, v_NoteText.T_BRANCH, v_NoteText.T_NUMSESSION );
*/

