/*
$Name:         scrou0515.mac
$Module:       Ценные бумаги
$Description:  не используется
*/
/* Операция РЕПО без признания ц/б (не ОРЦБ)
   Оплата по 2 ч     */

import InsCarryDoc, "sp_class.mac", "sp_car.mac", "sp_cars.mac";

macro ExecuteStep( doc, FDoc)
  record  deal(dl_tick);
  var FD, dat, FD1, Dp, Dp1, Dknext;
  var PayerAccountBuff = TRecHandler( "account" );
  var ReceiverAccountBuff = TRecHandler( "account" );
  var Amount, PayAmount;
  var PayAmount1 = $0, PercAmount1 = $0;
  var PayAmount2 = $0, PercAmount2 = $0;
  var rq_money = TRecHandler("dlrq.dbt");
  var rq_pc = TRecHandler("dlrq.dbt");

  SetBuff( deal, FDoc ); 
  FD = SPFirstDoc( deal, true );
  FD1 = SPFirstDoc( deal, false );

  if( FD.БылОтказОтИсполнения() != false )
     return 0;
  end;

  if( FD1.БылОтказОтИсполнения() != false )
     return 0;
  end;

  GetOprDate( FD.GetKindDate(DATE_DEALPAY), dat );

  rq_money = FD.GetRQ(DLRQ_TYPE_PAYMENT);

  if(FD.ExistPC)
    rq_pc = FD.GetRQ(DLRQ_TYPE_INCREPO);
  else
    rq_pc.Clear();
  end;

  if( ПроверитьТОНаПросроченность( rq_money, "оплате" ) == false )
     return 1;
  end;

  
  if(УстановитьСтатусТО(rq_money, DLRQ_STATE_EXEC, Dat) != 0)
    return 1;
  end;

  if(FD.ExistPC)
    if(УстановитьСтатусТО(rq_pc, DLRQ_STATE_EXEC, dat) != 0)
      return 1;
    end;
  end;

  return 0;
end;
