/*
$Name:         scrou0805.mac
$Module:       Ценные бумаги
$Description:  не используется
*/
/* Операция РЕПО без признания ц/б (не ОРЦБ)
   Закрытие offline    */

import InsCarryDoc, "scservop.mac";

macro ExecuteStep( doc, FDoc)
  record  deal(dl_tick);
  var FD;
  var     CloseAccArray = DL_AccCollector,
          ErrMsgArray   = DL_TUniqStrCollector;
  var     dat;

  SetBuff( deal, FDoc ); 

  FD = SPFirstDoc( deal, false );

  if( FD.IsOldDeal() )
     return 0;
  end;

  //Если по сделке есть ТО со статусами "Отложено", "Запланировано", "Просрочено", "Исполнение отложено" - то ошибка.
  if( FD.ЕстьНеиспТО() )
     return SayErrorBuySale( deal,"Обработаны не все ТО по сделке" );
  end;

/*!!! здесь должен быть основной код шага*/

  GetOprDate( DATE_DEALEEND_2, dat );

  if( DL_CloseAccountByDeal(deal.DealID,deal.BofficeKind,dat,CloseAccArray,ErrMsgArray) )
     if( ErrMsgArray.Size() > 0 )
        return SayErrorBuySale( deal, ErrMsgArray, true );
     else
        return SayErrorBuySale( deal, "Ошибка при закрытии счетов по сделке." );
     end;
  end;

  SaveDataCloseAccArray(deal,CloseAccArray);

  /*ДО = "Закрыт"*/
  if( not InsertOprStatus( SP_OPERSTATUS_SECURDEALS_DO, SP_OPERSTATUS_SECURDEALS_DO_CLOSE) ) 
     msgbox( "Ошибка при установке статуса <Документооборот> операции" );
     return 1;
  end;

  if( not InsertOprStatus( SP_OPERSTATUS_SECURDEALS_ZF, SP_OPERSTATUS_SECURDEALS_ZF_FINISH) ) 
     msgbox( "Ошибка при установке статуса <Закрытие offline> операции" );
     return 1;
  end;

  return 0;
end;
