
import Oralib;

CLASS MenuItem()
  var ObjectID,
      isTemplate,
      iIdentProgram,
      iNumberPoint,
      iNumberFather,
      iNumberLine,
      iCaseItem,
      cSystemItem,
      szNameItem,
      szNamePrompt,
      iHelp,
      iProgItem,
      cIdentProgram,
      Parm;
END;

CLASS TreeMenuItem()
  var Items = TArray();

  Macro GetTreeFromItemByAbsolut(r_ObjectID, r_isTemplate, r_iIdentProgram, r_iNumberPoint)
    var is;
    var stmp = "", itmp;
    var sqlreq, rs;

    if (r_isTemplate == "X")
        sqlreq = "select * " +
                 "from DMENUITEM_DBT " +
                 "where T_ObjectID = :1 and " +
                       "nvl(T_isTemplate,chr(0)) = 'X' and " +
                       "T_iIdentProgram = :3 and " +
                       "T_iNumberPoint = :4";
        rs = execSQLselectPrm(sqlreq,
                              SQLParam("1", r_ObjectID),
                              SQLParam("3", r_iIdentProgram),
                              SQLParam("4", r_iNumberPoint)
                             );
    else
        sqlreq = "select * " +
                 "from DMENUITEM_DBT " +
                 "where T_ObjectID = :1 and " +
                       "nvl(T_isTemplate,chr(0)) = chr(0) and " +
                       "T_iIdentProgram = :2 and " +
                       "T_iNumberPoint = :3";
        rs = execSQLselectPrm(sqlreq,
                              SQLParam("1", r_ObjectID),
                              SQLParam("2", r_iIdentProgram),
                              SQLParam("3", r_iNumberPoint)
                             );
    end;

    if(rs and rs.moveNext())
      is = Items.Size();
      Items[is] = MenuItem();
      Items[is].ObjectID      = rs.Value("T_ObjectID");
      Items[is].isTemplate    = rs.Value("T_isTemplate");
      Items[is].iIdentProgram = rs.Value("T_iIdentProgram");
      Items[is].iNumberPoint  = rs.Value("T_iNumberPoint");
      Items[is].iNumberFather = rs.Value("T_iNumberFather");
      Items[is].iNumberLine   = rs.Value("T_iNumberLine");
      Items[is].iCaseItem     = rs.Value("T_iCaseItem");
      Items[is].cSystemItem   = rs.Value("T_cSystemItem");
      Items[is].szNameItem    = rs.Value("T_szNameItem");
      Items[is].szNamePrompt  = rs.Value("T_szNamePrompt");
      Items[is].iHelp         = rs.Value("T_iHelp");
      Items[is].iProgItem     = rs.Value("T_iProgItem");

      Items[is].cIdentProgram = strfor(rs.Value("T_iIdentProgram"));

      if (is == 0)
        var p2;
        if (r_isTemplate == "X")
          p2 = "'X'";
        else
          p2 = "chr(0)";
        end;
        
        sqlreq = "select T_ObjectID, T_isTemplate, T_cIdentProgram, T_iNumberPoint,  " +
                 " T_Parm " + 
//                 "rsb_struct.getString(TO_BLOB(NVL(t_Parm, UTL_RAW.cast_to_raw(LPAD(CHR(0), 300, CHR(0)))))) as T_Parm " +
//                                   "(TO_BLOB(NVL(t_Parm, UTL_RAW.cast_to_raw(LPAD(CHR(0), 300, CHR(0)))))) as T_Parm " +
                 "from DMENUPARM_DBT " +
                 "where T_ObjectID = :1 and " +
                       "nvl(T_isTemplate,chr(0)) = " + p2 + " and " +
                       "T_cIdentProgram = :3 and " +
                       "T_iNumberPoint = :4";
        rs = execSQLselectPrm(sqlreq,
                              SQLParam("1", r_ObjectID),
                              SQLParam("3", Items[is].cIdentProgram),
                              SQLParam("4", r_iNumberPoint)
                             );
        if(rs and rs.moveNext())

          for (itmp,1,strlen(rs.Value("T_Parm")))
            stmp = stmp + string(codefor(substr(rs.Value("T_Parm"),itmp,1)):x);
          end;
          for (itmp,0,700)
            stmp = stmp + "0";
          end;

          Items[is].Parm = substr(stmp,1,600);

        end;
      end;

      if (Items[is].iNumberFather != 0)
        GetTreeFromItemByAbsolut(r_ObjectID, r_isTemplate, r_iIdentProgram, Items[is].iNumberFather);
      end;



    end;
  End;

  Macro CreateMenuTreeItem(DestObject, i, nf)
    var p1, p2;
    if (Items[i].cSystemItem == "X")
      p1 = "'X'";
    else
      p1 = "chr(0)";
    end;

    var sqlreq = "insert into DMENUITEM_DBT " +
                 "(T_ObjectID," +
                 " T_isTemplate," +
                 " T_iIdentProgram," +
                 " T_iNumberPoint," +
                 " T_iNumberFather," +
                 " T_iNumberLine," +
                 " T_iCaseItem," +
                 " T_cSystemItem," +
                 " T_szNameItem," +
                 " T_szNamePrompt," +
                 " T_iHelp," +
                 " T_iProgItem)" +
                 "values (" +
                           string(DestObject.ObjectID) +","+
                           DestObject.isTemplate +","+
                           string(Items[i].iIdentProgram) +","+
                           " (select nvl(max(T_iNumberPoint)+1,1) from DMENUITEM_DBT" +
                           "  where T_ObjectID = " + string(DestObject.ObjectID) +
                           "  and T_isTemplate = " + DestObject.isTemplate + 
                           "  and T_iIdentProgram = " + string(Items[i].iIdentProgram) + 
                           " )," +
                           string(nf) +","+                     // Items[i].iNumberFather
                           string(Items[i].iNumberLine) +","+   // <-- доработать
                           string(Items[i].iCaseItem) +","+
                           p1 + ","+
                           "'" + string(Items[i].szNameItem) +"',"+
                           "'" + string(Items[i].szNamePrompt) +"',"+
                           string(Items[i].iHelp) +","+
                           string(Items[i].iProgItem) +
                        ")";

     var mi = execSQL(sqlreq); 

     if (mi and (i == 0) and (Items[i].Parm != null))

       sqlreq = "insert into DMENUPARM_DBT " +
                "(T_OBJECTID, T_ISTEMPLATE, T_CIDENTPROGRAM, T_INUMBERPOINT, T_PARM) " +
                "values (" +
                          string(DestObject.ObjectID) +","+
                          DestObject.isTemplate +","+
                          "'" + string(Items[i].cIdentProgram) +"',"+
                          " (select max(T_iNumberPoint) from DMENUITEM_DBT" +
                          "  where T_ObjectID = " + string(DestObject.ObjectID) +
                          "  and T_isTemplate = " + DestObject.isTemplate + 
                          "  and T_iIdentProgram = " + string(Items[i].iIdentProgram) + 
                          " )," +
                          " '" + Items[i].Parm + "' " +
                       ")";
       mi = execSQL(sqlreq); 
     end;


  End;

  Macro DetectProgram(DestObject)
     var sqlreq;
     if (DestObject.isTemplate == "'X'")
       sqlreq = "select 1 from DMENUTPL_DBT " +
                "where T_MENUID = " + string(DestObject.ObjectID) + 
                " and T_IDENTPROGRAM like '%"+strfor(Items[0].iIdentProgram)+"%'";
     else
       sqlreq = "select 1 from DPERSON_DBT " +
                "where T_OPER = " + string(DestObject.ObjectID) + 
                " and T_szIDENTPROGRAM like '%"+strfor(Items[0].iIdentProgram)+"%'";
     end;
     return existsSQLselect(sqlreq);
  End;

  Macro TraceMenuTree(DestObject, i, nf)
    var p1, p2;
    if (Items[i].cSystemItem == "X")
      p1 = "'X'";
    else
      p1 = "chr(0)";
    end;
    var sqlreq = "select T_iNumberPoint " +
                 "from DMENUITEM_DBT " +
                 "where T_ObjectID = " + string(DestObject.ObjectID) +  
                  " and nvl(T_isTemplate,chr(0)) = " + DestObject.isTemplate +
                  " and T_iIdentProgram = " + string(Items[i].iIdentProgram) +
                  " and T_iNumberFather = " + string(nf) +                   //Items[i].iNumberFather),
                  " and (nvl(T_cSystemItem,chr(0)) = " + p1 + " or "               //Items[i].cSystemItem + "'"+
                  "       T_ICASEITEM = 0 )" +  // т.е. папка
                  " and trim(upper(T_szNameItem)) = '" + trim(strupr(string(Items[i].szNameItem))) + "'" +
                  " and T_iProgItem = " + string(Items[i].iProgItem);
    var rs = execSQLselectPrm(sqlreq);

    if (rs and rs.moveNext())
      i = i - 1;
      if (i >= 0)
        TraceMenuTree(DestObject, i, rs.value("T_iNumberPoint"));
      end;
    else
      CreateMenuTreeItem(DestObject, i, nf);
      if (i > 0)
        TraceMenuTree(DestObject, i, nf);
      end;
    end;  


  end;

  Macro CopyFor(DestObject)
    if (not DetectProgram(DestObject))
      println("Для ", DestObject.ObjectID," (",DestObject.isTemplate,")  не найдена подсистема ", strfor(Items[0].iIdentProgram) );
      return false;
    end;
    return TraceMenuTree(DestObject, Items.Size-1, 0);
  End;

END;

CLASS SourceItem(p1,p2,p3,p4)
  var ObjectID      = p1,
      isTemplate    = p2,
      iIdentProgram = p3,
      iNumberPoint  = p4;
END;

CLASS DestinationObject(p1,p2)
  var ObjectID      = p1,
      isTemplate    = p2;
END;

macro GetObjectIDByPartName(PartName, Type, DArr)
  var sqlreq, rs, is, isShablon;
  if (Type == "РОЛЬ")
    isShablon = "chr(0)";
    sqlreq = "select RU.T_OPER as ID " +
             "from DACSOPROLE_DBT ru left join DACSROLETREE_DBT rt on (RU.T_ROLEID = RT.T_ROLEID) " +
             "where RT.T_NAME like :1 " +
               "and RU.T_OPER >= :2 "
             ;
    rs = execSQLselectPrm(sqlreq,
                          SQLParam("1", PartName+"%"),
                          SQLParam("2", 1000)
                         );
  elif (Type == "ШАБЛОН")
    isShablon = "'X'";
    sqlreq = "select T_MENUID as ID " +
             "from DMENUTPL_DBT " +
             "where T_NAME like :1 "  +
               "and T_ISDISTRIBUTED = chr(0) "
             ;
    rs = execSQLselectPrm(sqlreq,
                          SQLParam("1", PartName+"%")
                         );

  else
    println("Неправильно указан тип объекта \"",Type,"\".  Копирования меню не будет.");
    return;
  end;

  while (rs and rs.moveNext())
    is = DArr.Size();
    DArr[is] =  DestinationObject(rs.Value("ID"), isShablon);
  end;
end;

macro FindChildren (Si, ObjectID, isTemplate, iIdentProgram, iNumberFather)
  var sqlreq, rs;
  if (isTemplate == "X")
      sqlreq = "select * " +
               "from DMENUITEM_DBT " +
               "where T_ObjectID = :1 and " +
                     "nvl(T_isTemplate,chr(0)) = 'X' and " +
                     "T_iIdentProgram = :2 and " +
                     "T_INumberFather = :3";
      rs = execSQLselectPrm(sqlreq,
                            SQLParam("1", ObjectID),
                            SQLParam("2", iIdentProgram),
                            SQLParam("3", iNumberFather)
                           );
  else
      sqlreq = "select * " +
               "from DMENUITEM_DBT " +
               "where T_ObjectID = :1 and " +
                     "nvl(T_isTemplate,chr(0)) = chr(0) and " +
                     "T_iIdentProgram = :2 and " +
                     "T_INumberFather = :3";
      rs = execSQLselectPrm(sqlreq,
                            SQLParam("1", ObjectID),
                            SQLParam("2", iIdentProgram),
                            SQLParam("3", iNumberFather)
                           );
  end;

  while(rs and rs.moveNext())

    // предварительно попробуем найти потомков
    if (not FindChildren (Si, ObjectID, isTemplate, iIdentProgram, rs.Value("T_iNumberPoint")))
      Si[Si.Size] = SourceItem(ObjectID, isTemplate, iIdentProgram, rs.Value("T_iNumberPoint"));
    end;

  end;

end;

macro FillSourceItems(Si, ObjectID, isTemplate, iIdentProgram, iNumberPoint)
  var sqlreq, rs;

  if (ValType(iNumberPoint) != V_undef)

    // предварительно попробуем найти потомков
    if (not FindChildren(Si, ObjectID, isTemplate, iIdentProgram, iNumberPoint))

      Si[Si.Size] = SourceItem(ObjectID, isTemplate, iIdentProgram, iNumberPoint);
      return;

    end;
  end;



  if (isTemplate == "X")
      sqlreq = "select * " +
               "from DMENUITEM_DBT " +
               "where T_ObjectID = :1 and " +
                     "nvl(T_isTemplate,chr(0)) = 'X' and " +
                     "T_iIdentProgram = :2";
      rs = execSQLselectPrm(sqlreq,
                            SQLParam("1", ObjectID),
                            SQLParam("2", iIdentProgram)
                           );
  else
      sqlreq = "select * " +
               "from DMENUITEM_DBT " +
               "where T_ObjectID = :1 and " +
                     "nvl(T_isTemplate,chr(0)) = chr(0) and " +
                     "T_iIdentProgram = :2";
      rs = execSQLselectPrm(sqlreq,
                            SQLParam("1", ObjectID),
                            SQLParam("2", iIdentProgram)
                           );
  end;

  while(rs and rs.moveNext())
    Si[Si.Size] = SourceItem(ObjectID, isTemplate, iIdentProgram, rs.Value("T_iNumberPoint"));
  end;

end;


/*****************************
    start
****************************/

var Si = TArray(), 
    SourceTree = TArray(),
    DestinationObjectList = TArray(),
    d, i, is;

/*
FillSourceItems(Si,1,  "", codefor("S"), 5220);
FillSourceItems(Si,1,  "", codefor("S"), 5633);
FillSourceItems(Si,1,  "", codefor("S"), 5634);
FillSourceItems(Si,1,  "", codefor("S"), 5635);
FillSourceItems(Si,1,  "", codefor("S"), 5637);
FillSourceItems(Si,1,  "", codefor("S"), 5711);
FillSourceItems(Si,1,  "", codefor("S"), 5729);
FillSourceItems(Si,1,  "", codefor("S"), 5730);
FillSourceItems(Si,1,  "", codefor("S"), 5731);
FillSourceItems(Si,1,  "", codefor("S"), 5248);
FillSourceItems(Si,1,  "", codefor("Ю"), 377);
FillSourceItems(Si,1,  "", codefor("Ю"), 21);
FillSourceItems(Si,1,  "", codefor("Ю"), 24);
FillSourceItems(Si,1,  "", codefor("Ю"), 22);
FillSourceItems(Si,1,  "", codefor("Ю"), 23);
FillSourceItems(Si,1,  "", codefor("Ы"), 100);
FillSourceItems(Si,1,  "", codefor("Ы"), 130);
FillSourceItems(Si,1,  "", codefor("Ы"), 160);
FillSourceItems(Si,1,  "", codefor("Ы"), 180);
FillSourceItems(Si,1,  "", codefor("Ы"), 200);
FillSourceItems(Si,1,  "", codefor("Ы"), 220);
FillSourceItems(Si,1,  "", codefor("Ы"), 240);
FillSourceItems(Si,1,  "", codefor("Ы"), 410);
FillSourceItems(Si,1,  "", codefor("Ы"), 430);
FillSourceItems(Si,1,  "", codefor("Ы"), 450);
FillSourceItems(Si,1,  "", codefor("Ы"), 616);
FillSourceItems(Si,1,  "", codefor("Ы"), 500);
FillSourceItems(Si,1,  "", codefor("Y"), 1088);
FillSourceItems(Si,1028,  "X", codefor("Г"), 1100);
FillSourceItems(Si,1,  "", codefor("J"), 4000);
FillSourceItems(Si,1,  "", codefor("Ю"), 225);
FillSourceItems(Si,1,  "", codefor("Ю"), 209);
FillSourceItems(Si,1,  "", codefor("Ю"), 226);
FillSourceItems(Si,1,  "", codefor("Ю"), 331);
FillSourceItems(Si,1,  "", codefor("Ю"), 116);
FillSourceItems(Si,1,  "", codefor("Ю"), 114);
FillSourceItems(Si,1,  "", codefor("S"), 5248);
FillSourceItems(Si,1,  "", codefor("S"), 5234);
FillSourceItems(Si,1,  "", codefor("S"), 5529);
FillSourceItems(Si,1,  "", codefor("S"), 5716);
FillSourceItems(Si,1,  "", codefor("S"), 5678);
FillSourceItems(Si,1,  "", codefor("S"), 5766);
FillSourceItems(Si,1,  "", codefor("S"), 13);
FillSourceItems(Si,1,  "", codefor("S"), 5321);
FillSourceItems(Si,1,  "", codefor("S"), 5512);
FillSourceItems(Si,1,  "", codefor("S"), 5568);
FillSourceItems(Si,1,  "", codefor("S"), 5651);
FillSourceItems(Si,1,  "", codefor("S"), 5653);

FillSourceItems(Si,1028,  "X", codefor("Y"), 1099);
FillSourceItems(Si,1028,  "X", codefor("J"), 5000);
FillSourceItems(Si,1026,  "X", codefor("Ы"), 6);
FillSourceItems(Si,1028,  "X", codefor("Ю"), 7);
*/

FillSourceItems(Si,1,  "", codefor("S"), 5890);





// РАСКОММЕНТИРОВАТЬ РОЛИ, ПОЛЬЗОВАТЕЛЯМ КОТОРЫХ ПРЕДНАЗНАЧЕНЫ ПУНКТЫ МЕНЮ

//GetObjectIDByPartName("[01] Специалист по операциям с векселями ДРРК (Контролер)",       "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[02] Специалист ДРРК по операциям с векселями",                   "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[03] Специалист по оформлению операций с векселями",              "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[04] Специалист по сопровождению и учёту операций с векселями",   "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[05] Специалист по учету и сопровождению операций залога",        "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[06] Специалист по оформлению залогов",                           "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[07] Специалист по отчётности Репозитария",                       "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[08] Налоговый менеджер",                                         "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[09] Специалист сопровождения для расчета налога ЮЛН",            "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[10] Прикладной администратор",                                   "РОЛЬ", DestinationObjectList);
GetObjectIDByPartName("[11] Специалист БУ ЦБ",                                           "РОЛЬ", DestinationObjectList);
GetObjectIDByPartName("[12] Специалист ЦБ",                                              "РОЛЬ", DestinationObjectList);
GetObjectIDByPartName("[13] Специалист БУ БО",                                           "РОЛЬ", DestinationObjectList);
GetObjectIDByPartName("[14] Специалист БО",                                              "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[15] Специалист БУ ПФИ",                                          "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[16] Специалист ПФИ",                                             "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[17] Специалист МБК",                                          "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[18] Специалист по сопровождению и учету операций с МБК ЕСЦ",     "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[19] Администратор операционного дня по операциям с ценными бум", "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[20] Администратор операционного дня по операциям вал.рын.и ПФИ", "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[24] Специалист по отчетности ПФИ",                               "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[25] Специалист по формированию отчетности ДО",                   "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[26] Специалист по формированию отчетности (ценные бумаги)",      "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[27] Контролёр ДКК",                                              "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[28] Аналитик",                                                   "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[33] Специалист ДРРК по брокерским операциям",                    "РОЛЬ", DestinationObjectList);
//GetObjectIDByPartName("[34] Специалист ДРРК по консультированию клиентов",               "РОЛЬ", DestinationObjectList);


//  РАСКОММЕНТИРОВАТЬ ОБРАЗЦЫ НАШИХ ПУНКТОВ МЕНЮ ДЛЯ РОЛЕЙ, ПОЛЬЗОВАТЕЛЯМ КОТОРЫХ ПРЕДНАЗНАЧЕНЫ ПУНКТЫ МЕНЮ
//  связь по номеру

//GetObjectIDByPartName("Полное меню",                                                                "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист ДРРК по операциям с векселями",                                   "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист РФ по оформлению операций с векселями",                           "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист по сопровождению и учёту операций с векселями",                   "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Экономист РФ",                                                               "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист по оформлению залогов",                                           "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист по отчётности Репозитария",                                       "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Налоговый менеджер",                                                         "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист сопровождения для расчета налога ЮЛН",                            "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Прикладной администратор",                                                   "ШАБЛОН", DestinationObjectList);
GetObjectIDByPartName("Специалист БУ ЦБ",                                                           "ШАБЛОН", DestinationObjectList);
GetObjectIDByPartName("Специалист ЦБ",                                                              "ШАБЛОН", DestinationObjectList);
GetObjectIDByPartName("Специалист БУ БО",                                                           "ШАБЛОН", DestinationObjectList);
GetObjectIDByPartName("Специалист БО",                                                              "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист БУ ПФИ",                                                          "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист ПФИ",                                                             "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист МБК",                                                             "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Администратор операционного дня по операциям с ценными бумагами",            "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Администратор операционного дня по операциям валютно-денежного рынка и ПФИ", "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Администратор информационной безопасности",                                  "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист по формированию отчетности ДО",                                   "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист по формированию отчетности (ценные бумаги)",                      "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Контролёр ДКК",                                                              "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Аналитик",                                                                   "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Просмотр МБК",                                                               "ШАБЛОН", DestinationObjectList);
//нет такого  образца пока//GetObjectIDByPartName("Аудитор",                                                    "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Работник отдела последующего контроля",                                      "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист ДРРК по брокерским операциям",                     "ШАБЛОН", DestinationObjectList);
//GetObjectIDByPartName("Специалист ДРРК по консультированию клиентов",                "ШАБЛОН", DestinationObjectList);


//GetObjectIDByPartName("Полное меню без лишних пунктов (временный образец для пользователя)",                  "ШАБЛОН", DestinationObjectList);
                                                                          

// НЕЗАБЫВАЕМ НАПОЛНИТЬ ПОЛЬЗОВАТЕЛЯ 1-КУ (это наполнение потом уходит на тестовую среду к R_Style)
//DestinationObjectList[DestinationObjectList.Size] =  DestinationObject(1, "chr(0)"); 
//DestinationObjectList[DestinationObjectList.Size] =  DestinationObject(9996, "chr(0)"); 
//DestinationObjectList[DestinationObjectList.Size] =  DestinationObject(9999, "chr(0)"); 
//DestinationObjectList[DestinationObjectList.Size] =  DestinationObject(1292, "chr(0)"); 


for (i, Si)
  is = SourceTree.Size;
  SourceTree[is] = TreeMenuItem();                                 	
  SourceTree[is].GetTreeFromItemByAbsolut(i.ObjectID, i.isTemplate, i.iIdentProgram, i.iNumberPoint);
end;

for (d,DestinationObjectList)
  for (i,SourceTree)  
    i.CopyFor(d);
  end;
end;

msgbox("ВЫПОЛНЕНО");
//exit (1);                                                                         
