import cb_sql;
import tsp;
import CheckRateLib;
import CheckRuDataLib;

macro CheckTransfRate ()
  var rs = RSDRecordset("Select RSBSessionData.curdate as curdate from dual");/*Аналогия {curdate} из globals (globals в startbnk.mac при запуске в безынтерфейсном режиме ведёт себя некорректно)*/
  var Curdate = Date();
  if (rs.movenext)
    Curdate = rs.value(0, null, V_DATE);
  end;

  var cmd = RsdCommand("select 1 from dvalintmarketrate_dbt where t_begindate >= ?");
  cmd.addParam("", RSDBP_IN, Curdate);
  cmd.execute();
  
  rs = RsdRecordset(cmd);

  if( not rs.MoveNext() )
    return "Не загружены трансфертные ставки на дату " + Curdate;
  end;
  return "";
onerror()
  return "";
End;

// DEF-40072
macro LabelExpireDate()
   var ErrCode, RegPath = "РСХБ\\ИНТЕГРАЦИЯ\\ДАТА_ИСТЕЧЕНИЯ_МЦ";
   var Val;
   var print_date = "";
   var warning_date;
   var default_date = date(04,03,2024);

   GetRegistryValue( RegPath, V_STRING, Val, ErrCode );

   if( ErrCode != 0 )
      //Это плохая ситуация. Создайте вышеуказанную настройку, чтобы не править макрос
      Val = default_date;
   else 
      Val = date(Val);
   end;
   if ( (ValType(Val) != V_DATE) or (Val == date(0,0,0)) ) // что же туда занесли?
      Val = default_date;
   end;

   // используем to_char, мы уже уверены, что параметр - дата
   // хотя неясно, зачем это надо
   var cmd = RSDCommand("select to_char(:pval,'yyyy-mm-dd'), add_months(:pval,-1) from dual");
   cmd.AddParam("pval", RSDBP_IN, Val); // конкретно здесь достаточно одного параметра
   var rs = RSDRecordSet(cmd);
   if (rs.movenext)
      print_date = rs.value(0);
      warning_date = rs.value(1);
   end;
   SetParm(0, print_date);

   return warning_date;
end;

//println();
macro WorkBegin()
//   var ver = "", Dt = TRsbDataSet("select t_ver||'.'||t_rel||'.'||t_build||'.'||t_patch||'('||t_update||')' rsver from dsetupdat_dbt where t_datesetup = ( select max(t_datesetup) from dsetupdat_dbt)");
//   if (Dt.movenext())
//      ver = Dt.rsver;
//   end;
//   msgbox("РОССЕЛЬХОЗБАНК | СОФР. ПРОДУКТИВНАЯ СРЕДА. | Будьте внимательны при вводе бизнес-данных | " + ver);

  var mes = "";
//DEF-40072
  var print_date,warning_date;
  warning_date = LabelExpireDate(print_date);
  if ( (index (";1;9990;9991;9995;9996;9999;", ";"+{oper}+";")) and
       (date() >= warning_date)
     )
    mes = mes + "ВНИМАНИЕ !!!\n";
    mes = mes + "Метка целостности для ИП истекает "+print_date+"\n";
    mes = mes + "Т.к. для установки новой метки требуется перезапуск интеграции (томкаты), то имеет смысл заказать МЦ заранее у Булат Лукманов и запланировать смену МЦ на выходной день.\n";
    mes = mes + "см. Главная книга: Справочники \\ Очереди для обмена сообщениями \\ Скролинг ключевой информации\n";
    mes = mes + "Полученный *.XML файл с МЦ выложить ..\\obj\\IP_KEY_INFO";
    msgbox (mes);
  end;
 
  // функционал поддержания тользовательских терминалов в эталонном состоянии
  if ( (((GetSystemInfo(RSL_SI_COMPNAME, false) == "SGO-AP2388") and  // работаем через пока единственный задействованный СП
         (GetSystemInfo(RSL_SI_COMPNAME, true) != "SGO-AP2388")   // терминал запущен не на СП
        )
       ) and 
       (rsldefcon.user == "RSHB_SOFR")
       and // Этих пользователей исключим из обновления
       (not index(";NULL;",";"+{oper}+";")) 
     )
    LogInfo();
    if (isDirsExist() == 0)
      RunCopyUpdateTerminalFiles();

    elif ( //(index(";9996;",";"+{oper}+";")) and 
           (isMainDirsExist() == 0) 
         )
      RunCopyUpdateTerminalMainFiles();
    end;
//    if ( ({oper} == 1) and (GetTrue(false, "Копируем архив терминалки?  (155 Мб)")) )
//      GetFirstTerm();
//    end;

  end;

//  msgbox("На внутреннем Портале размещены инструкции для пользователей СОФР: | Головной офис \\ Департамент информационных технологий \\ Инструкции \\ Инструкции СОФР");

  var cr_mes = CheckRate();
  if(cr_mes!="")
    msgbox(cr_mes);
  end;

//shev 20190810
  var Rudata_mes = CheckRuData();
  if(Rudata_mes!="")
    msgbox(Rudata_mes);
  end;

  //Simanov 06012020
  var transfrate_mes = CheckTransfRate();
  if ( transfrate_mes != "")
    MsgBox(transfrate_mes);
  end;

//  msgbox(" СОФР. ПРОДУКТИВНАЯ СРЕДА. | Будьте внимательны при вводе бизнес-данных ");

end;


