import Globals,PTInter,PaymInter, Oralib;


macro MainScroll()

var opr_kind, opr_name;

    macro AddColumn_NO_edit(ar,ind,fld,head,w)
      ar.value(ind*6+0) = fld;  // Поле таблицы
      ar.value(ind*6+1) = head; // Заголовок
      ar.value(ind*6+2) = w;    // Ширина
      ar.value(ind*6+3) = 2;    // 1 - редактировать, 2 - не редактировать
      ar.value(ind*6+4) = 0;    // Точность цифровых полей
      ar.value(ind*6+5) = 0;
    end;



    macro ScrollOper()
          macro EvProcScroll_oper (obj,cmd,id,key)
            if ((cmd == DLG_KEY) and (key == 13))
              opr_kind = obj.value(0);
              opr_name = obj.value(1);

              return CM_SELECT;
            end;
          end;

           private var cmd_o,rec_o,cSqlStr_o="";
           cSqlStr_o = string("select T_KIND_OPERATION, T_NAME from DOPRKOPER_DBT where T_KIND_OPERATION not like'-%'");

           rec_o = RsdRecordset(cSqlStr_o,RSDVAL_CLIENT,RSDVAL_STATIC);

           private var aScroll_o = TArray();
           AddColumn_NO_edit(aScroll_o,0,"T_KIND_OPERATION","Вид операции",5);
           AddColumn_NO_edit(aScroll_o,1,"T_NAME","Название операции",50);
           /*Возвращаем результат работы, чтобы понять выбрали значение или просто вышли*/
           return RunScroll(rec_o,2,aScroll_o,null,@EvProcScroll_oper,"Выбор операции", null, true);
    end;


    var kind;


    macro EvProcScroll (rs,cmd,id,key)
      /*Enter*/
      if ((cmd == DLG_KEY) and (key == 13))
       if(id == 3/*num_oper*/)
          var num_oper = int(rs.value(2));
          if(GetInt(num_oper,"Операционист",8))
            num_oper = string(num_oper);
            while(strlen(num_oper) < 8)
              num_oper = "0" + num_oper;
            end;
            rs.edit;
            rs.value("num_oper") = num_oper;
            rs.Update();
            updatescroll(rs,5);
            return CM_SAVE;
          end;
        elif(id == 4/*num_contr*/)
          var num_contr = int(rs.value(3));
          if(GetInt(num_contr,"Контроллер",8))
            num_contr = string(num_contr);
            while(strlen(num_contr) < 8)
              num_contr = "0" + num_contr;
            end;
            rs.edit;
            rs.value("num_contr") = num_contr;
            rs.Update();
            updatescroll(rs,5);
            return CM_SAVE;
          end;
        elif(id == 2/*num_pack*/)
          var num_pack = int(rs.value(4));
          if(GetInt(num_pack,"Пачка",8))
            rs.edit;
            rs.value("num_pack") = num_pack;
            rs.Update();
            updatescroll(rs,5);
            return CM_SAVE;
          end;
        end;

        return CM_IGNORE;
      /*F9*/
      elif((cmd == DLG_KEY) and (key == 323))
        rs.addnew(); 
        rs.value("opr_kind") = 0;
        rs.value("opr_name") = "";
        rs.value("num_oper") = "";
        rs.value("num_contr") = "";
        rs.update();
        updatescroll(rs,5);
        GoToScroll(rs);      
        return CM_IGNORE;
      /*F3*/
      elif((cmd == DLG_KEY) and (key == 317))
        if((id == 0/*opr_name*/) or (id == 1/*opr_kind*/))
          /*Проверяем что что-то выбрали*/
          if(ScrollOper())
            rs.edit;
            rs.value("opr_name") = opr_name;
            rs.value("opr_kind") = opr_kind;
            rs.Update();
            updatescroll(rs,5);
            return CM_SAVE;
          end;
        end;
      end;
    end;

    macro AddColumn(ar,ind,fld,head,w)
      ar.value(ind*6+0) = fld;  // Поле таблицы
      ar.value(ind*6+1) = head; // Заголовок
      ar.value(ind*6+2) = w;    // Ширина
      ar.value(ind*6+3) = 1;    // 1 - редактировать, 2 - не редактировать
      ar.value(ind*6+4) = 0;    // Точность цифровых полей
      ar.value(ind*6+5) = 0;
    end;


    private var cmd,rec,cSqlStr="";
    cSqlStr = string("select opr_kind, "
                  + "        opr_name, "
                  + "        num_oper, "
                  + "        num_contr, "
                  + "        num_pack "
                  + "from usr_TableNumOperBISQUIT usr "
                  + "order by opr_kind");

    cmd = RSDCommand(cSqlStr);
                                   
    rec = RsdRecordset(cmd,RSDVAL_CLIENT,RSDVAL_STATIC);

    private var aScroll = TArray();
    AddColumn_NO_edit(aScroll,0,"opr_kind","Вид операции",11);
    AddColumn_NO_edit(aScroll,1,"opr_name","Название операции",50);
    AddColumn_NO_edit(aScroll,2,"num_pack","Номер пачки",15);
    AddColumn_NO_edit(aScroll,3,"num_oper","Номер исполнителя",15);
    AddColumn_NO_edit(aScroll,4,"num_contr","Номер контролера",15);

    var isSelected = RunScroll(rec,5,aScroll,null,@EvProcScroll,"Табельные номера БИСквит в разрезе операций СОФР", " F9 Добавить операцию   F8 Удалить операцию   Enter (на поле) ввод значения Номер исполнителя или Номер контролёра", false);

end;

MainScroll();
exit(1);

