/*
$Name:        mmlb_j.mac
$Module:      МБ Кредиты
$Description: Полезные ф-ии.
*/
/*──────────────────────────────────────────────────────────────────────────┐
  RS-Bank 5.1                                          R-Style Software Lab

  File Name   : mmlb_j.mac
  Created     : 22.12.00
  Programmer  : Сабитов Р.Р.
  Description : Полезные ф-ии.
  Comment     : 
└───────────────────────────────────────────────────────────────────────────*/
IMPORT PTInter, FIInter, mmlibr, mmcnst_j, mmcarry, CurrInter;

PRIVATE file mmlb_j_pmprop ("pmprop") key 0;
mmlb_j_pmprop.Corschem = 0;                  
PRIVATE const mmlb_j_rmprop = TRecHandler ("pmrmprop");

MACRO ПолучитьКорСчет (PaymentID, FIID, isDebet, CorrAcc)
    mmlb_j_pmprop.PaymentID = PaymentID;
    mmlb_j_pmprop.DebetCredit = isDebet;
    if (not GetEQ (mmlb_j_pmprop))
        mm_error ("Платеж должен быть внешним");
        return false;
    end;

    CorrAcc = GetCorAcc (FIID, mmlb_j_pmprop.Corschem, CORS_ACC_ACCOUNT);

    if (CorrAcc=="")
        mm_error ("Не найден корреспонденский|счет в валюте " + ПолучитьКодФинИн(FIID), 
                   "|по схеме расчетов " + mmlb_j_pmprop.Corschem);
        return false;
    end;

    SetParm (3, CorrAcc);
        
    return true;
END;

MACRO Конвертировать (Сколько, изФИ, Результат, вФИ, Дата )
        VAR stat;
        stat = ConvSum(Результат, Сколько, Дата, изФИ, вФИ, 0);
        if (stat == 0)
                SetParm(2, Результат);
        else
                mm_error("Не найден курс ",ПолучитьКодФинИн(изФИ), " относительно ",ПолучитьКодФинИн(вФИ), " за ", Дата);
        end;

        return not stat;
END;

MACRO GetGround(paym)
    if ((FindPayment(paym.rec.PaymentID, 0, 0, 0,0, true, 0, 0, 0, mmlb_j_rmprop)==0) and
        (mmlb_j_rmprop.rec.Ground!=""))
        return mmlb_j_rmprop.rec.Ground;
    else
        if (paym.rec.Purpose == PM_PURP_PRINC)
            return "Предоставление средств";
        elif (paym.rec.Purpose == PM_PURP_PRINC_RET)
            return "Погашение основного долга";
        elif (paym.rec.Purpose == PM_PURP_PERCENT)
            return "Погашение срочных процентов";
        elif (paym.rec.Purpose == PM_PURP_OVD_PRINC)
            return "Погашение просроченного основного долга";
        elif (paym.rec.Purpose == PM_PURP_OVD_PERC)
            return "Погашение просроченных процентов";
        elif (paym.rec.Purpose == PM_PURP_PENALTY_PRINC)
            return "Погашение штрафов за просроченный основной долг";
        elif (paym.rec.Purpose == PM_PURP_PENALTY_PERC)
            return "Погашение штрафов за просроченные проценты";
        end;
    end;
    return "";
END;

///* Универсальная проводка на сумму в валюте платежа*/
//MACRO MM_UNI_Carry (fd, ВАктива, Сумма_Актива, ВДебет, СчетДебет, ВКредит, СчетКредит, ExecDate, Ground, PaymentID, Сумма_Кредит:@money)
//
//var Сумма_Дебет, СчетРасходов, СчетДоходов;
//
//    if (ВДебет!=ВАктива)
//        if (not Конвертировать (Сумма_Актива, ВАктива, Сумма_Дебет, ВДебет, ExecDate))
//            return false;
//        end;
//    else
//        Сумма_Дебет = Сумма_Актива;
//    end;
//
//    if (ВДебет == ВКредит)
//        Сумма_Кредит = Сумма_Дебет;
//        if (DocCarry( 0,
//                    1,                /*Глава*/
//                    ВДебет,           /*Валюта*/
//                    СчетДебет,        /*Дебет*/
//                    СчетКредит,       /*Кредит*/
//                    Сумма_Дебет,      /*сколько*/
//                    ExecDate,         /*За какое число*/
//                    0,                /*CarryResult*/
//                    Ground, PaymentID))
//            return false;
//        end;
//    else
//        if (ВАктива!=ВКредит)
//            if (not Конвертировать (Сумма_Актива, ВАктива, Сумма_Кредит, ВКредит, ExecDate))
//                return false;
//            end;
//        else
//            Сумма_Кредит = Сумма_Актива;
//        end;
//
//        if( not ПолучитьСчетСделки( "-%, Кр", fd, null, СчетРасходов, ExecDate) )
//            return false;
//        end;
//
//        if( not ПолучитьСчетСделки( "+%, Кр", fd, null, СчетДоходов, ExecDate) )
//            return false;
//        end;
//
//        if (not DL_MultyCarry( ВДебет, СчетДебет, Сумма_Дебет, 
//                         ВКредит, СчетКредит, Сумма_Кредит, 1,
//                         СчетДоходов, СчетРасходов, ExecDate, 
//                         ExecDate, Ground, PaymentID));
//            return false;
//        end;
//    end;
//
//    return true;
//END;

/*---------------------------------------------------------------------------
    Приводит счета в актуальное состояние во время жизни сделки.
----------------------------------------------------------------------------*/
MACRO ActAccAfterChangeParm(FirstDoc, Дата, Error:@string)
  var Категории      = TArray,
      Роли           = TArray,
      i             = 0,
      FindAccount   = "";

  macro Заполнить(Категория, Роль)
      if (Роль == NULL)
          Роль = FirstDoc.GetFIRoleByCaterory(Категория, FirstDoc.GetLeg().PFI)
      end;

      Категории[Категории.size] = Категория; 
      Роли[Роли.size]           = Роль;  
  end;

//-----------------------------------------------------------

  Заполнить(tdr_RzrvP(FirstDoc.GetTick().TypeDoc), FIROLE_RVPS);
  Заполнить(tdr_RzrvM(FirstDoc.GetTick().TypeDoc), FIROLE_RVPS);

//-----------------------------------------------------------

  if (Категории.size == 0)
      return true;
  end;
  if (Категории.size > Роли.size)
      Роли.size = Категории.size;
  end;

  while (i < Категории.size)
      FirstDoc.ReOpenAccount(Категории[i], FindAccount, NULL, Роли[i], NULL, Дата, NULL);
  
      if (FindAccount == "")
          Error = "Не могу актуализировать счет для категории " + Категории(i);
          return false;
      end;
      i = i + 1;
  end;

  SetParm( 2, Error );
  return true;
END;

/*---------------------------------------------------------------------------
Получить остаток на счете (на конец дня)
----------------------------------------------------------------------------*/
MACRO ПолучитьОстатокСчета(FirstDoc, Категория, Счет, Глава, Сумма, Дата, Валюта)
  if (ValType(Счет) == V_UNDEF)
      Счет = "";
  end;
  if (ValType(Глава) == V_UNDEF)
      Глава = 1;
  end;
  if (ValType(Дата) == V_UNDEF)
      Дата = {curdate};
  end;
  if (ValType(Валюта) == V_UNDEF)
      Валюта = NATCUR;
  end;
  Сумма = Money(0);
  SetParm( 4, Сумма );
  
  if(Счет == "") 
      if (not СчетСделки(Категория, FirstDoc, Счет, NULL, NULL, 1)) 
          return false; 
      else 
          SetParm( 2, Счет );
      end; 
  end;

  Сумма = RestA(Счет, Дата, NULL, Глава, Валюта);
  
  Сумма = abs (Сумма);
  
  SetParm( 4, Сумма );
  
  return true;
END;

/*---------------------------------------------------------------------------
Получить остаток на счете (на конец дня) с учетом знака
----------------------------------------------------------------------------*/
MACRO ПолучитьОстатокСчетаУчетЗнака(FirstDoc, Категория, Счет, Глава, Сумма, Дата, Валюта)
  if (ValType(Счет) == V_UNDEF)
      Счет = "";
  end;
  if (ValType(Глава) == V_UNDEF)
      Глава = 1;
  end;
  if (ValType(Дата) == V_UNDEF)
      Дата = {curdate};
  end;
  if (ValType(Валюта) == V_UNDEF)
      Валюта = NATCUR;
  end;
  Сумма = Money(0);
  SetParm( 4, Сумма );
  
  if(Счет == "") 
      if (not СчетСделки(Категория, FirstDoc, Счет, NULL, NULL, 1)) 
          return false; 
      else 
          SetParm( 2, Счет );
      end; 
  end;

  Сумма = RestA(Счет, Дата, NULL, Глава, Валюта);  
  SetParm( 4, Сумма );
  return true;
END;
