--Добавление блоков операции удержания НДФЛ
/*Status*/
DECLARE
BEGIN

  UPDATE DOPRSTVAL_DBT
     SET T_NAME = 'Расчет сумм'
   WHERE T_STATUSKINDID = 46081 
     AND T_NUMVALUE = 10;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
    VALUES(46081,13,'Корректировка',CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
    VALUES(46081,14,'Создание заявления на возврат',CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
    VALUES(46081,15,'Передача в Хранилище событий зачета ДЕПО',CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN

  INSERT INTO DOPRSTVAL_DBT(T_STATUSKINDID,T_NUMVALUE,T_NAME,T_ELIMINATED)
    VALUES(46081,16,'Передача в Хранилище и форм. завления',CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/



/*Blocks*/
DECLARE
BEGIN
  UPDATE DOPRBLOCK_DBT
     SET T_NAME = 'Расчет сумм'
   WHERE T_BLOCKID = 203806;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(203810,'Корректировка',4608,0,CHR(0),CHR(1),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(203811,'Создание заявления на возврат',4608,0,CHR(0),CHR(1),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

DECLARE
BEGIN
  INSERT INTO DOPRBLOCK_DBT(T_BLOCKID,T_NAME,T_DOCKIND,T_PARENT,T_UPGRADE,T_VERSION,T_VERSIONWEB)
  VALUES(203812,'Передача в Хранилище событий зачета ДЕПО',4608,0,CHR(0),CHR(1),0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/


/*Steps*/
DECLARE
BEGIN

  UPDATE DOPROSTEP_DBT
     SET T_NOTINUSE = 'X'
   WHERE T_BLOCKID = 203806
     AND T_NUMBER_STEP = 30;   

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(203810,30,100,0,0,CHR(0),0,'К',0,0,'nptxhold030.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Корректировка удержанного налога',460800000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(203811,25,1,0,0,CHR(0),0,CHR(0),0,0,'nptxhold025.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Создание заявления на возврат',460800000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPROSTEP_DBT(T_BLOCKID,T_NUMBER_STEP,T_KIND_ACTION,T_DAYOFFSET,T_SCALE,T_DAYFLAG,T_CALENDARID,T_SYMBOL,T_PREVIOUS_STEP,T_MODIFICATION,
                            T_CARRY_MACRO,T_PRINT_MACRO,T_POST_MACRO,T_NOTINUSE,T_FIRSTSTEP,T_NAME,T_DATEKINDID,T_REV,T_AUTOEXECUTESTEP,T_ONLYHANDCARRY,
                            T_ISALLOWFOROPER,T_OPERORGROUP,T_RESTRICTEARLYEXECUTION,T_USERTYPES,T_INITDATEKINDID,T_ASKFORDATE,T_BACKOUT,T_ISBACKOUTGROUP,
                            T_MASSEXECUTEMODE,T_ISCASE,T_ISDISTAFFEXECUTE,T_SKIPINITAFTERPLANDATE,T_MASSPACKSIZE)
  VALUES(203812,21,1,0,0,CHR(0),0,CHR(0),0,0,'nptxhold021.mac',CHR(1),CHR(1),CHR(0),CHR(0),'Передача в Хранилище событий зачета ДЕПО',460800000,CHR(0),'X',CHR(0),0,CHR(0),'X',CHR(1),0,CHR(0),0,CHR(0),0,CHR(0),CHR(0),'X',0);

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

/*status on block*/
DECLARE
BEGIN
  DELETE FROM DOPRSBLCK_DBT
   WHERE T_BLOCKID = 203806
     AND T_STATUSKINDID = 46081
     AND T_NUMVALUE = 6;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  DELETE FROM DOPRSBLCK_DBT
   WHERE T_BLOCKID = 203806
     AND T_STATUSKINDID = 46081
     AND T_NUMVALUE = 7;

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/


DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203806,46081,5,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203806,46081,13,'X');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203806,46081,14,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203806,46081,15,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203810,46081,6,'X');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203810,46081,7,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203811,46081,5,'X');

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203812,46081,13,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203812,46081,14,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
  INSERT INTO DOPRSBLCK_DBT(T_BLOCKID,T_STATUSKINDID,T_NUMVALUE,T_DEFAULT)
  VALUES(203812,46081,15,CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

/*blocks in operation*/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 2038
       AND T_BLOCKID = 203810;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN
    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,2038,203810,11,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,46081,13,0);

  END IF;
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 2038
       AND T_BLOCKID = 203811;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN
    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,2038,203811,12,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,46081,14,0);
  END IF;
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 2038
       AND T_BLOCKID = 203812
       AND T_SORT = 13;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN
    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,2038,203812,13,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,46081,15,0);
  END IF;
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN
  BEGIN
    SELECT T_OPERBLOCKID
      INTO v_OperBlockID
      FROM DOPROBLCK_DBT
     WHERE T_KIND_OPERATION = 2038
       AND T_BLOCKID = 203812
       AND T_SORT = 14;

    EXCEPTION
         WHEN OTHERS THEN v_OperBlockID := 0;
  END;

  IF v_OperBlockID = 0 THEN
    INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                              T_SYMBOLSFORINSERTION,T_SYMBOL)
    VALUES(0,2038,203812,14,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

    INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
    VALUES(v_OperBlockID,46081,16,0);
  END IF;
EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
  INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
              VALUES(3519,2040,'КБК','КБК удержанного налога',2040,CHR(1),CHR(1));
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
  INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
              VALUES(3522,201,'201','18210102010011000110',0,CHR(1),CHR(1));
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
  INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
              VALUES(3522,207,'207','18210102070011000110',0,CHR(1),CHR(1));
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
  INSERT INTO DLLVALUES_DBT(T_LIST, T_ELEMENT, T_CODE, T_NAME, T_FLAG, T_NOTE, T_RESERVE)
              VALUES(3522,208,'208','18210102080011000110',0,CHR(1),CHR(1));
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   INSERT INTO DOBJECTS_DBT (T_OBJECTTYPE, T_NAME, T_CODE, T_USERNUMBER, T_PARENTOBJECTTYPE, T_SERVICEMACRO, T_MODULE)
   VALUES(3522,'КБК','ВидКБК',0,0,CHR(1),CHR(0));

EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/