-- Таблица "DNPTXHOLDGEN_DBT"
DECLARE
    E_OBJECT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT( E_OBJECT_EXISTS, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE DNPTXHOLDGEN_DBT (
    T_NPTXOPID NUMBER(10)
  , T_YEAR NUMBER(5)
  , T_GENSYSTDATE DATE
  , T_GENSYSTTIME DATE
  , T_FROMSHEDULER CHAR(1)
)';
EXCEPTION
    WHEN E_OBJECT_EXISTS THEN NULL;
END;
/

COMMENT ON TABLE DNPTXHOLDGEN_DBT IS 'Сгенерированные операции удержания НДФЛ'/
COMMENT ON COLUMN DNPTXHOLDGEN_DBT.T_NPTXOPID IS 'Идентификатор сгенерированной операции удержания НДФЛ'/
COMMENT ON COLUMN DNPTXHOLDGEN_DBT.T_YEAR IS 'Налоговый год'/
COMMENT ON COLUMN DNPTXHOLDGEN_DBT.T_GENSYSTDATE IS 'Системная дата генерации'/
COMMENT ON COLUMN DNPTXHOLDGEN_DBT.T_GENSYSTTIME IS 'Системное время генерации'/
COMMENT ON COLUMN DNPTXHOLDGEN_DBT.T_FROMSHEDULER IS 'Признак запуска генерации из планировщика'/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTXHOLDGEN_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DNPTXHOLDGEN_DBT_IDX0 ON DNPTXHOLDGEN_DBT (
   T_YEAR ASC
)
/
