--Обновление НДР
BEGIN
  UPDATE DNPTXOBJ_DBT OBJ
     SET OBJ.T_ANALITICKIND2 = 2040,
         OBJ.T_ANALITIC2 = 201
   WHERE OBJ.T_DATE >= TO_DATE('01.01.2023','DD.MM.YYYY')
     AND OBJ.T_LEVEL = 8
     AND OBJ.T_KIND IN (1143, 870, 1144, 875)
     AND OBJ.T_ANALITICKIND2 <= 0
     AND NOT EXISTS(SELECT 1
                      FROM DNPTXOBDC_DBT DC, DNPTXOP_DBT OP
                     WHERE DC.T_OBJID = OBJ.T_OBJID
                       AND OP.T_ID = DC.T_DOCID
                       AND OP.T_DOCKIND = 4608
                       AND EXTRACT(YEAR FROM OP.T_PREVDATE) != EXTRACT(YEAR FROM OBJ.T_DATE)
                   );
    
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
  UPDATE DNPTXOBJ_DBT OBJ
     SET OBJ.T_ANALITICKIND2 = 2040,
         OBJ.T_ANALITIC2 = 208
   WHERE OBJ.T_DATE >= TO_DATE('01.01.2023','DD.MM.YYYY')
     AND OBJ.T_LEVEL = 8
     AND OBJ.T_KIND IN (1150, 1161, 1162, 1163, 1151)
     AND OBJ.T_ANALITICKIND2 <= 0
     AND NOT EXISTS(SELECT 1
                      FROM DNPTXOBDC_DBT DC, DNPTXOP_DBT OP
                     WHERE DC.T_OBJID = OBJ.T_OBJID
                       AND OP.T_ID = DC.T_DOCID
                       AND OP.T_DOCKIND = 4608
                       AND EXTRACT(YEAR FROM OP.T_PREVDATE) != EXTRACT(YEAR FROM OBJ.T_DATE)
                   );
    
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/


BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/