/*Обновить шаг*/
DECLARE
BEGIN
  UPDATE DOPROSTEP_DBT
     SET T_POST_MACRO = 'nptxhold021.mac'
   WHERE T_BLOCKID = 203812
     AND T_NUMBER_STEP = 21;
END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/