-- 1 Депо
  CREATE TABLE "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN" 
   (	"RECID" NUMBER(*,0) NOT NULL ENABLE, 
	"CONTRACTNUMBER" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CONTRACTDATE" DATE NOT NULL ENABLE, 
	"DEPONUMBER" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"DEPODATE" DATE NOT NULL ENABLE, 
	"DEPOID" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"ACCDEPONUMBER" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"SECTIONCODE" VARCHAR2(30 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN"."RECID" IS 'ИД записи';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN"."CONTRACTNUMBER" IS 'Номер Договора';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN"."CONTRACTDATE" IS 'Текущий статуc: 1 = формируется 2 = готов к обработке 3 = обрабатывается 4 = архив';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN"."DEPONUMBER" IS 'DEPONumber';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN"."DEPODATE" IS 'DEPODate';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN"."DEPOID" IS 'ИД Договора ДЕПО в АС Банка;ИД Договора ДЕПО в Диасофт';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN"."ACCDEPONUMBER" IS 'Номер счета';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN"."SECTIONCODE" IS 'Код раздела';
   COMMENT ON TABLE "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN"  IS 'Таблица договоров и счетов Депо';

  CREATE UNIQUE INDEX "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN_IDX0" ON "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN" ("RECID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN_T0_AINC" 
 BEFORE INSERT OR UPDATE OF RECID ON SOFR_CONTACCDEPOIN FOR EACH ROW
DECLARE
    v_id INTEGER;
BEGIN
    IF (:new.RECID = 0 OR :new.RECID IS NULL)
    THEN
        SELECT SOFR_CONTACCDEPOIN_SEQ_1.nextval INTO :new.RECID FROM dual;
    ELSE
        SELECT last_number INTO v_id FROM user_sequences WHERE sequence_name = UPPER ('SOFR_CONTACCDEPOIN_SEQ_1');
            IF :new.RECID >= v_id
            THEN
                RAISE DUP_VAL_ON_INDEX;
            END IF;
    END IF;
END;
/
ALTER TRIGGER "RSHB_SEC_TEST"."SOFR_CONTACCDEPOIN_T0_AINC" ENABLE;

-- 2 Депо

  CREATE TABLE "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT" 
   (	"RECID" NUMBER(*,0) NOT NULL ENABLE, 
	"CONTRACTNUMBER" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CONTRACTDATE" DATE NOT NULL ENABLE, 
	"DEPONUMBER" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"DEPODATE" DATE NOT NULL ENABLE, 
	"DEPOID" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"ACCDEPONUMBER" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"SECTIONCODE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"RESULTCODE" VARCHAR2(100 CHAR), 
	"RESULTTEXT" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."RECID" IS 'ИД записи';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."CONTRACTNUMBER" IS 'Номер Договора';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."CONTRACTDATE" IS 'Текущий статуc: 1 = формируется 2 = готов к обработке 3 = обрабатывается 4 = архив';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."DEPONUMBER" IS 'DEPONumber';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."DEPODATE" IS 'DEPODate';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."DEPOID" IS 'ИД Договора ДЕПО в АС Банка;ИД Договора ДЕПО в Диасофт';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."ACCDEPONUMBER" IS 'Номер счета';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."SECTIONCODE" IS 'Код раздела';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."RESULTCODE" IS 'Код ошибки';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"."RESULTTEXT" IS 'Текст ошибки';
   COMMENT ON TABLE "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT"  IS 'Таблица результатов обработки договоров и счетов Депо в СОФР';

  CREATE UNIQUE INDEX "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT_IDX0" ON "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT" ("RECID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT_T0_AINC" 
 BEFORE INSERT OR UPDATE OF RECID ON SOFR_CONTACCDEPORESULT FOR EACH ROW
DECLARE
    v_id INTEGER;
BEGIN
    IF (:new.RECID = 0 OR :new.RECID IS NULL)
    THEN
        SELECT SOFR_CONTACCDEPORESULT_SEQ_1.nextval INTO :new.RECID FROM dual;
    ELSE
        SELECT last_number INTO v_id FROM user_sequences WHERE sequence_name = UPPER ('SOFR_CONTACCDEPORESULT_SEQ_1');
            IF :new.RECID >= v_id
            THEN
                RAISE DUP_VAL_ON_INDEX;
            END IF;
    END IF;
END;
/
ALTER TRIGGER "RSHB_SEC_TEST"."SOFR_CONTACCDEPORESULT_T0_AINC" ENABLE;

-- 3 БО

  CREATE TABLE "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT" 
   (	"CONTRACTID" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CONTRACTNUMBER" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CONTRACTDATE" DATE NOT NULL ENABLE, 
	"TYPETP" NUMBER(10,0) NOT NULL ENABLE, 
	"FUNDS" VARCHAR2(100 CHAR), 
	"CLIENTTYPE" NUMBER(10,0) NOT NULL ENABLE, 
	"CLIENTID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"BRANCHID" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"CODECLI" VARCHAR2(10 CHAR), 
	"MGRCLI" VARCHAR2(100 CHAR), 
	"REGPLACECLI" VARCHAR2(100 CHAR), 
	"RESULTCODE" VARCHAR2(100 CHAR), 
	"RESULTTEXT" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."CONTRACTID" IS 'ИД договора';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."CONTRACTNUMBER" IS 'Номер договора';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."CONTRACTDATE" IS 'Дата договора обслуживания';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."TYPETP" IS 'Тип торговой площадки 	1 ? ММВБ, 2 ? Внебиржа';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."FUNDS" IS 'Буквенное обозначение валют через запятую, в которых будут происходить расчеты по договорую Например: RUB, USD';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."CLIENTTYPE" IS 'Тип клиента	1 - ФЛ, 2 - ЮЛ';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."CLIENTID" IS 'ИД клиента из Бисквит';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."BRANCHID" IS '4-х значный код филиала из Бисквит';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."CODECLI" IS 'Уникальный код клиента на Бирже';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."MGRCLI" IS 'Менеджер клиента';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."REGPLACECLI" IS 'Место регистрации клиента';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."RESULTCODE" IS 'Код ошибки';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"."RESULTTEXT" IS 'Текст ошибки';
   COMMENT ON TABLE "RSHB_SEC_TEST"."SOFR_CONTRACTBOOUT"  IS 'Таблица договоров БО';

-- 4 БО

  CREATE TABLE "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT" 
   (	"CONTRACTID" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CONTRACTNUMBER" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CONTRACTDATE" DATE NOT NULL ENABLE, 
	"TYPETP" NUMBER(10,0) NOT NULL ENABLE, 
	"FUNDS" VARCHAR2(100 CHAR), 
	"CLIENTTYPE" NUMBER(10,0) NOT NULL ENABLE, 
	"CLIENTID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"BRANCHID" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"CODECLI" VARCHAR2(10 CHAR), 
	"MGRCLI" VARCHAR2(100 CHAR), 
	"REGPLACECLI" VARCHAR2(100 CHAR), 
	"RESULTCODE" VARCHAR2(100 CHAR), 
	"RESULTTEXT" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."CONTRACTNUMBER" IS 'Номер договора';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."CONTRACTDATE" IS 'Дата договора обслуживания';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."TYPETP" IS 'Тип торговой площадки 	1 ? ММВБ, 2 ? Внебиржа';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."FUNDS" IS 'Буквенное обозначение валют через запятую, в которых будут происходить расчеты по договорую Например: RUB, USD';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."CLIENTTYPE" IS 'Тип клиента	1 - ФЛ, 2 - ЮЛ';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."CLIENTID" IS 'ИД клиента из Бисквит';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."BRANCHID" IS '4-х значный код филиала из Бисквит';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."CODECLI" IS 'Уникальный код клиента на Бирже';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."MGRCLI" IS 'Менеджер клиента';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."REGPLACECLI" IS 'Место регистрации клиента';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."RESULTCODE" IS 'Код ошибки';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"."RESULTTEXT" IS 'Текст ошибки';
   COMMENT ON TABLE "RSHB_SEC_TEST"."SOFR_CONTRACTBORESULT"  IS 'Таблица обработки результатов договоров БО';

-- 5 Сверка

  CREATE TABLE "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN" 
   (	"RECID" NUMBER(*,0) NOT NULL ENABLE, 
	"DEPONUMBER" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"ACCDEPONUMBER" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"SECTIONCODE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CONTRACTNUMBER" VARCHAR2(100 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN"."RECID" IS 'ИД записи';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN"."DEPONUMBER" IS 'DEPONumber';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN"."ACCDEPONUMBER" IS 'Номер счета';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN"."SECTIONCODE" IS 'Код раздела';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN"."CONTRACTNUMBER" IS 'Номер Договора';
   COMMENT ON TABLE "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN"  IS 'Таблица данных по договорам ДЕПО для сверки';

  CREATE UNIQUE INDEX "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN_IDX0" ON "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN" ("RECID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN_T0_AINC" 
 BEFORE INSERT OR UPDATE OF RECID ON SOFR_SVERKAACCDEPOIN FOR EACH ROW
DECLARE
    v_id INTEGER;
BEGIN
    IF (:new.RECID = 0 OR :new.RECID IS NULL)
    THEN
        SELECT SOFR_SVERKAACCDEPOIN_SEQ_1.nextval INTO :new.RECID FROM dual;
    ELSE
        SELECT last_number INTO v_id FROM user_sequences WHERE sequence_name = UPPER ('SOFR_SVERKAACCDEPOIN_SEQ_1');
            IF :new.RECID >= v_id
            THEN
                RAISE DUP_VAL_ON_INDEX;
            END IF;
    END IF;
END;
/
ALTER TRIGGER "RSHB_SEC_TEST"."SOFR_SVERKAACCDEPOIN_T0_AINC" ENABLE;

-- 6 Сверка

  CREATE TABLE "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN" 
   (	"RECID" NUMBER(*,0) NOT NULL ENABLE, 
	"ACCDEPOID" NUMBER(*,0) NOT NULL ENABLE, 
	"REPORTDATE" DATE NOT NULL ENABLE, 
	"ISIN" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"VALUE" NUMBER(18,2) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN"."RECID" IS 'ИД записи';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN"."ACCDEPOID" IS 'Дата договора обслуживания';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN"."REPORTDATE" IS 'Дата сведений';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN"."ISIN" IS 'ISIN';
   COMMENT ON COLUMN "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN"."VALUE" IS 'Сумма остатка';
   COMMENT ON TABLE "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN"  IS 'Таблица данных по счетам ДЕПО для сверки';

  CREATE UNIQUE INDEX "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN_IDX0" ON "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN" ("RECID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN_T0_AINC" 
 BEFORE INSERT OR UPDATE OF RECID ON SOFR_SVERKARESTDEPOIN FOR EACH ROW
DECLARE
    v_id INTEGER;
BEGIN
    IF (:new.RECID = 0 OR :new.RECID IS NULL)
    THEN
        SELECT SOFR_SVERKARESTDEPOIN_SEQ_1.nextval INTO :new.RECID FROM dual;
    ELSE
        SELECT last_number INTO v_id FROM user_sequences WHERE sequence_name = UPPER ('SOFR_SVERKARESTDEPOIN_SEQ_1');
            IF :new.RECID >= v_id
            THEN
                RAISE DUP_VAL_ON_INDEX;
            END IF;
    END IF;
END;
/
ALTER TRIGGER "RSHB_SEC_TEST"."SOFR_SVERKARESTDEPOIN_T0_AINC" ENABLE;
