DROP INDEX DPERSN_DBT_IDX1
/
DROP INDEX DPERSN_DBT_IDXI
/
DROP INDEX DPERSN_DBT_NORMAL_NAME1
/
DROP INDEX DPERSN_DBT_NORMAL_NAME2
/
DROP INDEX DPERSN_DBT_NORMAL_NAME3
/

ALTER TABLE DPERSN_DBT MODIFY T_NAME1 VARCHAR2(54)
/
ALTER TABLE DPERSN_DBT MODIFY T_NAME2 VARCHAR2(100)
/
ALTER TABLE DPERSN_DBT MODIFY T_NAME3 VARCHAR2(54)
/
ALTER TABLE DPERSN_DBT MODIFY T_NORMALIDENTNAME1 VARCHAR2(54)
/
ALTER TABLE DPERSN_DBT MODIFY T_NORMALIDENTNAME2 VARCHAR2(100)
/
ALTER TABLE DPERSN_DBT MODIFY T_NORMALIDENTNAME3 VARCHAR2(54)
/

CREATE INDEX DPERSN_DBT_IDX1 ON DPERSN_DBT
(T_BORN, T_NAME1)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/

CREATE UNIQUE INDEX DPERSN_DBT_IDXI ON DPERSN_DBT
(UPPER("T_NAME1"), UPPER("T_NAME2"), UPPER("T_NAME3"), T_PERSONID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/

CREATE INDEX DPERSN_DBT_NORMAL_NAME1 ON DPERSN_DBT
(T_NORMALIDENTNAME1)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/

CREATE INDEX DPERSN_DBT_NORMAL_NAME2 ON DPERSN_DBT
(T_NORMALIDENTNAME2)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/

CREATE INDEX DPERSN_DBT_NORMAL_NAME3 ON DPERSN_DBT
(T_NORMALIDENTNAME3)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/