/*„®΅ Ά¨βμ § ―¨αμ*/
DECLARE
  v_ID       NUMBER := 0;
  v_ParentID NUMBER := 0;

  v_Val      NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = 0 AND LOWER(T_NAME) = LOWER('COMMON');
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('„”‹');
  SELECT T_KEYID INTO v_ID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('’—‘’_–_„‹_‚…‘’‚›—…’€');

  SELECT T_LINTVALUE INTO v_Val FROM DREGVAL_DBT WHERE T_KEYID = v_ID;

  INSERT INTO DREGPARMSTORY_DBT(T_ID, T_KEYID, T_DATEBEGIN, T_DATEEND, T_INTVALUE, T_DOUBLEVALUE, T_BOOLVALUE, T_STRINGVALUE)
       VALUES (0, v_ID, TO_DATE('01.01.0001', 'DD.MM.YYYY'), TO_DATE('31.12.9999', 'DD.MM.YYYY'), 0, 0, 2, CHR(1));


EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/