-- Таблица "DDLCONTRINFBROK_TMP"

CREATE GLOBAL TEMPORARY TABLE DDLCONTRINFBROK_TMP (
    T_ID NUMBER(10)
  , T_INFID NUMBER(10)
  , T_DLCONTRID NUMBER(10)
  , T_RECNUM NUMBER(5)
  , T_BROKERNAME VARCHAR2(60)
  , T_CONTRNUMBER VARCHAR2(30)
  , T_CONTRDATE DATE
  , T_NUMANDDATEREF VARCHAR2(60)
  , T_LISTCOUNT NUMBER(5)
  , T_OPER NUMBER(5)
  , T_CHANGEDATE DATE
  , T_CHANGETIME DATE
  , T_TYPE NUMBER(5)
  , T_VERSION NUMBER(5)
  , T_ACTION NUMBER(5)
) ON COMMIT PRESERVE ROWS
/
COMMENT ON TABLE DDLCONTRINFBROK_TMP IS 'ДБО. Сведения о других брокерах. Врем'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_ID IS 'Идентификатор записи'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_INFID IS 'Идентификатор записи из постоянной таблицы'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_DLCONTRID IS 'Идентификатор ДБО'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_RECNUM IS 'Номер записи'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_BROKERNAME IS 'Наименование первоначального брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_CONTRNUMBER IS '№ договора ИИС у первоначального брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_CONTRDATE IS 'Дата договора ИИС у первоначального брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_NUMANDDATEREF IS 'Номер и дата Справки с информацией другого брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_LISTCOUNT IS 'Количество листов в Справке от другого брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_OPER IS 'Операционист, изменивший запись'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_CHANGEDATE IS 'Дата изменения'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_CHANGETIME IS 'Время изменения записи'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_TYPE IS 'Тип записи'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_VERSION IS 'Номер изменения записи'
/
COMMENT ON COLUMN DDLCONTRINFBROK_TMP.T_ACTION IS 'Действие'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDLCONTRINFBROK_TMP_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DDLCONTRINFBROK_TMP_IDX0 ON DDLCONTRINFBROK_TMP (
   T_ID ASC
)
/

CREATE SEQUENCE DDLCONTRINFBROK_TMP_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DDLCONTRINFBROK_TMP_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDLCONTRINFBROK_TMP FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDLCONTRINFBROK_TMP_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDLCONTRINFBROK_TMP_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
