-- Таблица "DDLCONTRINFBROKCH_DBT"

CREATE TABLE DDLCONTRINFBROKCH_DBT (
    T_ID NUMBER(10)
  , T_INFID NUMBER(10)
  , T_RECNUM_OLD NUMBER(5)
  , T_RECNUM_NEW NUMBER(5)
  , T_BROKERNAME_OLD VARCHAR2(60)
  , T_BROKERNAME_NEW VARCHAR2(60)
  , T_CONTRNUMBER_OLD VARCHAR2(30)
  , T_CONTRNUMBER_NEW VARCHAR2(30)
  , T_CONTRDATE_OLD DATE
  , T_CONTRDATE_NEW DATE
  , T_NUMANDDATEREF_OLD VARCHAR2(60)
  , T_NUMANDDATEREF_NEW VARCHAR2(60)
  , T_LISTCOUNT_OLD NUMBER(5)
  , T_LISTCOUNT_NEW NUMBER(5)
  , T_OPER NUMBER(5)
  , T_CHANGEDATE DATE
  , T_CHANGETIME DATE
)
/
COMMENT ON TABLE DDLCONTRINFBROKCH_DBT IS 'ДБО. Сведения о других брокерах. История'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_ID IS 'Идентификатор записи'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_INFID IS 'Идентификатор записи о другом брокере ДБО'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_RECNUM_OLD IS 'Прежний номер записи'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_RECNUM_NEW IS 'Новый номер записи'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_BROKERNAME_OLD IS 'Прежнее наименование первоначального брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_BROKERNAME_NEW IS 'Новое наименование первоначального брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_CONTRNUMBER_OLD IS 'Прежний № договора ИИС у первоначального брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_CONTRNUMBER_NEW IS 'Новый № договора ИИС у первоначального брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_CONTRDATE_OLD IS 'Прежня дата договора ИИС у первоначального брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_CONTRDATE_NEW IS 'Новая дата договора ИИС у первоначального брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_NUMANDDATEREF_OLD IS 'Прежние номер и дата Справки с информацией другого брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_NUMANDDATEREF_NEW IS 'Новые номер и дата Справки с информацией другого брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_LISTCOUNT_OLD IS 'Прежнее количество листов в Справке от другого брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_LISTCOUNT_NEW IS 'Новое количество листов в Справке от другого брокера'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_OPER IS 'Операционист, изменивший запись'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_CHANGEDATE IS 'Дата изменения'
/
COMMENT ON COLUMN DDLCONTRINFBROKCH_DBT.T_CHANGETIME IS 'Время изменения записи'
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDLCONTRINFBROKCH_DBT_IDX0';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE UNIQUE INDEX DDLCONTRINFBROKCH_DBT_IDX0 ON DDLCONTRINFBROKCH_DBT (
   T_ID ASC
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DDLCONTRINFBROKCH_DBT_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE   INDEX DDLCONTRINFBROKCH_DBT_IDX1 ON DDLCONTRINFBROKCH_DBT (
   T_INFID ASC
)
/

CREATE SEQUENCE DDLCONTRINFBROKCH_DBT_SEQ 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER DDLCONTRINFBROKCH_DBT_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDLCONTRINFBROKCH_DBT FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDLCONTRINFBROKCH_DBT_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDLCONTRINFBROKCH_DBT_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/
