DECLARE
	e_col_exist EXCEPTION;
	PRAGMA EXCEPTION_INIT (e_col_exist, -01430);
BEGIN
	EXECUTE IMMEDIATE 'ALTER TABLE DADGROUP_DBT MODIFY ( ' || 
			'T_USNCHANGED NUMBER(19)' ||
		')';

	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DADGROUP_DBT.T_USNCHANGED IS ''Последнее значение атрибута uSNChanged группы.''';

EXCEPTION WHEN e_col_exist THEN NULL;
END;
/

DECLARE
	e_col_exist EXCEPTION;
	PRAGMA EXCEPTION_INIT (e_col_exist, -01430);
BEGIN
	EXECUTE IMMEDIATE 'ALTER TABLE DADOPERNAME_DBT MODIFY ( ' || 
			'T_USNCHANGED NUMBER(19)' ||
		')';

	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DADOPERNAME_DBT.T_USNCHANGED IS ''Последнее значение атрибута uSNChanged''';

EXCEPTION WHEN e_col_exist THEN NULL;
END;
/

DECLARE
	e_col_exist EXCEPTION;
	PRAGMA EXCEPTION_INIT (e_col_exist, -01430);
BEGIN
	EXECUTE IMMEDIATE 'ALTER TABLE DADMEMBERS_TMP MODIFY ( ' || 
			'T_USNCHANGED NUMBER(19),' ||
			'T_USNCHANGEDGROUP NUMBER(19)' ||
		')';

	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DADMEMBERS_TMP.T_USNCHANGED IS ''Последнее значение атрибута uSNChanged''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN DADMEMBERS_TMP.T_USNCHANGEDGROUP IS ''Последнее значение атрибута uSNChanged группы''';

EXCEPTION WHEN e_col_exist THEN NULL;
END;
/
