DROP TABLE DDL_LEG_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE DDL_LEG_TMP (
    T_ID NUMBER(10)
  , T_DEALID NUMBER(10)
  , T_LEGID NUMBER(5)
  , T_PFI NUMBER(10)
  , T_CFI NUMBER(10)
  , T_START DATE
  , T_MATURITY DATE
  , T_EXPIRY DATE
  , T_PRINCIPAL NUMBER(32,12)
  , T_PRICE FLOAT(53)
  , T_BASIS NUMBER(5)
  , T_DURATION FLOAT(53)
  , T_PITCH NUMBER(5)
  , T_COST NUMBER(32,12)
  , T_MODE NUMBER(10)
  , T_CLOSED DATE
  , T_REFRATE NUMBER(10)
  , T_FACTOR FLOAT(53)
  , T_FORMULA NUMBER(5)
  , T_VERSION NUMBER(10)
  , T_RESERVE0 VARCHAR2(3)
  , T_PERIODNUMBER NUMBER(10)
  , T_PERIODTYPE NUMBER(5)
  , T_DIFF NUMBER(10)
  , T_PAYDAY NUMBER(5)
  , T_LEGKIND NUMBER(5)
  , T_SCALE NUMBER(10)
  , T_POINT NUMBER(5)
  , T_ISCALCUSED CHAR(1)
  , T_LEGNUMBER VARCHAR2(20)
  , T_RELATIVEPRICE CHAR(1)
  , T_NKD NUMBER(32,12)
  , T_TOTALCOST NUMBER(32,12)
  , T_MATURITYISPRINCIPAL CHAR(1)
  , T_REGISTRAR NUMBER(10)
  , T_INCOMERATE FLOAT(53)
  , T_INCOMESCALE NUMBER(10)
  , T_INCOMEPOINT NUMBER(5)
  , T_INTERESTSTART DATE
  , T_RECEIPTAMOUNT NUMBER(32,12)
  , T_REGISTRARCONTRID NUMBER(10)
  , T_PRINCIPALBASE NUMBER(5)
  , T_PRINCIPALDIFF NUMBER(10)
  , T_STARTBASE NUMBER(5)
  , T_STARTDIFF NUMBER(10)
  , T_BASE NUMBER(5)
  , T_PAYREGTAX CHAR(1)
  , T_RETURNINCOME NUMBER(32,12)
  , T_REJECTDATE DATE
  , T_DELIVERINGFIID NUMBER(10)
  , T_BITMASK NUMBER(10)
  , T_OPERSTATE NUMBER(5)
  , T_SUPPLYTIME DATE
  , T_TABLEPERCENT CHAR(1)
  , T_TYPEPERCENT NUMBER(5)
  , T_CAPTION NUMBER(10)
  , T_TYPEDATE NUMBER(5)
  , T_COUNTDAY NUMBER(5)
  , T_CORRECT FLOAT(53)
  , T_PAYFIID NUMBER(10)
  , T_NKDFIID NUMBER(10)
  , T_SROK CHAR(1)
  , T_CLIRINGDATE DATE
  , T_CLIRINGCHANGE CHAR(1)
  , T_DEPOSITID NUMBER(10)
  , T_DVP CHAR(1)
  , T_CLIRINGTIME DATE
  , T_SESSION NUMBER(5)
  , T_D1 NUMBER(32,12)
  , T_D2 NUMBER(32,12)
  , T_DMAXPAY DATE
  , T_QRETURN NUMBER(32,12)
  , T_QRECEIVE NUMBER(32,12)
  , T_SUMINCOME NUMBER(32,12)
  , T_MOVEDATE DATE
  , T_PLANMATURITY DATE
  , T_PAYERINCRTAXRATE FLOAT(53)
  , T_PAYERINCRTAX NUMBER(32,12)
  , T_RECEIVERINCRTAXRATE FLOAT(53)
  , T_RECEIVERINCRTAX NUMBER(32,12)
  , T_FLRATE FLOAT(53)
  , T_SPREDFLRT FLOAT(53)
  , T_FLRTID NUMBER(10)
  , T_ISFLRATE CHAR(1)
  , T_ID_FROM NUMBER(10)
  , T_DEALID_FROM NUMBER(10)
  , T_LEGID_FROM NUMBER(5)
  , T_PFI_FROM NUMBER(10)
  , T_CFI_FROM NUMBER(10)
  , T_START_FROM DATE
  , T_MATURITY_FROM DATE
  , T_EXPIRY_FROM DATE
  , T_PRINCIPAL_FROM NUMBER(32,12)
  , T_PRICE_FROM FLOAT(53)
  , T_BASIS_FROM NUMBER(5)
  , T_DURATION_FROM FLOAT(53)
  , T_PITCH_FROM NUMBER(5)
  , T_COST_FROM NUMBER(32,12)
  , T_MODE_FROM NUMBER(10)
  , T_CLOSED_FROM DATE
  , T_REFRATE_FROM NUMBER(10)
  , T_FACTOR_FROM FLOAT(53)
  , T_FORMULA_FROM NUMBER(5)
  , T_VERSION_FROM NUMBER(10)
  , T_RESERVE0_FROM VARCHAR2(3)
  , T_PERIODNUMBER_FROM NUMBER(10)
  , T_PERIODTYPE_FROM NUMBER(5)
  , T_DIFF_FROM NUMBER(10)
  , T_PAYDAY_FROM NUMBER(5)
  , T_LEGKIND_FROM NUMBER(5)
  , T_SCALE_FROM NUMBER(10)
  , T_POINT_FROM NUMBER(5)
  , T_ISCALCUSED_FROM CHAR(1)
  , T_LEGNUMBER_FROM VARCHAR2(20)
  , T_RELATIVEPRICE_FROM CHAR(1)
  , T_NKD_FROM NUMBER(32,12)
  , T_TOTALCOST_FROM NUMBER(32,12)
  , T_MATURITYISPRINCIPAL_FROM CHAR(1)
  , T_REGISTRAR_FROM NUMBER(10)
  , T_INCOMERATE_FROM FLOAT(53)
  , T_INCOMESCALE_FROM NUMBER(10)
  , T_INCOMEPOINT_FROM NUMBER(5)
  , T_INTERESTSTART_FROM DATE
  , T_RECEIPTAMOUNT_FROM NUMBER(32,12)
  , T_REGISTRARCONTRID_FROM NUMBER(10)
  , T_PRINCIPALBASE_FROM NUMBER(5)
  , T_PRINCIPALDIFF_FROM NUMBER(10)
  , T_STARTBASE_FROM NUMBER(5)
  , T_STARTDIFF_FROM NUMBER(10)
  , T_BASE_FROM NUMBER(5)
  , T_PAYREGTAX_FROM CHAR(1)
  , T_RETURNINCOME_FROM NUMBER(32,12)
  , T_REJECTDATE_FROM DATE
  , T_DELIVERINGFIID_FROM NUMBER(10)
  , T_BITMASK_FROM NUMBER(10)
  , T_OPERSTATE_FROM NUMBER(5)
  , T_SUPPLYTIME_FROM DATE
  , T_TABLEPERCENT_FROM CHAR(1)
  , T_TYPEPERCENT_FROM NUMBER(5)
  , T_CAPTION_FROM NUMBER(10)
  , T_TYPEDATE_FROM NUMBER(5)
  , T_COUNTDAY_FROM NUMBER(5)
  , T_CORRECT_FROM FLOAT(53)
  , T_PAYFIID_FROM NUMBER(10)
  , T_NKDFIID_FROM NUMBER(10)
  , T_SROK_FROM CHAR(1)
  , T_CLIRINGDATE_FROM DATE
  , T_CLIRINGCHANGE_FROM CHAR(1)
  , T_DEPOSITID_FROM NUMBER(10)
  , T_DVP_FROM CHAR(1)
  , T_CLIRINGTIME_FROM DATE
  , T_SESSION_FROM NUMBER(5)
  , T_D1_FROM NUMBER(32,12)
  , T_D2_FROM NUMBER(32,12)
  , T_DMAXPAY_FROM DATE
  , T_QRETURN_FROM NUMBER(32,12)
  , T_QRECEIVE_FROM NUMBER(32,12)
  , T_SUMINCOME_FROM NUMBER(32,12)
  , T_MOVEDATE_FROM DATE
  , T_PLANMANURITY_FROM DATE
  , T_PAYERINCRTAXRATE_FROM FLOAT(53)
  , T_PAYERINCRTAX_FROM NUMBER(32,12)
  , T_RECEIVERINCRTAXRATE_FROM FLOAT(53)
  , T_RECEIVERINCRTAX_FROM NUMBER(32,12)
  , T_FLRATE_FROM FLOAT(53)
  , T_SPREDFLRT_FROM FLOAT(53)
  , T_FLRTID_FROM NUMBER(10)
  , T_ISFLRATE_FROM CHAR(1)
  , T_ACTION NUMBER(5)
) 
ON COMMIT PRESERVE ROWS
/

COMMENT ON TABLE DDL_LEG_TMP IS 'Транш сделки'/

COMMENT ON COLUMN DDL_LEG_TMP.T_ID IS 'Идентификатор транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DEALID IS 'Идентификатор сделки'/

COMMENT ON COLUMN DDL_LEG_TMP.T_LEGID IS 'Номер транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PFI IS 'Финансовый инструмент принципала'/

COMMENT ON COLUMN DDL_LEG_TMP.T_CFI IS 'Финансовый инструмент цены'/

COMMENT ON COLUMN DDL_LEG_TMP.T_START IS 'Дата начала транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_MATURITY IS 'Дата завершения транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_EXPIRY IS 'Дата фиксинга, пересмотра ставки'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PRINCIPAL IS 'Объем транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PRICE IS 'Действующая ставка, курс'/

COMMENT ON COLUMN DDL_LEG_TMP.T_BASIS IS 'Базис начисления процентов'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DURATION IS 'Продолжительность периода'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PITCH IS 'Единица измерения продолжительности периода'/

COMMENT ON COLUMN DDL_LEG_TMP.T_COST IS 'Накопленный доход'/

COMMENT ON COLUMN DDL_LEG_TMP.T_MODE IS 'Режим начисления процентов'/

COMMENT ON COLUMN DDL_LEG_TMP.T_CLOSED IS 'Дата закрытия'/

COMMENT ON COLUMN DDL_LEG_TMP.T_REFRATE IS 'Идентификатор референтной котировки'/

COMMENT ON COLUMN DDL_LEG_TMP.T_FACTOR IS 'Коэффициент ставки, курса'/

COMMENT ON COLUMN DDL_LEG_TMP.T_FORMULA IS 'Метод формирования ставки, цены'/

COMMENT ON COLUMN DDL_LEG_TMP.T_VERSION IS 'Номер обновления'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RESERVE0 IS 'Идентификатор счета процентов'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PERIODNUMBER IS 'Количество временных интервалов'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PERIODTYPE IS 'Тип периода'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DIFF IS 'Отсрочка оплаты'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYDAY IS 'Дата оплаты в каждом месяце'/

COMMENT ON COLUMN DDL_LEG_TMP.T_LEGKIND IS 'Номер значения (алгоритма)'/

COMMENT ON COLUMN DDL_LEG_TMP.T_SCALE IS 'Масштаб ставки'/

COMMENT ON COLUMN DDL_LEG_TMP.T_POINT IS 'Число знаков после запятой в ставке'/

COMMENT ON COLUMN DDL_LEG_TMP.T_ISCALCUSED IS 'Признак использования калькулятора'/

COMMENT ON COLUMN DDL_LEG_TMP.T_LEGNUMBER IS 'Пользовательский номер транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RELATIVEPRICE IS 'Признак задания цены в процентах'/

COMMENT ON COLUMN DDL_LEG_TMP.T_NKD IS 'НКД'/

COMMENT ON COLUMN DDL_LEG_TMP.T_TOTALCOST IS 'Полная стоимость'/

COMMENT ON COLUMN DDL_LEG_TMP.T_MATURITYISPRINCIPAL IS 'Дата завершения транша - принципала'/

COMMENT ON COLUMN DDL_LEG_TMP.T_REGISTRAR IS 'Регистратор'/

COMMENT ON COLUMN DDL_LEG_TMP.T_INCOMERATE IS 'Ставка дохода'/

COMMENT ON COLUMN DDL_LEG_TMP.T_INCOMESCALE IS 'Масштаб ставки дохода'/

COMMENT ON COLUMN DDL_LEG_TMP.T_INCOMEPOINT IS 'Точность дохода'/

COMMENT ON COLUMN DDL_LEG_TMP.T_INTERESTSTART IS 'Дата начала начисления процентов'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RECEIPTAMOUNT IS 'Полученная сумма'/

COMMENT ON COLUMN DDL_LEG_TMP.T_REGISTRARCONTRID IS 'Договор с регистратором'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PRINCIPALBASE IS 'База даты транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PRINCIPALDIFF IS 'Срок транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_STARTBASE IS 'Базовая дата начала транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_STARTDIFF IS 'Срок начала транша'/

COMMENT ON COLUMN DDL_LEG_TMP.T_BASE IS 'База даты оплаты'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYREGTAX IS 'Платить регсбор'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RETURNINCOME IS 'Сумма возвращаемого дохода'/

COMMENT ON COLUMN DDL_LEG_TMP.T_REJECTDATE IS 'Дата отказа от сделки/2части'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DELIVERINGFIID IS 'Поставляемый выпуск'/

COMMENT ON COLUMN DDL_LEG_TMP.T_BITMASK IS 'Битовые флаги состояний'/

COMMENT ON COLUMN DDL_LEG_TMP.T_OPERSTATE IS 'Статус операции'/

COMMENT ON COLUMN DDL_LEG_TMP.T_SUPPLYTIME IS 'Время поставки'/

COMMENT ON COLUMN DDL_LEG_TMP.T_TABLEPERCENT IS 'Таблица процентных ставок'/

COMMENT ON COLUMN DDL_LEG_TMP.T_TYPEPERCENT IS 'Тип ставки'/

COMMENT ON COLUMN DDL_LEG_TMP.T_CAPTION IS 'Псевдоним индекса/ставки'/

COMMENT ON COLUMN DDL_LEG_TMP.T_TYPEDATE IS 'Вид даты'/

COMMENT ON COLUMN DDL_LEG_TMP.T_COUNTDAY IS 'Кол-во дней'/

COMMENT ON COLUMN DDL_LEG_TMP.T_CORRECT IS 'Корректировка'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYFIID IS 'Валюта оплаты'/

COMMENT ON COLUMN DDL_LEG_TMP.T_NKDFIID IS 'T_NKDFIID'/

COMMENT ON COLUMN DDL_LEG_TMP.T_SROK IS 'T_SROK'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DEPOSITID IS 'T_DEPOSITID'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DVP IS 'Поставка против платежа'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DMAXPAY IS 'Необходимо удержать налог с получателя'/

COMMENT ON COLUMN DDL_LEG_TMP.T_QRETURN IS 'Количество ц/б - ожидается возврата дивидендов от КА'/

COMMENT ON COLUMN DDL_LEG_TMP.T_QRECEIVE IS 'Количество ц/б - для возврата дивидендов КА'/

COMMENT ON COLUMN DDL_LEG_TMP.T_SUMINCOME IS 'Сумма начисления дохода по дивидендам'/

COMMENT ON COLUMN DDL_LEG_TMP.T_MOVEDATE IS 'Дата переноса на счета к исполнению'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PLANMATURITY IS 'Планируемая дата погашения'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYERINCRTAXRATE IS 'Повышенная ставка налога плательщика'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYERINCRTAX IS 'Повышенный налог плательщика'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RECEIVERINCRTAXRATE IS 'Повышенная ставка налога получателя'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RECEIVERINCRTAX IS 'Повышенный налог получателя'/

COMMENT ON COLUMN DDL_LEG_TMP.T_ID_FROM IS 'Идентификатор транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DEALID_FROM IS 'Идентификатор сделки 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_LEGID_FROM IS 'Номер транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PFI_FROM IS 'Финансовый инструмент принципала 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_CFI_FROM IS 'Финансовый инструмент цены 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_START_FROM IS 'Дата начала транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_MATURITY_FROM IS 'Дата завершения транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_EXPIRY_FROM IS 'Дата фиксинга, пересмотра ставки 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PRINCIPAL_FROM IS 'Объем транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PRICE_FROM IS 'Действующая ставка, курс 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_BASIS_FROM IS 'Базис начисления процентов 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DURATION_FROM IS 'Продолжительность периода 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PITCH_FROM IS 'Единица измерения продолжительности периода 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_COST_FROM IS 'Накопленный доход 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_MODE_FROM IS 'Режим начисления процентов 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_CLOSED_FROM IS 'Дата закрытия 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_REFRATE_FROM IS 'Идентификатор референтной котировки 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_FACTOR_FROM IS 'Коэффициент ставки, курса 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_FORMULA_FROM IS 'Метод формирования ставки, цены 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_VERSION_FROM IS 'Номер обновления 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RESERVE0_FROM IS 'Идентификатор счета процентов 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PERIODNUMBER_FROM IS 'Количество временных интервалов 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PERIODTYPE_FROM IS 'Тип периода 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DIFF_FROM IS 'Отсрочка оплаты 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYDAY_FROM IS 'Дата оплаты в каждом месяце 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_LEGKIND_FROM IS 'Номер значения (алгоритма) 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_SCALE_FROM IS 'Масштаб ставки 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_POINT_FROM IS 'Число знаков после запятой в ставке 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_ISCALCUSED_FROM IS 'Признак использования калькулятора 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_LEGNUMBER_FROM IS 'Пользовательский номер транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RELATIVEPRICE_FROM IS 'Признак задания цены в процентах 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_NKD_FROM IS 'НКД 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_TOTALCOST_FROM IS 'Полная стоимость 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_MATURITYISPRINCIPAL_FROM IS 'Дата завершения транша - принципала 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_REGISTRAR_FROM IS 'Регистратор 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_INCOMERATE_FROM IS 'Ставка дохода 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_INCOMESCALE_FROM IS 'Масштаб ставки дохода 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_INCOMEPOINT_FROM IS 'Точность дохода 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_INTERESTSTART_FROM IS 'Дата начала начисления процентов 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RECEIPTAMOUNT_FROM IS 'Полученная сумма 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_REGISTRARCONTRID_FROM IS 'Договор с регистратором 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PRINCIPALBASE_FROM IS 'База даты транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PRINCIPALDIFF_FROM IS 'Срок транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_STARTBASE_FROM IS 'Базовая дата начала транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_STARTDIFF_FROM IS 'Срок начала транша 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_BASE_FROM IS 'База даты оплаты 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYREGTAX_FROM IS 'Платить регсбор 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RETURNINCOME_FROM IS 'Сумма возвращаемого дохода 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_REJECTDATE_FROM IS 'Дата отказа от сделки/2части 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DELIVERINGFIID_FROM IS 'Поставляемый выпуск 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_BITMASK_FROM IS 'Битовые флаги состояний 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_OPERSTATE_FROM IS 'Статус операции 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_SUPPLYTIME_FROM IS 'Время поставки 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_TABLEPERCENT_FROM IS 'Таблица процентных ставок 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_TYPEPERCENT_FROM IS 'Тип ставки 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_CAPTION_FROM IS 'Псевдоним индекса/ставки 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_TYPEDATE_FROM IS 'Вид даты 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_COUNTDAY_FROM IS 'Кол-во дней 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_CORRECT_FROM IS 'Корректировка 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYFIID_FROM IS 'Валюта оплаты 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_NKDFIID_FROM IS 'T_NKDFIID 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_SROK_FROM IS 'T_SROK 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DEPOSITID_FROM IS 'T_DEPOSITID 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DVP_FROM IS 'Поставка против платежа 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_DMAXPAY_FROM IS 'Необходимо удержать налог с получателя 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_QRETURN_FROM IS 'Количество ц/б - ожидается возврата дивидендов от КА 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_QRECEIVE_FROM IS 'Количество ц/б - для возврата дивидендов КА 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_SUMINCOME_FROM IS 'Сумма начисления дохода по дивидендам 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_MOVEDATE_FROM IS 'Дата переноса на счета к исполнению 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PLANMANURITY_FROM IS 'Дата погашения планируемая'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYERINCRTAXRATE_FROM IS 'Повышенная ставка налога плательщика 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_PAYERINCRTAX_FROM IS 'Повышенный налог плательщика 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RECEIVERINCRTAXRATE_FROM IS 'Повышенная ставка налога получателя 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_RECEIVERINCRTAX_FROM IS 'Повышенный налог получателя 2'/

COMMENT ON COLUMN DDL_LEG_TMP.T_ACTION IS 'Действие'/

CREATE UNIQUE INDEX DDL_LEG_TMP_IDX0 ON DDL_LEG_TMP
(T_LEGKIND, T_DEALID, T_LEGID)
/

CREATE UNIQUE INDEX DDL_LEG_TMP_IDX1 ON DDL_LEG_TMP
(T_ID)
/

CREATE OR REPLACE TRIGGER DDL_LEG_TMP_T1_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DDL_LEG_TMP FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DDL_LEG_TMP_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DDL_LEG_TMP_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/