/*Добавление настройки*/
DECLARE
  v_ID       NUMBER := 0;
  v_ParentID NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = 0 AND LOWER(T_NAME) = LOWER('COMMON');
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('НДФЛ');

  INSERT INTO DREGPARM_DBT(T_KEYID,T_PARENTID,T_NAME,T_TYPE,T_GLOBAL,T_DESCRIPTION,T_SECURITY,T_ISBRANCH,T_TEMPLATE)
  VALUES(0,v_ParentID,'УЧЕТ_NKDB_TS_В_ДОХ',4,'X','Участие NkdB_TS при расчете НДР 4-го уровня вида ProcSec. YES - да, NO - нет',CHR(0),CHR(0),CHR(1)) returning T_KEYID INTO v_ID;


  INSERT INTO DREGPARMTAG_DBT(T_ID, T_KEYID, T_TAG1, T_TAG2, T_TAG3, T_TAG4, T_TAG5, T_TAG6, T_TAG7, T_TAG8, T_TAG9, T_TAG10)
              VALUES(0, v_ID, 'TAX', CHR(1), CHR(1), CHR(1), CHR(1), CHR(1), CHR(1), CHR(1), CHR(1), CHR(1));

  
  INSERT INTO DREGPARMSTORY_DBT(T_ID, T_KEYID, T_DATEBEGIN, T_DATEEND, T_INTVALUE, T_DOUBLEVALUE, T_BOOLVALUE, T_STRINGVALUE)
       VALUES (0, v_ID, TO_DATE('01.01.0001', 'DD.MM.YYYY'), TO_DATE('31.12.2023', 'DD.MM.YYYY'), 0, 0, CHR(0), CHR(1));

  INSERT INTO DREGPARMSTORY_DBT(T_ID, T_KEYID, T_DATEBEGIN, T_DATEEND, T_INTVALUE, T_DOUBLEVALUE, T_BOOLVALUE, T_STRINGVALUE)
       VALUES (0, v_ID, TO_DATE('01.01.2024', 'DD.MM.YYYY'), TO_DATE('31.12.2024', 'DD.MM.YYYY'), 0, 0, 'X', CHR(1));

  INSERT INTO DREGPARMSTORY_DBT(T_ID, T_KEYID, T_DATEBEGIN, T_DATEEND, T_INTVALUE, T_DOUBLEVALUE, T_BOOLVALUE, T_STRINGVALUE)
       VALUES (0, v_ID, TO_DATE('01.01.2025', 'DD.MM.YYYY'), TO_DATE('31.12.9999', 'DD.MM.YYYY'), 0, 0, CHR(0), CHR(1));
  
  INSERT INTO DREGVAL_DBT(T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX )
  VALUES(v_ID,0,0,CHR(0),0,0,0,'');




EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/
