/*Добавить блок в операцию*/
DECLARE
  v_OperBlockID NUMBER := 0;
BEGIN

  INSERT INTO DOPROBLCK_DBT(T_OPERBLOCKID,T_KIND_OPERATION,T_BLOCKID,T_SORT,T_NOTINUSE,T_NOINSERT,T_NOREPLACE,T_NOCLOSEINSERT,T_ISMANUAL,
                            T_SYMBOLSFORINSERTION,T_SYMBOL)
  VALUES(0,2035,203516,17,CHR(0),CHR(0),CHR(0),'X',CHR(0),CHR(1),CHR(0)) RETURNING T_OPERBLOCKID INTO v_OperBlockID;

  INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
  VALUES(v_OperBlockID,46051,1,0);

  INSERT INTO DOPRCBLCK_DBT(T_OPERBLOCKID,T_STATUSKINDID,T_NUMVALUE,T_CONDITION)
  VALUES(v_OperBlockID,46052,12,0);


EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/