CREATE OR REPLACE TRIGGER DLCONTRINFBROK_TMP_TBIU
  BEFORE INSERT OR UPDATE 
  ON DDLCONTRINFBROK_TMP
  FOR EACH ROW
DECLARE
BEGIN

  IF (INSERTING AND :NEW.T_CHANGEDATE = TO_DATE('01.01.0001','DD.MM.YYYY')) OR UPDATING THEN
    :NEW.T_CHANGEDATE := TRUNC(SYSDATE);
    :NEW.T_CHANGETIME := TO_DATE('01-01-0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD-MM-YYYY:HH24:MI:SS'); 
  END IF;

END;
/

CREATE OR REPLACE TRIGGER DLCONTRINFBROK_DBT_TBIU
  BEFORE INSERT OR UPDATE 
  ON DDLCONTRINFBROK_DBT
  FOR EACH ROW
DECLARE
BEGIN

  IF (INSERTING AND :NEW.T_CHANGEDATE = TO_DATE('01.01.0001','DD.MM.YYYY')) OR UPDATING THEN
    :NEW.T_CHANGEDATE := TRUNC(SYSDATE);
    :NEW.T_CHANGETIME := TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'); 
  END IF;

END;
/

CREATE OR REPLACE TRIGGER DDLCONTRINFBROK_DBT_VERSION
  BEFORE INSERT OR UPDATE ON DDLCONTRINFBROK_DBT FOR EACH ROW
DECLARE
BEGIN
  IF :old.t_version is not null THEN
    :new.t_version := :old.t_version + 1;
  ELSE
    :new.t_version := 0;
  END IF;
END;
/