/*
    $Name: ir_CM032.mac
    $Module:   Репозитарий
    $Description:  Анкета договора процентного свопа 
*/

import "ir_CMBase.mac";

private macro GetIndexNrdName(IndexID) 
var dl_sql, dl_cmd, dl_rs;
dl_sql = "SELECT t1.\*, t2.t_name " +
"  FROM dobjatcor_dbt t1, dobjattr_dbt t2 " +
" WHERE     t1.t_groupid = t2.t_groupid " +
"       AND t1.t_attrid = t2.t_attrid " +
"       AND t1.t_objecttype = t2.t_objecttype " +
"       AND t2.t_objecttype = 13 " +
"       AND t1.t_groupid = 101 and t1.t_object = ? " ;
dl_cmd = dl_RSDCommand(dl_sql);
dl_cmd.AddParam(IndexID);
dl_rs = dl_cmd.execute();
if (dl_rs.movenext())
  return dl_rs.Name;
end;
 msgbox("Требуется проверить корректность индекса плавающей ставки!");
 return GetValueLLName( 4095 /*OBJTYPE_INDEX_FLOATRATE*/, indexID )
end;

class (CMBase) CM032 ( _isRecon, _conveyerID, _ir_op : object)
  InitCMBase();

  m_isRecon     = _isRecon;
  m_conveyerID  = _conveyerID;
  m_ir_op       = _ir_op;
  m_MessageID   = REPOS_CM032;

  macro addCMAll(ir_generalinf     ,
                 TradeRepository   ,
                 Party1            ,
                 Party2            ,
                 UTIGeneratingParty,
                 Sender            ,
                 cm                ,
                 GrDealID          ,
                 TemplNum          ,
                 DealParmForReport )
    addGenInf(ir_generalinf, TemplNum, DealParmForReport);
    addRepAccGrDoc(GrDealID);
    addcmGrDoc(GrDealID);
    addParty(TradeRepository, Party1, Party2, UTIGeneratingParty, Sender);
    addCM(cm);
  end;

  macro insertAll
    var err = 0;
    err = insertGeneralinf;
    if (not err)
      err = insertParty;
    end;
    if (not err)
      err = insertDlgrdocCache;
    end;
    if (not err)
      err = insertCM;
    end;
    return err;
  end;

  macro ЗаполнениеCM (cm : @TrecHandler,
                      DataSet,

                      GenAgr,
                      FD)
    var rateFI = TRecHandler("fininstr.dbt");
    var FD2 = DVFirstDocNDeal(DataSet.DocKind, DataSet.DocID, 2);
    var PaymCount = FD.GetPaymentsCount();
    var PaymFloatRate = FD.GetPmFloatRate();

    cm.rec.PayerParty_O1ID = IR_PARTY_KIND_PARTY1;
    cm.rec.PayerParty_O1 = "Party1";
    cm.rec.ReceiverParty_O1ID = IR_PARTY_KIND_PARTY2;
    cm.rec.ReceiverParty_O1 = "Party2";
    cm.rec.EffectiveDate   = FD.ДатаНачала();
    cm.rec.TerminationDate = FD.ДатаИсполнения();
    cm.rec.NomValue_O1 = FD.nFI_().rec.Amount;
    cm.rec.NomCurrency_O1ID = FD.nFI_().rec.FIID;
    cm.rec.NomCurrency_O1 = GetFICode(cm.rec.NomCurrency_O1ID, null, FICK_ISOSTRING);
    //cm.rec.InitialExchange_O1;
    //cm.rec.FinalExchange_O1;
    //cm.rec.IntermediateExchange_O1;
    cm.rec.PeriodMultiplier_O1 = FD.nFI_().rec.Period;
    // NA: ALG_DV_PERIODKIND_PRRATE=7021 -> NA: ALG_DV_PAYMPERIODKIND=7041,7042
    if( PaymCount == 1 )
        cm.rec.PeriodType_O1ID = 1;   // срок сделки
        cm.rec.PeriodMultiplier_O1 = 1;
    elif( FD.nFI_().rec.PeriodKind == 1 )
        cm.rec.PeriodType_O1ID = 2;   // день
    elif( FD.nFI_().rec.PeriodKind == 2 )
        cm.rec.PeriodType_O1ID = 4;   // месяц
    elif( FD.nFI_().rec.PeriodKind == 3 )
        cm.rec.PeriodType_O1ID = 5;   // год
    end;
    cm.rec.PeriodType_O1 = DL_GetNameAlg( 7041 /*ALG_DV_PAYMPERIODKIND*/, cm.rec.PeriodType_O1ID );
    
    if( (FD.Deal.rec.Type == ALG_DV_FIX_FLOAT) or (FD.Deal.rec.Type == ALG_DV_FIX_FIX) )
        cm.rec.FixRate_O1 = "Y";
        cm.rec.FloatRate_O1 = "N";
        cm.rec.Rate_O1 = FD.nFI_().rec.Rate * 1.0 / 100;
    else
        cm.rec.FixRate_O1 = "N";
        cm.rec.FloatRate_O1 = "Y";
        cm.rec.FloatingRateIndex_O1ID = FD.nFI_().rec.RateIndex;
    //    cm.rec.FloatingRateIndex_O1 = GetValueLLName( 4074 /*OBJTYPE_INDEX_FLOATRATE*/, cm.rec.FloatingRateIndex_O1ID );
        cm.rec.FloatingRateIndex_O1 = GetIndexNrdName (FD.nFI_().rec.RateID);
        cm.rec.Spread_O1 = FD.nFI_().rec.Spread * 1.0 / 100;
        cm.rec.FloatingRate_O1 = PaymFloatRate * 1.0 / 100;
        if( ПолучитьФинИн(FD.nFI_().rec.RateID, rateFI) == 0 )
            cm.rec.FloatPeriodMultiplier_O1 = rateFI.rec.Duration;
            // NA: ALG_CB_RATE_PERIOD=2350 -> NA: ALG_DV_PAYMPERIODKIND=7041,7042
            if( rateFI.rec.TypeDuration == 1 )      // день
                cm.rec.FloatPeriodType_O1ID = 2;
            elif( rateFI.rec.TypeDuration == 2 )    // неделя
                cm.rec.FloatPeriodType_O1ID = 3;
            elif( rateFI.rec.TypeDuration == 3 )    // месяц
                cm.rec.FloatPeriodType_O1ID = 4;
            elif( rateFI.rec.TypeDuration == 4 )    // год
                cm.rec.FloatPeriodType_O1ID = 5;
            end;
            cm.rec.FloatPeriodType_O1 = DL_GetNameAlg( 7041 /*ALG_DV_PAYMPERIODKIND*/, cm.rec.FloatPeriodType_O1ID );
        end;
    end;
    // NA: ALG_PC_BASIS=2317 -> ALG_GENINF_DAYCOUNTCALC=8118
    if( FD.nFI_().rec.Basis == 8 )     // BASIS_ACT365 - 365 дней в году / в месяце по календарю
        cm.rec.DayCountFraction_O1ID = 0;
    elif( FD.nFI_().rec.Basis == 1 )   // BASIS_30360 - 360 дней в году / 30 дней в месяце
        cm.rec.DayCountFraction_O1ID = 1;
    elif( FD.nFI_().rec.Basis == 4 )   // BASIS_ACTACT - в году по календарю / в месяце по календарю
        cm.rec.DayCountFraction_O1ID = 2;
    elif( FD.nFI_().rec.Basis == 2 )   // BASIS_ACT360 - 360 дней в году / в месяце по календарю
        cm.rec.DayCountFraction_O1ID = 3;
    end;
    cm.rec.DayCountFraction_O1 = DL_GetNameAlg( 8118 /*ALG_GENINF_DAYCOUNTCALC*/, cm.rec.DayCountFraction_O1ID );

    cm.rec.PayerParty_O2ID = IR_PARTY_KIND_PARTY2;
    cm.rec.PayerParty_O2 = "Party2";
    cm.rec.ReceiverParty_O2ID = IR_PARTY_KIND_PARTY1;
    cm.rec.ReceiverParty_O2 = "Party1";
    cm.rec.EffectiveDate_O2 = cm.rec.EffectiveDate;
    cm.rec.TerminationDate_O2 = cm.rec.TerminationDate;
    cm.rec.NomValue_O2 = FD2.nFI_().rec.Amount;
    cm.rec.NomCurrency_O2ID = FD2.nFI_().rec.FIID;
    cm.rec.NomCurrency_O2 = GetFICode(cm.rec.NomCurrency_O2ID, null, FICK_ISOSTRING);
    //cm.rec.InitialExchange_O2;
    //cm.rec.FinalExchange_O2;
    //cm.rec.IntermediateExchange_O2;
    cm.rec.PeriodMultiplier_O2 = FD2.nFI_().rec.Period;
    // NA: ALG_DV_PERIODKIND_PRRATE=7021 -> NA: ALG_DV_PAYMPERIODKIND=7041,7042
    if( PaymCount == 1 )
        cm.rec.PeriodType_O2ID = 1;   // срок сделки
        cm.rec.PeriodMultiplier_O2 = 1;
    elif( FD2.nFI_().rec.PeriodKind == 1 )
        cm.rec.PeriodType_O2ID = 2;   // день
    elif( FD2.nFI_().rec.PeriodKind == 2 )
        cm.rec.PeriodType_O2ID = 4;   // месяц
    elif( FD2.nFI_().rec.PeriodKind == 3 )
        cm.rec.PeriodType_O2ID = 5;   // год
    end;
    cm.rec.PeriodType_O2 = DL_GetNameAlg( 7041 /*ALG_DV_PAYMPERIODKIND*/, cm.rec.PeriodType_O2ID );
    
    if( (FD2.Deal.rec.Type == ALG_DV_FLOAT_FIX) or (FD2.Deal.rec.Type == ALG_DV_FIX_FIX) )
        cm.rec.FixRate_O2 = "Y";
        cm.rec.FloatRate_O2 = "N";
        cm.rec.Rate_O2 = FD2.nFI_().rec.Rate * 1.0 / 100;
    else
        cm.rec.FixRate_O2 = "N";
        cm.rec.FloatRate_O2 = "Y";
        cm.rec.FloatingRateIndex_O2ID = FD2.nFI_().rec.RateIndex;
        //cm.rec.FloatingRateIndex_O2 = GetValueLLName( 4074 /*OBJTYPE_INDEX_FLOATRATE*/, cm.rec.FloatingRateIndex_O2ID );
        cm.rec.FloatingRateIndex_O2 = GetIndexNrdName (FD2.nFI_().rec.RateID);
        cm.rec.Spread_O2 = FD2.nFI_().rec.Spread * 1.0 / 100;
        cm.rec.FloatingRate_O2 = PaymFloatRate * 1.0 / 100;
        if( ПолучитьФинИн(FD2.nFI_().rec.RateID, rateFI) == 0 )
            cm.rec.FloatPeriodMultiplier_O2 = rateFI.rec.Duration;
            // NA: ALG_CB_RATE_PERIOD=2350 -> NA: ALG_DV_PAYMPERIODKIND=7041,7042
            if( rateFI.rec.TypeDuration == 1 )      // день
                cm.rec.FloatPeriodType_O2ID = 2;
            elif( rateFI.rec.TypeDuration == 2 )    // неделя
                cm.rec.FloatPeriodType_O2ID = 3;
            elif( rateFI.rec.TypeDuration == 3 )    // месяц
                cm.rec.FloatPeriodType_O2ID = 4;
            elif( rateFI.rec.TypeDuration == 4 )    // год
                cm.rec.FloatPeriodType_O2ID = 5;
            end;
            cm.rec.FloatPeriodType_O2 = DL_GetNameAlg( 7041 /*ALG_DV_PAYMPERIODKIND*/, cm.rec.FloatPeriodType_O2ID );
        end;
    end;
    // NA: ALG_PC_BASIS=2317 -> ALG_GENINF_DAYCOUNTCALC=8118
    if( FD2.nFI_().rec.Basis == 8 )     // BASIS_ACT365 - 365 дней в году / в месяце по календарю
        cm.rec.DayCountFraction_O2ID = 0;
    elif( FD2.nFI_().rec.Basis == 1 )   // BASIS_30360 - 360 дней в году / 30 дней в месяце
        cm.rec.DayCountFraction_O2ID = 1;
    elif( FD2.nFI_().rec.Basis == 4 )   // BASIS_ACTACT - в году по календарю / в месяце по календарю
        cm.rec.DayCountFraction_O2ID = 2;
    elif( FD2.nFI_().rec.Basis == 2 )   // BASIS_ACT360 - 360 дней в году / в месяце по календарю
        cm.rec.DayCountFraction_O2ID = 3;
    end;
    cm.rec.DayCountFraction_O2 = DL_GetNameAlg( 8118 /*ALG_GENINF_DAYCOUNTCALC*/, cm.rec.DayCountFraction_O2ID );
    
    return 0;
  end;
end;