/* IAL 11 November 2008                               */
/*                                                    */   
/* ДУ (Доверительное управление )                     */
/*                                                    */
/* Операция покупки ц/б внебиржевая  ДУ               */
/* Закрытие сделки                                    */

import InsCarryDoc, "tssec.mac";

macro ExecuteStep( doc, FDoc, DocKind, ID_Operation )
  
  record deal(dl_tick);

  var    FD, dat, error;

  SetBuff( deal, FDoc );
  FD = SPFirstDocTrust( deal, IsBackExec(deal, SP_EXECUTE_STEP_BUY) );

  GetOprDate( FD.GetKindDate(DATE_DEALEEND), dat );
  if( dat > {curdate} )
    MsgBox ("Преждевременное выполнение шага запрещено.");
    return 1;
  end;

  if( not FD.ПроверитьКомиссии( FD.pmwrtsum.rec ) )
     return SayErrorBuySale( deal,"Обработаны не все комиссии" );
  end;

  if( not ВыполненыВсеПроводки( FD, error ) )
     return SayErrorBuySale( deal, error );
  end;

  return 0;
end;  
