/*──────────────────────────────────────────────────────────────────────────┐
  RS-Bank 6.0                                          R-Style SoftLab

  File Name   : trvar340.mac
  Programmer  : Nikonorov Evgeny
  Операция    : Погашение векселей в ДУ
  Шаг         : 340 - Закрытие
└───────────────────────────────────────────────────────────────────────────*/
IMPORT PaymInter, vacateg, valib, vapaym, vaopr;


MACRO ExecuteStep(Buffer, dl_tick, DocKind, ID_Operation)
var
    stat = 0;

    record tick( dl_tick );
    SetBuff( tick, dl_tick );

    if(not VA_ArePaymsClosed(tick, BAi))     /* проверка платежей по активу */
      stat = VA_Err("Обязательства по сделке не исполнены");
    elif(not VA_ArePaymsClosed(tick, PM_PURP_PRINC_RET))   /* проверка платежей  */
      stat = VA_Err("Требования по сделке не исполнены");
    elif(not CheckAllStepsExecuted(ID_Operation))   /* проверка что все шаги выполнены */
      stat = VA_Err("Перед закрытием операции все шаги должны быть исполнены!");
    end;

    return stat;

END;


