import TSInter, "tsutil.mac", "tscateg.mac", "DlForms_h.mac", "tscomiss.mac", "TSCheckLimit.mac";

/*Номера полей в форме */
PRIVATE CONST PNFLD_A1      = 0,  /*Учредитель*/
              PNFLD_A2_1    = 1,  /*Договор №*/
              PNFLD_A2_2    = 2,  /*от*/
              PNFLD_A3      = 3,  /*ОФБУ*/
              PNFLD_A4      = 4,  /*Дата расчета*/
              PNFLD_A5      = 5,  /*Дата окончания расчетного периода*/
              PNFLD_A6_1    = 6,  /*Имущество в управлении (руб)*/
              PNFLD_A6_2    = 7,  /*Количество паев*/
              PNFLD_A7_1    = 8,  /*Выводятся: денежные средства*/
              PNFLD_A7_2    = 9,
              PNFLD_A8      = 10, /*Выводятся: Количество паев*/
              PNFLD_A30_1   = 11, /*Комиссия за досрочный вывод (руб)*/
              PNFLD_A30_2   = 12,
              PNFLD_A32_1   = 13, /*Комиссия за успешное управление (руб)*/
              PNFLD_A32_2   = 14,
              PNFLD_A33     = 15, /*Прибыль: общая*/
              PNFLD_A34     = 16, /*Прибыль: выводимая*/
              PNFLD_A35_1   = 17, /*Сумма налога*/
              PNFLD_A35_2   = 18,
              PNFLD_A36_1   = 19, /*Списываемый капитал (руб)*/
              PNFLD_A36_2   = 20,
              PNFLD_A40_1   = 21, /*Сумма к выплате*/
              PNFLD_A40_2   = 22,
              PNFLD_A41     = 23, /*Имущество, остающееся в управлении (руб)*/
              PNFLD_A42     = 24, /*Количество паев*/
              PNFLD_A70     = 25, /*Филиал  */
              PNFLD_A71     = 26, /*Исполнитель*/
              PNFLD_A71_1   = 27;

PRIVATE MACRO КоличествоПаевСтрокой(OrderFD_OFBU, Количество)
  return ДУ_ЧислоCЗаданнойТочностью(double(Количество), OrderFD_OFBU.Order().rec.DP_AmountPrecision);
END;


PRIVATE MACRO FldProc_Кдв_ф( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT ):INTEGER

  if( Cmd == DLG_INIT ) 
     FldShowValue = FldRealValue;
  elif( Cmd == DLG_CHANGEVALUE ) 
     FldRealValue = FldShowValue;
     if( FldRealValue < 0 )
        MsgBox( "Неверное значение поля.");
        return CM_IGNORE;
     end;
     pThis.AfterChange_Кдв_ф();
  end;
  return CM_DEFAULT;
END;

PRIVATE MACRO FldProc_Кусп_ф( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT ):INTEGER

  if( Cmd == DLG_INIT ) 
     FldShowValue = FldRealValue;
  elif( Cmd == DLG_CHANGEVALUE ) 
     FldRealValue = FldShowValue;
     if( FldRealValue < 0 )
        MsgBox( "Неверное значение поля.");
        return CM_IGNORE;
     end;
     pThis.AfterChange_Кусп_ф();
  end;
  return CM_DEFAULT;
END;

PRIVATE MACRO FldProc_Нкуд_ф( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT ):INTEGER

  if( Cmd == DLG_INIT ) 
     FldShowValue = FldRealValue;
  elif( Cmd == DLG_CHANGEVALUE ) 
     FldRealValue = FldShowValue;
     if( FldRealValue < 0 )
        MsgBox( "Неверное значение поля.");
        return CM_IGNORE;
     end;
     pThis.AfterChange_Нкуд_ф();
  end;
  return CM_DEFAULT;
END;

PRIVATE MACRO FldProc_Sпок_ф( pThis:DL_CPanel, Cmd:INTEGER, Key:INTEGER, FldShowValue:@VARIANT, FldRealValue:@VARIANT ):INTEGER

  if( Cmd == DLG_INIT ) 
     FldShowValue = FldRealValue;
  elif( Cmd == DLG_CHANGEVALUE ) 
     FldRealValue = FldShowValue;
     pThis.AfterChange_Sпок_ф();
  end;
  return CM_DEFAULT;
END;

CLASS (DL_CPanel) CItogs_Panel_OF( _Itogs:TArray, _Order:TRecHandler, _Req:TRecHandler, _IsProlongation:BOOL, _ReadOnly:BOOL, _EndCalcDate:DATE,
                                   _ID_Operation:INTEGER, _ID_Step:INTEGER, _CalcCom:DataCalcCom )

  VAR OrderFD:TS_OrderFD = NULL,
      OrderFD_OFBU:TS_OrderFD,
      UseNDFL,
      ID_Operation   = _ID_Operation, 
      ID_Step        = _ID_Step,
      Itogs          = _Itogs,
      EndCalcDate    = _EndCalcDate,
      ReadOnly       = _ReadOnly,
      ReqFD:TS_RequestFD = NULL, 
      IsProlongation = _IsProlongation,
      CalcCom        = _CalcCom;

  PRIVATE MACRO DocKind()
     if( ReqFD != NULL )
        return ReqFD.Kind;
     end;
     return 0;
  END;

  PRIVATE MACRO DocID()
     if( ReqFD != NULL )
        return ReqFD.Id;
     end;
     return 0;
  END;

  PRIVATE MACRO SaveItogsInBD( Itog:INTEGER ):BOOL
     if( OrderFD.SaveItog( Itog, Itogs[Itog], NATCUR, EndCalcDate, null, null, TS_TOTAL_SUMMA_IN, TS_TOTAL_SUMMA_ALL, DocKind(), DocID() ) != 0 )
         return false;
     end;
     return true;
  END;

  PRIVATE MACRO SaveAllItogsInBD():BOOL

     if( ReadOnly == false )

        if( (not SaveItogsInBD(ДУ_Sзаявл) ) OR
            (not SaveItogsInBD(ДУ_Кдв)    ) OR
            (not SaveItogsInBD(ДУ_Кдв_ф)  ) OR
            (not SaveItogsInBD(ДУ_Кусп)   ) OR
            (not SaveItogsInBD(ДУ_Кусп_ф) ) OR
            (not SaveItogsInBD(ДУ_Sвыпл)  ) OR
            (not SaveItogsInBD(ДУ_СКост)  )
          )
           return false;
        end;

        if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )
           if( (not SaveItogsInBD(ДУ_SзаявП) ) OR
               (not SaveItogsInBD(ДУ_Побщ)   ) OR
               (not SaveItogsInBD(ДУ_Пвыв_в) ) OR
               (not SaveItogsInBD(ДУ_Нкуд)   ) OR
               (not SaveItogsInBD(ДУ_Нкуд_ф) ) OR
               (not SaveItogsInBD(ДУ_СПок)   ) OR
               (not SaveItogsInBD(ДУ_СПок_ф) ) OR
               (not SaveItogsInBD(ДУ_СКостП) )
             )
              return false;
           end;
        else
            if( not SaveItogsInBD(ДУ_Sкап) )
              return false;
            end;
        end;

     end;
     return true;
  END;

  PRIVATE MACRO SaveItogsToPanel()

     if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )

        m_Panel.rec.A6_1  = Itogs[ДУ_ИТОГ_СК]; /* Имущество в управлении (руб) */
        m_Panel.rec.A6_2  = КоличествоПаевСтрокой(OrderFD_OFBU, Itogs[ДУ_КПУ]);     /* Количество паев */

        m_Panel.rec.A7_1  = Itogs[ДУ_Sзаявл];  /* Выводятся: денежные средства */
        m_Panel.rec.A8    = КоличествоПаевСтрокой(OrderFD_OFBU, Itogs[ДУ_SзаявП]);  /* Выводятся: количество паев */

        m_Panel.rec.A30_1 = Itogs[ДУ_Кдв];     /* Комиссия за досрочный вывод (руб) */
        m_Panel.rec.A30_2 = Itogs[ДУ_Кдв_ф];
        m_Panel.rec.A32_1 = Itogs[ДУ_Кусп];    /* Комиссия за успех (руб) */
        m_Panel.rec.A32_2 = Itogs[ДУ_Кусп_ф];

        m_Panel.rec.A33   = Itogs[ДУ_Побщ];    /* Прибыль: общая */
        m_Panel.rec.A34   = Itogs[ДУ_Пвыв_в];  /* Прибыль: выводимая */

        m_Panel.rec.A35_1 = Itogs[ДУ_Нкуд];    /* Сумма налога */
        m_Panel.rec.A35_2 = Itogs[ДУ_Нкуд_ф];
        m_Panel.rec.A36_1 = Itogs[ДУ_СПок];    /* Списываемый капитал */
        m_Panel.rec.A36_2 = Itogs[ДУ_СПок_ф];

        m_Panel.rec.A40_1 = Itogs[ДУ_Sвыпл];   /* Сумма к выплате */
        m_Panel.rec.A41   = Itogs[ДУ_СКост];   /* Имущество, остающееся в управлении */
        m_Panel.rec.A42   = КоличествоПаевСтрокой(OrderFD_OFBU, Itogs[ДУ_СКостП]);  /* Имущество, остающееся в управлении (паи) */

     else

        m_Panel.rec.A6_1  = Itogs[ДУ_ИТОГ_СК]; /* Имущество в управлении (руб) */
        m_Panel.rec.A30_1 = Itogs[ДУ_Кдв];     /* Комиссия за досрочный вывод (руб) */
        m_Panel.rec.A30_2 = Itogs[ДУ_Кдв_ф];
        m_Panel.rec.A32_1 = Itogs[ДУ_Кусп];    /* Комиссия за успех (руб) */
        m_Panel.rec.A32_2 = Itogs[ДУ_Кусп_ф];
        m_Panel.rec.A36_1 = Itogs[ДУ_Sкап];    /* Списываемый капитал (руб) */
        m_Panel.rec.A36_2 = m_Panel.rec.A36_1;
        m_Panel.rec.A40_1 = Itogs[ДУ_Sвыпл];   /* Сумма к выплате */
        m_Panel.rec.A41   = Itogs[ДУ_СКост];   /* Имущество, остающееся в управлении */

        if( ReqFD )
           m_Panel.rec.A7_1  = Itogs[ДУ_Sзаявл]; /* Если частичный вывод ДС */
        end;

     end;
  END;

  PRIVATE MACRO SaveItogsFromPanel()
     Itogs[ДУ_Кдв_ф]  = m_Panel.rec.A30_2;
     Itogs[ДУ_Кусп_ф] = m_Panel.rec.A32_2;
     Itogs[ДУ_Sвыпл]  = m_Panel.rec.A40_1;

     if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )
        Itogs[ДУ_Нкуд_ф] = m_Panel.rec.A35_2;
        Itogs[ДУ_СПок_ф] = m_Panel.rec.A36_2;
     end;
  END;

  PRIVATE MACRO РасчетПриПролонгации():INTEGER
     return 0;
  END;

  PRIVATE MACRO ReadSaveItog( ItogNum:@INTEGER )
     if( ПолучитьИтогДУ( OrderFD.ID, ItogNum, NULL, 0, NULL, DocKind(), DocID(), EndCalcDate, @Itogs[ItogNum] , NULL, NULL ) )
        MsgBox( "Ошибка при получении итога по операции" );
        return 1;
     end;
     return 0;
  END;

  PRIVATE MACRO ДатаПоследнегоИтогаКуспПоДоговору( OrderID:integer, CalcDate:date ):date

     var RetVal:date = date(0,0,0);
     var cmd, RSD;

     cmd = RSDCommand( " SELECT max(t_BeginDate) as BeginDate " +
                       "   FROM dtstotal_dbt                  " +
                       "  WHERE t_OrderID    = ?              " + 
                       "    AND t_TotalType  = ?              " +
                       "    AND t_BeginDate  < ?              "
                     );

     cmd.NullConversion = true;
     cmd.addParam( "", RSDBP_IN, OrderID        );
     cmd.addParam( "", RSDBP_IN, ДУ_ИТОГ_Н_Кусп );
     cmd.addParam( "", RSDBP_IN, CalcDate       );
     cmd.execute();

     RSD = TRsbDataSet( cmd );
     if( RSD.MoveNext() and (RSD.BeginDate != NULL) )
        RetVal = SQL_ConvTypeDate(RSD.BeginDate);
     end;

     return RetVal;
  END;

  PRIVATE MACRO ДатаПоследнегоИтогаКусп( OrderFD:TS_OrderFD, CalcDate:date )

     var RetVal:date = date(0,0,0);
     var LastDate:date, LastDate_OFBU:date;

     LastDate = ДатаПоследнегоИтогаКуспПоДоговору( OrderFD.Order().rec.ID, CalcDate );
     LastDate_OFBU = ДатаПоследнегоИтогаКуспПоДоговору( OrderFD.Order().rec.OFBU, CalcDate );
     if( (LastDate_OFBU != date(0,0,0)) and (OrderFD.КапиталУчредителя(LastDate_OFBU) <= 0.0) )
        LastDate_OFBU = date(0,0,0);
     end;

     if( (LastDate != date(0,0,0)) or (LastDate_OFBU != date(0,0,0)) )
        if( (LastDate != date(0,0,0)) and (LastDate_OFBU != date(0,0,0)) )
           if(LastDate > LastDate_OFBU)
              RetVal = LastDate + 1;
           else
              RetVal = LastDate_OFBU + 1;
           end;
        elif( LastDate != date(0,0,0) )
           RetVal = LastDate + 1;
        elif( LastDate_OFBU != date(0,0,0) )
           RetVal = LastDate_OFBU + 1;
        end;
     else
        RetVal = OrderFD.ДатаПервичногоВнесения() - 1;
     end;

     return RetVal;
  END;

  PRIVATE MACRO РасчетПриВыводеКапитала():INTEGER
     VAR Valid;

     if( (ReqFD.Request.rec.Status == 1/*TS_IOREQ_STATE_REG*/ ) OR
         (ReqFD.Request.rec.Status == 0/*TS_IOREQ_STATE_INP*/ )
       ) /*расчет*/

        if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )

           var BeginDate = ДатаПоследнегоИтогаКусп( OrderFD, EndCalcDate );
           var ТСНП:money = $0.0, СНПпн:money = $0.0, КПУ0:money = $0.0,
               СтП0:money = $0.0, СтП1:money = $0.0, СтП:money = $0.0;
           ТСНП = OrderFD.СНП(EndCalcDate);
           if(ТСНП == $0.0)
              MsgBox("Не задан курс пая на " + EndCalcDate);
              return 1;
           end;
           if( BeginDate != date(0,0,0) )
              СНПпн = OrderFD.СНП(BeginDate);
              if(СНПпн == $0.0)
                 MsgBox("Не задан курс пая на " + BeginDate);
                 return 1;
              end;
           end;

           Itogs[ДУ_СПок_ф]  = Itogs[ДУ_СПок] = ReqFD.СтоимостьПокупкиВыводимыхПаев(EndCalcDate, ТСНП, @Itogs[ДУ_Sзаявл], @Itogs[ДУ_SзаявП], null, true);
           Itogs[ДУ_КПУ]     = OrderFD.КоличествоПаев( EndCalcDate );
           Itogs[ДУ_ИТОГ_СК] = OrderFD.КапиталУчредителя( EndCalcDate );
           Itogs[ДУ_Побщ]    = Itogs[ДУ_Sзаявл] - Itogs[ДУ_СПок_ф];
           if(ReqFD.IsOutFULL() == true)
              Itogs[ДУ_Sкап] = OrderFD.ОстатокПоСчету( "Капитал ДУ", EndCalcDate );
              Itogs[ДУ_СПок_ф]  = Itogs[ДУ_СПок] = Itogs[ДУ_Sкап];
           else
              Itogs[ДУ_Sкап] = Itogs[ДУ_СПок_ф];
           end;

           /* комиссия за успех */
           if( BeginDate != date(0,0,0) )
              var Sпок = max(0, ReqFD.СтоимостьПокупкиВыводимыхПаев(EndCalcDate, null, null, null, @КПУ0, false, BeginDate));
              СтП0 = КПУ0 * (ТСНП - СНПпн);
              СтП1 = (Itogs[ДУ_SзаявП] - КПУ0) * ТСНП - Sпок;
              СтП  = СтП0 + СтП1;
              if(СтП > 0)
                 CalcCom.CalcDateS = EndCalcDate;
                 if( РасчетКомиссииБанкаЗаУспех( OrderFD, DocID(), EndCalcDate, TS_ComissSum( СтП, NATCUR ), ДосрочныйВывод, @CalcCom.ConCom_S, @CalcCom.sfdefcom_parm_S ) != 0 )
                    MsgBox( "Ошибка при расчете комиссии за успех." );
                    return 1;
                 end;
                 Itogs[ДУ_Кусп] = Itogs[ДУ_Кусп_ф] = CalcCom.sfdefcom_parm_S.rec.CommSum;
              end;
           end;

           /* комиссия за досрочный вывод */
           if( (ReqFD.Request.rec.Moratorium != "X") AND (ReqFD.Request.rec.TransferOFBU != "X") )
              var BeginInDate = OrderFD.ДатаПервичногоВнесения();
              if( (BeginInDate != Date(0,0,0)) and ((EndCalcDate - BeginInDate) >= 0) and ((EndCalcDate - BeginInDate) <= 365) )
                 CalcCom.CalcDateP = EndCalcDate;
                 if( РасчетКомиссииЗаДосрочныйВывод( OrderFD, DocID(), EndCalcDate, TS_ComissSum( (Itogs[ДУ_Sзаявл] - Itogs[ДУ_Кусп_ф]), NATCUR ), ДосрочныйВывод, @CalcCom.ConCom_P, @CalcCom.sfdefcom_parm_P ) != 0 )
                    MsgBox( "Ошибка при расчете комиссии за досрочный вывод." );
                    return 1;
                 end;
                 Itogs[ДУ_Кдв] = Itogs[ДУ_Кдв_ф] = CalcCom.sfdefcom_parm_P.rec.CommSum;
              end;
           end;

           if( UseNDFL )
              Itogs[ДУ_Нкуд_ф] = Itogs[ДУ_Нкуд] = max(0, round(((Itogs[ДУ_Побщ] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф]) * СТАВКА_НА_ДОХОДЫ_ФЛ() / 100), 0));
           end;

           Itogs[ДУ_Пвыв_в] = Itogs[ДУ_Побщ] - Itogs[ДУ_Нкуд_ф] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф];
           Itogs[ДУ_СКост]  = Itogs[ДУ_ИТОГ_СК] - Itogs[ДУ_Sкап];
           Itogs[ДУ_СКостП] = Itogs[ДУ_КПУ] - Itogs[ДУ_SзаявП];
           Itogs[ДУ_Sвыпл]  = Itogs[ДУ_Sзаявл] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф] - Itogs[ДУ_Нкуд_ф];
        else

           ReqFD.ПолучитьСуммыВывода( EndCalcDate, @Itogs[ДУ_Sзаявл] );

           Itogs[ДУ_ИТОГ_СК] = OrderFD.КапиталУчредителя( EndCalcDate );
           Itogs[ДУ_Sкап]    = Itogs[ДУ_Sзаявл];

           /* комиссия за успех */
           /* код не для дистрибутивной комиссии, так как сейчас в дистрибутиве не выставлен момент взимания = вывод капитала */
           var ПУ1:money = $0.0, ПУ2:money = $0.0, Кдв2:money = $0.0, Кдв1:money = $0.0, DP:money = $0.0;
           if( ПолучитьИтогДУ( OrderFD.Order().rec.ID, ДУ_ИТОГ_Н_Кдв, NULL, 0, NULL, NULL, NULL, OrderFD.ДатаНачалаПР(EndCalcDate), @Кдв1 ) != 0 )
              return 1;
           end;
           if( ПолучитьИтогДУ( OrderFD.Order().rec.ID, ДУ_ИТОГ_Н_Кдв, NULL, 0, NULL, NULL, NULL, EndCalcDate, @Кдв2 ) != 0 )
              return 1;
           end;
           if( ПолучитьИтогДУ( OrderFD.Order().rec.ID, ДУ_ИТОГ_ПУ, NULL, 0, NULL, NULL, NULL, OrderFD.ДатаНачалаПР(EndCalcDate), NULL, NULL, @ПУ1 ) != 0 )
              return 1;
           end;
           if( ПолучитьИтогДУ( OrderFD.Order().rec.ID, ДУ_ИТОГ_ПУ, NULL, 0, NULL, NULL, NULL, EndCalcDate, NULL, NULL, @ПУ2 ) != 0 )
              return 1;
           end;

           DP = max(0, ( (ПУ2 - ПУ1) - OrderFD.СуммаБазовойПрибыли( EndCalcDate, OrderFD.ДатаНачалаПР(EndCalcDate), true, 0 ) - (Кдв2 - Кдв1) ) );

           CalcCom.CalcDateS = EndCalcDate;
           if( РасчетКомиссииБанкаЗаУспех( OrderFD, DocID(), EndCalcDate, TS_ComissSum( DP, NATCUR ), ДосрочныйВывод, @CalcCom.ConCom_S, @CalcCom.sfdefcom_parm_S ) != 0 )
              MsgBox( "Ошибка при расчете комиссии за успех." );
              return 1;
           end;
           Itogs[ДУ_Кусп] = Itogs[ДУ_Кусп_ф] = CalcCom.sfdefcom_parm_S.rec.CommSum;

           /* комиссия за досрочный вывод */
           if( (ReqFD.Request.rec.Moratorium != "X") AND (ReqFD.Request.rec.TransferOFBU != "X") )

              /*Вывод в дату, отличную от даты окончания срока действия договора*/
              Valid = OrderFD.Valid( EndCalcDate ); 
              if( (Valid == null) OR ( EndCalcDate != (Valid.rec.EndDate + 1) ) )
                 CalcCom.CalcDateP = EndCalcDate;
                 if( РасчетКомиссииЗаДосрочныйВывод( OrderFD, DocID(), EndCalcDate, TS_ComissSum( Itogs[ДУ_Sкап], NATCUR ), ДосрочныйВывод, @CalcCom.ConCom_P, @CalcCom.sfdefcom_parm_P ) != 0 )
                    MsgBox( "Ошибка при расчете комиссии за досрочный вывод." );
                    return 1;
                 end;
                 Itogs[ДУ_Кдв] = Itogs[ДУ_Кдв_ф] = CalcCom.sfdefcom_parm_P.rec.CommSum;
              end;
           end;

           Itogs[ДУ_Sвыпл] = Itogs[ДУ_Sзаявл] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф];
           Itogs[ДУ_СКост] = Itogs[ДУ_ИТОГ_СК] - Itogs[ДУ_Sзаявл];
        end;

     else /*получить то, что было расчитано в операции*/

        Itogs[ДУ_ИТОГ_СК] = ПолучитьИтогДоОперации( OrderFD.ID, ДУ_ИТОГ_СК, EndCalcDate, DocKind(), DocID() );

        if( ReadSaveItog( ДУ_Sзаявл ) )
           MsgBox( "Ошибка при получении итога \"ДУ_Sзаявл\"по договору" );
           return 1;
        end;
        if( ReadSaveItog( ДУ_Кдв ) )
           MsgBox( "Ошибка при получении итога \"Н_Кдв\"по договору" );
           return 1;
        end;
        if( ReadSaveItog( ДУ_Кдв_ф ) )
           MsgBox( "Ошибка при получении итога \"ДУ_Кдв_ф\"по договору" );
           return 1;
        end;
        if( ReadSaveItog( ДУ_Кусп ) )
           MsgBox( "Ошибка при получении итога \"Н_Кусп\"по договору" );
           return 1;
        end;
        if( ReadSaveItog( ДУ_Кусп_ф ) )
           MsgBox( "Ошибка при получении итога \"ДУ_Кусп_ф\"по договору" );
           return 1;
        end;
        if( ReadSaveItog( ДУ_Sвыпл ) )
           MsgBox( "Ошибка при получении итога \"ДУ_Sвыпл\"по договору" );
           return 1;
        end;
        if( ReadSaveItog( ДУ_СКост ) )
           MsgBox( "Ошибка при получении итога \"ДУ_СКост\"по договору" );
           return 1;
        end;

        if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )

           if( ReadSaveItog( ДУ_SзаявП ) )
              MsgBox( "Ошибка при получении итога \"ДУ_SзаявП\"по договору" );
              return 1;
           end;
           if( ReadSaveItog( ДУ_Побщ ) )
              MsgBox( "Ошибка при получении итога \"ДУ_Побщ\"по договору" );
              return 1;
           end;
           if( ReadSaveItog( ДУ_Пвыв_в ) )
              MsgBox( "Ошибка при получении итога \"ДУ_Пвыв_в\"по договору" );
              return 1;
           end;
           if( ReadSaveItog( ДУ_Нкуд ) )
              MsgBox( "Ошибка при получении итога \"ДУ_Нкуд\"по договору" );
              return 1;
           end;
           if( ReadSaveItog( ДУ_Нкуд_ф ) )
              MsgBox( "Ошибка при получении итога \"ДУ_Нкуд_ф\"по договору" );
              return 1;
           end;
           if( ReadSaveItog( ДУ_СПок ) )
              MsgBox( "Ошибка при получении итога \"ДУ_СПок\"по договору" );
              return 1;
           end;
           if( ReadSaveItog( ДУ_СПок_ф ) )
              MsgBox( "Ошибка при получении итога \"ДУ_СПок_ф\"по договору" );
              return 1;
           end;
           if( ReadSaveItog( ДУ_СКостП ) )
              MsgBox( "Ошибка при получении итога \"ДУ_СКостП\"по договору" );
              return 1;
           end;

        else

           if( ReadSaveItog( ДУ_Sкап ) )
              MsgBox( "Ошибка при получении итога \"ДУ_Sкап\"по договору" );
              return 1;
           end;

        end;

     end;

     return 0;
  END;

  MACRO AfterChange_Кдв_ф()
     if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )
        Itogs[ДУ_Кдв_ф]   = m_Panel.rec.A30_2;
        Itogs[ДУ_Пвыв_в]  = Itogs[ДУ_Побщ] - Itogs[ДУ_Нкуд_ф] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф];
        Itogs[ДУ_Sвыпл]   = Itogs[ДУ_Sзаявл] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф] - Itogs[ДУ_Нкуд_ф];
        m_Panel.rec.A34   = Itogs[ДУ_Пвыв_в];
        m_Panel.rec.A40_1 = Itogs[ДУ_Sвыпл];
     else
        Itogs[ДУ_Кдв_ф]  = m_Panel.rec.A30_2;
        Itogs[ДУ_Sвыпл]  = Itogs[ДУ_Sзаявл] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф];
        m_Panel.rec.A40_1 = Itogs[ДУ_Sвыпл];
     end;
  END;

  MACRO AfterChange_Кусп_ф()
     if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )
        Itogs[ДУ_Кусп_ф]  = m_Panel.rec.A32_2;
        Itogs[ДУ_Пвыв_в]  = Itogs[ДУ_Побщ] - Itogs[ДУ_Нкуд_ф] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф];
        Itogs[ДУ_Sвыпл]   = Itogs[ДУ_Sзаявл] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф] - Itogs[ДУ_Нкуд_ф];
        m_Panel.rec.A34   = Itogs[ДУ_Пвыв_в];
        m_Panel.rec.A40_1 = Itogs[ДУ_Sвыпл];
     else
        Itogs[ДУ_Кусп_ф] = m_Panel.rec.A32_2;
        Itogs[ДУ_Sвыпл]  = Itogs[ДУ_Sзаявл] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф];
        m_Panel.rec.A40_1 = Itogs[ДУ_Sвыпл];
     end;
  END;

  MACRO AfterChange_Нкуд_ф()
     if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )
        Itogs[ДУ_Нкуд_ф]  = m_Panel.rec.A35_2;
        Itogs[ДУ_Пвыв_в]  = Itogs[ДУ_Побщ] - Itogs[ДУ_Нкуд_ф] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф];
        Itogs[ДУ_Sвыпл]   = Itogs[ДУ_Sзаявл] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф] - Itogs[ДУ_Нкуд_ф];
        m_Panel.rec.A34   = Itogs[ДУ_Пвыв_в];
        m_Panel.rec.A40_1 = Itogs[ДУ_Sвыпл];
     end;
  END;

  MACRO AfterChange_Sпок_ф()
     if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )
        Itogs[ДУ_СПок_ф]  = m_Panel.rec.A36_2;
        Itogs[ДУ_Побщ]    = Itogs[ДУ_Sзаявл] - Itogs[ДУ_СПок_ф];
        if(ReqFD.IsOutFULL() == false)
           Itogs[ДУ_Sкап]  = Itogs[ДУ_СПок_ф];
           Itogs[ДУ_СКост] = Itogs[ДУ_ИТОГ_СК] - Itogs[ДУ_Sкап];
           m_Panel.rec.A41   = Itogs[ДУ_СКост];
        end;
        Itogs[ДУ_Пвыв_в] = Itogs[ДУ_Побщ] - Itogs[ДУ_Нкуд_ф] - Itogs[ДУ_Кдв_ф] - Itogs[ДУ_Кусп_ф];
        m_Panel.rec.A33  = Itogs[ДУ_Побщ];
        m_Panel.rec.A34  = Itogs[ДУ_Пвыв_в];
     end;
  END;
  
  PRIVATE MACRO CalculateItogs()

     SaveItogsFromPanel();

     if( IsProlongation ) 
        РасчетПриПролонгации();
     else
        if( ReqFD )
           РасчетПриВыводеКапитала();
        end;
     end;

     SaveItogsToPanel();
  END;

  PRIVATE MACRO Report()
  END;

  PRIVATE MACRO InitFields()
     m_Panel.rec.A1      = OrderFD.Trustor.rec.ShortName; /*Учредитель*/
     m_Panel.rec.A2_1    = OrderFD.Number(); /*Договор №*/
     m_Panel.rec.A2_2    = OrderFD.BeginDate(); /*от*/
     m_Panel.rec.A3      = OrderFD_OFBU.Order().rec.ShortName; /*ОФБУ*/
     m_Panel.rec.A4      = {curdate}; /*Дата расчета*/
     m_Panel.rec.A5      = EndCalcDate; /*Дата окончания расчетного периода*/
     m_Panel.rec.A70     = {OperDprt}; /*Филиал  */
     m_Panel.rec.A71     = {Oper}; /*Исполнитель*/
     m_Panel.rec.A71_1   = {Name_Oper};
     m_Panel.rec.A7_2    = "RUR";/*в 1 очереди реализации - выводится "RUR" и не редактируется*/
     m_Panel.rec.A40_2   = "RUR";/*в 1 очереди реализации - выводится "RUR" и не редактируется*/
  END;

  MACRO Run( RunKey:INTEGER ):BOOL

     InitProgress( -1, "Расчет итогов по договору", "Расчет итогов по договору" );
        InitFields();
        CalculateItogs();
     RemProgress;

     if( Run( RunKey ) )
        SaveItogsFromPanel();

        if( SaveAllItogsInBD() )
           return true;
        end;
     end;
     return false;
  END;

  PRIVATE MACRO Construct( Order, Req ):BOOL
     if( Itogs == NULL )
        Itogs = TArray();
     end;

     if( Order == NULL )
        if( Req )
           OrderFD = TS_OrderFD( 0, Req.rec.OrderID );
           if( not OrderFD )                  
              MsgBox( "Не найден договор ДУ по заявлению ВВК \"" + Req.rec.Number + "\"");
              return false;
           end;
        else
           MsgBox( "Не задан договор ДУ для расчета итогов.");
           return false;
        end;
     else
        OrderFD = TS_OrderFD( 0, Order.rec.ID );
     end;

     OrderFD_OFBU = TS_OrderFD( 0, OrderFD.Order().rec.OFBU );

     if( Req )
        ReqFD = TS_RequestFD( Req, null, OrderFD );
     end;

     if( (EndCalcDate == NULL) OR (EndCalcDate == DATE(0,0,0)) )
        if( ReqFD )                
           EndCalcDate = Req.rec.CapitalDate;

           if( EndCalcDate == DATE(0,0,0) )
              EndCalcDate = {curdate};
           end;
        else             
           EndCalcDate = {curdate};
        end;
     end;

     Itogs[ДУ_Кдв]  = Itogs[ДУ_Кдв_ф]   = Itogs[ДУ_Sкап] = Itogs[ДУ_Sвыпл]  = Itogs[ДУ_СКост]  = Itogs[ДУ_Sзаявл] =
     Itogs[ДУ_Нкуд] = Itogs[ДУ_Нкуд_ф]  = Itogs[ДУ_Кусп] = Itogs[ДУ_Кусп_ф] = Itogs[ДУ_СПок]   = Itogs[ДУ_СПок_ф] =
     Itogs[ДУ_КПУ]  = Itogs[ДУ_ИТОГ_СК] = Itogs[ДУ_Побщ] = Itogs[ДУ_Пвыв_в] = Itogs[ДУ_SзаявП] = Itogs[ДУ_СКостП] = $0;

     UseNDFL = TS_IsPayerNPTaxAllCheck( OrderFD.Order().rec.Trustor, EndCalcDate );

     return true;
  END;

  PRIVATE MACRO Init()
     VAR StatusStr = "Esc Выход  ";
     if( ReadOnly == false )
        StatusStr = StatusStr + "F2 Исполнить  "
     end;

     StatusStr = StatusStr + "F7 Отчет";

     AddFieldProc( 0, PNFLD_A30_2, 0, @FldProc_Кдв_ф,  Itogs[ДУ_Кдв_ф]  );
     AddFieldProc( 0, PNFLD_A32_2, 0, @FldProc_Кусп_ф, Itogs[ДУ_Кусп_ф] );
     if( OrderFD_OFBU.Order().rec.DP_ShareCalc == TS_CALCPART_NOMINAL )
        AddFieldProc( 0, PNFLD_A35_2, 0, @FldProc_Нкуд_ф, Itogs[ДУ_Нкуд_ф] );
        AddFieldProc( 0, PNFLD_A36_2, 0, @FldProc_Sпок_ф, Itogs[ДУ_СПок_ф] );
     else
        DisableFields( Data(), PNFLD_A35_2 );
        DisableFields( Data(), PNFLD_A36_2 );
     end;

     Message( StatusStr );
     if( ReadOnly == true )
        DisableFields( m_Panel );
     end;
  END;

  MACRO KeyProc( Pan:Variant, Cmd:INTEGER, FldId:INTEGER, _Key:INTEGER )
     VAR RetKey = KeyProc( Pan, Cmd, FldId, _Key );

     if( (Cmd == DLG_KEY) AND (RetKey == CM_DEFAULT) )
        if( _Key == 321/*F7*/ ) /*Печать в Excel*/ 
           Report(); 
        end;
     end;

     return RetKey;
  END;

  PRIVATE MACRO Check():BOOL
     var RetVal = true;

     if( Itogs[ДУ_Кдв_ф] < 0 )
        MsgBox( "Сумма комиссии за досрочный вывод меньше 0." );
        RetVal = false;
     elif( Itogs[ДУ_Sвыпл] < 0 )
        MsgBox( "Сумма к выплате меньше 0." );
        RetVal = false;
     else
        if( (IsProlongation == false) and (ReqFD.Request.rec.Type == TS_KINDDECLAR_PARTLY) and (ReadOnly == false) )
           RetVal = TSCheckLimitMP( OrderFD.ID, EndCalcDate, m_Panel.rec.A41, 1/*TS_MP_LIMDIC_MINVOLMONEY*/ );
        end;
     end;

     return RetVal;
  END;

  initDL_CPanel( "trust.lbr", "PCLREPOF" ); 
  if( not Construct( _Order, _Req ) )
     return NULL;
  end;
END;

/*Расчет итогов при выводе капитала*/
MACRO TS_CalculateItogsOut_OF( Itogs:TArray, Req:TRecHandler, EndCalcDate:DATE, ID_Operation:INTEGER, ID_Step:INTEGER, CalcCom:DataCalcCom ):BOOL
  VAR Form = CItogs_Panel_OF( Itogs, NULL, Req, false, false, EndCalcDate, ID_Operation, ID_Step, CalcCom );
  if( Form )
     return Form.Run();
  end;
  return false;
END;
