import TSInter, "tssec.mac";


MACRO ВыполнитьСписаниПриПродаже( FD, dat, FDoc )
  VAR ALL_OverAmountBuy = $0;

  var CategAddIncome = "", CatDebetFR = "", FIRoleDebetFR = FIROLE_UNDEF,  CatCreditFR = "", FIRoleCreditFR = FIROLE_UNDEF;
  var FR = $0, SСакт = $0, TotalCost = $0, IncomeAccRest = $0;
  var SQLcmd, RSD, IsResponsible, FIRoleBA, FIRolePD, FIRoleDD;

  var PercentAcc     = TRecHandler("account.dbt");
  var DiscountAcc    = TRecHandler("account.dbt");
  var PrtfolioAcc    = TRecHandler("account.dbt"); 
  var IncomeAcc      = TRecHandler("account.dbt"); 


  SQLcmd = RSDCommand( " select sum.t_Portfolio, sum(lnk.t_CostBuy) CostBuy, sum(lnk.t_BalanceCostBuy) BalanceCostBuy, sum(lnk.t_NKDBuyAmount) NKDBuy,  sum(NVL(lnk.t_InterestIncomeAdd,0)) InterestIncomeAdd, sum(NVL(lnk.t_DiscountIncomeAdd,0)) DiscountIncomeAdd," +
                       "        NVL(SUM(ROUND(NVL(Lnk.t_InterestIncomeBuy, 0),2) + ROUND(NVL(Lnk.t_InterestIncomeAdd, 0),2)), 0) InterestIncomeSum, " +
                       "        NVL(SUM(ROUND(NVL(Lnk.t_DiscountIncomeBuy, 0),2)   + ROUND(NVL(Lnk.t_DiscountIncomeAdd, 0),2)), 0) DiscountIncomeSum, " +
                       "        SUM(ROUND(NVL(Lnk.t_InterestIncomeBuy, 0),2)) InterestIncomeBuy, " +
                       "        SUM(ROUND(NVL(Lnk.t_DiscountIncomeBuy, 0),2)) DiscountIncomeBuy, "+
                       "        SUM(ROUND(NVL(Lnk.t_NotCarryInterestBuy, 0),2) + ROUND(NVL(Lnk.t_NotCarryInterestAdd, 0),2)) NotCarryInterestSum, " +
                       "        SUM(ROUND(NVL(Lnk.t_NotCarryDiscountBuy, 0),2) + ROUND(NVL(Lnk.t_NotCarryDiscountAdd, 0),2)) NotCarryDiscountSum, " +
                       "        sum(NVL(lnk.t_OverChange,0)) OverAmountBuy, sum(NVL(lnk.t_NotCarryInterestAdd,0)) NotCarryInterestAdd, sum(NVL(lnk.t_NotCarryDiscountAdd,0)) NotCarryDiscountAdd " +
                       "   from dpmwrtlnk_dbt lnk, dpmwrtsum_dbt sum " +
                       "  where     lnk.t_SaleID = ? " + 
                       "        and sum.t_SumID = lnk.t_BuyID " +
                       "group by sum.t_Portfolio" );
  SQLcmd.addParam( "", RSDBP_IN, FD.pmwrtsum.rec.SumID );
  SQLcmd.execute();

  RSD = TRsbDataSet(SQLcmd);

  while( RSD.MoveNext() )

     FD.ОпределитьПортфельДляСписания( RSD.rec.Portfolio );

     if( RSD.rec.Portfolio == KINDPORT_TRADETRUST )
        FIRoleBA = FIROLE_BA_TP;
        FIRolePD = FIROLE_PD_TP;
        FIRoleDD = FIROLE_DD_TP; 
     else
        FIRoleBA = FIROLE_BA_PPR;
        FIRolePD = FIROLE_PD_PPR;
        FIRoleDD = FIROLE_DD_PPR; 
     end;

     if( not FD.OpenAccount( "ПортфельЭцб ДУ", null, null, FIRoleBA, PrtfolioAcc, dat) )
        return 1;
     end;

     if( (RSD.rec.InterestIncomeAdd > 0) or ((RSD.rec.NKDBuy+RSD.rec.InterestIncomeSum) > 0) )
        if( not FD.OpenAccount( "ПортфельЭцб ДУ", null, null, FIRolePD, PercentAcc, dat) )
           return 1;
        end;
     end;

     if( (RSD.rec.DiscountIncomeAdd > 0) or (RSD.rec.DiscountIncomeSum > 0) )
        if( not FD.OpenAccount( "ПортфельЭцб ДУ", null, null, FIRoleDD, DiscountAcc, dat) )
           return 1;
        end;
     end;

     /* Доначисление дохода */
     if( FI_IsResponsible(FD.fininstr.rec.FIID, dat ) == true )
        CategAddIncome = "ДоходыЭцб ДУ";
     else
        CategAddIncome = "ПДДЭцб ДУ";
     end;

     if( RSD.rec.InterestIncomeAdd > 0 )
        if( not ПроводкаПоКатегориямУчета( FD, 
                                           PercentAcc, CategAddIncome,     /* AccDeb , AccCred*/
                                           dat,                            /* Дата */
                                           2,                              /* Глава */
                                           FD.FaceFIID(),                  /* Валюта */
                                           RSD.rec.InterestIncomeAdd,      /* Сумма */
                                           FDoc,                           /* Документ */
                                           INPCARRY,                       /* Result_Carry */
                                           "",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,           /* Numb_Document */
                                           "Доначисление процентного дохода",/* Ground */
                                           0, FIROLE_PERCENT, FIROLE_PERCENT
                                         ) )
            return 1;
        end;
     end;

     if( RSD.rec.DiscountIncomeAdd > 0 )
        if( not ПроводкаПоКатегориямУчета( FD, 
                                           DiscountAcc, CategAddIncome,    /* AccDeb , AccCred*/
                                           dat,                            /* Дата */
                                           2,                              /* Глава */
                                           FD.FaceFIID(),                  /* Валюта */
                                           RSD.rec.DiscountIncomeAdd,      /* Сумма */
                                           FDoc,                           /* Документ */
                                           INPCARRY,                       /* Result_Carry */
                                           "",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,           /* Numb_Document */
                                           "Доначисление дисконтного дохода",/* Ground */
                                           0, FIROLE_DISCOUNT, FIROLE_DISCOUNT
                                         ) )
            return 1;
        end;
     end;

    if( RSD.rec.NotCarryInterestSum > 0 )
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "ПДДЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          RSD.rec.NotCarryInterestSum, /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Отнесение начисленного ПД на доходы",/* Ground */
                                          0, FIROLE_PERCENT, FIROLE_PERCENT
                                        ) )
           return 1;
       end;
    end;

    if( RSD.rec.NotCarryDiscountSum > 0 ) 
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "ПДДЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          RSD.rec.NotCarryDiscountSum, /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Отнесение начисленного ДД на доходы",/* Ground */
                                          0, FIROLE_DISCOUNT, FIROLE_DISCOUNT
                                        ) )
           return 1;
       end;
    end;

    if( (FD.ВидСрочностиСделки() != СделкаToday) AND IsEXCHANGE(FD.Group) )
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "-Расчеты, ДУ", "-Расчеты, ДУ",  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          RSD.rec.BalanceCostBuy,         /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Учет стоимости проданных ц/б на счете реализации",/* Ground */
                                          0, FIROLE_BA, FIROLE_SECURITIES
                                        ) )
           return 1;
       end;
    end;

    if( (RSD.rec.BalanceCostBuy - RSD.rec.NKDBuy - RSD.rec.InterestIncomeBuy - RSD.rec.DiscountIncomeBuy) > 0 )
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "-Расчеты, ДУ", PrtfolioAcc,  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          (RSD.rec.BalanceCostBuy - RSD.rec.NKDBuy - RSD.rec.InterestIncomeBuy - RSD.rec.DiscountIncomeBuy),         /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Списание балансовой стоимости",/* Ground */
                                          0, FIROLE_SECURITIES, FIROLE_BA
                                        ) )
           return 1;
       end;
    end;

    if( (RSD.rec.NKDBuy+RSD.rec.InterestIncomeSum) > 0 )
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "-Расчеты, ДУ", PercentAcc,  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          (RSD.rec.NKDBuy+RSD.rec.InterestIncomeSum),                    /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Списание уплаченного НКД и начисленного ПД",/* Ground */
                                          0, FIROLE_SECURITIES, FIROLE_PERCENT
                                        ) )
           return 1;
       end;
    end;

    if( RSD.rec.DiscountIncomeSum > 0 )
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "-Расчеты, ДУ", DiscountAcc,  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          RSD.rec.DiscountIncomeSum,          /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Списание начисленного ДД",/* Ground */
                                          0, FIROLE_SECURITIES, FIROLE_DISCOUNT
                                        ) )
           return 1;
       end;
    end;

    if( RSD.rec.Portfolio == KINDPORT_SALETRUST )
       ALL_OverAmountBuy = ALL_OverAmountBuy + RSD.rec.OverAmountBuy;
    end;

    SСакт = SСакт + (RSD.rec.BalanceCostBuy + RSD.rec.InterestIncomeAdd + RSD.rec.DiscountIncomeAdd);

  end;

  if( ALL_OverAmountBuy > 0 )
     if( FD.IsExistAccount( "ДоходыЭцб ДУ", null, true, FIROLE_DISCOUNT, IncomeAcc, null, dat) )
        IncomeAccRest = TS_GetRestAccountByRecord( IncomeAcc, dat);
     end;

     if( ABS(IncomeAccRest) > 0 )
        if( not ПроводкаПоКатегориямУчета( FD, 
                                           "ДоходыЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                           dat,                            /* Дата */
                                           2,                              /* Глава */
                                           NATCUR,                         /* Валюта */
                                           ABS(IncomeAccRest),             /* Сумма */
                                           FDoc,                           /* Документ */
                                           INPCARRY,                       /* Result_Carry */
                                           "",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,           /* Numb_Document */
                                           "Списание положительной переоценки",          /* Ground */
                                           0, FIROLE_DISCOUNT, FIROLE_CA
                                         ) )
            return 1;
        end;
     end;

     if( ABS(ALL_OverAmountBuy) > ABS(IncomeAccRest) )
        if( not ПроводкаПоКатегориямУчета( FD, 
                                           "РасходыЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                           dat,                            /* Дата */
                                           2,                              /* Глава */
                                           NATCUR,                         /* Валюта */
                                           ABS(ALL_OverAmountBuy),         /* Сумма */
                                           FDoc,                           /* Документ */
                                           INPCARRY,                       /* Result_Carry */
                                           "",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,           /* Numb_Document */
                                           "Списание положительной переоценки",          /* Ground */
                                           0, FIROLE_DISCOUNT, FIROLE_CA
                                         ) )
            return 1;
        end;
     end;
  elif( ALL_OverAmountBuy < 0 )
     if( FD.IsExistAccount( "РасходыЭцб ДУ", null, true, FIROLE_DISCOUNT, IncomeAcc, null, dat) )
        IncomeAccRest = TS_GetRestAccountByRecord( IncomeAcc, dat);
     end;

     if( ABS(IncomeAccRest) > 0 )
        if( not ПроводкаПоКатегориямУчета( FD, 
                                           "РасходыЭцб ДУ", "РасходыЭцб ДУ",  /* AccDeb , AccCred*/
                                           dat,                            /* Дата */
                                           2,                              /* Глава */
                                           NATCUR,                         /* Валюта */
                                           ABS(IncomeAccRest),             /* Сумма */
                                           FDoc,                           /* Документ */
                                           INPCARRY,                       /* Result_Carry */
                                           "",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,           /* Numb_Document */
                                           "Списание положительной переоценки",          /* Ground */
                                           0, FIROLE_CA, FIROLE_DISCOUNT
                                         ) )
            return 1;
        end;
     end;

     if( ABS(ALL_OverAmountBuy) > ABS(IncomeAccRest) )
        if( not ПроводкаПоКатегориямУчета( FD, 
                                           "РасходыЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                           dat,                            /* Дата */
                                           2,                              /* Глава */
                                           NATCUR,                         /* Валюта */
                                           ABS(ALL_OverAmountBuy),         /* Сумма */
                                           FDoc,                           /* Документ */
                                           INPCARRY,                       /* Result_Carry */
                                           "",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,           /* Numb_Document */
                                           "Списание положительной переоценки",          /* Ground */
                                           0, FIROLE_CA, FIROLE_DISCOUNT
                                         ) )
            return 1;
        end;
     end;
  end;

  if( SmartConvertSum( TotalCost, FD.dl_leg.rec.TotalCost, dat, FD.dl_leg.rec.CFI, NATCUR, true ) == false )
     return false;
  end;                      

  FR = TotalCost - SСакт;

  if( FR > 0 )
     CatDebetFR = "-Расчеты, ДУ"; 
     FIRoleDebetFR = FIROLE_SECURITIES;  
     CatCreditFR = "ДоходыЭцб ДУ"; 
     FIRoleCreditFR = FIROLE_BA;
  else
     CatDebetFR = "РасходыЭцб ДУ"; 
     FIRoleDebetFR = FIROLE_BA;
     CatCreditFR = "-Расчеты, ДУ"; 
     FIRoleCreditFR = FIROLE_SECURITIES;
  end;

  if( ABS(FR) > 0 )
     if( not ПроводкаПоКатегориямУчета( FD, 
                                        CatDebetFR, CatCreditFR,        /* AccDeb , AccCred*/
                                        dat,                            /* Дата */
                                        2,                              /* Глава */
                                        NATCUR,                         /* Валюта */
                                        ABS(FR),                        /* Сумма */
                                        FDoc,                           /* Документ */
                                        INPCARRY,                       /* Result_Carry */
                                        "",                             /* Kind_Oper */
                                        FD.tick.rec.DealCode,           /* Numb_Document */
                                        "Отражение фин. результата",    /* Ground */
                                        0, FIRoleDebetFR, FIRoleCreditFR
                                      ) )
         return 1;
     end;
  end;

  return 0;
END; 

MACRO ВыполнитьСписаниПриПогашении( FD, dat, FDoc )
  VAR ALL_OverAmountBuy = $0;

  var CategAddIncome = "", CatDebetFR = "", FIRoleDebetFR = FIROLE_UNDEF,  CatCreditFR = "", FIRoleCreditFR = FIROLE_UNDEF;
  var FR = $0, SСакт = $0, TotalCost = $0;
  var SQLcmd, RSD, FiRoleCateg = FIROLE_UNDEF, IncomeAccRest = $0, IsResponsible, FIRoleBA, FIRolePD, FIRoleDD;

  var PercentAcc     = TRecHandler("account.dbt");
  var DiscountAcc    = TRecHandler("account.dbt");
  var PrtfolioAcc    = TRecHandler("account.dbt"); 
  var IncomeAcc      = TRecHandler("account.dbt"); 

  if( FD.СделкаОРЦБ() )
     FiRoleCateg = FIROLE_ORCB_REQUEST;
  else
     FiRoleCateg = FIROLE_SETTL_AGENT;
  end;

  SQLcmd = RSDCommand( " select sum.t_Portfolio, sum(lnk.t_BalanceCostBuy) BalanceCostBuy, sum(lnk.t_CostBuy) CostBuy, sum(lnk.t_NKDBuyAmount) NKDBuy, sum(NVL(lnk.t_InterestIncomeAdd,0)) InterestIncomeAdd, sum(NVL(lnk.t_DiscountIncomeAdd,0)) DiscountIncomeAdd, " +
                       "        NVL(SUM(ROUND(NVL(Lnk.t_InterestIncomeBuy, 0),2) + ROUND(NVL(Lnk.t_InterestIncomeAdd, 0),2)), 0) InterestIncomeSum, " +
                       "        NVL(SUM(ROUND(NVL(Lnk.t_DiscountIncomeBuy, 0),2)   + ROUND(NVL(Lnk.t_DiscountIncomeAdd, 0),2)), 0) DiscountIncomeSum, " +
                       "        SUM(ROUND(NVL(Lnk.t_InterestIncomeBuy, 0),2)) InterestIncomeBuy, " +
                       "        SUM(ROUND(NVL(Lnk.t_DiscountIncomeBuy, 0),2)) DiscountIncomeBuy, " +
                       "        SUM(ROUND(NVL(Lnk.t_NotCarryInterestBuy, 0),2) + ROUND(NVL(Lnk.t_NotCarryInterestAdd, 0),2)) NotCarryInterestSum, " +
                       "        SUM(ROUND(NVL(Lnk.t_NotCarryDiscountBuy, 0),2) + ROUND(NVL(Lnk.t_NotCarryDiscountAdd, 0),2)) NotCarryDiscountSum, " +
                       "        sum(NVL(lnk.t_OverChange,0)) OverAmountBuy, sum(NVL(lnk.t_NotCarryInterestAdd,0)) NotCarryInterestAdd, sum(NVL(lnk.t_NotCarryDiscountAdd,0)) NotCarryDiscountAdd " +
                       "   from dpmwrtlnk_dbt lnk, dpmwrtsum_dbt sum " +
                       "  where     lnk.t_SaleID = ? " + 
                       "        and sum.t_SumID = lnk.t_BuyID " +
                       "group by sum.t_Portfolio" );
  SQLcmd.addParam( "", RSDBP_IN, FD.pmwrtsum.rec.SumID );
  SQLcmd.execute();

  RSD = TRsbDataSet(SQLcmd);

  while( RSD.MoveNext() )

     FD.ОпределитьПортфельДляСписания( RSD.rec.Portfolio );

     if( RSD.rec.Portfolio == KINDPORT_TRADETRUST )
        FIRoleBA = FIROLE_BA_TP;
        FIRolePD = FIROLE_PD_TP;
        FIRoleDD = FIROLE_DD_TP; 
     else
        FIRoleBA = FIROLE_BA_PPR;
        FIRolePD = FIROLE_PD_PPR;
        FIRoleDD = FIROLE_DD_PPR; 
     end;

     if( not FD.OpenAccount( "ПортфельЭцб ДУ", null, null, FIRoleBA, PrtfolioAcc, dat) )
        return 1;
     end;

//     if( ((RSD.rec.InterestIncomeAdd > 0) or ((RSD.rec.NKDBuy+RSD.rec.InterestIncomeSum) > 0)) AND (IsRET_COUPON(FD.Group) OR ((IsRET_ISSUE(FD.Group) OR IsRET_PARTLY(FD.Group)) AND (FD.tick.rec.Number_Coupon != ""))) )
     if(((RSD.rec.InterestIncomeAdd > 0) or ((RSD.rec.NKDBuy+RSD.rec.InterestIncomeSum) > 0)) AND (IsRET_ISSUE(FD.Group) OR IsRET_COUPON(FD.Group) OR (IsRET_PARTLY(FD.Group) AND (FD.tick.rec.Number_Coupon != ""))))
        if( not FD.OpenAccount( "ПортфельЭцб ДУ", null, null, FIRolePD, PercentAcc, dat) )
           return 1;
        end;
     end;

     if(((RSD.rec.DiscountIncomeAdd > 0) or (RSD.rec.DiscountIncomeSum > 0)) AND (IsRET_ISSUE(FD.Group) OR IsRET_PARTLY(FD.Group)))
        if( not FD.OpenAccount( "ПортфельЭцб ДУ", null, null, FIRoleDD, DiscountAcc, dat) )
           return 1;
        end;
     end;
   
     /* Доначисление дохода */
     if( FI_IsResponsible(FD.fininstr.rec.FIID, dat) == true )
        CategAddIncome = "ДоходыЭцб ДУ";
     else
        CategAddIncome = "ПДДЭцб ДУ";
     end;

//     if( (RSD.rec.InterestIncomeAdd > 0) AND (IsRET_COUPON(FD.Group) OR ((IsRET_ISSUE(FD.Group) OR IsRET_PARTLY(FD.Group)) AND (FD.tick.rec.Number_Coupon != ""))) )
     if( (RSD.rec.InterestIncomeAdd > 0) AND ( IsRET_ISSUE(FD.Group) OR IsRET_COUPON(FD.Group) OR (IsRET_PARTLY(FD.Group) AND (FD.tick.rec.Number_Coupon != "")) ) )
        if( not ПроводкаПоКатегориямУчета( FD, 
                                           PercentAcc, CategAddIncome,     /* AccDeb , AccCred*/
                                           dat,                            /* Дата */
                                           2,                              /* Глава */
                                           FD.FaceFIID(),                  /* Валюта */
                                           RSD.rec.InterestIncomeAdd,      /* Сумма */
                                           FDoc,                           /* Документ */
                                           INPCARRY,                       /* Result_Carry */
                                           "",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,           /* Numb_Document */
                                           "Доначисление процентного дохода",/* Ground */
                                           0, FIROLE_PERCENT, FIROLE_PERCENT
                                         ) )
            return 1;
        end;
     end;

     if( (RSD.rec.DiscountIncomeAdd > 0) AND ( IsRET_ISSUE(FD.Group) OR IsRET_PARTLY(FD.Group) ) )
        if( not ПроводкаПоКатегориямУчета( FD, 
                                           DiscountAcc, CategAddIncome,    /* AccDeb , AccCred*/
                                           dat,                            /* Дата */
                                           2,                              /* Глава */
                                           FD.FaceFIID(),                  /* Валюта */
                                           RSD.rec.DiscountIncomeAdd,      /* Сумма */
                                           FDoc,                           /* Документ */
                                           INPCARRY,                       /* Result_Carry */
                                           "",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,           /* Numb_Document */
                                           "Доначисление дисконтного дохода",/* Ground */
                                           0, FIROLE_DISCOUNT, FIROLE_DISCOUNT
                                         ) )
            return 1;
        end;
     end;

//    if( (RSD.rec.NotCarryInterestSum > 0) AND (IsRET_COUPON(FD.Group) OR ((IsRET_ISSUE(FD.Group) OR IsRET_PARTLY(FD.Group)) AND (FD.tick.rec.Number_Coupon != ""))) )
    if( (RSD.rec.NotCarryInterestSum > 0) AND ( IsRET_ISSUE(FD.Group) OR IsRET_COUPON(FD.Group) OR (IsRET_PARTLY(FD.Group) AND (FD.tick.rec.Number_Coupon != "")) ) )
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "ПДДЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          RSD.rec.NotCarryInterestSum,    /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Отнесение начисленного ПД на доходы",/* Ground */
                                          0, FIROLE_PERCENT, FIROLE_PERCENT
                                        ) )
           return 1;
       end;
    end;

    if( (RSD.rec.NotCarryDiscountSum > 0) AND ( IsRET_ISSUE(FD.Group) OR IsRET_PARTLY(FD.Group) ) ) 
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "ПДДЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          RSD.rec.NotCarryDiscountSum,    /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Отнесение начисленного ДД на доходы",/* Ground */
                                          0, FIROLE_DISCOUNT, FIROLE_DISCOUNT
                                        ) )
           return 1;
       end;
    end;

    if( (RSD.rec.CostBuy > 0)  AND ( IsRET_ISSUE(FD.Group) OR IsRET_PARTLY(FD.Group) ) )
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "+Расчеты, ДУ", PrtfolioAcc,  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          (RSD.rec.BalanceCostBuy - RSD.rec.NKDBuy - RSD.rec.InterestIncomeBuy - RSD.rec.DiscountIncomeBuy),                /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Списание балансовой стоимости",/* Ground */
                                          0, FiRoleCateg, FIROLE_BA
                                        ) )
           return 1;
       end;
    end;

//    if( ((RSD.rec.NKDBuy+RSD.rec.InterestIncomeSum) > 0) AND (IsRET_COUPON(FD.Group) OR ((IsRET_ISSUE(FD.Group) OR IsRET_PARTLY(FD.Group)) AND (FD.tick.rec.Number_Coupon != ""))) )
    if( ((RSD.rec.NKDBuy+RSD.rec.InterestIncomeSum) > 0) AND ( IsRET_ISSUE(FD.Group) OR IsRET_COUPON(FD.Group) OR (IsRET_PARTLY(FD.Group) AND (FD.tick.rec.Number_Coupon != "")) ) )
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "+Расчеты, ДУ", PercentAcc,  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          (RSD.rec.NKDBuy+RSD.rec.InterestIncomeSum),                    /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Списание уплаченного НКД и начисленного ПД",/* Ground */
                                          0, FiRoleCateg, FIROLE_PERCENT
                                        ) )
           return 1;
       end;
    end;

    if( (RSD.rec.DiscountIncomeSum > 0) AND ( IsRET_ISSUE(FD.Group) OR IsRET_PARTLY(FD.Group) ) )
       if( not ПроводкаПоКатегориямУчета( FD, 
                                          "+Расчеты, ДУ", DiscountAcc,  /* AccDeb , AccCred*/
                                          dat,                            /* Дата */
                                          2,                              /* Глава */
                                          FD.FaceFIID(),                  /* Валюта */
                                          RSD.rec.DiscountIncomeSum,          /* Сумма */
                                          FDoc,                           /* Документ */
                                          INPCARRY,                       /* Result_Carry */
                                          "",                             /* Kind_Oper */
                                          FD.tick.rec.DealCode,           /* Numb_Document */
                                          "Списание начисленного ДД",/* Ground */
                                          0, FiRoleCateg, FIROLE_DISCOUNT
                                        ) )
           return 1;
       end;
    end;

    if( IsRET_ISSUE(FD.Group) )
       if( RSD.rec.Portfolio == KINDPORT_SALETRUST )
          ALL_OverAmountBuy = ALL_OverAmountBuy + RSD.rec.OverAmountBuy;
       end;

       SСакт = SСакт + (RSD.rec.CostBuy + RSD.rec.NKDBuy + RSD.rec.InterestIncomeAdd + RSD.rec.DiscountIncomeAdd);
    end;

  end;

  if( IsRET_ISSUE(FD.Group) )  
     if( ALL_OverAmountBuy > 0 )
        if( FD.IsExistAccount( "ДоходыЭцб ДУ", null, true, FIROLE_DISCOUNT, IncomeAcc, null, dat) )
           IncomeAccRest = TS_GetRestAccountByRecord( IncomeAcc, dat);
        end;

        if( ABS(IncomeAccRest) > 0 )
           if( not ПроводкаПоКатегориямУчета( FD, 
                                              "ДоходыЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                              dat,                            /* Дата */
                                              2,                              /* Глава */
                                              NATCUR,                         /* Валюта */
                                              ABS(IncomeAccRest),             /* Сумма */
                                              FDoc,                           /* Документ */
                                              INPCARRY,                       /* Result_Carry */
                                              "",                             /* Kind_Oper */
                                              FD.tick.rec.DealCode,           /* Numb_Document */
                                              "Списание положительной переоценки",          /* Ground */
                                              0, FIROLE_DISCOUNT, FIROLE_CA
                                            ) )
               return 1;
           end;
        end;

        if( ABS(ALL_OverAmountBuy) > ABS(IncomeAccRest) )
           if( not ПроводкаПоКатегориямУчета( FD, 
                                              "РасходыЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                              dat,                            /* Дата */
                                              2,                              /* Глава */
                                              NATCUR,                         /* Валюта */
                                              ABS(ALL_OverAmountBuy),         /* Сумма */
                                              FDoc,                           /* Документ */
                                              INPCARRY,                       /* Result_Carry */
                                              "",                             /* Kind_Oper */
                                              FD.tick.rec.DealCode,           /* Numb_Document */
                                              "Списание положительной переоценки",          /* Ground */
                                              0, FIROLE_DISCOUNT, FIROLE_CA
                                            ) )
               return 1;
           end;
        end;
     elif( ALL_OverAmountBuy < 0 )
        if( FD.IsExistAccount( "РасходыЭцб ДУ", null, true, FIROLE_DISCOUNT, IncomeAcc, null, dat) )
           IncomeAccRest = TS_GetRestAccountByRecord( IncomeAcc, dat);
        end;

        if( ABS(IncomeAccRest) > 0 )
           if( not ПроводкаПоКатегориямУчета( FD, 
                                              "РасходыЭцб ДУ", "РасходыЭцб ДУ",  /* AccDeb , AccCred*/
                                              dat,                            /* Дата */
                                              2,                              /* Глава */
                                              NATCUR,                         /* Валюта */
                                              ABS(IncomeAccRest),             /* Сумма */
                                              FDoc,                           /* Документ */
                                              INPCARRY,                       /* Result_Carry */
                                              "",                             /* Kind_Oper */
                                              FD.tick.rec.DealCode,           /* Numb_Document */
                                              "Списание положительной переоценки",          /* Ground */
                                              0, FIROLE_CA, FIROLE_DISCOUNT
                                            ) )
               return 1;
           end;
        end;

        if( ABS(ALL_OverAmountBuy) > ABS(IncomeAccRest) )
           if( not ПроводкаПоКатегориямУчета( FD, 
                                              "РасходыЭцб ДУ", "ДоходыЭцб ДУ",  /* AccDeb , AccCred*/
                                              dat,                            /* Дата */
                                              2,                              /* Глава */
                                              NATCUR,                         /* Валюта */
                                              ABS(ALL_OverAmountBuy),         /* Сумма */
                                              FDoc,                           /* Документ */
                                              INPCARRY,                       /* Result_Carry */
                                              "",                             /* Kind_Oper */
                                              FD.tick.rec.DealCode,           /* Numb_Document */
                                              "Списание положительной переоценки",          /* Ground */
                                              0, FIROLE_CA, FIROLE_DISCOUNT
                                            ) )
               return 1;
           end;
        end;
     end;

     if( SmartConvertSum( TotalCost, FD.dl_leg.rec.TotalCost, dat, FD.dl_leg.rec.CFI, NATCUR, true ) == false )
        return false;
     end;                      

     FR = TotalCost - SСакт;

     if( FR > 0 )
        CatDebetFR = "+Расчеты, ДУ"; 
        FIRoleDebetFR = FiRoleCateg;  
        CatCreditFR = "ДоходыЭцб ДУ"; 
        FIRoleCreditFR = FIROLE_BA;
     else
        CatDebetFR = "РасходыЭцб ДУ"; 
        FIRoleDebetFR = FIROLE_BA;
        CatCreditFR = "+Расчеты, ДУ"; 
        FIRoleCreditFR = FiRoleCateg;
     end;

     if( ABS(FR) > 0 )
        if( not ПроводкаПоКатегориямУчета( FD, 
                                           CatDebetFR, CatCreditFR,        /* AccDeb , AccCred*/
                                           dat,                            /* Дата */
                                           2,                              /* Глава */
                                           NATCUR,                         /* Валюта */
                                           ABS(FR),                        /* Сумма */
                                           FDoc,                           /* Документ */
                                           INPCARRY,                       /* Result_Carry */
                                           "",                             /* Kind_Oper */
                                           FD.tick.rec.DealCode,           /* Numb_Document */
                                           "Отражение фин. результата",    /* Ground */
                                           0, FIRoleDebetFR, FIRoleCreditFR
                                         ) )
            return 1;
        end;
     end;
  end;

  return 0;
END; 

