CREATE GLOBAL TEMPORARY TABLE DSOFRSENDMSGEMAIL_TMP (
 T_ID               NUMBER(10),          
 T_CONTRNUMBER      VARCHAR2(64),
 T_SFCONTRID        NUMBER(10),
 T_CFTID            VARCHAR2(35),
 T_CLIENTID         NUMBER(10),
 T_SFDATEBEGIN      DATE,
 T_DLCONTRID        NUMBER(10),
 T_NOTETEXTID       NUMBER(10),
 T_DLCONTRMSGID     NUMBER(10),
 T_EMAILNOTIFYID    NUMBER(10),
 T_NAMECLIENT       VARCHAR2(640),
 T_RECIPIENTEMAIL   VARCHAR2(2000),
 T_SENDEREMAIL      VARCHAR2(2000),
 T_MSGTEXT          VARCHAR2(2000),
 T_MSGDATE          VARCHAR2(128),
 T_MSGSTATUS        NUMBER(10)
 ) 
ON COMMIT PRESERVE ROWS
/