-- Таблица "dptvsproxy_dbt"
CREATE TABLE DPTVSPROXY_DBT (
    T_PARTYID NUMBER(10)
  , T_PROXYID NUMBER(10)
  , T_DOCNUMBER VARCHAR2(15)
  , T_DOCDATE DATE
  , T_VALIDITYDATE DATE
  , T_DOCDESC VARCHAR2(200)
  , T_ISDEFAULT CHAR(1)
  , T_ISSOLEEXECUTIVE CHAR(1)
  , T_POST NUMBER(10)
)
/
COMMENT ON TABLE DPTVSPROXY_DBT IS 'Представители субъекта (векселя)'
/
COMMENT ON COLUMN DPTVSPROXY_DBT.T_PARTYID IS 'Ид. субъекта'
/
COMMENT ON COLUMN DPTVSPROXY_DBT.T_PROXYID IS 'Ид. представителя'
/
COMMENT ON COLUMN DPTVSPROXY_DBT.T_DOCNUMBER IS 'Номер документа о полномочиях'
/
COMMENT ON COLUMN DPTVSPROXY_DBT.T_DOCDATE IS 'Дата документа о полномочиях'
/
COMMENT ON COLUMN DPTVSPROXY_DBT.T_VALIDITYDATE IS 'Срок действия документа о полномочиях'
/
COMMENT ON COLUMN DPTVSPROXY_DBT.T_DOCDESC IS 'Сведения о документе о полномочиях'
/
COMMENT ON COLUMN DPTVSPROXY_DBT.T_ISDEFAULT IS 'Действует по умолчанию'
/
COMMENT ON COLUMN DPTVSPROXY_DBT.T_ISSOLEEXECUTIVE IS 'Является единоличным исполнительным органом'
/
COMMENT ON COLUMN DPTVSPROXY_DBT.T_POST IS 'Должность'
/

CREATE UNIQUE INDEX DPTVSPROXY_DBT_IDX0 ON DPTVSPROXY_DBT (
   T_PARTYID ASC
 , T_PROXYID ASC
) TABLESPACE INDX
/

CREATE UNIQUE INDEX DPTVSPROXY_DBT_IDX1 ON DPTVSPROXY_DBT (
   T_PROXYID ASC
 , T_PARTYID ASC
) TABLESPACE INDX
/
