
DECLARE
   e_no_exist_trigger EXCEPTION;
   PRAGMA EXCEPTION_INIT( e_no_exist_trigger, -4080 );
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER DSS_HISTORY_DBT_CORRECT_RECORD';

   EXCEPTION WHEN e_no_exist_trigger THEN NULL;
END;
/

DECLARE
  E_TABLE_NOT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT( E_TABLE_NOT_EXISTS, -00942 );
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DSS_HISTORYLOG_DBT';
EXCEPTION
  WHEN E_TABLE_NOT_EXISTS THEN NULL;
END;
/


