CREATE OR REPLACE TRIGGER DLCONTRFROB_TMP_TBIU
  BEFORE INSERT OR UPDATE 
  ON DDLCONTRFROB_TMP
  FOR EACH ROW
DECLARE
BEGIN

  IF (INSERTING AND :NEW.T_CHANGEDATE = TO_DATE('01.01.0001','DD.MM.YYYY')) OR UPDATING THEN
    :NEW.T_CHANGEDATE := TRUNC(SYSDATE);
    :NEW.T_CHANGETIME := TO_DATE('01-01-0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD-MM-YYYY:HH24:MI:SS'); 
  END IF;

END;
/

CREATE OR REPLACE TRIGGER DLCONTRFROB_DBT_TBIU
  BEFORE INSERT OR UPDATE 
  ON DDLCONTRFROB_DBT
  FOR EACH ROW
DECLARE
BEGIN

  IF (INSERTING AND :NEW.T_CHANGEDATE = TO_DATE('01.01.0001','DD.MM.YYYY')) OR UPDATING THEN
    :NEW.T_CHANGEDATE := TRUNC(SYSDATE);
    :NEW.T_CHANGETIME := TO_DATE('01.01.0001:' || TO_CHAR(SYSDATE, 'HH24:MI:SS'), 'DD.MM.YYYY:HH24:MI:SS'); 
  END IF;

END;
/