DECLARE 
	x_Cnt NUMBER;
BEGIN
  SELECT count(*) INTO x_Cnt FROM user_tables WHERE table_name = upper('DDATASUM_DBT');
  IF (x_Cnt = 0) THEN
    EXECUTE IMMEDIATE 
        'CREATE TABLE DDATASUM_DBT' || 
        '(' || 
					'T_OPERID NUMBER(10),' || 
					'T_DEBETSUM NUMBER(19,4),' || 
					'T_CREDITSUM NUMBER(19,4),' || 
					'T_CURRENCY NUMBER(10),' || 
					'T_MARKETSCHEMEID NUMBER(10),' || 
					'T_DOCID NUMBER(10),' || 
					'T_OBJECTID NUMBER(10)' || 
        ')';

		EXECUTE IMMEDIATE 'COMMENT ON TABLE DDATASUM_DBT IS ''Информацию о проводках по операциям''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDATASUM_DBT.T_OPERID IS ''Идентификатор операции''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDATASUM_DBT.T_DEBETSUM IS ''Сумма дебета''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDATASUM_DBT.T_CREDITSUM IS ''Сумма кредита''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDATASUM_DBT.T_CURRENCY IS ''Валюта расчётов''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDATASUM_DBT.T_MARKETSCHEMEID IS ''Схема расчётов с биржей''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDATASUM_DBT.T_DOCID IS ''ID операции расчётов или ID сделки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DDATASUM_DBT.T_OBJECTID IS ''DealID сделки по которой суммируются''';
		
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DDATASUM_DBT_IDX0 ON DDATASUM_DBT '||
			'('||
				' T_OPERID'||
				', T_CURRENCY'||
				', T_MARKETSCHEMEID'||
				', T_OBJECTID'||
			')';
	END IF;
END;
/
