DECLARE 
	x_Cnt NUMBER;
BEGIN
  SELECT count(*) INTO x_Cnt FROM user_tables WHERE table_name = upper('DACCTRN_ADD_DBT');
  IF (x_Cnt = 0) THEN
    EXECUTE IMMEDIATE 
			'CREATE TABLE DACCTRN_ADD_DBT '||
			'( '||
				'T_ACCTRNID NUMBER(10,0) DEFAULT 0, '||
				'T_STATE NUMBER(5,0) DEFAULT 0, '|| 
				'T_CHAPTER NUMBER(5,0), '||
				'T_DATE_CARRY DATE, '||
				'T_DATE_RATE DATE, '||
				'T_FIID_PAYER NUMBER(10,0), '||
				'T_FIID_RECEIVER NUMBER(10,0), '||
				'T_ACCOUNTID_PAYER NUMBER(10,0) DEFAULT 0, '||
				'T_ACCOUNTID_RECEIVER NUMBER(10,0) DEFAULT 0, '||
				'T_ACCOUNT_PAYER VARCHAR2(25), '||
				'T_ACCOUNT_RECEIVER VARCHAR2(25), '||
				'T_SUM_NATCUR NUMBER(32,12), '||
				'T_SUM_PAYER NUMBER(32,12), '||
				'T_SUM_RECEIVER NUMBER(32,12), '||
				'T_FIIDEQ_PAYER NUMBER(10,0), '||
				'T_FIIDEQ_RECEIVER NUMBER(10,0), '||
				'T_SKIPRESTEQCHANGE CHAR(1) DEFAULT CHR(0), '||
				'T_SUMEQ_PAYER NUMBER(32,12), '||
				'T_SUMEQ_RECEIVER NUMBER(32,12), '||
				'T_RESULT_CARRY NUMBER(5,0), '||
				'T_NUMBER_PACK NUMBER(5,0), '||
				'T_OPER NUMBER(5,0), '||
				'T_DEPARTMENT NUMBER(5,0), '||
				'T_BRANCH NUMBER(5,0) DEFAULT 0, '||
				'T_NUMB_DOCUMENT VARCHAR2(15), '||
				'T_GROUND VARCHAR2(600), '||
				'T_SHIFR_OPER VARCHAR2(6), '||
				'T_KIND_OPER VARCHAR2(2), '||
				'T_TYPEDOCUMENT VARCHAR2(16), '|| 
				'T_USERTYPEDOCUMENT VARCHAR2(16) DEFAULT CHR(1), '||
				'T_PRIORITY NUMBER(5,0), '||
				'T_MINPHASE NUMBER(5,0) DEFAULT 0, '||
				'T_MAXPHASE NUMBER(5,0) DEFAULT 0, '||
				'T_SYSTEMDATE DATE DEFAULT TO_DATE(''01.01.01'', ''DD.MM.YYYY''), '||
				'T_SYSTEMTIME DATE DEFAULT TO_DATE(''01.01.01 00:00:00'', ''DD.MM.YYYY HH24:MI:SS''), '||
				'T_CHECKSUM RAW(16) DEFAULT hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0)||' ||
						'hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0)||hextoraw(0), ' ||
				'T_EXRATEACCTRNID NUMBER(10,0), '||
				'T_PARENTACCTRNID NUMBER(10,0) DEFAULT 0, '||
				'T_CLAIMID NUMBER(10,0) DEFAULT 0, '||
				'T_METHODID NUMBER(5,0), '||
				'T_MINIMIZATIONTURN CHAR(1) DEFAULT CHR(0), '||
				'T_EXRATEACCPLUSDEBET VARCHAR2(25) DEFAULT CHR(1), '||
				'T_EXRATEACCPLUSCREDIT VARCHAR2(25) DEFAULT CHR(1), '||
				'T_EXRATEACCMINUSDEBET VARCHAR2(25) DEFAULT CHR(1), '||
				'T_EXRATEACCMINUSCREDIT VARCHAR2(25) DEFAULT CHR(1), '||
				'T_SKIPRECALCSUMNATCUR CHAR(1), '||
				'T_FLAGRECALCSUM NUMBER(5,0) DEFAULT 0, '||
				'T_RATE FLOAT(53), '||
				'T_SCALE NUMBER(10,0), '||
				'T_POINT NUMBER(5,0), '||
				'T_ISINVERSE CHAR(1), '||
				'T_USERFIELD1 VARCHAR2(120), '||
				'T_USERFIELD2 VARCHAR2(40) DEFAULT CHR(1), '||
				'T_USERFIELD3 VARCHAR2(80) DEFAULT CHR(1), '||
				'T_USERFIELD4 VARCHAR2(80) DEFAULT CHR(1), '||
				'T_NU_STATUS NUMBER(5,0) DEFAULT 0, '||
				'T_NU_KIND NUMBER(5,0) DEFAULT 0, '||
				'T_NU_STARTDATE DATE DEFAULT TO_DATE(''01.01.01'', ''DD.MM.YYYY''), '||
				'T_NU_ENDDATE DATE DEFAULT TO_DATE(''01.01.01'', ''DD.MM.YYYY''), '||
				'T_NU_ACKDATE DATE DEFAULT TO_DATE(''01.01.01'', ''DD.MM.YYYY''), '||
				'T_FU_ACCTRNID NUMBER(10,0) DEFAULT 0, '||
				'T_SIDETRANSACTION NUMBER(5,0), '||
				'T_EXRATEEXTRA NUMBER(32,12), '||
				'T_USERGROUPID NUMBER(10,0) DEFAULT 0, '||
				'T_OFRRECID NUMBER(10,0) DEFAULT 0, '||
				'T_OPERID NUMBER(10), '||
				'T_STEP NUMBER(5) '||
			')';

		EXECUTE IMMEDIATE 'COMMENT ON TABLE DACCTRN_ADD_DBT IS ''Сохраненные проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_ACCTRNID IS ''Уникальный идентификатор''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_STATE IS ''Состояние проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_CHAPTER IS ''Номер главы''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_DATE_CARRY IS ''Дата проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_DATE_RATE IS ''Дата курса для расчета эквивалента в национальной валюте''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_FIID_PAYER IS ''ID финансового инструмента счета плательщика''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_FIID_RECEIVER IS ''ID финансового инструмента счета получателя''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_ACCOUNTID_PAYER IS ''Идентификатор счета плательщика''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_ACCOUNTID_RECEIVER IS ''Идентификатор счета получателя''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_ACCOUNT_PAYER IS ''Номер счета плательщика''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_ACCOUNT_RECEIVER IS ''Номер счета получателя''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SUM_NATCUR IS ''Сумма эквивалента в национальной валюте''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SUM_PAYER IS ''Сумма дебета в финансовом инструменте счета плательщика''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SUM_RECEIVER IS ''Сумма кредита в финансовом инструменте счета получателя''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_FIIDEQ_PAYER IS ''Идентификатор финансового инструмента-эквивалента счета плательщика''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_FIIDEQ_RECEIVER IS ''Идентификатор финансового инструмента-эквивалента счета получателя''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SKIPRESTEQCHANGE IS ''Признак отключения изменения остатков в валюте-эквиваленте для счетов с НВПИ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SUMEQ_PAYER IS ''Сумма проводки в ВЭ счета НВПИ  (плательщика)''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SUMEQ_RECEIVER IS ''Сумма проводки в ВЭ счета НВПИ  (получателя)''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_RESULT_CARRY IS ''Результат проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_NUMBER_PACK IS ''Номер пачки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_OPER IS ''Операционист''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_DEPARTMENT IS ''Филиал''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_BRANCH IS ''Подразделение''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_NUMB_DOCUMENT IS ''Номер проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_GROUND IS ''Основание''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SHIFR_OPER IS ''Шифр операции''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_KIND_OPER IS ''Вид операции''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_TYPEDOCUMENT IS ''Тип документа''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_USERTYPEDOCUMENT IS ''Пользовательский тип документа''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_PRIORITY IS ''Приоритет проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_MINPHASE IS ''Минимальная фаза''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_MAXPHASE IS ''Максимальная фаза''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SYSTEMDATE IS ''Системная дата выполнения проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SYSTEMTIME IS ''Системное время выполнения проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_CHECKSUM IS ''Контрольная сумма''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_EXRATEACCTRNID IS ''Идентификатор проводки курсовой разницы''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_PARENTACCTRNID IS ''Идентификатор родительской проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_CLAIMID IS ''Идентификатор претензии''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_METHODID IS ''Метод выполнения мультивалютной проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_MINIMIZATIONTURN IS ''Признак минимизации оборотов''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_EXRATEACCPLUSDEBET IS ''Cчет курсовой разницы при урегулировании положительной курсовой разницы по ДТ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_EXRATEACCPLUSCREDIT IS ''Cчет курсовой разницы при урегулировании положительной курсовой разницы по КТ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_EXRATEACCMINUSDEBET IS ''Cчет курсовой разницы при урегулировании отрицательной курсовой разницы по ДТ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_EXRATEACCMINUSCREDIT IS ''Cчет курсовой разницы при урегулировании отрицательной курсовой разницы по КТ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SKIPRECALCSUMNATCUR IS ''Отключение пересчета суммы эквивалента в нац валюте''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_FLAGRECALCSUM IS ''Включение пересчета суммы плательщика и получателя''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_RATE IS ''Значение курса проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SCALE IS ''Масштаб курса проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_POINT IS ''Округление курса проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_ISINVERSE IS ''Признак обратной котировки курса проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_USERFIELD1 IS ''Пользовательское поле 1''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_USERFIELD2 IS ''Пользовательское поле 2''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_USERFIELD3 IS ''Пользовательское поле 3''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_USERFIELD4 IS ''Пользовательское поле 4''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_NU_STATUS IS ''Статус НУ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_NU_KIND IS ''Вид НУ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_NU_STARTDATE IS ''Стартовая дата НУ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_NU_ENDDATE IS ''Конечная дата НУ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_NU_ACKDATE IS ''Дата подтверждения НУ''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_FU_ACCTRNID IS ''НУ. Идентификатор проводки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_SIDETRANSACTION IS ''Сторона сделки''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_EXRATEEXTRA IS ''Наценка на курсовую разницу''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_USERGROUPID IS ''Идентификатор для группировки проводок''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_OFRRECID IS ''Идентификатор символа ОФР''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_OPERID IS ''Идентификатор операции''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN DACCTRN_ADD_DBT.T_STEP IS ''Шаг операции''';
		
		EXECUTE IMMEDIATE 'CREATE INDEX DACCTRN_ADD_DBT_IDX0 ON DACCTRN_ADD_DBT ' ||
			'(' ||
				' T_OPERID ASC ' ||
				', T_STEP ASC ' ||
			')'; 

	END IF;
END;
/
