--Обновление справочников
BEGIN
   INSERT INTO DOBJGROUP_DBT (T_OBJECTTYPE, T_GROUPID, T_TYPE, T_NAME, T_SYSTEM, T_ORDER, T_MACRONAME, T_KEEPOLDVALUES,
                              T_UPDATEFLAG, T_SUCCESSOPFLAG, T_ATTROBJECTTYPE, T_ATTRGROUPID, T_ISHIDDEN, T_FULLNAMEISBASIC,
                              T_SYSHIDDEN, T_NOTUSEFIELDUSE, T_ISMEANPARENTNODE, T_ISMANUALFIRST, T_COMMENT)
                      VALUES (101,55,'X','Сделка замещения','X',55,CHR(1),CHR(0),0,CHR(0),0,0,CHR(0),CHR(0),CHR(0),CHR(0),CHR(0),CHR(0),CHR(1));

                      
                      
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN

   INSERT INTO DOBJATTR_DBT (T_OBJECTTYPE, T_GROUPID, T_ATTRID, T_PARENTID, T_CODELIST, T_NUMINLIST, T_NAMEOBJECT, T_CHATTR, T_LONGATTR, T_INTATTR,
                             T_NAME, T_FULLNAME, T_OPENDATE, T_CLOSEDATE, T_CLASSIFICATOR, T_CORRACTYPE, T_BALANCE, T_ISOBJECT)
                      VALUES (101,55,1,0,'1','1','1',CHR(0),0,0,'Да','Да',TO_DATE('01.01.0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE('01.01.0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),0,CHR(1),CHR(1),CHR(0));


   INSERT INTO DOBJATTR_DBT (T_OBJECTTYPE, T_GROUPID, T_ATTRID, T_PARENTID, T_CODELIST, T_NUMINLIST, T_NAMEOBJECT, T_CHATTR, T_LONGATTR, T_INTATTR,
                             T_NAME, T_FULLNAME, T_OPENDATE, T_CLOSEDATE, T_CLASSIFICATOR, T_CORRACTYPE, T_BALANCE, T_ISOBJECT)
                      VALUES (101,55,2,0,'2','2','2',CHR(0),0,0,'Нет','Нет',TO_DATE('01.01.0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE('01.01.0001:00:00:00','DD.MM.YYYY HH24:MI:SS'),0,CHR(1),CHR(1),CHR(0));

                      
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
  INSERT INTO DNOTEKIND_DBT(T_OBJECTTYPE, T_NOTEKIND, T_NOTETYPE, T_NAME, T_KEEPOLDVALUES, T_NOTINUSE, T_ISPROTECTED,
                            T_MAXLEN, T_NOTUSEFIELDUSE, T_MACRONAME, T_DECPL, T_ISPROGONLY)
              VALUES(101,37,1,'Идентификатор связанной сделки замещения',CHR(0),CHR(0),CHR(0),0,CHR(0),CHR(1),0,CHR(0));
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/


BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/