--Добавление настройки
DECLARE
  v_ID       NUMBER := 0;
  v_ParentID NUMBER := 0;

BEGIN

  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = 0 AND LOWER(T_NAME) = LOWER('РСХБ');
  SELECT T_KEYID INTO v_ParentID FROM DREGPARM_DBT WHERE T_PARENTID = v_ParentID AND LOWER(T_NAME) = LOWER('ДИРЕКТОРИИ');

  INSERT INTO DREGPARM_DBT(T_KEYID,T_PARENTID,T_NAME,T_TYPE,T_GLOBAL,T_DESCRIPTION,T_SECURITY,T_ISBRANCH,T_TEMPLATE )
  VALUES(0,v_ParentID,'ДИР. ЗАГРУЗКИ СДЕЛОК ЗАМЕЩЕНИЯ',2,'X','Директория с *.xls (*.xlsx) файлами с информацией о сделках замещения',CHR(0),CHR(0),CHR(1)) returning T_KEYID INTO v_ID;

  INSERT INTO DREGVAL_DBT(T_KEYID,T_REGKIND,T_OBJECTID,T_BLOCKUSERVALUE,T_EXPDEP,T_LINTVALUE,T_LDOUBLEVALUE,T_FMTBLOBDATA_XXXX )
  VALUES(v_ID,0,0,CHR(0),0,0,0,'2E2E5C496D706F727400');


EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN NULL;

END;
/

BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/