/*Пересоздание временной таблицы*/
DROP TABLE DNPTX6COLLECT_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE DNPTX6COLLECT_TMP
(
  T_ISSNOB           NUMBER(5),
  T_SNOB_CLIENT      NUMBER(10),
  T_SNOB_TYPE        NUMBER(5),
  T_SNOB_DESCR       VARCHAR2(100),
  T_SNOB_INC_DATE    DATE,
  T_SNOB_PERIOD      NUMBER(5),
  T_SNOB_BASE        NUMBER(5),
  T_SNOB_NOB         NUMBER(32,12), 
  T_SNOB_RATE        NUMBER(5),
  T_SNOB_CALC_TAX    NUMBER(32,12), 
  T_SNOB_KBK         VARCHAR2(20),
  T_SNOB_HOLD_TAX    NUMBER(32,12),
  T_SNOB_TORATE      NUMBER(5),
  T_ISNDR            NUMBER(5),
  T_NDR_CLIENT       NUMBER(10),
  T_NDR_DATE         DATE, 
  T_NDR_TAXBASEKIND  NUMBER(5),
  T_NDR_SUM_PLUS_G   NUMBER(32,12),
  T_NDR_SUM_MINUS_G  NUMBER(32,12),
  T_NDR_KBK          VARCHAR2(20)
)
ON COMMIT PRESERVE ROWS
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX DNPTX6COLLECT_TMP_IDX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX DNPTX6COLLECT_TMP_IDX1 ON DNPTX6COLLECT_TMP
(T_SNOB_CLIENT, T_SNOB_INC_DATE, T_SNOB_RATE)
/