/*Создание временной таблицы*/
DROP TABLE DNPTX6DECODING_TMP CASCADE CONSTRAINTS
/

CREATE GLOBAL TEMPORARY TABLE DNPTX6DECODING_TMP
(
  T_ID               NUMBER(10),
  T_TYPEOPER         VARCHAR2(100),
  T_CLIENTID         NUMBER(10),
  T_TAXBASETYPE      NUMBER(5),
  T_TAXPERIOD        NUMBER(5),
  T_DATEPAID         DATE,
  T_TOTALPLUS        NUMBER(32,12),
  T_TOTALMINUSNORMAL NUMBER(32,12),                                  
  T_TOTALMINUSREAL   NUMBER(32,12),                                  
  T_TOTALMINUSOVER   NUMBER(32,12),
  T_TAXBASESUM       NUMBER(32,12),
  T_RATE             NUMBER(5),
  T_TAXCALCULATED    NUMBER(32,12),
  T_KBK              VARCHAR2(20),
  T_TAXPAID          NUMBER(32,12),
  T_TYPESNOB         NUMBER(5),
  T_RECTYPE          NUMBER(5)
)
ON COMMIT PRESERVE ROWS
/

CREATE UNIQUE INDEX DNPTX6DECODING_TMP_IDX0 ON DNPTX6DECODING_TMP (
   T_ID ASC
)
/

CREATE INDEX DNPTX6DECODING_TMP_IDX1 ON DNPTX6DECODING_TMP
(T_CLIENTID, T_DATEPAID, T_RATE)
/

CREATE OR REPLACE TRIGGER DNPTX6DECODING_TMP_T0_AINC
  BEFORE INSERT OR UPDATE OF T_ID ON DNPTX6DECODING_TMP FOR EACH ROW
DECLARE
  v_id INTEGER;
BEGIN
  IF (:NEW.T_ID = 0 OR :NEW.T_ID IS NULL) THEN
    SELECT DNPTX6DECODING_TMP_SEQ.NEXTVAL INTO :NEW.T_ID FROM DUAL;
  ELSE
    SELECT LAST_NUMBER INTO v_id FROM USER_SEQUENCES WHERE UPPER(SEQUENCE_NAME) = UPPER('DNPTX6DECODING_TMP_SEQ');
    IF :NEW.T_ID >= v_id THEN
      RAISE DUP_VAL_ON_INDEX;
    END IF;
  END IF;
END;
/