CREATE SEQUENCE USR_EXCHNG_LOG_DBT_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
CREATE TABLE USR_EXCHNG_LOG_DBT
(
    T_ID             NUMBER(10) NOT NULL,
    T_REQID          VARCHAR2(128 CHAR) DEFAULT CHR(1),
    T_REQID_LINKED   VARCHAR2(256 CHAR) DEFAULT CHR(1),
    T_TRANSPARENT_ID VARCHAR2(256 CHAR) DEFAULT CHR(1),
    T_MODULE         VARCHAR2(128 CHAR) DEFAULT CHR(1),
    T_BY_MACRO       VARCHAR2(128 CHAR) DEFAULT CHR(1),
    T_REQ_DTTM       TIMESTAMP(6),
    T_RESP_DTTM      TIMESTAMP(6),
    T_ERROR_CODE     VARCHAR2(25 CHAR) DEFAULT CHR(1),
    T_ERROR_MSG      VARCHAR2(2000 CHAR) DEFAULT CHR(1),
    T_REQ_MESSAGE    CLOB,
    T_RESP_MESSAGE   CLOB
);

COMMENT ON TABLE USR_EXCHNG_LOG_DBT                   IS 'Журнал пользовательских интеграционных сообщений';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_ID             IS 'Уникальный идентификатор записи';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_REQID          IS 'Идентификатор запроса';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_REQID_LINKED   IS 'Идентификатор запроса в связанном журнале';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_TRANSPARENT_ID IS 'Сквозной идентификатор сообщений';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_MODULE         IS 'Название модуля, от имени которого осуществляется взаимодействие';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_BY_MACRO       IS 'Название макроса, который выполняет сохранение сообщений';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_REQ_DTTM       IS 'Системные дата и время запроса';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_RESP_DTTM      IS 'Системные дата и время ответа';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_ERROR_CODE     IS 'Код ошибки';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_ERROR_MSG      IS 'Текст ошибки';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_REQ_MESSAGE    IS 'Запрос';
COMMENT ON COLUMN USR_EXCHNG_LOG_DBT.T_RESP_MESSAGE   IS 'Ответ';

CREATE UNIQUE INDEX USR_EXCHNG_LOG_DBT_IDX0 ON USR_EXCHNG_LOG_DBT
(T_ID)
LOGGING
NOPARALLEL;

CREATE INDEX USR_EXCHNG_LOG_DBT_IDX1 ON USR_EXCHNG_LOG_DBT
(T_REQID)
LOGGING
NOPARALLEL;

CREATE INDEX USR_EXCHNG_LOG_DBT_IDX2 ON USR_EXCHNG_LOG_DBT
(T_REQID_LINKED)
LOGGING
NOPARALLEL;

CREATE OR REPLACE TRIGGER USR_EXCHNG_LOG_DBT_T0_AINC
 BEFORE INSERT OR UPDATE OF t_id ON usr_exchng_log_dbt FOR EACH ROW
DECLARE
    v_id INTEGER;
BEGIN
    IF (:new.t_id = 0 OR :new.t_id IS NULL)
    THEN
        SELECT usr_exchng_log_dbt_seq.nextval INTO :new.t_id FROM dual;
    ELSE
        SELECT last_number INTO v_id FROM user_sequences WHERE sequence_name = UPPER ('usr_exchng_log_dbt_SEQ');
            IF :new.t_id >= v_id
            THEN
                RAISE DUP_VAL_ON_INDEX;
            END IF;
    END IF;
END;