--Обновление справочников
BEGIN
  UPDATE DMCCATEG_DBT SET T_OPTIONAL = chr(88) WHERE T_CODE IN ('Начисл.ПДД, ц/б', 'Премия, ц/б') AND T_LEVELTYPE = 1;
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/


BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/