--Обновление справочников
BEGIN
  INSERT INTO DNOTEKIND_DBT(T_OBJECTTYPE, T_NOTEKIND, T_NOTETYPE, T_NAME, T_KEEPOLDVALUES, T_NOTINUSE, T_ISPROTECTED,
                            T_MAXLEN, T_NOTUSEFIELDUSE, T_MACRONAME, T_DECPL, T_ISPROGONLY)
              VALUES(12,108,9,'Дата принятия решения по невозмещаемым активам',CHR(88),CHR(0),CHR(0),0,CHR(0),CHR(1),0,CHR(0));
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/


BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/