--Обновление справочников
BEGIN
  UPDATE DNOTEKIND_DBT SET T_NAME='Дата фиксации курса для невозмещаемых активов' WHERE T_OBJECTTYPE=12 AND T_NOTEKIND=108;
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/


BEGIN
 EXECUTE IMMEDIATE 'COMMIT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/