/*----------------------------------------------------------------*/
/* Макрос вызова сервиса с параметрами из исходного XML-сообщения */
/*                                                                */
/* Автор: Карпов В.                                               */
/*----------------------------------------------------------------*/

import GetServiceMsgXML;

private var outObj;

macro uServiceExecuteByMsg()
   var incomeXMLobj;
   var XMLstring;
   var serviceResult;
   var macroName;   /* Наименование сервиса (макроса) */
   var serviceName; /* Наименование сервиса (функции) */
   var startSym, endSym;

   XMLstring = uStrMsgPrepare();

   incomeXMLobj = uConvertXMLtoRSL(XMLstring);

   /* Получение названий вызываемых макроса и функции - begin */
   startSym = StrLen("RunMacro.") + 1;
   endSym = index(incomeXMLobj.methodName, ".", startSym) - 1;
   macroName = trim(SubStr(incomeXMLobj.methodName, startSym, (endSym - startSym + 1)));
   startSym = endSym + 2;
   serviceName = trim(SubStr(incomeXMLobj.methodName, startSym));
   msgbox(string("Макрос: ", macroName, "; Сервис: ", serviceName));
   /* Получение названий вызываемых макроса и функции - end */
   InstLoadModule(macroName);

   serviceResult = ExecMacroFile(macroName, serviceName, incomeXMLobj.methodparms[0],
                                                         incomeXMLobj.methodparms[1],
                                                         incomeXMLobj.methodparms[2],
                                                         incomeXMLobj.methodparms[3],
                                                         incomeXMLobj.methodparms[4],
                                                         incomeXMLobj.methodparms[5],
                                                         incomeXMLobj.methodparms[6],
                                                         incomeXMLobj.methodparms[7],
                                                         incomeXMLobj.methodparms[8],
                                                         incomeXMLobj.methodparms[9]);

   return serviceResult;
end;

outObj = uServiceExecuteByMsg();

msgbox("Done!");
Exit(1);